계산기 [STEP2] 릴리
yagom-academy/ios-calculator-app pull request #102
Opened 2021-11-15 18:28 UTC by yeahg-dev

안녕하세요 코리! @corykim0829 

스텝2 PR 요청드립니다.
바쁘신 와중에도 항상 빠르게 답변 남겨주셔서 감사합니다!🙏🏻
부족한 부분이 많아 오래걸리기도, 시행착오도 많았던 스텝이었던 것 같습니다🥲
아쉬운 부분이나 추가로 공부해 볼 키워드있다면 아낌없이 남겨주세요~😀

# [STEP2] Class Diagram
요구사항에서 제시한 클래스 다이어그램
<img width="1090" alt="스크린샷 2021-11-16 오전 2 50 55" src="https://user-images.githubusercontent.com/81469717/141830207-a2c5c577-22ae-4291-90df-8b83f11f7f54.png">
<br>

# 🤔 고민한 점
## 1. ArrayList의 시간복잡도에 대한 오해
지난 스텝에서 분석해본 ArrayList의 마지막 요소에 추가 시 시간복잡도가 잘못 생각한 것일 수도 있겠구나~싶었습니다.

>When an array needs to reallocate storage before appending or its storage is shared with another copy, appending is O(n), where n is the length of the array.
[참고 공식문서](https://developer.apple.com/documentation/swift/array/3126937-append)

배열이 저장공간을 재할당받아야 할 경우엔 O(n)의 복잡도를 가진다고 합니다.

|자료 구조/시간복잡도|ArrayList|LinkedList|
|---|---|---|
|마지막 요소에 추가|**O(n)**|O(n) <br>(추가를 하기위해 마지막요소를 탐색하는 시간복잡도까지 고려) |
|첫번째 요소 삭제|O(n) |O(1) |

따라서 Queue타입은 linkedList로 구현하는 것이 적절하겠다고 생각을 정정하게 되었습니다만,
아쉽지만😭 linkedList구현부터 다시 시작하면 스텝진행에 차질이 생길것 같아 우선 Array를 안고 가게되었습니다.
<br>

## 2. `private` property, method를 Test하는 방법
`queue`에  `private`을 설정해주었더니 test모듈에서 `queue`에 접근이 불가해서 테스트를 할 수 없는 이슈가 발생했습니다.

제가 생각해보고, 캠퍼들에게 조언을 얻은 `queue`를 테스트 하는 방법은 아래와 같은데요~
혹시 코리라면 어떻게 하실지 조언을 얻고 싶습니다!

 - test모듈과 프로덕션 간에 인터페이스 생성. `queue`를 get하는 연산프로퍼티를 정의한다. (test만을 위한 코드를 프로덕션 코드에 적어준다는게 좀 찜찜하다)
 - `private (set)`을 활용하는 방법
 - 다른 있는 메서드들을 활용해서 test case를 작성해 간접적으로 테스트하는 방법

저는 첫번째 방법으로 `queue`를 연산프로퍼티로 접근하는 방법으로 테스트케이스를 수정했습니다
<br>

## 3.`CalculatorItemQueue`를 구조체로 수정
UML의 요구사항에 따라 `CalculatorItemQueue`를 구조체로 수정했습니다. 

class만이 가지는 능력(상속, 타입캐스팅, Objective-C와 호환)을 사용할 일이 없음에도,
프로퍼티가 메서드내에서 계속해서 수정되어야하는 경우, mutating키워드를 쓰는 것보다 class를 쓰는 것이 적절한 것인지? 코리의 의견이 궁금합니다!

그리고 추가적으로 메서드를 통해 계속해서 변경되는 `queue`프로퍼티를 Class타입으로 만들어 참조로 전달하는 것이 더 성능측면에서 좋을 수도 있겠단 생각도 들었습니다. (시간관계상 `queue`타입을 클래스로 만드는 건 하진 못했습니다)
만약 `queue` 가 커지게 된다면 전달될 때마다 값이 복사되는데, 메모리를 과도하게 쓰고 시간이 오래 걸릴 것 같다고 판단했기 때문입니다.
<br>

# 😶 해결하지 못한 점
### `!`사용
`!`를 사용하지 말라는 프로젝트 요구사항과 코드의 안정성 측면에서는 강제언래핑을 지양하는 것이 좋다고 생각합니다.
String타입의 숫자와 연산자들을 각각 Double과 Operator타입의 배열로 반환하기 위해 클로저에 초기화와 함께 !를 사용해주었습니다.
```swift
static func parse(from input: String) -> Formula {
        let calcultorItems = ["➕","➖", "➗", "✖️"]
        let stringOperators = input.filter { calcultorItems.contains(String($0))}
        let stringOperands = componentsByOperator(from: input)
        let operators = CalculatorItemQueue(stringOperators.map({Operator(rawValue: $0)!}))
        let operands = CalculatorItemQueue(stringOperands.map({Double($0)!}))
        return Formula(operands: operands, operators: operators)
    }
```
좀 더 안전하게 타입을 변환하는 방법에 대해 조언을 구하고 싶습니다.

2021-11-16 07:22 UTC, corykim0829 requested changes
수고하셨습니다 릴리 👏👏👏

많이 고민하고 코드를 작성하신게 느껴집니다.

제가 커멘트 해드린 것 처럼 너무 시간이 많이 걸리는 작업들은 step3 이후에 진행하면 될 것 같아요.
일단은 빠르게 step2 조건만 만족 시키고 step3로 넘어가봐요!

고민한 부분들에 대한 답변들은 커멘트로 달아두었습니다! 확인하시고 더 이야기 나누어봐요!

화이팅입니다 💪

2021-11-16 07:34 UTC, corykim0829 requested changes

2021-11-16 07:34 UTC, corykim0829 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		631B7D3F27427A6E007227A2 /* String_Extension.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = String_Extension.swift; sourceTree = "<group>"; };
String_Extension이라고 하면 너무 포괄적인 느낌이 있네요. 더 구체적인 파일명으로 바꿔주면 좋을 것 같아요

2021-11-16 07:34 UTC, corykim0829 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		63A5001B273C1CBB00362DD6 /* Double_Extension.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = Double_Extension.swift; sourceTree = "<group>"; };
여기도 마찬가지로 파일명을 조금 더 구체적으로 개선해보면 좋을 것 같아요!

2021-11-17 05:21 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculatorError.swift
> +    case incomputableDivdie
네! 구체적인 상황으로 케이스명을 정해주는 것이 케이스만 보고도 명확하게 판단할 수 있을 것 같아요~

2021-11-17 05:23 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculatorError.swift
> +    case unknown
사실 `Double.nan`의 존재를 알기전에 `divide`메서드에서 0으로 나눌 때 던져줄 에러를 정의한 것인데요~
그리고 에러를 삭제하는 것을 깜박했습니다😅 삭제해도 될것 같아요!

2021-11-17 05:29 UTC, yeahg-dev commented on Calculator/Calculator/String_Extension.swift
> +        let splitedSustirng = self.split(separator: target)
네!

2021-11-17 05:48 UTC, yeahg-dev commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operands = CalculatorItemQueue(stringOperands.map({Double($0)!}))
네 수정해보도록 할게요!😃

2021-11-17 05:50 UTC, yeahg-dev commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let stringOperators = input.filter { calcultorItems.contains(String($0))}
스텝3구현 하면서 메서드 또는 프로퍼티로 구현해보도록 하겠습니다~

2021-11-17 06:19 UTC, yeahg-dev commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return components
flatMap과 compactMap의 차이점을 좀 더 공부해본 뒤에 수정해보도록하겠습니다! 
인자명은 아래와 같이 수정해보았습니다
```swift
static private func componentsByOperator(from input: String) -> [String] {
        let expression = [input]
        let operandsArray = Operator.allCases.reduce(expression){(expressionSplitedByOperator: [String], `operator`: Operator) -> [String] in
            return expressionSplitedByOperator.flatMap{$0.split(with: `operator`.rawValue)}
        }
        return operandsArray
    }
```

2021-11-17 06:29 UTC, yeahg-dev commented on Calculator/Calculator/Model/Formula.swift
> +        let CalculationTrial = operators.itemCount
동의합니다! 수정해볼게요!🙂

2021-11-17 07:37 UTC, yeahg-dev commented on Calculator/Calculator/Model/Formula.swift
> +        var result = operands.dequeue() as! Double
`guard var`문으로 옵셔널 바인딩을 해주었습니다!
 UI단에서 숫자만 입력받기때문에 그럴일은 없겠지만, 만약 옵셔널 바인딩에 실패한다면 `Double.nan`을 반환해서 NaN을 화면에 표시해주려고 합니다.

```swift
 mutating func result() -> Double {
        guard var result = operands.dequeue() as? Double else {
            return Double.nan
        }
```

2021-11-17 07:50 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var testableQueue: [CalculateItem] {
조언감사합니다!👍

2021-11-17 07:52 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue {
혹시 struct가 더 좋은 퍼포먼스가 나올 거라고 판단하신 이유는 무엇인지 간략하게 설명해주실 수 있을까요??

2021-11-17 07:57 UTC, yeahg-dev commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		631B7D3F27427A6E007227A2 /* String_Extension.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = String_Extension.swift; sourceTree = "<group>"; };
좀 더 구체적인 파일명이라 하면 Extension내에서 구현한 기능이 드러날 수 있도록 파일 네이밍하라는 것으로 이해했습니다!
그렇다면 extension에 기능을 추가할 때 마다 파일을 생성해주어야해서, 한 타입에 대한 익스텐션을 한 곳에서 관리하기 힘들지 않을까? 하는 생각이 들었습니다.

지금 제가 코리의 피드백을 잘 이해하고 있는게 맞나요~?

2021-11-18 02:31 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue {
해당 구조체 안에 레퍼런스 타입이 두개 이상이게 되면, struct를 복사하게 되면, 클래스보다 더 많은 비용이 발생하게 됩니다!

2021-11-18 02:33 UTC, corykim0829 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		631B7D3F27427A6E007227A2 /* String_Extension.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = String_Extension.swift; sourceTree = "<group>"; };
저는 개인적으로 한 타입에 대한 익스텐션이여도 어떤 기능을 하냐에 따라서 분리를 해주는 것도 좋다고 생각합니다. 물론 비슷한 기능이면 하나의 파일에 관리하는 게 좋겠죠!
String_Extension으로 해서 String의 모든 익스텐션이 나중에 들어간다면, 특정 익스텐션을 찾거나 유지보수하는데 조금 더 비용이 들 수도 있을 것 같아서요!

2021-11-18 02:33 UTC, merged

2021-11-18 06:23 UTC, yeahg-dev commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		631B7D3F27427A6E007227A2 /* String_Extension.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = String_Extension.swift; sourceTree = "<group>"; };
그런 비용이 들 수도 있겠군요~! 상세하게 설명해주셔서 감사합니다!😊👍 
기능반영해서 파일명 리네임해볼게요!

2021-11-18 06:28 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue {
설명 감사합니다!!😊 이 부분에 대해선 더 찾아보도록할게요~!