계산기 [Step2] Allie
yagom-academy/ios-calculator-app pull request #106
Opened 2021-11-16 07:09 UTC by wooyani77

@GREENOVER
안녕하세요, 그린! 🍏
계산기 step2 PR 드립니다!

step1 리뷰도 정말 감사했습니다!ㅎㅎ
이번 스텝도 리뷰 잘 부탁드려요!

### :star2: 주요 구현 내용
![](https://i.imgur.com/0w21O4r.png)
- ExpressionParser
    - `parse()` 문자열을 연산자와 피연산자로 분리하여 Formula를 반환하는 메서드
    - `componentsByOperators()` 문자열을 연산자를 기준으로 분리하여 피연산자 배열로 반환하는 메서드
- String Extension
    - `slpit()` 문자열을 연산자를 기준으로 나누고 각 문자를 String타입으로 형변환하여 [String]으로 반환하는 메서드
- Operator
    - 연산자를 정의한 열거형
    - `calculate()` 연산을 실행하는 메서드
- Formula
    - 연산자는 CalculatorItemQueue<Operator>의 `enQueueElements`에, 피연산자는 CalculatorItemQueue<Double>의 `enQueueElements`에 저장
    - `result()` 사칙연산 결과를 반환하는 메서드

-> 이정도로 분석해보았는데, 혹시 제가 잘못이해하고 있는 부분이 있다면 말씀해주세요! :)

### 🧐 고민되었던 점 및 해결방법
- `Operator` 열거형 내에서 마이너스 연산자를 `-`로 지정해주었는데요, 다른 캠퍼들과 이야기를 나누는 중에 음수가 들어왔을때와 구분을 지어주는게 좋을 것 같다는 의견이 있었습니다. 음수가 들어오는 경우는 생각을 못했었는데, 해당 의견 반영하여 마이너스 연산자를 `_`로 변경해주었습니다!

- `Operator` 열거형의 `divide()` 메서드에서 0으로 나누려고 할 때 오류를 던지고 `calculate()` 메서드에서 아래와같이 오류를 잡도록 해주었습니다. 그런데 switch-case문이 보기에 깔끔하지 않다고 느껴졌어요. 또, test case를 작성할 때도 번거롭다는 단점이 있었어요.
    ```Swift
    case .divide:
            var result: Double = 0
            do {
                result = try divide(lhs: lhs, rhs: rhs)
            } catch CalculatorError.divideByZero {
                print(CalculatorError.divideByZero.description)
            } catch {
                print(error)
            }
            return result
    ```
    그래서, `divide()` 메서드가 아닌 `calculate()`에서 오류를 던지고, 사용처에서 try 할 수 있게 바꿔주었습니다!
    ```Swift
    case .divide:
            if rhs == 0 {
                throw CalculatorError.divideByZero
            }
    ```
    
- TDD 방식으로 진행하는게 정말 어려운 것 같습니다 :cry: 자꾸 코드를 먼저짜고 테스트를 하게되더라구요..ㅎㅎ..

- componentsByOperators() 메서드를 구현하는 과정에서 정말 많은 시행착오가 있었습니다.. 😂 일단은 input을 바로 [input]으로 넣어줄 수 있는지 몰라서 append 메서드를 사용해보기도 하고, for문에서 input을 split하고 그 결과를 result에 넣어주고, 다시 돌고~ 이렇게 했어야 했는데 그냥 split하고 넣기만하면서 왜안되지? 생각만 하루정도 한 것 같아요..ㅎㅎ 다른 캠퍼의 도움을 받아 알아차릴 수 있었습니다!
    ```Swift
    func componentsByOperators(from input: String) -> [String] {
    
    // 수정 전
        var result: [String] = []
        result.append(input)
        var someArray: [String] = []
        Operator.allCases.forEach { `operator` in
            for input in result {
                someArray += input.split(with: `operator`.rawValue)
            }
        }
        return someArray
    
    
    // 수정 후
        var result: [String] = [input]
        Operator.allCases.forEach { `operator` in
            var splitedString: [String] = []
            for input in result {
                splitedString += input.split(with: `operator`.rawValue)
                result = splitedString
            }
        }
        return result
    }
    ```

- 지난 스텝에서 test case를 영어로 작성해보는 것도 좋을 것 같다고 하셔서 이번 스텝에서 적용해보았습니다! 영어로도 한글으로도 작성해보았어요!

### :question: 조언을 얻고싶은 부분
- 폴더 분리
    UML에 제시되어있는 각 타입별로 파일을 생성해 폴더를 나눠보았습니다! 하지만 어떻게 정리해야할지 잘 모르겠어요.. 예를들면, `String Extension`같은 경우에는 해당 메서드가 `ExpressionParser` 내부에서 사용되기 때문에 같은 파일에 작성할지 고민이 되었습니다. 
    그리고 `extension` 파일명을 `StringExtension`으로 해주었는데, 다른 캠퍼분들은 `String+extension`과 같은 식으로 하셨더라구요~ 개인의 취향차이라고 느꼈는데, 지금처럼 해주어도 되는지와 파일을 어떤 기준으로 분리해주는게 좋을지 그린의 의견이 궁금합니다 :smiley:

2021-11-16 11:26 UTC, GREENOVER requested changes
@wooyani77 
안녕하세요 엘리~!
이번 스텝2도 너무너무 고생많으셨습니다🙌
꽤나 생각할것도 많고 까다롭다면 까다로웠을텐데 멋지게 잘 해내셨네요 크..👍
이번주가 계산기(전) 프로젝트의 마지막 주이자 얼마 남지 않았네요..!
이번주도 잘 부탁드립니다.
스텝 3도 진행해보셔야 되니 필수적인것부터 빠르게 짚어볼께요!

### 칭찬 드리고 싶은 부분
- 파일 그룹화를 보기 좋게 잘 나눠주셨더라구요! 💯
- 리드미 정리와 커밋을 세부적으로 잘 작성해주신점 💯
- 여러 테스트 케이스에 대해 고민해보시고 녹여내신점 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. 마이너스 연산자에 대해
- 오호 그런 방법도 있었네요..! 저도 배워갑니다!
좋은 방법일것 같고 스텝3와 연동할때가 기대되네요👍
2. calculate 오류 처리에 대해
- 이 부분에 대해 고민하셔서 해결하신걸 코드에서 잘 보았습니다..!
통상적으로 저렇게 오류 처리를 많이 합니다. 잘 구현해주셔서 이 부분에서 더 드릴 말씀은 없네요🤭
3. TDD에 대해
- TDD... 정말 어렵죠.. 레드 그린 리팩토링 순으로 진행되는데 사실 항상 레드를 먼저 할 순 없죠..ㅠ
그래서 전체적으로 TDD를 선적용해서 하기보단 정말 짜잘하고 할 수 있는 최소 단위에 대해 부담 안되는선에서 레드 > 그린 > 리팩토링을 해보시는걸 추천드려요.
전체적으로 테스트 코드에 대해 먼저 생각하는게 정말 이상적이지만 그걸 처음부터 따라한다면 애플가야죠🚀
테스트 코드를 신경쓰고 중간에라도 짜보고 한다는거 자체가 지금은 정말 큰 의미입니다.
지금 충분히 잘하고 계시는게 코드로 보이기에 이대로 쭉 TDD를 조금씩 매 플젝에 신경만 쓴다면 애플 갈거에요~!
4. componentsByOperators() 메서드 구현에 대해
- 로직적으로 잘 짜주셨습니다.
정말 단순한건데 혼자 생각하면 놓칠때가 많더라구요!
저는 3시간? 정도 고민해보고 내가 당장 할 수 없는거다 라는걸 최대한 빨리 캐치해서 동료나 사수에게 물어보곤 합니다.
현업에서는 마냥 시간을 계속 붙잡고 있을 수 없기에 시간을 쓰는 방법을 터득하는것도 과정인것 같아요.
그래서 내가 정해진 시간에 고민해서 해낼 수 있는것과 도움이 필요한것을 구분하는것도 캠프에서 길러보면 좋겠어요👍
고민하다 안풀릴때 지금처럼 캠퍼들과 소통하는것 아주아주 나이스입니다🥳
하나 해당 메서드에서 욕심을 내보자면 고차함수로 더 구성해봤으면 어땠을까입니다~!
이건 스텝3에서 해보고 싶으시고 다른 구현들이 마무리되면 더 도전해봐도 좋을것 같아요🙌
5. Test case 한글 VS 영어
- 영어로된 테스트 케이스 메서드명을 확인했어요..!
한글 영어 둘다 장단점이 있고 그 장단점들을 잘 학습하고 계신것 같습니다.
둘의 장단점에 대해선 스텝1 PR에서 같이 나눠봤기에 여기선 넘어갈께요~😁
***
### 조언 요청에 대한 저의 의견
- 폴더 분리에 대해서 지금 정말 잘해주셨다고 봅니다.
우선 알고계신것처럼 스타일이고 어느 조직이냐에 따라 차이가 나지만 통상적인건 존재합니다.
저는 그 통상적으로를 따르려고 합니다.
우선 제가 하는 방식은 엘리처럼 기본타입을 extension하는것들은 별도 Extension 폴더를 만들어 거기에 구분시켜 넣어줍니다.
파일명은 `String+extensions`처럼 해줍니다. 저도 이렇게 파일명을 가져가는걸 통상적으로 사용한다는걸 어디서 보고 그렇게 하고 있는데
지금 레퍼런스를 찾으려니 잘 안나오네요😂
혹시 엘리가 찾게되면 공유해주시면 감사하겠습니다!
그리고 커스텀한 타입이나 VC , 모델등에 extension하는것들은 해당 파일안에서 코드를 분리해주는 방향으로 사용합니다.
코드가 많아져서 파일로 구분해야될때는 extension을 받는 주체를 담은 폴더에 같이 넣어주고 있습니다..!
저는 이게 통상적으로 사용한다고 알고 있고 그렇게 사용하고 있습니다.
제가 잘못 알고 있는거일수도 충분히 있기에 한번 라이브러리들 (애플이면 더 좋구요..!)을 파해치면서 어떤 네이밍과 그룹화를 해보는지 파악해보시면 도움이 더 될것 같습니다🙌
***
### 보완되면 좋을 부분
- 마이너한거긴한데 스텝1에서는 깃헙 이슈와 플젝 관리를 하셨던것 같은데 그 후로 작업된거 없어서 안타까웠어요..😂
꾸준히 진행해보시면 더 좋을것 같네요!🤭
- 디코 디엠으로도 말씀드렸듯 컨플릭 처리 과정에서 필수 파일이 누락되어 빌드가 되지 않는 부분이 있기에 해결 부탁드립니다..!
- 나머지는 코드 리뷰로 간단히 달아봤습니다🙋🏻
***
스텝 2 고생하셨습니다..!
빌드가 되지 않기에 우선은! Request Changes를 드리겠습니다😅
리뷰 코멘트를 같이 확인하여 수정할 부분이 있다면 수정을 거쳐 다시 재리뷰를 받고 다음 스텝으로 넘어가고 싶으시다면
우측 상단 리프레쉬 버튼을 눌러 리뷰 요청 해주시면 됩니다!
![스크린샷 2021-11-16 오후 8 25 19](https://user-images.githubusercontent.com/72292617/141977012-5d6632a0-69d0-464f-9a33-b08777a847f5.png)

2021-11-17 14:53 UTC, wooyani77 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    init(_ enQueueElements: [Element] = []) {
`ExpressionParser`의 `parse()` 메서드가 Formula를 반환하는데, CalculatorItemQueue를 생성하면서 enQueueElements에만 값을 넣어주기 위해 이니셜라이저를 만들어주었습니다. 그런데 다시보니 이미 구조체 내부의 프로퍼티에서 기본값을 주어서 이니셜라이저에는 초기값을 주지 않아도 되는 것 같습니다ㅎㅎ 이니셜라이저 위치와 같이 수정하겠습니다!

2021-11-17 14:59 UTC, wooyani77 commented on Calculator/Calculator/Model/Operator.swift
> +    func add(lhs: Double, rhs: Double) -> Double {
앗 UML에 맞게 접근제어 설정해주어야했는데 놓쳤습니다! 붙여주도록 할게요 🤭

2021-11-17 14:59 UTC, wooyani77 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    static func componentsByOperators(from input: String) -> [String] {
이부분도 수정했습니다!

2021-11-17 15:27 UTC, wooyani77 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        Operator.allCases.forEach { `operator` in
`targetOperator`로 수정해보았습니다..!

2021-11-17 15:42 UTC, wooyani77 commented on Calculator/Calculator/Model/Formula.swift
> +        while operators.isEmpty == false {
`!operators.isEmpty` 이런 방법도 있다는 걸 처음 알았습니다! ㅎㅎ 공식문서를 찾아보니 `!`를 붙여서 Bool 값을 반전시킬 수 있군요! 해당 방식으로 적용해보겠습니다!

2021-11-17 15:52 UTC, wooyani77 commented on Calculator/Calculator/Error/CalculatorError.swift
> +    case divideByZero
`CalculatorQueueError`와 `CalculateError`로 에러타입을 분리해주었습니다! 감사합니당ㅎㅎ

2021-11-17 16:09 UTC, wooyani77 commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
Formula가 구조체 타입이라 멤버와이즈 이니셜라이저가 자동으로 생성되어서 굳이 만들어줄 필요가 없다고 생각했습니다!
이니셜라이저를 만들어준다면 좀 더 명확하다는 장점도 있을 것 같습니다ㅎㅎ

2021-11-17 16:10 UTC, wooyani77 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +                       operators: CalculatorItemQueue(operators))
오,, 가독성이 조금 더 개선된 것 같아요! 말씀해주신 키워드로 공부해보겠습니다! ㅎㅎ

2021-11-17 16:11 UTC, wooyani77 commented on Calculator/CalculatorItemQueueTests/ExpressionParserTests.swift
> +
수정했습니다!

2021-11-17 16:16 UTC, wooyani77 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
위에서 피드백 주셨던 Formula 타입의 `result()` 메서드 내부의 while문의 조건에 쓰입니다!
```Swift
while !operators.isEmpty {
```

2021-11-17 16:24 UTC, wooyani77 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    var sut: CalculatorItemQueue<Double>!
이부분도 test case만 신경쓰느라 놓친부분이네요! 이부분도 개선해나가도록 하겠습니다ㅎㅎ

2021-11-17 16:30 UTC, wooyani77 commented
그린 🍏!
이번 step2 리뷰도 정말 감사합니다ㅎㅎ
피드백 반영하여 수정해보았습니다. 확인 부탁드려요!
누락된 파일도 다시 생성해주었습니다ㅜㅜ

2021-11-18 01:16 UTC, GREENOVER approved these changes
@wooyani77 
개선된것 확인했습니다 앨리..!!
고생하셨어요🙌
스텝 2 여기서 머지하겠습니다🥳🥳🥳

2021-11-18 01:16 UTC, merged