계산기[Step2] Toni
yagom-academy/ios-calculator-app pull request #107
Opened 2021-11-16 11:43 UTC by oksunwoo

안녕하세요 도미닉(@AppleCEO) ! 
제가 PR 기한을 또 놓쳐버렸네요.. 나름대로 계획을 짜서 이때쯤이면 되겠다 싶어서 고심 끝에 날짜를 정한 건데, 왜 자꾸만 시간이 부족한지 모르겠네요🥲 리뷰어와의 약속을 지켜야하나, 아니면 조금 늦더라도 성의있는 코드를 보내느냐 굉장히 고민을 많이 한 끝에, 조금 늦더라도 리뷰를 받을만한 껀덕지(?)가 있어야된다는 생각에 조금 늦더라도 완성시켜 보냅니다. 아마 제가 현직자 였으면, 우선 기한을 맞추는 것으로 목표를 했을 것 같은데, 저는 공부를 하는 입장이다보니 완성을 목표로 생각을 했습니다. 😓

이번에는 UML 차트가 먼저 주어지고, 주어진 UML대로 해석을 한뒤에 스텝을 진행하는 과정이 있었습니다. 제가 진짜 많이 부족해서, UML을 해석하는데 시간이 정말 많이 걸렸습니다. 이것만 거의 꼬박 2-3일 정도 쓴것 같아요. 

첫번째로는 
<img width="1185" alt="스크린샷 2021-11-16 오후 8 16 19" src="https://user-images.githubusercontent.com/55880539/141975895-70372211-dbea-484c-97f0-4987414a8917.png">

calculate를 어떻게 해석해야하지, split은 왜 저렇게 되있을까에 대한 고민을 참 많이했습니다. 우선 혼자 고민하는 시간이 충분히 필요할 것 같아서, 열심히 해석을 하려고 노력했습니다. add나 subtract 같은 것들은 private인데 calculate는 internal 인 것을 보고 calculate에서 결국은 연산을 처리하는 곳이구나 라는 생각을 하게 되었습니다. 

<img width="881" alt="스크린샷 2021-11-16 오후 8 16 28" src="https://user-images.githubusercontent.com/55880539/141976768-372bd097-41e3-4249-ae2a-2308a332b179.png">

이 부분은 특히 어려웠는데, parse는 무얼하는 메소드이며, ExpressionParser는 왜 Enum으로 되어있는지, componentsByOperators는 왜 있지 라는 생각을 참 많이했던 것 같습니다. 결국, 캠퍼들과 상의하고 주변에 도움을 요청한 끝에 어느정도 이해하기는 했지만, 완벽하게 숙지를 하고 진행을 하지 못해 살짝 찝찝한 기분도 있었습니다. TDD 방식으로 구현하려면, 완벽한 이해가 동반되어야 한다고 생각을 했거든요. 

제가 생각한 방식은 이렇습니다.
1. parse - 표현식이 스트링 타입으로 들어오는데, 리턴타입이 Formula 타입인 것으로 보아, 계산을 위한 입력이 들어오면 연산자큐와 피연산자큐에 각각 값을 따로 담는다고 생각했습니다.
2. componentsByOperators - 역시 input타입이 String이고, `Operator에 의한 구성요소` 라고 되어있어, 덧셈기호와 같은 것들이 이곳에서 처리가 되는구나 라고 생각을 하였습니다. 그리고 String의 Split이 이곳에서 사용될 수 있겠구나라고 생각을 하게 되었습니다.
3. Formula - operands와 operators를 갖고 있고, result 메소드가 있어서, ExpressionParser를 통해 나눈 데이터들을 각 큐에 담고, = 버튼을 누르는 순간 result를 통해 결과가 산출되는 구나 라고 생각하였습니다.

### 고민했던 점

1. -연산과 -기호
    
    처음에는 -연산을 기존의 - 부호를 사용하고, 음수를 나타내는 마이너스의 경우에는 _ 로 표기를 했었습니다. 하지만, enqueue시에 _기호를 다시 -로 바꿔줘야하는 번거로움이 생겼고, 결국 -기호를 가져와 연산에 사용했습니다.
    
2. String Extension Test
    
    최대한 TDD 방식을 사용하기 위해, 많은 고민을 했습니다만, extension역시 TDD로 구현해야한다는 것을 몰랐습니다. 추후에 코드를 완성하고 나서, 다른사람들의 코드를 보니 이 부분 역시 TDD로 구현을 한걸 발견했습니다... 무언가 기능이 더해진다면 TDD를 사용해야한다는 것을 그 때 깨달았습니다..
    
3. TDD 방식을 사용하다 코드의 길이가 길어지는 경우
    
    후반부의 코드 구현을 하다보니, 앞에 작성코드와 겹쳐서 test를 하기위해서는 코드의 작성단위가 조금 커져야한다는 것을 느꼈습니다. mock데이터를 만든다거나 하는 방식을 찾긴했지만, 차마 적용해볼 수 는 없었습니다....
    

### 질문사항

1. 같은 동작을 하는 구문의 반복
    
    ```swift
    static private func componentsByOperators(from input: String) -> [String] {
            var resultOfReplacing = input.replacingOccurrences(of: String(Operator.add.rawValue), with: " ")
            resultOfReplacing = resultOfReplacing.replacingOccurrences(of: String(Operator.subtract.rawValue), with: " ")
            resultOfReplacing = resultOfReplacing.replacingOccurrences(of: String(Operator.divide.rawValue), with: " ")
            resultOfReplacing = resultOfReplacing.replacingOccurrences(of: String(Operator.multiply.rawValue), with: " ")
            
            return resultOfReplacing.split(with: " ")
        }
    ```
    
    해당 코드에서 replacing이 4번 동작을 하는데, 같은 방식인 것을 알 수 있습니다. 제가 아직 문법이 미숙하여, 힌트 정도만 주시면 제가 찾아보고 이 메소드의 방식을 바꿔보겠습니다.
    

1. Parse 메소드 부분
    
    요구사항에선 parse메소드 안에 componentsByOperators 메소드가 있고, 숫자만 따로 추출하게 된다고 생각을 했습니다. 반대로, 문자 역시 같은 방식을 채택하는데, 이부분은 UML요구사항에서 메소드처리가 왜 안되어있는지 궁금했습니다. 혹시 제가 의도를 잘못파악한 게 아닌가 싶어 질문드립니다.
    

1. 부동소수점 오차 오류
    
    이 부분에 대해서는 캠프사이트에 많이 올라오기도 했지만, 적절한 적용법을 찾지못했습니다. 
    
2. ExpressionParser
    
    이 부분은 enum 타입으로 요구사항에 명시되어있는데, 왜 enum타입일까에 대한 적절한 이유를 찾지못했습니다.. 생각을 해보았지만, 비슷한 기능들에 대한 묶음? 정도로만 생각해보았습니다.

언제나 부족한 PR과 제 코드를 봐주셔서 항상 감사드립니다 ☺️

2021-11-17 06:40 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
토니 고생하셨습니다~

1. 같은 동작을 하는 구문의 반복
- for문을 돌릴 수도 있을 것 같습니다 ㅎㅎ

2. Parse 메소드 부분
- componentsByOperators 은 문자를 추출하는 것 아닌가요? 조금 더 자세한 내용 공유해주시면 좋을 것 같습니다!

3. 부동소수점 오차 오류
- 어떤 방법을 시도해보았고 왜 실패했나요? 그런 것들을 정리해보면 좋겠습니다~

4. ExpressionParser
- 구조체만을 사용하지 않고 enum으로도 이런 구성이 가능하다는 것을 알려주시려는 의미였지 않을까 싶습니다.

2021-11-17 06:40 UTC, AppleCEO commented on Calculator/Calculator/Error/OperatorError.swift
> +enum OperatorError: Error {
0 으로 나눈다는 것을 OperatorError 가 아니라 OperandsError 일 수도 있을 것 같은데 어떻게 생각하시나요? ㅎㅎ

2021-11-17 06:40 UTC, AppleCEO commented on Calculator/Calculator/Error/OperatorQueueError.swift
> +enum OperatorQueueError: Error {
큐에 대한 에러를 따로 저장하는 OperatorQueueError 열거형을 만드셨군요 💯 
OperatorError 와는 어떤 차이가 있고 왜 나눴는지 공유해주실 수 있을까요? ㅎㅎ

2021-11-17 06:40 UTC, AppleCEO commented on Calculator/Calculator/Extension/Extension+String.swift
> +    }
기본적으로 String 에서 제공하는 split 메소드를 사용하지 않고 별도 메소드를 생성한 이유가 있을까요?
그리고 구조체를 만들어서 이런 함수를 만드는 것과 extension 으로 String 에 이 메소드를 추가하는 것은 어떤 차이가 있을까요?

2021-11-17 13:18 UTC, oksunwoo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
```swift
componentsByOperators(from: input).forEach { component in
           guard let operation = Double(component) else {
                return
            }

            calculateFormula.operands.enqueue(operation: operation)
        }
```

축약형을 기본형으로 바꾸었습니다.
여기서도 for문을 쓸까, forEach를 쓸까도 고민했는데 forEach를 사용한 이유는 다음과 같이 두가지입니다.

1. forEach문은 주어진 문자열 또는 컬렉션타입을 끝까지 순회하게 됩니다. for문과는 달리 중간에 멈추거나 break나 continue를 사용할 필요가 없었다고 생각했기에 forEach를 사용해서 읽는 사람에게 하여금, 끝까지 돌게되는 반복문이라고 알려주고 싶었습니다.

2. Error 처리
for 문의 경우에는 guard 문을 써주었을때 return에서 Formula 타입으로 반환을 해주기가 매우 까다롭다고 느꼈습니다.

다음과 같은 이유로 forEach를 통해 구현해보았습니다.

2021-11-17 13:49 UTC, oksunwoo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators: [Character] = input.filter { "+/*₋".contains($0) }
```swift
 let operators: [Character] = input.filter { (`operator`: Character) -> Bool in
            return "+/*₋".contains(`operator`)
        }
```

길게 늘여서 바꿨습니다. 확실히 보기에도 좋고 저 또한 조금 더 쉽게 쉽게 읽을 수 있는 것 같습니다!

2021-11-17 14:00 UTC, oksunwoo commented on Calculator/CalculatorQueueTests/ExpressionParserTests.swift
> +    func test_정상적인_연산을_하는지() throws {
```swift
func test_12_곱하기_마이너스3_더하기_5_빼기_4_나누기_5_는_마이너스7_인지() throws {
        exampleData = "12 * -3 + 5 ₋ 4 / 5"
        
        var testFormula = ExpressionParser.parse(from: exampleData)
        
        XCTAssertEqual(-7, try testFormula.result())
    }
```
이렇게 변경완료하였습니다!

2021-11-17 14:13 UTC, oksunwoo commented on Calculator/Calculator/Error/OperatorError.swift
> +enum OperatorError: Error {
```swift
enum OperandsError: Error {
    case dividedByZero
}
```
맞네요! 변경완료 하였습니다. 
같은 맥락으로 큐에 값이 없는데 반환을 요청할때 발생하는 에러인 `OperatorQueueError`를 `CalculatorQueueError`라고 변경을 했습니다!

2021-11-17 14:42 UTC, oksunwoo commented on Calculator/Calculator/Error/OperatorQueueError.swift
> +enum OperatorQueueError: Error {
네 맞습니다!
이렇게 에러를 따로 나누어준 이유는 사용자가 사용을 하면서 발생할 수 있는 오류(0으로 나누기)와 구조적으로 발생할 수 있는 오류를 구분해주고 싶었기에 따로 나누었습니다!

2021-11-18 09:19 UTC, oksunwoo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        resultOfReplacing = resultOfReplacing.replacingOccurrences(of: String(Operator.multiply.rawValue), with: " ")
```swift
        for operation in Operator.allCases {
            resultOfReplacing = resultOfReplacing.replacingOccurrences(of: String(operation.rawValue), with: " ")
        }
```
처음에 for문을 사용하여 바꾸어본 코드입니다. 굳이 for문을 사용해야할 이유가 없는 것 같아서  forEach로 선택을 했습니다.

그 결과 다음과 같이 바꾸어보았습니다.

```swift
        Operator.allCases.forEach { (operation: Operator) -> () in
            resultOfReplacing = resultOfReplacing.replacingOccurrences(of: String(operation.rawValue), with: " ")
        }
```


번외로, 이 부분은 고차함수 reduce를 검색하고, 적용해본 코드입니다. 
```swift
   
        Operator.allCases.reduce(input) { (result: String, operation: Operator) -> String in
            return result.replacingOccurrences(of: String(operation.rawValue), with: " ")
        }
```

무엇이 가장 괜찮은지는 잘 모르겠습니다.😅

2021-11-18 09:40 UTC, oksunwoo commented on Calculator/Calculator/Extension/Extension+String.swift
> +    }
우선적으로, 그렇게 생성한 이유는 UML에서 요구했기때문에 따로 작성해주었습니다...
그래서 구조체를 만들떄와 extension을 사용했을 때와의 차이를 조금 생각해보았습니다.
- 첫번째로는 extension을 사용할 경우 파일 전영역에 영향력을 끼치는게 가능하다고 생각을 했습니다. 만약 구조체를 사용해서 메소드를 만들어준다면, 해당 인스턴스를 생성한 곳에서만 사용을 할 수 있도록 제한이 될 것이라고 생각했습니다. 
- 두번째로는 인스턴스의 유무입니다. 현재 String은 별도의 인스턴스를 생성하지 않아도 사용을 할 수 있지만, struct에 생성을 해준 경우에는 그 메소드를 호출하기 위해선, 인스턴스의 생성이 필요하다고 생각했습니다.

저는 이와같은 차이가 있다고 느꼈는데 혹시, 다른 요소가 있다면 알려주시면 감사하겠습니다!

2021-11-18 09:56 UTC, oksunwoo commented
안녕하세요 도미닉(@AppleCEO )!! 토니입니다.
날카로운 지적과 리뷰 감사드립니다.

도미닉께서 지적하신 부분들 수많은 고민끝에 수정해보았습니다. 부족한 부분있다면 지적해주시면 바로 수정해보겠습니다.

그리고 답변 남겨주신, Parse메소드를 간략하게 설명드리자면 

1. 우선적으로, componentsByOperators(input: String)을 통해서 문자열로 입력된 계산식을 입력받게 됩니다. 이 메소드는 +, - , / , * 연산자들을 모두 공백(" ")으로 바꾸어 숫자만 남겨주는 기능을 합니다. 그 후 남은 숫자들을 split하여 숫자큐에 enqueue 하게 됩니다.
2. 연산자들역시 연산자큐에 넣어주어야 하기에, Parse안의 input을 filter와 contains를 통해 +, - , / , *  기호들만 꺼내서 차례로 연산자큐에 euqueue하게 됩니다.

또 부동소수점 오류에 관해서 제가 생각했던 방법은 반올림이였습니다. round() 또는 format을 이용하여 반올림을 할까도 생각을 해보았지만, 조금 더 정교한 계산을 요구할때는 값이 다를수도있겠다고 생각하여 꼼수(?)를 쓰는 방법인것같아 실제로 사용하지는 않았습니다. 여러 캠퍼들과 이야기해본 결과 Decimal을 이용하면 일부 해결할 수 있다고 설명들었습니다. 하지만, String에서 Double로 다시 변환시에 비슷한 오류가 발생한다고 완벽한 방법은 아니라고 했습니다. 그 밖에, 추가로 생각해본 것은 부동소수점 오류가 소수점 17번째 자리에서 발생을 하길래, 16번째 즈음에서 절삭하는 방법도 생각해보았습니다.

이 이외로 도미닉이 지적해주신 부분 수정해서 각각 코멘트로 달아놓았습니다! 감사합니다

2021-11-18 11:13 UTC, AppleCEO commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        resultOfReplacing = resultOfReplacing.replacingOccurrences(of: String(Operator.multiply.rawValue), with: " ")
reduce 좋은 것 같아요 ㅎㅎ

2021-11-18 11:13 UTC, AppleCEO commented on Calculator/CalculatorQueueTests/ExpressionParserTests.swift
> +    func test_정상적인_연산을_하는지() throws {
test_12_곱하기_마이너스3_더하기_5_빼기_4_나누기_5_는_마이너스7_인지() 보다
test_12_곱하기_마이너스3_더하기_5_빼기_4_나누기_5_는_마이너스7_이다() 가 좋을 것 같기도 한데 어떻게 생각하시나요? ㅎㅎ

2021-11-18 11:19 UTC, AppleCEO commented on Calculator/Calculator/Extension/Extension+String.swift
> +    }
struct 에서 static function 을 만들면 어떨까요? ㅎㅎ
이런 경우 저는 extension 을 사용하는 것을 지양하는 편입니다.
관련없는 string에도 해당하는 메소드가 생기기 때문입니다.
https://velog.io/@wonhee010/extension
이 블로그 글을 한번 참고해보시면 좋겠습니다!

2021-11-18 11:19 UTC, merged