계산기 [Step3] 호박
yagom-academy/ios-calculator-app pull request #110
Opened 2021-11-17 06:41 UTC by hoBahk

안녕하세요 도미닉! @AppleCEO 

Step3 PR 보내드립니다!
이번에도 잘 부탁드립니다..!! 😃

## 고민한 점

1. 스크롤뷰에서 스크롤이 완전히 내려가지 않고 하나씩 밀리는 현상
스크롤이 가장 아래를 향하도록 하였는데 마지막 연산이 스크롤 아래에 있었습니다. 계속 하나씩 밀리는 현상이 있어 이유를 고민해보고 찾아보았습니다. 이유는 스택뷰가 추가 된 것이 업데이트 되기 전의 사이즈를 가지고 스크롤의 위치를 정한다는 것을 발견하게 되었습니다. 그래서 스크롤의 위치를 정하기 전에 스크롤 뷰를 업데이트 해주는 `scrollView.layoutIfNeeded()` 를 사용하여 스크롤뷰를 업데이트 하고 사이즈를 측정하여 스크롤의 위치를 정할 수 있게 하였습니다.

2. 메서드 분리
처음에 먼저 구현이 될 수 있도록 버튼을 누르면 동작하는 IBAction 메서드에 모두 넣고 나서 나중에 중복되거나 재사용이 될 수 있는 기능들을 메서드를 생성하여 분리하였습니다.

## 질문할 것

1. 에러처리
아래의 상황에서 꼭 에러를 던져줘야 하나요?
제가 생각하는 선에서는 default로 빠질 일이 없다고 생각하는데 에러처리를 하게 되면 do-try-catch문까지 써야 해서 해당 메서드를 사용하는 곳에서의 가독성이 많이 떨어진다고 생각이 됩니다. 
혹시 에러가 발생할 수 있다면 어떤 상황에서 에러가 발생하는지 힌트를 주실 수 있을까요?
도미닉의 조언을 구하고 싶습니다!

```swift
private func operators(for buttton: UIButton) -> String {
        switch buttton {
        case addButton:
            return String(Operator.add.rawValue)
        case subtractButton:
            return String(Operator.subtract.rawValue)
        case divideButton:
            return String(Operator.divide.rawValue)
        case multiplyButton:
            return String(Operator.multiply.rawValue)
        default:
            return ""
        }
    }
```

2. 코딩 컨벤션
간단한 if문과 옵셔널 바인딩 때문에 `return`하는 것을 다음 줄로 넘겨서 하면 가독성도 떨어진다고 생각했습니다. 그래서 아래와 같이 return만 해주는 if문, guard문은 한 줄에 적었습니다. 
그런데 이렇게 하면 다른 if문이나 guard문과의 통일성이 떨어질 수 있다고 생각했습니다.
그래서 고민을 했는데 통일성이 저하되는 것보다 가독성이 올라가는 것이 더 크다고 생각했습니다.
도미닉은 혹시 어떻게 생각하시나요? 도미닉의 의견이 궁금합니다!
아니면 다른 좋은 방법이 있을까요?

```swift
if operand == initializeToEmptyString { return }
        
guard let operatorLabelText = inputedOperatorLabel.text else { return }
```

2021-11-18 06:49 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
호박 고생하셨습니다
아래 코멘트들 참고해주세요

1. 에러처리
- tag 를 0,1,2,3,4 등 Int로 하고 switch문 대신에 rawValue 로 열거형을 만들어서 매칭을 시키면 어떨까요?

2. 코딩 컨벤션
- 저는 보통 풀어서 쓰는 것을 선호합니다. 짧은 코드가 가독성이 좋다는 생각은 안 하는 것이 좋습니다. 길어지더라도 정확한 위치, 예상되는 위치에 코드가 있는 것이 더 가독성이 좋다고 생각합니다.

2021-11-18 11:36 UTC, hoBahk commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet private weak var inputNineButton: UIButton!
도미닉이 조언해주신 것처럼 버튼의 `accessibilityIdentifier`를 사용하여 어떤 버튼인지 식별하게 하여 열거형의 `rawValue`와 매칭시켜 case를 받을 수 있게 하였습니다. 
그 후에 열거형에 `CustomStringConvertible` 프로토콜을 채택하여 해당하는 문자열을 반환할 수 있도록 하여 해결했습니다.😀

`CustomStringConvertible`프로토콜을 사용하면 메서드를 한번더 불러오지 않고 열거형과 케이스만 적어주면 문자열을 불러올 수 있어서 편리함이나 가독성 측면에서 이점이 있는 것 같네요!
도움 주셔서 감사합니다 ㅎㅎ

2021-11-18 11:39 UTC, hoBahk commented on Calculator/Calculator/Controller/ViewController.swift
> +        if operand == initializeToEmptyString { return }
아! 그렇군요..! 
저도 사실 그런 경우는 못보긴 했는데 한 줄로 간단하게 쓰고 싶단 생각에 그렇게 했는데 코드를 읽는 사람 입장에서는 읽기 힘들수도 있단 생각이 드네요!
풀어 쓰도록 수정하였습니다!

2021-11-18 11:39 UTC, hoBahk commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let operatorLabelText = inputedOperatorLabel.text else { return }
넵 수정했습니다 😄

2021-11-18 11:40 UTC, hoBahk commented on Calculator/Calculator/Error/CalculateError.swift
> +        }
`CustomStringConvertible` 프로토콜을 사용하여 수정했습니다!

2021-11-18 11:41 UTC, hoBahk commented on Calculator/CalculatorTests/ViewControllerTest.swift
> +        sut.
악.. 커밋을 막했었네요.. 지금은 삭제된 파일입니다.. ㅎ

2021-11-18 11:48 UTC, hoBahk commented on Calculator/Calculator/Controller/ViewController.swift
> +extension ViewController {
현재 코드에서는 단순히 기능별로 묶어서 표현하기 위해서 사용했습니다.
그리고 추후에는 프토토콜 채택하는 것을 분리하거나 (프로토콜을 구현하는 부분을 분리 등..) 기능확장 할 때 사용할 수 있을 것 같습니다!

2021-11-18 12:22 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
호박 고생하셨습니다~
몇가지 아쉬운 점 코멘트 드렸습니다!

2021-11-18 12:22 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +            } catch let error {
이 쪽 return 은 줄이 안 맞는 걸까요?

2021-11-18 12:22 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
보기 좋습니다~ 💯

2021-11-18 12:22 UTC, AppleCEO commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
이 부분도 축약형으로 보이네요 ㅜㅜ
기본형으로 바꿔볼까요?

2021-11-18 12:22 UTC, AppleCEO commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
이 부분도 기본형으로 바꿔보면 좋겠습니다.
줄 바꿈이 안 맞네요.

2021-11-18 12:22 UTC, AppleCEO commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
접근제어자를 제거한 이유가 있을까요?

2021-11-18 12:53 UTC, hoBahk commented on Calculator/Calculator/Model/Operands.swift
> +    }
네 최대한 변경해야하는 코드를 줄이자는 생각으로 변경되면 case의 rawValue만 변경하면 되도록 했습니다.

2021-11-18 12:54 UTC, hoBahk commented on Calculator/Calculator/Model/Operands.swift
> +enum Operands: String, CustomStringConvertible {
오우 기준이 있었으면 좋았겠지만.. 그냥 빼먹은 것 같습니다... ㅎ 
열거형 `operator`에도 `CustomStringConvertible`을 extension으로 분리하지 않아 같이 분리 했습니다.
따로 빼서 쓰니까 좀 더 보기 좋아진 것 같습니다. 
아직 익숙치는 않아서 더 신경쓰면서 해야겠네요..!

2021-11-18 12:54 UTC, hoBahk commented on Calculator/Calculator/Controller/ViewController.swift
> +            } catch let error {
앗 들여쓰기도 신경써야겠네요.. ㅎㅎ

2021-11-18 13:07 UTC, hoBahk commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
제가 축약한게 소괄호 하나 있는데 말씀하시는 부분이 맞을까요?
일단 소괄호 추가하였습니다. ㅎ

2021-11-18 13:10 UTC, hoBahk commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
여기도 소괄호 추가하였습니다.
그리고 `value`라는 이름이 너무 포괄적인 것 같아 `inputString`로 변경 하였습니다. 
줄바꿈은 너무 길어져서 보기가 힘들것 같아 의도하였습니다.
고차함수는 보통 줄바꿈을 하지 않고 쓰나요?

2021-11-18 13:23 UTC, hoBahk commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
테스트 코드에서 접근할 수 없어서 다시 삭제 했는데..
접근제어자를 설정하고 init까지 만들어놓고 그걸 사용하지 않고 접근제어자를 지워버렸네요. 
테스트 때문에 코드를 변경하는 위험한 행동을 했네요.. ㅎ 
다시 접근제어자 설정하고 테스트 코드를 변경하였습니다.

2021-11-19 06:10 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
두가지 코멘트 한번 확인해주시면 좋겠습니다~

연산 결과가 나온 상태에서 +/- 버튼을 누르면 숫자가 사라지네요. 이 부분도 한번 확인 부탁드립니다~
![image](https://user-images.githubusercontent.com/47517256/142573915-da49923d-59b6-4479-8b03-76ed621f8154.png)

2021-11-19 08:10 UTC, merged