계산기 [STEP 3] chacha
yagom-academy/ios-calculator-app pull request #117
Opened 2021-11-18 08:29 UTC by ChaminLee

안녕하세요 cory! @corykim0829 
계산기 Step 3 구현 완료하여 PR 보내드립니다. 

까다로운 예외 케이스를 커버해보려고 하다보니.. 코드가 조금 복잡하고 가독성이 떨어지게 된 것 같습니다.😢
그래도 최대한 기능의 분리에 초점을 맞추어 나누어보려고 노력했고, 예외 케이스를 커버하는 부분이나 어떻게 하면 자연스럽게 연산이 이어질 수 있는지 등 고민하고 코드를 작성해보았습니다!

이번 step도 잘 부탁드립니다!🙇🏻‍♂️

--- 
## 1. 고민된 점 및 해결 방법

> 1. Double은 16자리까지 표현이 가능하다는 것 

처음에 20자리까지 입력된다는 조건이 있어서 숫자를 입력하던 도중 특정 자리수를 넘어서는 순간부터 일부 숫자가 0으로 변하는 현상을 목격하였습니다. 이에 확인 결과 `Double`은 16자리의 수까지만 표현이 가능하다는 것을 알고 이를 대처하기 위해 `지수 표기법`으로 표현하고자 했습니다. 

이에 1000000... 입력을 하다가 17자리가 되는 순간 `1e+16`과 같이 표현되도록 구현하였습니다. 연산 이력이 나오는 `stackView`나 연산 결과를 보여주는 곳 또한 마찬가지로 17자리를 넘어서는 경우 `지수 표기법`으로 표현해주었습니다. 
 
> 2. 연산 결과가 있을 때, 피연산자/연산자 버튼을 눌렀을 때 대응 

우선 연산(`=`) 이후 연산자와 피연산자 케이스를 나누어 고민을 해봤습니다. 

- 피연산자 버튼 터치 시
	- 연산 결과를 지우고 새로운 식으로 시작
- 연산자 버튼 터치 시
	- 연산 결과가 유효한 경우 기존 식에서 이어서 연산식 추가
	- 연산 결과가 `NaN`인 경우 연산자 버튼이 작동하지 않도록 구현

> 3. 부동소수점 문제 

실제 연산을 테스트 할 때 `1.04 - 0.42`나 `10.0 / 3.0`과 같은 식에서 예상한 값과 다른 결과를 반환하는 것을 확인했습니다. 이에 문제는 부동소수점이라는 것 또한 확인하였고 이를 해결하기 위해 `Double`로만 연산하는 것이 아니라 `Decimal` 타입을 활용하여 연산하도록 구현하였습니다. 

> 4. ScrollView AutoScroll

연산 이력이 `stackView`에 계속 쌓이게 되면서 어느 순간 `stackView`의 높이가 `scrollView` 의 프레임 높이 보다 커지는 순간이 올 때가 있습니다. 이 때 요구되었던 것 처럼 자동적으로 `scrollView`의 최하단을 보여줄 수 있도록 구현하였습니다. 이 과정에서 `main run loop`에 대해 학습해보게 되었습니다. 사용자의 인터랙션을 처리하고 다시 `main run loop`로 돌아가는 시점을 `update cycle` 라고 하는데, 이 때 `view`들의 값이 변한다고 하여 애니메이션도 이 시점에 동작하겠구나 생각했습니다. 

이에 `layoutSubViews`를 예약하는 `setNeedsLayout` 과 `layoutIfNeeded`에 대해서 알게 되었습니다. 

- `setNeedsLayout`
	- `layoutSubViews`를 예약하여, `update cycle`에서 실행되도록 한다. 
	- view의 애니메이션 등이 즉각 반영되지 않는다. 
- `layoutIfNeeded`
	- `layoutSubViews`를 예약하는 행위는 동일하나, `update cycle`이 아닌 `layoutIfNeeded`이 불린 시점에 즉각 업데이트 한다. 
	- 애니메이션에 적합하다. 

위와 같은 내용에 기반하여 view의 변화가 즉각적인 반영이 필요하기에 `layoutIfNeeded`를 사용했습니다!

## 2. 질문하고 싶은 부분 

> 1. `NumberFormatter`를 활용하여 소수를 나타내는 방법

사용자의 입력이나, 화면에 표시되는 수에 대해서 기본적으로  `NumberFormatter`를 활용하여 3자리마다 `,` 를 찍어주었습니다. 이에 다양한 수에 대해서 테스트해보던 중 현재 값이 없는 0의 상태에서 `.`(점)을 입력하거나, 소수자리에 0을 입력하는 경우 `123.0000`에 값들이 반영되지 않고 사라지는 상황을 마주했습니다. 

이에 알아보니 `NumberFormatter`는 `1.`을 `1`로 보고 `123.0000`을 `123`으로 판단하는 듯 하여 다른 방법을 고안해봤습니다. 그래서 해결방법으로는 기존에 완성된 숫자를 가지고 `NumberFormatter`를 통해 변환하는 것이 아니라, `NumberFormatter`의 결과에 원하는(`NumberFormatter`로는 변환되지 않는) 숫자를 입력해주는 방식으로 해결했습니다. 

> ex.  `1.000`은 `NumberFormatter`로 표현할 수 없으니 `1`만 `NumberFormatter`를 통해 가공하고 뒤의 `.000`은 따로 붙여주는 방식

이와 같이 해결하긴 하였으나, 통상 숫자를 다루는 부분에 있어서 어떻게 처리하는 지 궁금합니다. 또 위 처럼 해결하는 것도 문제가 없을지 아니라면 더 좋은 방법이 있다면 조금의 힌트라도 주시면 감사하겠습니다~!

> 2. 부동소수점 문제

위의 고민 3번에서 말씀드린 것 처럼 `Decimal`을 활용하여 해결했다고 생각했으나, `100.0 / 3.0`을 하는 경우 `33.33333333333333`이 나오지 않고 `33.33333333333334`가 나오는 상황을 마주했습니다... (따로 올림 옵션을 주지 않았습니다!)

`10.0 / 3.0`을 해결해서 문제가 없을 것이라고 생각했는데 이와 같이 예상치 못한 문제를 보고나서 기존에 선택한 해결 방법이 100% 해결을 하지 못하는 것인가 고민하게 되었습니다. 결국에는 고민 후에도 마땅한 답을 내리지 못하여 여쭙습니다! 

부동소수점 관련한 문제를 해결하기 위해 `Decimal`을 사용한다고 알고 있는데, 이처럼 예외 케이스가 있다면 어떻게 해결해야 할지 궁금합니다!

> 3.  MVC에서의 ViewController의 역할 

Step 3를 진행하면서 모든 코드가 거의 다 `ViewController`에 작성된 것 같습니다. 이에 MVC의 단점으로 꼽히는 `ViewController`의 역할이 커지고 무거워 진다는 것을 몸소 느끼게 되었습니다. 

이에 view와 관련이 없는 기능들을 다른 타입을 생성하여 역할과 책임을 나눠야 하나 생각했지만, 이미 코드가 작성된 뒤여서 생각만 해봤습니다.... 

처음부터 나누었다면 역할과 책임이 분리되면서 `ViewController`의 역할도 조금 줄어들지 않았을까 생각이 되었습니다. 

이에 MVC 구조로 프로젝트를 진행할 때, MVC 구조를 유지하면서 `ViewController`의 역할을 덜어주는 방식은 위에서 말씀드린 것 처럼 view와 연관이 없는 기능들을 분리하는 정도라고 생각하는데 다른 더 좋은 방법이 있을지 궁금합니다. 혹은 MVC 구조 자체의 한계여서 다들 이야기하는 MVP, MVVM으로 일부 해결할 수 있는 것인지..! 궁금합니다!

> 4. `ViewController`에서 코드 작성시 TDD를 해야하나요?

아직 `UI TEST`를 학습하지 않아서인지, TDD를 해보려고 하니 감이 잡히지 않고 무언가 view와 연관된 코드들이 많다보니 테스트하기가 힘들겠다 라고 생각을 하게 되었고 결국에는 프로덕션 코드만 작성하게 되었습니다. 

이러한 상황에서도 TDD로 진행할 수 있는 부분이 있을까요? (ex. View와 연관되지 않은 메서드들..?) 도저히 감이 잡히지 않아 여쭙습니다!

---

감사합니다~!

2021-11-18 15:52 UTC, corykim0829 requested changes
수고 정말정말 많으셨어요 차차!! 👍👍👍

UI 구현도 전반적으로 잘 처리하셨습니다.
제가 시뮬레이터로 테스트해봤을 때에는 계산 결과 누적되는 스크롤뷰 윗 부분을 조금 더 확장할 수 있을 것 같은데 이 부분 한번 더 확인해주시면 좋을 것 같아요!!

제가 남겨드린 피드백 바탕으로 더 개선해봅시다!
추가로 궁금한 점은 언제든지 말씀해주세요!!

---

> 1. NumberFormatter를 활용하여 소수를 나타내는 방법

제 생각에는 소수 값일 경우 `.` 이후에 0만 있을 경우만 처리하면 되지 않을까요?
그리고 제가 몇가지 테스트를 해보니까 나누기 0을 테스트 할려고 헀을 때, 예를 들어 9 / 0 을 할 때 9를 누르고 나누기를 누르면 바로 0이 나와서 `=`을 누르면 오류가 나와야할 것 같은데, 바로 9가 나오더라구요! 이 부분은 이렇게 하기로 미션에서 약속이 된건가요?

> 2. 부동소수점 문제

이 부분은 깊게 파고 들지 않아도 될 것 같아요. 애플도 처리하는걸 보면 자리수를 제한하여 처리한 것 같아요. 중요한 부분이 아니니 시간이 남으면 자리수를 제한하는 방법 등으로 해결 할 수 있을 것 같아요.

> 3. MVC에서의 ViewController의 역할

VC가 무거워지는 것을 벌써 느끼셨군요! 좋은 인사이트입니다!

> 이에 MVC 구조로 프로젝트를 진행할 때, MVC 구조를 유지하면서 ViewController의 역할을 덜어주는 방식은 위에서 말씀드린 것 처럼 view와 연관이 없는 기능들을 분리하는 정도라고 생각하는데 다른 더 좋은 방법이 있을지 궁금합니다

이 부분에 대해서는 View나 Model 로직 관련한 것들을 객체로 분리하는 방법이 있을 것 같아요.
하지만 너무 걱정안하셔도 되는게, 지금 프로젝트에서는 한 화면에 버튼이 많아서 대응해야할 게 많은 것은 당연한 겁니다. 그러니 너무 걱정안하시고 진행하셔도 될 것 같아요. MVVM은 ViewModel 이라는 것을 만들자고 약속해서 Controller의 일을 조금 덜어주는 역할이 추가되는 것이니 너무 MVVM을 꼭 해야한다! 이런 생각은 안하셔도 됩니다. 모든 것에는 장단점이 있으니까요 그 차이점을 알아나가는 것도 중요합니다! MVC도 먼저 잘 알아가는 것도 중요하다고 생각합니다!

> 4. ViewController에서 코드 작성시 TDD를 해야하나요?

저도 UI TEST는 경험이 많이 없어서 죄송스러운데요 🥲
로직에 사용되는 부분만 테스트하는 것도 충분하다고 생각합니다! 그러기 위해서는 책임 분리를 잘 해야겠죠!

2021-11-18 15:52 UTC, corykim0829 commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBAction private func changePlusMinusSign(_ sender: Any) {
다른 버튼 IBAction과 동일한 컨벤션으로 네이밍을 하면 좋을 것 같아요!

2021-11-18 15:52 UTC, corykim0829 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var finalFormula = [String]()
Formula는 operand와 operator를 각각 큐로 가지고 있는 객체인데 여기서는 String 배열인데 조금 어색해요. 네이밍을 바꿔야할 것 같아요!

2021-11-18 15:52 UTC, corykim0829 commented on Calculator/Calculator/Extension/Extension+String.swift
> +
이곳 파일명을 다시보니 Extension 폴더 디렉토리 안에 Extension+String인게 어색하네요!
String의 Extension이라도 그 기능에 맞게 파일을 분리하는게 더 좋아보입니다.

2021-11-19 03:32 UTC, ChaminLee commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBAction private func changePlusMinusSign(_ sender: Any) {
이 부분만 다르게 작성이 되었네요..! `touchUpChangePlusMinusSign`으로 변경했습니다!

2021-11-19 03:33 UTC, ChaminLee commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func splitWithIntegerAndFraction(from operand: String) -> (interger: String, fraction: String) {
저번부터 계속 오타가... 꼼꼼히 확인하겠습니다😢

2021-11-19 04:15 UTC, ChaminLee commented on Calculator/Calculator/Controller/ViewController.swift
> +        let separatedCurrentOperand = splitWithIntegerAndFraction(from: currentOperand)
현재 로직 상 예를 들어 `01234.000`과 같은 숫자를 받을 수 있게 되어있는데, 이를 바로 `NumberFormmater`를 통해 가공하면 `1234`라는 값이 나오게 되어 부분을 나누어서 유효한 숫자 입력을 살려주기 위해 split을 사용하고자 했습니다. 

- 정수 부분
    - `0123` -> `123`
-  소수 부분 
    -  `000`

이에 분리한 정수 부분과 소수 부분을 활용하여 `정수 부분 + . + 소수 부분`으로 표현하도록 하여 누락되는 유효 숫자가 없도록 방지하였습니다! 혹시 다른 방식으로 0을 처리해야할까요??

2021-11-19 05:12 UTC, ChaminLee commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var finalFormula = [String]()
기존 `Formula`와는 형식이 달라 어색할 수 있었겠네요..! 아예 다른 단어이지만 "수식"이라는 의미를 갖게하도록 하기 위해 `mathExpression`으로 네이밍을 수정했습니다!

2021-11-19 05:25 UTC, ChaminLee commented on Calculator/Calculator/Extension/Extension+String.swift
> +
말씀주신 것 처럼 기능 별로 extension 파일이 분리되도록 구성하였고, 그 기능에 대한 내용을 담도록 네이밍을 수정해보았습니다!
![image](https://user-images.githubusercontent.com/45652743/142569859-e131227e-c748-47fc-bf2e-f3fa71573c3c.png)

2021-11-19 05:41 UTC, ChaminLee commented on Calculator/Calculator/Controller/ViewController.swift
> +        let selectedOperatorLabel = UILabel()
`ExpressionLabel` 커스텀 클래스를 만들어 아래와 같이 수정했습니다! 

```swift
let selectedOperatorLabel = ExpressionLabel(text: operatorText)
let selectedOperandLabel = ExpressionLabel(text: operandText)  
```

2021-11-19 05:43 UTC, ChaminLee commented on Calculator/Calculator/Controller/ViewController.swift
> +        let newHistoryStackView = UIStackView(arrangedSubviews: [selectedOperatorLabel, selectedOperandLabel])
`UILabel`과 마찬가지로 `UIStackView`도 커스텀 클래스인 `HistoryStackView`로 구현하였습니다!

이니셜라이저 부분은 기존 `UIStackView(arrangedSubviews: )`를 참고하여 구현하였습니다~!

```swift
let newHistoryStackView = HistoryStackView(arrangedSubviews: [selectedOperatorLabel, selectedOperandLabel])
```

2021-11-19 06:03 UTC, ChaminLee commented
안녕하세요 cory! @corykim0829 

Step 3까지 꼼꼼하게 피드백 주셔서 감사합니다! 
덕분에 많은 걸 배워가는 것 같아요!🙇🏻‍♂️

--- 

1. 개선 사항 

> 1. `7 / 0`

기존에 화면에는 0으로 출력되지만 실제로는 값을 가지고 있지 않게 구현했었습니다. 그래서 실제로 0이 보이긴 하지만 0을 터치해줘야 0 값이 들어가도록 했었습니다.그렇다보니 `7 / 0`하고 바로 `=` 누르는 경우 화면에서만 0이어서 `NaN`이 나오는 연산이 되지 않았었습니다. 이런 부분이 다소 어색해 보일 수 있을 것 같아, 이제 초기 값을 실제 0으로 갖도록 하여 해당 부분을 수정 완료하였습니다. 

> 2. Custom Class 추가 

동일한 속성을 반복적으로 줘야하는 부분들에 대해서 말씀주신 것 처럼 커스텀 클래스를 만들어 재사용성을 높였습니다! 훨씬 더 코드가 깔끔해지고 분리가 된 것 같은 느낌이 드네요!

> 3. 부동소수점

제가 질문한 `100.0 / 3.0`에 대한 문제의 원인은 찾은 것 같습니다! `Decimal`로 연산을 해주고 결과를 `Double` 타입으로 받기 위해 `NSDecimal`의 `.doubleValue`를 사용했었는데 여기서 예상치 못한 값으로 변하더라고요..! 이 부분은 조금 더 찾아보도록 하겠습니다!

--- 

감사합니다!

2021-11-20 14:07 UTC, corykim0829 commented on Calculator/Calculator/Controller/ViewController.swift
> +        let selectedOperatorLabel = UILabel()
생성자까지 활용하니 깔끔하네요 👍

2021-11-23 12:03 UTC, merged