ios-calculator-app [STEP 3] nicholas
yagom-academy/ios-calculator-app pull request #118
Opened 2021-11-18 08:44 UTC by Kim-EunsooSilver

안녕하세요~! 코리!!! 😭7

마지막 스텝 PR 전송입니다!!!
스텝1, 스텝2에서의 꼼꼼한 PR 덕분에 너무나 많은걸 배웠습니다~!
이번에도 좋은 피드백 기다리고 있겠습니다!!

# ‼️ 고민한점
1. 스토리 보드에 구현된 레이블들을 제거할지, 아님 뷰가 로드되면 제거할지 고민을 했습니다.
    * 아카데미에서 포크받은 소스이기에 일단, 제거하지 않았으며 로드되면 제거가 되도록 진행했습니다.
2. 자동 스크롤 다운에 대한 고민
    * 사용자의 입력될 때마다 최근에 입력한 값을 스크롤뷰 하단으로 삽입되며 스크롤을 자동으로 내리는 제약에 대해서 많은 고민을 했습니다!
    * 경험한 현상: 사용자가 입력한 시점에 바로 스크롤 다운 되는게 아닌, 한 박자(?) 늦은 스크롤 다운
    * 디버깅하면서 이해한 점
        * view 요소들을 생성하는 함수가 종료된 이후에 실질적으로 화면에 생성이 됨
        * 스크롤 다운이 되는 시점은 실질적인 요소가 생성되기 이전이기에 위에 적은 현상이 발생됨
    * 해결 방안
        * DispatchQueue를 이용한 스크롤 다운에 대한 지연을 줌
3. ViewController의 거대화
    * 기능 요구를 충족하다보니, ViewController가 비대해 진다는걸 느꼈습니다. 이에 Model과 직접적으로 통신하는 Controller를 별도로 구현하여, 분배하였습니다.
4. notFormattedOperand 변수를 만든 이유
    * 사용자의 입력을 실시간으로 입력받는 경우 numberFormatter의 영향으로 0.01을 입력할때 소수점 이후 0을 제거함
    * 실질적인 연산을 하기 위해서는 콤마를 제거하는 과정이 존재함
    * 이러한 이유로 사용자의 입력에 대해서 numberFormatter 형식을 거치지 않는 별도의 변수 `notFormattedOperand`를 만들었습니다.
5. numberFormatter의 최대 입력할수 있는 수
    * ref: https://stackoverflow.com/questions/45520019/numberformatter-issue-for-large-number
    * 사용자가 입력한 값이 15~16자리를 초과하는 경우 입력값과 다른 값을 출력되는 현상이 있었습니다.
    * 상기 사유로 사용자가 입력할 수 있는 수의 갯수를 15개로 제한을 두었습니다.
 
---
# ⁉️ 궁금한점
1. viewContoller 내부 @IBOutlet, @IBAction 요소들에 대한 접근 제어
    * 의존모둠 스크럼을 통해 알게되었습니다! 이전까지 프로젝트를 진행하면서 저는 접근제어를 별도로 진행하지 않았으며, 이 부분에 대해서도 리뷰를 받지 못했는데요! 코리가 생각하시는 해당 요소들에 대한 접근 제어 필요 유무가 궁금합니다.
2. 고민한점 2번에 대한 질문
    * 기재한 해결 방안을 찾기 이전에는 스크롤뷰에 자동 스크롤 다운이 되는 프로퍼티나 메서드가 존재하지 않을까라는 고민을 하고 찾아봤지만 찾지 못했습니다. 혹시 제가 찾지 못한건지... 궁금합니다!. 만약 없다면! 코리라면은 어떤 방향으로 해결을 하실지 궁금합니다.
3. ViewContoroller extension에 대한 질문
    * 이번에도 의존 모둠 스크럼을 통해 알게된 사실입니다..ㅎ ViewController 파일 내부에 기능별로 ViewContoroller를 extension을 통해 구분해 놓는 컨벤션(?)을 알게 되었습니다!! 이 컨벤션이 많이 사용되는 컨벤션인지 궁금합니다

---
이상입니다~! 좋은 피드백 많이 많이 부탁드립니다!!!👏🏻

2021-11-19 03:44 UTC, corykim0829 requested changes
수고 정말정말 많으셨습니다 니콜라스! 👏👏👏👏

코드가 전반적으로 깔끔해서 좋았습니다.
피드백 바탕으로 개선해봅시다 👍

---

> 1. viewContoller 내부 @IBOutlet, @IBAction 요소들에 대한 접근 제어

@IB 프로퍼티들은 스토리보드에서 가져올 때 생기는 어노테이션인데요! 왜 기본적으로 접근제어자가 이렇게 생기는지 한번 알아보면 좋을 것 같아요!
특별한 경우가 아니고는 default 접근제어자로 사용합니다.

> 2. 고민한점 2번에 대한 질문

UIKit UIScrollView에 자동 스크롤되는 함수나 프로퍼티는 없어요 😅
스크롤 하는 메소드는 니콜라스가 사용한 함수인 scrollRectToVisible와 setContentOffset가 있습니다.

말씀하신 부분에서 궁금한 부분이 있어요!
`경험한 현상: 사용자가 입력한 시점에 바로 스크롤 다운 되는게 아닌, 한 박자(?) 늦은 스크롤 다운`
이를 경험했다고 했는데 왜 DispatchQueue로 지연을 주신건지 궁금합니다!

> 3. ViewContoroller extension에 대한 질문

네 많이 사용합니다! 아예 파일을 분리하기도 하구요. ViewController가 커지는 경우가 흔하기 때문에 최대한 분리해주려는 작업이죠!

2021-11-19 03:44 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private var invalidCheckInputedOperand: Bool {
이 변수명을 조금 더 개선해보면 좋을 것 같아요. 지금은 어떤 역할인지 코드를 보지 않으면 짐작하기 힘들어요 👀

2021-11-19 05:07 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    func reset() {
코맨트를 보니 확실히 애매하다고 느꼈습니다!!! resetCalcurator로 함수명 변경했습니다!!!
감사합니다!!!🙏🏻

2021-11-19 05:12 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    func allClear() {
함수명, 변수명 고민했을때 찾아봤던 블로그 입니다.
> ref: https://m.blog.naver.com/triology/221066050241
> 계산기 버튼 이름의 본래 뜻
> AC: All Clear
> CE: Clear Entry

확실히 코리가 기재해주신 `clearAll`이 더 자연스러운데, 본래 준말이 별도로 존재하기에 코드를 수정하지 않았습니다!
Q. 궁금한점
* 코드단은 개발자가 보는 영역인데.. 본래의 뜻이 존재함에도 부자연스러운 표현이라면, 자연스러운 표현으로 변경을 해야하나요?

이번 코멘트는 코리의 의견을 듣고 반영하고 싶습니다!!!

2021-11-19 05:13 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorController.swift
> +        print(formula)
.... 디버깅 코드를 모두 제거했다고 생각했는데... 아니였네요...;;
민망스럽습니다....

2021-11-19 05:40 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private var invalidCheckInputedOperand: Bool {
🤔 코리 의견을 듣고 처음 보는 소스 코드라고 생각하고 다시 보았고 아래와 같이 변경했습니다.
* notFormattedOperand -> rawOperand
* invalidCheckInputedOperand -> checkNumberOfInputs

2021-11-19 06:06 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorController.swift
> +    private var formula = ""
🤔🧐 말씀학신데로 Formula 타입이 존재하므로 formula 라는 단어를 사용하면 혼동이 올거 같습니다.
해당 프로퍼티를 storedOperandAndOperator로 변경했습니다.

2021-11-19 07:38 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            label.font = UIFont.preferredFont(forTextStyle: .title3)
커스텀 UILable 클래스인 calculatorHistoryUILbel를 구현 후, 반영했습니다!!!

2021-11-19 07:40 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        func labelFormat(textValue: String) {
🤔 말씀하신 함수는 String을 입력받아 라벨을 생성후 stackView에 삽입을 하는 기능을 합니다.
이에 `insertValueToStackView`로 변경했습니다~!

2021-11-19 08:51 UTC, Kim-EunsooSilver commented
안녕하세요 코리~! 
피드백 주신 부분에 대해서 전반적으로 반영했습니다! 확인 부탁드립니다!!!🙏🏻

Q.코리의 질문
> 경험한 현상: 사용자가 입력한 시점에 바로 스크롤 다운 되는게 아닌, 한 박자(?) 늦은 스크롤 다운
> 이를 경험했다고 했는데 왜 DispatchQueue로 지연을 주신건지 궁금합니다!

A. 저의 답변
* 지연을 주지 않았을 경우 레이블을 포함하고 있는 스택뷰가 생성되기 이전에 스크롤 다운이 되었습니다. 
* 제가 구현한 데로라면은 아래와 같은 순서로 진행될것으로 예상했기에 DispatchQueue를 이용했습니다.
    1. 스택뷰가 실질적으로 생성되지 않음
    2.  DispatchQueue 실행
    3. 스택뷰를 만드는 함수 종료
    4. DispatchQueue로 지연은 줬던 스크롤 다운되는 기능 실행
---
추가적으로 의존모둠원의 도움으로 ViewController를 extension 기능을 활용하여 구분했습니다!
혹시 부족한 부분이 있다면 피드백 부탁드립니다~!

2021-11-20 09:47 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    func allClear() {
그 버튼에 대한 부분은 touchUpAllClearButton에서 이미 명시가 된 부분이라고 생각합니다. 그 버튼을 눌렀을 때 처리하는 코드는 통상적인 표현을 쓰는게 좋을 것 같아요.

2021-11-22 00:31 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    func allClear() {
크으으.... 또 배웠습니다...!
clearAll로 변경했습니다👏🏻

2021-11-23 11:52 UTC, merged