계산기 [STEP3] 릴리
yagom-academy/ios-calculator-app pull request #129
Opened 2021-11-19 10:49 UTC by yeahg-dev

안녕하세요 코리! @corykim0829 
시간과 실력이 부족해 스텝3의 요구사항을 모두 구현하지 못했지만🥲 
구현한 부분까지라도 리뷰를 받고 싶은 마음에 먼저 PR 요청드립니다.

연산을 하는 모델과 뷰 컨트롤러 연결하는 구현을 미완성해서 계산기능을 구현하질 못했네요😭
해당 부분은 PR후에 계속해서 수정해보려 합니다!

2주동안 정말 감사했습니다!
많이 부족하지만 잘 부탁드립니다!😊🙏🏻

# 고민한 부분
### 1. 표시되는 숫자를 관리하는 타입인 Number구조체 구현
버튼으로 숫자를 받고, 화면에 표시해주는 과정에서 NumberFormatter로 형변환을 하는 로직이 복잡할 것 같아 사용자 정의 타입을 만들어주었습니다. 다양한 케이스에 대한 테스트가 필요할 것 같아 TDD로 구현을 진행해보았습니다.
그런데 이렇게 타입을 분리해서 구현하는건  MVC패턴과 결을 달리하는 것 같다는 한켠의 찝찝함도 있었습니다ㅠㅠ

Number 구조체 역할
> - 사용자 입력을 유효한 숫자 표현으로 변환하여 리턴
> - 모델(`Formula`)에서 받은 Double타입의 연산결과를 유효한 숫자 표현으로 변환하여 리턴
<br>

### 2. ScrollView에 쌓이는 계산식을 관리하는 방법
scrollView의 contentView에 쌓이는 스택(연산자+피연산자)을 모두 더한 문자열이 ExpressionParser로 전해져서 Formula를 만들게 됩니다.
스택의 식을 뷰 컨트롤러에 어떻게 저장할지에 대해 두가지 방법을 고민해보았습니다.

뷰 컨트롤러에 ExpressionParser로 전해질 연산식 프로퍼티(String)을 선언한다.
1. UIScrollView의 delegate를 활용해서 컨텐츠가 추가될 때마다 자동으로 프로퍼티에 식을 더해준다.
2.  StackView가 add될때마다 프로퍼티에 식을 더해준다.

scrollView의 델리게이트를 활용해 볼 수 있을 것 같아 찾아보았는데, 막상 적용해 볼 수 있는 부분이 없어서 2번 방법으로 구현을 했습니다.
혹시 제가 놓친 부분이 있을까요~?
<br>

# 해결하지 못한 부분
### 1. 숫자 자리수

> 숫자는 최대 20자리까지만 표현합니다
> 잘리는 숫자는 반올림합니다

위 요구사항을 구현하지 못했습니다.
20자리의 숫자를 넣어도 출력가능한 범위는 소수점이하 17자리까지 였습니다. (NumberTests.swift에 관련 테스트가 있습니다)

그리고 17자리까지만 출력된다는 상황을 가정에서도, 18자리에서 반올림을 하는 기능을 구현하지 못했습니다.
```swift
class Formmater {
        let formatter : NumberFormatter
        init() {
            formatter = NumberFormatter()
            formatter.numberStyle = .decimal
            formatter.maximumFractionDigits = 20
            formatter.usesSignificantDigits = true
            formatter.maximumSignificantDigits = 20
            formatter.roundingMode = .ceiling
        }
```
제가 간과한 포인트에 대해 조언 부탁드립니다:)
<br>

### 2. 연산버튼을 첫번째로 터치시 스크롤 뷰에 연산자도 함께 출력되는 문제
숫자를 입력하고 `+` `-` `x` `÷`을 처음 눌렀을 때는 숫자만 스크롤 뷰에 올라가야 하는데,
그에 대한 분기처리가 미흡해서 이런 문제가 발생한다고 생각했습니다.
이 부분은 좀 더 고민해보도록 할게요!
<Br>

### 3. `=`터치 시 강제언래핑을 실패해서 그 다음 단계로 못 넘어가는 문제 
아래 코드는 지난 스텝에서 코리가 고차함수를 사용해보면 좋겠다고 리뷰를 주신 부분인데,
어떻게 고차함수로 만들어내야할지 구상이 안되어 포기했다가, 결국 이렇게 다시 마주하게되었네요😅
강제 언래핑이 얼마나 위험한 것인지 몸소 실감합니다!

```swift
for _ in 1...operators.itemCount {
            let rhs = operands.dequeue() as! Double
            let operation = operators.dequeue() as! Operator
            result = operation.calculate(lhs: result, rhs: rhs)
        }
```
<br>

### 4. 미구현 기능
- 스토리보드의 `AC`버튼 액션 메서드 
- 스택뷰가 추가될 때마다 Scroll이 올라가는 기능
- ScrollViews 오토레이아웃 적용
을 아직 구현하지 못했습니다.

2021-11-20 12:24 UTC, corykim0829 requested changes
수고 많으셨습니다 릴리! 👏👏👏

먼저 데이터 로직을 잘 처리하고 뷰로 넘겨주는 걸 생각하면서 피드백 반영하면 좋을 것 같습니다!
마음이 급하더라도 차근차근 나아갑시다 😀

---
> 1. 표시되는 숫자를 관리하는 타입인 Number구조체 구현
버튼으로 숫자를 받고, 화면에 표시해주는 과정에서 NumberFormatter로 형변환을 하는 로직이 복잡할 것 같아 사용자 정의 타입을 만들어주었습니다. 다양한 케이스에 대한 테스트가 필요할 것 같아 TDD로 구현을 진행해보았습니다.

➡️ Number 구조체라고 하셨는데, 현재 클래스라고 구현되어있습니다. 한번 확인 해주세요!
이 Number 객체가 제가 이해하기에는 계산기에서 입력한 숫자를 조금 더 잘 관리하기 위한 객체로 보이는데, Number라고 하면 숫자를 처리하는 그런 하나의 타입 처럼 보입니다. 그래서 이름을 먼저 개선해보면 좋을 것 같아요.


> 2. ScrollView에 쌓이는 계산식을 관리하는 방법

> (1). UIScrollView의 delegate를 활용해서 컨텐츠가 추가될 때마다 자동으로 프로퍼티에 식을 더해준다.
> (2). StackView가 add될때마다 프로퍼티에 식을 더해준다.

➡️ 버튼을 누를 때마다 따로 로직으로 처리를 하고, 뷰는 데이터를 받아서 업데이트하는 역할만 하는게 좋습니다. 그래야 뷰와 로직이 분리되어서 테스트를 하기 용이합니다.
1번이 정확하게 어떤 걸 의미하는지 잘 이해가 가지 않는데요.. 근데 2번은 StackView가 add될 때마다라고 하면 뷰단에 의존하는 것처럼 다른 버튼을 누를 때마다 따로 컨트롤러 단에서 로직을 처리하면 좋을 것 같아요.

> 3. 숫자 자리수
일단 `formatter.roundingMode = .ceiling` 는 올림 처리를 하는 코드입니다.
`formatter.maximumSignificantDigits = 20` 를 설정하면 `maximumFractionDigits`은 따로 설정할 필요가 없어요!
저도 직접 해보니 NumberFormatter로는 20자리까지 처리를 하지 못하네요. 
NumberFormatter가 아닌 다른 방법을 고민해봐야할 것 같아요!

2021-11-21 11:49 UTC, yeahg-dev commented on Calculator/Calculator/Controller/Number.swift
> +    let numberFormatter = Formmater().formatter
네 그럴 수 있을 것 같아요! 
NumberFormatter클래스를 상속하는 커스텀 클래스로 구현해보았습니다.
커스텀 클래스는 처음 만들어보는데 맞게 한 건지 모르겠네요😅

```swift
   class Formatter: NumberFormatter {
        
        override init() {
            super.init()
            self.numberStyle = .decimal
            self.usesSignificantDigits = true
            self.maximumSignificantDigits = 20
            self.roundingMode = .ceiling
        }
        
        required init?(coder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }
```

2021-11-21 11:55 UTC, yeahg-dev commented on Calculator/Calculator/Controller/Number.swift
> +        self.isBiggerThan0 = true
생성자에서 `self.isBiggerThan0` 에 `isBiggerThan0`를 대입해야하는데 실수로 true를 넣어주었네요..ㅎㅎ
수정했습니다!

2021-11-21 11:57 UTC, yeahg-dev commented on Calculator/Calculator/Controller/Number.swift
> +        guard digitCount < 20 else {
아하! 그렇겠네요~ 상수로 수정하는게 가독성이 더 좋을 것 같습니다.
수정해볼게요!

2021-12-31 08:31 UTC, closed without merging