계산기 [STEP3] 애플사이다
yagom-academy/ios-calculator-app pull request #133
Opened 2021-11-21 14:52 UTC by just1103

안녕하세요. 찌루루 @jae57
앞서 말씀드린대로 예정된 일정 안에 프로젝트 수행을 완료하지 못해서 주말에 마무리하여 STEP3 PR 드립니다. 늦어도 금요일까지 PR을 드렸어야 했는데 일정을 지키지 못했어요. 양해 부탁드립니다. 🥲 

일정이 가능하시면 이번주 프로젝트 리뷰에 방해되지 않는 선에서 PR 리뷰해주시면 정말 감사하겠습니다. 😊

## STEP3 구현 내용
- 사용자의 터치 이벤트를 처리하여 연산을 수행한다.
- StackView 및 Label을 활용하여 ScrollView에 연산 내역을 표시한다.
- 계산 내역이 길어지면, 사용자가 가장 최근의 연산 내역을 확인할 수 있도록 최하단으로 자동 Scroll 한다. 
- 소수점 자리는 최대 20자리까지 표시하고, 숫자는 1000 단위 마다 comma(,)를 표시한다.

## 고민한 점/궁금한 점
1. UI 요소를 스토리보드가 아니라 코드로 구현해본 것은 처음이었는데, ScrollView의 StackView/Label와 관련하여 코드가 제대로 작성된 것인지 궁금합니다. 불필요하거나 누락한 부분이 있다면 개선하겠습니다.

1. `숫자1-연산자1-숫자2-연산자2` 형태의 입력뿐만 아니라 `숫자1-연산자1-연산자2` 형태의 입력을 처리해야 했습니다. 이 경우 `연산자1`을 무시하고 `연산자2`를 반영해야 하므로 `숫자1-연산자1-연산자2-숫자2` 형태에서 `숫자2`를 입력받는 시점에 completeFormula에 `연산자1-연산자2` 정보가 반영되도록 처리했습니다.
   - 하지만 이 때문에 `숫자1-연산자1-연산자2-숫자2`가 입력된 시점에서 = 버튼을 탭할 경우, formula 및 ScrollView의 레이블에 `숫자2`가 표시되지 않는 문제가 발생했다. 따라서 touchUpResultBtn 함수에서 `숫자2`를 반영하도록 수정하였으나, **하드 코딩이므로 향후 유지보수에 부정적인 영향을 줄 수 있을 것 같습니다.** 이 경우 개선할 방법이 있을까요?
		```swift
		@IBAction func touchUpResultBtn(_ sender: UIButton) {
		    guard isCalculationOver == false else {
		        return
		    }
		    
		    completeFormula += currentOperand // formula에 반영되지 못한 마지막 숫자를 추가 (개선 필요)
		    addCalculationProcessWithHorizontalStackView() // StackView에 반영되지 못한 마지막 숫자/연산자를 추가 (개선 필요)
		    
		    refreshLabelsWithResult(of: completeFormula)
		    isCalculationOver = true
		}
		```
1. NumberFormatter를 적용하는 과정에서 따로 처리를 하지 않았는데, 유효숫자 처리가 저절로 됐습니다. (예) 0.123000000 → 0.123 / 1.22340000 → 1.2234) 
   `usesSignificantDigits` 프로퍼티에 대해 더 알아보니, default가 false라서 유효숫자 처리를 안하는 것으로 확인했는데, 어떻게 저절로 처리가 됐을지 궁금합니다. 😂
   - 관련 코드
		```swift
		func changeNumberFormat(of number: Double) -> String? {
		    numberFormatter.maximumFractionDigits = 20
		    numberFormatter.numberStyle = .decimal
		    
		    guard let resultInString = numberFormatter.string(from: NSNumber(value: number)) else { return nil }
		    
		    return resultInString
		}
		```

예외처리를 완벽히 구현하지 못한 상태라서 개선이 필요하거나 예외 처리가 완료되지 않은 부분은 주석으로 남겨두었습니다.

계산기 프로젝트가 많이 어렵다고 느꼈고 코드를 개선할 여지가 많을 것 같은데, 대략적인 방향이나 키워드라도 알려주시면 더 공부해보겠습니다. 😊

바쁜 와중에 이번 계산기 프로젝트 리뷰주셔서 감사합니다.

2021-11-22 06:04 UTC, jae57 requested changes
@just1103 
안녕하세요, 애플사이다!
마지막까지 완성하시려는 끈기와 열정 대단합니다👍

우선, 
ProcessLabel.swift 와 ProcessHorizontalStackView.swift 파일이 포함되어있지 않아서
저는 해당 파일을 볼 수가 없네요 ㅠㅜ 코멘트 남겼으니 보시고 수정 후 다시 PR주시면
수정된 것 기준으로 궁금한 점에 대한 답변과 코멘트 이어서 드리겠습니다!

2021-11-22 23:35 UTC, just1103 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		3696A7BA274A77A700A6012A /* ProcessHorizontalStackView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = ProcessHorizontalStackView.swift; path = ../../../../../Docum
다시 파일추가하여 말씀해주신 Copy items if needed 체크했고, 파일 포함하여 커밋된 것을 확인했습니다! 처음 보는 오류였는데 잘 알려주셔서 감사해요 👍

2021-11-23 00:45 UTC, just1103 commented on Calculator/Calculator/Controller/ViewController.swift
> +    func resetCalculator() {
VC의 접근제어자를 전체적으로 수정했습니다. 빼먹었던 부분인데 짚어주셔서 감사해요 😊

2021-11-23 00:51 UTC, just1103 commented on Calculator/Calculator/Controller/ViewController.swift
> +        return resultInString
아하! 그렇네요. 앞으로 결과값을 리턴할 때 리턴타입을 다시 한 번 확인해야겠습니다!

2021-11-23 00:57 UTC, just1103 commented on Calculator/Calculator/Controller/ViewController.swift
> +        if isLastOperator == false {
if문이 true인 경우를 항상 앞에 써주도록 유의해야겠네요! 
말씀해주신 부분을 다른 메서드에도 모두 적용했습니다. `if isCalculationOver == true { ... }` 부분도 모두 `if isCalculationOver { ... }`로 수정할 수 있었어요!

2021-11-23 01:19 UTC, just1103 commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
아하 그렇네요. 모든 연산기호를 변환하는 것이 아니라 1개면 변환하면 되니까 기존 코드보다 훨씬 효율적이네요! 감사합니다 :)

2021-11-23 06:30 UTC, jae57 commented
이제 파일 잘 보이네요 👍
우선 실행해보았는데 많은 부분 요구사항을 만족하고 있네요!
몇가지 아직 구현되지 않은 부분들 정리해보았습니다.
(제가 요구사항을 잘못이해한 것이라면 말해주세요 🙇‍♂️ ㅎㅎ)
- 숫자 3자리 수마다 쉼표 표기 -> 결과값을 보여줄 때만 적용이 되네요!
- 20자리 이상으로 숫자가 표현됨 -> 소수점 아래자리만 20자리를 카운트하고 있네요!
- 불필요한 숫자 제거 
  - 0 과 00 이 연속입력가능함 -> 000023 과 같은 숫자 표현이 가능함
  - 1.2340000 에서 뒷부분 0 이 표시됨
- 12 * 3 - 5 + 3 입력 후 CE 누르고, = 누르면 계산과정 스크롤뷰에 + 만들어있는 스택뷰가 추가되고, 결과값은 나오지 않습니다.

(+) 추가적으로, 계산과정들을 보여주는 ScrollView에 희미하게 스크롤바가 보이는데, showsVerticalScrollIndicator 속성을 이용해서 안보이도록 해주면 좋겠네요!

### 고민한 점/궁금한 점

1. 네, 잘 구현해주셨습니다. 
2. 하드코딩은 데이터 자체를 코드 내부에 직접 입력하는 것을 말합니다. 현재코드는 하드코딩으로 보이진 않고, 다만 같은 로직이 여러곳에서 반복적으로 보이는 데 이를 하나의 메서드로 어느정도 공통화 시켜주면 좀 더 정리가 될 것 같네요!
3. String(`"123.42000"`) 을 Double 혹은 Float으로 변환할 때 이미 유효하지 않은 숫자들이 제거되네요!

2021-11-24 02:58 UTC, merged