계산기(모둠) [STEP1] 아샌, 제리
yagom-academy/ios-calculator-app pull request #141
Opened 2021-11-23 08:33 UTC by ICS-Asan

안녕하세요. 쿠마! @leejun6694
아샌(@ICS-Asan), 제리(@llghdud921) 입니다. 
서로의 코드를 합치는 과정에서 조금 부족한 부분이 있겠지만 STEP1 리뷰 잘 부탁드립니다:)
작은 부분이라도 코멘트 주시면 다음 STEP2에 잘 반영할 수 있도록 노력하겟습니다!!
감사합니다!!

## 💻    주요 구현 내용
- **Model**
	
	- CalculatorQueue 구현(LinkedList 사용_제리)
		CalculatorQueue 내부 구현에서 DobleStack, LinkedList 차이가 있었습니다.
		LinkedList가 큐를 구현함에 있어 DoubleStack보다 시간복잡도가 줄어든다고 생각하여 
		LinkedList로 구현하였습니다.		
		기존 Operator와 Operands의 큐에 각각의 메서드를 통해 enqueue를 해주었지만 합치는 과정에서 Generic을 사용하여 범용성 있는 Queue로 리팩토링하였습니다.
	
	- Formula, ExpresstionParser(기존 로직 사용)
		기존 로직에서 LinkedList의 사용으로 인한 필수 변경사항에 대해 리팩토링 하였습니다.

	- Operator(기존 로직에 Decimal 변환과정 추가)
		기존 로직을 사용하되 연산 과정에서 발생하는 부동소수점 오차를 방지하기 위해 Decimal로 변환하는 과정을 추가하였습니다.
		이 과정에서 Decimal(0)으로 나누면 연산결과가 nan으로 나오기 때문에 divide메서드 내부에서 0으로 나누었을 때 nan을 반환하는 과정이 불필요해져 삭제하였습니다.
		
	- Error
		Error를 구현한 코드와 구현하지 않은 코드를 합치면서 정확한 Error 상황을 전달하기 위해 Formula내 result메소드에 Error를 던지도록 구현하였습니다. 

- **View & ViewController**

	- 전체 로직이 비슷하고 네이밍이 다른 정도라고 판단하여 각 코드에서 특징적으로 다르게 사용한 개념이나 기술을 하나의 코드에 반영하는 형식으로 진행하였습니다.
	
	- CustomView를 통한 StackView 생성
		StackView와 Label을 생성할 때 일일이 속성을 설정하지 않고 미리 CustomView를 통해 원하는 속성을 가진 UI요소를 생성해놓고 text만 새로 할당하여 사용할 수 있도록 했습니다.
		View의 속성에 대한 코드는 ViewController보다는 View내부의 파일에서 관리하는 것이 좋다고 생각했고, ViewController에서는 변경사항 및 추가를 하는 과정에만 관여해야 한다고 생각에서 수정을 하였습니다.
```swift
// 기존 코드 
func createFormulaStack() -> UIStackView {
        let formulaStack = UIStackView()
        
        formulaStack.axis = .horizontal
        formulaStack.alignment = .fill
        formulaStack.distribution = .fill
        formulaStack.spacing = 8
        formulaStack.addArrangedSubview(operatorLabel)
        formulaStack.addArrangedSubview(operandsLabel)
        
        return formulaStack
    }
    
    private var operatorLabel: UILabel {
        let operatorLabel = UILabel()
        operatorLabel.font = UIFont.preferredFont(forTextStyle: .title3)
        operatorLabel.textColor = .white
        operatorLabel.text = inputOperatorLabel.text
        
        return operatorLabel
    }

// 수정 코드
class FormulaStackView: UIStackView {
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        initializeLabel()
    }
    
    required init(coder: NSCoder) {
        super.init(coder: coder)
        initializeLabel()
    }
    
    func initializeLabel() {
        axis = .horizontal
        alignment = .fill
        distribution = .fill
        spacing = 8
    }
}

class FormulaLabel: UILabel {
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        initializeLabel()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        initializeLabel()
    }
    
    func initializeLabel() {
        textColor = .white
        font = UIFont.preferredFont(forTextStyle: .title3)
    }
}
```
- 결과를 출력하는 과정에서 Decimal 변환 적용
	NumberFormatter로 숫자 형태를 변환하기는 하지만 연산결과에서 발생하는 부동소수점오차를 방지하지는 못했습니다. 
	그래서 result메서드 결과값을 출력하기 전에 Decimal로 한번 전환을 하여 올바른 연산 결과가 반영될 수 있도록 수정하였습니다.	
			

## 💡   조언 받고 싶은 내용
- **효과적이고 가독성이 좋은 옵셔널 바인딩 방법**
아래의 코드에서와 같이 UI요소들의 프로퍼티 값이 옵셔널이라 어쩔 수 없이 바인딩 과정을 진행해야 했습니다.
하지만 nil이 나오지 않을 것이라 판단되어 바인딩이 되지 않았을 때 특별히 수행해야 할 로직이 없다고 판단됩니다.
그래서 현재는 단순히 return만 사용하고 있는데 이것이 무의미한 과정이라고 생각되어 리팩토링을 진행하고 싶습니다.
이러한 문제에 대해서 어떻게 해결할 수 있는지 조언을 구하고 싶습니다.
키워드나 방법들을 알려주시면 함께 알아보면서 적용해 보겠습니다.
```swift
@IBAction private func tapNumberPad(_ sender: UIButton) {
        guard let currentNumLabel = inputNumLabel.text,
             let inputNum = sender.currentTitle else { return }
}
```
- **메서드내부 로직 변경으로 인한 리팩토링**
코드를 합치는 과정에서 로직이 조금씩 다른 메서드들이 합쳐지는 상황이 있었습니다. 
이 결과 옵셔널 값을 리턴하는 메서드로 인해서 코드의 가독성이 떨어지는 것 같다고 생각이 되었습니다.
하지만 바인딩과정을 필수적이라고 생각하고 반복문 또한 필수적이라고 생각하여 현재의 코드로 구현을 하였습니다.
해당 코드를 조금 더 간결하게 하고 싶은 욕심이 있는데 어떻게 개선하면 좋을 지 조언을 구하고 싶습니다.
고차함수를 사용하는 것이나 로직을 변경하는 등의 조언을 주시면 같이 고민해보고 리팩토링 할 수 있도록 하겠습니다.
```swift
// 기존 코드
mutating func result() throws -> Double {
        var result = try operands.dequeue()
        repeat {
            let calculateOperator = try operators.dequeue()
            let calculateOperand = try operands.dequeue()
            result = calculateOperator.calculate(
                lhs: result,
                rhs: calculateOperand)
        } while !operators.outbox.isEmpty
        return result
    }

// 수정 코드
mutating func result() throws -> Double {
        guard var result = operands.dequeue() else {
            throw CalculatorError.emptyQueue
        }
        
        var isContinue = true
        repeat {
            if let calculateOperator = operators.dequeue(),
               let calculateOperand = operands.dequeue() {
                result = calculateOperator.calculate(
                    lhs: result,
                    rhs: calculateOperand)
            } else {
                isContinue = false
            }
        } while isContinue
        
        return result
    }
```

- **MARK 주석에 대한 의견**
	ViewController내 MARK 주석을 활용하는 부분에 있어서 아샌은 기능별로 주석을 명시하셨고 저는 메서드 접근제한자와 종류를 기준으로 주석을 명시했습니다. 어떤 방법이 적합한 것인지 고민을 해보았는데요 명확하게 결론이 내려지지 않아서 조언을 얻고 싶습니다.

- **extension과 파일 분리**
	코드를 정리하는 과정으로 extension을 활용하는 방법에 대해 질문드리고 싶은게 있습니다. 
	extension을 사용하면 컴파일 시에 효율성이 저하되지 않을까 라는 궁금증이 생겼습니다.  
	그리고 extension을 이용해 다른 파일로 분리하는 것이 가독성이나 컴파일 측면에서 괜찮은 방식인지 여쭤보고 싶습니다.
	

STEP2의 과정이 리팩토링과 테스트 코드 작성으로 공지가 되어있어 현재 STEP1은 서로의 코드를 합치고 필수적인 부분만 리팩토링 하였습니다.
STEP1 리뷰 잘 부탁드립니다!!
감사합니다 쿠마!!!

2021-11-23 12:36 UTC, leejun6694 requested changes
서로의 코드를 합쳐보는 재밌는 경험이 되셨을 것 같네요.
몇 부분에 리뷰 드렸는데 확인 부탁드려요 : )

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var inputNumLabel: UILabel!
접근 제어가 필요해보입니다 : )

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var inputNumLabel: UILabel!
가급적이면 줄임말을 지양합니다~~!

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        formulaStackView.arrangedSubviews.forEach { $0.removeFromSuperview() }
저도 궁금해서 리뷰를 남겨요~!
초기화를 해주는 곳이니까, 하나씩 지우는게 아닌 전체를 한번에 지울 수 있는 방법이 있을까요?

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private func initializeNumberFormatter() {
numberFormatter 의 경우, 초기화가 한번만 있는 것 같네요.
다른 초기화 method 들과는 역할이 달라보이고 말 그대로 처음에 어떻게 세팅해줄지의 코드여서, 다른 방법으로 구현해도 좋을 것 같습니다ㅎㅎ

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let currentNumLabel = inputNumLabel.text,
`label` 을 정의하는 것인지, `label` 의 `text` 를 정의하는 것인지 네이밍을 다시 생각해볼 필요가 있어보여요~

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +         currentNumLabel.contains(".") == false {
온점 (.) 도 negativeSign 값과 같이 따로 관리해도 좋을 것 같네요ㅎㅎ (다른 친구도 만들어져 있으니까,, 라는 생각이 들어요)
그리고 이런 값들을 따로 어딘가 모아두는 것도 방법이겠네요 : )

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/View/FormulaStackView.swift
> +        spacing = 8
spacing 의 type 을 한번 확인해볼까요?

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/View/FormulaLabel.swift
> +    func initializeLabel() {
접근 제어도 한번 더 확인해볼까요~

2021-11-23 12:36 UTC, leejun6694 commented on Calculator/Calculator/Model/Formula.swift
> +                isContinue = false
음.. 이 flag 를 없앨 수 있을까 고민이 되네요.
저도 repeat 을 많이 안써봐서 잘 모르지만,, 여기서 `return result` 도 가능할까요?

2021-11-23 13:07 UTC, leejun6694 commented
> 효과적이고 가독성이 좋은 옵셔널 바인딩 방법

음.. 이번에 코드를 합치면서 느끼셨을 수도 있지만, 협업을 하다보면 나와 상대가 다른 부분이 많구나를 느낄 수 있습니다. 그래서 내가 구현했을 땐, 항상 당연했던 것들도 협업에선 다를 수 있죠. 더 나아가, 내가 구현했던 코드를 나중에 누군가가 이어서 진행할 수도 있기 때문에, `하지만 nil이 나오지 않을 것이라 판단` 은 좀 더 신중하게 다가갈 필요가 있을 것 같습니다.
이후 동작이 없다면, 지금처럼 바로 return 해주는 것도 좋습니다. 다만, 다른 방법을 더 찾아보자면 nil 인 경우 값을 하나 세팅해준다거나, 에러를 발생시킨다거나 등등의 구현이 있겠네요ㅎㅎ
당장 생각나는 방법이 많이 없긴 하지만, 이렇게 처리를 할 수 있는 방법들이 여러가지가 있는데, 이 중에서 고민하고 하나를 선택해서 코드에 담아낸다면 충분히 의미있는 코드 한줄이 될 수 있다고 생각됩니다 : )

> MARK 주석에 대한 의견

두가지 방법 모두 좋습니다ㅎㅎ 잘 활용할 수 있다면, 섞어서 사용할 수도 있구요~~!
이건 개인의 취향으로 남기겠습니다...ㅎ

> extension과 파일 분리

효율성이 저하된다는 것은 어떤 부분일까요!? 좀 더 설명 부탁드려요~

2021-11-24 01:43 UTC, llghdud921 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var inputNumLabel: UILabel!
접근제어자 추가 및 줄임말 수정 완료했습니다~~!

2021-11-24 02:02 UTC, ICS-Asan commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        formulaStackView.arrangedSubviews.forEach { $0.removeFromSuperview() }
저희도 removeAll이나 다른 메서드를 통해서 한번에 지우는 방법에 대해 고민을 했었습니다.🤔
하지만 arrangedSubviews가 get only property라서 직접 해당 프로퍼티를 지우거나 할 수는 없었습니다. 
그래서 removeFromSuperview()라는 메서드를 사용하여 내부 stackView를 비워주었습니다.😅

2021-11-24 02:32 UTC, ICS-Asan commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private func initializeNumberFormatter() {
NumberFormatter를 상속하는 CalculatorNumberFormatter클래스를 새로 생성해보았습니다.
내부 이니셜라이저에 위 메서드가 설정하는 부분을 넣어주었습니다😀

2021-11-24 02:56 UTC, llghdud921 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let currentNumLabel = inputNumLabel.text,
네 더 명확하게 currentNumberText로 변수명 변경했습니다!

2021-11-24 03:25 UTC, llghdud921 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +         currentNumLabel.contains(".") == false {
우선 온점을 dot으로 만들어주고
negative와 dot을 가지고 CalculatorSigns파일에 struct static 변수로 모아두었어요:)

2021-11-24 03:29 UTC, llghdud921 commented on Calculator/Calculator/View/FormulaLabel.swift
> +    func initializeLabel() {
네 저희가 놓쳤네요!! 수정했습니다~

2021-11-24 04:48 UTC, ICS-Asan commented on Calculator/Calculator/View/FormulaStackView.swift
> +        spacing = 8
spacing의 type을 확인해보니 CGFloat라는 것을 알 수 있었습니다!!
지금은 문제가 되지 않지만 type을 알아두라는 의미로 질문을 주신 것이 맞나요??
아니면 `spacing = CGFloat(8)`과 같이 코드를 작성하는 것이 일반적인 방법인가요?

2021-11-24 05:18 UTC, llghdud921 commented on Calculator/Calculator/Model/Formula.swift
> +                isContinue = false
고민을 해봤는데요..... 해결책이 잘 떠오르지 않네요ㅠㅠ 
현재 repeat-while 반복해서 연산하고 flag가 있어서 명확하다고 생각합니다. 현재는 코드를 유지하고 step2 리팩토링 과정에서 조금 더 생각할 시간을 갖도록 하겠습니다.

2021-11-24 05:32 UTC, llghdud921 commented
>extension과 파일 분리
이 부분은 extension을 사용할 시에 가독성은 높아지지만 타입이 분리되어 있어서 컴파일 시에 performance 차이가 있지 않을까? 라는 의문에서 질문드렸어요

질문드리고 공부해보니 static dispatch와 dynamic dispatch 를 알게되었습니다. 
- static dispatch : 컴파일 타임에 실제 호출할 함수를 결정
- dynamic dispatch : 런타임시에 호출될 함수를 결정

이 둘의 차이가 저희가 생각한 의문과 일치하는 것 같습니다. 이러한 요소들이 extension을 사용할 때 중요한 요소인지 판단이 잘 되지 않는것 같아서 질문 드립니다. 추가적으로 extension으로 파일을 분리하는 것에

2021-11-25 01:47 UTC, leejun6694 commented on Calculator/Calculator/View/FormulaStackView.swift
> +        spacing = 8
`CGFloat` 위치에 `0` 으로 구현했을 떄와 `0.0` 으로 구현했을 때 차이가 있는지 찾아보면 도움이 될 것 같아요 : )
큰 차이는 아니지만, 한번 확인해볼만해요ㅎㅎ

2021-11-25 01:48 UTC, ICS-Asan commented on Calculator/Calculator/View/FormulaStackView.swift
> +        spacing = 8
네!!확인해보겠습니다!!감사합니다!!👍

2021-11-25 01:52 UTC, leejun6694 commented
저도 처음 고민해보는 부분이네요ㅎㅎ
https://stackoverflow.com/questions/32894879/are-extensions-bad-for-performance-in-swift/32896948
위 링크를 참고해보면, 성능상의 걱정은 안해도 되는 것 같습니다 : )

2021-11-25 01:53 UTC, leejun6694 approved these changes
리뷰 내용 반영 감사합니다 : )

2021-11-25 01:53 UTC, merged