계산기(모둠)[STEP 1] 나무, 제인, 허황
yagom-academy/ios-calculator-app pull request #145
Opened 2021-11-23 15:18 UTC by siwonkim0

안녕하세요 콘! (@protocorn93 ) 🌽
나무, 제인, 허황입니다.
계산기 모둠 프로젝트 STEP 1 입니다!
세명이서 코드를 합치느라 시간이 오래걸렸습니다 🥲

# 고민한 부분
1. calculatorItemQueue 구현 방식
Double stack vs LinkedList
두 방식이 시간복잡도가 O(1)로 차이가 없는데 코드가 더 간단해서 링크드 리스트보다 **더블스택으로 구현하는 방식**을 선택했습니다. 

2. nan 처리 방식
Error throw vs Double.nan
0으로 나눗셈 연산을 수행할 때, 별도의 에러처리 없이 의도한 결과를 도출할 수 있기에 두 방법 중 **nan을 반환하는 방법**을 선택했습니다.

3. 리팩터링
이번 STEP 1은 리팩터링에 초점을 두지 않고 병합에 초점을 두고 진행했습니다.
STEP 2에서는 요구사항에 명시된 바와 같이 네이밍, 객체 간 역할 분리 등에 초점을 맞추어 delegation 패턴을 활용하여 리팩터링 할 예정입니다.

2021-11-24 12:27 UTC, protocorn93 requested changes
같은 기능으 코드를 합치는게 쉽지 않은 과정이었을텐데, 수고많으셨습니다 여러분! @hwangjeha @jsim27 @siwonkim0 

**충돌이 발생했습니다. 이 부분도 챙겨주세요~ **

## 피드백 

1.  세 분이서 각자의 코드를 갖고 의견을 교환하며 설득을 하는 과정이 있었을텐데요. 어떤 과정으로 진행이 되었나요? 또한 어떤 부분이 가장 그 과정이 길었으며, 왜 유독 길었는지 궁금하네요! 
2.  다시 말씀드리지만 델리게이트 패턴만이 정답은 아닙니다. 클로저를 넘겨줄 수도 있을거구요! 여러분들이 델리게이트 패턴으로 리팩토링하기로 결정한 계기가 궁금하네요.

2021-11-24 12:27 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +        let dot = "."
전체적으로 코드를 보면 지역변수로 해당 값의 의미를 부여해서 사용하고 있는데요~ 전 이런것들을 내부 타입으로 선언해서 관리합니다.

> 제 방법이 정답은 아니고 그냥 개발하면서 소소하게 편리함을 느꼈던 코드 스타일(?)입니다.

```swift 
class ViewController: UIViewController { 
    enum UserInput { 
        static let Dot = "."
        static let Zero = "0"
        ...
    }
}
```
제가 이렇게 사용하는 이유는 다음과 같습니다. 

이렇게 되면 메서드 안에서 매번 의미 부여를 위한 프로퍼티를 선언하지 않아도 되고, 이 자체로 보다 명확한 의미를 전달할 수 있더라구요. 또한 혹여나 값이 변경된다고 해도 전체 코드를 뒤져가며 변경하지 않아도 되고, 선언부만 변경하면 되니까요. 또한 개발자 실수도 어느정도 방지가 되구요

이는 뷰의 너비/높이 등 수치값을 저장하면 더욱 유용하게 사용할 수 있습니다. ex) `Dimensions.CellHeight` 
디자이너가 보고 값을 변경해달라고 해도 이를 사용하는 코드를 뒤질필요없이, 해당 뷰컨트롤러 클래스 상단 정의부만 변경해주면 되기 때문이죠

이렇게 "상수" 성격의 값들을 별도의 네임스페이스로 관리하면 도움이 될 때가 종종 있더라구요~

2021-11-24 12:27 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +        return text?.replacingOccurrences(of: ",", with: "") ?? ""
한 줄 짜리 코드지만 명확한 의미 전달을 위해 메서드로 분리한 점이 아주 좋네요! 👏

2021-11-24 12:27 UTC, protocorn93 commented on Calculator/CalculatorUnitTests/CalculatorItemQueueUnitTests.swift
> +    var sut2: CalculatorItemQueue<Operator>!
기본적으로 단위 테스트 코드에서 사용하는 명명법이 존재하지만 그와함께 보다 의미있는 이름을 짓는것도 중요합니다. 

단위 테스트 코드는 일종의 기능 명세서가 될 수 있습니다. 좋은 단위 테스트 코드는 그 단위 테스트 코드만 보아도 어느정도 기능의 동작을 예상할 수 있습니다. 그렇기 때문에 다른 사람이 여러분의 코드를 볼 때 단위 테스트 코드를 보고 프로덕트 코드를 보게 되면 보다 쉽게 동작을 이해할 수 있죠! 

그렇기 때문에 `sut` 이라는 용어를 사용하지만, 보다 부가적으로 명확한 의미를 전달할 수 있으면 좋을 것 같아요

2021-11-24 12:27 UTC, protocorn93 commented on Calculator/CalculatorUnitTests/CalculatorItemQueueUnitTests.swift
> +    var sut2: CalculatorItemQueue<Operator>!
다른 테스트 코드에선 단순히 `sut`을 사용해도 무방하지만 (클래스 이름에 명시되니까) 
하지만 이 경우엔 좀 더 명확한 의미가 전달될 수 있으면 좋겠네요

2021-11-24 12:27 UTC, protocorn93 commented on Calculator/CalculatorUnitTests/ExperssionParserTests.swift
> +        sut = ExpressionParser.self
`super` 호출이 누락된 것 같습니다.

2021-11-24 12:27 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +        operandLabel.text = togglePlusMinus()
아래 `insertDot`은 메서드 내부에서 `operandLabel`에 값을 할당하는 반면,  `togglePlusMinus`는 값을 반환하고 호출부에서 할당해주는데, 이렇게 둘을 다르게 구현한 이유가 있을까요?

2021-11-25 02:18 UTC, hwangjeha commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var calculatorItems = [T]()
CalculatorItemQueue는 개인 계산기 프로젝트 STEP 1에서 구현한 내용입니다.
UML은 야곰 아카데미 제공하지 않고 직접 작성했는데 코드를 병합하는 과정에서 접근제어자가 누락됐습니다😭
접근제어자 추가해서 커밋하겠습니다😊

2021-11-25 02:18 UTC, hwangjeha commented on Calculator/Calculator/ViewController.swift
> +// MARK: - IBAction
이 부분도 접근제어자 추가 후 커밋하겠습니다😊

2021-11-25 02:41 UTC, siwonkim0 commented on Calculator/Calculator/ViewController.swift
> +        let dot = "."
오 ~ 저렇게 따로 타입을 만들어서 관리하면 편할 것 같아요! 팀원들과 상의해본 결과 뷰에 표시되기는 하나 데이터의 모음일 뿐이기 때문에 Model에 CalculatorSymbol 파일을 만들어서 계산기에 필요한 값들을 관리해주기로 했습니다! 

그리고 콘이 들어주신 예시에서 `static let Dot` 로 대문자로 해주신 부분이 있습니다.
외부에서 사용시 case와 static let 의 모양이 CalculatorSymbol.Dot으로 동일해서 혼동의 여지가 있을 것 같다는 생각이 들기도 합니다!! 

소문자로 들어갈 경우 case로 혼동될 수 있기때문에 이렇게 해주신걸까요? 🧐

2021-11-25 03:18 UTC, jsim27 commented on Calculator/CalculatorUnitTests/ExperssionParserTests.swift
> +        sut = ExpressionParser.self
😅추가하여 커밋하겠습니다!

2021-11-25 03:19 UTC, siwonkim0 commented on Calculator/CalculatorUnitTests/CalculatorItemQueueUnitTests.swift
> +    var sut2: CalculatorItemQueue<Operator>!
operandQueueUnderTest, operatorQueueUnderTest 로 변경했습니다! 

그 이유로는, sut 는 system under test 의 약자인데, 그와 비슷하게 각각 테스트중인 operandQueue와 operatorQueue 라는 의미를 담기 위해서입니다.

2021-11-25 03:38 UTC, hwangjeha commented on Calculator/Calculator/ViewController.swift
> +        operandLabel.text = togglePlusMinus()
통일성을 맞추려면 insertDot 메소드 처럼 값을 바로 할당해 주는게 좋겠네요😊
이유를 생각해보니 이유 없이 그냥 작성된 코드네요😭
앞으로 이유있는 코드를 작성하도록 노력하겠습니다😊

2021-11-25 03:41 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +        let dot = "."
네네 개인적으로는 그러한 목적으로 대문자를 사용하는데, (상수의 느낌으로...?) 이건 개인 스타일이라고 생각해주시면 될 것 같아요!

2021-11-25 03:51 UTC, jsim27 commented
> 세 분이서 각자의 코드를 갖고 의견을 교환하며 설득을 하는 과정이 있었을텐데요. 어떤 과정으로 진행이 되었나요? 또한 어떤 부분이 가장 그 과정이 길었으며, 왜 유독 길었는지 궁금하네요!

개인 프로젝트의 step1, 2 파트는 주어진 UML이 동일했기에 구현 내용이 거의 비슷하여 PR메세지에 언급한 부분들에 대해서만 토의한 후 장점이 있는 코드를 선택하였고 그리 많은 시간이 걸리지 않았습니다. 
하지만 step3는 허황, 제인의 구현 방식과 나무의 구현 방식이 구조적으로 차이가 있었기에 많은 고민이 필요했어요. 그래서 이후 스텝에서 리팩토링을 통해 구조적 장점이 있는 나무의 디자인패턴을 적용해보기로 하고, 우선 이번 스텝에서는 제인과 허황의 구현 내용을 중심으로 병합하기로 했습니다.
제인과 허황의 코드를 합치는 도중 개인 프로젝트때 발견하지 못한 예외상황들이 발견되거나, 구현 방식의 차이 때문에 기존 구현내용을 수정하여 병합해야 하는 지점들이 많이 발견되어 시간이 많이 걸렸던 것 같습니다.

2021-11-25 03:51 UTC, hwangjeha commented
> 다시 말씀드리지만 델리게이트 패턴만이 정답은 아닙니다. 클로저를 넘겨줄 수도 있을거구요! 여러분들이 델리게이트 패턴으로 리팩토링하기로 결정한 계기가 궁금하네요.

델리게이트 패턴이 정답이라고 생각해서 델리케이트 패턴을 적용하려는 건 아닙니다😭
모둠원 중 델리케이트 패턴을 적용해본 캠퍼가 있고, 델리케이트 패턴에 대해서 이해가 부족한 캠퍼도 있습니다.
같이 델리케이트 패턴을 적용해보면서 델리케이트 패턴에 대해서 이야기 해볼 수 있는 좋은 기회라고 생각해서 델리케이트 패턴으로 결정했습니다😊

2021-11-25 04:01 UTC, siwonkim0 commented
충돌에 대한 원인을 생각해봤는데, `yagom-academy:4-hwangjeha` 브랜치는 이미 허황이 작업한 커밋들이 쌓여있는 상태이기 때문에 저희가 이번 모둠 프로젝트로 진행한 `hwangjeha:4-najahwang-group` 브랜치의 파일 구조와 전혀 다르기 때문에 일어난 충돌이지 않을까 생각해봤습니다. 

하지만 어떤 방식으로 충돌을 해결해야하는지는 잘 떠오르지 않습니다. 😱
도 와 주 세 요 ... ㅠ 😭

2021-11-25 06:37 UTC, merged

2021-11-25 06:37 UTC, protocorn93 commented
수고하셨습니다! @hwangjeha @siwonkim0 @jsim27