계산기(모둠) [STEP 2] 호댕, 숲재
yagom-academy/ios-calculator-app pull request #148
Opened 2021-11-25 02:04 UTC by yanghojoon

리뷰어: @GREENOVER 
안녕하세요 그린! 

호댕과 숲재 계산기(모둠) 프로젝트 스텝2 PR 제출드립니다.
3주간 꼼꼼하게 리뷰 잘 해주셔서 너무 감사드립니다! 🙏 

### 🤔 고민했던 것
#### 1️⃣ CalculatorItemQueue를 완전한 Double Stack 형태로 바꾸는 것에 대해 고민했습니다. 
기존에 코드에선 reversed()를 2번 실행하여 불필요하게 변수에 할당해주는 과정이 있었습니다. 
단순히 reversed()를 할 때에는 시간복잡도가 O(1)이지만, 다른 변수에 할당할 때에는 O(n)의 시간 복잡도를 가졌기에 reversed()를 해서 할당하는 과정을 최소화했습니다. 

``` swift=
mutating func dequeue() -> Element? {
    if dequeueStack.isEmpty {
        dequeueStack = enqueueStack.reversed()
        enqueueStack.removeAll()
    }
        
    return dequeueStack.popLast()
}
```

#### 2️⃣ 피연산자가 음수이고 연산자가 +/- 일 경우 연산자와 피연산자를 수정하는 방법에 대해 고민했습니다. 
- "1 - -5" -> "1 + 5"
- "3 + -2" -> "3 - 2"

위 예시처럼 피연산자가 음수일 경우 연산자와 피연산자를 수정하는 것이 UI에 올라갔을 때 더욱 깔끔하다고 판단했습니다. 
따라서 `convertOperatorAndNegativeOperand` 메서드를 따로 생성하여 `hasPrefix`를 활용해 피연산자가 음수인지 확인 후 연산자와 피연산자를 처리해주도록 구현했습니다. 

#### 3️⃣ 기존에 `=` 연산자 버튼을 눌렀을 때 발생하는 오류에 대해, Alert를 통해 처리를 해주도록 고민했습니다.  
기존에는 `OperationError.devidedByZero` 오류가 발생할 때에만 에러 처리를 해주었고 다른 오류에 대해선 에러 처리를 해주지 않고 있었습니다. 
따라서, 에러 메세지를 호출하는 Alert를 생성하여 각 에러에 맞게 Alert가 호출되도록 구현했습니다. 

### ⛔️ 해결하지 못한 것
#### `formulasStackView.arrangedSubviews.forEach { $0.removeFromSuperview() }`의 시간복잡도를 줄일 수 있는 방법에 대해 궁금합니다. 
`formulasStackView.arrangedSubviews.forEach { $0.removeFromSuperview() }`의 경우 시간 복잡도가 O(n)으로 배열이 가지고 있는 요소가 많아질수록 성능 상으로 떨어지는 방법이라 생각합니다. 

하지만 다른 방법을 찾지 못했습니다.. 😢 
혹시 조언을 주실 부분이 있으신지 궁금합니다. 

---
이번 주도 잘 부탁드립니다🙏🏻 좋은하루 되세요👍

2021-11-25 09:20 UTC, GREENOVER requested changes
@yanghojoon @forestjae 
호댕 숲재 마지막 스텝까지 고생 많으셨습니다..!
리팩토링을 통해 더 견고해지고 개선된 앱이 정말 눈에 띄네요🙌
이번주만 지나시면 방학이시군요ㅋㅋ
남은 2일 화이팅해서 유종의 미를 거두어 봐요!🙏🏻
***
### 칭찬드리고 싶은 부분
- 끝까지 부지런히 프로젝트를 맡은 기한에 완수해내신 점 💯
- 리팩토링을 통해 더 나은 네이밍과 코드 구조를 개선해내신 점 💯
- 기능적으로 더욱 보완되어 어엿한 계산기가 된 점 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. CalculatorItemQueue를 완전한 Double Stack 형태로 바꾸는 것에 대해 고민
- 오.. 저도 두분의 코드를 합치면서 놓쳤던 부분이였던것 같은데 리팩토링을 통해 더 고민해보시고 나은 방향으로 발전을 시켜주셨군요👍
제 직무유기인것같아 죄송스럽기도 합니다..😅
고민에 대한 답을 찾으신것 같아 더 드릴 말씀은 없네요..! 시간복잡도를 고려해서 매번 코드를 구성하기가 힘들지만 정석대로 잘 해주시고 계시네요!
이대로 화이팅입니다ㅎㅎ
2. 피연산자가 음수이고 연산자가 +/- 일 경우 연산자와 피연산자를 수정하는 방법에 대해 고민
- hasPrefix를 사용하여 판단해주고 변경해주신점 아주 나이스합니다.
이견은 없지만 아주아주 마이너하게 리뷰로도 간단히 코멘트를 남겼지만 메서드 네이밍에 대해 조금 더 개선되면 어떨까? 라는 작은 의견이 있습니다.
3. Alert를 통한 에러 처리
- 사용자에게 에러라는걸 얼럿으로 세세히 알려주시려는 노력과 구현 잘 보았습니다..!
다만 하나 궁금한게 현재 코드에서 어떤 상황에서 저 얼럿이 노출되게 되나요?
두분에선 얼럿이 정상적으로 노출되는지 어떻게 테스트 해보셨을지 궁금합니다🧐
***
### 해결하지 못한 부분에 대한 저의 의견
- 우선 스택뷰 안 요소들을 반복을 통해 삭제하지 않고 한번에 removeAll하는 방법은 현재로썬 저도 잘 모르겠습니다😅
removeAll을 익스텐션으로 직접 구현해낼수도 있지만 결국 내부구현은 반복을 돌며 스택뷰 안 요소들을 제거해주기에 별 의미없다고 생각하고..
저도 간단히 생각해봤지만 레이블들을 담은 스택뷰 자체를 제거하고 다시 생성해주는 방법은 어떨까 싶었습니다.
그렇지만 그게 더 나은 방식인지 그렇게 함으로 더 고려해야할 사항이 오버엔지니어링이 아닌지에 대해서 확실히 맞다고 확답을 드릴 수가 없네요ㅠ
음.. 이게 MVC를 사용하다보니 조금 국한된 문제이기도 한데 아키텍쳐적으로 구조를 바꿔 뷰모델을 사용하면 해결이 되지 않을까 싶습니다만 본질적으로 다시 원점으로 돌아와 두분의 코드에서는 현재 저는 저 방법이 최선이라고 보였습니다.
아키텍쳐적 한계이기도 하다고 느껴졌으며 시간복잡도를 여기서 이정도까지 고려해야하는지에 대해 너무 오버엔지니어링이 되지 않을까란 생각도 있습니다.
위에서 말씀드렸듯 레이블들을 담은 뷰 자체를 생성/제거를 통해 하는 방법은 어떠신가요?
문제가 있을수 있지만 그 과정에서 어떤 문제가 있으며 어떤 차이가 있고 어떤게 더 나은 방향일지 탐구해보는 좋은 계기가 될 수 있을것 같아요🙋🏻
***
두분 다시한번 고생많으셨어요..!
몇가지 코드 리뷰 코멘트를 남겨보았습니다.
그중에 하나는 불필요 파일이 흘러 들어간것 같아 보여 우선 Request Changes로 상태를 전환하겠습니다..!
그 부분외에 수정하고 싶으신 부분이 있다면 수정하셔도 됩니다.
변경이 되면 재 리뷰 요청 부탁드리겠습니다🙏🏻

2021-11-25 09:20 UTC, GREENOVER commented on Calculator/CalculatorTests/ListTests.swift
> +class ListTest: XCTestCase {
요 파일은 왜 있는건지 궁금합니다🙋🏻
실제로 Xcode 실행 시 파일이 들어있지 않기에 잘못 흘러들어온 파일이라는 느낌이 드네요..!?

2021-11-26 05:07 UTC, yanghojoon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +
앗.. 이 부분은 확인을 못했었네요! 불필요한 띄어쓰기는 삭제했습니다.

2021-11-26 05:13 UTC, yanghojoon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +                                                                          operand: operand)
함수를 호출하는 부분이 한 줄에 작성될 수 없기 때문에 말씀해주신 컨벤션이 적합할 것 같네요! 수정 완료했습니다~

2021-11-26 05:21 UTC, forestjae commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private func convertOperatorAndNegativeOperand(`operator`: String,
해당 메소드는 피연산자가 음수일때 연산자와 피연산자를 적절히 변환해 주는 기능을 합니다(덧셈, 뺄셈 연산에서). 처음에는 convertOperatorAndOperandWhereNegativeOperand 라고 이름을 지었었는데, 너무 장황한것 같아서 최대한 핵심적인 요소만을 뽑아내어 이렇게 네이밍을 하게 되었습니다. 저희 생각에도 좀 더 명확하고 간결한 네이밍이 있을 것 같은데 고민해도 답이 나오지 않았습니다ㅠㅠ

2021-11-26 05:26 UTC, yanghojoon commented on Calculator/Calculator/Model/Formula.swift
> +        }
이 부분은 피연산자만 남아있을 경우 정상적인 계산식이 아니기 때문에 만들어 놓은 구문입니다. 

따라서 반복문을 통해 계산을 하고 피연산자가 남아있지 않은 경우에만 결과를 리턴할 수 있도록 구현했습니다. 

이 때 if-else 구문을 사용하는 것보다, guard 문을 사용하여 피연산자가 비어있지 않은 경우 빠른 종료를 하는 것이 목적이므로 guard 문을 사용했습니다.

2021-11-26 05:28 UTC, yanghojoon commented on Calculator/CalculatorTests/ListTests.swift
> +class ListTest: XCTestCase {
삭제가 제대로 되지 않았었군요! 이 부분은 삭제하여 다시 push 했습니다.

2021-11-26 05:41 UTC, forestjae commented
### Alert이 호출되지 않는 점

말씀하신 바와 같이, 현재 계산기 앱을 동작하는 과정에서 Alert을 띄우는 에러가 발생할 수 없습니다. VC에서 해당 에러가 발생할 수 있는 경우를 사전에 차단하고 있기 때문입니다. 다만 추후에 계산기의 기능이 추가되어 또 다른 에러가 발생할 수 있기 때문에 미리 구현 해 두었습니다. 

### StackView

현재 구현된 방식인 `forEach` 와 `removeFromSuperView`를 통하여 삭제하는 것보다 새로운 StackView의 인스턴스를 만들어 할당하는 것이 더 비용이 클 것이라고 생각하여, 그대로 두었습니다.

2021-11-26 06:06 UTC, GREENOVER approved these changes
@forestjae @yanghojoon 
고생 많으셨습니다!
수정사항들 확인했습니다🙌
정말 마이너마이너하지만 궁금한건 Alert을 아직 사용하진 않더라도 임의로 구현 시 로직을 태워 띄워보았을까요?
그런 부분들이 있었는지 궁금해요.
없었다면 필요할것 같아서요.
코드상 문제는 전혀 없지만 그래도 정상적으로 노출되는지 구현 시 단위 테스트로 확인해본다면 좋을것 같네요!
그 외에 더 수정될 부분은 없어보이고 또한 오늘이 마지막 날이군요..!
3주간 계산기와 싸우시느라 고생많으셨습니다☺️
방학 알차게 푹~ 쉬세요🙌

2021-11-26 06:06 UTC, merged