계산기(모둠) [STEP 2] Nicholas, Ari
yagom-academy/ios-calculator-app pull request #149
Opened 2021-11-25 03:28 UTC by leeari95

@corykim0829

@Kim-EunsooSilver @leeari95

안녕하세요. 코리~ 😊
STEP 2 에서 리팩토링 진행하고 PR 올려드립니다. 
리팩토링 과정중에 고민했던 부분과 수정하였던 부분을 상세히 적어보았습니다.
이 외에 혹시 부족한 점이 있다면 피드백 부탁드립니다! 😁

## 고민했던 것

- 코딩컨벤션에 맞게 파일이름 수정, 줄바꿈, 공백 기타 등등을 수정했습니다.
- 이전에 오작동하던 버그들을 찾아보면서 고쳐보았습니다.
    - `0` > `.` 을 누르면 `00.` 이 입력되는 부분 개선
        - 예상하는 결과 > `0.`
    - `2`, `5` > `.` 을 누르면 `025.` 이 입력되는 부분 개선
        - 예상하는 결과 > `25.`
    - `1` > `-` 를 누르면 `-01` 이 입력되는 부분 개선
        - 0이 추가로 앞에 생기는 부분 삭제가 필요
- 불필요한 파일 (LinkedList, calculatorHistoryUILbel) 삭제
- 계산기가 동작하지 않을 때 왜 동작하지 않는지 log가 나타나도록 추가해보았습니다. 사용자에게는 보여주지 않아도 되는 설명을 프로그래머는 볼 수 있도록 구성해보았습니다.

## 궁금했던 것 / 조언이 필요한 부분

- 해당 조건문이 너무 길어져서 가독성이 좋지 못하다는 생각이 들어서 변수에 대입하여 작성해주려고 했었는데, 이름을 명확하게 지으려다 보니까 네이밍이 길어지는 상황이 발생해서 결국엔 개선하지 못했습니다.
    
    ```swift
    guard rawOperand != "0" || InputedNumber != "0",
          rawOperand != "0" || InputedNumber != "00" else {
        return
    }
    ```
    
    해당 조건문의 역할은 현재 레이블이 `0`이 아니면서 터치한 버튼의 숫자가 `0` 혹은 `00`이 아니여야 통과하는 guard문입니다. 
    저희가 마지막으로 고민했던 길~었던 네이밍은 `isNotCurrentLabelZeroAndButtonTextZero` 였는데요. 혹시 코리의 의견은 어떠신지... 또 이 부분에 대한 조언도 부탁드립니다!
    
- 쌓여있는 계산식이 없는 상태에서 equal 버튼을 터치한다면 에러처리를 주어 log를 찍게 해주려고 했었습니다. 그러나 로직 상 에러처리 전에 작업하는 동작들이 에러가 나게 된다면 불필요해지는 작업들(예시: 쌓여있는 계산식이 없는데 에러처리 이전에 현재 레이블을 계산식에 추가하는 경우 다시 추가했던 계산식을 삭제해주기 위해 `clearAll()`메소드를 호출해주어야하는 상황)이라서 비효율적인 로직이 되는 상황이 와서 아래와 같이 guard문에 log를 추가해주는 형식으로 바꾸어 개선해주었습니다.
    
    ```swift
    guard calculationHistoryStackView.arrangedSubviews.count > 0 else {
        os_log(.error, log: .error, LogMessage.canNotCalculate)
        return
    }
    ```
    
    에러핸들링으로 log를 찍고 싶었지만 로직 자체를 바꿔주어야 하는 상황이 와서 포기했는데요. 이런 경우에 코리는 로직자체를 바꿔주시는 편인지... 궁금합니다.

2021-11-26 13:53 UTC, corykim0829 requested changes
수고 많으셨습니다 니콜라스, 아리!! 😀

### 궁금했던 것 / 조언이 필요한 부분

> 해당 조건문이 너무 길어져서 가독성이 좋지 못하다는 생각이 들어서 변수에 대입하여 작성해주려고 했었는데, 이름을 명확하게 지으려다 보니까 네이밍이 길어지는 상황이 발생해서 결국엔 개선하지 못했습니다.

고민하셨던 네이밍이 더 혼란을 초래할 수도 있을 것 같아서 더 깔끔한 로직을 만드는게 좋을 것 같습니다! 이 부분은 리뷰로 제가 적어두었습니다!

> 쌓여있는 계산식이 없는 상태에서 equal 버튼을 터치한다면 에러처리를 주어 log를 찍게 해주려고 했었습니다.

이 부분은 잘 구현하신 것 같아요. 비효율적인 로직이 된다는게 어떤 걸 말하시는지 현재 글만 봐서는 잘 이해가 되지 않네요 🥲

이번 스텝에서 리팩토링하시면서 테스트도 확인하면서 하셨는지 궁금합니다 😀
--- 

제가 몇가지 테스트해보니, 소수점 오류가 아직 몇개 남아있는 것 같더라구요!
이 부분 여유가 되시면 한번 확인해보시면 좋을 것 같아요!

<img width="360" alt="image" src="https://user-images.githubusercontent.com/34022757/143589421-0f276fb6-f46c-4e28-bf3e-e3ffb47ceea9.png"> <img width="360" alt="image" src="https://user-images.githubusercontent.com/34022757/143589444-b6eafad3-2274-4bab-9531-25358f3a430a.png">

2021-11-26 13:53 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
>      func resetCalcurator() {
이 부분 함수명이 오타가 있네요!

2021-11-26 13:53 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let InputedNumber = sender.titleLabel?.text else {
소문자로 시작해야할 것 같아요!
개인적으로는 inputNumber라고 하면 더 깔끔할 것 같네요 😀

2021-11-26 13:53 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
조건이 많이 필요한 로직이니 어쩔 수 없는 부분이라고 생각합니다.
guard로 해서 더 읽기 어려운 로직이 나온 것 같기도 하네요 if를 쓰면 더 읽기 쉽게 처리가 될 것 같아요! 꼭 guard를 써야하는건 아니니까 참고하세요! 😀

2021-11-26 13:53 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            os_log(.error, log: .error, LogMessage.resetNaN)
os_log사용하셨군요! 좋네요.!

2021-11-26 13:53 UTC, corykim0829 commented on Calculator/Calculator/Model/LogMessage.swift
> +enum LogMessage {
로그 메세지를 상수처리한 부분 좋습니다 👍

2021-12-03 06:17 UTC, leeari95 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
```swift
        if rawOperand == "" {
            if inputedNumber == "0" || inputedNumber == "00" {
                return
            }
        }
```
안그래도 저 조건문을 초반에 위 if문으로 작성을 하였는데, 이중 if문으로 들어가게 되서 나머지 조건문들도 모두 guard문으로 되어있기 때문에 통일성을 주고자 guard문을 사용하기로 하였었습니다. 또한 메소드를 빠져나가는 형태는 주로 guard문을 많이 사용한다고 피드백을 받았던 기억이 있어서 if문 보다는 guard문이 더 적절하다고 판단되었어요.
코리 말씀처럼 조건이 많이 필요한 로직이고, 또 좋은 변수명이 생각이 나지 않기 때문에 그대로 두어도 문제없겠다는 판단이 들었습니다.
혹시 코리의 생각은 어떠신가.. 궁금합니다!

2021-12-03 06:26 UTC, leeari95 commented
코리가 의견 주신 부분은 다 반영하여 수정해보았습니다. 😊
수정한 부분은 아래와 같습니다.
* 소수점 오류 있었던 부분 수정
* 메소드명과 변수명 오타를 수정

더 궁금한 점은 [코멘트](https://github.com/yagom-academy/ios-calculator-app/pull/149#discussion_r761672546) 추가로 남겨드렸습니다! 감사합니다!

2021-12-31 08:31 UTC, closed without merging