계산기 (모둠) [STEP 2] 차차, 릴리
yagom-academy/ios-calculator-app pull request #152
Opened 2021-11-25 07:56 UTC by ChaminLee

안녕하세요 코리! @corykim0829 
계산기(모둠) Step 2의 리팩토링을 마쳐서 PR 보내드립니다. 
전반적인 변경사항은 아래에 정리해두었습니다!
이번에도 끝까지 잘 부탁드립니다😀

---

## Model 

### LinkedList tail 구현

기존 LinkedList `appendNode` 메서드의 시간 복잡도가 `O(n)`이라는 것을 확인하고, LinkedList의 끝 노드를 항상 가지고 있는 `tail` 프로퍼티를 만들어주어 이를 해결하고자 했습니다. `head`만 있었을 때는 노드의 개수만큼 끝까지 이동해야했으나, `tail`을 참조하여 바로 다음 노드에 새로운 노드를 할당하는 방식으로 리팩터링을 진행했습니다. 

## View

### `required init(coder: )` 내 메서드

기존에 `required init(coder: )`내에 기본적으로 제공해주는 `fatalError`를 사용했었으나, 이전에 주셨던 코멘트에 따라 앱이 최대한 종료되지 않는 쪽으로 수정하고자 `super.init(coder: )`로 대체하였습니다. 

## ViewController

### `CalculatorManager` 생성

기존 `CalculatorViewController`가 가지고 있던 UI와 관련이 없는 로직을 `CalculatorManager`에게 역할을 넘겨주도록 리팩터링했습니다. 
이에 최대한 핵심 로직은 `CalculatorManager`가 가지고 있게 만들어줌으로써 조금이나마 `CalculatorViewController`의 역할을 덜어줄 수 있었습니다. 

하지만 이에 따라 `CalculatorManager`가 뚱뚱해지는(?) 현상을 보게 되었는데, 이와 같은 현상이 자연스러운 것인지 궁금합니다!
우선 `CalculatorManager`를 만들어줌으로써 확장성, 가독성, 재사용성 등 많은 이점을 얻을 수 있다고 생각하여 따로 구현해주었습니다!

--- 

## 질문 

> 1. `CalculatorManager`는 어디에 속하는 걸까요?

`CalculatorManager`를 만들어주기는 했으나 Model인지, 아니라면 ViewController를 돕기에 Controller로 봐야하는지 궁금합니다!
생각해봤을 때, 계산을 하는 로직을 돕는다는 관점에서는 Model에 가까운 것 같고, 단편적으로 봤을 때 ViewController에서 필요로하는 기능을 덜어주었기 때문에 Controller에 가까운 것 같다고 정리를 해봤습니다... 

결국에는 결론을 내리지 못했는데, 주로 이런 타입은 어디에 속하는지 궁금합니다!

---

감사합니다!🙏🏻

2021-11-26 14:17 UTC, corykim0829 requested changes
수고 많으셨습니다 차차, 릴리!! 🙌

로직을 CalculatorManager로 분리시켜서 ViewController가 깔끔해졌네요 👍
거기다 CalculatorManager 태스트까지 꼼꼼하게 하셔서 인상적이였습니다 👍

하지만 아직은 ViewController에서 하는 일도 많이 남아있어서 조금 더 CalculatorManager 객체 내부에서 로직을 처리해서 값을 ViewController에게 전달해주면 더 좋은 코드가 될 것 같아요!

---

> 1. `CalculatorManager`는 어디에 속하는 걸까요?

코드를 봤을 때에는 Model 쪽에 속합니다!

---

그리고 머지가 안되는 부분은 사소한 conflict인데 이 부분도 어떻게 해결하면 좋을지 고민해보면 좋을 것 같아요! 작은 conflict라 해결해보는 것도 큰 의미가 있을 것 같네요 😀

2021-11-26 14:17 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        calculatorManager.initialize()
초기상태로 리셋해주는 건데, calculatorManager를 초기화한다는거는 조금 어색하네요. calculatorManager도 리셋한다는 의미로 가져가면 좋을 것 같아요!

2021-11-26 14:17 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        calculatorManager.initializeCurrentOperand()
이 부분도 calculatorManager도 reset하는 부분이니 함수명을 변경하는게 자연스러울 것 같아요!

2021-11-26 14:17 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorManager.swift
> +    private let limitedDigitsOfExpression = 20
상수처리 좋습니다 👍

2021-11-26 14:17 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorManager.swift
> +    mutating func doCalculate() throws -> Double {
그냥 calculate라고 하면 더 깔끔할 것 같습니다!

2021-11-26 14:17 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorManager.swift
> +    class Formatter: NumberFormatter {
이 formatter는 CalculatorManager의 extension으로 보기에는 formatter에 관한 정보여서 따로 파일을 만들어서 처리하면 좋을 것 같아요!

2021-11-26 14:17 UTC, corykim0829 commented on Calculator/Calculator/Controller/CalculatorManager.swift
> +    var currentOperandDouble: Double? {
double이라고 붙여서까지 값을 만들기 보다는 상위 객체에서 Double로 캐스팅하는게 더 깔끔할 것 같네요!

2021-12-05 06:34 UTC, ChaminLee commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        calculatorManager.initialize()
`initialize`라는 단어가 혼동이 될 수 있을 것 같아 `reset`이라는 키워드로 변경하였습니다.

2021-12-05 06:35 UTC, ChaminLee commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        calculatorManager.initializeCurrentOperand()
위와 마찬가지로 `reset` 키워드를 활용하여 변경하였습니다.

2021-12-05 06:38 UTC, ChaminLee commented on Calculator/Calculator/Controller/CalculatorManager.swift
> +    mutating func doCalculate() throws -> Double {
메서드명은 `calculate` 로 변경했습니다!

2021-12-05 06:48 UTC, ChaminLee commented on Calculator/Calculator/Controller/CalculatorManager.swift
> +    class Formatter: NumberFormatter {
따로 파일을 만들어 `Formatter` 클래스를 정의해주는 방식으로 변경했습니다.

2021-12-05 06:59 UTC, ChaminLee commented on Calculator/Calculator/Controller/CalculatorManager.swift
> +    var currentOperandDouble: Double? {
`NSString`으로 캐스팅한 뒤에 `.doubleValue`를 사용하여 변환해주는 방식과 `Double()`로 감싸는 것을 고민하다가 더 직관적인 후자의 방식을 선택하였습니다.

2021-12-05 07:01 UTC, ChaminLee commented
안녕하세요 코리! @corykim0829 

조금 늦게 피드백을 확인하고 개선하여 내용 남겼습니다! 
추가적으로 기존에 merge conflict가 나던 부분을 해결했고, `CalculatorManager`가 Controller 폴더에 있던 것을 Model 폴더로 옮겨주었습니다. 

계산기 프로젝트 3주간 꼼꼼하게 피드백주셔서 감사합니다!! 🙏🏻

2021-12-31 08:31 UTC, closed without merging