계산기 I [STEP 1] Lingo
yagom-academy/ios-calculator-app pull request #160
Opened 2022-03-15 04:34 UTC by llingo

안녕하세요 엘림 @lina0322 😃 
계산기 I [STEP 1] PR 보냅니다. 잘 부탁드립니다!

> 코딩 컨벤션은 스타일쉐어 가이드를 참고하였으며 탭 사이즈는 2입니다.

## UML
<img width="500" alt="스크린샷 2022-03-15 오전 10 31 59" src="https://user-images.githubusercontent.com/94151993/158294801-13c102dd-69b2-4f25-ab3e-e9c9bb0f9b8a.png">

## 고민 및 해결한 점
### 1. removeAll vs []
리스트를 직접 구현하기전에는 [Element] 배열을 사용하여 구현했었습니다. 그때 모든 원소를 삭제하는 방법으로 removeAll 메서드를 사용하거나 빈배열 [] 을 넣는 방법이 있었고 두 개의 차이가 무엇인지 궁금했습니다.
[StackOverFlow - Performance removeAll vs []](https://stackoverflow.com/questions/54133045/performance-array-removeall-vs) 를 참고한 후 [Swift - Array.swift](https://github.com/apple/swift/blob/ad50a39b120343f4827edb0a5a7013bb586306a6/stdlib/public/core/Array.swift#L1255)의 removeAll 구현 함수를 살펴보았더니 
만약, capacity를 유지하지 않으면 _Buffer() 를 할당해준다고 되어있었습니다. 
```swift
@inlinable
public mutating func removeAll(keepingCapacity keepCapacity: Bool = false) {
  if !keepCapacity {
    _buffer = _Buffer()
  }
  else {
    self.replaceSubrange(indices, with: EmptyCollection())
  }
}
```

_Buffer는 objc일 경우 _ArrayBuffer<Element>, 아닐 경우 _ContiguousArrayBuffer<Element> 의 타입 별칭이며 
_ContiguousArrayBuffer는 구조체로 선언되어있고 _ArrayBufferProtocol을 채택하고 있는 Array를 의미하여 결국 _buffer = _Buffer()는 새로운 Array를 넣어준다고 생각했고 capacity를 유지해야하는 경우가 아니라면 두 경우는 큰 차이가 없다고 이해했습니다.
```swift
#if _runtime(_ObjC)
@usableFromInline
internal typealias _Buffer = _ArrayBuffer<Element>
#else
@usableFromInline
internal typealias _Buffer = _ContiguousArrayBuffer<Element>
#endif
```

### 2. List를 직접 구현하는 과정에서 발생한 구조체 에러에 대해
직접 구현한 List의 Node를 구조체로 구현하려고 했을때 다음과 같은 에러가 발생했었습니다. 
```
Value type 'CalculatorNode<Element>' cannot have a stored property that recursively contains it
```
원인을 찾아보니 동적 메모리 영역인 힙을 사용하는 참조타입과 달리 구조체는 정적 메모리 영역인 스택만 사용하기 때문에 구조체는 컴파일 단계 에서 고정된 메모리 크기를 가지고 있어야하는데 Node 내부의 Node 내부를 프로퍼티로 가지게 되면 `Node[Node[Node[Node...` 로 무한한 크기를 가지게 되기 때문에 에러가 발생하는 것이었습니다. ([StackOverFlow - struct can't have stored property itself](https://stackoverflow.com/questions/53626802/struct-cannot-have-stored-property-that-references-itself-but-it-can-have-an-arr))

따라서, LinkedList는 구조체로 Node는 클래스로 `next` 프로퍼티를 통해 다음 Node를 참조하도록 구현했습니다.

### 3. UML 작성시 제네릭과 프로토콜의 관계 설정에 대해
각 타입의 제네릭 Element가 CalculateItem 프로토콜을 채택해야하는 상황인데 UML에서는 어떻게 그려야할 지 모르겠습니다.
저는 제네릭 Element의 데이터를 직접 담는 타입이 CalculatorNode의 data 프로퍼티이기 때문에 CalculatorNode에서 CalculateItem  프로토콜을 실체화 관계로써 작성했는데 엘림의 의견은 어떠한지 궁금합니다!

### 4. TDD를 처음 진행하면서 고민되었던 사항
**LinkedList의 front와 rear가 같은 인스턴스를 참조하는지 확인**하는 테스트를 작성하고 이를 통과하도록 구현하는 과정에서 front와 rear를 `internal`로 설정 했었는데 이후 리팩토링 과정에서 front와 rear를 `private`로 외부에서 접근을 못하도록 감춰야 된다면 위의 테스트 코드는 실패하게됩니다. 
이럴때 구현했던 테스트코드를 제거하는 것인지 `private(set)`을 사용해 front와 rear 프로퍼티를 `읽기전용`으로 변경하더라도 테스트 코드를 살려둬야하는지 궁금합니다. 저는 이번 PR에서는 `private(set)`으로 `읽기전용`으로 변경하여 테스트코드를 제거하지 않았습니다.

### 5. 기타
테스트 코드에서 테스트 함수에 `private`를 설정하면 테스트가 진행되지 않는다는 것을 모든 테스트 함수에 적용한 후에 알았습니다 🥲

2022-03-16 10:34 UTC, lina0322 requested changes
안녕하세요, 링고! 반갑습니다~
이번 프로젝트 함께 힘내보아요!
서로 많은 것을 배울 수 있는 시간이 되었으면 좋겠습니다🙏

---

고민하고 해결한 부분이 상당히 인상깊었어요.
다양한 시도를 해보시고, 깊게 파보려고 노력하신 부분이 정말 좋았습니다!!
(#이 뭔가 궁금했는데 하단에 적어주셔서 의문이 해결되었네요. 적절하게 표현한 것 같아요😁)

다른 부분은 전부 잘 되어가고 있다는 생각이 들었는데요.
private 관련해서는 글 3개를 준비헤봤어욯ㅎㅎㅎ(어떤걸 좋아할지 몰라서😉)

제가 얘기하는 것도 좋지만, 다른 사람들은 어떻게 생각하고 어떻게 해결해 나갔는지 보여주고 싶어서
다양한 방향으로 준비해봤으니, 읽어보시고 또 의견 주시면 좋을 것 같습니다!

[첫번째 글](https://cocoacasts.com/how-to-unit-test-private-methods-in-swift)
[두번째 글](https://www.avanderlee.com/swift/testing-private-methods-variables)
[세번째 글](https://digitalbunker.dev/how-to-test-private-methods-variables-in-swift)

---

추가로 전체적인 코드가 매우 깔끔했어요. 앞으로가 기대되는 코드였습니다.

다만 Test 코드 부분이 조금 아쉬웠는데요. 
많이 테스트 하는 것도 중요하지만, `어떤걸` `왜` `어떻게` 테스트 해야하는지를 생각해보면 좋을 것 같아요.

혹시 링고가 지금 만든 모든것을 반드시 테스트해야한다고 생각하고 있거나, 
테스트 개수가 많으면 좋다고 생각하고 있다면... 
제가 드린 글을 다시 한 번 읽어보고, 동료들과 또 저와 얘기를 다시 나누는 것도 좋겠어요😁

이해 안 가거나 궁금한 것 있으면 편하게 디엠주시고, 수정 완료되면 마찬가지로 메세지 남겨주세욥! 🙇🏻‍♀️

2022-03-16 10:34 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  }
nil값이 포함될 수 있는 배열로 한 이유가 있나요?😀

2022-03-16 10:34 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  }
extension에서 init을 생성해주는 것과 어떤 차이가 있을까요?☺️

2022-03-16 10:34 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  mutating func enqueue(_ data: Element) {
mutating은 어떤 키워드인지 알고있나요??

2022-03-16 10:34 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +    guard self.isEmpty == false else {
여기서 self가 비어있지 않다는 것은 어떤것을 뜻하나요?🧐

2022-03-16 10:34 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorLinkedList.swift
> +  }
count가 음수가 되는 경우가 발생할 수도 있을까요?🧐

2022-03-16 10:34 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorLinkedList.swift
> +    var curr = self.front
curr은 어떤 의미로 사용되었나요?

2022-03-16 10:34 UTC, lina0322 commented on Calculator/Calculator/Presentation/ViewController.swift
> -        // Do any additional setup after loading the view.
사용하지 않는 코드를 지우는 것은 아주 좋은 습관입니다!
여기 작업 시작할때에는 ViewController에도 예쁜 이름을 지어줘볼까용?!😎

2022-03-16 10:34 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +final class CalculatorItemQueueTests: XCTestCase {
final은 어떤 키워드인가요?🙃

2022-03-16 10:34 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +  private var sut: CalculatorItemQueue<Double>!
sut, mock 등의 용어 차이를 알고있나요? 또 Double을 선택한 이유도 궁금해요🎉

2022-03-16 10:34 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +    XCTAssertTrue(self.sut.front?.next === self.sut.rear)
하나의 함수 안에서 너무 많은 것을 테스트하고 있지는 않은지 한번 생각해볼까요?😀

2022-03-16 10:34 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +  }
`test_first_리스트가_비어있을때`가 조건인데 `XCTAssertTrue(input)`로 함께 테스트 되는 이유가 있나요?
약간 dependency가 있어보이는데요🙃

2022-03-16 10:34 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +  }
리스트가 비어있지 않을때를 테스트하고 있는건가요..?🥲

2022-03-16 11:34 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  }
curr 변수에 맨 앞 노드를 옵셔널로 넣어줬고 반환할 배열에 넣어줄 때 `curr?.data`로 `nil`이 될 가능성이 있었기 때문에 **nil 값이 포함될 수 있는 배열** `[Element?]` 로 구현했었습니다. 
```swift
func allElements() -> [Element?] {
  var result: [Element?] = []
  var curr = self.front
  while curr != nil {
    result.append(curr?.data)
    curr = curr?.next
  }
  return result
}
```

리팩토링 과정에서 `while let`으로 옵셔널 바인딩하여 `[Element]`으로 반환하도록 변경하였습니다. 또한, curr 라는 변수의 네이밍이 current 라는 의미를 가지고 있지만 줄임말은 좋지 않은 네이밍이라고 생각하여 current로 변경하였고 바인딩한 상수는 node로 네이밍을 변경했습니다!

2022-03-16 12:06 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  }
기존의 직접 구현한 생성자를 `extension`에서 생성하더라도 멤버와이즈 생성자와 커스텀 생성자가 같아져버리기 때문에   
```swift
// 기존
init(list: CalculatorLinkedList<Element> = CalculatorLinkedList<Element>()) {
  self.list = list
}

// 개선
private(set) var list: CalculatorLinkedList<Element> = .init()
```
list를 private(set)으로 외부에서 변경을 할 수 없도록 수정하였고 기본 값으로 `.init()`을 해주어 멤버와이즈 생성자를 사용할 수 있도록 변경하여 기존 커스텀 생성자의 목적이었던 생성자 주입도 가능하도록 했습니다.

2022-03-16 12:44 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  mutating func enqueue(_ data: Element) {
클래스와 달리 구조체는 값 타입이기 때문에 
만약, 구조체의 인스턴스를 `let`으로 선언하게 되면 해당 인스턴스는 **상수**로 인스턴스를 생성했는지 **변수**로 인스턴스를 생성했는지 알 수 있는 방법이 없기 때문에 기본적으로 구조체는 메서드 내부에서 프로퍼티를 변경할 수 없도록하고 있습니다.

하지만, `mutating` 키워드를 사용하게 되면 **메서드 내부에서 프로퍼티를 변경할 것을 알 수 있게 되고 선언할 때 변수로 선언할 것을 보장할 수 있게되므로 해당 메서드가 끝나는 시점에서 프로퍼티의 수정된 복사된 인스턴스로 대체**하게 됩니다.

2022-03-16 12:49 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +    guard self.isEmpty == false else {
큐가 비어있지 않다는 뜻이지만 `self.isEmpty` 보다는 큐가 가지고 있는 리스트가 비어 있다는 의미로 `self.list.isEmpty`가 더 적절할 것 같습니다!

2022-03-16 13:17 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorLinkedList.swift
> +  }
테스트 코드를 작성해서 확인해본 결과 음수가 되는 것을 확인했습니다 😅
```swift
mutating func removeFirst() -> Element? {
  guard let front = self.front else {
    return nil
  }
  let data = front.data
  self.front = front.next
  self.count -= 1
  return data
}
```
guard 문을 사용하여 front 가 `nil`일 경우 종료하도록 개선했습니다!

2022-03-16 13:19 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorLinkedList.swift
> +    var curr = self.front
curr은 current 노드를 의미했었지만 줄임말은 좋지 않은 네이밍인 것 같아 current 로 변경했습니다!

2022-03-16 13:37 UTC, llingo commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +  private var sut: CalculatorItemQueue<Double>!
**sut** 은 `System Under Test`의 약자로 테스트를 진행할 타입을 의미하며 **Mock**은 `Mock 객체` 가짜 객체를 의미합니다!

이번 계산기 I 프로젝트는 실수 값을 다루기 때문에 Double을 선택했습니다.
이후 STEP에서는 연산자를 담는 큐, 피연산자(값: Double)을 담는 큐로 사용하게 될 것 같습니다!

2022-03-16 13:42 UTC, llingo commented on Calculator/Calculator/Presentation/ViewController.swift
> -        // Do any additional setup after loading the view.
`CalculatorViewController` 로 변경했습니다! 👍

2022-03-16 14:11 UTC, llingo commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +    XCTAssertTrue(self.sut.front?.next === self.sut.rear)
전반적으로 구현한 테스트 코드들 하나하나가 너무 많은 것을 테스트하고 있는 것 같습니다 🥲

2022-03-16 14:15 UTC, llingo commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +  }
각 테스트 코드가 실행되기전 `setUpWithError()`에서 sut 변수에 인스턴스를 새로 초기화해주기 때문에 
`//given`에서 아무 것도 하지 않는다면 결국 빈 리스트와 같은 것이지만 해당 사실을 생각하지 못했던 것 같습니다.

2022-03-16 15:04 UTC, llingo commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +  }
테스트 코드를 리팩토링하면서 
```swift
XCTAssertTrue(output)
```
보다
```swift
XCTAssertEqual(output, true)
```
로 작성하는 것이 더 가독성이 좋을 것 같다고 생각해서 수정했는데 엘림의 의견은 어떠한지 궁금합니다 🙂

2022-03-17 10:41 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  mutating func enqueue(_ data: Element) {
> 만약, 구조체의 인스턴스를 let으로 선언하게 되면 해당 인스턴스는 상수로 인스턴스를 생성했는지 변수로 인스턴스를 생성했는지 알 수 있는 방법이 없기 때문에 기본적으로 구조체는 메서드 내부에서 프로퍼티를 변경할 수 없도록하고 있습니다.

인스턴스를 var로 선언하면 mutating이 필요없나요?👀

2022-03-17 10:49 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +  }
가독성 측면이라면, 사실 저는 `XCTAssertTrue(output)`가 더 좋은 것 같아요ㅎㅎㅎ (이런건 약간 개인 취향이니까?)
그런데 이 두 케이스는 실패했을 때 보여지는 문구가 다르죠.
어떤걸 쓰는 쪽이 더 테스트하기 편할까요?😀
<img width="767" alt="스크린샷 2022-03-17 오후 7 47 50" src="https://user-images.githubusercontent.com/49546979/158793222-8c981b4c-b028-4a24-85c0-b7c15ef4419d.png">

2022-03-17 10:54 UTC, lina0322 approved these changes
링고! 이번 스텝 고생 많았습니다.
아주 조금 수정할게 남았지만, 다음 스텝도 해야하니까 여기서 머지하고!
제가 달아들인 코멘트에 대한 것들이나 추가 수정은 다음 스텝에서 함께 해주시면 감사하겠습니다~🙏

추가로 테스트 케이스가 성공하는 경우만 있는데요.
`실패하는 경우`에 대한 테스트도 한번 진행해보면 좋겠어요:)

이번 스텝 고생하셨습니다!!

2022-03-17 10:54 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
> list를 private(set)으로 외부에서 변경을 할 수 없도록 수정하였고 기본 값으로 .init()을 해주어 멤버와이즈 생성자를 사용할 수 있도록 변경하여 기존 커스텀 생성자의 목적이었던 생성자 주입도 가능하도록 했습니다.

링고의 `생성자 주입`은 어떤걸 의미한 걸까용?😀

2022-03-17 10:54 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorLinkedList.swift
> +  private(set) var count = Int.zero
`.zero`도 가능할까요?🧐

2022-03-17 10:54 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorLinkedList.swift
> +    while let node = current {
LGTM💕

2022-03-17 10:54 UTC, lina0322 commented on Calculator/Calculator/Resource/Base.lproj/Main.storyboard
> +                <viewController id="BYZ-38-t0r" customClass="CalculatorViewController" customModule="Calculator" customModuleProvider="target" sceneMemberID="viewController">
오, ViewController의 이름을 변경할 때 rename으로 했나요?👍

2022-03-17 10:55 UTC, merged

2022-03-17 11:29 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
생성자 주입은 의존성을 외부에서 주입하는 방법 중 하나입니다. 
의존성 주입하는 방법에는 대표적으로 1. 프로퍼티 주입, 2. 메서드 주입, 3. 생성자 주입의 방법이 있고 이 중 **생성자 주입**은 해당 타입의 인스턴스가 생성할 때 생성자를 통해 의존 관계에 있는 인스턴스를 넣어주어 두 객체 간의 결합도를 낮추는 방법입니다. 

> 이러한 의존성 주입을 통해 테스트가 용이해지고 유지보수 및 재사용성 향상, 결합도(Coupling)을 줄일 수 있습니다.

2022-03-17 11:32 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorLinkedList.swift
> +  private(set) var count = Int.zero
타입을 명시해준다면 사용이 가능할 것 같습니다!
```swift
private(set) var count = Int.zero
```

front, rear 프로퍼티는 타입을 명시해줬기 때문에 아래와 같이 리팩토링하는 것이 좋을 것 같습니다.
```swift
private(set) var count: Int = .zero
```

2022-03-17 11:32 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
음.. 그럼 지금 저 12번째 라인이 생성자 주입으로 의도한건가요....?🤔

2022-03-17 11:33 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorLinkedList.swift
> +  private(set) var count = Int.zero
타입을 명시 하고, 안 하는 것에 링고만의 기준은 무엇인가요?!😃

2022-03-17 11:34 UTC, llingo commented on Calculator/Calculator/Resource/Base.lproj/Main.storyboard
> +                <viewController id="BYZ-38-t0r" customClass="CalculatorViewController" customModule="Calculator" customModuleProvider="target" sceneMemberID="viewController">
코드에서만 변경해주게되면 해당 ViewController 클래스를 참조하고 있던 다른 파일에서 변경되지 않는 문제가 생기기 때문에 `rename`을 사용해서 변경했습니다 👍

2022-03-17 11:35 UTC, llingo commented on Calculator/CalculatorTests/CalculatorLinkedListTests.swift
> +  }
`XCTAssertTrue` 쪽이 실패 문구가 더 보기 좋은 것 같아요 😃

2022-03-17 11:45 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue.swift
> +  mutating func enqueue(_ data: Element) {
`var`로 선언해도 `mutating`이 필요합니다

Swift는 일반적으로 값을 복사할 때 `COW(Copy on Write)` 방식을 사용하게 됩니다. 즉, 실제 복사는 값이 변경될 때 복사가 됩니다. 만약, 구조체 메서드 내부에서 값을 변경하게되면 컴파일러는 알 방법이 없어 `mutating` 키워드를 사용하여 내부에서 값을 변경한다는 것을 컴파일러에게 알려주게 됩니다.

2022-03-17 11:55 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
네! 외부에서 다른 리스트를 주입하지 않는다면 기본값을 통해 사용할 수 있도록 했습니다.
하지만, 큐는 주입할 필요가 없는 것 같습니다 😅

2022-03-17 12:00 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
음, 저 잘 이해가 안가는데요. 
`private(set) var list: CalculatorLinkedList<Element> = .init()`이면
list가 밖에서 주입이 되는게 아니라, 내부에서 생성되는 것인데.. 어떻게 생성자 주입이 될 수 있는걸까용??😅

[의존성 관련한 글](https://lena-chamna.netlify.app/post/dependency_injection)을 한 번 같이 볼까요..?!
혹시 제가 링고의 의도를 잘 파악하지 못하고 있나요😭

2022-03-17 12:04 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorLinkedList.swift
> +  private(set) var count = Int.zero
만약, 메서드 내부에 `var result: [Element] = []` 와 같이 추후에 append 해서 담아주기 위해 타입 명시가 필요한 경우나 코드의 가독성에서 필요하다고 생각될 때 해주었고 `var count = Int.zero` 나 `var count = 0` 과 같이 타입을 명시할 필요가 없는 경우 안해 주었던 것 같습니다.

아직 애매모호한 상황이라서 이번 기회에 기준을 잡아야될 것 같습니다 👍

2022-03-17 12:06 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorLinkedList.swift
> +  private(set) var count = Int.zero
이미 알고 있겠지만, `var result = [Element]()` 이렇게도 생성이 가능하겠죠?😉

2022-03-17 12:22 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
제가 의존성 주입에 대해 잘못 이해하고 있었던 것 같습니다. 😅
구현된 코드는 기본값을 주고 있기 때문에 의존성 주입이라고 할 수 없을 것 같습니다!

2022-03-17 12:25 UTC, lina0322 commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
언제든 충분히 그럴 수 있어요! 사실 요런게  더 기억에 잘 남으니까요~
하지만, 같은 부분을 또 다시 제대로 설명할 수 없으면 속상하겠죠?!
요번에 한번 이 쪽 개념 한번 정리해보면 좋을 것 같아요😄
step1 고생하셨습니다! 👍👍👍👍

2022-03-17 12:26 UTC, llingo commented on Calculator/Calculator/Domain/CalculatorItemQueue/CalculatorItemQueue.swift
> +  private(set) var list: CalculatorLinkedList<Element> = .init()
감사합니다! 👍 👍 👍