계산기 [STEP 1] 우롱차
yagom-academy/ios-calculator-app pull request #162
Opened 2022-03-15 06:50 UTC by dnwhd0112

@jungseungyeo 
안녕하세요 린생
이번 PR도 잘 부탁드려요!

고민한 점
@testable 을 사용하여 private으로 선언한 내부 프로퍼티를 사용하려 했으나 실패하였다.
이를 해결하기 위하여 여러가지를 해보았지만 실패하여 일단 private 없이 선언하였다.
참고 사이트 : https://zeddios.tistory.com/1078

2022-03-15 14:05 UTC, jungseungyeo requested changes

2022-03-15 14:05 UTC, jungseungyeo commented on Calculator/Modal/CalculatorItemQueue.swift
> +    var queue: [Item] = []
이 값은오픈하면 안될거같아요. private을 사용해서 캡슐화를 지켜주세요

2022-03-15 14:05 UTC, jungseungyeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
사용하지 않는 함수들은 지워주세요

2022-03-15 14:05 UTC, jungseungyeo commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        if number == 2 && plusString == "-" {
이야기한 내용처럼 result를 ture, false를 넘어주지 말고 특정 값을 비교하여 작성해주세요

2022-03-15 17:17 UTC, dnwhd0112 commented on Calculator/Modal/CalculatorItemQueue.swift
> +
앗 ㅋㅋㅋ 수정하도록 하겠습니다.

2022-03-15 17:18 UTC, dnwhd0112 commented on Calculator/Modal/CalculatorItemQueue.swift
> +    var queue: [Item] = []
네 알겠습니다.

2022-03-15 17:18 UTC, dnwhd0112 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
넵

2022-03-16 13:14 UTC, jungseungyeo commented
우롱차 디코에서 이야기 한 내용을 잘 수정해주셨네요! 고생하셨어요! 캡슐화를 지키면서 코드를 만드는 것을 잊지말아주세요 ㅎㅎ 고생하셨습니다!

2022-03-16 13:14 UTC, jungseungyeo approved these changes

2022-03-16 13:14 UTC, jungseungyeo commented on Calculator/Modal/CalculatorItemQueue.swift
> +    private var queue: [CalculateItem] = []
너무 좋습니다 :)

2022-03-16 13:14 UTC, merged