계산기 I [Step1]
yagom-academy/ios-calculator-app pull request #164
Opened 2022-03-15 11:17 UTC by cherrishRed

2022-03-16 12:33 UTC, yoo-kie requested changes
안녕하세요 Red!

자료구조에 대한 정말 심도있게 고민해보셨네요:) 저도 덕분에 유익하게 읽었습니다!
그럼 올려주신 PR에 대한 저의 의견은 아래에서 말씀드리겠습니다. 🐸

## 🔗 문제상황과 해결방법
* dictionary 를 사용하여 Queue를 구현한 이유
* test Unit 의 네이밍
* test Unit 에서 private으로 설정한 값을 사용할 수 없는 문제 

### dictionary를 사용하여 Queue를 구현한 이유
queue를 공부하고 나서, swift 를 이용한 queue 구현에 대한 다양한 예제를 접했습니다. 
그 중 대표적인 것들이 
* stack 을 이용하기 (swift에서 배열을 이용)
* double stack 을 이용하기 (swift에서 2개의 배열을 이용)
* linked list 를 이용하기 (Node와 linked list 를 직접 구현)
이었습니다. 

stack을 사용하지 않은 이유는, remove first 라는 메서드를 사용할 경우 overhead가 발생하게 되어 큐처럼 보이지만 내부는 스택인 구조가 만들어지는 것 같아 사용하지 않았습니다. 

double stack을 이용할 경우 dequeue를 할 때마다 reverse 를 사용해서 2번째 stack에 값을 넣어주게 되는데, 첫번째 스택의 크기가 커질 수록 이 과정에서 걸리는 시간이 늘어난다고 판단하여 사용하지 않았습니다. 

linked list 는 시간 복잡도가 길지 않지만, Node를 만드는 과정에서 클래스를 사용하고 서로 주소를 계속 추적하고 있기 때문에 RC가 많이 증가하고 공간을 많이 차지한다고 생각했습니다. 

그래서 dictionary의 key 값을 array 의 index 처럼 이용하되 head가 0 이 아니어도 되도록, inqueue dequeue 시에 head와 tail의 값만 이동해 주면 되도록 로직을 만들었습니다. 
딕셔너리를 hash 함수를 사용하기 때문에 항상 시간 복잡도가 O(n)이라고 알고 있고 dictionary 이외에 다른 저장 공간을 사용하는 것도 아니기 때문에 좋은 로직이라고 생각했습니다.

linked list 방식의 구현을 연습해 보고 싶어서, QueueWithLinkedList 라는 브랜치에 그 방식으로도 구현해 보았습니다. 

### test Unit 의 네이밍
unit Test의 네이밍에 있어서 고민을 하다가, 유명하다고 하는 테스트 네이밍 기법 중 `메소드명_테스트하려는상태_기대하는동작` 을 사용하여 네이밍을 수정했습니다. 

### test Unit 에서 private으로 설정한 값을 사용할 수 없는 문제
오동나무가 야곰닷넷에 올려주신 강의를 보면서, @testable import target 을 하면 private 접근제어를 가진 프로퍼티나 메서드에도 Unit Test 시에 접근할 수 있다고 잘못 판단했습니다. 
문서들을 찾아보니, prviate 접근제어자가 일을 잘하고 있는 것이고 캡슐화를 적극 이용해 test를 하기를 권장하는 내용이었습니다.
그래서 privat(set)으로 접근하고 값 변경이 필요한 부분에 있어서는 메서드를 통해 해주게 되었습니다.

혹시 private 에 직접적으로 접근할 수 있는 방법이 있는데 제가 모르는 걸까요?

```
🐸 우선 제가 테스트 코드를 본격적으로 샤용해본 경험이 없어서 설명이 미흡할 수 있다는 점 양해 부탁드립니다!🥲
저도 Red가 말씀하신대로 Unit Test의 목적을 생각해봤을 때 개발자가 의도한대로 캡슐화가 잘 진행이 되었는지를 검증하는 측면에서 테스트 코드에서는 private에 접근할 일이 사실상 필요하지 않다고 생각됩니다:) 또한 Unit Test를 진행하면서 코드의 로직을 검증하는것 보다 객체의 동작을 테스트한다고 생각했을 때 private에 접근이 필요한지를 고민해보게 되는 것 같습니다!
이와 관련해서 Red의 추가적인 의견이 있다면 공유 부탁드립니다:) 같이 이야기 나눠봐요!
```

## 🔗 고민한 점 & 조언을 받고 싶은 부분
* Equtable을 채택하고 있지 않아, 값 비교를 못하는 부분
* 테스트 코드를 돌리고 난 후 생기는 테스트 코드 옆의 빨간색 
* ❗️Range requires lowerBound <= upperBound 에러 가 뜨는 이유 
* TDD

### Equtable을 채택하고 있지 않아, 값 비교를 못하는 부분
원래 `reset`메서드는 큐 안의 모든 값을 배열로 만들어 리턴해 주는 기능을 포함하고 있었습니다.
```swift 
mutating func reset() -> [CalculateItem?] {
    var allValue: [CalculateItem?] = []
    let countOfQueue = queue.count
    for _ in stride(from: 1, through: countOfQueue, by: 1) {
        allValue.append(dequeue())
    }
    head = 0
    tail = 0
    return allValue
}
```
그런데 이 메서드를 test code 를 통해 올바른 return 타입이 나오는지 `expectResult` 라는 `[CalculateItem?]` 타입의 인스턴스를 만들어서 비교해보려고 하였으나 `Equtable` 을 채택하고 있지 않아 되지 않는다는 오류가 떳습니다.

Equtable 타입을 채택하려고 시도하였으나, CalculateItem 이 각각 다른 타입을 캐스팅 하고 있어서, 타입이 일치한다면 같다고 해주어야 할지, 아니면 다운캐스팅을 이 단계에서 해줘도 되는건지 확신이 서지 않았습니다. 

그래서 reset 의 기능 자체에만 충실할 수 있도록, return 타입을 삭제 했습니다.😭

protocol 을 타입으로써 사용할 때, Equtable을 채택하고 싶다면 어떠한 방향으로 가는 것이 좋은 방법일지 조언을 얻고 싶습니다. 

```
🐸 먼저 reset이 배열을 반환하게 된다면 네이밍이 수정되어야 할 것 같습니다. 그리고 모든 배열을 반환하는 메서드가 필요한지에 대한 여부도 다시 고민해보시면 좋을 것 같습니다!
그리고 현재 CalculateItem은 프로토콜이기 때문에 Equatable 프로토콜을 채택하게 되면 Equatable 구현 내부의 Self가 명확한 CalculateItem 타입을 명시하지 못해서 더이상 CalculateItem 프로토콜을 타입처럼 사용할 수 없다는 오류를 발생시킵니다.
만약 두 객체를 비교하고 싶다면 CalculateItem을 채택하는 다른 struct나 class를 생성하여 Equatable를 채택하거나, CalculateItem을 채택하고 있는지를 확인하는 메서드를 직접 구현해주시는 것을 추천드립니다:)
```


### 테스트 코드를 돌리고 난 후 생기는 테스트 코드 옆의 빨간색 
![](https://i.imgur.com/eqZGJ4b.png)
이런식으로 오른쪽에 생기는 빨간 것은 무엇을 의미하는 것인가요?

Model 부분에 뜨는 것은 test가 진행되지 않은 부분이라고 받아들였는데, test code 에 나오는 빨간색은 의미를 찾지 못했습니다.😭

`🐸 지금 파악된 바로는 표시가 되는 테스트 케이스들은 guard문 return에서 걸리고 있는 것 같아요. 제대로 테스트가 진행되고 있는지 확인이 필요해보입니다.`

### ❗️Range requires lowerBound <= upperBound 에러 가 뜨는 이유

```swift
mutating func reset() -> [CalculateItem?] {
    var allValue: [CalculateItem?] = []
    let countOfQueue = queue.count
    for _ in stride(from: 1, through: countOfQueue, by: 1) {
        allValue.append(dequeue())
    }
    head = 0
    tail = 0
    return allValue
}
```
reset 메서드에서 지금은 없어진 부분이지만, for 문을 활용해서 dequeue를 연속적으로 해주는 부분이 있었습니다. 
```swift
for _ in 0...countOfQueue {
    allValue.append(dequeue())
}
```
이 부분을 위와 같이 작성하니 `Range requires lowerBound <= upperBound` 라는 에러가 떳습니다. stride 로 바꿔서 해결이 되긴 했지만, `0...countOfQueue` 도 closed Sequence 인데 들어갈 수 없는 이유를 찾지 못했습니다.
에러의 원인을 알려면 어느 부분을 공부해 보아야 할까요? 

`🐸 해당 에러가 발생했을 때의 for in구문의 루프 범위(0…countOfQueue)가 올바른지를 확인해보셔야 할 것 같습니다.`

### TDD
이번에 TDD 방식을 최대한 사용하려고 노력을 했습니다. 그런데 리펙토링 과정에서 익숙하지 않은 탓인지 test Unit 의 로직을 고치는 일이 많았습니다. 
TDD 테스트로직이 자주 변경 되면 좋지 않다고 생각이 들었는데 이 문제를 어떻게 해결하면 좋을까요?

```
🐸 저는 TDD를 아직 이론적으로만 접근해서 구체적인 답변을 드리기는 어려울 것 같은데요.😅
최대한 테스트 코드를 변경하지 않으려면 객체를 설계할 때 추상화를 통해 테스트 코드에서 내부 로직을 최대한 작성(또는 접근)하지 않고 각 객체 간의 의존성을 분리시켜주도록 노력할 것 같습니다.
```

2022-03-16 12:36 UTC, yoo-kie commented
그리고 추가적으로
현재 queue의 length에는 제한이 없는 상태로 enqueue & dequeue가 실행될 경우, head와 tail의 값만 증가하고 queue 내부의 데이터에는 변화가 없을 것 같습니다. dequeue 후에 접근을 하지 않을 데이터들이 계속 적재되어 개선이 필요해보입니다.

2022-03-16 12:39 UTC, yoo-kie requested changes

2022-03-16 12:39 UTC, yoo-kie commented on Calculator/Calculator/Model.swift
> +struct CalculatorItemQueue {
만약 CalculatorItemQueue에 큐가 비어있을 때를 확인하기 위한 isEmpty 메서드를 구현한다면 어떻게 구현할 수 있을까요?

2022-03-16 13:08 UTC, cherrishRed commented on Calculator/Calculator/Model.swift
> +        self.queue[tail] = data
네 컨벤션 통일 하도록 하겠습니다!

2022-03-16 13:26 UTC, yoo-kie commented on Calculator/Calculator/Model.swift
> +}
Red! 이건 STEP이 진행되면서 고민해보셔도 될 것 같아요:)

2022-03-16 16:41 UTC, cherrishRed commented on Calculator/Calculator/Model.swift
> +struct CalculatorItemQueue {
```swift
    var isEmpty: Bool {
        return queue.isEmpty
    }
```
이렇게 구현해 보았습니다.

2022-03-16 16:42 UTC, cherrishRed commented on Calculator/Calculator/Model.swift
> +        let value = self.queue[head]
넵 컨벤션을 통일 하겠습니다.

2022-03-16 17:06 UTC, cherrishRed commented on Calculator/Calculator/Model.swift
> +        }
앗, 제가 삭제하는 메서드를 구현 했다고 생각했는데 실수가 있었네요😭
이 부분을 체크 했다고 생각했는데 테스트 구문이 충분하지 않아서 발견하지 못했던 것 같습니다. 
remove 해주는 코드와 이것을 검사해주는 테스트 구문 모두 추가 했습니다.

2022-03-16 17:09 UTC, cherrishRed commented on Calculator/Calculator/Model.swift
> +}
Double 타입이 기본적인 타입이라서 직접적으로 프로토콜을 채택하는 것을 지양하는 낫다는 말씀이신가요? 
아직은 사용성 측면에서 어떠한 혼란을 야기할 수 있는지 짐작이 가지 않습니다.😅
혹시 말씀하신 개선 방향이 중간에 더블 타입을 가지는 새로운 타입을 만들어서 그 타입이 CalculateItem 아이템을 채택하도록 하는 방식 인가요?

2022-03-16 17:22 UTC, cherrishRed commented
개굴🐸! @yoo-kie 리펙토링 완료 했습니다. 
코멘트 주신 것 모두 잘 읽어 보았습니다. 🥰

## 리펙토링 한 내용 
* 빈 프로토콜의 주석 추가
* self. 명시 컨벤션 통일
* dequeue 메서드에 삭제하는 부분 구현
* isEmpty 메서드 구현
* 테스트 코드에 생기는 오류 수정, 주석 수정

테스트 코드에 `guard` 문을 사용해서 `else { return }` 부분을 통과하지 못해서 빗금이 생기는 오류와 
`else { return }`을 통과했을 때, 뒤의 코드가 실행이 되지 않아서 코드의 문제가 없다고 표시되는 오류를
guard 문을 삭제하는 것으로 리펙토링 했습니다. 

 ```swift
   func test_dequeue_OperatorType을뺄때() {
        sut.enqueue(with: 1.0)
        sut.enqueue(with: Operator.add)
        sut.enqueue(with: 2.0)
        _ = sut.dequeue()
        guard let result = sut.dequeue() as? Operator else { return }
        XCTAssertEqual(result, Operator.add)
    }
```
위의 코드를 아래와 같이 수정하였습니다. 
```swift
    func test_dequeue_OperatorType을뺄때() {
        sut.enqueue(with: 1.0)
        sut.enqueue(with: Operator.add)
        sut.enqueue(with: 2.0)
        _ = sut.dequeue()
        let result = sut.dequeue() as? Operator
        XCTAssertEqual(result, Operator.add)
    }
```

reset 의 반환 타입에 대해서는 아직까진 전체 배열을 반환해주는 메서드나 프로퍼티가 필요없다고 느껴 구현하지 않았고 이에 따라 Equtable은 구현하지 않았습니다.

2022-03-17 10:54 UTC, yoo-kie commented on Calculator/Calculator/Model.swift
> +}
넵 기본적인 타입이라 지양하는게 낫다고 말씀드린거였어요:) 그리고 Double의 extension에 CalculatItem 프로토콜을 채택했다는 사실을 추적하기 어렵다는 점에서 혼란을 야기할 수 있다고 말씀드렸습니다!

2022-03-17 11:09 UTC, merged