계산기 I [Step1] Safari
yagom-academy/ios-calculator-app pull request #165
Opened 2022-03-15 12:42 UTC by saafaaari

@1Consumption
안녕하세요. 올라프 
safari입니다. STEP1 PR 보냅니다.

# UML

<img src="https://i.imgur.com/eeqyTb5.png">

# 문제상황과 해결방법
- Queue 타입 구현에 있어 어떠한 방법으로 구현할까?
- Queue 타입에 들어올 데이터를 어떤 방법으로 제한할까?

## Queue 타입 구현에 있어 어떠한 방법으로 구현할까?
Queue 타입을 구현함에 있어 list를 활용한 방법을 공부하였습니다.
list를 공부하면서 배열 리스트가 있고, 연결 리스트가 있다는 것을 알게 되었습니다. 배열로도 Queue를 구현할 수 있고, 연결 리스트로도 Queue를 구현할 수 있었습니다. 결론적으론 연결 리스트를 선택하였습니다.

### 배열을 이용하여 Queue를 구현하지 않은 이유
큐는 선입선출이라는 특성을 가지고 있었습니다. 때문에 배열을 이용할 경우 앞에서 데이터를 빼야 하는데 그러면 뒤에 있는(1,2...,n) 인덱스가 한 칸씩 앞으로 당겨지는 작업이 발생! 때문에 데이터를 빼는 행위를 하면 내부에선 추가적인 연산이 연속적으로 증가하여 오버헤드가 발생(때문에 시간 복잡도 O(n)) 배열을 이용하면 데이터의 접근은 빠르나 삭제, 삽입에서 효율적인 방법은 아니라고 생각해 하지 않았습니다. 하지만, 배열을 이용하면서 위 문제를 해결할 수 있는 방법은 있었습니다.
- 삭제: O(n)
- 추가: O(1)

첫 번째는, 앞으로 당기지 않고, 데이터가 빠진 자리에 nil로 대체하는 방법
위 방법은 빠진 자리를 앞으로 당겨오지 않고 nil로 비워두는 방법입니다. 하지만, 빈 배열을 지속적으로 남겨두는 것은 좋은 방법이 아나라고 생각하였고, 때문에 중간중간 빈 배열을 remove 해줘야 했습니다.
- 삭제: O(1)
- 추가: O(1)

두 번째는, 하나의 배열 데이터를 두 개의 스택으로 각 반대 정렬을 통해 해결하는 방법이었습니다.
enqueue할 땐, 일반적으로 데이터를 append 해주고 dequeue 할 때, 배열을 뒤집어 뒤에 있는 데이터를 빼냄으로써, 선입선출을 해주는 방법이었습니다.
- 삭제: O(1)
- 추가: O(1)

### 연결 리스트를 채택한 이유
연결 리스트를 이용하면 삭제 추가에 있어 효율적으로 일을 처리할 수 있었습니다. 또한 큐에 필요한 기능을 연결 리스트로 구현하여 메서드만 불러와 큐 자체 파일은 간결했습니다. 하지만, 노드와 연결 리스트 객체를 직접 구현해야 했으며, 코드량이 많았습니다. 또한 연결 리스트는 노드라는 객체를 통해 데이터를 담는 특성이기 때문에 저장 공간 효율이 좋지 못할 것 같습니다. 그리고 데이터에 접근하려면, 배열과 같이 인덱스로 직접 접근이 아닌, 헤드부터 타고 들어가야 하기 때문에 검색에 있어 효율이 좋지 못한 것 같습니다. 하지만, 이번 프로젝트에서 큐는 중간의 값을 접근하는 경우가 없어 보였고, 큐 타입은 코드가 간결해져 연결 리스트를 채택하였습니다.
- 삭제: O(1)
- 추가: O(1)

## Queue 타입에 들어올 데이터를 어떤 방법으로 제한할까?

```swift
class CalculatorItemQueue<T: CalculateItem> {
...
}

 var sut: CalculatorItemQueue<Int>!

```
처음엔 위와 같이
제네릭을 이용하여 큐를 생성할 때, 타입이 정해지도록 하였고, Int 타입을 extension 하여 프로토콜을 채택해 채택한 타입만 제네릭에 들어올 수 있도록 하였습니다. 하지만, 제네릭은 타입이 사용될 때, 타입을 정해줘야 해서 정해진 순간 한 가지 타입만 저장될 수 있었습니다. 하지만, 프로토콜을 채택한 타입은 다 저장하고 싶은 생각에

```swift
class CalculatorItemQueue<CalculateItem> {
...
}

 var sut: CalculatorItemQueue<CalculateItem>!

```
위와 같이 수정하였습니다. 하지만, 위와 같이 프로토콜을 타입으로 사용하면, 값을 비교할 수 없고 비교할 때마다, 다운 캐스팅을 해줘야 했습니다. 또한, 컬렉션이 데이터를 저장할 때 하나의 데이터 타입만을 저장하는 것을 고려해 다시 처음의 방법을 선택했습니다.
# 조언을 받고 싶은 부분
- 테스트에 대해서
- 큐의 기능을 연결 리스트에서 메소드로만 불러와 사용하는 부분에 대해서

## 테스트에 대해서
저는 연결 리스트에서 기능을 구현하고 테스트에선 큐의 메서드를 불러와 테스트를 진행하였습니다. 큐가 연결 리스트 타입을 가지고 있기 때문에 자연스럽게 두 타입 모두 테스트가 진행되지만, 주 기능이 연결 리스트이기에 연결 리스트를 테스트할까도 생각했지만, 구현할 주체가 큐라고 생각되어 테스트 코드에서 큐의 인스턴스를 만들고 진행했습니다. 하지만 이 부분이 맞는 부분인지 틀린 부분인지 둘 다 상관없는 방법인지 궁금하고, 또한 테스트 코드 함수의 네이밍도 신경 써야 하는 부분인지 궁금합니다.

## 큐의 기능을 연결 리스트에서 메소드로만 불러와 사용하는 부분에 대해서
저의 코드에서 큐는 따로 로직이 없습니다. 연결 리스트의 메서드를 호출해 큐의 기능을 구현하였는데, 계속 구현을 하다 보니 큐이기보단 연결 리스트를 일부의 기능만 사용하고 있다는 생각이 계속 들었습니다. 이 부분에 대해서 올라프의 생각을 듣고 싶습니다.

2022-03-16 03:43 UTC, 1Consumption requested changes
@saafaaari
안녕하세요 사파리~ 이번 스텝 잘 부탁드려요!

작성해주신 코드를 읽어봤는데, 메소드를 역할별로 나누려고 노력한게 눈에 보였고 접근제어자도 잘 활용해주셔서 읽기 좋았습니다😄
또한 테스트 코드도 의미있게 잘 작성해주셨어요!

다만 커밋 로그를 보다가 한가지 아쉬운 커밋을 발견했어요.
https://github.com/yagom-academy/ios-calculator-app/pull/165/commits/7d507ad4ec5c7c65484ca42deb744940b16d3027 이 커밋의 이름이 너무 추상적이라고 생각해요. 분명 더 많은 일을 하는 커밋 같은데 말이죠. 이 커밋은 분리가 되어야하고, 이름을 보다 구체적으로 지을 필요가 있어보입니다.

아래는 조언을 받고싶다고 적어주신 부분에 대한 제 생각입니다.

> 테스트에 대해서
저는 연결 리스트에서 기능을 구현하고 테스트에선 큐의 메서드를 불러와 테스트를 진행하였습니다. 큐가 연결 리스트 타입을 가지고 있기 때문에 자연스럽게 두 타입 모두 테스트가 진행되지만, 주 기능이 연결 리스트이기에 연결 리스트를 테스트할까도 생각했지만, 구현할 주체가 큐라고 생각되어 테스트 코드에서 큐의 인스턴스를 만들고 진행했습니다. 하지만 이 부분이 맞는 부분인지 틀린 부분인지 둘 다 상관없는 방법인지 궁금하고, 또한 테스트 코드 함수의 네이밍도 신경 써야 하는 부분인지 궁금합니다.

지금은 큐가 연결리스트를 가지는 구조입니다. 그런데 연결리스트에 대한 테스트가 없는데 연결리스트의 로직은 누가 보장하나요? 따라서 두 객체 모두 테스트코드가 있어야합니다. 하위객체를 사용하는 상위객체는 하위객체의 로직이 보장되었다는 전제하에 사용되니까요.
또한 의존성 분리라는 키워드가 있어요. 이건 좀 어려운 개념이라 지금은 이런게 있다 정도만 알고 iOS를 조금 더 공부한 다음 의존성 분리에대해 공부해보도록 해요!

네이밍은 코멘트로 따로 남겼으니 참고해주세요!

> 큐의 기능을 연결 리스트에서 메소드로만 불러와 사용하는 부분에 대해서
저의 코드에서 큐는 따로 로직이 없습니다. 연결 리스트의 메서드를 호출해 큐의 기능을 구현하였는데, 계속 구현을 하다 보니 큐이기보단 연결 리스트를 일부의 기능만 사용하고 있다는 생각이 계속 들었습니다. 이 부분에 대해서 올라프의 생각을 듣고 싶습니다.

연결리스트의 기능을 사용자가 사용하기 좋게 큐라는 타입으로 만들어준거 아닌가요? 저는 자연스럽고 좋다고 생각해요~

---------------------------------------------------

나머지는 코멘트를 참고해주세요.
고생하셨습니다!

2022-03-16 03:43 UTC, 1Consumption commented on Calculator/Calculator.xcodeproj/xcshareddata/xcschemes/Calculator.xcscheme
> +</Scheme>
이 변경사항은 뭔가요? https://github.com/yagom-academy/ios-calculator-app/pull/165/commits/8ce6cbf9c977c4802040219040819fca32a5bcaf 이 커밋의 내용과 맞지 않아보여요.

2022-03-16 09:55 UTC, saafaaari commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
저도 올라프의 글을 읽고 찾아봤는데, 연산 프로퍼티로 구현되어 있는 것을 확인하고, 연산 프로퍼티로 리팩토링하였습니다.🙇‍♂️

2022-03-16 09:56 UTC, saafaaari commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
네 삭제하고, 올라프의 말대로 개행에 나름의 기준을 가지고 통일 시켰습니다.

2022-03-16 09:59 UTC, saafaaari commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
테스트 때, 검사하고 리팩토링한다고 사용했는데 놓친 것 같습니다. 리팩토링하였습니다.

2022-03-16 10:03 UTC, saafaaari commented on Calculator/Calculator/LinkdeList.swift
> +        tail = node
들여 쓰기를 덜 사용하기 위해서 했는데, 오히려 올라프 글대로 중복되는 코드와 return을 사용하는 부분보단 else를 사용하는 방법이 더 좋은 것 같습니다

2022-03-16 10:04 UTC, saafaaari commented on Calculator/Calculator/LinkdeList.swift
> +        }
🙇‍♂️

2022-03-16 10:09 UTC, saafaaari commented on Calculator/Calculator/LinkdeList.swift
> +        return count
올라프의 글을 읽고 나니 기준 없이하고 있었다는 것을 깨달았습니다. 전 타입 내부에선 프로퍼티와 함수 사이,  함수와 함수 사이에 공백을 해주는 방법으로 리팩하였고, 함수 내부에선 공백을 주지 않았습니다. 또한 컨벤션 또한 짧은 한줄 코드는 줄 바꿈을 하지 않는 방향으로 통일 시켰습니다.

2022-03-16 10:10 UTC, saafaaari commented on Calculator/Calculator/LinkdeList.swift
> +    }
get이라는 동사를 사용해 봤습니다. 괜찮은 가요?

2022-03-16 10:11 UTC, saafaaari commented on Calculator/Calculator/LinkdeList.swift
> +        var dataArray: [T] = []
처음 알았습니다.
dataBundle이라는 네이밍은 어떤가요? 몬가 한 데이터 뭉치라는 느낌을 주고 싶었습니다.

2022-03-16 10:14 UTC, saafaaari commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
맨 아래 코멘트로 따로 남겼습니다. 😊

2022-03-16 10:15 UTC, saafaaari commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var sut: CalculatorItemQueue<Int>!
맨 아래 코멘트로 따로 남겼습니다. 😊

2022-03-16 10:15 UTC, saafaaari commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
맨 아래 코멘트로 따로 남겼습니다. 😊

2022-03-16 10:17 UTC, saafaaari commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(reselt, 3)
맞습니다. 또한 좀 더 테스트가 명확해진 것 같습니다. 테스트 코드는 따로 리팩토링 커밋을 남기 않고 진행하기로 했기 때문에 다음 스텝에서 위 같은 방법을 적극 활용해 보겠습니다.

2022-03-16 10:20 UTC, saafaaari commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(reselt, [1, 2, 3])
이상하게 한글을 사용하면, Xcode가 종료되는 현상이 가끔 발생합니다.🥲
한글 사용이 문제인지, 우연히 한글을 사용할 때 팅겼는 지는 잘 모르겠습니다.

2022-03-16 10:22 UTC, saafaaari commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
감사합니다. `@discardableResult`에 대해서도 찾아보고 공부해보겠습니다.

2022-03-16 10:23 UTC, saafaaari commented on Calculator/Calculator.xcodeproj/xcshareddata/xcschemes/Calculator.xcscheme
> +</Scheme>
xml인건가요? 스토리보드를 건드리지 않았는데 왜 위 같은 코드 수정이 이루워졌는지 잘 모르겠습니다. 🧐

2022-03-17 13:49 UTC, 1Consumption approved these changes
사파리 고생하셨습니다.

의존성 주입이라는 어려운 개념을 학습하고 적용하시느라 정말 고생이 많으셨을 거 같아요. 
너무 잘 이해하셔서 솔직히 조금 놀랐습니다. 👍 

몇가지 자잘한 코멘트를 남기긴 했는데, 그렇게 크리티컬하진 않으니 어프루브 하겠습니다.

고생하셨습니다!💪

2022-03-17 13:49 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    }
필요없는 메소드 같아요

2022-03-17 13:49 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +}
파일을 따로 만들어서 분리해주세요.

2022-03-17 13:49 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    var dataA: [T] = []
dataA라는 이름이 뭘 의미하는지 모르겠어요. 변수는 A, B, C... 1,2,3 같은 값으로 구분되면 안됩니다.

2022-03-17 13:49 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +
공백이 조금 아쉽습니다.

2022-03-17 13:49 UTC, merged