계산기 [STEP 1] mmim
yagom-academy/ios-calculator-app pull request #167
Opened 2022-03-15 14:09 UTC by JoSH0318

@lina0322 안녕하세요 엘림! 첫번째 PR입니다! 잘부탁드립니다!
---
### UML
![](https://i.imgur.com/tYnfmpy.png)
---
### ❓고민한점 && ❗️트러블슈팅
#### 1️⃣ Queue(Linked Queue vs Double Stack Queue)
- ❓swift는 Queue 형태의 저장 구조를 지원하지 않는다. 따라서 Queue 구현에 있어 고민을 했다. 
- ❓이번 프로젝트에 필요한 기능은 1) 마지막 값에 값을 추가, 2) 첫번째 값을 시간복잡도 O(1)인 제거, 이 두가지로 판단된다.
- ❓첫번째 고려한 방법으로 Linked List를 이용한 Linked Queue: 배열에 노드를 할당함으로써 그 위치를 파악하고 추가/삭제를 해주는 방식이다. 노드에는 값과 그다음 노드의 노드 값이 있다. 하지만 이번 프로젝트는 배열의 마지막에 값추가 + 배열의 첫번째 값을 제거 해주는 Queue의 기능만 필요하다. 따라서 약간의 불필요한 코드가 발생한다 생각했고, 적합하지 않다고 생각했다. 만약 이번 프로젝트에 중간 값을 넣거나 제거해야하는 기능이 필요하다면 적합했을 것 같다.
- ❓두번째 고려한 방법으로 Double Stack을 이용한 Queue: 두개의 stack을 만들어주어 마지막에 값을 넣을 때는 정방향 배열에 삽입, 첫번째 값을 제거할 때는 reverse를 이용하여 역방향 배열을 만들어주고 그것의 마지막 값을 반환한다. reverse 메서드의 시간복잡도가 O(1)이기 때문에 가능한 방법이다.
- ❗️이러한 근거로 Double Stack을 사용한 Queue를 사용하였다.
- 💬 혹시 제 생각한 것이 맞을까요? 🥲

#### 2️⃣ 접근제어
- ❓처음에는 `var inputStack: [Element]`, `var outputStack: [Element]`만 존재했다. 문제는 테스트할 때 생겼다. 올바른 값이 있는지를 확인하기 위해 배열에 subscript 문법으로 접근했다.
- ❓하지만 private한 두 변수에 접근할 수 없었다. 생각해보니 값이 이 후에 프로젝트를 진행함에 있어 첫번째값과 마지막값의 조건(숫자인가, 연산자인가)에 따라 동작이 나뉠수도 있을 거라는 생각이 들었고, 또한 배열에 직접 접근하는 것이 접근제어에 있어 옳은 방향이 아니라고 판단했다. 
- ❗️array의 first, last, isEmpty, count method와 같은 기능을 만들어서 내부적으로 배열의 상태를 확인해주는 코드를 추가했다.
- ❗️test 코드에서 직접 배열에 접근하지 않고, first, last, isEmpty, count를 이용하여 값을 확인했다.
- 💬 이후에 조건에 따라서 first, last, isEmpty, count의 로직이 변경/삭제가 될 수도 있을 것 같습니다!
---
### 질문사항
1. 연산프로퍼티에서 getter만 사용하는 경우 get 키워드를 생략할 수 있는 것으로 알고있습니다! 제가 실수로 return 키워드를 깜빡하고 코드를 진행했는데 올바른 동작을 하는 것을 볼 수 있었습니다. return을 생략해도 되는 것인지, 만약 써도 된다면 가독성 측면에서 문제가 발생하는지 알고 싶습니다.
2.  Queue에는 Double 타입의 숫자, String 타입의 연산자가 들어갈 수 있습니다! 따라서 enum Operator와 extension Double이 protocol CalculatorItem을 준수하도록하고  CalculatorItem을 준수하는 타입만 Queue에 저장될 수 있도록 구현할 생각입니다.☺️ 이러한 측면에서 봤을 때 제가 구현한 방법이 맞을까요? 제가 잘못 생각하는 부분이 있다면 말씀해주세요 👍
---

2022-03-16 11:14 UTC, lina0322 requested changes
안녕하세요, 밈~ 반갑습니다!
이번 프로젝트 함께 힘내보아요!
서로 많은 것을 배울 수 있는 시간이 되었으면 좋겠습니다🙏

---

코드에 정답은 없고, 밈이 생각한 이유가 있다면 그걸로 저를 설득시키고 구현하는 거라고 생각해요!
요렇게 진행 해보다가, 중간에 뭔가 아니다 싶으면 갈아엎을 준비도 하는거고요.
몇번 갈아엎다보면 아, 힘들구나.. 하고ㅎㅎ 처음부터 잘 생각해야지 하면서 더 꼼꼼하게 생각하게 되는 것 같습니다.
(결론은 일단 이대로 가보자는거쥬~)

또, 지금 설계는 이렇지만 앞으로 하다보면 추가되고 삭제되고 변경되는 것들이 당연히 생길거에요.
그때 맞춰서 다시 테스트 코드도 작성하고, 다시 리뷰도 받는거니까 걱정할 필요는 없습니닷!!

마지막으로 질문해주셨던 return 명시같은 경우에는, 저는 꼭 명시해주는 편이에요ㅎㅎ
가독성에 있어서 있는게 더 좋더라고요. 근데 요런건 보통 개인 취향을 타기도하고
회사에서 주어지는 컨벤션이 있어서 따르게 될테니
지금 단계에서는 꼭 반드시 이렇게 써야지! 보다는 프로젝트마다 컨벤션 정하고 이렇게 저렇게
다양하게 써보는게 좋을 것 같습니다. 좋은 발견이에요~~👍

---

사실 코드가 많지 않아서, 리뷰할 부분도 많지 않았네요ㅎㅎ
그래도 제가 달아드린 부분 확인해주시고, 테스트 쪽이 조금 아쉬워요ㅠㅠ
assert 함수들 좀 더 다양하게 사용하는 연습이 되도록 테스트 코드 몇 개만 더 작성해보고
다음으로 넘어가면 어떨까~합니다!

이해 안 가거나 궁금한 것 있으면 편하게 디엠주시고, 수정 완료되면 마찬가지로 메세지 남겨주세욥! 🙇🏻‍♀️

2022-03-16 11:14 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +}
파일 분리 해주세요~🙏

2022-03-16 11:14 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<Element: CalculatorItem> {
struct를 선택한 이유는 무엇일까요?😀

2022-03-16 11:14 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(_ element: Element) {
mutating 키워드는 어떤거죠?!💁🏻‍♀️

2022-03-16 11:14 UTC, lina0322 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(result, nil)
nil인지 바로 체크 할 수도 있을 것 같은데요?😄

2022-03-16 12:21 UTC, JoSH0318 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +}
앗! 52번줄 enum은 파일 분리가 필요한데 제가 놓지고 말았네요 ㅜㅜ
이 부분에서 평소에 궁금했던 점이 있습니다 ☺️
제 코드처럼 protocol 이 짧은 경우 그리고 swift에서 제공하는 type(Int, String, Double 등) extension 같은 경우에는
파일분리는 어떻게 해줘야할지 항상 고민이었습니다.
좋은 방법? 추천해주고 싶은 방향이 있다면 조언 부탁드립니다 🙏

2022-03-16 13:01 UTC, JoSH0318 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(result, nil)
생각해보니 `XCTAssertNil`이 있었네요! 수정했습니다!

2022-03-16 13:04 UTC, JoSH0318 commented
@lina0322  엘림! PR 코멘트 감사합니다! 말씀하신 부분 수정하고 질문에 답변드렸습니다!

다시 생각해보는 기회가 된 것 같습니다. 특히 mutating에 관한 부분은 대충 알고 있었지 한마디로 설명할 정도는 아니었는데 이번 기회에 정리가 됐어요 😃

질문사항은 위 코멘트 댓글로 남겼습니다!

2022-03-17 10:37 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +}
저는 각각 나누어서 파일을 만드는 편입니다!😊
간혹 procotol이 delegate용으로 한 곳에만 종속된다면 ViewController위에 두기도 하는데요.
그 외에는 짧고 긹고 상관없이(심지어 이름만 지어줘서 껍데기만 있는 경우여도) 분리해주는 편입니다.
요거는 회사마다 다를 수 있지만, 지금은 분리하는걸 좀 더 추천드려요!👍

2022-03-17 10:39 UTC, lina0322 approved these changes
> 테스트 쪽이 조금 아쉬워요ㅠㅠ
assert 함수들 좀 더 다양하게 사용하는 연습이 되도록 테스트 코드 몇 개만 더 작성해보고
다음으로 넘어가면 어떨까~합니다!

요 부분 다음 step에 반영 부탁드릴게요~ 
이번 스텝 고생하셨습니다!🙏

2022-03-17 10:39 UTC, merged