계산기 [STEP 1] 쿼카
yagom-academy/ios-calculator-app pull request #173
Opened 2022-03-16 03:44 UTC by Quokkaaa

@1Consumption
안녕하세요 울라프! ⛄ 
LinkedList를 이해하고 코드작성하는데 예상보다 더 걸렸습니당 😭  처음에 블로그글을 참고할때 LinkedList를 소개하는 블로그 글마다 코드구현된 로직이 다르다보니 혼동이 왔던것같습니다. 그래서 처음 시도한 코드에서 테스트 도중 에러가 발생했는데 해결하는데 어려움이있어 아직 잘 이해를 못한것같다고 판단하여 지우고 새롭게 다시 하나하나 코드를 구현을 하게되어 예상시간보다 더 늦어졌던것같아요 😭 😭  
STEP1 리뷰 잘 부탁드리겠습니다.

- 처음에 참고했던 code [슈프림](https://tngusmiso.tistory.com/20)
- 이후에 참고한 code [개발자 소들이](https://babbab2.tistory.com/86?category=908011)

# UML
![](https://i.imgur.com/Hvysed9.png)

# LinkedList의 기능설명
`var count: Int` - head가 nil일 경우 0을 반환하며 그렇지 않을경우 node.next값이 nil일때까지 count += 1을 더해주는 방식으로 수를 계산합니다.

`func append(data: T)` - 매개변수를 통해 입력받은 data를 tail.next에 할당하여 뒤에 연결시켜주는 로직이며 head가 nil일 경우 head와 tail 둘다 data를 할당해줍니다.

`func removeFirst() -> T? `- head값이 nil이면 nil을 반홚해주고 head.next가 nil일경우에는 head의 값을 새로운 변수에 담은후 head의 값을 nil처리를 한후 담아놓았던 변수를 반환해주고 node의 값이 2개이상 존재할때는 head.data를 변수에 담아놓고 head의 데이터를 head.next에 설정을 해줌으로써 새로운 head를 다시 지정해주고 담아두었던 data를 반환합니다.

`func removeAll()` - head와 tail에 nil을 할당함으로써 중간에있던 모든 RC를 해제하여 값을 모두 제거해줍니다.

# list자료구조는 어떤것을 선택하는게 좋을지 ?
우선 array와 LinkedList구조에 대해서 간단하게 알아보았습니다.

array는 index가 존재하기때문에 값을 찾는데 수월하지만 삽입/삭제시 index재배치고 오버헤드가 발생한다는 특징이있었습니다.

LinkedList는 array의 오버헤드가발생하는단점을 보안하기위해 만들어졌으며 노드안에 data와다음node를가르키는주소가 담겨있으며 순서대로 기차와같은 형태로 데이터가 나열되어 값을 삽입/삭제시 오버헤드가 발생하지않습니다. 하지만 Node의 데이터와 주소값을 동시에 사용하기때문에 메모리를 더 사용한다는 점이 있었습니다.

울라프가 주신 조언과 함께 LinkedList 복잡한  방식을 이해하고 넘어가는것이 class와 RC에대해 조금더 이해하고 공부할 수 있는기회인것같아 선택했습니다.

# class와 struct 중 어느것을 선택할지?
CalculatorItemQueue는 구조체로하고
Node와 LinkedList는 클래스로 지정하였습니다.

우선 LinkedList의 방식은 노드가 다음노드를 참조하는 방식이 class를 사용해야하는 주된목적이라고 생각했습니다.
RC가 없는 즉 pointer의 가르킴이 설정이 안되어있는 노드는 메모리에서 해제가되기때문에 이러방식으로 구현된 LinkedList와 Node는 class로 구현되는게 적합한것같습니다.

CalculatorItemQueue는 만들어져있는 LinkedList를 활용해 큐의 특성이 담겨있으면 된다고 생각했는데 class로 만들어야할 이유를 잘 모르겠더라구요. 참조가 필요한건 LinkedList라서 애플권장사항인 구조체로 구현하게되었습니다.

# 제네릭 사용이유
- Int의 값만 받으면 되지않나 라는  생각을 했으나 입력을받을 값이 숫자와 연산자도 존재하기때문에 String의 값이 들어올 수 도 있다고 판단했습니다.
- 또한 요구사항에 보면 CalculateItemQueue요소들이 CalculateItem프로토콜을 준수하게끔 해야한다고 했는데 CalculateItemQueue만 프로토콜을 채택하는것과 CalculateItemQueue요소들이 프로토콜을 채택하는건 의미가 다르다고 생각했어요
그래서 요소들이 프로토콜을 채택하게되려면 요소의 타입이 프로토콜을 채택받아야 적절하다고 판단했고 그거에 적합한것이 제네릭을 사용하는 것이라고 생각했습니다.

# 고민&조언을 얻고싶은 부분
- CalculateItemQueue<Int>를 사용할때 Int가 CalculateItem프로토콜을 채택하지않으면 에러가 발생합니다. 그래서 extension을 구현해주었는데 연산자까지 받는다고하면 String타입을 사용하기도하고 그외 다른타입까지고 들어온다고하면 모든 데이터기본타입에 extension으로 CalculateItem프로토콜을 채택해주어야하나? 라는 의구심이들었습니다. 이렇게사용했을때는 제네릭의 기능을 원활하게 사용하지 못하는것같기도하고
혹시 extension을 모두 만들어주지않고 어떠한 데이터타입이드러와도 CalculateItem프로토콜을 채택하게끔 코드를 구현해볼수 있는 방법은 없을까요 ?

- 제가 위에서 LinkedList에 기능설명을 이해한대로 작성해보았는데요 혹시나 잘못 이해하고있거나 애매해보이는 부분이있으면 이야기해주시면 감사하겠습니다.

- CalculateItemQueue내 ieEmpty를 구현할때 count == 0이지않는이상은 비어있는게 맞다고판단하여 isEmpty기능은 따로구현하지않았습니다. 그런데 혹시 제가 보지못하고있는 문제가 발생할 수도 있지않을까?라는생각에 뭔가 찝찝한데요 
이렇게 구현해도 문제없을까요 ?

- TDD방식으로 코드를 작성하였습니다. 먼저 실패하는 테스트코드를 작성하고 그 다음 기능을 정상적으로 동작할 수 있게 작성을 했는데 적절하게 작성을 했는지 잘 모르겠습니다. 혹시 조언해주실부분이 있을까요 ?

2022-03-17 03:56 UTC, 1Consumption requested changes
안녕하세요 쿼카~~ 잘부탁드립니다. 
고생 많으셨어요.

코드의 컨벤션에 어느정도 기준이 있고, 어떻게하면 가독성 좋게 짤까를 고민한게 보이는 코드였습니다!
또한 각 객체의 역할분배도 적당하게 잘 된거같아요.👏 
테스트코드에서 메소드 이름을 한글로 지은거도 좋았습니다!

링크드리스트를 이해하고 구현하시느라 조금 오래걸렸지만, 괜찮아요. 회피하지 않고 구현한 점에서 정말 칭찬드리고싶어요.

아래는 질문주신 점에 대한 제 생각입니다.

> CalculateItemQueue를 사용할때 Int가 CalculateItem프로토콜을 채택하지않으면 에러가 발생합니다. 그래서 extension을 구현해주었는데 연산자까지 받는다고하면 String타입을 사용하기도하고 그외 다른타입까지고 들어온다고하면 모든 데이터기본타입에 extension으로 CalculateItem프로토콜을 채택해주어야하나? 라는 의구심이들었습니다. 이렇게사용했을때는 제네릭의 기능을 원활하게 사용하지 못하는것같기도하고
혹시 extension을 모두 만들어주지않고 어떠한 데이터타입이드러와도 CalculateItem프로토콜을 채택하게끔 코드를 구현해볼수 있는 방법은 없을까요 ?

`Any` 라는 타입이 있어요. 말 그대로 어떤 타입이든 들어올 수 있습니다. 하지만 이 타입을 사용하게 되면 어떤 타입이 들어올지 모르기 때문에 매번 런타임에 확인해야한다는 단점이있어요. 따라서 `CalculateItem`을 채택한 타입만 들어올 수 있도록 제약사항이 필요한거고요. 결론을 말하자면 쿼카가 말한건 아무래도 안되지싶어요.

> 제가 위에서 LinkedList에 기능설명을 이해한대로 작성해보았는데요 혹시나 잘못 이해하고있거나 애매해보이는 부분이있으면 이야기해주시면 감사하겠습니다.

잘 이해하셨습니다! 👍 

> CalculateItemQueue내 ieEmpty를 구현할때 count == 0이지않는이상은 비어있는게 맞다고판단하여 isEmpty기능은 따로구현하지않았습니다. 그런데 혹시 제가 보지못하고있는 문제가 발생할 수도 있지않을까?라는생각에 뭔가 찝찝한데요
이렇게 구현해도 문제없을까요 ?

사실 Queue에서는 LinkedList가 어떻게 데이터를 관리하는지 궁금하지 않아요. LinkedList는 데이터를 관리하는 역할일 뿐이고 Queue는 언제든지 데이터를 관리하는 타입을 다른거로 바꿀수도 있습니다. 따라서 count가 있을수도 있고 없을수도 있다는 뜻입니다. 이럴때는 어떻게 해야할까요? Queue가 구체타입을 알지 않고 어떤 인터페이스만 가진 프로토콜만 알게 하면 어떨까요?

> TDD방식으로 코드를 작성하였습니다. 먼저 실패하는 테스트코드를 작성하고 그 다음 기능을 정상적으로 동작할 수 있게 작성을 했는데 적절하게 작성을 했는지 잘 모르겠습니다. 혹시 조언해주실부분이 있을까요 ?

테스트를 위한 테스트를 작성한거같아요. 테스트 코드를 작성할 때 정말 필요한 테스트인가? 를 한번 생각해보셨으면 좋겠어요.
또한 테스트 파일이 관리가 안된 느낌입니다. Queue의 테스트와 LinkedList의 테스트가 하나의 파일에서 이루어지고 있어요.

-----------------------------------

나머지는 코멘트에 남겼으니 확인해주세요!

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Extension/extension.swift
> +}
파일명에 어떤 extension인지 명시가 되면 좋을거같아요.

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    private var queue = LinkedList<T>()
이름이 queue가 맞을까요?
그리고 var네요! 값이 바뀔일이 있나요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    }
연산프로퍼티로 선언한 이유가 있을까요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    }
mutating이 붙어야하나요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/LinkedList.swift
> +        tail = lastNode
if 문에서 return으로 종료하지말고, else문으로 바꾸면 어떨까요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/LinkedList.swift
> +        if head == nil { return nil }
guard문의 return은 개행을 하고 여기는 개행을 하지 않았네요. 특별한 기준이 있을까요?

그리고 `head == nil` 이 조건이 여러 메소드에서 쓰이는듯 합니다. 따로 메소드로 뺄 수 있을거같아요.

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/LinkedList.swift
> +        head = head?.next
if문이 필요할까요? 아래의 코드처럼 줄일 수 있지 않을까요?

```suggestion
        let data = head?.data
        head = head?.next
```

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/Node.swift
> +final class Node<T> {
final 키워드는 왜 붙여줬나요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/SceneDelegate.swift
>  }
사용하지 않는 주석을 지우거나 현재와 맞지 않는 주석을 수정한게 좋네요 👍

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var stringQueue: CalculateItemQueue<String>!
강제언래핑을 해준 이유가 있을까요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
이 두 메소드의 역할은 무엇인가요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
이건 뭐를 테스트한건가요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/Calculator/Model/LinkedList.swift
> +    var tail: Node<T>?
외부에서 head나 tail을 set하는건 좋지않아보여요. private(set)을 통해 외부에서 set은 못하지만 get은 가능하도록 허용해줄 수 있습니다.

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        sut.head = Node(data: 1, next: nil)
append를 사용하는게 맞지 않을까요?

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        sut.head = Node(data: 1, next: Node(data: 1, next: nil))
head에 직접 접근하는게 아니라, LinkedList의 기능을 테스트해야합니다. 이건 하드코딩 같은데요.

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
이 테스트와 `test_LinkedList인스턴스가data와next까지값가지고있을때_count2가나오는지()`의 차이는 뭔가요? 테스트를 위해 테스트를 짜면 안됩니다. 정말 필요한 테스트인지 생각 해보세요.

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(result, 3)
테스트할 데이터를 아래와 같이 관리하면 어떨까요? 혹여나 테스트할 데이터가 바뀌어도 numbers만 바꾸면되니까요.

```suggestion
        let numbers: [Int] = [1, 2, 3]
        numbers.forEach(sut.append(data:))        
        let result = sut.count
        
        XCTAssertEqual(result, numbers.count)
```

2022-03-17 03:56 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
모두 같은 테스트 같아요. 정말 필요해서 짠 테스트가 맞나요?

2022-03-17 08:05 UTC, Quokkaaa commented on Calculator/Calculator/Extension/extension.swift
> +}
dataType.swift파일로 네이밍 수정해보았습니다.

2022-03-17 08:11 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    private var queue = LinkedList<T>()
큐라는 구조내부에 있는 list를 가르키는 name이 더 정확할것같다는 생각이듭니다 !! nodes로 수정해봤어요!
프로퍼티의 값이 큐 내부의 메서드들로 인해 수정삭제가 될 수 있다는 것에 var로 설정하였으나 class가 가진 특정으로인해 let으로 수정해도 무방할것같습니다!

2022-03-17 08:12 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    }
메서드는 매개변수를 사용할 수 있지만 현재는 그럴필요가없으며 간단한 코드라서 연산프로퍼티로 사용했습니다.

2022-03-17 08:16 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    }
붙여줘야한다고 생각했는데 필요가없네요.. 이유는 class타입으로 프로퍼티가 초기화되었기때문인것같습니다.
구조체는 내부 프로퍼티의 값이 변경된다는것을 컴파일러에게 알려주는 역할로 mutating을 사용하는것같습니다만
class타입은 값의 주소를 참조하기때문에 값 변경이 가능해 mutating이라는 기능이 없어 사용할 필요가 없는것같아요

2022-03-17 08:18 UTC, Quokkaaa commented on Calculator/Calculator/Model/LinkedList.swift
> +        tail = lastNode
else문을 넣는것이 코드를 읽을때 더 자연스럽게 읽히는것같아요!! 수정하겠습니다.

2022-03-17 08:49 UTC, Quokkaaa commented on Calculator/Calculator/Model/LinkedList.swift
> +        if head == nil { return nil }
어림잡아서 길면 개행하고 그렇지않으면 40번줄처럼 작성을 했던것같습니다. 개행을 해주는게 좋을까요 ?
그리고 head == nil을 메소드로 빼는그림이 잘 상상이 되질않는데 어떤 식인지 알수있을까요? ?

2022-03-17 09:07 UTC, Quokkaaa commented on Calculator/Calculator/Model/LinkedList.swift
> +        head = head?.next
head가 nil일 경우에는 nil을 반환하는 코드는 필요하지않을까 싶어요!!

2022-03-17 09:11 UTC, Quokkaaa commented on Calculator/Calculator/Model/Node.swift
> +final class Node<T> {
상속을 할필요가 없다고 판단했고 final을 붙였을때 하위클래스의 최종 메서드, 속성 또는 하위 스크립트를 재정의하려는 모든 시도는 컴파일 시간오류로 보고가 되기때문에 final을 붙임으로써 컴파일 시간을 줄일 수 있어 성능에 도움이된다고 [공식문서](https://docs.swift.org/swift-book/LanguageGuide/Inheritance.html#:~:text=%ED%81%B4%EB%9E%98%EC%8A%A4%20%EC%A0%95%EC%9D%98(%20)%EC%97%90%EC%84%9C%20%ED%82%A4%EC%9B%8C%EB%93%9C%20final%EC%95%9E%EC%97%90%20%EC%88%98%EC%A0%95%EC%9E%90%EB%A5%BC%20%EC%9E%91%EC%84%B1%ED%95%98%EC%97%AC%20%EC%A0%84%EC%B2%B4%20%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A5%BC%20final%EB%A1%9C%20%ED%91%9C%EC%8B%9C%ED%95%A0%20%EC%88%98%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4%20.%20%EC%B5%9C%EC%A2%85%20%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A5%BC%20%ED%95%98%EC%9C%84%20%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A1%9C%20%EB%A7%8C%EB%93%A4%EB%A0%A4%EB%8A%94%20%EB%AA%A8%EB%93%A0%20%EC%8B%9C%EB%8F%84%EB%8A%94%20%EC%BB%B4%ED%8C%8C%EC%9D%BC%20%EC%8B%9C%EA%B0%84%20%EC%98%A4%EB%A5%98%EB%A1%9C%20%EB%B3%B4%EA%B3%A0%EB%90%A9%EB%8B%88%EB%8B%A4.classfinal%20class)에서 확인했습니다.

2022-03-17 09:26 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var stringQueue: CalculateItemQueue<String>!
테스트할때 수월하게 하기 위함입니다.
강제옵셔널이아닌 기본옵셔널 ? 표시도 가능했으나 이럴 경우에는 값을 사용할때마다 옵셔널로 맞춰서 비교해주거나 옵셔널을 벗겨서 값을 꺼내와야하기때문에 !로 사용하게된것같습니다.

2022-03-17 09:28 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
`setUpWithError`메서드는 test case가 실행되기 전마다 호출되어 각 테스트가 모두 같은 상태와 조건에서 실행할 수 있게해주고
`tearDownWithError`메서드는 test실행이 끝난 후 마다 호출되는 메서드이며 setUpWithError에서 설정한 값들을 해제할때 사용합니다.

2022-03-17 09:32 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
제가 구현한 타입을 이용해서 초기화가 잘되는지 확인해보고 싶었습니다. 근데 어떻게보면 너무 당연한것같아 굳이 해줄필요가 있나 ? 싶긴합니다..

2022-03-17 10:06 UTC, Quokkaaa commented on Calculator/Calculator/Model/LinkedList.swift
> +    var tail: Node<T>?
확인 감사합니다. private으로 은닉화 적용하겠습니다.
궁금한게있는데요 private(set) 을하거나 private으로 설정해서 프로퍼티에 접근할 수 있게해주는 메서드를 만드는 방법도 있을것같은데 이왕이면 후자로 하는게 좋을까요 ?

2022-03-17 10:11 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        sut.head = Node(data: 1, next: nil)
맞습니다. append메서드를 먼저 테스트했으면 좋았을텐데 append테스트하기 전이라서 그랬던것같습니다!

2022-03-17 10:11 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        sut.head = Node(data: 1, next: Node(data: 1, next: nil))
private 은닉화를 head와 tail에 적용해주고 메서드로 값을 가져오는 방식으로 수정했습니다!

2022-03-17 10:21 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
정말 테스트를 위한 테스트를 짰던것같네요 ㅜㅜ 더 고민해보겠습니다.

2022-03-17 10:24 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(result, 3)
hug!! 이렇게 사용가능한지 처음알았습니다!
sut.append(data:))메서드내에 값할당을 생략해도 되는 이유가 궁금합니다.

2022-03-17 10:26 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
음,, append메서드를 어떻게 짜면 좋을지 감이안오다보니 테스트하는 숫자의 범위를 늘렸던것같습니다..
혹시 정말 필요한지에대한 테스트를 짜기위한 좋은 방법이 있을까요 ?

2022-03-18 01:49 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/173/commits/a34b518638685c5d0dd9aef5215f3bd67391053f

2022-03-18 01:50 UTC, Quokkaaa commented on Calculator/Calculator/Extension/extension.swift
> +}
https://github.com/yagom-academy/ios-calculator-app/pull/173/commits/213b3089e2fb2c9f7a0e4492e8c474241a458e48

2022-03-18 01:51 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculateItemQueue.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/173/commits/a34b518638685c5d0dd9aef5215f3bd67391053f

2022-03-18 01:51 UTC, Quokkaaa commented on Calculator/Calculator/Model/LinkedList.swift
> +        tail = lastNode
https://github.com/yagom-academy/ios-calculator-app/pull/173/commits/f2c15e25261dbeba881b58d36918c8f24d2c568f

2022-03-18 01:54 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var stringQueue: CalculateItemQueue<String>!
기능을 테스트하기위해 값이 있다는 전제하에 하기때문에 어느정도 생략할 수 있고 만일 런타임이 발생하면 로직을 수정해줄 수 도 있기때문에 !를 사용했습니다.

2022-03-18 01:55 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/173/commits/c7e296ee3a1259e373e8a3e1f82074075c6533e7

2022-03-18 01:55 UTC, Quokkaaa commented on Calculator/Calculator/Model/LinkedList.swift
> +    var tail: Node<T>?
https://github.com/yagom-academy/ios-calculator-app/pull/173/commits/c7e296ee3a1259e373e8a3e1f82074075c6533e7

2022-03-18 02:05 UTC, Quokkaaa commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/173/commits/c7e296ee3a1259e373e8a3e1f82074075c6533e7

2022-03-18 12:44 UTC, merged