계산기 [STEP 1] Doogie
yagom-academy/ios-calculator-app pull request #174
Opened 2022-03-16 06:13 UTC by doogie97

@wonhee009

안녕하세요 라자냐!

Queue라는 것과 자료 구조라는 것에 대해 처음 접하다 보니 공부할 시간이 많이 부족해 첫 번째 PR을 오늘 오후까지로 요청드렸습니다.
코드를 그냥 만드는 것 만 하는 건 얼마 안 걸릴 것 같았지만 확실하게 이해를 하고 작성하는 게 좋을 것 같아 조금 늦은 시간으로 말씀드린 점 양해 부탁드리며 이번 프로젝트 잘 부탁드립니다!

# UML
![Untitled](https://user-images.githubusercontent.com/82325822/158527028-2cecf30a-22d6-4d2c-8cda-c4274f70763b.jpg)

# 고민한점 및 해결 방법
#### `LinkedList` vs `DoubleStack`
- `DoubleStack` 과 비교해 `LinkedList` 의 장점은 요소 중간의 값에 접근하기가 더 쉽고 빠른 것이라고 생각합니다. 그런데 이번 계산기 프로젝트에서는 중간 값에 접근할 필요도 없으니 해당 이점을 사용하지 않는다면 공간복잡도가 더 낮은 `DoubleStack`을 사용하는것이 좋다고 생각했습니다. (+ EC버튼은 가장 나중에 들어온 요소를 제거해야 하기에 이 부분에서도 `DoubleStack`이 더 유리하다고 판단)

#### `DoubleStack` 에서 고민한 점
1. `dequeue` 호출 시 `enqueueList`를 리버스 해서 요소를 뺀뒤 그 리스트를 다시 리버스 해서 `enqueueList`에 할당해줘야 하는것이 아닌가? 
>  적어도 이 계산기 프로젝트에서 `dequeu` 는 = 을 눌렀을 때 실행되므로 = 을 누른 이후에는 `enqueue` 가 사용될 일이 없다고 판단해 리버스 해서 뺀 리스트를 다시 `enqueueList` 에 할당해주는 과정을 하지 않았습니다
2. `dequeue`를 할때 리버스를 해서 빼면 되는데 왜 처음부터 굳이 `dequeueList`를 만들어두는 이유는 무엇일까?
> `dequeue`를 할 때마다 리버스를 해주면 요소가 여러개일 때 시간복잡도가 늘어남, 1번과 같은 이유로 한번 `dequeue`가 시작되면 `enqueue`를 할 일이 없으며 이에 따라 `dequeue`시작시 `inqueueList`를 리버스해 `dequeueList`에 할당해주고  `inqueueList`를 비워주는 과정으로 진행

# 조언받고 싶은 내용
STEP1을 구현하면서 제가 어떤 기능을 고민해서 구현했다고 하기보다는 '여러가지 공식화된 자료구조들 중 하나의 공식을 사용했다' 라고 생각합니다.
그렇기에 사소한 것에도 의문을 품고 ‘얘가 이걸 제대로 알고 있는게 맞나?’ 하는 식의 질문을 많이 던져주신다면 감사하겠습니다!

2022-03-16 08:29 UTC, wonhee009 requested changes
@doogie97 스텝1 수고하셨습니다!🎉
큐를 구현하기 위해 많은 생각을 한게 느껴졌습니다!
코드에 몇몇 코멘트 남겨두었으니 확인 부탁드립니다🙏

2022-03-16 08:29 UTC, wonhee009 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var count: Int { dequeueList.isEmpty ? enqueueList.count : dequeueList.count }
```suggestion
   var count: Int {
      return dequeueList.count + enqueueList.count
   }
```
이렇게 두 리스트 수를 다 더해줘야하지 않나요?.?

2022-03-16 08:29 UTC, wonhee009 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var last: item? { enqueueList.last }
`enqueeueList`가 비어있을때도 있을텐데 `first`, `last`를 보장할 수 있을까요?.?

2022-03-16 13:28 UTC, doogie97 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var last: item? { enqueueList.last }
아하!
dequeue를 하게 되면 enqueueList는 비워지게 되니 해당 코드는
```swift
    var first: item? { dequeueList.isEmpty ? enqueueList.first : dequeueList.last }
    var last: item? { dequeueList.isEmpty ? enqueueList.last : dequeueList.first }
```
이렇게 수정되는게 맞는 것 같습니다!

2022-03-16 13:43 UTC, doogie97 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var count: Int { dequeueList.isEmpty ? enqueueList.count : dequeueList.count }
`dequeueList`가 비어있다면 `enqueueList`에만 요소가 있을 것이고 `dequeueList`가 비어있지 않는 상황이라면 dequeue가 실행되어 `enqueueList`를 리버스 해 `dequeueList`에 할당해 주고 `enqueueList`를 비워준 상황일 것입니다.
위 근거로 `dequeueList` 가 비어있다면 `enqueueList` 의 count를, `dequeueList` 가 비어있지 않다면 `dequeueList`의 count를 할당해 주도록 구현했습니다.
아울러, 라자냐가 제안해 준 코드를 보고 생각해보았을 때 결국에는 n + 0 이거나 0 + n 이 될거라고 생각해 결과적으로는 같은 결과가 나올 것이라고 생각하는데 혹시 제가 놓친 무언가가 있을까요??
만약 결과적으로 같은 값이 나오는게 맞다면 두 코드 중에서는 어떤게 기능적으로 더 옳은 코드일지 여쭤보고 싶습니다!

2022-03-16 23:56 UTC, wonhee009 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var count: Int { dequeueList.isEmpty ? enqueueList.count : dequeueList.count }
- enqueue: enqueueList로만 append
- dequeue: dequeueList로만 pop
이렇게 이해했는데요.

enqueue(1) -> enqueue(2) -> enqueue(3) -> dequeue()이렇게 호출했다면
enqueueList: empty
dequeueList: 2, 1 (3은 pop되었음)
이렇게 들어가 있을거 같은데요.

이 상태에서 enqueue(4)를 호출한다면
enqueueList: 4
dequeueList: 2, 1
이렇게 있지 않을까요?

2022-03-16 23:57 UTC, wonhee009 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var last: item? { enqueueList.last }
dequeueList가 비어 있을때 enqueueList.first가 nil일 수 있지 않을까요?.?

2022-03-17 00:22 UTC, doogie97 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var count: Int { dequeueList.isEmpty ? enqueueList.count : dequeueList.count }
이번 프로젝트인 계산기 어플의 경우 `=` 을 누르면 dequeue가 바로 실행되서 요소들이 다 빠져나가기 전에(연산이 완료되기 전에)는 enqueue를 할 일이 없을 것이라고 생각해 위와 같이 작성했는데 계산기라는 생각을 제외하고 queue라는 자체만 놓고 본다면 넣었다 뺐다 할 수 있는 거니 제안해 주신 코드가 더 적합해 보입니다
아울러, " `=` 을 누르면 전부 dequeue가 될 것이다!" 라는 생각은 다음 스텝이 진행돼 봐야 더 고민해 볼 수 있는 내용이므로 현재 상황에서는 라자냐가 제안해 준 코드로 변경할 예정입니다!

2022-03-17 00:31 UTC, doogie97 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var last: item? { enqueueList.last }
네 맞습니다. 지금 생각으로는 first last를 계산기에서 사용할 생각은 없고 enqueueList 와 dequeueList가 pravaite으로 선언되어 있다보니 test를 할 때 값이 잘 들어갔는지 잘빠지는지를 맨 앞과 맨 뒤의 요소를 통해 확인하기 위한 용도로만 사용하고 있어 위 코드처럼 list가 비어있다면 nil을 반환해 주는 것 또한 의도를 하고 만들었기에 추후에 삭제가 될 수도 있는 코드입니다.
(nil이 반환된다면 enqueue 혹은 dequeue 함수의 오류라고 판단하기 위한 용도?)

혹시 제가 질문의 의도를 제대로 파악한 것이 맞을까요..??

2022-03-18 00:14 UTC, closed without merging