계산기 [STEP1] Eddy
yagom-academy/ios-calculator-app pull request #176
Opened 2022-03-16 14:35 UTC by kimkyunghun3

안녕하세요 @yoo-kie 😄
많이 늦어졌네요ㅜㅜ 괜찮을 때마다 하려고 했는데 공부도 하고 하려니 시간이 많이 늦어졌습니다!
첫 번째 리뷰 잘 부탁드립니다 :)

## 주요 함수
`CalculatorDoublyLinkedList` : 양방향 연결리스트 활용하여 노드를 넣고, 빼고, 수를 세는 클래스
`QueueLinkedList` : 데이터르 저장하는 방식으로 Queue를 이용하여 양뱡형연결리스트로 데이터를 보내는 클래스
`Node` : 양뱡향연결리스트에 필요한 노드 정보 클래스 
`CalculateItem`: 추후 사용할 프로토콜

## 고민한 점
먼저 Queue를 활용하고 그 내부를 어떤 것을 사용할지 고민했습니다.
배열, 스택 2개, 단방향 연결리스트, 양방향 연결리스트 4가지 방식이 존재한다는 것을 알게 되었습니다.

처음에는 배열로 구현하면 쉽겠구나? 생각했는데 요소를 제거할 때 문제가 있음을 파악했습니다. 제거할 때 하다 요소가 한칸씩 떙겨지기 때문에 오버헤드가 발생하여 효율이 떨어진다는 것을 알게되었습니다.
다음으로 스택을 2개로 구현하는 것인데 배열로 구현한 큐( QueueArray ) 와 비교하면
deQueue() 메소드의 수행속도가 빠르다는 것을 공부하게 되었습니다  ( O(1) > O(n) )
더블 연결리스트로 구현한 큐 ( QueueLinkedList ) 와 비교하면
Space Complexity ( 공간복잡성 ) 측면에서 연결리스트 보다 더 좋다고 하네요!
'더블스택  으로 구현한 큐'( QueueDoubleStack ) 의 공간 복잡성 : 빠름.
하지만 구현하는 것에서 비효율적이라고 판단해서 이를 배제했습니다.

그래서 마지막으로 단방향, 양방향 연결리스트 중에 고민 했는데 우리는 탐색은 필요없고 마지막 입력한 것을 제거하는 것이 필요한 것을 보고 양방향 연결리스트를 하면 좋을 것 같다고 생각해서 구현하게 되었습니다.

그래서 저의 고민은
- 실제 개념과 코드를 보게되니 짜는데에는 무리가 없었습니다. 하지만 교과서를 보고 문제를 푼느낌이라고 할까나, 최대한 안보고 개념만으로 짜려고 했으나 쉽지 않는 부분은 고민 끝에 일부 예제 코드를 보면서 했음에도 찝찝하긴 했습니다. 이런 부분은 다시 짜보며 연습해보며 익숙해지는 것이 맞겠죠?
- Test 코드를 먼저 작성하고 코드를 짜려고 하니 더 어려웠습니다. 먼저 어느 수준에서 테스트코드를 해야할지 감이 안와서 처음에는 enque하나 찾아보고, dequeue하나 해보고 이런식으로 했는데, 어느 단위로 쪼개서 테스트 코드를 작성할지 아직도 감이 오지 않습니다. 
- 자료구조에서 큐와 양방향연결리스트를 사용한 것인데 큐는 유저의 입력을 처리해주는 방식인 것이고, 실제 유저의 입력이 내부적(개발자만 아는)으로 처리는 양방향연결리스트로 생각한 것인데 이런 생각이 맞고, 그에 맞는 코드 작성인건지 궁금합니다.
- CalculateItem 이라는 빈 프로토콜을 작성하라고 했는데, 저는 아직까지도 이 프로토콜이 현재 STEP 1에서 왜 필요한지 의문이 듭니다. 첨에 들었던 생각은 이곳에서 연산이 이루어지면 되겠다 생각했는데, 현재에서는 필요해보이지 않아서 단순하게 채택정도만 했는데 혹시 제가 잘못된 생각을 하고 있는 것인가요?

2022-03-17 16:24 UTC, yoo-kie requested changes
안녕하세요 Eddy!

코드가 전반적으로 깔끔하고 자료구조에 대해서 공부해서 고민해보시고 코드를 작성하신 느낌을 받았습니다:)👍

그리고 아래에서 추가적인 의견 남겼습니다!

## 주요 함수
`CalculatorDoublyLinkedList` : 양방향 연결리스트 활용하여 노드를 넣고, 빼고, 수를 세는 클래스
`QueueLinkedList` : 데이터르 저장하는 방식으로 Queue를 이용하여 양뱡형연결리스트로 데이터를 보내는 클래스
`Node` : 양뱡향연결리스트에 필요한 노드 정보 클래스 
`CalculateItem`: 추후 사용할 프로토콜

## 고민한 점
먼저 Queue를 활용하고 그 내부를 어떤 것을 사용할지 고민했습니다.
배열, 스택 2개, 단방향 연결리스트, 양방향 연결리스트 4가지 방식이 존재한다는 것을 알게 되었습니다.

처음에는 배열로 구현하면 쉽겠구나? 생각했는데 요소를 제거할 때 문제가 있음을 파악했습니다. 제거할 때 하다 요소가 한칸씩 떙겨지기 때문에 오버헤드가 발생하여 효율이 떨어진다는 것을 알게되었습니다.
다음으로 스택을 2개로 구현하는 것인데 배열로 구현한 큐( QueueArray ) 와 비교하면
deQueue() 메소드의 수행속도가 빠르다는 것을 공부하게 되었습니다  ( O(1) > O(n) )
더블 연결리스트로 구현한 큐 ( QueueLinkedList ) 와 비교하면
Space Complexity ( 공간복잡성 ) 측면에서 연결리스트 보다 더 좋다고 하네요!
'더블스택  으로 구현한 큐'( QueueDoubleStack ) 의 공간 복잡성 : 빠름.
하지만 구현하는 것에서 비효율적이라고 판단해서 이를 배제했습니다.

그래서 마지막으로 단방향, 양방향 연결리스트 중에 고민 했는데 우리는 탐색은 필요없고 마지막 입력한 것을 제거하는 것이 필요한 것을 보고 양방향 연결리스트를 하면 좋을 것 같다고 생각해서 구현하게 되었습니다.

`
🐸 더블 연결리스트로 구현한 큐가 공간복잡도에서 빠르다는 의미가 어떤건지 설명해주실 수 있나요?
그리고 코드에서 직접 QueueLinkedList를 선언하여 enqueue와 dequeue를 하고 모든 아이템이 dequeue됐을때 isEmpty를 출력해보셨을까요? 그랬을 때 원하는 결과값이 나오셨나요?
`

그래서 저의 고민은
- 실제 개념과 코드를 보게되니 짜는데에는 무리가 없었습니다. 하지만 교과서를 보고 문제를 푼느낌이라고 할까나, 최대한 안보고 개념만으로 짜려고 했으나 쉽지 않는 부분은 고민 끝에 일부 예제 코드를 보면서 했음에도 찝찝하긴 했습니다. 이런 부분은 다시 짜보며 연습해보며 익숙해지는 것이 맞겠죠?

`🐸 아:) 말씀하신대로 코드에서 이론적인 이해는 하셨지만 로직이 정상적으로 동작하는지 혹시 확인해보셨을까요? 그리고 전반적으로 참조관계를 고려하면서 코드 개선이 필요해보입니다.`

- Test 코드를 먼저 작성하고 코드를 짜려고 하니 더 어려웠습니다. 먼저 어느 수준에서 테스트코드를 해야할지 감이 안와서 처음에는 enque하나 찾아보고, dequeue하나 해보고 이런식으로 했는데, 어느 단위로 쪼개서 테스트 코드를 작성할지 아직도 감이 오지 않습니다.

`🐸 프로젝트에서 필요한 기능(이벤트)들을 생각해보시면 좋을 것 같아요! 그리고 그 이벤트를 정상적으로 동작하는지를 유닛테스트로 작성해보시면 어떨까요?`

- 자료구조에서 큐와 양방향연결리스트를 사용한 것인데 큐는 유저의 입력을 처리해주는 방식인 것이고, 실제 유저의 입력이 내부적(개발자만 아는)으로 처리는 양방향연결리스트로 생각한 것인데 이런 생각이 맞고, 그에 맞는 코드 작성인건지 궁금합니다.

`🐸 흠 Eddy가 큐에서 양방향연결리스트를 사용하셨을 때 작성하신 이유가 있었을텐데요! 프로젝트 전반적으로 큐의 활용을 생각해봤을 때 활용도가 좋았는지를 고민해주시면 좋을 것 같아요.`

- CalculateItem 이라는 빈 프로토콜을 작성하라고 했는데, 저는 아직까지도 이 프로토콜이 현재 STEP 1에서 왜 필요한지 의문이 듭니다. 첨에 들었던 생각은 이곳에서 연산이 이루어지면 되겠다 생각했는데, 현재에서는 필요해보이지 않아서 단순하게 채택정도만 했는데 혹시 제가 잘못된 생각을 하고 있는 것인가요?

`🐸 기능서에서 CalculateItem은CalculatorItemQueue에서 다루는 요소가 준수한다고 요구되어 있는데요. 왜 요소가 CalculateItem을 준수해야하는지를 생각보시면 좋을 것 같습니다.`

2022-03-18 01:57 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculateItem.swift
> +
네 추후에도 프로토콜 내에서 기능이 없을 것이라고 예상해서
 // empty를 추가했습니다

2022-03-18 01:58 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculatorDoublyLinkedList.swift
> +class CalculatorDoublyLinkedList<T>: CalculateItem {
아 제가 제대로 읽지 못한 실수를 했네요 죄송합니다! 이름을 임의로 바꿔서 의미를 더 정확하게 하자고 했는데 다시 바꾸고 CalculateItem 준수하도록 바꿨습니다! 감사합니다

2022-03-18 01:59 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculatorDoublyLinkedList.swift
> +        return false
아 생각해보니 조건문 필요 없이 저 경우에 true가 될 것이고 아니면 false가 될 것이기에 간략하게 바꿀 수 있겠군요!

2022-03-18 02:04 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculatorViewController.swift
> +class CalculatorViewController: UIViewController {
아 이를 상속할 가능성이 없을 것 같습니다. 그래서 final를 써서 상속될 가능성이 없게 하여 메모리 할당의 비효율성을 줄일 수 있겠군요! Dynamic Dispatch는 상속에서 오버라이딩 가능성 때문에 런타임 시에 vTable를 찾아 메서드를 실행하기 때문에 성능상 손해를 봅니다.

상위 클래스에서 찾아야할지 오버라이딩 한 하위 클래스에서 찾아야할 지 런타임 시점에서 vTable 을 통해 찾아야해서 오버헤드가 발생할 수 있습니다.

그러나 만약 상속가능성이 없는 클래스나 오버라이딩이 되지 않는 메서드나 프로퍼티의 경우에는 굳이 Dynamic dispatch로 동작할 필요 없이 static dispatch로 바꿔주게 되면

2022-03-18 02:07 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculatorViewController.swift
> -
제가 보았던 컨벤션 조건으로는 메소드 위의 한칸을 띄어주는 것이라고 해서 저는 이것을 지키려고 했고, 이곳 외에 다른 곳에서도 한 칸씩 띄어서 동일하게 하려고 노력했습니다!

2022-03-18 02:20 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculatorDoublyLinkedList.swift
> +    public init() { }
아 이것을 처음에 작성한 것은 테스트 코드 작성 시 초기화가 되지 않았다는 에러가 계속 있었습니다.  Class 'CalculatorTests' has no initializers 와 같은 에러가 생겼는데 이는 실제로 sut 변수에 사용하려는 클래스 타입을 표시해줄 때 이에 대한 옵셔널 처리를 해주지 않아서 생기는 에러였습니다. 그래서 이를 강제 언래핑하거나 옵셔널로 해주면 해결되었기에 이 부분에서는 데이터가 꼭 들어온다고 생각했기에 강제 언래핑으로 했습니다. 그 이후의 저의 오해에 대한 코드 제거가 필요했던 것인데 안한 저의 실수같습니다! 
근데 처음 드는 생각은 이 클래스 내에서 초기화가 없다는 것인데, sut변수에 타입을 지정해주고 이를 설정해주면 초기화가 생기는 것이므로 에러가 해결된다고 생각했습니다. 이렇게 생각한 방향이 맞는건지 궁금합니다.

2022-03-18 02:21 UTC, kimkyunghun3 commented on Calculator/Calculator/QueueLinkedList.swift
> +    public init() { }
이것도 위의 설명으로 제거되어야할 코드라고 생각합니다!

2022-03-18 02:27 UTC, kimkyunghun3 commented on Calculator/Calculator/QueueLinkedList.swift
> +    }
아 이해했습니다. 만약 이 위의 코드인 resetAll 메서드 같은 경우에는 리스트에 있는 모든 것을 리셋시키기 때문에 기능을 수행하는 것이므로 메소드로 남는게 옳다고 생각합니다.
```swift
    public func resetAll() {
        return calculateList.resetAll()
    }
```
하지만 단순히 Node의 수를 반환하는 메서드라면 이는 연산프로퍼티로 하는 이유는 정의에서 확인 해보았습니다.
저장 프로퍼티와 달리 저장 공간을 갖지 않고, 다른 "저장 프로퍼티"의 값을 읽어 연산을 실행하거나, 프로퍼티로 전달받은 값을 다른 프로퍼티에 저장한다 
라는 정의가 있기에 기능 수행보다는 읽어 연산하여 이를 활용해서 다른 프로퍼티에서 활용하는 용도가 크므로 연산 프로퍼티를 사용하는지 맞다고 보았습니다.

2022-03-18 04:54 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculatorDoublyLinkedList.swift
> +    public var isEmpty: Bool {
다른 파일이나 모듈들에서 코드의 일부를 접근할 수 있는 것을 제한한다.

이 기능을 통해 코드의 내부 구현 사항을 숨길 수도 있고 선호하는 인터페이스를 특정해서 이를 접근하고 사용할 수 있게한다.

클래스, 구조체, 열거형, 프로퍼티, 메소드, 초기화, 서브스크립트 등등에 모두 다 접근제어를 정해줄 수 있다.

- Open, public

정의한 모듈 내에서 소스내에서 모든 entites에 접근가능한 수준이다. 또한 다른 모듈에서의 소스코드에서 이를 import하면 접근가능하다. 이는 특정한 곳에서의 접근 뿐만아니라 모든 곳에서 접근이 가능하도록 할 때 사용한다.

- Internal

접근제어를 쓰지 않으면 자동으로 선언되는 기본 접근수준으로, 모듈의 밖에서의 코드에서는 이 코드를 접근할 수 없지만 동일한 모듈에서의 코드에 대해서는 접근이 가능하다. 이는 모든 곳에서 보다는 모듈 안에서만으로 제한할 때 사용한다.

- File-private

정의내린 소스파일에서만 엔티티 사용을 제한한다. 전체 파일 내에서 기능들의 상세를 사용할 때 내부 구현에 대한 것을 숨길 수 있다. 이는 정의 내린 소스 파일로만 제한할 때 사용한다.

- private

동일한 파일에서 구현의 확장들, 구현 내부의 엔티티로만 사용을 제한한다. 하나의 선언 내에서 기능들의 상세를 사용할 때 내부 구현에 대한 것을 숨길 수 있다. 제일 좁은 의미로 파일 내에서 구현이 이루어지는 메소드 등에서만으로 제한할 떄 사용한다.

그래서 기본 접근제어자는 `internal` 입니다. 이 이유에 대해 혼자 생각을 해봤는데, 외부 모듈의 접근도 가능한 `public`인 경우에는 너무 많은 접근 제어를 허용하는 것 같다고 생각했고, internal보다 다음 단계인 file-private인 경우에는 현 프로젝트에서 파일 하나로 접근 수준을 낮춘 것이기에 너무 범위가 좁다고 생각해서 이 중간인 `internal` 이 기본값으로 설정된게 아닌가 싶습니다.

이에 대해서는 실제 문서에서 찾아봤습니다.

문서에서는 simple single-target app에서 보통 앱 내에서 모든게 이루어져 있어서 외부 모듈이 필요없다고 말을 합니다. 그래서 그 기본값으로 이렇게 설정한듯 싶습니다.
근데 여기에서 sigle-target app 이 무엇을 의미하는지 정확히 모르겠어서 질문드리고싶습니다!

3. 처음에는 모든 곳에서 접근할 수 있게 만들어야 Test code가 되는줄 알았습니다. 일단 private으로 하게되면 유닛 테스트 시 사용할 수 없기 때문에 캡슐화를 없앴습니다. 그리고 지금 공부를 더 해본 결과, public보다는 같은 모듈에서만 사용하므로 디폴트인 internal로 하면 되겠다고 생각했습니다. 하지만 이것도 테스트코드를 위해 캡슐화를 제거하는게 맞나 싶었습니다. 테스트코드를 하고 싶다 vs 캡슐화를 통해 접근 못하게 해야한다. 둘 사이에 갈등이 오갔습니다. 그래서 이를 공부해본 결과, 테스트 커버리지를 100%할 필요가 없고 테스트 코드가 필요한 부분은 캡슐화가 안된 부분이라는 글을 보게되었습니다. 그 말은 즉, 캡슐화한 부분이 아닌 곳만 테스트 코드를 작성하는게 더 낫다는 이야기 였습니다. 하지만 저는 일단 테스트코드를 통해 확인해봐야 하는 코드들이라고 생각해서 캡슐화를 진행하지 않았었습니다.

2022-03-18 04:56 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculatorDoublyLinkedList.swift
> +    var tailNode: Node<T>?
아닙니다. 이것은 `CalculatorDoublyLinkedList` 클래스에서의 구현 내에서만 사용하기 때문에 private를 통해 캡슐화를 할 수 있다고 판단했습니다. 그래서 private 접근제어를 넣어서 반영했습니다!

2022-03-18 04:57 UTC, kimkyunghun3 commented on Calculator/Calculator/QueueLinkedList.swift
> +    var calculateList = CalculatorDoublyLinkedList<T>()
이것도 이 클래스 내에서만 사용하기 때문에 private으로 하는 것이 옳다고 생각하게 되었습니다! 그래서 이를 반영해서 커밋했습니다!

2022-03-18 05:38 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculateItem.swift
> +
> 🐸 더블 연결리스트로 구현한 큐가 공간복잡도에서 빠르다는 의미가 어떤건지 설명해주실 수 있나요? 그리고 코드에서 직접 QueueLinkedList를 선언하여 enqueue와 dequeue를 하고 모든 아이템이 dequeue됐을때 isEmpty를 출력해보셨을까요? 그랬을 때 원하는 결과값이 나오셨나요?

먼저 더블연결리스트가 더 느리다는 것을 말해주려고 했습니다! 더블 스택 경우에는 배열로 되어있기 때문에 큐에 순서대로 다 모여져 있기에 O(1) 이라고 생각했고, 더블 연결리스트는 배열이 아니기 때문에 각각이 모여있지 않고 이곳저곳에 있어서 이를 찾아가야하므로 O(n)이라고 생각했습니다.

isEmpty 부분은 테스트 코드를 만들어서 해봤는데 테스트가 통과하는 것을 보니 원하는 결과값이 나온다고 파악할 수 있었습니다!

2022-03-18 05:45 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculateItem.swift
> +
> 🐸 아:) 말씀하신대로 코드에서 이론적인 이해는 하셨지만 로직이 정상적으로 동작하는지 혹시 확인해보셨을까요? 그리고 전반적으로 참조관계를 고려하면서 코드 개선이 필요해보입니다.

먼저 테스트코드를 통해 동작이 잘 되는 것을 확인했으며 이는 정상적인 동작이라고 확인되었습니다.
참조 관계에 대해서 개선이 필요하다고 하셔서 이를 고민해보고 어디를 개선해야할지 찾아보려고 노력했습니다. 참조 관계라는 것이 종속 관계와 다르게 한 쪽이 사라지더라도 다른 쪽에 사라지지 않는 관계 같은데, 여기에서 CalculatorDoublyLinkedList를 인스턴스로 사용하는 `CalculatorItemQueue` 구조체에서 대한 이야기가 아닌가 싶었습니다. 하지만 이 인스턴스가 없으면 이 내부 구조체에서의 메소드들이 동작하지 않기에 이는 종속관계인거같다는 생각이 들어서... 혹시 개선이 필요한 부분이 다른곳일까요? 더 고민해봐야할까요?

2022-03-18 05:46 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculateItem.swift
> +
> 🐸 프로젝트에서 필요한 기능(이벤트)들을 생각해보시면 좋을 것 같아요! 그리고 그 이벤트를 정상적으로 동작하는지를 유닛테스트로 작성해보시면 어떨까요?

이것을 생각해보니 현재 짜여진 테스트 코드가 필요한 기능들을 사용해서 한 것 같습니다. 그래서 이에 따른 유닛테스트가 작성되었다고 저는 생각합니다!

2022-03-18 05:48 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculateItem.swift
> +
>  흠 Eddy가 큐에서 양방향연결리스트를 사용하셨을 때 작성하신 이유가 있었을텐데요! 프로젝트 전반적으로 큐의 활용을 생각해봤을 때 활용도가 좋았는지를 고민해주시면 좋을 것 같아요.

먼저 제가 양방향 연결리스트를 사용한 것은 연산에서 마지막에 입력한 것을 제거하고 싶을 때의 기능 때문에 사용했습니다. 단방향 연결리스트로도 할 수는 있지만 이는 탐색하듯이 처음부터 끝까지 가야하기 때문에 비효율적이라고 생각했으며 양방향으로 끝에서 시작하게 하는 기능이 있으면 좋을 것 같다고 생각해서 이를 선택했습니다. 물론 더블 스택이 효율면에서는 더 좋지만 구현의 입장에서는 양방향 연결리스트가 더 낫다고 생각해서 이렇게 했던 것입니다..!

2022-03-18 05:50 UTC, kimkyunghun3 commented on Calculator/Calculator/CalculateItem.swift
> +
> 기능서에서 CalculateItem은CalculatorItemQueue에서 다루는 요소가 준수한다고 요구되어 있는데요. 왜 요소가 CalculateItem을 준수해야하는지를 생각보시면 좋을 것 같습니다.

제가 내린 결론으로는 이 프로토콜을 확장해서 타입들을 정의 내릴 수 있는 것 같습니다. 예를 들어, String, Double 만 계산기에서 필요하다면 이를 확장시켜서 이 프로토콜을 채택한 곳에서 이 타입들만 사용하게끔 만드는 방식이 있을 것 같습니다. 그래서 이렇게 빈 프로토콜을 두라고 했고 이를 채택하도록 하는 것 같다고 생각합니다.

2022-03-18 10:54 UTC, yoo-kie approved these changes

2022-03-18 10:54 UTC, merged