계산기 [STEP 2] 우롱차
yagom-academy/ios-calculator-app pull request #182
Opened 2022-03-18 09:33 UTC by dnwhd0112

@jungseungyeo
안녕하세요 린생
이번 PR도 잘 부탁드려요!

## 고민한 점
1. UML을 보고 함수를 선언하는대 어떤 방식으로 동작해야 되는지에 대하여 고민을 많이 하였다. 처음에는 하나씩 enqueue하는 구조라고 생각하였으나 UML에서는 추가로 enqueue 할 구석이 보이지 않았고 내가 생각했던거와 다르게 두게의 큐를 가지고 연산자와 숫자를 입력 받는 방식이였다.
2.  `componentsByOperators` 이름의 메서드가 있었는대 이 메소드 이름에 맞게 올바르게 기능을 구현하였는지 잘 모르겠다.
3.  `Formula` 구조체 안에서 코드를 좀 깔끔하게 쓰고 싶어 `stringToDouble` 메소드를 구현하였는대 extension으로 구현하였다. 맞게 한지 잘 모르겟다.

2022-03-18 13:04 UTC, jungseungyeo requested changes
우롱차 고생하셨어요!

### 1. UML을 보고 함수를 선언하는대 어떤 방식으로 동작해야 되는지에 대하여 고민을 많이 하였다. 처음에는 하나씩 enqueue하는 구조라고 생각하였으나 UML에서는 추가로 enqueue 할 구석이 보이지 않았고 내가 생각했던거와 다르게 두게의 큐를 가지고 연산자와 숫자를 입력 받는 방식이였다.

`넵 코드를 보면서 잘 구현해주신거 같아요. 두개의 큐로 구성을 하여 하는 방식을 저도 생각하였고, 이 방식을 유지해도 좋을거같아요.`

### 2. componentsByOperators 이름의 메서드가 있었는대 이 메소드 이름에 맞게 올바르게 기능을 구현하였는지 잘 모르겠다.

`이 부분은 디코에서 이야기 한 내용 처럼 잘 해주신거 같아요 :)`

### 3. Formula 구조체 안에서 코드를 좀 깔끔하게 쓰고 싶어 stringToDouble 메소드를 구현하였는대 extension으로 구현하였다. 맞게 한지 잘 모르겟다.

`이것도 디코에서 이야기 한 거 처럼 수정하면 좋을거같아요. 삭제하거나 제가 보여준 방식으로 수정하면 좋을거같아요.`

디코에서 이야기한 부분에서 몇가지 구현이 빠진 부분과 수정해야 되는 부분의 대해서 적용을 해주시면 좋을거같아요. 테스트 코드 네이밍도 수정하면 좋을거같아요. 또 Queue의 구현 방식이 step1에서 구현 방식을 수정하지 않았으면 좋겠습니다. 

이 부분 수정 부탁드려요 ㅎㅎ 수정한 부분의 대해서 궁금한 점이 있으면 언제든지 질문해주세요 :)

2022-03-19 15:43 UTC, dnwhd0112 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_deque_CalculatorItemQueue() {
네 알겠습니다.

2022-03-19 15:44 UTC, dnwhd0112 commented on Calculator/Modal/Extension.swift
> +    static func stringToDouble(_ str:String?) -> Double {
으아... 어떻게 짧게 했었는지 잘 기억이 나진않네요. 일단 해보겠씁니다.

2022-03-19 15:44 UTC, dnwhd0112 commented on Calculator/Modal/CalculatorItemQueue.swift
> +    private var queue: [T] = []
네 알겠습니다.

2022-03-19 15:46 UTC, dnwhd0112 commented on Calculator/Modal/ExpressionParser.swift
> +        let operands = CalculatorItemQueue<String>()
CalculatorItemQueue 말하는거죠?! 알겠습니다!

2022-03-19 15:46 UTC, dnwhd0112 commented on Calculator/Modal/ExpressionParser.swift
> +            if let _ = Double(item) {
네 double에 extension 을 해준다음 해보겠습니다!

2022-03-19 21:25 UTC, dnwhd0112 commented
@jungseungyeo 
코드 변경 완료했습니다!

2022-03-21 13:04 UTC, merged