계산기 I [Step2] Tiana
yagom-academy/ios-calculator-app pull request #183
Opened 2022-03-18 12:02 UTC by Kim-TaeHyun-A

안녕하세요 개굴 @yoo-kie 
Step2 PR 보냅니다😁

---
### 구현한 내용

- CalculatorError
- **extension** String
    - split(with target: Character) -> [String] : target을 기준으로 나뉜 문자열 배열을 반환
- Operator : 연산자에 맞는 연산 진행
    - calculate(lhs: Double, rhs: Double) **throws** -> Double
    - add(lhs: Double, rhs: Double) -> Double
    - subtract(lhs: Double, rhs: Double) -> Double
    - devide(lhs: Double, rhs: Double) **throws** -> Double
    - multiply(lhs: Double, rhs: Double) -> Double
- Formula : 연산자 큐와 피연산자 큐를 이용해서 결과값 반환
    - result() **throws** -> Double
- ExpressionParser
    - parse(from input: String) -> Formula : 연결 리스트를 이용해서 큐를 생성
    - componentsByOperators(from input: String) -> [String] : 숫자로만 이워진 배열을 추출

---

### 고민한 점

1. 네이밍
    - 테스트 케이스의 네이밍: 내부에 구현된 데이터를 자세히 명시하지 않고, 확인하려는 기능에 대해서만 설명하도록 작성했습니다. 이 경우, 내부에서 다른 데이터를 넣어서 확인해도 테스트 케이스의 이름은 수정할 필요가 없어 좋을 것 같습니다.
2. UML에 충실하게
3. 유닛 테스트
    - 외부에서 사용되지 않는다는 생각에 모든 테스트 케이스에 private을 설정했지만 제대로 테스트가 돌아가지 않아 무조건 테스트를 성공하는 것을 확인했습니다.
    - 정확한 이유는 모르겠지만 import한 모듈에서 접근이 필요해서 internal으로 설정하는 것 같습니다.🤔
    - 타겟을 설정할 때 import가 되지 않아 target membership을 임의로 체크했는데 이 때문에 Calcaultor 모듈이나 UIKit에 접근 불가능했습니다. 확인해보니, 해당 파일이 속한 최상위 그룹이 그 파일의 타겟이 되는 것 같습니다. 또 @testable로 모듈을 import하는 경우 굳이 target memebership을 하나하나 설정할 필요가 없는 것 같습니다.
4. 다른 타입과의 의존도
    - 이니셜라이저 내부에서 다른 타입의 인스턴스를 생성하기 보다는 외부에서 주입 받을 수 있도록 했습니다.
5. error handling
    - 0으로 나뉘는 것을 제외한 경우(ex. 연속된 연산자 입력)은 UI 쪽에서 제어가 가능하다고 판단하여 추가적인 에러 처리는 없습니다.
6. 파일 분리
    - Utils라는 그룹 내에 Error와 Extension을 넣었습니다.
7. commit 단위 작게
8. ExpressionParser
    - 이번 스탭에서 가능 고민했던 구현 부분이지만 구현이 깔끔하지 못한 것 같아 아쉬운 부분입니다.😭
    - UML에서 요구한 split() 메서드를 사용해서 연산자와 숫자를 분리하는 방법에 대해 고민했습니다.
    - prefix로 올 -/ +를 처리하는 방법에 대해 고민했습니다. 뷰에서 빈 칸을 넣어주고 이를 이용하는 것보다는 입력된 값에서 자체적으로 연산자와 숫자들을 분리하고 싶었습니다. 이 과정에서 연달아서 어떤 값이 오는지 확인해야 하지만 뷰에서 값을 직관적으로 받아올 수 있기 때문에 이 방법을 사용했습니다.
9. 테스트 삭제 시 타겟 제거
    - 불필요한 테스트를 삭제하는 경우 타겟을 지우지 않으니 모든 테스트를 통과해도 테스트가 실패했다고 나왔습니다. 이를 해결하기 위해 프로젝트 설정에서 남아있는 타겟을 제거했습니다.
10. 고차함수 활용
11. 프로토콜 채택 표기 순서
    - Operator의 경우 CalculateItem과 CaseIterable을 채택합니다. 채택 시 구현이 필요한 부분이 있으면 extension으로 따로 작성했겠지만, 이 경우 구현을 요구하지도 않아 타입 구현에서 2가지를 다 채택합니다. 구현되는 내용이 없어도 extension으로 다 빼는 것이 가독성이 좋은지 궁금합니다. 또 한 개 이상을 채택하는 경우 선호되는 채택 순서가 있을지 궁금합니다.🤔
12. 메스드만 가지는 enum
    - 값 타입은 주로 struct을 사용하고 case가 필요한 경우만 enum을 사용했습니다. 그런데, 이번 스탭의 UML을 보니 case가 없는 enum의 구현을 요구해서 그 이유에 대한 고민을 했습니다.
    - enum의 경우 케이스가 없으니 인스턴스 생성이 제한적이어서 특정 목적의 타입 메서드를 모아놓기에 좋을 것이라고 생각됩니다. 또한 저장 프로퍼티가 필요한 경우가 아니라면 enum을 통해서 정의하는 것 깔끔해보입니다.
13. 하드 코딩 지양
    - Separator 타입으로 값 구분용으로 사용된 underScore를 간접적으로 표기합니다.
14. 고차함수
    - 고차함수를 연결해서 계속 사용하는 것과 반복문을 사용했을 때의 차이점에 대해 고민했습니다.
    
    [https://medium.com/skoumal-studio/performance-of-built-in-higher-order-function-vs-for-in-loop-in-swift-166fa41b545f](https://medium.com/skoumal-studio/performance-of-built-in-higher-order-function-vs-for-in-loop-in-swift-166fa41b545f)
    
    - 시간 복잡도를 생각했을 때 반복적으로 element에 접근하니까 체이닝하는 경우는 반복문보다 더 안좋을 것 같은데요. 단편적으로 고차함수 하나와 반복문을 비교하는 경우는 비슷하거나 고차함수의 성능이 더 좋을 것 같습니다. 그렇지만 여러 개를 연결할 경우 체이닝이 더 나쁜 것 같네요. 구현을 어떻게 하느냐의 차이일수도 있지만 성능의 차이나 시간 복잡도(그 외에 최적화에 대한 차이도 있는 것 같은데 잘 모르겠습니다.🤔)에 대해 궁금합니다!

2022-03-19 09:28 UTC, yoo-kie requested changes
안녕하세요 Tiana!

UML에 표기되어 있는 사항을 모두 깔끔하게 구현해주셨네요:)👍👍👍👍
각 객체들의 역할이 명확하게 보였습니다. 그럼 아래에 고민하신 사항에 대한 저의 생각 남겨두겠습니다! 🐸

### 고민한 점

1. 네이밍
    - 테스트 케이스의 네이밍: 내부에 구현된 데이터를 자세히 명시하지 않고, 확인하려는 기능에 대해서만 설명하도록 작성했습니다. 이 경우, 내부에서 다른 데이터를 넣어서 확인해도 테스트 케이스의 이름은 수정할 필요가 없어 좋을 것 같습니다.

`🐸 넵 덕분에 유닛테스트 별로 기대 동작이 무엇인지, 확인하고자 하는 핵심 동작이 무엇인지가 명확하게 보였습니다.`

2. UML에 충실하게

`🐸 ⭐️⭐️⭐️⭐️⭐️`

3. 유닛 테스트
    - 외부에서 사용되지 않는다는 생각에 모든 테스트 케이스에 private을 설정했지만 제대로 테스트가 돌아가지 않아 무조건 테스트를 성공하는 것을 확인했습니다.
    - 정확한 이유는 모르겠지만 import한 모듈에서 접근이 필요해서 internal으로 설정하는 것 같습니다.🤔
    - 타겟을 설정할 때 import가 되지 않아 target membership을 임의로 체크했는데 이 때문에 Calcaultor 모듈이나 UIKit에 접근 불가능했습니다. 확인해보니, 해당 파일이 속한 최상위 그룹이 그 파일의 타겟이 되는 것 같습니다. 또 @testable로 모듈을 import하는 경우 굳이 target memebership을 하나하나 설정할 필요가 없는 것 같습니다.

4. 다른 타입과의 의존도
    - 이니셜라이저 내부에서 다른 타입의 인스턴스를 생성하기 보다는 외부에서 주입 받을 수 있도록 했습니다.

`🐸 Queue 내부의 linkedList를 외부에서 주입을 받게 되면 외부에서도 queue를 통하지 않고도 linkedList를 직접 수정할 수 있는 가능성이 생기는데요. 혹시 Tiana가 의도하신 사항일수 있으니 커멘트 참고 후 답변 부탁드립니다! 🙏`

5. error handling
    - 0으로 나뉘는 것을 제외한 경우(ex. 연속된 연산자 입력)은 UI 쪽에서 제어가 가능하다고 판단하여 추가적인 에러 처리는 없습니다.

6. 파일 분리
    - Utils라는 그룹 내에 Error와 Extension을 넣었습니다.

7. commit 단위 작게

8. ExpressionParser
    - 이번 스탭에서 가능 고민했던 구현 부분이지만 구현이 깔끔하지 못한 것 같아 아쉬운 부분입니다.😭
    - UML에서 요구한 split() 메서드를 사용해서 연산자와 숫자를 분리하는 방법에 대해 고민했습니다.
    - prefix로 올 -/ +를 처리하는 방법에 대해 고민했습니다. 뷰에서 빈 칸을 넣어주고 이를 이용하는 것보다는 입력된 값에서 자체적으로 연산자와 숫자들을 분리하고 싶었습니다. 이 과정에서 연달아서 어떤 값이 오는지 확인해야 하지만 뷰에서 값을 직관적으로 받아올 수 있기 때문에 이 방법을 사용했습니다.

9. 테스트 삭제 시 타겟 제거
    - 불필요한 테스트를 삭제하는 경우 타겟을 지우지 않으니 모든 테스트를 통과해도 테스트가 실패했다고 나왔습니다. 이를 해결하기 위해 프로젝트 설정에서 남아있는 타겟을 제거했습니다.

10. 고차함수 활용

11. 프로토콜 채택 표기 순서
    - Operator의 경우 CalculateItem과 CaseIterable을 채택합니다. 채택 시 구현이 필요한 부분이 있으면 extension으로 따로 작성했겠지만, 이 경우 구현을 요구하지도 않아 타입 구현에서 2가지를 다 채택합니다. 구현되는 내용이 없어도 extension으로 다 빼는 것이 가독성이 좋은지 궁금합니다. 또 한 개 이상을 채택하는 경우 선호되는 채택 순서가 있을지 궁금합니다.🤔

`🐸 넵 말씀하신대로 따로 구현을 하지 않았다면 extension으로 분리하지 않는 것이 가독성이 좋을 것 같습니다. 순서는 rawValue로 사용되는 타입이 가장 처음에 상속되어야하고 나머지에 대해서는 저같은 경우 implement되어 있는 프로토콜 -> 직접 정의한 프로토콜 순서로 작성합니다.`

12. 메스드만 가지는 enum
    - 값 타입은 주로 struct을 사용하고 case가 필요한 경우만 enum을 사용했습니다. 그런데, 이번 스탭의 UML을 보니 case가 없는 enum의 구현을 요구해서 그 이유에 대한 고민을 했습니다.
    - enum의 경우 케이스가 없으니 인스턴스 생성이 제한적이어서 특정 목적의 타입 메서드를 모아놓기에 좋을 것이라고 생각됩니다. 또한 저장 프로퍼티가 필요한 경우가 아니라면 enum을 통해서 정의하는 것 깔끔해보입니다.

`🐸 넵 따로 선언 및 할당되어야 하는 프로퍼티가 없는 단순 메서드의 집합일 경우 enum(또는 struct) + 타입 메서드를 활용하기도 합니다.`

13. 하드 코딩 지양
    - Separator 타입으로 값 구분용으로 사용된 underScore를 간접적으로 표기합니다.

`🐸 👍👍👍👍`

14. 고차함수
    - 고차함수를 연결해서 계속 사용하는 것과 반복문을 사용했을 때의 차이점에 대해 고민했습니다.
    
    [https://medium.com/skoumal-studio/performance-of-built-in-higher-order-function-vs-for-in-loop-in-swift-166fa41b545f](https://medium.com/skoumal-studio/performance-of-built-in-higher-order-function-vs-for-in-loop-in-swift-166fa41b545f)
    
    - 시간 복잡도를 생각했을 때 반복적으로 element에 접근하니까 체이닝하는 경우는 반복문보다 더 안좋을 것 같은데요. 단편적으로 고차함수 하나와 반복문을 비교하는 경우는 비슷하거나 고차함수의 성능이 더 좋을 것 같습니다. 그렇지만 여러 개를 연결할 경우 체이닝이 더 나쁜 것 같네요. 구현을 어떻게 하느냐의 차이일수도 있지만 성능의 차이나 시간 복잡도(그 외에 최적화에 대한 차이도 있는 것 같은데 잘 모르겠습니다.🤔)에 대해 궁금합니다!

```
🐸 Tiana가 고민하신대로 시간복잡도를 고려해봤을때 고차함수의 연속보다 한번의 반복문이 효율성이 높을때가 있습니다.
그리고 관련하여 아래의 질문들에 대해 고민해봐주시면 좋을 것 같습니다:)
1. 고차함수와 반복문의 차이는 무엇일까요? 어떤 상황에서 고차함수를 활용하는 것이 더 좋을까요?
2. 현재 프로젝트에서 고차함수로 체이닝되어 있는 부분의 체이닝 횟수를 줄여볼 수 있을 것 같은데요! 개선할 수 있을까요?
```

2022-03-21 04:36 UTC, Kim-TaeHyun-A commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		0E78D1FC27E4118500D6B92C /* DoubleExtension.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0E78D1FB27E4118500D6B92C /* DoubleExtension.swift */; };
조언 감사드립니다. 수정하였습니다😆

2022-03-21 04:36 UTC, Kim-TaeHyun-A commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		0E9B394C27E41DFC005A55C0 /* StringExtension.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0E9B394B27E41DFC005A55C0 /* StringExtension.swift */; };
조언 감사드립니다. 수정하였습니다.😆

2022-03-21 04:40 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
구조체는 값 타입으로 생성된 인스턴스를 다른 곳에 할당해서 서로 영향을 주지 않지만, 클래스의 경우 참조 타입이므로 다른 곳에서 할당하여 사용하는 경우 그 인스턴스를 공유하는 모든 곳에서 변경이 가능합니다.

구조체 타입의 인스턴스를 변수에 할당하면 해당 인스턴스의 변수 프로퍼티의 값 변경이 가능한 반면, 인스턴스를 상수에 할당하면 변수 프로퍼티라도 값 변경이 불가능합니다. 클래스는 인스턴스 할당을 변수에 하든 상수에 하든 상관없이 변수의 프로퍼티라면 값 변경이 가능합니다. 이때의 차이점이라면, 클래스 인스턴스를 상수에 할당하면 그 상수에는 다른 인스턴스를 할당할 수 없습니다.

구조체의 경우 프로퍼티의 값을 변경한다면, mutating 키워드가 필요하고 클래스는 그렇지 않습니다. 프로퍼티가 값 타입이냐 참조 타입이냐에 따라 다르지만 CalculatorItemQueue는 참조타입의 인스턴스를 상수 프로퍼티로 가져서 별도의 키워드 없이도 프로퍼티 내부를 수정할 수 있습니다.

class는 원래 vTable을 사용하지만 final class의 경우 상속의 가능성을 배제시켰기에 compile 시점에 메서드가 결정되는 static dispatch가 되어 run time에서의 성능은 struct과 비슷할 것으로 생각됩니다.

2022-03-21 04:42 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
>      }
구현 당시에는 private으로 선언했지만 이니셜라이저로 초기화할 때를 제외하면 접근이 불가능한 상태이며, 프로퍼티에 직접 접근은 불가능하지만 메서드를 통해 간접적으로 값을 변경하기에 괜찮다고 생각했습니다. 또 기존의 이니셜라이저는 node를 통해 인스턴스를 생성하는 방식이라 한 번에 리스트를 주입하는 것이 더 자연스러운 것 같았습니다. 이때 개굴이 보여주신 예시처럼 문제점이 있는데, 리스트가 참조타입이라 주입된 값이 외부에서도 변경될 위험이 있음을 고려하지 못했습니다.(private으로 한 것이 아무 의미가 없어지네요..😢)

타입간의 의존도를 낮추는 것이 무조건 좋다고 생각했는데 외부 타입이 해당 타입에서 꼭 필요한 요소의 경우는 의존을 하도록 설계하는 것이 더 바람직할 것 같습니다. 또한 타입의 사용자가 알 필요가 없는 외부 타입의 경우는 완전 숨기는 것이 좋은 것 같네요. 또, 주입할 값이 참조 타입인 경우는 더 고민해서 접근제어자나 생성/주입 방법에 대해 고민해야겠습니다😭

이니셜라이저에서나 프로퍼티의 기본값으로 빈 리스트를 생성하고 enqueue로만 node를 주입받는 것이 적절한 것 같습니다. 조언해주신 것을 고민해보니 큐의 형태가 연결리스트라는 것을 굳이 노출하지 않고 프로퍼티에 기본값으로 빈 리스트를 할당하고 enqueue로만 node를 추가하도록 하는 것이 더 좋을 것 같습니다! 이러면 이 타입이 사용되는 메서드 parse()에서도 리스트를 굳이 생성할 필요가 없어서 더 간결하게 큐를 만들 것 같네요🤔

자세한 예시로 문제점 지적해주셔서 감사드립니다😀
수정했습니다😆

2022-03-21 04:44 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Model/Formula.swift
> +        var result = operands.dequeue() ?? 0
조언 감사드려요! dequeue 메서드 내부에서 값이 없을 경우 에러를 던지도록 수정했습니다.😆

2022-03-21 04:46 UTC, Kim-TaeHyun-A commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        let result = sut.map { $0.data }
해당 타입이 Sequence 프로토콜을 채택하면서 구현한 메서드  makeIterator()의 기능이 의도대로 동작하는지를 확인하고 싶었습니다. 목적에 맞게 네이밍을 변경했습니다. 또한 확인하려는 메서드를 사용하도록 내부 구현을 변경했습니다.
적절하게 테스트 케이스를 만드는 게 어렵네요😂

컴파일 에러를 막으려면 프로토콜의 채택 여부를 확인하는 코드가 필요한데 확인하는 방법을 잘 모르겠습니다.😭 
Sequence 타입의 임의의 변수에 할당해서 guard하려니 에러가 나네요😢

```swift
guard let _: Sequence = sut else {
    return
}
```

> Protocol 'Sequence' can only be used as a generic constraint because it has Self or associated type requirements
>

2022-03-21 04:51 UTC, Kim-TaeHyun-A commented
안녕하세요 개굴 @yoo-kie 

고민한 점이나 코드에서 코멘트해주셔서 감사드립니다!
위에서 질문 주신 것에 대해 고민해봤는데 확인 부탁드려요😀

----
> 1. 고차함수와 반복문의 차이는 무엇일까요? 어떤 상황에서 고차함수를 활용하는 것이 더 좋을까요?
> 2. 현재 프로젝트에서 고차함수로 체이닝되어 있는 부분의 체이닝 횟수를 줄여볼 수 있을 것 같은데요! 개선할 수 있을까요?


1. 실행 속도는 반복문이 더 빠른 것 같습니다.
    
    ```swift
    let elementsCount = 100000
    let fahrenheit = Array(repeating: 0.0, count: elementsCount).map { _ -> Double in
        return Double.random(in: 32.0 ... 113.0)
    }
    
    func forVersionOfForEach() {
        let startTime = CFAbsoluteTimeGetCurrent()
        for degreesFahrenheit in fahrenheit {
            let _ = (degreesFahrenheit - 32.0) / 1.8
        }
        let durationTime = CFAbsoluteTimeGetCurrent() - startTime
        print("for문 경과 시간: \(durationTime)")
    }
    
    func singleForEach() {
        let startTime = CFAbsoluteTimeGetCurrent()
        fahrenheit.forEach({ (degreesFahrenheit) in
            let _ = (degreesFahrenheit - 32.0) / 1.8
        })
        let durationTime = CFAbsoluteTimeGetCurrent() - startTime
        print("forEach 경과 시간: \(durationTime)")
    }
    
    // for문 경과 시간: 0.016786932945251465
    // forEach 경과 시간: 0.08115100860595703
    ```
    
    고차함수는 상수에 바로 값을 할당할 수 있습니다. 컬렉션에 반복적으로 접근하여 수행하고자 하는 일을 완료한 뒤 임시적으로 어딘가에 할당하지 않고 모든 일이 완료된 후 결과를 생성합니다. 따라서 할당 후 변경의 여지를 주고 싶지 않은 경우 의도대로 설계할 수 있습니다. 반면, 반복문은 반복해서 컬렉션에 접근할 수 있지만 변경하려는 대상이 변수로 선언되어야 수정이 가능해서 추후 예상치 못한 변경의 위험에 노출됩니다.
    
    이번 스탭에서 ex: parse 메서드에서 map으로 생성된 결과를 이후 forEach에서 반복적으로 접근 가능합니다.
    
    또 고차함수는 내부에서 return을 해도 다음 element를 가져와서 명령문을 수행하지만, 반복문의 경우는 반복문을 종료합니다.
    
2. parse() 메서드 내부를 아래와 같이 수정했습니다
    
    ```swift
            componentsByOperators(from: input)
                .forEach {
                    guard let operand = Double($0) else {
                        return
                    }
                    operandQueue.enqueue(Node(data: operand))
                }
            
            var lastValue: Character = Separator.underScore
            
            input
                .map { (currentValue: Character) -> Operator? in
                    if let currentOperator: Operator = Operator(rawValue: currentValue),
                       let _ = Double(String(lastValue)) {
                        lastValue = currentValue
                        return currentOperator
                    }
                    lastValue = currentValue
                    return nil
                }
                .forEach {
                    guard let tmp: Operator = $0 else {
                        return
                    }
                    operatorQueue.enqueue(Node(data: tmp))
                }
    ```

2022-03-22 12:20 UTC, merged