계산기 I [STEP 2] malrang
yagom-academy/ios-calculator-app pull request #187
Opened 2022-03-19 12:49 UTC by malrang-malrang

@AppleCEO 
안녕하세요 도미닉!
두번째 Pr 잘부탁드립니다! :)

![](https://i.imgur.com/lHyYRxu.jpg)

요구서에 나와있는 UML 을 해석하는데 시간이 가장 오래 걸린것 같습니다! ㅜㅜ
전체적으로 읽어 보았을때 한개도 이해가 안가서...하나씩 어떤 기능을 담당하는지 생각하여 
코드를 작성하게 되었습니다!

- Formula
    - 연산자와 피연산자로 구분되어 각각 다른곳에 저장되어있는 프로퍼티 일것이다.
    - 연산자와 피연산자 에는 이미 어떠한 값들이 저장되어있다고 가정하여 `result` 기능을 만들었습니다.
- ExpressionParser
    - 버튼을 입력하면 하여 저장된 `String` 을 `input` 값으로 받아 연산자와 피연산자로 구분하는기능.
    - 연산자와 피연산자를 구분하여 각각 구분된 프로퍼티를 가지고있는 Formula 를 반환.
    - 이부분에서 가장 시간이 오래 걸렸습니다! 어떠한 기준으로 연산자와 피연산자로 나누어 줄것인지
    - 현재 공백을 기준으로 나누어 주었으나 `componentsByOperators` 메서드가 어떤것을 의도하였는지 고민하였습니다. 
    - 현재 구현된 코드 라면 `componentsByOperators` 는 String+extention 의 split 만을 호출해주는 기능 밖에는 없기때문에 사실상 무언가 큰 역할을 하고 있지 않아 이런식으로 사용되길 유도하신게 아닌것 같다는  생각을 갖게되었습니다 ㅠ

Step2 요구 사항대로 구현하다보니 링크드 큐의 형태가 조금 수정되었습니다!
이번 프로젝트에서 불필요한 기능을 제거해 최대한 덩치가 작게 만들었으며
class -> struct 로 변경, 내부로직도 사소한것들이 조금 변경되었습니다!

잘부탁드리겠습니다 :)

## 고민한점
1. 기존 구현해 두었던 링크드 리스트 를 구조체로 변경해야할지 고민했습니다.
단순하게만 보았을때는 `class` 와 `struct` 는 저장방식이 다르기때문에 `struct`로 수정하는것이 기능이 더 효율적일것이다 라고 생각 했으나 `struct` 로 변경하게되면 mutating 키워드를 사용하여 값을 전체적으로 복사하여 새로운 인스턴스를 만들게 됩니다.
그렇다면 이번 프로젝트에서 연산을 할때마다 `mutating` 으로 프로퍼티의 값이 변경되기 때문에 연산횟수가 많아질수록 성능이 저하될것으로 생각하였는데 앞에 말씀드린 이것과 `class` 에 `final` 키워드를 작성하는것 두가지중 어떤것이 성능이 더좋을지 판단하기 어려웠습니다 ㅠ

2. ExpressionParser parse 코드의 가독성
매개변수 `input` 으로 받은 값을 `forEach` 로 반복하여 각각의 `Element` 들을 `Double` 타입 으로 형변환이 가능하다면 `operands` 에 저장, `Double` 타입 으로 형변환이 불가능 하다면 `operators` 에 저장 하는 방식.

```swift
static func parse(from input: String) -> Formula {
        
        let componentsString = componentsByOperators(from: input)
        var values = LinkedQueue<Double>()
        var oper = LinkedQueue<Operator>()
        
        componentsString.forEach{
            if let number = Double($0) {
                values.append(newNode: number)
            } else if let convertOper = Operator(rawValue: Character($0)) {
                oper.append(newNode: convertOper)
            }
        }
        
        return Formula(operands: values, operators: oper)
    }
```
연산자와 피연산자를 각각 `compactMap` 으로 반환 하여 `forEach` 로 각 `Element` 들을 저장해주는 방식
```swift
static func parse(from input: String) -> Formula {
        let componentsString = componentsByOperators(from: input)
        
        var values = LinkedQueue<Double>()
        let convertDouble = componentsString.compactMap{ Double($0) }
        convertDouble.forEach{ values.append(newNode: $0) }
        
        var oper = LinkedQueue<Operator>()
        let converteOper = componentsString.compactMap{ Operator(rawValue: Character($0)) }
        converteOper.forEach{ oper.append(newNode: $0) }
        
        let calculator = Formula(operands: values, operators: oper)
        return calculator
    }
```
위의 두가지 경우 기능면에서는 1번째 예시가 더 좋을것이다 라는 생각 이지만 가독성 측면에서는 이해하기 어려울수 있을까.. 고민하였습니다.
어떠한 코드가 더좋은 방식이라고 할수 있을까요?? 이해하기 쉬운 코드가 가장 좋은 코드라 생각하고있습니다만..! ㅠㅠ 조언을 부탁드리겠습니다!

2022-03-20 12:07 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
이번 스텝 고생하셨습니다~
굉장히 빠른 PR 놀랐습니다!
코딩을 즐기시고 밤 늦게 까지 작성하셨다고 해서 감동했습니다.
저한테 질문이나 편하게 DM 주세요~
1. struct 을 사용하는 것이 좋나요?
-  저는 struct 를 사용하는 것을 선호합니다. 메모리 저장 공간이나 성능 상에 이점이 많은 것으로 알고 있어서 그렇습니다.
- 어떤 점이 장점인지 찾아보셔도 좋을 것 같습니다.

2. 어떠한 코드가 더좋은 방식이라고 할수 있을까요??
- 저는 우선적으로 기본형으로 모든 것이 표현됬으면 좋겠습니다. $0 이 첫번째 코드가 더 적어서 우선 이 코드가 더 이해하기 쉽지 않을까 싶기도 했습니다. 만약 이 코드들을 축약형을 사용하지 않으면 어떻게 작성될까요? 무조건 짧은 코드보다 있어야할 곳에 있어야 할 것들이 있는 코드들이 읽기 좋은 코드고 좋은 코드라고 생각합니다. 저는 조금 냉정하게 말씀드리면 둘 다 읽기 어려운 코드라고 생각합니다.

2022-03-20 12:07 UTC, AppleCEO commented on Calculator/Calculator/Utils/String+extention.swift
> +        return split(separator: target).map{ String($0) }
기본형을 사용하면 어떤 코드일까요?
기본형이 바로 떠오르시나요?
그렇더라도 저는 아직은 기본형을 사용하는 것은 추천합니다.
여러가지 코드를 작성할 수 있겠지만 아직은 어떻게 축약할 수 있냐보다는 코드의 동작에 집중할 시기라고 생각합니다!

2022-03-20 12:07 UTC, AppleCEO commented on Calculator/CalculatorTests/OperatorTests.swift
> +    }
우연히 이 나누기는 정상적으로 나올 수도 있을 것 같아요.
그런 의미로 test_divide 라는 메소드명은 조금 큰 의미일 수 있겠네요!
어떻게 개선해 볼 수 있을까요?

2022-03-20 12:07 UTC, AppleCEO commented on Calculator/CalculatorTests/QueueTests.swift
> +//  Created by 김동욱 on 2022/03/19.
날짜까지 신경 쓰는 부분 좋습니다.
개발자는 작성하는 코드의 주석 한 부분마저도 책임이 있습니다.
그리고 모두 자신이 이해하고 컨트롤할 수 있는 기능들만 사용하는 것이 좋습니다!
이렇게 디테일하게 신경쓴 부분 좋습니다~ 👍

2022-03-20 12:51 UTC, malrang-malrang commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var oper = LinkedQueue<Operator>()
앗! 이부분은 변수명을 변경하려고 생각했던부분인데 잊어버린것 같습니다 ㅜㅜ 
꼼꼼히 체크할수있도록 습관을 들이려 노력해야겠습니다!
수정하도록 하겠습니다! :)

2022-03-20 12:55 UTC, malrang-malrang commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            if let number = Double($0) {
그렇군요! 
처음 고차함수를 접할때 축약문법을 먼저 익히게 되어 이제껏 축약문법으로 많이 사용했던것 같습니다!
아무래도 축약문법으로 작성하게되면 해당 코드가 어떤것을 의미하는지 한눈에 이해하기 어려울것 같습니다!
지금 저에게는 축약문법 보다 기본형에 익숙해지도록 연습한후 추후 동료와 약속을 정해 어느정도까지 축약할것인지 협의후 사용하는것이 좋을것 같습니다! :)

2022-03-20 12:59 UTC, malrang-malrang commented on Calculator/Calculator/Model/Formula.swift
> +        guard var result = operands.removeFirst() else { return .nan }
옵셔널 바인딩도 해야하고 상수로 값을 고정 시키기보다 값이 변경될수 있게끔 사용해야 했기에 guard var 를 사용했습니다! 
네! 가장 중요한것은 기본기 라고 생각합니다! 
코드를 작성하며 코드의 길이를 줄이려고 생각했던 부분인것 같습니다! 
아직은 코드가 더 길어지더라도 읽기쉬운코드 ,기본기가 튼튼한 코드를 작성하려고 생각하며 코드를 작성해야 할것 같습니다!

2022-03-20 13:01 UTC, malrang-malrang commented on Calculator/Calculator/Model/Formula.swift
> +        }
이부분은 위와 같이 코드를 조금더 깔끔하고 줄일수있는 방법이 없을까? 고민하여 리팩터링 했던 부분입니다! 
처음에는 operators 에 저장된 값이 있다면 while 반복문을 진행하게끔 구현하였으나 코드의 양이 굉장히 많았습니다.
while 의 조건을 if 처럼 사용할수있다는 것을 알게되어 위와 같은 형태로도 사용할수 있음을 알게되었습니다!
위와 같은 방법으로 사용하게되면 옵셔널 바인딩 효과도 있어서 좋았던것 같습니다!

2022-03-20 13:03 UTC, malrang-malrang commented on Calculator/Calculator/Model/LinkedQueue.swift
> +    var value: Element
옵셔널을 제거했던이유는 옵셔널을 제거하지 않더라도 구현하는것에 아무런 영향은 없었습니다! 
하지만 모두 구현하고 돌아보니 노드는 값을 저장할때만 사용되는것일 텐데 오히려 옵셔널 이면 안되지 않을까? 라는 의문이 들었습니다!
값을 저장하기위해 만들어진 노드가 value 값이 nil 일수도 있다는것이 오히려 더 불확실성을 주는것같아 제거하였습니다!

2022-03-20 13:06 UTC, malrang-malrang commented on Calculator/Calculator/Model/LinkedQueue.swift
> +
아직 코딩 컨벤션이 습관화 되어있지않아 문제가 생긴부분입니다!
구현이 모두 끝난뒤 제 코드를 돌아보니 어떤 class 는 프로퍼티가 선언되기전 공백이 한줄 존재하고
어떤 class 는 공백이 존재하지 않는 모습이 되어 컨벤션을 모두 통일하기 위해 생겨난 공백입니다!

2022-03-20 13:09 UTC, malrang-malrang commented on Calculator/Calculator/Model/LinkedQueue.swift
> +        }
defer 를 처음 사용해보았습니다! 
사용방법은 모른채 이러한 것이 있다는것만 알고있었습니다! 
return 후에 defer 구문을 실행하는것은 모르고 있었지만 이번에 사용해보고 굉장히 특이한 기능이구나 라는 생각이 들었습니다!
이부분은 사용해야할때 defer 를 사용해보자 라고 마음먹었던 부분이었습니다!
그렇기에 바로 defer 를 이용한 코드로만 구현해보았습니다!
defer 를 사용하지 않은채로도 구현을 해보도록 하겠습니다!

2022-03-21 09:35 UTC, malrang-malrang commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            }
이 부분에대해 몇번 글을 보기는 했지만 어떤 이유인지 자세히 찾아본적은 없었습니다!
이번에 도미닉이 말씀해주셔 찾아보고 한번에 이해하지 못했으나 예시 사진을 보고 이해했습니다..!

![else](https://user-images.githubusercontent.com/88717147/159232766-f762cb41-405b-4487-9937-2fd2568a8c03.jpeg)

지금처럼 If-else 문이 덩치가 작다면 그나마 괜찮지만 기능을 추가 하게되어 else 가 추가된다면 
유지보수를 해야할때 어떤 부분을 수정해야할지 찾는게 어려워지고 조건 논리가 복잡해진다는것을 알게되었습니다!

이를 해결하기 위해 early return, early continue,  early break 같은 테크닉을 이용해
뒤의 코드구조를 간단하게 만들수 있다는것을 알게되었습니다!

2022-03-21 10:17 UTC, malrang-malrang commented on Calculator/Calculator/Utils/String+extention.swift
> +        return split(separator: target).map{ String($0) }
간단한 코드라면 기본형이 바로 떠오르지만 조금만 복잡해져도 기본형이 바로 떠오르지 않는것 같습니다! 
지금은 기본형으로 사용하고 숙달될수있도록 집중해야할것 같습니다! 
말씀해주셔 감사합니다 :)

2022-03-21 13:57 UTC, malrang-malrang commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return input.split(with: " ")
해당 부분은 회의실에서 도미닉과 얘기 나누었습니다! :)
UML 의 요구사항에 있기 때문에 구현은 해두었으나 개인적으로 지금과 같은 용도로 사용된다면 
components 메서드를 사용하는것이 좋을것 같다는 생각이 들었습니다!

2022-03-21 14:05 UTC, malrang-malrang commented on Calculator/CalculatorTests/OperatorTests.swift
> +    }
네 맞습니다! 해당 테스트는 나누기가 성공되는 케이스로 유지하고 네이밍을 수정하였습니다!
그후 Operato 의 값이 divide 일때 rhs 값이 0 이라면 결과값이 nan 인지 테스트하는 test 메서드를 추가로 구현해두었습니다! :)

2022-03-21 14:13 UTC, malrang-malrang commented
@AppleCEO 
안녕하세요 도미닉!
남겨주신 답변 모두 읽고 수정해보았습니다! 
조언을 받고 싶은 부분은 코멘트 답변에 작성해 두었으나 이곳에도 작성 해두겠습니다!
편하신 시간에 확인 부탁드리겠습니다 :)

guard var 를 사용된 부분을 리팩터링 하며 예시들을 작성해두었습니다! 
어떤것이 가장 직관적인지 판단이 서지않아 조언받고싶어 남겨둡니다!

해당 부분을 리팩토링 하는 과정에서 if 문으로 수정하려 했으나 if 구문 을 활용해서 작성하게 될경우 바인딩 된 값을 활용해야 하기 때문에 if 문 안에 while 구문을 사용해야하는 상황이 발생됩니다! 그렇게 되면 2중 들여쓰기가 됨으로 이해하기 어려운 코드가 되지않을까? 라는 생각이 들었습니다! 변수도 여러개 더 생성되게 됩니다!

기존의 코드
```swift
mutating func result() -> Double {
        guard var result = operands.removeFirst() else { return .nan }
        
        while let oper = operators.removeFirst(), let rhs = operands.removeFirst() {
            result = oper.calculate(lhs: result, rhs: rhs)
        }
        return result
    }
```
기능은 똑같지만 guard 를 제거함으로써 쪼...끔더 읽기 편한 방법으로 수정해보았습니다!
```swift
 mutating func result() -> Double {
        var result = operands.removeFirst() ?? .nan
        
        while let oper = operators.removeFirst(), let rhs = operands.removeFirst() {
            result = oper.calculate(lhs: result, rhs: rhs)
        }
        return result
    }
```
이러한 형태랑 while let 의형태를 수정하게되면 아래와 같은 형태로 구현할수 있을것 같습니다!
```swift
mutating func result() -> Double {
        var result = operands.removeFirst() ?? .zero
        
        while operators.isEmpty == false {
            guard let rhs = operands.removeFirst() else { return result}
            guard let `operator` = operators.removeFirst() else { return .nan }
            result = `operator`.calculate(lhs: result, rhs: rhs)
        }
        return result
    }
```
세가지 예시중 가장 아래 코드가 가장 직관적이라 볼수있을까요!?

조언을 부탁드리겠습니다!

2022-03-22 10:12 UTC, AppleCEO commented
2번째 코드가 좋아보이네요. 마지막 코드처럼 한 줄로 줄여서 쓰는 것은 별로 안 좋아해서요!

2022-03-22 10:37 UTC, merged