계산기 I [STEP 1] Onetool
yagom-academy/ios-calculator-app pull request #189
Opened 2022-03-20 01:33 UTC by kimt4580

@wonhee009 
안녕하세요 라자냐!
onetool 입니다!
개인 사정으로 인해 STEP 1을 약속드린 시간까지 PR하지 못하여 정말 죄송합니다.
리뷰 잘부탁드립니다! ☺️

🛠 구현내용

`list[T?]` : 어떤 타입이든 받을 수 있는 Array
`var head` : Array의 head를 알 수 있게 하는 변수
`var isEmpty` : 함수가 비어있는지 확인하는 Bool 타입 변수
`var count` : Array에서 총 몇칸이 사용되었는지 count를 세어주는 변수
`enqueue()` : Array에 value를 append 해주는 함수
`dequeue()` : head의 값을 nill 초기화 해주고 head의 위치를 이동시켜주는 함수

❗️고민한 점 & 궁금한점

1. Caculator를 왜 queue를 이용해서 구현해야 하는지 궁금합니다.
2. Test 코드를 구현하실 때, 함수 네이밍을 어떻게 하시는지 궁금합니다. 한글로 적으시는지 영어로 적으시는지.. 컨벤션 규칙은 따라야하는건지 잘 모르겠습니다..
3. dequeue를 진행할 때, 앞에 있는 값을 nil로 초기화 해주다가 head가 100이상으로 넘어가면 head를 초기화 해주도록 구현하였는데, 개선할 점 이 있을까요?

2022-03-21 04:57 UTC, wonhee009 requested changes
@kimt4580 안녕하세요 원툴~ 스텝1 수고하셨습니다!🎉

명세서에 아래의 내용이 있는데 코드에서 적용된 부분을 찾을 수 없는데 확인 부탁드립니다🙏
> CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수

#### 궁금한 점

- 큐를 이용해서 계산기를 구현하는 이유는 큐가 가지고 있는 FIFO 특징과 후위계산과 같은 계산 방식이 잘 맞아서 입니다. (큐의 특징과 계산식에 대해서 알아보는걸 추천드립니다.)
- 저는 영어로 적긴하는데 그 부분은 어느정도 팀 내의 컨벤션을 따르시면 될거 같습니다.
- 개선 부분에 대해서는 제대로 동작하는지 먼저 확인 부탁드립니다🙏

2022-03-21 04:57 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    var list = [T?]()
옵셔널 타입으로 선언하신 이유가 있으실까요?🤔

2022-03-21 04:57 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    var head: Int = 0
`head`의 초기값이 0인 것을 보아 index를 의미하는거로 보이는데요.
`head = list.first`처럼 element를 갖지 않고 index를 갖도록 정의한 이유가 있을까요?

2022-03-21 04:57 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +        return element
```swift
queue.enqueue(value: 1)
queue.enqueue(value: 2)
queue.dequeue()
queue.enqueue(value: 3)
queue.enqueue(value: 4)
queue.dequeue()
queue.dequeue()
queue.dequeue()
```
해당 동작을 했을 때 원툴이 원하는 결과값을 받을 수 있나요?

2022-03-21 05:45 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    var head: Int = 0
head의 위치를 변경하기 위해서 초기 값을 0번지로 두고 사용하기 위해서 index를 갖도록 정의했습니다!

2022-03-21 05:45 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    var list = [T?]()
head를 초기화 하게 되면 nil로 비어있을 수도 있기 때문에 옵셔널로 선언하게 되었습니다.

2022-03-21 05:50 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +        return element
제가 원하는 결과 값은 4일 것 같아서 test 코드를 작성했더니, 원하는 결과 값을 받을 수 있었습니다.
index를 0으로 초기화하면서 head 위치를 이동해주기 때문에 앞에 빈 공간이 남아있기 때문에 남아 있을 것 같습니다!

2022-03-21 06:45 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +        return element
<img width="187" alt="image" src="https://user-images.githubusercontent.com/30456206/159215366-db9080ee-1bc0-479d-b1c0-fc17a74d0c2e.png">

제가 해당 코드로 확인했을때에는 원하는 값이 안 나오는거로 확인했는데요. 해당 테스트 코드의 기준이 잘못된거 같습니다.
list의 count의 값을 비교하는게 아니라 dequeue된 element의 값을 비교해야하지 않을까요?

2022-03-21 06:53 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>:CalculateItem {
CalculateItem 프로토콜을 CalculatorItemQueue에서 **다루는 요소**가 채택해야하는거 같은데요.
여기서 말하는 **다루는 요소**는 무엇일까요?

2022-03-21 06:53 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    var list = [T?]()
Array를 이용할시는거 같은데 `list.removeFirst()`같은거를 활용한다면 옵셔널이 필요없지 않을까요?

2022-03-21 09:19 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    var list = [T?]()
list.removeFirst()를 사용하게 되면, 시간 복잡도 문제가 발생해서 옵셔널을 사용하여 nil로 초기화하고 head가 100 이상이 되면 removeFirst()를 사용해주도록 하였습니다.

2022-03-21 10:17 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +        return element
해당 코드 수정했습니다!

2022-03-21 10:18 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>:CalculateItem {
다루는 요소가 CaculateItem 프로토콜을 채택하도록 수정했습니다!

2022-03-21 12:38 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
`compactMap`을 사용하는 이유는 nil값을 필터링하기 위해서라고 이해했는데요.
`compactMap`의 반환 타입이 Array인데 `isEmpty`를 호출할 때마다 사용하지 않는 Array를 만들고, nil을 필터링하기 위해 list를 처음부터 끝까지 돌아야하는데 이런 방법이 효율적일까요?.?

2022-03-21 12:47 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +        if head > 100 {
100이 queue의 용량을 의미하는거로 이해했는데요.
해당 사항이 명세서에 있을까요?

2022-03-21 14:10 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +        if head > 100 {
용량이 아닌 임의로 head를 100번 이상 밀리게 되면 초기화 해주는 것으로 설정했습니다!

2022-03-22 10:58 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
`head`와 다른 점이 무엇일까요?

2022-03-22 10:58 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
last는 어떤 의미의 프로퍼티일까요? enqueueStack이 비어 있을때에는 last는 뭘까요?

2022-03-22 10:58 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
enqueueStack의 count만 본다면 queue의 count임을 보장할 수 있나요?

2022-03-22 11:48 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
enqueueStack의 first를 찾는 것인데, 의미가 없는 것 같습니다. 삭제하도록 하겠습니다!

2022-03-22 12:10 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
dequeueStack이 없다면 enqueueStack의 last고 아니면 dequeueStack의 first인데 제가 착각했습니다.
만약 enqueueStack이 비어있다면, nil 값일 것 같습니다. 코드 수정했습니다!

2022-03-22 12:11 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
enqueueStack이 없다면 dequeueStack의 last고 아니면 emqueueStack의 first로 수정했습니다!

2022-03-22 12:12 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
dequeueStack과 enqueueStack이 공존하는 경우를 생각하지 못했습니다. 수정했습니다!

2022-03-22 12:22 UTC, wonhee009 approved these changes
@kimt4580 스텝1 수고하셨습니다!🎉
코멘트 남겨두었는데 다음 스텝에서 반영해주시면 좋을거 같습니다!

2022-03-22 12:22 UTC, wonhee009 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
해당 프로퍼티를 사용하는 곳이 있을까요?

2022-03-22 12:22 UTC, merged

2022-03-22 12:32 UTC, kimt4580 commented on Calculator/Model/CalculatorItemQueue.swift
> +    }
test 코드 작성 할 때 사용하려고 했었는데 활용을 못한 것 같습니다! 다음 step 2에서는 활용하도록 하겠습니다.