계산기 1 [STEP 2] 쿼카
yagom-academy/ios-calculator-app pull request #191
Opened 2022-03-21 08:59 UTC by Quokkaaa

@1Consumption
안녕하세요 울라프! ⛄ STEP2 PR보내드립니다.

# UML
![스크린샷 2022-03-21 17 55 28](https://user-images.githubusercontent.com/91132536/159230029-10d8d86f-1bab-478a-a501-bd7d059b6238.png)

# 고민했던점&어려웠던점
- UML속에 있는 메서드들의 기능을 파악하는데 시간투자가 많았던것같습니다.
- 연산자를 구분하는 방법 `ExpressionParser`타입내 `componentsByOperator`와 `split`메서드를 활용해서 연산자와 피연산자를 분리하는 기능구현이 어려웠습니다.
- `split`메서드를 활용해서 숫자와 연산자를 분리하는 방법
- `result`메서드내에서 연산자와 피연산자가 `nil`일경우의 오류처리 구현
- divide메서드 사용시 0.0으로 나누기를 했을때의 오류처리
- 함수 기능분리
componentsByOperators()메서드내에서 연산자도 추출해야만 피연산자를 구할 수 있는 로직이다보니 연산자를 추출하는 기능까지 포함되어있어 기능분리가 필요하다고 판단했습니다. 그래서 연산자를 추출하는 코드는 exctractOperators()메서드로 따로 빼주었습니다.
- `Operator`의 `rawValue`값
`Operator`타입의 `case rawValue`가 기본 +,-,/,* 로진행했을때 만약에 입력된 문자열값에 `-2`인 음수가 존재할때 연산자와 겹칠 수 있어 이모지를 활용하여 연산자를 구분해주었습니다.

# 문제해결
- split을 활용해 연산자와 피연산자를 분리하는 로직을 구현할때 `operator.allCases`를 반복문을 돌려 `components`를 시켜주려고 했으나
숫자의 순서가 보장된 상태로 분리하는게 되지않았습니다. 예를들어 같은 연산자가 여러게있는경우
ex) `["5➕10➕2➖2✖️-2➗2➕5"]` -> `["5","10","2➖2✖️-2➗2","5"]` 이렇게 분리된 후에 분리한것들만 순서대로 담고 분리안된 요소를 추가로 분리하려고 했을때 순서가 보장되기가 어렵다고 판단했습니다.
그래서 앞에서부터 하나의 연산자만 `split`으로 `maxSplit`매개변수를 추가하여 한번만 분리한 후 [0]번째 인덱스의 값(분리가된 피연산자)을 새로운 배열에 넣고 [1]번째 인덱스의 값(분리가필요한값) 을 `string`값으로 다시 저장한 후에 이걸 반복하는 방식으로 진행하였습니다.

# 궁금한점&조언얻고싶은점
- 부동소수점이 나타나는 이유가 궁금합니다.
`let number = 234.532` 의 값을 저장했고 이를 lldb로 확인해봤을때 소수점 14자리값이 1이라는 오차가 발생하였습니다. 왜그런걸까요 ?
![](https://i.imgur.com/l9g007P.png)

- `ExpressionParser`가 `enum`으로 구현된 이유?
보통 `enum`은 나열할 수 있는데이터를 묶는데 주로 사용했었는데 `case`를 사용하지않고 메서드만 담아서 사용하는 타입으로 사용되었습니다.
enum의 특성이 저장프로퍼티를 생성할 수 없다는 점에서 `struct`로 구현해줄 필요가 없었던건지?? 아니면 다른 이유가 존재하는건지 궁금합니다.

- `result`메서드로직이 `operands.count`수 만큼 반복문을 돌려서 연산자의 연결된 메서드로 순서대로 연산을 해주며 값이 nil일때는 `0.0`을 `return`하는 로직으로 구현을 해보았으나 조금 안정적인 로직은 아니라고 판단되어 오류처리를
넣어주었습니다. 그런데 반환값으로 `Double?`타입을 지정하고 `nil`을 `return`해주는 방법도 있을것같지만 제가 생각했을때는 `nil`을 반환하게되면 연산 도중 런타임 오류가 발생할 수 있을것 같아 에러처리로 구현하는게 안전한 로직이라고 판단했어요. 혹시 이렇게 구현한 로직에 개선할 점이있거나 다른 더 좋은 방법이 있다면 조언 좀 부탁드립니다.

2022-03-22 06:21 UTC, Quokkaaa commented
@1Consumption 
울라프! 부동소수점에대해서 알아본 내용입니다.

부동소수점이란 3.14159, 0.1, -273.15와 같은 소수구성요소가 있는 숫자를 말합니다.
부동 소수점 유형은 정수유형보다 훨씬 더 넓은 범위의 값을 나타낼 수 있으며 Int에 저장할 수 있는 것보다 훨씬 크거나 작은 숫자를 저장할 수 있습니다.
Swift에서는 두가지 부호있는 부동소수점 숫자 유형을 제공하는데 Double과 Float이 있으며 Double은 64bit, Float은 32bit를 나타냅니다.
Double의 정밀도는 최소 15자리 소수점 이하 자릿수인반면 Float의 정밀도는 소수점이하 6자리까지 가능합니다.

`오차가 발생하는 이유`
내부적으로 컴퓨터는 0.1, 0.2 또는 0.3과 같은 숫자를 정확하게 나타낼 수 없는 형식(이진 부동소수점)을 사용하기 때문입니다. 코드가 컴파일되거나 해석될때 "0.1"은 이미 해당형식에서 가장 가까운 숫자로 반올림되어 계산이 발생하기전에도 작은 반올림 오류가 발생합니다.

`부동 소수점이 필요한이유`
컴퓨터 메모리는 제한되어 있기때문에 이진분수를 사용하든 소수를 사용하든 상관없이 무한정 정밀도로 숫자를 저장할 수 없습니다. 그래서 어느지점에서 끊어줘야합니다.

`반올림 오류가 발생하는 이유`
부동 소수점 숫자는 자릿수가 제한되어 있기때문에 모든 실수를 정확하게 나타낼 수 없습니다. 형식이 허용하는 것보다 더 많은 자릿수가 있는 경우 남은 자릿수는 생략되고 숫자는 반올림이됩니다.

[Floating-Point-Guide](https://floating-point-gui.de/formats/fp/)
[stackoverflow](https://stackoverflow.com/questions/54626597/float-and-double-arithmetic-not-returning-accurate-results)
[floating-pointNumber공식문서](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#:~:text=Floating%2DPoint%20Numbers,Double%20is%20preferred.)

2022-03-22 12:21 UTC, 1Consumption requested changes
안녕하세요 쿼카~
스텝2도 고생 많으셨습니다.
고민한 점이 느껴지는 코드였어요.

그런데 너무 최적의 시나리오만 테스트했다는 생각이 들어요. 여러가지 엣지케이스를 잡아내고, 대응하는것이 유닛테스트의 장점이기도한데 말이죠.
여러가지 엣지 케이스도 신경써주시면 좋겠습니다!

그리고 실패하는 테스트가 있었는데.. 이부분도 같이 봐주시면 좋겠습니다.

아래는 질문주신 점에 대한 제 코멘트입니다.

# 궁금한점&조언얻고싶은점
> 부동소수점이 나타나는 이유가 궁금합니다.
`let number = 234.532` 의 값을 저장했고 이를 lldb로 확인해봤을때 소수점 14자리값이 1이라는 오차가 발생하였습니다. 왜그런걸까요 ?
![](https://i.imgur.com/l9g007P.png)

이 부분은 추가로 남겨주신 코멘트에서 잘 학습해주셨네요!

> `ExpressionParser`가 `enum`으로 구현된 이유?
보통 `enum`은 나열할 수 있는데이터를 묶는데 주로 사용했었는데 `case`를 사용하지않고 메서드만 담아서 사용하는 타입으로 사용되었습니다.
enum의 특성이 저장프로퍼티를 생성할 수 없다는 점에서 `struct`로 구현해줄 필요가 없었던건지?? 아니면 다른 이유가 존재하는건지 궁금합니다.

저는 메모리에 계속 살아있는 네임스페이스를 사용하기 위함이라고 생각됩니다. 물론 struct나 class의 인스턴스 메소드로 선언해주고 매번 인스턴스를 만들어 사용하는 방법도 있습니다. 하지만 앱 전역적으로 살아있어야하기 때문에 매번 생성할 필요가 없다면 enum으로 만들어주는 편이에요.

> `result`메서드로직이 `operands.count`수 만큼 반복문을 돌려서 연산자의 연결된 메서드로 순서대로 연산을 해주며 값이 nil일때는 `0.0`을 `return`하는 로직으로 구현을 해보았으나 조금 안정적인 로직은 아니라고 판단되어 오류처리를
넣어주었습니다. 그런데 반환값으로 `Double?`타입을 지정하고 `nil`을 `return`해주는 방법도 있을것같지만 제가 생각했을때는 `nil`을 반환하게되면 연산 도중 런타임 오류가 발생할 수 있을것 같아 에러처리로 구현하는게 안전한 로직이라고 판단했어요. 혹시 이렇게 구현한 로직에 개선할 점이있거나 다른 더 좋은 방법이 있다면 조언 좀 부탁드립니다.

아니요 좋아보입니다. 어쨌든 에러가 발생했고, 처리를 해줘야하니까요.

2022-03-22 12:21 UTC, 1Consumption commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
input이 `5+`인 경우는 어떻게되나요?
TDD를 여러가지 에러 케이스를 만들어두고, 하나하나 정복해가는 느낌으로 접근해보세요.

2022-03-22 12:21 UTC, 1Consumption commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
계산식 내용을 설명하는게 아니라 보다 더 기능에 집중한 네이밍이면 좋을거같아요.

2022-03-22 12:21 UTC, 1Consumption commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
여기도 그래요. 가독성이 상당히 좋지않네요. 정확히 어떤걸 테스트하는 메소드인가요?

2022-03-22 12:21 UTC, 1Consumption commented on Calculator/OperatorTest/OperatorTest.swift
> +}
여기는 각각 연산자에 대한 테스트네요. 이름도 그에 맞게 바꾸면 좋겠습니다. 어떤 값을 가지고 테스트했냐는 그렇게 중요하지 않아요.
다만 0으로 나눈 경우, 연산자나 피연산자가 nil인 경우에 에러를 던지니 그 부분은 테스트를 추가해야겠네요.

2022-03-22 12:21 UTC, 1Consumption commented on Calculator/Calculator.xcodeproj/xcshareddata/xcschemes/Calculator.xcscheme
>                 ReferencedContainer = "container:Calculator.xcodeproj">
테스트 파일별로 타겟을 생성하지 말고 유닛테스트 타겟은 하나만 두고 테스트 파일을 추가하는건 어떨까요?

2022-03-22 12:38 UTC, Quokkaaa commented on Calculator/Calculator/Extension/Split.swift
> +    }
위 문제해결에 작성한 부분과 동일합니다.
예를들어 `5➕10➖5➗2 ✖️3➕5` 이상태에서 기존의 split을 활용하게되면 ➕ 연산자들이 동시에 분기가되기때문에 이 상태에서 분리가 필요한 나머지의 값을 추출해서 또 split을 하고 다시 정렬해줘야한다는게 어렵다고판단했어요
그런데 다른 캠퍼와 얘기해보니 기존 split메서드를 사용한 상태에서 추가로 split을 사용하면 이중배열이 되는데 이상태에서 flapMap 고차함수로 풀어줄 수 있다는 방법도 알게되었습니다.

2022-03-22 12:50 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            .forEach(queueOperators.enqueue(_:))
이해가잘 되지않는데요 혹시 자세한 설명가능한가요 ?

2022-03-22 12:52 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var operands = [String]()
input을 받은 값을 split을 하게되면 반환값이 string이라서 그에 맞게 해줘야하지않나요 ??
혹시 어떤 의도로 얘기하시는걸까요 ?

2022-03-22 13:04 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            newInput = splitedValues[1]
```swift
newInput = splitedValues.removeLast()
operands.append(splitedValues.removeLast())
```
remove메서드를 활용하거나 또는 .last 나 .first 프로퍼티를 바인딩으로 추출해볼 수 있을것같네요 !

2022-03-22 13:57 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
```swift
    static private func exctractOperators(from input: String) -> [Operator] {
        return input.compactMap {Operator(rawValue: $0)}
    }
```
이렇게 바꿔볼 수 있네요 ㅎㅎ 감사합니다.

2022-03-22 14:10 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            if let _ = Int(newInput) { operands.append(newInput); return }
이메서드의 반환타입이 [String]라서 결국 형변환을 해주고 반환해야하지 않나요 ?

2022-03-22 14:31 UTC, Quokkaaa commented on Calculator/Calculator/Model/Formula.swift
> +        return result
operands에 담긴 숫자들만큼 반복문을 돌리기위해 count값을 저장합니다.
첫 operands.dequeue한 값을 result 변수에 담아놓고
한번 dequeue를 했으니 2부터 반복문을 돌려서 count만큼 operator메서드에 result와 operandValue값을 할당하여 result로 저장하는겁니다.
```swift
예시) 5➕10➖5➗2 ✖️3➕5
operands = 5,10,5,2,3,5
operators = ➕,➖,➗,✖️,➕
var operandsCount = 6

첫번째 반복문, 2...6
var result = operands.dequeue(5)
var operandValue = operands.dequeue(10)
var operatorValue  = operators.dequeue()
result = operatorValue.calculate(5➕10)

두번째 반복문, 3...6
operands = 5,2,3,5
operators = ➖,➗,✖️,➕

var result = 15
var operandValue = operands.dequeue(5)
var operatorValue  = operators.dequeue(➖)
result = operatorValue.calculate(15➖5)

세번째 반복문, 4...6
operands = 2,3,5
operators = ➗,✖️,➕

var result = 10
var operandValue = operands.dequeue(2)
var operatorValue  = operators.dequeue(➗)
result = operatorValue.calculate(10➗2)

네번째 반복문, 5...6
operands = 3,5
operators = ✖️,➕

var result = 5
var operandValue = operands.dequeue(3)
var operatorValue  = operators.dequeue(✖️)
result = operatorValue.calculate(5✖️3)


다섯번째 반복문, 6...6
operands = 5
operators = ➕

var result = 15
var operandValue = operands.dequeue(5)
var operatorValue  = operators.dequeue(➕)
result = operatorValue.calculate(15➕5)

return result(20)
```

2022-03-22 14:32 UTC, Quokkaaa commented on Calculator/Calculator/Model/Formula.swift
> +        return result
@1Consumption 
dequeue가 메소드가 아니라는게 어떤뜻인가요 ?

2022-03-22 14:34 UTC, Quokkaaa commented on Calculator/Calculator/Protocol/CalculateItem.swift
넵

2022-03-22 14:34 UTC, Quokkaaa commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
제거 하겠습니다 ㅎㅎ!

2022-03-22 14:54 UTC, Quokkaaa commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
조건과 결과에 대한 네이밍이 표현력이 좋지만 이 처럼 복잡한 조건에는 기능에 집중하는 네이밍이 좋다는 말씀이실까요 ??

2022-03-22 14:56 UTC, Quokkaaa commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
그럴 수 있겠네요 !!
이 경우에는 
```swift
    func result() throws -> Double {
        let operandsRangeCount = 2..<operands.count
        guard operands.count > 2 || operators.isEmpty else {
            throw CalculateError.cannotCalculation
        }
```
연산자와 피연산자가 부족하면 오류를 던지는  방식으로 구현해보았습니다.

2022-03-22 15:07 UTC, Quokkaaa commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
result메서드를 테스트하기 위함인데요..!! 그러려면 큐에 값을 넣어야하다보니 가독성이 많이 안좋아진것같습니다.

2022-03-23 06:47 UTC, Quokkaaa commented on Calculator/Calculator.xcodeproj/xcshareddata/xcschemes/Calculator.xcscheme
>                 ReferencedContainer = "container:Calculator.xcodeproj">
테스트파일을 한파일에 담아서 관리하는게 깔끔한것같아요 !
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/3dd38b4f2b8b8c91852b564353ac8a03d00f7942

2022-03-23 06:52 UTC, Quokkaaa commented on Calculator/OperatorTest/OperatorTest.swift
> +}
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/c72184e0a0f5241fdd5c988ef9286162c27a0d83

2022-03-23 07:08 UTC, Quokkaaa commented on Calculator/OperatorTest/OperatorTest.swift
> +}
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/c4c5c085f65a3fe5cb719bb45137989a6740808c

2022-03-23 07:50 UTC, Quokkaaa commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/3ea6ec97923214660ce536a87c0cf252ea31f849

2022-03-23 07:51 UTC, Quokkaaa commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/e30f2109fcc8c872aaa736ed527114c5d86e75c0

2022-03-23 07:52 UTC, Quokkaaa commented on Calculator/Calculator/Protocol/CalculateItem.swift
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/230f539915ee27064cb2062a5745798c81ede761

2022-03-23 07:54 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/32efe4ef0055ec380d88049ede71c0257427af6c

2022-03-23 07:57 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            newInput = splitedValues[1]
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/0c116db00347204a85b137b01b98b8128ef93ddc

2022-03-23 13:33 UTC, Quokkaaa commented on Calculator/Calculator/Model/Formula.swift
> +        return result
사이드이펙이있을경우엔 메서드 아닐경우엔 연산프로퍼티사용

2022-03-23 13:37 UTC, Quokkaaa commented on Calculator/Calculator/Model/Formula.swift
> +        return result
while문으로 리펙토링 고려

2022-03-23 13:42 UTC, Quokkaaa commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
super 호출 필요

2022-03-23 13:44 UTC, Quokkaaa commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
유저 입장에서 엣지케이스로 테스트를 시도할 필요가 있음

2022-03-23 16:12 UTC, Quokkaaa commented on Calculator/Calculator/Model/Formula.swift
> +        return result
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/8956e1606195974910534a63d939ee6ce351630e

2022-03-24 03:58 UTC, Quokkaaa commented on Calculator/Calculator/Model/Formula.swift
> +        return result
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/b60bd54cf6db1b5939f4caccd797fc9b35139bb5

2022-03-24 04:00 UTC, Quokkaaa commented on Calculator/Calculator/Model/Operator.swift
> +        return lhs*rhs
https://github.com/yagom-academy/ios-calculator-app/pull/191/commits/243ce14f0cab56bb1859a457d8228f2004b5adfe

2022-03-24 10:36 UTC, 1Consumption requested changes
코멘트 하나 확인 부탁드릴게요

2022-03-24 10:36 UTC, 1Consumption commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            operands.append(splitedValues.removeLast())
removeLast()는 정말 안전한가요? 배열이 비어있는 상태에서 해당 메소드를 실행하면 어떻게 되나요?
Discussion을 읽는 습관을 들여주세요.

2022-03-24 12:28 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            operands.append(splitedValues.removeLast())
```swift
            guard let remainingValue = splitedValues.popLast(),
                  let operandValue = splitedValues.popLast() else { return }
            newInput = remainingValue
            operands.append(operandValue)
```

2022-03-24 12:28 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            operands.append(splitedValues.removeLast())
이렇게 수정완료했습니다.

2022-03-24 12:30 UTC, 1Consumption commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            operands.append(splitedValues.removeLast())
여기서도 error를 던지는게 어떨까요? 둘중 하나라도 없으면 계산이 무의미해지니까요

2022-03-24 12:37 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            operands.append(splitedValues.removeLast())
맞습니다!
```swift
            guard let remainingValue = splitedValues.popLast(),
                  let operandValue = splitedValues.popLast() else {
                throw CalculateError.cannotCalculation
            }
```

2022-03-24 12:37 UTC, Quokkaaa commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            operands.append(splitedValues.removeLast())
이와 같이 수정하고 커밋했습니다.

2022-03-24 12:39 UTC, merged