계산기 1 [STEP 2] 사파리
yagom-academy/ios-calculator-app pull request #192
Opened 2022-03-21 11:59 UTC by saafaaari

@1Consumption
안녕하세요. 올라프 
safari입니다. STEP2 PR 보냅니다.
잘 부탁드립니다.🙇‍♂️

# UML

<img src="https://i.imgur.com/ZsXpJEu.png">

# 문제상황과 해결방법
- split 로직에 대해서
- parse함수에서 생성된 Formule타입 내부 큐에 값이 잘 들어갔는지에 대한 테스트 
- 0으로 나눴을때, 오류 처리
- 연산식에 기본 시작값

## split 로직에 대해서
처음 String타입을 확장해서 split함수를 만들 때,
```swift
func split(with target: Character) -> [String] {
        return self.components(separatedBy: String(target))
    }
```
위처럼 연산자로만 분리하였습니다.
장점은, "2+3*2"처럼, 입력했을 때, 연산자로만 분리할 수 있었습니다. 하지만,
"2*-3+3"같은 경우 -3의 "-"는 연산자가 아닌 마이너스 부호이기 때문에, 연산자와 부호의 구문이 필요했습니다. 이와 같은 문제를 두 가지 해결책을 생각해 볼 수 있었습니다.
첫 번째는, 두 연산자가 붙어있고, 두 번째 연산자가 "-"이면 부호로 치는 방법입니다.
두 번째는, 입력 자체를 연산자 앞뒤로 공백을 넣어 입력하여 연산자와 부호를 구분하는 방법이었습니다. 예를 들어. "2 + 3 x -3"
결론적으론 두 번째 방법을 선택하여
```swift
func split(with target: Character) -> [String] {
        return self.components(separatedBy: " \(target) ")
    }
```
위와 같이 코드를 리팩토링하였습니다.
두 번째 방법을 선택한 이유는 먼저 두 코드를 생각해 봤을 때, 두 번째 방법이 간단하고, 코드가 간결할 것이라 생각해 가독성 면에서 더 나은 이점이 있을 것이라 생각했고, 공백은 UI에서 입력할 때 로직으로 해결하면 된다고 생각했습니다. 또한,
<img src="https://i.imgur.com/1UMxQQi.png" width="300">

UI 예시에도 연산과 수 사이엔 공백이 있고 부호와 수는 붙어있음을 확인할 수 있었습니다. 때문에 UI까지 생각했을 때, 두 번째 방법이 더 많은 이점이 있다고 생각해 채택하였습니다.

## compomnentsByOperators메서드와 parse메서드에 대한 테스트 
**compomnentsByOperators**메서드는 `split`을 가지고 input 데이터에서 피연산자만, 문자열 배열로 반환하는 메서드입니다. 이 메서드는 `private` 메서드이기 때문에, 단독으로 테스트를 할 수 없었습니다. 때문에 parse 메소드 테스트 과정에서 같이 테스트를 하는 방법을 선택했습니다.

**parse**메서드는 큐에 input 문자열을 가지고 연산자와 피연산자로 분리하여 큐에 enpueue 한 뒤, 그 큐를 가진 Formule 인스턴스를 반환하는 메서드입니다.
근데 Formule가 가지고 있는 큐에 원하는 값이 잘 들어갔는지 테스트하는 것은 생각보다 골치 아픈 일이였습니다. 왜냐하면, 먼저 큐에는 내부 데이터를 보여주는 메서드가 없습니다. 때문에 테스트를 위한 함수를 만들어야 테스트를 할 수 있는데 그는 좋은 방법이 아니라는 것을 배웠습니다. 그리고, 큐 내부 데이터를 테스트하는 것이 ExpressionParser 타입의 parse메서드를 테스트하는 것과 좀 거리감이 있다고 생각했습니다. parse의 목적은 문제없이 Formule를 반환하는 것이 목적이라 생각이 들어 ExpressionParser타입 테스트에선 만들어진 Formule가 올바른 계산을 하는지에 대한 테스트를 진행하였고, 큐에 올바른 값이 들어가지는지에 대한 확신은 breakpoint를 통해 확인하였습니다.

## 0으로 나눴을 때, 오류 처리
0으로 나눴을 때, 오류 처리를 해줘야 했습니다.
이 문제에 대해서 오류문을 던질지, 로직으로 해결할지 고민을 했습니다. 결론적으론 로직으로 해결하였습니다.
```swift
private func divide(lhs: Double, rhs: Double) -> Double {
        guard rhs != .zero else { return .nan }
        return lhs / rhs
    }
```
위와 같은 방법으로 .nan을 반환하는 조건문을 추가하였습니다.

## 연산식에 기본 시작값
아이폰 기본 계산기 앱을 조사해 봤을 때, 연산자 "*"와 3을 입력했을 때 기본값 연산식 시작 값 0을 두고 연산이 이루어짐을 확인할 수 있었습니다. 때문에 "+ 3 * 2"와 같이 연산식으로 시작하는 input 값을 들어왔을 때 먼저 0을 피연산자 큐에 enqueue 하고 시작할 수 있도록 기능을 추가하였습니다.

# 조언을 받고 싶은 부분
- 가독성을 위해 줄바꿈 추가
- TDD를 적극 사용하지 못한 부분

## 가독성을 위해 줄바꿈 추가
이번 스탭에서 올라프의 저번 피드백을 좀 반영하여 개행에 대한 기준을 세웠습니다.
특수한 경우가 아닐 시 타입 내부 또는, 메서드 내부 가장 상단엔 저장 프로퍼티를 위치하였습니다.
또한, 제어 코드는 그 사이에 한 번의 개행을 주었습니다. 추가적으로 LinkeList에 메서드들 중에서 일부 if 문을 guard 문으로 수정하였습니다. 이 부분에 대해 코드를 읽었을 때 좀 더 가독성이 나아졌는지 궁금합니다.

## TDD를 적극 사용하지 못한 부분
사실 ExpressionParser타입을 구현할 때부터 TDD를 적극 활용하지 못하였습니다. 먼저 compomnentsByOperators 메서드가 은닉화가 되어있어, 테스트를 하지 못하고 기능을 구현하였습니다.
parse메서드 또한, compomnentsByOperators메서드가 잘 돌아가나 확인하고 싶어 기능부터 구현하고, 테스트를 통해 버그를 잡았습니다. 프로젝트를 하다 보면 은닉화된 메서드를 자주 구현하게 되는데 이때 올바른 TDD 방법은 무엇인지 올라프의 조언을 듣고 싶습니다. 사실 한번 이야기를 나눌 기회가 있었지만, 그때 잘 이해를 못 했습니다.

2022-03-22 15:00 UTC, 1Consumption requested changes
안녕하세요 사파리~ 고생 하셨습니다.

남겨주신 코멘트에 대해서 제 생각을 조금 적어봤어요.
그리고 텍스트로는 설명하기 어려운게 있어 디코로 얘기를 해보도록 해요.

> **parse**메서드는 큐에 input 문자열을 가지고 연산자와 피연산자로 분리하여 큐에 enpueue 한 뒤, 그 큐를 가진 Formule 인스턴스를 반환하는 메서드입니다.
근데 Formule가 가지고 있는 큐에 원하는 값이 잘 들어갔는지 테스트하는 것은 생각보다 골치 아픈 일이였습니다. 왜냐하면, 먼저 큐에는 내부 데이터를 보여주는 메서드가 없습니다. 때문에 테스트를 위한 함수를 만들어야 테스트를 할 수 있는데 그는 좋은 방법이 아니라는 것을 배웠습니다. 그리고, 큐 내부 데이터를 테스트하는 것이 ExpressionParser 타입의 parse메서드를 테스트하는 것과 좀 거리감이 있다고 생각했습니다. parse의 목적은 문제없이 Formule를 반환하는 것이 목적이라 생각이 들어 ExpressionParser타입 테스트에선 만들어진 Formule가 올바른 계산을 하는지에 대한 테스트를 진행하였고, 큐에 올바른 값이 들어가지는지에 대한 확신은 breakpoint를 통해 확인하였습니다.

Queue 내부의 값을 왜 테스트 해야하나요? 이미 Queue 유닛테스트에서 확인한게 아닌가요? 이걸 사용하는 메소드에서 Queue 내부에 어떤 값이 있는지를 테스트하는게 맞을까요?

> 0으로 나눴을 때, 오류 처리
0으로 나눴을 때, 오류 처리를 해줘야 했습니다.
이 문제에 대해서 오류문을 던질지, 로직으로 해결할지 고민을 했습니다. 결론적으론 로직으로 해결하였습니다.
```swift
private func divide(lhs: Double, rhs: Double) -> Double {
        guard rhs != .zero else { return .nan }
        return lhs / rhs
    }
```
위와 같은 방법으로 .nan을 반환하는 조건문을 추가하였습니다.

계산기는 중간에 에러가 발생하면 정상적인 결과를 예상할 수 없기 때문에 에러를 던지고 계산을 종료하는게 어떨까요?

> 가독성을 위해 줄바꿈 추가
이번 스탭에서 올라프의 저번 피드백을 좀 반영하여 개행에 대한 기준을 세웠습니다.
특수한 경우가 아닐 시 타입 내부 또는, 메서드 내부 가장 상단엔 저장 프로퍼티를 위치하였습니다.
또한, 제어 코드는 그 사이에 한 번의 개행을 주었습니다. 추가적으로 LinkeList에 메서드들 중에서 일부 if 문을 guard 문으로 수정하였습니다. 이 부분에 대해 코드를 읽었을 때 좀 더 가독성이 나아졌는지 궁금합니다.

이부분은 코멘트로 따로 남겼어요!

> TDD를 적극 사용하지 못한 부분
사실 ExpressionParser타입을 구현할 때부터 TDD를 적극 활용하지 못하였습니다. 먼저 compomnentsByOperators 메서드가 은닉화가 되어있어, 테스트를 하지 못하고 기능을 구현하였습니다.
parse메서드 또한, compomnentsByOperators메서드가 잘 돌아가나 확인하고 싶어 기능부터 구현하고, 테스트를 통해 버그를 잡았습니다. 프로젝트를 하다 보면 은닉화된 메서드를 자주 구현하게 되는데 이때 올바른 TDD 방법은 무엇인지 올라프의 조언을 듣고 싶습니다. 사실 한번 이야기를 나눌 기회가 있었지만, 그때 잘 이해를 못 했습니다.

이부분도 디코로 얘기를 해보도록해요~

2022-03-23 01:45 UTC, saafaaari commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
" + 1 + 3 - 2" 같이 연산자가 먼저 시작하면, 0을 기본값으로 넣어주는 코드입니다. 결론적으로 "0 + 1 + 3 - 2"와 같은 결과가 나오게 됩니다. 필요없는 기능일까요??

2022-03-23 01:50 UTC, saafaaari commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    var sut: CalculatorItemQueue<MockList<Int>>!
공부하다가 알게 됐는데 mook이 아닌 mock 임을 확인해서 오타를 수정한 부분이었습니다.

2022-03-23 01:58 UTC, saafaaari commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    }
parse함수가 하는 일 중 대표는 Formula인스턴스를 반환하는 거라 생각해 반환하는 값이 Formula임을 확인한 코드 입니다. 하지만, 지금 보니 반환타입이 Formula인데 의미가 없는 테스트 케이스인것 같다는 생각이 듭니다. 좀더 의미있는 테스트 케이스로 수정해 보겠습니다.

2022-03-23 07:42 UTC, saafaaari commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/192/commits/88e2a254e2ff5facfdba8769c04c031dc8cbd4db 이와같이 수정을 해보았습니다.

2022-03-23 07:43 UTC, saafaaari commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    }
삭제를 했습니다.

2022-03-23 07:45 UTC, saafaaari commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    }
의식을 못했는데, 좀더 이러한 부분을 의식하고, 쓸모없는 코드는 삭제하는 습관을 길러보겠습니다.
감사합니다.

2022-03-23 07:47 UTC, saafaaari commented on Calculator/Calculator/Model/LinkdeList.swift
> +
확실히 다시 if문을 사용하고 긍정표현을 쓰는 방법이 더 가독성면에서 이점이 많은 것 같습니다.
이젠 guard와 if문을 더욱 적절할게 사용할 수 있을것 같아요.
감사합니다.

2022-03-23 07:47 UTC, saafaaari commented on Calculator/Calculator/Model/ExpressionParser.swift
> +
삭제했습니다. 감사합니다.

2022-03-23 08:01 UTC, saafaaari commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
이 부분에 대해서 많은 고민을 했는데 compomnentsByOperators에서 오류를 던지도록 하였습니다.
이유는 저 else문은 실행되기 힘든 구조를 가지고 있습니다. 이미 앞전에서 rawValue에 들어올 수 있는 값만을 operators가 가지고 있기 때문입니다. 하지만 https://github.com/yagom-academy/ios-calculator-app/pull/192/commits/4f6cf2c559ef40af50c30452d408c1646e0305ed 에서와 같이 compomnentsByOperators에서 잘못된 입력값이 들어왔을 때
```swift
 guard value.count == value.compactMap({ Double($0) }).count else {
            throw CalauletorError.invalidInputValue
        }
```
위 코드를 통해 검증하여 오류를 던지도록 하였습니다.

2022-03-23 08:02 UTC, saafaaari commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorQueue = CalculatorItemQueue<LinkdeList<Operator>>(LinkdeList<Operator>())
수정하였습니다. 감사합니다.

2022-03-23 08:03 UTC, saafaaari commented on Calculator/Calculator/Model/CalculateItem.swift
> +    }
올라프의 조언대로 오류를 던지는 방향으로 수정하였습니다.
https://github.com/yagom-academy/ios-calculator-app/pull/192/commits/d6e66d4650e67d2c3fa3692eda692337d602c439

2022-03-23 08:04 UTC, saafaaari commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
또한 data라는 변수의 네이밍을 opertorData로 수정하였습니다. data라는 네이밍이 너무 추상적인 느낌이 들었습니다. 더 나은 네이밍이 혹시 있을까요??

2022-03-24 10:27 UTC, 1Consumption commented
다음 스텝을 진행해주세요.

2022-03-24 10:27 UTC, merged