계산기 [STEP 2] Donnie
yagom-academy/ios-calculator-app pull request #195
Opened 2022-03-21 15:37 UTC by westeastyear

@AppleCEO
안녕하세요 도미닉!
계산기 [STEP 2]  PR 요청 보냅니다.
자꾸 PR계획을 바꿔서 죄송한 마음입니다ㅠㅠ
잘 부탁드립니다~! 🙇🏻‍♂️ 

---

# 📍 UML
<img src="https://user-images.githubusercontent.com/74251593/159279325-54f4c081-724c-4be1-acd7-458b5f053b10.png" width="100%" height="100%">

STEP 2에 맞게 UML을 업데이트 하였습니다!
초반에는 어떻게 할지 몰라 해메고 있었는데, 여러 캠퍼들의 도움으로 감을 잡을 수 있었고 마무리 할 수 있어서 감사하게 생각합니다~!

# [STEP 2]

## ⁉️ extension String 구문 고민한점
```swift
// before
extension String: CalculateItem {
    func split(with target: Character) -> [String] {
        self.split(separator: target).map { character in
            String(character)
        }
    }
}
```
```swift
// after
extension String: CalculateItem {
    func split(with target: Character) -> [String] {
        return components(separatedBy: String(target))
    }
}
```
- 기존에는 `split()`과 `map`을 사용하여 구현을 했었습니다. `split()`과 `map`의 시간복잡도는 `O(n)`이고, 이 둘을 같이 쓰게 되면 `O(2n)`이 된다는걸 알게 되었습니다. 
- 우연히 `components(separatedBy:_)`를 알게 되고, 코드에 반영하여 `O(n)`의 시간복잡도를 가지게 되는 코드를 작성하게 되었습니다. 
- 또 `split()`은 반환하는 타입이 `[String]`인게 없어서 `map`을 사용했었는데, `components(separatedBy:_)`는 자체적으로 `[String]`을 반환해주어 더욱 깔끔한 코드를 작성할 수 있었습니다.

## ⁉️ guard문을 쓸지, if문을 쓸지 고민한점
```swift
// before
func dequeue() -> T? {
        guard !linkedList.isEmpty else { return nil }
        return linkedList.removeFirst()
    }
```
```swift
// after
func dequeue() -> T? {
        if linkedList.isEmpty {
            return nil
        } else {
            return linkedList.removeFirst()
        }
    }
```
- `guard`의 가장 큰 특징을 꼽자면 `early return`입니다. 제일 먼저 조건들을 판단, `true`인 경우에만 코드를 진행시키고, `false`인 경우에는 `return`을 하게 됩니다. 그래서 코드가 길지 않다면 `guard`를 할 필요가 없음을 깨닫게 되었습니다. 
- 전의 코드는 `guard`를 사용하여 역의 역의 생각을 해서 코드를 작성하였는데, 읽기가 어렵다고 느껴졌습니다. 코드가 길지 않기도 하고, 가독성을 위해 `if`문을 사용하여 코드수정을 하게 되었습니다.

## ⁉️ Charactor타입으로 형변환중에 생긴 오류처리를 위해 고민한점
```swift
componentsByOperators(from: input)
            .filter { $0.count == 1 }
            .compactMap { Operator(rawValue: Character($0)) }
            .forEach{ operatorQueue.enqueue($0)}
```
- `Thread 1: Fatal error: Can't form a Character from a String containing more than one extended grapheme cluster`
- 한자리의 `String`은 `Charactor`타입으로 형변환이 되지만, `String`이 두자리 이상이 되게 되면 위와같은 오류를 발생시키는것을 알게 되었습니다. 다른 캠퍼에게 물어봐서 이 상황을 해결할 수 있었습니다. 
- 코드상에서는 연산자(+, -, *, / )만 들어오게만 하면 되기에 `filter`함수를 사용하여 문자의 갯수가 1개가 아닌 값들은 걸러지도록 코드를 추가하여 마무리 할 수 있었습니다.

## 💬 궁금한점
- `enum ExpressionParser`가 왜 `enum`으로 만들어졌는지 궁금합니다. `struct`로도 충분하다고 생각이 되어지는데, 아카데미에서 이렇게 설정을 해놓은 이유가 궁금합니다.
- `struct Formula`에서 `operator`란 이름을 사용하고자 앞뒤로 따옴표를 붙여서 사용하고 있는데, 이렇게 사용해도 괜찮은지 도미닉의 조언 부탁드립니다!!

2022-03-22 00:08 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.
@westeastyear 고생하셨습니다!
코드 리뷰 드립니다.
질문에 대한 답변은 오전 중에 댓글로 추가드릴게요!

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +
여기 추가된 공백의 이유가 있을까요? ㅎㅎ
코드에는 공백이나 줄바꿈 하나에도 의미가 있어야 합니다.
의도를 나타낼 수 있는 최소한의 줄바꿈을 추천드려요.
무조건 적은 줄의 코드가 좋다는 뜻은 아닙니다~

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Model/Error/DivideError.swift
> +}
나누기 에러이군요! 열거형 이름이 명확하네요~ 👍 
계산기 에러라는 열거형 이름은 어떨까요?
+, -, x 에서는 에러가 발생하지 않을까요?

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            .forEach{ operatorQueue.enqueue($0)}
$0 을 사용하지 않고 기본적인 형태로 바꿔 볼 수 있을까요?
저는 축약형을 사용하지 않는 것을 권장합니다.
빠르게 작성할 수 있지만 아직 어떻게 동작하는지 이해하지 못하실 것 이라고 생각합니다.
회사에 들어가고 동료와 약속을 해서 어떤 때는 축약형을 사용하자라고 정하지 않은 상태에서 마구 줄이는 것은 좋지 않습니다.

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Model/Formula.swift
> +    func result() throws -> Double {
throws 를 사용하여 에러를 처리하는 부분 좋네요! 💯

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Model/Formula.swift
> +        guard var result = operands.dequeue() else { return 0 }
여기 한 줄로 guard 를 사용하셨군요.
저는 if 문과 guard 등에서 한 줄로 작성하는 것을 선호하지 않습니다.
무조건 적은 줄의 코드가 좋은 것은 아닙니다.
있어야 할 것이 예상되는 곳에 있는 코드가 좋은 코드라고 생각합니다!

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Model/LinkedList/CalculatorLinkedList.swift
>              head = newNode
여기 else 를 사용하지 않고 똑같이 동작하도록 수정해 볼 수 있을까요?

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Model/Operator.swift
> +    }
동작들이 명쾌하네요~ 🔢

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/Calculator/Model/Queue/CalculatorItemQueue.swift
> +        }
여기도 else 를 사용하지 않고 똑같이 동작하도록 작성해 볼 수 있을까요?
여러 책에서 else 를 사용하지 않는 것이 코드를 이해하기 좋다고 설명합니다.
어떤 이유에서 그럴지 고민해볼까요?

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        _ = sut1.dequeue()
sut 에 1을 붙인 이유는 무엇일까요?

2022-03-22 00:08 UTC, AppleCEO commented on Calculator/CalculatorTests/ExpressionParser_test.swift
> +    func test_0으로_나누었을때_오류처리를_하는지() throws {
테스트 메소드명이 명확하네요~: 🥇

2022-03-22 09:53 UTC, AppleCEO commented
질문에 대한 답변 드립니다~
- enum ExpressionParser가 왜 enum으로 만들어졌는지 궁금합니다. struct로도 충분하다고 생각이 되어지는데, 아카데미에서 이렇게 설정을 해놓은 이유가 궁금합니다.
-> 아마 enum 으로 struct와 비슷한 동작을 처리할 수 있다는 것을 알려주려고 한게 아닐까 싶습니다! 조금 더 자세한 내용은 크루에게 질문해주시면 의도를 알려주실 것 같아요~
- struct Formula에서 operator란 이름을 사용하고자 앞뒤로 따옴표를 붙여서 사용하고 있는데, 이렇게 사용해도 괜찮은지 도미닉의 조언 부탁드립니다!!
-> 저는 빼는 것이 좋다라는 의견입니다. 보통 자주 쓰는 단어는 예약어로 정해져있을 수 있고 그런 것들은 문제를 일으킬 수 있습니다. 더 길고 명확한 이름이 좋지 않을까 싶네요~

2022-03-23 02:35 UTC, westeastyear commented on Calculator/Calculator/Controller/ViewController.swift
> +
제가 미처 발견하지 못하였습니다.
의미없는 공백 제거하였습니다.

2022-03-23 02:40 UTC, westeastyear commented on Calculator/Calculator/Model/Error/DivideError.swift
> +}
당시, 나누기에만 `Error`처리를 한다는 생각에 네이밍을 지었었습니다. 
향후에 다양한 곳에서 `Error`가 발생할 수 있다고도 생각이 되어집니다.
조언해주신대로 네이밍 수정하였습니다.

2022-03-23 03:26 UTC, westeastyear commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            .forEach{ operatorQueue.enqueue($0)}
다음과 같이 수정하였습니다. 
```swift
componentsByOperators(from: input)
            .compactMap { value in
                Double(value)
            }
            .forEach { value in
                operandQueue.enqueue(value)
            }
        
        componentsByOperators(from: input)
            .filter { value in
                value.count == 1
            }
            .compactMap({ value in
                Operator(rawValue: Character(value))
            })
            .forEach { value in
                operatorQueue.enqueue(value)
            }
```

2022-03-23 03:29 UTC, westeastyear commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        _ = sut1.dequeue()
당시, 또 다른 sut를 만들어 놓고 수정하지 않았던거 같습니다.
수정하였습니다.

2022-03-23 03:45 UTC, westeastyear commented on Calculator/Calculator/Model/Formula.swift
> +        guard var result = operands.dequeue() else { return 0 }
return구문을 개행하여 수정하였습니다.

2022-03-23 09:08 UTC, westeastyear commented on Calculator/Calculator/Model/Queue/CalculatorItemQueue.swift
> +        }
다음과 같이 수정하였습니다.
```swift
func dequeue() -> T? {
        if linkedList.isEmpty {
            return nil
        }
        return linkedList.removeFirst()
    }
```
`else`를 사용했을때는 반전된 로직을 작성하게 되는 논리적 위험을 가지게 된다고 생각이 들었습니다. 조건문에서 `early return`할 수 있는 부분을 분리하여, 미리 종료하게 하면, 뒤의 코드로 진입하지 않아 else문을 사용하지 않아도 됩니다.

2022-03-23 09:30 UTC, westeastyear commented on Calculator/Calculator/Model/LinkedList/CalculatorLinkedList.swift
>              head = newNode
다음과 같이 수정해보았습니다.
```swift
if !isEmpty {
    let previousTail = tail
    newNode.previous = previousTail
    previousTail?.next = newNode
    tail = newNode
}
if isEmpty {
    head = newNode
    tail = newNode
}
```
도미닉이 의도한 바와 일맥상통할까요? 보내주신 링크를 기반으로 생각해 보았습니다!

2022-03-23 13:35 UTC, AppleCEO commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            .forEach{ operatorQueue.enqueue($0)}
value는 $0 을 쓰는 것과 큰 차이를 못 느끼겠네요!
더 자세한 상황에 맞춰서 각 줄에 변수명이 달라질 수도 있을까요? ㅎㅎ

2022-03-23 13:35 UTC, AppleCEO commented on Calculator/Calculator/Model/LinkedList/CalculatorLinkedList.swift
>              head = newNode
아래 if문은 꼭 필요할까요? ㅎㅎ

2022-03-23 14:15 UTC, westeastyear commented on Calculator/Calculator/Model/LinkedList/CalculatorLinkedList.swift
>              head = newNode
일단 `isEmpty`를 사용해서 확실한 조건을 명시해 주어서 가독성히 향상되었다고 생각이 되어집니다.
그런데 아래의 if문이 없는 경우 원활한 코드진행이 되지가 않습니다... 어떤걸 의미하신 걸까요??

2022-03-23 14:52 UTC, westeastyear commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            .forEach{ operatorQueue.enqueue($0)}
도미닉의 조언대로 다음과 같이 수정해보았습니다.
```swift
        componentsByOperators(from: input)
            .compactMap { element in
                Double(element)
            }
            .forEach { operandElement in
                operandQueue.enqueue(operandElement)
            }
        
        componentsByOperators(from: input)
            .filter { stringDigit in
                stringDigit.count == 1
            }
            .compactMap({ element in
                Operator(rawValue: Character(element))
            })
            .forEach { operatorElement in
                operatorQueue.enqueue(operatorElement)
            }
```

2022-03-24 01:10 UTC, westeastyear commented on Calculator/Calculator/Model/LinkedList/CalculatorLinkedList.swift
>              head = newNode
다음과 같이 리펙토링 하였습니다.
훨씬 더 간결해진거 같네요ㅎㅎㅎ
```swift
    func append(_ value: T) {
        let newNode = Node(value: value)

        if isEmpty {
            head = newNode
            tail = newNode
            return
        }
        newNode.previous = tail
        tail?.next = newNode
        tail = newNode
    }
```

2022-03-24 03:19 UTC, merged