계산기 [STEP 3] Grumpy
yagom-academy/ios-calculator-app pull request #198
Opened 2022-03-23 02:39 UTC by grumpy-sw

@jungseungyeo
안녕하세요 린생! STEP 3 PR 보내드립니다!

<프로젝트를 진행하면서 해결되지 않은 의문점 & 개선하고 싶은 점>

1. 입력한 연산자의 변경
연산자 입력 후 피연산자가 입력에 들어오기 전에 다른 연산자를 입력하면 해당 연산자로 바뀌어야 한다고 생각했습니다. 숫자 입력이 들어왔을 때 그제서야 연산자의 입력을 멈추고 수식(```FormulaNotYetCalculated```)에 연산자를 넣어주는 함수인 ```addOperatorToFormulaIfExists()```함수를 만들어서 피연산자와 연산자의 수식에 추가하는 시점을 다르게 만들어 해결했습니다.

2. Side Effect의 증가
다음 두 가지 경우를 대응하기 위해 상태 혹은 기존 값을 담고 있는 변수를 생성했습니다.
    - 0의 상태와 첫 입력으로 0이 들어온 경우를 구분하기 위해서: 0의 상태를 나타내는 Bool타입 변수 ```zeroStatus```
    - 계산 내역 생성 시 연산자와 피연산자를 조합하기 위해 이전의 연산자를 담고 있는 변수 ```formerOperator```

프로그램의 오류를 잡는 데는 성공했지만, 변수의 추가적인 사용으로 Side Effect가 증가한 점이 조금 아쉬운데요, 개선의 여지가 있다면 어떤 방법이 있을지 린생의 의견을 듣고 싶습니다.

3. 최하단으로 자동 스크롤
자동 스크롤을 하도록 Offset을 지정해줄 때 하나의 항목이 꼭 가려지는 현상이 있었습니다. 
y의 값에 30을 추가했더니 그 현상이 사라졌는데, 다른 해결 방법은 없는지 조언을 듣고 싶습니다.
```swift
HistoryScrollView.setContentOffset(CGPoint(x: 0, y: (HistoryScrollView.contentSize.height - HistoryScrollView.bounds.height + 30)), animated: true)
```

2022-03-23 13:35 UTC, jungseungyeo requested changes
그럼피 고생하셨어요. 

코드를 보면서 몇가지 수정을 하면 좋을거 같다는 생각을 했습니다.

### 1. public 사용

`기본적으로 public을 사용하고 있어요. 이렇게 사용하면 좋지 않아요. 외부에 노출을 일단 시키고 보자는 느낌이 들기 때문에 먼저 private을 사용하는 습관을 가지면 좋아요. private으로 변경하고 외부에 노출하야 하는 경우 어떤 방식으로 노출할지를 고민한 다음 public이나 internal로 노출을 해주세요.`

### 2. 네이미
`함수의 네이밍은 첫문자를 소문자로 하는 것이 원칙이예요. 이 원칙을 지켜주세요. 또 변수도 맞찬가지입니다.`

### 고민한 점

`Side Effect의 증가의 대해서 저의 의견을 주셨는데요. zeroStatus와 같은 플래그십으로 상태를 체크하는 방식은 좋지 않습니다. 차라리 enum의 상태 값을 주고 view의 상태를 체크하는 방식이 좋아요. 프래그십을 두게 되면 그 값이 맞는지 틀리는 지 따라 분기 문이 생기기 때문에 그렇습니다.`

### 3.최하단으로 자동 스크롤
`스크롤이 되어서 상단의 것이 가려진다고 하였는데요 이럴때는 글짜 크기를 줄이는 방식이 있긴하지만 주러 이런 방식은 사용하지 않습니다. 또 스크롤을 보여주어서 결과를 보여주는 방식이라 이건 문제가 없어 보여요 ㅎㅎ`

2022-03-23 13:35 UTC, jungseungyeo commented on Calculator/Calculator/CalculatorViewController.swift
> +        setUpHistoryStackView()
위의 순서대로 함수를 나열해주면 좋을거같아요. 
순차적으로 swift는 진행하지 않지만 사람은 위에서 아래로 코드를 읽기 때문에 가독성 측면에서는 순서를 지켜주면 코드 읽기가 좋아질거같아요.

2022-03-23 13:35 UTC, jungseungyeo commented on Calculator/Calculator/CalculatorViewController.swift
> +        OperandZeroButton.value = "0"
따로 버튼 객체를 만들어서 사용해야 했나요? 이렇게 하면 갭슐화를 위반하게 됩니다. uibutton에서 text를 가져오는 방식이랑 무엇이 다른지 모르겠네요

2022-03-23 13:35 UTC, jungseungyeo commented on Calculator/Calculator/CalculatorViewController.swift
> +    public func generateOperandNumber(_ sender: OperandButton) {
public이 이유가 있나요? private으로 바꿔주세요 다른 함수도 동일해요 함수와 변수, 상수를 만들때 접근 제어자는 무조건 private으로 해주세요

2022-03-23 13:35 UTC, jungseungyeo commented on Calculator/Calculator/CalculatorViewController.swift
> +    @IBAction public func OperatorButtonAction(_ sender: OperatorButton) {
함수명을 소문자로 해주세요

2022-03-23 13:35 UTC, jungseungyeo commented on Calculator/Calculator/CalculatorViewController.swift
> +        if formulaNotYetCalculated.isEmpty {
조건의 맞을떄 return이면 guard문과 어떤 기준으로 다르게 사용하시나요?

2022-03-24 13:39 UTC, grumpy-sw commented on Calculator/Calculator/CalculatorViewController.swift
> +    @IBOutlet private weak var OperandZeroButton: OperandButton!
넵 변경했습니다!

2022-03-24 13:39 UTC, grumpy-sw commented on Calculator/Calculator/CalculatorViewController.swift
> +        OperandZeroButton.value = "0"
먼저 UIButton에서 text를 가져오는 방식이 적합하지 않다고 느낀 이유는
1) View의 Text는 언제든지 바뀔 여지가 있다.

2) View는 무언가를 표시하는 역할을 할 뿐, 어떠한 데이터를 갖고 있지 않는 것이 좋다.

라고 생각했기 때문입니다.

- View의 Text는 언제든지 바뀔 여지가 있다.

    만약 UIButton의 Text를 가져오는 방식을 채택했다면, Text가 변경되었을 때 컨트롤러에서 쓰이는 값 자체가 변경될 수가 있겠죠. 예를 들면 우리가 사용하는 숫자 표기법이 아닌 다른 숫자 표기법으로 숫자들을 바꾼다면 뷰 컨트롤러를 통해 계산기에 전달되는 값이 달라지게 될 것입니다.

- View는 무언가를 표시하는 역할을 할 뿐, 어떠한 데이터를 갖고 있지 않는 것이 좋다.

    말 그대로 View의 역할을 한정하고 싶었습니다. View의 어떠한 텍스트를 프로그램 내부에서 이를 사용한다면, 텍스트는 단순히 버튼의 title이 아니라 프로그램을 제대로 돌아가기 위한 데이터를 표시하는 매개체가 된다고 생각합니다. 이런 이유 때문에 모델이나 컨트롤러의 다른 구성요소 혹은 별도의 정보를 갖고 있지 않아야 한다는 뷰의 규칙을 위반하는 방법이라고 생각했습니다.

지난 프로젝트 때 비슷한 기능들을 switch문을 통해 각 버튼에 맞는 value를 반환해주는 converting용 함수를 만들어서 진행했다가 커스텀 클래스를 만드는 방법으로 하는 것을 추천받아서 진행했는데요, 그때는 캡슐화와 관련된 내용을 전혀 알지 못했었습니다.. 혹시 캡슐화의 위반과 올바른 개선 방향에 대해 답변을 들을 수 있을까요? 😂

2022-03-24 13:39 UTC, grumpy-sw commented on Calculator/Calculator/CalculatorViewController.swift
> +    public func generateOperandNumber(_ sender: OperandButton) {
변경했습니다!

2022-03-24 13:39 UTC, grumpy-sw commented on Calculator/Calculator/CalculatorViewController.swift
> +    @IBAction public func OperatorButtonAction(_ sender: OperatorButton) {
변경했습니다!

2022-03-24 13:39 UTC, grumpy-sw commented on Calculator/Calculator/CalculatorViewController.swift
> +        if formulaNotYetCalculated.isEmpty {
제 나름대로의 기준을 말씀드리자면....
1) 조건에 따른 분기를 여러 번 사용해야 한다면 ```if ~ else ~```
2) 조건이 '~일 때' 라고 읽혀지면 ```if```
3) 조건이 '~가 아닐 때' 또는 조건을 체크하고 Early Exit가 필요할 때 ```guard```

라고 사용하고 있었습니다. 

관련한 내용을 더 찾아보니 Early Exit에 해당되는 경우 guard문을 사용하는 것이 가독성 면에서 더 좋은 코드라고 하네요 😄 이 부분을 제가 놓치고 지나간 것 같습니다.

2022-03-24 17:28 UTC, grumpy-sw commented
@jungseungyeo 
안녕하세요 린생!

남겨주신 코멘트에 대한 답변 및 궁금한 점을 댓글로 달아 보았습니다!
더불어 프로젝트를 진행하면서 추가로 궁금해진 포인트 그리고 해결하지 못한 문제점 등 피드백 받고싶은 내용 아래에 적어봅니다.

<추가적인 궁금점❓>

1. '숫자는 최대 20자리까지만 표시합니다.'

![스크린샷 2022-03-24 오후 10 54 45](https://user-images.githubusercontent.com/63997044/159931620-ed4ec883-6b75-4c7e-913f-70a3da3184d3.png)

저는 이 부분을 소수점 아래 자리수가 최대 20자리라는 뜻으로 이해했는데요, 입력을 받을 때 자릿수에 대한 제약을 따로 걸어두지 않다 보니 사진과 같이 입력이 계속해서 받아지는 문제가 있었습니다. 이 부분은 소수점 아래 자리수가 아닌 전체 숫자 표시가 20자리까지로 인식하고 입력이 20자리가 넘어가면 오류를 던져 초기 상태로 되돌리도록 수정했습니다.

<해결하지 못한 부분>
계산 결과가 소수점이 없이 20자리를 넘어가는 경우, 20자리까지 표현하고자 20자리 미만의 자리는 반올림하도록 처리해야 하는데, 제가 생각했던 방법은 다음과 같습니다.
    1. 계산 결과를 20자리까지 잘라낸 결과를 변수에 저장한다.
    2. 계산 결과의 21번째 숫자를 확인한다.
    3. 2의 결과가 5보다 작으면 그대로 1의 결과를 출력한다. 5 이상이면 1의 결과에 1을 더한다.
    4. 자리수가 20자리가 될 때까지 1~3의 내용을 반복한다.
그런데 제 생각에는 '차라리 20자리 아래의 숫자는 버리는 게 낫지 않나?' 라는 생각이 들었습니다. 반올림을 하는 과정에서 오히려 원래 결과와 값이 크게 달라지는 경우도 있을 것 같고요. 소수점 이하 숫자들에 대해서만 반올림을 하는 것인지 궁금합니다.

___

2. 실제로 표시되는 자리수는?
 
![스크린샷 2022-03-24 오후 11 17 09](https://user-images.githubusercontent.com/63997044/159936157-f503c251-83dd-41d3-8b8d-e5e560430387.png)

Swift에서 Double() 자료형은 소수점을 최대 17자리까지 지원하기 때문에 그 아래의 정밀한 표현은 할 수 없다고 합니다.([링크](https://stackoverflow.com/questions/60798004/large-decimal-number-formatting-using-numberformatter-in-swift)) 왜인지는 모르겠으나 항상 17자리가 아닌 16자리 혹은 17자리까지만 출력되더라구요. 이 경우엔 NumberFormatter가 아닌 ```String(format: "%.\(String(20 - integerLength))f", result)``` 로 처리했습니다. 이렇게 하니 2 ÷ 3의 경우 0.666666666... 이 아닌 0.6666666666666666297 과 같이 자릿수는 맞지만 정확한 결과값을 표현하지 못하는 현상이 생겼는데요, 이것은 Double타입 연산의 한계라고 생각합니다만 혹시 요구사항에 위반되는 오류일까요?

___

3. 0의 상태
 > enum의 상태 값을 주고 view의 상태를 체크하는 방식이 좋아요.
라고 힌트를 주셨는데, 어떤 방식인지 잘 모르겠습니다.. 별도로 체크하는 개념 자체는 동일하다면 왜 변수가 아니라 enum이어야 하지...? 라는 생각이 계속 드네요.. 아직 많이 어려운 것 같습니다 ㅠㅠ 이 내용에 대한 린생의 추가적인 조언 부탁드립니다 🙏

___

4. 버튼 객체의 생성
이 부분은 위의 코멘트에 작성해놓았습니다!

2022-03-25 10:25 UTC, jungseungyeo commented on Calculator/Calculator/CalculatorViewController.swift
> +        OperandZeroButton.value = "0"
저의 의견은 1, 2번 의견의 동의하나 custom을 쓴다고 그게 해결 된 부분이 없어서 그런거같아요. 내부적으로 value를 가지고 있는것과 titlelabel.text를 가져오는 행동이 같다고 판단이 되었습니다. 

그래서 커스텀이 필요없다는 생각이 들었습니다. 또 값을 넣어주는 방식이 캡슐화를 위반하고 있어서 custom 방식을 권장하지 않았습니다. 
value = "1" <- 이렇게 넣어주는 형태가 데이터 은닉화를 위반하고 있고, 이것이 캡슐화를 위반하고 있어서 가능하다면 기본 button을 사용하는 것이 바람직하다고 판단이 되었습니다.

2022-03-25 10:26 UTC, jungseungyeo commented on Calculator/Calculator/CalculatorViewController.swift
> +        if formulaNotYetCalculated.isEmpty {
기준을 잘 잡은거 같아요. 이 부분을 말한 이유는 if문에서 걸리면 밑의 함수를 진행을 막는다면 제어문의 특확 된 guard를 사용하는게 좋을거같다는 판단이 들어서 그랬습니다. :)

2022-03-25 10:39 UTC, jungseungyeo commented
그럼피 고생하셨어요. 2주동안 계산기 프로젝트를 하느라 수고하셨고 질문의 대해서 답변을 드리겠습니다.

### 1. '숫자는 최대 20자리까지만 표시합니다.'

`수정을 잘 하신거 같아요. 질문의 의도가 반올림이 좋은지 아니면 올림이 좋은지 질문을 주신거 같아요. 저는 어느쪽이든 크게 문제는 없을거같아요. 이부분의 대해서는 기획에서도 없어고 구현하는 방식에서 야곰, 혹은 저에게 문의를 하고 맞추면 되는 부분입니다. 기획이라는 것은 항상 완벽할 수 없어 부족한 부분은 협의 하는 과정에서 완성이 되는 것이라고 이해하시면 될 거같아요. 좋은 질문이 였습니다. 앞으로 이런 문제가 많이 보일겁니다. 그 때는 완벽한 기획이 있다는 생각보다는 부족한 기획을 자신이 채워간다는 생각으로 진행 하면 좋을거같아요.`

### 2.실제로 표시되는 자리수는?

`이건 Double의 메모리 한계라 어쩔수 없는 형태입니다. 따라서 요구사항에 위반이라기 보다는 개발적인 한계라고 말하면 좋을거같아요. 1번의 질문 처럼 이 것또한 기획에서 놓치거나 완벽하지 않는 내용을 채워 주신거라고 생각하면 좋을거 같아요!`

### 3. 0의 상태

`상태를 잘 두었습니다. flag를 두는 것은 정말 안좋은 습관이예요. 개발자분들이 처음 할 때 실수하는 포인트입니다. 이것을 꼭 상태 값으로 해결하는 것은 아니지만 상태값을 두어 해결하는 방법이 일반적인거 같아요. 너무 잘 하셨습니다.`

### 4. 버튼 객체의 생성

`이 부분은 코멘트 저도 달긴 하였는데요. 커스텀을 만들어서 기존의 UIButton을 쓰고 있는 문제가 해결되지 않고 있어서 커스텀을 권장하지 않았습니다. titleLabel.text를 접근하여 사용하는 것과 value를 접근하여 사용하는 것이 크게 다르지않고, value를 접근하는 방식이 데이터의 은닉화를 위반하고 있습니다. 또 value가 없이도 uiButton으로만 해결이 가능하여 custom을 사용하는 이유를 알 수가 없다고 판단이 되었습니다. ㅠㅠ Custom을 사용하면 기존의 문제가 해결되어서 사용하는 방향으로 사용하는 것이 좋다고 생각이 들어서 의견을 드렸습니다.`


그럼피 너무 고생하셨어요. 이번 2주가 벌써 시간이 지나갔네요. 혹시 step이 끝났지만 궁금한점이 있으면 언제든지 말해주세요 :) 고생하셨습니다.

2022-03-25 10:39 UTC, jungseungyeo approved these changes

2022-03-25 10:39 UTC, merged

2022-03-25 10:47 UTC, grumpy-sw commented on Calculator/Calculator/CalculatorViewController.swift
> +        OperandZeroButton.value = "0"
아하 이해되었습니다 감사합니다! 👍