[Step1] Sookim, James, Bobby
yagom-academy/ios-calculator-app pull request #20
Opened 2021-03-27 09:47 UTC by Babywalnut

## [STEP 1] 계산기 :abacus:
@seizze
안녕하세요!  하이디!

### 고민되었던 점, 해결되지 않은 점, 궁금한 점 :interrobang:

- NAND와 NOR 연산자는 스위프트가 제공하는 연산자에 없어서 사용자 정의를 하여 구현하였는데precedence group을 지정하는 거에 대해서 고민하다가 AND와 NAND , OR와 NOR을 같은 precedence group으로 지정하였는데 적절한 방식일까요?
- 이번 프로젝트에서 제네릭과 리스트를 활용하면 좋다는 이야기가 있는데 적절히 사용하고 있는 건가요?
- 2진계산기 클래스와 10진계산기 클래스의 구조가 굉장히 흡사합니다. 이럴경우 프로토콜을 채택하는 것과 상속을 하는것 중 무엇을 선택해야할까요?
- 보수는 어떤방향으로 구현을 해야할지 잘모르겠습니다😭 피드백 부탁드려요🙏 
- 코드설계를 할 때 단순히 로직에 초점을 맞춰 코드를 작성을 해야할지 앱에서 실행이 될 것을 감안하고 작성해야할지 궁금해요

**아직 저희의 로직에 부족한점이 많은데요. 어떻게 수정해야할지 더 좋은 방향성을 제시해주시면 많은 도움이 될 것 같아요🙈**

2021-03-28 13:45 UTC, seizze requested changes
와 이번미션 난이도가 꽤 높아졌네요! 수고 많으셨습니다.

### 전체적인 의견

구현한 기능도 간략하게 몇 줄로 요약해 주면 이해가 빠를거 같아요. 여러분들이 나중에 기억을 떠올리기에도 좋구요~
예를 들면...
- 중위표기법을 후위표기법으로 변환하는 기능 구현
- 10진계산기 기능 중 +, -, 초기화 기능 구현

이런식으로요~ 리드미에 작성해 주셔도 좋고, PR 코멘트에 작성해 주셔도 좋습니다. ☺️

두 번째로, 로직만 만들어 두니 어떻게 사용하는지 이해하기에 조금 어려움이 있네요 ㅠㅠ 이런 로직을 구현하는 종류의 PR을 날릴 땐 코멘트나, run 했을 때 바로 동작하는 곳(`viewDidLoad`라던지..)에 이 계산기들을 사용하는 쪽에서 예시로 어떻게 사용하는지 간략하게 몇줄 코드를 작성해 주면 좋습니다. 저도 회사에서 공통 유틸리티를 구현한 후에, 어떻게 사용하는지 팀원분들이 최대한 한눈에 알기 쉽게 작성해서 코멘트나 위키에 추가하니까 더 전달이 빠르더라고요~

### 질문주신 사항에 대한 의견

아래엔 코멘트에 남겨주신 사항들에 대해 의견 남겼습니다.

> NAND와 NOR 연산자는 스위프트가 제공하는 연산자에 없어서 사용자 정의를 하여 구현하였는데precedence group을 지정하는 거에 대해서 고민하다가 AND와 NAND , OR와 NOR을 같은 precedence group으로 지정하였는데 적절한 방식일까요?

이 부분은 해당 코드에 코멘트 남겼습니다. ㅎㅎ

> 이번 프로젝트에서 제네릭과 리스트를 활용하면 좋다는 이야기가 있는데 적절히 사용하고 있는 건가요?

스택에서 제네릭과 리스트를 적용하신 부분 말씀하신거라면 기능 요구사항에 맞게 적절히 활용된거 같아요 ^^ 💯

> 2진계산기 클래스와 10진계산기 클래스의 구조가 굉장히 흡사합니다. 이럴경우 프로토콜을 채택하는 것과 상속을 하는것 중 무엇을 선택해야할까요?

구조 관련해서는 맨 아래에 총정리해서 의견 남겼으니 확인부탁드려요. ㅎㅎ

> 보수는 어떤방향으로 구현을 해야할지 잘모르겠습니다😭 피드백 부탁드려요🙏

보수가 왜 필요한지 좀더 설명해주실 수 있나용?.. 제가 공유받은 요구사항 문서엔 그 기능이 없는 것 같아요..

> 코드설계를 할 때 단순히 로직에 초점을 맞춰 코드를 작성을 해야할지 앱에서 실행이 될 것을 감안하고 작성해야할지 궁금해요

앱에서 실행이라는게 성능 측면 말씀하시는건가요? 아니면 API 설계 시 해당 API를 사용하는 쪽을 감안해야 하냐는 질문인가요? ㅎㅎ 전자든 후자든간에 항상 모든 경우를 고려해야 한다고 생각합니다. 요걸 질문하신게 맞는지 잘 모르겠네용.. 추가 질문이나 DM 편하게 주세요 🙏

2021-03-28 13:45 UTC, seizze commented on Calculator/Calculator/CustomPrecedenceGroup.swift
> +}
전역 함수로 구현하셨네요! 이 기능은 10진 계산기와 2진 계산기 모두에 해당하는 기능일까요? 이진 값을 나타내는 Binary 타입을 만들고 그 안에서 static 메서드로 선언해 보면 어떨까요? 2진 계산기에서 활용될 수 있게 필요에 따라 다른 프로토콜도 추가 구현해 볼 수 있을 것 같네요~

2021-03-28 13:45 UTC, seizze commented on Calculator/Calculator/Binary.swift
> +    typealias precedence = Int
typealias도 하나의 타입처럼 쓸 수 있으니까 보통 대문자로 적습니다. 🤓

2021-03-28 13:45 UTC, seizze commented on Calculator/Calculator/Binary.swift
> +        [">>" : 4, "<<" : 4 ,"&" : 3, "~&" : 3, "|" : 2, "~|" : 2, "^" : 2, "+" : 2, "-" : 2, "~" : 1]
연산자 타입을 선언하고, Comparable 프로토콜을 구현해서 우선순위를 더 단순하게 비교할 수 있도록 개선해 보면 어떨까요? 이렇게 구체적인 정보들은 하위 타입에서 갖고 있으면서 상위 타입이 명령했을 때 이를 이용해 적절하게 동작하도록 만드는 편이 더 객체지향적이라고 할 수 있습니다.

2021-03-28 13:45 UTC, seizze commented on Calculator/Calculator/Protocol.swift
> +protocol CalculationProtocol {
프로토콜이라고 타입에 프로토콜을 적어야 하는건 아닙니다.
Calculable, Ridable 처럼 "~할 수 있는"의 형식으로 많이 적습니다.
이렇게 하면 타입을 정의하는 쪽에선 다음과 같이 읽혀질 수 있습니다. 🚗 
```swift
class Car: Ridable {} // 자동차는 탈 수 있다
```

2021-03-28 13:51 UTC, seizze commented on Calculator/Calculator/Stack.swift
> +    var head: Node<T>?
요런 피드백을 드릴 땐 전체적으로 private이 잘 적용되어 있는지 한번 쭉 훑어보면 좋습니다. 😎

2021-03-28 14:19 UTC, seizze commented on README.md
> +### 설계
### 구조 관련 피드백
> 일부러 스레드가 생성되도록 코드에 코멘트를 달았습니다.

현재 말씀하신 것처럼 2진 계산기와 10진 계산기의 내용이 많이 중복되네요.

두 계산기에서 모두 구현하고 있는 중위 연산자를 후위 연산자로 변환하는 기능은 어느 계산기의 역할일까요? 10진 계산기와 2진 계산기의 세부적인 역할이기 보다는 일반적인 계산기의 역할이지 않을까요?

저는 지금 구현한 기능들 중, 일반적인 계산기가 해야하는 일들을 분리해 내서 계산기 타입을 만들어 개선하면 좋을 것 같다는 생각입니다. 그리고 10진/2진에서 공통된 기능을 프로토콜로 추상화하고, 일반적인 계산기 타입에서는 구체적인 타입을 모른 채 이 프로토콜에만 의존한 상태에서 적절한 메서드로 명령을 내리도록 만들면 좋을 것 같네요~ 이렇게 상위 타입은 시키기만 하고 하위 타입이 알아서 동작하도록 만드는게 더 객체지향적인 방법입니다. 이렇게 할 때 코드의 재사용성이 좋아지고, 테스트도 가능해집니다.

예를 들어, 중위표기법을 후위표기법으로 변환하는 기능의 경우, 연산자 우선순위는 구체 타입인 2진 계산기와 10진 계산기 각각이 들고 있고, 상위 타입에서는 이를 받아서 적절히 처리하는 방향이 좋습니다. 두 클래스의 구조가 굉장히 흡사한 부분도, 말씀드린 방법을 적용하면 자연스레 해결될 수 있어 보이네요.

10진 계산기와 2진 계산기가 개별적으로 다른 계산기라고 생각하지 말고, 계산기가 사용하는 하나의 모듈이라고 생각해 보세요. 지금 상태라면 다다음 스텝에서 UI와 연결할 때 많은 곳에서 모드에 따른 분기처리가 발생하게 될 것으로 예상됩니다.

세부적으로 개선될 부분도 더 보이는데 일단은 구조적인 부분을 개선해 보면 좋을 것 같아요. ☺️

2021-03-28 14:36 UTC, seizze commented
수정이 완료됐다면 완료됐다는 코멘트 남겨서 제게 알려주세요 😉

2021-03-30 11:35 UTC, inwoodev commented
## [STEP 1] 계산기 :abacus: - 2
@seizze 
안녕하세요! 하이디~ bobby,sookim,james와 피드백을 반영해서 수정해보았어요.

먼저 시간 내주셔서  코드 리뷰 해 주셔서 감사해요. 세세한 피드백이 많은 도움이 되었습니다:)
그리고 사용법을 남겨놓는다는 것이 깜빡했네요 ㅠㅜ 죄송합니다.
`viewDidLoad`에 간단하게 사용 예시 적어 놓았습니다. 확인 부탁드릴게요.

### 1차 피드백 반영하여 수정한 내용:
- 구조를 InputDataValidation에서 입력값이 유효한지 각각의 경우를 확인한 후  GeneralCalculator에서 계산기들의 공통점인 후위표기법으로 변환을 해주고 각각 10진,2진계산기 경우 DecimalCalculator와 BinaryCalculator에서 연산자에 맞는 연산을 실행해주도록 구조를 설계해봤어요! 이렇게 설계함으로써 General calculator라는 하나의 계산기 속에 2진계산 그리고 10진계산기능을  모듈로써 활용하였습니다. 이렇게 설계하니 중복되는 코드 또한 최대한 많이 줄일 수 있었어요.

- 연산자 배열을 10진수,2진수 계산기에서 동시에 사용하고 있기때문에 enum으로 모든 연산자를 정의했어요. 메서드 내에 인스턴스를 생성하지 않고 연산자와 피연산자를 구별하기 위해 enum안에 static을 사용했는데 이렇게 사용하면 단점이 있을까요? :thinking:
(enum에서 rawValue 값을 가져오기 위해 map을 사용해서 배열을 리턴했어요)

-  계산 데이터를 저장하는 싱글턴을 제거하고 class의 static variable을 이용하였습니다.
계산해야 하는 데이터를 싱글턴으로 사용하여 여러 class간 이동하며 사용하였더니 알수 없는 오류가 발생하였어요. 그래서 계산 데이터를 담은 Data 클래스를 생성한 뒤 해당 클래스의 static variable을 통해 데이터를 저장하도록 변경하였습니다.

- 프로토콜 수정
2진계산기와 10진계산기가 공유하는 프로토콜을 생성하였습니다.

- 줄넘김 수정
- 접근제어 설정

### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ❗️:question:

- Data class를 만든뒤 입력받은 배열과 후위표기법으로 변환한 배열을 GeneralCalculator와 DecimalCalculation에서 같이 사용해야되서 따로 class를 만든 부분이 구조적으로 어떤 지 궁금합니다.

- Custom Precedence group을 static 메서드로 변경하는 것
지역 메서드 또는 타입 내부의 static 메서드로 변경하려 하였으나 전역함수로 밖에 사용할 수 없는 것 같습니다. 다른 방법을 알려주시면 정말 감사하겠습니다 ㅠㅠ

- 2진계산기에서 +, - 연산을 하다 나온 언더플로값 그리고 오버플로값을 **오버플로 연산자**와 **언더플로 연산자**를 활용하여 값을 도출하였습니다. 이렇게 처리해도 괜찮은지 궁금해요.

- NOT(~)연산자가 입력되었을 때 연산자를 전위연산자로 정했어요. 그리고 연산자 다음 연산자가 나오는 경우 계산을 어떤식으로 할지 궁금합니다...

- 계산기를 확인해 보니까 9자리까지 계산기가 작동하는 것 같은데 UInt9는 없는 것 같습니다. 일단 UInt8로 계산을 하였는데 9자리 수를 어떤식으로 구현해야 할지 궁금해요.

2021-03-31 13:53 UTC, seizze approved these changes
수고 많으셨습니다. 전보다 개선된 점이 많이 보이네요! ☺️
추가적으로 테스트에 관련된 의견을 드렸으니 다음 단계 진행하면서 개선해 보면 좋을 것 같아요~

> Data class를 만든뒤 입력받은 배열과 후위표기법으로 변환한 배열을 GeneralCalculator와 DecimalCalculation에서 같이 사용해야되서 따로 class를 만든 부분이 구조적으로 어떤 지 궁금합니다.

해당 코드 부분(Data)에 코멘트 남겼습니다.

> Custom Precedence group을 static 메서드로 변경하는 것 지역 메서드 또는 타입 내부의 static 메서드로 변경하려 하였으나 전역함수로 밖에 사용할 수 없는 것 같습니다. 다른 방법을 알려주시면 정말 감사하겠습니다 ㅠㅠ

이것도 해당 부분에 남겼습니다!

> 2진계산기에서 +, - 연산을 하다 나온 언더플로값 그리고 오버플로값을 오버플로 연산자와 언더플로 연산자를 활용하여 값을 도출하였습니다. 이렇게 처리해도 괜찮은지 궁금해요.

mac 계산기로 해보니 언더플로우 된 채로 나오네요~ 스펙엔 맞는거 같아요 ㅎㅎ

> NOT(~)연산자가 입력되었을 때 연산자를 전위연산자로 정했어요. 그리고 연산자 다음 연산자가 나오는 경우 계산을 어떤식으로 할지 궁금합니다...

이미 연산자가 입력된 상태에서 또 연산자를 입력했을때 어떻게 구현할지는 기획 의도에 따라 달라지겠지만, 현재 계산기는 먼저 입력된 연산자를 지우고 새 연산자를 입력하고 있네요! 검증하는 기능에서 예외처리가 필요한 부분일 것 같아요.

> 계산기를 확인해 보니까 9자리까지 계산기가 작동하는 것 같은데 UInt9는 없는 것 같습니다. 일단 UInt8로 계산을 하였는데 9자리 수를 어떤식으로 구현해야 할지 궁금해요.

가장 간단한 방법은 오버플로/언더플로가 발생하는지 체크해서 그에 따른 값을 앞자리에 붙여줄 수도 있겠네요~ 정답은 없습니다~

2021-03-31 13:53 UTC, merged