계산기 Step3 우롱차
yagom-academy/ios-calculator-app pull request #200
Opened 2022-03-23 18:08 UTC by dnwhd0112

@jungseungyeo
안녕하세요 린생
이번 PR도 잘 부탁드려요!

---
## 궁금한 점
계산할때 double 타입으로 변환하는 바람에 숫자 길이에 제약이 생긴다. 이를 해결할 방안이 있을가?
stackView로 스크롤에 추가할때마다 스크롤뷰 아래쪽에 항목이 생기는대 스크롤 뷰도 같이 움직이고 싶은대 어떻게 해야할까?

## 고민한점
기존 주스메이커에서 tag를 이용한 방법을 써서 변환해주는 방법을 사용했었는대
이번에는 UIButton을 상속받은 class 를 만들어서 값을 할당하는 방식을 사용하였는대 괜찮은 방법인지?
코드가 중간중간 길어지는 부분이 있는대 이를 해결하기 위해 좀 더 함수로 묶는 방향이 좋았을까?

2022-03-24 02:05 UTC, jungseungyeo requested changes
안녕하세요 우롱차 고생하셨어요!

### 궁금한 점

`숫자 길이에 제약이 생긴다 <- 이 말이 메모리가 넘게 입력 받는 경우를 말하는 거 같아요. 이런 경우 부동 소수점 계산 방법이 있어요. 이런 방법으로 사용하는 것도 있습니다. `

### stackView로 스크롤

`스크롤뷰를 사용할떄 자동 스크롤을 말하는거 같아요. 이 건 방법이 있어요. scrollView의 setContentOffset 이런 함수가 존재합니다. 이 값은 특정 위치로 스크롤뷰를 이동시키는 함수 입니다. 이 함수를 사용하면 좋을거같아요.`

우롱차 고생하셨어요. 몇가지 의견을 남겨드립니다.

### 1. 플래그 값으로 상태 값 측정

`처음 상태를 측정 할 때 일반 적으로 생각하는 방법입니다. 하지만 이런 방식은 좋지 않아요. 코드를 쓰면서 알아차리셨겠지만, 자꾸 if 값으로 분기문이 생기는 것을 알 수 있어요. 이렇게 값을 쓰게 되면 복잡도가 높아지는 효과가 생기고 그 값의 어디서 변화는지 등의 체크가 필요해요. flag로 처리하지 말고 다른 형태로 해결하면 좋을거같아요.`

### 2. UIButton을 사용

`아마 새로운 역할을 하는 뷰를 생성하여 만들고 싶은 느낌을 많았을거같아요. 하지만 기본 스타일을 쓸수있다면 가능한 사용을 해주세요. 또 새로 만든 두 button이 서로 다른 것이 없기때문에 오히려 더 관리해야 하는 객체가 많아져 안좋아진거같아요. 이부분의 대해서 수정을 해주시면 좋을거같아요.`

코멘트 확인해주시고 수정해주세요. 혹시 궁금한점 있으면 언제든지 알려주세요 :)

2022-03-24 07:58 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +        if currentDisplayNumber.isEmpty && totalCalculate.isEmpty {
동의 합니다!

2022-03-24 07:58 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +    var currentDisplayNumber: String = ""
넵! 까먹었네요

2022-03-24 07:58 UTC, dnwhd0112 commented on Calculator/Modal/OperandButton.swift
> +    var value: String?
다시 생각해보니까 그러네요. 좀 더 좋은 방향으로 수정해보겠습니다.

2022-03-24 07:58 UTC, dnwhd0112 commented on Calculator/Modal/NumberButton.swift
> +class NumberButton: UIButton {
좀 더 좋은 방향으로 수정해보겠습니다.

2022-03-24 07:59 UTC, dnwhd0112 commented on Calculator/Modal/CalculatorItemQueue.swift
> +        if queue.isEmpty {
사실 guard 문으로 쓸까 했는대 guard 조건을 설정하는게 if 문보다 까다로워서 편한 방향으로 선언하다 보니 이렇게 쓴거 같아요.

2022-03-24 08:00 UTC, dnwhd0112 commented on Calculator/Modal/CalculatorItemQueue.swift
> +        if queue.isEmpty {
종료가 필요한 부분 -> guard를 쓰는게 좋은거 같습니다.

2022-03-24 08:00 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +        divideButton.value = "÷"
생각해보니 그러네요! 더 나은방향으로 수정해보겠습니다.

2022-03-24 08:00 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +    func initalizeButtonValue() {
넵

2022-03-24 08:01 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +    func addStackView() {
네... 느끼고 있었어요 좀 더 고민해볼게요

2022-03-24 08:01 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +    var negativeStatus = false
잘 이해가 가지 않아요... 나중에 따로 물어보겠습니다.

2022-03-24 08:02 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +        if negativeStatus == false {
네 좀 고민해보겠습니다.

2022-03-25 11:28 UTC, merged

2022-03-25 13:20 UTC, dnwhd0112 commented on Calculator/Calculator/CalculatorViewController.swift
> +    enum NegativeStatus {
앗 enum도 private가 가능하군요 ㅎㅎㅎ 알갰습니다