계산기 I [Step3] Tiana
yagom-academy/ios-calculator-app pull request #203
Opened 2022-03-24 04:49 UTC by Kim-TaeHyun-A

안녕하세요 개굴 @yoo-kie 
step3 PR 보냅니다. 마지막까지 잘 부탁드립니다😁

---
### 구현한 내용

CalculatorViewController: UIViewController

- calculatorInput 프로퍼티 : 누적으로 입력된 숫자와 연산자 문자열을 저장
- hasFirstInput 프로퍼티 : 스크롤 뷰 내부의 content인 스택에 값을 넣은 적이 있는지 확인. 제일 앞에 연산자가 오지 않기 때문에 구분 필요.
- 아울렛 변수
    - scrollView : 스크롤 뷰 제일 하단에 추가되는 스택이 고정적으로 출력되게 할 때 사용됨
    - inputStackView : 입력된 숫자와 연산자가 한 줄씩(각각 하나의 스택 구성하여) 들어가는 스택뷰
    - operatorLabel : 입력된 연산자를 보임
    - numberLabel : 현재 입력 중인 숫자 보임
    - acButton : 전체 입력 스택(inputStackView)을 비움
    - ceButton : 현재 입력 중인 숫자(numberLabel.text)를 제거
    - prefixButton : 현재 입력 중인 숫자의 제일 앞에서 -/+를 반전시킴
    - 연산자 버튼들(+, -, /, *, = )
    - dotButton
    - zeroButton : 0
    - doubleZeroButton : 00
    - 숫자 버튼(1~9)
 
- **@IBAction** **func** touchUpNumberButton(_ sender: UIButton)
    
    : 모든 숫자 버튼이 연결된 액션 메서드
    
    : 입력된 버튼을 확인하고 옳은 입력인지 확인(ex. 00이 눌렸는지, “.”이 한 번 이상 눌렸는지 확인)
    
    : 첫 숫자가 아닌 경우는 0이나 00을 눌러도 0이 입력될 수 있도록 처리
    
    : 현재 숫자 레이블에 입력될 첫 숫자이면서 .이 아닌 경우는 현재 입력값으로 숫자 레이블을 대체하고
    
    그렇지 않다면 기존 값에 연결되어야 하기에 append 시킴
    
- **@IBAction** **func** touchUpOperatorButton(_ sender: UIButton)
    
    : 모든 연산자 버튼과 연결된 액션 메서드
    
    : 현재 숫자 레이블의 값이 0이고 이제껏 입력된 숫자가 없으면 무시
    
    : 연산자가 눌리면 inputStackView에 스택을 추가
    
    : 연산자가 = 이면 calculatorInput을 파싱하여 계산
    
    : 계산된 결과가 20자리 이상이면 에러 처리
    
    : 소수점은 10자리까지
    
    : 숫자는 3자리씩 끊어서 , 로 구분
    
    : 결과를 숫자 레이블에 출력하고 연산자 레이블은 값을 없앰
    
    : 결과가 에러면 NaN 출력
    
    : 계산기에서 입력된 숫자가 있는 경우에만 연산자가 연산자 레이블에 표시되고 현재 입력 중이던 숫자가 0으로 갱신 되도록
    
- **@IBAction** **func** touchUpFunctionButton(_ sender: UIButton)
    
    : AC, CE, prefix(-/+)를 구분하여 적절한 기능 수행
    
- viewDidLoad() : 숫자 레이블과 연산자 레이블 초기화
- addStack()
    
    : 수평으로 쌓이는 스택에 연산자와 숫자를 넣고 해당 스택을 inputStackView에 추가
    
    : 첫 스택인 경우는 operator가 없지만 이후는 있으므로 구분
    
    : calculatorInput 에 스택에 들어간 내용 추가
    
    : 스크롤 뷰에서 새로운 값이 제일 하단에 고정되어 위치하도록
    
- removeStack()
    
    : inputStack의 서브뷰를 순회하면 제거
    
    : 초기화 진행
    
- findNumber(of button: UIButton) **throws** -> String
- findOperator(of button: UIButton) **throws** -> String
- findFunction(of button: UIButton) **throws**
- configurePrefix()
- isValidNumber(input: String, currentNumber: String?) -> Bool : 0과 . 에 관하여 유효한 입력인지 확인

 
---

### 고민한 점

1. numberLabel.text 값 갱신
    
    가독성을 위해 nubmerLabel.text를 변수에 담아서 사용하고 값을 갱신하려고 했지만 해당 값이 String이어서 의도대로 수정되지 않았습니다. 따라서, 값을 수정할 때는 원래 프로퍼티에 직접 접근하여 값을 갱신합니다.
    
2. 스토리보드의 stackView 이용
    
    이번 프로젝트에서는 동적으로 스택뷰가 스크롤뷰에 추가됩니다. 이때, 기존에 스토리보드에 있던 스택뷰를 사용하면 새로운 값이 추가되는 것이 아니라 기존 값이 변경됩니다. 따라서, 스택이 추가될 때마다 새로운 스택뷰를 만들어서 추가하는 방식으로 구현했습니다.
    
3. 스크롤 뷰 제일 하단에 최신 값 오도록 구성
    
    스크롤 뷰의 `func setContentOffset(_ contentOffset: CGPoint, animated: Bool)`
    
    를 사용해서 CGPoint를 설정합니다.

    https://www.objc.io/issues/3-views/scroll-view/
    
<img width="770" alt="스크린샷 2022-03-24 오후 1 21 00" src="https://user-images.githubusercontent.com/70807352/159842748-df46773d-e4a8-4163-be2d-9f81b932ea10.png">

    
scrollView.bounds 높이가 추가되는 스택뷰의 높이인 것 같습니다. y좌표를 컨텐츠 높이에서 스택뷰의 높이를 뺀 값으로 설정해서 스크롤 뷰의 제일 하단에 위치되는 것으로 생각됩니다.🤔
    
4. NumberFormatter 이용해서 숫자 표현하기
    
    <img width="575" alt="스크린샷 2022-03-24 오후 12 04 47" src="https://user-images.githubusercontent.com/70807352/159842783-151e47c1-e9c9-44c8-ba88-ea493bb73185.png">

<img width="518" alt="스크린샷 2022-03-24 오후 12 07 19" src="https://user-images.githubusercontent.com/70807352/159842813-2d0cdcd2-0c43-40f1-a2ee-a117604b244b.png">

    
반올림이 어떻게 되는지, 소수점이 어디까지 표현되는지를 디버깅을 통해 확인해서 원하는 결과를 얻을 수 있도록 구현했습니다.
    
5. 20자리를 최대 수로 설정하기
    
    String(format:) 을 사용해서 20자리의 숫자를 얻어내고 이후 NumberFormatter를 적용시키 원하는 형태의 숫자로 만들고 싶었지만 두 개를 동시에 적용시키는 것에 실패했습니다.😭
    
    String(format: “%20f”, 결과) 한 값을 Formatte.string()의 인자로 전달하니 출력값이 아예 나오지를 않습니다. Double형태가 아니어서 오류나는 것 같아서 타입을 바꾸기도 했지만 의도대로 동작하지는 않았습니다.
    
    그래서, 간단하게 20자리가 이상인 경우에서 에러처리를 하도록 구현하게 되었습니다.😢

6. 함수 작게 나누기
  기능적으로 하나의 역할을 한다고 생각되어 몇 함수의 길이가 너무 길어져서 고민입니다.🤔
  개인적으로 addStack() 나 touchUpOperatorButton() 의 경우 함수를 나누기가 애매하다고 생각됩니다. 😭

2022-03-24 16:44 UTC, yoo-kie requested changes

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
isValidNumber를 포함하여 조건문이 중복이거나 복잡한 것 같아요. hasFirstInput도 사용하지 않을 수 있을 것 같은데 예외처리가 필요한 상황을 고민해보시고 개선해보시면 좋을 것 같습니다.

ex. 이미 `currentNumber`는 "0"이므로 `numberLabel.text = "0"`로 설정할 필요없이 그 전에 return만 시켜주면 되지 않을까요?

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let input = try? findNumber(of: sender) else {
메서드명은 `findNumber`인데 받는 상수명은 `input`이라 가독성이 아쉬운 것 같아요. 서로 연관있는 네이밍으로 통일 시켜주면 가독성이 더 좋을 것 같아요!

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
findNumber와 마찬가지로 네이밍이 개선되면 좋을 것 같아요.

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +                numberLabel.text = numberFormatter.string(for: result)
이런 Formatter는 프로젝트에서 형태를 변환하는 용도로 자주 사용될 것 같은데요. 타입의 extension으로 구현해서 재사용성을 높여 보는건 어떨까요?

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if input == "=" {
= 버튼은 Operatore에 포함이 되지 않으며 if문으로 분기처리하는 것보다 별도의 IBAction으로 분리하는것이 좋을 것 같습니다.

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private var hasFirstInput = false
`hasFirstInput` 같은 경우, 상태에 대한 분기처리를 해주기 위한 플래그값으로 사용하셨는데요! 플래그 사용은 권장드리고 싶지 않습니다..ㅎㅎ 프로퍼티 상태를 관리하는 것이 어렵고 언제 어디서 값이 변경되는지 알기 어렵기 때문입니다. 스택뷰 내부에 값이 있는지를 확인해주는 다른 방법이 없을까요?

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        UIView.animate(withDuration: 0.3) {
0.3도 매직넘버 처리 같이 해주시면 좋을 것 같아요.

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
동일한 currentNumber.first에 대한 분기처리라면 switch문 활용은 어떠신가요??

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
removeFirst와 insert와 같이 값만 다른 동일한 코드의 중복을 개선할 수 있을까요?

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        let isValidDot = true
조건문으로도 예측 가능한 return 값이라 별도의 상수로 만들어주지 않으셔도 될 것 같아요:)

2022-03-24 16:44 UTC, yoo-kie commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				C713D9462570E5EB001C3AFC /* CalculatorViewController.swift in Sources */,
네이밍 수정 좋습니다👍

2022-03-24 17:19 UTC, yoo-kie commented
안녕하세요 Tiana!

이번 프로젝트도 고생 많으셨습니다.👏👏👏👏
UI도 함께 작업하시느라 더 작업이 복잡하셨을 것 같아요.😂

이번 PR에서는 아직 UI에 대한 부분은 시뮬레이터로 동작만 확인하고 따로 커멘트를 남기지는 않았습니다:) UI 관련한 건 나중에 따로 이야기 나눠보는 것도 좋을 것 같아요!

그럼 이번 STEP3에 대한 추가적인 의견 아래에 남기겠습니다.:)

### 고민한 점

1. numberLabel.text 값 갱신
    
    가독성을 위해 nubmerLabel.text를 변수에 담아서 사용하고 값을 갱신하려고 했지만 해당 값이 String이어서 의도대로 수정되지 않았습니다. 따라서, 값을 수정할 때는 원래 프로퍼티에 직접 접근하여 값을 갱신합니다.

`🐸 넵:) 괜찮습니다☺️ `
    
2. 스토리보드의 stackView 이용
    
    이번 프로젝트에서는 동적으로 스택뷰가 스크롤뷰에 추가됩니다. 이때, 기존에 스토리보드에 있던 스택뷰를 사용하면 새로운 값이 추가되는 것이 아니라 기존 값이 변경됩니다. 따라서, 스택이 추가될 때마다 새로운 스택뷰를 만들어서 추가하는 방식으로 구현했습니다.

`🐸 기존 스토리보드에는 비어있는 스택뷰를 임시로 넣어놓으셨더라구요! 이 부분 말씀하시는게 맞을까요?☺️`
    
3. 스크롤 뷰 제일 하단에 최신 값 오도록 구성
    
    스크롤 뷰의 `func setContentOffset(_ contentOffset: CGPoint, animated: Bool)`
    
    를 사용해서 CGPoint를 설정합니다.

    https://www.objc.io/issues/3-views/scroll-view/
    
<img width="770" alt="스크린샷 2022-03-24 오후 1 21 00" src="https://user-images.githubusercontent.com/70807352/159842748-df46773d-e4a8-4163-be2d-9f81b932ea10.png">

    
scrollView.bounds 높이가 추가되는 스택뷰의 높이인 것 같습니다. y좌표를 컨텐츠 높이에서 스택뷰의 높이를 뺀 값으로 설정해서 스크롤 뷰의 제일 하단에 위치되는 것으로 생각됩니다.🤔

`🐸 넵 연산을 통해 offset을 설정해주셨네요:)`
    
4. NumberFormatter 이용해서 숫자 표현하기
    
    <img width="575" alt="스크린샷 2022-03-24 오후 12 04 47" src="https://user-images.githubusercontent.com/70807352/159842783-151e47c1-e9c9-44c8-ba88-ea493bb73185.png">

<img width="518" alt="스크린샷 2022-03-24 오후 12 07 19" src="https://user-images.githubusercontent.com/70807352/159842813-2d0cdcd2-0c43-40f1-a2ee-a117604b244b.png">

    
반올림이 어떻게 되는지, 소수점이 어디까지 표현되는지를 디버깅을 통해 확인해서 원하는 결과를 얻을 수 있도록 구현했습니다.

`🐸 Formatter 사용 좋습니다! 커멘트에도 남겼듯이 Formatter는 주로 형식을 변경해주는데 사용하게 되는데요:) 타입의 extension으로 매번 Formatter를 작성해주지 않고 원하는 format을 갖추게 할 수 있도록 개선해보면 좋을 것 같아요!`

    
5. 20자리를 최대 수로 설정하기
    
    String(format:) 을 사용해서 20자리의 숫자를 얻어내고 이후 NumberFormatter를 적용시키 원하는 형태의 숫자로 만들고 싶었지만 두 개를 동시에 적용시키는 것에 실패했습니다.😭
    
    String(format: “%20f”, 결과) 한 값을 Formatte.string()의 인자로 전달하니 출력값이 아예 나오지를 않습니다. Double형태가 아니어서 오류나는 것 같아서 타입을 바꾸기도 했지만 의도대로 동작하지는 않았습니다.
    
    그래서, 간단하게 20자리가 이상인 경우에서 에러처리를 하도록 구현하게 되었습니다.😢

`🐸 20자리를 초과한 숫자를 입력받았을 경우 20자리만큼만 입력받는다는걸까용?`

6. 함수 작게 나누기
  기능적으로 하나의 역할을 한다고 생각되어 몇 함수의 길이가 너무 길어져서 고민입니다.🤔
  개인적으로 addStack() 나 touchUpOperatorButton() 의 경우 함수를 나누기가 애매하다고 생각됩니다. 😭

`🐸 좋은 고민사항입니다! 함수가 의도한 역할만을 수행하고 있는지를 고민해보시면서 개선하면 좋을 것 같습니다. touchUpOperatorButton 메서드 같은 경우 분리할 수 있는 부분을 하나 커멘트로 남겼습니다:) `

7. 추가적인 커멘트
`🐸 숫자 입력이 없는 상태에서 연산자를 반복해서 누르면 연산이 이뤄지지 않고 연산자의 종류만 변경이 되어야 한다고 알고 있는데요! 현재는 0으로 값이 추가되고 연산도 이루어지고 있는 것 같아요!`

2022-03-25 14:25 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +class CalculatorViewController: UIViewController {
수정했습니다😆

2022-03-25 14:25 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private var hasFirstInput = false
수정했습니다😆

2022-03-25 14:26 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        operatorLabel.text = ""
수정했습니다😆

2022-03-25 14:27 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
조건을 다시 살펴보고 수정했습니다😆

2022-03-25 14:27 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let input = try? findNumber(of: sender) else {
네이밍 변경했습니다😆

2022-03-25 14:27 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
네이밍 변경했습니다😆

2022-03-25 14:28 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +                numberLabel.text = numberFormatter.string(for: result)
재사용성을 생각해서 수정해보았습니다😆

2022-03-25 14:28 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if input == "=" {
조언해준신 것처럼 분리했습니당😆

2022-03-25 14:30 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private var hasFirstInput = false
플래그 사용이 지양되는군요🤔 calculatorInput 문자열의 값을 사용하는 방식으로 전체적인 수정 진행했습니다😆

2022-03-25 14:31 UTC, Kim-TaeHyun-A commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
switch 문으로 변경하면서 중복되는 구문이 없도록 수정했습니다😆

2022-03-25 14:41 UTC, Kim-TaeHyun-A commented
개굴 @yoo-kie 
늦게 피드백에 대한 답변 드려서 죄송합니다😭
하나를 수정하니 연쇄적인 문제가 생겨서 찾는데 시간이 걸렸습니당😢

피드백 주신 것 반영해서 코드 수정 진행했고 추가적인 답변을 아래에 달았습니다.

---
> 🐸 기존 스토리보드에는 비어있는 스택뷰를 임시로 넣어놓으셨더라구요! 이 부분 말씀하시는게 맞을까요?☺️
> 

스토리보드에서 만든 스택뷰가 동적 스택뷰를 만드는 데 활용될 수 있을지 궁금했습니다. 지금은 코드로 하나씩 만드는데 동적으로 생성하려면 스토리보드에서의 구현은 불가능한지에 대한 내용이었습니당😂

<br/>

> 🐸 Formatter 사용 좋습니다! 커멘트에도 남겼듯이 Formatter는 주로 형식을 변경해주는데 사용하게 되는데요:) 타입의 extension으로 매번 Formatter를 작성해주지 않고 원하는 format을 갖추게 할 수 있도록 개선해보면 좋을 것 같아요!
> 

```swift
extension NumberFormatter {
    static let calculator: NumberFormatter = {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        numberFormatter.maximumFractionDigits = 10
        return numberFormatter
    }()
}
```

위와 같이 확장했는데요. 개굴이 의도하신 방식이 맞을까요🤔

<br/>

> 🐸 아마 타입의 max값을 초과해서 발생하는 이슈일 것 같아요🤔
> 

> `Double` has a precision of at least 15 decimal digits
> 

라고 스위프트 공식문서에 적혀 있는데요. Double로 결과값을 얻고 있어서 20자리 이하가 표현될 수밖에 없겠네요.😂

<br/>

> 🐸 좋은 고민사항입니다! 함수가 의도한 역할만을 수행하고 있는지를 고민해보시면서 개선하면 좋을 것 같습니다. touchUpOperatorButton 메서드 같은 경우 분리할 수 있는 부분을 하나 커멘트로 남겼습니다:)
> 

각 함수가 어떤 역할을 하는지 정리하면서 리팩토링해봤습니다😆 함수를 작게 나누다보니 어디에 구현하는 것이 맞는지 고민하게 되었고 호출되는 순서로 배치했습니다. 역할이 작아지니 오류 찾기가 편하네요😀

<br/>

> 🐸 숫자 입력이 없는 상태에서 연산자를 반복해서 누르면 연산이 이뤄지지 않고 연산자의 종류만 변경이 되어야 한다고 알고 있는데요! 현재는 0으로 값이 추가되고 연산도 이루어지고 있는 것 같아요!
> 

리팩토링하면서 숫자 입력이 없으면 연산자만 바뀌도록 수정했습니다! PR 전에 리팩토링하면서 이상해진 것 같습니다.😭

---

* 리팩토링 과정에서 고민한 점
1. 스토리보드에서 Input Stack View 내부의 의미없는 content(stackView 2개)를 삭제해서 레이아웃 오류가 발생했습니다. 이를 해결하기 위해 input Stack View 의 높이를 임의의 수로 설정하고 우선도를 1로 낮춰서 xcode가 레이아웃을 계산이 가능하게 됩니다!

2. prefix를 일반 연산자와 분리된 타입으로 구현하면 전체 로직이 더 간단해 질 것 같습니다...😂

2022-03-28 15:13 UTC, merged