계산기 I [STEP3] mmim
yagom-academy/ios-calculator-app pull request #205
Opened 2022-03-24 17:26 UTC by JoSH0318

- @lina0322 엘림! 너무......늦게....PR드렸네요..😭
- 기다려주셔서 감사합니다...🙏
---
### 🤔고민한점
- 고민한점 ❓ / 트러블슈팅 ❗️
> 💬 엘림에게: 이번 프로젝트는 예외처리, 에러처리와의 싸움이었던 것 같습니다. 하나를 해결하면 두개의 문제가 발생하고, 또 시간을 투자할 수록 더 많은 예외와 에러를 만날 수 있던 프로젝트였습니다. 때문에 PR이 늦어졌어요 😭 많은 점을 고민했고, 그 전부를 기록하지 못해 의식의 흐름으로 메시지를 적어봅니다.
#### 1️⃣ stack view의 코드 구현
- ❓입력하는 카운트에 따라 stack view의 수가 정해지기 때문에 스토리보드에 구현할 수 없다.
- ❗️코드로 stack view를 추가해줘야한다고 판단했다.
- 예시로 받은 프로젝트의 기본값을 힌트로 scrollView > stackView > stackView > label2개 형태로 구현하기로 했다.
- ❗️먼저 입력되는 연산자와 피연산자 label의 특성을 설정해주었다. 그리고 그 label을 subStackView에 추가한다. addArrangedSubview 메서드를 사용!
- ❗️그 subStackView를 superStackView에 다시 추가하는 방법으로 구현했다. 마찬가지로 addArrangedSubview 메서드 사용!

#### 2️⃣ scroll view의 구현
- ❓scroll view는 기준점이 top에 있고 이번 프로젝트와는 반대의 움직임이다.
- 따라서 기준점을 내가 원하는 아랫쪽에 위치하도록 변경해야한다.
- ❗️setContentOffset(:animated:)를 이용하면 contents view의 기준점을 바꿀수 있다.
![](https://i.imgur.com/igiAAB1.png)
- contentOffset을 `CGPoint(x: 0, y: self.contentSize.height - self.bounds.size.height)` 설정해줬다. 
- bounds는 scrollView의 안에 생성되는 view의 고유 좌표계이다. 따라서 좌표가 아닌  `bounds.size.height`로 접근해야했다.
- ❓이렇게 설정을 하고 해당 메서드를 호출했지만 바로바로 업데이트 되지 않고 subStackView가 뒤늦게 올라가는 오류가 생겼다.
- ❗️view는 실시간으로 업데이트 되지 않기 때문에 `layoutIfNeeded()`을 통해 layout을 즉시 업데이트할 수 있도록 해야한다. 

#### 3️⃣ NumberFormatter
- ❓정수 3자리마다 ,를 출력해야된다. 또한 의미없는 0000을 제거한 상태로 수를 기록에 등록해야한다.
- ❗️`NumberFormatter`를 사용해야한다 판단했다.
- ❗️`numberStyle`을 `.decimal`로 설정해주는 것을 통해 해당 문제를 해결할 수 있었다.
- 또한, `roundingMode`과 `maximumFractionDigits`를 통해 반올림과 소수점자릿수 문제를 해결
- ❓이 과정에서 `maximumSignificantDigits`에 대한 오해가 생겼다. 최대 자릿수를 설정해주는 것으로 오해했고, 몇가지 실험을 통해 유효수의 최대값을 설정하는 메서드라는 것을 알게 됐다. 

#### 4️⃣ 소수점 이후 출력 문제
- ❓만약 1이라는 버튼을 4번 클릭하게 된다면 `1,111`처럼 `,`을 포함한 형태가 실시간으로 출력되어야한다.
- ❓따라서 `NumberFormatter`를 거쳐서 Label에 출력해야한다.
- ❓하지만 마지막 입력으로 `.` 을 입력하게 된다면 `NumberFormatter`에 `111.`과 같은 수가 들어가고 `111`이 출력되게된다. 따라서 `.`을 누름과 동시에 Label에는 `.`이 없는 `111`과 같은 형태가 출력된다. 내가 원하는 값은 `111.` 이 그래도 출력되는 것이다.
- ❓또한 `111.0`도 `111` 출력된다.
- ❗️`.`을 기준으로 두 개 요소로 배열에 담고, 정수만 `NumberFormatter`를 거치게하고 소수점 이후는 거치지 않는 형태로 label에 출력하도록 했다.

#### 5️⃣ 수많은 예외와 오류 케이스...
- ❓가장 많은 시간을 소요한 고민이었다. 생각할 경우의 수가 너무 많았고, 테스트할 수록 생각하지 못했던 경우가 계속 생겨나서 어떻게 처리해야하나 고민을 많이 했다.
- ❓예외처리를 할 수록 코드가 길어지고 때로는 쓸모없어진 코드가 발생하기도 했으며, 로직이 꼬여 오류가 발생하는 경우가 빈번했다.

#### 6️⃣ 함수 분리와 컨벤션
- ❓코드가 길어지면서 메서드의 크기?역할?이 커졌다. 한 가지 메서드에서 여러가지 일을 하는 경우가 많아졌고 분리를 해줘야했다. 솔직히 아직까지 어떤 방법 또는 기준으로 분리해줘야하는지 확실하지 않고 계속 고민 중이다.
- ❓컨벤션의 핵심은 가독성이다. 어떠한 코드가 가독성이 좋은지에 대해 고민했다. 프로퍼티/메서드 이름, 들여쓰기, 공백, 파일 분리 등 이전 프로젝트보다 더 많은 고민을 할 수 있었고, 조금씩 발전해가는 것을 느꼈다. 

### 🙋‍♂️질문사항
#### 1️⃣ 수많은 예외와 오류 케이스...
- 앞서 고민한 점에도 적은 내용입니다. 제가 생각하는 계산기는 입력마다 다른 동작을 해야하는 예외적인 경우가 많습니다. 저는 주로 guard-if문을 사용하여 이런 상황을 구현했습니다. 하지만 ㅜㅜㅜㅜㅜㅜ 이게 정말 맞는 것인지에 대한 확신이 없습니다. 예외처리를 할 수록 코드의 가독성이 떨어지고 지져분해지는 것을 느꼈습니다. 저의 접근 방법이 맞았던 걸까요... 이 부분에 있어 조언, 충고를 듣고싶습니다. 

#### 2️⃣ 소수점 이후 출력 문제
- 이 질문 또한 앞서 언급한 내용입니다. 제 생각엔 제가 선택한 방법이 좋은 방법은 아니라고 생각합니다. 하지만 그렇다고 해서 좋은 방법이 떠오르지 않는 문제였습니다. 이 부분에 있어서 조언이 필요합니다 엘림😭

#### 3️⃣ 숫자는 최대 20자리까지만 표현합니다...😨
- Double이 표현할 수있는 유효자릿수는 최대 16자리 정도입니다. 그런데...최대 20자리까지만 표현한다는 것이 납득하기 어려웠습니다. 연산 결과 또한 Double이기 때문에 결국 유효한 결과는 최대한 16자리라고 생각이 들었습니다. 이 부분에 있어서 조언을 듣고 싶습니다.

#### 4️⃣ flag에 대해서...
- 이번 프로젝트에서 3개의 Bool타입 flag를 사용했습니다. (isFirstTime, isDotUsed, isNone) 예외 조건을 처리하다보니 생겨난 flag들인데...이게 좋은 습관?인지 모르겠습니다.🥲

> 기타 질문 사항이 생기면 바로 여쭤보겠습니다 🙏

2022-03-26 07:33 UTC, lina0322 requested changes
안녕하세요, 밈!
평화로운 주말을 보내고 계신가요~
다음주에 방학이라던데ㅎㅎㅎ 푹 쉬고 오시려면 후딱 마무리 해야겠네요!

stackView를 코드로 밖에 구현할 수 없는 상황이라는 걸 잘 파악하고 진행하신 것 같아요.
또한 scroll view에 관한 공부도 하셨네요!
contentOffset에서 Offset이 명확하게 어떤 위치인지, 화면에 보이는건 어떤 부분인지 정확하게 집고 넘어가면 더 좋겠네요!

밈이 질문 주신 부분 중에 `수 많은 예외`라는 표현이 있었어요.
사실 기획에서 주는 것처럼 코드를 작성하다보면 정,말,정,말 수 많은 특이 케이스들이 발생하고
이슈가 발생해서 또 그런걸 막아주면서 새로운 케이스가 발생하기도...
그럴때 일수록 줄줄이 if문을 써서 막으면 좋을까요??
guard랑 if의 차이점을 명확하게 이해하고, 함수 분리나 코드 분리를 할 수도 있고 
역할을 나누면서 다양한 아키텍쳐를 적용하는 것까지도 생각할 수 있겠죠!(아키텍쳐는 예외처리를 위해서는 너무 큰 범위지만.. 그래도?!)

그래서 지금 밈의 질문들이 사실 
제가 보기에는 `1번 수 많은 예외와 오류 케이스`에 다 해당하는 내용들인 것 같아요!
코드에 정답은 없으니까 이렇게 저렇게 더 다양하게 시도해보고
코드 리뷰나 동료들과의 대화 등을 통해서 점점 더 다듬어 나가면 되니까, 지금 당장 할 수 있는 것에서 조금씩 수정하고 발전시켜 나가 봅시다!

자~ 마무리 어서 해볼까요!!! 화이팅🎉

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    }
초기 시점으로 모든걸 돌려놓는 부분들을 잘 모아놓았네요. GOOD☺️

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    @IBAction func ACButtonClicked(_ sender: UIButton) {
clicked라는 표현은 잘 안 쓰는 것 같기도...?🤔 다소 어색하네요 더 좋은 표현은 없을까요?

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        }
guard를 따로 나누어서 작업한 이유가 있을까요??

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +            return
이 부분을 guard로 하면 어떤 느낌일까요?

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        }
조건이 너무 많고 복잡해서 나중에 유지보수 할 때나, 다른 사람이 파악할땐 어려울 수 있겠어요.
좀 더 깔끔하게 하려면 어떤 방법이 있을까요?😀

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        } else if isFirstTime == false && operandLabel.text == "0" && isNone == true {
guard는 swift 문서에서 어떤 파트에 있을까요??ㅎ

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        let expressionString: String = expressionRecord
타입을 지정해준 이유가 있나요?😉

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    private func workAfter(_ result: String) {
work..? what kind of work?🤔

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    private func insert(_ selectedOperator: UILabel, _ selectedOperand: UILabel) -> UIStackView {
insert를 사용하는 부분에서, 매게변수루 어떤 어떤것이 들어가는지 명확하게 이해하기 어려울 수도 있겠어요👀
그리고 지금 함수의 기능은 UIStackView를 반환하는 것 같은데, 올바르게 함수명이 지어진건가욥?!👀

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        return operandExpressionForm
따로 타입의 Extension으로 분리하여 작업하는건 어떨까요?

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Utils/UIScrollView+Extexsion.swift
> +        layoutIfNeeded()
layoutIfNeeded는 왜 필요할까요? 그리고 관련된 함수들은 어떤게 있는지 확인해볼까요??🙏

2022-03-26 07:33 UTC, lina0322 commented on Calculator/Calculator/Utils/UIScrollView+Extexsion.swift
> +import UIKit
둘 다 필요합니까?💁🏻‍♀️

2022-03-26 07:33 UTC, lina0322 commented on README.md
> +- bounds는 scrollView의 안에 생성되는 view의 고유 좌표계이다. 따라서 좌표가 아닌  `bounds.size.height`로 접근해야했다.
`bounds VS frame`
시간날때 알아보면 좋겠어요🧐

2022-03-26 09:34 UTC, JoSH0318 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        let expressionString: String = expressionRecord
제가 알고 있기론!
swift에서는 타입 추론을 통해 타입 명시를 하지 않아도 된다고 알고있습니다. 하지만 컴파일러는 타입을 추론하는 과정을 거쳐야하기 때문에 조금 더 시간을 소모하는 것으로 알고있습니다. (물론 저희 프로젝트에서는 거의 영향이 없겠지만 덩치가 커진다면!)
이러한 근거로 새롭게 선언한 프로퍼티, 상수, 변수는 될 수 있다면 타입 명시를 하고있습니다.
아무래도 현업에선 제가 생각하는 것과 다른 면이 있을 수도 있다고 생각이 들어욥 😭 조언이 듣고싶습니다.

2022-03-26 09:39 UTC, JoSH0318 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    private func workAfter(_ result: String) {
어엇...너무 모호한 이름이었네요!
수정했습니다!

2022-03-26 09:48 UTC, JoSH0318 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    private func insert(_ selectedOperator: UILabel, _ selectedOperand: UILabel) -> UIStackView {
이 부분에 대해서 질문이 있습니다!
리턴 값을 가진 메서드 이름을 짓는 과정에서 생긴 궁금증입니다.
함수형 프로그래밍 측면에서 봤을 때, 리턴이 있는 함수는 1급시민으로써 상수와 같이 사용할 수 있습니다. 그런데!!! 
`expressionRecordStackView.addArrangedSubview(insert(selectedOperator, selectedOperand))` 와 같이
addArrangedSubview의 매개변수명이 동사여서 어색한 느낌이 있습니다.
그렇다면 이렇게 리턴 값이 있는 함수의 경우에는 "함수의 이름은 동사로 시작해라"라는 불문율을 깨고 명사로 지어도 되는 걸까요??

2022-03-26 10:08 UTC, JoSH0318 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        return operandExpressionForm
class 내부에서 대중적?으로 쓰이거나, 특별한 역할을 수행하는 메서드는 extenssion으로 구분하라는 말씀 같은데 맞나요?😀
아예 생각하고 있지 않던 부분이라 감사합니다! 수정했습니다!

2022-03-26 10:11 UTC, JoSH0318 commented on Calculator/Calculator/Utils/UIScrollView+Extexsion.swift
> +import UIKit
앗..import UIKit 필요합니다!!!!!!

2022-03-26 10:51 UTC, JoSH0318 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        }
guard문을 합할 수 있습니다!! 이것도 놓치고있던 부분이었네요 ㅎㅎ 수정했습니다

2022-03-26 10:51 UTC, JoSH0318 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    @IBAction func ACButtonClicked(_ sender: UIButton) {
tapped가 더 적합해보입니다!!!

2022-03-26 12:58 UTC, JoSH0318 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        }
이 부분에서 정말 많은 고민을 했던 것 같아요. 
if-else로 조건을 추가하기보단 if문으로 각 조건을 return시키는게 조금 더 좋아보이는 것 같아 수정했습니다.
이러한 방향이 맞을까요??

2022-03-26 13:37 UTC, JoSH0318 commented on Calculator/Calculator/Utils/UIScrollView+Extexsion.swift
> +        layoutIfNeeded()
처음에는 `layoutIfNeeded`없이 진행했을 때, stackview가 한 박자 늦게 올라가는 현상이 있어서 
drawing cycle 문제라는 것을 알고 공부해봤습니다. 사실 이것을 알기까지 참 오래걸렸습니다 😭
setNeedsDisplay / setNeedsLayout  처럼 cycle 호출 시점에 예약?을 걸어 자동으로 호출되는 메서드가있고
displayIfNeeded / layoutIfNeeded 처럼 cycle을 기다리지 않고 즉시 실행되는 메서드가 있었습니다!

2022-03-27 14:04 UTC, JoSH0318 commented
@lina0322 엘림! 🙋‍♂️ 리팩토링 완료했습니다. 
말씀하신 부분(if문을 함수로 분리)을 수정해봤지만, 아직 부족한 점이 많아서 제대로 된 것 같지 않네요 😭
DM으로 꼼꼼한 답변 해주셔서 감사했습니다. 2주 동안 고생하셨습니다. 😊

2022-03-30 05:10 UTC, merged