계산기 I [STEP3] Doogie
yagom-academy/ios-calculator-app pull request #206
Opened 2022-03-24 18:06 UTC by doogie97

안녕하세요! 라자냐! @wonhee009
STEP3에서 너무나도 많은 난관을 겪게 되어서 목요일 오후가 아닌 금요일 새벽에 PR보내게 됐습니다...!
그런 만큼 질문 사항이 좀 많기도하고... 길기도하고... 모호 할 수도 있는데 번거로우시더라도 답변 주시면 감사하겠습니다!

## 고민한 점
###  뷰 변화 반영 시점

숫자를 추가한 이후 ScrollView안에 있는 스택뷰에 추가되었으며 아래와 같은 코드를 통해 최하단으로 스크롤 하는 기능을 구현
```swift
    func scrollToBottom(labelStackView: UIStackView) {
        let bottomOffset = CGPoint(x: 0, y: contentSize.height - bounds.size.height)
        setContentOffset(bottomOffset, animated: true)
```
ScrollView가 갖고 있는 컨텐츠의 높이에서 스크롤뷰의 높이 만큼 빼준 값의 위치로 이동한다는 점에 있어 문제가 없다고 생각 했으나 리스트 한개씩 밀려서 올라오는 문제가 발생

![](https://i.imgur.com/SqN7o2a.png)

추가 전 ScrollView안에 있는 스택뷰의 크기를 확인 하고 추가 후 확인 했을 때 변화가 없었음
그래서 확인 결과 뷰의 변화가 반영되는 시점? 에 대한 글을 읽게 되었는데 그 글에 다르면
```swift
    func scrollToBottom(labelStackView: UIStackView) {
        layoutIfNeeded()  // << 요거!
        let bottomOffset = CGPoint(x: 0, y: contentSize.height - bounds.size.height)
        setContentOffset(bottomOffset, animated: true)
```
해당 메서드를 통해 레이 아웃을 바로 갱신 시킬 수 있었음

## 고민했던 것들 & 조언 받고 싶은 내용
### 1. ScrollView의 레이아웃 과정에서의 문제점
![](https://i.imgur.com/uynlj4h.png)
어플 실행시에는 ScrollView에는 아무 컨텐츠도 없는데 빨간줄이 뜨더라도 이렇게 비워줘야 하는지 아니면 아무 요소라도 추가하고 뷰 실행 시 제거해줘야 하는지 고민
->일단은 후자의 방법대로 추가 해놓고 어플 실행시 ViewDidLoad에서 제거해줬습니다

### 2. Double의 유효 자릿수 문제
![](https://i.imgur.com/oeAOF50.png)
Double의 유효 자릿수는 15자리 이지만 이번 프로젝트는 화면에 20자리까지 나타내기를 요구하였습니다

그런데 더블의 유효 자릿수와 별개로 입력되는 숫자를 제한한다고 해도 결과가 20자리를 넘고, 연산 결과를 20자리까지만 나오게 제한을 한다 해도 한 번의 계산만 20자리로 나올 뿐 그 계산 결과에서 추가 연산을 하면 결국에는 20자리가 넘는 상황이 발생했습니다.

그래서 결과적으로는 콤마를 포함한 20자리 수를 나타내기로 결정하였으나 
1. 이런 상황에서는 `3e+27` 이렇게 exponential을 통해 나타나는 것을 요구하는 것인지
2. 더블이 표현하지 못하는 숫자를 만나게 되면 오류를 표출해주면 되는지 궁금합니다

### 3. NumberFormatter의 maxSignificantDigits 란??
![](https://i.imgur.com/APd4KzR.png)

![](https://i.imgur.com/vkns1jz.png)
계산 결과가 위와 같이 나오는 케이스들이 너무 많았는데 부동소수점의 문제점이긴 하지만 해당 문제는 NumberFormatter의 maxSignificantDigits를 사용함에 있어 문제가 발생했습니다

```swift
let numberFormatter = NumberFormatter()
numberFormatter.maximumIntegerDigits = 10 // 1번
numberFormatter.maximumFractionDigits = 10 // 2번
numberFormatter.maximumSignificantDigits = 10 // 3번
```
NumberFormatter에서 자릿수를 제한하는 키워드는 위와 같이 세가지가 있는데 
1번은 정수의 자릿수를, 
2번은 소수의 자릿수를 제한하는 기능이라고 확인을 했으나 
3번의 경우 공식 문서와 그 예시로는 파악을 하기가 어려워 대충 정수와 소수를 원하는 자릿수로 제한하는 기능이라고 추측을 하고 사용하여 위와 같은 문제가 발생

추후 Double의 유효자릿 수에 대해 찾아보면서 Significant Digits를 직역하면 유효 자릿수라는 사실을 알게 되면서 `maximumSignificantDigits` 는 최대 유효자릿수를 설정해 주는 키워드로 확인 했으며 그로 인해 문제가 발생 한 것으로 파악했습니다(하지만, 이 부분도 추측이면 정확한 사실은 아님...)
그래서 maximumSignificantDigits가 하는 일이 정확히 무엇인지 궁금합니다

### 4. flag사용
flag를 통해 분기점을 나눠주는 곳이 많은데 일단 쓰면서도 해당 방법이 과연 괜찮은 방법인가...? 라는 의문이 계속 들었습니다(생각하기가 너무 머리가 아파서...)
그래서 궁금한 점은 flag는 웬만하면 사용하지 않는 것이 좋은지 아니면 딱히 상관이 없는지(?) 도 궁금합니다

2022-03-25 08:34 UTC, wonhee009 requested changes
@doogie97 스텝3 수고하셨습니다 🎉 
코드에 몇몇 코멘트 남겨두었으니 확인 부탁드립니다. 🙏 
전반적으로 "0", "."와 같은 부분들을 상수로 관리해주는 편이 좋을거 같습니다.

#### 고민한점

- 리스트가 한개씩 밀려서 올라오는 문제가 어떤 경우일까요

- 뷰를 remove하는 행위가 비용이 비싼 행위여서요. 뷰를 비워주고 워닝을 없애야할거 같습니다.

- Double의 유효 자릿수 문제: 헷갈리는 부분이나 애매한 부분은 기획자에게 물어보는게 좋을거 같습니다. 

- [stackoverflow](https://stackoverflow.com/questions/47026921/string-format-limit-significant-digits-swift) 확인해보시면 될거 같습니다. 

- flag가 너무 많아짐에 따라 하나의 메서드에서 많은 flag 값들을 확인하느라 조건문들이 무수하게 늘어나 코드의 이해도, 복잡도도 올라간거 같습니다. 또한, 이후 코드 수정 혹은 유지보수할때에 코드 파악 및 오류의 가능성도 올라간거 같습니다. 다시 한 번 조건들을 확인해보고 공통화할 수 있는 코드들은 공통화하고 줄일 수 있는 flag는 줄이는게 좋을거 같습니다.

2022-03-25 08:34 UTC, wonhee009 commented on Calculator/Calculator/Controller/ViewController.swift
> +        layoutIfNeeded()
호출해주는 이유가 있을까요?

2022-03-25 23:21 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var isNoneNumber: Bool = true
요구서에서 `현재 숫자입력이 없는 상태인 0에서는` 이라는 조건에 따라 로직이 달라지고 있어서 해당 조건을 맞춰주기 위해 설정했습니다
최초 실행시 보여지는 0과 AC, CE버튼을 눌렀을 때 보여지는 0을 구별하기 위함 입니다

2022-03-25 23:34 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        layoutIfNeeded()
scrollToBottom을 호출 해도 리스트가 한개씩 씹힘(?) 현상이 일어났습니다
lldb를 통해 스택뷰 추가 직전, 추가 직후, scrollToBottom호출 직후의 상황에서 연산 목록 스택뷰의 height를 확인 해 보니, 추가 직후라면 높이가 변경되어야 하는 것이 맞는데 즉시 반영이 되지 않는 것을 확인 했습니다
(이와 관련해 정보를 찾아보니 드로잉사이클에 따라 해당 변경은 다음 드로잉사이클이 시작될 때 반영된다는 것을 확인하게 되었습니다)
그래서 지금 이 scrollToBottom에서 사용되는 contentSize는 내가 스크롤 하기 원하는 컨텐츠의 사이즈가 아닌 그 이전의 사이즈 이기 때문에 contentSize를 사용 하기 전 layoutIfneeded() 함수를 통해 다음드로잉사이클 때 반영되어야 하는 레이아웃을 즉시 반영하기 위해 호출 하였습니다

2022-03-27 01:23 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var numberListStackView: UIStackView!
number만 담고 있는 것보다 formula를 담고 있는게 맞다고 생각해 `formulaListStackView`로 변경 하겠습니다

2022-03-27 01:24 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.isFirst = false
네 그렇습니다
사실 이 코멘트의 의도 파악을 하지 못했는데 조금만 상세하게 설명 가능할까요??

2022-03-27 01:55 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +            $0.removeFromSuperview()})
공식문서를 확인 했을 때 stackView의 경우 arrangedSubViews 배열이란게 있어서 서브뷰를 추가할 때 `addArrangedSubview` 메서드를 통해 추가한다고 확인 했습니다.
아울러, addSubView의 경우 추가될 서브뷰의 크기와 위치등을 설정해주어야 하지만 addArrangedSubview를 이용해 스택뷰에 추가할 경우 상위 스택뷰의 정렬 조건에 따라 추가되는 모습을 확인 할 수 있었습니다

2022-03-27 01:57 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func setBasicStatus() {
`initializeCalculator`라는 이름으로 바꿔보았는데 괜찮은가요?

2022-03-27 02:34 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.isFirst = false
일단 isFirst의 경우 줄일 수 있는 것으로 확인되어 제거 해 준 상태 입니다

2022-03-27 02:45 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.operandLabel.text = "0"
"0" 과 아래에서 말씀해주신 "-", "NaN" 과 더불어 "."  또한 여러군데에서 사용되고 있기에 뷰컨트롤러 상단에서 상수로 선언해 사용하였습니다.
다만 지금과 같은 상황에 뷰컨트롤러 안에서 상수로 선언해주는 것이 좋을까요 아니면 네임스페이스를 만들어 사용하는 것이 좋을까요??

2022-03-30 00:45 UTC, merged