계산기 I [STEP3] 쿼카
yagom-academy/ios-calculator-app pull request #207
Opened 2022-03-25 09:02 UTC by Quokkaaa

안녕하세요 @1Consumption 울라프!
시간관계상 할 수 있는부분까지만 구현했습니다.
아무래도 시간이 부족하다보니 STEP3는 개념공부를 거의 못하고 코드만 구현하기 바빳던것같아요 그래서 고민했던 점이나 어려웠던점 등 리뷰받을 수 있는 내용이 많지않아 아쉽습니다..
그래도 남은 시간동안 최대한 핵심경험은 학습하고 넘어고 마무리해보려고합니다!
구현한것까지만이라도 리뷰 잘부탁드리겠습니다 (꾸벅)

# 고민했던점&어려웠던점&조언을 얻고 싶은점
- NumberFormatter의 사용방법에대한 고민
- 아울랫 컬렉션을 활용하는 방법에 대한 고민
- '='클릭시 연산진행
두 가지 방법이 떠올랐는데요 첫번째는 연산자를 누를때마다 연산자와 피연산자를
전역변수에 저장해놓고 연산을 하는방법
두번째는 scrollView의 상위 stackview에 접근하고 하위 stackView에있는 연산자의 label과 피연산자의 label의 값을 가져오는 방법이 있다고 판단했습니다. 만일 두번째방법으로 구현해본다고하면 추가적으로 전역변수를 생성하지않고 값만 추출하면되기때문에 메모리측면에서도 좋지않을까해서 값에 접근하려고 시도해봤더니 타입추론을 여러번 해야하다보니 쉽지않았습니다. 
혹시 조언좀 주실 수 있을까요 ?
- 하나의 뷰컨트롤에서의 데이터 관리 방법이 있을지 궁금합니다.
- STEP3 핵심 경험이 스크롤뷰와 스택뷰를 경험하는것인데 이외 울라프의 생각은 어떠한지 궁금합니다.
- 요구사항대로 구현하는거에 집중하다보니 메서드내에 많은 기능이 들어간것같은데 이부분에대해서도 피드백 해주시면 감사하겠습니다.

# 해결하지못한부분
- 0으로 나누기에 대해서 결과값을 NaN으로 표기
- 잘리는 숫자에 대한 반올림
- '=' 버튼을 눌렀을때 연산하는 로직
- 연산에 올라간 값들이 많아질경우 스크롤되는 기능

2022-03-27 02:55 UTC, 1Consumption requested changes
@Quokkaaa
안녕하세요 쿼카! 마지막 스텝 고생 많으셨습니다.

그런데 대부분의 질문이 고민한 점을 적어주지 않고, 단수 해답을 원하는 거 같아서 답변하기 어려웠습니다. 특히 어떤 점을 고민하고 시도해봤는지, 어떤 어려운 점이 있었는지를 말씀해주셔야 제가 키워드를 드리고 방향을 제시해줄 수 있을 거 같습니다. 

> '='클릭시 연산진행
두 가지 방법이 떠올랐는데요 첫번째는 연산자를 누를때마다 연산자와 피연산자를
전역변수에 저장해놓고 연산을 하는방법
두번째는 scrollView의 상위 stackview에 접근하고 하위 stackView에있는 연산자의 label과 피연산자의 label의 값을 가져오는 방법이 있다고 판단했습니다. 만일 두번째방법으로 구현해본다고하면 추가적으로 전역변수를 생성하지않고 값만 추출하면되기때문에 메모리측면에서도 좋지않을까해서 값에 접근하려고 시도해봤더니 타입추론을 여러번 해야하다보니 쉽지않았습니다.
혹시 조언좀 주실 수 있을까요 ?

값을 입력받을 때마다 모델에 저장을 할 거 같습니다. 연산자냐 피연산자냐 여부는 숫자가 들어왔는지 여부로 구분하면 될 거 같고요. 

> 하나의 뷰컨트롤에서의 데이터 관리 방법이 있을지 궁금합니다.

데이터를 관리하는 객체를 만들고, 뷰컨에서는 해당 객체를 사용만 할 거 같습니다. 뷰컨트롤러의 역할은 모델 객체에 이벤트 전달하는 뷰니까요. 

나머지는 코멘트를 참고해주세요.

2022-03-28 03:04 UTC, Quokkaaa commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet var operatorBtns: [UIButton]!
weak는 약한참조로 강한순환참조를 방지하기위해 사용합니다. 그래서 더이상 사용하지않게될때 ARC가 인스턴스에 nil을 할당하여 메모리에서 해제가 되는걸로 이해하고 있어요!
저기 아울렛컬렉션에 weak를 할당하게되면 약한참조는 클래스와 클래스바인딩 프로토콜을 따르는 것에만 사용할 수 있다는 에러가나더라구요! 일반 UIButton이아니라 [UIButton]인 배열타입이라서 저런에러가 나는걸까요 ??
또한 아울렛컬렉션은 weak가 사용이안되면 강한순환참조를 방지하기가 어려울것같은데 그러면 컬렉션사용은 지양해야하는걸까 궁금합니다!
https://github.com/yagom-academy/ios-calculator-app/pull/207/commits/f1fbf2f8a1dab93b9d8c67bf3052d526d44c0d29

2022-04-09 02:30 UTC, Quokkaaa commented on Calculator/Calculator/ViewController.swift
> +        }
이와같이 리펙토링하였습니다.
https://github.com/yagom-academy/ios-calculator-app/pull/207/commits/55b01dd3f310b271925598fd95c16f44da3699b8

2022-04-09 02:31 UTC, Quokkaaa commented on Calculator/Calculator/ViewController.swift
> +        }()
말씀해주신대로 리펙토링 해보았습니다. ㅎㅎ
https://github.com/yagom-academy/ios-calculator-app/pull/207/commits/1ad8fc3f1289664b2d384314486aee4d3352d20d

2022-04-09 02:32 UTC, Quokkaaa commented on Calculator/Calculator/ViewController.swift
> +        inputFormulaLabel.text = "0"
메서드로 따로 기능분리해보았습니다.
https://github.com/yagom-academy/ios-calculator-app/pull/207/commits/77f62381df886ddd5f30d91882afc652172d200e

2022-04-09 03:01 UTC, Quokkaaa commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func touchUpOperandBtns(_ sender: UIButton) {
넵 수정하였습니다
https://github.com/yagom-academy/ios-calculator-app/pull/207/commits/2195a38fe27cc5566d74758f81ada414f4a4323f

2022-04-09 03:29 UTC, Quokkaaa commented on Calculator/Calculator/ViewController.swift
> +    }
초기에 앱을 실행하고 init이 된 이후에 viewDidLoad가 불리기도하고 화면전환이될때 그 뷰에대한 로드가된 시점에 불리는것으로 이해하고 있습니다.

2022-04-09 04:04 UTC, Quokkaaa commented on Calculator/Calculator/ViewController.swift
> +    }()
상수에 클로저를 할당한것입니다.
클로저는 일급객체이기때문에 전달인자로 보낼수있고, 변/상수등으로 저정하거나 전달할수있으며, 함수의 반환값이 될 수 도 있습니다. 그리고 추가로  참조 타입입니다.

그래서 이 상수의 선언방식은 클로저안에서 변/상수생성이 가능하여 최종적인 클로저 안에있는 상수의 값을 return받고 값을 저장하는 걸로 이해하고있습니다.

2022-05-23 00:21 UTC, closed without merging