계산기 I [STEP3] malrang
yagom-academy/ios-calculator-app pull request #209
Opened 2022-03-25 10:33 UTC by malrang-malrang

@AppleCEO 
안녕하세요 도미닉,..! 
step3 진행하면서 난이도가 많이 높다고 생각했습니다 ㅠㅠ 계산기.. 굉장히 어려운 친구였습니다 ㅠ
수차례 뜯어 고치기를 반복하여 ..
그래도 끝까지 만들어보고자 하여 기능 구현은 어찌어찌 하였으나 코드가 다듬어지지 않아 가독성도 떨어지며 손봐야할곳이 이만저만이 아닙니다..ㅠ
시간 관계상.. 최대한 가능한부분까지 만들어보았습니다.!

어떤 부분을 손보아야 가독성이 더좋을지 도미닉의 의견을 듣고싶습니다!
didTapOperator 메서드 내부의 중복되는 코드는 주말내에 고쳐보도록 하겠습니다..!

해결하지못한점
1. 결과값 이나왔을때 이후행동
- 숫자를 누를경우
- 연산자를 누를 경우
결과값이 NaN 일때 이후행동
- 숫자를 누를경우
- 연산자를 누를 경우

2022-03-26 09:36 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@malrang-malrang 이번 스텝 마지막까지 고생하셨습니다~
간단히 코멘트 드렸습니다.

2022-03-26 09:36 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +     let bottomOffset = CGPoint(x: 0, y: self.contentSize.height - self.bounds.size.height)
이 부분은 어떤 역할을 하나요?
오토레이아웃을 적용하지 않고 이렇게 위치를 하드코딩으로 넣어주는 이유가 있을까요?

2022-03-26 09:36 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
label 을 만들어주는 코드인데 함수명은 makeLable 이네요!
그리고 이렇게 make 라는 동사는 단순히 레이블을 하나 만들어주는 걸로 오해할 수 있을 것 같습니다.
기본 레이블이 하나 만들어지는 걸로 오해할 수 있으니 더 상세한 이름이 좋겠습니다~

2022-03-26 09:38 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +        let xx = valueToBeCalculated.joined(separator: " ") + " " + inputOperand
앗.. 이부분 네이밍을 수정한다는게.... ㅠㅠ 
이런 실수를 줄여야합니다..ㅠㅠ
명심하겠습니다!

2022-03-26 10:34 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
아래쪽 if 문은 없어도 되지만 if 문을 여러개 사용하다보니 if 문이 있는것이 가독성에 도움이 될까? 싶어 if 구문으로 작성하였습니다!
꼭 필요하진 않았던것 같습니다!
같은 이유로 작성된 if 구문은 제거 해보도록 하겠습니다!

2022-03-26 11:19 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let result = numberFormatter.string(for: convertedNumber) else { return "NaN" }
```swift
let result = numberFormatter.string(for: convertedNumber) ?? "NaN"
```
가드문을 개행 하였었으나

위와같이 Nil-Coalescing 방법으로 수정해보았습니다!

2022-03-26 11:24 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
그렇군요! 두 if 모두 실행구문 없이 함수를 종료하기 때문에 같이 합쳐두는게 좋을것 같습니다! :)

2022-03-26 11:30 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
해당 로직은 현재 호출 될때 마다 1개의 label 을 만들어주는 방식으로 사용되고 있습니다!
해당 메서드 makeLable 을 두번 호출하여 2개의 레이블을 만들어 스택뷰에 추가해 사용되고있습니다!
호출을 2번하는 상황인데 이름을 어떻게 수정해야할지 감이 오지 않아 한번더 여쭤봅니다 ! ㅜㅜ

그리고 현재 make label, make stackView 메서드는 구조를 변경해보려고 합니다!
didTapOperator 메서드 내부를 손보기 위해서는 이 두 메서드 구조를 변경해야할것 같습니다..!

2022-03-27 23:54 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
보통 위에서 조건이 걸리고 return 을 하면 아래 쪽 코드는 else가 자동으로 들어간다고 생각하면 됩니다!
그래서 지금은 inputOperand == "0" 의 else 인 inputOperand != "0" 이 자동으로 생략되있다고 생각하고 if문을 제거하는 것이 보기 좋을 것 같네요~

2022-03-27 23:55 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +        let xx = valueToBeCalculated.joined(separator: " ") + " " + inputOperand
바로 생각이 안 나더라도 xx 라는 네이밍보다는 떠오르는 가장 괜찮은 것 같은 이름으로 넣어주는 것이 좋습니다!
저는 xx, x 와 같은 상수명은 사용하지 않습니다~ 나중에 바꿔야한다고 해도 까먹을 수 있어서요.

2022-03-27 23:55 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let result = numberFormatter.string(for: convertedNumber) else { return "NaN" }
오우.. 이런 부분이 더 나을 수 있겠군요~ 🥇

2022-03-27 23:57 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +     let bottomOffset = CGPoint(x: 0, y: self.contentSize.height - self.bounds.size.height)
위치를 변경하기 위해서는 오토레이아웃에 스텍뷰를 사용하고 뷰를 히든처리 하면 위로 올라가는 동작을 사용할 수도 있을 것 같습니다.
오토레이아웃을 적용하는 뷰컨트롤러에서 이런 식으로 하드코딩해서 넣어주는 것은 많이 사용하지 않습니다.
오히려 이렇게 넣어주면 오토레이아웃을 나중에 적용하면 충돌이 발생할 수도 있고 어느 코드에서 이 위치를 바꿔주는지 찾기 힘들어서 유지보수에 안 좋을 수 있습니다!

2022-03-27 23:58 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
ㅎㅎ 네 makeLabel 보다는 더 명확한 이름이어도 좋을 것 같습니다. 예를 들어 계산 결과를 보여주는 것이면 makeCalculationResultLabel 등과 같은 이름도 가능하겠네요~

2022-03-28 00:41 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@malrang-malrang 고생하셨습니다~
몇가지 코멘트 마지막으로 드렸습니다.
확인해보고 수정해보고 다 수정하시면 머지해달라고 말씀해주시면 머지하도록 하겠습니다!

추가 코멘트
1. AppDelegate, SceneDelegate 가 뷰컨트롤러 폴더에 들어있는 부분이 좀 어색했습니다. 앱딜리게이트와 씬델리게이트는 뷰컨트롤러가 아니라고 생각하는데 이 폴더에 넣은 이유가 있을까요?

2.+/- 버튼을 누르면 최종 결과에서 바뀌는 것이 아닌 마지막에 연산자 뒤에 입력한 숫자가 바뀌었습니다. 예를 들면 85+3 = 을 해서 88 이 나왔을 때 +/- 를 누르면 -88 이 될 것이 예상되었는데 -3 이 나왔습니다.

3. 뷰컨트롤러가 다소 길었습니다.  연산 관련된 메소드는 따로 객체를 만들어 그 객체에 메소드로 메시지를 보내고 결과 값만 받아와서 뷰컨트롤러에서 뿌려주기만 하면 뷰컨트롤러의 코드 양이 줄어들 수 있을 것 같습니다.

2022-03-28 00:41 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +final class ViewController: UIViewController {
조금 더 상세한 뷰컨트롤러명이어도 좋을 것 같습니다~ 
기본으로 생성되는 뷰컨트롤러 이름을 사용하면 이 뷰컨트롤러가 어떤 뷰인지 나중에 뷰컨트롤러들이 많아지면 헷갈리게 됩니다.

2022-03-28 00:41 UTC, AppleCEO commented on Calculator/Calculator/Controller/ViewController.swift
> +        let `operator` = UILabel()
저는 이렇게 상수명을 사용하지 않습니다.
예약어가 있는 경우도 많아서 조금 더 긴 상수명이 좋습니다.
UILabel 을 생성해주므로 operatorLabel 이라는 이름도 좋겠네요~

2022-03-29 08:29 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
네! 수정하도록 하겠습니다! :)

2022-03-29 08:36 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +        let xx = valueToBeCalculated.joined(separator: " ") + " " + inputOperand
네! 명심하겠습니다! 이러한 습관 고쳐야하는데 말이죠...ㅜㅜㅜ Pr 하기전에도 꼼꼼히 꼭 체크 하도록,...하겠습니다!

2022-03-29 08:38 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +final class ViewController: UIViewController {
네! 이부분까지 생각하지 못한것 같습니다.. 수정해보도록 하겠습니다!

2022-03-29 08:39 UTC, malrang-malrang commented on Calculator/Calculator/Controller/ViewController.swift
> +        let `operator` = UILabel()
그렇군요! 항상 네이밍이 가장 큰 고민 입니다 ..ㅠㅠ 
추천해주신 네이밍으로 수정해보도록 하겠습니다!

2022-03-29 08:50 UTC, malrang-malrang commented
AppDelegate, SceneDelegate 가 뷰컨트롤러 폴더에 들어있는 부분이 좀 어색했습니다. 앱딜리게이트와 씬델리게이트는 뷰컨트롤러가 아니라고 생각하는데 이 폴더에 넣은 이유가 있을까요?
- 해당 부분은 AppDelegate, SceneDelegate 에대한 이해도가 없어..어디에 위치하여야 할지 알수없어 Controller 로 옮겨 두었었습니다!
- 아직 이해도가 부족하지만 모델에 위치하는것이 더 적합해 보입니다!

+/- 버튼을 누르면 최종 결과에서 바뀌는 것이 아닌 마지막에 연산자 뒤에 입력한 숫자가 바뀌었습니다. 예를 들면 85+3 = 을 해서 88 이 나왔을 때 +/- 를 누르면 -88 이 될 것이 예상되었는데 -3 이 나왔습니다.
- 네! 맞습니다! 이부분을 아직 수정하지 못했습니다!
- 연산후 결과값을 어떻게 활용할것인지 구현하지 않아 의도한 바와 다르게 작동되고 있습니다! 
- 수정해두도록 하겠습니다!
- 
뷰컨트롤러가 다소 길었습니다. 연산 관련된 메소드는 따로 객체를 만들어 그 객체에 메소드로 메시지를 보내고 결과 값만 받아와서 뷰컨트롤러에서 뿌려주기만 하면 뷰컨트롤러의 코드 양이 줄어들 수 있을 것 같습니다.

- 그렇군요! 적용 해보도록 하겠습니다!
- 안그래도 뷰컨트롤러의 크기가 너무 큰것같아 어떻게 해야 덩치를 줄일수 있을지 고민 하였습니다 ㅠ

2022-03-29 09:02 UTC, merged