계산기 [Step3] Taeangel
yagom-academy/ios-calculator-app pull request #210
Opened 2022-03-25 12:09 UTC by Taeangel

안녕하세요 라자냐 
@wonhee009

PR이 많이 늦었습니다 죄송합니다. 

- 궁금한점 
---
```swift
if visibleNumber.first == "0" && visibleNumber.contains(Asset.dot) == false {
  visibleNumber.removeAll()
  visibleNumber.append(inputString)
```
```swift
if visibleNumber != Asset.blank {
  fomula += visibleNumber
  fomula += Asset.spacing
  }
```
상수를 Asset에서 관리하였는데 이 두 부분에서 한 코드에서는 Asset을 사용가능하고 다른 한 코드에서는 사용이 불가능 합니다 이 차이가 궁금합니다.

- 고민한점
---
ViewController에서 너무많은 일을 해주는 것이 아닌가 고민입니다. 

에러처리를 일일이 조건문으로 처리하다보니 코드가 난해해 지는것이 고민입니다.

- 해결하지 못한것
---
1. mvc방식으로 관리를 하지 못하였습니다. ViewController 에서는 view관리만 해주고 model을 따로 만들어서 관리를 해주었어야 하는데 model은 존재하지 않고 View에서 view와 model을 한번에 관리합니다. 

2. numberFomatter를 관리를 잘하지 못하여 소숫점에 0을 입력하면 화면에서 표시해주지 못합니다. ex)`2.000000`

3. 중간에 commit이 꼬여서 커밋을 하면서 하고 있는줄 알고 있었는데 commit이 제대로 되지 않았습니다. 중간에 한번에 많이 commit이 되었습니다. 

4. -0 X 0 을 하면 -0이 결과값으로 반영됩니다.

2022-03-27 02:38 UTC, wonhee009 requested changes

2022-03-27 02:38 UTC, wonhee009 commented on Calculator/Calculator/Model/Util/Asset/Asset.swift
> +}
`Asset`이란 네이밍이 엑코에서 사용하는 이미지 에셋과 혼동이 있을거 같습니다.
또한, 안의 프로퍼티들을 확인해보니 다양한 타입들(에러, UI 요소 등...)이 혼재되어 있는거 같은데요. 이 부분들 분리해서 관리하는 것도 좋을거 같습니다.

2022-03-27 02:38 UTC, wonhee009 commented on Calculator/Calculator/ViewController/ViewController.swift
> +      guard doubleNumber != nil else {
```suggestion
     guard let doubleNumber = Double(visibleNumber) else {
```

2022-03-27 02:38 UTC, wonhee009 commented on Calculator/Calculator/ViewController/ViewController.swift
> +      self.numberLabel.text = makeformatter().string(for: doubleNumber)
해당 부분들 메서드로 분리해서 메서드를 호출해주는건 어떨까요?

2022-03-30 13:51 UTC, Taeangel commented on Calculator/Calculator/ViewController/ViewController.swift
> +      self.numberLabel.text = makeformatter().string(for: doubleNumber)
`convertNumberLabelToformatter()`로 분리하였습니다

2022-03-30 13:51 UTC, Taeangel commented on Calculator/Calculator/ViewController/ViewController.swift
> +      guard doubleNumber != nil else {
```swift
 guard let doubleNumber = Double(visibleNumber) else {
      return
    }
```
이와 같이 변경 하였습니다.

2022-03-30 13:53 UTC, Taeangel commented on Calculator/Calculator/Model/Util/Asset/Asset.swift
> +}
SimpleValue로 네이밍을 변경하였고 에러는 따로 열거형을 만들었습니다.   `static let staticViewSpacing = 10.0`
`static let maximum20Digits = 20` 이 두가지는 따로 열거형을 만들지 않고 바로 넣어주었습니다.

2022-05-23 00:21 UTC, closed without merging