계산기 II [STEP 1] Doogie, Onetool, Taeangel
yagom-academy/ios-calculator-app pull request #222
Opened 2022-03-29 12:09 UTC by kimt4580

안녕하세요 라자냐! @wonhee009 
STEP 1 PR 요청드립니다!
좋은 피드백 부탁드립니다! 🥹

### Refactoring
-  코드를 합치면서 생긴 문제점들이 많았습니다.
  - queue 구현 방식이 상이하여, 수정하였습니다.

  - mutating 선언으로 수정하였습니다.

  - result 함수의 error 반환 타입으로 인하여 변경 사항을 수정하였습니다.

2022-03-30 02:13 UTC, wonhee009 requested changes
스텝1 수고하셨습니다! 🎉 
서로 다르게 구현되어 있다보니 서로의 코드를 이해하고 수정하면서 합치는 과정이 재밌으셨을까요 😄
코드에 몇몇 코멘트 남겨두었으니 확인 부탁드립니다 🙏

- 9를 계속해서 누르면 아래와 같이 나오는데 확인 부탁드립니다.
<img src="https://user-images.githubusercontent.com/30456206/160729796-c9fbaefe-0aaf-4822-be00-ddecdab06d41.png" width="20%"> 
 
- 메서드의 순서도 개발자의 의도를 드러낸다고 생각합니다. 현재는 어떤 view를 만드는 메서드와 로직을 위한 메서드들이 섞여있는 느낌으로 코드를 쭉 읽는게 조금 힘들었는데요. 팀원들과 상의하여 어떤 순서로 메서드들을 배치하는게 잘 읽힐지 한 번 얘기해보는 것도 좋을거 같습니다. (저는 전반적으로 view를 초기 세팅하는 메서드들 -> 로직을 위한 메서드들 순서로 놓기도 하고 해당 VC의 핵심 기능이 아니라면 extension으로 분리하기도 합니다.)

- 1개의 메서드는 1개의 역할을 하도록 하는게 좋습니다. 메서드들을 전반적으로 살펴보고 하나의 역할을 하고 있는지 한 번 보는 것도 좋을거 같습니다!

- 메서드에 조건문이 많이 뭉쳐 있는거 같은데요. 공통화할 수 있다면 하나의 메서드로 분리해도 좋을거 같고, 그게 아니라면 꼭 필요한 조건인지 생각해 보시고 코드가 좀 더 다듬어졌으면 좋겠습니다.

- CalculateItem이라는 프로토콜을 만들었는데 해당 프로토콜을 활용할 수 있는 방법이 있을까요?

2022-03-30 02:13 UTC, wonhee009 commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
해당 조건은 어떤 경우인가요?

2022-03-31 03:00 UTC, doogie97 commented on Calculator/Calculator/Model/Fomula.swift
> +struct Fomula {
맞습니다 전체 적으로 오타가 있어 수정했습니다!

2022-03-31 03:21 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
연산자를 눌렀을 때도 리스트에 추가가 돼야한다고 요구서에서 확인했는데 어떤 의미로 = 만눌렀을 때 추가가 되기를 제안하신건지 궁금합니다

2022-03-31 03:26 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.listScrollView.scrollToBottom()
addFormula와는 분리하는게 맞다고 생각해 분리 하였습니다

2022-03-31 03:31 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
customView의 경우 차 후 각자 공부해보기로 하였으며 이번 프로젝트에서는 extension으로 분리는 것으로 진행했습니다

2022-03-31 03:32 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        return Double(number.replacingOccurrences(of: ",", with: "")) ?? 0
, 를 직접 입력하는 경우는 없지만 label에서 숫자를 가져와서 쓰다보니 5,303 이런식으로 ,가 포함되어있는 숫자는 Double로 변환시 nil로 반환이 되어서 숫자를 4자리 이상 입력할 수 없는 상황이 생겼었습니다.
그래서 ,를 없애주는 작업을 했습니다

2022-03-31 04:00 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        if changedNumber == "-0" { return stringZero}
guard let구문같은 경우에는 double을 받아 설정한 조건의 number format으로 변환해주는 작업이라고 생각하는데 혹시 아니라고 생각하신 이유가 어떤 이유일까요??
아울러, if구문의 경우는 해당 함수에 맞는 기능은 아닌 것 같아 수정하였습니다

2022-03-31 04:01 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
.뒤에 0을 누를 경우 numberformatter를 거치면서 .0이 사라지는 현상이 있었습니다(아마 .0은 필요 없는 숫자니까 반영을 해주지 않는 것 같습니다) 
그래서 소수점 뒤에 0을 추가할 때 numberformatter를 거치지 않고 바로 label에 반영할 수 있게 체크하는 함수 입니다

2022-03-31 04:51 UTC, wonhee009 commented on Calculator/Calculator/Controller/ViewController.swift
> +        return changeNumberFormat(number: number)
Format을 바꿔주는 메서드로 보이는데요.
`checkZeroAfterDot`의 역할이 맞을까요?

2022-03-31 04:51 UTC, wonhee009 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
`addFormula`라는 메서드와 `리스트의 추가`는 다른 역할이라고 생각했는데요.
연산자를 눌렀을때 리스트를 추가하는건 명세서 확인했습니다.
`formulaToSend`에 formula를 추가하는 부분은 =을 눌렀을때 하는게 맞지 않나 생각이 들었습니다.
`formulaToSend`에 formula를 추가하는 이유가 계산하기 위해서인데요. 실질적으로 계산이 이뤄지는 시점이 =을 누르는 시점이라고 생각했습니다.

2022-03-31 04:58 UTC, wonhee009 commented on Calculator/Calculator/Controller/ViewController.swift
> +        let doubleNumber = Double(number.replacingOccurrences(of: ",", with: "")) ?? 0
파라미터명을 numberString인 것도 나쁘지 않을거 같습니다.
`changeToDouble`같은 경우는 String extension으로 이동하는게 좀 더 역할이 맞지 않나 생각이 듭니다.
또한 ,을 제외하는 부분도 String extension으로 따로 빼는게 좋을거 같습니다.

2022-03-31 05:02 UTC, wonhee009 commented on Calculator/Calculator/Controller/ViewController.swift
> +        if changedNumber == "-0" { return stringZero}
```swift
  if changedNumber == "-0" { return stringZero}
```
해당 조건에 관한 얘기였습니다.
validation하는 부분이라고 생각해 가장 상단의 조건이지 않나 생각했습니다.

2022-03-31 07:46 UTC, doogie97 commented
1. 메서드의 순서
- 현재의 상태는 IBAction끼리 모아 놓고, function끼리 모아놓고, 그 밑에 extenstion을 통해 view를 구성하는 메서드들 위해 배치해 놓았습니다. 그런데 이렇게 배치 하는 것 보다 IBAction과 function을 가리지 로직을 위한 순서대로 배치하는 것이 좋은 것인지 여쭤보고 싶습니다!

2. 1개의 메서드 1개의 역할
- 최대한 기능분리를 위해 수정해보기는 했는데 현재 코드에서 어떤 부분이 더 분리가 되면 좋을지 조언을 받고 싶습니다!

3. CalculateItem이라는 프로토콜은 연산자와 더블을 묶어주는 공통점을 만들어주는 역할로만 생각을 했는데 어떻게 사용하면 좋을 지 감이 잡히질 않습니다... 라자냐의 생각은 어떤지 여쭤보고 싶습니다!

2022-04-01 02:24 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        if changedNumber == "-0" { return stringZero}
라자냐의 말대로 `changeNumberFormat()` 호출 전에 계산 결과인 result를 판단하는게 맞다고 생각이 들어 검증 시점을 변경하였습니다

2022-04-01 02:32 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        return changeNumberFormat(number: number)
`checkZeroAfterDot` 은 `changeNumberFormat`을 호출 하기 전에 소수점 뒤에 0을 정상적으로 넣어주기 위해 check하는 함수인데 이를 format을 바꿔는 상황에 사용하게 된다면 코드를 이해하는데 어려움이 있을 것 같습니다.
그래서 dot뒤에 zero가 있는지 판단하는 조건문을 `changeNumberFormat` 상단에 추가해서 .뒤에 0이 있다면 들어온 값을 그대로 리턴해주는 형식으로 변경하였습니다

2022-04-01 02:58 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        let doubleNumber = Double(number.replacingOccurrences(of: ",", with: "")) ?? 0
`changeToDouble` 뿐만 아니라 특정 string을 제외하는 기능 또한 String extenstion으로 따로 빼주어 구현하였습니다

2022-04-01 07:01 UTC, doogie97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
라자냐 말씀 대로 연산자 누를 때는 리스트에 연산자와 숫자가 올라가게만 처리했고 =을 눌렀을 때 리스트에 있는 text를 전달 해 주는 방식으로 수정하였습니다!

2022-04-01 08:11 UTC, wonhee009 approved these changes
스텝1 수고하셨습니다! 🙏

2022-04-01 08:11 UTC, merged