계산기 II [STEP 2] Lingo, mmim
yagom-academy/ios-calculator-app pull request #225
Opened 2022-03-30 12:35 UTC by llingo

@lina0322 
안녕하세요 엘림 👑
계산기 II [STEP 2] PR 보냅니다. 잘 부탁드립니다!

### To. 엘림

엘림! 저희 팀은 코드를 합치는 과정에서 리팩토링을 함께 진행해버렸습니다 😭 
그래서 STEP2에서 리팩토링한 게 테스트 코드 수정과 테스트 과정에서 생기는 오류 fix가 전부입니다 😭 

---

## UML
![계산기 II](https://user-images.githubusercontent.com/94151993/160551272-085dad6c-3a19-46d9-b5f0-6e16d57367fd.png)

---

### 고민 및 해결한 점

1️⃣ 코드를 합치는 과정에서 서로간의 코드가 충돌이 나는 경우도 있었지만, 수월하게 합쳐지는 경우도 많았습니다. 이것을 통해 다시 한번 객체지향 프로그램의 중요성을 깨달았습니다. 객체가 다른 객체를 의존하지 않고 역할과 책임을 다했기 때문에 합치는 과정에서 충돌이 없었다고 생각합니다! 

> 얼마나 객체끼리 의존하지 않고 있고, 객체가 역할과 책임에 충실하고 있는지를 파악해볼 수 있었습니다. 
역시 야곰의 큰그림 👍 👑

2️⃣ UML의 중요성

계산기 I 프로젝트의 STEP 2에서 주어진 UML을 각자 구현했었습니다. 계산기 II에서 팀원과 코드를 합칠 때 충돌이 적게나는 것을 느꼈고 이를 통해 **UML 설계의 중요성**을 깨달을 수 있었습니다.

3️⃣ 사전에 합의된 패턴의 중요성

`mmim`은 MVC패턴을 적용했고 `lingo`는 테스트를 위해 MVVM, 옵저버 패턴을 적용했습니다. 코드를 합치는 과정에서 서로 다른 패턴으로 구현되어있었고 그 과정에서 구조상의 충돌이 있었습니다. 
따라서, 설계하기전에 사전 합의된 패턴 사용의 중요성을 깨달을 수 있었습니다. 😅

### 궁금한 점

```swift
func addOperator(of operatorString: String) -> Bool {
    guard self.operandValue.value != "nan",
          self.operandValue.value != "0" || self.operatorType.value != nil
    else {
      return false
    }
    self.isResult = false
    if self.operandValue.value == "0" && self.operatorType.value != nil {
      self.operatorType.next(operatorString)
      return false
    }
    if let operatorType = self.operatorType.value {
      self.formulas.append(operatorType)
    }
    self.formulas.append(self.operandValue.value)
    self.operatorType.next(operatorString)
    self.operandValue.next("0")
    return true
}
```

저희 코드에서 대표적으로 guard문과 if문이 많은 메서드 중 하나입니다. 많은 조건들을 제어하기 위한 어쩔수 없는 선택이었다고 생각합니다. `early exit`의 같은 경우는 guard문을 사용하고 맨 위로, 나머지 조건들은 if문으로 아래쪽에 배치했습니다. 궁금한 점은 이런 경우 더 좋은 방법이 있을까요? 조언을 얻고 싶습니다.😭🙏

2022-03-31 15:23 UTC, lina0322 requested changes
안녕하세요, 두 분!!

진행 속도가 상당히 빠르네요👍
코멘트 달아두었으니까 확인 해주시고요! 

수정 혹은 더 디벨롭 했으면 하는 부분 적어드릴게요~

1. 동작 중 간혹 scrollView 가려질 때 있는 것 같습니다🙏
![IMG_0009](https://user-images.githubusercontent.com/49546979/161090251-4610051c-206e-4b13-9db0-598c3e1ab0ac.jpeg)

2. 코드 커버리지 확인 하는 방법 아시나요?ㅎㅎ 좀 더 커버리지를 늘릴 수 있는 방법이 있나요?
(물론 우리의 목표는 100% 만드는 것은 아니지만, 우리에겐 시간이 많이 남았으니까~~)
![스크린샷 2022-04-01 오전 12 16 06](https://user-images.githubusercontent.com/49546979/161090260-fee79618-8f87-4364-8f50-a4b0930095ec.png)

3. 아이폰 계산기는 버튼이 동그랗던데요?!ㅎㅎ 요거 가능할까요?

4. 현재 여러분의 코드 리팩토링 정도에 만족하고 계신가요? 더 디벨롭 할 건 정말 없나요??😀

2022-03-31 15:23 UTC, lina0322 commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    XCTAssertThrowsError(try expressionParser.result())
XCTAssertThrowsError 테스트 좋습니다~!

2022-04-01 09:29 UTC, JoSH0318 commented on Calculator/Calculator/Presentation/CalculatorViewModel.swift
> -    if self.operandValue.value == "0" && self.operatorType.value == nil {
name space를 만들어서 정리할 수 있을 것 같습니다. ㅎㅎ 이러한 방향으로 수정했습니다!

2022-04-01 09:37 UTC, llingo commented
> 1. 동작 중 간혹 scrollView 가려질 때 있는 것 같습니다🙏

scrollToBottom() 함수에 `self.contentInset.bottom`을 추가해서 해결했습니다.

> 2. 코드 커버리지 확인 하는 방법 아시나요?ㅎㅎ 좀 더 커버리지를 늘릴 수 있는 방법이 있나요?

Scheme 편집에 들어가서 테스트 커버리지 설정을 할 수 있었습니다! 테스트코드를 추가해서 커버리지를 늘렸습니다.

> 3. 아이폰 계산기는 버튼이 동그랗던데요?!ㅎㅎ 요거 가능할까요?

버튼에 CornerRadius을 주고 폰트의 크기와 스타일을 아래와 같이 변경했습니다.

<img width="400px" src="https://user-images.githubusercontent.com/94151993/161236905-5579839f-757e-4605-aefd-073adaa2c83e.png"/>

> 4. 현재 여러분의 코드 리팩토링 정도에 만족하고 계신가요? 더 디벨롭 할 건 정말 없나요??

몇가지 오류가 더 있었고 리팩토링을 진행했습니다. 추가적으로 하드코딩된 상수 값들을 네임스페이스를 생성해서 분리했습니다.

혹시, 좀 더 개선해야할 부분이 있다면 코멘트 부탁드립니다 🙏 👑

2022-04-04 01:34 UTC, lina0322 approved these changes

2022-04-04 01:34 UTC, merged