[Step1] - Steven, SJ, Kio
yagom-academy/ios-calculator-app pull request #23
Opened 2021-03-31 07:49 UTC by Kioding

@corykim0829

Cory! 첫 PR을 드디어... 보냅니다 🤗  

[계산기 프로젝트 요구사항](https://www.notion.so/3ca7a37080284edf86d3baf8630bfead)

### 구현 된 부분

- 스토리보드
    - 저번 주 목요일 Cory의 동의를 얻어서 간단하게 버튼을 만들어 보고 테스트를 하면서 구현했습니다.
    - 아이폰 11 기준으로 했고 오토레이아웃은 안했습니다.
    - `10/2` 버튼 클릭시 버튼의 view가 바뀝니다.
- 지금 step1에서 요구한 계산기에 공통된 부분을 빼라는 것은 하지 않았습니다.(extension, protocol 미구현)
- 기능에 충실하다 보니 설계 부분에서 미흡했습니다.
- 아직 변수 함수 이름도 완벽하지 않고 옵셔널은 강제추출한 부분들도 있습니다.
- 저번주에 솔리드를 배워서 적용해보고 싶었으나 하지 못했고 10진수 2진수 각각 클래스를 만들어서 모든 기능을 넣어줬습니다.

- 10진수 계산기
    - 최대한 아이폰 계산기와 비슷하게 구현했습니다.
    - 사칙연산(+, -, /, *) 우선순위에 따른 연산이 가능합니다.

        ```swift
        // 계산기 상황별 예시
        4 x 3 + → 12
        5 x 6 x → 30
        5 + 6 + → 11
        5 + 6 x 10 x → 60
        5 + 6 x 10 + → 65
        ```

    - 정수부와 실수부를 포함해서 숫자가 9개까지만 입력되게 구현했습니다.
    - 정수끼리 실수끼리 정수와 실수끼리 계산을 했을 때 잘 출력이 됩니다. (10.0 → 10)
    - 3자리 숫자마다 콤마가 찍히게 구현했습니다(1,234,567)
    - 점을 여러번 눌렀을 때도 한번만 출력 되게 했습니다(1.2.3. → X)

- 2진수 계산기
    - 2개의 수와 한개의 연산자가를 입력후 `=` 을 눌렀을 때만 결과 값을 볼 수 있습니다.
    - 아직 라벨에는 출력하지 않고 print 로 출력해 보았습니다.
    - AND, NAND, OR, NOR, XOR: 두 수의 비트에 대한 연산가능
    - NOT, Bit Shift: 현재수 연산

### 구현 못한 부분 & 미흡한 부분

- 10진수 계산기
    - `=` 으르 계속 눌렀을때 마지막 피연산자와 연산자가 적용되어서 연산하는 기능은 구현하지 못했습니다.
    - 마지막 입력이 연산자이고 그 다음 `=` 을 눌렀을 때도 나오는 결과는 구현하지 못했습니다.
        - `5+` 을 입력하고 `=` 을 계속 눌렀을 때 마지막 결과에 5가 더해져서 나옵니다.(5 10 15 20 ...)
- 2진수 계산기
    - 모든 피연산자와 연산자를 입력받아서 처리하는 것과 10진수 계산기 처럼 연산자를 클릭 할때 마다 결과값이 연산자 우선 순위에 따라서 출력되게 하는 것 중 한가지라도 구현하려고 했는데 하지 못했습니다.
- 공통기능 수행하는 protocol 미구현

### **조언을 얻고 싶은 부분 & 궁금한 점**

- 초기 설계할 때 UML을 짜야하는데, 어떻게 접근해야 할지 감이 잡히지 않아 일단 시작해보자고 생각하였습니다. 그 결과, 지금은 코드만으로 이루어진 상태인데, 코드 없는 상태에서 UML을 짜려고 할 때 어떤 점을 고려해야 좋을까요? Cory는 어떤 식으로 주로 생각을 하는지 궁금합니다.
- 지금 시간이 없어서 step1도 미완성이 상태에서 pr를 보내는데.. 앞으로 남은 시간을 어떻게 보내면 좋을지...
    - 월요일에 TDD를 배우고 내일 오토레아아웃을 배우는데 이부분을 더 공부할지 아니면 step1을 요구사항에 맞게 더 구조화 된 코드를 작성해야 될지 고민입니다..
- 2진 계산기에서 9자리 제한을 고민할 때 Uint8, Uint16에서 고민하다가 결국은 8자리의 숫자만 표시하는 형태로 하였는데 Int 타입으로 구현하여 9자리까지만 보여주는 게 나은 방법일지 궁금합니다.
- NumberFormatter()를 extension하여 전역 프로퍼티처럼 사용할수 있는 방법이 있는지 궁금합니다.

2021-04-01 04:46 UTC, corykim0829 requested changes
정말정말 고생 많이하셨습니다!! 👍👍👍👍
고민을 많이 한 흔적들이 보이네요! 올려주신 질문에 대한 답변들을 아래 남겨두었어요.
피드백 반영하시면서 진행하시면 될 것 같네요 ㅎㅎ

- 초기 설계할 때 UML을 짜야하는데, 어떻게 접근해야 할지 감이 잡히지 않아 일단 시작해보자고 생각하였습니다. 그 결과, 지금은 코드만으로 이루어진 상태인데, 코드 없는 상태에서 UML을 짜려고 할 때 어떤 점을 고려해야 좋을까요? Cory는 어떤 식으로 주로 생각을 하는지 궁금합니다.
➡️ 전체적인 로직을 맡을 클래스와 일을 맡겨줄 하위 클래스를 생각하는게 좋습니다. 이번에는 계산기 객체가 조금 특이한 케이스라서 UML을 짜는게 쉽지는 않았을 것 같네요!

- 지금 시간이 없어서 step1도 미완성이 상태에서 pr를 보내는데.. 앞으로 남은 시간을 어떻게 보내면 좋을지...
➡️ 일단은 피드백 반영해주시고, 지금 receiveInput 함수가 너무 많은 일을 하고 있으니 이를 분리시키고 들여쓰기를 낮춰보는 작업을 해봐요!
 
- 월요일에 TDD를 배우고 내일 오토레아아웃을 배우는데 이부분을 더 공부할지 아니면 step1을 요구사항에 맞게 더 구조화 된 코드를 작성해야 될지 고민입니다..
➡️ 피드백 반영하면서 TDD를 해보고 시간이 남으면 오토레이아웃을 해보는건 어떨까요?

- 2진 계산기에서 9자리 제한을 고민할 때 Uint8, Uint16에서 고민하다가 결국은 8자리의 숫자만 표시하는 형태로 하였는데 Int 타입으로 구현하여 9자리까지만 보여주는 게 나은 방법일지 궁금합니다.
➡️ 여유가 있으면 자리수를 늘려보는게 좋을 것 같네요 ㅎ

- NumberFormatter()를 extension하여 전역 프로퍼티처럼 사용할수 있는 방법이 있는지 궁금합니다.
➡️ 이 부분은 피드백에 남겨드렸어요!

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +class DemicalCalculator {
decimal 오타 같네요! 수정해주세요 :)

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +//  DimecalCalcultor.swift
decimal 오타 같네요! 수정해주세요 :)

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +struct Stack<T> {
스택 구조체 구현은 다른 파일로 분리하는게 어떨까요?

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/ViewController.swift
> +            calculator.receiveInput(buttonType: String(num9.tag))
버튼에 tag로 숫자값을 넣어놓았다면, 이 친구들은 switch문으로 처리해주지 않아도 되지 않나요?

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/ViewController.swift
> +extension UIButton {
extension을 사용했군요! 👏👏👏
extension도 따로 파일로 분리하는 게 좋습니다.

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +    func receiveInput(buttonType: String) {
이 함수를 사용하는 걸 보면
`calculator.receiveInput(buttonType: String(button.tag))`
이런 방식으로 사용하게 되는데 조금 어색하네요!
`calculator.input(~~)` 더 간결한 느낌으로 가면 좋을 것 같아요!
그리고 파라미터로 buttonType을 받는데 String을 받고 있어서 어색한 느낌이에요! 파라미터명을 수정하거나 다른 타입을 받는게 맞는 것 같네요 😀

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +                print(tempNumber)
print문은 최종 프로덕트 파일에는 사용하지 않는게 좋습니다!

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +    let numberFormatter = NumberFormatter()
NumberFormatter를 String에 extension으로 확장해보세요! 그럼 조금 더 깔끔하게 확장될 거에요 ㅎ
NumberFormatter 자체를 확장하는게 아니라 현재 String에 formatter를 적용하는 거니까 String에 확장해야 해요.

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +                        calculateUntilSatisfiedCondition()
이 함수명의 의미가 while문을 벗어날 때 까지 계산하라는 의미인가요? 👀

2021-04-01 04:46 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +            case "=":
가장 마지막 operator와 operand를 따로 저장해놓으면 =을 계속 눌렀을 때도 처리해줄 수 있지 않을까요? 👀

2021-04-01 07:17 UTC, Kioding commented on Calculator/Calculator/DimecalCalcultor.swift
> +class DemicalCalculator {
오타부분 수정하였습니다 😃

2021-04-01 07:35 UTC, Kioding commented on Calculator/Calculator/DimecalCalcultor.swift
> +struct Stack<T> {
새로운 파일로 분리했습니다 ☺️

2021-04-01 11:09 UTC, stevenkim18 commented on Calculator/Calculator/DimecalCalcultor.swift
> +class DemicalCalculator {
수정했습니다^^

2021-04-01 11:09 UTC, stevenkim18 commented on Calculator/Calculator/DimecalCalcultor.swift
> +//  DimecalCalcultor.swift
앗 이것도 같이 수정했습니다!

2021-04-01 11:10 UTC, stevenkim18 commented on Calculator/Calculator/DimecalCalcultor.swift
> +struct Stack<T> {
스택 파일도 따로 분리했어요!

2021-04-01 11:10 UTC, stevenkim18 commented on Calculator/Calculator/ViewController.swift
> +            calculator.receiveInput(buttonType: String(num9.tag))
아 이 부분은 모든 버튼 별로 액션을 만들어서 처리했어요!

2021-04-01 11:11 UTC, stevenkim18 commented on Calculator/Calculator/ViewController.swift
> +extension UIButton {
오늘 오토레이아웃에서 커스텀 버튼을 만드는 것을 배워서 그렇게 만들고 따로 파일을 분리헀어요!

2021-04-01 11:11 UTC, stevenkim18 commented on Calculator/Calculator/DimecalCalcultor.swift
> +                print(tempNumber)
10진수 부분은 실수로 들어갔네요! 제출전에 한번 더 확인하겠습니다.

2021-04-01 11:39 UTC, stevenkim18 commented on Calculator/Calculator/DimecalCalcultor.swift
> +                        calculateUntilSatisfiedCondition()
함수 이름을 calculate()로 바꿨습니다. 함수명이 직관적이지 않았나요?

2021-04-02 01:44 UTC, Kioding commented on Calculator/Calculator/DimecalCalcultor.swift
> +    func receiveInput(buttonType: String) {
메서드 명을 inputMathematicsSign으로 바꾸고, 파라미터명은 String값을 받는 것을 고려하여 buttonText로 변경하였습니다😀

2021-04-02 01:55 UTC, Kioding commented on Calculator/Calculator/DimecalCalcultor.swift
> +    let numberFormatter = NumberFormatter()
```swift
extension Double {
    func applyNumberFormatter()-> String {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        numberFormatter.maximumSignificantDigits = 9
        return numberFormatter.string(for: self)!
    }
}
```

Double에 extension으로 확장해보았습니다!

2021-04-02 02:08 UTC, Kioding commented
@corykim0829

`=` 에 대한 내용은 빼고 코멘트 주신 내용 수정해보았습니답!

2021-04-02 03:44 UTC, corykim0829 commented on Calculator/Calculator/DimecalCalcultor.swift
> +                        calculateUntilSatisfiedCondition()
메소드 명만 보고 어떤 동작을 하는지 파악하는게 아니라 메소드 주변의 while문을 봐야 이해가 되는 것 같아서요!
calculate라고만 해도 깔끔한 것 같습니다! 👍👍👍

2021-04-03 06:01 UTC, corykim0829 approved these changes
수고 많으셨습니다 😀😀😀😀

2021-04-03 06:01 UTC, merged