계산기 [STEP 1] 나이든별
yagom-academy/ios-calculator-app pull request #231
Opened 2022-05-16 23:27 UTC by OldStarKR

@protocorn93 안녕하세요 콘~ 첫 번째 PR입니다! 잘 부탁드리겠습니다.

---

## UML
![계산기 큐와 리스트](https://user-images.githubusercontent.com/102375432/168696695-1f0b5ec2-0d34-4beb-8b36-c0e5256af678.png)

---

## STEP 1 작업한 내용
* `Queue` 프로토콜을 구현했습니다.
    * 기능은 큐가 비었는지 검사하는 `isEmpty`, 첫 원소를 볼 수 있는 `peek`, 큐에 원소를 더하는 `enqueue`, 큐에서 원소를 빼는 `dequeue`를 지정했습니다.
* `CalculateItem` 프로토콜을 정의했습니다 - 아직은 비어 있습니다.
* `Queue` 프로토콜에 부합하는, `CalculatorItemQueue` 구조체를 만들었습니다.
    * 내부에서는 배열을 사용해 만들었으며, 들어가는 원소가 `CalculateItem` 프로토콜에 부합하도록 했습니다.
 
---

## STEP 1 고민한 점
* 큐와 리스트의 구현에 관해, [이 책](https://www.raywenderlich.com/books/data-structures-algorithms-in-swift)을 참고했습니다.
* 다만 연결 리스트에 관해 아직 잘 알지 못한다고 생각하기 때문에, 일단 배열로 구현했습니다.
    * `Collections` 프로토콜의 적용, COW를 통한 Value Semantic 확보, `isKnownUniquelyReferenced(_:)`에 관해 이해하기 위해 더 공부하고 있습니다.

---

## STEP 1  조언을 얻고 싶은 점
* 큐 자료구조를 구현할 때, 타입 메서드에 대해서도 TDD 방법론을 적용했습니다. 이렇게 하는 것이 맞는지 궁금합니다.
* 처음에 큐에 대해서만 테스트 코드를 짤 때는, Int 자료형을 대표로 삼아 테스트를 진행했습니다. 하지만 이후 `CalculatorItemQueue`의 원소가 `CalculateItem`에 conform하게 만드는 과정에서, 기존의 테스트 코드들이 빌드되지 않는 상황이 발생했습니다. 임시방편으로 `CalculateItem` 프로토콜에 conform하는 `CalculateItemTester`라는 임시 타입을 만들어 테스트 코드를 수정해 주었고, 잘 작동했습니다. 기존의 테스트로 인해 이미 신뢰성이 확보된 자료구조여도, 이렇게 조건이 바뀌면 다시 테스트해야 하는지, 그 과정에서 오로지 테스트 코드의 작동만을 위해 이렇게 임시로 자료형을 만들어서 사용하는 것이 온당한 방법인지 궁금합니다.
* `enqueue` 메서드를 테스트할 때, 큐 내부의 배열은 `private`해서, 당장 메서드가 성공했다고 해도 확인할 방법이 없었습니다. 그래서 이전의 테스트에서 이미 검증된 `dequeue` 메서드를 사용해서, `enqueue`로 넣은 값이 나올 때까지 큐에서 값을 빼 주었습니다. 그런데 각각의 테스트 케이스는 독립적이어야 한다고 알고 있습니다. 이 경우 어떻게 테스트를 진행하면 좋을지 궁금합니다.

2022-05-17 13:08 UTC, protocorn93 requested changes
@OldStarKR 수고하셨어요! 아직은 많은 기능은 없지만 첨부해주신 UML과 가독성 높은 코드로 리뷰를 하는데 어렵지 않았어요! 👍

## 조언을 얻고 싶은 점 

> 큐 자료구조를 구현할 때, 타입 메서드에 대해서도 TDD 방법론을 적용했습니다. 이렇게 하는 것이 맞는지 궁금합니다

잘하시고 계신 것 같아요! 다만 아직은 연습이기에 TDD의 과정을 모두 커밋을 하고 계시지만 익숙해지시면 하나의 사이클(red-blue-green)을 하나의 커밋으로 하셔도 무방합니다. 

> 처음에 큐에 대해서만 테스트 코드를 짤 때는, Int 자료형을 대표로 삼아 테스트를 진행했습니다. 하지만 이후 CalculatorItemQueue의 원소가 CalculateItem에 conform하게 만드는 과정에서, 기존의 테스트 코드들이 빌드되지 않는 상황이 발생했습니다. 임시방편으로 CalculateItem 프로토콜에 conform하는 CalculateItemTester라는 임시 타입을 만들어 테스트 코드를 수정해 주었고, 잘 작동했습니다. 기존의 테스트로 인해 이미 신뢰성이 확보된 자료구조여도, 이렇게 조건이 바뀌면 다시 테스트해야 하는지, 그 과정에서 오로지 테스트 코드의 작동만을 위해 이렇게 임시로 자료형을 만들어서 사용하는 것이 온당한 방법인지 궁금합니다.

네네 그럼요. 이후 프로젝트를 진행하면서도 비슷한 상황을 겪게 되실 것이지만 우리가 의존성을 주입할 때 concrete 타입을 전달하지는 않아요. 유연성과 단위 테스트 코드 작성을 용이하게 하기 위해 프로토콜을 넘기죠! 그리고 테스트 코드를 작성할 때 해당 프로토콜을 따르는 mock 객체를 만들어서 테스트 코드를 작성하곤해요. 

현재 상황도 비슷하다고 볼 수 있어요. 단위 테스트 코드를 작성하시면서. `CalculateItem` 프로토콜을 따르는 임의의 객체를 정의하고 이를 이용해 테스트해볼 수 있죠. 다만 이는 Test Doubles의 성격으로 Unit Test 타겟 안에 위치시키는게 바람직해요. 

Test Double에 대해서도 시간이 나시면 학습해보시는걸 권장합니다. 

> enqueue 메서드를 테스트할 때, 큐 내부의 배열은 private해서, 당장 메서드가 성공했다고 해도 확인할 방법이 없었습니다. 그래서 이전의 테스트에서 이미 검증된 dequeue 메서드를 사용해서, enqueue로 넣은 값이 나올 때까지 큐에서 값을 빼 주었습니다. 그런데 각각의 테스트 케이스는 독립적이어야 한다고 알고 있습니다. 이 경우 어떻게 테스트를 진행하면 좋을지 궁금합니다.

테스트가 독립적이어야 한다는 것이 하나의 메서드만 사용해서 검증을 해야한다는 것은 아니에요. 하나의 메서드를 테스트할 수도 있고 하나의 기능의 흐름을 테스트할 수도 있어요. `dequeue`가 테스트를 통해 검증이 되었다면 이를 이용해 `enqueue`를 테스트할 수 있겠죠! 

`enqueue`를 테스트하기 위해 `private` 접근제어자를 제거하는건 옳지 않아요! 우리는 결국 input 대비 output을 검증하는 것이기에 현재 @OldStarKR 가 작성해준 방법이 옳습니다! 

---

## 추가로 말씀드리고 싶은 부분 

커밋 로그가 좀 더 정리가 되면 좋을 것 같아요. 개행을 지운 커밋 등 제가 느끼기엔 리뷰하는데 조금은 불편을 야기할 수 있는 커밋들이 보이긴했어요! 

작업을 하시면서 이러한 커밋들이 존재하는 것은 괜찮으나 PR을 올리기전(remote에 올리기전)에는 interactive rebase를 활용해서 한번 정리해보시는 것도 좋은 습관이 될 수 있을 것 같아요!

2022-05-18 05:50 UTC, OldStarKR commented on Calculator/Calculator/Application/Domain/Models/CalculatorItemQueue.swift
> +        array.isEmpty
가독성 측면에서 `return`이 있는 편이 훨씬 더 보기 좋을 것 같아서, 추가해주었습니다.

2022-05-18 06:12 UTC, OldStarKR commented on Calculator/Calculator/Application/Domain/Models/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: Queue where T: CalculateItem {
큐 자료형을 `struct`로 결정하는 데에는, 이전 쥬스메이커 프로젝트에서 보았던 애플의 [이 글](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)이 큰 영향을 끼쳤습니다.

크게 두 가지 이유를 꼽아볼 수 있을 것 같습니다. 첫 번째로는, 특별한 이유가 있지 않은 이상 구조체를 쓸 것을 애플이 권장하기 때문입니다. 여기서 특별한 이유란, Objective-C와 연동되어야 하거나 모델링하고자 하는 데이터의 아이덴티티를 직접 손대야 할 경우입니다. 제 생각에 제가 지금 만들고 있는 큐는 이런 경우에 해당되지 않는 것 같아서 구조체로 정의했습니다.

두 번째는, 공통적인 기능을 구현하고 이를 채용하고 싶을 때는 프로토콜과 구조체를 사용할 것을 권장하기 때문입니다. 제가 정의한 `Queue`는 기본적으로 프로토콜로 되어 있습니다. 이는 큐를 여러 가지 자료구조를 통해 구현할 수 있고, 실제로도 지금은 배열로 구현되어 있지만 향후 연결 리스트로 구현하는 등 변화가 있을 수 있기 때문에, 프로토콜로 큐의 기능을 명시함과 동시에 내부 자료구조 및 메서드를 바꿀 수 있는 가능성을 열어 둔 것입니다. 그래서 이를 활용하고자 구조체로 정의했습니다.

다만, 조금 더 생각해볼 여지는 있을 것 같습니다. `CalculatorItemQueue`는 이 앱에서 유일하게 존재하는 큐이고, 또 계산기의 특성상 그래야만 하는데, 그러면 아이덴티티의 관리가 필요하지는 않을지 의문을 가져 보았습니다. 클래스에도 프로토콜은 적용시킬 수 있기 때문에, 최초 저의 구상에서 크게 벗어나지 않으면서도 원하는 바를 구현할 수 있지 않을까 하는 생각은 있습니다.

2022-05-18 06:12 UTC, OldStarKR commented on Calculator/Calculator/Application/Domain/Models/CalculateItemTester.swift
> +}
Unit Test 안으로 옮겨 주었습니다🙃

2022-05-18 06:15 UTC, OldStarKR commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
각각의 테스트에 동일하게 주어지는 조건을 설정하고 또 초기화하는 메서드로 알고 있습니다. `setUp`을 통해 테스트할 인스턴스를 초기화하고, `tearDown`을 통해 다음 테스트에 대비하여 `setUp`에서 생성한 인스턴스를 없애 주는 것으로 배웠습니다.

전체적인 흐름은 `setUp` -> 테스트1 -> `tearDown` ->  `setUp` -> 테스트2 -> `tearDown` -> ... 의 흐름으로 알고 있습니다.

2022-05-18 06:16 UTC, OldStarKR commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertFalse(result)
given - when - then 주석에 관해서 가장 고민했던 점이, given 시점에서 `setUp`에서 지정한 조건 이외에 특별한 조건이 필요하지 않으면 어떻게 해야 할까에 대한 것이었습니다. 지금은 가독성을 위해 주석을 추가하는 것이 좋다고 생각되어 주석을 추가했고, given 밑을 일단 비워 두는 것으로 처리해 두었습니다🥲

2022-05-18 06:17 UTC, OldStarKR commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_isEmpty가_제대로_작동하는지() {
전반적으로 한 번씩 읽어 보고, 좀 더 이해하기 쉬운 방향으로 수정했습니다🙂

2022-05-18 06:20 UTC, OldStarKR commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
단위 테스트 코드가 기능명세의 역할도 수행한다고 말씀해주신 부분에 매우 공감이 됐습니다. `dequeue`와 `peek`이 대표적으로 `nil`을 반환할 수 있는 연산 프로퍼티 및 메서드인데요, 해당 경우에 대한 테스트를 작성해 주었습니다.

2022-05-18 06:21 UTC, OldStarKR commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        }
고차함수의 사용에 대해 슬슬 손에 익혀봐야겠다는 생각을 저도 하게 됐습니다. 다만, 저 부분의 반복문이 테스트 코드를 리팩토링 하는 과정에서 사라져버렸네요..😅 향후 작업을 진행하면서 말씀해주신 부분이 큰 도움이 될 것 같습니다.

2022-05-18 06:46 UTC, protocorn93 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertFalse(result)
저는 그럴 때는 when/then만 작성해주곤해요! 테스트 메서드 네이밍으로 그 부분은 보충해줄 수 있을 것 같아요!

2022-05-18 06:57 UTC, merged