계산기 [STEP 1] Judy
yagom-academy/ios-calculator-app pull request #232
Opened 2022-05-17 02:39 UTC by Judy-999

안녕하세요 제이슨(@ehgud0670) 😊 계산기 STEP 1 PR 보냅니다!
PR 보내기 전부터도 친절하게 알려주셔서 고민하던 부분을 많이 해결하고 보내게 되었습니다.
다시 한 번 감사드려요 👍 부족한 점이 많지만 리뷰 잘 부탁드립니다!

---

### UML
![](https://i.imgur.com/6oooB2B.png)

---

### <br> 코드 설명
#### 1. 제네릭 타입의 구조체
```swift
struct CalculatorItemQueue<Item>
```
- `private(set) var calulatorItems: [Item] = []`
: 큐의 요소들을 쌓아두는 배열 
-> Item은 `CalculatorItem` 프로토콜을 준수하는 타입
- `private var head = 0`
: `dequeue`할 요소의 인덱스를 저장하는 프로퍼티
- `func isEmpty() -> Bool`
: 큐가 비어있는지, 즉 `calulatorItems`가 비어있는 여부를 반환하는 메서드
- `mutating func enqueue(_ element: Item)`
: `calulatorItems` 맨 뒤에 새로운 요소를 추가하는 메서드 
- `mutating func dequeue() -> Item?`
: `head`가 가리키는 위치의 요소를 반환하는 메서드

#### <br>2. 연산자를 갖는 열거형
```swift
enum Operator: CalculatorItem 
```
- **case** - plus, minus, multiply, division
- `CalculatorItem` 프로토콜을 준수

#### <br>3. 그 외
```swift
protocol CalculatorItem
```
- `calulatorItems`의 요소가 되는 비어있는 프로토콜

```swift
class CalculatorItemQueueTest: XCTestCase
```
- `CalculatorItemQueue`의 메서드를 테스트하는 클래스
---

### <br> 🧐 고민한 점
#### 1. 연산자와 피연산자
큐의 요소는 `CalculatorItem` 프로토콜을 준수해야하는데 큐에는 연산자와 피연산자가 들어가서 어떤 타입이 준수해야할까 고민했습니다. 연산자는 따로 열거형을 만들어 준수하게 했고, 숫자는 `Double` 타입을 사용한다고 생각하여 extension으로 프로토콜을 준수하게 했습니다. 

#### 2. 제네릭 타입
프로토콜이 `Equatable`를 준수하지 않아 테스트의 어려움을 겪어 피연산자는 `Double`로 연산자는 `Operator`로 각각 타입 캐스팅하여 테스트를 했습니다. 이후 제이슨이 제네릭 타입으로 하면 타입을 지정하여 타입 캐스팅이 필요 없다고 알려주셔서 `<Item>`을 가지는 제네릭 타입으로 정의하고 Item으로는 `CalculatorItem` 준수하는 타입을 사용했습니다.

#### 3. 큐의 효율성
현재 구현한 큐 방식은 `enqueue`와 `dequeue`를 반복하면 계속 배열이 커지는 문제가 있습니다. 큐의 크기를 정해놓은 후 `dequeue`할 때마다 해당 요소를 `nil`로 변경하고 일정 비율이 넘으면 `head`를 다시 0으로 변경하는 방법이 있다고 알고 있습니다. 하지만 이후 연결 리스트나 더블 스택으로 구현해보고 싶어 지금은 그냥 두었습니다!

### <br> 🤔 궁금한 점
#### 1. 테스트 범위
제이슨이 Swift에서 이미 만들어진 타입은 테스트할 필요가 없다고 하셨는데 사실상 `enqueue` 메서드는 배열의 `append` 메서드만, `isEmpty`메서드는 배열의 `isEmpty` 메서드만 사용합니다. 이럴 경우 제가 작성한 메서드긴 하지만 배열의 함수만 이용하는 것이니 따로 테스트할 필요가 없는 것인가요?

#### 2. mutating
현재 `CalculatorItemQueue`은 구조체로 되어있어 프로퍼티인 `calulatorItems`를 변경하는 `enqueue`와 `dequeue` 메서드는 `mutating`으로 되어있습니다. 구조체는 immutable 값을 지향한다고 알고 있어 클래스로 변경할까 했지만 이후 STEP을 모르지만 상속이 필요하지 않을 것 같고, 가지고 있는 프로퍼티 역시 값 타입이라 구조체로 두었는데 혹시 클래스가 좋을지 궁금합니다! 

#### 3. private 테스트
큐의 배열을 `private`로 지정했더니 테스트할 때 원하는 배열로 지정할 수 없는 문제가 있었습니다. 그래서 `dequeue` 메서드를 테스트할 때 `enqueue`를 반복한 후 테스트 했는데 괜찮은 방법인지 궁금합니다.

2022-05-18 04:24 UTC, Judy-999 commented
## 추가 수정
## 1. 더블 스택 큐 방식 적용
Array 하나만 사용했던 큐에서 스택 두 개를 사용한 더블 스택 뷰 방식으로 변경했습니다. 더블 스택 큐 방식은 enqueue하는 스택과 dequeue하는 스택을 분리해서 사용합니다. 

### 동작원리
- `enqueue(item)` : enqueue하는 스택에 push
- `dequeue() -> Item?` : dequeue하는 스택에서 pop
    * 두 스택이 모두 비어있을 때 -> `nil`
    * dequeue하는 스택이 비어있을 때 -> enqueue하는 스택을 뒤집어서 넣어줌
<br>

### 읽기만 가능한 연산 프로퍼티
```swift
 var calculatorItems: [Item] {
        get {
            return dequeueStack.stack.reversed() + enqueueStack.stack
    }
}
```
큐가 스택 두 개로 분리되어 있고 enqueue 스택은 `removeAll()`되기 때문에 큐의 전체 아이템을 읽을 수 있도록 읽기만 가능한 연산 프로퍼티를 사용했습니다.

### <br>더블 스택 방식으로 변경한 이유
더블 스택으로 변경했을 때의 이점은 다음과 같습니다.

#### 1) head 제거
Array 하나만 사용했을 때는 dequeue할 위치를 가리키기 위해 포인터 역할을 하는 head가 필요했지만 더블 스택 방식은 스택을 뒤집어서 pop하기 때문에 head가 필요없습니다.

#### 2) 비대해지는 배열 방지
이전 방식은 enqueue와 dequeu를 반복하다보면 계속해서 Array의 크기가 커졌습니다. 하지만 더블 스택은 dequeue 스택에 요소를 옮긴 후 enqueue 스택을 `removeAll()`하기 때문에 반복해서 사용해도 무한정 커지지 않습니다.
<br><br>

## 2. 제네릭 타입의 프로토콜 준수
```swift
struct CalculatorItemQueue<Item: CalculatorItem> 
```
제네릭 타입으로 둔 `Item`이 `CalculatorItem` 프로토콜을 준수하도록 제한을 두었습니다.

## <br><br>3. 추가 질문
`Stack`이라는 구조체를 따로 만들어서 큐에서 두개의 `Stack`을 가지도록 했습니다. 하지만 구현하고 보니 `Stack`의 메서드를 이용하는게 오히려 비슷한 동작을 반복하는 느낌이 들어 `Stack` 사용 없이 Array만 바로 큐에서 사용해서 하는 방식도 적용해봤습니다. (36ceb9f) `Stack` 있을 경우 혹시 모를 확장성에 대응할 수 있겠지만 이번 계산기 프로젝트에서는 사용할 일이 없어보이는데 굳이 `Stack`을 따로 구현하는게 비효율적인 방법이 아닌지 의문이 들었습니다.
<br>

---
변경하고 싶은 부분까지 기다려주셔서 감사합니다! 리뷰 잘 부탁드려요 😊

2022-05-18 09:05 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var dequeueStack = Stack<Item>()
enqueueStack 과 dequeueStack 을 외부로 노출시킬 필요가 있을까요~?
저번에 음성으로 말씀드린 것처럼 Queue라는 자료구조를 만든다면 안에서 내부적으로 동작하는 자료구조들은 감추는 게 나을 것 같아요. 왜냐하면 외부에서 직접 사용하는 것 보다는 메소드를 통해 동작시키는게 유지보수하는데 좋기 때문입니다 :)

2022-05-18 09:07 UTC, ehgud0670 commented on Calculator/Calculator/Model/Stack.swift
> +    var stack: [T] = []
위에 말씀드린 것처럼 내부에서 사용하는 자료구조는 감추는게 좋습니다. 
dequeueStack을 enqueueStack으로 업데이팅한다고 하면 그대로 업데이팅하는 게 나을 것 같아요. reversed 라는 메소드가 필요하다면 새로 만드시면 되겠습니다 🙂

2022-05-18 09:11 UTC, ehgud0670 requested changes
일단 첫번째 코멘트 남겼고 계속 리뷰하고 있을게요! 👍

2022-05-18 09:11 UTC, ehgud0670 commented on Calculator/Calculator/Model/Stack.swift
> +    var stack: [T] = []
또 저번에 말씀드린것처럼  stack 이라고 하기 보다는 그냥 items 라고 짓는게 좋을 것 같아요. 왜냐하면 stack이 아닐뿐더러 어떤 배열이나 딕셔너리의 이름을 지을때 타입(ex. `stack`, `array`) 그대로 이름 짓기보다는 어떤 것이 들어가 있는가를 토대로 복수형으로 이름을 지으면 좋기 때문입니다. (ex. `caluratorItems`, `items`)

2022-05-18 09:11 UTC, ehgud0670 commented on Calculator/Calculator/Model/Stack.swift
> +        return stack.popLast()
stack이 아닌데 stack이라고 하니깐 popLast라는 메소드가 이상해보이는 거죠! stack이면 논리상 pop 메소드이어야 하니까요 :)

2022-05-18 09:14 UTC, ehgud0670 commented on Calculator/Calculator/Model/Stack.swift
> +    var stack: [T] = []
참고하여 [링크](https://github.com/BoyScout2021/CleanCode/blob/main/Chapter_02_%EC%9D%98%EB%AF%B8%EC%9E%88%EB%8A%94_%EC%9D%B4%EB%A6%84/ehgud0670.md#%EA%B7%B8%EB%A6%87%EB%90%9C-%EC%A0%95%EB%B3%B4%EB%A5%BC-%ED%94%BC%ED%95%98%EB%9D%BC) 하나 드립니다. 제가 클린코드 내용을 요약했던 글입니다.

2022-05-18 09:26 UTC, ehgud0670 commented
> 3. 추가 질문
Stack이라는 구조체를 따로 만들어서 큐에서 두개의 Stack을 가지도록 했습니다. 하지만 구현하고 보니 Stack의 메서드를 이용하는게 오히려 비슷한 동작을 반복하는 느낌이 들어 Stack 사용 없이 Array만 바로 큐에서 사용해서 하는 방식도 적용해봤습니다. (https://github.com/yagom-academy/ios-calculator-app/commit/36ceb9f1c2906d82eeada664ee410f76ae958adc) Stack 있을 경우 혹시 모를 확장성에 대응할 수 있겠지만 이번 계산기 프로젝트에서는 사용할 일이 없어보이는데 굳이 Stack을 따로 구현하는게 비효율적인 방법이 아닌지 의문이 들었습니다.

=> 네, 사실 Swift의 Array는 제공하는 메소드가 많고 내부적으로도 효율적으로 잘 구현되어있는 자료구조이기 때문에 Array만 쓰셔도 문제가 없습니다. 
=> 그리고 지금 구현하신 Stack 으로 확장성이 더 있다고도 보기는 어려울 것 같아요! 말씀주신 [커밋](https://github.com/yagom-academy/ios-calculator-app/commit/36ceb9f1c2906d82eeada664ee410f76ae958adc) 내용만 보더라도 Swift 의 Array로 대체해도 무방하기 때문이죠.
=> List 대신 Stack을 정말 구현한다면 Array의 메소드들을 사용하지 않고 구현하시는게 더 배울 점이 많으실 것 같습니다 :) 
Swift 의 Array가 아닌 C언어의 [Array](https://dojang.io/mod/page/view.php?id=293)로 구현한다고 생각하고 구현하시면 스택의 내부 동작을 좀 더 이해하실 것 같아요!

2022-05-18 09:37 UTC, ehgud0670 commented
### 궁금한 점
> 1. 테스트 범위
제이슨이 Swift에서 이미 만들어진 타입은 테스트할 필요가 없다고 하셨는데 사실상 enqueue 메서드는 배열의 append 메서드만, isEmpty메서드는 배열의 isEmpty 메서드만 사용합니다. 이럴 경우 제가 작성한 메서드긴 하지만 배열의 함수만 이용하는 것이니 따로 테스트할 필요가 없는 것인가요?

=> 음 그래도 따로 테스트 할 필요가 있겠습니다. 내부의 메소드를 그대로 사용한다고 할지라도 자신의 만든 메소드를 테스트를 해야 한다고 생각해요. 왜냐하면 추후에 내부적으로 사용하는 자료구조가 Array가 아닌 다른 자료구조를 사용할 것도 대비해서도 항상 테스트 케이스는 통과해야 한다고 생각하기 때문입니다. 추후의 변화가능성을 차치하고서라도, 자신이 만든 메소드라면 내부 구현은 어떻게 되어 있는지 상관없이 테스트를 해야 한다고 생각합니다.  

2. mutating
현재 CalculatorItemQueue은 구조체로 되어있어 프로퍼티인 calulatorItems를 변경하는 enqueue와 dequeue 메서드는 mutating으로 되어있습니다. 구조체는 immutable 값을 지향한다고 알고 있어 클래스로 변경할까 했지만 이후 STEP을 모르지만 상속이 필요하지 않을 것 같고, 가지고 있는 프로퍼티 역시 값 타입이라 구조체로 두었습니다. 구조체와 클래스를 선택하는건 여전히 어렵네요.. 혹시 클래스가 좋을지 제이슨의 생각은 어떤지 궁금합니다!

=> 음, Queue라는 자료구조를 만드는 것이 과제이고, 현재 Swift에서 제공해주는 모든 자료구조가 struct인 것을 봤을때 struct가 어울립니다. 
그리고 해당 자료구조들도(ex. Array, Dictionary) mutating 메소드를 써가며 내부에 데이터를 저장하는 것을 보면 mutating 메소드로 구현하는 것이 옳다고 생각합니다. swift 에서 제공하는 Array를 한번더 래핑하여 다른 성격의 타입이 구조체인 자료구조를 만든다고 생각하시면 이해가 빠르실 것 같아요 :)

3. private 테스트
큐의 배열을 private로 지정했더니 테스트할 때 원하는 배열로 지정할 수 없는 문제가 있었습니다. 그래서 dequeue 메서드를 테스트할 때 enqueue를 반복한 후 테스트 했는데 괜찮은 방법인지 궁금합니다.

2022-05-18 09:44 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
isEmpty를 연산프로퍼티로 구현해도 좋을 것 같네요 :)
선택입니다. 지금 메소드로 구현이 좋으시다면 바꾸시지 않아도 돼요.

2022-05-18 09:47 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var dequeueStack = Stack<Item>()
그리고 사실 Queue를 사용하는 사용자 입장에선 enqueueStack 과 dequeueStack를 알 필요가 없기 때문입니다. 
caluatorItems 는 알 필요가 있네요 👍

2022-05-18 12:05 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
파라미터가 필요하지도 않고 단순 return만 하는 메서드라 굳이 메서드일 필요가 없다고 생각해 연산 프로퍼티로 변경했습니다 😊

2022-05-18 12:07 UTC, Judy-999 commented on Calculator/Calculator/Model/Stack.swift
> +        return stack.popLast()
그렇네요 😅 
`CalculatorItemQueue`에서도 진짜 stack을 사용하는게 아니니 `enqueueStack` -> `enqueueItems`, `dequeueStack` -> `dequeueItems`로 변경했습니다!

2022-05-18 12:08 UTC, Judy-999 commented on Calculator/Calculator/Model/Stack.swift
> +    var stack: [T] = []
좋은 링크 감사합니다👍 앞으로도 참고하겠습니다!

2022-05-18 12:09 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var dequeueStack = Stack<Item>()
왠지 사용할 것 같아 괜히 `private(set)`으로 했는데 막상 코드를 보니 접근하는 부분이 없었네요..!
둘 다 `private`으로 변경했습니다.

2022-05-18 19:23 UTC, ehgud0670 commented on Calculator/Calculator/Model/LinkedList.swift
> +        }else {
```suggestion
        } else {
```
=> 아시겠지만 여기 한 칸 띄워주세요~ :)

2022-05-18 19:23 UTC, ehgud0670 commented on Calculator/Calculator/Model/Node.swift
> +    init(_ value: Item){
```suggestion
    init(_ value: Item) {
```
=> 여기도요!

2022-05-18 19:29 UTC, ehgud0670 approved these changes
주디 고생많으셨습니다! 
테스트 코드도 잘 작성하셨고, 링크드 리스트도 직접 구현하셨네요! 👏👏👏
앞으로 2가지를 더 구현해보시면 좋을 것 같아요!
1) 원형(circular) 연결 리스트 + 원형 연결 리스트에서 가능한 메소드 추가 구현 
2) 연결리스트에 저장된 값(`[Item]`)들을 반환하는 메소드

그럼 Step2 진행하시면 될 듯 합니다. 고생 많으셨습니다. 🤩

2022-05-18 19:29 UTC, merged

2022-05-19 05:04 UTC, Judy-999 commented on Calculator/Calculator/Model/Node.swift
> +    init(_ value: Item){
왜 못봤을까요 😅 한 칸 띄웠습니다!

2022-05-19 05:05 UTC, Judy-999 commented on Calculator/Calculator/Model/LinkedList.swift
> +        }else {
알고 있는 컨벤션인데 놓친 부분이 있었네요..!