계산기 [STEP1] 웡빙
yagom-academy/ios-calculator-app pull request #233
Opened 2022-05-17 02:43 UTC by wongbingg

@jryoun1  안녕하세요 제이크! @wongbingg 입니다! 두근두근 첫 PR 보냅니다 잘 부탁 드립니다 ☺️☺️

## UML
![](https://i.imgur.com/WBmKFA1.png)
## TDD
- TDD 를 이용하여 단위테스트를 진행하며 최소한의 코드를 추가했습니다.
- 기능명세서의 역할을 하도록 했습니다.
- 배열로 구현한 큐 에서 더블스택으로 구현한 큐로 변경 해 주었을 때, 테스트에 작성 되어있는 요구사항들을 만족 시키기 위한 코드수정이 이루어졌습니다.  
## Queue
- 사용자에게 받은 입력값(숫자, 연산자)들을 쌓아놓기 위한 Qeueu를 구현했습니다.
- Queue의 종류에 대해 알아보았습니다.
    - **배열**
        - FIFO 특성을 가진다. 
        - 스위프트의 배열에서는 먼저 2배씩 늘려놓는다. 
        - 빈 공간에 enQueue()를 수행할 때는 수행속도가 O(1) 로 빠르다
        - 하지만 크기를 늘려야 하는 시점에서는 수행속도가 O(n)이다
        - deQueue() 수행 시, 빠진 배열을 매꿔주어야 해서 수행속도가 O(n) 
    - **연결리스트**
        - 자기자신의 노드와 다음노드를 가리키는 참조정보로 구성된다. 
        - 더블연결리스트의 경우는 여기에 이전노드를 가리키는 참조정보가 추가된다.
        - enQueue() 수행속도는 O(1)이 된다.
        - deQueue() 수행시 배열처럼 재정렬이 필요한 것이 아니므로 수행속도가 O(1)
        - 값, 이전노드참조, 다음노드참조 등을 포함하는 동적할당 때문이 상대적으로 큰 메모리 소모
        - 메모리 접근 시간이 느리다
    - **stack**
        - 배열로 append와 popLast 를 이용하면 stack처럼 사용 가능하다.
        - 나아가, 더블stack이란 FIFO를 구현하고자 할 때 배열에서 생기는 재정렬의 문제를 해결하고자 고안된 방법이다
        - Dequeue 전용 스택과 Enqueu 전용 스택을 만들어서, Enqueue에서 Dequeue로 넘겨줄 땐 reversed()로 반전시켜 넘겨주고 popLast를 하면, 배열의 첫번째 값을 얻고도 재정렬이 필요하지 않게 된다. 
        - 공간복잡도 측면에서도 더블연결리스트 보다 수행이 빠르다. 
        
- 본 프로젝트에서는 **FIFO**방식이 필요하고, 프로젝트 요구사항에 `"연산자 우선순위를 무시하고 앞에서부터 순서대로 계산합니다"` 라는 문구에서 큐 중간에 삽입하거나 삭제하는 과정은 필요하지 않다고 판단되어 , 처음엔 배열을 선택하게 되었고, deQueue() 수행 시 이루어지는 재정렬 문제를 해결하기 위해 더블stack으로 바꾸어 주었습니다. 

## 고민한 점 & 궁금한 점

- 요구사항 1 : 사칙연산 계산을 위한 큐(Queue) 타입(CalculatorItemQueue)과 큐타입 구현을 위한 `List 타입`을 직접 UML로 표현해봅니다
    - 여기서, `"List 타입"` 이란  연결리스트(node)를 이용하라는 지시 일까요 ? 그렇다면 제가 작성한 doubleStack 자료구조의 변경이 이루어져야 하는지 궁금합니다.

2022-05-18 10:21 UTC, jryoun1 requested changes
안녕하세요 @wongbingg 🙋‍♂️
step1 고생많으셨습니다!
2주 동안 잘 부탁드려요~ 

UML도 깔끔하게 그려주셨고, 자료구조 선택에 대한 이유도 잘 설명 해주셨네요💯 👏

다만 몇 가지 개선사항을 아래 리뷰에 남겨두었습니다!

### 고민한 점, 궁금한 점에 대한 답변
그렇지 않습니다. 위에서 말씀하신 것처럼 사칙 연산 계산을 하기 위한 큐 타입을 구현하는데는 여러가지 자료 구조들이 있을 것이고, 그 중에서 윙빙이 하신 것처럼 어떤 자료 구조를 선택하는 것이 좋을지 고민해보고 선택해서 구현을 해주시면 됩니다.🙏🏻

2022-05-18 10:21 UTC, jryoun1 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var currentArray: [T] {
위에서는 stack이었는데, 여기서는 array가 되었네요. 🤔
반환 값이 현재 stack에 있는 값들이니까 좀 더 명확한 네이밍이였으면 좋을 것 같아요.

2022-05-18 10:21 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        //given
GWT(given, when, then)으로 나눠서 작성해주셔서 가독성이 아주 좋네요 👏

2022-05-18 10:21 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_enQueue를이용해_배열에1을추가했을때_1이들어갔는지() {
함수명을 한글로 한 이유가 있을까요? 👀

2022-05-18 10:21 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_1_2_3배열에서_peek계산프로퍼티에_1이들어가는지() {
들어가는것이 아니라 반환되는것 같아요!

2022-05-18 10:21 UTC, jryoun1 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열에서_peek계산프로퍼티에_nil이들어가는지() {
여기도 동일합니다!

2022-05-18 11:59 UTC, wongbingg commented on Calculator/Calculator/CalculateItem.swift
> +protocol CalculateItem {
"CalculateItemQueue" 에 쌓인 "연산자와 피연산자"에 대한 계산을 수행 해주는 함수들이 들어올 것이라 예상됩니다..! 
또한 "=" 버튼이 눌렸을 때 전체 계산이 수행되는 것으로 보아, 이 타이밍을 delegate를 통해 전달 해주지 않을까? 하는 생각이 듭니다!

2022-05-18 12:17 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var isEmpty: Bool {
Array 가 기본적으로 자신의 count 값이 0 인지 Bool값을 반환하는 isEmpty 프로퍼티를 가지고 있고, 이를 활용하여 최소한의 코드를 작성 해보고자 읽기전용 연산 프로퍼티로 구현을 해보았습니다. 함수로 구현하게 될 시, 빈값인지 확인할 때 CalculateItemQueue.isEmpty() 와 같이 불필요한 소괄호가 붙게되어 더 표현이 깔끔한 연산 프로퍼티를 사용하게 된 것 같습니다 😄

2022-05-18 12:27 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueStack = Array<T>()
dequeueStack 과 enqueueStack 에 접근레벨은 private이 되어야 한다고 생각합니다! 하지만 지정해주게 되면 테스트케이스에서 사용할 수 없게되어 기본값 internal 로 두었습니다. 😂 이럴 경우에는 테스트 진행 후 다시 private으로 지정 해주는 것이 좋을까요? 궁금합니다!

2022-05-18 12:34 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_enQueue를이용해_배열에1을추가했을때_1이들어갔는지() {
학습했던 TDD 강의에서, Test 코드가 기능을 명세화, 문서화 하기 때문에 한국인 끼리의 작업이라면 한글로 작성하여 가독성이 좋게 작성하는 것을 추천해서 이런식의 구현을 해봤습니다! 😊

2022-05-18 12:52 UTC, jryoun1 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var isEmpty: Bool {
좋네요 👍🏻 
이외에도 [다른 관점](https://velog.io/@wonhee010/Computed-Property%EC%97%B0%EC%82%B0-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0-vs-Method)에서의 연산프로퍼티와 메서드를 사용하는 기준을 참고할 수 있는 글이 있어서 공유드려요 🙏🏻

2022-05-18 13:00 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueStack = Array<T>()
테스트에 dequeueStack 과 enqueueStack 을 사용하는 대신에 읽기전용 프로퍼티인 currentStack을 이용해 해결 하였습니다! ☺️
읽기전용 프로퍼티는 접근은 가능해도 수정할 수 없기 때문에 private 처리를 하지 않아도 되는게 맞을까요?

2022-05-18 13:06 UTC, jryoun1 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueStack = Array<T>()
test에서 직접적으로 dequeueStack, enqueueStack에 접근을 통해 값을 설정하고 테스트를 해야만 할까요? 
값을 변경하는 방법이라면 접근권한이 internal인 enqueue, dequeue 메서드를 통해서도 가능할 것 같아 보이네요 🙏🏻

나중에 private 변수, 함수를 테스트하는 방법에 대해서도 알아보시면 좋겠지만, 
이번 프로젝트의 범위에서 많이 벗어나는 내용이라서 이번에는 넘어가셔도 좋을 것 같습니다. 🙂
나중에 시간이 된다면 한 번 읽어보세요. [참고](https://www.avanderlee.com/swift/testing-private-methods-variables/)

2022-05-18 21:50 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var isEmpty: Bool {
좋은정보 공유 감사합니다! ㅎㅎ

2022-05-18 22:01 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueStack = Array<T>()
좋은정보 공유 감사합니다!ㅎㅎ

2022-05-18 22:03 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_1_2_3배열에서_peek계산프로퍼티에_1이들어가는지() {
연산 프로퍼티니까 말씀대로 반환이 맞겠군요!! 😂

2022-05-19 09:23 UTC, jryoun1 approved these changes
넵 변경해주신 사항 확인했습니다~ 
@wongbingg step1 고생하셨습니다! 👏 
step2도 화이팅입니다💪🏻

2022-05-19 09:23 UTC, merged