계산기 [STEP 1] Borysarang
yagom-academy/ios-calculator-app pull request #235
Opened 2022-05-17 06:57 UTC by yusw10

@corykim0829 
안녕하세요 Cory! Step1 완료하여 PR 보내드립니다..! 🫡
진행하면서 고민했던 부분 정리해보았습니다.

## STEP 1 진행사항
- 구현할 내용에 대해 class diagram을 작성해보았습니다.
- CalculatorItemQueue를 DoubleStack을 활용한 Queue방식과 직접 List를 작성하여 queue를 구현하는 두가지를 모두 진행해보았습니다(최종 Commit에는 List를 사용하여 queue를 구현한 방식을 올렸습니다)
- List, Queue 두가지 클래스는 TDD를 따라서 구현해보았습니다. 

## STEP 1 고민한 점

### TDD의 커밋
지난 활동학습 및 야곰닷넷의 Unit Test강좌를 들으며 테스트 주도 개발이라는 개발론을 공부할 수 있었습니다. [실패하는 테스트 -> 리팩토링 -> 테스트성공]의 루틴으로 정확한 단위 기능들을 구현해나간다는 취지도 이해했습니다. 다만 이번에 실제로 TDD를 따르며 Queue를 구현해보았는데 TDD시에 어떻게 커밋을 해야하는지 막막했습니다.(테스트, 리팩토링, 성공 마다 커밋인지 / 아니면 기능별로 한루틴마다 커밋인지)
특히 큐를 구현할 때 느낀점이, 기능끼리 연관이 되어있을 경우 다른 테스트를 할 수가 없어서 어떻게 진행하는지 감이 잘 안왔습니다(enqueue를 구현하지 않으면 내부 queue를 직접 대입해서 하는것인지.)

### Equtable
 자료구조를 구현하는과정중에 linkedList의 poplast, 또는 head나 tail에 정상적으로 인스턴스가 삽입되었는지 확인을 하려고 했습니다. 확인하던 중 XCTAssertEqual은 값타입만 비교가 가능하고 인스턴스를 비교하려면 Equtable 프로토콜을 상속받고 `==` 메서드를 오버라이딩 해야한다고 이해했습니다. 하지만 실제 더 큰 규모의 테스트에서는 같은 인스턴스인지를 비교할 경우가 많을것 같은데 이부분은 전부 Equtable을 상속받고 하는건지, 아니면 인스턴스 반환값을 테스팅할때 다른 기법이 있는건지 궁금합니다(현재 코드에서는 각 Node의 value로 비교하였습니다)

### Queue
다른 언어와 다르게 swift는 언어차원에서 queue를 구현해주지 않음을 이번에 처음 알았습니다. 후에 알고리즘 등 사용할 요소가 무궁무진하기에 이번에 공부를하게 되었습니다. 
 저는 두가지 배열을 사용하여 큐를 구현한 DoubleStackQueue를 구현해보았습니다. 그 이유로는, removeFirst()라는 배열의 메서드를 사용하여 간편하게 구현할 수 있었지만 복잡도가 n이라 좀 더 나은 방법이라고 많은 글에서 소개를하는 방법을 채택했습니다.
 다만 궁금한 점이 복잡도가 O(1)인 경우와 O(n)인 경우를 놓고 본다면 당연히 O(1)이 되도록 하는게 옳겠지만 이런 수준의 리팩토링이 **실제 어플리케이션에서 유의미한 성능 향상을 낼 수 있는지** 궁금했습니다. 

## UML
### Class Diagram
![](https://i.imgur.com/Bagv701.png)

2022-05-17 13:37 UTC, corykim0829 requested changes
수고하셨습니다 👏👏👏

### TDD의 커밋

> 지난 활동학습 및 야곰닷넷의 Unit Test강좌를 들으며 테스트 주도 개발이라는 개발론을 공부할 수 있었습니다. [실패하는 테스트 -> 리팩토링 -> 테스트성공]의 루틴으로 정확한 단위 기능들을 구현해나간다는 취지도 이해했습니다. 다만 이번에 실제로 TDD를 따르며 Queue를 구현해보았는데 TDD시에 어떻게 커밋을 해야하는지 막막했습니다.(테스트, 리팩토링, 성공 마다 커밋인지 / 아니면 기능별로 한루틴마다 커밋인지)
특히 큐를 구현할 때 느낀점이, 기능끼리 연관이 되어있을 경우 다른 테스트를 할 수가 없어서 어떻게 진행하는지 감이 잘 안왔습니다(enqueue를 구현하지 않으면 내부 queue를 직접 대입해서 하는것인지.)

➡️ 저는 커밋은 유의미한 코드의 작성, 수정을 읽기 좋은 단위라고 생각합니다! 조금 애매하긴 한데, 남겨준 커밋들을 커밋단위로 확인했을 때, 읽기 좋은지 한번 확인해보면서 감을 잡아보면 좋을 것 같아요!

### Equtable

> 자료구조를 구현하는과정중에 linkedList의 poplast, 또는 head나 tail에 정상적으로 인스턴스가 삽입되었는지 확인을 하려고 했습니다. 확인하던 중 XCTAssertEqual은 값타입만 비교가 가능하고 인스턴스를 비교하려면 Equtable 프로토콜을 상속받고 == 메서드를 오버라이딩 해야한다고 이해했습니다. 하지만 실제 더 큰 규모의 테스트에서는 같은 인스턴스인지를 비교할 경우가 많을것 같은데 이부분은 전부 Equtable을 상속받고 하는건지, 아니면 인스턴스 반환값을 테스팅할때 다른 기법이 있는건지 궁금합니다(현재 코드에서는 각 Node의 value로 비교하였습니다)

➡️ 저는 최소한의 Equatable 채택으로 하고 있습니다. Equatable을 채택하지 않고도 처리할 수 있다면 사용하지 않고 있습니다!

### Queue

> 다른 언어와 다르게 swift는 언어차원에서 queue를 구현해주지 않음을 이번에 처음 알았습니다. 후에 알고리즘 등 사용할 요소가 무궁무진하기에 이번에 공부를하게 되었습니다.
저는 두가지 배열을 사용하여 큐를 구현한 DoubleStackQueue를 구현해보았습니다. 그 이유로는, removeFirst()라는 배열의 메서드를 사용하여 간편하게 구현할 수 있었지만 복잡도가 n이라 좀 더 나은 방법이라고 많은 글에서 소개를하는 방법을 채택했습니다.
다만 궁금한 점이 복잡도가 O(1)인 경우와 O(n)인 경우를 놓고 본다면 당연히 O(1)이 되도록 하는게 옳겠지만 이런 수준의 리팩토링이 실제 어플리케이션에서 유의미한 성능 향상을 낼 수 있는지 궁금했습니다.

➡️ 해당 코드가 사용되는 환경에 따라서 다를 것 같아요. 현업에서는 컬렉션의 크기가 정말 커질 수 있기 때문에 복잡도도 영향을 줍니다!

2022-05-17 13:37 UTC, corykim0829 commented on Calculator/Calculator/CalculatorQueue/CalculatorList.swift
> +class Node<T> {
Node 클래스도 하나의 파일로 분리해주세요!

2022-05-17 13:37 UTC, corykim0829 commented on Calculator/Calculator/CalculatorQueue/CalculatorList.swift
> +    var tail: Node<T>?
private로 수정하여 내부에서만 처리할 수 있도록 하는게 좋을 것 같아요.

2022-05-17 13:37 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorListTests.swift
> +    func test_3개있을때_3반환() {
enqueue를 하지 않는이유가 있을까요?

2022-05-17 13:37 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorListTests.swift
> +    func test_노드가한개일때_pop하면_Node반환후_head및tail_nil() {
꼼꼼한 테스트 칭찬합니다! 👍

2022-05-17 19:05 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +
공백두줄은 제가 의도한 spacing은 아니어서 수정했습니다..!
한가지 궁금한 것이, 저는 클래스를 작성할때 [프로퍼티 - 생성자 - 내부메서드(함수의 끝에는 공백한줄) - 상속받는 메서드] 이런 순서로 구현하는 편인데 Cory는 각 영역에서 공백을 최대한 지우는 편이신가요(어떤 방식으로 공백을 주는것이 가독성이 좋다 라는걸 아직 잘 모르겠습니다.) 
[0879265](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/087926534cfb2e4c06c5c76eb0ae8d81bb6422c0)

2022-05-17 19:07 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +        self.queue = CalculatorList()
만약 프로퍼티가 굉장히 많은 인스턴스를 소유한다면, 각 프로퍼티에 대한 실제 인스턴스를 주입하는 과정은 생성자가 담당하는게 좀 더 관리하기 쉽다고 생각했습니다.
다만 코멘트주신대로 "지금 queue의 초기화가 꼭 생성자에서 이루어져야 할까?" 라는 접근에서는 불필요한 코드가 맞는것 같습니다. 
[95dff45](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/95dff4577b1b700594ecda23acc677d16f1c9271)

2022-05-17 19:09 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorList.swift
> +    func isEmpty() -> Bool{
공백 통일했습니다..!
[e1abddc](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/e1abddc128d8d342b874308fbca1894ee6d74873)

2022-05-17 19:09 UTC, yusw10 commented on Calculator/CalculatorTests/CalculatorListTests.swift
> +    func test_3개있을때_3반환() {
현재 테스트 코드에 올라간 테스트들은 내부 메서드를 작성한 순서대로 만든 테스트들입니다. 
최초에 size() 메서드를 구현할때는 enqueue를 구현하지 못했었습니다. 때문에 테스트를 진행해보려고 강제로 연결리스트를 만들기 위해 이어준것 같습니다.
[5554897](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/55548972310486d8d935df210d2049a83cd40cdf)

2022-05-17 19:19 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorList.swift
> +    var tail: Node<T>?
이부분도 수정 및 head 와 tail값에 직접적으로 접근하는 테스트코드를 size로 확인하도록 변경해보았습니다.
[5700a33](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/5700a33f6a66d24080b0cec6ab2d00c241255394)

2022-05-17 19:20 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +    func showHeadNode() -> Node<String>? {
peek을 구현해보려고 작성한 함수인데 지금보니 dequeue랑 동일한 함수였습니다...😢
[30e14b2](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/30e14b2994ee1d78d1796b6402f21f159ab7c85e)

2022-05-17 19:21 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +    func removeAllQueue() {
이 메서드에서 호출하는 List의 메서드랑 네이밍이 곂치면 안된다고 생각해서 Queue를 붙여봤었습니다. 수정했습니다..!
[d0f48e1](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/d0f48e14e53fdf066917971345e82a676ca65a4c)

2022-05-17 19:23 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +        let newNode: Node<String> = Node(value: input, next: nil)
next인자는 생성자에서 next가 nil값 고정이어도 써주는 것이 표현이 명확할 것 같다(Node 내부에 어떤 프로퍼티가 있는지 인스턴스 생성시에 고지하기위함)는 생각에서 Node의 생성자에 argument로 넣었었습니다. 
다만 코멘트 달아주셔서 다시 곰곰히 생각해 보았는데 Node선언부에 next 타입이 뻔히 있는데 굳이 생성자에서 불필요한 코드를 작성하지 않는게 좋은것같아서 비우는것으로 수정했습니다..!
[08f2c3b](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/08f2c3b2ff3e0872ba0792761c3a88bb4d90bf65)

2022-05-17 19:25 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorList.swift
> +        guard var counterNode: Node = head else {
이 부분도 위에 enQueue 메서드에서와 동일하게 명시한것 삭제했습니다..!
[08f2c3b](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/08f2c3b2ff3e0872ba0792761c3a88bb4d90bf65)

2022-05-18 02:25 UTC, corykim0829 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +
코드가 많아지면 오밀조밀 붙어있으면 가독성이 조금 떨어지더라구요! 말씀하신 대로 프로퍼티, 생성자, 내부메서드 간에는 공백 줄을 넣어주고 있어요!

2022-05-18 02:32 UTC, corykim0829 requested changes
수고하셨습니다!

미션 요구사항에서 조금 중요한 부분을 놓쳐서 이 부분만 수정하고 가면 좋을 것 같습니다!

2022-05-18 02:32 UTC, corykim0829 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +class CalculatorItemQueue: CalculatorItem {
Queue에서 다루는 요소가 CalculatorItem 프로토콜을 준수하는거지, Queue가 준수하는게 아닌 것 같아요!
<img width="640" alt="image" src="https://user-images.githubusercontent.com/34022757/168944690-4b472700-9b3b-49d3-ae05-8588ad761397.png">

2022-05-18 02:32 UTC, corykim0829 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +    private var queue: CalculatorList<String> = CalculatorList()
타입이 String으로 고정되어있는 부분이 남겨드린 위의 피드백과 관련이 있는 것 같습니다!

2022-05-18 05:15 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +class CalculatorItemQueue: CalculatorItem {
프로토콜을 준수해야 한다고해서 CalculatorItemQueue, 즉 클래스에서 상속받는다고 혼자 쓰윽 생각해버린것 같습니다...
굉장히 중요한 요소한 부분인거같은데 체크해주셔서 감사합니다..! 기능요구사항을 더 꼼꼼히 읽어야겠다고 생각했습니다..
[1e61c9a](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/1e61c9aededdaf86e046ef0a653924f6174c4c1a)

2022-05-18 05:16 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/CalculatorItemQueue.swift
> +    private var queue: CalculatorList<String> = CalculatorList()
이 부분도 프로토콜타입을 준수하게 만들었습니다...!
[6d4b368](https://github.com/yagom-academy/ios-calculator-app/pull/235/commits/6d4b3680f6f015f642c7d4c74154a7ddcf00ff95)

2022-05-18 08:19 UTC, merged