계산기 [STEP 1] seohyeon2
yagom-academy/ios-calculator-app pull request #238
Opened 2022-05-17 07:55 UTC by seohyeon2

안녕하세요 제이슨 @ehgud0670 ✨
계산기 STEP 1 PR 요청드립니다!

또한 STEP1과 관련하여 많은 도움 주셔서 감사합니다 😊
덕분에 많이 헤메지 않았어요 😁
물론 UML작성과 TDD가 처음이라 부족한 점이 많을 수 있습니다..ㅎㅎ
그럼 이번 리뷰 잘 부탁드립니다🙇🏻‍♀️

---

### UML 😶‍🌫️
- step2 공개 전, 계산기 동작설명을 보고 직접 작성한 UML입니다.
![스크린샷 2022-05-17 오후 3 05 22](https://user-images.githubusercontent.com/50102522/168758857-25e7dbfc-c755-45b0-b373-c770d3dbb5c6.png)

### 고민한 점 🤔
- dequeue 메서드의 구현 방식을 고민했습니다.
`removeFirst()`메서드를 사용하여 인덱스까지 없애는 쪽으로 구현할 지, 
값 반환 후 반환한 인덱스의 값을 nil로 처리하여 인덱스를 남겨둘지 고민했습니다.
물론 후자의 경우 시간복잡도가 O(1)인 큰 장점이 있지만, liked list로 구현할 때 시간복잡도를 줄여보려고 전자를 선택했습니다.
또한 전자의 경우 dequeu안에 head를 사용하지 않아 더 간결한 코드를 만들 수 있어 메서드를 사용하는 방식으로 구현했습니다.

### 3. 조언받고 싶은 점 😯
- 테스트 파일에도 MARK 주석을 사용하는지 궁금합니다.
MARK 주석을 사용하면 테스트 파일의 코드가 길어져도 같은 메서드에 대한 테스트를 `Jump bar menu`에서 모아서 확인할 수 있어 좋겠다라고 생각했습니다.
그래서 이번 스텝에서 테스트 파일에 MARK 주석을 사용해봤는데, 
테스트 파일에 MARK 주석을 사용하는 경우가 많은지 궁금합니다!

- 배열에 대한 isEmpty 메서드를 또 만들어 처리해도 괜찮은지 궁금합니다.
`dequeue()`와 `peak()`에서 배열이 비어있으면 `head`변수의 값을 -1로 초기화하는 부분이 중복되길래 `isEmpty()` 메서드를 따로 구현해주었습니다.
나중에 유지보수할 경우까지 생각하면 빼는게 맞는 것 같으면서도, 
메서드를 만드는 것보다 내장 메서드를 이용하는게 더 코드가 짧으니 이 방법이 맞나라는 생각이 듭니다.
`isEmpty()`를 직접 구현하는 것과 내장 메서드 사용 중에 어떤게 더 괜찮은 방법인지 궁금합니다!

2022-05-18 09:53 UTC, ehgud0670 reviewed
코드는 다 봤고 고민 및 궁금한점 답변드리도록 할게요 :)

2022-05-18 09:53 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var calculateItems = [T]()
private으로 감추시는게 좋을 것 같아요 :)

2022-05-18 10:00 UTC, ehgud0670 commented
> 테스트 파일에도 MARK 주석을 사용하는지 궁금합니다.
MARK 주석을 사용하면 테스트 파일의 코드가 길어져도 같은 메서드에 대한 테스트를 Jump bar menu에서 모아서 확인할 수 있어 좋겠다라고 생각했습니다.
그래서 이번 스텝에서 테스트 파일에 MARK 주석을 사용해봤는데,
테스트 파일에 MARK 주석을 사용하는 경우가 많은지 궁금합니다!

=> 네, 보통 같은 성격의 메소드가 많으면 MARK로 표시를 하면 파악하기 좋더라고요(예를 들어 `MARK: Delegate Methods`)
=> 테스트 코드의 경우에도 다른 사람이 볼때 MARK로 표시했을때 전체적으로 좀 더 파악하기 좋다면 쓰시면 좋을 것 같아요!

> 배열에 대한 isEmpty 메서드를 또 만들어 처리해도 괜찮은지 궁금합니다.
dequeue()와 peak()에서 배열이 비어있으면 head변수의 값을 -1로 초기화하는 부분이 중복되길래 isEmpty() 메서드를 따로 구현해주었습니다.
나중에 유지보수할 경우까지 생각하면 빼는게 맞는 것 같으면서도,
메서드를 만드는 것보다 내장 메서드를 이용하는게 더 코드가 짧으니 이 방법이 맞나라는 생각이 듭니다.
isEmpty()를 직접 구현하는 것과 내장 메서드 사용 중에 어떤게 더 괜찮은 방법인지 궁금합니다!

=> 일단 내부적으로 사용하는 Array는 감추는게 좋겠고, 감춘다면 isEmpty를 따로 구현하시는게 좋습니다. 또 다른 자료구조를 현이가 직접 구현하는 거니깐 필요한 메소드를 구현했다고 생각합니다. 왜냐하면 Queue가 비어있는지 Queue를 사용하는 사용자입장에서도 isEmpty는 필요하기 때문입니다 :)

2022-05-18 14:24 UTC, seohyeon2 commented
안녕하세요 제이슨!
`calculatorItems`을 배열에서 링크드 리스트로 수정 완료했습니다😀

2022-05-18 15:14 UTC, seohyeon2 commented
안녕하세요 제이슨✨
`calculateItems`를 배열에서 링크드 리스트 사용으로 수정했습니다😌
아직 많이 부족하지만 피드백 주시면 다음 스텝에선 더 성장한 모습으로 PR요청 드리겠습니다!!
저의 미숙한 부분이나 더 나은 방향에 대해 편하게 말씀해주시면 감사하겠습니다🙇🏻‍♀️

<br>

참고사항으로, 링크드 리스트로 바꾸면서 수정된 사항과 제가 구현한 링크드 리스트 설명을 아래에 적어봤습니다!

----

**<수정된 사항>**
**1. 접근제어자 추가**
- 피드백 주신 대로 `calculateItems` 에 접근제어자 추가했습니다.
- `LinkedList`클래스에도 변수들을 읽기 전용으로 만들었습니다. 

**2. 헤드와 테일 노드를 보여주는 메서드 추가**
- 접근제어자를 추가 하며, `CalculatorItemQueue`클래스에 헤드와 테일의 노드 정보를 보여주는 메서드를 생성했습니다.

**3. 링크드 리스트 테스트하는 테스트 파일 생성**
- 기존에는 `CalculatorItemQueueTests` 파일 안에서 링크드 리스트를 테스트 하였습니다. 코드가 길어져서 `CalculatorItemQueue`클래스에 대한 테스트와 `LinkedList`클래스에 대한 테스트를 구분 시켜주는게 좋을 것 같아서 `LinkedListTests` 파일을 생성했습니다.

**4. peak 메서드 제거**
- 계산기 동작설명의 데모를 보면 계산기 버튼을 누를 때 마다 누른 값들이 위에 표시됩니다. 원래는 `peak` 메서드를 이용해 이 기능을 구현해주려고 했습니다. 생각해보니 `enqueue` 메서드로 처리할 수 있을 것 같아 peak 메서드를 삭제했습니다.

---

**<Linked List 설명>**
1. 단방향 연결 리스트로 구현
- 양뱡향 연결 리스트와 단방향 연결 리스트 중에 어떤 것으로 구현할 지 고민했습니다.
이번 프로젝트에서는 중간에 데이터를 추가 및 삭제하는 과정이 필요 없을 것 같아 단방향 연결 리스트로 구현했습니다.

2. 변수 설명
- `head` : 노드의 가장 처음 부분을 가리키는 변수입니다.
- `tail` : 노드의 가장 마지막 부분을 가리키는 변수입니다.
- `previousness` : 추가한 노드의 바로 전에 있는 노드를 가리키는 변수입니다.
- `count` : 링크드 리스트안에 들어있는 노드의 개수를 뜻하는 변수입니다.
(`previousness`와 `count`는 노드를 삭제하는 과정에서 사용하기 위해 만들었습니다.)

2022-05-18 19:57 UTC, ehgud0670 requested changes
고생 많으셨습니다. 그럼 피드백 반영 부탁드릴게요. 다 하셨으면 말씀 주세요 😄

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
큐에는 필요없는 메소드같은데 지워도 되지 않을까요? 큐를 사용하는 사용자는 내부적으로 링크드리스트를 구현했다는 것을 알 필요가 없을 것 같아서요 🤔

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        if isEmpty() {
isEmpty도 Array의 isEmpty처럼 파라미터가 없으니 연산프로퍼티로 구현해도 됩니다. 참고로 말씀드려요~ :)

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Node/LinkedList.swift
> +    func moveToPreviousness() {
이건 내부에서만 사용하는 메소드같은데 private 을 붙이는 게 어떨까요?

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func resetQueue(){
```suggestion
    mutating func resetQueue() {
```

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Node/LinkedList.swift
> +    func delete() -> T? {
delete 의 반환값을 매번 쓰지 않는다면 `@discardableResult`를 쓰셔도 되겠습니다.

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Node/LinkedList.swift
> +    private(set) var previousness: Node<T>?
Node의 next가 있는것처럼 Node 안에 prev를 프로퍼티로 추가하고 previousness는 지우는게 어떨까요?
LinkedList에는 head, tail만 있고 previousness는 없는게 더 가독성이 좋아 보이네요 :)

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Node/LinkedList.swift
> +    private(set) var count = 0
count를 값을 매번 구하는 연산프로퍼티로 구현해서 버그가 아예 안나게 하는 것도 좋은 방법일 듯 합니다 :)
아니면 insert나 delete를 실제로 하고 값을 올리고 내렸으면 좋겠습니다. 현재는 delete 메소드를 여러번 호출하면 count값이 마이너스가 되겠네요.

2022-05-18 19:57 UTC, ehgud0670 commented on Calculator/Calculator/Node/LinkedList.swift
> +        count -= 1
여기 보시는 것처럼 count가 마이너스 값이 될 수 있겠네요.
테스트를 했음에도 왜 이런 상황이 발생했을까요? 실패 케이스(예외 케이스)에 대한 테스트는 하지 않았기 때문입니다.
예외 케이스(ex. 값이 없어도 여러번 delete 한 경우)에 대해서도 메소드나 프로퍼티가 어떤 값을 반환할지 테스트 해보세요 :)

2022-05-18 20:04 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
```suggestion
    mutating func reset() {
        calculateItems.reset()
    }
```
=> 네이밍 중복인 것 같아 위처럼 제안드려봅니다. 이미 큐이므로 reset 으로만 네이밍해도 이해 가능하고, 이미 링크드리스트이므로 reset 으로만 네이밍해도 이해 가능해서요!

2022-05-19 08:24 UTC, seohyeon2 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
`showHead()` 랑 `showTail()` 삭제 후, 
큐안에 들어 있는 items를  다 보여주는 `displayItems()` 메서드를 구현하였습니다😌

2022-05-19 08:24 UTC, seohyeon2 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        if isEmpty() {
연산 프로퍼티로 수정했습니다~

2022-05-19 08:26 UTC, seohyeon2 commented on Calculator/Calculator/Node/LinkedList.swift
> +    func moveToPreviousness() {
단방향 링크드 리스트에서 양뱡향 링크드 리스트로 바꾸면서 이 메서드를 삭제하였습니다!
추후에 기능 구현시 내부에서 사용하는 메서드는 꼭 `private` 처리하겠습니다😊

2022-05-19 08:26 UTC, seohyeon2 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func resetQueue(){
섬세한 피드백..감사합니다🥺👍

2022-05-19 08:27 UTC, seohyeon2 commented on Calculator/Calculator/Node/LinkedList.swift
> +    func delete() -> T? {
덕분에 새로운 속성에 대해서 알게 되었습니다!
감사합니다🥳

매번 반환값 사용하지 않는 메서드에 대해서 `@discardableResult` 처리해주었습니다.

2022-05-19 08:29 UTC, seohyeon2 commented on Calculator/Calculator/Node/LinkedList.swift
> +    private(set) var previousness: Node<T>?
`previousness`를 `Node` 클래스로 이동하면서 단방향에서 양방향 링크드 리스트로 수정했습니다😃

2022-05-19 08:30 UTC, seohyeon2 commented on Calculator/Calculator/Node/LinkedList.swift
> +    private(set) var count = 0
조건문을 사용하여 메서드를 여러번 호출해도 count 값이 마이너스가 되지 않게 수정했습니다☺️

2022-05-19 08:31 UTC, seohyeon2 commented on Calculator/Calculator/Node/LinkedList.swift
> +        count -= 1
예외 케이스..!  앞으로 예외 케이스도 꼭 테스트해보겠습니다!!!🔥

2022-05-19 08:36 UTC, seohyeon2 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
`CalculatorItemQueue` 안에 메서드들은 제안해주신 네이밍으로 수정했습니다!
`LinkedList` 안에 메서드들을 기존 배열 사용시 썼던 메서드명과 동일하게 수정했습니다😌
ex) reset -> removeAll

2022-05-19 09:49 UTC, ehgud0670 approved these changes
현이 고생 많으셨습니다 ㅎㅎ 
Step2 진행하세요! 💪

2022-05-19 09:49 UTC, ehgud0670 commented on Calculator/Calculator/Node/Node.swift
> +    var next: Node?
여기도 제네릭 쓰셔서 통일감을 주시면 좋을 것 같아요!

2022-05-19 09:49 UTC, ehgud0670 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
여기 부분도 링크드 리스트인 calculateItems의 값들을 반환하는 메소드를 구현해 리팩토링 해보세요
그럼 head tail도 외부에서 참조할 필요가 없을 듯 합니다. 
추가로 내부에서 사용하는 리스트도 프로토콜 타입(ex. `InnerList`)으로 의존성을 덜면 더 좋을 듯 합니다 :)

2022-05-19 09:49 UTC, merged