계산기 [STEP 1] BaekGom
yagom-academy/ios-calculator-app pull request #240
Opened 2022-05-17 09:03 UTC by Baek-Gom-95

안녕하세요 쿠마! @leejun6694  계산기 첫번째 PR 보내드립니다 잘부탁 드려요! 😊

# [STEP 1] 기능 및 코드 설명 🙂
- isEmpty: 큐가 비어있는지 확인하는 프로퍼티
- peek: 가장 앞에있는 큐가 무엇인지 알려줍니다
- enQueue: 큐 끝에 새로운 큐를 추가
- deQueue: 가장 먼저 들어온 앞의 큐 제거하고 제거한 큐 반환하기

# [STEP 1] 고민한점 및 해결방안 🤔
### 고민한점
### 테스트를 세분화:
- 테스트 세분화를 생각하면 할수록 점점 많아지는거 같습니다. 그러다 보니 끝이 없어서 제 생각선에서 일어날수 있는일들을 절충해서 세분화를 해습니다 

### 배운개념 💡

- Queue 
    * 일반적인 하나의 스택을 사용해서 하는 방법이 있고 두개의 스택(deQueue,enQueue) 따로 스택을 만들어서 하는 방법도 있다

- target 설정
    * 테스트 파일과 파일간의 타겟 설정을 하지않으면 오류가 발생합니다.

2022-05-17 17:09 UTC, leejun6694 requested changes
`List 자료구조`를 사용해서 step 을 진행해야 합니다.
확인 부탁드려요 : )

2022-05-17 17:09 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func enQueue(_ element: T){
`enqueue`, `dequeue` 는 올 소문자로 많이 사용하고 있습니다ㅎㅎ
참고 부탁드려요~

2022-05-17 17:09 UTC, leejun6694 commented on Calculator/Calculator/Protocols/CalculatorItem.swift
> +protocol CalculateItem {
빈 `protocol` 을 만들어준 이유가 있나요?

2022-05-19 06:36 UTC, Baek-Gom-95 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func enQueue(_ element: T){
새로운 정보 감사합니다 😊 소문자로 변경하였습니다

2022-05-19 06:39 UTC, Baek-Gom-95 commented on Calculator/Calculator/Protocols/CalculatorItem.swift
> +protocol CalculateItem {
요구사항에 빈 프로토콜로 만들어 놓으라고 해서 만들어 두었습니다 🙂

2022-05-19 14:06 UTC, leejun6694 approved these changes
리뷰 반영 감사합니다 : )
몇가지 코멘트를 추가했는데 확인해보시고, 수정을 진행하게 되면 step 2 에서 부탁드려요~~!

2022-05-19 14:06 UTC, leejun6694 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +    var headIsEmpty: Bool {
Queue 에서 구현하신 것처럼 `isEmpty` 로 네이밍해도 괜찮을 것 같네요 : )

2022-05-19 14:06 UTC, leejun6694 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +    var firstPeek: Node<T>? {
요것도요~!

2022-05-19 14:06 UTC, leejun6694 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +        while node?.next != nil {
`tail` 을 사용하면, 탐색 없이 구현 가능합니다ㅎㅎ
이 부분도 참고해주세요~

2022-05-19 14:06 UTC, leejun6694 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +        if head == nil { return nil }
이 코드는 없어도 구현 결과가 똑같을 것 같습니다 : )

2022-05-19 14:06 UTC, leejun6694 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +        head = nil
👍👍

2022-05-19 14:07 UTC, merged

2022-05-20 05:53 UTC, Baek-Gom-95 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +        if head == nil { return nil }
제거 해도 같은 결과인거 같아 제거 했습니다 😊

2022-05-20 05:56 UTC, Baek-Gom-95 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +    var headIsEmpty: Bool {
네이밍 isEmpty로 변경했습니다

2022-05-20 05:57 UTC, Baek-Gom-95 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +    var firstPeek: Node<T>? {
네이밍 peek로 변경했습니다 좋은 의견 감사합니다 ☺️

2022-05-20 06:34 UTC, Baek-Gom-95 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +        while node?.next != nil {
구현해 보니 같은 결과가 나오고 더 코드가 더 간결해 지는거 같아서 변경했습니다 🙂