계산기 [STEP1] KayAhn
yagom-academy/ios-calculator-app pull request #241
Opened 2022-05-17 09:21 UTC by KayAhnDS

🍎@ryan-son 
안녕하세요 Ryan! 첫번째 PR입니다!
잘 부탁 드립니다🙇🏻‍♂️

## 📖 고민한점 및 큐 구현 방법

- Queue를 어떻게 구현할까 생각했습니다.
    - 배열
    - 단방향 리스트
    - 양방향 리스트
- 세가지 중 배열을 이용해 큐를 구현했습니다.
    - 단방향 리스트를 선택하지 않은 이유.
        - 계산기 특성상 특정 값을 검색하는것이 중요하지 않고 결국 넣은 순서대로 나와야 하기 때문에 이부분에서 배열이 더 적합하다 판단했습니다.
    - 양방향 리스트를 선택하지 않은 이유.
        - 양방향 리스트로도 구현을 해보았는데 head와 tail 양방향에서 접근 및 추가, 삭제 가능하다는 점이dequeue의 기능을 해 제외하였습니다.
- 배열을 선택한 이유
    - 가장 앞의 요소를 제거하는 작업, head를 다음으로 넘기는 작업 → 각각 O(1) 소요.
        - 배열이 하나 필요한점
        - 재배치가 필요없는점

## 📖 궁금한점

- 양방향 리스트에서..

```swift
final class Node<T> {
    var prev: Node?
    var data: T?
    var next: Node?
    
    init(prev: Node? = nil, data: T?, next: Node? = nil) {
        self.prev = prev
        self.data = data
        self.next = next
    }
}

final class DoubleLinkedList<T: Equatable>: CalculateItem {
    private var count: Int = 0
    private var head: Node<T>?
    private var tail: Node<T>?
}
```

- 위의 코드에서
    
    ```swift
    private var count: Int = 0
    // private static var count: Int 로 하려했습니다.
    ```
    
    - 이부분을 private static var count: Int로 선언해서 노드가 생길 때 마다 하나씩 추가하려고 했는데 타입저장프로퍼티에 제네릭 타입이 들어가면 안된다는데 그 이유가 궁금합니다!

2022-05-17 18:38 UTC, ryan-son requested changes
@KayAhnDS

안녕하세요 케이~ Step 1 수행하시느라 고생 많으셨습니다!

>## 📖 고민한점 및 큐 구현 방법
> - Queue를 어떻게 구현할까 생각했습니다.

근거가 타당하네요👏! 말씀하신 것처럼 계산기에서는 특정 인덱스의 값을 탐색할 필요도, 중간에 위치한 값을 수정하거나 값을 추가/삭제할 소요가 없으니 적절한 해결책을 선택하셨다 판단됩니다. 개별 코멘트에서 더 자세히 다루고 있지만, 현재 적용하신 방법에서 head의 위치를 변경하는 것은 비용이 매우 적으나 [`removeFirst(_:)`](https://developer.apple.com/documentation/swift/array/2886730-removefirst)를 수행하는 것은 배열의 크기에 따라 비용이 적지 않을 수 있다는 것에 유의하셔야 합니다. 현재 적용된 내용으로는 최초 dequeue 이후에는 `removeFirst(_:)`를 지속적으로 수행하고 있으며, removeFirst 연산 이후 head의 위치를 초기화해주지 않고 있어 로직 상의 문제도 있을 것으로 판단됩니다. 사실 이런 문제들을 잡기 위해 TDD와 같은 기법을 적용하는 것이니 문제가 있을 수 있는 더 다양한 테스트 케이스를 고안하셔서 추가해보시길 바랍니다~ 💪테스트를 작성할 때는 번거로워도 앞으로 생길 수 있는 문제를 지속적으로 검증해준다고 생각하면 오히려 시간을 절약하는 것이거든요. 😊

> ## 📖 궁금한점
> - 이부분을 private static var count: Int로 선언해서 노드가 생길 때 마다 하나씩 추가하려고 했는데 타입저장프로퍼티에 제네릭 타입이 들어가면 안된다는데 그 이유가 궁금합니다!

타입프로퍼티로 고려하셨다면 `CalculatorItemQueue.count`와 같은 방식으로 접근하게 되겠네요. 그럼 있을 수 있는 모든 타입에 대해 count는 동일한 값을 제공해야 할까요? 예를 들어, `CalculatorItemQueue<String>.count`, `CalculatorItemQueue<Int>.count`, `CalculatorItemQueue<Double>.count`과 같이 무수한 케이스가 있을 수 있겠네요. 이런 경우에 대해 언어적으로 정책을 설정하기 모호하니 제한한 것으로 예상되네요. 아래와 같이 제네릭을 특정 타입으로 제한하면 타입 프로퍼티를 사용하실 수 있을거에요.

```swift
extension CalculatorItemQueue where T == Int {
    static var count: Int = 0
}
```

학습할 내용도 많으셨을텐데 빠르게 수행하셨네요. 피드백 참고하셔서 한 번 더 힘내봅시다! 💪
궁금한 것이 있으시거나 도움이 필요하시면 언제든지 찾아주세요~ 😉

2022-05-17 18:38 UTC, ryan-son commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_isFrontMethodWorksAsExpected() throws {
몇 번 언급드렸지만 테스트 메서드는 이름이 정말 중요해서 다시 말씀드릴게요. `front가 예상한대로 동작한다`라는 스펙으로는 기존 팀원들 이외 새로 합류하는 인원들을 이해시키기 어려울거에요. front가 어떤 상황에서 무슨 일을 하는 친구인지, 특정 상황에서 다르게 행동하는 경우가 있는지 (Queue에 요소가 있을 때와 없을 때 작동이 다르죠?)에 따라 테스트 케이스를 분리해주고 명확한 이름을 지어주는 것이 장기적으로 보았을 때 좋습니다!

극단적으로 케이가 이 앱을 만드는 회사에서 이탈했고, 제가 새로 합류하여 유일한 팀원이라면 이 테스트 타입을 보고 이렇게 생각할거에요..
```
큐가비어있는가 테스트 -> ?
큐가 nil인가 테스트 -> ?
count 메서드가 적절히 동작하는가 테스트 -> '적절히' 동작하는 것은 무엇인가? 모든 상황에서 동일하게 동작하는가?
front 메서드가 예상한대로 동작하는가 테스트 -> '예상한대로'..? 나는 예상되지 않는걸.. ㅠ
rear 메서드가 예상한대로 동작하는가 테스트 -> ㅠㅠ
clear 메서드가 예상한대로 동작하는가 테스트 -> ㅠㅠㅠ
```

2022-05-17 18:38 UTC, ryan-son commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
앞서 언급한 given (상황), when (행동), then (검증)의 형식으로 구성하면 테스트 케이스의 설명을 명확히 할 수 있어요.

```swift
// given (큐에 요소가 있을 때~)
// queue의 초기값을 이니셜라이저 등을 통해 세팅 [1, 2, 3]

// when (clear()를 수행하면~)
sut.clear()

// then (큐의 요소가 모두 제거된다)
XCTAssertTrue(sut.isEmpty)

=> given / when / then만으로 메서드 이름 작명 가능
```

2022-05-17 18:38 UTC, ryan-son commented on README.md
> +![CalculatorUML](https://user-images.githubusercontent.com/40224884/168769932-a942764c-5a44-4d04-b7a5-d55e61d8c8a8.png)
![image](https://user-images.githubusercontent.com/69730931/168881371-4b0c54d9-0c98-4fbf-836c-77f528f1a53c.png)

`count`, `isEmpty`, `front`, `rear` 등 연산프로퍼티는 여러 라인의 코드로 구성되어 있어도 결국 **프로퍼티**이니 변수 영역으로 옮길 수 있을 것 같아요. 추가로 프로퍼티들의 타입과 간략화된 메서드의 매개변수/매개변수타입/반환타입까지 작성된다면 더 유익한 다이어그램이 될 것 같네요~

2022-05-18 14:30 UTC, KayAhnDS commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		};
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/6b4cb932e17201078a71d1bc39a537ed077b5ec2

리소스 그룹을 추가해서 나눠주었습니다!

2022-05-18 14:34 UTC, KayAhnDS commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		};
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/e8e091120dcbdc8294456d52266bdcf86825a8d8

사실 이부분은 AppDelegate와 SceneDelegate 두가지 파일이 하는 역할을 찾아보았습니다.
먼저 AppDelegate는 어플리케이션의 entry point역할과 Life Cycle관리,
SceneDelegate는 화면에 무엇을 보여줄지 관리하는 역할인데 두 파일의 공통점을 찾지 못해 "Delegates" 라는 안타까운 이름으로 그룹화 했습니다..

2022-05-18 14:34 UTC, KayAhnDS commented on Calculator/Calculator/Model/CalculateItem.swift
> +import Foundation
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/34f0652198ea41dd3f9c720c059caf2ec9a8e65e

제거 해주었습니다!

2022-05-18 14:37 UTC, KayAhnDS commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var head: Int = 0
감사합니다!

2022-05-18 14:40 UTC, KayAhnDS commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/6e3abc3d2b938996070ec0028c2b0d1d9021c360

코멘트 해주신 부분을 찬찬히 읽어보니 더 가독성이 좋은것 같아, 큐의 연산 프로퍼티와 메서드를 수정했습니다!

2022-05-18 14:41 UTC, KayAhnDS commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/cc6641b22ae0114f3e1bf2c52ad0bfd720311ceb

말씀해 주신 부분 및 removeFirst()는 굳이 필요하지 않을것 같아 수정했습니다.

2022-05-18 14:43 UTC, KayAhnDS commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/f2291fa9b34926d2dea24701384f89d5008cb57b

좋은 정보 감사합니다. 앞으로는 적절한 내장함수를 이용해 작성하는 습관을 들여보겠습니다~!

2022-05-18 14:50 UTC, KayAhnDS commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
현재의 코드에서 제가 작성한 연산 프로퍼티들은 전부 get으로 구현이 되어 있어 보는 저도 혼동이 될것 같습니다.
일반적인 상황에서 연산 프로퍼티는 다른 저장속성에 의존해 연산 하는 방식이라고 알고 있습니다 또 메서드는 다른 저장 프로퍼티와 상관없이 독단으로 사용할 수 있다라고 알고있습니다.

2022-05-18 15:12 UTC, KayAhnDS commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
테스트 메소드가 실행되기 전에 setUpWithError이 실행되고

테스트 메소드가 실행 된 후 tearDownWithError가 호출됩니다.

2022-05-18 15:22 UTC, KayAhnDS commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_isQueueEmpty() throws {
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/8b05ccdef3a5a08e68d5ce774ca3927ce8c0d7b8

좋은 정보 주셔서 수정했습니다!

2022-05-18 15:25 UTC, KayAhnDS commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(result, nil)
좋은 정보 감사합니다!

2022-05-18 15:26 UTC, KayAhnDS commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/307159802894c6a2a6fcc344a7411e867da6c7dc

수정했습니다!

2022-05-18 15:31 UTC, KayAhnDS commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/241/commits/307159802894c6a2a6fcc344a7411e867da6c7dc

마찬가지로 수정했습니다! 감사합니다!

2022-05-18 15:50 UTC, KayAhnDS commented
@ryan-son
남겨주신 코멘트를 기반으로 수정 했고 각각 수정사항은 코멘트로 남겨두었습니다!
좋은 리뷰 감사합니다!

2022-05-18 16:57 UTC, ryan-son commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		};
Delegate라는 형식의 이름은 `UITableViewDelegate`, `UICollectionViewDelegate` 등 앞으로 많이 마주치게 될텐데요, `AppDelegate`와 `SceneDelegate`는 말씀해주신 것처럼 앱의 엔트리 포인트와 Scene Life Cycle 관리라는 측면에서 굉장히 중요한 역할을 수행합니다. 두 친구를 그룹핑할 때 흔히 보이는 네이밍은 `App`, `Application`, `Entries`와 같은 것이 있어요.

2022-05-18 17:14 UTC, ryan-son commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
그럼 dequeue를 수행할 때마다 head 앞에 불필요한 공간이 계속해서 생기니 메모리가 낭비될 수도 있을 것 같은데, 이 점에 대해서는 어떻게 생각하세요~?

2022-05-18 17:16 UTC, ryan-son commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
잘 알고계시네요~ 이 외에도 테스트 시 활용할 수 있는 메서드를 아래 아티클에서 소개하고 있으니 관심 있으시면 한 번 읽어보세요~
- [Set Up and Tear Down State in Your Tests - Apple Developer](https://developer.apple.com/documentation/xctest/xctestcase/set_up_and_tear_down_state_in_your_tests)

2022-05-18 17:46 UTC, ryan-son approved these changes
케이~ 피드백에 대해 많이 고민해보시고 반영하신 흔적이 느껴졌습니다. 고생 많으셨어요~

dequeue 로직에 대한 내용을 제외하고는 의견 드릴 내용이 크게 없어 머지하도록 하겠습니다.
새로 피드백 드린 내용은 참고하셔서 다음 스텝에 반영하시거나 의견 부탁드릴게요.

계속해서 화이팅하세요~ 💪

2022-05-18 17:46 UTC, ryan-son commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
적절한 시점마다 `removeFirst()`를 수행하지 않으면 dequeue가 여러번 수행될수록 큐는 필요 이상의 메모리를 차지할 수 있을 것 같은데, 케이의 의견이 궁금합니다~!

2022-05-18 17:46 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        // (큐에 요소 "1","2","3"이 있을때)
사실 주석으로 한글 작성은 안하셔도 돼요. 저는 이해를 도우려고 한글로 작성한 것이고, 실제로는 코드로 내용을 설명하시면 됩니다!

2022-05-18 17:46 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_isCountMethodReturnsTotalNumberOfElement() {
is도 마찬가지네요~

2022-05-18 17:46 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_isClearMethodWorksAsExpected() {
`test_clearRemovesAllElementsInQueue()` 와 같은 이름은 어떠신가요~?

2022-05-18 17:47 UTC, merged