계산기 [STEP1] Groot
yagom-academy/ios-calculator-app pull request #244
Opened 2022-05-17 12:24 UTC by Groot-94

@leejun6694
안녕하세요 쿠마... !
계산기 첫 PR을 보냅니다... 이번 프로젝트는 정말 멘붕입니다.. 
정말 많이 부족함을 느끼네요! 과감하게 리뷰 해주시면 더 발전하겠습니다!

# 📌 작업 내용
## CalculatorItemQueue
- Linked List를 사용한 큐를 구현했습니다.
- 이번 계산기 앱에서 필요한 기능을 3가지로 생각했습니다.
    - 1. 순서대로 값을 넣기
    - 2. 가장 앞에있는 값을 빼기
    - 3. 모든 값을 삭제하기
    
> 제가 분석한 내용은 아래와 같습니다.
계산기에 입력되는 숫자는 연산자 버튼이 눌리고 나서 큐에 들어갑니다. 
계산기에 입력되는 연산자는 숫자 버튼이 눌리고 나서 큐에 들어갑니다.
입력된 값(숫자, 연산자)을 모두 지우는 버튼이 눌리면 큐의 값을 모두 제거합니다.
입력된 값을 하나만 지우는 버튼이 눌리면 큐에 저장된 값이 아니라 마지막에 입력한 값이 지워집니다.

- 이렇게 정리해서 기능을 3가지라고 생각했습니다.

- 다음은 TDD를 위한 메서드입니다.
    - 1. first값을 확인하기
    - 2. 큐가 비어있는지 확인
## LinkedList
- 큐에서 사용할 기능과 동일하게 구현했습니다.
    - 1. 순서대로 값을 넣기
    - 2. 가장 앞에 있는 값을 빼기
    - 3. 모든 값을 삭제하기

- 다음은 TDD를 위한 메서드입니다.
    - 1. first값을 확인하기
    - 2. 큐가 비어있는지 확인
---
# 📌 고민한 점
## 어떤 방식의 List를 사용할지 고민했습니다.
- 배열을 사용할 경우 5개의 값을 넣은 상태에서 만약 1개의 `값을 빼면 그 크기가 자동으로 줄어드는지`에 대해 의문이 생겼고, swift에서 동적 배열의 크기를 어떻게 처리하는지 찾아봤으나 명확하게 답변을 찾기가 어려웠습니다.
- 여러 가지 방법을 찾아보던 중 클래스 타입의 노드를 만들고, 그 노드를 이용해서 Linked List 타입을 만들어서 사용하는 방법을 찾았습니다. `어디에서도 참조하지 않으면 자동으로 메모리에서 사라지는 특징을 이용한 값의 제거방법이 좋다고 생각해서` 사용하게 되었습니다.

## TDD 대해 고민했습니다. 
### 1. commit 단위
- TDD의 세가지 단계에서 `각 단계마다 commit을 해야할지` `함수의 기능 구현을 중심으로 commit을 해야할지` 고민을 했습니다.

### 2. 은닉화
- 처음 코드를 정의하는 부분에서 은닉화를 하지 않고 TDD 이후에 은닉화를 하는 방식으로 진행했을 때 문제가 있었습니다.

- 발생한 문제
    - TDD 과정에서 함수의 기능이 구현되지 않은 상황에서 테스트 코드를 작성하다 보니 프로퍼티에 접근이 필요한 부분이 있었습니다. 은닉화 이후에 테스트 코드에서 은닉화된 프로퍼티들은 찾지 못했기 때문에 오류가 났습니다.
- 해결방법
    - 프로퍼티 접근을 위한 함수를 만들고 테스트 코드에서 그 함수를 호출하는 방법으로 처리했습니다.
    - 테스트 코드에서 기능 구현을 아직 하지 않은 함수 A의 호출이 필요할 때 그 테스트 코드는 A 함수 기능을 구현 후에 테스트하는 방식으로 수정했습니다.
---
# UML
## Class Digram
![](https://i.imgur.com/FqKona7.png)

2022-05-17 17:21 UTC, leejun6694 requested changes
테스트 코드까지 작성을 잘해주셨습니다 bb
몇 가지 코멘트를 남겼는데, 확인 부탁드려요 : )

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/CalculatorItem.swift
> +protocol CalculatorItem {}
빈 `protocol` 을 만들어준 이유가 있나요?

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/LinkedList.swift
> +//
여기만 줄바꿈이 없네요..!

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/LinkedList.swift
> +        head = nil
👍

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/LinkedList.swift
> +        return false
위 조건을 한줄로도 구현이 가능합니다ㅎㅎ
가독성도 많이 떨어지지 않는데, 한번 구현해보는건 어떨까요?

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/LinkedList.swift
> +        if head == nil {
swift 는 일찍 method 를 끝내는 경우에 guard 를 사용할 수 있습니다.
이 부분도 참고해주세요~

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/LinkedList.swift
> +        while node?.next != nil {
while 문을 사용하지 않고도 구현이 가능합니다~
어떤 방법이 있는지 알고 계실까요!?

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/CalculatorItemQueue.swift
> +    mutating func deQueue() -> T? {
일반적으로는 올 소문자를 사용합니다~!
`enqueue`, `dequeue`

2022-05-17 17:21 UTC, leejun6694 commented on Calculator/Model/LinkedList.swift
> +    func confirmFirst() -> T? {
method 명을 개성있게 작성해주셨는데, 이미 널리 알려진 자료구조의 경우엔 이를 확인해보는 것도 좋을 것 같습니다.
`confirmFirst`, `takeOutFirst`
두 method 모두 확인 부탁드려요~!

2022-05-18 01:41 UTC, Groot-94 commented on Calculator/Model/LinkedList.swift
> +//
수정했습니다!
[5571fe7](https://github.com/yagom-academy/ios-calculator-app/pull/244/commits/5571fe7f17df176ca638a10574435246933faf46)

2022-05-18 01:45 UTC, Groot-94 commented on Calculator/Model/CalculatorItem.swift
> +protocol CalculatorItem {}
Step1 요구사항에서 프로토콜에 대한 내용이 있었습니다.

```
CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다.
CalculateItem 프로토콜은 빈 프로토콜입니다.
```

계산기의 동작과정을 보면서 사칙연산에 대한 메서드가 들어가지 않을까 생각은 했었습니다.
하지만 Step1의 요구사항에 집중하자는 생각으로 빈 프로토콜을 채택하도록 했습니다.

2022-05-18 01:54 UTC, Groot-94 commented on Calculator/Model/LinkedList.swift
> +        return false
처음에 삼항 연산자를 사용해서 구현하려고 했으나, return을 하는 부분에서 오류가 났었습니다. 
```swift
head == nil ? return true : return false
```
그래서 단순하게 삼항연산자에서 return을 할 수 없구나 라고 생각하고 리팩토링 없이 넘어갔습니다.

하지만 쿠마의 리뷰를 보고 다시 생각해보니 삼항연산자는 기본적으로 return을 하는 구조였습니다.... 그래서 수정해봤습니다!

[b9ddebf](https://github.com/yagom-academy/ios-calculator-app/pull/244/commits/b9ddebffd49ceada50a8413416362c9eb5d7a702)

2022-05-18 01:55 UTC, Groot-94 commented on Calculator/Model/LinkedList.swift
> +        if head == nil {
수정했습니다!
[b9ddebf](https://github.com/yagom-academy/ios-calculator-app/pull/244/commits/b9ddebffd49ceada50a8413416362c9eb5d7a702)

2022-05-18 01:55 UTC, Groot-94 commented on Calculator/Model/CalculatorItemQueue.swift
> +    mutating func deQueue() -> T? {
수정했습니다!
[b9ddebf](https://github.com/yagom-academy/ios-calculator-app/pull/244/commits/b9ddebffd49ceada50a8413416362c9eb5d7a702)

2022-05-18 01:55 UTC, Groot-94 commented on Calculator/Model/LinkedList.swift
> +    func confirmFirst() -> T? {
수정했습니다!
[b9ddebf](https://github.com/yagom-academy/ios-calculator-app/pull/244/commits/b9ddebffd49ceada50a8413416362c9eb5d7a702)

2022-05-18 01:59 UTC, Groot-94 commented on Calculator/Model/LinkedList.swift
> +        while node?.next != nil {
쿠마가 말씀하시는 방향이 단순하게 append 함수를 수정해서 while 문을 사용하지 않는 방식이라면 .. 저는 사실 잘 모르겠습니다..

만약 그게 아니라 가장 마지막 노드 정해주고 그 노드를 사용해서 값을 추가하는 방식이라면 구현해보도록 하겠습니다!

2022-05-18 02:01 UTC, Groot-94 commented
@leejun6694 빠른 리뷰 감사합니다!
리뷰에 대한 답변과 리팩토링을 완료 했습니다. 확인부탁드립니다 :)

2022-05-18 02:12 UTC, leejun6694 commented on Calculator/Model/LinkedList.swift
> +        while node?.next != nil {
네 ㅎㅎ tail 을 이용하는 방법입니다~!
불필요한 탐색을 줄여줄 수 있습니다 : )

2022-05-18 04:45 UTC, Groot-94 commented on Calculator/Model/LinkedList.swift
> +        while node?.next != nil {
tail 프로퍼티를 추가해서 수정해봤습니다!
[3b2f45f](https://github.com/yagom-academy/ios-calculator-app/pull/244/commits/3b2f45f0cff2631bbc8c9e39b247b31afc537c03)

2022-05-19 02:25 UTC, merged