계산기 [STEP1] Kiwi
yagom-academy/ios-calculator-app pull request #245
Opened 2022-05-17 12:35 UTC by kiwi1023

@jryoun1 안녕하십니까 제이크! 첫 PR 보냅니다!
이번 프로젝트는 정말 하나도 모르겠어서 기본 부터 차근차근 공부를 한다음 진행을 하느라 시간이 조금 늦어졌습니다.. 죄송합니다.. 하지만 한편으로는 나름 천천히 공부를 하고 구현을 하니 앞선 프로젝트 보다 이해도는 올라가고, 코드를 짜는 시간 자체는 줄어 들었던 것 같습니다. ㅎㅎ
아무쪼록 잘 부탁 드리겠습니다 ~!!!!!! 

## UML
![스크린샷 2022-05-17 오후 8 57 25](https://user-images.githubusercontent.com/101521502/168805632-3434b4e1-94d3-4a7b-a6e2-12a86c3452df.png)

## [STEP 1] 고민한점 및 해결방안 🤔

1. 양뱡향 or 단반향?

이번 계산기 프로젝트 STEP1을 구현할때 까지는(추후 STEP과정에서는 모르겠지만...) 양뱡향 노드를 사용할 이유를 찾지 못하였습니다.. 그러나 다른 동기들이 양뱡향으로 구현하시는 걸 보고, 많이 흔들렸지만.. 지조있게 단방향으로 구현을 하였습니다! 

2. Array or 연결리스트 ?

이번 프로젝트에서 큐를 배열로 구성할 경우 dequeue과정에서 오버헤드가 발생한다는 단점이 있다는 사실을 알게 되었습니다. 하지만 배열이나 연결리스트나 별 차이(사람이 느낄정도의 차이) 없이 구현될거라는 생각이 들기도 하지만... 연결리스트에 공부할 좋은 기회가 될 것 같아  연결리스로 구현을 하게 되었습니다 !

3. TDD

테스트 관련해서는 처음 구현을 해보는 거라 많이 부족할 것 같습니다... 많은 의견 부탁드립니다!!

## 궁금한 점🙋

``` swift
extension Node: Equatable {
    static func == (lhs: Node<T>, rhs: Node<T>) -> Bool {
        lhs === rhs
    }
}
```
Node의 제네릭 타입이 무엇이 될지 모르기 때문에 Equatable을 자동적으로 채택하지 않는 사실을 알고 따로 채택을 해주었습니다. 그런데 이 경우 왜 =를 3개를 써줘야 하는지 궁금합니다!

2022-05-18 12:45 UTC, jryoun1 requested changes
안녕하세요 @kiwi1023 🙋‍♂️
step1 고생 많으셨습니다! 

UML도 자세히 그려주시고, 고민한 점 및 해결방안도 자세히 적어주셔서 좋았습니다. 💯
다만 linkedList라는 자료구조를 선택하신데에 있어서 공부의 목적도 좋지만, 다른 자료구조들과의 비교를 해보고 어떠한 이유로 인해서 사칙연산 큐를 구현할 때 해당 자료구조를 택했는지에 대해서가 부족해서 조금 아쉬웠습니다!

몇 가지 코멘트를 남겨두었으니 확인부탁드려요🙏🏻

### 궁금한 점에 대한 답변
말씀하신 부분에 대해서도 아래 코드 부분에서 코멘트를 남겨두었습니다!

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Controller/AppDelegate.swift
> +//  Created by Kiwi.
좋습니다! 꼼꼼하게 프로젝트의 주인을 변경해주셨네요 🙂

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T> : CalculateItem{
Generic Type을 사용하셨네요 👏
다만 여기서 CalculatItem 뒤에 space가 없는 부분은 다른 곳들과는 다른 컨벤션인거 같은데 확인부탁드려요🙏🏻
또한 `CalculatorItemQueue<T> : CalculateItem` 에서 타입명 이후에 space는 의도하신 걸까요? 
프로젝트에서 전반적으로 통일이 되지 않은 것 같습니다!

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var list = Linkedlist<T>()
외부에서의 접근을 제한해주셨네요👏

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +           }
space에 대한 컨벤션이 프로젝트 전반적으로 통일되지 않은 것 같네요 🥲
이럴때는 아래와 같이 명령어를 사용해서 한 번에 통일하게 할 수 있습니다. 
1. 모든 코드를 선택 (ctrl+a) 
2. 모든 코드 혹은 필요한 부분 드래그를 통하여 선택이 된 상태에서 표준에 맞춰 자동 정렬 (ctrl + I)

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +       }
여기도 컨벤션 확인 부탁드려요! 🙏🏻

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/Nord.swift
> +//  Nord.swift
파일명에 오타가 있는 것 같아요

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/LinkedList.swift
> +            if head == nil {
guard와 if를 사용하는 기준이 있을까요? 🙋‍♂️

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/LinkedList.swift
> +    private(set) var head: Node<T>?
여기도 접근제어를 잘 사용해주셨네요 👏

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/Nord.swift
> +        lhs === rhs
여기가 말씀해주신 부분이군요! 
답변에 앞서서 질문이 있습니다. 🙋‍♂️
먼저 Swift에서는 == 연산자와 === 연산자가 있는데 두 연산자의 차이는 무엇일까요?
또한 여기서 Equatable을 채택해주신 이유는 무엇일까요? 
> Node의 제네릭 타입이 무엇이 될지 모르기 때문에 Equatable을 자동적으로 채택하지 않는 사실을 알고 따로 채택

이라고 해주셨는데, 다른 이유는 없을까요? 👀

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +//  Created by Kiwon Song on 2022/05/17.
왜 여기만 다른 이름이 생겼을까요? 🤔

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +    var sut: CalculatorItemQueue<Int>?
여기서 sut을 옵셔널 타입으로 선언한 이유가 있을까요? 👀

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +        //given
GWT(given, when, then) 형식으로 테스트를 작성해주셨네요 👏
덕분에 가독성이 좋아진 것 같습니다

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/LinkedListTest/LinkedListTest.swift
> +class LinkedListTest: XCTestCase {
구현하신 LinkedList 자료구조도 테스트를 해주셨네요 👏 💯

2022-05-18 12:45 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculateItem.swift
> +protocol CalculateItem {
해당 프로토콜은 나중에 어떤 역할을 하게 될까요? 👀

2022-05-19 03:52 UTC, kiwi1023 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T> : CalculateItem{
수정해주었습니다~!

2022-05-19 03:54 UTC, kiwi1023 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +           }
테스트가 처음이라 진행 과정에서  이런 저런 시도를 하기 위해 코드를 다른 곳에 옮겨 두었다가 다시 붙여넣는 행동을 하다가 이렇게 된 것 같습니다...ㅜㅜ 유의해야겠네요.. 수정했습니다..!

2022-05-19 03:54 UTC, kiwi1023 commented on Calculator/Calculator/Model/Nord.swift
> +//  Nord.swift
변경하였습니다!

2022-05-19 03:55 UTC, kiwi1023 commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +//  Created by Kiwon Song on 2022/05/17.
변경하였습니다!

2022-05-19 03:57 UTC, kiwi1023 commented on Calculator/Calculator/Model/LinkedList.swift
> +            if head == nil {
가독성을 기준으로 구별을 합니다..! 해당 코드에 어떤 것이 가독성을 높일지 판단 하여 선택을 하는 것 같습니다.

2022-05-19 04:06 UTC, kiwi1023 commented on Calculator/Calculator/Model/Nord.swift
> +        lhs === rhs
> Swift also provides two identity operators (=== and !==), which you use to test whether two object references both refer to the same object instance.

스위프트에서 객체를 비교할때는 ===,!==을 사용한다고 나와있네요.. ㅎㅎ

그리고 Equatable을 채택해준이유는 추후 step에서 node의 비교가 필요한 경우(ex. 데이터로 해당 노드를 찾는 경우)가 생길수도 있다는 생각에 채택 해주었습니다.

2022-05-19 04:26 UTC, kiwi1023 commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +    var sut: CalculatorItemQueue<Int>?
테스트 과정에서는 강제 언랩핑을 어느정도 수용한다는 것을 들은 적이 있었으나.. 그냥 뭔가 찝찝해서 옵셔널 처리를 해주고 진행을 하였습니다 ㅎㅎ

2022-05-19 04:53 UTC, kiwi1023 commented on Calculator/Calculator/Model/CalculateItem.swift
> +protocol CalculateItem {
큐와 연산자 간의 delegate 역할을 하지 않을까 생각을 하고 있으나.. 아직 잘 모르겠습니다 ..ㅜㅜ

2022-05-19 05:13 UTC, kiwi1023 commented
이번 프로젝트에서 큐의 구현이 기본 조건이므로 큐 내부에 enqueue와 dequeue 기능을 구현해야 된다고 생각 했습니다. 만약 array로 큐를 구현했을 때 dequeue 과정에서 시간 복잡도가 O(n)이고 또한 배열의 크기를 계속 늘리는 경우 수행 속도가 떨어진다는 점을 알고는 있었습니다. 그래서 이런한 부분에 있어 연결리스트를 사용하는 것에 이점이 있다고 생각했었습니다. 그러나 솔직히 계산기 앱을 구현한 후에 사람들이 앱을 실행하는 과정에서 '오 이앱은 큐를 배열로 구현해서 수행속도가 O(n)이라 앱이 느리구나' 라고 생각 할 정도로 차이가 있을까에 대한 의문을 가졌던 거였습니다 ㅎㅎ

2022-05-19 09:26 UTC, jryoun1 commented on Calculator/Calculator/Model/LinkedList.swift
> +            if head == nil {
guard를 사용하면 빠르게 return 할 수 있다는 장점과 depth를 줄일 수 있다는 장점도 있습니다!
자신만의 기준을 두고 사용하시다니 멋지네요!👍🏻  (어떠한 이유로 가독성이 좋은지에 대해서도 고민해보시면 좋을 것 같습니다!)

2022-05-19 09:27 UTC, jryoun1 commented on Calculator/Calculator/Model/CalculateItem.swift
> +protocol CalculateItem {
ㅎㅎ 좋습니다 해당 부분은 추후 step을 진행하시면서 확인해보시면 좋을 것 같아요 🙂

2022-05-19 09:38 UTC, jryoun1 commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +    var sut: CalculatorItemQueue<Int>?
어떤 부분이 찝찝하다고 느끼셨나요?? 
암시적 추출 옵셔널은 어떤 경우에 사용할까요? 테스트에서 sut 인스턴스 자체가 nil 경우가 있을까요?

물론 옵셔널 처리를 해주면 좋지만 테스트, 혹은 IBOutlet 요소들을 선언할 때와 같이 옵셔널이 아님을 100% 확신할 수 있는 경우에는 (아니라면 그것은 에러니까 처리를 해주는 것이 맞는 경우) 암시적 추출 옵셔널을 사용하셔도 됩니다!

2022-05-19 09:41 UTC, jryoun1 commented on Calculator/Calculator/Model/Nord.swift
> +        lhs === rhs
그렇다면 키위가 위에서 말씀해주신 node의 비교라는 것은 객체를 비교하는 걸까요 아니면 node의 값을 비교하는 걸까요? 👀
객체를 비교한다는 것은 어떤 의미일까요??
이 질문의 대답에 따라서 === 를 구현해줄지 == 구현해줄지 결정할 수 있겠네요!

2022-05-19 09:45 UTC, jryoun1 approved these changes
수정확인했습니다~ 
step1 고생하셨고, 남긴 코멘트는 step2에서 적용해주셔도 될 것 같아요! 
step1 머지하겠습니다 🙂

2022-05-19 09:45 UTC, merged