계산기 [STEP1] Brad
yagom-academy/ios-calculator-app pull request #247
Opened 2022-05-18 08:05 UTC by bradheo65

안녕하세요 도미닉!!😀 @appleceo <br>
계산기 STEP1 PR 요청드립니다!

UML작성과 TDD가 미숙하지만, 따끔한 리뷰 부탁 드립니다!!🤯</br>

### 목차</br>
[1. UML](#UML)</br>
[2. 프로젝트 진행하면서 고민한 점](#프로젝트-진행하면서-고민한-점-🫠)</br>
[3. 프로젝트 진행하면서 경험한 점](#프로젝트-진행하면서-경험한-점-✏️)</br>
[4. 질문하고 싶은 점](#질문하고-싶은-점-🤔)</br>

### UML 📈
---
STEP2 내용에 이번 프로젝트의 UML이 제시되어 있지만, STEP1의 구현 내용을 보면서 스스로 작성해 보았습니다. 

![image](https://user-images.githubusercontent.com/45350356/168969673-62204527-913d-44a5-80d5-c93adf18e9c1.png)

### 프로젝트 진행하면서 고민한 점 🫠
---
1. Queue를 배열, 연결 리스트(단방향, 양방향) 중에서 어떤 것을 선택해서 구현해볼까??
	-	해당 프로젝트(계산기)에서는 리스트에 저장되어 있는 요소를 찾는 기능은 불필요하다는 생각이 들었습니다. 그래서 리스트의 요소를 넣거나, 빼줄떄 오버헤드가 발생되지 않도록 연결 리스트를 이용했습니다.

### 프로젝트 진행하면서 경험한 점 ✏️
---
1.	자료구조 개념에 대한 이해가 부족한 것 같아 다시 공부해보았습니다.<br>
	-	자료구조란?
	- 	선형, 비선형
	-  	큐
	-	배열, 연결 리스트(단방향, 양방향)

2.	프로젝트의 내용과는 다르지만 큐에 저장되어 있는 요소들을 직접 프린트 하거나, 어디에 저장(할당?)되어 있는지 보는 것에 대한 생각해 보았습니다.<br>
enqueue로 데이터를 넣었을 때 Linklist 저장한 요소들 입니다.<br>

- 디버그 영역
<img width="569" alt="image" src="https://user-images.githubusercontent.com/45350356/168982246-90973e1e-f4cd-4a98-bfeb-f0f19321d385.png">

- queue의 요소들을 빈 배열에 넣어 표현해보았습니다.

```swift
mutating func scanTest() {
	var linkedLists: [Any] = []
	
	while head != nuil {
		linkedList.append(head?.data as Any)
		head = hed?.next
	}
	print(linkedLists)
```
![image](https://user-images.githubusercontent.com/45350356/168981785-ec8e83e6-7e07-4023-bb73-2b4637a4f4cb.png)

3.	BreakPont 활용을 해볼수 있는 기회였습니다.
	-	n
	- 	po

### 질문하고 싶은 점 🤔
---
1.	queue를 연결 리스트로 구현하기 위해 Node, LinkedList를 생성했습니다. Node는 class로, LinkedList는 struct로 생성했는데, 저의 생각으로는 Node는 직접적으로 데이터 값이 변경되어야 하기 때문에(실제로 저장하는 data가 있기때문에) class로, LinkedList인 경우 각 함수들의 기능만 복사해서 사용하기(다른 타입에서도 LinkedList의 기능을 복사해서 사용할 수 있어서??) 때문에 struct로 구현을 해주었는데 도미닉은 어떻게 생각하는지 궁금합니다!

2.	1번의 내용과 연관된 내용일수도 있는데, CalculatorItemQueue를 class로 구현한 이유는 Node를 참조해야 되기 때문이라고 생각 됩니다. 이 부분도 도미닉의 의견이 궁금합니다!!

2022-05-18 13:45 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.
@bradheo65 고생하셨습니다.
몇가지 개선할 점 남겨봤습니다.
폴더 별로 파일이 하나씩 인 것은 좀 어색한 것 같네요!

질문에 대한 답변
queue를 연결 리스트로 구현하기 위해 Node, LinkedList를 생성했습니다. Node는 class로, LinkedList는 struct로 생성했는데, 저의 생각으로는 Node는 직접적으로 데이터 값이 변경되어야 하기 때문에(실제로 저장하는 data가 있기때문에) class로, LinkedList인 경우 각 함수들의 기능만 복사해서 사용하기(다른 타입에서도 LinkedList의 기능을 복사해서 사용할 수 있어서??) 때문에 struct로 구현을 해주었는데 도미닉은 어떻게 생각하는지 궁금합니다!
- 오.. 좋은 생각 같아요. 저는 struct 사용을 선호해서 문제가 없다면 이렇게 struct 를 적극적으로 사용하는 것이 좋다고 생각합니다!

1번의 내용과 연관된 내용일수도 있는데, CalculatorItemQueue를 class로 구현한 이유는 Node를 참조해야 되기 때문이라고 생각 됩니다. 이 부분도 도미닉의 의견이 궁금합니다!!
- ㅎㅎ 레퍼런스 타입이 필요하기 때문에 그랬을까요? CalculatorItemQueue 를 구조체로 작성해보는 것은 어떨까요?

2022-05-18 13:45 UTC, AppleCEO commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				A301D2D92834B7CE00A025E3 /* Operator.swift in Sources */,
각 파일들을 만들어준 것 좋습니다! 👍

2022-05-18 13:45 UTC, AppleCEO commented on Calculator/Calculator/Model/LinkedList/LinkedList.swift
> +        }
이왕 비었는지 확인할 거 옵셔널 바인딩을 해보는 것은 어떨까요?

2022-05-18 23:57 UTC, bradheo65 commented on Calculator/Calculator/Model/Protocol/CalculatorItem.swift
> +    // no Item
초기 작성 시 헷갈리지 않도록 주석을 작성 했습니다.. PR 전에 삭제하는 것을 까먹고 있었네요...😱

2022-05-18 23:57 UTC, bradheo65 commented on Calculator/Calculator/Controller/ViewController.swift
> -
🫡

2022-05-19 00:00 UTC, bradheo65 commented on Calculator/Calculator/Model/LinkedList/LinkedList.swift
> +        }
```swift
    mutating func append(data: T?) {
        let newNode = Node(data: data)
        
        guard let node = head else {
            head = newNode
            return
        }

        node.next = newNode
    }
```
으로 옵셔널 바인딩을 해주었습니다.

removeFirst 에서도 동일하게 옵셔널 바인딩을 해볼까? 생각해보았는데, head 값이 직접적으로 삭제가 되기 떄문에 let이 안된다고 예상하고 코드를 작성해보았는데.. 당연히 에러가 나오더라구요..

2022-05-19 00:03 UTC, bradheo65 commented on Calculator/Test_Calculator/Test_Calculator.swift
> +    func test_입력이제대로들어가는지() throws {
test_5689배열이제대로들어가는지 로 변경해보았습니다 !! 🫡

2022-05-19 05:50 UTC, bradheo65 commented
안녕하세요? 도미닉 PR 재요청 드립니다.
생각보다 놓친 부분이 많아서... 도미닉 덕분에 코드에 대해 한번더 생각해보았습니다 ㅎㅎ😵‍💫

이전에 DM으로 옵셔널 처리부분은 while let으로 구현해보는 방향으로 제시 해주셨는데, 직접 적용해보니 head에만 데이터가 들어가고 next로는 요소값들이 들어가지 않는 현상이 나와서 guard let으로 다시 표현해 주었습니다. 저의 생각으로는 while let 에서 새롭게 만든 변수가 외부에서 참조가 안되어 발생되는 문제로 보입니다... 도미닉의 생각이 궁금합니다!!🤔 (사실 완벽하게 이해하지 못했습니다.. 단순 while문이 nil 처리하는 것 같다는 느낌이 들긴하는데.... 흠.)
아래는 사용한 코드 입니다.
``` swift
    mutating func append(data: T?) {
        while let nextNode = head?.next {
             head = nextNode
            return
        }
        
        head = Node(data: data)
    }
```

2022-05-19 08:19 UTC, bradheo65 commented on Calculator/Calculator/Model/LinkedList/LinkedList.swift
> +        }
```swift
    mutating func append(data: T?) {
        if head == nil {
            head = Node(data: data)
            return
        }
        
        var node = head
        while let newNode = node?.next {
            node = newNode
        }
        node?.next = Node(data: data)
    }
```
로 수정했습니다!

2022-05-20 00:21 UTC, merged