계산기 [STEP 1] 재재
yagom-academy/ios-calculator-app pull request #248
Opened 2022-05-18 09:47 UTC by ZZBAE

안녕하세요, 라이언 @ryan-son  !

먼저, step1 PR 을 할 때까지 충분히 기다려주셔서 정말 정말 감사드립니다.. 🥲
참고해야 할 공식문서들과 많은 것들을 새로 공부하면서 생각보다 시간이 정말 많이 걸렸던 것 같습니다.
아직 완벽하게 이해하지도 못한 것 같고 공부할 것들이 많으니, 저의 부족한 점을 많이 지적해주세요..!

잘 부탁드립니다!! 🔥

# 🧮 계산기 프로젝트 (Calculator)
> 프로젝트 기간 2022.05.16 월  ~ 2022.05.18 수
팀원: 재재
리뷰어: Ryan
---

## 💾개발환경 및 라이브러리
[![swift](https://img.shields.io/badge/swift-5.6-orange)]()
[![xcode](https://img.shields.io/badge/Xcode-13.3-blue)]()

## 👩🏻‍💻 프로젝트 진행 방식
- 이번 프로젝트를 수행함에 있어 꼭 읽고 참고해야하는 공식 문서 빠짐없이 읽고 공부하기
- Step 1 수행 중 핵심경험 체크 ➡️ 왜 필요할지 생각하기
- 순서도와 UML 작성 필수
- 모르거나 헷갈리는 부분 꼭 꼭 질문하기

## 💡Step 1 수행 중 핵심경험
- [x] TDD 시작하기
- [x] 기존의 프로젝트에 Test Target 추가
- [x] Queue 자료구조의 이해와 구현

## 🗺 UML
<img width="705" alt="스크린샷 2022-05-18 오후 3 51 48" src="https://user-images.githubusercontent.com/98302604/168981981-391409f5-9e3c-4199-8577-8afb12b5a310.png">

## 🔨구현 내용
>- TDD를 이용하여 Unit Test를 진행할 테스트 코드 6개를 추가하였습니다.
>- 계산기가 입력받는 숫자와 연산자는 연산큐에 쌓입니다.
>- 기능명세서에 명시되어 있는 부분을 준수하였습니다.

## 🏀TroubleShooting (고민한점, 해결한점)
1. **우선 CalculatorItemQueue 내부에서 연산정보를 담는 큐를 구현할 수 있는 자료형식은 3가지 방법이 있습니다.**

1-1. 배열

<img width="658" alt="스크린샷 2022-05-18 오후 4 44 30" src="https://user-images.githubusercontent.com/98302604/168988056-f2712d96-fbec-4f27-b383-52beee3c74ba.png">

[사진출처](https://babbab2.tistory.com/86)

index를 이용하여 메모리 공간 위에 나란히 나열을 해놓는 구조입니다.</br>접근이 빠르다는 장점이 있지만 한 element를 삭제하거나 삽입할 때, 하나씩 자리를 바꿔줘야하는 번거로움이 생깁니다.

1-2. LinkedList

<img width="753" alt="스크린샷 2022-05-18 오후 5 03 10" src="https://user-images.githubusercontent.com/98302604/168989343-d7f6e0e2-5ffc-4426-9347-f6615147de9f.png">

[사진출처](https://babbab2.tistory.com/86)

각각의 공간에 있는 데이터를 연결시켜주는 구조입니다.</br>이 경우, 배열처럼 재배치를 하지 않아도 되기 때문에 중간에 element를 수정해도 괜찮다는 장점이 있지만, 데이터를 담는 별도의 공간이 많이 필요하기 때문에 저장 공간의 효율과 데이터를 찾는 속도가 느려진다는 단점이 있습니다.

1-3. DoubleStack

<img width="576" alt="스크린샷 2022-05-18 오후 5 10 19" src="https://user-images.githubusercontent.com/98302604/168990488-15cf8640-f1fc-4e15-b2c2-a2e2c3cf2896.png">

[사진출처](https://limjs-dev.tistory.com/90)

stack을 2개를 구현하여 처음 stack에 들어온 값들의 순서를 뒤바꿔주어 두번째 stack에서 element를 재배열 없이 그대로 뺄 수 있다는 장점이 있습니다. 저는 이 자료구조가 조금 더 이해가 되는 것 같아서 DoubleStack을 구현해주었습니다!

2. **TDD를 구현했는데, Test를 어떤식으로 시작해야할지 감이 안와서 오래걸렸던 것 같습니다.**
```swift
class CalculatorItemQueueTests: XCTestCase {
    var sut: CalculatorItemQueue<Int>?
    
    override func setUpWithError() throws {
        sut = CalculatorItemQueue()
    }
    
    override func tearDownWithError() throws {
        sut = nil
    }
    
    func test_1을_enqueue하면_1이_있다() {
        //given
        sut?.enqueue(1)
        
        //when
        let enqueueData = sut?.peek
        
        //then
        XCTAssertEqual(1, enqueueData)
    }
}
```
위와 같이 변수 sut(system under test)를 만들어주고, setUpWithError()와 tearDownWithError()를 이용해 하나의 테스트를 실행할 때마다 다음 테스트에 방해가 가지 않게 비워주는 역할을 할당해주었습니다. test에 각각 숫자를 랜덤으로 넣어서 enqueue와 dequeue, count, peek, isEmpty 를 순차적으로 테스트해보았습니다. 

---

## ⁉️조언을 구하고 싶은 부분
 - TDD는 원래 실패가능한 테스트로 코드를 짜기 전에 해야하는 것이라고 배웠는데, 사실 이번 프로젝트를 진행하면서 실패가능성을 어떤 식으로 생각해야하는지 감이 오지 않아 결국 코드를 먼저 만들어보고 그거에 대한 테스트 타켓을 만들게 되었습니다🥲 혹시 TDD를 만들 때, 메서드의 분리나 처음 작성할 때 애매한 부분들을 어떤식으로 해결해야하는지 라이언의 조언을 듣고 싶습니다..!

 - UML을 혼자서 처음 작성해보았는데, 각각의 관계가 깔끔하게 연관관계인지 의존관계인지 많이 헷갈렸던 것 같습니다. CalculatorItemQueue와 CalculatorItemQueueTest는 직접적으로 의존이 되어 있다기 보다 그냥 연결되어 있다고 생각해서 화살표 없이 작성해보았는데, 라이언은 어떻게 생각하시나요?🧐

## ⌨️ 커밋 규칙
* feat    : 기능 추가 (새로운 기능)
* fix      : 버그 수정
* refact : 리팩토링 (네이밍 수정 등)
* style   : 스타일 (코드 형식, 세미콜론 추가: 비즈니스 로직에 변경 없음)
* docs    : 문서 변경 (문서 추가, 수정, 삭제)
* test    : 테스트 (테스트 코드 추가, 수정, 삭제: 비즈니스 로직에 변경 없음)
* chore   : 기타 변경사항 (빌드 스크립트 수정 등)

## 💻 코드 컨벤션
Swift Statements 형식 준수

2022-05-18 16:47 UTC, ryan-son requested changes
재재~ 계산기 첫번째 Step 수행하시느라 고생 많으셨습니다! 짧은 시간에 새로운 자료구조를 다양하게 구현하는 방법에 대해 학습해 보셨네요. 이 PR은 Queue를 구현하는 방식을 글과 그림, 그리고 링크로 자세히 설명해두셔서 Wiki로도 활용할 수 있겠어요.

## 좋았던 점
- 커밋 단위가 보기 좋게 작게 나누어 주셔서 파악하기 좋았어요.
- 학습하시고 고민하신 내용을 공유해주셔서 고민한 과정을 이해하기 수월했습니다.
- 개발 환경을 공유해주셔서 저에게 문제가 발생하더라도 개발 환경의 차이로 인해 발생한 것은 아닌지 생각해볼 수 있었고, 이로 인해 불필요한 커뮤니케이션 비용이 발생하지 않을 수 있어 좋았습니다.

## 아쉬운 점
- 커밋메시지가 이해하기 어려운 경우가 있네요. 예를 들어 daff32bf012efeeb18de9522d1286e51b1157e95 와 같은 커밋은 어떤 목적이고, 앞으로 무슨 의미를 가지는지 이해하기 어려웠어요 (커밋에는 what과 how, PR에는 what, how, why를 담는다는 의도라면 개별 커밋에는 how를 채워주세요). 그 당시에는 필요했어도 의미없는 커밋이라면 interactive rebase와 같은 방법을 통해 불필요한 커밋을 하나로 합치는 방법도 고려해보시면 좋겠습니다.

> ## ⁉️조언을 구하고 싶은 부분
> - TDD는 원래 실패가능한 테스트로 코드를 짜기 전에 해야하는 것이라고 배웠는데, 사실 이번 프로젝트를 진행하면서 실패가능성을 어떤 식으로 생각해야하는지 감이 오지 않아 결국 코드를 먼저 만들어보고 그거에 대한 테스트 타켓을 만들게 되었습니다🥲 혹시 TDD를 만들 때, 메서드의 분리나 처음 작성할 때 애매한 부분들을 어떤식으로 해결해야하는지 라이언의 조언을 듣고 싶습니다..!

- 실패하는 테스트란 용어는 최초에 바로 이해하기 어렵긴 합니다. 하지만 아무것도 구현되지 않은 상태에서 테스트를 짠다면 반드시 실패하는 테스트겠죠. 바로 그 의미입니다.
- 예를 들어볼게요. 어떤 방식을 이용해서 큐를 구현하든 큐가 가지는 기본적인 특징이 있습니다. 선입선출과 같은 것이죠. 이를 통해 구현된 코드가 아무것도 없는 상태에서 테스트 스펙을 결정하고 테스트 코드도 짤 수 있습니다.
  - 큐가 비어있을 때 요소 넣기 -> 큐에는 새로 넣은 요소가 있고 큐에 들어있는 요소 개수는 새 요소 개수
  - 큐에 요소가 있을 때 새 요소 넣기 -> 큐에는 이전의 요소 뒤에 새로 넣은 요소가 위치하고 개수는 기존 + 새 요소 개수
    - 이 경우 큐의 첫번째 요소, 마지막 요소 조회를 위한 구현이 추가될 수 있으나 어떠한 경우에도 안정적으로 동작함을 보장하기 위해 테스트 스펙으로 정할 수 있음
  - 큐가 비어있을 때 요소 빼기 -> nil 또는 에러 던지기, 에러 반환 등 다양한 정책 수립 가능
  - 큐에 요소가 있을 때 요소 1개 빼기 -> 반드시 먼저 들어간 요소가 먼저 나온다는 원칙을 준수함을 보장, 큐를 구현한 방식의 특징을 잘 고려하여 특정 구간에서 특이하게 작동하는 경우 (edge case)가 없는지 점검하고, 만약 있으면 반드시 테스트 케이스에 추가한다.

구현된 것이 없어도 이 내용은 테스트로 작성이 가능할거에요. 바로 코드 작성이 어렵다면 주석을 통해 의사코드로 작성하실 수도 있고요. TDD는 이러한 테스트 케이스를 하나씩 정의하고 구현해나가는 개발방법론이에요 (모든 스펙을 한꺼번에 정의하고 한꺼번에 구현하는 것은 매우 어려워요).

이렇게 타입 요구사항을 테스트로 작성하셨다면 이제 이 테스트 스펙을 통과할 수 있는 타입을 구현하시면 됩니다. 테스트가 통과한다면 이제 코드를 예쁘게 고치고 구조화하는거죠.

> - UML을 혼자서 처음 작성해보았는데, 각각의 관계가 깔끔하게 연관관계인지 의존관계인지 많이 헷갈렸던 것 같습니다. CalculatorItemQueue와 CalculatorItemQueueTest는 직접적으로 의존이 되어 있다기 보다 그냥 연결되어 있다고 생각해서 화살표 없이 작성해보았는데, 라이언은 어떻게 생각하시나요?🧐

저의 경우에는 테스트 메서드가 포함되는 타입은 UML에 포함하지는 않고 있어요. 비즈니스 로직이나 뷰 간의 의존관계를 파악할 때 유용한 도구인데, 테스트 타입과의 의존관계는 없거나 중요하지 않은 경우가 많으니까요. 
현재 구현된 수준에서 타입 간의 의존 관계는 없다고 볼 수 있어요. 특정 타입이 본인이 필요로하는 기능을 구현하기 위해 다른 타입의 기능을 사용하여야 하는 경우도 없고, 특정 타입이 다른 타입을 소유하는 경우도 없으니까요. 프로토콜을 유의미하게 준수하는 경우도 없으니 (`Int`의 경우) 아마 다음 단계에서 타입이 더 많이 구현된다면 더 의미있는 UML을 그릴 수 있지 않을까 생각되네요. 의존, 연관관계가 생기는 시점부터 논의해봅시다~

궁금한 점이 있으시거나 막히시면 언제든지 찾아주세요~ 계속해서 화이팅입니다! 💪

2022-05-18 16:47 UTC, ryan-son commented on Calculator/Models/CalculatorItemQueue.swift
> +}
이 친구는 이 위치에 있기보다 Int의 extension 파일 또는 CalculateItem 파일에 있는 것이 더 좋아보이는데, 재재는 어떻게 생각하세요~?

2022-05-18 16:47 UTC, ryan-son commented on Calculator/Models/OperatorItem.swift
> +    case multiple
오타가 있네요~ 😉
```suggestion
    case subtract
    case multiply
```

2022-05-18 16:47 UTC, ryan-son commented on Calculator/Models/OperatorItem.swift
> +            return "+"
name보다는 mark, symbol, sign과 같은 이름이 더 어울릴 수 있겠네요~

2022-05-18 16:47 UTC, ryan-son commented on Calculator/Protocols/CalculateItem.swift
> +import Foundation
사용하지 않는 프레임워크는 제거해도 좋을 것 같습니다!

2022-05-18 16:47 UTC, ryan-son commented on README.md
> -- 이 저장소를 자신의 저장소로 fork하여 프로젝트를 진행합니다
Readme에 재재가 그리신 멋진 UML과 시행착오, 해결한 내용 등을 정리해두면 남들에게 경험을 공유하거나 되돌아와서 살펴보기 좋을거에요.

2022-05-19 08:13 UTC, ZZBAE commented on Calculator/Calculator.xcodeproj/project.pbxproj
>  				C713D9402570E5EB001C3AFC /* Calculator */,
라이언이 말씀해주신 방향을 참고해서 수정해보았습니다!

- Sources : 코드, 뷰
- Resources : Asset, 설정파일, 기타 리소스

근데 위에서 적어주신 것처럼 이렇게 나눠주면 나중에 찾고싶은 파일이 있을 때 빨리 찾을 수 있다거나 이러한 이유들로 파일을 묶어주는 것이 맞는지 아니면 다른 이유가 있나요? 제가 제대로 이해를 했는지 헷갈려서 다시 여쭤봤습니다 🥲

2022-05-19 08:13 UTC, ZZBAE commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
제가 super 메서드를 아예 생각 못해서 놓친 부분인 것 같습니다😖
[공식문서](https://developer.apple.com/documentation/appkit/nsviewcontroller/1434476-viewdidload) 를 참고해서 super 메서드 추가 해주었습니다!

```swift
override func setUpWithError() throws {
        super.try setUpWithError()
        sut = CalculatorItemQueue()
    }
    
    override func tearDownWithError() throws {
        super.try tearDownWithError()
        sut = nil
    }
```

2022-05-19 08:14 UTC, ZZBAE commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
유닛 테스트 공부하면서 꼭 참고해보겠습니다! 감사합니다 🫡

2022-05-19 08:14 UTC, ZZBAE commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(firstExpectation, firstResult!)
링크 참고하고 공부 후 수정해주었습니다. 그리고 테스트마다 
```swift
XCTAssertEqual(expectation, result)
```
expectation과 result 순서를 통일시켜주어 조금이나마 깔끔해보이도록 수정해주었습니다!

2022-05-19 08:14 UTC, ZZBAE commented on Calculator/Models/CalculatorItemQueue.swift
> +    private var secondQueue: [T] = []
아 이름에 Items를 추가함으로 Collection 타입을 암시해줄 수 있군요..! inStackItems 랑 outStackItems로 수정해주었습니다 ㅎㅎ

2022-05-19 08:14 UTC, ZZBAE commented on Calculator/Models/OperatorItem.swift
> +    case multiple
앗 죄송합니다ㅜㅜ 수정하였습니다.

2022-05-19 08:14 UTC, ZZBAE commented on Calculator/Protocols/CalculateItem.swift
> +import Foundation
넵 프레임워크 제거해주었습니다.

2022-05-19 08:14 UTC, ZZBAE commented on README.md
> -- 이 저장소를 자신의 저장소로 fork하여 프로젝트를 진행합니다
앗 리드미 작성을 깜빡한 것 같습니다. 작성 후 추가하겠습니다!

2022-05-19 14:25 UTC, ZZBAE commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
제가 이해를 못했던 부분을 따로 여쭤봤었는데, 자세하게 다시 알려주셔서 감사합니다!
초기값이 빈 큐가 아닐 때 해당 구문을 이용해서 활용해보겠습니다 😄

2022-05-19 14:27 UTC, ZZBAE commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_5를_넣으면_queue가_비어있지_않다() {
```swift
func test_아무것도_없는상태에서_dequeue를_하면_nil이_나온다() {
        //given
        let expectation: Int? = nil
        //when
        let result = sut?.dequeue()
        //then
        XCTAssertEqual(expectation, result)
    }
    
    func test_5를_enqueue하고_dequeue하면_queue가_비어있다() {
        //given
        let input = 5
        let expectation: Bool = true
        //when
        sut?.enqueue(input)
        sut?.dequeue()
        let result = sut?.isEmpty
        //then
        XCTAssertEqual(expectation, result)
    }
```
알려주신 내용을 참고하여 큐에 요소가 있을 때 enqueue 하면 이미 있던 요소 뒤쪽으로 새로운 요소가 들어가는 테스트 하나랑 큐에 요소가 하나 있을 때 dequeue하면 해당 요소를 반환하고 큐는 빈 상태가 되는 테스트 하나를 추가했습니다!

2022-05-19 16:21 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(firstExpectation, firstResult!)
하나는 옵셔널 타입이고 다른 하나는 옵셔널 타입이 아닐 때 서로 동등함을 비교할 수 있는 이유가 무엇이었나요? 학습하신 내용을 공유해주실 수 있으실까요?

2022-05-19 16:23 UTC, ryan-son commented on Calculator/Models/CalculatorItemQueue.swift
> +    private var secondQueue: [T] = []
Items가 Collection 타입임을 암시한다기보다 복수형 명사로 이름 지어진 경우 Collection 타입이라고 예상합니다!

2022-05-19 16:47 UTC, ryan-son approved these changes
재재, 피드백에 대해 고민해보시고 반영하시느라 고생 많으셨습니다~! 👏

이미 Step 1의 요구사항은 잘 만족하셨고, 이번 피드백에서도 큰 수정사항은 없어보여 머지하겠습니다.

계속해서 Step 2도 잘 수행하시길 응원할게요~ 💪 필요하시면 언제든지 찾아주세요~

2022-05-19 16:47 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +
공백은 지워주시면 되겠네요~

2022-05-19 16:47 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        sut?.enqueue(1)
이 경우에 CalculatorItemQueue 타입에 초기 큐를 설정해줄 수 있는 의 이니셜라이저를 하나 마련해서 세팅해보는건 어떨가요? '1이 queue에 있고'라는 초기 상태를 마련하기 위해 검증 대상인 메서드를 사용하는 것은 의문이 생길 수 있을 것 같아요. enqueue를 한 번 수행한 것과 두 번 수행한 것은 결과가 다를 수 있으니까요. 지금은 예시가 enqueue라 당연해보일 수 있지만 더 복잡한 메서드라면 달라보일 수 있을 것 같네요.

2022-05-19 16:47 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_1과3을_넣으면_count가_2다() {
테스트 이름이 타입의 기능 범위라고 생각한다면 1과 3이라는 내용보다는 '요소 2개를 넣으면'이라는 네이밍이 더 적합할 수 있겠네요. 극단적으로 1과 3은 어떤 정수가 되어도 성공하는 것이니까요~ 다른 테스트 메서드들도 이 내용을 고려해서 이름을 조금씩 수정해보는건 어떨까요?

2022-05-19 16:47 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +}
이 파일과 파일을 포함한 폴더는 프로젝트에서 참조가 끊어져 있네요. 프로젝트에 활용되지 않는 파일은 제거해주세요~

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/69730931/169353106-83ad0179-a38e-4a81-9bc0-7582990209ea.png">

2022-05-19 16:47 UTC, ryan-son commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        sut?.dequeue()
dequeue의 결과로 반환된 내용을 같이 검증해도 좋겠네요~

2022-05-19 16:47 UTC, ryan-son commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_아무것도_없는상태에서_dequeue를_하면_nil이_나온다() {
이렇게 실패하거나 에러가 발생하는 케이스도 테스트의 대상에 포함해두면 실패해야할 때 실패하지 않는 경우를 자동적으로 파악할 수 있게 되어 더 신뢰성 있는 구현이 가능합니다~!

2022-05-19 16:48 UTC, merged