계산기 [STEP 1] 민쏜
yagom-academy/ios-calculator-app pull request #249
Opened 2022-05-18 17:27 UTC by minsson

@protocorn93 

안녕하세요, 콘! 😁
Step 1 PR 제출합니다. 검토 부탁드립니다! ☺️

이번 과제는 정말 정말 정말 어렵게 느껴졌습니다.
보통은 요구사항 구현에는 문제가 없고, 어떻게 가독성을 높일지에 대해 고민하는 편입니다.
그런데 이번 과제는 요구사항을 이해하기도, 그것을 실행하기도 쉽지 않아 무척 막막했습니다.
우선 과제를 제출하기는 하지만, 스스로 확신이 없는 내용을 제출하는 상황이라 무척 아쉽습니다.🥲
Step 2, 3에 가면서 더욱 발전할 수 있도록 노력하겠습니다! 많은 조언 부탁 드립니다..!! 🙇‍♂️

## 1. 과제 방향을 잡을 때의 생각의 흐름
### 1) `CalculatorItemQueue` 타입
> CalculateItem 프로토콜이 요구하는 기능에 따라 연산 작업을 수행해야 하지 않을까.. 라고 생각했는데, 네이밍과 매치가 잘 되지 않는 것 같습니다. 우선 그런 기능을 한다고 가정하고 아래 내용을 작성했습니다.
- 클래스 vs 구조체: 아직 상속의 필요성이 느껴지지 않아 구조체를 선택했습니다.
- 숫자 버튼을 통한 입력은 String으로 받겠지만, String을 Double로 형변환하여 받는다고 가정해, 인스턴스 저장속성인 queue는 `[Double]`로 지정했습니다.
	- **최초 입력을 String으로 받아야 하는 이유**: '하나의' 숫자는 연산자 혹은 기능키(CE, = 등) 단위로 구분되기 때문입니다. 즉, 숫자가 아닌 버튼이 입력되는 순간 '하나의' 숫자가 끊어진다고 보면 될 것 같습니다. (가령 `123+456+789=` 라면, 123, 456, 789가 될 것 같습니다.) 
	- **Float이 아닌 Double 타입을 선택한 이유**: 숫자를 최대 20자리까지 표현해야 하기 때문입니다.
- 연산자 혹은 기능키 버튼 단위로 끊어진 Double 타입의 숫자를 계산합니다.
- 계산 결과는 가능하다면 정수로, 불가능하다면 실수로 보여줍니다.

### 2) `CalculateItem` 프로토콜
- 사칙연산을 위한 메서드(혹은 연산프로퍼티)를 요구합니다.
- 요구사항 상 빈 프로토콜이라고 하여 우선은 빈 상태로 남겨두었습니다.

### 3) Queue 구현 방법
- 우선 Array를 이용해 구현했습니다.
	- 코드의 구조와 가독성을 고려하고, 그리고 아직 익숙하지 않은 protocol, extension, TDD 등을 잘 활용하는 것에 초점을 두고 싶었기 때문입니다. (현재로서는 이것에만 집중해도 잘 안 되는 것 같습니다..🥲)
	- 시간복잡도가 문제가 된다면, 추후 CalculatorItemQueue의 코드만 변경해 해결할 수 있다고 생각했기 때문입니다.

## 2. 해결이 되지 않은 점
과제 자체가 완벽하게 이해되지 않아 많은 내용을 추측에 의지해 진행한 것 같습니다. 요구사항의 문구도 잘 이해되지 않는 측면이 있었습니다.
- `사칙연산 계산을 위한 큐(Queue) 타입 (CalculatorItemQueue)`의 의미
- `큐타입 구현을 위한 List 타입`의 의미

## 3. 조언을 얻고 싶은 부분
- TDD를 처음 해보았는데, 올바른 방향으로 진행되었는지 궁금합니다.
- 전반적으로 커밋메시지 작성이 잘 이루어지고 있는지 궁금하고, 특히, 3a7482a7a67c9dfb7bf7d92c0a4e3c5d78eadd02 와 같이 유의미하지 않은 변경사항에 대한 커밋메시지 작성법이 궁금합니다.
- 클래스, 구조체 등의 커스텀 타입을 정의하고, 인스턴스들끼리 데이터를 주고 받는 구조를 생각해내기가 쉽지 않습니다. 학습서의 단편적인 예제 외에, 혹시 간략하지만 완결된 구조의 코드를 볼 수 있는 곳이 있는지 궁금합니다..! 콘은 저처럼 개발을 막 배워나가는 과정에서 책이나 강의 외에 어디서 코드를 보고 배우셨나요?
- 코드와 구조 등에 대해서도 구체적으로 여쭤보고 싶은데, 사실 이번 과제는 어느 것 하나 확실하게 이해하지 못한 것 같아 어떤 질문을 해야할지도 막막합니다. 🥲

2022-05-19 15:26 UTC, protocorn93 requested changes
@minsson!! 정말 고생하셨어요! 일단 구현된 코드가 많지 않아 많은 피드백을 남겨드리진 못했어요! 대신 이와 더불어 PR에 남겨주신 부분에 대해 이야기를 조금 더 해볼게요.

# 1. 과제 방향을 잡을 때의 생각의 흐름

## 1) CalculatorItemQueue 타입

> `CalculateItem` 

먼저 저는 이 프로토콜을 계산에 사용되는 값들이 채택해야 하는 프로토콜로 이해를 했으며 기능명세상 `값`과 `연산자`를 나타내는 타입이 이를 채택해야 한다고 생각했어요. 

>  `클래스 vs 구조체: 아직 상속의 필요성이 느껴지지 않아 구조체를 선택했습니다`

이것만으로는 이유가 부족하다고 생각해요. 애플이 설명하는 이 글을 읽어보시고 좀 더 이야기를 보충해나가셨으면 좋겠어요. [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)

# 2.  해결이 되지 않은 점

그래도 어느정도 명세에 따라 잘 작성해주신 것 같아요. 

> 사칙연산 계산을 위한 큐(Queue) 타입 (CalculatorItemQueue)의 의미

말 그대로 숫자와 연산자를 담고 연산을 하는데 사용될 수 있는 FIFO 방식의 큐를 구현한 타입이라고 보시면 될 것 같아요. 현재는 `enqueue`와 `dequeue` 밖에 존재하지 않는데, `peek`이나 `isEmpty`와 같은 인터페이스도 큐가 제공할 수 있는 기능이지 않을까 싶어요. 그래서 이 부분에 대해서도 구현해보시면 어떨까 싶어요!

> 큐타입 구현을 위한 List 타입의 의미

큐 타입의 내부 상태를 표현하기 위한 자료구조를 의미하는 것으로 이해했어요. 기본적으로 민쏜의 구현대로 라면 이 List 타입은 배열(Array)가 되는 것이구요. 코드 코멘트에도 남겼지만 `removeFirst`의 시간복잡도를 학습해보시면 예상과 조금은 다를 수 있어요. 이를 위해 다른 자료구조를 직접 구현해보실 수 도 있으실거에요 (물론 옵셔널한 부분입니다!) 그 예로는 링크드리스트가 있을 것 같네요! 

자 여기서 제가 코드 코멘트에 남겼던 부분에 대해 조금 더 보충해서 설명드리자면 우리가 `CalculatorItemQueue`에게 기대하는 것은 값을 어떻게 저장하느냐(자료구조)가 아닙니다. 민쏜의 구현대로라면 `enqueue`와 `dequeue`가 기대하는 것이죠. 

그렇기 때문에 구현체에 따라 자료구조와 위 두 인터페이스의 구현은 달라질 수 있어요. 좀 더 직접적인 힌트를 드리자면 `enqueue`와 `dequeue`는 추상화되어야 할 대상이에요. 이들을 프로토콜로 추출하고 `CalculatorItemQueue`가 이를 채택하여 구현하는 형태가 되면 좋을 것 같아요. 

# 3. 조언을 얻고 싶은 부분

> TDD를 처음 해보았는데, 올바른 방향으로 진행되었는지 궁금합니다.

커밋과 각 구현 내용을 보았을 때 잘 해나가고 있는 것으로 보여져요. 기본적으로 테스트 코드를 먼저 작성하는 개발 방식이고 이는 우리가 해당 객체를 구현의 관점이 아닌 메시지, 인터페이스 관점으로 바라볼 수 있도록 해주는 개발 방식이라고 생각해요. 인터페이스를 먼저 생각하기 때문에 오버엔지니어링도 방지하고 좀 더 간결하고 명확한 코드를 작성할 수 있기도 하구요.

지금은 연습을 하는 과정이기에 사이클의 과정 일부가 커밋으로 남아있지만, 이후에 어느정도 익숙해지시면 모든 과정을 커밋으로 남길 필요는 없어요! 하나의 사이클을 하나의 커밋 단위로 가져가는 것도 좋을 것 같아요! 

> 전반적으로 커밋메시지 작성이 잘 이루어지고 있는지 궁금하고, 특히, https://github.com/yagom-academy/ios-calculator-app/commit/3a7482a7a67c9dfb7bf7d92c0a4e3c5d78eadd02 와 같이 유의미하지 않은 변경사항에 대한 커밋메시지 작성법이 궁금합니다.

저는 해당 커밋이 충분히 의미있는 단위라고 생각해요! 커밋 단위는 현재도 충분히 잘 나눠주시고 계시는 것 같아요. 덕분에 코드를 이해하기 편했어요. 다만 커밋 메시지는 최대한 간결하게 작성해주면 좋을 것 같아요. 물론 그렇게 되려면 단위가 작을 수록 좋겠죠! 

> 클래스, 구조체 등의 커스텀 타입을 정의하고, 인스턴스들끼리 데이터를 주고 받는 구조를 생각해내기가 쉽지 않습니다. 학습서의 단편적인 예제 외에, 혹시 간략하지만 완결된 구조의 코드를 볼 수 있는 곳이 있는지 궁금합니다..! 콘은 저처럼 개발을 막 배워나가는 과정에서 책이나 강의 외에 어디서 코드를 보고 배우셨나요?

> 코드와 구조 등에 대해서도 구체적으로 여쭤보고 싶은데, 사실 이번 과제는 어느 것 하나 확실하게 이해하지 못한 것 같아 어떤 질문을 해야할지도 막막합니다. 

이 두 부분에 대해서는 함께 말씀드리고 싶어요. 저도 사실 처음 공부할 때는 구현 자체에 더 집중을 했던 것 같아요. "일단 돌아가게만 하자" 마인드였던 것 같아요. 이게 나쁜 것은 아니에요. 결국 우리는 돌아가는 소프트웨어를 만드는 것이니까요! 하지만 돌아가는 소프트웨어는 유지보수와 땔 수 없는 사이에요. 결국 유지보수도 우리의 책임이게 유지보수 하기 좋은 코드를 작성할 필요가 있어요. 그렇기 때문에 리팩토링이라는 과정이 필요한거구요. 그리고 더더 나아가 이러한 문제를 해결하기 위해 다양한 아키텍처가 등장하기도 하는거구요. 

이 밑바탕에는 객체지향이 있어요! 이 부분이 굉장히 추상적으로 다가오실 수 있어요. 당연한거에요! 저도 많은 상황과 많은 코드를 작성해보면서 이해가 되기 시작했거든요. 그 시작으로 [객체지향의 사실과 오해](http://www.yes24.com/Product/Goods/18249021)라는 책을 굉장히 추천해드려요. 이를 다 읽어보시고 코드 레벨로 설명하는 동일한 저자가 쓴 "오브젝트"라는 책도 추천드리구요. (후자는 지금 단계에서는 이해하시기 조금은 어렵지 않을까 싶어요) 

그리고 이와 함깨 [클린코드](http://www.yes24.com/Product/Goods/11681152) 라는 책도 읽어보시는걸 권장드려요

2022-05-19 15:26 UTC, protocorn93 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
정말 이렇게 내부 상태값을 검증을 해야할까요? 현재 민쏜이 구현한 `CalculatorItemQueue`에게 기대하는 것은 FIFO 방식의 입출력이 전부이고 이것만 검증하면 된다고 생각해요. 200, 300을 `enqueue`하고 `dequeue`시 200을 반환하는지 검증을 하는 것이 더 바람직해보여요.

2022-05-21 13:24 UTC, minsson commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        queue.isEmpty ? nil : queue.removeFirst()
> 문법적으로 허용이 가능한 부분이지만 저는 `return` 명시적으로 사용해주곤 해요. 그게 더 가독성이 좋다고 판단하기 때문이에요. 이 부분에 있어 민쏜의 생각은 어떤가요?

처음에 `return` 키워드를 명시적으로 사용하지 않은 건 가능하다면 코드의 길이를 줄여보려고 한 선택이었어요. 뭔가 삼항연산자를 더 깔끔해보이게 쓰고 싶었던 생각도 있었던 것 같아요.

그런데 콘의 말씀을 아래와 같이 두 코드를 작성해 비교해보니, 제가 작성한 코드를 처음 보는 동료 입장에서는 `return` 키워드가 명시적으로 사용될 때 더 빠르게 코드의 내용을 이해할 수 있을 거라는 생각이 들었어요. 동료 입장 뿐만 아니라 작성한 제 입장에서도 일주일 후에는 그럴 것 같고요 😅

```swift
mutating func dequeue() -> Double? {
    queue.isEmpty ? nil : queue.removeFirst()
}

mutating func dequeue() -> Double? {
    return queue.isEmpty ? nil : queue.removeFirst()
}
```

특히 코드의 길이가 길 때 더더욱 이 메서드가 결론적으로 무엇을 반환하는지 살펴보게 될 것 같은데, 그 때 `return`이라는 키워드가 없다면 시간을 좀 더 소모해야할 것 같아요.

그래서 저도 앞으로 이런 경우에 `return` 키워드를 명시적으로 사용하려고 합니다. 감사합니다! ☺️

2022-05-22 21:24 UTC, minsson commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        queue.isEmpty ? nil : queue.removeFirst()
> 현재는 기본 `Array` 타입을 Queue 타입의 List로 사용하고 있는데요. 여기서 `removeFirst`의 시간복잡도는 어떻게 될까요? 그리고 시간복잡도가 왜 그렇게 나오는지 한번 학습해보시면 좋을 것 같아요🤔

`removeFirst()`의 시간복잡도는 O(n)이며, 이때 n은 해당 컬렉션의 길이를 의미합니다.

`removeFirst()`를 호출시, 배열의 0번째 요소를 반환하게 됩니다.
이 때, 배열의 1번 인덱스부터 마지막 인덱스까지의 요소들은 빈 0번째 인덱스를 채우기 위하여 모두 한 칸씩 앞으로 이동하게 됩니다.

이에 따라 총 n번의 작업이 발생하므로 시간복잡도는 O(n)이 됩니다.

한편, 정반대의 의미를 갖는 `removeLast()`의 시간복잡도는 O(1)입니다.
`removeLast()`를 호출시 배열의 마지막 요소를 반환하게 되는데, 앞 부분에 빈 인덱스가 발생하지 않으므로 배열의 요소가 이동할 필요가 없기 때문입니다.

참고 문서:
[공식문서 - removeFirst()](https://developer.apple.com/documentation/swift/array/2884646-removefirst)
[공식문서 - removeLast()](https://developer.apple.com/documentation/swift/array/2885764-removelast)

2022-05-22 21:36 UTC, minsson commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var queue: [Double] = []
> 이 프로퍼티는 외부에 노출되지 않는게 좋을 것 같아요. `CalculatorItemQueue`가 외부에 제공해야하는 인터페이스는 `enqueue`와 `dequeue`, 이 두 가지여아만 한다고 생각해요. `enqueue`를 하고 `dequeue`를 통해 간접적으로 내부 상태에 대해 알 수 있으니까요!
> 
> 최대한 내부 구현은 숨기고 인터페이스만 공개하는 것이 객체지향의 설계의 시작이라고 할 수 있어요. 이렇게 말씀드리는 이유에 대해서는 차차 학습해보시면서 이해해보셨으면 좋겠어요.

객체지향의 개념은 조금은 이해가 되지만, 그걸 코드에 어떻게 적용해야 할지 판단의 기준이 잘 서지 않는 것 같아요 🥲
그렇기에 코드 단계에서 콘이 이렇게 피드백 해주시는 게 너무 귀중하게 와닿습니다! 🤩
우선 말씀하신대로 외부에 노출하지 않기 위해 `private(set)`을 `private`로 변경했어요.

처음에는 Queue에 어떤 요소들이 들어있는지 조회할 수 있어야 한다고 생각했는데, 콘의 말씀을 듣고 보니 굳이 그걸 외부에서 조회할 이유가 없을 것 같다는 생각이 들었어요. 아직도 `최대한 내부 구현은 숨긴다`에서 `최대한`이 얼마나인지 완벽하게 이해되지는 않지만, 콘의 피드백 덕분에 적어도 이 코드와 유사한 상황에서는 캡슐화를 좀 더 잘할 수 있을 것 같아요. 😁

2022-05-22 21:39 UTC, minsson commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var queue: [Double] = []
> 명세에는 `계산기가 입력받은 숫자와 연산자는 연산큐에 쌓입니다`와 같이 나와있는데요.
> 
> 이 배열에 연산자도 함께 담기기 위해서는 보다 제네릭한 타입으로써의 `queue`가 되어야하지 않을까요?!

요구사항을 잘 이해하지 못했네요! 😭 숫자 생각만 했었던 것 같아요.
말씀하신대로 제네릭을 활용해 수정했습니다!

2022-05-22 21:43 UTC, minsson commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
> 정말 이렇게 내부 상태값을 검증을 해야할까요? 현재 민쏜이 구현한 `CalculatorItemQueue`에게 기대하는 것은 FIFO 방식의 입출력이 전부이고 이것만 검증하면 된다고 생각해요. 200, 300을 `enqueue`하고 `dequeue`시 200을 반환하는지 검증을 하는 것이 더 바람직해보여요.

TDD 배우면서 최대한 자세하고, 많은 케이스를 써야 한다고 생각했었어요. 그런데 콘의 말씀을 듣고 보니 이 테스트 케이스는 의미없이 다양한 테스트케이스를 작성했다는 생각이 들었어요. 콘이 말씀해주신 케이스는 `dequeue()`에 있는만큼, `enqueue(_:)`에서 다룰 이유도 없어보였고요. 🙃

따라서 이 테스트 케이스와, 그밖의 다른 의미없어 보이는 테스트케이스도 삭제했습니다!

2022-05-22 22:13 UTC, minsson commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        queue.isEmpty ? nil : queue.removeFirst()
> 또 하나! `dequeue`라는 메시지에 응답하기 위해 `queue`에서 값을 제거할 때 이미 queue가 비어 있어 반환할 값이 없다면 nil을 반환하고 있는데, 그렇게 결정한 이유가 궁금하네요! 에러를 던지자는 팀원이 있다면 민쏜은 어떻게 설득을 해보실 수 있을까요?

우선 팀원이 그렇게 제안하는 이유를 물어볼 것 같아요. 우선 지금은 제 실력이 낮아 애초에 무엇이든 확신은 없지만, 언젠가(그날이 온다면 😭) 많이 성장해 제 코드에 확신이 생긴다고 해도, 제가 얼마든지 틀릴 수 있고, 무조건적인 정답도 없다고 생각하기 때문이에요.

그 다음에 제 생각도 덧붙여볼 것 같은데요. 저는 `dequeue`라는 말을 `큐에서 꺼낸다`고 받아들였고, 큐에 꺼낼 게 없다면, '없음'을 보여줄 수 있는 `nil`을 반환하는 게 에러보다 더 직관적일 거라고 생각했어요. 우선 nil을 반환 받고, nil을 반환 받는 게 문제가 되면 그때 `nil이 나오면 에러를 던진다`라는 방식으로 접근할 수 있을 거라는 생각이 들었다고 말할 것 같아요.

그리곤 서로 의견을 조율하면 될 것 같아요.

그런데 추가적으로, 이런 상황을 함께 논의해보고 싶을 것 같아요.

애플은 어떻게 할까 궁금해서 컬렉션 타입의 `remove`와 관련된 메서드들을 검색해봤는데 신기한 걸 알게 됐거든요.

1) 아래의 이미지의 removeFirst()와 같이, `Removing Elements`와 관련된 함수는 값이 없으면 nil이 아니라 error를 내보내요. 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/96630194/169717930-9ffca417-599a-4ffe-8a9f-c625ba4539bd.png">

2) 그런데 아래 이미지와 같이, `popLast()` 메서드는 같은 카테고리에 있는 다른 모든 메서드들과 달리, 값이 없을 때 error가 아니라 nil을 내보내고 있어요.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/96630194/169718027-81b4e4d3-2cc1-48e7-a266-a958fc8a51ff.png">

우선 저는 1번 결과를 보고 `nil이 아니라 error를 던지는 게 낫겠다`라는 생각이 들었어요.
하지만 2번 결과와 관련해, 저는 둘 중 하나로 통일하는 게 이런 메서드들을 사용하는 사람 입장에서 더 이해가 잘될 것 같은데, `popLast()` 하나만 다르다는 게 잘 이해가 되지 않더라고요. 혹시 콘은 왜 `popLast()`만 다른지 알고 계신가요?

2022-05-22 23:53 UTC, minsson commented
콘, 안녕하세요!
우선 상세한 피드백 감사합니다! 많은 도움이 됐어요!
귀중한 피드백을 주신만큼 코드를 무작정 수정하기보다는, 부족하지만 나름대로 공부를 더 하고 과제를 수정하는 게 좋을 것 같아서 시간을 조금 많이 투자했던 것 같아요. 여전히 잘 모르는 게 많지만요... 🥲

그래도 Step 2, Step 3는 이번 주가 끝나기 전에 다 제출할 수 있을 거라고... 생각.. 합니다... 🤥 
(내가 무릎을 꿇은 건 추진력을 얻기 위함이었다! 라는 짤이 생각나네요... 🙃)

## 콘의 Step 1 종합 코멘트에 대한 답변
### 1) 구조체와 클래스의 선택 기준
조언해주신 [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes) 을 읽어보았어요! 좋은 Article을 알려주셔서 감사해요 😁 제가 글을 읽고 이해한 바를 바탕으로 구조체를 선택한 근거를 덧붙여보자면, 아래와 같아요!

상속 등 클래스를 반드시 써야할 이유가 없다면, 애플은 구조체를 쓰는 걸 권장하고 있어요.
- 클래스는 참조 타입으로, 클래스로 작성된 코드는 자칫하면 앱 전체에 예상치 못한 결과를 가져오는 상황이 생길 수 있어요. 지금 보는 코드상으로는 문제가 없어보이더라도, 논리적 오류가 있다면, 문제의 원인을 파악하는 것조차 어려울 수 있어요.
- 구조체는 클래스와 달리 값타입이기 때문에, 위에 서술한 클래스의 단점을 갖지 않아요. 로컬의 변경사항을 앱 전체에 의도적으로 변경사항을 전달하지 않으면 다른 곳에 영향을 주지 않아요. 그래서 예상치 못한 변경사항이 존재할 수 있다는 걱정을 하지 않아도 돼요.
- 게다가 구조체는 대부분의 경우에 클래스의 역할을 대체할 수 있어요. 즉, 클래스가 갖고 있는 단점이 없으면서도, 역할을 대체할 수 있기 때문에 애플에서는 클래스를 반드시 써야하는 상황이 아니라면 일단 구조체를 쓰라고 강권하고 있어요.
	- 특히, 상속과 관련된 부분이 인상 깊었어요. 이 글을 읽기 전에, 저는 클래스를 사용한다면 그 이유는 상속 때문일 거라고 생각했었어요. 그런데!
	- > However, the kinds of inheritance hierarchies you can build with class inheritance can be also modeled using protocol inheritance and structures.
	- 라는 문장을 보면, 프로토콜 상속과 구조체를 이용하면 클래스의 상속으로 만드는 상속 계층구조를 구현할 수 있다는 걸 알 수 있었어요. 🤩 
- 그럼에도 불구하고 클래스를 써야할 때도 있어요.
	- Use Classes When You Need Objective-C Interoperability
	- Use Classes When You Need to Control Identity
	- 라고 해요! Objective-C 관련 내용은 이해가 되는데, Control Identity 관련해서는 아직 완벽하게 이해가 되지는 않아요. 이건 더 많은 공부가 필요할 것 같아요.

### 2) Queue에서의 `peek`과 `isEmpty`의 구현
넵, 구현했어요! 😃 구현할 때 `isEmpty()`라고 메서드로 쓰는 게 익숙해 메서드로 구현했는데, 연산프로퍼티로 구현할 수도 있겠다는 생각이 들었어요. 혹시 콘은 이에 대해 어떻게 생각하시나요?

### 3) removeFirst의 시간 복잡도
이와 관련된 이야기는 코드 코멘트에 답변을 남겼어요.

### 4) Array 외의 다른 자료구조의 구현 (Linked List)
조언해주신 것처럼, Linked List를 사용해서 구현해봤어요. Queue를 구현하는 방법이 Linked List 외에도 여러가지가 있고, 그에 따른 장단점도 많아, 나중에 따로 구현해봐야겠다는 생각이 들었어요!

### 5) `enqueue`와 `dequeue`의 추상화 (프로토콜로 추출)
조언해주신대로 구현해봤는데, 제가 콘의 말씀을 정확하게 이해했다는 확신은 없어요... 🥲 그래서 밑에 따로 질문을 남겨놨어요.

### 6) 책 추천: 객체지향의 사실과 오해, 오브젝트, 클린코드
책 추천 감사드려요! 객체지향의 사실과 오해는 얼마 전에 사서 조금씩 읽어나가고 있어요! 아직 초반부를 읽고 있어요! 다만 지금의 제 실력으로는, 그리고 아직 초반부를 읽고 있는 상황에서는 '글로는 이해가 되지만, 이걸 바탕으로 코드 구현을 어떻게 해야할지는 좀 막막하다'는 게 솔직한 감상이에요.. 😔 얼른 다 읽어야겠어요!

오브젝트와 클린코드는 들어봤지만 아직 구입하지 않았어요. 객체지향의 사실과 오해를 다 읽고 구입해서 읽어보려고 해요. 특히 객체지향의 사실과 오해에서 서사적으로 개념을 다뤘다면, 오브젝트에서는 실제 코드가 많다고 해서 기대가 돼요. 그리고 클린코드는 목차만 봐도 재미있어보여요..! 얼른 읽고 싶습니다 😁

## 질문
> 자 여기서 제가 코드 코멘트에 남겼던 부분에 대해 조금 더 보충해서 설명드리자면 우리가 `CalculatorItemQueue`에게 기대하는 것은 값을 어떻게 저장하느냐(자료구조)가 아닙니다. 민쏜의 구현대로라면 `enqueue`와 `dequeue`가 기대하는 것이죠.
> 
> 그렇기 때문에 구현체에 따라 자료구조와 위 두 인터페이스의 구현은 달라질 수 있어요. 좀 더 직접적인 힌트를 드리자면 `enqueue`와 `dequeue`는 추상화되어야 할 대상이에요. 이들을 프로토콜로 추출하고 `CalculatorItemQueue`가 이를 채택하여 구현하는 형태가 되면 좋을 것 같아요.

이 두 문단이 아직은 잘 이해가 되지 않아요. 🥲
1) 첫문단의 '기대한다'라는 워딩과 관련해 조금만 더 자세히 설명해주실 수 있나요?
2) 두번째 문단은
	1) `구현체에 따라 자료구조와 위 두 인터페이스의 구현은 달라질 수 있어요.` 라는 문장이 이해가 되지 않았어요. 더 자세히 설명해주실 수 있나요..!?
	2) `추상화되어야 할 대상이다`라는 문장이 '응당 그렇게 되어야 한다'고 이해되는데, 사실 왜 그래야 하는지 아직은 잘 이해가 되지 않아요. 왜 이걸 프로토콜로 추출하고, 채택하는 방식으로 구현해야 하는지 더 자세히 설명해주실 수 있나요...?

2022-05-23 14:36 UTC, protocorn93 commented
> 넵, 구현했어요! 😃 구현할 때 isEmpty()라고 메서드로 쓰는 게 익숙해 메서드로 구현했는데, 연산프로퍼티로 구현할 수도 있겠다는 생각이 들었어요. 혹시 콘은 이에 대해 어떻게 생각하시나요?

`isEmpty`는 스위프트 콜렉션 타입들을 보았을 때 연산프로퍼티로 구현해도 좋을 것 같네요! 

## 질문 

객체지향에서 중요한 것은 객체간의 협력이에요. 우리가 객체를 설계할 때 단순히 이 객체의 기능을 위해 설계하는 것이 아니라, 특정 문맥, 하나의 명세 안의 다양한 객체들간의 상호기능 속에서의 기능을 구현 및 설계하는거에요. (이런 부분은 객사오+오브젝트 책을 읽으시면 이해가 좀 더 수월하실거에요.) 

여기서 기대한다는 "해당 객체에게 어떤 메시지를 보낼 수 있고 그 객체는 그 메시지에 응답할 수 있다는 것"을 기대한다라고 표현했어요. 우리가 Queue라는 객체에 `enqueue`라는 메시지(요청)를 전달할 수 있고, Queue는 내부적으로 enqueue라는 메시지에 자신만의 구현으로 응답하는거에요. 

제가 너무 어렵게 말씀드리는 것 같은데, 쉽게 한 줄로 요약해보자면 구현은 숨기고 인터페이스만 드러내야 전체적인 객체간의 협력의 유연성이 높아져요. 이를 위해서는 변하는 것과 변하지 않는 것을 구분하는 연습이 필요해요. 

Queue의 기능에서 변하지 않는 것은 `enqueue`, `dequeue`라는 인터페이스에요. 변할 수 있는 것은 내부 자료구조 및 구현이 되겠죠. 비슷한 예로 값을 저장하는 어딘가에 저장하는 역할을 담당하는 객체에게 변하지 않는 것은 값을 저장하는 행위에요. 하지만 변할 수 있는 것은 저장소가 되겟죠. 서버에 저장할 수도 있고 로컬 DB에 저장할 수도 있는 것이구요. 

여기서 "저장"이 추상화된 행위이고 "저장 방법"은 실제 구현인겁니다!

2022-05-23 14:44 UTC, protocorn93 reviewed
> 넵, 구현했어요! 😃 구현할 때 isEmpty()라고 메서드로 쓰는 게 익숙해 메서드로 구현했는데, 연산프로퍼티로 구현할 수도 있겠다는 생각이 들었어요. 혹시 콘은 이에 대해 어떻게 생각하시나요?
isEmpty는 스위프트 콜렉션 타입들을 보았을 때 연산프로퍼티로 구현해도 좋을 것 같네요!

## 질문

객체지향에서 중요한 것은 객체간의 협력이에요. 우리가 객체를 설계할 때 단순히 이 객체의 기능을 위해 설계하는 것이 아니라, 특정 문맥, 하나의 명세 안의 다양한 객체들간의 상호기능 속에서의 기능을 구현 및 설계하는거에요. (이런 부분은 객사오+오브젝트 책을 읽으시면 이해가 좀 더 수월하실거에요.)

여기서 기대한다는 "해당 객체에게 어떤 메시지를 보낼 수 있고 그 객체는 그 메시지에 응답할 수 있다는 것"을 기대한다라고 표현했어요. 우리가 Queue라는 객체에 enqueue라는 메시지(요청)를 전달할 수 있고, Queue는 내부적으로 enqueue라는 메시지에 자신만의 구현으로 응답하는거에요.

제가 너무 어렵게 말씀드리는 것 같은데, 쉽게 한 줄로 요약해보자면 구현은 숨기고 인터페이스만 드러내야 전체적인 객체간의 협력의 유연성이 높아져요. 이를 위해서는 변하는 것과 변하지 않는 것을 구분하는 연습이 필요해요.

Queue의 기능에서 변하지 않는 것은 enqueue, dequeue라는 인터페이스에요. 변할 수 있는 것은 내부 자료구조 및 구현이 되겠죠. 비슷한 예로 값을 저장하는 어딘가에 저장하는 역할을 담당하는 객체에게 변하지 않는 것은 값을 저장하는 행위에요. 하지만 변할 수 있는 것은 저장소가 되겟죠. 서버에 저장할 수도 있고 로컬 DB에 저장할 수도 있는 것이구요.

여기서 "저장"이 추상화된 행위이고 "저장 방법"은 실제 구현인겁니다!

2022-05-23 14:44 UTC, protocorn93 commented on Calculator/Calculator/Model/Node+LinkedList.swift
> +        currentNode?.nextNode = newNode
물론 `head` 하나만으로도 링크드리스트의 기본 기능들을 구현할 수 있지만, 맨 끝 노드를 가리키는 `tail`을 하나 더 두고 관리하면 그 구현이 훨씬 수월해질 수 있어요

2022-05-23 14:44 UTC, protocorn93 commented on Calculator/Calculator/Model/Queue+CalculatorItemQueue.swift
> +    private var queue = LinkedList<Element>()
`queue`는 클래스 인스턴스 레퍼런스 변수이기에 `let`으로 선언되어도 무방해보여요

2022-05-23 14:44 UTC, protocorn93 commented on Calculator/Calculator/Model/Queue+CalculatorItemQueue.swift
> +    }
`queue`에 할당된 값을 변경하는 것이 아니라, queue가 가리키는 인스턴스는 변함이 없고 그 내부의 값을 변경하는 행위이기에 `mutating`는 불필요해보여요

2022-05-23 14:54 UTC, minsson commented on Calculator/Calculator/Model/Node+LinkedList.swift
> +        currentNode?.nextNode = newNode
그렇네요!! `tail`이 있으면 우선 `append(_:)`에서 가장 끝 노드를 찾아가는 멀고 먼 여정을 생략할 수 있겠다는 생각이 들어요.

2022-05-23 14:56 UTC, minsson commented on Calculator/Calculator/Model/Queue+CalculatorItemQueue.swift
> +    }
맞아요 😭 이런 디테일한 부분도 더 세세하게 볼게요! ☺️

2022-05-23 14:57 UTC, merged