계산기 [STEP 2] 수꿍
yagom-academy/ios-calculator-app pull request #250
Opened 2022-05-19 14:50 UTC by Jeon-Minsu

안녕하세요, 찰리!! @kcharliek 
너무 늦은 시간이지만 계산기 프로젝트 STEP 2 PR 보냅니다!!
STEP2의 기능들을 완벽하게 구현하였다고 보기는 어렵지만, 현재 혼자 고민할 수 있는 범위 내에서
최대한 고민을 해보고, 찰리와 함께 피드백을 나누고 싶어 이렇게 PR 드립니다.
특히, 고차함수들을 적극적으로 사용하려한 결과 여쭤보고 싶은 점이 많이 생겼습니다. 
이번에도 잘 부탁드립니다!! 🙇‍♂️🙇

## 고민한점 
### 1. Queue 생성 방법case-less enum 초기화 문제

- 계산기 프로젝트 STEP2 `UML`에 따르면, `ExpressionParser`는 열거형 구조로, `parse()` 함수와 `componentsByOperators` 함수만 내부에 구현되기를 요구하였습니다. 이전까지 접한 열거형 구조는 모두 프로퍼티 혹은 메서드가 구현된 적이 있었으나, 이 경우들 모두 `case`를 가지고 있던 사례들이었습니다. 하지만, 이번에 처음으로 `case`가 내부에 구현되지 않은 `enum` 구조를 접하게 되었습니다. 이에 초기화 없이 어떻게 열거형 구조 내의 인스턴스 메서드를 호출할 수 있을지 갈피를 잡지 못하였습니다. 하지만 두 가지 사실을 통하여 위의 문제를 해결할 수 있었습니다.

- 먼저, `case`가 구현 되지 않은 `enum`은 인스턴스로 생성이 불가능하여, 뜻하지 않는 초기화를 막을 수 있고, 순수히 `namespace` 로서만 작동할 수 있다는 장점을 알게 되었습니다. 즉, `case-less` `enum`은 의도된 구조임을 확인할 수 있었습니다. 다음으로, `UML`에서 `ExpressionParser` 내부의 함수에는 밑줄 표시(underline)가 되었다는 점을 간과하였습니다. 밑줄 표시는 해당 프로퍼티 혹은 메서드가 `static` 임을 의미합니다. 즉, `ExpressionParser` 내부 메서드인 `parse()` 함수와 `componentsByOperators`는 인스턴스 메서드가 아닌 타입 메서드로 구현되어야 함을 깨달았습니다. 타입 메서드로 이를 구현하면, 초기화 없이도 열거형 구조내 원하는 메서드를 사용할 수 있었습니다.

<br>

### 2. ExpressionParser 내 componentsByOperators 메서드 존재 이유

- 코드

```swift
private static func componentsByOperators(from input: String) -> [String]
```

- `ExpressionParser` 내 `componentsByOperators` 메서드를 구현하는 이유가 처음에 납득이 가지 않았습니다. `parse()` 함수에서 충분히 입력받은 값 내에 존재하는 연산자를 추출할 수 있다고 생각이 되는데, 왜 굳이 하나의 함수를 더 생성하였고, 추출을 할 거면 피연산수인 `operand` 또한 추출이 되어야 하는데, 왜 연산자만을 추출하는 지 납득이 가지 않았습니다.

- 이에 고민한 결과, 두 가지 근거를 발견하였습니다. 먼저, 연산자만을 추출한 이유는 피연산자를 먼저 추출한다면, 예를 들어, “10+2-3”이라는 `string` 값을 입력받았다면, 고차함수 `filter`나 `split`을 통해 추출하면 ‘10’, ‘2’, ‘3’이 추출되는 것이 아닌, ‘1023’ 혹은 ‘1’, ‘0’, ‘2’, ‘3’이 추출된다는 것을 발견하였습니다. 이는 우리가 계산기에서 원하는 결과는 후자가 아닌 전자의 상황입니다. 따라서 이를 온전하게 추출하기 위하여서는 아래의 코드에서 알 수 있듯, `filter`를 통하여 입력받은 값 내 숫자가 아닌 값, 즉 연산자만을 추출한 다음, 하나의 `string`으로 반환된 연산자를 `map`을 통하여 `[String]`으로 반환하면, 각각의 요소에 연산자를 하나씩 배분할 수 있게 됩니다.

- 코드
```swift
let operators = input.filter { $0.isNumber == false }.map { String($0) }
```

- 그리고 이 연산자 배열을 `parse()`함수에 가져와 이를 바탕으로 `split`을 진행하면, 피연산수를 각각의 자리수에 맞게 온전하게 추출할 수 있었습니다. 정리하자면, 함수의 기능별 분리와 피연산수가 아닌 연산자를 먼저 추출하여 `[String]`에 넣기 위하여 프로젝트 요구사항에 기입되었던 것 같습니다.
<br>

### 3. for-in 구문(반복문) 지양 고민

- 계산기 프로젝트 요구 사항에 따르면, 변수보다는 상수를, 반복문 조건문 보다는 고차함수를 더 활용하기를 권장하였다. 이에 `ExpressionParser` 구조체의 `parse()` 메서드 내에서 하나하나 추출한 연산자와 피연산수를 각각의 큐에 `enqueue()`하는 과정에서 사용된 `for`문을 사용하지 않고, 값이 원하는 바와 같이 들어갈 수 있기 위해서는 어떤 방법이 있을지 궁리하였습니다.
> 

- 코드

```swift
for i in 0..<operators.count {
    operatorsQueue.queue.enqueue(element: operators[i])
}
for j in 0..<operands.count {
    operandsQueue.queue.enqueue(element: Double(operands[j]) ?? 0.0)
}
```

- 이에 고차함수 `forEach`를 이용하면 반복적으로 `enqueue()` 메서드를 실행할 수 있었습니다. `forEach`는 컬렉션 요소의 갯수만큼 반복해주는 고차함수로, `for-in` 루프와 동일한 순서로 시퀀스의 각 요소에 대해 주어진 클로저를 호출합니다. 반복할 작업을 클로저에 작성하여 파라미터로 넘겨주고, `Collection`에 저장된 요소는 클로저를 반복 실행할 때마다 클로저 상수로 넘겨받습니다. `for - in` 반복문과 `forEach`의 차이로 반복문이냐 아니냐가 있었습니다. `for-in` 구문은 반복문으로 `continue`, `break`를 사용할 수 있지만, `forEach`는 반복 기능을 하는 메서드로 다음의 기능을 사용할 수 없었습니다. 이는 클로저의 현재 호출을 종료하거나 후속 호출을 건너뛸 수 없음을 의미합니다.

- 다음으로, `forEach` 메서드는 `return` 문을 사용하면 외부 범위가 아니라 본문에 대한 현재 호출에서만 종료되며 후속 호출을 건너뛰지 않습니다. `for-in` 구문의 경우 반복을 하다가 `return` 키워드를 발견하면 함수 자체가 종료됩니다. 하지만, `forEach`에 경우는 `return` 키워드를 발견할 시, 현재 자신이 전달한 클로저를 종료하고, 다음 반복 클로저가 실행됩니다(클로저를 요소 갯수를 초과하지 않았다는 가정 하). 즉, 반복 횟수는 절대적이기에 `return`문을 발견하여도 반복 횟수에는 영향을 주지 않음을 의미합니다.

- 따라서, 추출한 연산자와 피연산수는 절대적으로 연산큐에 입력받아야 되기 때문에 `for-in` 구문보다는 `forEach`를 사용하여 확실하게 `enqueue` 하는 것이 더욱 적절하다 판단하여 이를 사용하였습니다.
<br>

## 의문점

### 1. extension String 존재 이유

- 프로젝트 요구사항으로 `String`의 `extension`을 구현하고, 추가적으로 `Character` 값을 입력받으면 `[String]`으로 반환하는 `split` 함수를 구현하는 내용이 있었습니다. 저는 이 `String` `Extension` 내 `split` 함수가 `ExpressionParser` 열거형 구조 내 `parse()` 메서드의 기능 구현을 위하여 `componentsByOperators()` 메서드에서 반환받은 `[String]` 타입의 값의 요소 하나하나를 이용하여 피연산수를 연산자와 분리하기위하여 사용해야 된다고 판단하였습니다. 하지만 `string` `extension` 내 `split`을 이용해본 결과, 먼저 각 요소를 `Character`로 변환해주어야 하고, 한번에 피연산수를 추출하지 못하여 이용하는 것이 옳지 않다고 판단하였습니다. 특히, 후자의 근거 때문에 사용을 기피하였는데, 이를 예를 들어 설명해보겠습니다.
 

- “10+2-3” 이란 `string` 값을 입력받으면, `componentsByOperators()` 메서드를 통하여 [”+”, “-”]를 추출할 수 있습니다. 그리고 다시 이 “10+2-3” 입력값에 동시에 연산자를 추출하지 않고, 반복문을 이용하여 하나하나 추출하게 된다면, [“10”, “2-3”], [”10+2”, “3”]와 같은 결과 값을 얻게 됩니다. 그렇다고 한번 쪼갠 결과값을 다시 한번 받아, `split` 함수를 구현할 수 없었습니다. 이는 `split` 메서드의 반환값이 `string`이 아닌 `[String]`이기 때문에 `string` 메서드를 사용하지 못하기 때문입니다.
> 

- 코드

```swift
// 실패방법 1

for number in 0..<operators.count {
        let operands = input.split(with: Character(operators[number]))
}

// result
// ["10", "2-3"]
// ["10+2", "3"]

// 실패방법 2

let operands_1 = input.split(with: Character(operators[0]))
let operands_2 = operands_1.split(with: Character(operators[1]))

// result
// operands_1은 string이 아닌 [String]이므로 split 메서드 사용 불가
```

- 저는 이를 해결하기 위하여, `string` `extension`에 구현한 `split` 함수가 아닌, 기존의 `split` 함수의 `whereSeparator` 파라미터를 통하여 클로저로 “operators.contains(String($0))”를 입력하여 연산자가 있는 위치를 기준으로 피연산수를 분리하여, [“10”, “2”, 3”]이라는 원하는 값을 반환할 수는 있었습니다. 하지만, `string`에 `extension`을 통해 `split(with:)` 함수를 만든 근거가 반드시 있다고 생각합니다. 따라서, `extension`을 통해 구현한 `split(with:)` 함수를 통해서 계산기 입력값을 원하는 값으로 반환하는 방법이 있을지 궁금합니다.
<br>

### 2. result() 함수 내 reduce 고차함수 구현 가능 여부

- `Formula` 구조체 내 `result()` 함수는 연산큐에 들어간 모든 값을 계산한 결과를 반환하는 함수로 이해하였습니다. 이에 실수(`double`) 연산큐 내의 첫 값부터 호출하고, 다음으로 연산자(`string`) 연산큐의 첫 연산자를 호출하고, 다시 실수(`double`) 연산큐 내의 두번째 값을 호출하여 연산을 해야 한다고 판단하였습니다. 우리의 인식 속 계산기는 “10 + 2 - 3 + 4”의 값이 있으면, “10+2”를 먼저 연산하여 결과값 “12”를 반환하고, 이를 다시 좌변에 두어 “12 - 3 + 4”의 연산이 이루어진다고 생각합니다. 하지만, 코드로 이를 구현하면, 좌변과 우변을 각각 `operands.queue.dequeue()`로 설정한다면, “10 + 2”는 정상적으로 이루어지지만, 다음의 연산은 “3 - 4”가 되어버립니다. 따라서, 연산의 결과가 `calculate` 함수의 좌변에 항상 위치하게 하여 다음과 같이 계산기 기능을 구현하였습니다.

- 코드

```swift
mutating func result() -> Double {
    var result = operands.queue.dequeue() ?? 0.0
    
    while operators.queue.isEmpty == false {
        let `operator` = operators.queue.dequeue() ?? ""
        let operatorCase = Operator(rawValue: Character(`operator`))
        
        result = operatorCase?.calculate(lhs: result, rhs: operands.queue.dequeue() ?? 0.0) ?? 0.0
    }
    
    return result
}
```

- 이에 구현은 성공하였으나, 요구사항에서 반복문을 지양하라는 내용이 있기에, 이를 고차함수인 `reduce`를 이용하여 `calculate` 메서드 내 좌변은 결과값이 항상 업데이트되고, 우변은 `operands.queue.dequeue()`를 입력하면 구현이 가능하지 않을까 생각했으나, 끝내 이를 해결하지 못하였습니다. 일단 이해를 위하여 다음과 같이 `reduce()`를 이용한 코드를 구현해보았습니다.
 

- 코드

```swift
let result = operands.queue.enqueueStack.reduce(0) { operatorCase?.calculate(lhs: result, rhs: operands.queue.dequeue()) }
```

- 첫번째 문제는, 좌변에 들어가는 `result`의 값이 계속 업데이트 되어야 합니다. 일반적인 `reduce()` 에서는 이를 구현하는 방법을 찾지 못하였지만, `reduce(into:)` 함수를 이용하면 좌변의 `result`를 값을 업데이트 할 수 있을 가능성을 발견하였습니다. 다음으로, 우변의 값을 “operands.queue.dequeue()”을 이용한다면 `dequeue()` 메서드에 구현된 `enqueueStack`의 요소를 없애는 `removeAll()` 메서드를 통하여 `enqueueStack`이 빈 배열이 되고 맙니다. 하지만, 이또한 우변의 값을 `$0`으로 설정하면 해결할 수 있을 것입니다. 그러나, 마지막 가장 큰 문제로, `operatorCase`에서 큐에 들어간 연산자의 순서대로 다양한 연산자가 때에 맞춰 입력되어야 하나, 위와 같이 코드를 작성하면 하나의 연산자로만 `calculate` 메서드가 작동하게 됩니다. 이에, 찰리에게 반복문을 사용하지 않고 `operatorCase`가 시기적절하게 들어갈 수 있는 방법이 있는지 질문드립니다.
<br>

### 3. 나누기 0에 대한 에러 처리 방법

- `Operator` 열거형 구조 내에 `divide` 메서드에 대하여 우변의 값이 0이면, 다시 말해 나누는 값이 0이면 `CalculatorError`의 `dividedByZero` 에러 케이스에 `throw`하는 기능을 구현하였습니다. 이를 통해 `dividedByZero` 에러 발생 시, `NaN`을 반환하는 식으로 구현해보고자 하였습니다. `divide`의 에러는 `calculate` 함수 내에서 `do-catch`를 통해 처리가 되어야 한다고 판단하였으나, `calculate`함수의 반환타입은 `Double`이므로 `NaN`이라는 `String` 값을 반환할 수 없었습니다. 일단, 입력 받을 것 같지 않은 `Double(Int.max)`를 반환하여 `UI`와 연동할 시 `Double(Int.max)`의 값이 나올 때 `text`로 `NaN`이 표시될 수 있도록 하는 방식을 고려해보았습니다. 이에 대하여, `calculate`에서 에러 처리를 하는 것이 적절해 보이는지, 그리고 `String` 값을 반환하기 위한 좋은 방법이 무엇이 있을지 조언을 구하고 싶습니다.
<br>

2022-05-21 04:02 UTC, kcharliek commented
## 고민한 점에 대해

1. 'enum' 대해, UML 설계 의도는 말씀하신 것 처럼 namespace를 위함이 맞아보입니다. 그러나 저는 namespace + static method 조합의 Util 설계를 피하는 편입니다. static 의 여러 단점들에 대해서는 최적화가 많이 되어서 그 이유는 아니고요. 단순히 애플이 그렇게 사용하지 않기 때문입니다. 실제로 애플의 Util 설계 사례를 보면 static method를 사용하는 경우가 거의 없습니다. JSONDecoder, DateFormatter 등. 현재 설계에 대해 이견이 있는 건 아니니 이런 의견도 있다 정도로 받아들여주시면 좋겠습니다.

2. componentsByOperators 에 대해. 이미 구성된 설계에 꼭 맞출 필요는 없다고 생각합니다. 기본 가이드 정도로 해서 나름의 설계로 변경해서 진행하셔도 괜찮습니다. 설명주신 부분들에 대해서는 이견없습니다.

3. 이견 없습니다

2022-05-21 04:18 UTC, kcharliek commented
## 의문점에 대해

1. extension String 존재 이유

수꿍의 구현 방법이 좋다고 생각합니다만, 꼭 split(_ char: Char) -> [String] 을 이용해서 구현한다면, 특정 메서드를 재귀(or Loop) 로 호출해서 구현할 수 있을 것 같습니다.

"-", "+", "*", "/" 이 포함 되지 않을 때 까지 쪼개는 식입니다.
"10+1-2" (+ 로 쪼갬) ->  "10", "1-2" (- 로 쪼갬)-> "10", "1", "2" -> Operator 없으니 탈출.

2. 말씀 주신 방법은 잘 이해하지 못했습니다.

반복문을 사용하지 않고 reduce 로 구현하는 방법을 고민해본다면, 맨 앞에 "+" operator를 넣고 0부터 계산을 시작하는 방식이 있을 것 같습니다.
예를 들면 "10+3-4" 를 게산한다면 맨 앞에 + 를 넣어서 "+10+3-4" 를 만들고요. 이를 쪼개서 (+, 10), (+, 3), (-, 4)의  Tuple Array 로 만들어  Queue에 넣습니다. 그리고 하나씩 dequeue하며 0부터 Operator에 따라 계산을 해 나가는 방식으로요.

3. 에러 처리에 대해
"Double(Int.max) 를 Error로 본다" 와 같은 구현은 좋지 않습니다. 누군가 보기엔 Int.max 또한 정상 값일 수 있고, Int.max가 Error라는 사실을 별도로 관리해야하는 번거로움이 있기 때문입니다. 오류가 난다면 차라리 Optional로 두어 return nil을 반환하는 것이 나을 것 같고요. 조금 더 정석으로 접근하자면 Result타입을 이용한다던지, calculate 또한 throwable하게 구현하시면 됩니다.

2022-05-21 04:24 UTC, kcharliek commented on Calculator/Calculator/Model/Operator.swift
> +    func calculate(lhs: Double, rhs: Double) -> Double {
계산 로직 Operator 내부에 있는 것 좋네요.👍

2022-05-21 04:36 UTC, kcharliek commented
Base Branch 확인 바랍니다.

2022-05-21 04:37 UTC, kcharliek requested changes
코드 전반적으로는 이상 있는 부분 없어보입니다. 잘 해주셨어요 :)

계산 관련한 테스트 코드가 없어보이는데요. 이를 추가해주시는 것을 필수 수정 사항으로 하겠습니다~

2022-05-23 10:07 UTC, kcharliek commented on Calculator/Calculator/Model/Formula.swift
> +    var operands: CalculatorItemQueue<Double>
private으로 변경해주세요. 
계산기 사용자는 Formula 내부가 operands와 operators 로 구성되어있다는 것에 관심이 없습니다.

2022-05-23 10:28 UTC, kcharliek commented on Calculator/Calculator/Model/Formula.swift
> +    mutating func result() -> Double {
1. throw 로 구현해주세요
2. ?? 를 제거하고 if-let 등 optional - binding을 사용해서 구현해주세요

2022-05-23 11:39 UTC, Jeon-Minsu commented on Calculator/Calculator/Model/Formula.swift
> +    var operands: CalculatorItemQueue<Double>
`Formula` 내부 `operands`와 `operators` 은닉화 수정 완료하였습니다.

2022-05-23 16:16 UTC, Jeon-Minsu commented on Calculator/Calculator/Model/Formula.swift
> +    mutating func result() -> Double {
throw를 통한 에러처리와 ??를 제거하고 guard구문을 통하여 옵셔널 바인딩을 진행해보았습니다.

2022-05-24 01:20 UTC, kcharliek commented on Calculator/FormulaTests/FormulaTests.swift
> +        XCTAssertEqual(result, expectation)
Error -> String 변환을 하지 않고, Error 자체로 Equality를 비교했어도 괜찮았을 것 같습니다.

2022-05-24 03:09 UTC, Jeon-Minsu commented on Calculator/FormulaTests/FormulaTests.swift
> +        XCTAssertEqual(result, expectation)
피드백을 반영하여 수정완료하였습니다 😄

2022-05-24 03:33 UTC, merged