계산기 [STEP 2] 나이든별
yagom-academy/ios-calculator-app pull request #251
Opened 2022-05-20 02:41 UTC by OldStarKR

@protocorn93 안녕하세요 콘! 두 번째 PR입니다. 이번에도 잘 부탁드립니다.

### STEP 2 작업한 내용
* 사칙연산을 나타내는 `Operator` 타입을 구현했습니다.
* 사용자가 입력한 식을 나타내는 `Formula` 타입을 구현했습니다.
* 사용자의 입력을 받아서 `Formula`로 바꿔 주는 `ExpressionParser` 네임스페이스를 구현했습니다.

---

### STEP 2 고민한 점
* 기능 요구서에 주어진 UML의 해석이 전반적으로 어려웠습니다. 아직 UML에 대한 숙련도가 떨어질 뿐더러, 제 자신이 생각하고 짠 것이 아니기 때문에 주어진 요구사항을 어떻게 구현해야 할지에 대해 많이 고민했습니다.
* `ExpressionParser` 안의 `componentsByOperators`가 무슨 뜻인지 알아듣지 못해 처음에 어려움을 겪었습니다. 일단 연산자만 반환하는 거라고 받아들여서, 연산자만 반환했습니다.
    * 원래는 result 배열을 따로 만들고 연산자의 `allCases`에 대해 `forEach` 클로저 안에서 `result` 배열 안에 들어있는 개개의 케이스마다 연산자를 기준으로 분리해주고 flatten해주는 과정을 반복해서, 숫자와 연산자가 예쁘게 떨어져 있는 배열을 반환하고자 했으나, 클로저 안에서 `compactMap`을 불러올 수가 없었어서, 현재의 방향으로 선회했습니다.
    * 또한 해당 배열을 만들 수 있다 해도, 연산자를 판별할 수 있는 `isNumber`는 `Character`를 대상으로 하는 메서드라, 두 자리 이상의 수를 반환할 수 없다는 문제도 있었습니다. 이래저래 연산자만 반환하는 것이 맞다고 받아들였지만.. 꺼림칙함을 지울 수 없었습니다.
* 0으로 나눌 때, 큐에 더 이상 아이템이 없을 때 등 에러 핸들링을 해야 할 몇 가지 상황에 todo 주석을 달아 두었는데, 이는 함부로 뭘 추가하지 말라는 기능 요구서에서의 요구사항 때문입니다. 물론 에러 케이스를 분리하는 것은 좋다고 써 있지만, 그와는 별개로 새로운 타입의 지정이기 때문에, 이 문제를 저 자신이 인지하고 있는 상태에서 리뷰어와 대화를 나눠 보고 싶었습니다. 
    * 기본값을 0으로 지정한 이유는, 계산기라는 프로그램에서 기본값은 0으로 여겨지기 때문입니다. 다만 이 경우, 의도치 않게 0으로 나누는 문제가 발생할 수도 있어, 주시하고 있습니다.
* 케이스가 하나도 없는 `enum` 안에 메서드를 써 넣는다는 것은, `enum`을 온전히 네임스페이스로 쓴다는 것임을 알았습니다. 따라서 `static`을 붙여야 불러올 수 있었습니다.
* 개인적으로 시간에 쫓길 일이 있어서, 완전히 TDD를 적용하지 못 한 것이 아쉽습니다.

---

### STEP 2 조언을 얻고 싶은 점
* 기능요구서의 UML에 작성되어 있는 `split`함수의 구현 요구사항에 대한 이유가 궁금합니다.
    * 기존 `split`은 `String`을 반환하지 않으니까, 라고 하면 이해는 가지만, 그리고 요구서에 써 있는 대로 구현했지만, 구현한 것을 당장은 사용하지 않았습니다. `ExpressionParser` 안에서 사용한 `split`은 [여기](https://developer.apple.com/documentation/swift/string/2893447-split) 나온 `split`입니다.
    * `Operator`가 `CaseIterable`인 이유, `split`을 구현하게 한 이유, `componentsByOperators`가 `[String]`을 반환하는 이유 모두 연계되어 있다고 생각해서 그쪽 방향으로 짜 보려고 했지만, 아쉽게도 세 가지 간의 얼개를 분명하게 찾을 수가 없었습니다.
* `parse` 메서드 안에서, 타입 캐스팅을 하는 과정에서는 어쩔 수 없이 옵셔널이 발생하게 됩니다. 이 경우 `if let`을 통해 옵셔널을 해제해 주었는데, 이렇게 하는 것이 이 상황에서 맞는지, nil-coalescing operator를 통해서 기본값을 주는게 더 나았을지 궁금합니다. 
    * 일단 `operators`와 `operands`는 이미 작성한 로직을 통해 내부의 값을 보장할 수 있으므로 값이 들어가지 않을 일은 없다고 생각했지만, 절대라는 건 없다고 생각하니만큼, 기본값의 제공을 통해 일단 동작하게는 했어야 했을지 궁금합니다. 
    * 다만 기본값을 제공한다면, 비슷한 오류가 발생했을 때 사용자가 의도치 않은 값을 받아들게 되고, 그것은 잘못된 동작이라는 면에서 결국 대동소이하다는 생각이 들었습니다.

---

2022-05-21 00:34 UTC, protocorn93 requested changes
@OldStarKR 고생하셨어요! UML만 보고 구현한다는 것이 절대 쉽지 않은 일인데 전체적으로 가독성 좋게 잘 구현해주신 것 같아요.

또한 누락되어 있는 것 같은데 _**`ExpressionParser`, `Formula`에 대한 단위 테스트 코드도 작성되어야 할 것 같아요.**_

## 고민한 점

> ExpressionParser 안의 componentsByOperators가 무슨 뜻인지 알아듣지 못해 처음에 어려움을 겪었습니다. 일단 연산자만 반환하는 거라고 받아들여서, 연산자만 반환했습니다.

저는 메서드 네이밍만 보고 operator를 반환하는 것이 아니라 operator를 기준으로 나뉘어진 요소들을 반환하는 메서드로 이해했어요. 어떻게 생각하시나요? 

> 0으로 나눌 때, 큐에 더 이상 아이템이 없을 때 등 에러 핸들링을 해야 할 몇 가지 상황에 todo 주석을 달아 두었는데, 이는 함부로 뭘 추가하지 말라는 기능 요구서에서의 요구사항 때문입니다. 물론 에러 케이스를 분리하는 것은 좋다고 써 있지만, 그와는 별개로 새로운 타입의 지정이기 때문에, 이 문제를 저 자신이 인지하고 있는 상태에서 리뷰어와 대화를 나눠 보고 싶었습니다.

저는 에러 타입은 명세와 별도로 정의해도 괜찮다고 생각해요! 

> 케이스가 하나도 없는 enum 안에 메서드를 써 넣는다는 것은, enum을 온전히 네임스페이스로 쓴다는 것임을 알았습니다. 따라서 static을 붙여야 불러올 수 있었습니다.

네네 맞아요. 그리고 기본적으로는 생성자를 통해 생성을 할 수 없기 때문에 잘못 사용되는 것을 방지할 수 있지요! 그래서 네임스페이스가 필요한 경우라면 구조체보다는 열거형을 사용하시면 되요! 

여기서 네임스페이스라함은 관련된 값을 묶어두는 용도로 사용될 수 있는데, 저는 아래와 같은 용도로도 자주 사용합니다. 

```swift
enum Metric { 
  static var buttonHeight: CGFloat = 80
  ...
}

```

> 인적으로 시간에 쫓길 일이 있어서, 완전히 TDD를 적용하지 못 한 것이 아쉽습니다.

너무 조급해하지 않으셔도 되요! TDD는 꾸준히 지속적으로 연습하셔야 해요. 코드로 작성하는 것도 중요하지만  사고방식을 TDD 처럼 바꿔보시는 연습도 해보시는걸 권장해드려요! 

## STEP 2 조언을 얻고 싶은 점

> 기능요구서의 UML에 작성되어 있는 split함수의 구현 요구사항에 대한 이유가 궁금합니다.

처음엔 개인적인 생각으론 `parse` ➡️ `componentsByOperators` ➡️ `split`(String extension)

이런 사용 구조를 갖는 것으로 생각을 했어요. `componentsByOperators`는 Operator를 반환하는 것이 아니라 Operator 기준으로 나뉘어진 요소들을 반환하는 녀석이 아닐까 하는 생각을 했어요.

> parse 메서드 안에서, 타입 캐스팅을 하는 과정에서는 어쩔 수 없이 옵셔널이 발생하게 됩니다. 이 경우 if let을 통해 옵셔널을 해제해 주었는데, 이렇게 하는 것이 이 상황에서 맞는지, nil-coalescing operator를 통해서 기본값을 주는게 더 나았을지 궁금합니다.

이 부분에선 `while let`을 활용해볼 수 있을 것 같은데 어떻게 생각하시나요?

2022-05-21 00:34 UTC, protocorn93 commented on Calculator/Calculator/Application/Domain/Models/Operator.swift
> +        }
아차 명세에 throw가 명시되어 있지 않아 그러신걸까요?

2022-05-24 07:37 UTC, OldStarKR commented on Calculator/Calculator/Application/Domain/Models/Operator.swift
> +        }
ㅎㅎㅎ맞습니다!! `CalculatorError` 타입 정의해서 전반적으로 에러 핸들링 해 주었습니다.

2022-05-24 07:41 UTC, OldStarKR commented on Calculator/Calculator/Extensions/String+Extensions.swift
> +        return self.split(separator: target).map { String($0) }
처음에 그렇게 했던 이유는, `split`이 `Character`를 반환하기 때문에 이렇게 해 주었던 것입니다.

하지만 아무래도 요구사항을 잘못 구현한 것 같다고 생각이 되어 다시 구현하는 과정에서 해당 부분은 없어졌습니다. 다만, 먼저 타입 캐스팅을 진행해 상수에 할당하고 해당 상수를 기반으로 작업을 하는 방법을 전반적으로 채용하는 계기가 되었습니다.

2022-05-24 07:49 UTC, OldStarKR commented on Calculator/Calculator/Application/Domain/Models/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
처음에는 `result` 메서드가 `dequeue` 동작을 수행해줘야 하고, `dequque`는 `mutating` 메서드기 때문에 두 개의 큐를 변수로 지정해야 한다고 생각했습니다.
그러나 말씀해주신 대로 상수로 설정하고 사용할 방법을 생각해보니, `result` 메서드 안에서 상수 프로퍼티인 `operators`와 `operands`를 변수로 복사해준 다음, 해당 큐 두 개를 기반으로 계산을 진행하는 방법을 떠올렸습니다. 그리고 테스트를 진행한 결과 잘 작동되었습니다. 
프로퍼티를 immutable하게 정해줌으로써 만약의 경우 일어날 수 있는 데이터 손상을 미연에 방지할 수 있고, result 메서드에도 불필요한 mutating 키워드를 제거해줄 수 있었습니다. 😉

2022-05-24 07:56 UTC, OldStarKR commented
아무래도 `ExpresssionParser`가 말씀해주신 부분으로 구현되는게 맞는 것 같다고 생각이 되어서, 이번 리팩토링에서는 해당 부분을 가장 신경썼습니다. 이외에도 피드백 주신 부분이 전반적으로 공감이 되는 내용이어서, 더 적극적으로 반영하게 된 것 같습니다.

2022-05-24 22:41 UTC, protocorn93 approved these changes
잘 봤어요! 👏 수고하셨어요!

2022-05-24 22:41 UTC, protocorn93 commented on Calculator/Calculator/Application/Domain/Models/Operator.swift
> +    func calculate(lhs: Double, rhs: Double) -> Result<Double, CalculatorError> {
오 👏 `Result` 타입을 활용하셨군요! 👍

2022-05-25 03:12 UTC, merged