계산기 [STEP 2] Borysarang
yagom-academy/ios-calculator-app pull request #252
Opened 2022-05-20 02:55 UTC by yusw10

안녕하세요 Cory!
계산기 STEP2 PR 보내드립니다.
이번엔 하면서 스스로 많이 부족했던것 같아서 가감없는 조언 부탁드립니다..!
@corykim0829 !

## 작업내용
- 연산자 피연산자를 분리하여 Formula에 초기화해주는 `ExpressionParser`구현
- 피연산자, 연산자 queue를 이용하여 계산 결과를 반환할 수 있는 `Formula`구현
- 각 연산에 대한 실제 연산을 구현한 `Operator`구현
- 테스트 케이스 작성
- 0으로 나누는 case를 핸들링하기 위한 `CalculatorError`와 case 지정
- Class Diagram 업데이트
- String의 `split`메서드 오버로딩

## 고민했던 내용

### Class diagram을 보고 구현
이번 STEP을 구현하면서 가장 고민을 했던 부분은 **"이 메서드, 타입은 왜 있는거지...?"** 였습니다. 특히 `ExpressionParser`의 `componentsByOperater` 메서드가 가장 고민이 많이 되었습니다. formula가 실제 피연산자와 연산자를 각 큐에 배정하고 실제 수식을 연산을 한다면, `formula의 각 queue에 할당해주는 parse만 있으면 해결되는것 아닌가? 라고 생각했습니다.`

우선 UML그대로 구현하기 위해 
1. parse에서는 연산자와 피연산자 queue에 값을 삽입해준뒤 formula 인스턴스를 반환 formula 인스턴스를 반환
2. componentsByOperator에서는 operator별로 분할해주기 위해 operator를 추출

이렇게 두가지로 기능을 분리해보았습니다. 

### character를 Operator 타입으로
Formula의 result() 메소드에서는 연산자와 피연산자를 순서대로 꺼내와 연산을 합니다. 각 요소는 LinkedList로 구현된 `Node<CalculatorItem>`타입이며 `Double`과 `Operator` 모두 CalculatorItem 프로토콜을 준수하고 있습니다.

저는 테스트를 위해 테스트코드를 아래와 같이 작성했습니다.
```swift
sut.operands.enQueue(15.0)
sut.operators.enQueue("+")
sut.operands.enQueue(9.0)
let result = sut.result()
XCTAssertEqual(result, 24.0)
```
Character타입을 가지고 Operator의 enum case를 유추해야하는 모순이 생겨서 이 부분을 어떻게 변경해야하나 고민했습니다. 

이 부분을 해결하려고 캐스팅을 여러가지로 시도하거나 CalculatorItemQueue를 수정해야하나 고민했는데 생각해보니 코드자체의 문제는 없었습니다. 
```swift
//given
sut.operands.enQueue(15.0)
sut.operators.enQueue(Operator.add)
sut.operands.enQueue(9.0)
//when
let result = sut.result()
//then
XCTAssertEqual(result, 24.0)****
```

애당초 연산자를 enQueue하는과정에서 Operator타입을 삽입하지 않고 Character를 삽입하고 있었습니다. 위의 코드대로라면 다시 매핑해주는 메서드가 필요했을것이라고 생각했습니다. 이 코드를 작성하면서 enQueue 파라미터에 대해 생각해 볼 수 있어서 Formula를 구현할 때 헤매지 않고 바로 작성할 수 있었던것 같습니다. 

자문자답을 해버린 내용이었지만 함수 파라미터로 프로토콜을 처음 사용해보느라 고민을 많이 해서 작성해보았습니다. 

## 궁금한 점

> <span style="color:red">**UML을 보고도 이해가 잘 되지 않는경우 Cory는 어떤식으로 해결하셨는지 궁금합니다.** 저는 제 나름대로 해석해서 작성하긴 했는데 이렇게 하는게 맞는 방법이라고는(맞는지를 떠나서 의도를 제 마음대로 해석했다 생각해서...)생각이 들지 않아 질문드립니다.</span>

> <span style="color:red">0으로 나누는 케이스를 테스트해주기 위해서 현재는 그냥 `debugPrint`를 사용했는데 에러 핸들링에 관련된 이렇게 하는게 맞는지, 아니면 throw를 상위개체로 전파하도록 구현해서 테스트코드에서 직접 do-try-catch로 해야하는지 아직 잘 모르겠습니다. </span>

> <span style="color:red">추가로 명세서의 UML 대로라면 Error에 대한 enum을 사용하지 못하는건데(class상에서 관계가 없기 때문에 이렇게 생각했습니다), 그렇다면 이 부분은 UML에 없더라도 사용해도 되는건지, 아니면 제가 미리 변경한다고 말씀을 드렸어야 했을까요...?</span>

2022-05-20 02:57 UTC, yusw10 commented
[Class Diagram]

![CalculatorAppClassDiagramStep1](https://user-images.githubusercontent.com/39454792/169441332-9b76a5d6-72d0-4b2f-a0c2-0e97f807e1b9.png)

2022-05-22 06:16 UTC, corykim0829 requested changes
수고 많으셨습니다 👍

> UML을 보고도 이해가 잘 되지 않는경우 Cory는 어떤식으로 해결하셨는지 궁금합니다. 저는 제 나름대로 해석해서 작성하긴 했는데 이렇게 하는게 맞는 방법이라고는(맞는지를 떠나서 의도를 제 마음대로 해석했다 생각해서...)생각이 들지 않아 질문드립니다.

➡️ 의도 부분은.. UML을 작성한 사람과 커뮤니케이션을 하면서 이해를 해야하는게 맞다고 생각합니다. 미션 형식으로 하기 때문에 힘든 부분이 있었을 것 같네요! 코드를 보면 잘 이해하신 것 같아서 너무 걱정안하셔도 될 것 같습니다!

> 0으로 나누는 케이스를 테스트해주기 위해서 현재는 그냥 debugPrint를 사용했는데 에러 핸들링에 관련된 이렇게 하는게 맞는지, 아니면 throw를 상위개체로 전파하도록 구현해서 테스트코드에서 직접 do-try-catch로 해야하는지 아직 잘 모르겠습니다.

➡️ 현재는 throw로 하는게 더 좋은 방법 같습니다! 잘 구현하셨어요! 일단은 debugPrint로 처리하시고, 나중에 UI 처리 하면서 에러 핸들링은 더 고도화 하면 좋을 것 같아요

> 추가로 명세서의 UML 대로라면 Error에 대한 enum을 사용하지 못하는건데(class상에서 관계가 없기 때문에 이렇게 생각했습니다), 그렇다면 이 부분은 UML에 없더라도 사용해도 되는건지, 아니면 제가 미리 변경한다고 말씀을 드렸어야 했을까요...?

➡️ 원래는 저에게 말을 해줬어야하는게 맞는 것 같습니다! 일단은 그대로 Error를 가지고 진행하는 걸로 하겠습니다!

2022-05-22 06:16 UTC, corykim0829 commented on Calculator/CalculatorTests/FormulaTests.swift
> +        sut = Formula(operands: CalculatorItemQueue(), operators: CalculatorItemQueue())
operands, operators에 CalculatorItemQueue 인스턴스를 이렇게 생성해서 주입하는게 조금 어색해 보이는데, 개선해보면 좋을 것 같습니다!

2022-05-23 11:25 UTC, yusw10 commented on Calculator/CalculatorTests/FormulaTests.swift
> +        sut = Formula(operands: CalculatorItemQueue(), operators: CalculatorItemQueue())
분리 해보았습니다. 
궁금한점이, 생성한 인스턴스를 변수에 따로 할당하고 Formula에 넣어주는 과정이 불필요한 과정이라고 생각해서(변수 두개만큼의 메모리를 쓴다고 생각했습니다) 이렇게 바로 파라미터부분에 생성자로 주입을 해준것인데 이정도는 "가독성을 위해서 분리해주는것이다" 라고 이해하면 되는걸까요?

[27b0c37](https://github.com/yagom-academy/ios-calculator-app/pull/252/commits/27b0c375dfc176ec280d33c561ee6db1a2ea06d5)

2022-05-23 11:26 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/ExpressionParser.swift
> +            }
enum의 `init(rawValue:)`  활용해서 수정 해보았습니다..!

[46d30e7](https://github.com/yagom-academy/ios-calculator-app/pull/252/commits/46d30e7afd0327e2f5ab521c9d5730c5b81e29a1)

2022-05-23 11:28 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/Formula.swift
> +            }
말씀주신대로 무한루프 해놓고 밑에 조건절을 바로 걸어둔걸 다시 읽어보니 좋지않은것같았습니다...!

[185e2ba](https://github.com/yagom-academy/ios-calculator-app/pull/252/commits/185e2ba146cd104e424b5cad002a757ba0e63769)

2022-05-23 11:31 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/ExpressionParser.swift
> +    static private func componentsByOperators(from input: String) -> [String] {
앗 혹시 componentsByOperators 메서드 맞을까요..?
class diagram에서 접근제한자가 언어별로 달라서 본인이 기준을 정하고 통일감있게만 사용하면 괜찮다고 야곰이 조언해주어서
1. + 기호는 internal
2. - 기호는 private
으로 만들었었습니다...!
다만 지금 componentsByOperators메서드에 private이 붙어있는데 fileprivate같은걸로 바꾸라는 말씀이신건지 잘모르겠습니다.

2022-05-23 11:32 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/Formula.swift
> +
넵 수정했습니다..!

[5e0dbd9](https://github.com/yagom-academy/ios-calculator-app/pull/252/commits/5e0dbd9beb9c06cfd5fee96a44b467a88c5d0463)

2022-05-23 11:32 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/Formula.swift
> +        guard var lhs: Double = operands.deQueue()?.value as? Double else {
넵 제거했습니다...!

[2dd52e6](https://github.com/yagom-academy/ios-calculator-app/pull/252/commits/2dd52e6a8012b082dab0656315d902a7d1fe598e)

2022-05-23 11:33 UTC, yusw10 commented on Calculator/Calculator/CalculatorQueue/Formula.swift
> +            guard let calcOperators = operators.deQueue()?.value as? Operator else {
`operator` 를 원래는 그대로 사용하려고 했었는데 이미 키워드로 등록이 되어있어서 `operators`로 사용했던것 같습니다. 
이부분도 수정해보았습니다..!

[f9f824d](https://github.com/yagom-academy/ios-calculator-app/pull/252/commits/f9f824da62f1fb0ffd66c4a6b774d2cca54dd0e9)

2022-05-24 12:28 UTC, corykim0829 commented on Calculator/Calculator/CalculatorQueue/ExpressionParser.swift
> +    static private func componentsByOperators(from input: String) -> [String] {
아 제가 잘못봤네요! 확인했습니다! 👍

2022-05-24 12:44 UTC, corykim0829 commented on Calculator/CalculatorTests/FormulaTests.swift
> +        sut = Formula(operands: CalculatorItemQueue(), operators: CalculatorItemQueue())
무엇보다 이런 방식으로 잘 처리하지 않아서 결국 가독성을 해치게 되는 것 같아요!
Formula 생성자에서 인스턴스를 생성해서 넣어줘도 되고, Formula 자체 프로퍼티가 인스턴스를 바로 생성해서 가지고 있어도 되죠.
그리고 외부에서 주입시켜주고 싶다면, 빈 Queue struct가 필요한 것이기 때문에 굳이 두개를 따로 생성하지 않고 하나의 struct 인스턴스를 각 파라미터에 넣어줘도 됩니다! 참고하세요!

2022-05-24 12:44 UTC, corykim0829 commented on Calculator/Calculator/CalculatorQueue/ExpressionParser.swift
> +            }
CaseIterable을 활용해서도 처리할 수 있어요! 참고하세요!

2022-05-24 12:45 UTC, corykim0829 approved these changes
수고 많으셨습니다!!

step3 목표일정 저에게 말해주시고 시작하시면 될 것 같아요!!

2022-05-24 12:45 UTC, merged