계산기 [STEP2] 웡빙
yagom-academy/ios-calculator-app pull request #253
Opened 2022-05-20 06:03 UTC by wongbingg

안녕하세요 제이크! @jryoun1  @wongbingg 입니다! 오늘 오전까지 PR을 목표 했었는데 완성되지 않은 부분이 많아 늦어졌습니다 🥲🥲 아무리 고민해도 해결되지 않은 부분 몇가지를 남겨두고 나머지 부분에 대한 PR 올립니다! 미숙한 부분이 많아 텍스트로 두들겨 패 주시면 감사하겠습니다 🔨

# STEP2

## UML Diagram
![](https://i.imgur.com/xfjdHte.png)

## 구현사항
- **CalculatorItemQueue**
    - Fomula 에서 사용되기 위해 `count` 읽기전용 연산프로퍼티와 `init()` 구문을 추가 해주었습니다. enqueue를 활용하여 하나씩 넣어주는 것보다 배열로 한꺼번에 초기화 시켜줄 때 넣어주는 편이 낫다고 생각했습니다.
- **Fomula**
    - Fomula = 공식 이라는 해석이 되었습니다. 이 공식이라는 구조체 안에서 연산자 큐 ( oprators ) 와 피연산자 큐 ( operands ) 안의 값들을 이용하여 result 라는 함수에서 전체 계산을 하도록 구현 해주었습니다. 
- **ExpressionParser**
    - string으로 들어온 값을 분리하여 연산자큐 와 피연산자큐 에 나눠 담아주는 작업이 이루어 졌습니다.
- **Operator**
    - 각 케이스 별로 이루어지는 계산로직을 다르게 실행해줄 수 있도록 `switch - case` 를 이용했습니다. 
- **Extension Double**
    - 이 부분의 역할을 파악하지 못했습니다
- **Extension String**
    - 기존의 split 함수는 ``[SubString]`` 을 반환하지만, ``[String]`` 을 반환할 수 있도록 새롭게 만들어 주었습니다.

## 고민한 점 & 궁금한 점
- force unwrapping
    - 첫번째로, 최소 연산자 한개와 피연산자 두개가 존재해야 한다는 guard 문을 작성 했습니다.
    ```swift
    mutating func result() -> Double? {
        guard operands.count > 1 && operators.count >= 1 else { return nil }
    ```

    - 두번째로, guard 문에서 걸러진 데이터를 활용하는 것이기에 dequeue() 의 값은 무조건 존재한다 생각하여 옵셔널 바인딩 처리는 따로 하지 않고 force unwrapping 을 해주었습니다. 이 상황이 문제가 될까요?
    ```swift
    var result = Operator(rawValue: operators.dequeue()!)?
            .calculate(lhs: operands.dequeue()!, rhs: operands.dequeue()!) ?? 0
    ```
    - 세번째로, Operator의 rawValue("+","-","x","/")에 해당하지 않는 값이 들어갈 수 있으므로 옵셔널 체이닝이 이용되었는데, 이부분도 마찬가지로 화면에서 버튼을 입력받는 부분이라 저값 이외의 값이 들어오기는 힘들것 이라는 생각이 들어 force unwrap 처리를 해주고 싶었습니다. 어떻게 생각하시나요?  
- enum 타입의 테스트
    - expressionParser enum 에 대한 테스트를 진행할 때, 초기화구문이 없어 각 테스트케이스 마다의 초기화와 메모리 해제를 해줄 수 없어 어떻게 테스트할지 고민했습니다. 다른캠퍼와 상의 중 타입메서드로 만들어주면 테스트가 가능하다 하여 이 방법을 이용해 진행 했습니다. UML 다이어그램에 이 부분이 밑줄이 쳐저있는 것이 static 이라는 뜻일까요? 
- 테스트만을 위한 코드
    - 함수를 구현하다 보니, "CalculatorItemQueue" 에서 currenStack 이라는 프로퍼티와 enqueue() 함수는 테스트 코드에서만 사용된다는 것을 깨달았습니다. 이 부분은 어쩔 수 없는 것일까요? 
- 에러처리
    - 나누기 0 을 할 경우 "NaN" 이라는 문구를 텍스트 필드에 표시 해주어야 하는데, Operator 내에 divide 함수에서 에러를 처리해 주게 되면 반환타입인 Double을 반환하라고 오류가 나서 이 부분에 대한 조언을 듣고 싶습니다.

- 프로토콜 활용방법
    - 현재 CalculateItem 이라는 프로토콜을 활용하지 않고 있는데 이부분 활용 방법에 대한 조언을 듣고 싶습니다

2022-05-23 12:02 UTC, jryoun1 requested changes
step2도 고생하셨습니다 @wongbingg 👍🏻

코드도 전반적으로 깔끔하게 잘 작성하신 것 같고, 테스트코드도 잘 작성해주셔서 읽기 쉬웠던 것 같습니다 💯
다만 개선되었으면 하는 몇가지 부분들이 있어서 코멘트 남겨두었습니다 🙏🏻

### 고민한점 및 궁금한점
1. Fomula에서 force unwrapping

이에 대한 답변은 아래 코멘트에 남겼습니다.

2. enum 타입의 테스트

넵 웡빙이 말씀하신대로 static 속성을 가졌을 때에는 밑줄을 그어서 표기합니다👍🏻

3. 테스트만을 위한 코드

현재 스텝까지봤을 때는 테스트만을 위한 코드라고 볼 수 있겠네요. enqueue의 경우에는 step3에서 입력을 받았을 때 enqueue를 사용할 것 같긴합니다. 반면에 currentStack은 잘 모르겠네요 🤔
만약 웡빙이 불필요하다고 생각한다면 지워주셔도 될 것 같아요! 필요한 시점에 구현을 해도 될 것 같아요. 

4. 에러처리

throws를 사용해보는 건 어떨까요? 0으로 나눴을 때 throws를 하고 실제로 UI를 연동하는 부분에서 이에 대한 처리를 try, do-catch 문을 통해서 해결할 수 있을 것 같아보입니다! 

5. 프로토콜 활용방법

> step1 명세서에서 
CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다.
CalculateItem 프로토콜은 빈 프로토콜입니다.

음,, 저도 확실하지는 않지만 위의 명세서를 봐서는 CalculatorItemQueue에 들어올 수 있는 다양한 타입을 대비한 것이라고 생각이 됩니다. 다만 지금 상황에서는 빈 프로토콜 그대로 두어도 괜찮을 것 같습니다.

2022-05-24 05:02 UTC, wongbingg commented on Calculator/Calculator/Operator.swift
> +extension Operator {
`extension` 은 어떠한 타입에 기능을 추가할 때 사용하는 것으로 알고 있습니다. 또한 코드정리?를 위해 사용할 때도 있는데 저는 접근레벨이 `private` 으로 되어있는 함수들을 따로 빼주기 위해 사용하였습니다. `extension`에 `private` 접근레벨을 부여하게 되면 그 안의 멤버들의 접근레벨 또한 자동으로 default private으로 되기 때문입니다.

2022-05-24 05:03 UTC, wongbingg commented on Calculator/Calculator/Fomula.swift
> +        while !operands.isEmpty || !operators.isEmpty {
풀어서 써보니 훨씬 가독성이 좋아졌습니다 😄

2022-05-24 05:03 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +//MARK: - Fomula Test
숙지하여 각 타입별 테스트를 파일로 나누었습니다 😄

2022-05-24 05:05 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_operands에_1_2_3_9_27_2가들어가고_operator에_더하기_빼기_더하기_더하기_나누기가들어갔을때_result가_18_을출력하는지() {
코드를 통해 의도를 확인할 수 있는 테스트들은 이름을 모두 간략화 시켜 필요치 않은 문구를 제거 해주었습니다 😄

2022-05-24 05:07 UTC, wongbingg commented on Calculator/Calculator/ExpressionParser.swift
> +        Operator.allCases.forEach { i in
항상 놓치는 부분인 것 같습니다.. 🥲 
반복문의 의도를 파악할 수 있게 oneOperator라는 이름으로 변경 해주었습니다.

2022-05-24 05:54 UTC, wongbingg commented on Calculator/Calculator/Fomula.swift
> +        guard operands.count > 1 && operators.count >= 1 else { return nil }
"Formula" 타입에서 force unwrapping을 하지 않기 위해서 `"CalculatorItemQueue"`의 `dequeue()` 메서드에서 nil값이 들어올 경우를 `error`로 던져주는 작업을 하였습니다. 그리하여 "Formula" 에서는 하위 메서드`dequeue()`의 반환값을 non-optional  타입으로 받게되어 unwrapping이 필요가 없어졌습니다. 
결과적으로 nil이 생길 경우를 `error`로 만들어주어서 제거 해주었습니다. 이런 방식으로 제거하는 것이 좋은 방향인지 궁금합니다 ! 😵‍💫

2022-05-24 05:57 UTC, wongbingg commented on Calculator/Calculator/OperatorError.swift
> +enum OperatorError: Error {
에러 처리가 필요하다는 것은 인지하고 있었으나 어떻게 활용할지 몰라 일단 만들어놓고 본 것 같습니다 .. ㅎㅎ
이번 수정사항에서 각 타입별 에러타입을 만들었는데 혹시 프로젝트가 제시하는 방향에 어긋난 것 일까요?!
😿

2022-05-24 05:57 UTC, wongbingg commented on Calculator/Calculator/OperatorError.swift
> +//  OperateError.swift
확인했습니다 ! ☺️

2022-05-24 05:58 UTC, wongbingg commented on Calculator/Calculator/Fomula.swift
> +        var result = Operator(rawValue: operators.dequeue()!)?
확인했습니다 ! ☺️

2022-05-24 05:59 UTC, wongbingg commented on Calculator/Calculator/Fomula.swift
> +struct Fomula {
확인했습니다 ! ☺️

2022-05-24 06:00 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var sut2: Fomula!
테스트할 타입별로 파일을 나누어 각각의 테스트파일에서 별개의 sut 으로 사용하게 되었습니다 ! 😁

2022-05-24 06:01 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +//MARK: - ExpressionParser Test
확인했습니다 ! ☺️

2022-05-24 06:01 UTC, wongbingg commented on Calculator/Calculator/Operator.swift
> +        switch self {
감사합니다 !  🫡🫡

2022-05-24 06:03 UTC, wongbingg commented on Calculator/Calculator/ExpressionParser.swift
> +        let operandsList = componentsByOperators(from: input).map{ Double($0) ?? 0}
확인했습니다 ! ☺️ 자꾸 디테일한 부분을 놓치는 것 같습니다 😵😵

2022-05-24 06:03 UTC, wongbingg commented on Calculator/Calculator/ExpressionParser.swift
> +        let operatorsList = Array(input).map{ String($0) }.filter{ Double($0) == nil }.map{ Character($0) }
감사합니다 !  🫡🫡

2022-05-24 06:26 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_operands에_1_2_3_9_27_2가들어가고_operator에_더하기_빼기_더하기_더하기_나누기가들어갔을때_result가_18_을출력하는지() {
0으로 나누기를 시도했을 때, OperatorError.dividedByZero 라는 오류를 던져주도록 구현 하였습니다.☺️

2022-05-24 09:56 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_operands에_1_2_3가들어가고_operator에_더하기_빼기_가들어갔을때_result가_0_을출력하는지() {
기존에는 "ExpressionParser" 에서 `parse(from: )` 에 들어오는 string 값에 띄어쓰기가 없을 것이라 생각했었습니다."1+2-3x-2" 이런 식으로 다닥다닥 붙어있는 형태를 생각했는데, 음수처리를 하는 상황에서 `componentByOperators(from:)` 에 string 이 들어가면 음수 부호마저 같이 사라져서 고난을 거쳤습니다. 동기 캠퍼들의 얘기를 듣던 중 띄어쓰기가 사이에 있을 것이라는 얘기를 듣고 바로 적용 해보니 
"1 + 2 - 3 x -2" 이런 식으로 띄어쓰기가 있다면 처리를 쉽게 해줄 수 있었습니다. 사용자 입력을 받을 때 띄어쓰기도 사이사이에 함께 지정 해주게 되면 이런 식으로 string이 들어올 것이라 예상됩니다. 
위 내용을 적용하여 음수값이 들어왔을 때의 test 까지 마무리 했습니다 ☺️

2022-05-24 12:35 UTC, jryoun1 commented on Calculator/Calculator/OperatorError.swift
> +enum OperatorError: Error {
앗 아닙니다 ㅎㅎ 단지 기획서에 이런 문구가 있었던 것 같아서 여쭤봤습니다 🙏🏻

> 아래 제시한 UML대로 연산과 관련한 타입을 구현합니다.
UML에 표기한 사항은 모두 구현해야합니다.
추가하고 싶은 사항이 있다면 리뷰어와 협의 후 진행하세요.
새로운 타입 추가 외에 UML의 기존 내용 수정은 불가합니다.

2022-05-24 13:22 UTC, jryoun1 approved these changes
고생하셨습니다~ 👏
몇 가지만 코멘트 남겼습니다! 
해당 부분들은 step3에서 반영해도 될 것 같아서 step2는 여기서 머지하겠습니다 🙂

2022-05-24 13:22 UTC, jryoun1 commented on Calculator/Calculator/Fomula.swift
> +        guard operands.count > 1 && operators.count >= 1 else { return nil }
넵 괜찮아 보입니다 👍🏻

2022-05-24 13:23 UTC, merged