계산기 [STEP2] KayAhn
yagom-academy/ios-calculator-app pull request #254
Opened 2022-05-20 06:43 UTC by KayAhnDS

@ryan-son 🌳
안녕하세요 Ryan! 
이번 스텝은 제가 저번 스텝에서 생각했던 그림과 달라 많이 생각해보고 또 세세하게 “어떻게 하라는 요구사항은 없어” 
최대한 러프하게 구현하는 방향으로 정하고 구현했습니다.

좋은 리뷰 항상 감사합니다.

## 📖 고민한 점 및 구현

### OperatorEnum

- Operator Enum에서 연산 프로퍼티 추가만 하면 유용하게 사용할 수 있기 때문에 rawValue대신 한번 추가 해봤습니다.
- calculate 메서드는 case에 따라 내부의 메서드를 불러오는 역할을 합니다.
    - divide할때 0을 나누거나 0으로 나눠주어 생기는 에러는 코드가 너무 지져분해 질것 같아 일부러 처리하지 않았습니다. → 나중에 try-catch로 잡아주겠습니다.

### SplitExtension, DoubleExtension

- SplitExtension 및 DoubleExtension 파일은 요구사항을 그대로 따랐습니다.

### ExpressionParser

- [http://www.cs.sjsu.edu/~pearce/modules/lectures/uml2/class/index.htm](http://www.cs.sjsu.edu/~pearce/modules/lectures/uml2/class/index.htm)
- UML에서 밑줄이 의미하는것이 무엇인지 검색하다 위의 주립대학의 자료를 보고 타입 메서드로 구현했습니다.

### CalculatorItemQueue<T>

- STEP1의 코멘트를 기반으로 수정 했습니다.

### Formula

- 2중 depth를 피하려 코드가 많이 어지럽습니다.
    - 함수를 써서 최대한 깔끔하게 하려했지만 이번 스텝은 무조건 UML에 있는 대로 하는것이 목표였기 때문에 그렇게 하지 않았습니다.
- 에러처리
    - 여기서도 → throw를 해서 에러처리를 하려했지만 원래 있는 메서드 원형을 건드리는것은 원하지 않아 그렇게 하지 않았습니다.
- 로직
    - 요구사항이 조금 더 유연해 지면 보기 좋고 이해하기 쉬운 코드가 나올것 같습니다.

### CalculatorItemQueueTests

- STEP1의 코멘트를 기반으로 수정 했습니다.

## 📖 해봤던것 및 생각한것

1. 이번 스텝에서 따로 TDD를 해보지는 않았지만 ViewControll에서 콘솔로 찍어봤을때 결과가 잘 나왔습니다.
2. 여러가지를 테스트 하던중에 만약 계산기에 괄호가 있다면 어떻게 해야할지 생각도 해봤습니다.
<br>

2022-05-21 18:55 UTC, ryan-son requested changes
케이~ 명확하지 않은 요구사항을 통해 이만큼이나 구체적으로 Step 2를 구현해보셨네요! 정말 대단합니다! 👏 

저도 UML을 통해 유추하는 것에는 한계가 있어 직접 구현해보며 추측해보고 시험해보길 반복한 것 같아요. 이 프로젝트는 UML 뿐만 아니라 해당 메서드가 어떤 역할을 수행하는지 정도는 함께 포함해야 하는 것이 아닌가하는 생각도 들었어요 (애플이 제공하는 프레임워크에서도 documentation을 통해 메서드 시그니처와 해당 메서드, 매개변수, 반환값에 대한 설명은 제공하니까요).

걱정하시던 것에 비해 기능을 거의 완벽하게 구현해주셔서 큰 틀에서의 이견은 없었어요. 어느 타입에서 어떤 범위까지의 일을 할 것인가에 대해 케이 나름대로 고민을 해보시고 이야기 나누면 재미있을 것 같다는 생각이 드네요.

TDD와 유닛 테스트는 다른 것이라는건 알고 계시죠~? TDD를 수행하지 않으셨다고 하더라도 구현 후 유닛 테스트를 작성하시면 구현한 내용에 신뢰성을 부여할 수 있어요! 이번 변경 요청사항은 개별 코멘트에 더불어 유닛 테스트를 작성하는 것으로 하겠습니다. 어떤 테스트 케이스를 포함하면 좋을지 깊게 고민해보시면 좋을 것 같아요.

그럼 고생 많으셨고, 계속해서 화이팅하세요~! 필요하시면 언제든지 말씀해주세요~ 😉

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        var operands = input.split { ["+", "-", "*", "/"].contains(String($0)) }
`Queue`의 요소를 `Operator`, `Double`으로 구성해주려면 `operators`, `operands`의 요소를 해당 타입으로 변환해주는 구문이 이 메서드에 포함되어야 할거에요. `(String 또는 Character)` <-> `Operator` 간 변환을 용이하게 하기 위해 UML에서 `Operator`의 `rawValue` 타입을 `Character`로 지정했다고 추측되네요. 현재와 같이 `rawValue`를 이용하지 않을 예정이라면 변환을 지원하는 연산프로퍼티 혹은 메서드가 필요할거에요.

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        var operands = input.split { ["+", "-", "*", "/"].contains(String($0)) }
연산자 종류를 구현부에서 직접 literal하게 작성하는 것은 유지보수 측면에서 좋지 않을 수 있어요. 예를 들어 연산자 마크가 변경되는 경우, `Operator`의 `ownValue`와 `parse(from:)` 메서드 구현부를 모두 수정해야 한다는건 구현한 사람이 아니면 모두 알기는 어려울 수 있을테니까요. 다른 방법을 고민해보는건 어떨까요? Operator는 이미 `CaseIterable`을 준수하고 있으니 이걸 이용해볼수도 있겠네요~ 제가 구현한 방식도 있는데, Step 2가 머지되는 시점에 한 번 이야기 나누어보아도 재미있을 것 같아요.

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        while !(operators.isEmpty && operands.isEmpty) {
- 저는 not 연산자가 가독성이 좋지 않은편이라 생각해서 isNotEmpty라는 연산프로퍼티를 extension으로 구현해서 사용하는 편이에요. 
- `operators.isNotEmpty && operands.isNotEmpty`를 그대로 써도 이해가 잘 되고 좋지만, `canCalculate` 또는 `canEnqueue` 등 연산프로퍼티를 정의해서 사용하는 것도 나쁘지 않을 것 같아요.

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        }
`operators`와 `operands`는 타입 변환만 해주면 `retrievedOperators`와 `retrievedOperands`의 생성자에 들어갈 수 있을 것 같은데, `while`문을 통해 `enqueue`를 해주는 것이 더 좋다고 판단하셔서 이렇게 방향을 잡으셨던걸까요?

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        return input.filter {$0 == "+" || $0 == "-" || $0 == "/" || $0 == "*" }.map { String($0) }
- 앞서 말씀드린 것처럼 Operator Character를 구현부에서 literal하게 작성하는 것은 바람직 해보이지 않은 것 같아요. 다른 방법은 없을까요?
- 고차함수에서 클로저 인자와 작동시킬 메서드의 매개변수 요구사항이 같다면 `.map(String.init)`과 같은 형식으로도 작성할 수 있으니 참고하세요~

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/OperatorEnum.swift
> +    }
UML의 요구사항에 따르면 Operator의 rawValue 타입은 Character이니 구현 요구사항에 따르면 ownValue의 내용이 case의 rawValue로 작성하는 것이 UML을 그린 사람의 의도였다고 볼 수 있겠네요. 각자 장단점이 있을 것 같아요.

1. 현재와 같이 작성한 경우
- 장점: 이해하기 쉽다.
- 단점: 지정된 Character와 Operator 간 변환에 별도 연산프로퍼티 또는 메서드를 구현하여야 한다.
2. rawValue를 활용한 경우
- 현재의 경우와 반대의 장단점을 가짐

현재의 방식으로 진행할 예정이라면 `ownValue` 보다 적합한 이름을 사용하는 것도 고려해볼만 한 것 같아요. sign, mark, symbol 등 더 적합한 이름이 있을 것 같네요~

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/OperatorEnum.swift
> +    public func calculate(lhs: Double, rhs: Double) -> Double {
public 접근 제한을 설정한 이유는 무엇인가요~?

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/OperatorEnum.swift
> +    }
PR 본문을 통해 말씀하신 것처럼 적절한 에러 핸들링이 필요하겠네요.

2022-05-21 18:55 UTC, ryan-son commented on Calculator/Calculator/SubModel/SplitExtension.swift
> +}
UML 상 존재하지만 구현에 활용하지 않는다면 제거하셔도 됩니다~

2022-05-21 18:55 UTC, ryan-son commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_EmptyWhenQueueDoesNotHaveElement() {
언더바 이후 이름을 소문자로 시작하면 camel case를 준수할 수 있겠네요~

2022-05-24 06:29 UTC, KayAhnDS commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		6A888EBE28376810007E419C /* Formula.swift in Sources */ = {isa = PBXBuildFile; fileRef = 6A888EBD28376810007E419C /* Formula.swift */; };
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/5aa59506f72048c51d46b34c6151d8a2f31ae184

수정했습니다!
그리고  "저는 Extension을 파일 단위로 나눌 때 통상적인 경우 타입이름+Extension으로, 특정 프로토콜을 준수할 경우 타입이름+프로토콜이름으로 짓고 있습니다. 케이도 이번 기회에 본인만의 기준을 만들어보시면 좋겠네요~"
이 부분도 고려해서 네이밍 하겠습니다!

2022-05-24 06:30 UTC, KayAhnDS commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +			);
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/3579638a4a2ac14c09d8f3ed68e82bc3a0f95fb3

https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/f37f9f9ba13b63af35da1ccfe4eaa79773bbc6a9

변경했습니다!

2022-05-24 06:31 UTC, KayAhnDS commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T> {
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/08384dea30ec0b19e4a351c4409cb7b185f939de

프로토콜을 채택하도록 했습니다.

2022-05-24 06:31 UTC, KayAhnDS commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<String>
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/cffb3eb1e748f78ee0fa6ee12a62a4ddbaa5f5df

추가해주었습니다!

2022-05-24 06:58 UTC, KayAhnDS commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<String>
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/d6d3f81ebb253ebd4833cd77594b40ea6bb20c97

타입을 바꾸어주었습니다~!

2022-05-24 07:00 UTC, KayAhnDS commented on Calculator/Calculator/Model/Formula.swift
> +        while operators.count != 0 {
이부분은 애초에 계산기를 누를때 에러를 반환하는것으로 그림을 그렸습니다.
다음 스텝에서 큐에 가장 마지막에 있는것이 연산자일때 각각의 경우를 처리해주겠습니다!

2022-05-24 07:04 UTC, KayAhnDS commented on Calculator/Calculator/Model/Formula.swift
> +            }
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/d6d3f81ebb253ebd4833cd77594b40ea6bb20c97

말씀해주신대로 조금 더 생각해보니 간결해졌습니다!

2022-05-24 07:05 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        var operands = input.split { ["+", "-", "*", "/"].contains(String($0)) }
String으로 받는것보다 처음부터 받을때 잘 받는것도 하나의 방법이구나 생각하고 수정했습니다.

2022-05-24 07:06 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        var operands = input.split { ["+", "-", "*", "/"].contains(String($0)) }
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/8f9900f754685efdb25e17d2999aeb903cc6bdac

ownValue를 없애주고 14번 라인의 코드를 수정했습니다.

2022-05-24 07:08 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        while !(operators.isEmpty && operands.isEmpty) {
while은 사용하지않고 생성할때 인자로 넘겨주어 생성하도록 했습니다!

2022-05-24 07:09 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/ExpressionParser.swift
> +        return input.filter {$0 == "+" || $0 == "-" || $0 == "/" || $0 == "*" }.map { String($0) }
앞에서도 말씀하신것처럼 한곳에서 바꾼다면 모든 파일의 코드를 수정해야하는 일이 생길수도 있을것 같습니다. 
앞으로는 열거형을 잘 이용해보도록 하겠습니다!

2022-05-24 07:10 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/OperatorEnum.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/8f9900f754685efdb25e17d2999aeb903cc6bdac

연산프로퍼티도, 쓰는곳도 많지 않아서 rawValue로 구현했습니다.

2022-05-24 07:11 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/OperatorEnum.swift
> +    public func calculate(lhs: Double, rhs: Double) -> Double {
UML에 '+' 사인이 있어서 일부러 public으로 지정해 주었습니다.

2022-05-24 07:22 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/OperatorEnum.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/254/commits/334630a0f9e968ec7649dd8293c6f5a6d6376883

핸들링 처리 해주었습니다!

2022-05-24 07:23 UTC, KayAhnDS commented on Calculator/Calculator/SubModel/SplitExtension.swift
> +}
이부분은 다음 스텝에서도 사용하지 않는다면 지우겠습니다!

2022-05-24 07:23 UTC, KayAhnDS commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_EmptyWhenQueueDoesNotHaveElement() {
카멜케이스를 준수해서 수정했습니다!

2022-05-24 07:25 UTC, KayAhnDS commented
@ryan-son 
안녕하세요 Ryan!
리뷰해주신 부분 읽어보니 처음에 너무 러프하게 구현해서 그런지 고칠부분도 많고, 유연성있는 코드를 구현 하려다보니 시간을 많이 소요했습니다.
달아주신 코멘트에 대한 부분은 각각의 코멘트에 작성했으며, 몇몇 코멘트가 달리지 않은 부분은 중복되는 부분입니다.
감사합니다!

2022-05-24 15:24 UTC, ryan-son commented on Calculator/Resource/SubModel/ExpressionParser.swift
> +        return input.filter { Operator.allCases.map({ String($0.rawValue)}).contains(String($0))}.map { String($0) }
이 부분도 이렇게 작성해볼 수 있겠네요~
```suggestion
        return input.filter(\.isOperator).map(String.init)
```

2022-05-24 15:25 UTC, ryan-son commented on Calculator/Resource/SubModel/Operator.swift
> +            throw valueError.divideByZeroError
이 에러 타입은 소문자로 시작하는군요~ 😉

2022-05-24 15:26 UTC, ryan-son commented on Calculator/Resource/SubModel/SplitExtension.swift
> +        return self.split(separator: target).map{ String($0) }
매핑방식을 `.map { String($0) }` 혹은 `.map(String.init)` 중에 하나로 통일하는 편이 가독성 면에서 더 좋을 수 있겠어요.

2022-05-24 15:30 UTC, ryan-son commented on Calculator/Source/Model/Formula.swift
> +            guard let currentOperand = operands.dequeue() else { throw valueError.operandEmptyError }
줄바꿈은 취향의 영역이지만 저는 단순히 반환값이 없는 return문이 아니라면 [Swift Statements](https://docs.swift.org/swift-book/ReferenceManual/Statements.html#ID434)에서 권장하는 형식대로 개행을 해주는 편이긴 해요.

![image](https://user-images.githubusercontent.com/69730931/170073992-a936c3b4-0477-4cb3-9dfe-c431bf89ddf5.png)

2022-05-24 15:32 UTC, ryan-son commented on Calculator/Source/Model/Formula.swift
> +            calculationResult = try currentOperator.calculate(lhs: calculationResult, rhs: currentOperand)
에러를 계속해서 상위 메서드로 던지기보다 범위를 한정할 수 있을 때 핸들링을 하자는 의견이 나올 때도 있어요. 케이는 어떤 방식을 더 선호하시나요?

2022-05-24 15:38 UTC, ryan-son commented on Calculator/Source/Model/CalculatorItemQueue.swift
>      private var queue: [T?] = []
`Double`과 `Operator` 타입이 `CalculateItem` 프로토콜을 준수하여야 하는 이유는 무엇일까요? `CalculatorItemQueue`의 제네릭 요소로 사용될 수 있기 때문이라고 한다면, `CalculateItem`을 준수하는 타입은 `CalculatorItemQueue` 자신이라기보다 `Queue`의 요소인 `T`가 적합할거에요. 이 개념이 잘 이해 되지 않으신다면 다시 회의실에서 만나서 이야기 나눠보도록 해요~

2022-05-24 15:39 UTC, ryan-son commented on Calculator/Resource/SubModel/DoubleExtension.swift
> +}
요구사항이 없는 빈 프로토콜인 `CalculateItem`을 채택한다는 것이 어떤 의미인지, 무엇을 위한 것인지 생각해본다면 앞서 언급한 내용이 이해가 되실거에요.

2022-05-24 16:00 UTC, ryan-son reviewed
케이 코멘트에 답변 추가했습니다~

2022-05-24 16:01 UTC, merged