계산기[Step2] Groot
yagom-academy/ios-calculator-app pull request #255
Opened 2022-05-20 08:34 UTC by Groot-94

@leejun6694  안녕하세요 쿠마! 
Step2 첫 PR 보냅니다! 늦은 밤중에 리뷰도 해주시고 감사합니다! 많은 도움이 되었습니다!
이번 리뷰도 잘 부탁드립니다 👍 

# 📌 작업 내용
## CalculatorItemQueue update
- dequeue 호출 시 return 값이 nil이면 에러를 반환하도록 수정 했습니다.

## Formula
- 큐를 사용해서 연산자와 피연산자를 저장하도록 했습니다.
- 입력받은 연산자와 피연산자를 이용해 계산의 결과값을 출력하는 메서드를 만들었습니다
    - 예외처리
        - ÷ 0 는 에러를 반환하도록 했습니다.

## CalculateError
- 에러처리를 위한 Enum 타입을 추가했습니다.

## ExpressionParser
### parse 
- 계산기 사용자의 연산 입력을 받아 formula의 큐에 값을 넣어주는 기능을 구현했습니다.

### componentsByOperators
- 입력에서 연산자와 피연산자를 공백으로 분리한다는 가정하에 연산자와 피연산자를 나눠서 배열에 담아주는 기능을 구현했습니다.

## Operator
- 각각의 연산자를 enum 타입으로 구현했습니다.

### calculate
- 호출하는 연산자를 확인해 계산값을 반환하도록 구현했습니다.

## String
### split
- 기존 String 함수는 [Substring] 을 반환하기 때문에 [String]으로 반환할 수 있도록 함수를 추가했습니다.
---
# 📌 고민한 점
## result(), parse() 함수에서 optional을 처리하는 방식을 고민했습니다.
- result() 함수 큐에서 값을 꺼내와서 계산해야 했기 때문에 optional 처리를 해야 하는 부분이 많아 코드의 가독성이 많이 떨어졌습니다.
- parse() 함수에서 String 값을 각각 큐의 타입에 맞게 변환해줘야 하는 작업이 많아서 코드의 가독성이 많이 떨어졌습니다.

### 해결방법 
- result() 함수에서 optional을 처리하지 않고 dequeue 함수에서 리턴 값이 nil 이면 `nil Error를 반환`하도록 수정했습니다. 
- parse() 함수에서는 optional을 `compactMap`으로 처리하는 방식을 사용했습니다.
-  혹시 더 좋은 방법이 있을지 쿠마의 의견이 궁금합니다!

## Enum 타입의 메서드들을 사용하는 방식에 대해 고민했습니다.
- 인스턴스를 생성하지 않는 Enum 타입은 case를 통해 메서드에 접근하는 방법을 사용했는데, 이번에 주어진 UML엔 case가 없는 Enum 타입을 사용하도록 요구사항에 있었습니다
- 어떻게 사용해야 할지 몰라서 몇 시간 삽질을 한 후에나 static으로 설정해주고 타입 메서드 방식으로 사용해야 함을 깨달았습니다...
- 이렇게 Enum으로 타입메서드를 사용하면 Struct와 다른 게 인스턴스 생성을 막을 수 있다는 차이점이 있다고 알고 있습니다. `단순하게 그 이유로 이런 Enum의 타입메서드를 사용하는지 아니면 다른 더 중요한 이유가 있는지 궁금합니다!`

## componentsByOperators 메서드를 어떻게 사용할까를 고민했습니다.
- 가능하면 주어진 UML을 그대로 지켜서 코딩을 하고 싶다고 생각을 했기 때문에 저 메서드를 어떻게 사용할지 고민을 많이 했습니다. 하지만 지금 제가 사용한 방식은 굳이 사용해야 하나? 라는 생각을 들게 합니다. 여러 번 리팩토링을 하면서 최선의 결과를 찾았다고 생각했지만, 아직 부족하다고 느껴집니다... 쿠마라면 어떤 방식으로 사용했을지 궁금합니다..!
---
# UML
## Class Digram
![Calculator](https://user-images.githubusercontent.com/96932116/169488000-4db48666-6b2d-43ad-b53b-ea47ce763119.png)

2022-05-22 17:34 UTC, leejun6694 requested changes
얘기 나눴던 것보다 훨씬 더 고민이 많이 담겨있는 코드로 구현해주셨습니다 : )
좋은 아이디어에 몇가지 추가로 생각해봤으면 하는 부분을 코멘트 남겼습니다~! 참고 부탁드려요!!

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/Formula.swift
> +        guard result != Double.infinity else {
계산이 끝난 후에 result 를 확인하는 구조로 보입니다.
0 으로 나누는 계산 자체는 문제가 없는 것으로 구현되는데, error 와 try-catch 를 잘 사용하고 있는 것을 여기에도 반영해보면 어떨까요?

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/Formula.swift
> +        guard result != Double.infinity else {
계산이 끝난 후에 result 를 확인하는 구조로 보입니다.
0 으로 나누는 계산 자체는 문제가 없는 것으로 구현되는데, error 와 try-catch 를 잘 사용하고 있는 것을 여기에도 반영해보면 어떨까요?

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/OperatorsTests/OperatorsTests.swift
> +    func test_calculate_case가_didvide일때_나누기를하는지() {
0 을 나누면 어떻게 되나요!?

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/OperatorsTests/OperatorsTests.swift
> +    func test_calculate_case가_didvide일때_나누기를하는지() {
0 을 나누면 어떻게 되나요!?

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/Enum/ExpressionParser.swift
> +        componentsByOperators(from: input).filter { Double($0) == nil }.compactMap { Operator.init(rawValue: Character($0)) }.forEach {
`filter { Double($0) == nil }` 는 문자를 뽑아오는 좋은 아이디어네요~!
음,, 그런데 그다음 계산인 `Operator.init(rawValue: )` 를 통해서 문자를 바로 뽑아올 수 있을 것 같습니다.
중복되는 계산을 줄일 수 있을 것 같은데, 참고 부탁드려요 : )

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/Enum/ExpressionParser.swift
> +        componentsByOperators(from: input).filter { Double($0) == nil }.compactMap { Operator.init(rawValue: Character($0)) }.forEach {
`filter { Double($0) == nil }` 는 문자를 뽑아오는 좋은 아이디어네요~!
음,, 그런데 그다음 계산인 `Operator.init(rawValue: )` 를 통해서 문자를 바로 뽑아올 수 있을 것 같습니다.
중복되는 계산을 줄일 수 있을 것 같은데, 참고 부탁드려요 : )

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/CalculatorItemQueue.swift
> +        guard let number = linkedList.removeFirst() else{
띄어쓰기...!

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/CalculatorItemQueue.swift
> +        guard let number = linkedList.removeFirst() else{
띄어쓰기...!

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/Enum/CalculateError.swift
> +enum CalculateError: Error {
에러를 정의해주셨네요 bb

2022-05-22 17:34 UTC, leejun6694 commented on Calculator/Model/Enum/CalculateError.swift
> +enum CalculateError: Error {
에러를 정의해주셨네요 bb

2022-05-22 17:47 UTC, leejun6694 commented
> result(), parse() 함수에서 optional을 처리하는 방식을 고민했습니다.

좋은 아이디어입니다! 다만, 코멘트 남긴 부분이 있으니 확인 부탁드려요~!!

> Enum 타입의 메서드들을 사용하는 방식에 대해 고민했습니다.

음.. 저도 인스턴스 생성이 불필요한 경우, enum 을 사용하고 있습니다...!

> componentsByOperators 메서드를 어떻게 사용할까를 고민했습니다.

input 방법 구현에 따라 달라질 수 있는 method 인데, 현재의 상황에서는 잘 구현해주신 것 같네요~!
추후 step 에서 얘기를 더 나눠보면 좋을 것 같습니다.

2022-05-23 06:48 UTC, Groot-94 commented on Calculator/Model/Extension/Double.swift
> +extension Double {}
음... 이번에도 UML에 빈 extension이 있어서 채택하는 방향으로 했습니다.. 제 생각에는 step 3에서 계산기 실제 구현 중 연산결과를 나타내는 부분을 위한 프로토콜이 아닐까 생각했습니다.

```
사용자에게 표시하는 숫자는 뒤에 0000 등 불필요한 숫자가 나타나지 않도록 합니다

예) 0.123000000 → 0.123 / 1.22340000 → 1.2234
숫자는 최대 20자리까지만 표현합니다
잘리는 숫자는 반올림합니다
숫자는 3자리마다 쉼표(,)를 표기해줍니다
```
이 부분을 처리해주는 함수라고 생각합니다..

2022-05-23 07:33 UTC, Groot-94 commented on Calculator/Model/Formula.swift
> +        guard result != Double.infinity else {
마지막 결과값에서 검증하는 방식이 아니라 0 으로 나눗셈을 시도하면 계산을 시작하기 전에 error를 던지도록 수정했습니다.

[ce4d230](https://github.com/yagom-academy/ios-calculator-app/pull/255/commits/ce4d230aa4ab88850d6aef22222e33fe9b29ec80)

2022-05-23 07:40 UTC, Groot-94 commented on Calculator/Model/Enum/ExpressionParser.swift
> +        componentsByOperators(from: input).filter { Double($0) == nil }.compactMap { Operator.init(rawValue: Character($0)) }.forEach {
단순히 `filter { Double($0) == nil } `를 지우고 테스트를 진행하면 `Character($0)` 부분에서 런타임 에러가 발생했습니다.
`"123" 과 같이 1개 초과의 문자를 포함하는 String에 대해 Character로 변환을 시도 하면서 문제가 생겼다고 생각합니다.`
그래서 Operator enum 타입에 새로운 init을 추가하는 방법으로 수정을 해봤습니다. 제가 수정한 방법이 쿠마의 의도와 맞는지 잘 모르겠네요..

[ea7526d](https://github.com/yagom-academy/ios-calculator-app/pull/255/commits/ea7526d4cd05592306781fc4662ae21416a0d470)

2022-05-23 07:41 UTC, Groot-94 commented on Calculator/Model/CalculatorItemQueue.swift
> +        guard let number = linkedList.removeFirst() else{
수정했습니다..🥹

[440b35a](https://github.com/yagom-academy/ios-calculator-app/pull/255/commits/440b35a31a603d2395ebba75c95160b39e10e665)

2022-05-23 12:57 UTC, leejun6694 approved these changes
LGTM

2022-05-23 12:57 UTC, leejun6694 commented on Calculator/Model/Enum/ExpressionParser.swift
> +        componentsByOperators(from: input).filter { Double($0) == nil }.compactMap { Operator.init(rawValue: Character($0)) }.forEach {
네ㅎㅎ 맞습니다~~! 👍

2022-05-23 12:58 UTC, leejun6694 commented on Calculator/Model/Formula.swift
> +        guard result != Double.infinity else {
divide method 에서 error 처리하는 방법도 있을 것 같아요.
지금 구현도 너무 좋습니다~~!

2022-05-23 12:58 UTC, merged