계산기 [STEP2] Kiwi
yagom-academy/ios-calculator-app pull request #258
Opened 2022-05-20 13:56 UTC by kiwi1023

@jryoun1 안녕하십니까 제이크! STEP 2에서 고민을 많이 하다 보니 많이 늦어진 점 양해 부탁드립니다..ㅜㅜ
이번 과제도 역시 많이 어렵네요 ㅎㅎ 이번에도 리뷰 잘 부탁드리겠습니다!

## UML
![Untitled Diagram drawio](https://user-images.githubusercontent.com/101521502/169535712-3fcaabca-cc39-444e-a31c-04f72d3f7670.png)

## 궁금한 점🙋

1. expressionParser 열거형의 역할이 무엇일가에 대한 고민을 아주 많이 했습니다.  고민끝에 내린 결론은 String으로 받은 연산식을 Double(숫자)과 Operator(연산기호)로 나누어 각각의 큐에 분리 해주는 역할을 한다고 결론을 내렸습니다. 이 과정에서 componentsByOperators함수를 구현을 했어야 했는데, parse함수의 역할과 많이 중복되다는 생각이 들었습니다. 그래서 저는 componensByOperators함수 내부에서 공백으로 split만 해주는 간단한 역할만 부여 한다음 parse함수 내부에서 고차함수를 이용해 분리작업을 진행하였습니다. 사실 componentsByOperators함수의 필요성에대해 여전히 의문을 가지고 있습니다. 이에 대한 제이크의 생각이 궁금합니다!

2.  String 확장에서 split을 구현해주고 있는데 이 함수의 구현의도가 제 생각에는 split의 반환값이 원래는 subString이지만 String으로 반환하기 위해 다시 구현해주고 있다고 생각합니다.  하지만 이러한 기능은 이미 componants에서 하고 있는데 왜 다시 구현하는지 의문이 들고 있습니다...
 
3.
```swift
func test_하나의_식을_문자열값으로_받은_경우_연산이_올바르게_되어야한다() {
        //given
        let expression = "2 + 6 × 5 ÷ -2"
        //when
        var result = ExpressionParser.parse(from: expression)
        //then
        XCTAssertEqual(try result.result(), -20)
    }

 let operators = componentsByOperators(from: input).filter{ Double($0) == nil }.compactMap{ Operator(rawValue: Character($0)) }
```
test 과정에서 expression에 음수를 넣었을때  components과정에서 operands에 문제없이 Double타입 배열 형태로 할당 되었는데 , 그러나 연산자 기호를 componants 해주는 과정에서 아래 사진처럼 계속 오류를 일으켰습니다. 그래서 filter함수를 사용하여 filter{ Double($0) == nil }라는 조건을 하나 더해 주니 더이상 오류가 나지 않았습니다. 여기서 궁금증은 아무리 생각해도 filter함수를 사용하지 않아도 구현이 가능해야 될거같은데 왜 음수가 연산자 componants 과정에서 에러를 일으키는지 궁금 합니다.

![스크린샷 2022-05-20 오후 10 25 14](https://user-images.githubusercontent.com/101521502/169537563-6c3e372b-bac8-4eb5-972b-ca49cc527d02.png)

2022-05-23 14:03 UTC, jryoun1 requested changes
@kiwi1023 고생하셨습니다 🙏🏻

테스트 코드도 잘 작성해주셨고, 고민을 많이 하신 것이 코드에도 녹아 있는 것 같아서 보기 좋았습니다!
다만 몇 가지 개선되면 좋을 것 같은 부분들이 있어서 코멘트에 남겨 두었습니다!

### 궁금한 점
질문하신 부분들에 대해서는 코멘트에 답변을 남겼습니다! 확인부탁드려요~

2022-05-24 04:43 UTC, kiwi1023 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    static func componentsByOperators(from input: String ) -> [String] {
접근제한에 따라 +,-를 구별해 주었던 거였는데, 실수가 있었습니다.. 또한 밑줄은 타입메서드를 표현한 것이었습니다! uml은 변경하겠습니다

2022-05-24 04:51 UTC, kiwi1023 commented on Calculator/Calculator/Model/Extension.swift
> +//  Extension.swift
변경해주었습니다!

2022-05-24 04:55 UTC, kiwi1023 commented on Calculator/Calculator/Model/Formula.swift
> +        guard var result = operands.dequeue() else { throw OperatorError.emptyList }
보통 guard문을 쓸때 한줄로 표현을 하는 편입니다(gaurd문의 장점 중 하나가 가독성이라고 생각하기 때문에) 그러나 가드문을 쓰더라도 너무 길때 개행을 해주는 편입니다. 😃

2022-05-24 04:56 UTC, kiwi1023 commented on Calculator/Calculator/Model/Extension.swift
> +        split(separator: target).map{String($0)}
수정했습니다~

2022-05-24 05:00 UTC, kiwi1023 commented on Calculator/Calculator/Model/Operator.swift
> +        guard rhs == 0 else { return lhs / rhs }
수정하였습니다~!

2022-05-24 05:12 UTC, kiwi1023 commented on Calculator/Calculator/Model/Extension.swift
> +extension Double: CalculateItem {
정확히는 잘 모르겠으나.. 추후 1000의 자리 구분 (,) 등에 쓰이지 않을까 생각하고 있습니다... ㅎ

2022-05-24 05:14 UTC, kiwi1023 commented on Calculator/Calculator/Model/Operator.swift
> +enum OperatorError: Error {
UML은 변경하겠습니다!

2022-05-24 05:23 UTC, kiwi1023 commented on Calculator/Operator/OperatorTest.swift
> +    func test_두수를_divide로_연산했을때_나누기가_되어야한다() {
추가해주었습니다~!

2022-05-24 05:26 UTC, kiwi1023 commented on Calculator/Calculator/Model/Formula.swift
> +            if let number = operands.dequeue(),
수정하였습니다!

2022-05-24 05:41 UTC, kiwi1023 commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    func test_하나의_식을_문자열값으로_받은_경우_연산이_올바르게_되어야한다() {
operands의 enqueue메서드 data값에 Double을 기본값으로 설정해 주었기 때문에 빈문자열 테스트는 진행하지 못하였지만, 다른 테스트는 더 추가 해주었습니다! 좋은 조언 감사합니다!

2022-05-24 06:10 UTC, kiwi1023 commented on Calculator/FormulaTest/FormulaTest.swift
> +    func test_숫자를_집어넣었을때_연산이_정상적으로_작동하는지() {
다른 테스트는 더 추가 해주었습니다! 좋은 조언 감사합니다!

2022-05-24 13:28 UTC, jryoun1 commented on Calculator/Calculator/Model/Operator.swift
> +enum OperatorError: Error {
앗 말씀드린 이유는 아래와 같은 문구가 있었던 것 같아서 여쭤봤습니다.
> 아래 제시한 UML대로 연산과 관련한 타입을 구현합니다.
UML에 표기한 사항은 모두 구현해야합니다.
추가하고 싶은 사항이 있다면 리뷰어와 협의 후 진행하세요.
새로운 타입 추가 외에 UML의 기존 내용 수정은 불가합니다.

이미 에러타입을 만들어주셨으니 수정해주셔도 될 것 같아요

2022-05-24 13:40 UTC, jryoun1 reviewed
아직 전부 수정이 된 것 같지 않아서 일부분만 코멘트 드렸습니다! 🙏🏻

2022-05-24 13:40 UTC, jryoun1 commented on Calculator/Calculator/Extension/Double Extension.swift
> +//  Double Extension.swift
저는 주로 extension의 경우에는 Double+Extension 이런식으로 작성하는 것 같아요. 
저렇게 네이밍해주는 근거는 다른 라이브러리들을 보면 대부분 저런식으로 해주고 있고, 그 이유는 Objective-C 네이밍 가이드였고 Swift 또한 Objective-C에서 파생되다 보니 많은 부분을 따라하고 있다고 알고 있습니다. 
네이밍은 정말 자유지만 다른 동료 개발자들과 협업 시 딱 정해지지 않았지만 어느정도 다들 기대하는 네이밍이면 어떨까요?
참고 [레퍼런스](https://stackoverflow.com/questions/26319660/whats-the-best-practice-for-naming-swift-files-that-add-extensions-to-existing) 공유드립니다!

2022-05-24 13:40 UTC, jryoun1 commented on Calculator/Operator/OperatorTest.swift
> +    func test_0으로_divide_했을때_Error가_호출되어야한다() {
0으로 나눴을 때가 추가되었네요 👏

2022-05-26 05:05 UTC, kiwi1023 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = componentsByOperators(from: input).filter{ Double($0) == nil }.compactMap{ Operator(rawValue: Character($0)) }
수정하였습니다!

2022-05-26 05:23 UTC, kiwi1023 commented on Calculator/Operator/OperatorTest.swift
> +    override func tearDownWithError() throws {
이부분의 공부는 아직 부족하여 추후 더욱 공부를 해보겠습니다!

2022-05-26 05:24 UTC, kiwi1023 commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    override func tearDownWithError() throws {
매 테스트 마다 호출과 초기화를 담다하는 역할을 하는 거라고 생각하고 있습니다!

2022-05-26 13:05 UTC, jryoun1 approved these changes
@kiwi1023 고생하셨습니다~ 💯
무조건 기획대로 따라서 구현하는 것이 아니라 왜 필요한지에 대해서도 충분히 고민하시는 것이 인상 깊었습니다! 👏
step2는 여기서 merge하겠습니다! 다만 [CaseIterable 프로토콜](https://developer.apple.com/documentation/swift/caseiterable) Operator 타입에서 왜 채택했으며, enum의 case들을 배열처럼 활용하는 방법도 나중에 확인해 보시면 좋겠습니다🙏🏻
그럼 step3도 화이팅입니다! 💪🏻

2022-05-26 13:06 UTC, merged