계산기 [STEP2] 바드
yagom-academy/ios-calculator-app pull request #259
Opened 2022-05-20 20:11 UTC by bar-d

@GREENOVER 안녕하세요 그린! STEP2 PR 보냅니다..!  

아직 UML만 보고 로직을 파악하고 코드를 구현하는게 많이 어렵네요🥲  
STEP1의 로직을 변경하고 다시 구현하느라 늦었습니다.
중간에 리팩토링을 정신없이 하다보니 초반 커밋메시지가 많이 지저분한 점 죄송합니다.
README.md 파일은 피드백을 한번 받고 추가해서 올리도록 하겠습니다.
이번에도 잘 부탁드리겠습니다🙇‍♂️

## `UML`
![Screen Shot 2022-05-21 at 3 38 59 AM](https://user-images.githubusercontent.com/92622931/169591921-3fdbfa72-1031-4410-986e-3c6f6d192090.png)  

## `고차 함수`
- `String`을 split하게 되면 반환 값이 subString이 되므로 해당 값을 다시 받아와서 새로운 컨테이너에 생성하기 위해 고차함수인 `map()`과 `filter()`를 사용하였습니다.

## `클로저`
- 클로저에 익숙하지 않아서 아직 사용하는데 어려움을 겪고 있는 것 같습니다.
- 축약형을 쓰지 않고 기본형을 사용할려고 하였는데 축약형에 익숙해져서 축약형을 사용하게 되었습니다.

## `TEST 코드`
- 테스트 코드를 나름 열심히 짯다고 생각했는데 아직도 좋은 테스트 코드들을 짜고있는지 모르겠습니다.

---

## `고민한점🤔`
### `initializer`
- 처음 아래와 같은 오류가 나왔을 때 왜 오류가 나는지 이해가 안됬는데 생각해보니 class 내 프로퍼티가 저장이 되어있지 않아서 이니셜라이저를 해줘야 되었는데, 안해줘서 오류가 났었습니다.
![Screen Shot 2022-05-21 at 3 49 51 AM](https://user-images.githubusercontent.com/92622931/169593682-51cd7d27-c2e0-462d-b1db-adc8ed0f2233.png)  
- 아래와 같이 프로퍼티에 기본값을 넣어주어 해결을 하였습니다.  
- ![Screen Shot 2022-05-21 at 3 49 58 AM](https://user-images.githubusercontent.com/92622931/169594537-4ebf6353-f427-467c-bf29-6c0f26df32be.png)

### `Generic`
- 제네릭타입으로 반환 값을 주면 아래와 같이 에러가 나기에  강제로 다운캐스팅을 했었습니다.
![mutating func deQueue() throws](https://user-images.githubusercontent.com/92622931/169594839-2e12f8aa-29e4-4660-9e30-07401dcfae54.png)
- 하지만 그린의 조언을 듣고 만들어놓은 에러를 이용해서 처리를 하게 되었습니다.  
 강제 언래핑은 앱크래쉬의 주 원인이 될 수 있기에 지양하도록 노력하겠습니다.
![mutating func deQueue() throws - T {](https://user-images.githubusercontent.com/92622931/169595391-1cefa5a4-e49f-4f6d-afde-40d12336dc0d.png)

### `componentsByOperators `
- 처음 componentsByOperators 함수를 구현할 때 `input`값을 받아 숫자가 포함이 안되어있는지 확인(`filter()`)하고 확인한 숫자들을 다시 `String`값으로 새로운 컨테이너를 생성해 주었습니다.  
![static func componentsByOperators(from input String) -  String](https://user-images.githubusercontent.com/92622931/169598542-7b4144d2-7eb4-46b8-a47a-2d07e36b0e25.png)  
- 로직에 문제가 없을 줄 알았지만 해당 함수에서 음수가 들어가게 된다면 함수는 음수를 연산자와 양수로 분리하게 될 것이란 걸 깨닫고 다시 한번 리팩토링을 해주게 되었습니다.

- 결국 다시 `componentsByOperators`함수를 리팩토링을 해주게 되었고, 입력받을 때 공백을 기준으로 나누어준 다음 `parse` 함수 내부에서 두개의 프로퍼티를 만들어 연산자와 피연산자를 분리하도록 하였습니다.
![static func parse(from input String) throws - Formula](https://user-images.githubusercontent.com/92622931/169598995-ce266e46-0876-4079-b28d-01e289a21237.png)  
- TDD를 꼼꼼하게 하였다면 이러한 문제가 발생하지 않았을 텐데, 다음에는 좀 더 꼼꼼하게 테스트 해보도록 노력해보겠습니다.

### `연산자 처리`
- 연산자 처리를 위해 여러가지 방법들을 시도해 보았습니다.
![Screen Shot 2022-05-21 at 4 52 29 AM](https://user-images.githubusercontent.com/92622931/169602803-0df49dc5-48d6-4830-81cf-f67d290e0e8f.png)
![Screen Shot 2022-05-21 at 4 55 45 AM](https://user-images.githubusercontent.com/92622931/169602832-5ade82a6-e82e-41d7-a55b-575017e74da4.png)
- 여러 방법을 시도한 결과 제일 아래에 있는 방법으로 채택하였고, 채택한 이유 중 가장 큰 이유는 연산자는 `Character`는 하나의 문자로 이루어져 있기 때문에 하나로 카운트 되는지가 제일 중요하다고 생각하였습니다.
---

## `궁금한점🙋`
### `에러 처리`
- 현재 아는 방법은 에러처리를 `throw`나 `do catch` 구문으로 처리하는 방법만 알고 있는데  `do catch`를 사용하면 코드가 많이 두터워진다는 느낌을 받았습니다.    
  혹시 `do catch`말고 혹시 다른 방법도 존재하긴하나요?

### `접근제한자`
계산기 프로젝트 STEP2 UML의 접근 제한자 기호가 + - 로 나누어져 있는데,
구글에서 [swift access control symbols](https://stackoverflow.com/questions/51120706/swift-access-control-when-to-use-which-preceding-symbols-for-a-class-diagram)라고 검색해보니
자바는 이렇게 쓰이는데
```
+   Public
-   Private
#   Protected
~    Package
*   Random
```
스위프트는 이렇게 쓰인다고 하더라고요
```
++    open
+     public
~     internal
-~    fileprivate
-     private
```
공식적으로 쓰이는 기호가 있는건가요?
야곰의 말로는 접근제한자도 컨벤션느낌으로 다를 수도 있다고 들었던 것 같습니다.  
현재 UML에서는 `+` 는 `public` `-` 는 `private`일 것 같습니다.  
그린의 의견은 어떠한가요?

2022-05-20 20:17 UTC, bar-d commented
현재 PR을 보내고 나니 이러한 충돌이 일어나고 있습니다  
혼자 하기에는 두려워서 해당 문제는 내일 다른 분들에게 도움을 요청해서 처리해보겠습니다.
![Screen Shot 2022-05-21 at 5 15 45 AM](https://user-images.githubusercontent.com/92622931/169604288-457f3fca-753d-44bd-80d4-9558d264f17c.png)

2022-05-21 12:34 UTC, GREENOVER commented
@bar-d 
코드 리뷰에 앞서 빌드가 안되는것 같은데 수정 부탁드립니다..!🙏🏻

2022-05-21 15:21 UTC, bar-d commented
현재 그린의 커멘트를 보고 확인을 해보았는데, 로컬 레포지토리에서 돌려보았을 때는 문제가 없었습니다.
그래서 혹시 리모트 레포지토리와 로컬 레포지토리에 다른 점이 있지 않을까 해서,
미리 복사본을 만들어 놓고 `git pull` 을 통해 받아왔는데, 타겟설정도 그렇고 info.plist에 문제가 있어서 다시 재설정을 해주었습니다.
ㅎㅎ... 혼란을 일으켜 죄송합니다...

2022-05-22 02:36 UTC, GREENOVER requested changes
@bar-d 
스텝2 너무 고생 많으셨습니다 바드!!🥳🥳🥳
우선 전체적으로 정해진 UML을 이해하고 그걸 토대로 TDD를 진행하면서 해야했어서 처음 접할때 쉽지 않은 스텝이였을텐데
너무 잘 이해하시고 소화해주셨어요👍
전체적으로 리뷰는 놓쳤던 부분이나 다시 한번 확인해보면 좋은점들을 찾아봤습니다ㅎㅎ
한번 리뷰를 토대로 다듬어본다고 생각해주시면 감사하겠어요🙏🏻
항상 말씀드리지만 제 리뷰는 꼭 수정해달라는게 아닌 의견입니다!
제 의견에 사로잡혀서 다른 생각을 못하는것이 더 위험할것 같아서 누차 말씀드립니다🙋🏻
바드가 생각하기에 다른 의견이 있으시거나 더 적합한 방법이 있다면 그 방향으로 무조건 고입니다!!
그럼 우선 PR 코멘트에 대한 답변 부터 드려보겠습니다~
***
### 칭찬 드리고 싶은 부분
- UML을 잘 이해하고 구성한 점 💯
- 전체적으로 테스트 코드를 아주 상세히 많이 작성해보면서 검증해주신 점 💯
- 고차함수 사용을 적절히 잘 해주신 점 💯
- 이번 스텝에서 컨플릭 등 많은 처리를 통해 성장하신 점 💯
***
### 궁금하신 부분에 대한 저의 의견
1. 에러처리
- 우선 제가 알기로도 바드가 알고 있듯 에러 핸들링을 하는 방법은 throw do catch 요것들을 활용하는것 외엔 없는걸로 알아요!
만약 에러 핸들링을 하면서 고민하시는게 코드가 두터워진다고 느끼시는거라면 에러 핸들링을 결국 최종적으로 catch해서 다뤄주는 부분을 응집시켜보면 좋을것 같다고 느껴집니다!
저는 보통 에러를 catch해서 처리해주는 부분은 최상단으로 관심사를 가져갑니다.
예를들어 UI가 있는 프로젝트라고 친다면 버튼을 눌렀을때 타고타고 그 속에서 에러를 throw해주고 그럴텐데 결국 catch는 버튼을 눌렀던 그 메서드에서만 해줍니다.
그러면 조금 두터워지고 관심사가 여기저기 흩뿌려져있는거를 가독성 좋게는 할 수 있다고 생각해요🙋🏻
2. 접근제한자 UML 관련
- 우선 공식적으로 딱 Swift에서는 UML로 표기하기에 이거쓴다! 그렇게 애플에서 네이밍 가이드처럼 발표를 하거나 한적은 없는걸로 알고 있어요..!
(애플에서 UML을 자기 입맛대로 만들어 발표하지 않는 이상 없지 않을까라는 생각...)
그렇기에 UML을 표현하는건 하나의 대중적인 컨벤션을 따르게 되는거고 오피셜한건 없습니다.
바드가 기재해준 방식이 가장 많이 쓰이는 컨벤션이기에 다른사람들도 전반적으로 저런 컨벤션을 쓰는거라고 생각하구요.
저또한 저걸로 이해하고 있고 조금씩만 다르지 아예 완전히 다른 컨벤션은 아직 본적은 없습니다🤔
그렇기에 바드가 이해하신바와 같이 public이 + private이 -가 될것이고 이번 제공된 UML 구조에서도 그렇게 보입니다🙋🏻
***
### 보완되면 더 좋을 부분
- 우선 전체 리뷰를 조금 많이 남기긴 했지만..😭 UML 명세와 조금 다른 부분들 혹은 놓친 부분들이 있어 한번 UML 명세와 다시 비교해보면 좋을것 같습니다..!
- 테스트 코드가 너무너무 상세하고 디테일한데 실패 케이스도 있으면 어떨까해요..!🙋🏻
성공과 실패에 대한 케이스 모두 고려되어 작성되는게 TDD에서 지향하는 방향이라고 생각듭니다😁
- 리드미도 이번 스텝에서 작성되면 좋겠네요👍 시간이 좀 걸리겠지만.. 나중에 하려면 분명 힘드실거에요😭
***
다시 한번 스텝2 어려웠을텐데 잘 이해하고 하시느라 고생 많으셨습니다!
마찬가지로 수정 후 재리뷰 요청 혹은 머지 등의 요청을 해주시면 됩니다ㅎㅎ
화이팅입니다!!🙌

2022-05-22 05:18 UTC, bar-d commented on Calculator/Calculator.xcodeproj/xcshareddata/xcschemes/Calculator.xcscheme
> +         </TestableReference>
별도의 파일을 만들어볼 생각을 안하고 각 테스트 별로 테스트 타겟을 만들어야 하는줄 알았습니다..!

2022-05-22 05:19 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Error/OperatorError.swift
> +    public var errorDescription: String? {
리팩토링을 하던 도중 실수가 있었던것 같습니다

2022-05-22 05:20 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Error/OperatorError.swift
> +        case .devide:
`devideFail`이란 에러로 변경해주었습니다

2022-05-22 05:22 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Extension/String.swift
> +//  String.swift
좋은 자료 감사합니다

2022-05-22 05:27 UTC, bar-d commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				D7A1C3AD28375C27004767E3 /* Extension */,
파일 분리 도중 잘못 설정한 것 같습니다

2022-05-22 05:32 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Error/QueueError.swift
> +    case operands
`wrongOperators` 와 `wrongOperands`로 네이밍을 변경해주었습니다.

2022-05-22 05:39 UTC, bar-d commented on Calculator/Calculator/Model/Enum/ExpressionParser.swift
> +                        .compactMap{ Operator(rawValue: Character($0)) }
연산자는 `+`, `-`, `*`, `/`이므로 카운트가 하나밖에 될 수가 없습니다. 하지만 숫자 같은 경우는 음수나 더블 형태가 나올 수 있기에 filter로 1차로 한 번 검증을 해주었고, 컨테이너 내  값들을 `Character`로 변환을 해주었을 때, 연산자가 아닌 것들은 nil값이 나오기에 `compactMap`을 통해 nil값을 제거해주었습니다.

2022-05-22 05:43 UTC, bar-d commented on Calculator/Calculator/Model/Enum/ExpressionParser.swift
> +        return input.split(with: " ")
버튼이 눌릴 때 공백을 더해주면 된다고 생각했는데 다시 한번 생각해보겠습니다.

2022-05-22 05:46 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Operator.swift
> +enum Operator: Character, CaseIterable {
caseIterable을 채택함으로써 열거형 케이스를 배열처럼 사용할 수 있는 것으로 알고 있습니다.

2022-05-22 05:52 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Operator.swift
> +enum Operator: Character, CaseIterable {
해당 프로젝트에서 넣어준 이유를 생각하면 caseIterable을 사용할려면 피연산자와 연산자를 나누는 로직을 변경해봐야 할 것 같습니다.

2022-05-22 05:58 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Operator.swift
> +            }
실질적으로 계산을 할 때에 에러를 잡아줘야 하기에 `calculate()`함수가 사용되는 곳에서 에러를 잡아줘야 하는 것이 맞다고 생각이 드네요

2022-05-22 06:08 UTC, bar-d commented on Calculator/Calculator/Model/Enum/Operator.swift
> +enum Operator: Character, CaseIterable {
아니면 현재 상황에서는 쓰일 일이 없지만 연산자 버튼을 컬렉션 타입으로 만들어준다면 `CaseIterable`을 사용할 수 있을 것 같습니다.

2022-05-22 06:26 UTC, bar-d commented on Calculator/Calculator/Model/Formula.swift
> +        guard var lastResult = try? operands.deQueue() else { throw QueueError.operands }
현재 큐가 비어있을 때까지 반복문이 돌고 나오는 값이라 생각하여  
반복문이 끝나고 마지막으로 나오는 값이라 생각하여 lastResult라고 네이밍을 해주었습니다.

2022-05-22 06:29 UTC, bar-d commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var joinedQueue: Array<T> = []
joinedQueue라는 변수를 만들어준 이유는 한번 더 검증을 해보자는 의미에서 만들어준 변수입니다.
물론 로직상에서는 충분히 불필요한 변수로 보입니다만, 혹시라도 잘못된 값이 나올 수 있지 않을까라는 생각에 만들어줬는데,  
제 로직에 확신이 있다면 불필요한 변수가 될까요

2022-05-22 06:42 UTC, bar-d commented on Calculator/ExpressionParser/ExpressionParserTests.swift
> +    func test_문자열에서_componentsByOperators를사용하여_operaters를_character로_형변환을하여집어넣는가2() throws {
테스트 코드를 리팩토링해주는 과정에서 제거해주지 못했습니다🥲

2022-05-22 23:57 UTC, bar-d commented
안녕하세요 그린! @GREENOVER 
피드백 반영해서 다시 제출합니다..!  
꼼꼼하게 했다고 생각했는데 아직도 많이 부족하네요..  
컨벤션에 신경 많이 쓰도록 하겠습니다.
그린이 제안해주신 컨벤션은 사용해보고 저에게 맞는 컨벤션을 찾아가 보겠습니다.
강제 푸시한 것은 커밋 메세지를 잘못쓴 상태로 푸시를 하여 다시 수정하여 보냈습니다.


## 🤔궁금한점
- ### `TDD`
> 테스트 코드가 너무너무 상세하고 디테일한데 실패 케이스도 있으면 어떨까해요..!🙋🏻  
성공과 실패에 대한 케이스 모두 고려되어 작성되는게 TDD에서 지향하는 방향이라고 생각듭니다

- 라고 말씀해주신 부분에서   
![Screen Shot 2022-05-22 at 8 52 37 PM](https://user-images.githubusercontent.com/92622931/169698207-ae9d0273-99f5-489f-b71d-3fb37e63cecb.png)  
![Screen Shot 2022-05-22 at 8 55 37 PM](https://user-images.githubusercontent.com/92622931/169698211-f17dc627-bafe-4e0b-83fe-7eb2351b4997.png)  
  위 케이스 처럼 `XCTAssertFalse`를 사용해서 처리를 하라는 말씀인지  
아니면 정말 테스트가 실패하는 테스트를 말씀하시는 건지 이해를 잘 못해서 피드백을 받은 후 수정할려고 합니다.



- ### `접근제한자 UML 관련`
> 접근제한자 UML 관련
우선 공식적으로 딱 Swift에서는 UML로 표기하기에 이거쓴다! 그렇게 애플에서 네이밍 가이드처럼 발표를 하거나 한적은 없는걸로 알고 있어요..!
(애플에서 UML을 자기 입맛대로 만들어 발표하지 않는 이상 없지 않을까라는 생각...)
그렇기에 UML을 표현하는건 하나의 대중적인 컨벤션을 따르게 되는거고 오피셜한건 없습니다.
바드가 기재해준 방식이 가장 많이 쓰이는 컨벤션이기에 다른사람들도 전반적으로 저런 컨벤션을 쓰는거라고 생각하구요.
저또한 저걸로 이해하고 있고 조금씩만 다르지 아예 완전히 다른 컨벤션은 아직 본적은 없습니다🤔
그렇기에 바드가 이해하신바와 같이 public이 + private이 -가 될것이고 이번 제공된 UML 구조에서도 그렇게 보입니다🙋🏻  

- 제가 이해한 바로는 저는 +가 `internal`, -가 `private`으로 이해했는데 이게 맞을까요?

- ### `에러처리`
> catch를 어디쪽에서 해주는게 적절할까요?  
지금처럼 divide 메서드를 사용하는 calculate 메서드?  
아니면 calculate 메서드를 실제적으로 호출하는 부분?
- 현재 로직에서는 calculate메서드를 실질적으로 호출하는 부분에서 처리를 해줘야 하지만,  
다음 스텝으로 넘어가게 된다면 이벤트가 발생할 때 catch를 해줘야 할 것 같습니다.

2022-05-22 23:58 UTC, GREENOVER commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var joinedQueue: Array<T> = []
네 불필요한 변수일거라 생각듭니다..!
만약 확신이 없어 검증을 해주는 용도라면 불필요한 변수가 생기지 않도록 로직을 수정하는편이 맞을것 같다고 생각해요🙋🏻
말씀대로 로직에 확신이 있다면 제거되어도 될것 같아요.

2022-05-22 23:59 UTC, GREENOVER commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var joinedQueue: Array<T> = []
그 로직에 확신을 갖기위해 테스트 코드를 짜는것이라 생각들고 확신을 갖기 위해 여러 테스트 케이스를 거칠거라고 생각들어서요!
그걸 다 통과하면 확신을 가져도 되지 않을까요?

2022-05-23 00:23 UTC, GREENOVER approved these changes
@bar-d 
주말에 리팩토링 하느라 너무 고생많으셨습니다!
전체적으로 이전 리뷰 코멘트 사항을 잘 반영해주셨네요🙌
추가 코멘트 및 기존 코멘트에서 질의에 대한 답변을 토대로 이후 스텝으로 넘어가서 수정해도 충분히 괜찮을것 같아 머지하겠습니다!
꼭 코멘트 한번 읽어보시고 의견 혹은 반영되면 좋을것 같습니다😁
***
### 질문하신 부분에 대한 저의 의견
1. TDD 실패 케이스 관련
- 정말 단순히 뭘 써서 해라 라는 의미는 아닙니다.
1 = 1과 같이 성공하는 케이스만 있으면 반대로 당연한 말이겠지만 1 != 2와 같이 기대값과 결과값이 다를때 검증되는 케이스도 있어야 되지 않을까해요.
지금 성공하는 값이 정말 그 기대값과 결과값이 같아서 성공하는것인지 기대값에 상관없이 계속 성공하는것인지에 대한 검증은 없다고 생각해요.
물론 머리로는 "당연히 1 = 1이 성공했으니 1 != 2도 성공하겠지!"로 생각될 수 있지만 컴퓨터는 다르니까요🥲
XCTAssertNotEqual와 같은 메서드를 사용해도 될거라 생각합니다🙋🏻
그 케이스에 대한 검증 시나리오만 잘 정의한다면 다만 사용해야될 메서드는 정해져있지 않습니다.
그에 따라 적절한 케이스를 사용해야될것 같아요!
2. 접근제한자 UML 관련
- 아 일반적으로 PR 코멘트에 남겨주신 public이 +, private이 -로 사용되고,
지금 야곰의 UML에서는 internal이 +인것 같네요🥲
아고.. 제가 혼란을 드렸습니다🙏🏻
혹시 이것도 저희의 추측일테니 정말 확실히 internal인지 public인지 파악하려면 이걸 제시한 야곰 혹은 크루원들에게 물어보는게 제일 확실할거 같습니다!
3. 에러처리
- 네 저도 동의합니다! 그 방향으로 진행해보시죠👍
***
다음 스텝도 화이팅입니다🙌

2022-05-23 00:23 UTC, GREENOVER commented on Calculator/Calculator/Model/Extension/Double.swift
> +//  Double.swift
얘도 기본 Double 타입의 extension이면 파일명의 컨벤션을 맞춰볼 수 있을것 같습니다🙋🏻

2022-05-23 00:23 UTC, GREENOVER commented on Calculator/FormulaTests/FormulaTests.swift
> +        XCTAssertThrowsError(try test())
이 테스트 실패합니다🥲

2022-05-23 00:23 UTC, GREENOVER commented on Calculator/Calculator/Model/Enum/Operator.swift
> +                return try divide(lhs: lhs, rhs: rhs)
띄어쓰기가 뎁스가 한단계 더 된것 같습니다🙋🏻

2022-05-23 00:23 UTC, GREENOVER commented on Calculator/Calculator/Model/Formula.swift
> +                OperatorError.devideFail
음 에러가 여기서 catch를 선언해주는게 맞을까요~?🙋🏻

2022-05-23 00:23 UTC, merged

2022-05-23 07:24 UTC, bar-d commented on Calculator/FormulaTests/FormulaTests.swift
> +        XCTAssertThrowsError(try test())
수정했습니다🥲

2022-05-23 07:26 UTC, bar-d commented on Calculator/Calculator/Model/Formula.swift
> +                OperatorError.devideFail
throw를 넣어주고 던져주었습니다.   
현재 calculate함수를 호출하는 부분이 Formula 구조체 내이기 때문에   
현재 로직에서는 여기서 catch를 해주는게 아닌가요?

2022-05-23 07:44 UTC, GREENOVER commented on Calculator/Calculator/Model/Formula.swift
> +                OperatorError.devideFail
아마 저 30번째 라인에서 워닝 메시지가 나올텐데 어떤건지 한번 보시면 어떻게 잘못쓰였는지 확인해보실 수 있을거 같아요..!

2022-05-23 08:01 UTC, bar-d commented on Calculator/Calculator/Model/Formula.swift
> +                OperatorError.devideFail
![Screen Shot 2022-05-23 at 4 56 28 PM](https://user-images.githubusercontent.com/92622931/169771396-8f575d35-428a-4436-bab3-b7f3be41a83f.png)

![Screen Shot 2022-05-23 at 4 57 52 PM](https://user-images.githubusercontent.com/92622931/169771618-d6047667-1237-4b21-912d-896ec0f2f0e6.png)  
제가 catch를 해주고 catch를 해준 것에 대해 던져줄지 프린트를 할지 리턴값을 줄지 해당 결과를 사용하지 않아서 나온 워닝 메세지인 것 같습니다.  
30번째 줄에 throw를 넣어주었다고 말씀드린거였는데 혹시 제가 오해하시게 말씀드린걸까요...?

2022-05-23 08:21 UTC, GREENOVER commented on Calculator/Calculator/Model/Formula.swift
> +                OperatorError.devideFail
아아 제가 코멘트를 잘못읽었습니다!
죄송합니다ㅠㅠ
네네 수정하신 방향이 맞다고 보입니다..!

2022-05-23 08:28 UTC, bar-d commented on Calculator/Calculator/Model/Formula.swift
> +                OperatorError.devideFail
넵 감사합니다..!