계산기I [STEP 2] unchain123
yagom-academy/ios-calculator-app pull request #264
Opened 2022-05-23 06:17 UTC by unchain123

# 계산기I STEP2 PR
@AppleCEO 
 안녕하세요 도미닉 많이 늦었습니다. 
많이 고민해보고 늦더라도 확실히 알고 가고 싶은데 늦기만 하고 확실히 알게 됐는지는 잘 모르겠습니다. ㅜㅜ 잘부탁드릴게요

## 기능구현 및 코드설명 ✏️
- result : ExpressionPaser에서 넘겨받은 숫자와 연산기호를 확인하고 계산해서 결과를 도출하는 함수
- enum Operator : + - / × 기호를 기본값으로 같는 열거형
 * calculate : 초기화된 연산기호에 따라서 사칙연산 중 해당하는 로직을 실행 하는 함수
     * add : 덧셈 로직
     * subtract : 빼기 로직
     * divide : 나누기 로직
     * multiply : 곱하기 로직
* ExpressionPaser :
     * componentByOperator : 문자열 값을 문자열 배열로 반환해주는 함수
     * parse : 계산기를 통해 입력받은 문자열값을 숫자와 연산기호로 구분하여 Formula구조체에 초기화 해주는 함수

## [STEP 2] 고민한점 및 해결방안 🤔
1.  현재 조건 :``` swift operands.linkedList.head != nil ``` 인데 처음엔 ``` swift operands.linkedList.head.next != nil ```로 했었더니 반복이 되지 않아서 테스트에 실패했었습니다. 처음엔 당연히 head.next 값이 nil일 때 까지 반복해야 한다고 생각했는데 처음에 이미 next값은 nil이기 때문에 반복이 되지않았고 실패했다는 걸 알고 수정을 해주었습니다.

2. Formula 구조체를 만들 때 operands와 operator의 기능이 어떻게 되는지 처음엔 머릿속에 잘 그려지지 않아서 한참을 고민 했던것 같습니다. 이 두개의 기능을 파악하기 위해 UML을 계속해서 분석해 보면서 parse를 통해 이 값들을 받아와야 한다는 걸 깨닫고 구현 할 수 있었습니다. 

3. 테스트파일을 추가 할 때마다 알 수 없는 오류들이 많이 나타났는데 타켓 맴버쉽 설정에서 오는 오류들이라는 얘기를 들었습니다. 그래서 타켓 맴버쉽 설정 대신 테스트 코드에서 @testable 을 사용해서 import해주었습니다.

4. split vs components
 - 둘다 문자열에서 호출 가능하고 split은 리턴값이 Substring배열이고 components는 String배열이다.
 - components는 Foundation프레임워크를 import해야한다.
 
## 궁금한 점 🥲

1. Static enum
 - UML에서 ExpressionPaser의 메서드를 static키워드를 붙여주라고 되어 있어서 static을 붙여서 구현했지만 정확히 어떤 이유가 있는지 파악하지를 못했습니다. 제가 찾아본 바로는 이렇게 해주는 것이 타입 메서드로 만들어주고 인스턴스에 할당하지 않고 클래스 자체에서 사용되는 메소드를 뜻한다고 했습니다. 단지 인스턴스에 할당을 하지 않고 사용함으로써 얻는 이점이 무엇인지 제대로 파악하지 못했습니다. 혹시 알려주시거나 참고할만한 문서가 있는지 궁금합니다.

2.  ``` swift let operators = paser.filter {
            allOperator.contains($0)
            } 
``` 

- 클로저에 대해 아직 공부가 부족해서 그런지 이 부분이 제가 잘 이해가 되지 않았습니다. 중괄호를 통해서 클로저를 실행하는 줄 알고 있었는데 contains에서는 소괄호로 해주었습니다. 이부분은 도저히 해결이 되지않아 동기 캠퍼들의 도움을 받아서 작성했습니다. 제가 어떤 부분을 더 공부해보면 좋을지 궁금합니다.

2022-05-23 14:24 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.
@unchain123 고생하셨습니다.
어려운 프로젝트인데 해내셨군요~
몇가지 개선할 점들 남겨놨습니다.

질문에 대한 답변
- Static enum
UML에서 ExpressionPaser의 메서드를 static키워드를 붙여주라고 되어 있어서 static을 붙여서 구현했지만 정확히 어떤 이유가 있는지 파악하지를 못했습니다. 제가 찾아본 바로는 이렇게 해주는 것이 타입 메서드로 만들어주고 인스턴스에 할당하지 않고 클래스 자체에서 사용되는 메소드를 뜻한다고 했습니다. 단지 인스턴스에 할당을 하지 않고 사용함으로써 얻는 이점이 무엇인지 제대로 파악하지 못했습니다. 혹시 알려주시거나 참고할만한 문서가 있는지 궁금합니다.
- 인스턴스를 만들지 않고 사용하면 우선 메모리 공간을 덜 차지하겠죠. 인스턴스를 따로 만들지 않아도 메소드를 쓸 수 있어서 만약 여러 군데에서 사용되는 것이라면 매번 클래스를 생성해서 이 메소드를 실행해줘야 할텐데 클래스를 생성하지 않고 메소드를 바로 호출하면 편하고 빠르게 사용할 수 있는 장점이 있을 것 같습니다 ㅎㅎ

클로저에 대해 아직 공부가 부족해서 그런지 이 부분이 제가 잘 이해가 되지 않았습니다. 중괄호를 통해서 클로저를 실행하는 줄 알고 있었는데 contains에서는 소괄호로 해주었습니다. 이부분은 도저히 해결이 되지않아 동기 캠퍼들의 도움을 받아서 작성했습니다. 제가 어떤 부분을 더 공부해보면 좋을지 궁금합니다.
- 축약을 여러 번 해서 저렇게 사용 가능한 것 같습니다. 우선 기본형으로 작성해보면 좋습니다. 예를 들면 .map 을 작성하고 파란색으로 예상 구조가 있는 부분을 더블클릭하면 기본적인 형태로 map 에 들어갈 코드가 만들어집니다. 이 기능 활용해보면 좋겠네요. 잘 안되면 DM 주시면 같이 해볼 수도 있을 것 같습니다!

2022-05-23 14:24 UTC, AppleCEO commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +        XCTAssertEqual(result, input)
given, when, then 으로 나눠준 것 좋습니다! 👍

2022-05-23 14:24 UTC, AppleCEO commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
>      func test_숫자5와6을_넣었을때_5와6이들어있는지확인() {
5와 6을 어디에 넣었는지 메소드명에 들어나도 좋겠네요~

2022-05-23 14:24 UTC, AppleCEO commented on Calculator/Enum/ExpressionParser.swift
> +        let result = results.map { String($0) }
여기서 $0 을 사용하는 단축형을 사용하는 대신에 기본형으로 작성해보면 어떨까요?

2022-05-23 14:24 UTC, AppleCEO commented on Calculator/Enum/ExpressionParser.swift
> +        let operands = paser.compactMap{ Double($0) }
이런 부분들도 기본형을 활용해서 풀어서 작성해보면 어떨까요? $0 을 사용해서 어떻게 넣으면 동작은 하지만 기본적으로 어떻게 구성되어있는지 풀어서 작성하는 것에 먼저 익숙해지는 것이 좋을 것 같아요~

2022-05-23 14:24 UTC, AppleCEO commented on Calculator/Enum/ExpressionParser.swift
> +        return Formula(operands: operandsQueue, operators: operatorsQueue)
리턴에 생성자가 있으면 조금 읽기 어려운 것 같아요 ㅎㅎ
위에서 상수에 넣어주고 그 상수를 리턴해주면 어떨까요?

2022-05-23 14:24 UTC, AppleCEO commented on Calculator/Model/LinkedList.swift
> +        }
while let 을 사용해보셨군요! 💯

2022-05-23 14:24 UTC, AppleCEO commented on Calculator/Model/Formula.swift
> +            }
guard let 이 반복적으로 쓰이는데 한 줄에 작성해보면 어떨까요? ㅎㅎ

2022-05-24 04:47 UTC, unchain123 commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
>      func test_숫자5와6을_넣었을때_5와6이들어있는지확인() {
넵 어디에 들어가는 지 변경해 주었습니다

2022-05-24 04:51 UTC, unchain123 commented on Calculator/Enum/ExpressionParser.swift
> +        let result = results.map { String($0) }
기본형으로 변경했습니다.

2022-05-24 04:51 UTC, unchain123 commented on Calculator/Enum/ExpressionParser.swift
> +        let operands = paser.compactMap{ Double($0) }
기본형으로 다 같이 변경했습니다

2022-05-24 05:00 UTC, unchain123 commented on Calculator/Enum/ExpressionParser.swift
> +        return Formula(operands: operandsQueue, operators: operatorsQueue)
아! 그렇군요! 상수를 리턴하는 방식으로 변경해 주었습니다.

2022-05-24 05:01 UTC, unchain123 commented on Calculator/Model/Formula.swift
> +                return 0.0
에러를 던지는 방식으로 변경 했습니다.

2022-05-24 05:03 UTC, unchain123 commented on Calculator/Model/Formula.swift
> +            }
넵 바로 변경했습니다. 안그래도 너무 어색한거 같았습니다.

2022-05-24 05:04 UTC, unchain123 commented
@AppleCEO 
도미닉 자세한 피드백 감사합니다.  수정사항 모두 수정해 주었습니다.

2022-05-24 05:16 UTC, merged