계산기 [STEP 2] Brad
yagom-academy/ios-calculator-app pull request #266
Opened 2022-05-23 07:41 UTC by bradheo65

안녕하세요 도미닉!! @AppleCEO

PR이 예상일정 보다 늦어져서 죄송합니다!!.

고차함수에 대한 이해가 부족하다보니 고민을 많이 했네요...코드가 잘 작성되었는지 확인 부탁드립니다!!

## [STEP 2]

### 이번 스텝 수행 중 핵심 경험 체크
- [x] UML을 기반으로 한 코드구현
- [x] 숫자와 연산자 입력에 큐 활용
- [x] TDD를 기반으로 코드 작성하기(선택)
---

## UML
![image](https://user-images.githubusercontent.com/45350356/169752215-996a275b-5de5-478e-8b7d-a772b921f7e9.png)

---
 
### STEP02 구현 내용📑
- ExpressionParser: 
    - parse: input값을 각 프로퍼티에 return해주는 함수
    - componentsByOperators: input 값을 split으로 수정해주는 함수
- Operator: 
    - calculate: rawValue 별 함수 기능 수행하는 함수
    - add: 더하기
    - subtract: 빼기
    - divide: 나누기
    - multiply: 곱하기
- Formula:
    - result: lhs, rhs를 계산한 값을 리턴해주는 함수
    - lhs: 최초 연산수 (계속 업데이트 필요)
    - number: lhs와 비교하는 연산수

### STEP02 진행하면서 고민한 점 🫠
---
1. 초기 lhs, rhs 연산수, 연산자 구분 코드 작성 후 TDD를 작성하고 테스트 결과를 보니 연산수가 짝수(["1", "+", "2"])로 들어가 있어야만 성공이 되었고, 홀수(["1", "+", "2", "+3"])로 입력 시 error가 나와 다시 생각해보니 lhs를 계속 업데이트해야 되는 로직으로 구현을 해야만 짝수, 홀수로 입력해도 lhs를 result값으로 반환하면 되기에 코드에 반영해보았습니다.

2. ExpressionParser에서 연산수와 연산자를 나누어 각각의 프로퍼티에 넣어 주어야 하는데 고차함수의 이해가 부족해 어떻게 처리를 해야 될지는 생각했지만 막상 코드로 구현하기 어려웠습니다. 그래서 고차함수 파트를 다시 공부하고 나서 프로젝트 코드 상에서 for문으로 사용해서도 처리가 가능하지만 코드 들여쓰기, 프로퍼티 사용 등 고차함수의 이점을 통해 원하는 결과값을 도출할 수 있도록 코드를 작성해보았습니다.

### STEP02 진행하면서 경험한 점 ✏️
---
1.	UML을 보며 TDD 작성 후에 코드를 작성
	-    UML을 보면서 TDD를 하는데 처음에는 ExpressionParser -> Foumula -> CalculatorItemQueue로 작은 기능 부터 TDD를 작성해보았는데 활동학습 가이드에서는 큰 기능부터 구현하라고 되었있습니다. 확실히 큰 기능부터 TDD를 작성하고 나니 작은 기능에 대해 보완할 점, 추가해야 될 점이 보이기 시작했습니다.

2.	TDD 각 파일 별 분리

3.	고차함수 <br>
	-	map
	- 	filter
	-   reduce
	
    -> 고차함수 사용을 통해 단순 반복문과의 차이점을 알게 되었습니다.

4.	Error 활용을 해볼수 있는 기회였습니다.
	- 	throws -> ()
	- 	throw

---

2022-05-23 14:38 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
@bradheo65 고생하셨습니다.
이번 프로젝트 쉽지 않았는데 진행하시느라 힘드셨죠
몇가지 개선사항들 남겨봤습니다.
이해 안되거나 궁금한거 있으면 편하게 연락주세요.
화이팅입니다!

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
> +        splitElements.compactMap {Double($0)}
{Double($0)} 이런 형태는 좀 어색하네요.
보통 한 줄로 줄여서 쓰면 { 뒤에 한 칸 띄고 } 앞에도 한 칸 띄어서 작성했던 것 같아요(물론 여러 줄로 풀어서 작성하는 것이 더 좋습니다)
$0 을 사용하는 축약형을 사용하지 않고 풀어서 쓰는 기본형으로 작성해보면 좋겠습니다.
아직은 기본형이 어떤 모양인지 익숙해지지 않았기 때문에 이렇게 줄여서 써서 어떻게 동작하는 것인지 이해하지 못하는 것보다 기본형으로 작성하는 것을 추천드립니다~

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
> +            .forEach {
아래 .forEach 는 여러 줄로 작성되어 있는데 위에 compactMap 은 한 줄로 너무 줄여서 써서 벨런스도 맞지 않아 보이고 어색하네요~

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
> +        return Formula(operands: operandQueue, operators: operatorQueue)
리턴에서 생성자를 사용하는 것은 조금 어색한 것 같습니다
리턴 위에서 상수에 이 생성자를 넣고 리턴할 때 그 상수를 가져다가 쓰는 방식이 더 좋을 것 같아요!

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/Formula.swift
> +            }
가드 렛이 반복되는데 한 줄에 작성해보면 어떨까요?

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/Formula.swift
> +        }
에러가 발생하면 throw 를 던져주는 것 좋습니다! 👍

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/LinkedList.swift
> +
여기에 공백은 어떤 의미일까요?
코드에는 공백이나 줄바꿈 하나에도 의미가 있어야 합니다.
의도를 나타낼 수 있는 최소한의 줄바꿈을 추천드려요.
무조건 적은 줄의 코드가 좋다는 뜻은 아닙니다~

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/Double+Extension.swift
> +}
이 코드는 어떤 동작을 하나요?

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Calculator/Model/Extension/String+Extension.swift
> +        return self.split(separator: target).map{String($0)}
축약형이 많이 들어갔군요!
그리고 return 에서 이러한 처리들이 많이되면 코드를 찾아가고 이해하기 힘들어집니다.
어떤 상수에 split 한 결과를 넣어주고요
또 아래 줄에서 split 한 결과를 map 해주는 방식,
그리고 return 에서는 map 한 결과를 보내주는 식으로 3줄 이상으로 풀어서 작성해보면 좋겠네요~

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Test_CalculatorItemQueue/Test_CalculatorItemQueue.swift
> +    func test_enqueue_실행시_123456_를넣었을때_123456_를반환하는지() {
메소드명이 명확하네요~ 🔢

2022-05-23 14:38 UTC, AppleCEO commented on Calculator/Test_CalculatorItemQueue/Test_CalculatorItemQueue.swift
> +            sut.enqueue([$0])
$0 을 아직은 사용하지 않는 것이 좋을 것 같아요.
.enqueue, .map 등을 입력하면 파란색으로 예상되는 타입, 코드들의 형태가 보여지는데 그 부분을 떠블클릭하면 기본적인 형태의 코드로 구조가 작성됩니다.
그 방식 사용해보고 기본형으로 작성해보면 좋겠네요~

2022-05-24 00:25 UTC, bradheo65 commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
> +        splitElements.compactMap {Double($0)}
아!! 좋은 리뷰 감사합니다!!
단지 축약형이 좋다고 생각해서 썻는데,, 다시 생각해보니 코드만 보고 어떤 타입을 넣고 return해주는 지 코드에 직접 표현을 하면 더 가독성이 증감 되겠군요 !! 코드는 작성 시엔 짧게..라고 생각하고 있었네요..
이렇게 변경해 보았습니다 !!
```swift
        splitElements.compactMap { (element: String) -> Double in
            let alterElement: Double = Double(element) ?? 0.0
            return alterElement
        }.forEach {
            operandQueue.enqueue($0)
        }
```

2022-05-24 00:26 UTC, bradheo65 commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
> +            .forEach {
위와 같은 기본형태로 재작성 해보니 확실히 밸런스가 있어 보여요!
```swift
        splitElements.compactMap { (element: String) -> Character in
            let alterElement: Character = Character(element)
            return alterElement
        }.forEach {
            if let operatorElements = Operator(rawValue: $0) {
                operatorQueue.enqueue(operatorElements)
            }
        }
```

2022-05-24 00:36 UTC, bradheo65 commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
> +        return Formula(operands: operandQueue, operators: operatorQueue)
넵 확실히 깔끔해졌습니다. 아래 코드 대로 수정 해보았습니다!
```swift
        let parseDataResult = Formula(operands: operandQueue, operators: operatorQueue)
        return parseDataResult
```

2022-05-24 00:36 UTC, bradheo65 commented on Calculator/Calculator/Model/CalculatorQueue/Formula.swift
> +        }
🫡

2022-05-24 00:40 UTC, bradheo65 commented on Calculator/Calculator/Model/CalculatorQueue/Formula.swift
> +            }
음.. 제생각은 ErrorCase가 서로 다르기에 나누었는데 두가지중 하나가 에러일때 발생되는 에러 추가하면 되겠네요!
```swift
enum ErrorCase: Error {
    case operandsDequeue
    case operatorDequeue
    case listDequeue
}
```

```swift
guard let number = operands.dequeue(),
      let result = operators.dequeue() else {
    throw ErrorCase.listDequeue
}
```

2022-05-24 00:42 UTC, bradheo65 commented on Calculator/Calculator/Model/CalculatorQueue/LinkedList.swift
> +
앗 미처 확인하지 못한 부분 이네요 ,, 리뷰 감사합니다!

2022-05-24 01:30 UTC, bradheo65 commented on Calculator/Test_CalculatorItemQueue/Test_CalculatorItemQueue.swift
> +    func test_enqueue_실행시_123456_를넣었을때_123456_를반환하는지() {
감사합니다 ㅎ🫡

2022-05-24 01:32 UTC, bradheo65 commented on Calculator/Test_CalculatorItemQueue/Test_CalculatorItemQueue.swift
> +            sut.enqueue([$0])
네 도미닉의 의견에 동의 합니다! 기본형으로 하니 확실히 어떤 타입을 활용할지랑 반환되는지에 대해 다시 한번 생각해보는 계기가 되었습니다. 감사합니다!!
```swift
extension String {
    func split(with target: Character) -> [String] {
        let splitStringResult = split(separator: target)
            .map{ (element: String.SubSequence) -> String in
                let alterElement = String(element)
                return alterElement
            }
        return splitStringResult
    }
}
```

2022-05-24 01:34 UTC, bradheo65 commented on Calculator/Calculator/Model/Extension/String+Extension.swift
> +        return self.split(separator: target).map{String($0)}
네 도미닉의 의견에 동의 합니다! 기본형으로 하니 확실히 어떤 타입을 활용할지랑 반환되는지에 대해 다시 한번 생각해보는 계기가 되었습니다. 감사합니다!!
```swift
extension String {
    func split(with target: Character) -> [String] {
        let splitStringResult = split(separator: target)
            .map{ (element: String.SubSequence) -> String in
                let alterElement = String(element)
                return alterElement
            }
        return splitStringResult
    }
}
```

2022-05-24 02:53 UTC, bradheo65 commented on Calculator/Calculator/Model/Double+Extension.swift
> +}
UML에 아무런 타입이 적혀져 있지 않아서 코드를 작성하진 않았지만.

재생각에는 추후엔 operand(연산수)에서 어떠한 처리를 해주지 않을까 생각됩니다..

2022-05-24 03:48 UTC, bradheo65 commented
### 궁금한 점
---
nan을 반환해서 값을 가져오고 싶어 TDD에서 테스트 결과를 보니 동일한 것으로 나오는데.. return Doubel.nan을 해도 오류 메시지가 나오더라구요... 에러 메세지에서 String을 이용할려고 했지만 result() -> Double로 되어있어 어떤 방향을 구현해야 할지 궁금합니다..
<img width="898" alt="스크린샷 2022-05-24 오후 12 41 54" src="https://user-images.githubusercontent.com/45350356/169944376-02e2b632-427b-4627-895b-f46e2d525bff.png">

2022-05-24 05:08 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/Formula.swift
> +            }
아.. 다른 오류였었나요 코드에 보면 같은 오류를 반환하는 것 같아서 세부적으로 나눌 수 있다면 기존 구조도 괜찮을 것 같습니다~

2022-05-24 05:19 UTC, merged