계산기 [STEP 2] BaekGom
yagom-academy/ios-calculator-app pull request #267
Opened 2022-05-23 11:23 UTC by Baek-Gom-95

안녕하세요 쿠마! @leejun6694  계산기 STEP2 첫 PR 보내드립니다 UML 분석을 하다보니 많이 늦었습니다! 잘부탁드립니다! 😊

# UML
![6189d7537c82755a83c68a7d](https://user-images.githubusercontent.com/94192712/169808392-7b0c4564-0b4d-44fa-b45a-a1fecca99507.jpeg)

# [STEP 2] 기능 및 코드 설명 🙂
- result: 피연산자와 연산기호를 while문으로 연산후 리턴 
- parse: 피연산자와 연산기호를 빈칸 기준으로 split 후 숫자면 opernds 에 enqueue 기호면 operators 에 enqueue 후 Formula 타입으로 리턴
- componetsByOperators: 매개변수를 빈칸기준으로 split 후 [String] 으로 반환
- split: 매개변수로 들어온 것을 조건값으로 문자열을 나누어 [String] 형으로 반환
- add: lhs 와 rhs 를 값을 더해서 반환
- substract: lhs 와 rhs 를 값을 빼서 반환
- divide: lhs 와 rhs 를 값을 나누어서 반환
- multiply: lhs 와 rhs 를 값을 곱해서 반환

# [STEP 2] 고민한점 및 해결방안 🤔
### 고민한점
### UML 분석:
- 만들어 본것이 아닌 만들어진 UML을 보고 분석을 하고 내용을 생각하는게 참으로 어려운거 같습니다 

### 배운개념 💡

- Extension
    * String 에 원하는 기능을 추가헸습니다 extension 이란 어떤 기능이라는걸 알고 처음 사용하는 거라 앞으로 유용하게 사용할거 같습니다

2022-05-23 16:29 UTC, leejun6694 requested changes
깔끔하게 구현해주셔서 코드를 편하게 읽을 수 있었습니다.
몇 가지 코멘트를 남겼는데, 확인 부탁드려요~!

2022-05-23 16:29 UTC, leejun6694 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +    private var tail: Node<T>?
첫번째 `tail` 을 설정해주는 곳은 어디있을까요!?

2022-05-24 06:21 UTC, Baek-Gom-95 commented on Calculator/Calculator/Enum/ExpressionParse.swift
> +
컨벤션에 더욱 신경쓰겠습니다 ㅠㅜ 😭

2022-05-24 06:22 UTC, Baek-Gom-95 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +    private var tail: Node<T>?
append 함수에 tail 설정을 추가해주었습니다 🙂

2022-05-24 06:23 UTC, Baek-Gom-95 commented on Calculator/Calculator/Enum/ExpressionParse.swift
> +            if let parseArithmetic = Operator(rawValue: Character(parseString)) {
그부분을 생각 못한거 같습니다 감사합니다! if else 문으로 변경하였습니다 😊

2022-05-24 06:24 UTC, Baek-Gom-95 commented on Calculator/Calculator/Formula.swift
> +            result = operators.calculate(lhs: result, rhs: operands)
예외처리를 해줬어야 되는데 앞으로 주의해야겠습니다 😭 `Enum Calculator ` 를 만들어서 0으로 나누게 될시에 에러처리 해주었습니다

2022-05-24 06:25 UTC, Baek-Gom-95 commented on Calculator/Calculator/Extension/StringExtension.swift
> +        return split(separator: target).map{ (value) in return String(value)}
고차함수를 사용하여 생략을 해보았습니다 🙂

2022-05-24 07:14 UTC, leejun6694 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +        let node = head
Node 를 새로 정의하는게 아닌가요...?

2022-05-24 07:28 UTC, Baek-Gom-95 commented on Calculator/Calculator/LinkedList/LinkedList.swift
> +        let node = head
head에 값이 있을경우 tail에 새로운 값을 넣어주도록 변경했습니다

2022-05-24 07:29 UTC, leejun6694 approved these changes
LGTM

2022-05-24 07:30 UTC, leejun6694 commented on Calculator/Calculator/Extension/StringExtension.swift
> +        return split(separator: target).map{ (value) in return String(value)}
`.map { String($0) }`
으로도 구현이 가능합니다~!

2022-05-24 07:30 UTC, merged