계산기 [Step 3] Groot
yagom-academy/ios-calculator-app pull request #269
Opened 2022-05-25 05:49 UTC by Groot-94

@leejun6694 안녕하세요 쿠마!
Step3 첫 PR 보냅니다! 어제까지 보내려고 했지만, 많이 어려웠습니다! 아직 부족함이 많겠지만, 예정보다 늦었기 때문에 PR을 보냅니다! 이번에도 좋은 리뷰 부탁드립니다 👍

# 📌 작업 내용
## ViewController
- UI와 연동해서 계산기능을 수행하는 앱을 구현했습니다.
- 계산 진행 중 에러처리는 "NaN" 을 반환하도록 구현했습니다.
## Double
- Double 값이 소수점을 포함하는 경우 20자리까지만 표시하고 나머지는 반올림해서 String을 반환하는 함수를 구현했습니다.
- Double 값의 3자리마다 , 를 포함하도록 구현했습니다.
---
# 📌 고민한 점
### scrollView의 크기를 지정해주는 부분에서 고민을 했습니다.
##### 초기 storyboard
![](https://i.imgur.com/Ier2Bby.png)
- scrollView의 ContentView(StackView)에 존재하던 StackView 2개를 지우고 앱 실행에선 문제없이 새로운 StackView가 추가되었지만, 아래와 같이 scrollView의 Y축에 대한 경고창이 보였습니다.
##### 수정 후 경고창 storyboard
![](https://i.imgur.com/HYgqPSz.png)
- 경고창을 해결하기 위해서 scrollView의 Y축을 지정해주려고 Y축의 길이를 지정하면 scrollView의 크기가 고정돼서 늘어나지 않았습니다.
- Add Missing Constrains 버튼 클릭 시 경고창은 사라졌지만, ContentView로 쓰이는 StackView 안에 새로운 StackView를 추가해도 실제로 앱에선 나타나지 않았습니다.
#### 해결방법
- 콘텐츠뷰에 빈 라벨을 하나 가진 StackView를 추가하고 앱 시작 시 ViewDidRoad에서 ContentView의 SubView를 모두 지워주는 동작을 하도록 했습니다.
    ##### 최종 storyboard
    ![](https://i.imgur.com/snKRVzV.png)
---
### scrollView에 수식이 추가될 때 최하단으로 자동 스크롤 할 수 있도록 하는 부분에서 고민했습니다.
- downScroll() : 스크롤뷰의 화면을 가장 밑으로 내려주는 기능의 함수입니다.
- operatorButtonAction() : 연산자와 피연산자를 수식으로 추가하고, 화면으로 보여주는 함수입니다.
#### 문제상황
- downScroll() 를 operatorButtonAction() 안에서 호출했을 시 1칸씩 덜 내려오는 문제가 있었습니다. 
- 브레이크 포인트로 확인 시` downScroll()는 operatorButtonAction()의 실행이 끝나기 전에 마지막에 호출이 되고`, `operatorButtonAction() 실행이 끝나고 나서 ContentView(StackView)에 새로운 수식이 추가되는 순서`였기 때문에 1칸 씩 덜 내려온다고 판단했습니다.
#### 해결을 위한 시도
- 1. didSet을 사용해서 ContentView(StackView)의 수정이 끝나면 호출하도록 했습니다.
    >왜인지 함수를 호출하지 않았습니다... 단순히 ContentView(StackView)에 새로운 StackView를 추가하는 동작은 ContentView(StackView)의 변화로 판단하지 않는다고 생각해봤습니다...
- 2. ScrollViewDelegate의 scrollViewDidChangeAdjustedContentInset(UIScrollView) 함수를 이용해서 수정하려고 해봤습니다.
    >ScrollView안에 새로운 StackView를 추가하는 방식이 아닌 ContentView(StackView)에 추가하는 방식이기 때문에 직접적인 ScrollView의 수정이 일어나지 않다고 판단해서인지 호출하지 않았습니다.
- 3. StackViewDelegate는 찾아봤지만, 없었습니다..
- 4. viewDidLayoutSubviews() 를 사용하는 방법
    >숫자패드를 눌렀을 때 operandLabel이 변경되면 viewDidLayoutSubviews()을 호출했지만, 이상하게도 
    ContentView(StackView)에 새로운 StackView를 추가하는 동작은 호출하지 않는지, 아니면 뷰에 추가되기 전에 먼저 실행되는 것인지.. 문제가 해결되지는 않았습니다.
#### 해결방법
- DispatchQueue를 사용해서 downScroll()를 0.01초 뒤에 실행하는 방법으로 해결했습니다. 하지만 아쉬움이 많이 남습니다. 제가 모르는 방법이 있을 것 같네요... 혹시 쿠마라면 어떻게 해결하셨을지 궁금합니다.
### CalculateItem의 쓰임새를 고민했습니다.
- 구현하면서 이 프로토콜을 어떻게 사용하면 좋을지 고민을 해봤습니다.. 하지만 실제로 사용하지는 못했습니다.. 어떤 용도로 사용해야 할지 도저히 모르겠습니다...
---
# UML
## Class Digram
![](https://i.imgur.com/RODTZM8.png)

2022-05-25 17:57 UTC, leejun6694 requested changes
그루트 안녕하세요!
몇가지 코멘트를 남겼는데 확인부탁드려요~!
그리고 가능하다면 디스코드로 얘기를 더 나눠볼까요!?

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +        mathematicalExpressionStackView.subviews.forEach { $0.removeFromSuperview() }
왜 처음에 subview 들을 remove 하고 시작하는지 궁금합니다 : )

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction private func acButtonAction(_ sender: UIButton) {
method 는 `동작(행위)`을 하는 것이므로, 네이밍에 동사가 포함되면 좋을 것 같네요.
스타일은 각자가 다르겠지만, 구글링을 통해 대다수의 개발자들이 어떻게 네이밍하는지 참고해도 좋습니다!

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    private var isOperandinputed = false
`isOperandInputed`
i 가 소문자로 입력되어있네요..!?

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +        guard let operand = Double(getText(operandLabel.text)) , operand != 0.0 else {
잘못된 띄어쓰기가 있는 것 같습니다~~!

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +        operandLabel.text = String(-Int(operand))
`Int` 로 변경하는 이유가 있나요?
이유가 있는거면, `Double` 로 굳이 캐스팅하지 않아도 될 것 같네요...?

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +            mathematicalExpression += " \(getText(operatorLabel.text)) \(getText(operandLabel.text))"
`mathematicalExpression` 의 초기값을 "0" 으로 하면, `isFirstInput` 가 필요 없을 수도 있다는 생각이 드네요~!
어떠신가요?

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    private func getText(_ string: String?) -> String {
`optional` 값이 많다보니 method 를 만든 마음은 이해가 갑니다ㅎㅎ
하지만, 몇군데는 `string 값이 없는 경우는 에러로 처리`해주는게 맞지 않을까? 라는 생각이 드는 곳도 있네요.
여유가 조금 있다면, 이 부분도 수정하면 좋을 것 같아요~!

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +            return "NaN"
모두 똑같이 처리한다면, catch 가 하나만 있어도 되지 않을까요?

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +            isOperandinputed = true
공통으로 사용되는 코드는 if-else 밖에서 처리해도 되겠네요~

2022-05-25 17:57 UTC, leejun6694 commented on Calculator/Model/Enum/Operator.swift
> +enum Operator: Character, CaseIterable ,CalculateItem {
띄어쓰기..!

2022-05-26 08:11 UTC, Groot-94 commented
@leejun6694 안녕하세요 쿠마! 말씀해주셨던 부분은 수정했습니다. 그리고 다른 제약사항도 추가해봤습니다.
- 0을 입력하고 123 등 일반 숫자를 입력 시 "0123" 과 같은 형태에서 "123"으로 변경해서 스크롤뷰에 들어가도록 수정했습니다.
- 0123.123.123 과 같이 숫자가 아닌 피연산자 입력뒤에 연산자 버튼을 클릭 시  NaN을 출력하도록 수정했습니다.
- 기존에 해결하지 못 한 `scrollView의 크기를 지정해주는 부분에서 고민을 했습니다.` 부분을 해결했습니다! 그로인해 리뷰해주신 `왜 처음에 subview 들을 remove 하고 시작하는지 궁금합니다 : )` 내용의 remove는 삭제했습니다. 

디스코드에서 이야기를 하고 싶다고 하셔서 아직 push를 하진 않았습니다 :)

2022-05-27 07:13 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +        mathematicalExpressionStackView.subviews.forEach { $0.removeFromSuperview() }
처음 fork 받았을때 스크롤뷰에 있던 서브뷰를 지우기 위해 사용했습니다.
스토리보드에서 서브뷰를 처음부터 지우고 오토레이아웃 수정으로 해결했습니다 :)

[09e7f09](https://github.com/yagom-academy/ios-calculator-app/pull/269/commits/09e7f09d92c61fc35625aa81fbfbbbd2f289daf9)

2022-05-27 07:14 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction private func acButtonAction(_ sender: UIButton) {
UI버튼 동작에 대한 네이밍을 어떻게 할 지 고민하다가 다른 함수와  같은 방식으로 수정해봤습니다!

[18701e8](https://github.com/yagom-academy/ios-calculator-app/pull/269/commits/18701e86d1fe62c2579a2e8a72a608a316aa34b8)

2022-05-27 07:15 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +    private var isOperandinputed = false
수정했습니다

[18701e8](https://github.com/yagom-academy/ios-calculator-app/pull/269/commits/18701e86d1fe62c2579a2e8a72a608a316aa34b8)

2022-05-27 07:17 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +            isOperandinputed = true
수정했습니다

[7457072](https://github.com/yagom-academy/ios-calculator-app/pull/269/commits/7457072075b2a8af8b9ecc90a1738db510ca8453)

2022-05-27 07:17 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +            return "NaN"
그럴거 같네요,, 수정했습니다

[7457072](https://github.com/yagom-academy/ios-calculator-app/pull/269/commits/7457072075b2a8af8b9ecc90a1738db510ca8453)

2022-05-27 07:48 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +    private func getText(_ string: String?) -> String {
말씀해주신 내용을 듣고 operator와 operand 부분에 필요하다고 optional binding 생각이 들어서 수정했습니다!

[1d81577](https://github.com/yagom-academy/ios-calculator-app/pull/269/commits/1d81577d70cb675b7cd634eaf9e7a2d68ec18f89)

2022-05-27 07:49 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +            mathematicalExpression += " \(getText(operatorLabel.text)) \(getText(operandLabel.text))"
수정했습니다!!

[cb62fd1](https://github.com/yagom-academy/ios-calculator-app/pull/269/commits/cb62fd1aa2adc3981cbc739106095629348d21b9)

2022-05-27 07:57 UTC, Groot-94 commented
@leejun6694 
안녕하세요 쿠마
말씀해주신 부분에 대한 수정과 필요하다고 생각했던 부분들에 대해 추가를 완료했습니다 :) 
## 추가내용
- Scrollview 밖에 있는 operandLabel도 3자리 마다 "," 분리하도록 수정했습니다.
- 0을 먼저 입력하고 숫자를 입력할 때 "01213"으로 나타나는 부분을 "1213" 과 같이 나타나도록 수정했습니다.
- 0과 00이 계속해서 입력되는 부분 ( 예: "0000")을 수정했습니다.

2022-05-29 16:01 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction private func acButtonAction(_ sender: UIButton) {
`IBOutlet` 의 네이밍처럼 `IBAction` 도 어떤 동작 + UI 이름이 포함되면 어떨까요?
예) `tapAcButton(_ sender: UIButton)`

2022-05-29 16:06 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +        operandLabel.text = checkTheSign(getText(operandLabel.text))
```
guard let operand = operandLabel.text, Double(operand) != 0.0 else {
    return
}
operandLabel.text = "-" + operand
```

위처럼도 구현이 가능할까요?

2022-05-29 16:11 UTC, leejun6694 approved these changes
안녕하세요 그루트!
리뷰 내용을 알맞게 수정해주셨네요ㅎㅎ 고생 많으셨습니다.

2022-05-29 16:11 UTC, merged

2022-05-30 01:07 UTC, Groot-94 commented on Calculator/Calculator/ViewController.swift
> +        operandLabel.text = checkTheSign(getText(operandLabel.text))
```swift
guard let operand = operandLabel.text, Double(operand) != 0.0 else {
            return
        }
       
operandLabel.text = checkTheSign(operand)
```
중복으로 -가 늘어나는 현상을 처리하기 위해 현재 부호를 확인하는 checkTheSign 함수를 사용했습니다!
훨씬 간결하고 가독성이 좋네요..