계산기 [Step2] 재재
yagom-academy/ios-calculator-app pull request #270
Opened 2022-05-25 10:42 UTC by ZZBAE

라이언 안녕하세요! @ryan-son 🦁
계산기 step 2 PR 하기까지 오래걸렸는데 양해해주시고 기다려주셔서 정말 감사드립니다 🙇🏻‍♀️

# 🧮 계산기 프로젝트 (Calculator) - Step 2
> 프로젝트 기간 2022.05.20 금  ~ 2022.05.25 수 </br>
팀원: 재재</br>
리뷰어: Ryan
---

## 💾개발환경 및 라이브러리
[![swift](https://img.shields.io/badge/swift-5.6-orange)]()
[![xcode](https://img.shields.io/badge/Xcode-13.3-blue)]()

## 👩🏻‍💻 프로젝트 진행 방식
- 이번 프로젝트를 수행함에 있어 꼭 읽고 참고해야하는 공식 문서 빠짐없이 읽고 공부하기
- Step 2 수행 중 핵심경험 체크 ➡️ 왜 필요할지 생각하기
- 명세에 나와있는 UML 분석 후 코드 작성하기
- 모르거나 헷갈리는 부분 꼭 꼭 질문하기

## 💡Step 2 수행 중 핵심경험
- [x] UML을 기반으로 한 코드구현
- [x] 숫자와 연산자 입력에 큐 활용

## 🗺 UML
<img width="998" alt="스크린샷 2022-05-25 오후 7 23 34" src="https://user-images.githubusercontent.com/98302604/170241197-5150f98e-194b-4886-8015-169b4fdc70ab.png">

## 🏀TroubleShooting (고민한점, 해결한점)
1. UML 분석
> 이번 Step 에서 가장 중요한 건 지정되어 있는 UML을 반영하여 코드 작성을 하는 것이였습니다. 우선 UML에 익숙하지 않기도 하고 전체적인 흐름을 알기가 어려워서 분석하는데 오랜 시간이 걸렸던게 아쉽기도 하고 배운점도 많았습니다. String extension에서 만들어준 split 함수를 이용해서 enqueue된 값을 하나의 연산자로 나누고, componentsByOperators에서 열거해준 4개의 연산자로 나눌 수 있게 만들어준 후, parse 에서 피연산자와 연산자로 나누어 최종적으로 Formula 에서 나눠준 것들을 계산해주는 흐름으로 이해를 했습니다.

2. 인스턴스화에 대해
```swift
struct Formula {
    var operands = CalculatorItemQueue<Double>()
    var operators = CalculatorItemQueue<Operator>()
```
```swift
struct Formula {
    var operands: CalculatorItemQueue<Double>
    var operators: CalculatorItemQueue<Operator>
```
이렇게 구조체 내부 프로퍼티에 타입만 설정해놓는거랑 선언하면서 인스턴스화를 아예 해버리는거랑 무슨 차이가 있는지 궁금했는데, operands 와 operators 는 단순히 Formula의 인스턴스 프로퍼티이기 때문에 굳이 미리 queue인스턴스를 생성할 일은 없다는 서포터즈 분의 조언에 따라 구현해보았습니다.

## ⁉️ 조언을 구하고 싶은 부분
제가 아직 에러처리를 하는 방법을 알지 못해서 catch는 다음 스텝에서 진행해보도록 하겠습니다.. 이 부분 혹시 라이언의 설명을 조금 들어도 괜찮을까요?😅

## ⌨️ 커밋 규칙
* feat    : 기능 추가 (새로운 기능)
* fix      : 버그 수정
* refact : 리팩토링 (네이밍 수정 등)
* style   : 스타일 (코드 형식, 세미콜론 추가: 비즈니스 로직에 변경 없음)
* docs    : 문서 변경 (문서 추가, 수정, 삭제)
* test    : 테스트 (테스트 코드 추가, 수정, 삭제: 비즈니스 로직에 변경 없음)
* chore   : 기타 변경사항 (빌드 스크립트 수정 등)

## 💻 코드 컨벤션
Swift Statements 형식 준수

2022-05-25 13:41 UTC, ryan-son commented
@ZZBAE 재재~ 타겟 브랜치를 본인의 브랜치로 변경해주세요~ 🙏

2022-05-26 04:07 UTC, ryan-son requested changes
재재~ UML만 참고해서 로직을 구현하기 쉽지 않았을텐데 고생 많으셨습니다! 자세한 피드백은 개별 코멘트를 참고해주세요~

> ## 🏀TroubleShooting (고민한점, 해결한점)
> 1. UML 분석
> 이번 Step 에서 가장 중요한 건 지정되어 있는 UML을 반영하여 코드 작성을 하는 것이였습니다. 우선 UML에 익숙하지 않기도 하고 전체적인 흐름을 알기가 어려워서 분석하는데 오랜 시간이 걸렸던게 아쉽기도 하고 배운점도 많았습니다. String extension에서 만들어준 split 함수를 이용해서 enqueue된 값을 하나의 연산자로 나누고, componentsByOperators에서 열거해준 4개의 연산자로 나눌 수 있게 만들어준 후, parse 에서 피연산자와 연산자로 나누어 최종적으로 Formula 에서 나눠준 것들을 계산해주는 흐름으로 이해를 했습니다.

요구사항은 반드시 UML에 따라 구현해보라는 것이지만, 불필요하다고 판단되는 경우에 일부는 활용하지 않아도 괜찮습니다. 어떤 경우에는 메서드의 매개변수와 반환 타입을 변경하는 편이 더 나은 경우도 있으니 본인이 더 효율적이라고 생각되는 구조가 있다면 유연하게 변경해보셔도 괜찮습니다.

> 2. 인스턴스화에 대해
```swift
struct Formula {
    var operands = CalculatorItemQueue<Double>()
    var operators = CalculatorItemQueue<Operator>()
```
```swift
struct Formula {
    var operands: CalculatorItemQueue<Double>
    var operators: CalculatorItemQueue<Operator>
```
> 이렇게 구조체 내부 프로퍼티에 타입만 설정해놓는거랑 선언하면서 인스턴스화를 아예 해버리는거랑 무슨 차이가 있는지 궁금했는데, operands 와 operators 는 단순히 Formula의 인스턴스 프로퍼티이기 때문에 굳이 미리 queue인스턴스를 생성할 일은 없다는 서포터즈 분의 조언에 따라 구현해보았습니다.

구조체의 모든 프로퍼티에 초기값을 선언하는 경우 이니셜라이저에 기본값을 적용한 것과 같이 인스턴스 초기화 구문을 간단하게 만들 수 있다는 장점이 있습니다. 구조체는 클래스와 달리 기본적으로 [`memberwise initiailizer`](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html#ID214)를 제공하니 이런 특성을 가지는데, 클래스의 경우에는 별도 이니셜라이저를 제공하지 않고 프로퍼티에 초기값을 제공하면 외부에서 프로퍼티를 지정해줄 수 있는 수단을 잃게 됩니다. 구조체와 클래스 간에 이런 차이가 발생하는 이유를 알아보는 것도 재미있을거에요~

> ## ⁉️ 조언을 구하고 싶은 부분
> 제가 아직 에러처리를 하는 방법을 알지 못해서 catch는 다음 스텝에서 진행해보도록 하겠습니다.. 이 부분 혹시 라이언의 설명을 조금 들어도 괜찮을까요?😅

물론이죠~ 에러처리 뿐만 아니라 다른 방면으로도 도움이 필요하시면 말씀해주세요~

2022-05-28 05:52 UTC, ZZBAE commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		7E4DE30E283E37A2009C09EC /* Formula.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7E4DE30D283E37A2009C09EC /* Formula.swift */; };
Step1 에서 말해주신 것처럼 Sources가 코드와 뷰를 다루는 것들의 폴더인데 Extension, Protocols, Models 가 안에 들어가야하는 것을 생각 못한 것 같습니다. 말씀해주신 것 반영하여 폴더 수정하였습니다!

2022-05-28 07:43 UTC, ZZBAE commented on Calculator/Models/Formula.swift
> +                throw FormulaError.emptyError
앗 넵! `noOperandsInQueue` 케이스로 사용 변경해주었습니다!

2022-05-28 07:45 UTC, ZZBAE commented on Calculator/Models/Formula.swift
> +            }
넵 수정 완료 해주었습니다!

2022-05-28 07:45 UTC, ZZBAE commented on Calculator/Models/Formula.swift
> +        guard var result: Double = operands.dequeue() else { throw FormulaError.noOperandsInQueue }
앗 제가 이런 저런 시도를 해보느라 정작 컨벤션을 맞추지 않고 커밋을 해버렸네요. 죄송합니다ㅠㅠ 수정 완료해주었습니다!

2022-05-28 07:46 UTC, ZZBAE commented on Calculator/Models/ExpressionParser.swift
> +        operators.forEach { operatorsQueue.enqueue( $0 ) }
넵 ! 확인 후 변경해주었습니다. 다음부터 주의하겠습니다! 🥲

2022-05-28 07:52 UTC, ZZBAE commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		};
다른 분들도 알아보기 용이하려면 일반적인 extension 파일 이름 형식을 사용하는게 좋다고 하셔서 적용해보았습니다!

2022-05-28 08:13 UTC, ZZBAE commented on Calculator/Models/Formula.swift
> +    case emptyError
`noOperandsInQueue`랑 맞춰서 `noOperatorsInQueue`로 바꾸어주었습니다. 수정한 것 괜찮은가요..?

2022-05-28 17:30 UTC, ZZBAE commented on Calculator/Extension/Character+Extension.swift
> +}
사칙연산 기호가 `Character` 로 표현될 수 있어서 `Character` 에 `CalculatorItem` 프로토콜을 채택해 주었지만,  `OperatorItem`  enum에 `CalculatorItem` 프로토콜을 채택하여 rawValue로 사칙연산 기호를 추적할 수 있다는 사실을 알게되어 수정해주었습니다.

2022-05-31 11:51 UTC, ZZBAE commented on Calculator/Models/Formula.swift
> +            result = (operatorsItem?.calculate(lhs: result, rhs: operandsItem))!
넵 OperatorItem 요소로 바꿔주어 강제 옵셔널 해제 해주었습니다! 앞으로 지양하겠습니다ㅠㅠ!

2022-06-01 01:06 UTC, ryan-son commented on Calculator/Models/Formula.swift
> +    case emptyError
이름이 짝을 이루어 좋다고 생각해요~

2022-06-01 01:06 UTC, ryan-son commented on Calculator/Models/Formula.swift
> +    case emptyError
이름이 짝을 이루어 좋다고 생각해요~

2022-06-01 01:07 UTC, closed without merging