계산기 [STEP 3] 수꿍
yagom-academy/ios-calculator-app pull request #271
Opened 2022-05-26 12:47 UTC by Jeon-Minsu

안녕하세요, 찰리!! @kcharliek 
미리 말씀드렸던 기한보다, 그리고 이렇게 늦은 시간에 계산기 프로젝트 STEP 3 PR을 드려 사과의 말씀을 전합니다.
STEP3의 기능들은 새로운 함수들보다는 실제 계산기는 어떻게 구현되어 있는지 자꾸 고민해보고,
고민한 기능들을 추가하는 데 있어 시행착오 과정이 생각보다 많은 시간을 잡아먹어 지연 제출하게 되었습니다.
현재 혼자 완성할 수 있는 범위 내에서는 최대한 노력해보았고, 이에 추가적으로 혼자 끙끙 앓기보다는
찰리와 함께 의견을 나누고 싶어 부족한 면이 많지만 PR 드립니다.
마지막 스텝도 잘 부탁드립니다!! 🙇‍♂️🙇

# [STEP 3]

## 고민한점 
### 1. 음수 계산

- 일반적인 계산기는 음수의 값이 입력받았을 때도, 이를 음수로 인식하여 문제없이 계산을 해나갑니다. 하지만, 계산기 프로젝트에서의 계산은 `Operator`열거형 구조의 `calculate` 메서드를 통해 진행됩니다. 여기서 `subtract` 케이스의 `rawValue`를 키보드에 있는 `-`로 입력하면, "1-(-1)"이라는 `input`에 대하여 `subtract` 케이스가 두 번 언급한 것으로 받아들여, 계산을 두 번 실행하고자 하고, 이는 곧 피연산수 부족으로 인하여 오류를 발생시킵니다.
- 이를 해결하기 위하여 처음에는 음수로 입력된 값이면, 일반적인 경우 피연산수의 개수보다 연산자의 개수가 크거나 같을 것이므로, 피연산수의 수가 연산자의 수보다 1개 더 많아질 때까지, 반복문을 실행시켜, 각각의 "+-", "/-", "*-", "--"의 경우에 맞는 동작을 구현해야할까 고민하였습니다.
- 하지만, 더욱 근본적인 측면에 집중한 결과, 빼기의 "-"와, 음수를 의미하는 "-"부호에 대하여 일반적으로는 같다고 생각하나, 컴퓨터에서는 이를 서로 다른 것으로 인식하게 한다면 위의 문제를 해결할 수 있었습니다. 스토리보드에 접근하여 마이너스 연산 버튼의 `currentTitle`을 확인한 결과, 키보드에 있는 "-" 부호와 서로 다르다는 것을 발견하였습니다. 이에 `Operator`열거형 구조의 `subtract` 케이스의 `rawValue`를 `currentTitle`과 같은 부호로 설정하고, 부호전환에 관하여서는 키보드에 있는 "-" 부호를 이용한 결과, 빼기와 음수를 컴퓨터에서 구분하여 인식이 가능해져 음수 연산이 정상적으로 작동하였습니다.

<br>

### 2. stackView 내 subview 삭제

- 메인 스토리 보드에 구현되어 있는 `stackView` 내 두 개의 `subView`를 코드를 통해 제거하고자 하였습니다. 이에 `removeArrangedSubview` 메서드를 통해 해당 뷰들을 제거하였습니다. 최초하면에는 이 서브뷰들이 보이지 않아 제거된 줄 알았으나, 사용자 입력값을 뷰에 올리게 될 때, 계산기 화면의 구석에서 다시 등장하는 것을 확인할 수 있었습니다. 이를 통해 해당 메서드로는 없어진 것처럼 보이나 사실은 없어진게 아닐까 의심을 하게 되었습니다. 이를 바탕으로 뷰 계층구조와 자료들을 검색해본 결과, `removeArrangedSubview` 메서드를 통해서는 배열에서 해당 뷰를 제거할 수는 있지만, 여전히 뷰의 `hierarchy`에는 남아있고, 심지어는 제거된 뷰들의 위치와 크기가 더 이상 스택 뷰에서 관리되지 않는다는 사실을 알 수 있었습니다.
- 그래서 해당 뷰들을 뷰의 `hierarchy`에도 남지 못하도록, 확실하게 제거하고자 `removeFromSuperview` 메서드를 실행하였고, 이를 해결할 수 있었습니다. 추가로, 애플 개발자 문서를 찾아보니 `removeFromSuperview` 메서드 이외에도 뷰의 `isHidden`속성을 `true`로 설정하면 같은 결과를 도출할 수 있음을 알게 되었습니다.
<br>

## 의문점

### 1. 함수 내 guard 문을 별도의 함수로 기능 분리

- `touchNumberButton` 메서드만 살펴보아도 `guard`문이 6개나 쓰였습니다. 물론 옵셔널 바인딩을 위하여 사용한 경우도 있지만, 조건을 설정해주기 위하여 guard문을 사용한 경우도 적지 않았습니다. 이에, 함수의 기능 분리를 위하여, 각각의 guard문을 `touchNumberButton` 내에서 분리하여 별도의 함수 내에 구현하고, 이를 호출만 하는 방식으로 `touchNumberButton` 메서드를 수정해보았습니다. 하지만, 이는 정상적으로 작동하지 않았습니다. 
- 이러한 실패 결과가 나타난 이유를 예를 들어 설명드리자면, 3개의 조건을 만족하였을 때 프로퍼티를 변경하는 `method`라는 함수를 구현해보았습니다. 아래와 같이 하나의 함수 내 3개의 guard문이 있고 값을 변경하는 코드가 존재할 때는 `condition1`을 충족한 이후, 이를 충족하는 상태에서 `condition2`에 접근하고, 또 이를 충족하면 `condition3`에 접근하여, 모두 충족할 시, 값을 변경하는 코드에 접근할 수 있게 됩니다.

```swift
func method() {
    guard condition1 else { return }
    guard condition2 else { return }
    guard condition3 else { return }
    
    someProperty = changedProperty
}
```
<br>

- 하지만 아래와 같이 각각의 `guard`문을 함수로 빼내어 이를 호출하는 방식으로 진행할 시, `firstGuard`문의 조건을 충족한다면, 첫번쨔 조건을 충족했다는 상태에서 `secondGuard()` 함수에 접근하는 것이 아니라, 조건을 충족한 상태가 만료된 채 두번째 `guard`문 함수에 접근하는 것으로 인식하였습니다. 즉, 3가지 조건을 충족한다 하여도, 값을 변경하는 코드에 접근하였을 때의 상태는 그 3가지 조건을 동시에 만족한 상태가 아닌 것입니다. 
```swift
func method() {
    firstGuard()
    secondGuard()
    thirdGuard()
    someProperty = changedProperty
}

func firstGuard() {
    guard condition1 else { return }
}

func secondGuard() {
    guard condition2 else { return }
}

func thirdGuard() {
    guard condition3 else { return }
}

```
<br>

- 이를 바탕으로, 저는 `guard`문을 함수 외부로 빼내기에는 어렵다고 판단이 되는데, 제가 이해한 작동 방식이 옳은 것인지, 그리고 이를 해결할 수 있는 방법이 무엇이 있을지 여쭈어보고 싶습니다.

<br>

### 2. stackView 내 subview로 Label 추가 시 애니메이션

![May-26-2022 20-51-04](https://user-images.githubusercontent.com/99063327/170482942-b1586a97-f5fb-4675-9003-28df8e00cbe7.gif)

- 계산기에서 입력한 지난 연산자와 피연산수는 입력 이후, 스크롤뷰 내 스택뷰에 쌓이는 방식으로 진행하고자 하였습니다. 이에 `Label`의 속성을 생략하면 다음과 같은 코드를 작성할 수 있었습니다.

```swift
private func clearLastInput() {
    lastInput.subviews.forEach { $0.removeFromSuperview() }
}

private func addCalculatorItems() {
	...
    let label = UILabel()
    label.isHidden = true
    lastInput.addArrangedSubview(label)
    UIView.animate(withDuration: 1) {
        label.isHidden = false
	}
	...
}
```
<br>

- 먼저, 스토리보드에서 확인할 수 있는 초기에 설정된 스택뷰를 `clearLastInput` 함수를 통하여 제거하고, 연산자 버튼이 터치될 때마다, 이전까지 입력된 피연산수와 연산자를 스택뷰에 추가하기 위하여, `addCalculatorItems` 함수 내 `addArrangedSubview` 함수를 사용하였습니다. 하지만 이를 작동한 결과는 위의 동적 이미지에서 확인하실 수 있듯이, 처음의 입력값은 왼쪽에서 오른쪽으로 이동하는 것에 비해, 나머지 입력값은 아래에서 위로 이동함을 알 수 있었습니다.
- 지금까지 고민해본 결과, `clearLastInput` 함수로 인하여 스택뷰가 아무것도 없을 때는 왼쪽에서 오른쪽으로 이동하지만, 스택뷰가 하나라도 존재한다면 아래에서 위로 애니메이션이 작동하는 것 같습니다. 현재는 `Label`을 스택뷰 안에 넣어 뷰를 추가하는 방식으로 진행하였는데, 이렇게 진행할 시에는 모든 입력값들이 왼쪽에서 오른쪽으로 이동함을 발견할 수 있었습니다.
- 왜 이러한 문제가 일어나는지 오랜 시간 고민해봐도 마땅한 근거를 발견하지는 못했습니다. 이에 찰리는 위의 문제가 어떤 이유로 일어나는지 알고 계신지 질문드리고 싶습니다.

<br>

### 3. UILabel.text 옵셔널 처리

- Step2의 피드백을 통하여 ??의 사용을 지양하고, 옵셔널 바인딩 방법을 사용해야 함을 배울 수 있었습니다. 이를 바탕으로 Step3를 진행해보았는데, `touchNumberButton` 메서드와 관련하여 `guard` 구문을 통하여 "text = numberInput.text"으로 옵셔널 바인딩을 하여, 여러 조건을 충족하는지 `text`를 통해 확인해보고, 최종적으로 `numberInput.text`의 값을 최신화해주기 위해선 "numberInput.text = text"와 같이 `text`를 다시 넣어주어야 했습니다.
- 이에, 옵셔널 바인딩을 다음의 방법으로 진행하는 것이 옳은지 확신이 들지 않고, 해당 프로퍼티를 계속 이용하고자 하는데, 그 프로퍼티 자체의 네이밍을 사용하면서 옵셔널 추출을 하는 또다른 방식이 있을지 궁금합니다.
<br>

### 4. stackView 화면 하단 자동 이동

```swift
private func goToBottomOfScrollView() {
    scrollView.setContentOffset(CGPoint(x: 0,
                                        y: scrollView.contentSize.height - scrollView.bounds.height),
                                animated: true)
}
```
<br>

- 저는 위의 코드를 `touchOperatorButton` 함수 내에 구현하여 연산자 버튼이 클릭되어, 입력값들이 스택뷰에 올라간 이후, `goToBottomOfScrollView` 함수를 통하여 화면이 아래로 스크롤 되도록 구현해보았습니다. 그러던 중, 문제점을 발견하였는데, `addCalculatorItems` 함수 내에서 "UIView.animate(withDuration: 1) { label.isHidden = false }" 코드가 없으면, 새로운 입력값이 스택뷰에 오를때마다 실시간으로 화면이 아래로 스크롤 되는 것이 아닌, 한박자 늦게 이동되고 있음을 발견하였습니다. 
- `animation`의 유무가 화면 자동 이동에 영향을 미친 것인지, 혹은 화면 자동 이동 코드는 모두 한박자 늦게 이동되고 있었는데, `animation`을 통해 화면이 자동적으로 이동된 것인지 혼란스러워 질문드리고자 합니다.

<animation 적용시>

![May-26-2022 21-25-41](https://user-images.githubusercontent.com/99063327/170487742-ba7a66f9-402e-4a2f-81b8-fed06ec1948d.gif)

<animation 미적용시>

![May-26-2022 21-27-13](https://user-images.githubusercontent.com/99063327/170487905-10dc6b9e-29e4-4303-a19c-86adac5e5d9c.gif)

2022-05-27 01:55 UTC, kcharliek commented
## 궁금하신 점에 대해

1. guard문 분리 관련

``` swift
func check1() -> Bool {}
func check2() -> Bool {}
func check3() -> Bool {}

func doSomething() {
    guard check1(), check2(), check3() else {
        return
    }
    // do something
}
```

은 어떨까요~?

2. 왼쪽에서 오른쪽으로 이동하는 애니메이션 관련

아무것도 입력하지 않았을 때 (왼쪽에 있었을 때), 하나 입력했을 때 (오른쪽으로 이동 완료했을 때)
각 상태에 대해 view debugging으로 frame 확인 해보시겠어요~? 제가 의심하고 있는 건 label이 추가되었을 때 stackView 의 Frame이 변해서 그렇게 될 것 같습니다. 맞다면 autolayout을 다시 설정해야할 것 같네요. 

3. optional binding 관련 ...

numberInput.text 로 분기를 태우기 위해 optional-binding을 하고, numberInput.text 를 갱신하기 위해 numberInput.text = text 로 할당하는 건 당연해보입니다. 어떤 점이 우려되시는지 모르겠는데 더 말씀해주시면 좋겠습니다 ㅎㅎ 

4. 코드를 보고 적겠습니다.

2022-05-27 02:04 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBAction private func touchNumberButton(_ sender: UIButton) {
iOS 개발에서 'touch' 라는 키워드는 그 자체로 Action이 되지 않습니다. touch 라는 단어를 사용하시고 싶다면 
[touchUpInside](https://developer.apple.com/documentation/uikit/uicontrol/event/1618236-touchupinside)와 같은 조금 더 종합적인 상태 표현이 필요해요.

 제가 제안드리는 button의 touchUpInside action에 대한 네이밍은 numberButtonDidTapped() 입니다. 많이들 사용하는 관용적 표현이라 한번 이렇게 적어보시길 권해드리겠습니다.

2022-05-27 02:18 UTC, kcharliek requested changes
모든 메서드 10 줄 이내로 구현하도록 수정해주세요.

2022-05-27 02:18 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBAction private func touchNumberButton(_ sender: UIButton) {
touchNumberButton 쪽 메서드가 많이 길어보입니다.
코드를 보고 한 눈에 모든 로직이 눈에 들어와야합니다.
그러려면 메서드를 많이 쪼개셔서 짧게 짜셔야할거에요.

touchNumberButton 10줄 제한을 드리겠습니다. 위 질문에서 guard 여쭤보신게 이쪽 같기도 하고요. 해결되셨다면 한번 짧게 짜보시길 권해드리겠습니다.

2022-05-27 02:18 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +        var formula = ExpressionParser.parse(from: totalInput)
switch - case 문 별도 메서드로 분리해주세요 . 요건 method분리해야하는 대표적인 코드입니다. 코드 읽다가 갑자기 등장하면 읽는 맥락을 깹니다.

2022-05-27 02:20 UTC, kcharliek commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = input.filter { $0.isNumber == false && $0 != "." && $0 != "-" }.map { String($0) }
filter 조건을 메서드로 분리할 수도 있을 것 같고요. 걸러야하는 문자들 (., -) 를 array로 둔다던지. 잘 정리해서 가독성을 높힐 수 있을 것 같습니다.

지금 코드를 본다면 왜 .과 -를 제외하는지 알기 어렵습니다.

2022-05-27 02:21 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +        let firstTrimmedInput = labelText.replacingOccurrences(of: " ", with: "")
trim method 별도 분리해주세요.

2022-05-27 02:22 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +        let label = UILabel()
label 생성 메서드 분리해주세요 .

2022-05-27 02:22 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let convertedNumberInput = convertNumberInput() else {
guard 부분 메서드 분리해주세요 .

2022-05-27 02:24 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func applyNumberFormatter(_ number : Double) {
이 메서드가 하는 일은 applyNumberFormatter 라기 보다는 
numberInput의 값을 갱신하는 것이 핵심으로 보입니다.
numberFormatter는 이를 도울 뿐이고요.

setNumber(_ number: Double) 정도 제안드립니다.

2022-05-27 02:24 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func removeComma() -> String? {
removeComma 이 메서드 작게 메서드를 쪼개주세요.

2022-05-27 04:07 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBAction private func touchNumberButton(_ sender: UIButton) {
`IBAction` 함수의 경우 `touch`에서 `DidTapped`로 네이밍 수정하였습니다.

2022-05-27 04:16 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +        var formula = ExpressionParser.parse(from: totalInput)
`handleError` 함수를 생성하여 해당 기능을 분리하였습니다.

2022-05-27 05:58 UTC, Jeon-Minsu commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = input.filter { $0.isNumber == false && $0 != "." && $0 != "-" }.map { String($0) }
`componentsByOperators` 함수 내 필터 조건 메서드를 생성하였습니다. `ExpressionParser` 열거형의 `componentsByOperators` 함수의 필터조건을호 `isOperator` 함수를 생성하여 대체해보았습니다. `isOperator` 함수 기능 구현을 위한 `isNumber`, `isNumberSymbol` 함수를 통해 입력값이 숫자이거나 숫자기호일 경우, 연산자가 아님을 판단하는 기능을 구현하였습니다.

2022-05-27 06:36 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +        let firstTrimmedInput = labelText.replacingOccurrences(of: " ", with: "")
`removeWhitespaces` 함수를 생성하여 공백을 제거하는 기능을 구현하였습니다. 또한, `addTrimmedInputToTotalInput` 함수안에 `removeWhitespaces`와 `removeComma`를 호출하여 공백과 콤마를 제거한 값을 totalInput에 추가하는 함수를 구현해보았습니다.

2022-05-27 07:50 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func applyNumberFormatter(_ number : Double) {
`setNumber(_ number: Double)`로 네이밍 수정완료하였습니다!

2022-05-27 19:05 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBAction private func touchNumberButton(_ sender: UIButton) {
`guard` 구문을 포함하여 함수 내 기능을 최대한 분리하여 하나의 함수가 하나의 기능만을 수행하도록 수정해보았습니다.

2022-05-27 19:07 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +        let label = UILabel()
`label` 생성 메서드를 `makeUILabel` 메서드로 기능을 분리하고, 이를 다시 `UILabel` 생성과 `setLabelProperty`로 분리하여 수정해보았습니다.

2022-05-27 19:08 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let convertedNumberInput = convertNumberInput() else {
`addCalculatorItems` 메서드를 `makeUIStackView`와 `addStackView`로 기능을 분리하였습니다.

2022-05-27 19:09 UTC, Jeon-Minsu commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func removeComma() -> String? {
위의 상황을 반영하여 하나의 함수가 하나의 기능만을 수행할 수 있도록 수정을 진행해보았습니다.

2022-05-27 19:22 UTC, Jeon-Minsu commented
### 1. guard문 분리 관련

찰리와의 추가적인 피드백을 통하여 각각의 함수가 어떤 기능을 하는지 직관적으로 파악할 수 있도록, 기능을 명시적으로 구현하였고, 또한, 하나의 함수가 하나의 기능만을 수행할 수 있도록 최대한 기능을 분리하여 코드 수정을 진행하였습니다.

### 2. 왼쪽에서 오른쪽으로 이동하는 애니메이션 관련

이번 스크롤 뷰의 하단 자동 이동 문제를 해결하기 위해서는 `main loop`와 `update cycle`에 대하여 알아둘 필요가 있었습니다. 계산기의 입력값이 스크롤 뷰 내 스택뷰에 오를 때는 `update cycle`에 해당합니다. 이에 `layout`을 재배치 하거나 `view`들을 다시 그리는 작업을 진행하기 위해서 `update cycle`에 자동적으로 호출될 수 있도록 명령을 해야 합니다. 따라서, 저는 `scrollView.layoutIfNeeded()` 코드를 추가하여 업데이트 사이클마다 자동적으로 하단으로 이동할 수 있도록 설정해보았고, 이를 통해 `UILabel`에 불필요한 `animation`을 실행할 필요가 없어졌습니다.

### 3. optional binding 관련 

Nil-Coalescing 사용으로 옵셔널 바인딩 사용에 익숙하지 않아 이를 헷갈려한 것 같습니다. 찰리와의 피드백을 통하여 충분히 이해하였습니다!

이번 STEP3 PR에 대한 궁금증을 많이 해결할 수 있었습니다. 특히 전체 함수를 10줄 이내로 작성하는 연습은 정말 고되었지만, 앞으로의 로직 구성, 코드 구현에 있어 뜻깊은 시간이 되었습니다. 물론 아직도 발전시켜야할 부분들이 많지만, 이번 찰리와의 프로젝트를 통해 많은 것들을 배우고, 성장할 수 있는 시간을 보낼 수 있었습니다. 정말 감사합니다!! 수고 많으셨습니다 🙇‍♂️🙇‍♂️

2022-05-30 03:34 UTC, kcharliek commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func isCommaButtonNotTappedTwice(sender: UIButton, number: String) -> Bool {
isNotXXX 와 같은 Bool Type 메서드들이 보입니다.
일부 개발자들은 분기에 부정형을 넣는 것을 싫어합니다.
부정형 분기는 else 문에서 이중부정이 발생해서 가독성을 떨어뜨리기 때문입니다.
참고해서 긍정형으로 변경해보시길 권해드리겠습니다.

ex) isNotEmpty -> isEmpty

2022-05-30 03:37 UTC, kcharliek approved these changes
아주 고생하셨습니다.
정말 짧게 잘하셨습니다.

2022-05-30 07:52 UTC, merged