계산기 [STEP3] 웡빙
yagom-academy/ios-calculator-app pull request #272
Opened 2022-05-26 14:47 UTC by wongbingg

안녕하세요 @jryoun1  @wongbingg 입니다!! 이번에는 예상 PR 시간 내에 보내지만 여전히 미흡한 점을 남겨두고 있습니다 ..😩
중구난방 한 코드속에서 .. 보기에 불편하신 모든 부분에 대해 듣고 싶습니다! 잘 부탁 드립니다 😊😊

# STEP3

## UML Diagram

![](https://i.imgur.com/t5KwBzo.png)

## 구현사항
- 기존의 "String+Extensions" 에 문자열에서 특정 Character 를 모두 지워주는 함수를 추가 했다.
```swift=
    removeEntire(character: Character) -> String
```  
- 화면의 모든 UI를 연결 해주었다. 
- `NumberFormatter`를 이용하여 숫자의 소숫점 제한과, 세자리 마다 쉼표 설정을 추가했다
- 각 연산자 버튼에 대한 계산을 수행하도록 구현했다 
    - "+","-","×","÷"
        - 버튼 터치시, 입력하던 숫자를 스택으로 올리고 다음 숫자를 받을 수 있도록 구현했다.
        - 만약 현재 `screenLabel`이 0이라면 부호만 바뀌도록 구현했다.
        - 나누기 수행 시 0으로 나눈다면 NaN 오류를 출력하게 만들었다.
    - "="
        - 버튼 터치시, 스택에 쌓여있는 숫자들을 읽어와 `ExpressionParser()`에 넣어줬다.
        - 계산 결과값이 `screenLabel`에 표시되도록 했다. 
        - 만약 현재 `screenLabel`이 "0" 이거나 "결과값"이어서 `currentOperatorLabel` 이 비어있다면 아무것도 수행하지 않도록 구현했다.
- 기능버튼("AC","CE","+/-") 에 대한 수행을 구현했다.
    - "AC"
        - `historyStackView` 에 쌓여있는 스택들을 `removeAllIn()`함수를 이용해 모두 제거 해주었다.
    - "CE"
        - 현재 `screenLabel` 에 올려져 있는 text를 0으로 변경 해주었다.
    - "+/-"
        - 현재 `screenLabel` 에 올려져 있는 text에 -1을 곱해주었다
        - 현재값이 0이라면 수행되지 않도록 구현했다.
- historyStackView
    - `goToBottomOfScrollView()`
        - 스택이 추가될 때 마다 최하단으로 자동 스크롤 되도록 구현했다.

## 수행 중 버그 기록
- 빼기 연산 오류
    - 스토리보드상 "-" 버튼과 `Operator` 에 subtract 케이스의 rawValue "-" 와 서로 다른 문자였다.. 
- "=" 버튼 터치 이후 결과값으로 새로운 계산수행 불가
    - `generateTextData()` 로직에서 기존에는 `historyStackView` 의 모든 값을 읽어오는 역할을 했어서 이전 값들과의 결합상의 오류가 있었는데, 값을 읽어오기 시작하는 index를 설정하기 위해 `calculateStackCount` 라는 프로퍼티를 만들어 이전에 계산했던 스택들의 개수를 세어 그 다음 계산에서는 이후부터 계산하도록 구현했다.
- 스토리보드에 기본으로 존재하는 Stack
    - scrollView 안에 존재하는 stack을 제거하니 constraint 오류가 발생, 이를 스토리보드 상에서 제거할 수 없으므로 코드로 viewDidLoad에서 제거 해주었다. 
    - 이유는 위의 연속적인 계산을 위한 index설정을 해주었는데, 이 기본 스택 때문에 생길 오류를 방지하기 위해서이다
    - numberFormatter를 이용해 세자리마다 쉼표 표시를 하니, 스택에서 숫자값을 읽어오는 로직에서 오류가 발생, 쉼표가 포함되어 있어 Double로 형변환이 되지 않았다. 또한 기능버튼 "+/-" 에서도 Double로 형변환에 오류를 뿜었다. 이를 해결하기 위해 "String+Extensions" 에서 `removeEntire()` 를 하나 만들어주어 문자열에서 특정문자를 모두 제거해주는 로직을 작성했다. 

## 구현 화면

----< **간단한 사칙연산** >------------------------<**긴 사칙연산**>--------------------<**쉼표와 소수점 처리**>  

<img src="https://i.imgur.com/hug9Vkw.gif" width="200" height="400"/><img src="https://i.imgur.com/xBp50Dd.png" width="25" height="400"/><img src="https://i.imgur.com/tbweDEl.gif" width="200" height="400"/><img src="https://i.imgur.com/xBp50Dd.png" width="25" height="400"/><img src="https://i.imgur.com/7gkHoq4.gif" width="200" height="400"/>  
  
    
    
# 

---< **기능버튼 "CE", "+/-"** >-----------------<**오류처리 NaN**>--------------------<**계산내역 스크롤**>

<img src="https://i.imgur.com/c7G71QF.gif" width="200" height="400"/><img src="https://i.imgur.com/xBp50Dd.png" width="25" height="400"/><img src="https://i.imgur.com/JirfoPe.gif" width="200" height="400"/><img src="https://i.imgur.com/xBp50Dd.png" width="25" height="400"/><img src="https://i.imgur.com/iXxQRBa.gif" width="200" height="400"/>

## 고민한 점 & 궁금한 점

- 어떻게든 구현은 하게 되었지만, 시간이 많이 없어 촉박하게 진행했던 것 같습니다. 코드의 가독성 면이나 구조나 여러가지 문제점들이 많을 것 같습니다. 보기 불편하신 부분, 이해가 되지 않는 부분에 대해서 말씀 해주시면 감사하겠습니다
- "Double+Extensions" 에 추가해주려 했던 소수점 자리제한과 세자리마다 쉼표 표시 기능이 이미 존재하는 NumberFormatter로 구현이 가능하여 이번에도 마찬가지로 "Double+Extensions"이 비었습니다. 하하..
- CalculateItem 프로토콜도 마찬가지로 활용방안에 대해 생각이 나지 않아 비워둔 상태입니다.  
- 기능구현에 중점을 두고 코드를 휘갈겨 놓고 그 뒤에 코드를 정리하는 방식을 이용했습니다. 아직 코드설계에 대한 개념 부족과 경험 부족으로 이런 현상이 일어나는 것 같습니다. 정리한 것이 지금 코드인데 더 정리할 수 있는 부분을 찾지 못했습니다 어떤 부분이 있을지 궁금합니다!

2022-05-26 16:55 UTC, jryoun1 requested changes
@wongbingg step3까지 정말 잘 구현해주셨네요 👏
코드도 깔끔하고 가독성 있게 작성해주셔서 정말 읽기 편했습니다 💯 👍🏻
readme와 commit도 깔끔하게 잘 작성해주셨네요 🙌🏻
몇 가지 코멘트 남겼습니다! 확인부탁드려요~ 


### 고민한점에 대한 답변
Double extension, CalculateItem protocol에 대해서 활용방안이 없다면 꼭 구현할 필요는 없다고 봅니다. 어떤 의도로 위의 사항들을 필수로 만들어놓은 기획자랑 이야기 해보는 것도 하나의 방법이라고 생각합니다 🙂

### 개선할만한 사항

이전 계산 영역을 스크롤할 때 아래 사진과 같이 scroll Indicator (스크롤바)가 보이는데 코드나 스토리보드를 통해서 제거하면 앱을 사용하는데 더 깔끔할 것 같습니다 🙏🏻

<img src="https://user-images.githubusercontent.com/45090197/170525755-7c247d30-8354-4e54-82e6-692ff4cfc6bf.png" width="200" height="400"/>

### 버그
1. 소수점을 계산할 때 아래 사진과 같이 0.555가 아니라 .555로 나오고 있습니다 🚨 
<img src="https://user-images.githubusercontent.com/45090197/170534330-a1584f2f-1160-419d-92eb-3e8ce398c205.png" width="200" height="400"/>

2. 숫자는 최대 20자까지 표현이 되어야하는데 20자를 넘어서까지도 표현이 되고 있습니다 🚨
<img src="https://user-images.githubusercontent.com/45090197/170535248-acfb5a34-370f-4afe-88cc-9b3b9740bae1.png" width="200" height="400"/>

3. 계산에 오류가 있는 것 같습니다. 아래 사진을 참고해주세요!
<img src="https://user-images.githubusercontent.com/45090197/170535443-6abd2a18-78df-4ae8-a84a-39527e928c66.png" width="200" height="400"/>

2022-05-26 16:55 UTC, jryoun1 commented on Calculator/Calculator/Extensions/String+Extensions.swift
> +            self.remove(at: firstIndex(of: character) ?? self.endIndex)
nil coalescing operator 를 사용해 endIndex를 지우는 것보다
확실하게 firstIndex(of: character)가 없다면 종료하는 것이 낫지 않을까요? 🤔

2022-05-26 16:55 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +                    textData = textData.removeEntire(character: ",")
`,` 가 있는 경우까지도 고려하셨군요! 아주 좋습니다 👏

2022-05-26 16:55 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +        UIView.animate(withDuration: 0.2) {
크~ 애니메이션까지 주셨네요 💯 👍🏻

2022-05-26 16:55 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +        if currentOperatorLabel?.text == "" {
if 보다는 guard가 더 좋아보입니다! 
if 와 guard를 사용하는 기준이 있을까요? 🙋‍♂️

2022-05-26 16:55 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +        if currentOperatorLabel?.text == "" {
`""` 빈문자열이 코드에서 여러번 하드코딩 되는데 상수로 선언되어있으면 휴먼에러를 방지할 수 있을 것 같습니다!

2022-05-26 16:55 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +            if ((error as? FormulaError) != nil) {
지난번 PR에서 Error들을 만약 하나의 CalculatorError: Error 이런식으로 계산기에서 발생할 수 있는 에러들을 모아둔다면, error를 switch case를 통해서 작성할 수도 있을 것 같습니다.
```swift
enum CalculatorError: Error {
    case emptyStack
    case notEnoughInput
    case dividedByZero
}

// ...

   } catch let error as CalculatorError {
            switch error {
            case .dividedByZero:
                // 에러처리
            case .notEnoughInput:
                // 에러처리
            case .emptyStack:
                // 에러처리
            }
    } catch {   }
```

또한 정의되지 않은 Error가 발생한 것에 대해서 처리는 하지 않아도 
어떤 에러인지 파악은 할 수 있도록 print를 해줄 수는 있을 것 같습니다.

2022-05-26 16:55 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +            var operandText = operand
`operandText` 도 상수로 선언할 수 있을 것 같습니다 🙏🏻

2022-05-26 22:10 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var screenLabel: UILabel?
이전 프로젝트 때 리뷰어 분께서 @IBOutlet변수 도 한번 옵셔널로 선언해보라는 지시가 있어서 그 때의 기억으로 쓴 것 같습니다. 강제 언래핑을 사용했을 때 오류가 나는 경우는 UI객체가 생성되기 전 즉, viewDidLoad() 가 되기 전에  @IBOutlet변수를 사용하려 하면 오류가 발생 합니다. 이번 프로젝트에는 그럴 일이 없겠지만 좋은 습관을 만들어 보고자 작성해보았습니다😊 보통은 무난하게 강제언래핑을 사용하는 맞을까요? 그리고 이렇게 @IBOutlet변수를 옵셔널 처리하게 되면 같이 협업하는 동료가 봤을 때 헷갈리게 될까요? 궁금합니다

2022-05-26 22:13 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView?
계산 내역을 보여주는 역할을 하므로 스택과 마찬가지로 history라는 이름을 붙여 주었습니다 ! 😊

2022-05-26 22:15 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var screenLabel: UILabel?
IBOutlet 변수들도 외부에서 접근하면 안되므로 private 접근제어를 해주었습니다 😊

2022-05-26 22:20 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBAction func operandButtonDidTapped(_ sender: UIButton) {
이 부분도 마찬가지로 외부에서 접근될 일이 없다고 생각되어 private 접근제어를 해 주었습니다! 😊😊

2022-05-26 22:34 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +extension ViewController {
코드의 구분감을 주기 위해 extension을 사용하였는데 이번경우와 같이 메서드가 적은 경우는 말씀 해주신 대로 주석을 이용하여 구분해주는 것이 더 좋을 것이라 생각되어 이 부분 수정하였습니다 !! 😊😊👍👍

2022-05-26 22:40 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        stack.arrangedSubviews.forEach { stack.removeArrangedSubview($0) ; $0.isHidden = true }
사실 이 부분은 사용해 보지 않은 기능을 써보자는 취지에서 작성하게 되었습니다. 줄바꿈의 기능으로 알고 있는데  말씀해주신 Swift.org 문서의 대부분의 예시가 그렇다면 쓰지 않는 편이 좋을 것 같다는 생각이 듭니다 😂 그래서 수정 하였습니다 ☺️

2022-05-26 22:48 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        operatorLabel.font = UIFont.preferredFont(forTextStyle: .title3)
반복되는 부분을 캐치하지 못했군요! 😂 이 부분 마찬가지로 수정 하였습니다 ☺️☺️

2022-05-26 22:48 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        add(generateStackView(), to: historyStackView)
감사합니다!! 🫡🫡

2022-05-26 22:50 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +                                               y: scrollView.contentSize.height - scrollView.bounds.height,
오 정말 유용한 기능입니다 !! 한방에 정렬이 해결 되었습니다! 앞으로 계속 사용할 것 같습니다 감사합니다 ㅎㅎ 😊😊

2022-05-26 22:51 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        scrollView.scrollRectToVisible(CGRect(x: 0,
감사합니다! ㅎㅎ 디테일에 항상 신경을 써야겠군요 🧐🧐

2022-05-27 01:29 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        var textData: String = ""
처음에 textData라는 String타입의 변수만 지정해주고 로직을 실행 했는데 변수가 초기화가 되지 않은 상태로 closure에서 capture를 하려 하면, 오류가 났었습니다! 그래서 그대로 빈 스트링 "" 를 통해 초기화를 시켜주었는데 이로인해 스위프트의 타입추론이 가능해져 String이라는 타입 어노테이션이 필요가 없어지게 되었다는 것을 인지하지 못한 것 같습니다 ! 다른 곳 과의 통일을 위해 타입 어노테이션을 지웠습니다 ☺️

2022-05-27 01:44 UTC, wongbingg commented on Calculator/Calculator/Extensions/String+Extensions.swift
> +
전체적인 컨벤션이 뒤죽박죽이 되어있는 것 같습니다 🥲 loop문은 개행 한번으로 구분 해주자는 저만의 컨벤션이 있었는데 어느 곳은 개행이 없는 것이 가독성이 좋고 어느 곳은 개행이 있는 것이 보기 좋았습니다 . 이럴 경우 컨벤션을 지켜 가독성을 포기해야 할까요 ? 아니면 가독성을 우선시하고 컨벤션을 지키지 않는 것이 좋을까요?

2022-05-27 02:20 UTC, wongbingg commented on Calculator/Calculator/Extensions/String+Extensions.swift
> +            self.remove(at: firstIndex(of: character) ?? self.endIndex)
함수시작 첫 줄에 guard let 을 통해 firstIndex(of: character) 를 옵셔널 바인딩 처리 해주었었는데 여기서 문제는 while 루프를 한번 돌고 난 뒤, 존재하는 다음 쉼표에 대한 새로운 인덱스값을 가져와야 하는데 처음에 바인딩 시켜준 인덱스 값을 그대로 가지고 있어 나머지 쉼표가 사라질 때 까지 같은 인덱스 값을 계속 제거하는 현상이 일어났습니다. 그래서 guard 문을 쓸 수 없겠구나 생각했는데 while 문 안에 guard let 을 사용하니 해결이 되었습니다 ! 함수의 기본 형태에서 반환값도 제거해 스스로를 수정하는 형태의 함수로 변경했습니다

2022-05-27 02:25 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        if currentOperatorLabel?.text == "" {
다시 보니 guard 문이 더 깔끔하게 적용될 거 같아 수정하였습니다 ㅎㅎ 조건문에는 아직 guard 문 보다는 if 문이 익숙하여 먼저 사용했던 것 같습니다. 이런 조건으로 걸러주는 내용, 조건이 만족되지 않을 시 빠르게 종료시켜줘야 할 경우는 guard 문 사용이 더 유용할 것 같습니다 ☺️

2022-05-27 02:29 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        if currentOperatorLabel?.text == "" {
숙지하여 빈 문자열을 emptyText라는 상수에 선언 해주고 이를 활용 해주었습니다 ☺️

2022-05-27 02:58 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +            var operandText = operand
removeEntire() 함수가 반환값이 사라지고 스스로를 변경하도록 수정했기 때문에 operandText 가 그대로 변수로 있어야 될 것 같습니다 😔😔

2022-05-27 03:11 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +            if ((error as? FormulaError) != nil) {
이 부분 숙지하여 적용 하였습니다. 저번에 말씀하신 부분에 대해 이해를 잘 못했던 것 같습니다 ㅎㅎ 에러 타입을 3개로 가져가니 핸들링에서 번거로워져서, 제시 해주신 대로 이렇게 하나로 묶어서 처리하는 편이 좋을 것 같습니다 !! 🤩🤩

2022-05-27 06:03 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +                    textData = textData.removeEntire(character: ",")
감사합니다 !!  🤩🤩

2022-05-27 06:03 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        UIView.animate(withDuration: 0.2) {
감사합니다 !!  🤩🤩

2022-05-27 06:04 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var formula: Formula?
감사합니다 !!  🤩🤩

2022-05-28 09:26 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var screenLabel: UILabel?
아하 그런 의도가 있었군요 좋습니다 👏 

옵셔널로 하는가 아니면 암시적 언래핑을 하는지에 대한 관점은 안전성과 편리성에 대한 선택일 것 같습니다.
안전한 것을 원한다면 옵셔널로 선언하고 매번 언래핑을 통해서 확인할 수 있고, 반면 암시적 언래핑을 사용한다면 항상 nil이 아닐 것이라는 보장하고 암시적 언래핑을 사용했기 때문에 사용할 때 편하게 값을 사용할 수 있을 것 입니다.
다만 IBOutlet의 경우에는 IBOutlet으로 선언된 view component가 nil인 것은 명백한 에러일 가능성이 높고, 이는 잘못된 시나리오로서 발생하는 에러가 아닐 가능성이 높습니다. 즉, IBOutlet 객체가 nil인 경우에는 app이 아예 크래시가 나면서 수정이 되어야할 필요가 있으며, 만약 IBOutlet 객체를 사용하지 않을 것이라면 선언을 하지 않도록 하기 위해서 대부분은 강제 언래핑을 하는 것이 아닐까라는 생각이 드네요 ㅎㅎ 

말씀하신 것처럼 viewDidLoad()되기 전에 IBOutlet 변수에 접근은 불가능하기 때문에 상황에 따라서 고려해서 사용하시면 좋을 것 같습니다🙏🏻 IBOutlet 변수를 암시적 언래핑하는 것에 대한 아티클들이 많이 있으니 한 번 찾아보시는 것도 좋을 것 같아요👍🏻

2022-05-28 09:29 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +        var textData: String = ""
타입 어노테이션 자체가 문제가 있는 것은 아니지만 특별한 이유가 있는 것이 아니라면 프로젝트 내부에서 전반적으로 통일되는 것이 좋을 것 같아서 말씀드렸습니다.
여기서 특별한 이유는 예를 들어 어떤 타입은 CGFloat이어야 하는데 초기 값을 Int 값으로 설정하는 경우에는 컴파일러가 이 값이 Int인지, CGFloat인지 알 수 없기 때문에 명시해주기 위해서 아래와 같이 명시해줄 수 있을 것 같네요.
```swift
let value: CGFloat = 8
```

2022-05-28 09:31 UTC, jryoun1 commented on Calculator/Calculator/Extensions/String+Extensions.swift
> +
가독성이라는 것은 개인적인 가독성도 중요하지만, 다른 사람이 코드를 읽는다고 생각했을 때의 가독성이 좀 더 중요하다고 생각됩니다.
다른 사람이 웡빙의 코드를 처음 볼 때 `loop문은 개행 한번으로 구분 해주자` 라는 웡빙의 의도를 빠르게 알아챌 수 있을까요?! 🤔 
그런 관점에서는 통일되는 것이 중요할 것 같네요! 

물론 이러한 컨벤션은 협업하는 사람들끼리 정해졌다면 그걸 따르는 것이 최우선입니다! ㅎㅎ

2022-05-28 09:53 UTC, jryoun1 approved these changes
step3까지 2주동안 정말 고생하셨습니다! 
readme도 잘 정리해주시고, 열심히 고민하신 부분들이 코드에 녹아있던 것 같아서 좋았던 것 같네요 👍🏻

답변해주신 코멘트에 답글들과 수정해주신 부분에 코멘트 몇가지만 남겼습니다~ ㅎㅎ
수정해주신 에러부분들도 확인했습니다 👍🏻

4번에 대한 답변은 [이 글](https://woongsios.tistory.com/34)을 참고해보시면 좋을 것 같네요! 
그럼 수고하셨습니다 🙇🏻‍♂️

2022-05-28 09:53 UTC, jryoun1 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func setAttribute(to label: UILabel) {
공통되는 부분을 함수로 빼주셨네요 👍🏻
가능하다면 UILabel 자체를 extension하고 매개변수로는 fontStyle, textColor를 받는다면 
물론 여기는 vc가 하나지만 확장된다면 다른 vc에서도 해당 함수를 사용할 수 있겠네요!

2022-05-28 09:53 UTC, jryoun1 commented on Calculator/Calculator/Errors/CalculatorError.swift
> +enum CalculatorError: Error {
계산기에서 발생할 수 있는 에러를 한개의 에러타입으로 합쳐주셨네요 깔끔하네요 ㅎㅎ 

다만 꼭 모든 에러들을 하나로 만들 필요는 없습니다! 
예를 들어 네트워크 통신을 하는 앱이 있다면 해당 앱은 
`네트워크 통신시 발생하는 에러`, `해당 앱이 logic적으로 발생하는 에러` 이런식으로 분류는 가능할 것 같습니다! 

앞으로 다른 프로젝트를 하면서 어떻게 에러를 묶을지도 같이 고민해보시면 좋을 것 같습니다 🙏🏻

2022-05-28 09:53 UTC, jryoun1 commented on Calculator/Calculator/Extensions/String+Extensions.swift
> +            guard let indexOfCharacter = firstIndex(of: character) else { return }
👍🏻

2022-05-28 09:53 UTC, merged

2022-05-29 01:08 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var screenLabel: UILabel?
좋은 정보 감사합니다 ! 🤩🤩

2022-05-29 01:11 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        var textData: String = ""
이 부분도 컨벤션으로 적용 해야겠군요 ! 감사합니다 ㅎㅎ 🤩🤩

2022-05-29 01:14 UTC, wongbingg commented on Calculator/Calculator/Extensions/String+Extensions.swift
> +
전반적인 이해가 되었습니다! 감사합니다 ㅎㅎ

2022-05-29 01:17 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func setAttribute(to label: UILabel) {
확장성을 고려 해보면 말씀해주신 방법이 훨씬 좋은 방법이 될 것 같습니다! 큰 그림을 보도록 시야를 넓혀야겠군요!!👍