계산기 [STEP 3] Bonf
yagom-academy/ios-calculator-app pull request #276
Opened 2022-05-27 05:20 UTC by apwierk2451

안녕하세요 찰리 @kcharliek 계산기 프로젝트 STEP3 PR보내드립니다. 예상보다 일찍 PR 드립니다. 이 이상은 찰리의 도움을 받는 게 나을 듯 싶어서 보내드립니다. 편하신 시간에 확인 부탁드립니다. 코드가 많이 지저분합니다. 마구 마구 남겨주세요..

## 1. UML 작성
![](https://velog.velcdn.com/images/apwierk2451/post/83c045bc-06ad-4f80-9c6a-23d11cb9b7ec/image.png)
## 2. 키워드
- ScrollView
- StackView
- addArrangeSubView
- bounds - 스크롤 위치
## 3. 문제 / 해결
- NumberFormatter 사용하면서 반점이 들어가 계산에 문제가 생겼다. scrollView로 값이 들어갈 때 반점을 빼는 방법으로 해결하였다.
- 기존 스크롤뷰-스택뷰-레이블 안에 값을 직접 넣어주는 방식으로 만들었다. 기존에 스택뷰가 2개인데 2개 이상일 경우 레이블과 스택뷰를 만들어주는 방식으로 만들었다가 삭제하고 다시 만드는 과정에서 문제(스택뷰의 개수가 맞지 않음)가 발생했다. 기존에 있던 스택뷰를 모두 지워주고 연산자를 누를 때마다 레이블, 스택뷰를 새로 만드는 방법으로 해결하였다.
- UILable.text에 값을 추가하려고 += 연산자를 이용하려는데 오류가 발생하였다. 옵셔널 값에는 += 연산을 할 수 없다는 것을 알게되었다. 새로운 상수에 값을 넣고 UILabel.text를 초기화 해주는 방식으로 해결하였다.
- UILable.text에 값들이 옵셔널 값으로 나온다. UIView.text 값 들은 !로 강제 언래핑 해주었다.

## 4. 조언 받고 싶은 부분
- ScrollView Offset값 주는 과정에서 마지막 연산 부분이 안올라와서 확인해보니 27-8정도의 크기 차이가 있었습니다. 그래서 임의적으로 27 값을 더 해주긴 했는데 왜 값이 남는지 모르겠습니다.
```swift
let bottomOffset = CGPoint(x: 0, y: scrollView.contentSize.height - scrollView.bounds.size.height + 27)
            scrollView.setContentOffset(bottomOffset, animated: true)
```

- step2에서 만들어 놓은 에러 처리에 대한 에러 처리를 어떻게 주어야 할 지 모르겠어서 DevideZero말고는 딱히 다른 처리를 해주지 못했습니다. 어떤 방식으로 처리하는게 좋을지 조언 받고 싶습니다.

## 5. 프로퍼티, 메서드 설명
currentValue : 현재 입력 중인 연산자와 숫자
defaultStackView : 기존에 만들어져있는 Label 2개를 담고 있는 스택뷰 -> viewDidLoad 에서 삭제 후 진행
expressionView : ScrollView 내부의 스택뷰
inpuedStack : 새로 만든 스택들을 저장하는 Array
NumberOfFormula : = 누르기 전 총 연산 수
scrollView : scrollView
totalFormula : 총 연산식 String

addStackView() : stackView 만드는 메소드
AlertErrorEvent() : 에러 경우 백그라운드 경고 알림
changeFormat() : NumberFormatter 이용하여 형식을 맞춰주는 메소드
createLabel() : createLabel
creaStackVeiw() : creaStackVeiw
isDouble() : 소수인지 아닌지 알려주는 메소드
removeZeroOfDouble() : 소수일 경우 소수 점 뒤에 필요없는 0 제거
setCalculator() : 초기 설정으로 만드는 메소드

2022-05-27 07:55 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet private var currentValue: [UILabel]!
property 순서 맞춰졌으면합니다.

1. IBOutlet
2. internal property
3. private property 

순서가 대략적인 업계 표준입니다.

2022-05-27 07:59 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction private func tappedNumbers(_ sender: UIButton) {
numberButtonDidTapped() 정도의 네이밍 제안드립니다.

tappedNumbers 또한 틀렸다고 느끼지는 않습니다만, 많은 분들이 사용하는 스타일은 아니어서 말씀드립니다.

2022-05-27 08:19 UTC, kcharliek requested changes

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet private var currentValue: [UILabel]!
currentValue가 UILabel Array라는 문맥이 잘 이해되지 않습니다.

current 라는 단어는, currentLocation 과 같이 현재 상태를 표현할 때 쓰는데요. IBOutlet은 '현재' 라는 상태가 있을 수 있을까 싶네요.

그리고 네이밍 규칙 첫 번쨰는 UILabel Type 이라면 -label, UIView Type이라면 -view, CGRect라면 -frame 과 같이 type을 유추할 수 있어야합니다.
Value 라는 단어는 타입을 유추하기 어렵기 때문에 지양해야합니다. 물론 예외는 있습니다만. 지금은 아니라고 생각해요.

새로운 이름은 xxxLabels 정도 제안드립니다. current를 꼭 써야할지 다시 고민해주세요 .

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet private weak var expressionView: UIStackView!
UIStackView Type이라면 xxxStackView 였으면 합니다.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private var inputedStack: [UIStackView]!
네이밍 수정 바랍니다.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private var NumberOfFormula = 1
swift 변수는 소문자 시작을 원칙으로합니다.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private var totalFormula: String = ""
Fomula Type이 이미 있기 때문에, XXXFomula 라고 이름을 지으면 Fomula Type인가 하고 헷갈릴 것 같습니다. 다른 이름 고민 바랍니다.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet private var defaultStackView: [UIStackView]!
array는 복수 s를 붙여주세요.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        guard value == "0" || value == "NAN" || value == "-0" else {
` guard value == "0" || value == "NAN" || value == "-0" else `
가 무엇을 검사하는걸까요.

guard checkInvalidValue() else {
   return
}

이런 식으로 의미를 부여하면 가독성이 더 좋아질 것입니다.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +              var value = currentValue[1].text else {
이 코드를 처음 본 사람은  currentValue[1] 가 무엇을(어떤 Label을) 의미하는지 알기 어렵습니다.

index 로 접근하고싶다면. computedProperty를 만들어서 의미를 달아주세요.

ex) var plusLabel: UILabel { currentValue[1] }

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        let isDot = isDouble(value)
`값이 Double이면 Dot이다`

라는 문맥이 이해되지 않습니다.

네이밍 다시 고민 바랍니다.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        let value = formattableValue.filter { $0 != ","}
value 라는 이름이 많이 쓰인 것 같습니다.

value의 의미가 메서드에 담겼다던지 명확한 상황에서 써도 괜찮은 단어입니다만, 그 value가 무엇을 의미하는지 써주는 것이 좋습니다.

이번에는 모든 value에 의미를 붙여서 리네이밍 해보셨으면 합니다.

2022-05-27 08:19 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        guard currentValue[1].text != "NAN" else { return }
Method가 깁니다. 메서드는 10~15줄 내외가 좋습니다.

동작하는 건 만큼 중요한 건 읽기 좋아야 한다는 점입니다.

의미 단위로 메서드로 쪼개서 짧게 만들어주세요.

2022-05-27 08:28 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private func createStackView(_ UILabel: [UILabel]) -> UIStackView {
변수는 소문자로 시작해야합니다.
특히나 Type 이름과 겹치는 일은 없어야합니다.

UILabel -> labels 정도 제안드립니다.

2022-05-27 08:28 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private func isDouble(_ value: String) -> Bool {
함수 명이 isDouble인데 Double 형인지 검사하지 않고
. 을 가지고 있는지를 확인하고있네요.

hasDot 정도 이름 제안드립니다.

2022-05-27 08:28 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.5) {
DispatchQueue.main.async가 왜 들어갔을까요 .

2022-05-27 08:28 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private func setCalculator(_ inputValue: String) {
setXXX는 XXX에 값을 할당하는 setter 처럼 읽힙니다.

그래서 setCalculator 는 calculator 객체를 할당하는 것 처럼 읽히고, 파라미터가 calculator: Calculator여야할 것 같습니다.

문맥상 .. label을 갱신해주는 것 같은데요.

setLabelText(_ text: String) 정도 제안드립니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private func setCalculator(_ inputValue: String) {
setLabelText(_ text: String) 로 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.5) {
불필요하다 판단하여 제거하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private func isDouble(_ value: String) -> Bool {
hasDot으로 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        guard currentValue[1].text != "NAN" else { return }
최대한 메서드를 의미별로 쪼개서 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        let value = formattableValue.filter { $0 != ","}
네이밍 너무 어렵네요..ㅠ 수정하였지만 눈에 밟히는 네이밍 꼭 짚어주세요...

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        let isDot = isDouble(value)
hasDot으로 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +              var value = currentValue[1].text else {
최대한 의미부여하여 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        guard value == "0" || value == "NAN" || value == "-0" else {
checkInvalidValue 메서드를 만들어 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private var totalFormula: String = ""
totalCalculation으로 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private var NumberOfFormula = 1
넵 ! 실수로 대문자가 들어갔네요

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet private weak var expressionView: UIStackView!
createdStackViews로 수정하였습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet private var currentValue: [UILabel]!
흠.. 네이밍은 아직도 너무 어렵군요.. ㅠ 
current를 지우고 valueLabels로 변경하였습니다. value가 어떤 value를 나타내는지 유추하기 어려울 듯 싶으나 더 좋은 아이디어가 잘 떠오르지 않네요..

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction private func tappedNumbers(_ sender: UIButton) {
앞으로 버튼 액션 메서드의 네이밍 템플릿을 맞추는 습관을 갖겠습니다.

2022-05-29 15:11 UTC, apwierk2451 commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet private var currentValue: [UILabel]!
좋은 정보 감사합니다. 
알려주신 프로퍼티 순서대로 정렬하였습니다.

2022-05-30 03:26 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        guard valueLabels[1].text != "NAN" else { return }
``` swift
guard 검사() else {
    return 예외처리()
}
실행()
```
위 operatorButtonDidTapped 를 포함한 많은 코드에서 이런 꼴을 만족시킬 수 있을 것 같은데요.
지금 코드에서 모든 검사를 하나로 모으로, 결국 무엇을 처리하고싶은지 하나의 메서드로 모으고 이런 식으로 수정해보면 좋겠습니다.
정말 4줄 코드가 가능해질거에요. 가독성도 좋아지고요.

2022-05-30 03:28 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +        } else if changeValue == "CE" {
AC, CE, NAN 등과 같은 상수들이 보이는데요.
아무래도 오타가 날 수도 있고요. 관리의 용이성을 위해
```
enum Constant {
    static let nan: String = "NAN"
    static let ac: String = "AC"
}
```

이런 식으로 상수로 정의해서 다룰 수 있을 것 같습니다. 
호출할 때는 Constant.nan 이런식으로 하고요.

2022-05-30 03:29 UTC, kcharliek commented on Calculator/Scene/Calculator/Controller/CalculatorViewController.swift
> +    private var numberOfCalculation = 1
저는 가능한 Type 표현을 하는 것을 선호합니다.
실제로 값이 1이더라도, 1을 표현할 수 있는 타입이 정말 많거든요.
iOS 개발자라면 당연히 Int 타입인 것을 알겠지만, 명시적인 것도 꽤 좋습니다.

2022-05-30 03:30 UTC, kcharliek approved these changes
전반적으로 코드가 많~~이 깔끔해졌다고 느낍니다.

추가 코멘트는 참고만 부탁드리고, 다음 과제에서 적용시켜보시길 바라겠습니다.

고생하셨습니다 :)

2022-05-30 07:52 UTC, merged