계산기 [STEP 3] BaekGom
yagom-academy/ios-calculator-app pull request #277
Opened 2022-05-27 06:52 UTC by Baek-Gom-95

안녕하세요 쿠마! @leejun6694 계산기 STEP23첫 PR 보내드립니다 처음하는 부분이 많다보니 늦었습니다! 잘부탁드립니다! 😊

# [STEP 3] 기능 및 코드 설명 🙂
- clearFormulaAndSign: 계산기의 모든 연산과 계산식 기호를 초기화 시켜줍니다
- InputNumber: 계산기의 번호판을 눌렀을때 조건값에 따라 숫자처리를 해줍니다
- InputDecimalPoint: 계산기의 '.' 버튼 처리를 해줍니다
- calculateFormula: '=' 버튼을 눌렀을때 저장되어있던 계산식을 최종처리 해줍니다
- InputSign: 연산기호 '+','-','÷','×' 버튼을 눌렀을때 처리를 해줍니다
- removeAll: AC 버튼을 눌렀을때 clearFormulaAndSign() 메소드를 호출해 계산기를 초기화 해줍니다
- clearEntity: CE 버튼을 눌렀을때 처리를 해줍니다
- changeSign: ⁺⁄₋ 버튼을 눌렀을때 현재 입력한 숫자의 부호를 변환합니다
- numberFormatter: 매개변수로 받아온 숫자를 .decimal로 변경후 반환해줍니다
- createStackView: 새로운 스택뷰와 레이블을 생성한 스택뷰에 넣어주고 스택뷰를 반환해줍니다
- scrollSetting: 스택뷰가 추가되면 스크롤뷰가 추가된 스택뷰의 크기만큼 viewPort 설정해줍니다

# [STEP 3] 고민한점 및 해결방안 🤔
### 고민한점
### 스크롤뷰 조정:
- 스크롤뷰가 계산식이 추가될때마다 layout을 설정해줘야되는데 코드로 해줘야하는지 아니면 처음부터 scroll뷰를 늘려놓을지 고민하다
동기들에게 질문하여 해결하였습니다
### 계산식 추가:
- 숫자가 0이 아닌경우 연산기호 버튼을 누르면 숫자가 추가되어야하는데 저장을 어떻게 할지 고민했습니다 
### 최종계산:
- 최종계산식을 넘길때 빈칸을 기준으로 넘겨야하는데 어떻게할지 고민했습니다
### '.','0' 이 입력버튼 처리:
- 해당버튼을 눌렀을때 조건과 그 조건에 해당하는 처리를 고민했습니다 
### 스택뷰추가:
- 스크롤뷰 재설정과 함께 스택뷰를 추가해서 계산식을 추가해줘야하는데 어떻게 해줘야할지 고민했습니다

### 배운개념 💡

- ScrollView
- StackView
- AutoLayout
- CGPoint
- NumberFormatter
- joined
- subview

2022-05-29 16:31 UTC, leejun6694 requested changes
안녕하세요!
전체적으로 코드가 한차례 정리되면 좋을 것 같습니다.
리뷰 내용이 한 부분이 아닌, 다른 코드에도 적용되는 경우가 있으니 한번 전체적으로 확인 부탁드려요~!

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/Enum/ExpressionParse.swift
> +    static func parse(from input: String) -> Formula {
👍

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet weak var mathSign: UILabel!
`access control` 을 고려해보면 좋을 것 같습니다 : )

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet weak var mathSign: UILabel!
IBOutlet 등의 UI 는 어떤 UI 인지 명시적으로 네이밍에 작성 부탁드려요~!
예) `mathSignLabel`

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +        stackView.subviews.forEach{ (view) in view.removeFromSuperview() }
아래와 같이 작성이 가능합니다! 참고 부탁드려요 (띄어쓰기도..!)
`stackView.subviews.forEach { $0.removeFromSuperview() }`

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func InputNumber(buttonNumber: UIButton) {
여기도 access control 확인해주세요~!

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func InputNumber(buttonNumber: UIButton) {
method 의 첫글자는 소문자로 부탁드립니다.

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func InputNumber(buttonNumber: UIButton) {
UIButton 이 buttonNumber 라는게 조금 생소하네요..
기본값인 sender 나 button 과 관련된 naming 이 어떨까요?

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +        if inputFormula == "0" && formulaNumber == "0" {
로직 이전에 체크해야하는 조건문들이 많은데, 여러 곳에서 사용하는 조건문이라면 따로 computed property 나 method 를 활용해보는건 어떨까요?
guard 문과 if 문이 혼재되고 있는데, 이를 통일시켜 보는 것도 가독성에 많은 도움이 될 것 같습니다 : )

2022-05-29 16:31 UTC, leejun6694 commented on Calculator/Calculator/ViewController.swift
> +        guard let currentFormula = mathFomula.text else { return }
```
guard let buttonDecimalPoint = sender.currentTitle,
           let currentFormula = mathFomula.text else {
               return
}
```
위와 같이 묶어서 사용할 수도 있습니다~

2022-05-30 14:36 UTC, Baek-Gom-95 commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet weak var mathSign: UILabel!
접근 제어차 추가를 해주었습니다! 네이밍은 항상 어려운거 같습니다 ㅠㅜ 네이밍도 변경해주었습니다 😊

2022-05-30 14:37 UTC, Baek-Gom-95 commented on Calculator/Calculator/ViewController.swift
> +        stackView.subviews.forEach{ (view) in view.removeFromSuperview() }
이렇게 간단화 할수 있었네요! 감사합니다 변경하여 적용했습니다 😊

2022-05-30 14:38 UTC, Baek-Gom-95 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func InputNumber(buttonNumber: UIButton) {
- 접근제어자 추가 해주었습니다! 🙂 
- 컨벤션을 체크해도 나오네요 더욱 신경쓰겠습니다 😭
- 기본값은 sender로 변경하니 좀 더 네이밍이 명확한거 같습니다 🤔

2022-05-30 14:39 UTC, Baek-Gom-95 commented on Calculator/Calculator/ViewController.swift
> +        if inputFormula == "0" && formulaNumber == "0" {
해당 로직의 조건문을 method를 만들어주어 따로 빼주었습니다 🙂

2022-05-30 14:39 UTC, Baek-Gom-95 commented on Calculator/Calculator/ViewController.swift
> +        guard let currentFormula = mathFomula.text else { return }
이렇게 한번에 체크 가능했었네요 감사합니다! ☺️

2022-05-31 03:12 UTC, leejun6694 approved these changes
피드백 내용을 잘 반영해주셨습니다!
아쉬운 부분들이 있지만, 그룹 활동 피드백을 통해 같이 개선해나가면 좋겠습니다 : )

2022-05-31 03:12 UTC, merged