계산기 [Step3] Kiwi
yagom-academy/ios-calculator-app pull request #280
Opened 2022-05-27 16:01 UTC by kiwi1023

@jryoun1 안녕하십니까 제이크! STEP 3 정말 힘드네요... 많이 부족하지만 잘 부탁 드리겠습니다!

## UML
![Untitled Diagram drawio (2)](https://user-images.githubusercontent.com/101521502/170734702-c5c77729-f014-46f6-83b8-32e6b386408b.png)

## 고민한점

사실 이번 프로젝트를 하면서  구글링을 통한 코드 참조를 많이 진행하게 된 것 같습니다. 초반에는 이게 과연 내가 프로젝트를 제대로 하는 것인가에 대한 의문과 걱정이 있었지만, 이것 또한 하나의 공부이며 앞으로 개발자로 프로젝트를 진행해도 구글링을 통한 코드 참조를 많이 하게 될거라는 조언을 받게 되었습니다. 하지만 단순 붙여넣기가 아닌 제 방식대로의 수정을 진행하였으며 코드의 구조가 이해 되지 않을 경우는 사용을 하지 않았습니다. 

이번 STEP 3가 너무 어려웠습니다... 그렇기 때문에  특정 부분에 대한 질문은 가지고 있지 않습니다. 왜냐하면 특정 부분에 의문이 생겼다기 보다는 근본적인 개념과 공부의 부족함을 필요성을 느꼈기 때문입니다ㅜㅜ 

많이 부족한 코드지만 지금까지 해주신 것 처럼 좋은 의견 주신다면 더 공부하고 잘 정리해서 최종 리드미 작성때 집어넣겠습니다!

2022-05-28 11:05 UTC, jryoun1 requested changes
step3까지 2주동안 고생하셨습니다 @kiwi1023 
고민하신 부분들이 코드에도 많이 보이는 것 같아서 좋았습니다 👍🏻 
다만 말씀하신 것처럼 구글링은 개발을 하면서 필수적인 것입니다. 모든 것을 기억하고, 머리속에 있는 지식으로 코드를 작성하기에는 너무 많은 종류의 함수, 프로토콜 등 방대한 자료가 많습니다.

다만 키위가 말씀하신 것처럼 이를 사용할 때 자신이 이해하고 사용할 수 있도록 해야하고, 그렇지 않다면 이를 이해하기 위해서 필요한 개념들도 공부를 하는 자세가 중요한 것 같고, 키위는 이미 잘 해나가고 계신 것 같네요 👍🏻

물론 프로젝트의 step을 나가는 것도 중요하지만 step을 빠르게 나가고 다 끝내는 것보다 초반 몇개의 step만을 진행하더라도 자신이 작성한 코드에 대해서 설명할 수 있고, 여러 방법들 중에서 왜 해당 방법을 택해서 코드를 작성했는지 설명할 수 있도록 공부하는 것이 개인적으로는 더 중요한 것 같다고 생각이 듭니다. ㅎㅎ 왜냐면 캠프가 끝나도 프로젝트는 다시 혼자서 얼마든지 할 수 있다고 생각하기 때문입니다! 

코드에 대해서 코멘트를 몇 가지 남겨두었습니다!

### 에러
1. `,` 가 포함된 숫자들은 위에 연산 기록에 남지 않고 있습니다. e.g. 100,000,000 + 1 = 1,000,001 로 =를 눌렀을 때는 나오지만 위에 1,000,000,000이 기록되지 않고 있습니다.
2. 20자리 이상이 넘어가면 숫자가 초기화 됩니다. (잘리는 숫자는 반올림되어야합니다)

2022-05-29 08:05 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +final class CalculatorViewController: UIViewController {
final 키워드를 붙이면, Dynamic Dispatch 가 아닌 Static Dispatch 로 작동해 성능 향상에 이점을 주기 때문에 붙여주었습니다!

2022-05-29 08:05 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private var userNumberTapped = false
단순 실수 였던것 같습니다 ! 수정했습니다!

2022-05-29 08:06 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        setupViews()
수정하였습니다!

2022-05-29 08:10 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        let digit = sender.currentTitle!
제이크가 저번 리뷰에서 100% 확신할 수있는 경우에는 강제언랩핑을 해주어도 괜찮다고 해주셔서.. 나름 100%로 확신할 수 있다 생각하여 강제 언랩핑을 해주었는데 옵셔널의 가능성이 있을지에 대한 관련부분 공부를 더 하여 수정 진행하겠습니다!

2022-05-29 09:55 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            operandLabel.text! = ""
수정하였습니다!

2022-05-29 09:55 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if operandLabel.text! == "NaN" {
수정하였습니다!

2022-05-29 10:03 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction private func didTapNumberButton(_ sender: UIButton) {
수정하였습니다 !

2022-05-29 10:03 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        let validNumber = makeDouble(number: operandLabel.text!)
수정하였습니다 !

2022-05-29 10:05 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        let numberFormatter = NumberFormatter()
깊게 고려하지 않았던 것 같습니다.. ㅎㅎ 수정하였습니다 !

2022-05-29 10:08 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            userNumberTapped = true
수정 하였습니다 !

2022-05-29 10:30 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if operandLabel.text! == "NaN" {
수정하였습니다!

2022-05-29 10:30 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction private func didTapNumberButton(_ sender: UIButton) {
수정하였습니다!

2022-05-29 10:31 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if operandLabel.text!.contains(",") {
이부분은 구현을 어떻게 해야할지 잘 모르겠습니다..

2022-05-29 10:31 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        let textCurrentlyInDisply = operandLabel.text!
수정하였습니다!

2022-05-29 10:39 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if textCurrentlyInDisply.contains(Character(dot)) {
수정하였습니다!

2022-05-29 10:44 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private func makeDouble(number: String) -> Double {
수정 하였습니다 !

2022-05-29 10:45 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            return nil
실수가 있었습니다 유의하겠습니다!

2022-05-29 10:51 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        stack.alignment = .fill
수정하였습니다!

2022-05-29 10:59 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        let numberStackLabel = UILabel()
수정하였습니다!

2022-05-29 11:01 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            operandLabel.text = "NaN"
수정하였습니다 !

2022-05-29 11:05 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction private func removeAllButton(_ sender: UIButton) {
이부분이 잘 이해가 되지 않습니다 !

2022-05-29 11:07 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        userNumberTapped = false
이 부분도 이해가 잘 가지 않습니다...

2022-05-29 11:19 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        scrollView.layoutIfNeeded()
입력한 값이 스택뷰에 쌓인다음 즉시 업데이트 되지 않는 문제를 겪었습니다. 그래서 해결방법을 구글을 통해 찾게 되었는데, 이 메소드가 update cycle이 올 때까지 기다린 다음 layoutSubviews를 호출시키는 것이 아니라 즉각적으로 layoutSubviews를 발동시키는 메소드라는  사실을 알게 되었습니다. 그렇기 때문에 즉시 값이 변경되어야 하는 애니매이션에서 layoutIfNeeded 메서드가 주로 사용된다길래 사용하게 되었습니다!

2022-05-30 13:24 UTC, jryoun1 reviewed
고생하셨습니다 🙏🏻
수정하신 부분 확인하고 코멘트 남겼습니다!

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +           userInput.removeLast()
removeLast는 왜 2번 해주는걸까요?

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let _ = Double(String(lastCharacter)) else { return }
이것도 하나의 guard로 통합할 수 있을 것 같습니다.

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let stack = generateStack() else {
guard문을 사용할 때 else 이후 블록의 줄바꿈에 대한 규칙이 있어야할 것 같아요 🙏🏻

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private func setLabel(_ label: String) -> UILabel {
함수의 역할은 label의 textColor와 text를 설정해주는데 함수명과 매개변수명만 봐서는 무엇을 설정하는지 명확하지 않은 것 같습니다.

가능하다면 UILabel 자체를 extension하고 매개변수로는 textColor, text를 받는다면 물론 지금 프로젝트는 vc가 하나지만 확장된다면 다른 vc에서도 해당 함수를 사용할 수 있을 것 같아보입니다.

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            guard let validNumber = userInputNumber else { return }
위의 let과 guard let을 한번에 호출 할 수 있을 것 같은데 나눈 이유가 있을까요? 👀

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            return
이때는 그냥 return만 해도 될까요? 🤔
정의되지 않은 Error가 발생한 것에 대해서 처리는 하지 않아도
어떤 에러인지 파악은 할 수 있도록 print를 해줄 수는 있을 것 같습니다.

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        } catch OperatorError.divideZero {
각각의 error case를 키위가 작성하신대로 처리할 수도 있지만 아래와 같이 작성할 수도 있습니다.
```swift
   } catch let error as CalculatorError {
            switch error {
            case .dividedByZero:
                // 에러처리
            case .notEnoughInput:
                // 에러처리
            case .emptyStack:
                // 에러처리
            }
    } catch {   }
```

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            removeStack()
if 블럭 내부의 행동이 반복되고 있는데 하나로 묶을 순 없을까요? 👀

2022-05-30 13:24 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        numberFormatter.numberStyle = .decimal
여전히 formatter를 반복해서 설정해주고 있네요 🤔

2022-05-30 13:25 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction private func removeAllButton(_ sender: UIButton) {
ac, ce, +/- 와 같은 특수 기능들은 sender.currentTitle의 값을 통해서 하나의 함수 내부에서 각각의 경우를 확인하고 알맞은 처리를 해줄 수 있을 것 같습니다.

2022-05-30 13:35 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    //MARK: - 숫자 버튼
수정했습니다!

2022-05-30 13:36 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if operandLabel.text!.contains(",") {
String 타입 자체를 extension한 [예시](https://babbab2.tistory.com/124)들을 찾아보면 도움이 될 것 같습니다.

2022-05-30 13:39 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let digit = sender.currentTitle else{ return }
수정했습니다!

2022-05-30 13:39 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if currentOperandText.count >= 20 {
수정했습니다!

2022-05-30 13:40 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if currentOperandText.count >= 20 {
수정했습니다!

2022-05-30 13:40 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        } else {
수정했습니다!

2022-05-30 13:41 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if isNumberTapped  {
수정했습니다!

2022-05-30 13:42 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard currentOperandText.contains(Character(dot)) == false else { return }
수정했습니다!

2022-05-30 13:43 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            isNumberTapped  = true
수정했습니다!

2022-05-30 13:45 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if operandLabel.text == zero && inputStackView.subviews.isEmpty == false && userInput.count >= 2 {
remove에 대한 오류를 없애주고자 했습니다!

2022-05-30 14:15 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let _ = Double(String(lastCharacter)) else { return }
수정했습니다!

2022-05-30 14:15 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let stack = generateStack() else {
수정했습니다!

2022-05-30 14:18 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            guard let validNumber = userInputNumber else { return }
수정했습니다!

2022-05-30 14:19 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            return
수정했습니다!

2022-05-30 14:20 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        numberFormatter.numberStyle = .decimal
수정했습니다!

2022-05-30 14:33 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private let zero: String = "0"
수정했습니다!

2022-05-30 14:33 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            return
수정했습니다!

2022-05-30 14:33 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            removeStack()
수정했습니다!

2022-05-30 14:33 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        numberFormatter.numberStyle = .decimal
수정했습니다!

2022-05-30 15:38 UTC, jryoun1 approved these changes

2022-05-30 15:38 UTC, merged