계산기 [STEP 2] 민쏜
yagom-academy/ios-calculator-app pull request #283
Opened 2022-05-28 14:43 UTC by minsson

안녕하세요, 콘!
Step 2 PR 제출합니다. 검토 부탁드립니다! ☺️

Step 2는 정말.. 정말 쉽지 않았어요...

그 이유를 생각해보자면,
1) UML을 통해 각 객체간 관계를 파악하는 것
2) 메서드와 변수명을 통해 각 객체의 역할을 추론하는 것
이 두 작업이 무척 낯설었기 때문이었던 것 같아요.

아래는 제가 콘에게 드리고 싶었던 질문들이에요.
이것들 외에도 제가 인지하지 못하고 넘어간, 개선하면 좋을만한 사항들이 많을 거라고 생각해요.
아직 제가 이해하고 적용하기에 어려울만한 내용이라도 피드백 해주시면 나중에 발전해나가면서 다시 돌아보고, 성장할 수 있는 계기가 될 것 같아요..!

제게는 콘의 피드백이 너무 귀중한만큼 가감없는 피드백 부탁 드립니다..!!
감사합니다!!

# 프로젝트를 수행하면서 궁금했던 것들

## 1. extension Double
UML과 달리, 저는 `split(with:)` 메서드를 별도로 구현하지 않았어요. 현재 제가 작성한 구조상으로는 `componentsByOperators(from input:)` 메서드와 역할이 겹쳐, `split(with:)`을 쓰게 되면 오히려 불필요한 코드가 된다고 생각했기 때문이에요. 

제가 UML을 이해한 바로는, `componentsByOperators(from input:)` 안에서 `split(with:)`을 쓰는 구조 같아요. 제가 이해한 바가 맞다면, UML이 이렇게 작성된 데에는 아마 어떤 합리적인 이유가 있을텐데, 저로서는 아직 잘 이해가 되지 않아요.

만약 이게 실제로 회사나 다른 프로젝트에서 UML을 그린 동료 혹은 상사와 협업하는 상황이었다면, 아마 업무를 수행하기 전에 이 부분에 대해 미리 질문했을 것 같아요.

개인 프로젝트다보니 혼자서는 답을 잘 찾지 못했어요. 콘은 어떻게 생각하시나요?

## 2. ExpressionParser 열거형
만약 제가 직접 구현했다면, 저는 열거형 대신에 구조체를 사용했을 것 같아요. 열거형은 case를 이용해 선택의 경우의 수를 지정하기 위해 사용한다고 알고 있었는데, case가 없는 열거형은 낯설었어요. 

이런 case가 없는 열거형을 구조체와 비교한다면 어떤 장단점이 있는지 궁금해요.

## 3. parse(from:) 메서드의 Test
parse(from:) 메서드의 목적은 아규먼트로 받은 계산식을 연산자 Queue와 피연산자 Queue로 분류해, Formula 인스턴스를 리턴하는 거라고 생각했어요.

이를 테스트하기 위해 아래와 같은 코드를 작성했었는데, `Global function 'XCTAssertEqual(_:_:_:file:line:)' requires that 'Formula' conform to 'Equatable'` 라는 에러가 발생했어요.

생각해보니 Node()와 Node()를 비교하는 거니 당연히 그렇겠다는 생각이 들었어요. 그래서 PR로 제출한 코드와 같이 `result()` 메서드를 사용해 간접적으로 `parse(from:)` 메서드의 작동을 테스트해봤어요.

이런 경우에 콘이라면 어떻게 진행했을까요?

```swift
    func test_parse메서드_input계산식을_연산자Queue와_피연산자Queue로_나누어_Formula타입으로_반환한다() {
        // given
        let input = "100+200-150*3/2"
        
        // when
        var operandsExpected = CalculatorItemQueue<Double>()
        var operatorsExpected = CalculatorItemQueue<Operator>()
        
        [100.0, 200.0, 150.0, 3.0, 2.0].forEach( { operandsExpected.enqueue($0) } )
        [Operator.add, Operator.subtract, Operator.multiply, Operator.divide].forEach( { operatorsExpected.enqueue($0) } )
        
        let result = ExpressionParser.parse(from: input)
        
        // then
        XCTAssertEqual(result, Formula(operands: operandsExpected, operators: operatorsExpected))
    }
}
```

## 4. parse(from input:)의 축약
`parse(from:)`의 정의부를 보면 아래와 같은 코드가 포함되어 있어요. `parse(from:)` 메서드에서 아규먼트로 전달 받은 `input`에서 함수의 최종 리턴에 포함시킬 `피연산자 Queue`인 `resultOperands`를 추출하기 위한 코드예요.

아래 코드와 같이 그 과정의 한 단계마다 변수 네이밍을 신경써서 가독성을 높이고자 해봤어요.
그런데 결과물을 보니, 이 과정은 말그대로 데이터를 추출하기 위해 잠깐 거쳐가는 과정일 뿐인데, 이렇게 변수명을 자세하게 적는 게 유의미한 걸까? 라는 의문이 들었어요.

오히려 너무 자세히 적다 보니 가독성이 안 좋아진 것 같기도 하다는 생각이 들었어요.
```swift
let numbersParsedFromInput: [String] = componentsByOperators(from: input)
let numbersToEnqueue: [Double] = numbersParsedFromInput.compactMap( { Double($0) } )
numbersToEnqueue.forEach( { resultOperands.enqueue($0) } )
```

그래서 최대한 축약하면 어떤 모습일지 궁금해서 아래처럼 축약해봤어요. 

```swift
componentsByOperators(from: input)
    .compactMap( { Double($0) } )
    .forEach( { resultOperands.enqueue($0) } )
```

두번째 코드는 너무 극단적인 축약이라고 생각하지만, 첫번째의 코드는 또 너무 자세한 것 같아요. 
콘은 어떻게 생각하시나요?

## 5. componentsByOperators(from:) 메서드의 구조

### 1) 최초 작성본
```swift
static private func componentsByOperators(from input: String) -> [String] {
    let numbers: [String] = input.components(separatedBy: ["+", "-", "*", "/"])
        return numbers
}
```

처음에 작성한 코드에서는 `["+", "-", "*", "/"]`과 같이 매직 리터럴이 사용되고 있어요. 이를 개선해보고자 아래와 같이 작성해봤어요.

### 2) 제출 코드
```swift
static private func componentsByOperators(from input: String) -> [String] {
    var operators: CharacterSet = []
    Operator.allCases.forEach( { operators.insert(charactersIn: String($0.rawValue)) } )
    
    let numbersOnly: [String] = input.components(separatedBy: operators)
    return numbersOnly
}
```

위에서 components(separatedBy:)에 ["+", "-", "*", "/"]을 아규먼트로 넣었던 바, 당연히 allCases로 받은 값도 그대로 넣을 수 있다고 생각했었는데, 예상치 못한 문제가 있었어요. 

아규먼트 타입이 CharacterSet이어야 한다는 거였어요. 이에 따라 해결법을 찾아 제출 코드를 작성했어요.

이렇게 작성함으로써 매직 리터럴을 제거할 수 있었고, 앞으로 어떤 연산자가 새로 생기든 대응할 수 있다는 점에서 확장성이 좋아졌다는 생각이 들어요. 

하지만 과연 이것이 읽기 좋은 코드인가에 대한 의문이 들어요. 이 코드를 처음 보는 동료가 원활하게 읽을 수 있을까요? 좀 더 풀어서 쓰는 게 좋을까요? 아니면 제 레벨에서는 난해해 보이지만, 현업 수준에서는 아무 문제 없이 읽히는 코드인가요? 콘은 어떻게 생각하시나요?

## 6. result() 메서드의 변수명과 옵셔널 바인딩의 리턴값
```swift
func result() throws -> Double {
    guard var lhs = operands.dequeue()?.data else { return 0.000000000999 }
    
    while let mathOperator = operators.dequeue()?.data,
          let rhs = operands.dequeue()?.data {
        lhs = try mathOperator.calculate(lhs: lhs, rhs: rhs)
    }
    
    let result = lhs
    return result
}
```

### 1) 변수명
위 메서드에서 `lhs`라는 변수명이 적절하지 않다고 생각하는데, 더 나은 대안이 떠오르지 않아요. 처음에는 `temp`라고 썼는데 더 좋지 않은 변수명이라고 생각해서 일단은 `lhs`라고 해놓은 상태였어요.

`lhs`: `Operator` 열거형에 포함된 `calculate(lhs:rhs:)`메서드에 사용할 변수예요. 우선 숫자 Queue의 첫번째 숫자를 넣게 되어 있어요.

그 후 반복문에서  `calculater(lhs:rhs:)`를 호출할 때 `lhs`의 아규먼트로 넣어요. `rhs` 자리에는 숫자 Queue에서 `Dequeue()`되는 값이 들어와요.

그리고 반복문을 통해 연산을 진행하며 연산 결과를 `lhs` 변수에 계속 쌓아나가는 방식이에요. 보통 이런 역할을 하는 변수명에는 `total`이나 `result` 같은 네이밍을 사용했는데, 맨 처음 숫자 Queue에서 첫번째 값이 들어가는 코드가 있어 그렇게 네이밍을 하는 것도 어색하다는 생각이 들어요.

콘은 어떻게 생각하시나요?

### 2) 옵셔널 바인딩의 리턴값

옵셔널 바인딩에서 값이 없을 경우에 대해 `return 0.000000000999`라고 써놨어요. `result()`의 리턴형이 `Double`이라 어떤 값을 리턴해야할지 고민하다가 만약 계산기에서 마주하게 되면 보통 이상하게 생각할 수 있는 숫자를 넣어봤어요. 아니면, 차라리 에러를 리턴하는 게 더 나을지도 모른다는 생각이 들기도 해요. 콘은 어떻게 생각하시나요?

2022-05-29 10:24 UTC, protocorn93 requested changes
고생하셨어요 민쏜! 고민한 흔적이 느껴진 코드였어요! 👏👏

# 궁금했던 것들

## 1. extension Double

`componentsByOperators(from input:)`는 비즈니스 로직의 고차원 수준의 메서드라고 생각했어요. input은 전체수식이고, operator를 기준으로 잘라줘라는 메시지를 나타내고 이를 나누고 실제로 로직 구현을 위해 split을 사용한다고 생각했어요.

## 2. ExpressionParser 열거형

`static` 메서드만 존재하는 객체나 별도의 상수를 관리하는 namespace도 `enum`으로 많이 정의하는데요. 그 이유는 case 없는 enum은 생성자를 통해 생성이 불가능하기 때문이에요. 구조체로 정의하면 생성자를 사용해 객체를 생성할 수 있겠죠. 물론 `private init` 같은 코드를 작성할 수 있겠지만 `enum`을 사용하는 것이 좀 더 편리할 수 있을 것 같아요. 

## 3. parse(from:) 메서드의 Test

`result`의 값으로 비교하는 것도 좋아보여요. 실제로 우리가 기대하는 결과는 최종 연산값이니까요. 하지만 parse라는 행위 자체를 테스트 해보기 위해선 말씀해주신대로 `Equatable`을 채택하여 `==` 메서드를 직접 구현하는 방법이 있을 수 있어요! 

## 5. componentsByOperators(from:) 메서드의 구조

저는 현재 구조도 충분히 가독성이 좋다고 생각해요. 기본 메서드들의 아규먼트 레이블이나 메서드명을 통해서 구현하고자하는바를 명확히 드러낼 수 있었다고 생각해요

2022-05-29 10:24 UTC, protocorn93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        numbersToEnqueue.forEach( { resultOperands.enqueue($0) } )
궁금했던 것들 4번(`4. parse(from input:)의 축약`)에 대한 코멘트에요. 

보통 복잡한 연산이 들어가게 되면 저도 분리하는 편인데요. 현재에는 단순한 형변환이기에 최종 변수명만 잘 정해주시면 고차함수를 활용하는 것도 괜찮아보여요

2022-05-29 10:24 UTC, protocorn93 commented on Calculator/Calculator/Model/Fomula.swift
> +    var operators = CalculatorItemQueue<Operator>()
이렇게 열어두기보단 `private`으로 숨겨주고 `Formula` 생성자를 통해 `operands`와 `operator`를 채워주는 것이 어떨까요

2022-05-29 10:24 UTC, protocorn93 commented on Calculator/Calculator/Model/Fomula.swift
> +    var operators = CalculatorItemQueue<Operator>()
UML상 개방되어있는 프로퍼티라면 `let`으로 선언하여 외부에서 값의 수정은 불가능하게 막아주는 것더 좋아보여요

2022-05-29 10:24 UTC, protocorn93 commented on Calculator/Calculator/Model/Fomula.swift
> +        guard var lhs = operands.dequeue()?.data else { return 0.000000000999 }
궁금했던 것들 6번(`result() 메서드의 변수명과 옵셔널 바인딩의 리턴값`)에 해당하는 코멘트에요. `Double?` 타입을 반환하는 것이 적절해보이지만 UML상 그렇지 못하다면 에러를 던지는게 맞다고 보여져요. `0.000000000999`는 정말 주관적인 값이기에 적절하지 않아보이네요. 아

2022-05-29 10:24 UTC, protocorn93 commented on Calculator/Calculator/Model/Fomula.swift
> +            lhs = try mathOperator.calculate(lhs: lhs, rhs: rhs)
궁금했던 것들 6번(`result() 메서드의 변수명과 옵셔널 바인딩의 리턴값`)에 해당하는 코멘트에요. 연산결과를 축적해나가는 방식인데요. `lhs`보단 `result`라는 변수명으로 축적해나가는게 좋아보여요. 

비슷한 행위를 하는 고차함수인 `reduce`를 참고해보셔도 좋을 것 같아요.

2022-05-29 10:24 UTC, protocorn93 commented on Calculator/Calculator/Model/Node+LinkedList.swift
> +    private var tail: Node<Element>?
`head`는 `private(set)`인데 반해 `tail`은 `private`인 이유가 있을까요??

2022-05-29 17:42 UTC, minsson commented on Calculator/Calculator/Model/Error.swift
> +    case divisionByZero
그렇군요! 감사합니다, 수정했습니다!

2022-05-29 17:53 UTC, minsson commented on Calculator/Calculator/Model/Fomula.swift
> +            lhs = try mathOperator.calculate(lhs: lhs, rhs: rhs)
조언에 따라 `lhs`를 `result`로 변경했어요. 그에 맞춰 `rhs`의 네이밍을 고민하다가 `currentNumberForCalculation`라는 변수명이 떠올랐는데, 변수명이 너무 길고, `calculate`라는 이름의 메서드의 아규먼트로 들어가므로 `계산`이라는 의미가 중복되는 것 같아서 `currentNumber`라고 써봤어요.

2022-05-29 17:58 UTC, minsson commented on Calculator/Calculator/Model/Node+LinkedList.swift
> +    private var tail: Node<Element>?
저는 `CalculatorItemQueue` 구조체의 `peek`에서 아래 코드와 같이 `head`를 조회하고 있어, `head`는 `private(set)`이 되어야 한다고 생각했어요.
```swift
    var peek: Element? {
        return queue.head?.data ?? nil
    }
```

반면, `tail`의 경우 내부적으로 `append` 메서드에서 사용하지만, 외부에서는 사용하지 않기 때문에 읽기가 필요하지 않아 `private`으로 설정하는 게 더 좋다고 생각했어요.

제 생각에 대한 콘의 의견은 어떤가요?

2022-06-03 08:30 UTC, minsson commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
```swift
        let operatorsFromInput: [Operator] = input.compactMap( { Operator(rawValue: $0) } )
        operatorsFromInput.forEach( { resultOperators.enqueue($0) } )
```
로 개선해봤어요! 이게 콘이 염두에 두신 방향이 맞을까요?
그런데 아직 저에게는 기존 코드가 더 쉽게 읽히는데, 아마 제가 고차함수에 익숙치 않아서 그렇게 느껴지는 것 같다는 생각이 들어요.

그래서,
이 경우에 고차함수를 활용한 방안이 가독성과 성능 모두 더 좋기에 고차함수를 쓰는 건지,
혹은 현업에 계신 분들이 보시기에도 가독성이 조금 떨어지는데 성능 때문에 쓰는 건지 궁금해요!

2022-06-03 08:32 UTC, minsson commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        numbersToEnqueue.forEach( { resultOperands.enqueue($0) } )
감사해요! 앞으로 단순 형변환을 진행하는데 코드가 불필요하게 길다면, 고차함수를 한번에 여러 단계를 적용하는 방식도 염두에 둘 수 있을 것 같아요!

2022-06-03 08:33 UTC, minsson commented on Calculator/Calculator/Model/Fomula.swift
> +        guard var lhs = operands.dequeue()?.data else { return 0.000000000999 }
아래와 같이 에러를 던지도록 수정했어요!

```swift
    func result() throws -> Double {
        guard var result = operands.dequeue()?.data else { throw CalculatorError.emptyCalculatorItemQueue }
        
        while let mathOperator = operators.dequeue()?.data,
              let currentNumber = operands.dequeue()?.data {
            result = try mathOperator.calculate(lhs: result, rhs: currentNumber)
        }

        return result
    }
}
```

2022-06-03 09:04 UTC, minsson commented on Calculator/Calculator/Model/Fomula.swift
> +    var operators = CalculatorItemQueue<Operator>()
아래와 같이 변경했습니다! UML과는 다르지만, 숨겨주는 게 더 좋은 것 같아 전자를 선택했습니다!!
```swift
    private var operands: CalculatorItemQueue<Double>
    private var operators: CalculatorItemQueue<Operator>
```

2022-06-05 01:52 UTC, protocorn93 commented on Calculator/Calculator/Model/Fomula.swift
> +    var operators = CalculatorItemQueue<Operator>()
let 으로 선언하고 생성자에서 할당해주는 방법도 좋을 것 같아요. Step3 진행하면서 수정해보시죠.

2022-06-05 01:53 UTC, protocorn93 commented on Calculator/Calculator/Model/Node+LinkedList.swift
> +    private var tail: Node<Element>?
queue 자체가 peek을 지원해서 head를 숨기는게 좀 더 적절해보여요! Step3 진행하면서 수정해보시죠.

2022-06-05 01:54 UTC, protocorn93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
고차함수를 쓴다고 가독성이 떨어진다고 생각하진 않아요! 고차함수 내부도 for문인 것은 동일해요. 

전 오히려 고차함수 그 자체로 하고자하는 바를 더 명확하게 드러낸다고 생각해요.

2022-06-05 02:15 UTC, merged

2022-06-05 12:36 UTC, minsson commented on Calculator/Calculator/Model/Fomula.swift
> +    var operators = CalculatorItemQueue<Operator>()
넵, Step 3에 적용했어요!

2022-06-05 12:40 UTC, minsson commented on Calculator/Calculator/Model/Node+LinkedList.swift
> +    private var tail: Node<Element>?
> queue 자체가 peek을 지원해서 head를 숨기는게 좀 더 적절해보여요! Step3 진행하면서 수정해보시죠.

숨긴다 라는 게 `private(set)`을 `private`로 변경하는 게 좋겠다는 것으로 받아들였는데, 제가 이해한 게 맞을까요?

아래와 같이 peek의 정의부에서 head를 이용해서 return하고 있어서 head를 접근 수준을 `private var`로 바꾸지 못했는데, 제가 콘의 의도를 잘 이해하지 못한 것 같아요... 😅

```swift
    var peek: Element? {
        return queue.head?.data ?? nil
    }
```