계산기 [STEP 3] 브래드
yagom-academy/ios-calculator-app pull request #284
Opened 2022-05-29 09:20 UTC by bradheo65

안녕하세요 도미닉!! @AppleCEO

STEP03 PR 보내드립니다.

구현을 못할 줄 알았지만 동기캠퍼들의 도움을 많이 받아서 구현해보았습니다!!
도미닉의 생각하시는 방향! 적극적으로 피드백 부탁 드립니다!!

## [STEP 03]

### 이번 스텝 수행 중 핵심 경험 체크
- [x] IBOutlet / IBAction의 활용
- [x] 스택뷰의 활용
- [x] 스크롤뷰의 활용
---
 
### STEP03 계산기 프로그램 동작 
![Simulator Screen Recording - iPhone 12 - 2022-05-29 at 17 58 15](https://user-images.githubusercontent.com/45350356/170860517-054f76f9-023c-40ae-8836-b1c254f4a019.gif)

---
### STEP03 구현 내용📑
- CalculatorViewController: 
    - touchNumberButton(): 숫자 버튼 액션 기능
    - touchOperatorButton(): 연산자 버튼 액션 기능
    - touchOptionButton(): 옵션 버튼 액션 기능
    - makeStackLabel(): 데이터가 들어올 때마다 스택에 라벨 추가 기능 
    - removeOldLabels(): 기존 라벨 제거
    - didTapAnswerButton(): "=" 눌렀을 때 동작되는 기능
    - didTapACButton(): "AC" 눌렀을 떄 동작되는 기능
    - didTapCEButton(): "CE" 눌렀을 때 동작되는 기능
    - didTapSignButton(): "+/-"눌렀을 떄 동작하는 기능
    
### STEP03 진행하면서 고민한 점 🫠
---
고민한 점이 너무나도 많지만 대표적으로 고민한 점에 대해 작성해보았습니다.

1. 아래 사진처럼 각 버튼들을 한개의 액션버튼 메소드에 묶어서 사용했습니다. 이에 장단점에 생각해 보았습니다.
![image](https://user-images.githubusercontent.com/45350356/170857754-3bc4bee2-69d3-48d0-a093-f3b36bd8df50.png)

- 장점
    - 각 버튼마다 이벤트 액션메소드를 만들지 않아도 된다.
    - 한개의 액션메소드에서 버튼들의 제어가 가능하다.
- 단점
    - 한개의 메소드 안에 버튼이 여러개 있다보니 제어문이 필수적으로 들어간다.. 각 버튼별로!

    나의 생각: 기능적으로는 동일하게 작동되지만 결국엔 유지보수, 가독성 측면으로 생각해보자면 스타일, 어떤 프로그램인지 마다 다른 것 같은데,, 예를 들어 이번 프로젝트가 계산기니까.. 숫자버튼은 숫자버튼끼리, 연산버튼들은 연산버튼끼리 비슷한 형식의 기능끼리 묶어주어서 표현해보았습니다.

2. 이번 프로젝트에서 제어문을 많이 사용했는데, 특히 ViewController의 버튼 액션 기능들에 대한 제어는 if문을 많이 사용해보았습니다.. 가독성 부분에서는 switch case를 활용하는 것이 더 좋을 것 같다고 생각했지만, 현재 액션을 Button.title의 값들을 통해 제어하므로 switch case인 경우 각 조건들을 다 써주지 않는 이상은 default를 마지막에 추가해야 해서.. 오히려 코드 줄이 더 늘어나고, 막상 default에서 "어떤 처리를 해주는 것에도 고민이 나올 것 같다"고 생각해서 if문으로 작성했습니다. 막상 작성하고 보니 역시 switch case문이 가독성 부분에선 더 좋은 것 같다고 고민해보았습니다!

### STEP03 진행하면서 경험한 점 ✏️
---
1.	계산기 프로그램이 코드 안에서 많은 동작들을 하는 것을 알게 된 경험..
2.	처음부터 가독성 좋은 코드로 작성하고 싶었지만 많은 시간이 소모되는 것을 알고 기능 구현 부터 하는 방법이 더 좋은 방법이라는 것이라는 생각.
3.	scrollView 안에 stack 뷰, 또 stack 뷰안에 또 다른 stack.. 작은 화면에 Layout이 서로 얽혀있다는 것.
4.	혼자 생각해서 해결해도 좋지만, 동료와 얘기를 통해 더 좋은 방법을 알게 되고 반대로 동료에게 나의 생각을 전달하는 정말 좋은 경험
---

2022-05-29 13:20 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@bradheo65 고생하셨습니다.
개선할 점들이 많이 보였습니다.
댓글들 확인해주세요~

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var numberStackLabel2: UILabel!
이렇게 뒤에 2를 붙이는 방식보다 조금 더 명확한 이름이 있으면 좋을 것 같아요.

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    var inputValue: String = ""
"" 는 비어있는 의미인 것 같네요.
비어있는 것, 값이 있을 수도 있고 없을 수도 있는 타입이 있는데 그 것을 사용해보면 어떨까요?

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if !operatorStorage.isEmpty {
else 도 사용할 거라면 부정이 먼저 나오는 것보다 긍정이 먼저 나오면 보기 좋을 것 같아요.
if !operatorStorage.isEmpty 는 비어있다는 건지 안 비어있다는 건지 한 눈에 들어오지 않아요.
if operatorStorage.isEmpty 로 하면 비어있으면 이라고 영어로 읽혀서 더 좋은 것 같아요.

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            return
이거는 이 이프, 이프엘스 문 밖에서 처리할 수도 있을 것 같네요!

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        operatorLabel.text = "\(ButtonTitle)"
ButtonTitle 상수는 String 타입인데요.
"\(ButtonTitle)" 으로 할당한 이유가 있을까요?
상수 이름은 소문자로 시작하는 것이 좋습니다!
타입 이름은 대문자로 보통 시작하고요~

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +
여기도 공백들이 어떤 의미일까요?

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if ["AC"].contains(ButtonTitle) {
조금 이해하기 어렵네요.
문자열 배열을 상수에 할당하는 방식도 있을 것 같아요.
자주 사용된다면 열거형 같은 곳에 넣어서 하드코딩을 제거해보면 좋겠습니다~

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        } else if ["⁺⁄₋"].contains(ButtonTitle) && presentNumbers != "0" {
이것들이 else 로 묶여 있을 이유가 있을까요?
if 문만 사용하도록 수정해 볼 수 있을까요?

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        let stackView = UIStackView()
어떤 것이 담기는지 이름이 좀 더 명확하면 좋겠습니다~

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +                                   + numberLabel.font.lineHeight)
너무 복잡합니다 ㅜㅜ
- 일 때와 + 일 때 처리를 다르게 해주고 있는 것처럼 보이기도 하네요.
암호를 보는 것 같습니다! 어떻게 개선해 볼 수 있을까요?

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        stackOperatorLabel.text = "\(presentOperator) "
presentOperator 도 String 인데요.
stackNumberLabel.text = presentNumbers
이렇게 할당해주지 않은 이유가 있을까요?
저는 "\()" 이런 식으로 할당하는 것에 부정적입니다.
읽기도 어려워지고 변수나 상수가 어떤 타입인지 헷갈릴 수도 있을 것 같아요.

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
뎁스가 좀 깊어진 것 같네요.
함수로 빼낸다던지 해서 뎁스를 줄여볼 수 있을까요?

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            }
기본형을 사용한 부분 좋습니다~ 💯

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculateItem/Operator.swift
> +    case divide = "÷"
divide 는 + 가 아닌 것 같은데 오타일까요?

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
> +//        }
사용하지 않는 코드는 지워주는 것이 좋습니다! 🔢

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/ExpressionParser.swift
>          }
꼭 이렇게 연달아서 . 으로 엮어줄 필요는 없습니다.
filter 를 한 결과 값을 상수에 할당하고 그것을 forEach 돌려보면 좋겠습니다~

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue/LinkedList.swift
> +        return count
checkCount 는 카운트를 확인한다는 것으로 보이는데요.
반환을 한다면 더 좋은 메소드명이 있을 것 같습니다.
그리고 이 메소드는 mutating 이 안 붙어도 되지 않나요?

2022-05-29 13:20 UTC, AppleCEO commented on Calculator/Test_CalculatorItemQueue/Test_CalculatorItemQueue.swift
> +    func test_dequeue_실행시_123456_를넣었을때_6_를반환하는지() {
어디에 넣었을 때가 메소드명에 포함되면 좋겠네요.

2022-05-29 23:58 UTC, bradheo65 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		A301D2D12833CAA200A025E3 /* CalculatorViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = C713D9452570E5EB001C3AFC /* CalculatorViewController.swift */; };
🫡

2022-06-01 03:12 UTC, bradheo65 commented
아무래도 급하게 기능구현을 하다보니 기본적인 코드 컨벤션도 맞춰지지 않아서.. 창피하네요. 리뷰 정말 감사합니다!

2022-06-01 09:10 UTC, AppleCEO approved these changes
제가 의도한 대로 많이 바뀐 것 같습니다.
if !operators.isEmpty 를 작성하지 말라고 말씀드렸던 것은 댓글로도 남겨놨는데
else문이 있는 경우에는 
if !operators.isEmpty {

} else {

} 이런 구조보다는
긍정인 if operators.isEmpty 가 먼저 나오게 되면 이해하기 더 쉬울 것 같아서 말씀드렸습니다.
(모든 if문에서 !을 빼라는 의도는 아니었습니다.)

2022-06-03 21:42 UTC, AppleCEO commented
![image](https://user-images.githubusercontent.com/47517256/171957604-229c8553-cf66-4263-97b7-535def11ce85.png)
전에 예상했던 것처럼 conflicts 가 뜨네요. Resolve confilicts 버튼이 보이시나요? 보이시면 한번 충돌을 해결해 볼 수 있을까요?

2022-06-04 15:51 UTC, bradheo65 commented
@AppleCEO  도미닉! 해결했어요~

2022-06-04 22:38 UTC, AppleCEO commented
오.. 해결하셨군요. 머지 드릴까요? ㅎㅎ

2022-06-05 00:07 UTC, merged