계산기 II [STEP 1] bard, hugh
yagom-academy/ios-calculator-app pull request #287
Opened 2022-05-30 14:25 UTC by Hugh-github

@GREENOVER 
안녕하세요 그린! 
계산기 II [STEP 1] PR 잘 부탁드립니다 ☺️

### UML
![Untitled](https://user-images.githubusercontent.com/102569735/171013972-f0c57142-b68c-4cd1-882f-5332266278bb.jpg)

### Merge 방법
- UML에 작성한 타입을 기준으로 branch를 만들어 해당 타입에 대한 한 사람의 코드를 가져와 merge하는 방식으로 진행했습니다.

### Code를 선택한 이유
- Operator, Formula 에서는 에러를 처리하는 방식만 다르고 로직은 같아 Operator는 바드의 코드를 사용하고 Formula 휴의 코드를 사용했습니다. 그 과정에서 Formula의 로직을 확인하고 에러를 해결하기 위해 테스트 코드를 작성했습니다.
- CalculatorItemQueue는 배열을 사용해 큐를 구현하는 것보다 더블 스택을 통해 큐를 구현했을 때 dequeue의 시간 복잡도가 유리하다고 판단하여 바드의 코드를 사용했습니다.
- Queue 프로토콜에 요구사항을 작성해 CalculatorItemQueue에서 해당 요구사항을 구현하도록 하였습니다. 
- ExpressionParser 같은 경우 Controller에서 데이터를 전달할 때 임의로 공백을 넣는 것보다 공백 없이 데이터를 전달하는 게 좋다고 판단하여 휴의 코드를 사용했습니다. 
- String+extension에 NumberFormatter를 통해 세 자리 수마다 콤마가 찍히도록 설정하였고, 뒤에 불필요한 숫자들을 제거해 주는 메서드를 구현했습니다.
- CalculatorViewController
  - 바드 : 전체적인 로직을 구현
  - 휴 : ScrollView에 추가될 Label과 Stack 연산 프로퍼티 생성

휴가 계산기 1의 Step3가 미완성 상태이기 때문에 후에 리팩토링 과정에서 로직을 변경할 예정입니다. 

### 궁금한 점
1. 똑같은 원격 저장소에 merge를 진행할 때 기능에 따라 branch를 만들어 merge를 하는게 좋은 방식인지 궁금합니다.
2. merge된 코드를 테스트할 때 테스트를 어떤 기준으로 해야 하는지 궁금합니다. 저희 같은 경우 가장 큰 차이가 나는 메서드에 대해 테스트 코드를 작성했습니다. UML 기준으로 코드가 잘 작성되었다면 다른 타입에 대해서는 테스트가 불필요하다고 생각했습니다.
3. 프로젝트 내 핵심 경험 중 제네릭을 활용하여 범용적인 타입을 구현하라는 것은 큐라는 프로토콜을 만들어 활용하라는 것인지 궁금합니다.
4. UML 기준으로 Model을 작성했다면 둘 중 한명의 Controller를 똑같이 가져와도 정상적으로 실행이 돼야 된다고 생각합니다. 그렇다면 Controller는 어떠한 기준으로 코드를 합쳐야 하는지 궁금합니다.
현재 Action 버튼 같은 경우도 서로 다르게 target을 설정해 로직에 차이가 존재합니다. 추후에 리팩토링 하는 과정에서 고쳐나가야 하는 부분인지 궁금합니다.

2022-05-31 02:12 UTC, GREENOVER requested changes
@Hugh-github @bar-d 
안녕하세요 두분! 이번 프로젝트 기간은 아주 짧고 크게 부담이 없는 프로젝트일거라 생각이 드네요😁
한주 짧은 기간이지만 요구사항을 다 만족시켜 좋은 프로젝트로 마무리 시켜보시죠!
다시 한번 1주일 잘 부탁드립니다🙏🏻
그럼 리뷰 시작하겠습니다~
두분 빠르게 코드 합치고 더 견고한 결과를 만들어내셨네요👍👍
고생 너무 많으셨어요ㅎㅎ
전체적으로 크게 리뷰할게 없었어요.
제 리뷰들의 절반은 여러분들이 해당 코드를 선택한 이유를 여쭤봤고 절반은 조금 더 보완되면 좋을 부분들에 대해 선택의 리뷰를 남겼습니다.
아..! 하나 메이저한게 있습니다.
해당 프로젝트 컴파일 자체가 안되실거에요.
리뷰 코멘트로도 남겨두었지만 없는 프로토콜 채택 및 특정 파일에서 괄호 하나가 누락되어 있더라구요🥲
리팩토링 전 그 부분부터 빠르게 확인 해보시면 좋을것 같습니다!
***
### 칭찬 드리고 싶은 부분
- 메서드들을 관심사에 따라 적절히 역할을 쪼개서 만들어 주셨네요 💯
- 커밋 이력만 보아도 페어 프로그래밍을 아주 잘 해주셨네요 💯
- UML 기반으로 병합할 코드에 대해 잘 선택해주셨네요 💯
- 코드를 합치는 방식이 좋았어요 💯
***
### 궁금하신 부분에 대한 저의 의견
1. 병합 방식
- 우선 두괄식으로 말씀드리면 지금 방식을 저는 선호합니다!
지금처럼 휴의 Cowork 브랜치를 main으로 생각하고 해당 브랜치를 최종적으로 PR을 보내기 위함이라면 해당 브랜치에서 직접 각자 하나씩 작업한것들을 commit push만 해서 바로 반영시키는것보다 지금처럼 기능 단위로 다른 브랜치를 생성해 작업 후 해당 Cowork 브랜치로 PR을 날려 리뷰 후 반영하는것이 협업 시 현업에서도 거의 99% 사용되는 방식입니다.
어쩌면 협업을 하는 회사라면 100%일수도?
아시다시피 바로 커밋하게 되면 리뷰를 거칠 수도 없고 실수가 있어도 바로 반영됨에 다시 롤백하거나 수정한 커밋을 푸쉬하는등 커밋 이력 관리가 지저분하게 됩니다.
물론 리베이스를 통해 커밋 메시지를 다시 관리해줄 수 있지만 그런 일련의 과정들을 지금 방식이라면 굳이 할 필요가 없을것 같아요.
또한 브랜치를 기능별로 생성해 작업했더라면 시간이 많이 흐른 후 해당 시점에서 어떤 문제가 발생했는지 Cowork 브랜치에서 파악하기위해선 다시 추적해 나가면서 리버트해야하는데 그 과정들이 여간 만만치 않을 수 있어요.
그럴때도 지금 방식이 이점이 될것 같습니다!
2. 테스트 코드 관련
- 제가 어떤 질문인지 정확히 구문 이해를 하지 못했어요🥲
병합 과정에서 로직이 많이 차이가 나 기존 테스트 코드 방식으로 컴파일이 오류난다면 물론 테스트 코드 수정 혹은 추가는 필요할것 같아요.
그리고 두분이 따로 작업하셨을때 UML 방식 기반으로 작업하셨으니 거의 차이가 없다면 테스트 코드에 대해 기존것 사용하고 재 구현은 필요없다라는 의미로 말씀하신건지 궁금해요🙋🏻
그것과 별개로 두분 모두 각자 해당 브랜치에서 테스트 코드 정상적으로 실행되시나요?
저는 `There is no scheme and/or test plan that contains every test you are trying to run.` 오류 즉 스킴 오류가 나네요🙋🏻
3. 범용적 타입 구현
- 지금 잘 해주신것 같은데요!?
지금도 큐를 제네릭하게 구현해주셨기에 크게 뭐 새롭게 할건 없을것 같아요🙋🏻
저는 해당 요구사항을 그렇게 이해했는데 제가 기획자가 아니다보니 다른 의미가 있을수도 있겠네요!
조금 더 의문이 든다면 크루 및 야곰한테 여쭤보면 좋을것 같아요🤔
4. Controller 병합 관련
- Model 병합과 컨트롤러 병합은 별개 아닐까요??
이어서 말씀하신것처럼 버튼 액션들에 대한 타겟 및 내부 로직들이 전부 다를것이고 만약 에러 catch등의 처리가 서로 상이하다면 이또한 다를것이라 Model을 UML 기준으로 잘 병합한다쳐도 컨트롤러를 기존것을 그대로 가져와 사용해도 에러를 발생시키지 않는것은 아닐것 같아요!
두개를 분리해 다르게 보시는건 어떨까요?🙋🏻
Controller 코드를 서로 합칠때도 다른 부분에서 하셨던것과 같이 로직이 어떤게 더 나은지 네이밍 및 메서드의 역할등 잘 되어있는지 기준을 세우신걸로 판단하고 합쳐보시면 좋을것 같습니다!
***
스텝 1 고생 많으셨어요ㅎㅎ
컴파일이 되지 않기에 우선은 request Changes로 남겨두겠습니다🥲
재 리팩토링이 끝나면 리뷰 재요청을 해주시면 확인하겠습니다!
화이팅이에요🥳🥳

2022-05-31 10:49 UTC, Hugh-github commented on Calculator/Calculator/Model/Operator.swift
>  enum Operator: Character, CaseIterable, CalculatorItem {
네 CalculateItem으로 수정했습니다.
충돌로 인해 코드를 수정할 때 확인을 못한 것 같습니다.

2022-05-31 10:49 UTC, bar-d commented on Calculator/Calculator/Model/ExpressionParser.swift
>          }
처음 그린이 제시해준 방안과 같이 코드를 작성하였는데, 디버깅을 한다면 고차함수가 나누어져 있어야 더 에러가 어디서 나는지 확인을 할 수 있다고 생각하여 위와 같은 방식으로 상수를 선언해주어 코드를 두 번 나누어 작성하게 되었습니다.  
가독성 면에서는 그린이 제시해준 방안이 더 좋다고 생각합니다.

2022-05-31 10:50 UTC, Hugh-github commented on Calculator/Calculator/Model/ExpressionParser.swift
>          return formula
수정했습니다 ☺️

2022-05-31 10:50 UTC, Hugh-github commented on Calculator/Calculator/CalculatorViewController.swift
> +    private var subStackView: UIStackView {
감사합니다 👏👏👏

2022-05-31 11:19 UTC, Hugh-github commented on Calculator/Calculator/CalculatorViewController.swift
> +        } catch {
이상하다는 생각이 들어 큐와 관련된 에러들은 result에서 catch 해주고 Operator와 관련된 오류들은 Controller에서 Catch 하도록 수정했습니다.
큐와 관련된 에러들을 result()에서 catch 하니까 코드의 가독성도 떨어지고 더 많은 에러를 던지는 일이 발생했습니다.
UML을 따라 함수를 구현하다 보니 함수 또한 너무 많은 기능을 한다는 느낌을 받았습니다.
코드의 가독성이 떨어져도 에러를 이렇게 처리하는 게 맞는지 궁금합니다.

2022-05-31 12:22 UTC, Hugh-github commented on Calculator/Calculator/Model/Error/QueueError.swift
> +    case wrongOperands
확인해 보니 empty 같은 경우 사용하고 있지 않아 제거해 주었습니다.

2022-05-31 12:25 UTC, Hugh-github commented on Calculator/Calculator/CalculatorViewController.swift
> +            operandsTextLabel.text? = OperatorError.devideFail.errorDescription
catch 하는 과정에서 Error case를 따로 정의해 추가적인 에러에 대해서 다른 메시지가 출력되도록 수정했습니다.

2022-05-31 12:27 UTC, Hugh-github commented on Calculator/Calculator.xcodeproj/project.pbxproj
>  				726D7CB4283363F700F87D86 /* Model */,
모델 폴더와 하위에 존재하던 Extension 폴더를 제거해 주었습니다. conflict를 해결하는 과정에서 미숙해 발생한 문제점인 것 같습니다.

2022-05-31 12:40 UTC, bar-d commented on Calculator/Calculator/Model/ExpressionParser.swift
>          return formula
현재 비어있는 Double+extension 파일에 함수로 분리를 하여 넣어주었습니다..!

2022-05-31 12:48 UTC, Hugh-github commented on Calculator/Calculator/CalculatorViewController.swift
> +        guard let formattedResult = numberFormatter.string(for: result) else { return }
Double에서 extension을 통해 formatText라는 구현해 함수의 기능을 분리했습니다.

2022-05-31 12:51 UTC, Hugh-github commented on Calculator/Calculator/Model/String+extension.swift
> +extension String {
그린의 말처럼 수정했습니다.
스타일 차이라고 하니 참고하겠습니다!

2022-05-31 12:52 UTC, Hugh-github commented on README.md
> +	- 현업에서는 어떻게 코드를 통합하는가?
감사합니다 👏👏👏

2022-05-31 13:08 UTC, Hugh-github commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        deQueueStack = []
그린이 바드에게 주신 문서를 보면  저희가 작성한 코드 같은 경우 재할당을 해줘야 하는데 removeall()을 사용할 경우 재할당을 해주는 것이 아닌 내부에 있는 element를 제거해 주는 것 같습니다.
혹시 저희가 해당 문서를 제대로 이해한 게 맞을까요?
https://stackoverflow.com/questions/31183431/swift-delete-all-array-elements
https://stackoverflow.com/questions/57788602/which-one-is-better-removeall-of-array-or-initialising-the-array-again

2022-05-31 13:15 UTC, Hugh-github commented
이번 프로젝트 PR을 보내면서 conflict가 발생했습니다. conflict를 해결하는 과정에서 저희의 실력이 미숙해 프로젝트 파일이 겹치고 누락된 부분이 존재했습니다. 

저희가 ScrollView에 추가될 StackView와 UILabel을 연산 프로퍼티로 선언해 사용했는데 Cocoa Touch Class를 이용해 각각의 타입을 만들어 사용하는 게 더 좋은 방법일지 궁금합니다.

2022-06-01 01:45 UTC, GREENOVER commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        deQueueStack = []
네 잘 이해하셨다고 보여요!
그랬을때 어떤게 더 적절하다고 생각하시나요~?

2022-06-01 01:49 UTC, GREENOVER commented on Calculator/Calculator/CalculatorViewController.swift
> +        } catch {
음 제 생각엔 결국 최상단 즉 호출의 첫 시작을 일으키는 부분에서 모든 에러 처리를 해줘야 적절하지 않을까 싶습니다!

2022-06-01 02:17 UTC, GREENOVER approved these changes
@Hugh-github @bar-d 
고생하셨씁니다!
그런데 코멘트에서는 수정이 이뤄졌다고 달려있는데 실제 코드에서 반영이 안된 부분들이 조금 있는것 같습니다🙋🏻
그 외 코멘트 질문에 대해서는 리코멘트로 답변 드렸습니다..!
***
우선 PR 코멘트 질문에 대한 답변부터 드리겠습니다~!
저는 우선 코드로 뷰를 선언하고 그려주는걸 좋아해요.
이것도 정말 상황의 차이이기에 어떤것이 더 좋다 말다 딱 명확하게 말하기는 어렵다고 생각해요.
즉 코드로 뷰를 짜냐 스토리보드로 뷰를 짜냐 이 차이에서 파생된다고 보여요.
둘다 확실히 장단점은 가지고 있다고 보입니다.
그럼에도 불구하고 저는 코드로 뷰를 짜는것을 선호하고 이점이 더 크다고 생각해요🙋🏻
여러분들도 이번 프로젝트를 진행하시면서 두 방법 모두 조금씩 사용을 해보셨던것 같은데 역으로 여러분들은 어떤것이 더 괜찮았고 추후에 프로젝트에서 뷰를 만들어 제공하는것이 아닌 전체적으로 다 직접 만들어줘야한다면 어떤 방식을 채택하실것 같나요?
한번 두 방식의 차이에 대해 학습 및 인지해보시면 여러분들만의 기준이 생길것 같습니다🙌
***
현재 코멘트로도 다시 남기긴 했지만 두가지 처리는 되어야 할것 같아요..!
1. 계산 로직의 결함이 있어 보입니다😭
- 기존 코멘트에 재코멘트로 단 부분이 있는데 확인 부탁드려요..!
2. 테스트가 정상적으로 되시나요?
- 최초 PR 코멘트로도 남겨드렸는데 답변 및 수정된것이 없어 질문 드립니다ㅠ
아마 안되실것 같은데 그 이유는 아래처럼 스킴을 보면 바드가 예전에 만드셨던 Tests들에 대해서만 추가되있고 해당 테스트들은 현재 없습니다.
즉 지금 FomularTest 자체가 스킴에 없을거에요🥲
![스크린샷 2022-06-01 오전 11 15 06](https://user-images.githubusercontent.com/72292617/171314430-c6583d0d-33ad-437b-99ec-c6af33122bed.png)
더불어서 병합을 하고 난 뒤 테스트 코드들이 많이 사라진 느낌이에요ㅠ
테스트 코드도 다음 스텝에서 보완되면 더 좋을것 같아요!
***
다시 한번 고생 많으셨고 우선 해당 스텝은 머지하겠습니다!
이후 스텝에서 리팩토링을 전체적으로 해보시면 좋겠습니다🙌

2022-06-01 02:17 UTC, GREENOVER commented on Calculator/Calculator/CalculatorViewController.swift
> +            operandsTextLabel.text? = OperatorError.devideFail.errorDescription
![스크린샷 2022-06-01 오전 11 00 54](https://user-images.githubusercontent.com/72292617/171313013-475b0a71-b5eb-43c7-85f5-61d553223e47.png)
이럴경우도 존재하네요!
부호를 붙여준게 아닌 8 마이너스 8 마이너스 처럼 순서를 입력하면 계산결과가 올바르지 않습니다.
추가로 아래와 같이 에러가 나지 않아야됨에도 에러가 나네요🥲
계산 로직에 결함이 있다고 보입니다ㅠ
![스크린샷 2022-06-01 오전 11 04 17](https://user-images.githubusercontent.com/72292617/171313371-e97bb947-0432-4686-8740-74fcd61834f7.png)

2022-06-01 02:17 UTC, GREENOVER commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    public mutating func clearAllStacks() {
아직 수정이 이뤄지지 않은것 같은데 맞을까요?

2022-06-01 02:17 UTC, GREENOVER commented on Calculator/Calculator/Model/Error/QueueError.swift
> +    case wrongOperands
아직 수정이 안이뤄진것 같습니다🙋🏻
그런데 empty의 케이스가 사용되지 않는것은 로직의 결함인지 아니면 정말 사용할 필요가 없는 로직인지 궁금합니다.

2022-06-01 02:17 UTC, merged