계산기  II [STEP 1]  Kiwi, 웡빙
yagom-academy/ios-calculator-app pull request #289
Opened 2022-05-31 02:35 UTC by kiwi1023

# 계산기2 STEP1
@jryoun1 안녕하세요 제이크! Team Step1 PR 남깁니다! step1에서는 합치는걸 위주로  진행을 하였고요! step2부터는 제이크가 주신의견과 저희의 생각을 토대로 리펙토링 및 디벨롭을 진행할 예정입니다! 잘 부탁 드립니다! 아 또한 Kiwi의 프로젝트가 merge안된 시점에서 프로젝트를 진행하였었는데 PR을 하려고 보니 충돌이 발생하여 branch를 지웠다가 다시 생성해서 PR을 보내 커밋이 한번에 많이 이루어지게 되었습니다..

## 고민한점 🧐

- 리스트 구현방식

kiwi의 리스트 구현 방식은 LinkedList를 사용하였으나, LinkedList의 특성상 Nord의 타입이 Class여야만 했었는데, 이경우 아무리 LinkedList와 Queue를 Struct로 구현할 지라도 Nord의 타입으로 인해 Class처럼 참조타입의 성격을 가지게 되었습니다.

그러나 저희의 생각은 새로운 타입을 구현할 때에는 Struct와 같은 값타입으로 구현해야 된다고 생각해서, 웡빙의 더블스택을 리스트의 구현방식으로 채택 하였습니다!

- expressionParser 에 들어가는 string 데이터 저장 방식 

kiwi의 방법인 "변수에 저장" 을 사용 했습니다. 

## 버그수정 🐛

- 테스트코드 수정

더블스택으로 모델을 변경한 뒤, 기존에 LinkedList에 대한 테스트를 더블스택에 대한 테스트코드로 바꿔 주었습니다. 

- 문자열 내 "," 값 제거

kiwi의 쉼표제거 방식이 기존의 메서드를 활용하여 좀더 간편히 제거 할 수있다는 생각에 kiwi의 방식을 따르기로 하였습니다. 다만 Step2과정에서 범용성 차원에서 Stiring을 extension 해주는 과정을 고려중에 있습니다.
```swift=
.replacingOccurrences(of: ",", with: emptyString)
```
- didOpearatorButtonTapped() 버그 수정

현재 operandLabel 값이 0일 경우 부호만 바뀌도록 해야 하는데, 부호를 바꾸면 0이 계속 스택에 추가되는 오류를 수정했습니다

- 다른 "-" 기호

코드 병합이 이루어진 후, 웡빙의 Operator모델에서 사용하던 "-" 기호와 kiwi의 ViewController에서 사용하는 "-" 기호가 달라 오류가 났습니다

- NaN 오류 발생시 

NaN 오류 발생이후 숫자 버튼을 눌르면 초기화가 되게 설정을 해주었으나, 연산자 버튼에 대한 설정을 안해 주어서 추가적으로 진행하였습니다

2022-06-01 12:05 UTC, jryoun1 requested changes
안녕하세요 @kiwi @wongbingg 
계산기II step1 고생하셨습니다.

현재 코드가 수정전과 수정후가 섞여있는 것 같아서 합치는 과정에서 문제가 발생한 것 같네요. 
확인부탁드립니다. 

또한 프로젝트 제약사항에 아래와 같은 항목이 있는데 지켜지지 않은 것 같은데 이유가 있을까요? 👀
두 분이서 코드를 합치는 과정에서는 함께 설명하면서 진행이 된 것인지 궁금하네요 🤔
> 커밋은 짝꿍과 번갈아가며 남깁니다
서로 코드를 설명하고 비교하여 더 나은 코드로 합칩니다
한 캠퍼의 코드로만 합치는 일은 없도록 합니다
한 모둠원의 코드 비율이 70%를 초과할 수 없습니다


## 에러 🚨
1. 현재 숫자의 입력이 최대 17자리까지밖에 안되고 있습니다. 그리고 아래의 그림과 같이 숫자를 계속 입력하다보면 16번째 이후에 0이 자동으로 붙는 현상이 발생하고 있습니다.

<img src="https://user-images.githubusercontent.com/45090197/171399755-7635ee59-2ec9-4fec-a59b-a51aa7f51edd.png" width="230" height="450">

2022-06-02 04:32 UTC, wongbingg commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +//  Created by Kiwi, Wongbing
감사합니다 ! 👍👍

2022-06-02 04:39 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
>  //  Calculator - ViewController.swift
수정했습니다!

2022-06-02 04:58 UTC, wongbingg commented on Calculator/Calculator/Controller/CalculatorViewController.swift
>      @IBAction private func didremoveAllButtonTapped(_ sender: UIButton) {
카멜 케이스를 깜빡 했군요 ! 수정 했습니다 ㅎㅎ

2022-06-02 05:15 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +
가드문은 보통 한줄로 표현하고 if 문일때는 개행을 해주는 편입니다!

2022-06-02 05:15 UTC, wongbingg commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private let zero: String = "0"
기존에 머지가 되지 않은 상태인 키위의 "브랜치1"를 시작점으로 새로운 "브랜치2"를 만들어 계산기 ll 스텝을 진행하고, 키위의 "브랜치1"이 머지를 받은 후에, 저희가 미리 작업 했던 "브랜치2" 를 "브랜치1"에 머지 하려는 과정에서 충돌이 일어나게 되어, "브랜치2" 의 작업내용을 머지하는 것이 아닌 아예 통째로 복사 붙여넣기를 "브랜치1" 에서 진행하여, 이런 오류가 났던 것 같습니다 .

2022-06-02 05:15 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private var isNumberTapped : Bool = false
수정하였습니다!

2022-06-02 05:22 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private let zero: String = "0"
저의 개인프로젝트 step3가 머지 되지 않은 상황에서 team 프로젝트 주간이 시작되어 제 레포지토리에서 새로운 브랜치를 생성한다음 팀프로젝트를 진행하였었습니다. 그러나 제 step3가 머지된 이후 team 프로젝트 step 1을 PR을 보내려 보니 충돌이 일어나서 PR을 보낼 수 없었습니다 그래서 저희는 team 프로젝트 코드를 복사한후 브랜치를 삭제한다음 다시 브랜치를 step3 머지 이후 새로 파서 PR을 보내는 과정에서 한번에 커밋이 이뤄지고 이러한 상황이 일어나게 된겁니다.

2022-06-02 05:23 UTC, wongbingg commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +        try super.setUpWithError()
재정의 키워드인 override를 사용할 때에, 상속받은 부모 메서드의 특성을 가져온 뒤에 재정의 해주는 것이 안전하다 생각되어 super 호출을 해주었습니다. 😊😊

2022-06-02 05:32 UTC, kiwi1023 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if operandLabel.text == failedResult {
수정했습니다 !

2022-06-02 05:35 UTC, wongbingg commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +class CalculatorItemQueueTests: XCTestCase {
테스트 파일도 더이상 상속할 필요가 없으므로 final 키워드를 붙여주는군요! 새롭게 배웠습니다 ! ㅎㅎ 🫡

2022-06-02 05:55 UTC, wongbingg commented
안녕하세요 제이크!  에러사항을 제외한 코멘트 부분에 대한 수정이 이루어졌습니다. 최대 17자리까지 표현되는 에러사항은 step2 리팩토링 단계에서 한꺼번에 처리하는 것 이 좋다 생각하여 남겨 두었습니다.

2022-06-02 05:57 UTC, kiwi1023 commented
또한 숫자가 16자리 까지 표현되는 현상은 Double(?)의 특성으로 들었는데(이후 반올림은 numberFormmater때문으로 생각하고 있습니다) 혹시 이부분에 대해서는 어떻게 생각하시나요?

2022-06-02 11:57 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    private let zero: String = "0"
넵 확인감사합니다 🙇🏻‍♂️
이런 실수가 발생할 순 있지만, PR을 보내기 전에는 적어도 자신이 수정한 코드가 제대로 돌아가는지, 제대로 수정이 되었는지 확인하는 것은 협업에 있어서 중요한 부분이라고 생각합니다. 그렇지 않으면 다른 팀원들은 돌아가지 않거나, 의도되지 않은 코드를 확인하는데 시간을 낭비할 수 있습니다. 다음부터는 잘 확인해주세요🙏🏻

2022-06-02 12:02 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +
제가 말씀드린 부분은 initiateCaculator() 함수 내부에서는 if문 블럭 안에 줄바꿈이 없이 작성되고, 
makeValidNumber() 함수 내부에서는 if문 블럭안에 코드 한 줄씩 줄바꿈이 있는 경우가 있고 
전반적으로 코드 전체에서 줄바꿈에 대해서 통일성이 없는 것 같아서 여쭤보았습니다. 
```swift
private func makeValidNumber() {
        guard let currentOperandText = operandLabel.text else { return }

        if currentOperandText.contains(",") {
            operandLabel.text = (operandLabel.text ?? emptyString).replacingOccurrences(of: ",", with: emptyString)
        }

        if currentOperandText.contains(".") == false {
            let userInputNumber = makeDouble(number: (operandLabel.text ?? emptyString))

            guard let validNumber = userInputNumber else { return }

            let number = doNumberFormatter(number: validNumber)

            operandLabel.text = number
        }
    }

//...
    private func initiateCaculator() {
        guard let currentOperatorText = operatorLabel.text else { return }

        if inputStackView.subviews.isEmpty == false, currentOperatorText.isEmpty {
            removeStack()
            operandLabel.text = emptyString
            userInputNumber = emptyString
        }
      // ...
}
```

2022-06-02 12:59 UTC, jryoun1 approved these changes
키위 웡빙 두 분 모두 고생하셨습니다. 
다만 **kiwi의 계산기 I step3**에서 수정하셨던 convention 및 수정 사항들이 적용되지 않은 부분들이 많이 보입니다. 다음 스텝에서 확인하고 반영해주세요!

> 숫자가 16자리 까지 표현되는 현상은 Double(?)의 특성으로 들었는데(이후 반올림은 numberFormmater때문으로 생각하고 있습니다) 혹시 이부분에 대해서는 어떻게 생각하시나요?

넵 말씀하신 것처럼 16자리 이상에서는 자동으로 반올림이 되기 때문에 20자리까지 표현하는 것만 다음 스텝에서 확인해주시면 될 것 같습니다 👍🏻
step1은 여기서 머지하겠습니다!

2022-06-02 12:59 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard operandLabel.text != "NaN" else { return }
하드 코딩된 부분이 남아있네요 🤔

2022-06-02 12:59 UTC, jryoun1 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard operandLabel.text != "NaN" else { return }
여기도 동일합니다.

2022-06-02 12:59 UTC, merged