# 계산기2 [STEP 1, 2]: 나이든별, 민쏜
yagom-academy/ios-calculator-app pull request #306
Opened 2022-06-05 15:09 UTC by OldStarKR

@protocorn93 안녕하세요~~ 계산기2 프로젝트 진행이 늦어져서 죄송합니다🥲 이번에도 잘 부탁드리겠습니다!!

@minsson @OldStarKR
### 계산기 2 프로젝트 수행 중 작업한 내용
* 나이든별의 코드에 민쏜의 아이디어를 결합하는 형태로 진행되었습니다.
    * 소수점(.)이 여러 번 찍히지 않는 문제를 해결하기 위해, `firstDecimalPointInCurrentNumber` 프로퍼티를 만들어서 조건으로써 적용했습니다.
    * 소수점을 찍었을 때, 이어지는 숫자를 입력하지 않으면 점이 화면에 뜨지 않는 문제를 수정했습니다.
    * 하드코딩되어 있는 여러 가지 값들을 네임스페이스를 활용해 정리해 주었습니다.
    * 불필요하게 오류를 던지는 부분을 많이 제거했습니다.
    * = 연산자를 사용해 값이 도출되었더라도, 이후에 연산자를 추가로 입력해서 연산을 할 수 있도록 바꾸었습니다.
    * 부호 바꾸기 버튼을 두 번 눌렀을 때 다시 양수로 바뀌지 않는 문제를 해결했습니다.
* 다양한 의견교환을 통해 리팩토링했습니다.
    * `currentNumber`가 `NaN`이나 `Err`가 아닌지 검증하는 과정을 따로 메서드로 빼서 기록했습니다.
    * 연산자의 '번역' 과정을 제거했습니다. `Operator`의 `rawValue`를 UI에서 사용되는 연산자와 동일하게 변경해 코드를 더 간결하게 만들고, 이를 통해 가독성의 향상을 도모했습니다.

---

### 고민한 점
* 스크롤 뷰를 맨 밑까지 내리는 것에 대해 고민했습니다.
    * 나이든별에게 이전에 주신 피드백을 토대로, `bottomOffset`을 `CGPoint(x: 0, y: self.frame.maxY)`로 지정해서, 보편적인 경우에 스크롤 뷰를 맨 밑으로 내리는 것은 어려움 없이 할 수 있었습니다.
    * 다만, 처음 스크롤이 가능해지는 지점에서는 스크롤이 덜 내려가는 현상을 목격했습니다.
        * 예를 들어 1+2+3+... 계산을 진행하다 보면, 9를 더할 때 처음으로 화면을 벗어나게 되는데, 이 때 스크롤이 되지 않습니다.
    * 어떤 원인 때문에 이런 현상이 발생하는지 감을 잡지 못해서, 어떤 키워드로 검색해야 하는지 선정하지 못했습니다. 해당 부분에 대해 조언을 얻고 싶습니다.

![scrollviewstuck](https://user-images.githubusercontent.com/102375432/172056175-29427f45-01fd-4db0-9589-b67671587a8a.gif)

* 두 사람이 프로젝트를 풀어나간 방식이 매우 상이했으며, 이 때문에 합칠 때 고민이 많았습니다.
    * 나이든별의 코드에 민쏜의 코드를 더하는 방식으로 진행했지만, 이렇게 작업하기로 결정하는 명확한 기준이 부족했다고 느꼈습니다.
    * 이렇게 각자 작업하고 코드를 합치는 과정이 현업에서도 자주 있는 일인지, 이런 경우 어떤 것을 기준으로 삼아 작업을 하는지에 대해서 여쭤보고 싶습니다.
    * 혹시 가능하시다면 나이든별과 민쏜의 코드의 구조나 설계 측면에서 각각 어떤 장단점을 추출하면 좋을지 예시를 들어주시면 많은 도움이 될 것 같습니다.

2022-06-06 07:50 UTC, protocorn93 requested changes
이미 두 분의 코드베이스를 많이 봐와서 크리티컬한 코멘트는 많이 남기지는 못했네요. 

💪💪 두분 모두 고생하셨어요! 👏👏


# 고민한 점

> 스크롤 뷰를 맨 밑까지 내리는 것에 대해 고민했습니다.

이 부분에 있어 제가 제안드린 `max.y`는 임시 방편이라고 생각이 들어요. content size와 frame의 height를 비교해서 contentOffset을 지정해주는게 정석으로 보여요. 다만 이 부분에 있어서 저도 아직 상세히 디버깅해보진 못했으나, 스택뷰의 컨텐츠 사이즈가 스크롤뷰의 frame 사이즈보다 커지는 순간에 레이아웃에 대한 정보를 잘 모르고 있는 것 같아요. 

타이밍 이슈갖기도 하구요. 이 부분에 있어서는 일단 넘어가고 저도 시간 날 때 조금 더 살펴볼게요. 

> 이렇게 각자 작업하고 코드를 합치는 과정이 현업에서도 자주 있는 일인지, 이런 경우 어떤 것을 기준으로 삼아 작업을 하는지에 대해서 여쭤보고 싶습니다. 

이런 경우는 거의 없다고 보시면 되요. 사실상 비효율적인 행위니까요! 같은 기능을 두 사람이 같이(페어) 개발하는 것은 있어도, 각각을 서로 다르게 개발하는 일은 없다고 보시면 되요. 

다만 이러한 학습과정중에선 서로의 코드에 대한 공부도 있지만, 상대방을 설득시키는 과정도 중요하다고 생각해요. 사실 코드리뷰라는 것이 비슷한 행위니까요! 둘이서 합의한 최선의 방식을 채택하는 행위라고 생각해요. 

코드에는 정답은 없다고 생각해요. 항상 최선의 선택을 하는 것이라고 생각해요. 트레이드오프! 상대방을 설득시키도록 노력해보세요!

2022-06-06 07:50 UTC, protocorn93 commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +    private func gotResult() -> Bool {
보통 `got-`보단 `has-` prefix를 사용하는 것 같아요~

2022-06-06 07:50 UTC, protocorn93 commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +            }
면접관들이 질문하기 좋은 포인트 같아요. DispatchQueue.main.async를 사용한 이유부터 시작해서 정말 이곳에서 필요한지에 대해 두 분의 의견을 물어볼거에요. 그때 확실히 설득을 할 수 있어야해요.

그렇지 않으면 "그냥" 쓴 지원자가 되는 것이고, 그만큼 마이너스인 요소도 없는 것 같아요!

2022-06-06 07:50 UTC, protocorn93 commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +    }
다만 둘의 성격이 조금은 달라 이렇게 묶어두는 것에 고민이되긴하네요. 

저는 콜렉션 타입에 isNilOrEmpty를 만들어서 사용하긴해요. nil or empty와 nan or error가 비슷한 맥락인지는 저도 조금 고민이긴하네요.

2022-06-12 08:19 UTC, OldStarKR commented on Calculator/Calculator/Application/Domain/Namespaces/CalculatorConstants.swift
> +}
프로젝트 내에서 사용한 기록을 찾아 보니, `CalculatorViewController` 안에서만 사용되고 전혀 글로벌하지 않았습니다🥲 해당 부분 뷰 컨트롤러의 안쪽으로, `private enum`으로 빼 주었습니다. 저 개인적으로는 프로젝트들을 진행하면서 네임스페이스의 활용에 대해 많이 배우게 되네요..

2022-06-12 08:21 UTC, OldStarKR commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +    }
저희의 의도는, 계산기 내에서는 둘이 사실상 같이 움직이기 때문에 한 곳에 묶어서 빼 두자라는 생각이었습니다. 에러가 발생한 '상황'에 대한 검사라 그렇게 생각하게 되었던 것 같군요!

하지만, 어떤 맥락에서 결이 다르다고 말씀하셨는지는 알 것 같습니다. NaN은 계산기라는 체계 안에서 일어날 수 있는 분명히 드러나는 ‘0으로 나누기' 오류를 나타낸다면, Err은 소프트웨어로써 앱 안에서 일어나는 예기치 못한 에러를 나타내는 것에 가까운 것 같다- 라고 저희끼리 이야기를 나누어 보았습니다. 계산기 프로젝트를 수행하는 데에는 큰 문제가 없을 수도 있지만, 앞으로 더 규모 있는 프로젝트를 수행할 때는 더 주의해야 할 부분임을 인지했습니다.

2022-06-12 08:22 UTC, OldStarKR commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +        let operandNow = numberFormatter.string(for: operandData) ?? CalculatorConstants.zero
가장 고민했던 네이밍 두 군데에 대해 다 짚어주셔서 매우 감사하게 생각하고 있습니다😄 해당 부분의 변수명을 바꾸기 위해 메서드 안을 들여다 보니, `operatorNow`를 이제 사용하지 않고 있다는 것을 발견해, 최종적으로는 지워졌습니다.

2022-06-12 08:27 UTC, OldStarKR commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +        refreshNumberLabel(with: CalculatorConstants.dot)
레이블의 텍스트, 나아가 그것을 위해 `currentNumber` 프로퍼티를 너무 직접 건드리려고 했다는 생각이 들었습니다. 표시되는 숫자에 소수점도 함께 표시하고자 하는 과정에서, 예외로 삼아야 할 케이스에 대해 잘못 판단해서 벌어진 상황이라고 생각이 듭니다. 원래 숫자 포매터를 거치는 과정에서 문제가 생기는 부분은, 소수점을 찍고 나서 뒤에 아무런 숫자가 없을 경우였기 때문에, `refreshNumberLabel` 메서드 안에서는 `hasSuffix`를 통해 단지 맨 뒤에 "."을 달고 있는지만 체크해 주고, 그 케이스만 특수하게 취급하여 해결할 수 있었습니다.

2022-06-12 08:28 UTC, OldStarKR commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +    private func gotResult() -> Bool {
이 부분도 이름지을 때 고민했던 부분인데 알려주셔서 매우 감사드립니다☺️

2022-06-12 08:33 UTC, OldStarKR commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +            }
해당 부분에 대해서 많이 생각해보고 많이 의견을 나누어 보았는데요, 최종적으로는 빼기로 결정했습니다.

UI 관련된 부분에 `DispatchQueue.main.async`를 써줘야된다는 건 개인적으로 가지고 있는 일종의 원칙같은 것이었습니다. 다만 이번 피드백을 계기로, `DispatchQueue` 자체의 사용 목적에 대해 생각해봤습니다. 굳이 UI 관련된 작업을 할 때 `main` 큐를 불러오는 이유는, 데이터 로딩 등 시간이 오래 걸리고 무거운 작업을 하는 과정에서 UI가 영향을 받지 않게끔 하고자 한다는 것입니다. 즉  `main` 큐를 따로 불러와서 사용한다는 것은, 바꿔 말하면 `main`이 아닌 다른 큐에서도 작업할 만큼 내부적으로 작업해야 할 것이 많다는 의미이며, 이는 곧 다수의 스레드를 사용하고자 한다는 것입니다. 

계산기 프로젝트에 맞게 생각하자면, 계산기의 ui는 따로 외부의 데이터를 불러와서 새로고침하는 것은 아닙니다. 또한 다루는 데이터의 크기가 UI에 지장을 줄 정도로 크지도 않습니다. 따라서, 굳이 메인 큐를 불러와서 작업을 하지 않아도 작업에는 지장이 없겠구나~ 하는 생각이 들었습니다.

이를 계기로, 특정한 원칙에 너무 얽매이지 말아야 한다고 생각해봤습니다. 기술을 쓸 때 쓰는 것도 중요하지만, 안 쓸 때 안 쓰는 것도 중요하다는 생각을 해 봤습니다.

2022-06-13 14:19 UTC, protocorn93 commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +    }
네네. 어떻게 보면 사소하다고 볼 수 있는 부분이지만 그렇게 고민을 해보시는 과정이 나중에 큰 도움이 되실거에요!👍👍

2022-06-13 14:22 UTC, protocorn93 commented on Calculator/Calculator/Application/Presentation/ViewControllers/CalculatorViewController.swift
> +            }
네네. 다만 현재 코드를 보면 위의 코드는 메인 쓰레드에서 실행되고 있기 때문에 별도로 쓰레드를 지정해주지 않아도 메인 쓰레드에서 실행되게 되어있어요. 다만 이 코드가 async하게 동작해야 하는지에 대한 의문이었어요! 두 분의 의도도 충분히 이해했습니다👍

2022-06-13 15:14 UTC, merged