계산기 [STEP 1] rhovin
yagom-academy/ios-calculator-app pull request #307
Opened 2022-09-19 11:13 UTC by yuvinrho

@wonhee009 

안녕하세요 라자냐~ 로빈입니다.
이번 프로젝트 첫 PR 드립니다. 조금이라도 불편한 코드 있으면 코멘트 거침없이 마구마구 부탁드립니다. 코멘트로 맞는거 좋아합니다😆 잘부탁드립니다~~

# STEP 1

# 클래스 다이어그램
![step1_클래스_다이어그램](https://user-images.githubusercontent.com/49301866/191002263-90fae1a3-e645-4ddb-b94e-54c41ddea149.png)

# CalculatorItemQueue 구현
- `CalculatorItemQueue<T>`: 계산기가 입력받은 숫자와 연산자를 담기위해서 제네릭을 사용했습니다.
- `var enqueue: [T]` : 입력받은 숫자와 연산자가 저장되는 큐
- `var dequeue: [T]` : `enqueue` 에 있는 데이터를 내보내는 큐
- `pop()` 구현 : removeFirst()의 시간복잡도 O(n)이기 떄문에 `enqueue`, `dequeue`를 이용하여 시간복잡도 O(1)인 메소드를 정의하였습니다. 
```swift
private func pop() -> T? {
    if dequeue.isEmpty {
        dequeue = enqueue.reversed()
        enqueue.removeAll()
    }
    
    return dequeue.popLast()
}
```

2022-09-19 12:03 UTC, yuvinrho commented
@wonhee009 

안녕하세요 라자냐~ 로빈입니다.
이번 프로젝트 첫 PR 드립니다. 조금이라도 불편한 코드 있으면 코멘트 거침없이 마구마구 부탁드립니다. 코멘트로 맞는거 좋아합니다😆 잘부탁드립니다~~

# STEP 1

# 클래스 다이어그램
![step1_클래스_다이어그램](https://user-images.githubusercontent.com/49301866/191002263-90fae1a3-e645-4ddb-b94e-54c41ddea149.png)

# CalculatorItemQueue 구현
- `CalculatorItemQueue<T>`: 계산기가 입력받은 숫자와 연산자를 담기위해서 제네릭을 사용했습니다.
- `var enqueue: [T]` : 입력받은 숫자와 연산자가 저장되는 큐
- `var dequeue: [T]` : `enqueue` 에 있는 데이터를 내보내는 큐
- `pop()` 구현 : removeFirst()의 시간복잡도 O(n)이기 떄문에 `enqueue`, `dequeue`를 이용하여 시간복잡도 O(1)인 메소드를 정의하였습니다. 
```swift
private func pop() -> T? {
    if dequeue.isEmpty {
        dequeue = enqueue.reversed()
        enqueue.removeAll()
    }
    
    return dequeue.popLast()
}
```

# 테스트 코드 추가
- `test_큐에_데이터가_아무것도_없을경우_pop()` : 큐가 비어있는 경우 pop을 했을때 nil이 나오는지 확인
- `test_push_1_2_3_pop_1_2_3()` : 1,2,3 순서대로 큐에 푸쉬한 숫자가 1,2,3 순서대로 팝이 되는지 확인
- `test_queue_isEmpty_true()` : 큐가 비어있을 경우 isEmpty 프로퍼티가 true를 반환하는지 확인
- - `test_queue_isEmpty_false()` : 큐가 비어있지 않을 경우 isEmpty 프로퍼티가 false를 반환하는지 확인

2022-09-20 02:17 UTC, wonhee009 requested changes
수고하셨습니다~~
코멘튼 남겨두었으니 확인 부탁드려요~

2022-09-20 02:17 UTC, wonhee009 commented on Calculator/Calculator/Models/CalculatorItemQueue.swift
> +    private var dequeue: [T] = []
`enqueue`, `dequeue`를 프로퍼티로 선언하셨네요!
둘의 역할이 무엇인가요?

2022-09-20 02:17 UTC, wonhee009 commented on Calculator/Calculator/Models/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
`CalculaterItem`은 Queue가 다루는 "요소"가 따르는 프로토콜 아닌가요?

2022-09-20 02:53 UTC, yuvinrho commented on Calculator/Calculator/Models/CalculatorItemQueue.swift
> +    private var dequeue: [T] = []
`enqueue`는 push한 데이터를 저장만 하는 역할입니다.
`dequeue`는 pop을 할때 `enqueue`에 있는 데이터를 내보내기 위한 역할로 사용합니다~

2022-09-20 05:01 UTC, yuvinrho commented on Calculator/Calculator/Models/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
이전에 항상 구조체나 클래스가 프로토콜을 채택하는 것만 해봐서 요구사항을 잘못 이해했습니다😂
아래와 같이 수정하였습니다~
```swift
private var enqueue: [CalculateItem] = []
private var dequeue: [CalculateItem] = []

func push(_ element: CalculateItem)
func pop() -> CalculateItem?
```

그리고 이전에 사용한 테스트 코드는 추후 CalculateItem 프로토콜 구현 후 작성하기 위해 삭제하였습니다~

2022-09-20 23:32 UTC, wonhee009 approved these changes
수고하셨습니다:)

2022-09-20 23:32 UTC, merged