계산기 [Step1] 나무, 지원, 테리
yagom-academy/ios-calculator-app pull request #31
Opened 2021-06-23 03:06 UTC by taelee42

@TaeJoongYoon 

안녕하세요 Tyler 저희 계산기 프로젝트를 Step1으로 구현해봤습니다.
리뷰 잘부탁드릴게요😆😊

## 구현내용
아직 View 부분은 만들지 않았고 내부 모델 부분만 구현해 봤어요
저희는 2가지 타입을 만들었습니다.
Stack 타입으로 Stack자료구조를 구현해봤고요
Calculator 타입으로 계산기 모델을 구현했습니다.
Calculator 타입의 주요 역할은 크게 2가지를 구현해봤습니다.
  1. 중위연산 표기법으로 저장된 배열을 후위연산 표기법의 배열로 변환하는 함수 -> convertToPostfix()
  2. 후위연산 표기법의 배열을 계산해서 결과를 리턴하는 함수 -> calculatePostfix()

## 고민한 점 & 궁금한 점
1. struct 내부의 프로퍼티를 변경할 때 mutating 키워드를 사용하는데, 이때 바꾼값을 새로 할당 하는 것인지 궁금합니다.  그리고 class의 프로퍼티를 변경할 때는 mutating 키워드가 필요하지 않은데, 이는 그 프로퍼티의 주소에서 직접 값을 바꾸기 때문인지도 궁금합니다.  만약 그렇다면 프로퍼티를 자주 변경해야 하는 상황이라면 class 가 성능상에 이점이 있는것인가요?

2. tempStack에서 pop()을 하는 경우 String? 타입으로 리턴하는데요. 이를 언래핑하고 또 Double로 변환까지하다보니 아래와 같이 2번의 바인딩을 하였습니다.
이때 이름을 짓기가 매우 힘들었는데요. 아래처럼 같은 이름(operand1→ operand1, operand2-> operand2) 으로 변환하는 형태가 괜찮은지 궁금합니다.
```swift
guard let operand2 = tempStack.pop(), let operand1 = tempStack.pop() else {
    continue
}
if let operand2 = Double(operand2), let operand1 = Double(operand1) {
...
```

2021-06-23 14:33 UTC, TaeJoongYoon commented on Calculator/Calculator/Stack.swift
> +enum ErrorCases: Error {
Stack을 이용한 계산에서 발생할만한 에러 케이스들을 정리하셨군요 ㅎㅎ 좋습니다 👍

2021-06-23 14:33 UTC, TaeJoongYoon commented on Calculator/Calculator/Stack.swift
> +class Stack {
Stack 자료구조에 대해 class로 만드신 이유가 있을까요???

2021-06-23 14:33 UTC, TaeJoongYoon commented on Calculator/Calculator/Stack.swift
> +    var stack: [String] = []
Stack 자료구조의 내부list 객체는 외부에서 참조를 하면 안될것 같은데 접근제어자를 활용하면 어떨까요 ㅎㅎ

2021-06-23 14:33 UTC, TaeJoongYoon commented on Calculator/Calculator/Stack.swift
> +    }
단순히 값을 반환하는 함수는 연산 프로퍼티로 대체해도 좋을것 같습니다!

2021-06-23 14:34 UTC, TaeJoongYoon commented on Calculator/Calculator/Stack.swift
>      }
Stack자료구조에서 pop을 하면 지금과 같이 top에 있던 값이 빠지면서 반환하게 되는데 잘 적용된것 같네요 :)

2021-06-23 14:49 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +	var infixNotation = [String]()
접근제어자는 꼭! 신경써주세요 😄  물론 함수도 같이 봐주시면 더 좋습니다~!

2021-06-23 14:49 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +		return "*/".contains(first) && "+-".contains(second)
contains 함수를 이렇게 이용하다니.. 아이디어가 좋습니다 💯

2021-06-23 14:49 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +	func convertToPosfix() -> [String] {
postfix에서 t가 빠진것 같아요!

2021-06-23 14:50 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +			postfix.append(top)
코드상 강제언래핑을써도 에러가 나지 않을 상황에서도 이렇게 옵셔널 바인딩과 같이 안전한 언래핑 방법을 사용하시는 것이 좋습니다 💯

2021-06-23 14:53 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +            }
계산과정에서는 특별히 이상한 점이 보이지 않지만 강제 언래핑을 사용하지 않는 방향으로 수정하면 좋을것 같아요~

2021-06-23 14:55 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +					}
에러 상황에 대한 처리를 추가하셨다니 좋습니다 ㅎㅎㅎ

2021-06-23 15:01 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +	func pushOperator(to stack: Stack, postfix: inout [String], element: String) {
현재의 함수구현 그대로 간다면 함수 네이밍을 조금 수정할 필요가 있어보여요.
`push(operator: to: postfix:)`와 같은 형태가 좀 더 어순에 맞게 느껴지는데 이 부분은 세 분이 얘기해보시고 결정하시면 될것같아요~

2021-06-23 15:55 UTC, TaeJoongYoon requested changes
안녕하세요! @taelee42 @jsim27 @지원, 이번 계산기 프로젝트 리뷰를 맡은 타일러라고 합니다 :)
앞으로 2주동안 잘 부탁드리겠습니다~ 궁금한 점 있으시면 언제든 여쭤봐주세요 ㅎㅎㅎ

먼저 남겨주신 고민점에 대해 의견 공유드려볼게요!

---
## 1. struct 내부의 프로퍼티를 변경할 때 mutating 키워드를 사용하는데, 이때 바꾼값을 새로 할당 하는 것인지 궁금합니다. 그리고 class의 프로퍼티를 변경할 때는 mutating 키워드가 필요하지 않은데, 이는 그 프로퍼티의 주소에서 직접 값을 바꾸기 때문인지도 궁금합니다. 만약 그렇다면 프로퍼티를 자주 변경해야 하는 상황이라면 class 가 성능상에 이점이 있는것인가요?

struct는 값 타입이기 때문에 내부 프로퍼티들은 인스턴스 함수에 의해 값이 수정될 수 없습니다. 그래서 앞에 mutating 키워드를 붙이게 되는 것이죠. 이런 mutating 함수를 통해 값 변경을 실행하면 해당 함수가 종료될때 변경사항을 원래 struct에 재기록하게 됩니다. 혹은 함수 내에 self프로퍼티를 이용하면 새 인스턴스를 할당 시킬수도 있습니다. 이 내용은 아래 문서에서 **Modifying Value Types from Within Instance Methods** 부분을 보시면 좀 더 이해가 되실 것 같아요!
[Swift 공식문서 - Methods](https://docs.swift.org/swift-book/LanguageGuide/Methods.html)

그리고 class 같은 경우는 참조 타입이기 때문에 말씀해주신것처럼 mutating 키워드 없이도 인스턴스 함수를 통해 내부 프로퍼티 값을 변경할 수 있습니다. ㅎㅎ

struct에서 mutating 함수를 이용한 내부 값 변경도 내부적으로는 최적화를 해서 단순 값 변경에 있어서 성능상 이점은 어느 것이 더 좋다고 할 수는 없을것 같아요. 저희가 Swift에서 사용하는 기본 데이터 타입들도 struct로 되어있습니다. 그래서 단순 값의 변경이 잦은것보다는 값 타입 vs 참조 타입의 특성에 더 의존해서 결정하는 것이 좋아보여요! 만약 struct와 class의 선택 기준에 대해 아직 모호하다면 아래 문서를 참고해 보는것도 좋습니다 ㅎㅎ
[Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)

## 2. tempStack에서 pop()을 하는 경우 String? 타입으로 리턴하는데요. 이를 언래핑하고 또 Double로 변환까지하다보니 아래와 같이 2번의 바인딩을 하였습니다. 이때 이름을 짓기가 매우 힘들었는데요. 아래처럼 같은 이름(operand1→ operand1, operand2-> operand2) 으로 변환하는 형태가 괜찮은지 궁금합니다.

```swift
guard let operand2 = tempStack.pop(), let operand1 = tempStack.pop() else {
    continue
}
if let operand2 = Double(operand2), let operand1 = Double(operand1) {
...
```

음... 같은 변수명을 사용하는건 지양하는게 좋을것 같네요.
`operand2String` `operand2`같이 변수명을 바꿔도 되고
String에 대한 extension으로 `asDouble`같은 연산 프로퍼티를 만들거나 Calculator 내에 stack의 pop을 받아서 Double로 반환하는 함수를 만드는 등 피해갈 방법은 다양할 것 같아요! 세 분이 회의해보시고 적당한 방법으로 방향을 잡으시면 좋을것 같습니다 :)

---

우선 남겨주신 점들에 대해 간단히 의견 남겨봤습니다 ㅎㅎㅎ
그리고 코드를 보며 전체적으로 제안드려볼 몇가지가 생각났는데 이것도 같이 얘기나눠보시면 좋을것 같아요.

1. Operator 타입 만들기
현재는 operator 관리를 단순 string값으로 관리하고 계시지만 operator는 현재 "+ - * /" 4가지로 구성이 되어있고 우선순위가 정해져 있으며 연상 방법도 달라집니다. 이를 struct나 enum과 같이 타입화를 한 뒤에 `Comparable` protocol을 이용하면 코드가 훨씬 깔끔해 질것 같아요 :)

2. 접근제어자 관리
저번 프로젝트에서 은닉화에 대해 공부하셨던걸로 기억하는데요 ㅎㅎ 가볍게 접근제어자만 관리해주셔도 쉽게 적용할 수 있습니다. 이는 중요한 부분이기때문에 새로운 프로젝트를 시작하더라도 항상 신경써주시면 좋을것 같아요 ㅎㅎㅎ

3. 강제 언래핑 관리
커밋이 다 끝났을때는 결과적으로 강제 언래핑이 사라졌지만 각 커밋마다 강제 언래핑이 있는 경우가 많은것 같아요. 비록 결과적으로 사라졌지만 강제 언래핑에 대한 습관이 남을 가능성이 있어서 이는 지양해주시면 좋습니다 👍 



STEP1에 대한 첫 PR을 빠르게 보내주셨는데요, 그럼에도 불구하고 코드안에서도 고민의 흔적들이 남아있어서 너무 좋았습니다!
정답은 없으니 지금처럼 계속 깊은 고민끝에 좋은 코드들을 작성해서 보내주세요 :)
궁금하신 점이나 이해가 안가시는 점이 있다면 언제든 여쭤봐주세요 ㅎㅎㅎ

ps. 혹시 세 분의 indent 설정이 다르게 되어있을까요??? 커밋마다 indent변경도 따라와서 수정내역이 많이 보이네요..!

2021-06-23 15:55 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +    func moveNonPriorOperator(from stack: Stack, to postfix: inout [String], than element: String) {
예를들어 함수인자의 순서를 `moveLowerPriorityOperators(than: from: to:)` 처럼 바꾸면 어순이 좀더 맞을것 같아요!

2021-06-24 01:29 UTC, jyoon54 commented on Calculator/Calculator/Stack.swift
> +class Stack {
class가 참조타입이고 struct가 가 값타입이니까 프로퍼티도 그럴것이라 생각했고 직접 참조해 바꿔주는 class가 더 맞을것 같아서 그렇게 했습니다.  밑에 공유해주신 내용 읽어보고 좀 더 알아보겠습니다!

2021-06-24 01:29 UTC, jyoon54 commented on Calculator/Calculator/Stack.swift
> +    var stack: [String] = []
private로 접근제어 해주는게 좋겠네요!

2021-06-24 01:31 UTC, jyoon54 commented on Calculator/Calculator/Stack.swift
> +    }
이 함수와 top도 연산프로퍼티로 변경하였습니다

2021-06-25 07:51 UTC, taelee42 commented on Calculator/Calculator/Calculator.swift
> +	func pushOperator(to stack: Stack, postfix: inout [String], element: String) {
감사합니다. 말씀해주신쪽으로 변경해봤습니다~

2021-06-25 07:52 UTC, taelee42 commented on Calculator/Calculator/Calculator.swift
> +	func convertToPosfix() -> [String] {
오타가 있었군요! 감사합니다!!

2021-06-25 07:59 UTC, taelee42 commented
@TaeJoongYoon 
친절하고 꼼꼼한 리뷰 감사드려요!!
말씀해주신쪽으로 고쳐보았습니다. 
고치면서 들었던 생각들에 대해 아래 정리해봤습니다.

## 궁금한 점, 고민한 점

### 1. swift 파일들을 어떤방식으로 분류하면 좋은지 (예: Model 폴더, Error폴더 등을 만들기 vs 안만들고 그냥 프로젝트명 폴더안에 같이 넣기) 궁금합니다. 
항상 자세하게 폴더를 나누는것이 좋은 방식일까요? 그리고 enum과 Error, extension, protocol 등은 항상 파일로 분류해 주는것이 좋을까요?

### 2. 말씀해주신대로 Operator타입에 comparable을 채용해서 Operator간의 크기를 비교했습니다.

여기서 궁금한점이 있는데요.
현재의 코드에서는 `operator1 < operator2` 이런식으로 비교하게 되는데요. 이렇게 되면 의미적으로 **연산자 자체의 크기를 비교하는 뉘앙스의 코드**가 되더라고요.
그래서 다른 방식을 생각해봤는데요.

저희가 이미 구현해놓은 Operator의 우선순위를 나타내는 컴퓨티드 프로퍼티인 precedence를 사용해서 
`operator1.precedence < operator2.precedence`
요렇게 코드를 치면 오퍼레이터의 **우선순위의 높낮이를 비교하는 뉘앙스**를 주어 자연스러워지는것 같습니다. 
다만 이렇게 하니 operator간의 비교할 일이 사라져서 comparable 프로토콜을 안 쓰게 되어 타일러가 제안해주신 방향과는 다르게 가는거 같아 기존방법으로 선회했습니다.

혹시 타일러는 이부분에 대해 어떻게 생각하시는지 궁금합니다.

### 3. 저희가 구현한 함수중에 moveNonPrecedentOperator라는 함수가 있는데요. 인자의 이름이 너무길어져서 아래와 같이 줄바꿈을 했는데 이렇게 작성해도 괜찮은지 궁금합니다.

```swift
private func moveNonPrecedentOperator(than currentOperator: Operator,
                                      from operatorStack: inout Stack<Operator>,
                                      to postfix: inout [String]) throws{
        while let top = operatorStack.top, currentOperator <= top {
            guard let top = operatorStack.pop() else {
                throw ErrorCases.emptyStackAccess
            }
            postfix.append(top.rawValue)
        }
    }
```

### 4. 말씀해주신 클래스와 스트럭쳐를 언제 써야하는지에 관한 문서를 읽어봤습니다. 링크 감사드려요~
stack을 클래스에서 구조체로 변경하였습니다.
변경하다보니 Calculator타입도 문서를 생각하며 다시보니 딱히 클래스로 쓸 이유가 없는거 같은데 이것도 구조체로 변경하는게 나을까요?

2021-06-25 08:06 UTC, taelee42 commented on Calculator/Calculator/Stack.swift
> +enum ErrorCases: Error {
감사합니다! 😄

2021-06-25 08:07 UTC, taelee42 commented on Calculator/Calculator/Stack.swift
>      }
감사합니다! 😄
removeLast는 비어있을때 crash가 발생해서 popLast로 변경했습니다!

2021-06-25 08:07 UTC, taelee42 commented on Calculator/Calculator/Calculator.swift
> +	var infixNotation = [String]()
네~ 접근제어자를 신경써서 만들어봤습니다

2021-06-25 08:07 UTC, taelee42 commented on Calculator/Calculator/Calculator.swift
> +		return "*/".contains(first) && "+-".contains(second)
감사합니다! 😄

2021-06-26 03:38 UTC, TaeJoongYoon commented on Calculator/Calculator/Stack.swift
> +struct Stack<T> {
Generic 개념을 이용하셨군요! 좋습니다 ㅎㅎㅎ 💯 💯

2021-06-26 03:38 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +    private func moveNonPriorOperator(than element: String, from stack: inout Stack<String>, to postfix: inout [String]) {
inout 키워드를 사용할때는 메모리 접근에 대해 취약해질수가 있습니다. inout키워드를 회피하면서 이 함수를 재구성해보는건 어떨까요??? 자세한 내용은 아래 링크를 읽어보세요 ㅎㅎㅎ
[Swift - Memory Safety](https://docs.swift.org/swift-book/LanguageGuide/MemorySafety.html)

2021-06-26 03:40 UTC, TaeJoongYoon commented on Calculator/Calculator/Operator.swift
> +enum Operator: String, Comparable {
Comparable 프로토콜을 쉽게 구현하셨군요..! 제가 생각했던 아이디어와 일치합니다!

2021-06-26 03:40 UTC, TaeJoongYoon commented on Calculator/Calculator/Operator.swift
> +    var precedence: Int {
내부적으로 precedence라는 변수를 둬서 사용하는 입장에서도 안헷갈릴것 같네요 ㅎㅎㅎㅎ

2021-06-26 03:43 UTC, TaeJoongYoon commented on Calculator/Calculator/Operator.swift
> +    func calculate(lhs: Double, rhs: Double) throws -> Double {
계산과정을 Operator안에 정의함으로써 역할을 분리시킨건 매우 좋습니다 💯 
함수인자 네이밍에 대해서는 lhs, rhs는 단순히 좌/우 값이란 뜻이니까 기존에 operand1, operand2도 괜찮아보입니다 ㅎㅎ

2021-06-26 03:45 UTC, TaeJoongYoon commented on Calculator/Calculator/Model/Calculator.swift
> +        var operatorStack = Stack<String>()
tempStack보다 훨씬 의미있는 네이밍이 된것 같습니다 :)

2021-06-26 06:25 UTC, TaeJoongYoon commented on Calculator/Calculator/ErrorCases.swift
> +enum ErrorCases: Error {
이번에는 ErrorCases라는 네이밍을 좀더 의미있는 네이밍으로 변경해보는건 어떨까요???

2021-06-26 07:00 UTC, TaeJoongYoon commented on Calculator/Calculator/Calculator.swift
> +            guard let `operator` = Operator(rawValue: element) else {
변수명을 예약어로 하게되면 지금과 같이 ``을 같이 써줘야 하는 불편함과 이후에 헷갈릴수 있는 여지를 두기 떄문에 이는 피하는 것이 좋아 보입니다 ㅎㅎ

2021-06-26 07:10 UTC, TaeJoongYoon commented on Calculator/Calculator/Operator.swift
> +    }
현재 < 함수만 구현되어 있는데 이러면 .plus와 .minus에 대해 == 비교를 하면 true값이 나올까요?!?
만약 그렇지 않다면 추가적으로 어떤 함수를 구현해줘야 할까요??

2021-06-26 07:28 UTC, TaeJoongYoon approved these changes
안녕하세요 나무, 지원, 테리~
짧은 시간동안 피드백도 잘 반영해주시고 코드들도 더 깔끔하게 작업된것 같네요 ㅎㅎㅎ
이번 작업에서는 제가 적어드린 inout키워드 사용과 operator로 "="이 입력되었을때에 대한 것만 고민해주시면 될것 같네요 :)

남겨주신 궁금한 점에 대해 봐볼게요!

---
## 1. swift 파일들을 어떤방식으로 분류하면 좋은지 (예: Model 폴더, Error폴더 등을 만들기 vs 안만들고 그냥 프로젝트명 폴더안에 같이 넣기) 궁금합니다.

음.. 해당 enum, error, protocol 들이 프로젝트 전체적으로 영향을 주는지, 혹은 해당 파일내에 객체들에만 영향을 주는지에 따라 다를 것 같아요.
전체적으로 영향을 준다면 따로 파일을 두어서 관리하는게 나을 것 같고 해당 파일내에만 영향을 준다면 같은 파일에 둬서 private으로 제한하거나 특정 객체에만 영향을 준다면 객체 내에 선언하여 관리하는것도 방법인 것 같습니다 :)

## 2. 말씀해주신대로 Operator타입에 comparable을 채용해서 Operator간의 크기를 비교했습니다.

확실히 제안해주신 방법도 좋아보이네요.
제가 제안드린 방법은 Comparable 프로토콜을 숙지하고 있는 개발자들끼리는 이해하기 쉽고 코드도 간결해지는 장점이 있어보이고
여러분이 제안해주신 방법은 Comparable 프로토콜을 굳이 사용하지 않아도 되고, 의미있는 네이밍을 가진 변수를 사용함으로써 누가봐도 직관적으로 이해할 수 있는 장점이 있어보입니다 ㅎㅎ
어떤 방법을 선택하든 좋아보이네요. 두 가지의 활용방법에 대해서는 숙지하신 것 같으니 세분이 회의해보시고 방향을 결정해보시죠 :)


## 3. 저희가 구현한 함수중에 moveNonPrecedentOperator라는 함수가 있는데요. 인자의 이름이 너무길어져서 아래와 같이 줄바꿈을 했는데 이렇게 작성해도 괜찮은지 궁금합니다.

```swift
private func moveNonPrecedentOperator(than currentOperator: Operator,
                                      from operatorStack: inout Stack<Operator>,
                                      to postfix: inout [String]) throws{
        while let top = operatorStack.top, currentOperator <= top {
            guard let top = operatorStack.pop() else {
                throw ErrorCases.emptyStackAccess
            }
            postfix.append(top.rawValue)
        }
    }
```
보다는 줄바꿈을 아래와 같이 해주시는게 좋습니다.

```swift
private func moveNonPrecedentOperator(
      than currentOperator: Operator,
      from operatorStack: inout Stack<Operator>,
      to postfix: inout [String]) throws
    {
        while let top = operatorStack.top, currentOperator <= top {
            guard let top = operatorStack.pop() else {
                throw ErrorCases.emptyStackAccess
            }
            postfix.append(top.rawValue)
        }
    }
```

## 4. 말씀해주신 클래스와 스트럭쳐를 언제 써야하는지에 관한 문서를 읽어봤습니다. 링크 감사드려요~ stack을 클래스에서 구조체로 변경하였습니다. 변경하다보니 Calculator타입도 문서를 생각하며 다시보니 딱히 클래스로 쓸 이유가 없는거 같은데 이것도 구조체로 변경하는게 나을까요?

이후 STEP이 어떻게 완성될지 몰라서 확답을 못드리지만, 만약 Calculator의 결과값을 여러 객체에서 사용해야 한다면 지금처럼 class로 둬도 될것 같고 그게 아니라 그때마다 계산만 할 용도라면 struct로 바꾸어도 괜찮을것 같아요 ㅎㅎㅎ

—

2021-06-26 07:29 UTC, merged