계산기 [STEP1] 토털이
yagom-academy/ios-calculator-app pull request #310
Opened 2022-09-19 14:32 UTC by tottalE

@protocorn93 
안녕하세요 토털이입니다!
첫 PR 보냅니다!
첫 PR이라 짧지만 잘 부탁드립니다!

### UML
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/66786418/191173636-6c0c2def-5876-468e-9e28-b90366dfe14c.png">

### 고민이 있었던 지점
- linkedList를 큐에 어떻게 적용할까 고민이 많았습니다. 결국 링크드 리스트를 구현하고 구현한 링크드 리스트를 큐에 연결하여 사용하는 것으로 코드를 마무리 지었습니다. 그냥 리스트를 사용할 경우, 오버헤드가 발생할 것 같아 링크드 리스트로 구현해 주었습니다.
- 테스트 주도 개발 경험: 어떻게 테스트를 만들어주고, 그에 맞게 개발을 할지 고민이 많았습니다. 제가 하는 테스트가 맞는지 의문이 많이 들기도 했습니다.
- removeAll()에 대하여: removeAll에서 head와 tail의 node를 삭제하는 것으로 링크드 리스트를 비워주었는데, 과연 메모리 상에서 이 node는 삭제 되었을까? 하는 의문이 들었습니다.

2022-09-20 14:16 UTC, protocorn93 requested changes
수고많으셨어요~! 👍 링크드리스트도 직접 구현해보신 점 매우 훌륭해요! 실제로 많은 기업 면접자리에서 링크드리스트 라이브 코딩도 심심치 않게 등장하는 편이에요! 

---

## 고민한 점 


> 테스트 주도 개발 경험: 어떻게 테스트를 만들어주고, 그에 맞게 개발을 할지 고민이 많았습니다. 제가 하는 테스트가 맞는지 의문이 많이 들기도 했습니다.

커밋을 보면 크게 문제는 없어보여요. 지금처럼 천천히 연습해가면서 꾸준히 해보시면 될 것 같아요.


> removeAll()에 대하여: removeAll에서 head와 tail의 node를 삭제하는 것으로 링크드 리스트를 비워주었는데, 과연 메모리 상에서 이 node는 삭제 되었을까? 하는 의문이 들었습니다.

가장 단순한 방법은 Node의 deinit에 print문을 통해 확인해보는 방법이 있겠죠! 다만 참조에 대한 충분한 이해가 되셨으면 잘 삭제되는걸 예상해볼 수 있어요~ 

기본적으로 클래스 인스턴스는 참조 카운트가 0이 되어야 메모리에서 사라지는데 head가 nil이 되면 head가 가리키고 있는 Node 인스턴스의 참조 카운트가 0이 될 것이고 이것이 메모리에서 사라지게 되면서 연쇄적으로 메모리에서 사라지게 될 거에요!

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +    var value: String
`value`는 `let`으로 선언어도 될 것 같아요.

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +struct LinkedList {
`LinkedList`를 구조체로 구현해준 이유가 있을까요?

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +    init() {}
빈 생성자는 제거해줘도 무방해보여요

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +    mutating func push(_ value: String) {
이 메서드가 이후에 외부에서 사용될 일이 있을까요? 그렇지 않다면 접근제어자를 붙여주시는게 좋을 것 같아요~

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +    var value: String
또한 `Node`는 다양한 타입의 `value`를 담을 수 있도록 해주면 좋을 것 같아요. 제네릭을 활용해보시면 될 것 같아요.

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +    mutating func removeLast() -> String? {
이 메서드도 마찬가지로 이후에 외부에서 사용될 일이 있을까요? 그렇지 않다면 접근제어자를 붙여주시는게 좋을 것 같아요~

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.queue.head?.value, "3")
테스트 코드를 작성할 땐 given, when, then으로 구분해서 작성해주시는게 가독성이 좋아요. 
```swift
// given

// when 

// then
```

2022-09-20 14:16 UTC, protocorn93 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.queue.isEmpty, true)
`queue`는 숨기고 `sut`에 `isEmpty` 메서드를 만들어서 이를 통해 검증을 하는게 바람직해보여요

2022-09-20 14:46 UTC, tottalE commented on Calculator/Calculator/CalculatorItemQueue.swift
> +extension String : CalculateItem {}
네 분리 완료했습니다!

2022-09-20 14:50 UTC, tottalE commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var queue: LinkedList = LinkedList()
네 완료했습니다!

2022-09-20 14:59 UTC, tottalE commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.queue.head?.value, "3")
네! 테스트 요구사항에서는 주석을 처리하지 못해서 고려해서 개행해 두었습니다!

2022-09-20 15:02 UTC, tottalE commented on Calculator/Calculator/CalculatorItemQueue.swift
> +class CalculatorItemQueue {
final 클래스로 수정 완료했습니다!

2022-09-20 15:04 UTC, tottalE commented on Calculator/Calculator/LinkedList.swift
> +    var value: String
value 상수로 전환해주었습니다!

2022-09-20 15:10 UTC, tottalE commented on Calculator/Calculator/LinkedList.swift
> +struct LinkedList {
linkedlist는 CalculatorItemQueue내에서 값이 복사되어 바뀔일이 없다고 생각했습니다! 특별히 클래스를 사용할 이유가 없다고 생각해서 스트럭트를 사용해 주었는데 제 논리가 비약하죠? 허허 ㅠㅠ

2022-09-20 15:15 UTC, tottalE commented on Calculator/Calculator/LinkedList.swift
> +    mutating func push(_ value: String) {
네 알겠습니다!

2022-09-20 15:16 UTC, tottalE commented on Calculator/Calculator/LinkedList.swift
> +    mutating func removeLast() -> String? {
이 경우 테스트에서 tail을 확인할때 사용되어서 이 부분은 접근제어자를 붙여주지 않기로 했습니다!

2022-09-20 15:20 UTC, tottalE commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.queue.isEmpty, true)
네 그렇게 해 주었습니다!

2022-09-20 15:21 UTC, tottalE commented on Calculator/LinkedListTests/LinkedListTests.swift
> +class LinkedListTests: XCTestCase {
네 그렇게 수정해 보았습니다! 혹시 부족한 부분이 있으면 말씀해 주세요!

2022-09-21 01:13 UTC, protocorn93 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +class CalculatorItemQueue {
그리고 이건 비단 이 PR에서만 해당하는건 아니고 이후에 커리어를 시작하고서도 도움이 될 수 있는 PR 커뮤니케이션 방법 중 하나인데요 

> [2a7968f](https://github.com/yagom-academy/ios-calculator-app/pull/310/commits/2a7968f94548131a99d56e25353b57326dae032c) 여기에 수정했어요

라고 직접 스레드에 명시해주는게 코드 리뷰를 하고 수정한 부분을 확인하는 입장에서 더 편해요! 그렇지 않으면 다시 스크롤해서 하단으로 내려가 해당 커밋을 눌러서 확인하고 다시 돌아와야 하는 번거로움이 있을 수 있거든요!

2022-09-21 01:19 UTC, protocorn93 commented on Calculator/Calculator/LinkedList.swift
> +struct LinkedList {
이 프로젝트에선 충분히 그렇게 판단내릴 수 있을 것 같아요. 

하지만 구조체(값타입)내에서 클래스 인스턴스 프로퍼티(레퍼런스 타입, 여기선 `Node` 인스턴스를 가리키는 `head`, `tail`을 의미)를 가질 때는 주의해야해요. 

```swift
let linkedList1 = LinkedList() 
let linedList2 = linkedList1
```

이렇게 링크드리스트 객체를 복사해서 할당한다고 생각하지만 실제로 내부 레퍼런스 프로퍼티도 복사되고 이 복사된 레퍼런스 프로퍼티는 하나의 인스턴스를 가리키고 있기 때문에 `linkedList1`의 `head` 값을 변경하면 `linkedList2`의 값도 변경될 우려가 있어요. 

즉 예상치 못하게 동작할 수 있다는 점이 존재하죠! 이 부분도 참고해서 이후 프로젝트 진행하실때 유의해주시면 될 것 같아요!

2022-09-21 01:23 UTC, tottalE commented on Calculator/Calculator/CalculatorItemQueue.swift
> +class CalculatorItemQueue {
네 감사합니다! 다음부터 적용해서 해보도록 하겠습니다 :)

2022-09-21 01:24 UTC, tottalE commented on Calculator/Calculator/LinkedList.swift
> +struct LinkedList {
아 그렇네요! 값 타입이지만 안에 프로퍼티들이 인스턴스라서 자칫 잘못생각하면 저런 실수가 나올 수 있겠네요! 좋은 이야기 감사합니다!

2022-09-21 02:29 UTC, merged