계산기 [Step 1] Ayaan
yagom-academy/ios-calculator-app pull request #311
Opened 2022-09-19 15:08 UTC by oneStar92

@junbangg
안녕하세요 알라딘!! 저는 아얀이라고 합니다!!
앞으로 2주 동안 계산기 프로젝트 잘 부탁드립니다!!
늦은 저녁 PR은 너무너무너무너무 죄송합니다!!!
---
## Step 3: 재고 수정 기능구현

## ✏️ TodoList
- [x] TDD 시작하기
  - [x] 기존 프로젝트에 Test Target 추가
- [x] Queue 자료구조의 이해와 구현
- [x] List 자료구조 직접 구현해보기(선택)
  - [x] 리스트를 활용해 Queue 구현(선택

## Class Diagram
![](https://raw.githubusercontent.com/oneStar92/ios-calculator-app/Step_1/CalculateItemQueue_ClassDiagram.png)

## 🤔 고민했던 점
### Linked List와 Array
Array의 데이터 추가, 삭제, 탐색의 시간 복잡도는 추가하려는 데이터의 위치가 맨뒤면 O(1), 삭제하려는 데이터의 위치가 맨뒤가 아니라면 O(n), 데이터 탐색의 시간복잡도는 O(1)입니다. 하지만 Linked List는 추가하려는 데이터가 맨뒤, 맨앞인 경우 O(1), 삭제하려는 데이터가 맨 앞이라면 O(1), 탐색은 O(n)의 시간 복잡도를 가집니다.
계산기의 특성상 추가 및 삭제만 이루어지고 탐색은 불필요함으로 삭제시 시간 복잡도가 O(1)인 Linked List를 선택하여 Queue를 구현하였습니다.

## 🙏 조언을 구하고 싶은 부분
### TDD Test Case관련
현재 TDD를 통한 개발에 초점을 두고 코드를 구성해봤습니다.
Class Diagram을 토대로 코드를 작성한 후 -> 필요한 Test Case를 파악하여 추가 -> 각 테스트 케이스를 충족해 나아가면서 refactor. 순서를 이렇게 진행하였는데... 이게 맞는 순서인지 아직 잘 모르겠습니다... 알라딘의 생각은 어떤지 궁금합니다!!

2022-09-20 05:12 UTC, oneStar92 commented
- [6b638df](https://github.com/yagom-academy/ios-calculator-app/pull/311/commits/6b638dfc67e2c52169ed8d98792934dd3e1300f0) : PR요청드린 후 요구사항을 다시 읽어보니 'CalculatorItemQueue가 다루는 요소가 CalculateItem을 준수하는 한다.'를 잘못 해석하여 코드를 작성하여서 CalculateItemQueue에서 제네릭으로 선언된 T가 결국 CalculateItemQueue가 다루는 요소임으로 제네릭 T가 CalculateItem을 준수하도록 수정하였습니다.

2022-09-21 03:21 UTC, junbangg requested changes
수고하셨습니다~! 
몇가지 생각해보면 좋을것 같은 부분들에 대해서 댓글 남겨드렸습니다~!

그리고 질문 주신 `TDD` 는 잘 이해하고 계신것 같아요! 테스트를 먼저 만들어놓고 그 테스트를 통과할 수 있는 코드를 리팩토링을 거치는 사이클을 통해 코드를 완성하는 느낌스:)
근데 질문주신 내용중에
`Class Diagram을 토대로 코드를 작성한 후 -> 필요한 Test Case를 파악하여 추가 -> 각 테스트 케이스를 충족해 나아가면서 refactor`
첫번째 `Class Diagram을 토대로 코드를 작성한 후` 
여기서 "코드를 작성" 이 어떤 코드일까요??

궁금하신 부분은 디엠이나 코멘트로 부탁드릴게요! 수고하셨습니다~

2022-09-21 03:21 UTC, junbangg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_입력값_1_이_enqueue되어서_queue의_head의_data가_input과_같은가() {
메서드명이 자세해서 아주 좋은데 조금 더 `given` , `when`, `then` 을 구분 지을 수 있는 방법은 없을까요??

2022-09-21 03:21 UTC, junbangg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        var queue: CalculatorItemQueue<Int> = CalculatorItemQueue<Int>()
요 친구는 지금 메서드마다 생성되고 있네요!
어차피 테스트 대상은 `CalculatorItemQueue` 인데 이 친구를 전역으러 빼서 재활용하는게 어떨까요??  
`sut`와 `override func setUpWithError()`, `override func tearDownWithError()` 에 대해서 한번 알아봐보시면 좋을것 같습니다!

2022-09-21 03:21 UTC, junbangg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        queue.enqueue(input[2])
`for` 문을 사용하는건 어떨까요?!

2022-09-21 03:21 UTC, junbangg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        }
여기서는 `forEach` 를 잘 사용하셨네요!
위에서는 반복문을 사용 안한 이유가 따로 있으실까요?!

2022-09-21 03:21 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var tail: Node<T>? = nil
단순연결리스트, 이중연결리스트를 비교해보면서 고민해보셨을까요 이번에?!

2022-09-21 03:21 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +            tail = node
`tail = node` 는 아래 `else` 분기에서도 있네요?!

2022-09-21 03:21 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var count: Int = 0
그리고 `count` 를 만들어주신 이유가 있을까요?!(틀렸다는건 아닙니다!)

2022-09-21 03:21 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        guard let nowHead = self.head else {
`currentHead` 는 어떨까요 :)

2022-09-21 03:21 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
이 친구는 지금 이름이 `Queue` 인데 구현은 연결리스트로 보입니다~!
이렇게 하기로 선택한 이유가 있을까요?!

2022-09-21 03:52 UTC, oneStar92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var tail: Node<T>? = nil
단순연결리스트에 대한 이중연결리스트의 가장 장점은 특정 인덱스에 해당하는 값을 가져올때 즉 검색 기능의 시간 복잡도가 줄어드는거라고 생각합니다. 단순연결리스트는 검색은 O(n)의 시간 복잡도를 이중연결리스트는 O(n/2)의 시간 복잡도를 가지고 있기 때문이죠.
현재 요구사항에는 특정 인덱스 값에 접근하는 기능을 구현할 필요가 없다고 생각하여 단순연결리스트를 선택했습니다!

2022-09-21 03:55 UTC, oneStar92 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        }
코드를 작성하다보니 .. 3개는 손으로 작성할만 했는데, 그 이상이 되니 for문을 사용한것 같습니다...😂

2022-09-21 06:46 UTC, oneStar92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var count: Int = 0
private(set)을 지정하게 되면 get은 기본값인 internal로 접근 제한을 하여서 해당 모듈 전부에서 읽는것이 가능하게하고 set은 private로 접근 제한을 하여서 해당 코드 내부에서만 수정이 가능하게 제한하는 키워드로 알고있습니다.
이러한 기능을 하는 private(set)을 사용한 이유는 head, tail을 사용하여 unit test를 진행하기 위해서 사용했습니다.
count의 경우 모듈 내부에서 값을 읽어오는 경우가 있을 것 같아서 private(set)으로 지정해 주었습니다.
count를 만들은 이유는 차후에 Queue의 몇개의 요소가 들어있는지 확인할 경우가 있을 것 같아서 만들었습니다.

2022-09-21 08:33 UTC, oneStar92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func peak() -> T? {
[151ac7b](https://github.com/yagom-academy/ios-calculator-app/pull/311/commits/151ac7b9568e084cebdd5c5286d131a845951201) 네이밍 수정하였습니다!! 오타가 났네요 ㅠㅠ

2022-09-21 08:34 UTC, oneStar92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        guard let nowHead = self.head else {
[151ac7b](https://github.com/yagom-academy/ios-calculator-app/pull/311/commits/151ac7b9568e084cebdd5c5286d131a845951201) currentHead가 좀더 명확한거 같네요 ㅠㅠ

2022-09-21 08:35 UTC, oneStar92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +            tail = node
[fe64b14](https://github.com/yagom-academy/ios-calculator-app/pull/311/commits/fe64b145d465bbe33625ea448f998c1d82354d17) 좀더 좋은 방법으로 코드를 작성할 수 있어서 수정하였습니다. 어떻게 저 부분을 분리할까 고민하다가 겹치더라도 그냥 사용하였는데 생각을 좀더 해볼껄 그랬네요..

2022-09-21 08:37 UTC, oneStar92 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        var queue: CalculatorItemQueue<Int> = CalculatorItemQueue<Int>()
[6e85cb0](https://github.com/yagom-academy/ios-calculator-app/pull/311/commits/6e85cb05926b61d5563a406a0536ee25658fc73b) 코멘트 주신내용을 활용해서 수정하였습니다.
- `sut`: system under test의 약자
- `override func setUpWithError()`: test메소드가 실행시 마다 실행되는 메소드
- `override func tearDownWithError()`: test메소드가 종료시 마다 실행되는 메소드

2022-09-21 08:38 UTC, oneStar92 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        queue.enqueue(input[2])
[a3c4f79](https://github.com/yagom-academy/ios-calculator-app/pull/311/commits/a3c4f7981e943ac4bb4abfaceb46c189407e9473) 수정하였습니다!

2022-09-21 08:40 UTC, oneStar92 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_입력값_1_이_enqueue되어서_queue의_head의_data가_input과_같은가() {
[f2b6594](https://github.com/yagom-academy/ios-calculator-app/pull/311/commits/f2b65945a4eee19693b68d219b60ec21d208e6ed) 조금더 명확하게 수정하였습니다.
- `given`: ~을/을
- `when`: ~하면
- `then`: ~인가

2022-09-21 08:43 UTC, oneStar92 commented
Class Diagram을 토대로 코드를 작성한 후 -> 필요한 Test Case를 파악하여 추가 -> 각 테스트 케이스를 충족해 나아가면서 refactor
에서 코드작성 부분은 저는 코드의 뼈대만 작성하는 수준으로 이해하였습니다.

2022-09-22 13:43 UTC, junbangg approved these changes
수고하셨습니다..!다음 스텝 진행 해주시면 될것 같아요! 댓글 남긴가 참고해주세용

2022-09-22 13:43 UTC, junbangg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
구굳👍

2022-09-22 13:43 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var tail: Node<T>? = nil
흠 단순연결리스트랑 이중연결리스트에서 검색 복잡도를 각각 말씀해주셨는데!
왜 그렇게 생각하시는지가 궁금합니다..!
그리고 빅오 표기법에서 O(n) 이랑 O(n/2) 는 둘다 O(n) 입니다!앞에 붙은 상수는 의미가 없어요..! 왜 그런지 한번 공부해시는것도 좋을것 같아여👍👍

2022-09-22 13:43 UTC, merged