계산기 [STEP1] 제이푸시
yagom-academy/ios-calculator-app pull request #317
Opened 2022-09-20 07:22 UTC by jjpush

안녕하세요 @junbangg 알라딘!! 
처음 인사를 드리게 되었네요 반갑습니다! 😁

# UML

![](https://i.imgur.com/UKmxlrq.png)

# 🤔 고민한 점
## 순차리스트와 연결리스트

- **큐타입을 구현하기 위한 리스트 타입 대한 고민.**
큐타입 구현을 하기 위해서 리스트 타입에 대해 알아보고 순차리스트와 연결리스트로 나뉘는 걸 알게되었습니다.
이 중 순차리스트를 배열을 사용해서 구현 시, dequeue과정에서 O(n)의 시간복잡도를 가진다는 이유 때문에 연결리스트 방식으로 큐타입 구현을 선택했습니다.

- **연결리스트를 구현하면서 class vs struct**
연결리스트를 구현하면서 Node 클래스를 struct로 구현해보았는데
struct는 자신을 재귀로 가질 수 없고, 
이 Node Struct를 가지는 ItemList의 사이즈가 무한한 크기가 된다는 오류 때문에 class로 설정했습니다. 
아직 이해를 잘 못했지만 오류 때문에 class로 설정해 주었습니다.

# 🙇‍♂️ 조언을 얻고 싶은 점
- **UML은 언제 그리는게 좋은가?**

코드를 작성하면서 UML을 계속 수정하게 되거나 코드를 전부 작성한 뒤에 그리게 되는 경우가 많아지는 것 같습니다.🥲
그러다 보니 프로젝트를 시작함과 동시에 UML을 작성하는 것이 비효율적이라는 느낌을 받았는데요..
제 생각으로는 다른 사람에게 프로젝트에 대해 설명이 필요한 시점에 작성하면 좋다고 생각이 들었습니다. 어느 시점에 UML을 그리는 것이 적당한가요?

또, 만약 프로젝트를 시작할 때 UML을 그린다면 로직에 필요한 프로퍼티나 메서드가 머릿속에 잘 그려지지 않는 것 같습니다. UML을 그리는 팁 같은게 있을까요? 순서도를 그려본다던지..?

- **TDD기반 작업을 하는 법**

이번에 TDD를 알게 되어서 적용을 해 보았습니다.
처음 적용을 하다 보니 충분한 테스트 케이스가 적용되었는지 의문이 들어서 조언을 받고 싶습니다 😁

추가로 조언을 받고 싶은 내용입니다.
- 간단한 메서드의 테스트
    - 예를들어 isEmpty() 같은 메서드의 경우 head가 nil인지만 판단을 하는데 이런 메서드는 테스트가 필요없을 것 같은데 이런 메서드들도 테스트를 해 주는게 좋을까요?
- 테스트 메서드가 private 되어있는 경우에 테스트
    - private를 해제하거나 private(set) 설정을 한 후에 테스트 해주었는데 테스트를 한 후에 다시 private로 되돌려주어야 할지, 설계를 바꿔야할지 고민입니다. 어떻게 테스트를 하는게 좋을까요?

- 반복적인 모듈 import
    - 타입 별로 분리해서 테스트 파일을 만들어 주었는데 이렇게 하니 `@testable import 모듈` 코드가 반복되는 것 같습니다. 혹시 반복을 줄이고 싶다면 파일 하나에 여러 클래스를 작성하는 방법 밖에 없을까요?

이번 계산기 프로젝트 잘 부탁드립니다 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

2022-09-21 15:55 UTC, junbangg requested changes
수고하셨습니다!!
질문 주신 내용들 답변 드리자면

1. UML은 언제 그리는게 좋은가?
혹시 하시면서 `UML` 의 이점으로 느껴지신 부분은 없으셨나요??
물론 문서화의 목적이라면 처음부터 하는게 조금 비효율적으로 느껴질 수 있겠지만, 

`UML`이 좋은 이유는 설계에 있다고 개인적으로 생각해요!
객체지향에 대해서 공부를 충분히 하시고 프로젝트 시작 전, 또는 특정 기능을 개발하기 전에 `UML` 을 그려보시면 코딩하기가 굉장히 수월해진다? 라는 느낌을 받으실 수 있을것 같습니다! (제 생각ㅋㅋ)

2. TDD기반 작업을 하는 법
지금 테스트코드를 작성해주셨는데 
혹시 `given, when, then` 에 대해서 공부해보셨을까요??
테스트에서 정말 많이 쓰이는 패턴/컨벤션 인데 현업에서도 정말 많이 쓰인답니다!
테스트 코드에서 `given, when, then` 의 구조로 바꿔주시면 더 좋을것 같아요! 
아니면 혹시 그걸 안하신 이유가 있다면 이야기 해주시면 감사하겠습니다:)

- 간단한 메서드의 테스트
구현이 기본적이고 간단한 메서드가 있더라도 로직의 중요한 부분을 차지하고 있다면 충분히 테스트의 대상이 될 수 있다고 생각해요!
추후에 요구사항이 바뀌거나, 타입의 동작을 조금 바꿔야될 필요가 있어서 리팩토링을 수행했는데 핵심 로직인 메서드를 테스트 하면 더 안전하지 않을까요 그래도?! (아무리 기본적인 메서드더라도) 
이 또한 제 개인적인 생각일 뿐입니다~!

- 테스트 메서드가 private 되어있는 경우에 테스트
테스트의 가장 기본적인 원칙은 테스트코드와 실제 코드의 분리입니다!
그래서 실제 코드가 바뀌어야된다면 그게 의미 있는 테스트 코드일까 라는 생각이 드네요..! `private` 가 맞다면 그건 테스트에서 직접 접근을 안하는게 맞다고 생각합니다 개인적으로!

그리고 `TDD`라면 테스트 코드를 먼저 작성 하셨을텐데 그럼 `private` 가 되는지/안되는지는 그 뒤에 결정될 일 아니었을까요?! :)  (`TDD` 넘 어렵ㅎㅎ)

- 반복적인 모듈 import
`반복적인 모듈 import`를 원치 않는 이유가 있으실까요?!

2022-09-21 15:55 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
`isEmpty` 를 메서드로 만드신 이유가 있을까요?!

2022-09-21 15:55 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var count: Int = 0
`count` 를 사용하기로 하신 이유가 무엇인지 궁금합니다!

2022-09-21 15:55 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    var sut: CalculatorItemQueue<String>!
`sut` 를 잘 사용하셨군요 👍👍👍👍

2022-09-21 15:55 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func test_push50개_잘_들어가는지() {
"잘 들어가는지" 보다 조금 더 구체적인 네이밍은 어떨까요?!

2022-09-21 15:55 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    override func tearDownWithError() throws {
이 메서드가 필요한 이유가 무엇이라고 생각하시나요?!

2022-09-21 15:55 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.tail?.data, "4")
여기서 계속 `?` 를 사용하는게 과연 좋을지 모르겠습니다 🤔

2022-09-21 15:55 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.tail?.data, "4")
`n` 번째 원소를 확인하기 위해 `.` 으로 계속 접근하는것 말고 조금 더 유연한 방법은 없을까요?

2022-09-21 17:58 UTC, jjpush commented on Calculator/Calculator/Model/CalculateItem.swift
> +extension String: CalculateItem { }
Queue의 제네릭으로 CalculateItem을 채택한 타입만을 받을 수 있도록 `CalculatorItemQueue<Item: CalculateItem>` 처리를 해주었습니다. 
특히 String으로 한 이유는 1+2+3 같은 식이 들어올 경우 `["1", "+", "2", "+", "3"]` 이렇게 받아서 처리하면 타입 하나로 처리할 수도 있겠다 생각해서 String으로 채택해주었습니다!

2022-09-21 18:05 UTC, jjpush commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
첫번째는 기능분리가 이유였습니다. enqueue 메서드에서는 값을 큐에 넣는 작업을 하는데 큐가 비어있는지 확인하는 작업을 함께 한다는 것이 두가지 기능을 하고있다고 생각했습니다.

두번째는 반복되는 코드의 사용 때문이었습니다. 처음 작성했을 때는 enqueue뿐 아니라 dequeue에도 큐가 비어있는지 체크하는 작업을 한 후에 작업을 했었는데 빠른탈출과 가독성을 이유로 제거되었습니다. 그 부분에서 큐가 비어있는지 확인하는 작업이 중복되어서 메서드로 만들어두었습니다.

2022-09-21 18:17 UTC, jjpush commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var count: Int = 0
사실 clearQueue 메서드는 TDD 방식이 아닌 메서드를 작성하고 테스트를 했는데 반환값이 없다보니 테스트를 갯수로 했습니다 😅
이 것과 배열의 count가 있듯 큐에도 count는 큐의 필수요소 중 하나라고 생각한 점이 겹쳐서 count를 사용하게 되었습니다.

2022-09-21 18:17 UTC, jjpush commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    var sut: CalculatorItemQueue<String>!
감사합니다!! 😁😁😁😁

2022-09-21 19:02 UTC, jjpush commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    override func tearDownWithError() throws {
코드를 작성하면서 의문이 들었던 점이었습니다 
테스트 케이스 마다 순서가 
setUP - 테스트 진행 - tearDown 
으로 된다고 알고 있었는데 setUP할때마다 초기화를 해주니 nil을 굳이 해줄 필요가 없다고 생각했습니다

하지만 존재하는 이유는 있을 것 같아서 찾아보니
테스트 케이스를 종료하는 순간 임시파일을 정리하거나 테스트 중 필요한 데이터를 캡처해야할 때 사용한다는걸 찾았습니다

데이터를 캡처한다는 것은 뭔가 테스트에 사용된 값들로 분석하기 위해서 캡처 해서 사용한다는 것 같은데
임시파일을 정리한다는 뜻은 잘 이해가 되지 않았습니다 어떤 상황이 임시파일을 정리하는 순간인가요? 🤔

2022-09-21 19:10 UTC, jjpush commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.tail?.data, "4")
`?`를 통해서 계속 접근하지 않고 값을 넣은 후 while문으로 head가 nil일 때까지 뽑아내서 
값이 많더라도 유연하게 비교할 수 있도록 변경하였습니다.

```swift
func test_큐에_1_2_3_4_값을_넣으면_순서대로_1_2_3_4_들어있는지_확인() {
        // given
        let elements = ["1", "2", "3", "4"]
        var popedElement: [String?] = []
        
        // when
        elements.forEach { element in
            sut.enqueue(element)
        }
        
        while sut.head != nil {
            let element = sut.dequeue()
            popedElement.append(element)
        }
        
        // then
        XCTAssertEqual(popedElement, elements)
    }
```

2022-09-21 19:47 UTC, jjpush commented
>1. UML은 언제 그리는게 좋은가?
혹시 하시면서 `UML` 의 이점으로 느껴지신 부분은 없으셨나요??물론 문서화의 목적이라면 처음부터 하는게 조금 비효율적으로 느껴질 수 있겠지만, `UML`이 좋은 이유는 설계에 있다고 개인적으로 생각해요! 객체지향에 대해서 공부를 충분히 하시고 프로젝트 시작 전, 또는 특정 기능을 개발하기 전에 `UML` 을 그려보시면 코딩하기가 굉장히 수월해진다? 라는 느낌을 받으실 수 있을것 같습니다! (제 생각ㅋㅋ)

제가 문서화의 목적으로만 UML을 생각해서 비효율적 이라고만 느껴졌던 것 같습니다 ㅠㅠ 아직까지는 프로그램의 크기가 작아서 그런지 UML의 효과를 잘 느끼지 못하는 것 같습니다..만 그래도 좀 큰 프로그램을 작성해보거나 복잡한 설계를 가진 프로그램을 UML로 그려본다면 어떤 효과인지 알 것 같기도 합니다 ㅋㅋ 객체지향에 대한 공부가 좀 더 깊어지면 확실히 느껴지겠죠? 조언 감사합니다! 😁

>1. TDD기반 작업을 하는 법
지금 테스트코드를 작성해주셨는데혹시 given, when, then 에 대해서 공부해보셨을까요??테스트에서 정말 많이 쓰이는 패턴/컨벤션 인데 현업에서도 정말 많이 쓰인답니다!테스트 코드에서 given, when, then 의 구조로 바꿔주시면 더 좋을것 같아요!아니면 혹시 그걸 안하신 이유가 있다면 이야기 해주시면 감사하겠습니다:)

컨벤션으로 작성하는 것까지는 생각을 못하고 머릿속으로만 given, when, then을 생각하며 테스트를 짰습니다 🥲

given - 이런 가정에서
when - 이렇게 하면
then - 결과가 이렇다.

를 적용해서 

given에는 변수의 선언
when에는 테스트의 실행
then에는 결과 값을 넣어주었는데

`test_testWord를_50개_넣은_후_50개를_제거했을_때_count가_0()`  테스트의 경우, 
값을 넣고난 후 빼기 전의 count도 `XCTAssertEqual(sut.count, 50)`로 테스트 해주어야 하나? 를 고민하다가 테스트 하나에는 하나의 테스트만 넣어야 한다는 생각에 삭제를 했습니다. then이 아닌 다른곳에서 `XCTAssert`를 사용해주기도 하나요?

또, `func test_큐가_비어있는데_dequeue를_실행하면_nil()` 테스트를 하는데 비어있는 경우는 given으로 아무것도 해줄 것이 없어서 given을 빈칸으로 두었습니다. 이처럼 given이 주어지지 않기도 할 수 있나요?

>2. 간단한 메서드의 테스트
구현이 기본적이고 간단한 메서드가 있더라도 로직의 중요한 부분을 차지하고 있다면 충분히 테스트의 대상이 될 수 있다고 생각해요!추후에 요구사항이 바뀌거나, 타입의 동작을 조금 바꿔야될 필요가 있어서 리팩토링을 수행했는데 핵심 로직인 메서드를 테스트 하면 더 안전하지 않을까요 그래도?! (아무리 기본적인 메서드더라도)이 또한 제 개인적인 생각일 뿐입니다~!

이해했습니다! 아주 간단한 메서드라도 테스트를 해주는 것이 좋아보이네요 👍👍👍👍

>3. 테스트 메서드가 private 되어있는 경우에 테스트
테스트의 가장 기본적인 원칙은 테스트코드와 실제 코드의 분리입니다!그래서 실제 코드가 바뀌어야된다면 그게 의미 있는 테스트 코드일까 라는 생각이 드네요..! private 가 맞다면 그건 테스트에서 직접 접근을 안하는게 맞다고 생각합니다 개인적으로! 그리고 TDD라면 테스트 코드를 먼저 작성 하셨을텐데 그럼 private 가 되는지/안되는지는 그 뒤에 결정될 일 아니었을까요?! :) (TDD넘 어렵ㅎㅎ)

아 이 부분도 이해가 되었습니다 테스트코드와 실제 코드가 분리되어야 하고 private여야 하는 부분(제 코드에서는 isEmpty())은 내부에서 사용한다는 뜻일테니 사용하는 메서드를 테스트 하면서 같이 테스트가 되겠네요! isEmpty()는 기능분리를 하면서 나오게 된 메서드라 이런경우는 어떻게 테스트 해야하나... 생각했었습니다

>4. 반복적인 모듈 import반복적인 모듈 import를 원치 않는 이유가 있으실까요?!

반복적으로 모듈을 import 하면 적겠지만 비용이 소모된다고 생각했습니다. 흠... 실제로 비용이 소모될 것 같긴 한데 소모를 해서라도 파일을 분리해서 가독성을 올리는게 훨씬 이득이라고 생각하고는 있습니다! 다만 혹시나 비용을 소모 하지 않을 수 있는 방법이 있다...면 해결될 것 같은데 혹시 그런 방법이 있을까요?

2022-09-23 03:51 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
넘 좋은 근거들입니다👍
다만, 이럴때는 메서드가 아니라 연산 프로퍼티로 표현이 가능할것 같은데 그것도 고려해보시면 좋을것 같아요!!

2022-09-23 03:52 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    override func tearDownWithError() throws {
저도 임시파일?에 대해서는 모르겠는데 왠지 컴파일/빌드와 관련된 이야기일듯 싶습니다..! 자세히는 모르겠네요 이건 저도! 혹시 임시 파일 이야기는 어디서 보셨는지 여쭤봐도 될까요?!!

2022-09-23 03:53 UTC, merged

2022-09-23 05:35 UTC, jjpush commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    override func tearDownWithError() throws {
[여기](https://developer.apple.com/documentation/xctest/xctestcase/set_up_and_tear_down_state_in_your_tests) 중 **Prepare and Tear Down State for a Test Class** 부분에서 봤습니다!

>If you need to clean up temporary files or capture any data that you want to analyze after the test class is complete, use the [tearDown()](https://developer.apple.com/documentation/xctest/xctestcase/1496280-teardown) class method on XCTestCase.

2022-09-23 05:38 UTC, jjpush commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func isEmpty() -> Bool {
아 잊고있었습니다 😭
연산프로퍼티로 구현할 수 있는 것들을 자꾸 메서드로 구현하게 되네요
뭔가 틀린건 아니지만 swift의 특징인 연산프로퍼티를 많이 활용해보면 좋겠다고 생각해서요..
딱 보고 "이건 연산프로퍼티로 구현해야지" 라고 생각하게 되는건 많이 짜보면 자연스레 늘겠죠? 🥲