계산기 [STEP1] 써니쿠키
yagom-academy/ios-calculator-app pull request #318
Opened 2022-09-20 07:35 UTC by sunny-maeng

@lina0322 
안녕하세요 엘림 !
저는 써니쿠키입니다 잘부탁드립니다 ! 🙇🏻‍♀️ 😄
자료구조가 처음이라 부족한점이 많습니다 😅
계산기 프로젝트 진행 동안 잘 부탁드리겠습니다 !

---

# 🧮 계산기(Calculator)
## ✅ 프로젝트 수행 중 경험하고 배운 것
- UML작성하기
    ☑️ class Diagram 으로 타입 구현내용과 타입간의 관계 그려보기
- TDD 기반으로 진행하기
    ☑️ [unit test 실패 ➡️ 성공 ➡️ 리팩토링] 과정을 통해 기능 구현해보기 
- 자료구조 Queue, 연결리스트 구현하기 
    ☑️ Queue와 연결리스트 대한 개념, 원리를 배우고 코드로 구현해보기

---

## 🧩 UML (Class Diagram)
<img width=550, src = "https://i.imgur.com/uhppobf.png">

---

## ⚒️ 구현내용 
☑️ 계산기에서 입력받는 숫자와 연산자를 저장 할 `Queue타입`의 `CalculatorItemQueue` 구조체를 구현했습니다.
☑️  Queue타입 구현을 위한 `연결리스트 타입`을 `Node` 클래스와 `LinkedList` 구조체로 구현했습니다.
☑️  요구사항에 맞게 비어있는 `CalculateItem` 프로토콜을 만들고 `CalculatorItemQueue`에서 채택했습니다.
☑️ `LinkedListTests`의 메서드, `CalculatorItemQueue`의 메서드들에 대한 unit test를 진행했습니다.
    <<img width=550, src = "https://i.imgur.com/NdIcwWJ.png">

---

## 🤔 고민한 부분
### 1️⃣ Queue 구현에 사용 할 자료형식
`CalculatorItemQueue` 클래스 내부에서 연산자와 숫자를 저장할 큐에 사용할 자료형식으로 처음엔 `배열(Array)`을 사용했다가 `단방향 연결리스트(Linked List)`로 수정했습니다.

**1-1 Queue의 자료형식으로 배열(Array)을 사용한다면 ?**
- 배열을 이용하면 index로 데이터에 접근할 수 있어서 index를 알고있다면 데이터에 빠르게 접근할 수 있다는 장점이있습니다.
- 하지만, Queue는 FIFO(First In First Out)방식이기 때문에 index 0 부터 삭제될텐데 그 때마다 Array안에서는 element의 인덱스를 하나씩 땡겨서 재배치하는 작업때문에 오버헤드가 발생하는 단점이 있습니다.
    <details>
        <summary> 📌 [click] 배열을 사용했을 때 CalculatorItemQueue 내부 코드 </summary>
    
    ```swift
    struct CalculatorItemQueue {
    var itemQueue: [(arithmetics: String, number: Int)?] = []
    .
    .
    ```    
    - 배열(Array)의 data로 `튜플`을 사용했었습니다. 
    - 튜플원소에 이름을 주어 연산자(arithmetics)와 숫자(number)를 구분했었습니다. 
   - 전체 코드는 아래와 같습니다. Array에서 쓸 수 있는 메서드와 index로 접근하는 방식으로 queue를 구성했었습니다.    
    
    ```swift
    struct CalculatorItemQueue {
        var itemQueue: [(arithmetics: String, number: Int)?] = []
        var index:Int = 0

        mutating func enqueue(_ data: (String, Int)) {
            itemQueue.append(data)
        }

        mutating func dequeue() -> (String, Int)? {
            guard let data = itemQueue[index] else {
                return nil
            }

            itemQueue[index] = nil
            index += 1

            return data
        }

        mutating func clear() {
            itemQueue.removeAll()
            index = 0
        }
    }
    ```
    </details>

**1-2 Queue의 자료형식으로 LinkedList를 사용한다면 ?**
- 배열에서 설명한 오버헤드에 대한 단점을 보완할 수 있습니다
- 연결리스트는 서로 떨어진 공간에 존재하는 데이터를 연결해 놓았기 때문에 첫번째 데이터가 삭제되어도 재배치에 발생하는 오버헤드가 발생하지 않습니다.
- 하지만 배열처럼 인덱스로 접근하지 못하고 첫번째 데이터부터 순차적으로 접근해야해서 접근속도가 느리다는 단점이 있습니다. 
- 이를 보완하기 위해서 양쪽에서 탐색할 수 있는 양방향연결리스트를 고려할 수 있습니다

**1-3 그렇다면 단방향 연결리스트를 쓸까 양방향 연결리스트를 쓸까?**
- 양방향 연결리스트는 단방향 연결리스트의 탐색시간이 느리다는 단점을 보완하기 위해 사용하는데 계산기 프로젝트에서는 탐색할 일이 없어서 **✅ 단방향연결리스트를 사용했습니다.**
- 프로젝트 요구사항을 보면 `연산은 연산자 우선순위를 무시하고 앞에서부터 순서대로 계산합니다.` 라고 되어있기 때문에 queue에서 중간에 있을 곱하기와 나누기를 탐색할 일이 없습니다. 

---

## 🙇🏻‍♀️ 조언을 얻고 싶은 부분

### LinkedList 클래스없이, Queue에서 Node를 직접 이용한 메서드를 만드는게 나았을까요 ?

CalculatorItemQueue 구조체를 구현하고보니 메서드들이 그저 LinkedList의 메서드를 호출하고만 있는 것 같습니다. 같은 일하는 메서드를 이름만 바꿔주고 새로 만들어 준 느낌입니다.

예를들어 queue에 숫자 2를 저장하고 싶을 때 아래 코드로 저장할 수 있습니다.
```swift
var calculatorItemQueue = CalculatorItemQueue()

CalculatorItemQueue.enqueue("2")
CalculatorItemQueue.itemQueue.append("2")
```
이처럼 CalculatorItemQueue의 메서드를 이용하거나 LinkedList의 메서드를 이용할 수 있는 두가지 방법이 있습니다. 
이렇다면 굳이 LinkedList를 구현하지 않고 CalculatorItemQueue 구조체 안에서 Node 클래스를 이용해 직접 구현하는게 맞는건가? 라는 의문이 남습니다 😓

자료구조별로 LinkedList를 사용할거야!, Queue도 사용할거야! 라고 했을 때 각각 분리해서 구현하고 사용하는지, 
위에 적은 내용처럼 Queue내부에서 직접 Node를 이용해 LinkedList의 메서드를 작성해서 사용하는지, 현업에서 대중적인 방법이 궁금합니다. 취향차이라면 엘림은 어떤방법을 추구하시는지 궁금합니다 🤔 

---

자료구조를 처음 접해서 황당한 질문처럼 들릴수도 있을 것 같아 걱정되네요!ㅎㅎ PR내용에 이해가 어려운 부분이나, 이상하게 느껴지시는 코드가 있으면 말씀해주세요! 🙇🏻‍♀️

2022-09-20 12:45 UTC, lina0322 requested changes
안녕하세요, 써니쿠키! 
이번 스텝 진행하느라 고생 많으셨습니다.
고민과 생각이 많았을 것 같아요~

저는 정답은 없다고 생각해요ㅎㅎㅎ.. 좀 더 빠른 길이 있을 수도 있지만
우리 공부하러 온거니까 써니쿠키가 하고싶은거 시도해보고, 중간에 바꿀거 있으면 뒤엎어도보고
리팩토링도 해보고 하는거죠.
다양한걸 직접 해보고 장단점을 직접 느껴봅시다.

코멘트 달았습니다, 이해 안가거나 어려운 부분 있으면 메세지 주시고요
이번 프로젝트도 화이팅입니다!

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Conrtroller/ViewController.swift
>  }
의도하신 수정인가요? 커밋이나 PR할 때, 의도한 수정인지 아닌지 체크 하는 습관도 중요해요!

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
CalculatorItemQueue가 CalculateItem을 채택했다는게 어떤걸까요.
앞으로의 계획이 궁금해지네요🧐

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(_ data: String) {
mutating은 어떤 키워드인가요?

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
함수명이 잘 이해가 가지 않는데요ㅎㅎ 어떤 의도일까요?

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
나머지는 메모리에 존재하지 않을까요?👀

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +        var currentNode = head
self를 쓰기도하고 안쓰기도하네요. 어떤 기준으로 사용하고 계실까요?🙂

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    mutating func removeLast() {
지운 last를 반환해줄 필요는 없을까요?
array에 removeFirst와 removeLast가 어떻게 동작하는지 보고 따라하는것도 좋을 것 같아요.
기존에 만들어진 함수들이 그렇게 만들어진것에는 이유가 있을지도..?!

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +        currentNode?.next = nil
어떤 로직으로 동작하고 있는지 설명해주실 수 있을까요~?

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +
의미 없는 줄바꿈으로 보여요!

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/Node.swift
> +        self .next = next
self뒤에 띄어쓰기 인가요..?

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    var last: Node<String>? {
T를 String으로 지정하신 이유가 있을까요?

2022-09-20 12:45 UTC, lina0322 commented on Calculator/Calculator/Model/Node.swift
> +class Node <T> {
LinkedList와 queue는 struct로,
node는 class로 구현하셨네요! 이유가 궁금합니다.

2022-09-20 12:45 UTC, lina0322 commented on Calculator/CalculatorTests 2/CalculatorTests.swift
> +        sut.itemQueue.head = nil
비우는 함수가 있을텐데요. 그리고 밖에서 head를 접근하는거 괜찮은가요?🧐

2022-09-20 12:45 UTC, lina0322 commented on Calculator/CalculatorTests 2/CalculatorTests.swift
> +        try super .tearDownWithError()
띄어쓰기 하는 습관이 있는 것 같네요?😂

2022-09-20 12:45 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var sut: CalculatorItemQueue! = CalculatorItemQueue()
CalculatorItemQueue 관련한 테스트 파일이 2개로 나눠진거같은데 맞나요..???

2022-09-20 12:45 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
위에서 본거랑 똑같네요. 여기는 String으로 진행하셨네요.
위쪽 테스트 통과 되나요??

2022-09-20 12:45 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual("2", sut.itemQueue.head?.next?.data)
밖에서 데이터에 직접적으로 접근하는게 안전해보이지 않습니다!

2022-09-20 12:45 UTC, lina0322 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(nil, sut.itemQueue.head?.next?.next?.data)
isEmpty 같은건 어떤가요?

2022-09-21 01:14 UTC, sunny-maeng commented on Calculator/Calculator/Conrtroller/ViewController.swift
>  }
코드가 의도한데로 작동되는지 console창에서 확인해보고 싶어서 테스트코드를 작성했다가 지운내용이 기록되었어요!
코드를 삭제하고 커밋 했었어야 했는데 놓친부분이었습니다 
말씀주신 것처럼 체크하는 습관을 들여야겠습니다 감사합니다 :)

(PS. 코드 삭제 후 커밋할 때에는 커밋명에 `chore`를 붙여주어 별로 중요하지 않은 일을 수정하는 경우의 의미를 붙여주었습니다.)

2022-09-21 01:18 UTC, sunny-maeng commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
프로젝트 요구사항에 빈프로토콜을 채택하라는 내용이 있어 추가했었습니다.
Step2가 나온 지금 Step2까지 내용을 보니 감히 추측컨데..
빈프로토콜 `CalculateItem`을 채택한 여러타입(enum,class,struct...)을 CalculateItem Type으로 이용할 것 같습니다!

2022-09-21 01:23 UTC, sunny-maeng commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(_ data: String) {
일반적으로 구조체와 열거형같은 **값타입**에서는 인스턴스 메서드내에서 값타입의 속성을 수정할 수 없습니다.
 이 때 `mutating` 키워드를 이용하면 self 프로퍼티의 속성값을 수정할 수 있게해줍니다

2022-09-21 01:46 UTC, sunny-maeng commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
큐의 첫번째 data를 확인한다는 의미를 담고싶었습니다.
수정해보자면 `checkFirstQueue`로 해볼 수 있을 것 같습니다..🤔

원래는 이 메서드를 만든 이유는 추후 큐에담긴 데이터들을 계산기처럼 계산 할 때 
첫째 값 확인 -> 첫째 값 삭제 -> 확인 -> 삭제 -> ... 를 반복하기 위해서였습니다.

하지만 아래 엘림이 남겨주신 또다른 코멘트에서
>array에 removeFirst와 removeLast가 어떻게 동작하는지 보고 따라하는것도 좋을 것 같아요.
기존에 만들어진 함수들이 그렇게 만들어진것에는 이유가 있을지도..?!

이 코멘트를 읽고 생각해보니 첫째값을 삭제하는 메서드 안에서 값을 확인 할 수 있을 것 같아 삭제했습니다!

2022-09-21 02:59 UTC, sunny-maeng commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
Node가 Class타입이기 때문에 ARC에 의해 자동으로 메모리에서 삭제될 것이라고 생각했습니다.

ARC의 기본원칙은 
주소가 참조될 때 RC +1이되고,
RC = 0일 때는 자동으로 메모리에서 지우는것입니다.

말로하는 것보다 그림이 편할 것 같아서 그림으로 그려보았습니다.
예를들어 3개의 데이터가 LinkedList로 연결되어있고, head를 nil 시켰을 때 메모리의 상태를 차례대로 그렸습니다. 

<img width = 400 src = "https://i.imgur.com/iI8RpHc.png">

- Struct인 LinkedList는 head를 스택영역에 저장하고, head의 값으로 힙영역의 첫번째노드의 주소를 갖고있으면서 RC를 +1해줍니다.
- 첫번째 노드의 next에는 다음 노드의 주소를 참조하고, 이 때문에 두번째 노드의 RC도 1이됩니다.
- 세번째 노드도 두번째 노드의 next에 주소가 참조되어있기 때문에 RC가 1이됩니다.

<img width = 400 src = "https://i.imgur.com/wmO9xLl.png">

- head가 nil이 되면 첫번째 노드의 주소가 사라지므로 RC -1해주고 첫번째 노드의 RC가 0이 됩니다

<img width = 400 src = "https://i.imgur.com/EINOp3I.png">

-첫번째 노드는 RC가 0이라 메모리에서 지워지고 연쇄작용으로 next에서 참조하던 두번째 노드의주소가 지워지면서 두번째 노드의 RC도 0으로 만들어줍니다.

<img width = 400 src = "https://i.imgur.com/8g5HhTJ.png">

- 연쇄작용으로 세번째 노드도 RC가 0이됩니다.

<img width = 330 src = "https://i.imgur.com/1QCDZwO.png">

- 결과적으로 모든 데이터들이 메모리에서 지워지게 됩니다.

2022-09-21 03:07 UTC, sunny-maeng commented on Calculator/Calculator/Model/LinkedList.swift
> +        var currentNode = head
self를 사용하려고 노력중입니다...마지막에 늘 확인해야지 하고 놓치고 있네요 😭!
사용하는 것으로 통일해서 커밋했습니다 
꼼꼼하게 봐주셔서 정말 감사합니다 :)

2022-09-21 03:58 UTC, sunny-maeng commented on Calculator/Calculator/Model/LinkedList.swift
> +    mutating func removeLast() {
removeFirst, removeLast 메서드가 삭제하는값을 리턴하도록 수정했습니다.
더불어 CalculatorItemQueue 의 dequeue메서드도 삭제하는 값을 리턴하도록 수정했습니다

2022-09-21 04:21 UTC, sunny-maeng commented on Calculator/Calculator/Model/LinkedList.swift
> +        currentNode?.next = nil
예를들어 <data, next>로 구성된 노드가 
<A의값, B노드> / <B의값, C노드> / <C의값, nil> 라는 3개의 노드로 연결리스트로 있을때 ,
세번째 <C의값, nil>을 remove하기 위해서는 두번째 <B의값, C노드>노드 에서 C노드를 지워줘야 합니다.
때문에 _`마지막값의 이전값`_ 즉 <C, nil>의 이전값인 <B, C노드> 노드를 찾아서 이 노드의 C노드를 nil로 지우는 로직입니다.
즉 _`마지막값의 이전값`_의 _`next`_ 값을 nil로 만들어 주는 로직입니다.

그냥 마지막 세번째인 <C, nil> 노드를 찾아서 지워준다면 두번째 <B, C노드>에서는 C노드를 계속 갖게되므로 마지막값의 이전값을 찾아서 그 노드의 next를 nil로 remove 해야합니다
코드의 내용은


```swift
    mutating func removeLast() -> Node<String>? {
        //마지막값을 반환해주기위한 값으로 lastNode를 선언합니다
        var  lastNode = self.head
        
        //연결리스트에 값이 아무것도 없으면 nil을 반환해줍니다
        guard self.head != nil else {
            return nil
        }
        
        //연결리스트에 값이 한개 있으면 첫번째값을 remove하고 반환해줍니다
        guard self.head?.next != nil else {
            self.head = nil
            return lastNode
        }
        
        //연결리스트에 값이 여러개있을 때 마지막의 이전값까지 찾아가기위해
        //currentNode를 사용할 것입니다
        var currentNode = self.head
        
        //마지막값의 이전값을 찾아갑니다
        while currentNode?.next?.next != nil {
            currentNode = currentNode?.next
        }
        
        //마지막값의 이전값의 다음값 = 즉 마지막값을 lastNode에 담아주고 remove합니다
        lastNode = currentNode?.next
        currentNode?.next = nil
        
        //remove된 마지막값을 리턴합니다.
        return lastNode
    }
```

2022-09-21 04:23 UTC, sunny-maeng commented on Calculator/Calculator/Model/LinkedList.swift
> +
삭제했습니다 감사합니다 😂

2022-09-21 04:24 UTC, sunny-maeng commented on Calculator/Calculator/Model/Node.swift
> +        self .next = next
띄어쓰기....수정했습니다! 😂

2022-09-21 04:29 UTC, sunny-maeng commented on Calculator/Calculator/Model/LinkedList.swift
> +    var last: Node<String>? {
LinkedList를 사용할 큐에 담길 데이터를 UIButton에서 받기 때문에 UIButton이 String으로 값을 받아서 String으로 구현했었습니다. 
하지만 담은 후에는 연산을 위해 Int로 옮겨 담아야 할 것 같아서 <T>로 수정했습니다!

2022-09-21 04:57 UTC, sunny-maeng commented on Calculator/Calculator/Model/Node.swift
> +class Node <T> {
node는 프로퍼티 `next`에 Node를 담고있습니다.
node가 struct로 구현된다면 next에 새로운 노드가 생길 때마다 값이 복사되고, 불필요한 노드들이 생기게 될 것이기 때문에 값타입인 struct보다 참조타입인 class를 사용해야한다고 생각합니다

2022-09-21 05:07 UTC, sunny-maeng commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var sut: CalculatorItemQueue! = CalculatorItemQueue()
test navigatior에서  처음만든 테스트 파일이 회색글씨로 표시되면서... 이상한 오류를 만나서 파일을 삭제하고 다시 생성 했었어요!
파일상에는 삭제되어보이는데.. 엘림이 열 때는 문제가 되고있나요?? 🥹

추가로 네이밍도 변경했습니다 ..!

2022-09-21 05:30 UTC, sunny-maeng commented on Calculator/CalculatorTests 2/CalculatorTests.swift
> +        sut.itemQueue.head = nil
아하..! 비우기함수의 유닛테스트가 끝나기 전에는 이전의 유닛테스트에서 사용하지 못하는 줄 알았습니다🤣
head에 접근하지 못하도록 head를 private처리했습니다. 그 외에도 접근제한을 설정해 보았습니다..
LinkedList의 프로퍼티들을 private 처리했습니다 !

2022-09-21 06:06 UTC, sunny-maeng commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
제 xcode에서는 파일이 삭제되서.. Int로 하는 테스트 함수가 사라졌습니다..!😢

2022-09-21 06:08 UTC, sunny-maeng commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(nil, sut.itemQueue.head?.next?.next?.data)
감사합니다
LinkedList와 CalculatorItemQueue에 isEmpty함수를 생성해주니 테스트코드가 훨씬 쉽네요 ㅎㅎ!

2022-09-21 07:19 UTC, sunny-maeng commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual("2", sut.itemQueue.head?.next?.data)
head와 data는 private(set)을 설정해주었고, 
next로 접근을 지양한 코드로 전면 수정했습니다.

2022-09-21 08:15 UTC, sunny-maeng commented
@lina0322(@엘림)
엘림! 꼼꼼한 리뷰 정말 감사드립니다 😍
수정내용은 남겨주신 코멘트에 리댓글로 남겼습니다!

설명에 틀린부분이나 수정한 코드에 문제가있다면 가감없이 말씀해주세요
감사합니다 🙇🏻‍♀️✨

2022-09-21 09:19 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
와우, 이미지까지 만들어서 설명해주시다니 감사합니다ㅎㅎ 정말 좋은 자료를 잘 만들었네요!
꼭 리드미에 적어두시길!!! 정성스러운 답변 감사합니다!

2022-09-21 09:32 UTC, lina0322 requested changes
고생하셨습니다! isEmpty는 한 번 체크해봐야할거같아요~
나머지는 이번 스텝에서 안하고 다음에 같이 녹여내도 좋을거같습니답!

2022-09-21 09:32 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        self.itemQueue == nil ? true : false
linkedList의 head가 없는게 empty아닌가용??👀 또는 linkedList.isEmpty 체크?!

2022-09-21 09:32 UTC, lina0322 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +
setUpWithError와 tearDownWithError은 반드시 필요한가용? 없으면 어떻게되나요??

2022-09-21 09:32 UTC, lina0322 commented on Calculator/LinkedListTests/LinkedListTests.swift
> +class LinkedListTests: XCTestCase {
의도적으로 실패하는 테스트도 만들어보면 좋을거같아요ㅎㅎ
물론 테스트 자체는 통과인데, 내부적으로 실패요!

2022-09-21 11:18 UTC, sunny-maeng commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +
setUpWithError 메서드는 각각의 테스트가 실행되기 **전**에 실행된다고 알고있어서 제 코드에서는 sut을 초기화할 수 있도록 오버라이드하여 구현했습니다. 
tearDownWithError 메서드는 각 테스트가 종료된 **후**에 실행된다고 알고있어서 테스트 후에  sut을 정리하는 작업을 오버라이드하여 구현했습니다.

하지만 제 코드에서는 두 메서드를 모두 지워줘도 문제없이 작동합니다 🤔 
 구글링으로 unit test의 life cycle을 검색해보려했는데 이 내용을 이해할만한 문서를 찾지 못했습니다😭 
 
 코드에서는 브레이크포인트를 걸어서 확인해보면 sut을 생성해준 12번라인에서 테스트가 끝난 후에도 여러번 break되면서 인스턴스가 새로 생성되는 것 같습니다... 조금 더 공부를 해봐야 할 것 같습니다..
 
 혹시 엘림은 이유를 알고 계신가요?? 🤔😂😓

2022-09-21 11:29 UTC, sunny-maeng commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        self.itemQueue == nil ? true : false
감사합니다 itemQueue의 head가 nil인지 체크하는 코드로 수정했습니다! ㅎㅎ

2022-09-21 12:37 UTC, sunny-maeng commented on Calculator/LinkedListTests/LinkedListTests.swift
> +class LinkedListTests: XCTestCase {
아!
의도적인 실패테스트를 추가해주면 성공테스트의 신뢰도가 더 높아지겠군요!
감사합니다 기존 테스트메서드에 XCTAssertNotEqual 을 이용해 실패테스트를 추가해 커밋했습니다 🙇🏻‍♀️

2022-09-21 12:39 UTC, sunny-maeng commented
@lina0322 (@엘린)
엘린 한가지 의문점을 남겼지만,, 커멘트에 리댓으로 수정내용 작성하고 커밋했습니다 😳💡🙇🏻‍♀️

2022-09-22 07:35 UTC, merged