계산기 [Step1] 수박, 타코캣, 건
yagom-academy/ios-calculator-app pull request #32
Opened 2021-06-23 09:09 UTC by soo941226

@SungPyo 
안녕하세요! 1B 조입니다!
이번에 계산기 프로젝트를 만들면서 고민을 정말 많이 했는데 정말 어렵고 힘든 프로젝트인 것 같습니다. 뷰에도 반영을 해야하는데 이것도 못한 게 마음에 걸리네요.
 잘 부탁드립니다. 감사합니다!

## 고민한점
 1. 어떤 개체간의 관계를 고려할 때(응집성과 결합성 등?), 스택에 입력값을 쌓는 것을  viewController 와 Calculator 구조체 중 어느곳에서 구현하는 게 더 좋을지를 고민하였습니다. (중위연산을 후위연산으로 변환하는 과정을, viewController에서 할 지, Calculator에서 할 지 고민하였습니다.)
 2. 공통기능을 하는 액션A를 만든 뒤, 모든 버튼이 A에 연결되어있으면서 또 각각의 기능을 하는 액션을 따로 구현할 것인지 아니면 모든 버튼이 하나의 액션에 연결되어있으면서 스위치를 돌려서 공통의 일을 한 뒤 자신의 일을 찾아갈 것인지를 고민하였습니다.
 3. 계산기Delegate를 만들어서 계산기의 '=' 버튼을 입력하기 전까지 계산 가능한 식을 return하는 delegation pattern을 쓰는건 어떨지 궁금합니다!
 4. 1의 질문에 이어서인데, Calculator를 protocol과 extension으로 구현하여 viewController로 상속받는 게 나을지 고민하였습니다. 현재의 뷰가 계산기인데, 뷰 컨트롤러 자체가 계산기가 되면 더 직관적인 것 같아 질문을 드리게 됐습니다.
 5. viewController의 메소드 중 touchUpEqualButton에서 중위연산을 후위연산으로 변환하고 있는데, 이게 생각보다 많이 어려웠고 오류도 많이 나서 시간을 많이 잡아먹었습니다. 지금보다 더 간결하고 직관적인 방법이 있을지 궁금합니다.
 6. 후위연산으로 변환은 어떻게 하기는 한 것 같은데, 막상 사용을 하려니 많이 막막하고 감이 잘 잡히지 않아 조언을 좀 구하고 싶습니다.

2021-06-24 12:56 UTC, SungPyo requested changes
안녕하세요! Step1 리뷰네요!

잘 부탁드립니다.

## 고민한 점에 대한 답변
1. 어떤 개체간의 관계를 고려할 때(응집성과 결합성 등?), 스택에 입력값을 쌓는 것을 viewController 와 Calculator 구조체 중 어느곳에서 구현하는 게 더 좋을지를 고민하였습니다. (중위연산을 후위연산으로 변환하는 과정을, viewController에서 할 지, Calculator에서 할 지 고민하였습니다.)
`아키텍쳐 관련된 고민을 하시는군요! 고민을 하시는건 좋습니다! 하지만 현재 상황에서 아키텍쳐 설계 단계에 고민이 있다면. 그 고민은 잠시 접어두시고 ViewController 든 Calculator 든 구현 후 정상적인 동작을 먼저 이끌어 내는것이 먼저라고 생각됩니다. 그 이후에 생각해도 늦지않아요~ 그리고 현재 상황에선 ViewController에 하든 Calculator에 하든 명확하게 분리되어 표현된다면 상관 없다고 봅니다 :)`

2. 공통기능을 하는 액션A를 만든 뒤, 모든 버튼이 A에 연결되어있으면서 또 각각의 기능을 하는 액션을 따로 구현할 것인지 아니면 모든 버튼이 하나의 액션에 연결되어있으면서 스위치를 돌려서 공통의 일을 한 뒤 자신의 일을 찾아갈 것인지를 고민하였습니다.
`액션 자체는 그 액션 자체의 일만 하는게 옳습니다. 따로 나누셔도 좋고, 하나로 합치셔도 좋습니다. tag를 이용하여 사용하셔도 되고, 각 버튼의 enum이나 구조체를 이용해서 구현하셔도 됩니다! 저라면 하나의 IBAction을 사용할 것 같네요 ㅎㅎ`

3. 계산기Delegate를 만들어서 계산기의 '=' 버튼을 입력하기 전까지 계산 가능한 식을 return하는 delegation pattern을 쓰는건 어떨지 궁금합니다!
`결과가 나쁘지 않다면 어떤것이든 시도하는건 좋아요. 개발 전에 하는 많은 생각보다 먼저 개발하고 눈으로 보고 느끼는게 훨신 더 좋은 결과를 낳는다고 생각됩니다.`

4. 1의 질문에 이어서인데, Calculator를 protocol과 extension으로 구현하여 viewController로 상속받는 게 나을지 고민하였습니다. 현재의 뷰가 계산기인데, 뷰 컨트롤러 자체가 계산기가 되면 더 직관적인 것 같아 질문을 드리게 됐습니다.
`음 아직 뷰가 완벽하게 나오지 않아서 상속에 대해 좋다 나쁘다를 제가 말씀드리기는 조금 힘들 것 같아요. 상속과 관련된 부분은  객체지향 개발 5대 원리중 하나인 리스코브 치환 원칙에 대해서 한번 공부하시면 좋을 것 같아요!`

5. viewController의 메소드 중 touchUpEqualButton에서 중위연산을 후위연산으로 변환하고 있는데, 이게 생각보다 많이 어려웠고 오류도 많이 나서 시간을 많이 잡아먹었습니다. 지금보다 더 간결하고 직관적인 방법이 있을지 궁금합니다. 후위연산으로 변환은 어떻게 하기는 한 것 같은데, 막상 사용을 하려니 많이 막막하고 감이 잘 잡히지 않아 조언을 좀 구하고 싶습니다.
`경험을 먼저 말씀드리면 저는 실무에서 6년간 iOS 개발을 하면서 '==' 정도의 연산자 오버라이딩을 한 적은 있지만 중위연산을 후위연산으로 바꾸어 개발한 적이 단 한번도 없습니다. 그래서 궁금한게 있는데 중위연산을 후위연산으로 변환해서 사용해야만 하는 이유가 있는건가요?`

## 그 외
1. indent가 코드마다 조금씩 다른것 같은데. indent를 맞춰 주셨으면 좋겠어요. 가독성이 떨어집니다!
2. UIButton을 상속받은 ??Button을 만들고 해당 버튼이 어떠한 값을 갖는지 주입하고 만들어 놓은 Component Enum을 Associate enum으로 선언하여 어떤 number인지 알 수 있다면 해당 버튼의 액션에서 Component만 전달하더라도 'updateChangableOperator' 이러한 함수의 사용을 줄일 수 있을 것 같아요 :) 
3. touchUpEqualButton 액션에 관련된 부분은.. 기능에 대한 메소드로 분리가 되었으면 좋겠다는 생각이 좀... 드네요 (코드를 읽기가 굉장히 어렵습니다.)
4. Stack의 storedValue를 포함하여 내부에서만 사용하는 프로퍼티의 경우 접근 제어자를 활용하면 코드 분석 시간을 줄일 수 있습니다.
5. 그 외의 나머지 코드들은 디코에서 리뷰를 한번 받고싶네요 :)

Step1 고생하였습니다!

최대한 기존 로직을 건드리려고 하지 않고, 최대한 이해하기 쉽게 리뷰를 하려고 했는데 전달이 잘 되었는지 걱정되네요.😱

한번정도 더 생각하고 수정... 괜찮겠죠?

2021-06-24 12:57 UTC, SungPyo commented on Calculator/Calculator/Controller/ViewController.swift
> +	func updateChangableOperator(with: String) {
전체적인 Indent가 틀어져 있어서 보기가 불편합니다!
나머지 함수에 대한 내용은 리뷰 텍스트에 적어뒀어요 :)

2021-06-24 12:57 UTC, SungPyo commented on Calculator/Calculator/Model/CalculatorDelegate.swift
> +enum CalculatorComponent {
이넘을 이렇게 설계하고 만든건 좋습니다! 
하지만 활용도가 너무 낮은 것 같은데, 어떻게 하면 더 좋게 활용할 수 있는지 고민해 보시는것도 좋을 것 같아요.

2021-06-29 11:23 UTC, soo941226 commented
@SungPyo
내일날씨맑음 안녕하세요! 1B조입니다!
미구현되었던 기능들을 구현하면서,  말씀하신 점을 최대한 반영하여 스탭1을 마무리 지어보려고 합니다.

> 타코캣:
> >  Calculatorable 프로토콜 안에 convertToPostfixExpression, calculatePostfixExpression 를 선언하고 extension에서 convertToPostfixExpression을 구현하였습니다. 사실 이렇게 구현한 이유는 한 번 Extension을 써 보고 싶어서입니다. 만약 pop 관점에서 접근한다면 프로토콜 안에 선언된 두 개의 메소드를 extension안에서 구현해야하는 건지 궁금합니다. 그렇지 않다면 프로토콜 안에 선언된 것들 중 extension으로 구현해야 하는 것들의 기준이 있는건지 궁금합니다.
>
> 수박 :
> > 1. 함수의 단위를 어떻게 잘라내는 게 맞는지 확신이 서지 않았습니다. 특히 Calcaulator타입의 convertToPostfixExpression와 같은 함수에서 스택과 같은 지역변수를 공유해야한다는 점이, 함수를 쪼개는 것을 더욱 어렵게 했습니다. 이러한 점을 고려하셔서 지금의 함수가 괜찮다는 생각이 드시는지, 고친다면 어떻게 고치는 게 좋을지 조언을 해주시면 감사하겠습니다
> > 2. 지금 IBAction에는 저희 입장에서는 어쩔 수 없다는 느낌으로 문자열을 하드코딩하고 있는데 혹시 이러한 점도 개선할 필요가 있을까요? 뭔가 방향이 있다면, 공유해주시면 큰 도움이 될 것 같습니다.
>
> 건 : 
> > .signConverter에서 부호변환하는 방법에서 현재는 switch문에서 분기처리를 하여  처리하는 방식으로 진행하고 있는데 내일날씨맑음은 어떤 방법으로 처리하실지 궁금합니다.

2021-06-30 08:57 UTC, SungPyo approved these changes
고생하셨습니다.

옵셔널 해제 후 바로 아무 작업도 하지 않는 경우에는 모나드를 공부하시고 flatMap을 이용하면 좀 더 깔끔한 코드를 만들 수 있습니다.
그 외에도 ​개선해야 할 점 (inputStorage.popLast() 등.. ) 이 존재하지만 
Step2로 빠르게 넘어가기 위해서 그리고 그 후에 추가적으로 리팩토링이 가능한 시기가 분명히 있으니 Step1은 이정도까지 하는것으로 할게요.

### 타코캣
ㄴ `음.. 질문이 이게 맞는진 모르겠지만 생각한 대로 적어볼게요. 저는 프로토콜을 만드는 기준을 '특정 기능에 대한 묶음' 으로 기준을 잡습니다. 현재 만드신 계산 프로토콜 처럼요. 내부에 있는 메서드는 연산 방식만 다르지 둘다 계산 프로토콜에 들어가는게 이상해 보이지 않습니다. 프로토콜을 확장하여 만드는 함수는 기본값 이라고 생각하시면 됩니다. 내가 구현부를 정의하지 않고 사용했을때의 기본값 정도로요. 그것도 상황마다 다르겠죠? 그런 상황들을 잘 생각하시면 됩니다 :) 억지로 쓰지말고 나중에 찾아서 사용해 볼 수 있게 해도 괜찮습니당`

### 수박
ㄴ 1. `제가 생각하는 함수의 단위는 기능별 입니다. 물론 말씀하신대로 지역변수를 양쪽의 함수에서 모두 사용하게 되면 불편함이 분명히 생기겠죠. 그럼 또 지역변수를 없애보려 노력할테고.. 이것의 반복입니다. `

ㄴ 2. `IBAction같은 경우는 제가 Step1에서 말씀드렸던 것 처럼 Button을 확장하거나 상속받은 클래스를 이용하면 어느정도 String의 사용을 줄일 수 있다고 생각합니다. 이해되지 않는 부분을 무조건 꼭 개선하실 필요는 없어요. `

### 건
ㄴ `현재 상태라면 저도 switch문을 사용할 것 같아요.  
하지만 이러한 로직 자체는 Step1에 말했던 슈퍼 클래스 내부로 이동될 것 같습니다.`

고생하셨습니다!

2021-06-30 08:58 UTC, merged