계산기 [STEP 1] zhilly
yagom-academy/ios-calculator-app pull request #320
Opened 2022-09-20 07:48 UTC by zhilly11

@junbangg 
안녕하세요 알라딘!
질리라고 합니다🙇🏻‍ 계산기 프로젝트 리뷰 잘 부탁드립니다!

## UML 
<p align="center">
    <img src= https://i.imgur.com/pRygJN3.png width=500>
</p>

![]()

## 🤔 고민했던점

### `CalculatorItemQueue`안에 List type 고민
먼저 여러가지 방법들을 생각해봤었습니다.
1. `queue`: `queue`로 구현한다면 사용자가 입력한 수식을 순차적으로 저장이 가능하다. 하지만 요소를 꺼내올 때에는 항상 맨 앞의 값만 가져올 수 있다.
2. `stack`: `stack`으로 구현을 했다면 사용자가 입력한 수식을 먼저 `queue`에 저장해서 연산자와 피연산자를 구분해 `stack`에 넣었을 것 같습니다. 이런 방식으로 `stack`을 사용하면 후위연산식으로 만들어 연산자 우선순위를 사용해 계산할 수 있다는 장점이 있지만, 이번 프로젝트에서는 연산자 우선순위를 사용하지 않기 때문에 `stack`을 사용하지 않았습니다.
3. `linked list`: `queue`보단 메모리 관리나, `removeFirst()`의 오버헤드를 극복할 수 있다고는 하나 이번 프로젝트에서는 하나의 연산식 만을 가지고 사용하기 때문에 연산식의 중간에 접근하거나, 중간에 값을 추가하지 않기 때문에 굳이 `linked list`를 사용할 필요가 없다고 생각했습니다.

따라서 queue를 사용하고 안에 최소한의 기능만을 작성해서 구현하였습니다.

<br>

### Unit Test에서 `CalculatorItemQueue`의 타입
추후에 프로젝트에 들어가게 되면 queue를 어떤 타입으로 쓸지 모르고 또한 재사용을 가능하게 하기 위해서 제네릭 타입으로 `CalculatorItemQueue`를 작성했습니다. 하지만 아래 코드의 UnitTest에서 queue가 String, Double, Int 타입으로 각각 생성되는지 테스트를 진행할 때 문제가 생겨서 일단 String 타입으로 sutQueue를 생성해주고 Double이나 Int로 생성하는 테스트를 할 때는 따로 queue를 선언해줘서 테스트를 진행했습니다. String 타입으로 선택해 진행한 이유는 추후에 한 queue에 연산자들과 피연산자들이 들어오게 될 텐데 이럴 때에는 String 타입으로 진행해야한다고 생각해서 String을 default로 생각하고 테스트를 진행했습니다.

```swift
final class CalculatorTests: XCTestCase {
    
    var sutQueue: CalculatorItemQueue<String>?

    override func setUpWithError() throws {
        try super.setUpWithError()
        sutQueue = Queue<String>()
    }

    override func tearDownWithError() throws {
        try super.tearDownWithError()
        sutQueue = nil
    }
    
    func test_비어있는_String타입queue생성이가능할때() {
        XCTAssertTrue(sutQueue.isEmpty)
    }
    
    func test_비어있는_Double타입queue생성이가능할때() {
        let queue = CalculatorItemQueue<Double>()
        
        XCTAssertTrue(queue.isEmpty)
    }
    
    func test_비어있는_Int타입queue생성이가능할때() {
        let queue = CalculatorItemQueue<Int>()
        
        XCTAssertTrue(queue.isEmpty)
    }
    
    ...
}
```

<br>

## ✏️ 조언을 얻고 싶은 부분

> Unit Test에서 `CalculatorItemQueue`의 타입
- 제네릭으로 선언한 타입을 테스트할 때 조금 더 좋은 방법이 있을까요? 아니면 지금처럼 타입 하나를 default로 잡고 진행하는 방법이 괜찮을까요?
- 처음으로 TDD방식으로 진행했는데 잘 지키며 진행되었는지 궁금합니다! 또한 알라딘만의 팁이 있을까요?
- 또한 TDD방식으로 진행하면서 어떻게 코드를 작성하는것이 Unit Test에 좋은 코드인지 많은 고민과 어려움이 있었습니다. 알라딘은 Unit Test와 애플리케이션 내의 코드 중요도를 몇대몇 정도로 생각하시는지 궁금합니다. 물론 정답은 없지만 알라딘만의 규칙이 있는지 궁금합니다!
- TDD를 진행하면서 커밋단위도 궁금했는데요. test case에도 범주를 나누어 커밋을 하는게 좋을까요?

2022-09-21 16:26 UTC, junbangg requested changes
수고하셨습니다!! 
질문 주신 내용을 답변 드리자면..
```
제네릭으로 선언한 타입을 테스트할 때 조금 더 좋은 방법이 있을까요? 아니면 지금처럼 타입 하나를 default로 잡고 진행하는 방법이 괜찮을까요?
```
`고민한점` 에서 이어지는 질문 같은데 이거 더 추상화를 시키면 되지않을까요??
코드 중에 `String`, `Int`, `Double` 을 extension으로 무언가를 채택하는 코드가 있던데 그건 왜 있는건가요?!?

```
처음으로 TDD방식으로 진행했는데 잘 지키며 진행되었는지 궁금합니다! 또한 알라딘만의 팁이 있을까요?
```
음 이 부분에 대해서 제가 말씀을 드리고 싶었던건
`given, when, then` 입니다.. 활동학습때 아마 이야기가 되었겠지만! 아니라면 한번 공부해보셔도 좋을것 같아요:)
이걸 메서드명, 그리고 코드 구조를 짤때 참고해주시면 훨씬 좋은 테스트 코드가 만들어질것 같아요!
지금도 잘하셨지만, `given, when, then` 으로 최대한 리팩토링 해보시면 연습이 될것 같습니다:)
가독성도 좋아지고 메서드 구조도 훨씬 깔끔하고 이해하기 좋은 테스트 코드가 될것 같아요.

```
또한 TDD방식으로 진행하면서 어떻게 코드를 작성하는것이 Unit Test에 좋은 코드인지 많은 고민과 어려움이 있었습니다. 알라딘은 Unit Test와 애플리케이션 내의 코드 중요도를 몇대몇 정도로 생각하시는지 궁금합니다. 물론 정답은 없지만 알라딘만의 규칙이 있는지 궁금합니다!
```
저도 테스트코드 잘 몰라요..ㅎㅎ
사실 현업에서 테스트코드가 가끔은 좀 우선순위에서 미뤄질때가 있어요ㅜㅜ
그건 절대 개발자들이 하기 귀찮아서가 아니라..기능 배포를 훨씬 중요하게 생각하는 사람들과도 일을 하고 있기 때문이에요
그래서 일단 애플리케이션의 실제 코드가 더 중요하다고 보긴 하는데..장기적으로 탄탄한 코드를 만들기 위해서는 테스트 코드도 분명히 필요하다고 생각해요. 아니 거의 필수라고 보셔도 될것 같아요!

그리고 저는 규칙은 따로 없지만... 
- 메서드명으로도 충분히 어떤 테스트인지 이해할 수 있고
- `given, when, then` 의 구조를 지키고
- `given, when, then` 이외의 일은 하지 않게 만들고
- 실제 코드가 영향을 받지 않게 한다
요 정도인것 같아요 당장 생각나는건!
그리고 추가적으로 ! (이건 나중에 공부하게 되시겠지만) `Test Double` 을 효과적으로 활용하려고 노력해요 개인적으로! 
`Test Double` 에 대해서 공부해고 사용 방법을 연습하다보면 실제 코드가 테스트성이 더 좋아질 수 있을것 같아요 나중에!

```
TDD를 진행하면서 커밋단위도 궁금했는데요. test case에도 범주를 나누어 커밋을 하는게 좋을까요?
```
그건 하기 나름인것 같아요! 정해두신 기준들로 일관성 있게만 해주시면 될것 같습니다:)


그리고 저도 궁금한것들이 있는데
1. UML 에 타입간의 의존 관계를 표기 안해주신 이유가 있을까요?
2. `queue` 를 구현하기 위해 `stack` 과 `linked list` 를 고민하는게 맞지 않을까요?!! 지금 구현하신 `queue` 는 결국 무엇으로 구현하신건가요?

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var sutQueue: CalculatorItemQueue<String>!
흠 `sutQueue` 로 네이밍을 해주신 이유가 있을까요?!?!?

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_비어있는_String타입queue생성이가능할때() {
요 단위 테스트가 어떤걸 검증하는건지 잘 이해를 못한것 같아요!!

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_비어있는_String타입queue생성이가능할때() {
아래도 마찬가지지만 `생성이 가능할때` 를 검증한다는게 무엇인가요??
그리고 그걸 `isEmpty` 로 검증하는 이유도 궁금합니다!

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에3을push했을때() {
메서드명이 미완성인것 같아요!
`queue` 에 3을 push 했을때
까지는 좋은데..그 후에 예상되는 결과를 표기해주시면 가독성/테스트 컨벤션에 더 맞을것 같아요!

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에3_6_9를push했을때() {
위 코멘트랑 똑같은 이야기!

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에3_6_9를push하고pop을한번했을때() {
여기도 위 코멘트와 똑같은 이야기!

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertNil(sutQueue.pop())
기본적으로 테스트 코드를 작성할때 
`given, when, then` 을 따르는게 여러모로 좋다고 생각합니다.
여기서도 최소한 테스트의 구조를 나타내기 위해서라도 
테스트에 들어가는 데이터 -> 예상되는 데이터를 상수로 빼주면 좋을것 같습니다

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에3_6_9를push하고pop을네번했을때() {
여기도 마찬가지로 메서드명 끝에 예상되는 결과를 적어주시면 좋을거 같아요
테스트 내용을 이해하는데 큰 도움을 주는 부분입니다

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        }
검증을 위해 `result` 가 `nil` 이 될때까지 `for` 문을 돌리는건가요?

2022-09-21 16:26 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에1_2_3_4_5를push했을때count값이5인지() {
요 메서드가 마음에 듭니다👍
메서드명도 친절하고 메서드 구성도 `given, when, then` 을 따르고 있는것 같아요!

2022-09-22 05:41 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var sutQueue: CalculatorItemQueue<String>!
sut (system under test) queue 이런 생각을 해서 저런 식으로 작성을 해봤습니다.
나중에 새로운 list나 새로운 object가 생기면 추가로 sut 뒤에 네이밍을 붙여서 사용하려고 하는 생각이었지만

지금 생각해 보면 단위 테스트는 모듈단위로 진행을 해야 하기 때문에 다른 object가 생기면 다른 test 파일에서 test를 해줘야 하는 게 맞는다고 생각이 드네요.
네이밍은 `sut`로 수정하는 게 맞을 것 같습니다!

2022-09-22 11:54 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_비어있는_String타입queue생성이가능할때() {
저렇게 작성한 이유는 테스트를 맨 처음 시작할 때 아무것도 없는 상태에서 일단 `비어있는 queue도 생성이 가능해야 한다.`라는 생각을 했습니다. 그래서 queue에 항상 값이 들어있는 것이 아니라서 처음 만들 때 비어있어도 정상적으로 테스트를 통과해야 한다. 라는 의미로 작성을 했습니다.

아래에 `isEmpty`로 검증했던 이유는 XCTAssert 메서드의 종류를 다 알지 못해서 일단 isEmpty로 검증을 했는데 어떤 방법이 더 있을까요?

2022-09-22 13:26 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        }
검증을 위해 작성했습니다. 좀 더 의도가 명확해지도록 메서드 명과 `for`문 수정했습니다!

2022-09-22 13:26 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue에1_2_3_4_5를push했을때count값이5인지() {
감사합니다!

2022-09-22 13:27 UTC, zhilly11 commented
> 고민한점 에서 이어지는 질문 같은데 이거 더 추상화를 시키면 되지않을까요??

혹시 이해가 안가서 그러는데 조금만 더 자세하게 설명해주실 수 있을까요? 저는 아래에 String, Int, Double 을 extension했던 이유가 추상화이지 않을까 라는 생각이였습니다.

> 코드 중에 String, Int, Double 을 extension으로 무언가를 채택하는 코드가 있던데 그건 왜 있는건가요?!?

`CalculatorItemQueue`의 다루는 요소가 `CalculatorItem`프로토콜을 준수한다. 그라고 `CalculatorItem`은 빈 프로토콜입니다. 라는 STEP-1의 요구사항이 있었습니다. 하지만 `CalculatorItem`을 빈 프로토콜로 두게 된다면 유닛테스트를 진행할 수 없어서 임시로 String, Int, Double 도 extension을 활용해 `CalculateItem` 프로토콜을 채택하게 해서 유닛테스트를 진행하였습니다. 또한 나름의 추상화가 될 수도 있을것이라 생각하기도 했습니다.

> 처음으로 TDD방식으로 진행했는데 잘 지키며 진행되었는지 궁금합니다! 또한 알라딘만의 팁이 있을까요?

아직은 유닛테스트에 익숙하지 않아서 일단 차근차근 해보자 라는 식으로 테스트 코드를 작성했던 것 같아요. 사실 아직 아무것도 없는 상태에서 테스트 코드를 먼저 작성하고 테스트 코드를 통과할 수 있게끔 코드를 작성하는 것이 이해가 어렵고 어색하지만! given when then을 명확하게 써서 구현하는 방법으로 리팩토링 진행하고, 구조를 최대한 지키도록 해보겠습니다!

알라딘 조언처럼 `test double`이라는 개념은 추후에 유닛테스느가 어느정도 이해하고 적절히 구현할 수 있게되면 키워드를 공부해보겠습니다. 조언 감사해요~

> 1. UML 에 타입간의 의존 관계를 표기 안해주신 이유가 있을까요?

단순하게 `CalculatorItemQueue`의 다루는 요소가 `CalculatorItem`프로토콜을 준수하는 것이지 `CalculatorItemQueue`가 의존하지는 않는다고 생각해서 관계를 표기하지 않았습니다. 하지만 다시 생각해보니 `CalculatorItemQueue` 안에서 `CalculatorItem`프로토콜을 준수하는 요소들을 사용하니 `dependency` 관계라고 생각이 들기도 하는데요. 아래 그림처럼 표기하는 것이 맞을까요?
 
 ![](https://i.imgur.com/PqwxKu4.png)

> queue 를 구현하기 위해 stack 과 linked list 를 고민하는게 맞지 않을까요?!! 지금 구현하신 queue 는 결국 무엇으로 구현하신건가요?

음.. 제가 생각하기엔 queue와 stack은 반대 되는 개념이라고 생각하고 queue와 stack을 구현할때 linked list를 활용해서 구현할 수 있다고 생각했습니다.
다시보니 위에서 제가 저렇게 적었던걸 보시면 나름의 오해가 생길 수도 있을 문단이라고 생각되네요 😅

지금 구현한 queue는 단순히 private 배열로 구현을 해서 queue에서 사용가능한 기능들만 최소한으로 구현해놓았습니다. 지금단위에서는 굳이 linked list 가 필요하다는 생각이 안들었고 추후에 STEP-2나 STEP-3에서 필요성이 느껴진다면 수정을 해보도록 하겠습니다!

2022-09-23 12:34 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var queue: [T] = []
흠 이 친구 원래 이름이 `queue` 였나요??
생각해보니까 이러면 큐 안에 큐가 있는 느낌이 되겠네요🤔

2022-09-23 12:34 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_비어있는_String타입queue생성이가능할때() {
`비어 있는 큐가 생성이 가능해야된다.` 이걸 테스트 하는 이유가 무엇인가요??🤔
생성을 하면 당연히 비어있는 인스턴스가 생기는게 아닌가,..?라는 생각에 질문 드렸습니당

그리고 지금 `비어있는 큐가 생성이 가능해야된다.`를 테스트 하기 위해서 
`isEmpty` 를 사용하는것은 뭔가 자연스럽기 못한거 같아요 개인적으로는..!
굳이 따지면 이건 `isEmpty` 를 검증하는 느낌??인것 같습니다ㅏ

아마 처음으로 TDD 로 시작하실때 작은것 하나하나 꼼꼼하게 테스트 하시려다가 이렇게 된것 같네요..! 저도 TDD 하면 항상 이렇답니다..

2022-09-23 12:54 UTC, junbangg approved these changes

2022-09-23 12:54 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        let queue = CalculatorItemQueue<Double>()
이 친구가 `given` 에 해당될것 같아요!

2022-09-23 12:54 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func test_queue가비어있을때_isEmpty가true인지() {
요 메서드는..지금 상태로는 큰 의미가 없어보여요 제 생각에는..!

2022-09-23 12:54 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        XCTAssertNoThrow(sut)
sut 에 push 했는데 에러가 날 수 있나요? 코드 구조상???

2022-09-23 12:54 UTC, merged

2022-09-23 13:02 UTC, zhilly11 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var queue: [T] = []
Linked List로 구현해서 이제 queue라는 네이밍은 사라졌습니다!

2022-09-23 13:05 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func test_queue가비어있을때_isEmpty가true인지() {
처음 TDD다 보니까 첫 시작을 어떻게 끊어야 할지 감이 오지 않아서 저렇게 작성했던 것 같습니다.
제가 생각하기에도 필요없는 test case라고 생각되어 삭제 했습니다!

2022-09-23 13:08 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        XCTAssertNoThrow(sut)
push가 잘 된 것을 확인하려면 직접 저장된 것을 확인해야 하는데 queue에서는 접근할 방법이 값을 빼보는 것 말고는 방법이 없다고 생각 되어서 저런식으로 테스트를 했지만!

지금 LinkedList로 구현한 상태에서는 head를 private(set) 으로 지정해줘서 확인해 보는 방법도 있을 것 같습니다!

지금은 isEmpty를 추가로 검증하는 test로 수정했습니다!