계산기 [STEP 1] 준호
yagom-academy/ios-calculator-app pull request #321
Opened 2022-09-20 07:59 UTC by junho15

@1Consumption 

올라프 안녕하세요. 준호입니다.
계산기 프로젝트 STEP 1 PR을 보냅니다.
잘부탁드립니다.

## 구현 내용
* CalculatorItemQueueTests
    - sut - 테스트를 할 CalculatorItemQueue 타입 으로 선언.
    - setUpWithError() - 각각의 test case 가 실행 되기 전 sut를 초기화하는 메서드.
    - tearDownWithError() - 각각의 test case 실행이 끝난 후 sut에 nil을 할당하는 메서드.
    - test_1더하기2를_enqueue하고_dequeue하면_1더하기2가_그대로나오는지() - 큐가 제대로 동작하는 지 테스트하는 메서드.
* CalculatorItemQueue - CalculatorItemQueue 요소는 CalculateItem 프로토콜을 준수하는 제네릭 타입.
    - LinkedList- 중첩 타입으로 LinkedList 클래스 추가.
        + Node- 중첩 타입으로 Node 클래스 추가.
            - value - Node의 값을 저장하는 프로퍼티.
            - next - 다음 Node를 저장하는 프로퍼티.
        + head - LinkedList의 Node 중 제일 먼저 추가한 Node.
        + tail - LinkedList의 Node 중 제일 마지막에 추가한 Node.
        + addLast() - LinkedList의 끝에 Node를 추가하는 메서드.
        + removeFirst() - LinkedList의 제일 앞 Node의 vlaue를 반환하고 해당 Node를 없애는 메서드.
    - queue - LinkedList 타입의 프로퍼티.
    - enqueue - queue에 element를 추가하는 메서드.
    - dequeue - queue에서 element를 빼는 메서드.

## 코드를 작성할 때 고민되었던 점
* TDD
    - TDD를 기반으로 코드를 작성하려고 했습니다.
    - 먼저 실패하는 테스트를 우선 작성했습니다. (c77ac23 커밋)
    ~~~swift
        func test_1더하기2를_enqueue하고_dequeue하면_1더하기2가_그대로나오는지() {
            let input: Array<String> = ["1", "+", "2"]
            
            input.forEach { sut.enqueue($0) }
            var result: Array<String> = []
            for _ in 0...2 {
                if let returnValue = sut.dequeue() {
                    result.append(returnValue)
                }
            }
            
            XCTAssertEqual(result, input)
        }
    ~~~
    - 다음에는 우선 테스트를 통과하도록 Array를 활용하여 queue를 구현했습니다. (f57ecc4 커밋)
    ~~~swift
        class CalculatorItemQueue<T>: CalculateItem {
            private var queue: Array<T> = []
            
            func enqueue(_ element: T) {
                queue.append(element)
            }
            
            func dequeue() -> T? {
                return queue.isEmpty ? nil : queue.removeFirst()
            }
        }
    ~~~
    - Array보다 LinkedList가 더 queue에 적합하여 LinkedList를 사용하도록 개선했습니다. (526e2af 커밋)

2022-09-21 00:58 UTC, 1Consumption requested changes
안녕하세요 @junho15 
고생하셨습니다.

코드가 전체적으로 깔끔하네요. 또한 이유가 있어보입니다.
조언을 얻고싶은 부분에 적어주신 내용은 코멘트로 답변을 달았습니다.

아래는 고민되었던 부분에 적어주신 내용 중 저와 생각이 다른 부분이 있어서 적어봤습니다.

나머지는 코멘트를 참고해주세요.

---------------------------------------------------------

queue에는 Array보다 LinkedList가 더 적합하여 LinkedList를 사용하도록 개선했습니다.(https://github.com/yagom-academy/ios-calculator-app/commit/526e2af3aa99506f4f4f7c2edbdaddd892e92c9a 커밋, 현재 코드)
Array의 append 메서드는 O(1)의 복잡도이지만, removeFirst 메서드는 O(n)의 복잡도임.
LinkedList를 사용하면 삽입, 삭제에 O(1)이 소요됨.

> 흥미로운 접근입니다. 시간복잡도를 고려하셨군요.
하지만 이러한 이유로 struct와 class를 구분짓는 것은 좋지 못한 접근 같습니다. 차라리 struct인 array를 사용하고, O(1)의 복잡도를 가진 기능을 만드는게 나아보여요.

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
이 클래스가 `CalculatorItemQueue` 내부에 있어야 하는 이유가 있나요?

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T: CalculateItem> {
final 키워드에 대해서 공부해보세요.

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
tail을 옵셔널바인딩하는 이유가 nil인지 아닌지를 체크하기 위함인가요? 이후 코드에는 굳이 옵셔널 바인딩을 한 이유를 찾을 수가 없네요. 또한 이 guard문이 어떤 역할을 하는지를 알려면 코드를 해석해야합니다.

아래와 같이 조건에 이름을 지어주는건 어떨까요?

```suggestion
        func addLast(_ element: T) {
            if isEmpty {
                tail = Node(value: element)
                head = tail
            } else {
                let newNode = Node(value: element)
                last.next = newNode
                tail = newNode
            }
        }
        
        private var isEmpty {
            return tail == nil
        }
```

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +            tail = newNode
Node를 생성하는 코드가 중복되는거 같습니다.

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var queue: LinkedList<T> = LinkedList()
펑션이 나오다가 갑자기 프로퍼티가 나오네요. 선언하는 위치의 기준이 있을까요?

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +@testable import Calculator
`@testable` 어노테이션은 어떤 역할을 하나요?

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +extension String: CalculateItem { }
이 extension을 test target에서 해준 이유가 있을까요?

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +            }
불필요한 옵셔널 바인딩 같습니다.
저는  테스트 코드에서는 `어떤 기능을 테스트할지`만 집중하는 편입니다. 그래서 `테스트코드`에서는 가독성을 위해서라면 강제언래핑도 괜찮다고 생각해요.

2022-09-21 00:58 UTC, 1Consumption commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
이 테스트 케이스로는 queue에 들어있는 element의 수보다 dequeue를 많이 하면 어떻게 되는지 알 수 있을까요?

2022-09-21 01:00 UTC, 1Consumption commented
아! 추가적으로 테스트코드에 적용할 수 있는 `given-when-then`패턴도 같이 학습하시면 좋겠습니다.

2022-09-21 10:46 UTC, junho15 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
> 흥미로운 접근입니다. 시간복잡도를 고려하셨군요.
> 하지만 이러한 이유로 struct와 class를 구분짓는 것은 좋지 못한 접근 같습니다. 차라리 struct인 array를 사용하고, O(1)의 복잡도를 가진 기능을 만드는게 나아보여요.

* 2bd3e16 에서 LinkedList 대신 더블 스택(enqueueStack, dequeueStack)을 사용해서 queue를 다시 구현해보았습니다.
* LinkedList와 비교해서 코드 길이가 많이줄었습니다.
* dequeue 에서 사용한 reversed, popLast 메서드가 모두 O(1)의 복잡도이기 때문에 성능에서도 큰 차이가 없을 듯합니다.

2022-09-21 10:51 UTC, junho15 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T: CalculateItem> {
> final 키워드에 대해서 공부해보세요.

* final 키워드는 더이상 상속하지 못하게 하는 역할을 하기 때문에 final class의 subclass를 만들면 컴파일 에러가 발생합니다.
* CalculatoritemQueu는 상속될 필요가 없을 듯합니다.
* ed12232 에서 CalculatoritemQueu에 final 키워드를 추가했습니다.

2022-09-21 10:54 UTC, junho15 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
* 2bd3e16에서 LinkedList를 제거했습니다.

2022-09-21 11:02 UTC, junho15 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +            tail = newNode
* 2bd3e16 에서 LinkedList를 제거했습니다.
* 아래와 같이 수정해서 Node를 한번만 생성할 수 있겠습니다.
~~~swift
            let newNode = Node(value: element)
            if isEmpty {
                tail = newNode
                head = tail
            } else {
                last.next = newNode
                tail = newNode
~~~

2022-09-21 11:08 UTC, junho15 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var queue: LinkedList<T> = LinkedList()
> 펑션이 나오다가 갑자기 프로퍼티가 나오네요. 선언하는 위치의 기준이 있을까요?

* 2bd3e16 에서 LinkedList를 제거했습니다.
* LinkedList를 CalculatorItemQueue의 중첩타입으로 선언했기 때문에 CalculatorItemQueue의 프로퍼티 queue 선언하기 전에 LinkedList을 먼저 선언했습니다.

2022-09-21 11:14 UTC, junho15 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +@testable import Calculator
* @testable은 Unit Test에서 실제 앱 타겟에 있는 코드들에 접근하기 위한 키워드 입니다.
* 기본적으로 타입들은 internal 접근 수준이라 테스트 타겟에서 앱 타겟에 있는 타입에 접근하기 위해 필요합니다.

2022-09-21 11:20 UTC, junho15 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +extension String: CalculateItem { }
* bd266c0 에서 Extensions/String+CalculateItem.swift 파일을 추가하고, 추가한 파일로 extension을 이동했습니다.
* String 타입으로 queue를 테스트하기 위해 extension을 추가했습니다. 
* extension 위치에 대한 고민 없이, 필요한 곳에서 바로 extension을 했습니다.
* extension만 따로 모아 두는 편이 좋을거 같아 파일을 분리했습니다.

2022-09-21 11:24 UTC, junho15 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +            }
* e6d8508 에서 dequeue 반환 값을 강제 추출하도록 수정했습니다.
* !를 사용하지 말라는 것에만 너무 생각이 갇혀있었습니다. 테스트 코드에서는 가독성을 위해서 사용해도 무방할 거 같습니다.

2022-09-21 11:32 UTC, junho15 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
* 195ec15 에서 enqueue한 거보다 더 많이 dequeue하면 nil을 반환하는 지 검사하는 테스트 케이스를 추가했습니다.

> 아! 추가적으로 테스트코드에 적용할 수 있는 `given-when-then`패턴도 같이 학습하시면 좋겠습니다.
* e6d8508 , 195ec15 에서 given, when, then 주석을 추가했습니다.
* 기존 테스트 케이스(test_1더하기2를_enqueue하고_dequeue하면_1더하기2가_그대로나오는지)도 given(코드를 실행하기 전 조건을 설정), when(코드를 실행), then(실행 결과가 예상한 결과와 같은지 확인) 의 순서에 맞게 하려고 한 것인데, given, when, then 주석이 빠진 부분에 대해 코멘트를 주셨나 해서 우선 주석을 추가했습니다.

2022-09-22 06:37 UTC, 1Consumption commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +extension String: CalculateItem { }
이러면 테스트 모듈에서만 String이 CalculateItem 프로토콜을 채택하게 되는게 아닌가요?
실제 구현부에서는 String이 CalculateItem 프로토콜을 채택하지 않았는데, 테스트타겟에서만 채택을 하면 어떤걸 테스트하는건가요?

2022-09-22 06:38 UTC, 1Consumption commented
고생하셨습니다. 코멘트를 하나 달았는데, 참고해주세요.
다음 스텝을 진행하셔도 좋습니다.

2022-09-22 06:38 UTC, merged

2022-09-22 07:00 UTC, junho15 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +extension String: CalculateItem { }
* 네 수정 전 코드가 말씀 주신 문제를 가지고 있었습니다. bd266c0 에서 수정해서 실제 구현부에서 String이 CalculateItem 프로토콜을 채택하도록 했습니다. 제가 코멘트를 오해할 수 있게 적었네요.