계산기 [Step 1] baem
yagom-academy/ios-calculator-app pull request #322
Opened 2022-09-20 07:59 UTC by Dylan-yoon

@1Consumption 
안녕하세요 올라프!☃️
먼저 Calculator 프로젝트 리뷰 받게되어 영광입니다.!

2일동안 `UnitTest`와 `Queue` 를 처음 접하게되어 어려움이 있었습니다. 
그럼에도 불구하고.. 이렇게 PR 올리게되었습니다.

### `Strcut`를 사용한 이유.
아직 `Class`와 `Struct`를 어느 때에 사용해야할지 감도 잡히지 않았기 때문에 제가 생각하는 범위내에서 Struct를 사용하게 되었습니다.
상속을 사용하지 않으며, 디이니셜 사용하지 않기 때문에 사용했습니다.

### 큐 를 구현하는 방법.
`큐(Queue)`라는 간단한 내용들을 알고  있었지만 직접 구현해본것은 처음입니다.
다른 캠퍼들과 이 부분에 대해서 대화 하는것을 조금씩 들었고, `Linked list`, `node` 등 다양한 개념들이 나왔지만,
확실하게 알지 못하고, `제너릭`에 대해서도 개념이 많이 부족하기 때문에 정확하게 쓸 수 없다면 쓰지 않으려고 했습니다.
그렇기 때문에 큐 라는 방식, (먼저 들어오면 먼저 나간다)라는 개념을 제 생각대로 배열을 사용해서 구현을 했습니다.

## 조언받고싶은점 🤔
아직은 코드를 많이 써내려가지 않았기 때문에, `UnitTest`를 사용하는 지금의 방법이 맞는지, 혹은 어떻게 개선해야할지 조언을 부탁드리고 싶습니다.
`Swift`에서 `큐(Queue)`라는 개념을 이해하기 위해 좋은 팁이나 문서가 있다면 조언부탁드리고 싶습니다. 추후 조언주신 부분으로 조금더 리펙토링하고 싶습니다. ^&^

많이 서투르지만 잘 부탁 드리겠습니다.!

2022-09-21 01:18 UTC, 1Consumption requested changes
안녕하세요 @Dylan-yoon 
고생하셨습니다.

먼저 조언받고 싶은 점에 적어주신 부분에 대해서 말해볼게요.

아직은 코드를 많이 써내려가지 않았기 때문에, UnitTest를 사용하는 지금의 방법이 맞는지, 혹은 어떻게 개선해야할지 조언을 부탁드리고 싶습니다.
> 잘 하고 계십니다. given-when-then 패턴을 사용한 점이 인상깊었어요.

Swift에서 큐(Queue)라는 개념을 이해하기 위해 좋은 팁이나 문서가 있다면 조언부탁드리고 싶습니다. 추후 조언주신 부분으로 조금더 리펙토링하고 싶습니다. ^&^
> Swift에서라는 말이 적합한가 싶어요. Queue는 자료구조입니다.

-------------------------------------------------------------

이제 코드를 읽으면서 느꼈던 아쉬운 점을 말해볼게요.

* 한번에 여러개의 역할을 하는 커밋이 종종 있습니다. 또한 어떤 일을 하는지 커밋 로그를 자세히 봐야 알 수 있는 커밋이 있습니다.
https://github.com/yagom-academy/ios-calculator-app/pull/322/commits/2fd0e57eef8ec1354d48684a7339fd68f4c89990 https://github.com/yagom-academy/ios-calculator-app/pull/322/commits/993fd31ec6dc22be81c6df99e1e724b92c41d11e

* 제네릭을 사용하지 않았습니다. `제너릭에 대해서도 개념이 많이 부족하기 때문에 정확하게 쓸 수 없다면 쓰지 않으려고 했습니다.` 라고 하셨는데, 우리는 지금 학습하는 과정이고, 어떤 기능을 정확하게 사용한다는 것은 많이 어려워보여요. 그래서 어느정도 학습을 하고, 코드에 녹이면서 2차적으로 학습을하는게 좋아보입니다. 그리고 그 코드를 리뷰어와 같이 고민하면서 더 좋은 방향으로 리팩토링하는게 어떨까요?
물론 너무 모르면서 사용하면 문제가 되니 어느정도는 학습을 하고 사용해주세요.

---------------------------------------------------------------------------

나머지는 코멘트를 참고해주세요.

2022-09-21 01:18 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
`enqueue`, `dequeue` 라는 이름이 더 맞아보여요.

2022-09-21 01:18 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
```suggestion
    mutating func subtractQueue() -> String? {
        return queue.removeFirst()
    }
```

이렇게 바꿀 수 있을듯 합니다.

2022-09-21 01:18 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: [String] = [String]()
외부에서 알아야하는 프로퍼티인가요?

2022-09-21 01:18 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
dequeue된 값을 비교하는게 기능상 더 맞는 테스트 아닐까요?

2022-09-21 01:18 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
이 두 테스트 케이스가 같은 기능을 테스트하는거 같습니다.

2022-09-21 01:18 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +@testable import Calculator
이 어노테이션은 어떤 역할을 하나요?

2022-09-21 01:18 UTC, 1Consumption commented on Calculator/CalculatorTests/CalculatorTests.swift
> +final class CalculatorTests: XCTestCase {
final은 어떤 역할을 하나요?

2022-09-22 06:19 UTC, Dylan-yoon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
네 확인했습니다. 
큐, 스택 등 자료구조에서 사용하는 용어를 제대로 알지 못했었기 때문에 제 생각으로 네이밍을 지었습니다.
어느정도 자료구조에 대해서 찾아보고 나니 부끄러워 지는 네이밍이네요 😭
변경했습니다!

2022-09-22 06:30 UTC, Dylan-yoon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: [String] = [String]()
어제 새벽에 캠퍼 7기 웅과 함께 말씀하시면서 생각을 해보았습니다.
private을 붙여줘야할지 private set 을 붙여주어야 할지 고민 했습니다.

private으로 설정한 이유는, 외부에서 큐에 대한 정보를 직접적으로 알 필요는 없을 것이라고 생각했습니다.
여러가지 글들을 찾아 보았는데, queue 내부 정보들을 모두 알려주는 기능을 구현해주는것을 보지 못했습니다.
그렇기 때문에 private으로 제한을 두고 큐에대한 모든 정보를 알려주는 함수 또한 생성하지 않을 예정입니다.
혹시 이부분에 대해서 잘못알고있거나 참고를 해보았으면 하는 부분이 있으면 조언 부탁드리겠습니다.!!

2022-09-22 09:40 UTC, Dylan-yoon commented on Calculator/CalculatorTests/CalculatorTests.swift
> +final class CalculatorTests: XCTestCase {
final 키워드는 클래스가 상속 되는 것을 방지하는데 
calculatorTests가 더이상 상속 받을 필요가 없다고 생각했기 때문에 final키워드를 작성했습니다.

2022-09-22 09:46 UTC, Dylan-yoon commented on Calculator/CalculatorTests/CalculatorTests.swift
> +@testable import Calculator
`@testable` 은 테스트 하기위해 다른모듈에서 가져와야 하는데,
다른 타깃에 있는 코드에 접근하기 위한 키워드입니다.

2022-09-22 18:30 UTC, Dylan-yoon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
네 확인하교 변경했습니다.
감사합니다!

2022-09-22 18:31 UTC, Dylan-yoon commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
위 코멘트와 마찬가지로 기능을 합쳐서 리펙토링 했습니다!

2022-09-23 00:33 UTC, 1Consumption requested changes
코멘트를 확인해주세요.

2022-09-23 00:33 UTC, 1Consumption commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		F6C4E90D28DC6E2900AA9ECF /* String.swift in Sources */ = {isa = PBXBuildFile; fileRef = F6C4E90C28DC6E2900AA9ECF /* String.swift */; };
파일 이름이 정확히 어떤 것을 의미하는지 모르겠습니다. 보통 어떤 타입에 프로토콜을 채택한 파일 이름은 `타입이름+프로토콜이름`으로 짓습니다.

ex) `Int+CalculateItem`

2022-09-23 00:33 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
반환형이 `Bool`타입이면 조건 자체를 리턴하면 가독성이 더 좋아집니다.

```suggestion
    var isEmpty: Bool {
        return queue.isEmpty
    }
```

2022-09-23 00:33 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
이 프로퍼티는 왜 필요한가요? 테스트외에 사용하는 곳이 있나요?

2022-09-23 00:33 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
이 메소드도 필요한 이유를 잘 모르겠습니다. 테스트를 위해 추가한 기능일까요?

추가적으로 `first`의 반환형이 옵셔널이니까 아래와 같이 바꾸는게 좋아보여요.
```suggestion
    func peek() -> CalculatorItem? {
        return queue.first
    }
```

2022-09-23 01:14 UTC, Dylan-yoon commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		F6C4E90D28DC6E2900AA9ECF /* String.swift in Sources */ = {isa = PBXBuildFile; fileRef = F6C4E90C28DC6E2900AA9ECF /* String.swift */; };
어떻게 이름을 지어야할지 몰라서.. 타입이름으로두고 파일화 했습니다.
감사합니다.

2022-09-23 02:14 UTC, Dylan-yoon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
테스트를 위해서 사용한 것은 아닙니다.
자료구조와 큐에 대해서 자료를 찾다보니
기본적으로
queue, enqueue, dequeue, isEmpty, peek, clear, count등으로 구현을 하고 있는것을 이번에 알았습니다.
때문에 어느정도는 구현해 보기 위해, 추후에 사용할 수 있을것 같아, 프로퍼티 생성을 했습니다!

2022-09-23 02:15 UTC, Dylan-yoon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
isEmpty와 first에 대해 정확하게 모르고 썼다는 생각이 드네요.. 
앞으로는 타입확인하면서 더 정확하게 쓰도록 하겠습니다 감사합니다!

2022-09-23 02:16 UTC, Dylan-yoon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
넵 감사합니다 확인했습니다!

2022-09-23 02:18 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
Queue는 꼭 이 기능을 포함해야한다 라는 문서가 있나요? 제 말은 당장 사용하지 않는 기능인데 만들 필요가 있냐 라는 겁니다.

2022-09-23 02:24 UTC, Dylan-yoon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
따로 문서는 없었습니다.
지금 당장 사용하지 않습니다. 
그렇기 때문에 지금 CalculatorItemQueue 에서는 
enqueue, dequeue 만으로 충분 한 것 같다고생각됩니다. 불필요한 기능인 것 같습니다...
앞으로도 당장 필요하지 않은 기능을 '한번해봐야지' 라는 생각으로 만들지 않도록 하겠습니다.ㅠ😭

2022-09-23 02:32 UTC, 1Consumption commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
학습을 하는 사람으로서 한번 해봐야지 라는 마인드는 정말 좋습니다. 
다만 제가 이 피드백을 드린 이유는 count프로퍼티가 실제로는 필요하지 않은데, 테스트의 assertion을 위해 존재한다고 생각하기 때문이었어요.

2022-09-23 02:37 UTC, 1Consumption commented
고생하셨습니다.
다음부터는 베이스 브랜치를 피쳐브랜치로 해주세요.
다음 스텝을 진행하셔도 좋습니다.

2022-09-23 02:37 UTC, merged