계산기 [STEP 1] inho
yagom-academy/ios-calculator-app pull request #327
Opened 2022-09-20 10:20 UTC by inho-98

안녕하세요, @lina0322 
인호입니다! 계산기 앱 진행하는 동안 잘 부탁드리겠습니다!ㅎㅎ

## 고민했던 점
### UML 작성
(UML그림은 리드미에도 작성해두었습니다.)
![](https://i.imgur.com/NtEh2WQ.png)
- `CalculatorItemQueue`는 `Node`타입 프로퍼티를 가지고 있고, 이를 메서드에서 활용하고 있어서 의존 관계를 나타내는 화살표를 이용했습니다.
- `CalculatorItemQueue`가 `CalculateItem`프로토콜을 채택하고 있어서 프로토콜 실체화를 나타내는 화살표를 이용했습니다.

### Queue구현시 배열과 리스트 중 고민
- 큐를 구현하려고 공부하면서 배열과 연결 리스트의 장단점을 이해하고 어떤 방식을 사용할지 고민했습니다. 
계산기의 작동방식을 고려해 보았는데요, `1 + 3 - 2 * 5`등과 같은 연산을 할때, 큐의 첫번째 요소(`예시로는 1, "+" ...`)부터 빼오면서 연산을 할것이라고 생각하고, 배열을 이용하면 첫 요소가 사라질때, 다른 요소의 인덱스가 모두 이동해야하는 점이 비효율적일 것 같아서 단방향 연결 리스트를 이용했습니다.

### `CalculatorItemQueue`타입의 프로퍼티와 메서드
- **`head`프로퍼티**: 계산기를 구현할때, 큐의 마지막 요소에 접근할 필요는 없을 것 같다고 생각하여 `tail`같이 마지막 요소를 나타내는 프로퍼티는 사용하지 않고, 첫번째 요소를 나타내는 `head`만 구현했습니다.
- **`enqueue`와 `dequeue`메서드**: 두 메서드는 큐의 기본적인 요소라고 생각해서 구현했습니다. 
큐에 요소를 추가하는`enqueue`메서드는 마지막 노드의 `next`프러퍼티가 `nil`일때까지 이동하고 마지막 노드뒤에 새로운 요소를 추가합니다.
`dequeue`메서드는 큐의 선입선출 특성에 맞게 첫번째 요소를 제거하면서 반환합니다.
- **`removeAll`메서드**: 계산기에 어떤 기능이 필요할까 고민하다가 모든 요소를 지우는 `AC`버튼의 기능을 위해 생성한 메서드입니다.

### `Node<T>`타입의 프로퍼티
- 타입에 제네릭(T)은 큐에 들어올 요소가 숫자와 문자일것 같아서 사용했습니다.
- `data`와 `next`프로퍼티를 가지고 있습니다.
`next`프로퍼티의 타입이 옵셔널인 이유는 새로운 노드가 추가될때, 항상 다음 노드를 가지고 있지 않기 때문입니다.

## 조언을 얻고싶은 부분
- `Node`타입의 프로퍼티나 `CalculatorItemQueue`타입의 프로퍼티, 메서드 네이밍을 지을때, 일반적으로 큐를 구현할때 많이 사용하는 이름을 사용했습니다. 
일반적으로 사용하는 이름을 그대로 사용해도 좋을지, 혹은 현재 프로젝트에 더 맞는 이름을 사용하는게 좋을지 고민입니다.🤔
- 지금은 `CalculatorItemQueue`타입이 `CalculateItem`프로토콜을 채택하고 있습니다. 그런데 요구사항에는 
    > CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다.

    와 같이 작성되어있는데, "다루는 요소가 프로토콜을 준수한다"는 문장에 대해서 제가 놓친부분이 있는건지 혹은 다음 스텝에서 알수 있을까 싶어 일단 그대로 두었습니다..!

2022-09-20 12:53 UTC, lina0322 requested changes
반갑습니다, 인호!

지금 가지고 있는 의문과 고민들은 그대로 들고 다음 스텝에 가봅시다ㅎㅎㅎㅎ
해보면서 느껴보는거죠~

코멘트 달았는데요, 좀 더 어떤 기능들이 필요할지 생각해보면 좋을거같아요.

어렵거나 이해안가는 부분 있으면 메세지 주세요~
이번 프로젝트도 힘내봅시다!

2022-09-20 12:53 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
CalculatorItemQueue와 Node를 class로 구현하신 이유가 궁금합니다!

2022-09-20 12:53 UTC, lina0322 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        let queue = CalculatorItemQueue<Int>()
매 테스트 마다 queue를 생성해주고 있는데요.
굳이 그럴 필요가 있을까요?ㅎㅎ 방법을 좀 더 찾아봅시다.

2022-09-20 12:53 UTC, lina0322 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(input, queue.head?.next?.next?.data)
마지막 노드에 어떤 값이 들었는지 볼 수 있는 방법을 만드는건 어때요? 영원히 next를 할 순 없을거같은데요!

2022-09-20 14:26 UTC, inho-98 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +}
step1 시작하기 전에 일단 만들었던 테스트 코드인데 필요가 없었습니다😂
삭제했습니다!

2022-09-20 14:54 UTC, inho-98 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        let queue = CalculatorItemQueue<Int>()
테스트에서 사용하는 `sut`프로퍼티를 추가해서 중복을 제거했습니다!
```swift
var sut: CalculatorItemQueue<Int>!
```

2022-09-20 15:37 UTC, inho-98 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(input, queue.head?.next?.next?.data)
해당부분을 작성하면서 이게맞나..? 고민했어서 `last`프로퍼티를 추가해줬습니다! 연산 프로퍼티로 구현했습니다.
```swift
var last: Node<T>? {
    if head == nil {
        return nil
    } else {
        var node = head
        while node?.next != nil {
            node = node?.next
        }
        return node
    }
}
```

2022-09-20 16:39 UTC, inho-98 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(3, result)
`notEqual`이 있는지는 몰랐는데, 말씀해주셔서 적용해봤습니다!👍

2022-09-21 03:04 UTC, inho-98 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T>: CalculateItem {
`Node`는 데이터가 전달되는 과정에서 값 전달이 아닌 참조를 전달해야한다고 생각했습니다.
링크드리스트에서 앞의 노드가 다음 노드에 대한 정보를 가지고 있을때, 가지고 있는 그 정보가 다음 노드의 메모리(참조)라고 생각합니다! 

`CalculatorItemQueue`는 추후의 스텝에서 여러개의 큐를 생성하거나, 이를 전달하는 과정이 있진 않고 하나의 큐에 대해서 작업을 할것이라고 생각했습니다. 그래서 구조체나 클래스 둘다 크게 상관 없을 거라고 생각했습니다..!

2022-09-21 03:09 UTC, inho-98 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssert(queue.head == nil)
`Array`의 프로퍼티와 메서드들 보고, `isEmpty`프로퍼티를 연산프로퍼티로 만들어봤습니다!
```swift
var isEmpty: Bool {
   if head == nil && last == nil {
        return true
   } else {
        return false
   }
}
```

2022-09-21 09:12 UTC, lina0322 reviewed
고생하셨습니다~
추가 코멘트는 다음 스텝에서 수정하거나 이야기 나눠도 좋습니다ㅎㅎ
원하시면 머지해드라고, 아니면 수정하고 말씀해주세요!

2022-09-21 09:12 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
여기도 guard로 탈출시키고, 그 후에 동작하는건 어떨까요?ㅎㅎ
지금도 좋습니다!

2022-09-21 09:12 UTC, lina0322 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
setUpWithError과 tearDownWithError는 꼭 필요한가요? 없으면 어떻게될까요???

2022-09-21 09:13 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
제가 리뷰를 하고있었는데, 수정이 중간에 들어왔네요. 이런 경우에는 놓치는 커밋이 생길 수도 있습니다.
리뷰 요청 후에는 되도록 수정은 하지 말아주시고, 수정이 필요한 경우에는 메세지나 코멘트를 남겨주시길 바랍니다~

이 부분은 헤드만 nil인데, 나머지는 메모리에서 해제해주지 않아도 되나요?ㅎㅎ

2022-09-21 09:20 UTC, inho-98 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        if head == nil && last == nil {
네, 의도적으로 붙여준게 맞습니다..!

2022-09-21 09:21 UTC, inho-98 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
뒤에 다른 코드에서 `guard`문을 사용하기도 했고, 의미도 더 직관적이라고 느껴져서 수정했습니다!

2022-09-21 09:24 UTC, inho-98 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
`Node`의 인스턴스가 언제 메모리에서 해제되는지 `deinit`을 이용해서 확인하고 있었는데요,
사실 테스트에서 위 두 함수가 없어도 테스트가 문제없이 작동되는걸 확인했습니다!
다만 두 함수를 적어줄 때에만 `deinit`이 호출되길래 확실히 하는게 좋겠다 싶어서 사용했습니다..!

두 함수가 없어도 작동되는 이유에 대해서는 구글링을 했는데 관련된 자료는 아직 찾지 못했습니다..!🥲

2022-09-21 09:26 UTC, inho-98 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
기존 코드에서 `head = nil`을 사용하는 방식으로 변경했는데요, 
고민했던건 말씀해 주신대로 "나머지가 메모리에서 해제되는가"였는데, 
`deinit`메서드를 이용해서 헤드의 노드를 지워주면 연쇄적으로 나머지 노드도 메모리에서 해제되는걸 확인하고 
현재 코드로 수정했습니다..!

2022-09-21 09:27 UTC, inho-98 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
아래 코드에서 `guard`문을 사용하기도 했고, `guard`문이 더 직관적으로 느껴져서 수정했습니다!ㅎㅎ

2022-09-22 07:34 UTC, merged