계산기 [STEP 1] SummerCat
yagom-academy/ios-calculator-app pull request #330
Opened 2022-09-20 14:41 UTC by ttokin

@havilog 안녕하세요 하비~~
고민한 것에 비해 코드로 작성된 부분이 적지만..... 정말 많은 고민이 있었는데..
다음에 시간 되실 때 면담 요청드리겠습니다..

# 계산기 [STEP 1] SummerCat

## UML
<img width = "300" src="https://i.imgur.com/d5vQhi5.png">

---

## 고민한 부분

### 1. Queue의 자료 구조 선택 (Double Stack Queue vs Double Linked Stack vs Array)

Double Stack Queue는 이번 프로젝트를 진행하면서 처음 알게 된 자료구조여서 사용해보기로 했습니다.

시간 복잡도 측면에서 비교했을 때
- Array: dequeue할 때마다 removeFirst()해야 하기 때문에, dequeue의 시간복잡도는 항상 O(N)
- Double Stack Queue: outputArr가 비어있을 때 dequeue할 때만 inputArr를 removeLast()하기 때문에, O(N)보다는 평균적으로 작음
- Double Linked List: Dequeue 시 시간복잡도 O(1)로 제일 빠름

### 2. `CalculateItem` 프로토콜을 어디에 적용할 것인가?
```swift
protocol CalculateItem {
    
}

struct CalculatorItemQueue {
	var inItems: [CalculateItem] = []
	var outItems: [CalculateItem] = []
    
	mutating func enqueue(item: CalculateItem) {
		inItems.append(item)
	}   
}
```

`CalculateItem`을 갖는 배열을 `CalculatorItemQueue` 내에 선언할 경우, 테스트 코드에서 아래와 같은 오류가 발생합니다.

<img width = "500" src = "https://i.imgur.com/4z91jpT.png">

→ 이 오류를 해결하기 위해서 `CalculateItem`이 `Equatable`을 준수하게 해주려고 하면 또 아래와 같은 오류가 발생합니다...
<img width = "500" src = "https://i.imgur.com/D7B1NMw.png">

프로토콜 inheritance는 프로토콜 자체에서만 가능하고 extension에서는 불가능하기 때문입니다......

```swift
protocol CalculateItem: Equatable {
	static func ==(_ lhs: _ rhs: ) -> Bool {
		...
	}
}
```

위와 같이 `CalculateItem`이 `Equatable`을 채택하도록 하면 될 것 같은데, 과제 요구사항에 `CalculateItem`을 빈 프로토콜로 남겨두라고 해서 다른 방법을 찾아보기로 했습니다.

결국 아래와 같이 제네릭을 사용해서 구현해 주었습니다.

```swift
protocol CalculateItem {
    
}

struct CalculatorItemQueue<T: CalculateItem> {
    var inputStack: [T] = []
    var outputStack: [T] = []
    
    mutating func enqueue(item: T) {
        inputStack.append(item)
    }
    
    mutating func dequeue() -> T? {
        if inputStack.isEmpty, outputStack.isEmpty { return nil }
        
        if outputStack.isEmpty {
            outputStack = inputStack.reversed()
            inputStack.removeAll()
        }
        
        return outputStack.removeLast()
    }
}
```

그리고 이제 `CalulateItem`을 준수하는 무언가를 활용해서 테스트를 해야 하는데,
처음에는 아래와 같이 `String`이 `CalculateItem`을 준수하도록 해주는 빈 extension 생성해서 `String`을 활용해서 테스트를 진행했습니다.

```swift
extension String: CalculateItem {

}
```

그런데 입력값으로 String이 아닌 입력값을 넣어줄 경우도 있을 것이라고 생각해서, 테스트코드 내에 테스트를 위한 `Item` 구조체를 새로 만들어 주었습니다.

```swift
struct Item: CalculateItem, Equatable {
	var data: String
}
```

<img width = "500" src = "https://i.imgur.com/wZtCaTZ.png">

---

## 해결 안 된 부분

연결 리스트로도 구현해 보려고 했는데, `Node`를 `Equatable`하게 만들어주는 부분에서 실패했습니다.

```swift
class Node<T>: Equatable  {
    static func == (lhs: Node<T>, rhs: Node<T>) -> Bool {
        if lhs.value as? String == rhs.value as? String,
           lhs.prev == rhs.prev,
           lhs.next == rhs.next {
            return true
        }
        
        return false
    }
    
    var value: T
    var prev: Node?
    var next: Node?
    
    init(value: T) {
        self.value = value
        self.prev = nil
        self.next = nil
    }
    
    init(value: T, prev: Node?, next: Node?) {
        self.value = value
        self.prev = prev
        self.next = next
    }
}
```

위와 같이 `==` 함수를 구현하면 아래 테스트 실행 시 `BAD ACCESS` 오류가 발생합니다.
dequeue과정에서 `firstNode`를 `remove`에서 삭제해줄 때, `remove` 내에서 `node == front`로 비교하는 과정에서 `BAD ACCESS`가 발생합니다...😭😭

```swift
func test_dequeue_원소가2개이상일때_1개디큐() {
    // given
    let firstItem: Item = Item(data: "first item")
    let secondItem: Item = Item(data: "second item")
        
    let firstNode: Node = Node<Item>(value: firstItem)
    let secondNode: Node = Node<Item>(value: secondItem)
        
    let expectedDequeuedNode = firstNode

    // when
    sut.enqueue(node: firstNode)
    sut.enqueue(node: secondNode)
    let dequeued = sut.dequeue(node: firstNode)

    // then
    XCTAssertEqual(dequeued, expectedDequeuedNode)
    XCTAssertEqual(sut.list.front, secondNode)
    XCTAssertEqual(sut.list.rear, secondNode)
}
```

2022-09-21 12:02 UTC, havilog requested changes
구현하시느라 고생하셨습니다 써머캣 :)
궁금하신 부분 시간 되실 때 질문 주세요 ㅎㅎ

2022-09-21 12:02 UTC, havilog commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        let expected: Item? = nil
given은 배열이 비어있을 때도 포함되어야하지 않을까요?

2022-09-21 12:35 UTC, ttokin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
확인했습니당! 구현에만 급급해서 이것저것 신경쓰지 못한 부분이 많네요...😭
`Item`으로 변경해주었습니다

2022-09-21 12:50 UTC, ttokin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
removeAll()의 시간복잡도는 `O(N)` (N: 해당 배열이 가지고 있는 원소의 개수)인 것으로 알고 있는데요,
제가 가정해본 두 가지 시나리오에서 시간 복잡도를 계산한 결과는 다음과 같습니다.

```
3개 enqueue -> 1개 dequeue -> 2개 enqueue -> 1개 dequeue
단일 배열:  O(1) + O(N) + O(1) + O(1)+ O(N) = O(2N)
더블 스택:  O(1) + O(N) + O(1) + O(1) + O(1) = O(N)

3개 enqueue -> 3개 dequeue -> 2개 enqueue -> 1개 dequeue
단일 배열: O(1) + O(N) + O(N) + O(N) + O(1) + O(1) + O(N) = O(4N)
더블 스택: O(1) + O(N) + O(1) + O(1) + O(N) + O(1) = O(2N)
```

만약 `원소 하나를 enqueue -> 원소 하나를 dequeue -> 원소 하나를 enqueue -> 원소 하나를 dequeue -> ...` 하는 경우라면 단일 배열과 더블 스택의 시간 복잡도가 동일하겠지만,
`원소 10개를 enqueue -> 원소 10개를 dequeue`한다면 단일 배열과 더블 스택 사이에 시간 복잡도 차이가 꽤 생길 거라고 생각합니다. (단일 배열의 경우 O(N)을 10번 수행, 더블 스택의 경우 O(N)을 한 번만 수행)

2022-09-21 15:29 UTC, ttokin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
그래서 원소의 개수가 적당히 적은 경우에는 더블 스택이 유의미하게 시간 복잡도가 낮다고 생각하지만,
만약에 N이 엄청 커져서 점화식으로 표현하게 되면 둘 다 O(N)으로 표현하게 될 것 같습니다.. 그러면 시간 복잡도가 같아지네요??????😭

2022-09-22 12:37 UTC, ttokin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var outputStack: [T] = []
그러네요.. 외부에서 직접적으로 접근해서 변경까지 할 수 있는것은 적절하지 않다고 생각해서 `private(set)`으로 변경해 주었습니다.

2022-09-22 13:07 UTC, ttokin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
더블 스택은 배열에 비해서 직관적이지는 못한 것 같아서 다른 사람이 보았을 때 한 번에 이해하기는 어려울 수 있을 것 같습니다.
더블 스택을 사용했던 의도는 사용해보지 않은 자료구조를 사용해서 익혀보자! 였습니다.

2022-09-22 13:14 UTC, ttokin commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        let expected: Item? = nil
`CalculatorItemQueue`가 초기화 된 시점에서 빈 배열로 초기화가 되어 있기 때문에 별도로 작성할 필요가 없다고 생각했습니다.

테스트 함수 이름에 "빈배열에서"라는 어구가 포함되어 있어서 빈 배열인것을 `given`에 명시해 주는 것이 좋다는 말씀이실까요?
아니면 혹시 `expectedInputStack`과 `expectedOutputStack`도 작성해서 둘 다 비어있는지 확인하는게 좋겠다는 말씀이실까요?

2022-09-22 13:43 UTC, ttokin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        if isEmpty { return nil }
지금까지는 `guard let`을 활용해서 `let`으로 새로 정의한 상수를 `guard`문 밖에서 사용하고 싶을 때만 `guard`를 쓰고, 그 외에 단순 조건 비교의 경우에는 `if`를 주로 사용했습니다.

하비가 질문해주셔서 조금 더 찾아보니,
`guard`를 사용하면 `guard`문보다 아래에 작성된 코드들은 `guard`에서 제시한 조건을 무조건 만족하고 있다는 것을 imply 할 수 있어서 더 직관적일 수 있겠다고 생각이 드네요.
만약 `guard`의 결과값이 false인 경우에도 공통으로 실행되어야 할 코드가 `guard`문보다 아래에 작성되어 있다면, 그 때는 `if`문을 사용할 것 같습니다.

2022-09-22 15:13 UTC, ttokin commented on Calculator/CalculatorTests/CalculatorTests.swift
> +@testable import Calculator
공식문서 Access Control에 의하면 `internal` 접근 수준은 자신이 정의된 모듈 내에서만 사용이 가능하며, Swift 에서는 Xcode의 각 빌드 **Target을 별도의 모듈**로 취급한다고 합니다.

> 모듈은 코드 배포의 단위(single unit of code distribution). 하나의 단위로 빌드&배포되는 프레임워크나 앱이다. Swift에서는 `import` 키워드를 사용해서 다른 모듈에서 `import`할 수 있다.

→ Unit Test를 추가할 때 Unit Test Target을 추가해서 테스트 코드를 작성했기 때문에, `CalculatorTests`는 별도의 타겟으로 존재하고 있고, Swift에서는 각 빌드 Target을 별도의 모듈로 취급하니까, `import` 해줘야 `CalculatorTests`에서 `Calculator`의 entity들을 사용할 수 있습니다.

만약 `Calculator`에 구현된 모든 것들(클래스/구조체 내에 구현된 모든 메서드와 프로퍼티 포함)의 접근 제어자를 `public`(또는 `open`)으로  설정해 준다면, `@testable` 키워드 없이 `import Calculator`만 해도 테스트 코드는 정상적으로 작동할 것입니다. 왜냐하면 `public`이나 `open`의 경우, 해당 모듈을 `import`하는 모듈에서 접근이 가능하기 때문입니다.

하지만 캡슐화&은닉화를 생각했을 때 모든 것을 `public`이나 `open`으로 설정하는 것은 바람직하지 못하기 때문에 다른 방법으로 `Calculator` 타겟의 entity에 접근해야 하는데, 이 접근을 가능하게 해주는 것이 `@testable` 입니다.

`@testable` 어노테이션을 붙여주면, `internal`이나 `public`으로 작성된 entity가 `open` 레벨이 되게 해줘서 테스트 타겟에서 접근할 수 있게 해 줍니다 (API의 경우에는 `public`으로 해준다고 하는데, API가 뭔지 몇 번 봐도 개념이 잘 안잡히네요).

2022-09-23 09:51 UTC, ttokin commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
요거는 제가 하비 질문의 의도를 잘 파악하지 못하고 있어서 가능하시면 면담 요청 드립니다! 🙇🏻‍♀️

2022-09-23 11:28 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
ㅎㅎ 요 내용은 면접 단골 질문인데요, class와 struct의 차이점이 무엇인지, 왜 해당 객체가 struct로 구현되어야하는지를 좀 더 정리된 말로 명확하게 표현하실 수 있으시면 좋을 것 같습니다 :)

2022-09-23 11:29 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
틀린 코딩은 아니에요! 현업에서도 T, U 쓰시는분들 계시는데 제 개인적인 취향을 알려드린겁니다 ㅎㅎ

2022-09-23 11:31 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        if isEmpty { return nil }
요것도 취향을 타는 부분이긴 하지만, 제 개인적인 의견으로는
요렇게 isEmpty를 보장해야하는 경우?에는 `guard`가 context상 더 어울리는 느낌인거 같아요 ㅎㅎ

2022-09-23 11:34 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
사실 요번에 리뷰하면서 더블스택이라는 개념이 있는지도 처음 알게되었는데요 ㅎㅎ...
알고리즘 풀 때나 실제로 개발할 때 한 번도 경험 못해본 생소한 개념이라 질문드렸었습니다 ㅎㅎ
근거를 가지고 사용하신 모습 보기 좋네요 :)

2022-09-23 11:34 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
요건 좀따 얘기하시죠 ㅎㅎ

2022-09-23 11:34 UTC, havilog commented on Calculator/CalculatorTests/CalculatorTests.swift
> +@testable import Calculator
LGTM 👍

2022-09-23 11:40 UTC, havilog approved these changes
수고하셨어요 썸머캣 :)

2022-09-23 11:40 UTC, havilog commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertEqual(sut.inputStack, expected)
음 사실 제 생각이 틀렸을 수도 있지만,
여기서 테스트하고자 하는 동작은 "enqueue를 했을 때 queue에 item이 들어가는가?"까지라고 생각해요 ㅎㅎ
그래서 저라면? sut의 inputStack에 들어가는지 까지 검증하기 보다는 inputStack을 private으로 설정해두고,
queue의 count를 표현하는 computed property나 isEmpty와 같은 아이로 검증하지 않을까 싶네요!

2022-09-23 11:40 UTC, havilog commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        let expected: Item? = nil
```
// given
배열이 비어있을 때

// when
dequeue를 하면

// then
XCTAssertNil(result) 
```
요런 느낌을 상상하고 남긴 코멘트였습니다 ㅎㅎ

2022-09-24 11:09 UTC, merged