계산기 [STEP 1] L J
yagom-academy/ios-calculator-app pull request #331
Opened 2022-09-20 15:36 UTC by lj-7-77

안녕하세요 라자냐(@wonhee009) 
LJ(@lj-7-77)입니다! 
계산기 STEP-1 PR 보냅니다. 잘 부탁드립니다.

## UML
![](https://i.imgur.com/OFpSoFh.jpg)

---
[STEP 1]
## 고민한 점
### 1. 배열과 리스트 중 무엇을 사용해야 하는지
리스트의 장점은 리스트에 포함된 여러개의 데이터 중 중간에 있는 값을 삭제하거나 특정 위치에 삽입할 때 속도가 빠른점인데, 계산기의 경우에는 그런 상황이 없을 것이라 예상하였습니다.
맨 마지막에 입력받는 값만 지우는 기능인 CE버튼을 사용하는 경우 리스트는 처음부터 맨 마지막까지 찾아가서 확인 후 지워야해서 비효율적이라 생각하였습니다. 
그러나 요구사항명세서에 선택사항이긴 하지만 List 자료구조로 표기된 이유가 있을 것 같은데 아직은 이유를 찾지 못했습니다.

### 2. 입력받는 숫자와 연산자를 열거형으로 만든 이유
사용자로부터 입력받은 숫자와 연산자가 계산기의 버튼으로 한정되어있기 때문에 한정된 값 이외에는 입력받지 않을 수 있는 타입인 열거형으로 사용하였습니다.

### 3. TDD의 실패하는 테스트를 만들 때 **테스트코드의 결과부분**을 고쳐야 하는지, **실제 구현된 메서드 부분**을 고쳐야 하는지
XCTAssertEqual의 예상결과값을 일부러 틀리게하여 콘솔창에서 실패메세지를 확인한 후 맞는 결과값을 넣었습니다. 실패하는 테스트를 먼저 구현 후 실제 메서드코드를 고치는 순서가 맞지만 잘 지켜지지 않았습니다.

---
## 해결하지 못한 점
열거형 연산자에서 빠진 연산자들을 열거형에 case로 추가해주어야 할지, 구조체 CalculatorItemQueue에 구현해야 할지 고민이 되어 좀 더 공부해야 파악할 수 있을 것으로 예상됩니다.

---
## 배운개념
queue(선형,원형), List(노드,단방향,양방향), TDD, enum, UML, NumberFormatter

---
## 참고 링크
[UML-넥스트리소프트](https://www.nextree.co.kr/p6753/)
[UML](https://rldd.tistory.com/m/365)
[NumberFormatter](https://developer.apple.com/documentation/foundation/numberformatter/)
[swift로 queue구현하기 블로그](https://babbab2.tistory.com/86)

2022-09-20 23:36 UTC, wonhee009 requested changes
수고하셨습니다!
코멘트 남겨두었으니 확인 부탁드려요 :)

2022-09-20 23:36 UTC, wonhee009 commented on Calculator/Calculator/ViewController.swift
> +
필요 없는 스페이스가 들어간거 같습니다~

2022-09-20 23:36 UTC, wonhee009 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var resultQueue: [T] = []
사용하지 않는 프로퍼티인거 같은데요. 역할이 뭘까요?.?

2022-09-20 23:36 UTC, wonhee009 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var resultQueue: [T] = []
요구서에 "CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수"라는 조건이 있는데요.
CalculateItem 프로토콜도 없는거 같고, 요소들이 해당 프로토콜을 준수하고 있지 않은거 같습니다.

2022-09-21 02:38 UTC, lj-7-77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var resultQueue: [T] = []
현재는 사용하지 않는 프로퍼티가 맞습니다. queue는 입력받은 숫자를 담아 큐에 추가/삭제할 목적으로, resultQueue는 계산결과를 저장할 목적으로 미리 만들어두었습니다.
테스트할 때만 queue 프로퍼티를 enqueue와 dequeue메서드에서 사용하였습니다.

2022-09-21 08:51 UTC, lj-7-77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var resultQueue: [T] = []
넵, CalculateItem 프로토콜 파일을 추가하고, CalculatorItemQueue에서 프로토콜을 채택하였습니다. 프로토콜이 필요한 이유를 고민하다가 모르니 나중에 필요하면 추가하자는 안일한 생각을 가졌던 것 같습니다. 요구사항 조건임에도 불구하고 가볍게 여겼습니다. 빈 프로토콜의 역할을 공부해보고 적용하면 되었던 건데, 부끄럽습니다. 앞으로는 요구사항 명세서를 꼼꼼히 확인하는 자세를 갖추겠습니다.

빈 프로토콜의 역할은 공식문서에서 타입으로써의 프로토콜에서 찾아볼 수 있었습니다.
실존타입(existential type)으로 불리고, 예로 A프로토콜을 채택한 상수B가 있다면, 해당 상수B에는 A프로토콜을 채택한 어떤타입의 인스턴스든 설정할 수 있다고 합니다.
큐에 넣고싶은 인스턴스가 여러타입(숫자는 Double, 연산자는 String)일 경우, CalculateItem 프로토콜을 채택하여 숫자와 연산자 여러타입을 저장할 수 있는 큐로 만들기 위해 프로토콜이 필요하다고 생각합니다.  

```swift
struct CalculatorItemQueue<T: CalculateItem> { //다루는 요소에 프로토콜 채택
    var queue: [T] = []
    var resultQueue: [T] = []
```

이렇게 프로토콜을 채택하니 테스트파일에서 여러가지 오류가 생겼습니다.
제네릭을 좀 더 공부해보고 시도해본 후 다시 코멘트 작성하겠습니다.

2022-09-21 13:18 UTC, lj-7-77 commented
그리고  `CalculatorItemQueue.swift` 파일에서 `dequeue 메서드`를 더블스택큐 형태로 개선해보고 싶습니다. 수정 후 다시 말씀드리겠습니다.

2022-09-22 02:06 UTC, wonhee009 requested changes

2022-09-22 02:06 UTC, wonhee009 commented on Calculator/Calculator/CalculateItem.swift
> +}
```suggestion
protocol CalculateItem {}
```

2022-09-22 02:06 UTC, wonhee009 commented on Calculator/Calculator/CalculateItem.swift
> +}
굳이 개행하지 않아도 될거 같습니다 :)

2022-09-22 02:06 UTC, wonhee009 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var leftStack: [T] = []
right, left라는 네이밍보다는..
rightStack은 enqueue만 이뤄지는 enqueueStack 이렇게 역할이 잘 드러나는 네이밍은 어떤가요?

2022-09-22 05:02 UTC, lj-7-77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var leftStack: [T] = []
아하 네 명확하게 알 수 있어 좋습니다. 수정하였습니다 :)

2022-09-22 05:20 UTC, lj-7-77 commented
UML도 코드에 맞춰 수정하였습니다.
리뷰 감사합니다. 🤓
혹시 더 의견주실부분이 없다면 머지 부탁드립니다😀

2022-09-22 07:05 UTC, wonhee009 approved these changes
수고하셨습니다 :)

2022-09-22 07:06 UTC, merged