계산기 [Step 1] Jeremy
yagom-academy/ios-calculator-app pull request #332
Opened 2022-09-20 16:16 UTC by yjjem

---
### 🍠 안녕하세요! 🙌
---
@leejun6694
안녕하세여 쿠마 🍠

무려 큐 구현에 딕셔너리를 써보겠다는 생각을 실현시켜 본 7기 제레미입니다...
생각보다 오래 걸려서 시간 내에 못 올렸지만.. 리뷰 잘 부탁드리겠습니다.
태클 너무 좋아요.  🫡

# 🧬UML
![](https://i.imgur.com/wnlPvtF.jpg)

# 🛠 구현 내용

- ***Dictionary***
    - **딕셔너리 선택 이유**
    List의 overhead문제, Insertion, Deletion 시간복잡도 문제 그리고 Linked List의 Search, Acess 시간복잡도 문제를 해결할 수 있는 것이 딕셔너리라는 생각이 들어 아래와 같이 구현을 시도했습니다. 다르게 표현해보자면 요소의 순서 문제만 해결된다면 딕셔너리가 Array와 Linked List의 장점들을 가지게 되겠다는 생각이 선택의 이유입니다.
    
    - **구현하면서..**
    key값으로 순서를 정의해주고 `firstElementIndex`를 정의하여 FIFO을 가능하게 만들었습니다. 딕셔너리로 구현을 해보면서 `KeyValuePairs`를 사용하면 순서가 정의된 딕셔너리를 만들 수 있다는 것을 알게되었지만 제대로 된 사용법을 몰라 사용하지 않았습니다.
    
    ``` swift
    private var elementCount: Int = 0
    private var firstElementIndex: Int = 0
    var queue = [
        0:Item,
        1:Item,
        2:Item,
        3:Item
    ]
    ```
- ***Dictionary 메소드 removeValue(forkey:)***
    ```swift
    mutating func getFirst() -> Item? {
        let firstItem = queue.removeValue(forKey: firstElementIndex)
        firstElementIndex += 1
        return firstItem
    }
    ```
- ***Item*** 구조 
    ```swift
    struct Item: Hashable, CalculatorItem {
        var operation: Operations?
        var sign: NumberSigns?
        var number: Double
    }
    ```
# 🌝 궁금한 점
- 쿠마의 "큐의 올바른 구현"에 대한 견해가 궁금합니다.
- 큐를 딕셔너리로 구현하는 것에 대해서 array의 장점과 linked list의 장점 모두 가지면서 구현할 수 있다고 생각을 하는데. 이는 일리있는 생각인지 궁금합니다.
- private func 를 Unit Test에서 private을 해재하지 않고 사용할 수 있는 방법이 있을까요?
- 리뷰어 추가 해드리려고 했는데 검색해봐도 안나오네요.. 혹시 방법을 아시나요?

2022-09-21 09:57 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +    var queue: [Int: Item] = [:]
딕셔너리로 구현하신 분은 처음이여서 흥미롭네요~!

2022-09-21 10:00 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +    var queue: [Int: Item] = [:]
Int 의 범위를 넘으면 문제가 발생하겠네요..?

2022-09-21 10:04 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +        return lastItem ?? nil
`return lastItem`
위 코드로 충분해보입니다ㅎㅎ

2022-09-21 10:06 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +        elementCount = 0
`firstElementIndex` 는 초기화하지 않아도 괜찮을까요?

2022-09-21 10:13 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +    private var firstElementIndex: Int = 0
우선 위 코드를 당장 봤을 땐, 구현 중 index 관리에서 주의가 많이 필요할 것 같다고 생각되네요~!

2022-09-21 10:13 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +        let firstItem = queue.removeValue(forKey: firstElementIndex)
dictionary 에서 remove value 를 진행하고나서, 메모리가 어떻게 관리되는지 확인을 해봐야할 것 같습니다 : )
요부분은 저도 좀 더 확인해볼게요~!

2022-09-21 10:14 UTC, leejun6694 requested changes
Jeremy 안녕하세요~!
오.. 재밌는 주제를 주셔서 저도 생각을 좀 더 해봐야할 것 같습니다ㅎㅎ
가능하다면 내일 디스코드로 같이 얘기 나눠봐요~!

2022-09-21 10:15 UTC, leejun6694 commented
> private func 를 Unit Test에서 private을 해재하지 않고 사용할 수 있는 방법이 있을까요?

unit test 파일에서 extension 과 fileprivate 을 활용해볼 수 있을 것 같네요~!

리뷰어 추가 해드리려고 

> 했는데 검색해봐도 안나오네요.. 혹시 방법을 아시나요?

요건 저도 잘 모르겠습니다ㅠㅠ

2022-09-24 11:51 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +    func append(newNode: Node<Element>) {
queue 는 대중화된 자료구조 이므로 일반적인 네이밍이 있습니다. 한번 찾아볼까요?

2022-09-24 11:52 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +        if let tail = self.tail {
`tail` 이 아니고 `head` 를 기준으로 체크가 되면 좋을 것 같습니다.
`removeAll()` 과 함께 생각을 해볼까요?

hint : 메모리 해제

2022-09-24 11:53 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +        let result: Node? = head
self 가 생략 가능한 곳에
어떤 곳은 `작성`을 하고 있고
어떤 곳은 `생략`을 하고 있습니다.
하나의 스타일로 맞춰주세요 : )

2022-09-24 11:54 UTC, leejun6694 requested changes
Jeremy 안녕하세요 : )
링크드 리스트로 수정한 부분에 리뷰를 드렸는데 확인 부탁드립니다~!

2022-09-24 17:14 UTC, yjjem commented on Calculator/Calculator/CalculatorItemQueue .swift
> +        let result: Node? = head
지적해주셔서 감사합니다 ! 
불필요한 self를 삭제하였습니다 😊

2022-09-24 17:14 UTC, yjjem commented on Calculator/Calculator/CalculatorItemQueue .swift
> +    func append(newNode: Node<Element>) {
리뷰 감사합니다! 
`enqueue()` 와 `dequeue()`로 네이밍 수정했습니다  😇

2022-09-25 06:03 UTC, yjjem commented on Calculator/Calculator/CalculatorItemQueue .swift
> +        if let tail = self.tail {
enqueue시 head를 기준으로 판별하도록 변경했습니다 ~ 감사합니다

2022-09-25 06:43 UTC, leejun6694 approved these changes
LGTM~!

2022-09-25 06:43 UTC, merged