계산기 [Step2] Kyo
yagom-academy/ios-calculator-app pull request #340
Opened 2022-09-23 04:54 UTC by KyoPak

@uuu1101 
안녕하세요! 태태! Kyo 입니다.
어제 의존성 질문이 많았는데 덕분에 많이 해결되었습니다. 감사합니다.
계산기 Step-2 PR 드립니다. 이번에도 잘부탁드립니다!!🙇👍

### 진행 단계 : Step2
## ⭐️ 구현한 기능
- Operator
    - 요구사항 조건에 맞는 case들과 ```add```,```subtract```,```divide```,```multifly``` private메서드들을 구현하였고 ```calculator()```에서 case에 맞는 메서드들을 호출하였습니다.
- ExpressionParser
    - ```componentsByOperators()``` : String값을 연산자(operator)들을 기준으로 잘라주어 String배열을 리턴하는 메서드입니다.
    - ```parse()``` : String값을 연산자(operator) 기준과 피연산자(operand) 기준으로 나누어 각각 CalculatorItemQueue타입에 넣은 후 Formula타입을 리턴하는 메서드입니다.
- Formula
    - ```result()``` : 연산자만 담긴 CalculatorItemQueue와 피연산자만 담긴 CalculatorItemQueue를 로직을 통하여 계산 결과값을 도출하는 메서드입니다.

![제목 없는 다이어그램](https://user-images.githubusercontent.com/59204352/191893437-3885c44e-cb43-46e6-aeb6-49a7beb0d05e.jpg)

## ⭐️ 코드를 작성할 때 고민되었던 점
- 고차함수를 더욱 잘 활용하였다면 ExpressionParser타입의 ```parse()```, ```componentsByOperators()``` 메서드를 더욱 간결하게 표현했을 수 있을 것 같습니다. 
    - 때문에 가독성 부분을 신경을 썻고 지나친 열거식 고차함수 사용을 지양하였습니다.
- 필요한 file들이 많아짐에 따라서 폴더화 구분을 고민하여 분류하였습니다.
- 아무래도 commandLineTool 환경에서 구현한 것이 아니다 보니 직접 실행 해보는 것이 어려웠습니다. 이러한 문제 때문에도 로직을 구현했을때 UnitTest가 중요하구나를 느낄수가 있었습니다. 

## ⭐️ 해결이 되지 않은 점
- 더 적은 고차함수를 사용하여 간결하게 메서드 내부를 구현하지 못한점..이 아쉽습니다.

## ⭐️ 조언을 얻고 싶은 부분 
- 이번 프로젝트를 진행하며 TDD를 실천하지 못했습니다. 그렇게 하다보니 UnitTest를 진행하였을 때 조금 작성하기가 난해하였고 데이터를 직접 넣어주면서 진행해나갔습니다. 데이터를 직접 넣어주는 UnitTest 방식을 개선하려고 Mock등이 나온건지..? 궁금합니다.
- 고차함수 활용에서 개선방안을 듣고 싶습니다.

2022-09-26 10:18 UTC, uuu1101 requested changes
안녕하세요 Kyo! 
의존성 관련하여 많이 해결이 되었다니 다행이네요 😊
많은 고민들을 하시고 코드를 작성하신 부분들이 보이네요 👍🏻👍🏻👍🏻

몇가지 코멘트 남겨두었어요, 확인 부탁드립니다.
고민해볼 부분을 조금 남겨보자면, 
- 고차 함수를 사용하여 간결하게 표현된 코드와 가독성이 좋은 코드가 있다면 Kyo는 어떤 코드를 선택하실지 궁금합니다. 물론 고차함수 사용을 지양하자고 하는 말이 아니니 이러한 부분을 한번 고민해보시면 좋을 것 같습니다.

- TDD에 있어서 테스트에 필요한 데이터가 나온 배경이 궁금하신걸로 이해를 했습니다.
이 부분도 TDD에서 테스트 코드를 작성하고 실행하는 시점이 언제인지 생각해보시면 좋을 것 같아요.
우리가 구현해야하는 기능이 어떤것이 있는지 먼저 생각해보고 그 로직을 검증하기 위한 코드는 어떤게 있을지 고민해보면 TDD 관련하여 UnitTest하는데 있어 조금 더 수월하지 않을까 싶습니다.

- 고차 함수 활용에서 개선방안이라고 하셨는데, 어떠한 개선방안을 여쭙는지 궁금합니다.
그 전에 제가 먼저 위에서 드렸던 질문을 고민해 보시면 좋을 것 같습니다.

코드에는 정답이 없기 때문에 저 또한 다른 리뷰어 분들과 생각이 다를 수 있어요.
그렇기에 조언 드리는 내용은 저의 주관적인 생각이 많이 들어가기 때문에 이렇게 질문을 먼저 드리는 것이고, Kyo만의 코드를 작성한 근거가 있다면 그것 또한 좋은 코드라고 생각합니다 👍 
상황에 따라 간결한 코드가 좋은 코드일 수 있고, 긴 코드가 좋은 코드가 될 수도 있어요. 😊

2022-09-26 10:18 UTC, uuu1101 commented on Calculator/Calculator/Models/Operator.swift
> +enum Operator: Character, CaseIterable, CalculateItem {
`String`이 아닌 `Character`를 채택하셨네요 👍🏻
이렇게 `Character`를 채택하게 된 배경이 궁금합니다 :)

2022-09-26 10:30 UTC, KyoPak commented on Calculator/Calculator/Models/ExpressionParser.swift
> +        let operatorComponents = input.map { String($0) }.filter { operatorTypes.contains($0) }
`map`과 `compactMap`의 가장 큰 차이점으로는 `compactMap`은 옵셔널요소를 제거한다는 점입니다. 
옵셔널 바인딩과 nil값을 자동으로 제거해준다는 점이 가장 큰 차이점이라고 생각됩니다.

2022-09-26 12:05 UTC, KyoPak commented on Calculator/Calculator/Models/Operator.swift
> +enum Operator: Character, CaseIterable, CalculateItem {
기본적으로 String채택시 rawvalue를 문자열, Character채택시 문자를 rawValue로 지정하게 됩니다.
그외에 열거형에서 String을 채택하면 rawValue를 지정안해주는 상황이 되었을때, 그대로 case의 이름이 들어가게 됩니다.
```swift
enum Operator: String, CaseIterable {
    case add               // rawValue : "add"
    case subtract          // rawValue : "subtract"
    case divide            // rawValue : "divide"
    case multifly          // rawValue : "multifly"
}
```
하지만  Character을 채택하게 된다면 rawValue를 직접 지정해줘야합니다.

이정도로만 파악 중인데.. 혹시 제가 놓친 또 다른 차이점이 있을까요?🤩

2022-09-26 12:50 UTC, KyoPak commented
태태 ! 좋은 코멘트와 많은 질문거리들을 주셔서 감사합니다! 제가 나름 태태의 질문에 고민 후 답변 달아보았습니다 !

1. 고차 함수를 사용하여 간결하게 표현된 코드와 가독성이 좋은 코드가 있다면 Kyo는 어떤 코드를 선택하실지 궁금합니다. 물론 고차함수 사용을 지양하자고 하는 말이 아니니 이러한 부분을 한번 고민해보시면 좋을 것 같습니다.
    - 이 부분에 대해서는 조금 더 고민을 해보고 실력을 쌓은 후, 지향점을 정해야 할 것 같습니다. 
    - 하지만 둘중 하나를 정하자면..가독성이 더 중요한 요소인 것 같습니다. 왜냐하면 코드의 양이 방대해질수록 협업, 유지보수를 위해서 가독성에 더 힘써야 하지 않을까 생각합니다!


2. TDD에 있어서 테스트에 필요한 데이터가 나온 배경이 궁금하신걸로 이해를 했습니다.
이 부분도 TDD에서 테스트 코드를 작성하고 실행하는 시점이 언제인지 생각해보시면 좋을 것 같아요.
우리가 구현해야하는 기능이 어떤것이 있는지 먼저 생각해보고 그 로직을 검증하기 위한 코드는 어떤게 있을지 고민해보면 TDD 관련하여 UnitTest하는데 있어 조금 더 수월하지 않을까 싶습니다.
    - TDD 부분이 상당히 어렵네요..구현할 기능을 먼저 생각을 해봐야겠네요! 감사합니다. 데이터나 객체를 임의로 집어넣는 방법들은 직접 공부해보며 알아보겠습니다..!


3. 고차 함수 활용에서 개선방안이라고 하셨는데, 어떠한 개선방안을 여쭙는지 궁금합니다.
그 전에 제가 먼저 위에서 드렸던 질문을 고민해 보시면 좋을 것 같습니다.
    - 넵! 부족한 부분? 가독성등 제 코드에 대한 태태의 피드백을 들어보고 싶었습니다..!ㅎㅎ

4. UML에서 +와 -는 어떤 의미일까요?
    - UML에서 +는 개방(open,public,internal) -는 폐쇄(fileprivate, private)를 의미하는 것으로 알고 있습니다!

5. UML에서 밑줄쳐져있는 것은 어떤 의미일까요?
    - UML에서의 밑줄은 Static을 의미하는 것으로 알고 있습니다!

6. Test 쪽과 Calculator 타겟의 최소 OS버전이 다르던데, 의도하신걸까요?
    - iOS와 Test버젼은 미쳐 생각을 못했던것같습니다..! 이번 경험을 잊지않겠습니다🥲

2022-09-27 14:46 UTC, uuu1101 commented
제네릭의 네이밍을 지정해주신 부분 좋습니다 👍🏻
고차함수 관련해서는 잘 사용하시고 계신것 같아요. 다만 처음 사용하실때 축약형보다는 풀어쓰시는걸 추천드리고
익숙해지시면 그때 축약형을 사용하는것도 좋은 방법이라고 생각합니다 :)

2022-09-27 14:46 UTC, merged