계산기 [STEP 2] inho
yagom-academy/ios-calculator-app pull request #342
Opened 2022-09-23 07:53 UTC by inho-98

안녕하세요, @lina0322 
인호입니다ㅎㅎ
이번 PR도 잘부탁드립니다🙌

## UML
![](https://i.imgur.com/B8KGbFd.png)
UML에 작성된 내용을 바탕으로 과제를 진행했습니다!

## 고민했던 점
### Step1 연장선
#### `CalculateItem`프로토콜의 역할
지난 스텝에서 `CalculatorItemQueue`가 `CalculateItem`을 채택하는게 아닌것 같다는 생각을 했는데, 이번 스텝에 와보니 큐 요소가 프로토콜을 채택하는 것이었습니다.(`Double`과 `Operator`) 
그래서 기존에 `CalculatorItemQueue`에 채택되어 있던 프로토콜은 삭제했습니다!

---
### Step2
> 변수보다는 상수를, 반복문 조건문 보다는 고차함수를 더 활용하도록 노력해보세요.

과제의 요구사항을 계속 고려하면서 작성하였습니다.
### UML 이해
- UML을 기반으로 접근 제어를 사용하고, `ExpressionParser`에 밑줄된 메서드가 타입 메서드를 의미한다는 걸 알게되고 적용했습니다.
### `Formula` 타입과 메서드
- `Formula`타입의 `result`메서드는 연산자와 피연산자 큐를 이용하여 결과를 리턴합니다.
- 피연산자큐인 `operands`가 비워질때까지 `dequeue`와 `calculate`을 시행하고, 이전의 연산 결과가 `lhs`에 할당됩니다.
(1+2+4-7 -> 3+4-7 -> 7-7 )
- 계산기에서 입력된 요소 없이`=`을 누르면(결과를 호출하면) 0을 리턴합니다. 입력된 요소가 없다는 것은 `oprands`의 큐가 비어있고, `lhs`가 없는 상황을 의미합니다.
- `rhs`가 없는 상황은 `lhs`와 연산자까지만 입력하고 결과를 호출하는 상황인데, 이때는 연산자는 무시하고 마지막 연산결과인 `lhs`를 리턴합니다.
```swift
func result() -> Double {
    guard var lhs = operands.dequeue() else { return 0 }
        
    while !operands.isEmpty {
        guard let rhs = operands.dequeue() else { return lhs }
        guard let `operator` = operators.dequeue() else { return 0.0 }
        lhs = `operator`.calculate(lhs: lhs, rhs: rhs)
    }
    let result = lhs
        
    return result
}
```

### 입력된 문자열을 큐로 변경하는 방법
- 계산기의 입력이 끝났을때, 연산할 `input`이 어떤 형태로 전달될까 고민했습니다. 
처음에는 `1+2+6*4%9`와 같이 들어올 것이라고 생각했는데
계산기 동작 화면에서 아래 사진과 같이 연산자의 `-`와 부호를 나타내는 `-`를 구분짓기 위해 `1 + 2 + 6 * 8 % -9`와 같이
**연산자와 피연산자를 공백으로 구분하여** 전달 될것이라고 판단했습니다. 이런 입력을 가정으로 나머지 코드가 작성되었습니다.
![](https://i.imgur.com/2mCLauC.png)

### String extension의 `split()`메서드
- 입력받은 문자열을 매개변수인 `target`을 기준으로 자르고, 배열에 담아 리턴하는 함수입니다.
프로젝트에서는 공백을 기준으로 문자열을 자르는 곳에 사용됩니다.
```swift
let input = "1 + 2 - 5 % -4"
let separatedInput = input.split(with: " ")
//[1, +, 2, -, 5, %, -4]
```
### `ExpressionParser`의 `componentsByOperators()`메서드
- `componentsByOperators`의 역할을 네이밍과 parse와의 관계를 바탕으로 오래 고민했는데요, 최종적으로는 "operator 옆의 요소들"이라고 해석하여 입력받은 문자열(`inpuut`)에서 피연산자 배열만을 리턴하는 함수라고 결정했습니다.
- 위의 `split`메서드를 이용해서 먼저 공백을 제거한 문자열 배열을 만든 뒤, 각 문자열 요소 중에 숫자를 포함하는 요소들만 `filter`하여 리턴합니다.
```swift
let separatedInput = input.split(with: " ")
let components = separatedInput.filter({ $0.filter({ $0.isNumber }).count != 0 })
        
return components
```
### `ExpressionParser`의 `parse()`메서드
- `parse`메서드의 역할을 "입력 요소 중 원하는 정보를 추출한다"라고 생각했습니다. 
- `operandsInInput`은 `componentsByOperators()`메서드에서 전달받은 값을 `Double`의 형태로 변환합니다.
- `operatorsInInput`은 `input`중에서 연산자의 `rawValue`와 같은 요소를 `fliter`합니다.
- `input`에서 받은 연산자와 피연산자는 각각 `forEach`를 이용해 큐에 담습니다.(`enqueue`)

```swift
static func parse(from input: String) -> Formula {
    let operands: CalculatorItemQueue<Double> = .init()
    let operators: CalculatorItemQueue<Operator> = .init()
    let operandsInInput = componentsByOperators(from: input).compactMap { Double($0) }
    let operatorsInInput = input.split(with: " ")
                                .filter({ $0.count == 1 })
                                .compactMap { Operator(rawValue: Character($0)) }
        
    operandsInInput.forEach({ operand in
        operands.enqueue(element: operand)
    })
        
    operatorsInInput.forEach({ `operator` in
        operators.enqueue(element: `operator`)
    })
        
    return Formula(operands: operands, operators: operators)
}
```

## 조언을 얻고싶은 부분
### Extension 파일 분리
- `String`과 `Double`의 `Extension`을 파일을 분리하여 만들었는데, 지금 방식도 괜찮은지, 아니면 타입 별로도 나누어야하는지 궁금합니다!
#### `ExpressionParser`과 `split()`메서드
- 지금 구현해 놓은 `componentsByOperator()`과 `split()`메서드들에 대해서 확실하지 않은 부분이 있습니다. 다른 방법이 더 있을것 같다는 생각도 들고, 지금 방법에서도 굳이? 싶은 부분이 있는데 엘림 의견도 궁금합니다..!!

2022-09-26 13:19 UTC, lina0322 requested changes
이번 스텝도 고생하셨습니다!

---

1. UML을 가지고 하는 프로젝트는 어땠나요?ㅎㅎ UML의 장단점은 어떤게 있을까요?
2. 마찬가지로 TDD의 장단점은 무엇일까요? 이번에 테스트 코드를 먼저 짜보셨을까요?🙂
3. 테스트 수가 너무 적습니다.. 실패하는 테스트까지 포함해서 최소 10개 이상은 해보셔야할거같아요. 특히 계산기는 상당히 복잡한 로직과 다양한 경우를 마주할 수 있기 때문에 다양한 테스트가 필요해보입니다!
4. 에러 처리가 미흡해보여요. 실제 계산기 동작을 좀 더 명확하게 파악해야할 것 같아요. 

---

아래에 코멘트 남겨놓았습니다! 천천히 반영해보시고, 궁금한거나 이해가 안가는 부분 있으시면 편하게 메세지 주세요!!

2022-09-27 08:12 UTC, inho-98 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +                                    .filter({ $0.count == 1 })
```swift
let operatorsInInput = input.split(with: " ")
                            .filter { $0.count == 1 }
                            .compactMap { Operator(rawValue: Character($0)) }
```
`Operator`를 `rawValue`로 생성할때, `Character`타입으로 에러없이 변환하기 위함입니다!
`filter`메서드가 없으면 "12"같이 한자리 이상의 숫자도 포함되기 때문입니다.

2022-09-27 08:13 UTC, inho-98 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        })
의미 전달 차원에서 남겨두었었는데요, 다시 보니 축약 문법을 사용해도 의미가 잘 전될되는것 같아 아래처럼 수정했습니다!
```swift
operandsInInput.forEach { operands.enqueue(element: $0) }        
operatorsInInput.forEach { operators.enqueue(element: $0) }
```

2022-09-27 08:15 UTC, inho-98 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorsInInput = input.split(with: " ")
고민을 해봤는데, in 이 생략되면 "입력 중 연산자"가 아닌 "연산자 입력", "피연산자 입력"처럼 해석이 돼서
의미가 많이 다르다고 생각해서 그대로 유지했는데요..! 어떻게 생각하시나요?🤔

2022-09-27 08:18 UTC, inho-98 commented on Calculator/Calculator/Model/Formula.swift
> +        return result
말씀해 주신 몇가지 부분이 에러로 처리돼야해서 에러를 추가하고, 0으로 나누는 것에대한 처리도 추가했습니다!

https://github.com/yagom-academy/ios-calculator-app/pull/342/commits/531df16fa19028f9124b04ff89c4b5e2b520831d: 에러 처리
https://github.com/yagom-academy/ios-calculator-app/pull/342/commits/0cecc1b87d5d6488d3be0413f9cd1fd0de9a2bd2: 0으로 나누는 상황에 대한 처리

2022-09-27 08:18 UTC, inho-98 commented on Calculator/Calculator/Model/Operator.swift
> +    case divide = "%"
계산기 앱의 모양을 생각하면서 "%"로 작성했는데,
실제 연산 기호를 생각하면 "/"인것 같아서 수정했습니다!😅

2022-09-27 08:20 UTC, inho-98 commented on Calculator/FormulaTests/FormulaTests.swift
> +    }
말씀해 주신대로 테스트가 부족해보여서 테스트 케이스를 더 추가했습니다!

- https://github.com/yagom-academy/ios-calculator-app/pull/342/commits/1530d8c0628535e9f419b110ec1fc884be37547a : Formula에 대한 테스트
- https://github.com/yagom-academy/ios-calculator-app/pull/342/commits/977346924e3bb0cb9a667eac37c076a3944eef09: ExpressionParser에 대한 테스트

2022-09-27 08:22 UTC, inho-98 commented
> UML을 가지고 하는 프로젝트는 어땠나요?ㅎㅎ UML의 장단점은 어떤게 있을까요?
- 처음에는 
마찬가지로 TDD의 장단점은 무엇일까요? 이번에 테스트 코드를 먼저 짜보셨을까요?🙂
테스트 수가 너무 적습니다.. 실패하는 테스트까지 포함해서 최소 10개 이상은 해보셔야할거같아요. 특히 계산기는 상당히 복잡한 로직과 다양한 경우를 마주할 수 있기 때문에 다양한 테스트가 필요해보입니다!
에러 처리가 미흡해보여요. 실제 계산기 동작을 좀 더 명확하게 파악해야할 것 같아요.

2022-09-28 04:05 UTC, lina0322 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorsInInput = input.split(with: " ")
저는 input이 입력 값이라는 의미도 가능하다고 생각했습니다!
```
입력.split(with: " ")
입력값.split(with: " ")
```
네이밍도 개인 취향이 있다고 생각해서 본인이 원한다면 굳이 변경하지 않아도 좋아욥!

2022-09-28 04:06 UTC, merged