계산기 [STEP 2] 준호
yagom-academy/ios-calculator-app pull request #345
Opened 2022-09-23 11:14 UTC by junho15

@1Consumption 

올라프 안녕하세요.
계산기 프로젝트 STEP 2 PR을 보냅니다.
기능 구현에 생각보다 시간이 많이 소요되서 PR이 늦었네요.
이번에도 잘 부탁드립니다.

## 구현 내용
* Operator - Character 타입의 rawValue를 가지고, CaseIterable, CalculateItem 프로토콜을 채택함.
    - calculate(Double, Double) -> Double? - Double 타입의 두 값을 전달 받아서 self의 연산자별 연산 메서드로 연산을 해준 뒤 반환함. ( 0으로 나누면 nil을 반환하도록 옵셔널 타입으로 구현 )
    - add/subtract/divide/multiply(Double, Double) -> Double - 각 연산 메서드는 private 키워드를 추가해서 은닉화함.
* Double+CalculateItem - Double 타입이 CalculateItem 프로토콜을 채택하도록 extension 추가.
* String+split - String 타입에 split 메서드를 추가하기 위해 extension 추가.
    - split(Character) -> [String] - 전달 받은 Character 값으로 문자열을 나눈 후 배열로 반환함.
* CalculatorItemQueue - 클래스에서 구조체로 변경 ( STEP2 UML에 맞게 수정 )
* Formula
    - operands - 피연산자를 저장하는 CalculatorItemQueue<Double> 타입의 프로퍼티.
    - operators - 연산자를 저장하는 CalculatorItemQueue<Operator> 타입의 프로퍼티.
    - result() -> Double? - operands와 operators의 값으로 연산해서 결과를 반환하는 메서드.
* ExpressionParser
    - parse(String) -> Formula - 문자열을 입력 받으면 연산자와 피연산자를 나누어서 Formula 타입으로 반환하는 메서드.
    - componentsByOperators(String) -> [String] - 전달 받은 문자열을 Operator로 나눈 후 피연산자 부분만 문자열 배열로 반환함.
    - 두 메서드 모두 인스턴스 없이 사용할 수 있도록 타입 메서드(static)로 선언.

 ## UML
<img width="1104" alt="UML" src="https://user-images.githubusercontent.com/48776496/191948103-4c768a08-07a3-4f91-aa51-037b5d7d07cc.png">

## 코드를 작성할 때 고민되었던 점
* 음수 처리
    - STEP2에서 음수를 처리하는 부분이 제일 까다로웠습니다.
    - "-12--1+-3" -> 연산자 = [-, +], 피연산자 = [-12, -1, -3] (ExpressionParserTests의 두 번째 테스트 케이스)
    - 문자열 "-12--1+-3"에서 피연산자를 가져오는 기능을 componentsByOperators(String) -> [String] 메서드에서 구현했습니다.
    ~~~swift
        private static func componentsByOperators(from input: String) -> [String] {
            var result: Array<String> = [input]
            for operatorCase in Operator.allCases {
                result = result.flatMap { $0.split(with: operatorCase.rawValue) }
            }
    ~~~
    - 우선 String 타입에 extension으로 추가한 split 메서드와 flatMap 을 사용해서 모든 연산자로 분리를 해 주었습니다. 
    - "-12--1+-3" -> ["", "12", "", "1", "", "3"]
    - 음수를 표시하는 - 도 빼기 연산자로 인식해서 음수일 경우 앞에 "" element가 생깁니다.
    - 아래 부분에서 ""는 없애고, "" 뒤에 오는 문자열에는 -를 붙여서 반환해주도록 했습니다.
    ~~~swift
            var isNegative: Bool = false
            result = result.compactMap {
                if $0 == "" {
                    isNegative = true
                    return nil
                } else {
                    let value: String = isNegative ? "-\($0)" : $0
                    isNegative = false
                    return value
                }
            }
            return result
        }
    ~~~

    - parse 메서드에서는 componentsByOperators 메서드에서 반환한 String 배열을 Double 타입으로 바꿔서 operands에 enqueue 했습니다.
    ~~~swift
        static func parse(from input: String) -> Formula {
            var result: Formula = Formula()
            
            componentsByOperators(from: input).compactMap { Double($0) }.forEach {
                result.operands.enqueue($0)
            }
            
    ~~~
    - 아래 부분에서는 문자열 "-12--1+-3"에서 연산자만 operators에 enqueue하도록 했습니다.
    - 첫글자에 있는 - 는 음수를 나타내므로 removeFirst로 제거했습니다.
    - 연산자 뒤에 오는 - 는 모두 음수를 나타내는 기호이기 때문에 마찬가지로 제거했습니다.
    - 마지막으로 숫자를 제외한 연산자만 operators에 enqueue 했습니다.
    ~~~swift
            var inputRemovedNegativeSignal: String = input
            if input.hasPrefix("-") {
                inputRemovedNegativeSignal.removeFirst()
            }
            Operator.allCases.forEach {
                inputRemovedNegativeSignal = inputRemovedNegativeSignal.replacingOccurrences(of: "\($0.rawValue)-", with: "\($0.rawValue)")
            }
            inputRemovedNegativeSignal.compactMap { Operator.init(rawValue: $0) }.forEach {
                result.operators.enqueue($0)
            }
            
            return result
        }
    ~~~

* TDD
    - STEP2 에서도 최대한 TDD로 코드를 작성하려고 했습니다.
    - 추가한 enum, struct, extension에 대응하는 Tests 클래스를 만들어서 각각의 테스트 케이스를 추가했습니다.
        + enum Operator - OperatorTests
        + extension String - StringTests
        + struct Formula - FormulaTests
        + enum ExpressionParser - ExpressionParserTests

## 조언을 얻고 싶은 부분
* STEP2 UML에 오류 처리를 위한 Enum이 없어서, 우선 0으로 나누기를 시도하는 경우 nil을 반환하도록 했습니다. 혹시 다른 방법이 있을까요?

### 참고링크
* [hasPrefix](https://developer.apple.com/documentation/swift/string/hasprefix(_:))
* [replacingOccurrences](https://developer.apple.com/documentation/foundation/nsstring/1412937-replacingoccurrences)

2022-09-26 13:17 UTC, 1Consumption requested changes
고생하셨어요 @junho15 

코드가 전체적으로 나이스하네요.
솔직히 리뷰할게 별로 없습니다... 앞으로도 이렇게만 해주세요.

그래도 코멘트를 남겼으니 참고 부탁드릴게요.

2022-09-26 13:17 UTC, 1Consumption commented on Calculator/Calculator/Model/Operator.swift
> +            return divide(lhs: lhs, rhs: rhs)
nil 보다는 명확한 error를 던지는게 더 괜찮아보여요. nil은 약간 의미가 모호하네요.

2022-09-26 13:17 UTC, 1Consumption commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        XCTAssertTrue(resultOpernads == expectedOperands && resultOperators == expectedOperators)
이런 조건에는 상수로 이름을 붙이는게 어떨까요? 테스트 펑션 이름을 읽으면 되긴 하지만, 코드 자체의 가독성은 안좋네요.

2022-09-26 13:17 UTC, 1Consumption commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        }
이건 개인적인 취향인데, 컨디션에는 앞에! 을 붙이는 걸 선호하지 않아요. 가독성이 안 좋다고 생각하거든요. 저는 짧은데 가독성이 안 좋은 코드보다는 약간 길지만, 가독성이 좋은 코드를 선호합니다.

2022-09-27 04:17 UTC, junho15 commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        XCTAssertTrue(resultOpernads == expectedOperands && resultOperators == expectedOperators)
- ecb9925 에서 결과 값과 예상 값을 비교하는 상수(isEqualToExpectedOperands, isEqualToExpectedOperators)를 추가하고 사용하도록 수정했습니다.

2022-09-27 04:18 UTC, junho15 commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        }
- a024be6 에서 "!" 대신 "== false"를 사용하도록 수정했습니다.
- 가독성 있는 코드를 작성하도록 앞으로도 고민하겠습니다. 감사합니다.

2022-09-27 04:19 UTC, junho15 commented on Calculator/Calculator/Model/Formula.swift
> +            guard let lhs: Double = result != nil ? result : operands.dequeue(),
- e70f345 에서 삼항연산자 대신 if-else 문을 사용하도록 수정했습니다.

2022-09-27 04:22 UTC, junho15 commented on Calculator/Calculator/Model/Operator.swift
> +            return divide(lhs: lhs, rhs: rhs)
- ace2b1e 에서 오류 처리를 위해 열거형 CalculateError를 추가했습니다.
- 8a75dfa 에서 0으로 나누려고 할 때 error를 throw하고 호출하는 쪽에서 do-try-catch문으로 처리하도록 했습니다.
- 테스트 케이스도 try? try!를 사용해서 오류 처리에 대응하도록 수정하고, 0으로 나누려고 할 때 error가 던져지는지 확인하도록 케이스를 수정했습니다.

2022-09-27 04:24 UTC, junho15 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
- 지금 연산자 큐/피연산자 큐를 사용하고 있는데, 말씀 주신 스택을 사용하는 방법이 바로 떠오르지 않습니다. 좀 더 힌트를 받을 수 있을까요?

2022-09-27 04:30 UTC, junho15 commented on Calculator/Calculator/Extensions/String+split.swift
> +}
- 우선 STEP 2에서 제시된 UML대로 extension을 만들어보았습니다.
- 기존 split은 반환 타입이 [SubSequence] 타입이고, components는 매개 변수 separator가 string 타입입니다.
- character 타입을 매개변수로하고 [String] 타입으로 반환하는 새로운 메서드를 추가하라는 의미로 이해하고 추가했습니다.

2022-09-27 04:35 UTC, junho15 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
- class로 하면 하나의 인스턴스를 계산기 앱 내에서 공유한 뒤, 인스턴스를 참조하는 모든 곳에서 인스턴스의 변경 값을 바로 확인할 수 있습니다. 때문에 STEP 1에서는 class를 선택했습니다.
- STEP 2에서는 제시된 UML(struct)에 맞게 수정했습니다.

2022-09-28 13:06 UTC, merged