계산기 [STEP2] 제이푸시
yagom-academy/ios-calculator-app pull request #346
Opened 2022-09-23 11:45 UTC by jjpush

안녕하세요 알라딘! @junbangg 
STEP2가 완료되어서 PR 보내드립니다! 😁

오늘 TDD의 좋은 점을 확실히 느꼈는데
그냥 구현하는 것보다 시간은 오래 걸리지만
코드 내에서 구현이 복잡해져도 어떤 값을 넣었을 때 어떤 값이 나와야 하는지가 명확하니
좋은 설계가 유도되는 것 같네요.. 저는 오늘부터 TDD 신봉자가 되기로 했습니다 👍👍
사용하다보면 시간도 조금씩 빨라지겠죠? ㅎ

# 🛠 기능 설명

## Formula

- operands
    - 기존 코드에는 제네릭으로 <Item: CalculatorItem>을 받았으나 operands는 Double 타입만 받도록 수정했습니다.
- operators
    - 마찬가지로 Operator 타입만 받도록 수정했습니다.

- result()
    - 수식은 항상 피연산자가 하나 많게 설계되어 있으므로 첫 번째 피연산자를 result로 먼저 가지고 있습니다.
    - 피연산자 큐와 연산자 큐 모두 empty 일때까지 반복문을 실행합니다.
    - 값을 뽑아내지 못하면 잘못된 수식이므로 Error를 던집니다.
    - 피연산자 큐와 연산자 큐에서 하나씩 뽑아낸 후 계산을 수행합니다.
    - 계산에서 오류가 발생하는 경우 Error를 던집니다.

## Operator
- calculate(lhs: Double, rhs: Double)
    - 어떤 열거케이스로 들어오는지를 switch문으로 체크해서 해당하는 메서드를 실행합니다.
- add(lhs: Double, rhs: Double)
    - lhs에 rhs를 더하는 메서드
- subtract(lhs: Double, rhs: Double)
    - lhs에 rhs를 빼는 메서드
- divide(lhs: Double, rhs: Double)
    - lhs에 rhs를 나누는 메서드
    - 0으로 나누는 경우 divideZeroError를 던집니다.
- multiply(lhs: Double, rhs: Double)
    - lhs에 rhs를 곱하는 메서드

## ExpressionParser

- parse(from input: String)
    - 연산자를 기준으로 나눠진 숫자와 연산자가 있는 String 배열을 Formula 인스턴스 내부의 큐에 넣은 후 formula를 return 합니다. 
- componentsByOperators(from input: String)
    - 매개변수로 들어온 string을 숫자와 연산자로 나누어 배열로 만든 후 return 합니다.
    - 알고리즘
        - 매개변수로 들어온 값은 components로 초기화
        - "1+23-4" 가 들어올 경우 `+, -, *, /`를 반복해서 분리.
        - +. 분리된 "1", "+", "23-4" 값을 progressSplit에 추가
        - -. 분리된 "1", "+", "23", "-", "4" 값을 progressSplit에 추가
        - components 업데이트.
        - components 내부 요소를 forEach 문으로 반복.
- enqueue(_ component: String, in formula: inout Formula)
    - 가독성을 위해 만든 메서드 입니다.
    - 매개변수로 받은 String을 Double인지, 연산자인지 판단 후 formula의 operands 큐와 operators 큐에 넣는 기능을 합니다.

## Error

- divideZeroError
    - 0으로 나눌 경우 발생하는 에러 입니다.
- wrongFormulaError
    - 수식이 잘못되었을 경우 발생하는 에러 입니다.

## Extensions
### Double
- protocol을 채택해주는 extension 입니다.
- extension 맥락에 맞게 protocol 파일에서 옮겼습니다.

### String
- split(with target: Character)
    - String을 확장해서 self의 값을 target을 기준으로 나누어 return 하는 메서드 입니다.
    - self의 forEach 문으로 target에 해당하는 값이 나올 때까지 component에 담고 있다가 target이 나오는 순간 component와 target을 result에 추가합니다.
    - 이후 마지막 더미를 넣어주기 위해 한번더 추가합니다.

# 🤔 고민한 점

## Formula 인스턴스의 제네릭

```swift=
struct Formula<Item: CalculateItem> {
    var operands: CalculatorItemQueue = CalculatorItemQueue<Item>()
    var operators: CalculatorItemQueue = CalculatorItemQueue<Item>()
```
Formula 인스턴스를 생성하면서 Formula<Item: CalculatorItem> 의 형태가 되어야 하는지 고민했었습니다.
여기서 제네릭을 사용하니 Formula를 사용하는 ExpressionParser도 제네릭을 사용해주어야 해서 설계가 이상해진다 생각했었습니다.

```swift=
struct Formula {
    var operands: CalculatorItemQueue = CalculatorItemQueue<Double>()
    var operators: CalculatorItemQueue = CalculatorItemQueue<Operator>()
```

다시 천천히 설계도를 보니 operands 는 Double, operators 는 Operator 받으면 될 것 같아서 위처럼 해결했습니다.

# 🙇‍♂️ 조언을 얻고 싶은 점

- TDD 개발 순서

![](https://i.imgur.com/ZM8MF9w.png)

>TDD를 활용한 구현은 의존성 관계 그래프의 최말단 타입부터 구현하면 편리합니다.
예) CalculatorItemQueue → Formula → ExpressionParser 순서

최말단은 어디인가요?

TDD를 활용한 구현을 하려고 위의 순서대로 구현을 해봤는데
Queue는 STEP1에서 구현이 끝났고,
Formula의 result()를 구현하는데 ExpressionParser가 Formula를 생성해주기 때문에 테스트를 하려면 ExpressionParser가 먼저 구현이 되어있어야 했었습니다. 😭

또 ExpressionParser를 구현하는 중에는 String.split이 필요했었는데 최말단이 아니라 최상단부터 구현한 것 같은 느낌이 들었습니다.

제 생각에는 ExpressionParser → Formula → CalculatorItemQueue 순서로 구현하는 것이 더 편했던 것 같습니다

2022-09-24 10:24 UTC, jjpush commented
안녕하세요 알라딘! 음수 값들이 들어왔을 때 체크하지 못하는 버그를 발견해서 추가 커밋 넣었습니다.

`adjustMinusNumber() -> [String] 추가` 

테스트 케이스 입니다.
![](https://i.imgur.com/s6VAuvY.png)

2022-09-26 15:26 UTC, junbangg requested changes
TDD의 장점을 느끼셨다니 아주 좋네요👏👏👏👏👏👏
신봉자 되셨으니까 나중에 저도 좀 알려주세요..어렵

어떤 테스트 파일의 메서드명들은 한국어로 되어있고 이번에 추가로 생긴 테스트 메서드명들은 영어로 되어있던데 혼용해서 사용하고 계신 이유가 있으실까요?!

그리고 질문 주신거에 대해서 간단히 이야기하자면

일단
```
TDD를 활용한 구현은 의존성 관계 그래프의 최말단 타입부터 구현하면 편리합니다.
예) CalculatorItemQueue → Formula → ExpressionParser 순서
```
요 내용은 요구사항에 있던거죠???
흠 그러게 말입니다 `최말단` 이 뭔지 모르겠네요 저도 ... 근데 꼭 저렇게 해야될 필요는 없어보이네요!
제이푸시가 느끼기에 `ExpressionParser` 먼저 하는게 좋다고 생각하셨다면 그게 맞는거죠! 꼭 정답이 있는 부분은 아닌것 같습니다.

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        while !result.operands.isEmpty() {
요것도 느낌표이긴한데..사람마다 다르겠지만
`result.operands.isEmpty() == false` 가 더 가독성이 좋다고 생각을 하는 편입니다 개인적으로

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        while !result2.operators.isEmpty() {
`operators` 랑 `operands`의 내용을 비우는 코드가 만약에 자주 생길것 같으면 요것도 메서드로 빼는 방법도 괜찮겠네요!(테스트에서만 쓰는 메서드로) 

테스트 코드 메서드도 어쨋든 메서드라서 너무 많은 내용이 들어가있는것보다 적당히 메서드로 분리 시키는것도 좋다고 생각합니다 개인적으로

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/FormulaTests.swift
> +
불필요한 줄바꿈이 있어보이네요

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/FormulaTests.swift
> +
여기도!

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/FormulaTests.swift
> +
여기도요!

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/OperatorTests.swift
> +
얘네는 혹시 왜 이름에 `_` 가 들어가있나요??

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/OperatorTests.swift
> +        let number_2 = 2.0
위 댓글과 같은 내용!

2022-09-26 15:26 UTC, junbangg commented on Calculator/CalculatorTests/StringExtensionTests.swift
> +    func test_When_testString_split_Then_return_String_that_except_specific_character() {
뒤에 `that_except_specific_character` 부분은 조금 어색해보입니다!
혹시 왜 `except_specific_character` 인가요??

2022-09-27 05:20 UTC, jjpush commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    @discardableResult
네 맞습니다! 노란 경고창을 없애주기위해 사용했습니다 😄

2022-09-27 05:39 UTC, jjpush commented on Calculator/Calculator/Model/Error/CalculatorError.swift
> +    case wrongFormulaError
그렇네요,, 필요하지 않은 부분인 것 같습니다!

2022-09-27 05:42 UTC, jjpush commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operant = operators.dequeue(),
operator가 예약어로 걸려있었기 때문입니다 🥲
그래서 operator와 비슷한 뜻을 가진 단어들을 찾아보다가 operant 에 조작을 하는 사람이라는 뜻이 있어서 사용을 했습니다!

2022-09-27 05:45 UTC, jjpush commented on Calculator/Calculator/Model/Formula.swift
> +                  let number = operands.dequeue() else {
operators -> operator
operands -> operand
원래는 s만 빼서 사용하고 싶었는데 
operator가 다른 단어로 바뀌다보니 operand도 다른 단어로 하고 싶었습니다 ㅎ..

2022-09-27 05:46 UTC, jjpush commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    var sut: CalculatorItemQueue<Double>!
넵! 맞습니다

2022-09-27 05:51 UTC, jjpush commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        var popedElement: [Double?] = []
오타.. 😭 감사합니다! 수정했습니다

2022-09-27 05:53 UTC, jjpush commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    func test_When_generate_parse_Then_expect_Not_nil() {
When과 Then을 대문자로 사용하니 문장이 한눈에 잘 보이는 것 같아서 사용했습니다

2022-09-27 06:11 UTC, jjpush commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        while !result.operands.isEmpty() {
네 저도 동의하는 부분이라 수정했습니다!

2022-09-27 06:12 UTC, jjpush commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +        while !result2.operators.isEmpty() {
아 그렇네요 생각하지 못했습니다..  테스트에서만 쓰는 메서드로 빼주었습니다!

2022-09-27 06:33 UTC, jjpush commented on Calculator/CalculatorTests/FormulaTests.swift
> +
수정했습니다!!

2022-09-27 06:34 UTC, jjpush commented on Calculator/CalculatorTests/FormulaTests.swift
> +
여기도 수정했습니다!!

2022-09-27 06:34 UTC, jjpush commented on Calculator/CalculatorTests/FormulaTests.swift
> +
여기도요!

2022-09-27 06:40 UTC, jjpush commented on Calculator/CalculatorTests/OperatorTests.swift
> +
원래 제 컨벤션은 "변수1" 인데
여기를 작성할때는 number1이 넘버원.. 변수1이 아닌 1을 뜻하는 것 같은 느낌이라 "_1"을 사용했었습니다.
이런 경우가 있으니 원래의 컨벤션을  "_1"로 바꾸는게 좋을까요? 알라딘의 경우에는 어떤 컨벤션을 사용하시나요?
일단 통일 해주기 위해 _를 제거했습니다!

2022-09-27 06:58 UTC, jjpush commented on Calculator/CalculatorTests/StringExtensionTests.swift
> +    func test_When_testString_split_Then_return_String_that_except_specific_character() {
`testString이 주어졌을 때 특정(+, -, *, /) 문자를 제외한 String을 반환한다`
는 문장을 생각했었습니다. 지금 다시 읽어보니 문장이 이상하네요..

`When_given_testString_Then_return_String_that_separated_specific_character` 로 변경했습니다!

2022-09-27 07:33 UTC, jjpush commented
>TDD의 장점을 느끼셨다니 아주 좋네요👏👏👏👏👏👏
신봉자 되셨으니까 나중에 저도 좀 알려주세요..어렵
>
>어떤 테스트 파일의 메서드명들은 한국어로 되어있고 이번에 추가로 생긴 테스트 메서드명들은 영어로 되어있던데 혼용해서 사용하고 계신 이유가 있으실까요?!

캠프 중에 여러가지 많이 경험해보자는 생각에 이번 STEP2의 테스트 메서드는 영어로 짜보고 싶었습니다!
영어로 사용해본 느낌은 When Then 으로 구분해서 사용하니까 눈에도 잘 들어오고 나쁘지 않았던 것 같습니다

>그리고 질문 주신거에 대해서 간단히 이야기하자면
>
>일단
>
>TDD를 활용한 구현은 의존성 관계 그래프의 최말단 타입부터 구현하면 편리합니다.
>예) CalculatorItemQueue → Formula → ExpressionParser 순서
>요 내용은 요구사항에 있던거죠???
>흠 그러게 말입니다 최말단 이 뭔지 모르겠네요 저도 ... 근데 꼭 저렇게 해야될 필요는 없어보이네요!
>제이푸시가 느끼기에 ExpressionParser 먼저 하는게 좋다고 생각하셨다면 그게 맞는거죠! 꼭 정답이 있는 부분은 아닌것 같습니다.

맞는 것 같습니다! 조언 감사합니다 ㅎㅎ

한가지 질문이 더 있는데요
혹시 cmd U를 통해서 전체실행을 하면 시뮬레이터가 main, clone1, clone2, clone3 이렇게 생성이 되는 이유를 알 수 있을까요?
XCTestCase 클래스를 상속한 클래스당 하나가 생성이 되나 싶었는데 테스트 클래스는 5개인데 시뮬레이터는 4개라 그건아닌듯 했습니다..
왜 클론이 생성이 되나요?

2022-09-27 07:35 UTC, jjpush commented on Calculator/CalculatorTests/OperatorTests.swift
> +        let number_2 = 2.0
수정했습니다! ㅎㅎ

2022-09-28 14:20 UTC, junbangg commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operant = operators.dequeue(),
아 그렇겠구나... 음 근데 `operant`는 제가 알기로는 뜻이 좀 많이 다른 단어라서 조금 혼란의 여지를 줄 수 있을것 가트네요!

2022-09-28 14:23 UTC, junbangg commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operant = operators.dequeue(),
아 그렇겠구나... 아예 그럼 `currentOperator` ??
`while` 문 안에 있으니까 나쁘지않을것 같기도 하고..흠
`operant` 는 뜻이 좀 다른쪽의 단어라 혼란의 여지를 줄 수도 있을것 같네요..!

2022-09-28 14:24 UTC, junbangg commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    func test_When_generate_parse_Then_expect_Not_nil() {
하기 나름이긴하지만 `camel` `snake` case 가 혼용되어 사용되고 있는 느낌이라 좀 낯설긴 했었네요 처음 봤을때..!

2022-09-28 14:25 UTC, junbangg commented on Calculator/CalculatorTests/OperatorTests.swift
> +
음 지금 말씀하시 넘버원이라는게
첫번째? 를 의미하는걸까요???

2022-09-28 14:27 UTC, junbangg commented on Calculator/CalculatorTests/StringExtensionTests.swift
> +    func test_When_testString_split_Then_return_String_that_except_specific_character() {
`When_given_testString_Then_return_String_separated_by_specific_character`
도 괜찮을것 같네요..!그리고 중간중간 대문자가 조금 이상해보이긴하네요 보면 볼수록..!`When`, `Then` 은 대문자로 사용하고싶으시다면 `String` 만큼은 소문자를 사용하는게 맞을것 같습니당

2022-09-28 14:34 UTC, junbangg approved these changes

2022-09-28 14:34 UTC, merged

2022-09-28 15:16 UTC, jjpush commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    func test_When_generate_parse_Then_expect_Not_nil() {
아하 그렇네요.. 이렇게 사용하니 camel snake 혼용이되네요 더 고민을 해봐야겠습니다 ㅋㅋㅋ

2022-09-28 15:17 UTC, jjpush commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operant = operators.dequeue(),
‘operator’ 이런식으로 사용하면 예약어라도 사용할 수 있는 것 같아서 스텝3에서 반영해보겠습니다!!

2022-09-28 15:18 UTC, jjpush commented on Calculator/CalculatorTests/OperatorTests.swift
> +
숫자 그 자체로 ‘1’ 을 나타내는 느낌을 받았었습니다

2022-09-28 15:18 UTC, jjpush commented on Calculator/CalculatorTests/StringExtensionTests.swift
> +    func test_When_testString_split_Then_return_String_that_except_specific_character() {
아하 넵! 반영해보도록 하겠습니다!