계산기 [Step 2] Ayaan
yagom-academy/ios-calculator-app pull request #348
Opened 2022-09-24 13:53 UTC by oneStar92

@junbangg

안녕하세요, 알라딘🫡
이번 스텝은 TDD 빼고는 별다른 어려움은 없이 진행된 것 같습니다🤔
TDD를 최대한 적용하려고 노력해서 PR이 많이 늦어졌습니다😭
이번 Step도 잘 부탁드립니다!!🤟
---
# Step 2: 계산 타입 및 주변 타입 구현

## ✏️ TodoList
- [x] UML을 기반으로 한 코드구현
- [x] 숫자와 연산자 입력에 큐 활용
- [x] TDD를 기반으로 코드 작성하기(선택)

## ⭐️ 기능 설명

- `Operator`: `Character`형 원시값을 가지고, `CaseIterable` 및 `CalculateItem` Protocol을 채택한 enum Type입니다.
    - `calculate(lhs: ,rhs:)`: 자기 case에 해당하는 연산을 수행하는 메소드입니다.
- `Formula`: `CalculatorItemQueue` Type의 `operands`와 `operators`를 프로퍼티로 가진 strcut Type입니다.
    - `result()`: 자신이 소유한 `operands`와 `operators`를 이용하여 계산한 결과를 return하는 메소드 입니다.
- `ExpressionParser`: static Type의 `parse(from: )`메소드를 가지고 있는 enum Type입니다.
    - `parse(from: )`: 전달받은 `String` Type을 `componentsByOperators(from: )`메소드를 이용해 연산자와 피연산자로 나눈 후 `Formula` Type에 `enqueue()`한 후 반환하는 역활을 수행합니다.
    - `componentsByOperators(from: )`: 전달받은 `String` Type을 연산자와 피연산자로 나누어 그 값을 return하는 메소드 입니다.
- `Double`: extension을 통해 `CalculateItem` 프로토콜 채택했습니다.
- `String`: extension을 통해 `split()`메소드를 오버로드 했습니다.

## ⭐️ 고민했던 점

- 음수표현
음수 부호를 "-"를 통하여 음수를 처리하게 되면 연산자로 변환되는 오류가 발생하였습니다.
음수 부호는 연산자와 피연산자로 나누는 기능을 수행할때 피연산자 값이 비어있을때만 발생하는 것을 파악하였고 이를 이용하여 음수에 대한 부호 처리를 해결했습니다.

## ⭐️ 고민했던 점

- TDD
TDD를 기반으로 코드를 작성에 많은 어려움을 겪었습니다. **어떤 Test Case통해 검증을 해야 되는지**, **각 단계에서의 코드의 수준 어느정도여야 하는지**, **commit단위는 어떻게 해야되는지**등의 많은 고민을 하였습니다.
검색을 통한 학습 및 캠퍼들과의 대화를 통해서 TDD는 경험의 영역이니 일단 부딪혀보자는 결론을 내렸고 TDD기반으로 손 가는대로 코드를 작성했습니다.
현재 Step 2의 Commit 단위와 제가 작성한 Test Case들에 대한 알라딘의 생각을 듣고싶습니다...

2022-09-27 16:08 UTC, junbangg requested changes
잘봤습니다:) 
테스트 코드를 정말 열심히 작성하셨군요 👏👏👏👏👏👏👏👏👏
테스트 코드 구조도 저번보다 훨씬 개선된것 같은 느낌입니다! 댓글 남긴거 확인부탁드려요~

질문해주신 내용 답변을 드리자면
```TDD를 기반으로 코드를 작성에 많은 어려움을 겪었습니다. 어떤 Test Case통해 검증을 해야 되는지, 각 단계에서의 코드의 수준 어느정도여야 하는지, commit단위는 어떻게 해야되는지등의 많은 고민을 하였습니다.
검색을 통한 학습 및 캠퍼들과의 대화를 통해서 TDD는 경험의 영역이니 일단 부딪혀보자는 결론을 내렸고 TDD기반으로 손 가는대로 코드를 작성했습니다.
현재 Step 2의 Commit 단위와 제가 작성한 Test Case들에 대한 알라딘의 생각을 듣고싶습니다...
```

커밋 단위는 정하기 나름인것 같아요!
의미 있는 기준만 정하신다면 그게 정답이라고 생각합니다 저는.,.!
그리고 테스트를 하는 기준은 여러개일 수도 있을것 같은데..`Test Coverage` 한번 구글링 해보셔도 좋을것 같습니당

저는 개인적으로 테스트 하려는 타입(`sut`) 의 모든 메서드는 전부 테스트를 하려고 노력하는데(물론 TDD는 저도 많이 안해봤지만:) ) 필요에 따라서 테스트 케이스를 다양하게 가져갈 필요가 있겠죠??! 중요한 로직을 담당하고 있는 메서드일수록 그런것 같아요..!
원하신 답변이 이런거였는지는 잘 모르겠군요ㅎㅎ 추가적으로 이야기해볼만한게 있다면 디엠주세요 저번처럼~~~~~

2022-09-27 16:14 UTC, junbangg commented on Calculator/Calculator/Model/ExpressionParser.swift
> +enum ExpressionParser {
요 메서드들은 테스트를 따로 안하고 계신걸까요??(못보고 지나친건가..)

2022-09-28 01:57 UTC, oneStar92 commented on Calculator/Calculator/Model/BasicDataType.swift
> +    func split(with target: Character) -> [String] {
[fc0b908](https://github.com/yagom-academy/ios-calculator-app/pull/348/commits/fc0b908b53966aada020de03880eb7ec24dc5cce) 해당 커밋 보시면 사용하고있습니다...
커밋 시기가 많이 나중이긴 하지만요..ㅋㅋㅋ

2022-09-28 02:00 UTC, oneStar92 commented on Calculator/Calculator/Model/BasicDataType.swift
> +        if !temporaryString.isEmpty {
저는 `!`키워드를 많이 사용하는데 생각해보니 우연히 읽고 넘어가게되면 `!`키워드를 보지 못하는 경우도 있을 것 같네요.
고민해 보겠습니다!

2022-09-28 02:07 UTC, oneStar92 commented on Calculator/Calculator/Model/Operator.swift
> +extension Operator: CalculateItem {}
제가 Type 선언부에 어떤 프로토콜 채택 쓰는걸 안좋아해서...
별다른 의미는 없습니다ㅋㅋㅋ
`extenstion`으로 프로토콜을 채택한 후 해당 프로토콜 기능 구현을 하게되면 프로토콜을 채택해서 구현한 기능이 무엇인지 보기 좋아서 저렇게 `extension`키워드를 사용했습니다. 질문해 주신 부분은 굳이 저렇게 빼지 않는게 오히려 더 가독성이 좋아 보이네요...

2022-09-28 02:56 UTC, oneStar92 commented on Calculator/Calculator/Model/BasicDataType.swift
> +    func split(with target: Character) -> [String] {
여러 경우의 테스트 케이스를 추가했습니다!

2022-09-28 02:57 UTC, oneStar92 commented on Calculator/BasicDataTypeTests/BasicDataTypeTests.swift
> +    func testDouble_주어진_실수2를_CalculateItem_Type으로_Type_Checking한_경우_그_결과는_참입니다() {
수정했습니다!ㅋㅋㅋ

2022-09-28 03:24 UTC, oneStar92 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        for _ in 1...input.count {
```swift
var result: Int?
while !sut.isEmpty {
      result = sut.dequeue()
}
```
로 수정하였습니다.

2022-09-28 03:25 UTC, oneStar92 commented on Calculator/FormulaTests/FormulaTests.swift
> +    func testFormula_Fornula_Type을_인스턴스화한_경우_그_값은_Nil이_아닙니다() {
삭제했습니다 ㅠㅠ

2022-09-28 06:29 UTC, oneStar92 commented on Calculator/OperatorTests/OperatorTests.swift
> +        XCTAssertNotNil(sut)
[6197b5a](https://github.com/yagom-academy/ios-calculator-app/pull/348/commits/6197b5afddae57a46e3bfc1912a10c6747cdb2ef) 삭제했습니다...

2022-09-28 06:30 UTC, oneStar92 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +enum ExpressionParser {
[39a1223](https://github.com/yagom-academy/ios-calculator-app/pull/348/commits/39a12237d6fd5511248ffd75faff168e49e29a61) 작성한 줄 알고 넘어갔네요 ㅠㅠ TDD로 구현을 하다가 너무 지쳐서 한개정도는 하고 안했는데... Unit Test도 안하다니 ㅠㅠ Test Case 추가했습니다!

2022-09-28 06:31 UTC, oneStar92 commented on Calculator/FormulaTests/FormulaTests.swift
> +            return
[7aee7cc](https://github.com/yagom-academy/ios-calculator-app/pull/348/commits/7aee7cc52d43e6d260711bb17708809c239c88f1) 수정했습니다.

2022-09-28 06:32 UTC, oneStar92 commented on Calculator/FormulaTests/FormulaTests.swift
> +            return
[7aee7cc](https://github.com/yagom-academy/ios-calculator-app/pull/348/commits/7aee7cc52d43e6d260711bb17708809c239c88f1) 수정했습니다!

2022-09-28 06:32 UTC, oneStar92 commented on Calculator/FormulaTests/FormulaTests.swift
> +            return
[7aee7cc](https://github.com/yagom-academy/ios-calculator-app/pull/348/commits/7aee7cc52d43e6d260711bb17708809c239c88f1) 수정했습니다!

2022-09-29 12:44 UTC, junbangg commented on Calculator/Calculator/Model/Operator.swift
> +extension Operator: CalculateItem {}
요건 편하신대로 해주시면 될것 같습니다~~정답은 없는거니까:)

2022-09-29 12:57 UTC, junbangg commented on Calculator/BasicDataTypeTests/BasicDataTypeTests.swift
> +    func testString_주어진_String_Type_1더하기2더하기3을_오버로딩한_split메소드를_사용해_더하기를_기준으로_나눈_경우_그_결과는_1_더하기_2_더하기_3이_담긴_StringArray와_같다() {
테스트 메서드명은 저도 항상 고민을 많이 하는 부분인데...
지금의 네이밍 방향(?)이라면 메서드의 모든 내용을 처음부터 끝까지 메서드명에 담으려고 하시는것 같네요..!
조금 더 간단하게 
`given when then`
형태로만 나누고 디테일한 부분들은 좀 생략해도 작성하신 코드의 가독성으로도 충분할것 같아요!👍
이건 워낙 여기저기 다르게 하고 있는 부분이기도 하고 괜히 언급을 했다가 아얀의 창의성(?)을 가두게 될까봐 이야기를 안했던 부분인데
추후에라도 ? 조금 더 간단하면서 직관적인(정말 어려운 일이지만) 메서드명을 작성하는걸 고민해보셔도 좋을것 같네용

예를 들어
`given_equationString_when_split_expect_correctStringArray` 
대충 요런느낌으로 어떤 메서드겠구나? 라는것만 확인시켜주는 느낌??으로 해도 충분할것 같아요
(이게 절대 정답은 아닙니당)

2022-09-29 12:58 UTC, merged

2022-09-29 22:49 UTC, oneStar92 commented on Calculator/BasicDataTypeTests/BasicDataTypeTests.swift
> +    func testString_주어진_String_Type_1더하기2더하기3을_오버로딩한_split메소드를_사용해_더하기를_기준으로_나눈_경우_그_결과는_1_더하기_2_더하기_3이_담긴_StringArray와_같다() {
뭔가 저는 명확하게 보이는게 좋다고 생각해서 저렇게 접근을 했는데... 음... 좋은 의견 감사합니다!