계산기 [STEP 2] SummerCat
yagom-academy/ios-calculator-app pull request #349
Opened 2022-09-25 11:21 UTC by ttokin

@havilog 안녕하세요 하비! 계산기 스텝2 리뷰 요청드립니다 🙇🏻‍♀️🙇🏻‍♀️
제 머릿속에서 생각나는 예외 사항들을 최대한 테스트에 담아서 테스트 -> 실패 -> 리팩토링 순서로 진행해보려고 노력했습니다.
저번처럼 따끔한 리뷰 부탁드립니다 🥰 항상 감사해요!

# 계산기 [STEP 2] SummerCat

## UML
<img src="https://i.imgur.com/kGyXaei.png">

---

## 고민한 부분
1. `componentsByOperator(from: )` 메서드의 역할
연산자로 이루어진 배열을 반환하는 메서드인지, 연산자로 구분한 숫자들을 반환하는 메서드인지 역할이 헷갈렸습니다. 후자에 더 가깝다고 생각해서 매개변수로 주어진 문자열을 연산자로 구분해서 문자열 배열로 반환해주는 내용으로 구현하였습니다(`"1+2+3" -> ["1", "2", "3"]`). 처음에는 음수로 된 숫자가 들어오는 경우를 고려하지 않고 작성했다가, 음수로 된 숫자도 정상적으로 처리할 수 있도록 수정했습니다.

2. 예외 처리
제가 생각한 예외 상황은 `1. 0으로 나누었을 때`, `2. 음수 입력값을 받는 경우`, `3. 연산자가 두 개 연달아 입력되었을 경우`, `4. 입력값의 맨 첫번째 값이 연산자인 경우`, `5. 입력값의 맨 마지막 값이 연산자일 경우` 입니다. 이 중 1 ~ 4번은 처리했으나, 5번의 경우 처리하지 못했습니다.
    - `1. 0으로 나누었을 때`: 처음에는 divisor가 0인 경우 `divisorIsZero`라는 오류를 정의해주고 해당 오류를 반환하도록 했었으나, 과제 요구사항을 다시 읽어본 후 `.nan`을 반환하는 것으로 변경해 처리했습니다.
    - `2. 음수 입력값을 받는 경우`: 수식을 입력할 때, 연산기호를 누르면 연산기호 앞뒤로 공백을 같이 입력하는 것으로 가정하고 공백을 기준으로 각 입력값을 구분한 후 연산자를 제거해주어 연산자 `-`와 음수에 붙는 기호 `-`가 모두 연산자로 처리되지 않도록 했습니다.
    - `3. 연산자가 두 개 연달아 입력되었을 경우`: 아이폰 기본 계산기 앱의 경우 "3*/3"과 같이 연산자 두 개가 연속으로 올 경우, 앞의 연산자를 무시하고 뒤의 연산자만 적용해서 계산을 처리합니다. 이 규칙을 적용해서 `lastElement` 변수에 바로 직전의 요소를 저장해두고, **"이전의 요소는 연산자, 현재의 요소는 숫자"** 인 경우에만 연산자 큐에 연산자를 추가합니다.
    - `4. 입력값의 맨 첫번째 값이 연산자인 경우`: 연산자 큐와 피연산자 큐가 별도로 분리되어 있기 때문에 둘의 순서가 뒤섞이지 않도록 하기 위해서는 입력값의 맨 첫번째 값이 연산자인 경우, 임의로 피연산자 큐의 맨 앞에 0을 추가하도록 처리했습니다.

---

## 해결하지 못한 부분

1. 예외 처리
`5. 입력값의 맨 마지막 값이 연산자일 경우`: 입력된 수식을 오류로 분류하고 연산값을 반환하지 않을지, 맨 마지막 연산자 다음에 임의의 수를 넣어서 처리해야 할 지 고민이 되었습니다(아이폰 기본 계산기 앱의 경우에는 맨 마지막 연산자 다음에 자동으로 넣어주는 임의의 수가 +,- 연산일 경우와 *,/ 연산일 경우가 각각 다름). 만약 오류로 처리해서 핸들링 하게 되면 `ExpressionParser`의 `parse`에서 처리할 것 같습니다.

2. 메서드의 역할 분리
과제 요구사항을 UML에 제시된 내용에서 최대한 벗어나지 않는 것으로 이해해서 `parse` 메서드 같은 경우 한 메서드가 하는 역할이 너무 많은 것으로 보입니다. 역할 분리를 하도록 리팩토링 하면 좋을 것 같습니다.

2022-09-26 01:25 UTC, havilog requested changes
> 예외 처리
> 5. 입력값의 맨 마지막 값이 연산자일 경우: 입력된 수식을 오류로 분류하고 연산값을 반환하지 않을지, 맨 마지막 연산자 다음에 임의의 수를 넣어서 처리해야 할 지 고민이 되었습니다(아이폰 기본 계산기 앱의 경우에는 맨 마지막 연산자 다음에 자동으로 넣어주는 임의의 수가 +,- 연산일 경우와 *,/ 연산일 경우가 각각 다름). 만약 오류로 처리해서 핸들링 하게 되면 ExpressionParser의 parse에서 처리할 것 같습니다.

요거는 제가 코멘트 해드릴만한 건 없을거 같고 더 고민해보시면 될 같구,,

> 메서드의 역할 분리
> 과제 요구사항을 UML에 제시된 내용에서 최대한 벗어나지 않는 것으로 이해해서 parse 메서드 같은 경우 한 메서드가 하는 역할이 너무 많은 것으로 보입니다. 역할 분리를 하도록 리팩토링 하면 좋을 것 같습니다.

요거는 코멘트 달아드렸습니다!

스탭2도 고생하셨어요 썸머캣 :)

2022-09-26 01:25 UTC, havilog commented on Calculator/Calculator/Model/Formula.swift
> +    var operators = CalculatorItemQueue<Operator>()
위에 말한대로 이 아이들을 외부에서 주입받으면 여기에 바로 접근할 필요가 없을거 같습니다 ㅎㅎ

2022-09-26 01:25 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
고민하셨던 부분에 대한 내용인거 같은데요,
음.. 사실 저는 input에 공백이 왜 필요한지가 잘 이해가 안되긴 하네요 ..ㅎ

저도 오래 고민해본건 아니라 더 최적화는 가능하겠지만,
요렇게 샘플코드를 짜봤는데 이러면 간단하게 converting할 수 있지 않을까요?
```
let input: String = "1+3-22*5/0"
let separator: String = "+-*/"
let operators: CharacterSet = CharacterSet(charactersIn: separator)
let numbers = input.components(separatedBy: operators)
let operands = input.filter(\.isNotNumber).map(String.init)

print(numbers) // ["1", "3", "22", "5", "0"]
print(operands) // ["+", "-", "*", "/"]

extension String.Element {
    public var isNotNumber: Bool {
        return !self.isNumber
    }
}

```

2022-09-26 01:25 UTC, havilog commented on Calculator/Calculator/Model/Operator.swift
> +    }
혹시 요 부분에서 0으로 나누는 케이스에 대한 처리를 하지 않고, `result()` 함수에서 처리하신 이유가 있을까요?

2022-09-27 03:08 UTC, dev-summer commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
넵넵! 처음에 UML상 기재된 것 외에 프로퍼티/메서드/... 를 추가해도 괜찮은지 잘 모르겠어서 통으로 작성했었는데 조언 주신 대로 나눠서 작성해 보았습니다.

2022-09-27 03:09 UTC, dev-summer commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
꼭 필요하다기 보다는 편한 길을 찾고자..했던거같아요ㅎㅎ
하비가 조언해주신대로 다른 분들 코드도 참고해서 수정했습니다.

2022-09-27 03:16 UTC, dev-summer commented on Calculator/Calculator/Model/Operator.swift
> +    }
여기에 작성할지 전체 수식을 다루는 부분에서 작성할지 고민했었는데, add/subtract/multiply에는 분기조건이 작성되어 있지 않아서 divide에만 작성하면 (보기에) 일관성이 떨어져 보여서 `result()`에 작성했었습니다 (굉장히 쓸데없는 집착이었네요ㅠㅠ).
그런데 하비 이야기를 듣고 다시 생각해보니.. 나누는 기능을 하는 함수 자체에서 분기 조건을 주는 것이 더 적절하다고 판단되어 그렇게 수정했습니다!

2022-09-27 03:39 UTC, ttokin commented
@havilog 안녕하세요 하비 =)

제가 생각했던 예외 상황인 `1. 0으로 나누었을 때`, `2. 음수 입력값을 받는 경우`, `3. 연산자가 두 개 연달아 입력되었을 경우`, `4. 입력값의 맨 첫번째 값이 연산자인 경우`, `5. 입력값의 맨 마지막 값이 연산자일 경우` 중 3~5번의 경우, 아래 프로젝트 예제를 보니 모델에서 처리할 부분이 아니라고 생각되어 해당 예외 상황에 대한 처리부분은 코드에서 제거하였습니다.
완성되서 들어온 수식에서 검증하는 것이 아니라, 수식을 입력받는 과정에서 검증하도록 할 예정입니다.
<img width="300" src="https://i.imgur.com/6XYoEjS.png">

이외에 코멘트 주신 부분 포함하여 전반적으로 수정했습니다. 감사합니다!

2022-09-27 14:44 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
[04eabf0](https://github.com/yagom-academy/ios-calculator-app/pull/349/commits/04eabf01564452e00e3e1670b9289b834539e0fb)
요렇게 커밋 붙여넣기 해서 이 커밋으로 해당 수정사항 알려주시면 리뷰가 더 수월할거 같습니다 ㅎㅎ

2022-09-27 15:02 UTC, havilog requested changes
고생하셨습니다 썸머캣 :)
조금만 더 다듬으면 아주 좋은 코드가 ..!@

2022-09-27 15:02 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
요건 알고리즘이라 리뷰하기 좀 힘들지만 ..ㅎㅎ
봤을 때 음수값을 파싱하는 거 같은데,
궁금한게 계산기에서 음수가 들어갈 수가 있는건가요??
-가 들어오면 빼기로 처리하면 될거같은데 음수에 대한 처리는 혹시 1+(-2*6) 이렇게 괄호도 지원하는 경우를 대비하고자 하심일까요 ..?

2022-09-28 01:55 UTC, ttokin commented on Calculator/Calculator/Model/Extensions/String+.swift
> +    }
제가 [공식문서1](https://developer.apple.com/documentation/swift/string), [공식문서2](https://developer.apple.com/documentation/foundation/strings_and_text)에서 찾아보았을 때에는 String에는 `isNumber`와 같은 기능을 하는 함수를 발견하지 못해서 익스텐션으로 따로 구현해 주었습니다.
Character는 Standard Library에 `isNumber`가 있는데 String에는 없어서요..ㅠㅠ

2022-09-28 02:53 UTC, ttokin commented on Calculator/Calculator/Model/Operator.swift
> +    }
`Formula`에 작성했을 때 처음에는 에러로 처리를 했었다가, 과제 요구사항에 `0으로 나누기에 대해서는 결과값을 NaN으로 표기합니다.`라는 문구가 있어서 `.nan`을 활용하는 방법으로 수정했습니다!
`.nan`을 사용해 본 적이 없어서 사용해 본 것도 있습니다! (사용해보니 `.nan`은 `==`로 비교할수가 없어서 `isNan`으로 `.nan`인지 확인해야 한다는 것도 알 수 있었습니다.)

2022-09-28 04:38 UTC, ttokin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
과제 요구사항에 `⁺⁄₋ 버튼은 현재 입력한 숫자의 부호를 변환합니다.`라고 기재되어 있어서,
`1 - -1`이면
```
   1
- -1
```
이런 식으로 입력이 들어갈 거라고 생각해서 저렇게 음수값을 처리했어요! (괄호는 저 로직으로 처리가 안될 것 같습니다)
아래는 과제 페이지의 실행 예시입니다.
![image](https://user-images.githubusercontent.com/111038381/192688535-22710d3f-7225-4513-8577-16678f64a8ae.png)

2022-09-28 06:29 UTC, ttokin commented on Calculator/Calculator/Model/Formula.swift
> +                  let rhs = operands.dequeue() else { return result }
![image](https://user-images.githubusercontent.com/111038381/192700420-45233e4b-0b87-4ca6-88a3-7b8250b2ac4d.png)
과제 예시 이미지를 보고 연산자가 2개 이상 연달아서 들어오는 경우 등은 `Formula`로 들어오기 전에 처리한다고 생각했어요.
음수를 표현하는 부호의 경우 `operators`로 들어가지 않기 때문에 operands와 operators간의 개수에 영향을 주지 못합니다.
그래서 결론적으로 `Formula`로 들어올 때에는 operator의 개수가 operands보다 1개 적게 들어온다고 생각했고, 수식의 첫 번째 항목(숫자)를 `guard var result = operands.dequeue() else { return 0 }`에서 첫 항으로 받고, 이후에는 `연산자-숫자` 순서로 짝지어서 들어올 수밖에 없다고 생각했어요.

2022-09-28 06:34 UTC, ttokin commented on Calculator/Calculator/Model/Formula.swift
> +        guard var result = operands.dequeue() else { return 0 }
"123"이 들어왔을 때 계산 버튼을 누르면 `result` (="123")을 반환합니다!
`else` 안의 `return 0`가 실행되는 조건은 `operands`(숫자)가 하나도 들어오지 않았을 때여서, 0으로 출력되면 괜찮..지 않을까요?
사실 저도 return 값으로 어떤 것을 return 해야 하는지 고민했는데 더 좋은 방법을 생각해내지 못했어요.

2022-09-28 06:36 UTC, ttokin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
하비가 알려주신대로 더 간결하게 만들어 보았습니다!
[233ced8](https://github.com/yagom-academy/ios-calculator-app/pull/349/commits/233ced8166639892f0f6252cfef5d85fc376a42a)

2022-09-28 06:37 UTC, ttokin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
요기도 줄여봤는데 의도하신 대로 줄였는 지는 잘.. 모르겠어요 🤔 [afb2a34](https://github.com/yagom-academy/ios-calculator-app/pull/349/commits/afb2a34faad88f4163511b9f61cd34294356c2fd)

2022-09-28 10:02 UTC, havilog approved these changes
수고하셨어용 썸머캣

2022-09-28 10:02 UTC, havilog commented on Calculator/Calculator/Model/Formula.swift
> +        guard var result = operands.dequeue() else { return 0 }
음 지금 로직 상에는 0이 나가도 문제가 없을거 같긴 한데요 ㅎㅎ
처음 이 코드를 보는 사람이면 0에 대한 히스토리를 잘 이해하기 힘들 수도 있을거 같아요!
initial value가 나가거나, 에러가 나가거나 해도 될거같다는 생각이 드네요 ㅎㅎ
지금은 괜찮을거 같습니다!

2022-09-28 12:32 UTC, merged