계산기 [STEP 2] bella
yagom-academy/ios-calculator-app pull request #352
Opened 2022-09-26 01:26 UTC by hyhy0429

@protocorn93
안녕하세요 콘!🥳 
[Step 2] p.r 보냅니다!
잘 부탁드립니다! 🙏🏼

### [고민했던 점]
#### extension String 내부 구현
- 입력받고자 하는 타입과 반환 타입이 정해져 있었고, 이를 표현하고자 예시를 생각하며 고민했었습니다. 
예를 들어, "1+3*5+6*4" 와 같은 String이 통으로 들어올 경우에 자기자신을 Character 기준으로 나눠서 String 배열에 담아 ["1","+","3"...] 의 값이 반환되도록 구현해보았습니다.

#### enum Operator
- Operator의 타입에서 CaseIterable 은 들어만 보고 사용해보지 않았는데, [CaseIterable](https://developer.apple.com/documentation/swift/caseiterable)을 보며 이해해보았습니다. 
- `UML에서 + 와 - 는 상대적으로 개방적인 것과 폐쇄적인 것을 의미합니다.`  라고 명시되어 있어 `-`가 지정되어 있는 메서드에는 private을 설정해주었고, calculate 메서드만 접근이 가능하도록 하여 Operator의 rawvalue에 따라 계산이 되도록 구현했습니다.

#### Formula
- 처음에는 Formula 타입내에 있는 두 개의 프로퍼티가 무엇인지 알 수 없었으나, 각각 숫자와 연산자가 담기는 큐임을 알 수 있었습니다. 
- result 메서드 구현 시에, 숫자와 연산자 큐에서 값을 꺼내 계산을 하여 결과값을 반환하도록 구현해보았습니다. 이 과정에서, 각각의 큐에 값이 들어있지 않을 수 있어서 바인딩을 통해 꺼낼 값이 없을 때에는 0을 반환하도록 하였습니다. 
앞서 계산이 만약 이루어졌다면, 숫자와 연산자가 한개이상 남았을경우에 이어서 계산이 이루어지도록 구현해보았습니다.

#### FormulaTest 
- 원래는 TDD를 구현하지 않으려고 하였으나, Formula에서 구현한 코드가 제대로 작동하는지 테스트가 필요했습니다. Xcode 연습장을 활용하는데에 한계를 느끼고 [STEP 2]에서 TDD를 다시 작성해보며 테스트의 중요성과 필요성을 느끼게 되었습니다.
- 테스트 구문을 작성하는데 있어서, 저의 예상 결과값과  result()메서드의 숫자가 뭔가 계속 달라 문제를 찾지 못하다가 숫자가 반대서부터 계산이 되는 점을 발견하게 되었고, 캠퍼의 도움을 받아 enqueueStack에 담아야 할 값을 dequeueStack에 담고 있는 것을 알게 되어 바로 수정하자, 결과값이 제대로 비교되어 테스트가 성공될 수 있었습니다. 🥲

#### ExpressionParser
제일 고민을 많이 했던 부분입니다. 
- **componentsByOperators()**
1️⃣ 첫번째 시도
extension String의 split(_target: Character) 사용하여 target에 Operator의 allcases의 rawValue를 넣으면 split의 기준값인 연산기호에 따라 숫자만 구분될 수 있을 거라고 생각해서 이를 구현하기위해, rawValue를 Character로 감싸보기도하며 고민해보았지만, 쉽지 않아 다른 방법을 많이 고민했습니다. 
2️⃣ 두번째 시도
componentsByOperators에서 받아온 input 파라미터를 map을 이용해 나누면 좋겠다고 생각을 했어서 구현해보았지만, 단순한 한자리의 숫자가 나올 경우에는 잘 담아지지만 두 자리 숫자 혹은 소수점자리숫자가 들어올 경우에는 각각 나누어져 들어가게 됨을 깨닫게 되었습니다. 
`예) "4.0+5/3+50" -> ["4", "." ,"0", "+", "5", "/" ....] `
3️⃣ 세번째 시도 
Operator의 rawValue가 들어간 배열을 만들고, forEach와 contains를 활용하여 스트링을 거쳐 스트링 배열에 담는 방법을 사용하였으며, 원하는 결과인 숫자는 숫자끼리 연산자는 연산자만 배열에 담기게 구현 할 수 있었습니다.
`예) "4.0+5/3+50" -> ["4.0", "+", "5", "/", "3", "+", "50"] `
- **parse**
저는 parse메서드의 결과값은 componentsByOperators의 반환값에서 숫자인 경우는 operands큐에 넣고, 연산자인 경우는 operators큐에 넣고 싶었습니다.  따라서 forEach를 이용하여 조건에 따라 각각의 큐에 넣어주게되었습니다. 
이 과정에서 compactMap도 시도해보았으나, 큐에 담기 위해서는 배열이 아닌 요소 하나씩을 큐에 넣어주어야 한다고 생각해서 compactMap을 사용하지 않게 되었습니다. 

### [해결되지 않은 점 & 조언이 필요한 점]
- ExpressionParser의 componentsByOperators 메서드를 제법 잘 구현했다고 생각했는데, 음수를 표현하는 - 기호와 마이너스 연산자를 가리키는 -를 구별할 방법이 없다고 생각되었고 이에 대해 고민하고 구글링을 해보았으나 방법을 찾지 못했습니다. 🥲

2022-09-27 08:54 UTC, protocorn93 requested changes
와 벨라! 고생하셨어요! 👍 전체적으로 가독성이 좋았어요! 그리고 고민하신 흔적이 보였어요! 👏

오타 수정과 같은 커밋은 interactive rebase를 통해서 쉽게 이전 커밋과 합칠 수 있어요! interactive rebase를 활용하시면 다양한 상황에서 쉽게 커밋 로그를 보다 깔끔하게 유지할 수 있어요. 이건 별도로 한번 학습해보시는 것도 좋아요! 

> 캠퍼의 도움을 받아 enqueueStack에 담아야 할 값을 dequeueStack에 담고 있는 것을 알게 되어 바로 수정하자, 결과값이 제대로 비교되어 테스트가 성공될 수 있었습니다. 🥲

저도 이런 실수 굉장히 많이 하는데, 발견하면 참 허탈하죠 🥲

고민하셨던 ExpressionParser도 적절하게 잘 구현되었는데, 제가 생각한 메서드와 조금은 다른 부분이 있어서 관련해서 코멘트 남겨놓았어요! 벨라가 틀렸다는게 아니고 저와 생각이 달랐다라는 코멘트이기에 확인 부탁드릴게요! 

## [해결되지 않은 점 & 조언이 필요한 점]

> ExpressionParser의 componentsByOperators 메서드를 제법 잘 구현했다고 생각했는데, 음수를 표현하는 - 기호와 마이너스 연산자를 가리키는 -를 구별할 방법이 없다고 생각되었고 이에 대해 고민하고 구글링을 해보았으나 방법을 찾지 못했습니다. 🥲

우리가 `"-" `이 문자열을 사용자의 관점에서 바라보고 있어서 그런 것 같아요. 프로그램의 관점에선 마이너스와 빼기가 모두 `"-"`가 아니어도 연산하는데는 문제가 없을 것 같아요. 사용자에게 보여지는 것은 모두 `"-"`이지만, 내부에서 연산을 할 땐 마이너스는 `"_"`, 빼기는 `"-"`로 구현되어도 문제 없어보여요.

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/Extension.swift
> +        let subStringArray = self.split(separator: target)
`return self.split(separator: target).map { String($0) }`

으로 단순하게 구현할 수 있을 것 같아요

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/ExpressionParser.swift
> +            } else if operators.contains($0) {
`else`만으로는 충분하지 않았나요?!

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/ExpressionParser.swift
> +    private static func componentsByOperators(from input: String) -> [String] {
저는 메서드명만을 보고 operator를 기준으로 operand들을 반환해주는 것이 이 메서드의 역할로 생각했었어요! `"12+3+4"`를 넣으면 `[12, 3, 4]`를 반환하는거지요! 물론 그렇게 되면 `parse` 메서드에서 `input`의 operator를 한 번 더 걸러주긴 해야하지만 말이죠! 

벨라가 시도한 방법도 괜찮은 방법 같아요. 다만 메서드명과는 조금은 이질적이긴하네요!

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/ExpressionParser.swift
> +        var operators = CalculatorItemQueue<Operator>.init()
`init`을 명시하신 이유가 있을까요? `CalculatorItemQueue<Double>()`로도 충분해보여서요

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/Formula.swift
> +        return result
연산 코드가 복잡한 것 같아요. `result`의 최초 값을 `firstNumber`로 두고 `while` 조건을 `operands`가 빌 때까지 반복하도록 해서 구현하면 좀 더 간단하게 작성할 수 있을 것 같아요.

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/Operator.swift
> +        return lhs / rhs
`rhs`가 0인 케이스에 대한 대응도 필요해보여요

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/Operator.swift
> +    func calculate(lhs:Double, rhs:Double) -> Double {
이건 다른 코드들에도 해당하는 코멘트인데요~ 메서드 정의부나 호출부에서 파라미터와 타입 혹은 값 사이에 공백을 하나 추가해주시면 좋을 것 같아요. 
```swift
func calculate(lhs: Double, rhs: Double) -> Double 

Operator.add.calculate(lhs: 3, rhs: 5)
```

이렇게요

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/ExpressionParser.swift
> +enum ExpressionParser {
`enum`으로 구현시 어떤 이점이 있었을까요? 물론 프로젝트 명세이긴하지만, 어떤 이유가 있을지 고민해보셨나 궁금해서요!

2022-09-27 08:54 UTC, protocorn93 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
`forEach`를 적절히 잘 사용하신 것 같아요!

```swift
components.compactMap { Double($0) }.forEach { operands.enqueue(element: $0) }
components.compactMap { Operator(rawValue: Character($0) }.forEach { operators.enqueue(element: $0) }
```

이렇게 구현하시는 분들도 종종 보았는데, 불필요한 반복문이 많아지더라구요

2022-09-27 11:28 UTC, hyhy0429 commented on Calculator/Calculator/Extension.swift
> +        let subStringArray = self.split(separator: target)
자기자신(String)을 target으로 나누고, String으로 변환시켜 배열에 담아 반환하는 것이군요! 🙆🏻‍♀️
제가 이번기회에 필요에 따라 고차함수들을 알아보고 적용하는 과정에 있어서 고민을 했었는데, 콘이 말씀해주신 방법이 훨씬 간결하네요~!
수정해보겠습니다! 🙌🏼

2022-09-27 11:29 UTC, hyhy0429 commented on Calculator/Calculator/ExpressionParser.swift
> +            } else if operators.contains($0) {
포함하는 경우와 아닌 경우 반반으로 나누게 되니, if와 else 로 충분해보입니다! 🙂

2022-09-27 11:32 UTC, hyhy0429 commented on Calculator/Calculator/ExpressionParser.swift
> +    private static func componentsByOperators(from input: String) -> [String] {
맞아요! 

사실 UML에 명시된 메서드명에서 전하고자 하는 의미대로 operands만 반환할 것인지에 대해 굉장히 많이 고민을 했었는데요, 제가 원하는 방향은 componentsByOperators() 에서 연산자와 피연산자로 나누어 구분해주고 그 반환 값을 parse() 메서드에서 사용하길 원하는 마음이 더 컸어서 이렇게 구현하게 되었습니다!

사실 메서드명에서 의도한 바와는 다르게 느껴져, 저도 조금 찝찝하긴 했었습니다! 🥲

2022-09-27 11:38 UTC, hyhy0429 commented on Calculator/Calculator/Formula.swift
> +        return result
아하! 던져주신 조건들로 고민해서 조금 더 간결하게 다시 구현해보겠습니다!

2022-09-27 11:38 UTC, hyhy0429 commented on Calculator/Calculator/Operator.swift
> +        return lhs / rhs
아? 0이 들어올 수도 있겠군요!? 😵

2022-09-27 11:39 UTC, hyhy0429 commented on Calculator/Calculator/Operator.swift
> +    func calculate(lhs:Double, rhs:Double) -> Double {
앗! 넵 신경쓰도록 하겠습니다! 🙏🏼

2022-09-27 11:40 UTC, hyhy0429 commented on Calculator/Calculator/ExpressionParser.swift
> +enum ExpressionParser {
만약 ExpressionParser가 struct로 구현되어 있었다면, 내부 메서드를 사용시에 ExpressionParser의 인스턴스를 생성한 후의 인스턴스의 메서드로 사용이 가능했겠으나, enum으로 구현하면서 타입 프로퍼티로 바로 사용이 가능한 장점이 있다고 알고 있습니다! 🙂

2022-09-27 11:41 UTC, hyhy0429 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
오? 저는 아직 고차함수 초보라 밑에 구현한 예시에 대해서도 생각해보며, 어떤 점이 불필요한 반복문인지에 대해서도 생각해보겠습니다! ✍🏼

2022-09-27 12:04 UTC, hyhy0429 commented on Calculator/Calculator/ExpressionParser.swift
> +        var operators = CalculatorItemQueue<Operator>.init()
아! 사실 둘다 별다른 차이가 없는 것으로 알고 있고, 예전에는 .init을 주로 사용하던 버릇이 있어서 사용하게 된 것 같습니다!
이유가 없이 사용하긴 했는데, 사실 코드 하나하나의 의미와 이유가 있어야하는데 코드 작성시 유의하겠습니다! 🙂

2022-09-27 14:42 UTC, hyhy0429 commented
@protocorn93 
콘! 피드백 내용 반영해서 수정해보았습니다! 🙆🏻‍♀️
그 외에도 남겨주신 `interactive rebase`도 살펴보고 연습해볼게요! 감사합니다🥲 
깃도 코드도 초보인 저에게 더더욱 많은 피드백 부탁드립니다! 🙏🏼

2022-09-28 05:12 UTC, protocorn93 commented on Calculator/Calculator/ExpressionParser.swift
> +    private static func componentsByOperators(from input: String) -> [String] {
네네!! 전 벨라 방식도 좋은 것 같아요! 👍

2022-09-28 05:15 UTC, protocorn93 commented on Calculator/Calculator/ExpressionParser.swift
> +enum ExpressionParser {
`struct`로 구현해도 내부 메서드가 `static`이면 사용 가능한건 동일해요~! 하지만 `enum`은 기본적으로 생성자가 없기 때문에 잘못사용되어 객체를 생성하는 실수를 방지할 수 있어요! 그래서 상수형 값들의 네임스페이스를 정의할 때 `enum`을 많이 사용하곤해요! 

```swift
final class SomeViewController: UIViewController { 

  // MARK: Consts
  
  private enum Metric { 
    static let someViewHeight: CGFloat = 30.0
  }
}
```

2022-09-28 09:36 UTC, hyhy0429 commented on Calculator/Calculator/ExpressionParser.swift
> +enum ExpressionParser {
아하! 💡
`enum`으로 생성시에 뜻하지 않는 초기화를 막을 수 있고 순수하게 namespace 로서만 작동하게 되는 장점이 있군요! ✏️
네임스페이스가 무엇인지에 대해서도 찾아보았는데, `서로 연관되어 있는 것들을 모아놓은 공간` 이라고 하네요! [참고문서](https://stackoverflow.com/questions/39022242/difference-between-static-enum-and-static-struct) 들을 더 찾아보고 읽어보며 TIL에 적어보겠습니다! 
알려주셔서 감사합니다! 🥳

2022-09-28 09:54 UTC, merged