계산기 [STEP 2] 미니
yagom-academy/ios-calculator-app pull request #353
Opened 2022-09-26 02:01 UTC by leegyoungmin

안녕하세요. 하비(@havilog)
주말은 잘보내셨나요?
STEP1 꼼꼼한 피드백 해주셔서 감사합니다. 🙇‍♂️🙇‍♂️🙇‍♂️
STEP2 구현 완료되어서 PR 발송합니다.

## 🤔 고민한점
- 음수에 대한 처리
    - 모든 수에 대해서 연산자를 앞 + 뒤로 빈 문자열을 추가하여 받아서 처리하는 것으로 결정하였다.
    - 로직 상 음수로 들어오는 값에 대한 연산자를 추출하는 문제와 피연산자를 양수로 변경하는 문제가 있었기 때문이다.
    - 음수의 조건은 앞에 빈 문자열이 존재하고, 뒤에 Double 타입으로 변경될 수 있는 양수가 존재하는 경우이다. 하지만, 빈 문자열없이 존재하게 된다면, 2개의 연산자가 연속적으로 나오게 된다.
    - 2개의 연속적인 연산자를 추출하기 위해서는 `앞에 연산자가 2개 존재하고, 뒤에 연산자가 -를 표현해야 한다.`라는 조건으로 음수를 판단하여야 한다. 이에 대한 처리는 굉장히 복잡하기 때문에 빈 문자열을 추가하여서 연산자와 피연산자를 우선적으로 구분하려 하였습니다.

- Formula result 함수 내 처리
    - Formula `result() -> Double?` 함수는 두개의 연산자 큐와 피연산자 큐를 통해서 연산 결과를 도출하는 함수이다.
    - 두개의 큐를 통해서 연산을 수행할 수 있는 데이터에 대해서 수행할 수 있는 로직을 작성하려고 하였다.
    - 하지만, 고민 되었던 점은 초기화를 통해서 받아온 원시 프로퍼티의 값을 dequeue를 통해서 데이터를 지우는 것과 프로퍼티 값을 제거하는 것을 고민하였다.
    - 이에 대해서 프로퍼티의 값을 수정하는 것은 입력 받은 데이터를 잃어버리는 일이라고 생각하여서 함수 내에서 변수를 생성하여서 활용할 수 있도록 하였다.

        ```swift
        private let operands: CalculatorItemQueue<Double>
            private let operators: CalculatorItemQueue<Operator>

            init(operands: [Double] = [], operators: [Operator] = []) {
                self.operands = CalculatorItemQueue(elements: operands)
                self.operators = CalculatorItemQueue(elements: operators)
            }

            ...

            func result() -> Double? {
                var operands = operands, operators = operators
                ...
            }
        }
        ```

## 🥺 조언을 얻고 싶은 부분
- ExpressionParser 로직
    ```swift
    static func parse(from input: String) -> Formula {
        let otherSpecial: CharacterSet = ["^", "!", "@", "#", "$", "%", "&"]
        let removedSpecial = input.components(separatedBy: otherSpecial).joined()
        
        let removedPlain = removedSpecial.filter {
            Double(String($0)) != nil || Operator(rawValue: $0) != nil || $0 == " "
        }
    }
        
    ```
    - ExpressionParser의 로직 사용자의 입력을 받는 부분을 아직 구현하지 않았기 때문에 Edge Case에 다양한 입력 오류가 존재할 수 있는 부분을 추가하였습니다. 이런 부분에 대해서는 추가 구현을 한 후, 수정을 하면 되는 걸까요?

    ```swift
    static private func componenetsByOperators(from input: String) -> [String] {
        let operators = Operator.allCases.map { $0.rawValue }
        var result: String = input
        
        operators.forEach { result = result.split(with: $0).joined() }
        result = result.replacingOccurrences(of: "  ", with: "")
        
        return result.split(separator: " ").map { $0.description }
    }
    ```
    - 빈 문자열을 기준으로 피연산자와 연산자를 구분하였는데, 작성한 로직상 마지막 부분에 "  " 두개의 빈 문자열이 붙어있는 경우에 대해서 직접적으로 지워주는 것에 문제가 발생하는 부분이 있는 지 궁금합니다.
- Formula 로직
    ```swift
    func result() -> Double? {
        ...
        while !operands.isEmpty {
            ...
            
            do {
                calResult = try firstOperator.calculate(lhs: calResult, rhs: rhs)
            } catch {
                return nil
            }
        }
        
        return calResult
    }
    ```
    - result 함수 내에서 나눗셈 연산은 throws 함수를 호출하게 되어서 `do - try - catch` 구문을 사용하였습니다. 아직은 다른 오류가 존재하지 않지만, 추가적인 오류가 다양하게 발생하게 될 경우에는 내부에서 catch 구문으로 처리를 하여 값을 반환하는 부분이 적절한지, `throws` 함수로 선언하여서 외부에서 오류를 처리할 수 있도록 하는 것이 적절한지 궁금합니다.

2022-09-26 14:45 UTC, havilog requested changes
> ExpressionParser의 로직 사용자의 입력을 받는 부분을 아직 구현하지 않았기 때문에 Edge Case에 다양한 입력 오류가 존재할 수 있는 부분을 추가하였습니다. 이런 부분에 대해서는 추가 구현을 한 후, 수정을 하면 되는 걸까요?

남긴 코멘트로 답변이 되었을거 같아요 ㅎㅎ

> 빈 문자열을 기준으로 피연산자와 연산자를 구분하였는데, 작성한 로직상 마지막 부분에 " " 두개의 빈 문자열이 붙어있는 경우에 대해서 직접적으로 지워주는 것에 문제가 발생하는 부분이 있는 지 궁금합니다.

혹시 요구사항중에 음수를 반드시 받아야하고, 문자열에 공백이 들어오는 요구사항이 있었나요?
알고리즘 문제라고 생각한다면, 그 요구사항에 따라 파싱하는 로직이 많이 달라질거 같아요!
만약 개발자가 input을 제어할 수 있는 상황이라면 저라면 공백이 있는게 더 에러가 나올 상황이 많아질 거같다고 생각되네요 ㅎㅎ

> result 함수 내에서 나눗셈 연산은 throws 함수를 호출하게 되어서 do - try - catch 구문을 사용하였습니다. 아직은 다른 오류가 존재하지 않지만, 추가적인 오류가 다양하게 발생하게 될 경우에는 내부에서 catch 구문으로 처리를 하여 값을 반환하는 부분이 적절한지, throws 함수로 선언하여서 외부에서 오류를 처리할 수 있도록 하는 것이 적절한지 궁금합니다.

코멘트에 남겼듯이, 뷰에서 result로 nil을 받았을 때 어떻게 처리할지에 대한 고민을 해보셨을 까요?
result()함수 내부에서 모든 에러를 전부 nil로 하게될 경우 어떤 에러를 어떻게 처리할지에 대한 고민을 해보시면 좋을거 같아요 ㅎㅎ

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let otherSpecial: CharacterSet = ["^", "!", "@", "#", "$", "%", "&"]
이렇게 예외처리를 하면 로마어나 예외처리 되지않은 문자열들이 들어왔을 때 앱이 터지지 않을까요?

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = Operator.allCases.map { $0.rawValue }
저는 `Operator.allCases.map(\.rawValue)` 이런 식으로 keyPath를 쓰면 코드가 짧아져서 좋더라구요 ㅎㅎ

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operands: [Double] = componenetsByOperators(from: removedPlain).compactMap { Double($0) }
저도 오래 고민해본 건 아니고, 더 최적화할 여지는 충분히 많지만,
단순히 문자열 파싱이라면 요런 식으로도 해볼 수 있을 거 같아요!

고차함수랑 isNumber, isLetter, isPunctuation 요런 것들도 활용해볼 수 있다는 것도 알아두시면 좋을거 같습니다 ㅎㅎ

```
import Foundation

let input: String = "1+3-22*5/0"
let separator: String = "+-*/"
let operators: CharacterSet = CharacterSet(charactersIn: separator)
let numbers = input.components(separatedBy: operators)
let operands = input.filter(\.isNotNumber).map(String.init)

print(numbers) // ["1", "3", "22", "5", "0"]
print(operands) // ["+", "-", "*", "/"]

extension String.Element {
    public var isNotNumber: Bool {
        return !self.isNumber
    }
}

```

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/Formula.swift
> +    private let operators: CalculatorItemQueue<Operator>
얘네를 let으로 하고 18번 라인을 var로 지역변수로 잡아주신 이유가 있을까요?

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/Formula.swift
> +    init(operands: [Double] = [], operators: [Operator] = []) {
default로 빈 배열을 넣어주신 이유가 있을까요? ㅎㅎㅎ

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/Formula.swift
> +    func result() -> Double? {
nil이 반환되었을 때 오류처리를 어떻게 할 지 생각해보신 부분이 있으실까요? ㅎㅎ

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/Operator.swift
> +        if rhs == 0 {
guard 와 if를 어떨 때 쓰시나요??

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/OperatorError.swift
> +    case divideZero
수동태도 고려해볼 수 있을거 같아요 ㅎㅎ
devidedByZero와 같이? ㅎㅎ

2022-09-26 14:45 UTC, havilog commented on Calculator/Calculator/Model/Formula.swift
> +        guard var calResult: Double = operands.dequeue() else {
저는 `calResult` 요렇게 약어를 쓰는 것보다는 풀어써주는걸 좋아해요 ㅎㅎ
약어를 쓰면 처음 코드 보는 사람이 이해하기 어려운 측면이 있는거 같아서요!

2022-09-27 04:23 UTC, leegyoungmin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let otherSpecial: CharacterSet = ["^", "!", "@", "#", "$", "%", "&"]
위와 같이 처리를 하는 것은 적절하지 않다고 생각되네요 ㅜㅜ

사용자의 입력으로 다양한 값이 들어 올 가능성을 배제하고 구현을 하는 것은 적절하지 않다고 생각하여서 추가하게 되었습니다.
하지만, 사용자의 입력을 외부에서 조절 할 수 있는 것에 대해서 고민하지 못한 것 같습니다.
위와 같은 예외처리는 외부에서 조절할 수 있도록 구현하였습니다.

2022-09-27 04:23 UTC, leegyoungmin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = Operator.allCases.map { $0.rawValue }
이부분은 몰랐던 부분인데 더욱 간결한 코드가 된 것 같습니다.

2022-09-27 04:40 UTC, leegyoungmin commented on Calculator/Calculator/Model/Formula.swift
> +    private let operators: CalculatorItemQueue<Operator>
직접적으로 계산을 수행하게 된다면, 로직 상의 오류나 다양한 외부적인 요인으로 인해서 계산이 중단이 될 수도 있다고 생각했습니다.
그렇기 때문에 직접적으로 선언해준 데이터에 대해서는 값을 직접적으로 지우지 않고 계산을 하기 위해서 18번 라인에서 값을 복사하여서 사용하였습니다.

2022-09-27 04:46 UTC, leegyoungmin commented on Calculator/Calculator/Model/Formula.swift
> +    init(operands: [Double] = [], operators: [Operator] = []) {
처음에는 빈 배열을 통해서 비어있는 Formula를 생성하는 경우가 있을 것이라고 생각하였습니다.
하지만, 외부에서 오류로 생각하여서 생성을 막을 수 있다고 생각하여서 수정하였습니다.

2022-09-27 04:50 UTC, leegyoungmin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operands: [Double] = componenetsByOperators(from: removedPlain).compactMap { Double($0) }
다양한 방법들을 시도해보았습니다.
이들 중 가장 좋은 방법이라고 생각한 것은 flatMap을 활용하여서 마이너스의 개수를 파악하고, 이 부호는 뒤의 숫자에 존재하는 것을 정의하여서 숫자를 생성하도록 하였고,  Operator 중 어떤 것과 - 부호가 붙어있는 경우를 연산자의 Charactor타입으로 반환하는 방법으로 구현하였습니다.

2022-09-27 05:03 UTC, leegyoungmin commented on Calculator/Calculator/Model/Formula.swift
> +    func result() -> Double? {
nil을 반환하는 경우는 어떤 에러가 발생하였다는 것을 정확히 알 수 없어 외부에서 에러를 판단할 수 없다고 생각하였습니다.
Result 타입 반환을 통해서 통합적인 에러를 발생시킬 수 있도록 하였습니다.

Result 타입을 사용한 이유는 내부에서 발생하는 에러는 모두 연산식이 잘못된 경우라고 생각하였습니다. 그렇기 때문에 통합적으로 연산식이 잘못된 오류를 반환할 수 있도록 하고 이에 대한 세부적인 사항을 구현 할 수 있다고 생각했습니다.

2022-09-27 05:07 UTC, leegyoungmin commented on Calculator/Calculator/Model/Formula.swift
> +        guard var calResult: Double = operands.dequeue() else {
`cal`라는 약어는 지양할 수 있도록 calculatedValue 라는 이름으로 변경하였습니다.

2022-09-27 05:09 UTC, leegyoungmin commented on Calculator/Calculator/Model/OperatorError.swift
> +    case divideZero
더 의미가 명확한 이름이라고 생각하여서 변경하였습니다.

2022-09-27 05:12 UTC, leegyoungmin commented on Calculator/Calculator/Model/Operator.swift
> +        if rhs == 0 {
저는 guard 구문을 여러가지의 에러를 처리해야 할 경우, Early Exit를 하기 위해서 사용합니다. 위와 같은 경우는 여러개의 에러가 아닌 한가지의 에러만 구현해야 하는 상황이기 때문에 if를 사용하였습니다. 
조건이 여러가지가 필요한 경우에도 guard 구문을 사용하는데, 위와 같은 경우는 한가지의 조건을 통해서 에러를 처리할 수 있는 경우이기 때문에 guard 구문이 아닌 if 구문을 활용하였습니다.

2022-09-27 14:28 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let otherSpecial: CharacterSet = ["^", "!", "@", "#", "$", "%", "&"]
요런 수정사항 있으실 때, 커밋 링크 주시고 
asdf1234 커밋으로 수정했다고 알려주시면 리뷰에 더 도움이 될거 같아요!

2022-09-27 14:41 UTC, havilog approved these changes
수고하셨습니다 미니 ㅎㅎ

2022-09-27 14:41 UTC, havilog commented on Calculator/Calculator/Model/Formula.swift
> +            }
`result()` 함수 자체가 throw 할 수도 있고, 이 부분에서 Result로 만들어서 넘겨주는 방법도 있을텐데요 ㅎㅎ
요 둘 중에 Result로 만들어서 넘겨줘야겠다고 생각하신 이유가 궁금하네요!

2022-09-27 14:41 UTC, havilog commented on Calculator/Calculator/Model/Operator.swift
> +        if rhs == 0 {
오 이 부분은 제 생각이랑은 조금 다른데요 ..!
물론 코드에 정답은 없고 제 생각이 정답도 아니지만,
보통 guard같은 경우는 다음 line으로 넘어가지 않도록 보장할 때? 주로 사용하는 것 같아요 ㅎㅎ
만약 남자만 군대 갈 경우
```
guard isMan else { return }
goArmy()
```
요렇게 짤 수 있겠죠?

반면 if일 경우 어떤 조건에서 함수를 수행하거나 둘 이상의 경우에서 선택할 때 사용할 수 있을 거 같아요 ㅎㅎ

```
if man {
 // 남자 화장실로
} else if woman {
 // 여자 화장실로 
}
```

요런 식으로요!

2022-09-27 14:41 UTC, havilog commented on Calculator/Calculator/Extensions/String+.swift
> +}
요거는 swift에서 first party로 지원해 줄텐데 double에 대한 처리를 위해서 만드신걸까요?

2022-09-27 14:41 UTC, havilog commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return input.filter { !$0.isNumber }.map { $0 }
`.map { $0 }`은 아무 역할도 안하고 있는거 같네요 ㅎㅎ

2022-09-27 16:01 UTC, leegyoungmin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let otherSpecial: CharacterSet = ["^", "!", "@", "#", "$", "%", "&"]
아 죄송합니다.
미처 생각하지 못했네요. 다음부터는 커밋 확인해서 같이 링크 걸 수 있도록 하겠습니당🙇‍♂️

2022-09-27 16:15 UTC, leegyoungmin commented on Calculator/Calculator/Model/Formula.swift
> +            }
Result 타입을 활용한 이유는 하나의 에러 타입으로 반환할 수 있도록 하는 의도였습니다.
다시 생각해보니, 여러가지의 오류 처리 방법을 활용하게 되면, 코드의 일관성을 헤칠 수도 있다고 생각하였습니다.
또한, 하나의 오류 타입만을 활용하기 때문에 오류를 명확하게 하지 않아도 된다고 생각하였습니다.

위와 같은 생각으로 코드를 일관성 있도록 throw를 할 수 있도록 수정하였습니다. 1d920c1e006644c80aebba08c203439c9e386ff4

2022-09-27 16:17 UTC, leegyoungmin commented on Calculator/Calculator/Extensions/String+.swift
> +}
Xcode 오류가 나서 없는 것으로 확인해서 생성한 것 같습니다 ㅜㅜ
삭제하였습니다.

2022-09-27 16:18 UTC, leegyoungmin commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return input.filter { !$0.isNumber }.map { $0 }
이전에 사용하던 코드를 미처 지우지 못한 것 같습니다.
삭제 수정하였습니다.

2022-09-27 16:27 UTC, leegyoungmin commented on Calculator/Calculator/Model/Operator.swift
> +        if rhs == 0 {
음 하비 말처럼 early Exit를 하는 상황에서는 더욱 가독성이 좋은 코드를 작성할 수 있겠네요.
근데, 위와 같은 코드에서는 `guard rhs != 0` 이라는 구문을 활용하는 것이 좋은지 잘 모르겠습니다.
조금 더 프로젝트를 수행하면서 명확하게 알 수 있도록 공부해보겠습니다.

2022-09-28 03:00 UTC, merged