계산기 [STEP 2] zhilly
yagom-academy/ios-calculator-app pull request #356
Opened 2022-09-27 04:54 UTC by zhilly11

안녕하세요 알라딘! @junbangg
STEP-2를 드디어 끝내게 되어 PR 보냅니다
잘부탁드립니다🙇🏻

## UML
![](https://i.imgur.com/8CDh04z.jpg)

<br>

## 🤔 고민했던점

### CalculatorItemQueue 내부 구현 array -> linked list
구현을 바꾼 이유
1. queue는 pop연산시 빈번한 데이터의 이동이 일어납니다.
2. queue 같은 경우 맨 앞의 원소를 제거해야 하기 때문에 array를 사용해서 구현하면 O(n)의 복잡도가 소요됩니다. 왜냐하면 제거하고 뒤의 요소들을 재배치 해줘야 하기 때문이죠. 1번과 비슷한 이유입니다.
3. Linked List는  삽입/삭제에 O(1)이 소요됩니다. 즉 제거된 뒤의 요소 재배치 필요하지 않습니다.

따라서 Linked List 선택했습니다! (+ swift로 구현해보고 싶은 이유도,,)

### ExpressionParser와 split의 역할
`split()` : target(문자)를 기준으로 구분해서 [String]타입으로 반환해주는 함수 (ex: target이 `+`면 `1+2+3` -> `["1", "2", "3"]`)
`parse()` : input문자열을 Formula타입으로 가공해서 반환해주는 함수
`componentsByOperators` : input문자열을 `Operators`를 기준으로 구분해서 반환해주는 함수

제가 UML을 보고 이해한 내용은 이정도 인데요. 구현을 하면서 `split()`의 이유가 뭔지 궁금했습니다. target은 character타입 하나인데 이걸로는 간단한 문자열 분리밖에 못할것 같다는 생각이 들기도 했구요. 사실상 제대로 된 분리는 `ExpressionParser`파일에서 대부분 이루어지구요. 물론 STEP-3에서 사용을 할 수도 있겠지만..

그래서 일단은 UML을 기준잡고 착실하게 구현만 해놓았습니다.

### Unit Test 단위
소스파일들이 많아지니 어떻게 테스트를 해야할지 고민이 들었습니다. 하나의 test파일에서 작성하게 되면 각각의 변수들 앞에 sut를 붙여 여러개 작성해야하나라는 생각도 했습니다. 결국엔 테스트가 필요하다고 생각되는 소스파일 하나당 test파일 하나씩 생성하여 각각의 test case들을 작성하면서 case들을 통과할 수 있도록 작성했습니다.

<br>

## ✏️ 조언을 얻고 싶은 부분
### Extension파일들의 네이밍
현재는 `Extension`폴더를 따로 만들어줘서 그안에 `ExtensionString`, `ExtensionDouble`이라는 네이밍으로 작성해뒀는데, 보통은 어떤 네이밍으로 파일의 이름을 작성하는지 궁금합니다!

### Linked List
현재 구현한 Linked List는 단방향입니다. queue의 기능만 수행하면 될 것이라고 생각해서 중간에 삽입하는 함수나 이전 노드를 가리키는 값들은 작성하지 않았습니다. 알라딘이 보시기엔 구현이 잘 되어있는지, 고칠점은 없는지, 추가할 점은 없는지! 궁금합니다 :)

### 고차함수
STEP-2중 고차함수들을 써봤습니다. 공식문서만 보고 작성하기엔 예제나 정의된 메서서드들만 보고 하기엔 어려움이 많이 있었습니다.... 알라딘은 고차함수를 학습하실때 어떻게 하셨는지 궁금합니다!!

### UML
예를들어 UML에 `split(with target: Character)-> [String]` 라고 기재되어 있다면 정확하게 구현을 하는게 올바른 것인가요?
만약에 `split`함수안에 인자가 `Characret`보다는 `CharacterSet`이 알맞다고 생각이 들어도 UML대로 구현을 하는게 맞는지 궁금해서 여쭤봅니다. 제 생각에는 UML대로 구현을 하는게 맞다고는 생각이 드나 언제나 정답은 없으니까요.. 알라딘 의견이 궁금합니다!

2022-09-28 15:07 UTC, junbangg requested changes
수고하셨습니다!!
테스트 코드를 아주 열심히 작성해주신것 같네요👍👍👍👍👏👏👏👏👏👍👍

댓글 참고해주세요

그리고 질문 주신 내용은
```
Extension파일들의 네이밍
현재는 Extension폴더를 따로 만들어줘서 그안에 ExtensionString, ExtensionDouble이라는 네이밍으로 작성해뒀는데, 보통은 어떤 네이밍으로 파일의 이름을 작성하는지 궁금합니다!
```
> 정답은 없지만.. 보통 `____+Extensions` 으로 하는것 같아요! 
```
Linked List
현재 구현한 Linked List는 단방향입니다. queue의 기능만 수행하면 될 것이라고 생각해서 중간에 삽입하는 함수나 이전 노드를 가리키는 값들은 작성하지 않았습니다. 알라딘이 보시기엔 구현이 잘 되어있는지, 고칠점은 없는지, 추가할 점은 없는지! 궁금합니다 :)
```
> 댓글 참고해주세용

```
고차함수
STEP-2중 고차함수들을 써봤습니다. 공식문서만 보고 작성하기엔 예제나 정의된 메서서드들만 보고 하기엔 어려움이 많이 있었습니다.... 알라딘은 고차함수를 학습하실때 어떻게 하셨는지 궁금합니다!!
```
> 최대한 공식 문서 참고했었고..음.. 처음부터 막 축약으로 하지않고 최대한 풀어서 사용하면서 이해하려고 노력했던것 같습니당 
```
UML
예를들어 UML에 split(with target: Character)-> [String] 라고 기재되어 있다면 정확하게 구현을 하는게 올바른 것인가요?
만약에 split함수안에 인자가 Characret보다는 CharacterSet이 알맞다고 생각이 들어도 UML대로 구현을 하는게 맞는지 궁금해서 여쭤봅니다. 제 생각에는 UML대로 구현을 하는게 맞다고는 생각이 드나 언제나 정답은 없으니까요.. 알라딘 의견이 궁금합니다!
```
> 음 UML은 어디까지나 개발을 돕기 위한, 이해를 돕기위한 툴?이긴 한것 같아서..실제 코드가 더 중요한것 같긴합니다 저는..! 궁금해하셨던게 이게 아닌것 같은 느낌이 드네요 근데...ㅎ

2022-09-28 15:07 UTC, junbangg commented on Calculator/CalculatorTests/StringSplitTests.swift
> +        XCTAssertEqual(result, ["1","1"])
배열 원소 사이에 띄어쓰기 해줘도 될것 같습니당

2022-09-28 15:07 UTC, junbangg commented on Calculator/CalculatorTests/StringSplitTests.swift
> +        XCTAssertEqual(result, ["1","2","3"])
배열 사이에 띄어쓰기가 필요해보입니다 여기도

2022-09-28 15:07 UTC, junbangg commented on Calculator/CalculatorTests/StringSplitTests.swift
> +        XCTAssertEqual(result, ["4","5"])
여기도!

2022-09-29 04:28 UTC, zhilly11 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +            tail = newNode
이렇게 작성한 이유는 현재 tail의 next를 newNode로 잡아주고 tail을 newNode로 지정 해준다고 생각했습니다.
![image](https://user-images.githubusercontent.com/99257965/192938983-86d7324f-70e0-49de-8c7d-197a6aaddd42.png)
혹시 잘못된 부분일까요?

2022-09-29 04:30 UTC, zhilly11 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> T? {
queue가 비어있다면 nil을 반환해주고
그렇지 않다면 head의 데이터를 반환 및 head의 위치를 head.next로 바꿔주는 역할이라고 생각합니다!

2022-09-29 04:45 UTC, zhilly11 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var count = 0
`head`와 `tail`을 `private(set)` 해준 이유는 unit test에서 데이터가 잘 들어가는지 test를 위해 사용했습니다.
생각해 보니 queue의 기능 중엔 굳이 `set`이 필요하지 않다고 생각하여 관련된 코드 삭제했습니다!
`count`의 경우는 필요하다고 생각되어 그대로 놔뒀습니다.

2022-09-29 04:55 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
>      func test_queue를_Double타입으로_빈queue생성할때_Error가안나고_isEmpty가true인지(){
> 중간중간 대문자는 혹시 왜 쓰신건가요!!?
타입이라고 생각해서 대문자로 작성했습니다.
test 메서드 네임에는 대문자를 작성하는 것을 지양해야 할까요?

>`_` 를 사용하신 기준도 궁금합니당
기준 없이 조금 더 읽기 쉬울 수 있도록 작성했던 것 같습니다.....
지금 생각해 보니 기준 없어 보이는 것이 보기 안 좋다고 생각이 드네요,, :(
추후에 컨벤션을 정해서 작성 수정해 보 도록하겠습니다!

2022-09-29 04:59 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func test_queue에_3_6_9를enqueue했을때_isEmpty가False인지() {
unit test를 작성할 때 최대한 많은 test case 들을 작성하면 좋다고 배워서 작성했던 것 같습니다!

2022-09-29 05:01 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
>          for _ in 1...sut.count + 1 {
보통 배열을 for문 으로 가져올 때 저렇게 사용하곤 했습니다.
알라딘의 질문 의도가 궁금합니다..!

2022-09-29 10:19 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
>          for _ in 1...sut.count + 1 {
아하! 저는 왜 range가 1 로 시작하는지가 궁금했습니다ㅎㅎ
보통은 `0` 부터 시작하긴 해요! (다른 숫자 부터 시작해야되는 특별한 이유가 없다면)

2022-09-29 10:22 UTC, merged

2022-09-29 10:43 UTC, zhilly11 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +            tail = newNode
아! 그런 말씀이셨군요! 코드가 짧게밖에 안 보여서 이해하지 못했었습니다!

2022-09-29 10:46 UTC, zhilly11 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
>          for _ in 1...sut.count + 1 {
밑에 for문을 말씀하신 거였군요..!
저도 평소엔 0부터 시작하도록 쓰는 편인데 여기는 왜 이렇게 써있었을 까요 ㅎㅎㅎㅎㅎ,,
수정해보겠습니다~ 👍