계산기 [STEP 2] LJ
yagom-academy/ios-calculator-app pull request #357
Opened 2022-09-27 06:30 UTC by lj-7-77

# 계산기 STEP-2 PR
안녕하세요 라자냐(@wonhee009) 엘제이(@lj-7-77)입니다.
STEP 2 잘 부탁드립니다.

---
[STEP 2]
## 고민한 점
### 1. 0으로 나누기 하는경우, 반환값이 있는 메서드에서의 에러처리
반환값이 있는 메서드에서의 에러처리는 에러를 던질 때 반환할 값이 없기때문에 에러가 났습니다.
> 에러메세지 : Variable 'result' used before being initialized

반환값이 없는 함수까지 에러를 던지는 방법으로 해결하였습니다.

### 2. 에러로 받아온 후, 이 에러가 난걸 어떻게 확인할 지
XCT함수를 활용하였습니다.XCFail과 XCTAssertThrowsError를 찾아보고 XCTAssertThrowsError에서 받아온 에러의 원인이 제가 예상한 에러와 맞는지 확인하였습니다.

### 3. 0으로 나누면 결과값은 inf값, 에러처리 보다 더 간단한 방법이 없을지 
inf는 Double타입에서 지원하는 무한대라는 값이었기 때문에 반환값에 넣어도 문제가 없었습니다.
반환값에 넣고 테스트파일에서 받은 후 isInfinity가 true일 때 NaN을 출력하는 것으로 해결하였습니다.

---
## 해결하지 못한 점
- Formula result메서드에서 더이상 숫자가 없을 때까지 연산을 해야하는 부분을 reduce 고차함수로 구현하려고 시도했으나 해결하지 못했습니다. reduce의 매개변수와 실행코드를 클로저에 넣어야하는데 어떻게 바꿔주어야하는지를 모르겠습니다.
-  Formula result메서드에서 계산해야 할 피연산자 두개 중 마지막 피연산자 rhs에 값이 없을 때 nil이 됩니다. 이 때 오류처리를 해주어야 하는데 현재는 nil병합연산자로 처리 후 default값으로 99.999를 반환하였습니다. 아직 해결점을 찾지 못했습니다.
- split의 역할을 찾지 못했습니다. UML에 있어 빈 메서드로 파일만 만들어놓았습니다. 

---
## 배운개념
do-catch, Double타입 infinity,nan, XCFail, XCTAssertThrowsError

---
## 참고 링크
야곰 스위프트프로그래밍 책 - 고차함수부분 map, filter, reduce
[swift github / 함수](https://github.com/apple/swift/blob/main/stdlib/public/core/Integers.swift )
[Double타입 nan](https://developer.apple.com/documentation/swift/double/nan)
[XCTFail](https://developer.apple.com/documentation/xctest/1500970-xctfail)
[XCTAssertThrowsError](https://developer.apple.com/documentation/xctest/1500795-xctassertthrowserror/)
[XCTAssertThrowsError코드참고](https://www.appsdeveloperblog.com/xctassertthrowserror-assertion-example/)

2022-09-28 01:20 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요.

- Formula Reduce: 어떤 코드를 사용하려 했었는지 같이 주시면 이해하기 좋을거 같습니다.
- Formula nil: rhs 값이 없는 경우가 있나요..?
- split의 역할은 말 그대로 나누는 역할인데요. String extension에 정의하는 것이니 입력받은 수식을 나누는 역할을 해야겠죠. UML은 말 그대로 코드 설계도인데 해당 역할을 모른다면 빈 메서드를 넣어두는게 아니라 설계자에게 의도를 물어보시는게 좋을거 같습니다.

2022-09-28 01:20 UTC, wonhee009 commented on Calculator/Calculator/Model/Formula.swift
> +        }
위의 while 문을 통해 현재 `operands`는 Empty일 텐데요.
`operands`는 empty인데 `operator`는 남아 있는 상황이라면 계산이 정상적으로 이뤄졌다고 봐야할까요?

2022-09-28 01:20 UTC, wonhee009 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let result: [String] =  input.components(separatedBy: ["+","-","*","/"])
"+", "-", "*", "/"를 사용하는 부분이 있는거 같은데요.
`enum Operator`가 `CaseIterable`를 채택하고 있는데 `allCases` 등을 활용해볼 수 있지 않을까요

2022-09-28 01:20 UTC, wonhee009 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        sut.enqueueStack = [100.0, 200.0]
`calculatorItemQueue.enqueueStack`으로 접근 가능해서 public하게 열려 있다고 이해했는데요.
어디서든 `CalculatorItemQueue`의 내부 스택에 접근할 수 있어야 할까요?
저는 이런 부분들은 private으로 막혀 있고 `CalculatorItemQueue`라는 인터페이스를 통해서만 변경되어야 한다고 생각합니다.
이렇게 다 열려 있으면 어디서는 `CalculatorItemQueue`를 통해 스택이 변경되고 어디서는 내부 스택에 접근해서 데이터를 변경할텐데 이렇게되면 데이터의 정확성을 보장하기 힘들어지고 이후 디버깅도 힘들거 같습니다.

2022-09-29 08:58 UTC, lj-7-77 commented on Calculator/Calculator/Model/Formula.swift
> +        var rhs = operands.dequeue() ?? 99.999
**현재사용한 방법 - nil병합연산자**
> var lhs = operands.dequeue() ?? 99.999

에서 lhs 변수는 double타입입니다. 
operands.dequeue()의 결과값의 타입은 옵셔널입니다.
때문에 nil병합연산자를 이용하여 unwrapping해주었습니다. 99.999는 lhs변수의 Double타입에 맞춘 **임시부여한 기본값**입니다.
테스트할 때 기본값을 0으로 두는것 보다 99.999가 오류난 상황을 잘 파악할 수 있을것이라 생각하여 정하였습니다.

**고민한 방법 1 - guard let unwrapping**
아래코드는 guard로 unwrapping했었던 코드입니다. 그래도 역시 return 임시값을 해주어야합니다.
```swift
mutating func result() -> Double {
        var result: Double

        guard var lhs: Double = operands.dequeue(),
              let rhs: Double = operands.dequeue(),
              let operatorsValue = operators.dequeue() else {
            return 99.999
        }
        result = operatorsValue.calculate(lhs: lhs, rhs: rhs)
        
        while !operands.dequeueStack.isEmpty {
            lhs = result
            guard let rhs: Double = operands.dequeue(),
                  let operatorsValue = operators.dequeue() else {
                return 99.999
            }
            result = operatorsValue.calculate(lhs: lhs, rhs: rhs)
        }
        if operators.dequeueStack.isEmpty == false {
            operators.dequeueStack.removeAll()
        }
        return result
    }
```

---
**고민한 방법 2 - 옵셔널값을 최초로 반환하는 곳(CalculatorItemQueue의 dequeue메서드)에서 unwrapping을 해준 후에 가져오는 방법, unwrapping이 안되는 경우는 에러로 처리**
그런데 이 경우는 do-catch 안에서 쓰이는 변수값의 scope가 do-catch문 내부로 한정되어있어서 결과값을 반환할 때 사용할 수 없다는 에러가 뜹니다. 

```swift
mutating func dequeue() throws -> T {   //  CalculatorItemQueue.swift
        reverseQueue()
        
        guard let value  = dequeueStack.popLast() else {
            throw OccuredError.tryGetEmptyValue
        }
        return value
    }

```

```swift
mutating func result() throws -> Double {      //  Formula.swift
        var lhs: Double
        var result: Double
        
        do {
            lhs = try operands.dequeue()
            let rhs: Double = try operands.dequeue()
            let operatorsValue = try operators.dequeue()
            result = operatorsValue.calculate(lhs: lhs, rhs: rhs)
        } catch {
            throw OccuredError.tryGetEmptyValue
        }
        
        
        while !operands.dequeueStack.isEmpty {
            lhs = result
            do {
                let rhs: Double = try operands.dequeue()
                let operatorsValue = try operators.dequeue()
                result = operatorsValue.calculate(lhs: lhs, rhs: rhs)
            } catch {
                throw OccuredError.tryGetEmptyValue
            }
        }
        if operators.dequeueStack.isEmpty == false {
            operators.dequeueStack.removeAll()
        }
        return result
    }
```

```swift

import Foundation 

enum OccuredError: Error {  //  Error.swift - 설명드리기 위한 코드입니다.(커밋X)
    case tryGetEmptyValue
}
```

2022-09-29 11:44 UTC, lj-7-77 commented on Calculator/Calculator/Model/Operator.swift
> +            self.init(rawValue: ".")
➡️ "." 코드를 작성한 이유
- `ExpressionParser.swift` 파일의 `parse` 메서드의 역할은 피연산자(숫자)와 연산자를 각각 배열에 저장합니다.
- 그 중 연산자를 저장하는 방법은 Charactor타입인 ``"+"`` 값을 Operator타입인 `.add` 로 바꾸어 저장합니다. 바꾸는 과정에서 `self.init(rawValue: ".")` 이 코드가 필요했었습니다.
- Operator.swift 파일에서 `self.init(rawValue: ".")` 이 코드를 입력하지 않으면 아래와 같은 에러메세지가 뜹니다.
    > 'self.init' isn't called on all paths before returning from initializer

➡️ 에러메세지 해석
- 제 구현의도는 연산자기호값에 따라 Operator의 case를 결정하고, 결정된 case를 배열요소로 저장하고 싶었습니다.
+, -, *, / 는 각 case에 맞게 정하도록 작성했지만, 그 외의 연산자기호값이 올 경우 switch문의 default가 실행될 것이고, 저는 아무것도 하지않고 초기화를 종료하고싶었습니다.
- 그런데 컴퓨터 입장에서 보면 초기화를 어떻게 할 것인지 작성하지 않아서 위와 같은 에러메세지가 뜬 것으로 해석했습니다.

➡️ 결론
- Operator.swift 파일에서 ``"."`` 코드를 포함한 `init()` 초기화 메서드를 삭제했습니다. 
- 다른 방법으로도 Operator타입으로 변경 저장이 가능했습니다.
    아래 코드에서 for-in문을 forEach문과 그 안에 if문으로 해결할 수 있었습니다.


➡️ 수정 전
```swift
// ExpressionParser.swift 
static func parse(from input: String) -> Formula {
     (...중략...)
    let separatedOperators: [String] = input.filter {
            (input: Character ) -> Bool in
        return (input == "+") || (input == "-") || (input == "*") || (input == "/")
    }.map {
        (input: Character) -> String in
        return String(input)
    }
     
     //for-in문
    for stringOperator in separatedOperators {  
        
        //Operator타입의 init메서드 사용해야 했던 부분
        let convertedToCaseOperators: Operator = Operator.init(rawValue: stringOperator) 
        formula.operators.enqueue(element: convertedToCaseOperators)
    }
    return formula
}
```

➡️ 수정 후
```swift
// ExpressionParser.swift 
 static func parse(from input: String) -> Formula {
     (...중략...)
        let separatedOperators: [Character] = input.filter {
        (input: Character ) -> Bool in
        return (input == "+") || (input == "-") || (input == "*") || (input == "/")
    }
     
     //forEach문
    separatedOperators.forEach { separatedCharactorOperator in
        Operator.allCases.forEach { equalOperator in
                                   
            // rawValue를 이용하여 바꾸어 저장하는 부분
            if equalOperator.rawValue == separatedCharactorOperator {
                let convertedToCaseOperators: Operator = equalOperator
                formula.operators.enqueue(element: convertedToCaseOperators)
            }
        }
    }
    return formula
}
```

2022-09-29 12:36 UTC, lj-7-77 commented on Calculator/Calculator/Model/Formula.swift
> +        }
➡️ if구문 의도
operands는 empty인데 operator는 남아 있는 상황이 생기는 경우는
사용자가 `5.0 + (-10.0) + 3.0 * ` 를 차례로 누른 후 = 버튼을 눌렀을 경우를 고려하여 작성하였습니다.
마지막에 연산자를 입력 후 숫자를 입력하지 않고 = 버튼을 눌렀을 경우에는 입력이 끝난것으로 간주하고 남은 연산자들은 삭제하는 것으로 처리하였습니다.
때문에 정상적으로 이뤄졌다고 보았습니다.

➡️ 계산식 입력을 끝마친 것이 아닐 경우
고민해보니 `5.0 + (-10.0) + 3.0 * ` 누른 후 = 버튼이 아닌 `- * + 9.0` 로 입력한 경우일 가능성도 있어보입니다. 
그렇다면 사용자가 예상한 계산 식은 `5.0 + (-10.0) + 3.0 + 9.0` 일 것으로 생각됩니다.
연산자를 담고있는 스택을 전부 삭제하는 것 보다는
스택에 담기 전 `+,-,*,/` 연산자를 두 번 연속 입력할 경우에는 마지막에 입력한 연산자만 저장하는 방법으로 구현해야 할 것 같습니다. 이 부분은 좀 더 고민해보겠습니다.  생각치 못했던 부분입니다. 꼼꼼하게 봐주셔서 감사합니다.

2022-09-29 15:16 UTC, lj-7-77 commented
> Formula Reduce: 어떤 코드를 사용하려 했었는지 같이 주시면 이해하기 좋을거 같습니다.

넵, 앞으로 PR 할 때는 구체적으로 코드나 커밋아이디를 말씀드리겠습니다!
```swift
mutating func result() -> Double {
     var lhs = operands.dequeue() ?? 99.999
     var rhs = operands.dequeue() ?? 99.999   //중복
     var operatorsValue = operators.dequeue()   //중복
     var result = operatorsValue?.calculate(lhs: lhs, rhs: rhs) ?? 99.999//중복
        
     while !operands.dequeueStack.isEmpty {
        lhs = result
        rhs = operands.dequeue() ?? 99.999   //중복
        operatorsValue = operators.dequeue()   //중복
        result = operatorsValue?.calculate(lhs: lhs, rhs: rhs) ?? 99.999//중복
        }
}
```

**- Formula 구조체에서 result 메서드의 역할**
피연산자배열과 연산자배열로부터 값을 가져와서 더이상 값이 없을 때까지 계산하는 역할입니다.
**- lhs 변수**
피연산자를 담은 operands배열로부터 인덱스0에 있는 값(가장 먼저 입력된값)을 담는 변수입니다. 첫번째값을 가져온 후 값을 삭제합니다.
**- rhs 변수**
lhs가 값을 담은 후에 다시 operands배열로부터 인덱스0에 있는 값(lhs에서 가져간 값 다음으로 가장 먼저 입력된값)을 담는 변수입니다.
**- operatorsValue 변수**
연산자를 담은 operators배열로부터 인덱스0에 있는 값(가장 먼저 입력된 연산자값)을 담는 변수입니다.
**- result 변수**
lhs와 rhs로 operatorsValue에 해당되는 연산을 하고 그 결과를 담는 변수입니다.
**- reduce 고차함수를 사용하고싶은 부분**
reduce는 첫번째 매개변수에는 이전계산의 결과값을 담고, 두번째 매개변수에는 배열요소값을 담아서 더이상 값이 남아있지 않을 때까지 반복하여 계산 후 마지막 계산 결과값을 반환합니다.
현재 코드에서는 3-5번줄과 9~11번줄이 중복되어있고, 이 부분을 고차함수인 reduce를 이용하여 개선하고 싶습니다.

2022-09-30 15:42 UTC, lj-7-77 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let result: [String] =  input.components(separatedBy: ["+","-","*","/"])
넵, 그 부분을 놓치고 있었네요! 리뷰 주신대로 allCases를 활용하여 구현해보았습니다.

```swift
static func componentsByOperators(from input: String) -> [String] {
    var operatorSet: CharacterSet = CharacterSet()
    Operator.allCases.forEach{
        operatorSet.insert(charactersIn: String($0.rawValue))
    }
    let result: [String] = input.components(separatedBy: operatorSet)
    return result
}
```

2022-09-30 16:05 UTC, lj-7-77 commented
> 질문 : Formula result메서드에서 계산해야 할 피연산자 두개 중 마지막 피연산자 rhs에 값이 없을 때 nil이 됩니다. 이 때 오류처리를 해주어야 하는데 현재는 nil병합연산자로 처리 후 default값으로 99.999를 반환하였습니다. 아직 해결점을 찾지 못했습니다.

> 리뷰 : Formula nil: rhs 값이 없는 경우가 있나요..?

1+2*3- 과 같이 
연산자가 하나 남는 상황에서는 rhs변수에 nil값이 저장될것이라 예상했습니다.
그런데 생각해보니 이부분은 값을 입력받는 기능을 구현할 때 보완이 가능합니다.
연산자다음에 = 버튼이 눌릴경우 마지막에 입력한 연산자만 저장하는 방법으로요. 
그러면 rhs에 nil이 오는 경우를 고려하지 않아도 되어 오류처리를 안해도 됩니다.

2022-09-30 17:10 UTC, lj-7-77 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        sut.enqueueStack = [100.0, 200.0]
넵, 어디서든 `CalculatorItemQueue`의 내부 스택에 접근할 수 있으면 안된다고 생각합니다.
아래와 같이 수정하였습니다.
```swift
    func test_dequeueStack이_비어있지않은경우_값을_넣지않는지() {
        sut.enqueue(element: 100.0)
        sut.enqueue(element: 200.0)
```
그리고 접근제어자 키워드를 작성하지 않은 상태인 것을 testable attribute를 테스트파일에 명시해놓아서 접근 가능한 상태라고 잘못 파악하고 있었습니다.
접근제어자가 필요한 이유 중 데이터의 정확성 보장과 효율적인 디버깅이 있다는 점 배워갑니다. 현재 프로젝트에 private 접근제어자가 안걸려있는데, 추가 수정하겠습니다.

2022-09-30 17:45 UTC, lj-7-77 commented on Calculator/Calculator/Model/String.swift
> +    }
넵 말씀주신대로 크루에게 물어보았습니다.
정답은 정해져있지 않고, 제가 어떤 의도로 구현하는지에 따라 split의 역할이 달라진다 하였습니다.
입력받은 수식을 나누는 역할은 이미 componentsByOperators에서 하고있기 때문에 제가  생각기에는 split메서드는 불필요하다 생각합니다.

만약 그럼에도 UML을 따라야했을 경우의 구현을 해보았습니다.
```swift
func split(with target: Character) -> [String] {
    let result: [String] = self.components(separatedBy: String(target))
    return result
}
```

2022-10-02 00:18 UTC, wonhee009 commented on Calculator/Calculator/Model/Formula.swift
> +        var rhs = operands.dequeue() ?? 99.999
저는 `result`가 꼭 non-Optional여야 할지 모르겠습니다. `result`가 Optional이고 `result`를 호출하는 곳에서 nil이라면 에러를 노출하면 되지 않나 생각했습니다.

2022-10-02 01:47 UTC, lj-7-77 commented on Calculator/Calculator/Model/Formula.swift
> +        var rhs = operands.dequeue() ?? 99.999
아하 반환타입을 옵셔널로 하는 방법도 있었네요! 해보겠습니다!

2022-10-02 09:06 UTC, lj-7-77 commented on Calculator/Calculator/Model/Formula.swift
> +        var rhs = operands.dequeue() ?? 99.999
에러처리 구현해보았습니다.

에러 던지는 곳 (Formula.swift, result() 메서드)
```swift
mutating func result() throws -> Double? {
    //(...중략...)
    guard let firstOperatorsValue: Operator = operators.dequeue() else {
        throw OccuredError.emptyOperator
    }
    //(...중략...)
     return result
}
```
---
에러 받는 곳 (FormulaTests.swift, 테스트메서드)
```swift
func test_연산자입력_안되었을_경우_오류처리_하는지() {
    //given
    sut.operands.enqueue(element: 5.0)
    sut.operands.enqueue(element: -10.0)

    //when
    var result: Double?
    do {
        result = try sut.result()
    } catch OccuredError.emptyOperator {
        print("잘못된 입력입니다. 연산자를 포함하여 입력해주세요.")
    } catch { }

    //then
    XCTAssertEqual(result, nil)
}
```
에러를 받는 곳은 result메서드를 호출하는 곳인데, 테스트메서드에 구현하였습니다. 나중에 화면과 연결되어 오류처리를 하려면 result메서드를 호출하는 곳에 do-catch구문이 들어가야 합니다.

2022-10-03 07:50 UTC, wonhee009 approved these changes
수고하셨습니다 :)

2022-10-03 07:50 UTC, merged