계산기 [STEP 3] 토털이
yagom-academy/ios-calculator-app pull request #358
Opened 2022-09-27 06:57 UTC by tottalE

@protocorn93  안녕하세요 콘~ 다시 만나 반갑습니다~~ 이번 리뷰도 잘 부탁드립니다~ 제가 UIkit을 잘 알지 못해서 많이 지적해 주실 수록 제 실력은 쭉쭉 올라갈겁니다 ㅎㅎ~!! 잘 부탁 드려용😇

## 🌈 고민한 점 및 궁금한 점
### 1. `layoutIfNeeded()`
```swift
private func updateScrollViewToBottom() {
        
        operandAndOperatorScrollView.layoutIfNeeded()
        operandAndOperatorScrollView.setContentOffset(
            CGPoint(x: 0,
                    y: operandAndOperatorScrollView.contentSize.height - operandAndOperatorScrollView.bounds.height),
                    animated: true)
}
```
- 위 함수가 항상 마지막 stackView를 제외한 연산 stack의 결과만 보여주어서 어떤 방법이 있을까 찾다가, 스택뷰가 스크롤뷰를 업데이트 하기 전에 업데이트 되지 않았다는 사실을 알고 `layoutIfNeeded()`를 써 주었습니다. 이 부분이 제가 가장 많이 고민했던 부분이었던 것 같습니다!!

### 2. 함수의 기능 분리
- 제가 UIKit을 잘 알지 못해서 어떤 면에서는 로직 분리가 잘 되어있는 것인지 많이 고민이 됩니다. 예를 들어, 저는 아래 코드와 같은 방식으로 많은 로직들을 처리해 주었는데요.

```swift
@IBAction func subtractButtonPressed(_ sender: UIButton) {
        
    if operandLabel.text == "0" {
        updateExpression(nextOperator: "−")
        return
    }
    updateOperandAndOperatorStackView()
    updateExpression(nextOperator: "−")
}
```

`if operandLabel.text == "0"`의 조건에 들면 그냥 바로 리턴할 수 있도록 분기를 나누어 주었는데 많은 코드에서 그런 부분을 찾으실 수 있으실 겁니다. 이런 방법이 가독성이 좋은 방법인지 궁금합니다! 그리고 기능 분리가 잘 되어있는 것일지 의문이 듭니다!!

### 3. enum 처리와 String 값 사이의 고민
- 1,2,3,4,5,6,7,8,9와 같은 값을 enum으로 만들어 처리를 해 줄지 String 그대로 처리를 해 줄지 고민을 했었습니다. 결론적으로 제가 분기를 스트링으로 나누어 주는 부분이 많아 String으로 처리하는 것이 더 깔끔할 것 같아서 그렇게 진행해 주었습니다. 뭔가 자동화(?)하지 않은 느낌이라 찜찜하기도 한데 이 부분에서 제가 좀 더 다른 데이터 타입들을 사용해 주었다면 더 좋았을까요? 궁금합니다 ㅎㅎ

2022-09-28 06:48 UTC, protocorn93 requested changes
수고하셨어요 토털이! UIKit 작업도 잘 해주신 것 같아요. 스크롤뷰도 적절하게 활용해서 깔끔하게 구현하신 점 인상적이었어요! 👍

스토리보드를 활용해 UI를 그려주셨는데, 이를 확인하려면 제가 레포를 다운받아서 직접 확인하는 방법밖에 없어요! (물론 저는 리뷰어 입장이니까 이렇게 하는게 당연한데, 현업에선 이렇게 하기에는 수고와 시간이 더 들어가겠죠! 그래서 스토리보드로 작성하는 팀은 보통 구동 영상이나 사진을 첨부하곤해요.) 아시다시피 머지 컨플릭이 발생했을 때 수정도 어렵구요! 

그래서 현업에선 코드로 UI를 작성하곤해요! 그래서 좋은 연습방법으론 스토리보드로 구현한 UI를 다시 코드로 구현하는 방법이에요! 이건 시간날 때 추가로 학습해보시는걸 권장해드려요. 


--- 


## 🌈 고민한 점 및 궁금한 점

> 1. layoutIfNeeded()

적절하게 잘 사용해주신 것 같아요. 이와 비슷한 역할을 하는. `setNeedsLayout`이라는 메서드도 있어요. 이 둘의 차이점을 공부해보시면 레이아웃 프로세스 전반에 대해 이해를 하는데 도움이 될 거에요! 관련된 블로그글도 상당히 많으니 한번 학습해보시는걸 권장해드려요! 

> 2. 함수의 기능 분리

가독성이나 관리 부분에 있어서는 제가 관련해서 코멘트를 남겨놓았어요! 저는 1줄짜리 메서드라도 코드보다 메서드명이 보다 직관적인 의미를 전달한다면 그렇게 분리해서 사용하는 편이에요! 현재 토털이 코드를 보아도 그렇게 잘 작성되어 있는 것으로 보여져요! 

> 3. enum 처리와 String 값 사이의 고민

이 부분에 대해서는 제가 별도로 코멘트를 남겨놓았어요! 


--- 

## 추가 피드백

> ExpressionParser의 역할은 어디까지인가? 

현재 음수/양수 부호처리, 소숫점 처리를 뷰 컨트롤러에서 진행되는걸로 보여져요. 이런 것들도 `ExpressionParser`에서 처리되어야 하지 않을까요? 우리가 ExpressionParser 코드를 그대로 다른 앱이나 플랫폼으로 옮겨간다고 했을 때 어느 역할까지 가져가는게 좋을까요?

> 소소한 UI 이슈

스크린샷 상에서는 잘 안보이는데, vertical scroll indicator를 안보이게 해주시면 좋을 것 같아요! 

<image src="https://user-images.githubusercontent.com/20634806/192707661-15ceacb9-5940-43ed-8ffb-6bac7c7bd679.png" width=350/>

2022-09-28 06:48 UTC, protocorn93 commented on Calculator/Calculator/Model/CalculatorError.swift
> +    case dividedByZero
0으로 나누는 것을 에러로 추출한 점 훌륭해요! 👍

2022-09-28 06:48 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet weak var operatorLabel: UILabel!
`@IBOutlet` 변수들에도 접근제어자를 붙여주세요~

2022-09-28 06:48 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func numberZeroButtonPressed(_ sender: UIButton) {
`@IBAction` 메서드도 마찬가지로 접근제어자 붙여주세요~

2022-09-28 06:48 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +        numberFormatter.numberStyle = .decimal
메서드를 실행할 때마다 `NumberFormatter`를 생성할텐데, 물론 큰 성능상의 이슈는 없어보이지만 저는 보통 내부 프로퍼티로 선언해놓고 재사용하긴해요

2022-09-28 06:48 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +            updateExpression(nextOperator: "÷")
`0`으로 나눌 때 `nextOperator`를 `+`로 하신 이유가 궁금하네요

2022-09-28 06:48 UTC, protocorn93 commented on Calculator/Calculator/ViewController.swift
> +        if operandLabel.text == "0" {
`operandLabel.text == "0"` 조건이 반복되는데 이렇게 반복된다면 별도 프로퍼티로 추출하는게 좋아요!

2022-10-01 08:47 UTC, tottalE commented
> 현재 음수/양수 부호처리, 소숫점 처리를 뷰 컨트롤러에서 진행되는걸로 보여져요. 이런 것들도 ExpressionParser에서 처리되어야 하지 않을까요? 우리가 ExpressionParser 코드를 그대로 다른 앱이나 플랫폼으로 옮겨간다고 했을 때 어느 역할까지 가져가는게 좋을까요?
현재 부호를 붙여주는 역할은 view에서 하지만, 그 부호를 parse하는 역할은 모두 ExpressionParser에서 담당하고 있습니다! 그래서 저는 Parse를 해서 Formula를 만들어주는 기능까지만 ExpressionParser에서 하도록 하고, ExpressionParser에 값이 들어가기 전에 변화하는 값들은 viewController에서 하나의 스트링에 단순히 넣고 빼고하는 반복 작업만을 하도록 하였습니다. 결국 저의 로직에서는, UI상에서 보이게, 그리고 ExpressionParser에 들어갈 내용을 정해주는 것 까지가 VC의 역할이고,  ExpressionParser는  만들어진 하나의 스트링을 단순히 Parse(분류)해서 Formula로 만들어주는 역할만을 담당하게 해주었습니다. VC상에서의 로직도 단순히 화면상에서 마이너스가 존재하는가 존재하지 않는가?로 UI를 업데이트 방향성을 정하는 로직이자 스트링을 업데이트 해주는 로직으로 사용하고 있습니다. 이것을 ExpressionParser에서 하지 않고 VC에서 하면, UI 업데이트를 올바르게 해줄 수 있으며, 그 업데이트와 함께 스트링을 단순하게 업데이트 해줄 수 있어 코드의 간결성을 높여준다고 생각했습니다.

2022-10-01 08:48 UTC, tottalE commented on Calculator/Calculator/Model/CalculatorError.swift
> +    case dividedByZero
감사합니다 :)

2022-10-01 09:27 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet weak var operatorLabel: UILabel!
> 여기에 수정했어요!

[3c12e2c](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/3c12e2c47a5de4195f86589f00193c3ef637ba96)

2022-10-01 09:29 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func numberZeroButtonPressed(_ sender: UIButton) {
> 여기에 수정했습니다!!

[c4a0095](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/c4a00959029921d2c93eeac262ef3f34d8c16172)

2022-10-01 09:37 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +        numberFormatter.numberStyle = .decimal
네 참고하여 재사용할 수 있도록 하겠습니다!

> 여기에 고쳤습니다!

[3b995c9](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/3b995c95531094960dd4fed448b4ad13f49028ae)

2022-10-02 02:34 UTC, tottalE commented on Calculator/Calculator/Model/Operator.swift
> +    case subtract = "−"
네 계산기에서 단순히 부호를 고쳐주는 -와 −는 굉장히 구분하기 어려운데 ㅋㅋㅋ 그게 캐릭터 상에서 구분이 되어서 Double값에 -를 넣어 마이너스 숫자를 파싱할 수 있도록 만들어 주기 위해서 저렇게 사용해주었습니다. 바꾼 캐릭터는 - 가 아닌 −로 좀 더 긴 캐릭터입니다. 읽으실 때 헷갈리셨을 텐데 제가 설명을 더 드릴걸 그랬습니다! 하하

2022-10-02 02:58 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +        updateOperandLabel(with: "00")
네 정말 좋은 방법인 것 같아요! 
네임 스페이스 만들어주고, 메서드들에 적용까지 완료했습니다 감사합니다 👍 

> 여기에 수정해 주었습니다 :) 메서드를 나누어서 커밋해서 커밋이 좀 많네요 ㅎㅎ
[e3479ed](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/e3479ed8bb3ace171c229a91040f15e69278030d)
[141df38](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/141df38e83103b7e8a19c3dc1d6b9f448995a82e)
[a391f7a](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/a391f7a33627a4a85a4a978a006ec8e01dd3f8ba)
[52ae199](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/52ae199bf49cff72574f115713b1a3ad251cad8c)
[bce9321](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/bce9321b2f05beff10abfc15dd810f5777b00abe)
[8c1786a](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/8c1786a661f697359274e1863bccd541cebc0917)
[3e31510](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/3e315104b3cffa7c3678e66f1fe682a649b462b8)
[f8839ad](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/f8839ad34a0d033811bad6d254ac0cd708e926c4)
[045b685](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/045b685a194fc82ad810e119b5918d04a4c250bf)
[8612d4e](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/8612d4e39685e8ddaaae0a16b0b67b64dc0d7f59)
[3930f41](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/3930f41351ffe3d9b0a19c2748693fea74abb621)

2022-10-02 03:04 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +            updateExpression(nextOperator: "÷")
이 로직은 레이블이 0일 경우에 연산자를 바꿔주는 기능을 넣기위해 추가해준 분기입니다!! 다른 연산자들에서도 같은 분기를 사용중입니다 ㅎㅎ

2022-10-02 03:05 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
>  class ViewController: UIViewController {
네 뷰컨트롤러는 차마 생각하지 못했네요! 좋은 리뷰 감사합니다!!

> 여기에 수정했습니다!
[81d0309](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/81d03097cdb36623aa32bb4a8bf4baab76d560b4)

2022-10-02 03:08 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +    private func removeAlloperandAndOperatorStackViewSubviews() {
네 저도 너무 메서드명이 길어져서 고민이 되었는데, 특히 지금처럼 뷰가 하나뿐인 앱에서는 subview가 특정되기 때문에 말씀하신 네이밍이 좋은 것 같습니다!

> 여기에 수정해주었습니다!
[d320d0d](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/d320d0d709db7431e0da7cf569ae69fcbdad3403)

2022-10-02 03:08 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +        if operandLabel.text == "0" {
네 이 부분은 네임스페이스 부분에서 같이 해결되었습니다 ㅎㅎ 감사합니다 ㅎㅎ

2022-10-02 03:09 UTC, tottalE commented on Calculator/Calculator/ViewController.swift
> +    var expression: String = ""
네 윗부분에서 프로퍼티 접근제어자와 함께 수정해주었습니다!

> 이 부분에서 수정했어요!
[3c12e2c](https://github.com/yagom-academy/ios-calculator-app/pull/358/commits/3c12e2c47a5de4195f86589f00193c3ef637ba96)

2022-10-04 13:38 UTC, merged