계산기 [STEP 2] Baem
yagom-academy/ios-calculator-app pull request #359
Opened 2022-09-27 12:25 UTC by Dylan-yoon

@1Consumption 안녕하세요 올라프!
드디어 저도 step2 pr올리게 되었네요...
먼저 이렇게 프로토콜과 익스텐션을 활용해서 구현하는게 처음이다보니 생각하는 시간이 많아졌습니다.
TDD를 조금 따르고 싶어서 해보긴했지만, 생각보다 UnitTest에서 구현한 함수들이 오류가 많이나서 시간이 오래걸렸던것 같습니다

## 고민했던점 & 조언을 얻고싶은 부분
나눗셈 연산할 때 0을 입력하게된다면 Operator에서 에러를 내야할지, formula 에서 내야할지에 대한 고민을 많이했습니다.
이부분은 고민을 해보고 올라프의 조언을 좀 듣고 진행하고싶어서 아직 에러처리를 하지않았습니다.
operator.calculates 
formula 
아직도 고민중에 있는것 같습니다.😭

String+Extension의 split과 ExpressionParser의 componentsByOperator의 의미를 잘 모르겠습니다..
UML에 있기 때문에 선언을 해두고 고민을 계속 해보았는데,, 어떻게 활용해야할지 고민을 많이했습니다.

나름 파일 분리를 해보았는데, 올라프 같은 경우는 보통 어떻게 하시는지 궁금합니다.

2022-09-27 18:20 UTC, 1Consumption requested changes
안녕하세요 @Dylan-yoon
고생하셨습니다.

고민을 많이 한 티가 나는 코드였어요. 👍
또한 커밋도 최대한 작게, 하나의 역할만 하도록 나눠서 좋았습니다.

몇가지 아쉬운 점은 코멘트로 남겼어요.

아래는 질문주신 점에 대한 제 답변입니다.

## 고민했던점 & 조언을 얻고싶은 부분
- 나눗셈 연산할 때 0을 입력하게된다면 Operator에서 에러를 내야할지, formula 에서 내야할지에 대한 고민을 많이했습니다.
이부분은 고민을 해보고 올라프의 조언을 좀 듣고 진행하고싶어서 아직 에러처리를 하지않았습니다.
추가로 Operator에서 에러 쓰로우를 하지않는 상태로 유닛테스트를 해왔는데, throws 키워드를 사용하게 된다면 많은 유닛테스트들에 try를 붙여주어야 하는 상황이 올텐데 이럴땐 어떻게 해야되는지 궁금합니다.

> 저라면 formula 에서 에러를 던질듯 합니다. 계산을 할 때 발생하는 에러니까요. 또한 throws 키워드를 원래 사용해야하는데 사용하지 않았기 때문에 throws 추가시 try를 붙여줘야하는건 어쩔수 없어보입니다. 

- 유닛테스트 시작할때 파일마다 모든 시뮬레이터가 켜지는데..
disable해서 끄는방법 밖에 없는지 궁금합니다..
![스크린샷 2022-09-27 23 01 00](https://user-images.githubusercontent.com/77507952/192547595-1e041bc2-3fa2-482d-81b3-e915b5a8b0cd.png)

> 디스코드에서도 얘기를 나눴는데, 테스트 파일마다 타겟을 만들지 말고, 하나의 테스트 타겟에 여러개의 테스트 파일을 만드는게 나아보입니다.

나머지는 코멘트를 참고해주세요.

2022-09-27 18:42 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +        }
사칙연산이다보니 스위치에 같은 로직이 4번이나 반복되기 때문에 이를 묶어서 처리하고자 내부에서만 사용할 목적으로 사용했습니다.

2022-09-28 09:29 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +                throw ExpressionParserError.doNotChangeDouble
네 확인했습니다.!

2022-09-28 09:31 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +            beforeDoubleValue = ""
네 맞습니다.
`componentsByOperator` 와 `split`을 구현하지 않았기 때문에 Parse에서 모든것을 해결하게 되어버렸습니다.
수정하겠습니다.

2022-09-28 09:32 UTC, Dylan-yoon commented on Calculator/Calculator/Model/FormulaEntity/Formula.swift
> +        while !(operators.count == 0) {
네 확인했습니다! 감사합니다!

2022-09-28 14:54 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +                try enqueueOperand(and: .subtract)
고민되었던점에서 말씀드렸듯, 고민해결되어 리펙토링했습니다.
```swift 
func test_divide일_때_calculates실행_시_오류를_던져주는가() {}
```
유닛테스트 구현해서 오류처리 하였습니다.
또한 try 사용으로인한 사이드 이펙트 또한 수정했습니다

2022-09-28 15:16 UTC, Dylan-yoon commented on Calculator/Calculator/Model/FormulaEntity/Formula.swift
> +        calculateResult = firstOperand as! Double
타입 캐스팅을 이번 프로젝트에서 처음 써보았습니다.
다른 옵셔널들은 모두 guard 혹은 if문을 통해 강제 언랩핑을 하지않았지만,
안일하게 double이 무조건 들어온다 생각하고 오류처리를 하지않았던것 같습니다.

확인하고 바로  강제 언랩핑이아닌 오류처리를 했습니다.
감사합니다!

2022-09-28 15:23 UTC, Dylan-yoon commented on Calculator/Calculator/Model/Operator.swift
> +    }
고민되었던점에서 말씀드렸듯, 고민해결되어 리펙토링했습니다.

func test_divide일_때_calculates실행_시_오류를_던져주는가() {}
유닛테스트 구현해서 오류처리 하였습니다.
또한 try 사용으로인한 사이드 이펙트 또한 수정했습니다

2022-09-28 17:47 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +        operands.enqueue(changingDouble)
네 그렇습니다.
마지막을 어떻게 처리해야할까 고민하다가 방법이 떠오르지 않아서 마지막에 추가적으로 한번 더 실행 했습니다.

2022-09-28 17:55 UTC, Dylan-yoon commented on Calculator/UnitTests/ExpressionParserTests/ExpressionParserTests.swift
> +        XCTAssertEqual(try? result?.result(), expression2Result)
맞습니다.
추가로
```
//when
var result = try ExpressionParser.parse(from: given)
```
이렇게 변수 상수를 만들어서 XCTAssertThrowsError에 넣어준다면
when 에서 에러가 발생되기 때문에 실행되지 않을텐데

given
when
then 
패턴에서 
when을 어떻게 처리해야될지 고민이됩니다.

지금 리펙토링한것처럼 주석만 남겨두어도 되는지 궁금합니다!

2022-09-28 18:09 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +                try enqueueOperand(and: .subtract)
새로 ExpressionParser를 구현한다음 unit test 진행해서
리팩토링했습니다 감사합니다!

2022-09-28 18:13 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +    }
```swift
    private static func componentsByOperator(from input: String) -> [String] {
        return input.split(with: " ")
    }
```
split 구현한것을 바탕으로 공백 기준으로 배열로 바꾸어 주었습니다,

2022-09-28 18:27 UTC, Dylan-yoon commented on Calculator/Calculator/Model/String+Extension.swift
> +        return result
처음에 components를 쓸거면 이걸 왜 구현하라고 했을까 라고 생각했습니다.


```swift
if result.first == "" {
            result.removeFirst()
        }
        if result.last == "" {
            result.removeLast()
        }
```
결국은 위와 같이 빈 공백을 없애기 위해 새로운 extension을 정의했구나 라고 다시생각 했던것 같습니다.!

2022-09-29 11:39 UTC, 1Consumption requested changes
고생하셨습니다.💪 

코멘트를 조금 남겼으니 확인 부탁드릴게요.

2022-09-29 11:39 UTC, 1Consumption commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +        }
이부분 코드를 좀 더 설명해주시겠어요? 잘 이해가 되지않네요.

2022-09-29 11:39 UTC, 1Consumption commented on Calculator/Calculator/Model/FormulaEntity/Formula.swift
> +        while !(operators.count == 0) {
여기가 수정되지 않은듯해요.

2022-09-29 11:39 UTC, 1Consumption commented on Calculator/Calculator/Model/String+Extension.swift
> +        }
https://developer.apple.com/documentation/foundation/nsstring/1415462-trimmingcharacters 이 메소드를 참고해보세요.

2022-09-29 11:39 UTC, 1Consumption commented on Calculator/UnitTests/ExpressionParserTests.swift
> +        XCTAssertThrowsError(try ExpressionParser.parse(from: given3))
에러를 던지는지만 보지말고 어떤 에러를 던지는지도 확인해야하지 않을까요?

2022-09-29 11:39 UTC, 1Consumption commented on Calculator/UnitTests/OperatorTests.swift
> +        sut = .subtract
이거는 given에 들어가지 않나요?

2022-09-29 11:46 UTC, Dylan-yoon reviewed
test

2022-09-29 11:46 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +            operands.enqueue(0.0)
test

2022-09-29 12:07 UTC, Dylan-yoon commented on Calculator/UnitTests/OperatorTests.swift
> +        sut = .subtract
https://github.com/yagom-academy/ios-calculator-app/pull/359/commits/d66598856a9277116237da8503a54d345024b52d
given when then 패턴에 맞게 다시 정리했습니다 감사합니다!

2022-09-29 12:28 UTC, Dylan-yoon commented on Calculator/Calculator/Model/String+Extension.swift
> +        }
https://github.com/yagom-academy/ios-calculator-app/pull/359/commits/3c52ebe82e6883d9eff1d491f542c6d97b8f25ff
감사합니다.
말씀해주신대로 적용해보았습니다 감사합니다!!!!!!

2022-09-29 12:56 UTC, Dylan-yoon commented on Calculator/UnitTests/ExpressionParserTests.swift
> +        XCTAssertThrowsError(try ExpressionParser.parse(from: given3))
https://github.com/yagom-academy/ios-calculator-app/pull/359/commits/10e9473fab9d220045b89f60192c52d8b662bb29

네 감사합니다 확인 후 변경했습니다.

2022-09-29 13:58 UTC, Dylan-yoon commented on Calculator/Calculator/Model/ExpressionParserEntity/ExpressionParser.swift
> +        }
https://github.com/yagom-academy/ios-calculator-app/pull/359/commits/50cbafe1bf50e20a8ca7e2fc6f4f57a056cdc302
아이디어가 따로 떠오르지 않아서..
함수로 분리해주었습니다..

2022-09-30 09:51 UTC, merged

2022-09-30 09:51 UTC, 1Consumption commented
고생하셨습니다.