계산기 [Step3] Kyo
yagom-academy/ios-calculator-app pull request #362
Opened 2022-09-28 06:42 UTC by KyoPak

@uuu1101 
안녕하세요! 태태! Kyo 입니다.
계산기 Step-3 PR 드립니다. 이번 Step은 로직적으로 생각할 부분이 많아서 고생했습니다..
추가로 완성도를 위해서 몇 가지 기능을 추가해보았습니다.
그리고 코드에서 계산 내역을 History라고 표현을 해서 PR에서도 History라고 표현하겠습니다!

1. `=` 버튼을 눌러서 계산을 완료한 후에도 연산자를 누르면 다시 계산을 이어나갈수 있도록했습니다.
    - 계산결과가 나왔을 때는 Operator와 AC, EC 버튼만 누를수 있게 끔 하였습니다.
2. NumberFormatter 적용을 계산 결과 Label 뿐만 아니라 History에도 적용하였습니다. 
3. 0을 따로 누르면 0을 포함한 계산 기능 구현했습니다. 

추가적으로 설명이 필요하신 부분이 있다면 메세지 주시면 바로 달려가겠습니다! ㅎㅎ
이번에도 좋은 피드백 잘 부탁드립니다!!🙇

### 진행 단계 : Step3
## ⭐️ 구현한 기능
- `makeHistoryStackViewLabel()`
    - ScrollView 내부의 StackView에 들어갈 Label들을 생성하는 메서드 입니다.
- `makeHistoryStackView()`
    - makeHistoryStackViewLabel()를 이용하여 만든 Label들을 하나의 StackView로 생성하는 메서드입니다.
- `updateCalculateHistory()`
    - 계산 History를 추가해줄때마다 호출이 되며, 내부에서 호출될때마다 layoutIfNeeded()함수로 바로 레이아웃을 다시 그린 후에, ContentSize의 높이와 frameSize의 높이의 차이 만큼 ScrollView의 y축이 내려가게끔 하는 메서드입니다.

- `tappedNumberPads()` : (1~9, 0, 00) 버튼 클릭시 동작 메서드
 `tappedOperatorPads()` : (+, -, ÷, ×) 버튼 클릭시 동작 메서드 
`tappedCalculate()` : (=) 버튼 클릭시 동작 메서드
`tappedDotPads()` : (.) 버튼 클릭시 동작 메서드 
`tappedChangePositiveNegative()` : (⁺⁄₋) 버튼 클릭시 동작 메서드
`tappedAllClear()` : (AC) 버튼 클릭시 동작 메서드
`tappedClearEntry()` :  (EC) 버튼 클릭시 동작 메서드

- `tappedNumberPads()`
    - 이 메서드 기능을 차례대로 기재하겠습니다.
        1. 현재 입력값이 DefaultZero이거나 zero일 경우에서 내부에서 "00"입력과 Operator가 `=` 이 아닐 경우에 현재 currentOperand에 값 대입.
        2. 입력값이 이미 있을 경우에는 누르는 값들이 덧붙여져서 추가되는 방식으로 구현
- `tappedOperatorPads()` 
    - 이 메서드 기능을 차례대로 기재하겠습니다.
        1. 가장 첫번째 숫자 입력 전에 Operator 입력 방지.
        2. 계산의 결과 이후에 또 Oerator을 입력한다면 mainLabel값을 Zero로 바꾸고  currentOperant값을 defaultZero로 바꾸어 연속해서 연산할수 있도록 구현.
        3. currentOperand가 defaultZero인 경우에는 연산 안되게 구현.
        4. 계산 History에 추가

## ⭐️ 코드를 작성할 때 고민되었던 점

- 실제로 0을 사용하고 싶은 경우와 Default 0과의 비교
    - 실제로 0을 계산에 추가할 때와 기본 mainResultLabel이 0일 때 구분이 필요하였습니다.
    - 실제로 유저가 0을 입력할 때와, 기본 Default 0을 사용할때 둘을 구분하기 위해서 `mainResultLabel`의 값은 모두 `Constant.zero`라는 값을 사용하였고, 그 내부 로직을 사용할 때는  currentOperand의 값을 `Contant.defaultZero(D0)`, `Constant.zero(0)` 라는 각각의 값으로 변경하며 구분하였습니다.
- ScrollView
    - 일단 ContentSize와 FrameSize의 차이가 발생할 때 ScrollView의 위치를 그 차이만큼 내렸다고 생각됩니다. 그리고 layoutIfNeeded()의 호출위치에 대해서도 헷갈리는 점이 많았습니다. layoutIfNeeded()를 언제 호출하느냐에 따라서 동작이 달라지는데 이 부분은 조금 더 고민해봐야할 것 같습니다..
- 전체적인 로직
    - 전체적인 로직을 구현하는 것은 시간이 오래걸리지않았지만 세부적인 로직들을 추가하는 과정에서 고민을 많이 했습니다. 그 결과로 코드상에서 조건문들이 많아지고 조금 복잡하게 되었습니다.
- `=` 버튼을 누르고 계산을 이어나갈수 있는 기능
    - `=` 버튼을 누른 후에 Operator들을 누르면 다시 DefaultZero값이 되고 숫자만 입력이 되게끔 구현을 하였는데, 조건문에 계산결과라는 플래그가 필요로 하였고, Constant.calculate를 플래그로 사용하였습니다.

## ⭐️ 해결이 되지 않은 점
- 아직 테스트에서 발생된 오류는 없습니다만..태태가 동작해보실때 오류를 찾는다면 전달 꼭 부탁드립니다.🤣

## ⭐️ 조언을 얻고 싶은 부분 
- 이렇게 동작이 중요한 프로그램 Step을 진행해나갈때는 테스트 방식을 어떻게 진행하는지 궁금합니다.
    - 직접 실행을 해보며 오류 부분을 찾거나 lldb를 이용해서 변수에 대입되는 값들을 찾는 방식으로 테스트를 진행하는지 혹은 별도의 Unit테스트와 유사한 방법이 또 있는지 궁금합니다.
- 로직이 복잡해짐에 따라서 플래그가 많아지고 조건문이 많아졌습니다. 이럴수록 코드를 읽는 사람은 가독성이 떨어질것이라고 생각되는데 향후 Step진행시에 mark로 주석처리를 해서 기능을 명시해도 괜찮을지 궁금합니다.
- ScrollView를 내리는 방법을 layoutIfNeeded()와 contenSize.height와 FrameSize.height의 차이로 구현을 하였는데 다른 방법이 떠오르지 않는데 태태의 생각이 궁금합니다! 
- 전체적으로 메서드의 이름, 코드컨벤션, 로직부분을 피드백 받고 싶습니다..!

2022-09-30 05:45 UTC, uuu1101 requested changes
안녕하세요 @KyoPak !
리뷰가 조금 늦어졌는데, 이해해주셔서 감사합니다 :) 

코드 컨벤션은 전체적으로 깔끔해서 보기 좋았습니다. 👍🏻

컨벤션 및 네이밍에 관련해서 몇가지 코멘트 두었어요.
테스트를 하면서 기능면에서 오류는 저도 아직 찾지 못했습니다 😊

## 궁금한 점 
- 숫자 0을 계산식에 포함하셨는데, 이유가 궁금합니다.
단순한 궁금증입니다 :) 

## 조언이 필요한 사항
- Step을 진행해나갈때는 테스트 방식을 어떻게 진행하는지 궁금합니다.
> UnitTest를 통해서 로직을 검증하고 서버 통신 & 데이터 전달에 관한 부분들은 lldb를 주로 사용하는 편입니다. 현재 단계에서는 많이 경험해보시는게 제일 좋은것 같습니다. lldb는 정말 유용합니다.

- 로직이 복잡해짐에 따라서 플래그가 많아지고 조건문이 많아졌습니다.
> 해당 부분은 물론 주석이 필요없는 코드를 작성하는게 가장 좋은 방법이겠지만, 그렇지 못할 경우 코드를 읽는 사람을 위해 필요한 주석은 추가해주면 좋다고 생각듭니다. 
if문 대신 switch문을 사용한다거나, 여러 if문이 겹친다면, if문 로직을 하나의 메서드로 빼서 관리를 해줄 수도 있을 것 같습니다. 

- ScrollView를 내리는 방법을 layoutIfNeeded()와 contenSize.height와 frame.height의 차이로 구현을 하였는데 다른 방법이 떠오르지 않는데 태태의 생각이 궁금합니다!
> 저도 구현을 한다면 이렇게 구현을 할 것 같습니다. 

- view.layoutIfNeeded() 를 100%이해하고 사용하지 못했습니다. View를 즉각 업데이트하는 함수라는 것은 알고 있었지만, 이 코드를 삽입하는 위치에 대해서 이해가 잘 되지않습니다.. 크기가 재조정되고 난후에 호출이 되어도 동일하게 스크롤뷰가 확장되어야한다고 생각하는데 직접해본결과 그렇지 않았습니다.

> 직접 해보신 결과 뷰가 확장이 되지 않았다고 하셨는데, 스크롤이 내려가지 않아서 확장이 되지 않았다고 판단하신걸까요? 어느부분에서 호출하셨는지 궁금합니다.
```
//view.layoutIfNeeded()
let contentOffsetValue: CGFloat = historyScrollView.contentSize.height - historyScrollView.frame.height
historyScrollView.setContentOffset(CGPoint(x: 0, y: contentOffsetValue), animated: true)
view.layoutIfNeeded()
```
만약 이렇게 호출하신거라면, 어떠한 차이가 있었는지 한번 생각해보시면 좋을 것 같습니다.
`layoutIfNeeded()`는 즉시 뷰를 업데이트 해주는부분을 알고 계시니 한번 더 고민해보시고 이해가 어려우시다면 DM으로 말씀해주세요 😊

관련하여 View LifeCycle 과View/ 레이아웃 업데이트 관련하여 문서도 한번 보시면 좋을 것 같습니다 !

2022-09-30 05:45 UTC, uuu1101 commented on Calculator/Calculator/Common/Constant/Constant.swift
> +    static let dot = "."
Name space를 Struct로 만드셨네요. 
외부에서 인스턴스 생성을 막기위해 private init()을 두신것 같은데 `enum`을 사용하지 않고 이렇게 작성하신 이유가 궁급합니다.

2022-09-30 05:45 UTC, uuu1101 commented on Calculator/Calculator/Controllers/ViewController.swift
> +    @IBOutlet weak var mainResultLabel: UILabel!
네이밍에 main을 포함하신 이유가 있으실까요?
main을 제외한 다른 `OperatorLabel`이나, `ResultLable`이 존재하나요?

2022-09-30 05:45 UTC, uuu1101 commented on Calculator/Calculator/Controllers/ViewController.swift
> +    @IBOutlet weak var historyStackView: UIStackView!
`@IBOutlet` 가 사용되는 프로퍼티들은 왜 강제옵셔널을 사용할까요?
우리가 알기로는 강제옵셔널 사용은 지양하라고 하잖아요!?

2022-09-30 05:45 UTC, uuu1101 commented on Calculator/Calculator/Controllers/ViewController.swift
> +    private func setUILabel() {
`set` , `setup`, `configure` 의 차이를 알고 계시면 추후에 네이밍 할때 도움이 되실것 같습니다 !

2022-09-30 05:45 UTC, uuu1101 commented on Calculator/Calculator/Controllers/ViewController.swift
> +    private func setClearCalculateHistory() {
`clearHistory` , `clearCalculateHistory` 는 어떨까요?
`그리고 코드에서 계산 내역을 History라고 표현을 해서 PR에서도 History라고 표현하겠습니다!` 라고 하셨듯이 History의 의미가 명확하다고 느껴져서요 :)

2022-09-30 05:45 UTC, uuu1101 commented on Calculator/Calculator/Controllers/ViewController.swift
> +
해당부분은 개행을 하신 이유가 있으실까요?

2022-09-30 05:45 UTC, uuu1101 commented on Calculator/Calculator/Controllers/ViewController.swift
> +
해당부분도 동일합니다.

2022-09-30 06:25 UTC, KyoPak commented on Calculator/Calculator/Common/Constant/Constant.swift
> +    static let dot = "."
해당 부분은 전 프로젝트에서는 enum을 사용했었습니다. 
그때 enum으로 하게 된다면 `private init { }` 설정이 불필요하고 이름을 통일성있게 관리가 가능하기 때문에 enum 타입을 했었는데요. 이번 프로젝트에서 괜히 한번 struct로도  관리를 해보고 싶어서 사용했습니다.. 수정이 맞는것같아서 수정했습니다..!🤣

2022-09-30 06:31 UTC, KyoPak commented on Calculator/Calculator/Controllers/ViewController.swift
> +
return이 포함되어 있는 Line들은 되도록 줄 개행을 했었는데 이 부분은 오히려 개행을 해서 이상하네요..!
return 위에 많은 Line들이 있을 때는 줄 개행을 하고 짧을경우는 안하는 방향으로 정하겠습니다 !

2022-09-30 06:31 UTC, KyoPak commented on Calculator/Calculator/Controllers/ViewController.swift
> +
위와 같습니다!

2022-09-30 06:47 UTC, KyoPak commented on Calculator/Calculator/Controllers/ViewController.swift
> +    @IBOutlet weak var mainResultLabel: UILabel!
main을 빼니깐 더 간결해진것같습니다! 
따라서 추가로 `updateMainResultLabel()` ➡️ `updateResultLabel()` 로 변경하였습니다 :)

2022-09-30 06:54 UTC, KyoPak commented on Calculator/Calculator/Controllers/ViewController.swift
> +    private func setClearCalculateHistory() {
해당부분을 생각해보니 setting개념보다는 단순 기능 동작이기 때문에 태태말대로  set을 빼는게 맞다고 판단되어
`clearCalculateHistory()`로 변경하였습니다!

2022-09-30 14:08 UTC, KyoPak commented on Calculator/Calculator/Controllers/ViewController.swift
> +    @IBOutlet weak var historyStackView: UIStackView!
일단 @IBOutlet의 정의를 알아보았습니다. 
정의는 IBOutlet 키워드를 이용하여 nib 또는 Storyboard에서 뷰를 설정할 수 있는 프로퍼티였습니다!
또한 IBOutlet은 InterfaceBuilder과 스토리보드를 연결을 해주는데, 이 때 선언한 IBOutlet이 nil인건 선언한 View가 nil이라는 것이고 명백한 에러를 발생시키기 위해서 강제옵셔널 처리를 한 것같습니다..!
태태의 생각이 궁금합니다!

2022-10-03 03:33 UTC, uuu1101 commented
디스코드 통해서 `layoutIfNeeded()` 관련하여 설명드렸습니다 :)

2022-10-03 03:33 UTC, merged