계산기 [ Step 2 ] Jeremy
yagom-academy/ios-calculator-app pull request #368
Opened 2022-09-29 02:25 UTC by yjjem

---
### 🍠 안녕하세요! 🙌
---
@leejun6694
안녕하세여 쿠마 🍠
드디어... STEP 2 완료하여 PR드립니다.
이번 리뷰도 잘 부탁드리겠습니다..

# 🛠 구현 내용
Formulat 의 result() 메소드가 호출되면 operands queue에서 바로 dequeue를 받아오게 됩니다(이는 불필요한 조건문을 피하기 위해 채택한 방법입니다), 이후 while문을 이용하여 operator head의 next값이 nil일 떄 까지 반복하여 변수 calculateResult에 값을 넣어주는 방식입니다.

```swift!
struct Formula {
    var operands: CalculatorItemQueue<Double> = .init()
    var operators: CalculatorItemQueue<Operator> = .init()
    
    mutating func result() throws -> Double? {
        guard let firstOperand = operands.dequeue() else { return nil }
        var calculateResult: Double = firstOperand
        
        while operators.head?.next != nil {
            guard let operation = operators.dequeue(), 
                  let rhs = operands.dequeue() else { return nil }
            calculateResult = try operation.calculate(lhs: firstOperand, 
                                                      rhs: rhs)
        }
        
        return calculateResult
    }
}

```
| <center> # 1 - Formula result() 메소드 작동 시각화 (구현과 상이할 수 있습니다..) |
| -------- |
| <center> <img src="https://user-images.githubusercontent.com/88357373/192834641-d50a08ee-439e-4030-a96c-41e055da7805.gif" width="500px"/>|

# 🫠 고민한 점
    
### 1. CalculatorItemQueue 

Unit Test를 해보기 전까지 동작하지 않는다는 것을 눈치채지 못하고 있었습니다. 사실 잘 생각해보면 당연한 것 이었습니다.
Linked List라는 것이 Link가 있어야 하는데 제가 하고있던 것은 그저 next와 tail에 서로 다른 새로운 Node를 넣어주는 것 이었습니다. 
```swift!
// before
mutating func enqueue(data: Element) {
        if head != nil {
            tail?.next = Node(value: data)
            tail = Node(value: data)
        } else {
            head = Node(value: data)
            tail = Node(value: data)
        }
    }
    
// after
mutating func enqueue(data: Element) {
        if head != nil {
            tail?.next = Node(value: data)
            tail = tail?.next
        } else {
            head = Node(value: data)
            tail = head
        }
    }
    
// CalculateItemQueue init
    init(head: Node<Element>? = nil) {
        self.head = head
        self.tail = head
    }
```
위의 after의 예제와 같이 tail이 tail.next를 참조하도록 변경하여 linked list 구현에 성공하였습니다.
CalculatorItemQueue 의 init에서 head = head, tail = head 라고 참조하도록 해서 첫번쨰 노드에 따로 head.next를 지정하지 않아도 된다는 것을 이해했습니다. 
    
### 2. UML
이번 스탭 진행하면서 제일 어렵게 느껴진게 바로 UML에 따라 코드를 작성하는 것 이었습니다. 사실 익숙해지면 괜찮지만 미래를 추측하지 않고 구현하는 일은 처음에 쉽게 와닿진 않았습니다. 최말단 부터 UML대로 구현하게 되면 체계적이면서 먼 미래를 생각할 필요 없이 요구되는 것들만 구현하면 되기에 현재에만 집중할 수 있었습니다. UML 구현에 대한 감을 어느정도 잡은 것 같습니다.
    
### 3. String extension split 메소드
초기에는 입력값들을 어떻게 분리해야 좋을지 많이 고민을 했습니다. 
예를 들어보자면, 입력값 "1.0+12.3+3.14-5.0"을 while문으로 item이 operator가 아니라면 반복해서 한 변수에 저장하여 operator가 나오면 다시 append 하는 정말 쓸모없는 고민들을 했습니다. 이번 스탭이 오래걸린 이유 중 하나입니다..

사실 간단하게 User Interaction을 받을 떄 /2.2/+2 와 같이 항상 "/"가 붙게 구현하면 해당 기호? 를 기준으로 split하고 return type이 subsequence array인 것만 map으로 잡아주면 해결되는 문제였습니다.
    
```swift
extension String: CalculateItem {
    
    func split(with target: Character) -> [String] {
        return self.split(separator: "/").map{ String($0) }
    }
}
```
### 4. zero division Error
아래와 같이 0을 나누려고 하면 `divisionError`를 throw하는 방식으로 구현했습니다. 제가 고민한 것은 바로 이것을 어디서 핸들링 하느냐 입니다. 결론부터 말씀드리자면 추후에 viewController 내부에서 핸들링 할 생각으로 모든 연관된 함수에 throw를 붙여주어야만 했습니다. 
    
지나가던 선배기수분이 Result type라는 것이 있다는 힌트를 던져주고 가셨는데 해당 기능을 사용하게 된다면 에러가 없더라고 값을 기능을 통해 값을 전달해야하는 번거러움이 있고 따로 부가적으로 switch문을 구현해야하는 것 같아서 일단 사용하지는 않았습니다.
    
```swift
    func divide(lhs: Double, rhs: Double) throws -> Double {
        if rhs == 0 {
            return 0
        } else if lhs == 0 {
            throw CalculateError.divisionError
        }
        return lhs / rhs
    }
```

# 🌝 궁금한 점
- 쿠마는 Result type을 자주 사용하시는지, 그리고 핸들링 방식으로는 do catch 와 result type 중 무엇을 더 선호하시는지 궁금합니다.

### 🫠 마치면서..
 너무 큰그림을 그리면서 체계없이 구현하는 것에 익숙해져 있었던 것 같습니다. 그래서 더 UML구현이 처음에는 이해되지 않았던 것이라고 생각도 됩니다. UML 을 통한 구현을 몸소 느낄 수 있는 step 이라는 생각이 드네요..

2022-09-29 13:52 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
>      var head: Node<Element>?
`head` 와 `tail` 은 외부에 노출되어도 괜찮을까요?

2022-09-29 13:53 UTC, leejun6694 commented on Calculator/Calculator/Extensions/String +.swift
> +
불필요한 줄바꿈이 있습니다.

2022-09-29 13:55 UTC, leejun6694 commented on Calculator/Calculator/Formula.swift
> +        while operators.head?.next != nil {
while 과 함께 optional binding 도 처리하면 어떨까요?

2022-09-29 13:56 UTC, leejun6694 commented on Calculator/Calculator/Formula.swift
> +            calculateResult = try operation.calculate(lhs: firstOperand, rhs: rhs)
`lhs` 가 `firstOperand` 맞을까요..?

2022-09-29 13:56 UTC, leejun6694 commented on Calculator/Calculator/Operator.swift
> +            return 0
여기가 에러 아닐까요...?

2022-09-29 13:57 UTC, leejun6694 commented on Calculator/CalculatorTesting/CalculatorTesting.swift
> +    //    }
불필요한 코드는 삭제해주세요.

2022-09-29 13:58 UTC, leejun6694 requested changes
Jeremy 안녕하세요 : )
step 2 구현하느라 고생 많으셨습니다.
구현에 실수가 조금 있으신 것 같아요..! 확인 부탁드립니다~!

2022-09-30 08:13 UTC, yjjem commented on Calculator/Calculator/Formula.swift
> +        while operators.head?.next != nil {
while let 을 잊고있었군요... 
2번 예시와 같이 사용하는 경우도 있나요?
```swift
// 1번 예시
while let _ = operators.head?.next  {
            guard let operation = operators.dequeue(), let rhs = operands.dequeue() else { return nil }
            calculateResult = try operation.calculate(lhs: firstOperand, rhs: rhs)
        }
// 2번 예시
while let head = operators.head, let _ = head.next  {
            guard let operation = operators.dequeue(), let rhs = operands.dequeue() else { return nil }
            calculateResult = try operation.calculate(lhs: firstOperand, rhs: rhs)
        }
```

2022-09-30 08:16 UTC, yjjem commented on Calculator/Calculator/Formula.swift
> +            calculateResult = try operation.calculate(lhs: firstOperand, rhs: rhs)
lhs가 calculateResult이어야 하는데 firstOperand를 넣어버렸군요..
수정했습니다..

2022-09-30 08:21 UTC, yjjem commented on Calculator/CalculatorTesting/CalculatorTesting.swift
> +    //    }
주석처리 해놓고 깜빡한 코드입니다.. 다시 풀었습니다! 감사합니다 🥲

2022-09-30 08:24 UTC, yjjem commented on Calculator/Calculator/Operator.swift
> +            return 0
왜 rhs를 0일 떄 0을 return 하게 만들었는지 잘 모르겠지만.. 아래와 같이 수정했습니다.
```swift
   func divide(lhs: Double, rhs: Double) throws -> Double {
        guard lhs != 0 else { throw CalculateError.divisionError }
        return lhs / rhs
    }
```

2022-09-30 09:19 UTC, yjjem commented on Calculator/Calculator/CalculatorItemQueue .swift
>      var head: Node<Element>?
메소드로 접근하는 것 이외에는 접근하지 못하도록 해야 하는데 실수했습니다!
private(set) 으로 지정해주어 UnitTest에서는 볼 수 있도록 해줬습니다.

```swift
private(set) var head: Node<Element>?
private(set) var tail: Node<Element>?
```
노드의 경우 final 을 지정해주어 바꾸지 못하게 설정했습니다. final은 이런식으로 절대로 바꾸거나 상속, extend 하지 못하도록 하고싶을때 사용하는 것이 맞는지 궁금합니다.
```swift
final class Node<Element: CalculateItem> { }
```

2022-10-02 15:17 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +final class Node<Element: CalculateItem> {
👍

2022-10-02 15:17 UTC, leejun6694 commented on Calculator/Calculator/CalculatorItemQueue .swift
> +    private(set) var head: Node<Element>?
private(set) 으로 설정한 이유가 있나요?

2022-10-02 15:18 UTC, leejun6694 commented on Calculator/Calculator/ExpressionParser.swift
> +        operators.forEach{
띄어쓰기..!

2022-10-02 15:19 UTC, leejun6694 commented on Calculator/Calculator/ExpressionParser.swift
> +            guard let operatorItem = Operator(rawValue: Character($0)) else { return }
forEach 가 아닌 filter 와 같은 고차함수로 이어나갈 순 없을까요?

2022-10-02 15:20 UTC, leejun6694 commented on Calculator/Calculator/Formula.swift
> +        while let _ = operators.head?.next  {
이것은 필요한 조건일까요?

2022-10-02 15:22 UTC, leejun6694 approved these changes
피드백을 잘 반영해주셨지만, 같이 얘기 나눠야할 포인트들이 좀 더 있네요ㅎㅎ
시간 맞춰서 고민점이랑 같이 얘기해봐요~

2022-10-02 15:22 UTC, merged