계산기 [STEP3] 제이푸시
yagom-academy/ios-calculator-app pull request #370
Opened 2022-09-29 10:32 UTC by jjpush

안녕하세요 알라딘! @junbangg 
STEP3 PR을 보냅니다!

# 🛠 기능 설명
## accessibilityIdentifier
UITest에서 사용하는 accessibilityIdentifier를 저장해두는 열거체 입니다.
- calculatorDisplayLabel
- operatorDisplayLabel
- calculatorArchive

## nameSpace
숫자들의 상태 네임스페이스를 저장해두는 열거체 입니다.
- zero
- negative
- empty
- nan

## StackViewCell
- stackView
- operatorLabel
- operandLabel
- generateStackView()
    - 스택뷰에 레이블을 넣고 반환해주는 메서드 입니다.

## ExpressionParser
- Int에서 Double로 교체

## ViewController

### IBOutlet
- calculatorDisplayLabel
- operatorDisplayLabel
- calculatorArchive
- scrollView

### IBAction
- numberButtonTapped()

1~9의 버튼을 눌렀을 때 실행하는 메서드 입니다.

- zeroButtonTapped()

0, 00 버튼을 눌렀을 때 실행하는 메서드 입니다.

- dotButtonTapped()

. 버튼을 눌렀을 때 실행하는 메서드 입니다.

- operatorButtonTapped()

`+ - * /` 버튼을 눌렀을 때 실행하는 메서드 입니다.

- changeSignButtonTapped()

`+/-` 부호변환 버튼을 눌렀을 때 실행하는 메서드 입니다.

- clearEntryButtonTapped()

CE 버튼을 눌렀을 때 실행하는 메서드 입니다.

- allClearButtonTapped()

AC 버튼을 눌렀을 때 실행하는 메서드 입니다.

- calculateButtonTapped()

`=` 버튼을 눌렀을 때 실행하는 메서드 입니다.

### 변수
- displayLabelText

calculatorDisplayLabel 레이블에 값을 넣을 String 변수 입니다.

- formula

수식이 담길 String 변수 입니다.

### 메서드
- setAccessibilityIdentifier
각 UILabel에 accessibilityIdentifier를 설정해주는 메서드 입니다. 
UITest에서 요소를 찾을 때 Identifier를 통해서 찾기 위해서 만들었습니다.

- pushInFormula

수식에 값을 집어넣는 메서드 입니다.
수식이 비어있다면 operand만 넣고
비어있지 않다면 operator와 operand를 추가합니다.

- pushInArchive

calculatorArchive에 스택 뷰를 만들어서 넣어주는 메서드 입니다.

# 🤔 고민한 점
- UITest 

Test를 하면서 이번에는 UI기 때문에 UITest를 해보고 싶어서 열심히 찾아서 적용을 해보았습니다.
staticTexts[""]를 이용해서 적용해야 했는데 뷰의 텍스트로 적용을 해야해서 방법을 계속 찾아보다가 accessibilityIdentifier 를 찾게되었습니다.
그래서 accessibilityIdentifier enum을 만들고 추가해 주었습니다. 이후 staticTexts["id"]로 참조 했습니다.

- 자동 스크롤

스택 뷰에 뷰를 추가 했을 때 자동으로 가장 아래로 스크롤 할 수 있는 방법을 고민했습니다.
구글링한 결과 CGPoint를 잡아서 setContentOffset를 CGPoint로 잡아서 설정해 주었습니다

# 👿 해결되지 않은 점

애초에 띄어쓰기로 구분하지 않고 다 붙어있는 String으로 받아서 처리한게 문제가 되었던 것 같은데 값이 커져서 numberFormatter가 숫자를 1e+15이런식으로 표시할 경우 숫자를 제대로 받지 못하는 버그가 있었습니다.  

# 🙇‍♂️ 조언을 받고 싶은 점

프로그래밍을 하면서 재능이 정말 중요한가요
요즘들어 느껴지는 것 같네요...ㅠ

2022-09-30 15:34 UTC, junbangg requested changes
수고하셨어요!!
질문 내용은 디코에서 이야기 해보시죠~

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +            guard let textToDouble = Double(displayLabelText) else {
`textToDouble` 은 뭔가 변환을 하는 행위 같은 느낌이네요??  변환이 됐다는걸 표현할 수 있으면 좋겠네요!

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +    private(set) var formula: String = nameSpace.empty
이 친구는 혹시 왜 `private(set)` 으로 정하셨나요?

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +        calculatorArchive.accessibilityIdentifier = accessibilityIdentifier.calculatorArchive
적당히 줄바꿈 해주신거 센스 굳~

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
`title` 은 스트링인거겠죠?! `titleString`, `titleText` 는 어떠신지ㅎㅎ

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
위랑 같은 이야기~

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
위랑 같은 이야기~

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
타이틀이 많네 ㅋㅋ위랑 같은 이야기!

2022-09-30 15:34 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +        if self.formula.isEmpty {
요기서 `self` 를 쓰셨는데
위에 다른 프로퍼티들은 `self` 가 없네요! 이것만 `self` 를 해주신 이유가 있을까요?

2022-09-30 15:49 UTC, junbangg commented
그리고 `ViewController` 에서 사용하고 계신 대부분의 메서드들이 `private` 가 가능할것 같은데 처리를 안해주신것 같아요!

2022-10-01 11:01 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +            guard let textToDouble = Double(displayLabelText) else {
네이밍이 조금 안좋아보이네요 😭
`convertedTextToDouble` 로 변경 해보았습니다

2022-10-01 11:01 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +        calculatorArchive.accessibilityIdentifier = accessibilityIdentifier.calculatorArchive
🎉

2022-10-01 11:06 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
아하.. 조금 더 상세히 명시하도록 `titleText`로 수정했습니다!

2022-10-01 11:06 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
수정했습니다!

2022-10-01 11:06 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
수정했습니다!

2022-10-01 11:06 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +        guard let title = sender.currentTitle,
ㅎ.. 수정했습니다!

2022-10-01 11:09 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +        if self.formula.isEmpty {
클래스 전역변수를 사용할 때는 self를 붙여주는 것이 좋다고 생각했는데 다른 것들이 다 빠져있었네요 다른 프로퍼티들에 `self`를 붙여주었습니다!

2022-10-01 11:12 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.scrollView.setContentOffset(bottomOffset, animated: true)
기능분리를 깜빡했네요...! 메서드로 분리했습니다!

2022-10-01 11:18 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
> +    func allClearArchive() {
듣고보니 resetArchive가 훨씬 나아보이네요 수정했습니다
계산 히스토리가 저장되는 곳을 archive라고 생각해서 해당 스택뷰를 calculatorArchive로 네이밍 했었는데 그 저장소를 비운다는 생각을 했습니다.

2022-10-01 11:22 UTC, jjpush commented on Calculator/Calculator/Model/StackViewCell.swift
> +    func genarateStackView() -> UIStackView {
!!
감사합니다 수정했습니다

2022-10-01 11:23 UTC, jjpush commented on Calculator/Calculator/Model/accessibilityIdentifier.swift
> +enum accessibilityIdentifier {
대문자로 변경했습니다..!

2022-10-01 11:37 UTC, jjpush commented on Calculator/Calculator/Model/nameSpace.swift
> +enum nameSpace {
네임스페이스 또한 변수라고 생각해서 소문자를 사용했었습니다.

네임스페이스를 대문자로 사용해야 하는 이유는 무엇인가요? 🤔🤔🤔

한단어로 변경하고 대문자로 수정해 두었습니다!

2022-10-01 11:39 UTC, jjpush commented on Calculator/CalculatorTests/ExpressionParserTests.swift
>  final class ExpressionParserTests: XCTestCase {
final을 얼마전에 알게 되었는데 
Test 클래스가 상속되어 어떤 작업이 진행되면 안된다고 생각이 들어서 final을 적용해보았습니다

2022-10-01 11:39 UTC, jjpush commented on Calculator/Calculator/Controller/ViewController.swift
>  class ViewController: UIViewController {
그렇네요!! final 처리해 주었습니다

2022-10-05 13:57 UTC, junbangg approved these changes

2022-10-05 13:58 UTC, merged