계산기 [STEP 3] 미니
yagom-academy/ios-calculator-app pull request #372
Opened 2022-09-29 13:59 UTC by leegyoungmin

@havilog
하비 제가 다양한 방식을 시도하다가 병합을 잘못해서 27일짜 Commit 부터 보시면 될 것 같습니다 ㅜㅜ
깔끔하게 보실 부분만 하도록 했어야 하는데 죄송합니다 ㅜㅜ

### 고민했던 점
- 상태 저장
    - 계산기에서 계산을 하기 위해서 필요한 것은 숫자, 숫자에 새로운 의미를 부여하는 특수 문자, 연산자 이다.
    - 처음에는 위의 구분에 따른 값을 작성할 수 있는 지에 대한 상태를 저장하려고 생각하였습니다.
    - 하지만, 너무 많은 상태를 관리했어야 했고, 다양한 상태를 관리하지만 다양한 상태들이 유기적으로 한개의 값이 true일때, 두개의 값이 false가 되는 값이 되게 됩니다.
    - 위와 같은 상황에서는 어떤 상황에 값을 추가해줘야 하는지 모호해졌습니다.
    - 그래서 숫자를 입력하는 상황과 연산자를 입력하는 상황에서 반대의 값을 전체 식에 저장하는 로직으로 생각하게 되었습니다. 이때, 특수 문자에 대해서는 특수한 설정을 해줌으로써 값의 의미를 줄 수 있도록 하였습니다.
    - 이때, 숫자를 입력하는 상황에서는 연산자를 식에 추가하도록 하고, 연산자를 입력하는 상황에서는 숫자를 식에 추가하도록 하였습니다.

### 궁금한 점
- View
    - 하비가 말했었던 것 처럼 StackView에 대해서 뷰를 상속 받아서 커스텀 뷰를 생성할 수 있도록 하였습니다.
    - 하지만, 뷰를 생성하는 과정에서 스택 뷰 내부에서 커스텀한 라벨을 작성할 수 있도록 하였어야 했습니다.
    - UILabel을 확장해서 활용하는 것과 클래스를 구성하여서 뷰를 그리는 것에 대해서 고민하게 되었고, 두 가지 방법 중에서 각각 어떤 이점이 있는 지 궁금합니다.

- View 2
    - 스크롤 뷰를 구성하면서 궁금한 부분이 생겼습니다.
    - 스크롤 뷰는 content의 사이즈에 따라서 길이가 변하는 것으로 알고 있습니다. 저희 프로젝트 내에서 stackview 내부의 뷰를 추가하여 contentSize가 증가하고 있습니다.
    - 하지만, 마지막 아이템이 있는 위치로 scroll을 자동적으로 하려고 할때, layoutIfNeeded 메서드를 통해서 레이아웃을 다시 잡아 줄 수 있었어야 합니다. 그렇다면, 95a092e11109d74c93dc871886db57a213a83923 에서 처럼 다양한 뷰에서 뷰의 레이아웃을 잡지 못하여서 예상치 못한 움직임을 보일 수 있는 것인가요?
    - 이때, 어떤 것에 의해서 예상과 다르게 움직이기게 되는 지 어떻게 알 수 있습니까?

2022-09-30 02:41 UTC, havilog requested changes
스탭3 진행하시느라 고생하셨습니다 미니 :)

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var currentOperatorLabel: UILabel!
private은 필수입니다! ㅎㅎ

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Common/Constants.swift
> +        static let defaultOperatorLabelValue: String = ""
상수값인데 이 값이 어느 레이블에 들어갈지까지 여기서 안정해도 될거 같아요

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    private let defaultPointValue: String = Constant.Calculator.defaultPoint
상수를 잡고 왜 다시 이걸 뷰컨의 메모리에서 들고 있는걸까요?

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +        resetLabels()
약간 시그니처의 문제인데요,
view가 load됐을 때 reset한다가 알잘딱깔센으로 이해가 되긴 하는데요
보통은 initial state를 configure한 뒤에, 뭔가 리셋해야할 상황이 일어나면 resetState()가 불릴거 같아요.
그래서 초기값을 설정해주는 부분이랑 reset해주는 함수명이 분리되면 좋을거 같습니다 ㅎㅎ

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    }
요것도 정말 애매한 코멘트고 취향차이이긴 한데요 ,,,
함수로 최대한 쪼개는 건 정말 좋긴 한데,
한 줄의 변경사항은 때에 따라 그냥 함수 없이 써주는게 더 잘 읽힐수도 있을거 같아요 ㅎㅎ

예를 들어
```
func appendExpressionFromOperator() {
     mathExpression.append(selectedOperator)
}
```
요 함수는 `mathExpression.append(selectedOperator)` 이 문장을 그대로 한 번 더 wrapping한 느낌이 들어서요 ㅎㅎ

틀렸다는건 아니지만 함수를 쪼개는 명확한 기준이 있으면 좋을 것 같습니다!ㅎㅎ

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +        }
만약 다른 에러에 대한 처리를 안한다면,
요 구문은 지워지거나, `// no-op`과 같이 작성해주시면 좋을거 같아요!
동료 개발자가 실수한건지 의도한건지 파악할 수 있도록이요

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    func changeLabels(_ numbers: String, _ operators: String) {
여기서 wildcard로 파라미터를 숨긴다면,
이 함수를 처음 쓰는 개발자는 어떤 값을 어떻게 바꾸는지 파악하기 힘들거 같아요!

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/View/CalculatedRecordStackView.swift
> +        label.font = .preferredFont(forTextStyle: .title3)
font를 `.preferredFont`로 작성하신 이유가 있을까요?

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/View/CalculatedRecordStackView.swift
> +    }
요 init은 꼭 필요한 아이일까요?

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Common/Extensions/Charactor+.swift
> +}
만약 여러 뷰에서 공통적으로 사용되는 extension이 아닌,
특정 뷰에서 함수 역할을 하는 extension이라면 
해당 파일 내에서 private extension으로 작성할 수도 있을거 같아요

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +            convertDidCalculate()
요런 아이들이 하나의 함수로 묶여도 좋을 거같네요

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +        addChildStackView()
코드만 봤을 때 `childStackView`의 역할이 뭔지 파악하기 힘들거 같아요.
이름이 더 명시적이면 좋을거 같습니다!

2022-09-30 02:41 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +        }
여기서 return시키면 의도치 않은 동작이 일어날 확률도 있을거 같은데 혹시 고민해보셨을까요?

2022-09-30 12:29 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var currentOperatorLabel: UILabel!
더욱 신경쓰도록 하겠습니다!!
cd5d3eb65ec4403dda003057a467ab1775fc327b 여기서 수정하였습니다.

2022-09-30 12:32 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Common/Constants.swift
> +        static let defaultOperatorLabelValue: String = ""
상수 값에 대해서 더욱 자세한 의미를 내포하고자 하였는데 의미가 퇴색된 것 같습니다.
cd5d3eb65ec4403dda003057a467ab1775fc327b 이곳에서 수정하도록 하였습니다.

2022-09-30 12:34 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    private let defaultPointValue: String = Constant.Calculator.defaultPoint
상수값을 메서드 내에서 직접적으로 활용하게 되었을 때, 코드가 길어져서 가독성이 떨어진다고 생각하여서 선언을 해주었습니다.
하비가 말씀해주신 것처럼 메모리에 이미 올라가 있는 값을 다시 메모리에 올린다는 것을 관과한 것 같습니다.
cd5d3eb65ec4403dda003057a467ab1775fc327b 이곳에서 삭제할 수 있도록 하였습니다.

2022-09-30 12:39 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +        resetLabels()
초기화를 하는 것과 리셋을 하는 것에 의미를 섞어서 사용한 것 같다는 생각이 들었습니다.
초기화를 하는 메서드는 초기화를 하는 메서드로 구분할 수 있도록 함수를 구분 하였습니다.
be24f6f5cf9ad68e361c0de43e2fcb9f77b5d5ca 이곳에서 수정하였습니다.

2022-09-30 12:42 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    }
사용자의 입력에 대응하기 위해서 다양한 처리를 해야한다는 생각에 함수를 무분별하게 쪼개서 사용한 것 같습니다.
함수로 감싸지 않아도 의미를 알아 차릴 수 있는 부분 같은 경우는 로직 상에서 직접적으로 호출 할 수 잇도록 하였으며, 함수로 감싸지 않았을 때, 함수의 의미가 명확하지 않은 부분만 함수로 감싸서 활용할 수 있도록 수정하였습니다.
5f3d1b7622d7c6fb38ad80cb4cddc49911397765 이곳에서 수정하였습니다.

2022-09-30 12:46 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +    func changeLabels(_ numbers: String, _ operators: String) {
동시에 설정하는 경우가 적기 때문에 위의 메서드를 삭제하고, 각각 구분하여서 활용할 수 있도록 변경하였습니다.
 5f3d1b7622d7c6fb38ad80cb4cddc49911397765 이곳에서 수정하였습니다.

2022-09-30 12:48 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/View/CalculatedRecordStackView.swift
> +        label.font = .preferredFont(forTextStyle: .title3)
처음에는 storyboard 상에 나와 있는 뷰의 폰트 크기들 동일하게 하기 위해서 title3의 크기를 지정하기 위해서 해당 메서드를 사용하였지만, 지정하지 않아도 될 것 같다는 생각이 들어서 해당 부분 삭제하였습니다.
cd5d3eb65ec4403dda003057a467ab1775fc327b 이곳에서 삭제하였습니다.

2022-09-30 13:11 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/View/CalculatedRecordStackView.swift
> +    }
StackView에 있는 arrangedSubViews 파라미터를 가지는 생성자는 편의 생성자 이기 때문에 designed 생성자가 필요합니다. 이를 위해서 frame을 통해서 UIStackView 타입의 생성자를 재정의 해줘야 합니다.

2022-09-30 13:11 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Common/Extensions/Charactor+.swift
> +}
b58a9aed73d64581e64b99ded797c0206f24ed38 이곳에서 수정하였습니다.

2022-09-30 13:15 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +            convertDidCalculate()
위의 메서드들의 모음은 초기화가 되는 상태로 돌아가는 의미의 resetInitState의 함수로 묶어서 활용할 수 있도록 하였습니다.
dbc7c000ccc18f99cd2e160dfcd9bc62177497e5 여기서 수정하였습니다.

2022-09-30 13:17 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +        addChildStackView()
명시적으로 log뷰로 변경하였습니다.
5da0c565dce500b1898ee6dc91aca4126332c476

2022-09-30 13:19 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +        }
로직상 확인 된 바로는 숫자만 입력한 상황에서 발생하는 것으로 확인 했습니다.
이때에는 계산기를 처음 부터 다시 시작하도록 하였습니다.
be24f6f5cf9ad68e361c0de43e2fcb9f77b5d5ca 이곳에서 didTappedEqualButton에서 수정하였습니다.

2022-09-30 17:07 UTC, havilog approved these changes
수고하셨어요 미니 :)

2022-09-30 17:07 UTC, havilog commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +}
toggle()함수 Bool에 firstParty로 있을텐데 새로 구현하신 이유가 있나요?

2022-10-01 03:01 UTC, leegyoungmin commented on Calculator/Calculator/Sources/Calculator/Controller/CalculatorViewController.swift
> +}
swiftUI에서만 작동하는 함수로 알고 있었습니다 ㅜㅜ
다음 부터는 잘 알아보고 작성할 수 있도록 개선하겠습니당!

2022-10-01 06:38 UTC, merged