계산기 [Step 3] Ayaan
yagom-academy/ios-calculator-app pull request #373
Opened 2022-09-29 23:14 UTC by oneStar92

@junbangg 

안녕하세요, 알라딘🫡
오늘도 좋은 아침입니다!!
어떻게 하다보니 아침에 PR을 보내게 됐네요ㅋㅋㅋㅋㅋ
이번 Step도 잘 부탁드립니다!!👍
---
# Step 3: 계산기 UI 연동

## ✏️ TodoList

- [x] IBOutlet / IBAction의 활용
- [x] 스택뷰의 활용
- [x] 스크롤뷰의 활용

## ⭐️ 기능 

- `InitializationProtocol`: AC기능 구현을 위한 protocol입니다.
- `NumberLabel`
    - `append()`: 전달된 값을 바탕으로 `self.text`의 값을 변화 시킵니다.
    - `appendDecimalPoints()`: 소수점을 추가합니다.
    - `swapNumberSign()`: 숫자의 음수,양수 부호를 부여합니다.
- `OperatorButton`
    - `operatorSign`: ID를 활용하여서 알맞은 연산자를 반환합니다.
- `OperandButton`
    - `number`: ID를 활용하여서 알맞은 연산자를 반환합니다.
- `CommandButton`
    - `command`: ID를 활용하여서 `Command` Type을 init한 결과를 반환합니다.
- `FormulaStackView`: 수식을 StackView내부에 할당한 후 subView로 해당 StackView를 추가하는 수행합니다.
    - `appendFormula`: 숫자, 연산자 레이블을 전달받아 이를 바탕으로 수식을 스택뷰에 추가합니다.
- `CalculatorNumberFormatter`: SingleTon 패턴으로 NumberFormatter를 사용합니다.

## ⭐️ 트러블 슈팅

- `NumberFormatter`가 필요한 Type마다 생성해 준 후 알맞은 조건을 부여해야 코드가 중복되서 작성되는 일이 발생했습니다. 이러한 증상을 해결하고자 `NumberFormatter`를 소유한 `CalculatorNumberFormatter`을 정의해준 후 이를 싱글톤 패턴으로 사용하여 해당 문제를 해결했습니다.

- AC와 CE등 각종 초기화를 수행할때마다 해당 기능을 하는 메소드를 뷰마다 호출해야되는 현상이 발생했습니다. 이러한 중복된 코드를 해결하고자 초기화가 필요한 타입은 `InitializationProtocol`을 채택한 후 `Initialization()` 메소드를 정의했습니다. 이를 바탕으로 Main VC에서 해당 프로토콜을 채택한 타입을 Array로 저장하였고 `forEach`문을 사용해 간단하게 초기화를 하도록 했습니다.

- `NumberFormatter`를 사용하게되면 반환된 결과값은 ','를 포함한 값이였습니다. 이러한 현상으로 해당 문자열은 `Double`로 변환이 불가능하는 현상이 발생했습니다. 해당 현상으로 인해 계산이 안되고 입력하던 숫자가 갑자기 스스로 초기화 되는 등 많은 버그가 발생했으며 이를 해결하고자 고차함수 `filter()`를 사용해 ','을 제거한 후 필요한 역활을 수행하도록 했습니다.

## ⭐️ 질문 사항
- ScrollView의 스크롤 이동? 해결방법. 수식이 추가되면 해당 수식으로 스크롤이 내려가야 사용자가 화면을 봤을때 보다 편리하게 보일 것 같습니다. 하지만 해당을 구현하는 방법을 공식문서에서는 찾지 못했습니다... 우선 여러 블로그나 Stack over flow를 통해서 알게된 내용을 바탕으로 해당 기능을 구현하였는데요. 알라딘은 이러한 기능을 어떻게 구현하는지 아시나요? 혹시 다른 방법이 없는지 궁금합니다.
```swift=
extension UIScrollView {
    func moveToBottom() {
        layoutIfNeeded()
        let bottomOffset = CGPoint(x: 0, y: self.contentSize.height - self.bounds.size.height)
        setContentOffset(bottomOffset, animated: true)
    }
}
```

2022-09-30 08:15 UTC, oneStar92 commented
[d3db7f2](https://github.com/yagom-academy/ios-calculator-app/pull/373/commits/d3db7f2b27af26c1d4d92177e4db3a4f0bccd72c)
0.00001 으로 소수점 입력을 받고 싶은 경우 입력이 안되는 현상을 해결하여서
PR을 보낸후 추가적으로 push하였습니다.

2022-09-30 14:53 UTC, junbangg requested changes
수고하셨습니다!!
뷰/기능마다 타입으로 분리하려고 했던게 인상적이었습니다👏👏👏👏
댓글 참고해주세요!
질문해주신 부분은 ...저도 비슷하게 해왔기 때문에(물론 특별한 경우에는 좀 다를 수는 있겠지만 )ㅎㅎ
그리고 클론해서 확인해보니까 잘 동작하는것 같더라고요!

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Button/OperandButton.swift
> +class OperandButton: UIButton {
오..요 타입 간단히 설명 부탁드려도 될까요??

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
`IBOutlet` 도 private 처리하는게 어떨까요?!

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func initialization() {
제 개인적인 스타일이긴 하지만 private 메서드를은 `extension` 으로 따로 정리를 하는건 어떨까요??
`mark` 주석으로 표시를 해두셔서 뭔가 분리하고 싶어하시는 느낌이 들어서요:)

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func initialization() {
그리고 `initialization` 이라는 단어가..흠 저는 개인적으로 메서드는 웬만하면 동사면 좋을것 같다는 생각이에요!
어떻게 생각하시나요??

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Label/NumberLabel.swift
> +class NumberLabel: UILabel {
여기 뭔가 숨이 막히는 느낌이 드네요😅

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Label/NumberLabel.swift
> +    private var interger: String = "0" {
오타..!

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Label/NumberLabel.swift
> +    private func appendInterger(for numberOfString: String) {
`Integer` 오타있습니다!

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Label/OperatorLabel.swift
> +        self.text = nil
엇 메서드명은 `initialization` 인데 `nil` 처리를 하고 있네요??
차라리 `reset` 같은 이름이 더 적절해보이네요 !

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +//MARK: - CalculatorItemQueue
요 마크 주석은 필요할까요??🤔
바로 밑에 타입이 있긴한데..흠 
마크 주석 사용하고계신 이유?/의도? 가 어떻게 되는지 궁금합니다!

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/NumberFormatter/CalculatorNumberFormatter.swift
> +class CalculatorNumberFormatter {
요게 재사용성 때문에 싱글톤으로 만드셨다고 했는데
그냥 일반 클래스/구조체로도 충분히 재사용할 수 있지 않나요???
싱글톤으로 하신 이유가 궁금합니다:)

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/Protocol/InitializationProtocol.swift
> +protocol InitializationProtocol {
요거 정의하신 이유가 어떻게 되시나요?!

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/ScrollView/UIScrollView.swift
> +        setContentOffset(bottomOffset, animated: true)
이거 질문 주셨는데 저도 비슷하게 사용했/사용합니다!

2022-09-30 14:53 UTC, junbangg commented on Calculator/Calculator/StackView/FormulaStackView.swift
> +    func initialization() {
위에 이야기했던 네이밍 이슈 여기도 해당 됩니다!

2022-10-01 16:52 UTC, oneStar92 commented on Calculator/Calculator/Button/CommandButton.swift
> +}
앗.. 밤을새서 하느냐고 미쳐 신경쓰지 못한 부분들이 너무 많네요 ㅠㅠ

2022-10-01 16:52 UTC, oneStar92 commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
수정했습니다 ㅠㅠ

2022-10-01 16:53 UTC, oneStar92 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func initialization() {
> 제 개인적인 스타일이긴 하지만 private 메서드를은 `extension` 으로 따로 정리를 하는건 어떨까요?? `mark` 주석으로 표시를 해두셔서 뭔가 분리하고 싶어하시는 느낌이 들어서요:)

오!! 좋은 방법 같네요ㅎㅎ 한번 사용해 보겠습니다!

2022-10-01 16:54 UTC, oneStar92 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private func initialization() {
> 그리고 `initialization` 이라는 단어가..흠 저는 개인적으로 메서드는 웬만하면 동사면 좋을것 같다는 생각이에요! 어떻게 생각하시나요??

초기화를 표현해주고 싶은 욕구가 너무 강했던것 같네요.. `reset`을 왜 생각하지 못했을까요..

2022-10-01 16:54 UTC, oneStar92 commented on Calculator/Calculator/Label/NumberLabel.swift
> +    private var interger: String = "0" {
죄송합니다 ...

2022-10-01 16:54 UTC, oneStar92 commented on Calculator/Calculator/Label/NumberLabel.swift
> +    private func appendInterger(for numberOfString: String) {
죄송합니다 ...

2022-10-01 16:54 UTC, oneStar92 commented on Calculator/Calculator/Label/OperatorLabel.swift
> +        self.text = nil
좋은 의견 감사합니다! 수정하였습니다

2022-10-01 16:54 UTC, oneStar92 commented on Calculator/Calculator/StackView/FormulaStackView.swift
> +    func initialization() {
ㅠㅠ 수정하였습니다....

2022-10-01 17:00 UTC, oneStar92 commented on Calculator/Calculator/Button/OperandButton.swift
> +class OperandButton: UIButton {
버튼들은 사용할때 어떻게 사용할지 고민했습니다.
ID를 사용할지, title을 그냥 사용할지, tag를 사용할지 고민을 좀 많이했습니다.
tag는 아직 경험하지 못했지만 휴먼 오류등 여러 문제를 야기할 수 있다는 리뷰를 받은적이 있어서 사용에서 제외하였고요.
title도 마찬가지로 휴먼 오류를 발생시킬 수 있다고 생각해 사용에서 제외하였습니다.
ID를 사용해서 주어진 ID에 맞는 숫자를 부여하고 싶어서 UIButton을 상속받아서 숫자를 프로퍼티로 가지고있는 피연산자 버튼을 만들었습니다.
다른 버튼들도 위와 동일한 이유로 디자인 하였습니다.

2022-10-01 17:09 UTC, oneStar92 commented on Calculator/Calculator/Protocol/InitializationProtocol.swift
> +protocol InitializationProtocol {
초기화프로토콜이라는 개념으로 정의했습니다.
각 버튼에 따른 초기화를 해줘야 하는 View들이 존재합니다.
해당 View에 모든 초기화 메소드를 구현하다보니 이러한 초기화프로토콜로 정의해 놓고 해당 프로토콜을 채택하여 구현하게되면 해당 뷰는 초기화를 할수 있는지 없는지 여부를 알 수 있다고 생각했습니다.

2022-10-01 17:12 UTC, oneStar92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +//MARK: - CalculatorItemQueue
마크를 분리의 목적도 있지만 조금 길다고 느껴지는 코드의 경우 바로 이동할 수 있는 분기점을 만드는 용도로도 사용하다 보니 제일 위로 가고싶을때가 종종 있었습니다.. 그때마다 휠을 쓰는게 불편해서 MARK를 적는 버릇이 생긴 것 같네요... home키를 누르면 되는데 말이죠...ㅋㅋㅋㅋ 수정하였습니다.

2022-10-01 17:21 UTC, oneStar92 commented on Calculator/Calculator/Label/NumberLabel.swift
> +class NumberLabel: UILabel {
음... 저도 지금 보니 많이 숨이 막히네요...
사실 리뷰를 받은 후 많은 고민이 있었습니다.
NumberLabel이 너무 많은 일을 맡고있더라고요...
사실 숫자의 쉼표,부호,소수점 표시는 넘버포맷터가 해줘야 하는 역활이지 NumberLabel에서 해야되는 일은 아닌 것 같다는 느낌이 너무너무너무 들었습니다...
해당 부분을 다시 구현하려고 했는데 너무 많은 부분이 수정이 일어나고 대공사가 시작되는 느낌이 들어 다음으로 미뤄놨습니다...
현재 해당부분을 다시 수정하여 PR을 보내면 알라딘이 너무 햇갈릴 것 같고 다시 코드를 보시는 번거로움이 생길 것 같아 추후에 저 스스로 리팩토링을 하는 방향으로 방향을 잡았습니다.
NumberLabel은 Label의 역활만!
NumberFormatter는 숫자를 표현해주는 역활만!
이 부분을 이야기하시는 것 같네요...

2022-10-01 17:27 UTC, oneStar92 commented on Calculator/Calculator/NumberFormatter/CalculatorNumberFormatter.swift
> +class CalculatorNumberFormatter {
당시 싱글톤을 사용한 이유는
```swift
numberStyle = .decimal
roundingMode = .halfUp
usesSignificantDigits = true
maximumSignificantDigits = 20
```
numberFormatter를 사용할 때마다 위 코드를 통해서 설정을 해야되서 싱글톤을 사용했습니다.
위 내용도 생각해보니 NumberFormatter를 상속받은 후 생성자를 오버라이드서 생성자에서 위 코드를 적어주면 번거로운 일이 없었을 것 같습니다...
그래도 NumberFormatter를 싱글톤으로 사용해도 따로 생기는 이슈는 없을 것 같은데...
알라딘의 생각이 궁금하네요...

2022-10-05 14:01 UTC, junbangg approved these changes
👍👍

2022-10-05 14:01 UTC, merged