계산기 [Step 3] som
yagom-academy/ios-calculator-app pull request #378
Opened 2022-09-30 10:14 UTC by jsa0224

안녕하세요, 태태! (@uuu1101) 
Step 3 구현할 부분이 너무 많아서... 오래 걸렸습니다😂
그리고 원래 Step 3의 브렌치를 추가해서 거기에 커밋을 남겼어야 하는데, 제 멘탈 이슈로 Step 2에 계속 남겼더라고요... 커밋 메세지도 잘못 남긴 게 많습니다. 이 부분 양해 부탁드려요🙇‍♀️

# 📍고민한 부분
- **`NumberFormatter`의 사용**
이 부분은 소수점 자리를 어디까지 지정할 것인지, 정하는 부분입니다. 보통은 10자리, 20자리로도 지정을 하더라고요. 저는 공학 계산기보다는 일상에 쓰이는 계산기를 구현하기로 해서, 2자리까지만 지정했습니다. 
```swift
numberFormatter.maximumFractionDigits = 2
```

- **`StackView`의 구현**
고민한 부분은 아니지만, 개인적으로 어려운 부분이었습니다! 보통 뷰의 상세한 구현은 스토리 보드에서 하는 편이었는데, 코드로 구현하려고 하니 어떤 설정들이 있는 지 잘 몰라서 찾아보는데, 시간이 걸렸습니다. 

# 📍해결되지 않은 부분

|9999999를 계속 누르면 10...000으로 변함|음수 사칙연산의 오류|
|:------:|:------:|
|![](https://i.imgur.com/LXr51Gk.gif)|![](https://i.imgur.com/PNt2RxR.gif)|

왼쪽의 오류는 아마 **NumberFormatter**의 사용 여부 때문에 일어나는 오류 같은데, **iPhone**에서 지원하는 계산기 어플도 같은 기능을 하더라고요. 그래서 이걸 오류라고 봐야 하는 지, 애매해졌습니다.
오른쪽의 오류는 제가 리팩토링하면서 한 번 수정해보겠습니다! 

# 📍조언 받고 싶은 부분
- `CalculatorNameSpace`
`CalculatorNameSpace`이 `enum` 타입이다 보니 `.rawValue`를 통해 접근하다 보니, 코드가 길어지는 데, 다른 타입으로 구현할 방법이 있을까요?

- `고차함수`
최대한 조건문도 고차함수로 활용해보고 싶은데, 조건문의 코드 양이 길어지면, 조건문으로 구현하는 것이 좋을까요? 아니면 고차함수로 구현하는 것이 좋을까요?

2022-10-01 07:06 UTC, uuu1101 requested changes
안녕하세요 som(@jsa0224) ! 
STEP3 구현하시느라 고생많으셨습니다.
에러처리도 해보시고, 복잡한 부분이 많으셨을텐데 잘 구현하셨네요!

## 해결되지 않은 부분
- 999,999 에서 9를 한번 더 눌렀을때 왜 9,999,999 가 되지 않는가?
> 생각하신대로 답은 numberFormatter에 있습니다. 
`numberFormatter.usesSignificantDigits = true` 라고 작성하셨는데, 이 코드는 어떤 역할을 할까요?

> 해당 부분은 NumberFormatter의 [usesSignificantDigits](https://developer.apple.com/documentation/foundation/nsnumberformatter/1417793-usessignificantdigits)문서에 답이 있을것 같습니다. 
이 외에도 NumberFormatter 문서를 보시면 많은 정보들이 있으니 사용하실때 내가 사용하는 것이 어떤것인지 한번 확인해보는 것도 좋을 것 같습니다.

- 음수 연산에 대한 건 지금 연산하는 방법에 대해서 한번 더 검증을 해보시면 좋을 것 같습니다 :)

## 조언 받고 싶은 부분 
- `CalculatorNameSpace`이 `enum`타입이다 보니 `.rawValue`를 통해 접근하다 보니, 코드가 길어지는 데, 다른 타입으로 구현할 방법이 있을까요?
> rawValue 관련해서는 코멘트로 남겨두었습니다.
- 최대한 조건문도 고차함수로 활용해보고 싶은데, 조건문의 코드 양이 길어지면, 조건문으로 구현하는 것이 좋을까요? 아니면 고차함수로 구현하는 것이 좋을까요?
> 고차함수 사용 관련해서는 좋은 코드라는 건 잘 읽혀지는 코드이고 어떻게 로직이 이뤄지는지 알 수 있는 코드라고 생각합니다. 코드 정답이라는 것은 없지만, 결국 코드를 보는건 사람이니까요.
코드의 양이 길다고 안좋고 짧다고 좋은 코드라고는 할 수 없어요. 이 부분에 대해서는 고민을 해보시고 지금은 고차함수를 공부해보고 한번 사용해봤다 정도로 생각하시고, 앞으로 프로젝트를 하시면서 익숙해지시면 되는 부분이라고 생각해주시면 될 것 같아요. 😊

2022-10-02 03:43 UTC, jsa0224 commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet private weak var scrollView: UIScrollView!
강제 언래핑은 `nil`이 아니라는 것이 확실할 때만 사용하라고 배웠던 기억이 있습니다. `@IBOutlet`은 스토리보드의 뷰와 인터페이스 빌더를 연결해주는 역할을 합니다. 여기서 만약에 옵셔널 바인딩을 한다면, 사용자에게 연결이 되지 않았다는 오류를 보여줄 수 있는 점을 남긴다고 생각이 됩니다. 그래서 `@IBOutlet`으로 선언한 뷰가 `nil`이 될 여지를 남긴다면, 아예 사용을 권하지 않는다는 측면에서 강제 언래핑을 하는 거 같습니다.

2022-10-02 03:54 UTC, jsa0224 commented on Calculator/Calculator/Controller/ViewController.swift
> +                                expression: CalculatorNameSpace.emptyOperator.rawValue)
```swift
catch ValueError.emptyOperandsQueue {
       displaySignAndLabel(sign: CalculatorNameSpace.exclamationMark.rawValue,
                          expression: CalculatorNameSpace.emptyOperand.rawValue)
} catch ValueError.emptyOperatorsQueue {
       displaySignAndLabel(sign: CalculatorNameSpace.exclamationMark.rawValue,
                           expression: CalculatorNameSpace.emptyOperator.rawValue)
}
```
혹시 이 부분 말씀하시는 건가요?? `emptyOperandsQueue`와 `emptyOperatorsQueue`의 오류를 각각 캐치해주는 구문입니다. 태태가 보시기엔 어떤 점이 동일한 거 같으신가요? 다시 한 번 설명해주실 수 있으실까요?😥

2022-10-02 04:12 UTC, jsa0224 commented on Calculator/Calculator/Controller/ViewController.swift
> +        scrollView.layoutIfNeeded()
`layoutIfNeeded()`는 UI를 업데이트 하라는 queue의 뒤에 넣는 것이 아니라 맨 앞에 넣어 곧바로 UI가 변경되기를 기대할 수 있는 메서드라, 아래에서 위로 올라오는 애니메이션을 구현할 때 사용한다고 합니다. 저도 아직 개념을 명확하게 모르겠어서 [Draw Cycle](https://developer.apple.com/library/archive/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/GraphicsDrawingOverview/GraphicsDrawingOverview.html)을 공부해보려고 합니다! 해당 위치에 호출한 이유는, `autoSlideScrollView()`가 자동으로 스크롤을 내려주는 역할을 하기 때문입니다.

2022-10-02 04:28 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorNameSpace.swift
> +    case zero = "0"
타입 프로퍼티가 있었네요..! 개념만 잠깐 공부해보고 코드로 구현한 적이 없어서 생각도 못 한 거 같습니다... 타입 프로퍼티는 선언이 한 번 되었을 때, 메모리에 올라가면 그 뒤로는 생성되지 않으며, 어디서든 이 타입 프로퍼티에 접근할 수 있다는 장점을 가지고 있습니다. 타입 프로퍼티로 한 번 구현해보겠습니다!

2022-10-02 08:49 UTC, jsa0224 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var totalString: String = ""
넵 수정하도록 하겠습니다!

2022-10-02 09:04 UTC, jsa0224 commented
안녕하세요, 태태! 즐거운 일요일입니다...
태태가 말씀해주신 부분과 함께, 음수 연산이 안 되는 점도 같이 리팩토링했습니다!
음수 연산은 '-'가 연산자 '-'와 같은 기호를 사용하고 있어서, operator에 subtract이 들어가는 오류더라고요...😂

NumberFormatter 관련해서는 아직 제가 이해 못 한 부분도 있어 주말동안 더 공부하려고 합니다🤗
주말인데도 불구하고 리뷰 남겨주셔서 정말 감사합니다!!!

2022-10-03 03:36 UTC, uuu1101 commented on Calculator/Calculator/Controller/ViewController.swift
> +                                expression: CalculatorNameSpace.emptyOperator.rawValue)
아,, 이부분은 제가 헷갈린것 같습니다 😂😂😂

2022-10-03 03:37 UTC, uuu1101 commented on Calculator/Calculator/Controller/ViewController.swift
> +        scrollView.layoutIfNeeded()
해당 부분에 대해서 이해하는데 어려움이 있으시면, DM 부탁드립니다 :)

2022-10-03 15:46 UTC, merged