PR 계산기 [STEP 3] zhilly
yagom-academy/ios-calculator-app pull request #379
Opened 2022-09-30 11:20 UTC by zhilly11

안녕하세요 알라딘! @junbangg
STEP-3를 완료해서 PR 보냅니다
잘부탁드립니다🙇🏻

## UML
![](https://i.imgur.com/kyj8tKg.jpg)

<br>

## 🤔 고민했던점
### MVC 구조
MVC 구조를 최대한 지켜보고자 각각의 역할만 최대한 수행할 수 있도록 구현했습니다. 
- `MainViewController` : 
    - 최대한 보여지는 부분만 책임질 수 있도록 작성했습니다
    - 사용자에게 입력받은 값들은 `CalculatorController`로 보내서 처리합니다.
- `CalculatorController` :
    - 사용자에게 입력받은 값들을 처리해 `Formula`모델에 저장하는 역할을 합니다.
    - 사용자의 입력 컨트롤의 대부분을 담당합니다.
- `Formula` :
    - Controller에서 가공된 데이터들을 기반으로 비즈니스 로직을 수행합니다.
    - 수행한 값을 Controller에서 전달 받고 Controller는 View에 전달합니다. 

하지만 MVC 구조를 사용하니까 사용자에게 보여줄때만 NumberFormatter를 활용 할 수 있어서 오류가 나지 않고 구현 할 수 있었습니다. 기능분리의 장점이라고 생각합니다!
    
처음 MVC 패턴을 이용하여 작성하다 보니 Controller의 양이 방대해지고, View 와 Controller의 강결합이 되어있다고 생각이 되었습니다.

또한 시간이 조금 더 있었다면 `View`와 `Controller`를 Delegate를 이용해 사용할 수 있었을 것 같다는 생각이 들었습니다 😅 (아쉬운 점 ,,,)

### 

<br>

## ✏️ 조언을 얻고 싶은 부분
### Error Handlig
소스파일이 많아지고 방대해지다 보니 어디서 어떻게 에러처리를 해야할지 아이디어가 떠오르지 않았습니다.
계산이 안되는 값이면 `.nan` 처리를 해서 사용하긴 했는데 점점 방대해지는 프로젝트에 Error Handlig을 어떻게 하면 좋을까요?

### MVC
지금 소스는 View에서 입력받은 값들이 대부분 Controller에서 가지고 있다가 마지막에 연산버튼을 터치하면 그때 `ExpressionPaser`를 통해 `Formula`에 저장하고 `Model`에 있는 비즈니스 로직을 통해 연산 결과값을 가져와서 다시 `View`에게 전달하는데요.
지금 이러한 방식이 MVC패턴의 기본을 잘 지키고 있는지 조언을 얻고 싶습니다!

2022-09-30 16:12 UTC, junbangg requested changes
수고하셨습니다!!
아키텍쳐에 대해서도 고민하시고 적용을 하려고 하신 노력 아주 칭찬합니다~~

질문 내용 주신거 간단하게 이야기 드리자면
```
Error Handling
소스파일이 많아지고 방대해지다 보니 어디서 어떻게 에러처리를 해야할지 아이디어가 떠오르지 않았습니다.
계산이 안되는 값이면 .nan 처리를 해서 사용하긴 했는데 점점 방대해지는 프로젝트에 Error Handling을 어떻게 하면 좋을까요?
```
> 제가 제대로 이해를 못한것 같은데 소스파일이 많아지는거랑 에러 핸들링이랑 혹시 어떤 포인트에서 연관이 있는거죠?!!

```
MVC
지금 소스는 View에서 입력받은 값들이 대부분 Controller에서 가지고 있다가 마지막에 연산버튼을 터치하면 그때 ExpressionParser를 통해 Formula에 저장하고 Model에 있는 비즈니스 로직을 통해 연산 결과값을 가져와서 다시 View에게 전달하는데요.
지금 이러한 방식이 MVC패턴의 기본을 잘 지키고 있는지 조언을 얻고 싶습니다!
```
위에서 말씀하신것 처럼 `MVC` 아키텍쳐의 특징 중의 하나가 뷰컨이 방대해질 수 있다?는거죠~ㅎㅎ
맞습니다!그래서 그걸 분리 하시려고 노력을 하신것 같아요!

지금 뷰컨은 최대한 뷰만 담당하게 설계를 하셨다고 이야기를 해주셨는데..!(그래서 `사용자 입력을 컨트롤하는` 타입도 따로 만들어주신것 같아요??)

`MVC` 가 원래 `Model` `View` `Controller` 잖아요?
근데 두개를 합쳐버릴 수도 있대요! (애플말로는!)
그래서 놀랍게도 `ViewController` 라는 타입 자체가`MVC` 에서 `View` 와 `Controller` 레이어를 합친거랍니다..ㄷㄷㄷ 그래서 사실 다른 타입 없이 모델만 잘 만들어놔도 이미 `MVC` 를 잘 따르는거라고 볼 수 있을것 같아요! 만약에 비즈니스로직이 너무 방대해서 뷰컨이 정말정말정말 커진다면~~그걸 해결하기 위해 비즈니스 로직을 담당하는 타입을 따로 만들어서 분리킬 수도 있을것 같은데..! 그쯤되면 `MVC` 가 아닌 다른 아키텍쳐를 생각해볼만한 시점이 되는것 같습니다! 

나중에 `MVVM` 와 같은 다른 아키텍쳐에 대해서도 공부하게 되실텐데 그때 재미를 느끼실것 같네요:)
그리고 궁금하셨던 부분들도 많이 해소가 될것 같기도 하네요! 

일단 `MVC` 의 문제점을 느끼시고 그걸 스스로 해결하려고 했다는 점이 가장 중요한것 같네요 지금은!

추가적으로 이야기하고싶은 내용이 있다면 디엠 주세요~~

https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/MVC.html
한번 참고하셔 될것 같습니당

2022-10-01 04:58 UTC, zhilly11 commented on Calculator/Calculator/Controller/CalculatorController.swift
> +final class CalculatorController {
더 이상 해당 클래스에서 하위 클래스로 상속이 필요 없다고 생각해서 작성하긴 했습니다만, 조금 더 찾아보는 중에 `final`키워드로 선언된 요소들은 직접 호출하는 반면, 그렇지 않은 요소들은 간접 호출되어 `final`의 경우보다 느리게 작동한다고 하네요! 이런 이유에서 사용했습니다..!

2022-10-01 05:56 UTC, zhilly11 commented on Calculator/Calculator/Controller/CalculatorController.swift
> +    private var displaySign: Operator.RawValue = Operator.unknown.rawValue
`Character`로 표시하는 것 보다는 좀 더 의미를 담아보고자 `displaySign`의 type을 `Operator`로 수정했습니다!

2022-10-01 06:04 UTC, zhilly11 commented on Calculator/Calculator/Controller/CalculatorController.swift
> +    private func callbackCalculateResult() -> String {
`callback` 키워드 삭제했습니다!

```swift
if canCalculate == true {
            return calculateResult()
}
```

이런 식으로 사용할 수 있도록!

2022-10-01 06:07 UTC, zhilly11 commented on Calculator/Calculator/Controller/CalculatorController.swift
> +    private func isOverCount20(stringNumber: String, input: String?) -> Bool {
조금 더 직관적이도록 `isOverExpressionLimit`으로 수정했습니다~!

2022-10-01 06:09 UTC, zhilly11 commented on Calculator/Calculator/View/MainViewController.swift
>  class MainViewController: UIViewController {
`ViewController`도 `final` 키워드를 적용할 수 있군요..! 붙여줬습니다!

2022-10-01 06:10 UTC, zhilly11 commented on Calculator/Calculator/View/MainViewController.swift
> +    @IBOutlet weak var displayNumberLabel: UILabel!
이 친구들은 `CalculateController`에서 호출되는 친구들이라 `private` 처리하지 않았습니다!

2022-10-01 06:12 UTC, zhilly11 commented on Calculator/Calculator/View/MainViewController.swift
> +        }
처음에는 `configure` 기능으로 작성하다가 나중에 추가를 하다보니 `reset`기능에 더 가까워 졌네요..!
`resetDisplayLabels`로 수정했습니다~

2022-10-01 06:14 UTC, zhilly11 commented on Calculator/Calculator/View/MainViewController.swift
> +        self.numberFormatter.numberStyle = .decimal
맞네요..! 자료들을 참고하다 보며 쓰다보니 저렇게 작성 되었던 것 같습니다. `self`키워드 삭제했습니다!

2022-10-01 06:16 UTC, zhilly11 commented on Calculator/Calculator/View/MainViewController.swift
> +        guard let text = result,
이 부분은 제가 미쳐 발견하지 못했네요!..,, 항상 신경 쓰며 작성하곤 했는데,,😅

2022-10-01 06:20 UTC, zhilly11 commented on Calculator/Calculator/View/MainViewController.swift
> +    func resetDisplayNumberLabel() {
이 친구도 Controller에서 사용하는 친구라 붙여주지 않았습니다~

2022-10-01 06:26 UTC, zhilly11 commented
달아주신 코멘트들 조언들 잘 읽어보았습니다!👍
제 지식과 능력치가 점점 스택처럼 쌓이고 있는 것 같아요 ㅎㅎ
리뷰 감사합니다 알라딘🙇🏻

2022-10-05 13:55 UTC, junbangg commented on Calculator/Calculator/Controller/CalculatorController.swift
> +final class CalculatorController {
넵 맞아요 나중에 메서드 디스패치에대해 공부해보시면 이해에 도움이 될것 같습니당~~

2022-10-05 13:56 UTC, junbangg approved these changes
👍👍

2022-10-05 13:56 UTC, merged