계산기 [STEP 1] Charlotte, Marco
yagom-academy/ios-calculator-app pull request #38
Opened 2021-06-25 03:08 UTC by Keeplo

@wonhee009

@yaewonLee @keeplo

안녕하세요 라자냐! 🤠

이번에 리뷰를 부탁드리게된 말꼬와 샬롯입니다! 잘부탁드립니다~

Step1에서 중점적으로 구현한건 스택, 큐 구조와 중위 연산을 후위 연산으로 변환 하는 것,
후위 식을 연산해서 결과를 얻는 과정입니다.

## 고민되었던 점 🤯
* **종류가 다른 열거체 타입을 사용할때 생기는 빈 부분 처리**
한가지 열거체 타입으로 연산자와 피연산자를 다 담는 구현을 시도했는데, 
숫자일경우 사용하는 연산 프로퍼티나 연산자일때 사용하는 연산 프로퍼티, 메서드를 구현할때 
서로 다른 종류의 타입이 오는 경우 부분에 처리가 어려웠습니다. 
이 부분을 좀더 효율적으로 바꿀 방법으로 추천해 주실만한 게 있는지 궁금합니다.
~~~swift
// example
var extracted: Double { // 숫자 타입일때만 사용함
   switch self {
   case .number(let value):
      return value
   default:
      return -1
   }
}
~~~
* **함수가 엮이는 경우**
내부적으로 중위 연산을 후위 연산으로 변환하는 메서드나 연산자 간에 비교를 해서 스택을 처리하는 매서드등
결과를 얻는 매서드에 연관되어 내부에서 동작되는 경우가 많습니다.
그런 경우 분리해서 사용하는 게 좋을 지 지금처럼 하나의 과정이라 엮여도 되는지 궁금합니다
~~~swift
// 등호 누르고 결과 얻기 - 현재 코드
var infixQueue

makeCalculation() {
   var postfix = transformInfixToPostfix()
}
transformInfixToPostfix() -> Array {
   return postfix
}

// 등호 누르고 결과 얻기 - 현재 코드
var infixQueue
var postfix
makeCalculation() {
   infixQueue
   -> postfix
}
transformInfixToPostfix() {
   postfix
   -> result
}
~~~
* **발생가능성 없는 오류 대비 필요성**
스택 타입 내부에 구현된 배열은 비어있을때 removeFirst 메소드동작시 stackunderflow 에러가 발생합니다.
저희가 구현한 코드에서 당장 문제도 없고 버튼으로 접근해서 동작 중에 해당 에러가 발생할 가능성이 매우 낮은 데
미리 구현을 해야하는 지, 에러가 발생하면 처리하는 게 맞는 지 궁금합니다.
~~~swift
// 에러 처리 없는 pop()
struct Stack {
   mutating func pop() -> T {
        return stack.removeLast()
    }
}
~~~ 

## 피드백 받고 싶은 부분 😹
* **변수명, 함수명.....끝나지 않는 숙제**
함수면 동사, 변수나 상수는 명사 등등 시도해 보았는 데... 잘 부탁드립니다. 
calculate 와 관련된 용어가 너무 자주 사용되어서 아래와 같은 용어로 구분해보기도 했습니다. 
이런 부분도 피드백 받고 싶습니다.
operator 를 대체할 이름이 떠오르지 않았는 데, 키워드를 변수명으로 사용하는 점도 어떤지 궁금합니다.
~~~swift
// example 1
let computedNumber = dequeueElement.computeNumber(lhs.extracted, rhs.extracted)

// example 2
while let top = operatorStack.top,
              (top.priority == `operator`.priority) || (top.priority > `operator`.priority) {
}
~~~

2021-06-25 13:36 UTC, wonhee009 requested changes
샬럿, 말꼬 수고하셨습니다!
코드가 깔끔하다는 인상을 많이 받았습니다!

- **종류가 다른 열거체 타입을 사용할때 생기는 빈 부분 처리**

관련해서 리뷰에도 남겼지만 샬럿이랑 말꼬가 남겨주신 예시로 얘기해볼게요!
샬럿과 말꼬는 `default`일때 -1을 반환해주고 있네요!
사실상 -1이 반환되는 상황이라면 우리가 원하던 계산 결과에 영향을 미치게 되겠죠?
하지만 `extracted`를 사용하는 곳은 이미 `case number`라고 보장을 받아 `default`로 빠지지 않을거라고 생각해 -1을 반환하도록 작성했을거 같아요.

저는 이럴때 샬럿, 말꼬가 작성해준 `StackError`, `CalculateError`처럼 에러를 정의하고 `default`인 상황에서는 에러를 반환하도록 코드를 작성해줬었어요.
그랬던 이유는 -1을 반환하는 경우에는 결과값에만 영향을 주니 어느 부분에서 에러가 발생했는지 정확하게 알기 어렵기 때문였어요.
이 부분이 샬럿과 말꼬에게 하나의 답변이 될 수 있겠네요😀

- **함수가 엮이는 경우**

지금처럼 문제 없다고 생각합니다!

-**발생가능성 없는 오류 대비 필요성**

이 부분은 첫 번째 답변과 이어질거 같아요.
발생가능성 없는 오류여도 100% 보장할 수 있을까요?
예시로 샬럿과 말꼬가 정의해 둔 `Stack`을 Calculator가 아닌 새롭게 정의되는 class/struct에서 사용하게 될때에도 해당 오류가 100% 발생하지 않을 수 있을까요?
이 부분에 대해서 생각해보면 좋을거 같아요!

2021-06-25 13:36 UTC, wonhee009 commented on Calculator/Calculator/Model/Calculator.swift
> +extension Calculator {
`extension`에 정의한 함수와 아닌 함수는 어떤 기준으로 나눈걸까요?

2021-06-25 13:36 UTC, wonhee009 commented on Calculator/Calculator/Model/Calculator.swift
> +                                                _ postfix: inout Queue<ArithmeticSign>) {
`postfixQueue`라는 파라미터명은 어떤가요?

2021-06-25 13:36 UTC, wonhee009 commented on Calculator/Calculator/Model/Calculator.swift
> +                }
0으로 나눴을 경우에 대해서 처리를 했네요!
"NaN"을 반환하는 방식이 아닌 `ViewController`에 정의해둔 `CalculateError`를 활용해 볼 수 있을까요?

2021-06-28 05:27 UTC, yaewonLee commented on Calculator/Calculator/Controller/ViewController.swift
> +
Errors.swift 파일을 따로 생성하여 에러 타입들을 모아서 작성해보았습니다..!

2021-06-28 05:30 UTC, Keeplo commented on Calculator/Calculator/Model/ArithmeticSign.swift
> +    var extracted: Double {
enum의 case 내부에 저장했던 형태의 숫자를 꺼내온다고 생각해서 작성해보았습니다.
~~~swift
let five = ArithmeticSign.number(5)
let extractedNumber = five.extracted
~~~

2021-06-28 05:34 UTC, yaewonLee commented on Calculator/Calculator/Model/Stack.swift
> +}
리뷰 참고하여 사용하는 쪽으로 수정해보았습니다  👍🏻

2021-06-28 05:36 UTC, Keeplo commented on Calculator/Calculator/Model/Calculator.swift
> +struct Calculator {
화면 변환이 이루어지며 인스턴스를 참조하는 경우나, 상속관련된 기능을 사용하지 않아서 구조체로 구현해보았습니다.

2021-06-28 05:39 UTC, Keeplo commented on Calculator/Calculator/Model/Stack.swift
> +    }
스택구조에서는 stack underflow 에러가 발생합니다.

arr.removeLast() 같은 경우도 빈 배열에서 제거 동작을 해서 runtime Error가 발생합니다.

2021-06-28 05:39 UTC, yaewonLee commented on Calculator/Calculator/Model/Queue.swift
> +    }
Queue underflow가 발생합니다

2021-06-28 05:51 UTC, Keeplo commented on Calculator/Calculator/Model/Calculator.swift
> +                }
함수의 동작을 멈추고 처리되는 부분이라 return으로 처리했는데
라자냐 조언처럼 Error 처리를 하는게 좀 더 앱동작에 원할 할것 같습니다!

2021-06-28 05:52 UTC, yaewonLee commented on Calculator/Calculator/Model/Calculator.swift
> +extension Calculator {
extension에 정의한 프로퍼티와 메소드는 외부에서 접근이 가능한 함수들 입니다.

2021-06-30 23:14 UTC, wonhee009 reviewed
@yaewonLee @Keeplo 샬럿, 말꼬 리뷰 남겨두었으니 확인하시고 다음 스텝에 해당 사항들 적용해주세요!🙏
이 부분 적용 완료 후 DM 주시면 스텝2 리뷰할게요!
수고하셨서요 😀

2021-06-30 23:14 UTC, wonhee009 commented on Calculator/Calculator/Model/Calculator.swift
> +                guard let castedLhs = lhs as? Operand else { throw ArithmeticError.downCastingError }
`guard let` 구문에서 else 별로 다른 Error를 throw하기 위해 `guard let ` 구문이 4개로 반복되고 있는거 같아요. 이 부분 같은 Error끼리는 구문을 합칠 수 있을거 같아요.

2021-06-30 23:14 UTC, wonhee009 commented on Calculator/Calculator/Model/Arithmetic.swift
> +}
Operand의 value 값은 한 번 정해지면 수정될 일도 없고 상속을 사용하지 않는데 `class`로 정의한 이유가 있을까요?

2021-06-30 23:14 UTC, wonhee009 commented on Calculator/Calculator/Model/Arithmetic.swift
> +}
이전에는 숫자와 연산자가 같은 type으로 묶여 있었다면 스텝1을 개선하면서 숫자/연산자를 다른 type으로 분리하고 이를 하나의 Stack/Queue에 담기 위해 protocol을 만들어서 채택하도록 한거 같아요🎉

2021-06-30 23:15 UTC, merged