계산기 [STEP 3] SummerCat
yagom-academy/ios-calculator-app pull request #380
Opened 2022-09-30 11:37 UTC by ttokin

@havilog 하비 기한이..지나버렸죠...
안 놀고 열심히 했는데...😭 앞으로도 더 열심히 할게요..

---

## 고민한 부분

### 1. `historyStackView`에 쌓인 stackView를 모두 지우는 방법

처음에는 `removeArrrangedSubviews(view:)` 메서드를 활용해 쌓여있는 stackView를 모두 날렸었는데, 이럴 경우 다음 입력값이 들어왔을 때 레이아웃 제약에 문제가 생겼습니다. `removeFromSuperview()` 메서드로 교체해주면서 문제가 해결되었는데, 두 메서드 간의 차이점이 무엇인지는 주말동안 열심히 공부해 보겠습니다..

**혹시 요거랑 관련된 내용을 공부하면서 같이 공부해보면 좋을 주제가 있다면 추천해주시면 감사하겠습니다!**

---

## 해결하지 못한 부분

### 1. `String`을 `Double`로 변환 시 값이 왜곡되는 현상

`20.3`과 같은 숫자의 경우, `ExpressionParser`에서 `Double.init`하는 순간 근사값인 `20.300000000000001`로 바뀌게 됩니다.. 이런 현상은 Swift의 Double이 부동소수점 타입이기 때문에 나타나는 것으로 이해했습니다. 이 값을 바로 잡아 주기 위해서는 원래의 수에 10^15를 곱해준 수를 round로 반올림 해준 뒤, 다시 10^15로 나눠서 원래의 값을 찾는 방법이 있다는 것을 알 수 있었습니다.
다만 `20.3 * 1,000,000,000,000,000`과 같이 뒤에 충분히 큰 수를 곱해주었을 때 결과값이 `20,300,000,000,000.001`이 아닌 `20,300,000,000,000`이라는 의도된 값이 도출되서 위의 로직은 반영하지 않았습니다.

2022-09-30 17:21 UTC, havilog requested changes
썸머캣 구현하느라 고생하셨어요 ㅎㅎ
주말에 조금 더 .. 고생하시면 곧 즐거운 방학이!!

2022-09-30 17:21 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    }
요론 한 줄 짜리 함수들은 오히려 depth가 더 깊어져서 읽기 힘들어질 수도 있어요!
함수로 쪼개는 명확한 기준이 있으면 좋을 것 같습니다 ㅎㅎ

2022-09-30 17:21 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +        }
그 때 건디 리뷰 때 말씀드린거 같은데 .. 
제 생각에는 키패드 눌렀을 때 함수를 재사용하시려고 이 함수를 작성하신거 같은데 함수내부에서 분기처리가 일어나면 .. 
함수로 쪼개는 의미가 없는거 같아요!
zero나 doubleZero같은 아이들은 @IBAction 함수를 쪼개는것도 좋아보여요

2022-09-30 17:21 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    }
요 함수는 재사용되지도 않고 있고, touchUpSymbolChangeButton 내부에서 여러 개의 함수를 실행하지 않는데 함수로 쪼개신 의미가 무엇일까요?

2022-09-30 17:21 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    }
LGTM 👍

2022-09-30 17:21 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +              let numberToAppend = currentNumberLabel.text else { return }
위에서 addToStackView()함수를 실행하고 여기서 조건을 만족시키지 못해 return된다면 어떻게 될지 생각해보셨을까요?

2022-09-30 17:21 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    private func updateOperatorLabel(_ operatorSign: String) {
전 보통 이런 함수라면 wildcard를 사용하지 않고 with라는 단어를 사용하는데,
요건 취향이니 참고용으로만 알아주세요 ㅎㅎ

2022-10-01 09:02 UTC, ttokin commented on Calculator/Calculator/Model/Extensions/UIScrollView+.swift
> +import Foundation
맞습니당... 아직 hierarchy가 머릿속에 다 안 들어와있어서 그런것 같아요. 정리해보겠습니다!

2022-10-01 09:18 UTC, ttokin commented on Calculator/Calculator/Model/Extensions/UIStackView+.swift
> +}
처음에 `UIStackView`에 구현되어 있는 `removeArrangedSubview(_ view: UIView)` 메서드의 형식을 참고해서 만들었던 함수라서 그랬습니다..!
그런데 지금 다시 보니까 굉장히 이상한 메서드네요... 파라미터로 받아온 스택뷰를 쓰지도 않는 ㅠㅠ
자신을 호출한 스택뷰의 서브뷰를 삭제하는 것이 더 잘 드러나도록 `self`를 사용해서 수정했습니다!

2022-10-01 11:17 UTC, ttokin commented on Calculator/Calculator/Model/LineStackView.swift
> +    init(operatorStr: String, operandStr: String) {
전반적으로 변수명 대충 지은 것들 리네임 해줄 때 놓친 것 같아요.. 심신미약... 수정했습니다! 죄송해요...

2022-10-01 11:21 UTC, ttokin commented on Calculator/Calculator/Model/Operator.swift
> +//  Created by SummerCat on 2022/09/24.
ㅇㅏ.....부끄럽네요....^^ 수정하는법 구글링해서 수정했어요....

2022-10-01 11:59 UTC, ttokin commented on Calculator/Calculator/Model/LineStackView.swift
> +    }
요고는 처음에 설계할 때 `init`에서 하게 될 지 몰랐을 때 혹시 필요할까? 싶어서 이름만 작성해 두었던 메서드예요. 검토하면서 삭제했어야 하는데 놓쳤네요....
전반적으로 이번에 검토를 제대로 못한 것 같아서 부끄럽습니다 ㅠㅠ

2022-10-01 13:49 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    }
`@IBAction`에도 `private`을 붙여야 하나..? 붙여도 잘 작동하나..? 를 고민해보니 그러려면 스토리보드와 뷰컨간의 관계?를 알아야 할 것 같더라고요. 이걸 알기 위해서는 또 `init(coder: )`에 관해 알아보면 된다고 해서 공부해보고 있는데, `init(coder: )`로 전달받은 객체(이 경우 스토리보드 객체?)를 가지고 인스턴스를 초기화하고, 현재 작성된 함수들 같은 경우 그 인스턴스 내에서만 작동하면 되는 함수니까 `private`로 선언해도 문제가 없다!라고 생각했어요.

2022-10-01 13:59 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    }
처음 작성할 때에는 `touchUpSymbolButton`에서 최종적으로 몇 개의 메서드를 호출하게 될 지 몰라서 우선 분리해서 작성했었는데요, 막상 작성하고 나니 호출할 메서드가 하나뿐이어서 이걸 합치는게 좋은지 아닌지 고민했어요. 갑자기 스치듯이 '버튼이랑 직접 연결된 메서드에 자세한 구현 내용이 들어가 있는 것을 바람직하다고 할 수 있나?'라는 의문이 생겼었어서 그대로 두었던 것 같아요.
수정 방안은 `changeSymbol` 메서드 내에 구현된 내용을 `touchUpSymbolButton` 안으로 옮기거나, `changeSymbol` 안에 `if-else`로 구현된 부분을 두 개의 메서드로 쪼개서 분기점을 `touchUpSymbolButton`에 구현해주는 방법 두 가지가 있을 것 같아요.

2022-10-01 14:04 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    private func updateOperatorLabel(_ operatorSign: String) {
Swift에 자체적으로 구현되어 있는 메서드들을 참고했을 때에도 `with`를 사용하는게 좋은 것 같아서 수정했습니다!
해당 함수 안에서 사용하고 있는 `replacingOccurrences(of: with: )`와의 일관성도 그렇고 `with`로 작성하는게 훨씬 좋아보이네요.

2022-10-01 14:10 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    private func addToStackView() {
매개변수도 없어서 메서드 이름을 보고 역할을 알기 어렵겠네요..
수식 한 줄을 추가하는 메서드라고 생각해서 `addSingleFormulaLineToStackView`라고 수정했습니다.

2022-10-01 14:29 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    }
요렇게 쪼개서 작성했던 의도는 저 세 가지 함수가 항상 같이 호출되는 것은 아니기 때문에 우선 나눠서 작성한 후 필요한 것들만 골라서 호출하려고 그랬던 것 같습니다. 그리고 메서드 이름을 통해서 쌩 코드로 들어가 있는 것보다 의미를 좀 더 빠르게/쉽게 파악할 수 있을 것 같기도 하고요..?
이런 한 줄 짜리 메서드를 만드는 것도 취향의 영역인지 지양해야 할 것인지 궁금해요.

2022-10-02 04:25 UTC, ttokin commented on Calculator/Calculator/Model/LineStackView.swift
> +    }
`UIView`에는 이니셜라이저가 `init(frame: CGRect)`, `init?(coder: NSCoder)` 이렇게 두 개가 구현되어 있는데, 이 중에서 `init(frame: CGRect)`는 코드로 뷰를 그릴 때 사용되는 이니셜라이저이고, `init?(coder: NSCoder)`는 스토리보드의 데이터로 뷰를 그릴 때 사용되는 이니셜라이저입니다.
이 `init?(coder: NSCoder)`는 `NSCoding` 프로토콜을 채택하고 있는 클래스에서 구현하도록 `NSCoding` 프로토콜에 정의되어 있는 이니셜라이저입니다([애플공식문서](https://developer.apple.com/documentation/foundation/nscoding/1416145-init)). 프로토콜 내에 정의된 이니셜라이저는 그 프로토콜을 채택하는 이니셜라이저에서 반드시 `required` 키워드를 붙여서 구현해야 하는데, `UIView`는 `NSCoding` 프로토콜을 채택하고 있기 때문에 요 이니셜라이저를 `required init`으로 구현해야 하는 거죠. 반면에 `init(frame: CGRect)`는 `NSCoding`에 정의된 이니셜라이저가 아니라 `UIView`에 정의된 이니셜라이저라서 `required init`이 아닌 것 같습니다.
코드로 뷰를 구현할 때에는 반드시 두 이니셜라이저 모두 넣어줘야 한다고 하는데 왜 사용하지도 않을 `init(coder: NSCoder)`까지 넣어줘야 하는지는 잘 모르겠어요..😢

2022-10-02 04:31 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +              let numberToAppend = currentNumberLabel.text else { return }
그런 일이 발생한다면 화면상의 수식은 한 줄 업데이트가 되겠지만 실제 계산되어야 하는 수식에는 계산될 내용이 추가가 안되는 상황이 발생할 것 같아요.
그런데 `addToStackView()`에도 동일한 조건을 포함한 guard-else-return이 있어서 이런 상황은 발생하지 않을 것 같은데 하비 생각은 어떠신가요??

2022-10-02 05:56 UTC, havilog commented on Calculator/Calculator/Model/LineStackView.swift
> +    }
좋습니다 또킨 ㅎㅎ 
사실 .. 저도 코드로 그릴 때 왜 이 아이가 필요한지까지 깊게 생각해본 적은 없는데요,
저는 앱이 크래시나는건 상당히 심각한 버그라고 생각하는 사람이어서
아마 fatalError가 찍힐 일은 없겠지만 혹시 모르니까 이 initializer안에서도 super.init을 불러주는 편이긴 합니다 ㅎㅎ

2022-10-02 05:57 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +    }
취향의 영역이라고 생각합니다! ㅎㅎ
그냥 그럴수도 있다 정도의 코멘트라고 생각해주시면 좋을거 같아요 :)

2022-10-02 06:04 UTC, havilog approved these changes
수고하셨어요 또킨맘

2022-10-02 06:04 UTC, havilog commented on Calculator/Calculator/View/CalculatorViewController.swift
> +              let numberToAppend = currentNumberLabel.text else { return }
addToStackView()에도 동일한 조건을 포함한 guard-else-return이 있다고 하셨는데,
그러면 중복된 상태검증이 두번 일어나는 걸수도 있을거 같네요 ㅎㅎ
사실 동작은 잘 일어날거 같은데요, 코드의 시그니쳐만 봤을 때에는 스택 뷰를 추가한 뒤에 텍스트가 없어서 return되면 빈 스택뷰가 추가될 수도 있는건가? 라는 생각이 들 수도 있을 거 같아요 ㅎㅎ

2022-10-03 08:42 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +              let formattedNumber = Formatter.toFormattedString(from: currentNumber) else { return }
이부분 어제 웨더에게 방법이 뭐가 있을지 여쭤봤었는데요, 제가 아직도 옵셔널이 익숙하지 않아서 모든 함수가 다 옵셔널이 아닌것을 인자로 받도록 함수를 만든 게 큰 원인 중 하나였네요....ㅎ_ㅎ;;;;
수정해보았습니다 [f579057](https://github.com/yagom-academy/ios-calculator-app/pull/380/commits/f5790579318cb6112cecec861c701b11c73c2a72)

2022-10-03 08:47 UTC, ttokin commented on Calculator/Calculator/View/CalculatorViewController.swift
> +        }
조금 리팩토링을 해 보았는데, 소수점이 포함된 경우와 아닌 경우로 나누는 게 가장 효율적?일 것 같았어요.
이 기준으로 나누면 0과 00을 입력받는 경우도 사실 별도로 분리할 필요는 없어 보이는데(넘버포매터를 활용할 경우 0이든 000이든 화면에 출력은 0으로 보이니까), 혹시 몰라서 0과 00은 분리해두었습니다..!
[f579057](https://github.com/yagom-academy/ios-calculator-app/pull/380/commits/f5790579318cb6112cecec861c701b11c73c2a72)

2022-10-03 10:31 UTC, merged