계산기 II [STEP 1] 준호, baem
yagom-academy/ios-calculator-app pull request #387
Opened 2022-10-04 06:04 UTC by junho15

@1Consumption

울라프 안녕하세요.
계산기II Step 1 에 맞게 리팩토링 보다는 서로의 코드를 설명해 주고 이해 한 다음, 코드를 병합하는 것에 목표를 두었습니다.
리팩토링은 Step 2에서 진행하도록 할 예정입니다.
감사합니다.

## 변경 사항 
* Operator
    * 열거형의 원시 값이 StoryBoard의 글자랑 같은 `준호` 코드를 사용했습니다.
* CalculatorItemQueue
    * 제너릭 사용과 더블스택이 더 효율적이라 생각해서 `준호` 코드를 사용했습니다.
* ExpressionParser
    * 연산자와 피연산자를 나누는 기능의 parse 메서드가 좀 더 가독성 있는 `baem` 코드를 사용했습니다.
* String+split
    * ExpressionParser 코드에 맞게 `baem` 코드를 사용했습니다.
* Formula 
    * 제네릭 타입을 활용한 CalculatorItemQueue를 사용하기 위해 `준호` 코드를 사용했습니다.
* ViewController(Calculator)
    * ViewController 구현은 둘의 코드가 크게 달랐습니다. 앞의 코드와의 연계성을 위해 `준호`코드를 사용했습니다.

## 코드 병합에 따른 오류 해결
* 수정된 ExpressionParser의 parse 메서드는 연산자와 피연산자 사이에 공백이 포함된 입력 값을 받아야 합니다.
* parse 메서드에 전달할 String 타입의 입력 값을 만들어주는 convertOperatorsOperandsToString 메서드에서 연산자와 피연산자 앞에 공백을 추가하도록 수정했습니다. b8d4a98
    ~~~swift
        mutating private func convertOperatorsOperandsToString() -> String {
            var result: String = ""
            operands.reverse()
            operators.reverse()
            while operands.isEmpty == false || operators.isEmpty == false {
                if let input: String = operands.popLast() {
                    // 앞에 공백 추가
                    result.append(" \(input)")
                }
                if let input: String = operators.popLast() {
                    // 앞에 공백 추가
                    result.append(" \(input)")
                }
            }
            return result
        }
    ~~~
* 마찬가지로 테스트 케이스도 연산자와 피연산자 사이에 공백을 입력하도록 수정했습니다. 2e24248
    ~~~swift
        func test_parse에_문자열11더하기2곱하기3을전달했을때_operands에11과2와3을_operators에더하기와곱하기를담은_Formula를반환하는가(){
            // given
            let input: String = "11 + 2 × 3"

        func test_parse에_문자열마이너스12빼기마이너스1더하기마이너스3을전달했을때_operands에마이너스12와마이너스1와마이너스3을_operators에빼기와더하기를담은_Formula를반환하는가() {
            // given
            let input: String = "−12 − −1 + -3"
    ~~~

* ExpressionParser를 병합하면서 불필요한 오류처리를 삭제했습니다. df4a4fc

    ~~~swift
    // 수정 전
            default:
                guard let double = Double.convertStringContainingCommaToDouble($0) else {
                    throw ExpressionParserError.canNotChangeDouble
                 
    // 수정 후
                default:
                    if let double = Double.convertStringContainingCommaToDouble($0) {
                        result.operands.enqueue(double)

        }
    ~~~
    
## 조언을 얻고 싶은 부분
* Calculator
    * ViewController에서 view와 직접 관련이 없는 기능은 Calculator 구조체를 만들어서 Calculator의 메서드를 호출하도록 했습니다. be2c87f
    * 지금 구현한 방향이 맞는 지 조언을 얻고 싶습니다.

2022-10-04 17:19 UTC, 1Consumption requested changes
안녕하세요 @junho15 @Dylan-yoon 
고생하셨습니다.

프로젝트 제약사항에 `커밋은 짝꿍과 번갈아가며 남깁니다.`가 있었는데, @junho15 혼자 커밋을 한 것처럼 보이네요. 또한 `한 모둠원의 코드 비율이 70%를 초과할 수 없습니다`라는 제약사항이 있는데, 대부분의 코드가 @junho15 에게서 온 듯합니다. 다음부터는 프로젝트 제약사항을 꼭 읽고 지켜주세요.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/37682858/193882070-3fd91028-eda1-455a-9606-84824e97857c.png">

-------------------
# 조언을 얻고 싶은 부분
ViewController에서 view와 직접 관련이 없는 기능은 Calculator 구조체를 만들어서 Calculator의 메서드를 호출하도록 했습니다.
> 잘 하셨습니다. View는 UI를 보여주고, 이벤트를 받는 역할만 한다는 점을 계속 신경써주세요.

2022-10-05 01:31 UTC, Dylan-yoon commented on Calculator/Calculator/Extensions/String+split.swift
> +        self.trimmingCharacters(in: [" "]).components(separatedBy: String(target))
이부분은 제 코드를 가져왔는데 return의 경우 한줄이니까 생략해도 되겠다 라고 생각을 했는데,
다른 코드들과의 통일성을위해 return을 붙였습니다.
또한 extention으로 메서드를 처음 만들어 보아서, 명시해주는게 좋다고 생각해서 self를 붙였습니다. https://github.com/yagom-academy/ios-calculator-app/pull/387/commits/0c4624dee9f80ffdf88b6d27b5f05859d8519162

2022-10-05 01:37 UTC, junho15 commented on Calculator/Calculator/Model/Calculator.swift
> +    static let negativeSymbol: String = "-"
연산자/피연산자의 기본값과 음수 기호를 상수로 지정해서 사용하고 싶었습니다.
static 없이 인스턴스의 프로퍼티로 사용하면 다른 인스턴스 프로퍼티에서 기본값으로 사용할 수 없어서 타입 프로퍼티를 사용했습니다.
이럴경우 타입 프로퍼티보다 네임스페이스를 사용하는 게 더 적절할까요?

2022-10-05 02:06 UTC, junho15 commented on Calculator/Calculator/Model/Calculator.swift
> +
428d214 에서 불필요한 공백을 제거했습니다.

2022-10-05 02:07 UTC, junho15 commented on Calculator/Calculator/Model/Calculator.swift
> +        }
428d214 에서 최종적으로 호출하는 쪽(viewController)에서 에러 처리를 하도록 수정했습니다.

2022-10-05 02:15 UTC, junho15 commented on Calculator/Calculator/Extensions/Double+convertStringContainingCommaToDouble.swift
> +    }
static 변수는 메모리 영역에 함수는 코드 영역에 올라가는걸로 알고있습니다. 
ExpressionParser 열거형의 parse 메서드와 Calculator 구조체의 applyFormat 메서드에서 사용하고 있습니다.
각 타입별로 메서드를 추가하는 것 보다 Double 타입의 extension에 한 번 선언해서 사용하는 게 적절하다고 생각했습니다.
혹시 더 좋은 방법이 있을까요?

2022-10-05 03:09 UTC, junho15 commented on Calculator/Calculator/Model/Calculator.swift
> +    }
702f028 에서 NumberFormatter를 만들어서 포맷된 문자열을 반환하는 applyNumberFormat 메서드를 추가해서 기능을 분리했습니다.

2022-10-05 08:54 UTC, junho15 commented on Calculator/Calculator/Model/Calculator.swift
> +    mutating func inputOperator(_ input: String) -> Bool {
94f26e9 에서 isEditingState 연산 프로퍼티를 Bool 타입으로 선언하고 사용하도록 수정했습니다.
전달할 매개변수가 없어서 Bool 타입을 반환하는 메소드 대신 연산 프로퍼티를 사용했습니다.

2022-10-05 13:59 UTC, 1Consumption commented on Calculator/Calculator/Extensions/String+split.swift
> +        self.trimmingCharacters(in: [" "]).components(separatedBy: String(target))
음 틀렸다는게 아닙니다. 이유가 있다면 안고쳐도 될거같은데요...

2022-10-05 14:01 UTC, 1Consumption commented on Calculator/Calculator/Model/Calculator.swift
> +    static let negativeSymbol: String = "-"
지금은 `Calculator` 내부에서만 사용하고 있지 않나요? 더더욱이 static일 이유가 없어보이고, internal일 이유도 없어보입니다.

2022-10-05 14:03 UTC, 1Consumption commented on Calculator/Calculator/Model/Calculator.swift
> +        }
에러를 print만 해서는 의미가 없습니다. 알러트를 띄우던 어떻게든 사용자에게 알려야해요. 다음 스텝에서 보완해주세요.

2022-10-05 14:12 UTC, 1Consumption commented on Calculator/Calculator/Extensions/Double+convertStringContainingCommaToDouble.swift
> +    }
static 변수가 code영역에 들어가나요?
저라면 이 extension에 들어간 로직을 따로 객체로 빼서 필요한 곳에서 들고 있을거 같아요.

2022-10-05 14:13 UTC, 1Consumption requested changes
코멘트를 확인해주세요.

2022-10-06 01:11 UTC, junho15 commented on Calculator/Calculator/Model/Calculator.swift
> +    static let negativeSymbol: String = "-"
[cf28d5f](https://github.com/yagom-academy/ios-calculator-app/pull/387/commits/cf28d5f118a54f61d461c026403ac3851d0cf312) 에서 static 상수를 private 인스턴스 상수로 변경했습니다. 이니셜라이저에서 기본값을 주도록 했습니다.

2022-10-06 01:14 UTC, Dylan-yoon commented on Calculator/Calculator/Model/Calculator.swift
> +        }
넵 감사합니다! 보완하도록 하겠습니다.

2022-10-06 02:24 UTC, merged