계산기 [STEP1] Soll, Hosinging, 산체스
yagom-academy/ios-calculator-app pull request #39
Opened 2021-06-28 03:22 UTC by sanches37

@leejun6694 

안녕하세요 쿠마! Step1 PR을 늦게나마 보냅니다.

### 고민했던 점, 궁금한 점

1. 프로토콜을 적용해보고 싶어서 굳이 Calculatable이라는 프로토콜을 선언하고, 피연산자끼리 계산을 하는 함수를 프로토콜의 요구사항으로 적어보았는데요. 프로토콜을 적용하지 않았다면 특정 타입의 익스텐션이나 계산과 관련한 클래스(예: class Calculatable)나 구조체(예: struct Calculatable) 또는  열거형 내 함수로 표현했을 것 같습니다. 쿠마라면 이런 부분들은 어떤 방식으로 작성을 했을지 궁금합니다. 

2. Result<>타입의 사용이 익숙치 못해서 Error프로토콜을 채용한 CalculatorError enum을 생성하고 throwing function을 통해서 중간 중간 발생할 수 있는 에러의 처리를 throw해줬습니다.
do 블록안에서 try를 사용을 하거나, Result {}안에서 try를 사용하거나 또는 do 블록 없이 try? 를 통해 throwing function을 호출 할 수 있는 것으로 알고 있었는데요. 작성을 하다보니 do 블록이 없이도 throwing function을 호출 가능한 경우가 있더라구요(?) 테스트로 실행할 때에는 문제가 없었어서.. try를 do블록이나 Result {}안에서 호출하지 않아도 문제가 되는 부분이 없을까 궁금했습니다.

3. SOLID 원칙 중에 단일책임 원칙을 공부하고 코드를 보니, Calculator 클래스가 두가지 기능을 하고 있었습니다. 1. 중위연산자 배열을 후위연산자 배열로 변환하는 기능, 2. 후위연산자를 계산하는 기능 두가지가 있더라구요. 이 둘을 분리하는 것이 좋을까요?

4. Any 타입 배열에 들어가는 Operator와 Double타입을 다운캐스팅하는 하는 과정에서 코드가 복잡해보여 이를 String으로 통일했습니다. 그런데 숫자이다 보니 String 타입으로 형변환하는 과정에서 정보 유실?이 발생하지 않을까요? 의견 부탁드립니다.

5. infixArray, stack, postfixArray 배열들의 타입을 프로토콜 타입으로 지정해서, 프로토콜을 채택한 클래스를 배열내에서 사용함으로써 Double,String 타입 관계 없이 배열에 넣으려고 생각은 했지만, 구현을 해보진 못했습니다. 지금 모든 배열 타입이 String을 받는 방식으로 구현했는데, 배열내에 프로토콜 타입을 받아서 구현하는 방법과 비교해서 어떤 장단점이 있을 지 궁금합니다. 

확인부탁드립니다. 감사합니다!

2021-06-29 08:42 UTC, leejun6694 requested changes
처음 접하는 자료 구조를 적절하게 구현하셨네요 💯 

1. 지금 작성해주신 것처럼 저도 protocol 을 적극 활용해봤을 것 같습니다ㅎㅎ 코멘트 남겨드린 부분도 확인 부탁드려요~!
2. 일부러 에러 케이스로 실행해보면 어떻게 되는지 확인해볼까요??
3. method 로만 구분되어도 될 것 같습니다 : )
4. 복잡하다고 판단했던 코드를 알 수 있을까요? + 타입 변환은 적절히 진행된다면, 문제 없을 것 같네요ㅎㅎ
5. 모든 타입을 String 으로 받는 방식으로 구현했을 때, 어떤 장단점이 있으셨나요!?

2021-06-29 08:42 UTC, leejun6694 commented on Calculator/Calculator/Calculator.swift
> +extension Calculator: Calculatable {
`Calculatable` 의 method 들은 `Calculator class` 뿐만 아니라, 다른 곳에서도 동일한 행동을 하는 method 들로 보입니다.
지금도 알맞게 구현해주셨지만 (💯 ), protocol method 중 일반적으로 똑같은 코드를 실행하는 method 는 어떻게 정의할 수 있을지 짚고 넘어가면 좋을 것 같네요 : )

2021-06-29 08:42 UTC, leejun6694 commented on Calculator/Calculator/Stack.swift
> +struct Stack<T> {
적절한 줄바꿈은 가독성에 도움이 됩니다. 참고해주세요~~!

2021-06-29 08:42 UTC, leejun6694 commented on Calculator/Calculator/Stack.swift
> +struct Stack<T> {
제네릭을 적절하게 사용해주셨네요 👍

2021-06-29 08:42 UTC, leejun6694 commented on Calculator/Calculator/Stack.swift
> +    mutating func push(element: T) {
push method 를 사용할 때, element 는 굳이 명시하지 않아도 될 것 같네요ㅎㅎ

2021-06-30 02:15 UTC, sanches37 commented on Calculator/Calculator/Calculatable.swift
> +    func add(_ firstNumber: Double, _ secondNumber: Double) -> Double
피드백 주신 내용을 바탕으로 firstOperand, secondOperand 로 변경했습니다. 괜찮을까요?

2021-06-30 02:22 UTC, sanches37 commented on Calculator/Calculator/Calculator.swift
> +    var priority: Int {
```swift
guard let currentOperator = try? checkOperator(item) else { throw CalculatorError.unknown }
guard let stackOperator = try? checkOperator(topOfStack) else { throw CalculatorError.unknown }
if stackOperator.priority >= currentOperator.priority {
```

converToPostfixNotation 함수 내에서 currentOperator 와 stackOperator 의 우선순위 비교를 위해 Operator enum 의 priority 프로포티에 접근할 수 밖에 없어서 접근제어자를 fileprivate 로 지정했습니다.

2021-06-30 02:23 UTC, sanches37 commented on Calculator/Calculator/Calculator.swift
> +    private var postfixArray = [String]()
```swift
private var infixNotation = [String]()
private var postfixNotation = [String]()
private var OperandAndOperatorStack = Stack<String>()
```
피드백 주신 내용을 바탕으로 위 코드처럼 변경해보았습니다. 괜찮을까요?

2021-06-30 02:29 UTC, sanches37 commented on Calculator/Calculator/Calculator.swift
> +            if let _ = Double(item) {
```swift
itemsLoop: for item in infixNotation {
            if item.toDouble() {
                postfixNotation.append(item)
                continue itemsLoop
            }
            if OperandAndOperatorStack.isEmpty {
                OperandAndOperatorStack.push(item)
                continue itemsLoop
            }
```
if 문 중첩을 피하기 위해서 구문이름표를 사용해봤습니다.

```swift
extension String {
    
    func toDouble() -> Bool {
        if let _ = Double(self) {
            return true
        }
        return false
    }
}
```
피드백 주신 내용대로 String 을 extension 으로 확장하여, String을 Double로 변경하는 메소드를 추가하였습니다.
힌트로 주신 내용이 이런 방식이 맞는지 궁금합니다.

2021-06-30 02:30 UTC, sanches37 commented on Calculator/Calculator/Calculator.swift
> +                    guard let topOfStack = stack.top else { return ["Error"] }
다른 부분과 같이 에러처리 하도록 수정하였습니다.

2021-06-30 02:31 UTC, sanches37 commented on Calculator/Calculator/Calculator.swift
> +        guard let `operator` = Operator(rawValue: input) else {
예약어를 사용하지 않고, acquiredOperator 로 변경했습니다.

2021-06-30 02:34 UTC, sanches37 commented on Calculator/Calculator/Calculator.swift
> +extension Calculator: Calculatable {
다른곳에서도 동일한 행동을 하는 method 라고 말씀하셨는데, calculatePostfix 함수 내부에서만 사용하고 있어서 다른곳에서도 동일한 행동을 한다는 표현이 어떤 의미인지 잘 모르겠습니다. 그리고 프로토콜 메서드 중에서 일반적으로 똑같은 코드를 실행하는 메소드를 정의한다는게 어떤 의미인지 모르겠습니다. 관련된 키워드를 알려주시면 수정할 수 있도록 하겠습니다.

2021-06-30 02:35 UTC, sanches37 commented on Calculator/Calculator/Stack.swift
> +struct Stack<T> {
공식스위프트 파일을 참고하여, 사용자 정의 타입에서 첫줄은 개행을 해주는 것으로 정의했습니다.

2021-06-30 02:37 UTC, sanches37 commented on Calculator/Calculator/Stack.swift
> +    mutating func push(element: T) {
말씀하신대로 element 를 명시하지 않기 위해 argumet label 을 와일드카드로 사용했습니다.

2021-06-30 03:06 UTC, sanches37 commented
2. 일부러 에러 케이스로 실행해보면 어떻게 되는지 확인해볼까요??
-> 각각의 케이스로 추가 테스트를 해보겠습니다.

4. 복잡하다고 판단했던 코드를 알 수 있을까요? + 타입 변환은 적절히 진행된다면, 문제 없을 것 같네요ㅎㅎ
```swift
func converToPosifixNotation(of originArray: Array<Any>) -> Array<Any> {
        for item in originArray {
            switch item {
            case _ as Double:
                postArray.append(item)
            case let someOperator as Operator:
                if stack.isEmpty {
                    stack.push(element: someOperator)
                    print(stack)
                } else {
                    guard let topOfStack = stack.top as? Operator else { return [1] }
                    
                    if topOfStack >= someOperator {
                        guard let topOfStack2 = stack.pop() as? Operator else { return [2] }
                        postArray.append(topOfStack2)
                        stack.push(element: someOperator)
                    } else {
                        stack.push(element: someOperator)
                    }
                }
```
-> 초기 코드일 때 형변환을 많이해서 복잡해 보였는데, 쿠마의 말씀을 들으니 형변환은 문제가 되지 않는다는 것을 알게 되었습니다.

5. 모든 타입을 String 으로 받는 방식으로 구현했을 때, 어떤 장단점이 있으셨나요!?
-> String 배열로 사용한 이유가 형변환을 많이해서라고 생각해서 사용하게 됐는데, String 배열로 사용하면서도 조건에 따라 타입 변경을 할 수 밖에 없었습니다. 어떤 기준으로 좀 더 좋은 코드일지를 판단할지 모르겠습니다.

시간내서 정성어린 피드백 해주셔서 정말 감사드립니다. 😄😙☺️

2021-07-01 07:18 UTC, leejun6694 approved these changes
step 2 p/r 에서 추가로 진행할 예정입니다.

2021-07-01 07:18 UTC, merged