계산기 II [STEP 2] 준호, baem
yagom-academy/ios-calculator-app pull request #401
Opened 2022-10-06 11:38 UTC by Dylan-yoon

@1Consumption 

울라프 안녕하세요.
어느덧 마지막 PR 입니다. 3주 동안 많이 배웠습니다.
감사합니다.

## 변경 사항 
* 에러를 Label에 표시
    * 에러를 사용자에게 알리기 위해 Label에 보여지도록 수정했습니다. 36b2226
    ~~~swift
        do {
            if let result: String = try calculator.inputEqual() {
                operandLabel.text = result
                operatorLabel.text = calculator.currentOperator
            }
        } catch CalculateError.dividedByZero {
            resetOperatorLabel()
            operandLabel.text = CalculateError.dividedByZero.localizedDescription
        } catch {
            operandLabel.text = error.localizedDescription
        }
    ~~~

* Converter 구조체 추가
    * Converter 구조체를 만들어서 Converter의 인스턴스 메서드로 기존 Double 타입의 static 메서드를 대체했습니다. fc1767f
    ~~~swift
        struct Converter {
            func convertStringContainingCommaToDouble(_ input: String) -> Double? {
                let numberFormatter: NumberFormatter = NumberFormatter()
                numberFormatter.numberStyle = .decimal
                numberFormatter.groupingSeparator = ","
                return numberFormatter.number(from: input)?.doubleValue
            }
        }
    ~~~
    
* 네이밍, 컨벤션 수정, 계산기에서 어색하거나 이상 동작 수정
    * 전체 코드를 보면서 가독성이 떨어지거나 적절하지 못 한 변수명, 상수명, 메서드명을 수정했습니다.
    * 줄바꿈 등 컨벤션을 통일되도록 수정했습니다.
    * 시뮬레이터에서 계산기를 직접 사용하면서 어색하거나 이상 동작을 찾아서 수정했습니다. 00566fd 812a352
    
## 조언을 얻고 싶은 부분

* 에러 처리를 하면서 하나의 에러만 있을 때, 추후 추가의 가능성을 열어 switch문을 사용해서 하는게 좋을지, 아니면 변수로 처리해버리는 것이 좋을지에 대해 조언을 얻고싶습니다.
```swift
enum CalculateError: Error {
    case dividedByZero
    
    var localizedDescription: String {
        switch self {
        case .dividedByZero:
            return 
        }
    }
}
```

* 리팩토링을 했는데 저희가 놓친 부분이나, 좀 더 개선할 수 있는 부분이 있을까요?

2022-10-06 16:36 UTC, 1Consumption requested changes
부족한 리뷰어를 만나 3주간 고생 많으셨습니다. @Dylan-yoon @junho15 
남은 캠프생활도 잘 보내시길 바라겠습니다.

리팩토링할 수 있는 부분이나 어색한 부분은 코멘트로 남겼어요.

---------------------------------
# 조언을 얻고 싶은 부분
에러 처리를 하면서 하나의 에러만 있을 때, 추후 추가의 가능성을 열어 switch문을 사용해서 하는게 좋을지, 아니면 변수로 처리해버리는 것이 좋을지에 대해 조언을 얻고싶습니다.
>  switch문을 사용하는게 맞아보여요. enum의 장점 중 하나는 case가 추가되면 컴파일러가 잡아주는 것 이라고 생각합니다. 그래서 추후에 case가 추가 되었을 때 컴파일러가 에러처리 부분을 잡아주기 때문에 switch문을 유지하는게 맞다고 생각합니다.

2022-10-06 16:36 UTC, 1Consumption commented on Calculator/Calculator/Model/Calculator.swift
> +        }
get을 생략해도 되는데 붙여준 이유가 있을까요?

2022-10-06 16:36 UTC, 1Consumption commented on Calculator/Calculator/Model/Converter.swift
> +    func convertStringContainingCommaToDouble(_ input: String) -> Double? {
어떤 Converter인지 이름에 추가되면 좋을거같아요.

2022-10-06 16:36 UTC, 1Consumption commented on Calculator/Calculator/Model/ExpressionParser.swift
>                  result.operators.enqueue(Operator.divide)
Operator enum을 rawValue로 init해서 비교하는게 더 깔끔해보입니다. 그리고 rawValue 타입이 Character인게 좀 이상하네요.

2022-10-06 16:36 UTC, 1Consumption commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return componentsByOperator(from: input).first == "-"
여기도 `-` 보다는 Operator enum으로 비교하면 좋겠습니다.

2022-10-06 16:36 UTC, 1Consumption commented on Calculator/Calculator/ViewController.swift
> +            operandLabel.text = error.localizedDescription
근데 오류를 나누는 의미가 있나요? 어차피 계산기에서 오류가 발생하면 `resetOperatorLabel()` 메소드를 호출할거 같은데요.

2022-10-07 06:01 UTC, Dylan-yoon commented on Calculator/Calculator/Model/Calculator.swift
> +        }
set 을 사용하지 않을 때 get을 생략 할 수 있다는 것은 알고있었습니다.
return 또한 생략이 가능한 것을 알고 있었지만, 
막상 코드를 짜면서 미처 생각하지 못했던것 같습니다.
[3652917](https://github.com/yagom-academy/ios-calculator-app/pull/401/commits/36529177e911bde64d521c640b393655b1cf4bbb)

2022-10-07 06:12 UTC, Dylan-yoon commented on Calculator/Calculator/Model/Converter.swift
> +    func convertStringContainingCommaToDouble(_ input: String) -> Double? {
Formatter를 사용하는 메서드를  가지고 있기 때문에  FormatConverter로 변경 했습니다! [811d1b9](https://github.com/yagom-academy/ios-calculator-app/pull/401/commits/811d1b9c3c66ce882c552bd3f562a07c0cf3417a)

2022-10-07 07:20 UTC, junho15 commented on Calculator/Calculator/ViewController.swift
> +            operandLabel.text = error.localizedDescription
* 0으로 나눴을 때는 "Nan"이 피연산자 label에 표시하고, 나머지 오류일 경우에는 해당 오류의 localizedDescription을 피연산자 label에 표시하려고 했습니다.
* 프로젝트 제약 조건의 예시 gif에서 0으로 나누기 오류가 발생했을 때 연산자를 비워주도록 동작해서 resetOperatorLabel() 메소드를 추가했습니다. 나머지 오류의 경우는 따로 제약 조건에 없어서 오류 내용을 label에 표시해서 사용자가 알 수 있도록 했습니다.
* 이번 프로젝트의 경우에는 나머지 오류 발생의 경우를 생략하는 것도 괜찮을까요?

2022-10-07 07:20 UTC, junho15 commented on Calculator/Calculator/ViewController.swift
> +            operandLabel.text = error.localizedDescription
* 0으로 나눴을 때는 "Nan"이 피연산자 label에 표시하고, 나머지 오류일 경우에는 해당 오류의 localizedDescription을 피연산자 label에 표시하려고 했습니다.
* 프로젝트 제약 조건의 예시 gif에서 0으로 나누기 오류가 발생했을 때 연산자를 비워주도록 동작해서 resetOperatorLabel() 메소드를 추가했습니다. 나머지 오류의 경우는 따로 제약 조건에 없어서 오류 내용을 label에 표시해서 사용자가 알 수 있도록 했습니다.
* 이번 프로젝트의 경우에는 나머지 오류 발생의 경우를 생략하는 것도 괜찮을까요?

2022-10-07 07:33 UTC, junho15 commented on Calculator/Calculator/Model/ExpressionParser.swift
>                  result.operators.enqueue(Operator.divide)
* UML에 rawValue 타입이 Character로 되어 있어서 타입을 바꾸지 않고 처리하는 방법을 고민했습니다.
* Operator.init(rawValue: Character($0)) 을 바로 사용하니 런타임 에러가 발생하여 Character 타입이 될 수 있는지 String의 count로 먼저 확인했습니다. 다른 방법이 있을까요?
~~~swift
        componentsByOperator(from: input).forEach {
            if $0.count == 1,
               let bindedOperator = Operator.init(rawValue: Character($0)) {
                switch bindedOperator {
                case .add:
                    result.operators.enqueue(Operator.add)
~~~

[cca9396](https://github.com/yagom-academy/ios-calculator-app/pull/401/commits/cca9396df89b7da7f9144f1f876c283650d3acff)

2022-10-07 07:34 UTC, junho15 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return componentsByOperator(from: input).first == "-"
[cca9396](https://github.com/yagom-academy/ios-calculator-app/pull/401/commits/cca9396df89b7da7f9144f1f876c283650d3acff) 에서 같이 수정했습니다.

2022-10-17 01:58 UTC, closed without merging