계산기 II [STEP 2] Gundy, zhilly
yagom-academy/ios-calculator-app pull request #403
Opened 2022-10-06 12:43 UTC by Gundy93

@uuu1101

안녕하세요 태태! 😃

이번 리뷰도 잘 부탁합니다 🙌

## 고민했던 점

### NumberFormatter의 부분 적용
기존에는 `0.`이나 `0.000`, `0.0100` 이런 숫자들이 키패드로 입력되지 않았었습니다.
그래서 고민하다가 정수, 점, 소수 부분 3가지로 나눠 적용하는 방식으로 진행했습니다.
하지만 또 이렇게 진행 하다보니 scroll view에 추가될 때 필요없는 부분들 까지 입력되는 문제가 생겼습니다. 그래서 `makeStackView()` 메서드에서 `NumberFormatter`를 통해 한 번 더 가공해서 값을 넣어줬습니다.

### UILabel을 싱글톤 패턴으로 사용할 수 있지 않을까?
`Controller`부분에서 view에 있는 label들을 직접 수정하는 부분이 있어서 싱글톤 패턴을 사용하면 `view`와 `controller`에서 같은 친구를 가지고 계속 가공을 하면 되는 것이 아닐까? 라는 생각에 리팩토링을 시작했습니다.

UILabel을 직접 싱글톤 클래스로 설정했을 때 안됨

결국 프로토콜을 이용해 `Controller`는 직접 `View`를 가지지 않고 `View`가 준수하고 있는 `MainViewControllerDelegate`프로토콜을 통해 `View`에 접근함 따라서 어쩌다보니 의존성 역전을 지키게 된 것 같습니다..

### 유닛 테스트를 통과하는 리팩토링
![](https://i.imgur.com/mWmOfR6.png)
유닛테스트를 통과할 수 있는 방향으로 리팩토링을 진행하였습니다.

## 조언을 구하고 싶은 부분

### View와 Controller에 대한 의존성 역전 방법
```swift=
//CalculatorView.swift
    private var calculatorController: CalculatorControllerProtocol!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        calculatorController = CalculatorController(view: self)
    }

```
현재 `Controller`는 `View`에 접근할때 `Protocol`만을 사용하여 접근하고 있어서 직접적으로 의존성을 가지지 않고 있지만, `View`는 `Controller`에 접근할 때 위에 코드의 6번째 줄처럼 직접적으로 `Controller`를 호출하고 있습니다. 해결할 좋은 방법이 있을까요?

### 리팩토링의 대상으로 삼으면 좋은 부분이 궁금합니다
현재 리팩토링을 한 것 중 매직 리터럴을 없애는 수정도 하였는데, 이런 식으로 매직 리터럴이 없는 코드로 리팩토링을 한다거나, 컨벤션을 통일하는 리팩토링을 한다거나 처럼 신경쓰면 좋은 리팩토링 대상이 대표적으로 무엇이 있을까요?

2022-10-07 15:10 UTC, uuu1101 requested changes
안녕하세요 ! @zhilly11 @Gundy93 👋🏻
STEP2 진행하시느라 고생하셨습니다.
몇가지 코멘트 남겨두었어요. 확인부탁드립니다.
### 조언이 필요한 부분 
**View와 Controller에 대한 의존성 역전 방법**
> 이 부분은 Init을 사용하거나 View 생성후에 set하는 추상화된 프로토콜을 인자로 받는 프로퍼티를 만들어 사용 할 수 있을것 같습니다.  

**리팩토링의 대상으로 삼으면 좋은 부분이 궁금합니다**
> 저의 경우에는 코드의 가독성을 우선순위로 두고 리팩토링을 진행합니다.
결국 사람이 코드를 보는 것이라 가독성이 중요하다고 생각하기 때문인데요.
여기서 가독성은 코드 컨벤션이 될 수도 있고 메서드 명이 될 수도 있고 프로퍼티 명이 될 수도 있겠네요.
그 후에는 코드의 depth가 깊어진 부분에 대해서 메서드로 빼거나, 하나의 뷰에 여러 뷰들이 하드코딩 되어 있다면, 이런 부분들도 각각의 뷰들로 빼어내는 작업을 합니다.

- 싱글톤 패턴을 적용하는 대상이 어떤 것인지 한번 알아보면 좋을 것 같습니다.

2022-10-07 15:10 UTC, uuu1101 commented on Calculator/Calculator/View/CalculatorView.swift
>      func makeStackView() {
메서드 명에서 make는 어떨때 사용하는게 좋을까요?
[API Design Guideline](https://www.swift.org/documentation/api-design-guidelines/#naming) 문서를 한번 보는것도 좋을것 같습니다.

2022-10-07 15:10 UTC, uuu1101 commented on Calculator/Calculator/View/CalculatorView.swift
> +        displayNumberLabel.text = String(Int.zero)
`Constant`에 같이 정의하지않고 이렇게 정의하신 이유가 궁금합니다

2022-10-07 15:14 UTC, uuu1101 commented on Calculator/Calculator/Model/Constants.swift
> +}
이렇게 상수를 따로 관리하는 부분 좋네요👏
특정한 View에서만 사용한다면 특정 View에서 가지고 있는 것도 좋은 방법일 때가 있다는 것도 알아두시면 좋을 것 같아요.😊

2022-10-11 06:33 UTC, zhilly11 commented on Calculator/Calculator/View/CalculatorView.swift
> +        displayNumberLabel.text = String(Int.zero)
굳이 따로 enum으로 빼지 않아도 바로 사용할 수 있고, 누가 봐도 한 번에 이해 가능한 친구들은 바로 사용했습니다.

2022-10-11 06:35 UTC, zhilly11 commented on Calculator/Calculator/View/CalculatorView.swift
>      func makeStackView() {
makeStackView 메서드는 Factory가 아니고 결과적으로 addArrangedSubview()를 목적으로 하기 때문에 addStackView로 메서드 명을 변경하였습니다.

2022-10-11 06:42 UTC, zhilly11 commented
> 이 부분은 Init을 사용하거나 View 생성후에 set하는 추상화된 프로토콜을 인자로 받는 프로퍼티를 만들어 사용 할 수 있을것 같습니다.

init을 override 하는 것이 쉽지 않고, 
두 번째 조언해 주신 방법은 이해가 잘 가지 않습니다...
지금 방법과 어떤 점이 다른지 이해가 잘 안가네요

혹시 예시를 조금 들어 주실 수 있을까요?

2022-10-17 01:58 UTC, closed without merging