계산기 [STEP 1] 릴라
yagom-academy/ios-calculator-app pull request #410
Opened 2023-01-25 04:36 UTC by juun97

## 계산기 [STEP 1] 릴라
@wongbingg
안녕하세요 웡빙 첫 피알 보냅니다! 잘 부탁드리겠습니다🙏🏻
혼자서 처음 진행하다 보니 실수한 부분이 많네요 😂...
밑에 양심고백 있습니다...🥺

## 고민했던점 🤨

### 1️⃣ dequeue의 로직
- Array에서 제공하는 메서드인 removeFirst를 통해 간단하게 구현을 할 수도 있었습니다. 하지만 removeFirst의 경우 첫 번째 요소를 삭제한 뒤 남은 요소들의 인덱스를 한 칸씩 당겨줘야하는 작업이 필요해 O(n) 의 시간복잡도를 가져 성능면에서 더 개선의 여지가 있을거라 생각했습니다.
- 그렇게 해서 생각한 로직이 firstIndex 변수를 만들어 삭제할때마다 Index를 제어해 firstIndex가 유효한 값이 있는 첫번 째 인덱스를 가르키도록 하는 것 이었습니다..
- dequeue 가 일어날 때 삭제된 요소에 nil을 할당하고 firstIndex를 1증가 시키게 되면 O(1)의 시간복잡도를 가지게 되어 더 개선된 성능을 가지게 됩니다.
- 물론 이 로직도 개선의 필요가 있습니다. 겉으로 보았을때 queue의 크기는 줄어든것 처럼 보일수도 있으나 실제로는 queue의 크기는 변하지 않고 nil이 할당 되있는 상태입니다. 

### 2️⃣ dequeue가 진행된 queue의 count 구하기
- 실제로 queue의 요소가 삭제된 것이 아닌 nil을 할당하는 것이었기에 array의 count를 사용하게 되면 nil을 포함한 count를 반환한다는 것을 Unit Test 를 통해 알게 되었습니다.
- queue에서 유효한 값이 있는 첫 번째 인덱스는 frontIndex가 보유하고 있었기에 endIndex 에서 frontIndex 를 빼주게 되면 실제 보유하고 있는 요소의 갯수가 나오게 됩니다.

## Class Diagram
<img width="700" alt="image" src=https://i.imgur.com/o0GTPSD.png>

## 조언이 필요한 부분 🙇🏻‍♂️ 
STEP1 요구사항에 아래와 같은 문구가 있습니다.
```
CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다
```
 

그래서 Queue의 인스턴스 생성시 CalclateItem 채택한 타입들은 요소로 받도록 구성해 보았습니다.
```swift
var instanceQueue: CalculatorItemQueue<CalculateItem>
```
이 경우 우리가 사용할 타입에 대해 CalculateItem 프로토콜을 채택을 해줘야 했기에 Extension 을 활용해 Int 에서 채택할 수 있게 구현을 했습니다.

여기서 궁금한 부분이 Extension 코드가 어디서 작성되어야 하는지 파일의 위치를 잡는게 애매했습니다!
- 1️⃣ Queue 를 정의하는 파일에서 해야하는지
- 2️⃣ CalculateItem 프로토콜을 구현한 파일에서 작성해야하는지

### 다음 STEP 부터 개선할 점 😭
매도 먼저 맞는게 낫다 싶어 먼저 양심고백 하겠습니다 웡빙...
- 1️⃣ **브랜치 나누기**
: 바로 코드작성을 시작해서 브랜치 나누는것도 세상 깜빡하고 메인브랜치에 작업했습니다...
- 2️⃣ **TDD 지키기**
: 마침 전날에 Queue를 TIL로 올리게 되어서 해당 코드를 복붙해와서 하나씩 Test 해가면서 코드를 완성시켜야하는 TDD 를 준수하지 못했습니다...
- 3️⃣ **커밋단위 나누기**
: 마참가지로 Queue 코드를 그대로 들고와서 바로 테스트케이스 까지 작성하다가 커밋 보내는걸 나중에 생각나서 한꺼번에 보냈습니다...

2023-01-25 11:37 UTC, wongbingg reviewed
안녕하세요 릴라~! 계산기 프로젝트 Step1 고생하셨습니다 ☺️

### ✅ 고민했던 점에 대하여
### 1️⃣ dequeue의 로직
>- Array에서 제공하는 메서드인 removeFirst를 통해 간단하게 구현을 할 수도 있었습니다. 하지만 removeFirst의 경우 첫 번째 요소를 삭제한 뒤 남은 요소들의 인덱스를 한 칸씩 당겨줘야하는 작업이 필요해 O(n) 의 시간복잡도를 가져 성능면에서 더 개선의 여지가 있을거라 생각했습니다.

좋은 고민을 해주셨네요~! 맞습니다 배열타입에서 제공하는 removeFirst() 메서드의 경우 O(n) 의 시간복잡도를 가지게 됩니다. 

>- 그렇게 해서 생각한 로직이 firstIndex 변수를 만들어 삭제할때마다 Index를 제어해 firstIndex가 유효한 값이 있는 첫번 째 인덱스를 가르키도록 하는 것 이었습니다..
>- dequeue 가 일어날 때 삭제된 요소에 nil을 할당하고 firstIndex를 1증가 시키게 되면 O(1)의 시간복잡도를 가지게 되어 더 개선된 성능을 가지게 됩니다.
>- 물론 이 로직도 개선의 필요가 있습니다. 겉으로 보았을때 queue의 크기는 줄어든것 처럼 보일수도 있으나 실제로는 queue의 크기는 변하지 않고 nil이 할당 되있는 상태입니다. 

배열을 구독하는 인덱스에 header 역할을 부여하려고 하셨네요 ~! 좋은 시도인 것 같아요 👍 




### 2️⃣ dequeue가 진행된 queue의 count 구하기
>- 실제로 queue의 요소가 삭제된 것이 아닌 nil을 할당하는 것이었기에 array의 count를 사용하게 되면 nil을 포함한 count를 반환한다는 것을 Unit Test 를 통해 알게 되었습니다.
>- queue에서 유효한 값이 있는 첫 번째 인덱스는 frontIndex가 보유하고 있었기에 endIndex 에서 frontIndex 를 빼주게 되면 실제 보유하고 있는 요소의 갯수가 나오게 됩니다.

해결방안을 찾으셨네요 ~! 다만, 많은 dequeue와 enqueue 가 일어났을 때, 모든 기록이 배열에 남아있어 결국 배열의 크기가 커질 수 있다는 문제점이 있겠네요🧐


## Class Diagram

클래스 다이어그램도 잘 작성해주셨네요~! 
다만, 현재 코드가 UML에 맞게 작성되었는지 확인해볼 필요가 있을 것 같아요, 또한 관계를 나타낸 화살표 두개가 같은 모양인데, 이 두 화살표가 같은 의미를 가지는 것인지는 조금 더 고민 해봐야할 것 같아요 🧐


## 조언이 필요한 부분 🙇🏻‍♂️ 
>여기서 궁금한 부분이 Extension 코드가 어디서 작성되어야 하는지 파일의 위치를 잡는게 애매했습니다!
>- 1️⃣ Queue 를 정의하는 파일에서 해야하는지
>- 2️⃣ CalculateItem 프로토콜을 구현한 파일에서 작성해야하는지

이 부분은 정답이 없기에 릴라가 사용한 방법으로 진행해도 좋을 것 같아요! 저 같은 경우 프로젝트 전반에 걸쳐 공용으로 사용되는 Extension인 경우 Int+Extension 이런 네이밍의 파일로 분리해주기도 합니다. 참고만 해주세요☺️

### 다음 STEP 부터 개선할 점 😭
>- 1️⃣ **브랜치 나누기**
: 바로 코드작성을 시작해서 브랜치 나누는것도 세상 깜빡하고 메인브랜치에 작업했습니다...

괜찮습니다 ㅎㅎ 벌써 브랜치를 나누어 진행 하시는군요! 다음 스텝부터 적용 해봐도 좋을 것 같아요

>- 2️⃣ **TDD 지키기**
: 마침 전날에 Queue를 TIL로 올리게 되어서 해당 코드를 복붙해와서 하나씩 Test 해가면서 코드를 완성시켜야하는 TDD 를 준수하지 못했습니다...

다음 스텝부터 생성할 객체들에 대해 TDD 를 적용 해보시면 좋을 것 같아요 👍

>- 3️⃣ **커밋단위 나누기**
: 마참가지로 Queue 코드를 그대로 들고와서 바로 테스트케이스 까지 작성하다가 커밋 보내는걸 나중에 생각나서 한꺼번에 보냈습니다...

커밋단위를 나누는 기준도 중요하다고 생각해요~! 이 부분도 다음스텝에서는 적용해보면 좋을 것 같아요🧐

2023-01-25 12:13 UTC, wongbingg requested changes

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculateItem.swift
> +}
요구사항에 맞게 빈 프로토콜을 구현을 해주셨네요 👍

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +
이 곳에 개행이 3번 되어있는데 이 부분은 릴라의 컨벤션 인가요~?

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
UML 상에서는 count 와 isEmpty 가 메서드로 표시가 되어있던 것 같은데 실제 구현은 계산 프로퍼티로  되어있네요 🧐

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
mutating 키워드는 무엇을 의미하나요? 🧐

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
접근제어자를 public으로 선언해주신 이유가 있을까요 ?

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
- 어트리뷰트 discardableResult 는 어떤 의미인가요 ?

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
큐 내부를 빈 배열로 초기화하는 메서드를 잘 작성 해주셨네요 👍

2023-01-25 12:13 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
큐의 맨 앞의 요소를 반환해주는 peek() 메서드를 잘 구현 해주셨네요 👍

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
재정의 메서드에는 보통 super 를 통해 부모 메서드를 호출 해주는 경우가 많은데요, 어떤 이유로 부모 메서드를 호출 해줄까요?

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    //MARK: - isEmpty 메서드 테스트 케이스
메서드명 만으로 어떤 테스트를 하는지 알 수 있게 네이밍을 잘 해주셔서 이렇게 마크주석을 달아주지 않아도 될 것 같아요 👍

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
- isEmpty 에 대한 테스트가 잘 수행되었네요 👍
- 테스트 시작 시, clear() 메서드를 호출해주시는 이유가 있을까요?

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
setupWithError() 메서드와 tearDownWithError() 메서드는 어떤 역할을 할까요 ?

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
- peek() 메서드에 대한 테스트를 잘 해주셨네요 👍
- sut.peek() 을 해준 뒤, 타입캐스팅을 통해 Int 타입으로 변환을 시켜주고 있는 것이 어색한 것 같아요.  
- 어떻게 하면 바로 Int 타입을 반환하게 해줄 수 있을까요?

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
- enqueue() 메서드 테스트가 잘 이루어졌네요 👍

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
size 메서드를 테스트하는 것이 아닌, count 프로퍼티를 테스트 하고 있는 것 같아요 🧐

2023-01-25 12:13 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
dequeue 를 실행한 후에 첫번째 요소가 삭제 되었는지 확인하는 테스트가 아닌 것 같아요🧐

2023-01-25 14:34 UTC, juun97 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
- struct 에서는 원래 메서드로 프로퍼티를 수정하는것이 불가능합니다! 
- 하지만 mutating 키워드를 사용하게 되면 내부메서드에서도 프로퍼티의 값을 수정할 수 있게 해줍니다! 
- 그래서 mutating 키워드를 사용하게 됐습니다 :)

2023-01-25 14:35 UTC, juun97 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +
앗 미쳐 확인하지 못한 부분이었습니다! 수정해두겠습니다

2023-01-25 14:36 UTC, juun97 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
반환타입이 있는 메서드를 사용할 때는 변수를 생성해서 담아주지 않으면 경고메세지를 주게 됩니다! 이 때 `discardableResult` 를 사용하게 되면 변수에 담지 않고 메서드만 실행을 해도 경고메세지가 뜨지 않습니다!

2023-01-25 14:38 UTC, juun97 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
테스트를 실행할 때마다 새로운 queue인스턴스가 생성되기에  queue 에 값이 없지만 값이 없다는 조건을 명시적으로 보여주고 싶었기 때문에 clear() 메서드를 호출했습니다!

2023-01-26 06:51 UTC, juun97 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
앗 처음에 혼동해서 네이밍을 잘못했습니다! 
```swift
test_count는_queue요소의_갯수를_get_한다()
```
로 네이밍 변경했습니다

2023-01-26 06:56 UTC, juun97 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
UML 작성시기에 해당부분을 혼동 했었네요,,,! ㅜㅜ UML 수정하겠습니다!
접근제어자 부분은 테스트를 진행하기 위해 임시로 public 을 뒀습니다!  이 부분은 internal 로 수정하는게 더 어울리려나요!?

2023-01-26 14:21 UTC, juun97 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
부모메서드를 기반으로 추가적인 기능을 작성하려 하기 때문에 부모메서드를 호출하는것 같습니다!
setupWithError 는 테스트 케이스를 시작하기전 호출되는 메서드이고 tearDownWithError 는 테스트 케이스가 끝날 때 마다 호출 되는 메서드 입니다!

2023-01-26 15:35 UTC, juun97 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
```swift
func test_peek을_실행할때_queue의_첫번째요소가_반환된다() {
        //given
        let firstElement = 1
        let secondElement = 2
        let thirdElement = 3
        //when
        sut?.enqueue(firstElement)
        sut?.enqueue(secondElement)
        sut?.enqueue(thirdElement)

        sut?.dequeue()
        
        let result = sut?.queue.first
        let expectation: Int? = nil
        //then
        XCTAssertEqual(result, expectation)
    }
```

큐의 first 가 nil 과 비교하여 테스트했습니다!

2023-01-26 15:37 UTC, juun97 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
큐의 구현부분에서 제너릭의 타입을 CalculateItem 프로토콜을 채택한 타입만 받을 수 있게 해준뒤 테스트 코드부분에서 Int 를 extension 해주어 인스턴스 생성시 Int 큐를 만들어 진행하니 다운캐스팅이 따로 필요하지 않았습니다!

2023-01-26 16:06 UTC, juun97 commented
![](https://i.imgur.com/fmBUm2M.png)

Queue의 경우 인스턴스 생성시 CalculateItem 프로톨과 List 와의 관계를 가지게 됩니다. 이 관계는 잠시동안이 아닌 Queue의 삭제시 까지 이어지기에 연관을 나타내는 실선 화살표로 표현을 했습니다!

2023-01-27 02:46 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
테스트 파일에서 @testable import 를 통해 프로젝트를 임포트 시켜준다면 public 으로 처리할 필요가 없어질 것 같아요!

2023-01-27 02:58 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
프로퍼티 값이 어떻게 수정 되는지에 대해서도 알아보시면 좋을 것 같아요 ☺️

2023-01-27 03:11 UTC, wongbingg commented
전반적으로 수정이 잘 이루어졌네요 👍 질문에 대한 답도 잘 해주셨습니다
이번 스텝은 머지할게요~! 다음 스텝 에서는 개선할 점을 적용해보면 좋을 것 같아요.
화이팅 입니다 💪

2023-01-27 03:11 UTC, merged