계산기 [Step1] Harry
yagom-academy/ios-calculator-app pull request #418
Opened 2023-01-25 09:25 UTC by HarryHyeon

## 고민했던 점

### Array vs LinkedList
이번 계산기 프로젝트에서 필요한 큐의 자료구조를 Array로 할지 LinkedList로 할지 고민을했습니다.

#### Array의 특징
> 동일한 데이터 타입을 하나의 변수에 순서대로 나열한 자료 구조
> 메모리에 연속적으로 저장이 됨

- 배열의 특정 인덱스의 원소를 접근하는 시간 복잡도 O(1).
    - 메모리에 연속적으로 저장하기 때문에 인덱스를 가진다.
    - 따라서 인덱스를 사용해 특정 원소에 빠르게 접근이 가능.
- 배열의 특정 원소를 삭제할 경우
    - 제일 마지막 원소가 아닌경우에는 삭제후에 빈 자리만큼 앞으로 땡겨줘야하기 때문에
시간 복잡도는 O(n)
- 배열에 원소를 삽입할 경우
    - 삽입되는 위치 이후의 요소들을 뒤로 한칸씩 이동시켜야하기 때문에 시간 복잡도 O(n) 소요
- 배열에 원소를 가장 마지막에 추가하는 경우
    - 배열의 인덱스를 이용해 배열의 마지막에 추가 할 수 있으므로 시간 복잡도는 O(n)

#### LinkedList의 특징
> 데이터와 링크로 구성된 노드를 이용하여 메모리에 저장된 순서와 상관없이 연결된 자료구조

- 연결리스트의 특정 노드에 접근
    - 헤드 노드부터 순차적으로 탐색하여 특정요소에 접근해야하므로 O(n)의 시간 복잡도를 가짐
- 연결리스트의 특정 노드를 삽입할 경우
    - 맨 앞과 맨 뒤의 삽입은 헤드와 테일을 알고 있기때문에 시간 복잡도 O(1)
    - 중간에 삽입할 경우 어느 위치에 삽입할 것인지 탐색한 후에 삽입해야하므로 O(n)
- 연결리스트의 특정 노드를 삭제할 경우
    - 맨 앞, 맨 뒤 삽입은 탐색하지 않아도 되므로 O(1)
    - 중간에 위치한 노드를 삭제시에 탐색해야하므로 O(n)

#### 결론: 단방향 LinkedList로 구현
- 계산기 프로젝트에서는 삭제는 큐의 첫번째 데이터에서 발생하기 때문에 배열을 사용했을때 비효율적이라고 생각이 들었습니다.
- 계산기 프로젝트에서 중간에 데이터를 삽입할 경우가 없기때문에 탐색속도는 고려하지 않아도 된다고 생각했습니다.
- 큐의 모든 데이터를 삭제하고 싶을때 배열의 removeAll()을 호출할때 O(n)의 시간 복잡도가 소요되기 때문에 링크드리스트에서는 head와 tail에 nil만 주면 메모리가 해제되기 때문에 배열로 하는 것보다 효율적이라고 생각했습니다.
- 배열로 했을때 한칸씩 앞으로 당겨주는 작업을 해야하기 때문에 그렇게 생각했고, Double Stack Queue라는 것을 공부해보았는데 공간을 두배로 사용하고 reversed() 작업을 추가로 해주어야하기 때문에 이 또한 효율적이지 못하다고 생각을 했습니다.

### Class Diagram
<img src="https://i.imgur.com/05OpoVE.png" width="700">

- 클래스다이어그램을 그릴때, 요구사항에서 CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수해야한다고 명시되어있었습니다.
- 그런데 CalculatorItemQueue가 해당 프로토콜을 의존하거나 참조 또는 구체화를 한다는 개념이 아닌거 같아 선을 이어주지 않았습니다.

2023-01-26 03:48 UTC, llingo requested changes
안녕하세요 Harry
계산기 프로젝트 STEP 1 수고하셨습니다 :)

---

앞으로의 원활한 리뷰 진행을 위해 몇 가지 안내사항을 드리겠습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

---

배열과 연결리스트의 장단점을 파악한 후 이를 기반으로 기능 구현 방향을 설정하신 점 매우 좋네요 :+1:

2023-01-26 03:48 UTC, seu0313 commented on Calculator/Calculator/Model/CalculateItem.swift
> +extension String: CalculateItem {}
요구사항대로 잘 구현해주셨습니다 👍

2023-01-26 03:48 UTC, seu0313 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: LinkedList<Element>
[P1] 외부에서 스택의 값을 접근 및 변경할 수 있어야 하나요? 내부에서는 변경가능하지만 외부에서는 읽기전용 프로퍼티로 만들어줄 수 있는 `private(set)`에 대해 공부해보시면 좋을 것 같아요. :)

2023-01-26 03:48 UTC, seu0313 commented on Calculator/Calculator/Model/LinkedList.swift
> +    @discardableResult
`discardableResult`는 어떤 기능을 하는 Attribute인가요?

2023-01-26 03:48 UTC, seu0313 commented on Calculator/Calculator/Model/LinkedList.swift
> +    mutating func appendLast(_ value: T) {
클래스에는 없지만 구조체에는 mutating 키워드를 사용하도록 되어있는데요. mutating 키워드는 어떤 기능을 하나요?

2023-01-26 03:48 UTC, seu0313 commented on Calculator/Calculator/Model/LinkedList.swift
> +struct LinkedList<T> {
연결리스트를 직접 구현해주셨네요 좋습니다 👍 💯

2023-01-26 03:48 UTC, seu0313 commented on Calculator/Calculator/Model/LinkedList.swift
> +    var tail: Node<T>?
[P2] `head`와 `tail`의 경우 내부에서만 쓰는 것 같아요 접근제어자를 추가하는 것이 좋을 것 같아요

2023-01-26 03:48 UTC, seu0313 commented on Calculator/Calculator/Model/LinkedList.swift
> +        guard let value = head?.value else { return nil}
[P2] 한 칸 띄워주면 더 좋을 것 같아요 :)

```swift
guard let value = head?.value else { return nil}
                                               ⬆️
```

2023-01-26 03:48 UTC, llingo commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +final class CalculatorItemQueueTests: XCTestCase {
`final` 키워드를 잘 활용해주셨네요 👍

2023-01-26 03:48 UTC, llingo commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    var sut: CalculaterItemQueue<Int>!
CalculatorItemQueue에서 CalculatorQueueTests 타겟에서 직접 추가하는 방식으로 사용하신 것 같아요. `@testable`라는 키워드에 대해 공부해보시면 좋을 것 같아요.

![스크린샷 2023-01-26 오후 12 37 01](https://user-images.githubusercontent.com/94151993/214753661-c26d10e6-2665-48b7-81c2-cbc40a2f78ec.png)

2023-01-26 03:48 UTC, llingo commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    }
`setUpWithError`와 `tearDownWithError` 메서드는 언제 호출되나요? 이외에도 비슷한 기능을 하는 메서드에는 어떤 것이 있을까요?

2023-01-26 03:48 UTC, llingo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: LinkedList<Element>
내부에서 사용하는 것은 `연결 리스트`인데 `큐`라고 네이밍 되어있는 것 같아요.

2023-01-26 03:48 UTC, llingo commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        let result = sut.queue.count
[P2] 테스트 코드에서 `expectation`이란 네이밍은 XCTest의 XCTestExpectation과 혼돈을 줄 수 있을 것 같아요. 지금은 비동기 코드에 대한 테스트가 없기 때문에 문제가 되진 않지만 추후를 고려했을때 다른 네이밍을 추천드립니다.

2023-01-26 03:48 UTC, llingo commented on Calculator/CalculatorTests/LinkedListTests.swift
> +        XCTAssertEqual(result, expectation)
[P2] given, when, then 사이에는 한 칸씩 줄바꿈해줘서 구분해주는 것이 좋을 것 같아요 :)

2023-01-26 07:38 UTC, HarryHyeon commented on Calculator/CalculatorTests/LinkedListTests.swift
> +        XCTAssertEqual(result, expectation)
> [P2] given, when, then 사이에는 한 칸씩 줄바꿈해줘서 구분해주는 것이 좋을 것 같아요 :)

넵 다른 given, when, then에는 다 개행이 있었는데 이부분은 제가 실수로 빠뜨렸습니다. 수정완료했습니다!

2023-01-26 07:45 UTC, HarryHyeon commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        let result = sut.queue.count
> [P2] 테스트 코드에서 `expectation`이란 네이밍은 XCTest의 XCTestExpectation과 혼돈을 줄 수 있을 것 같아요. 지금은 비동기 코드에 대한 테스트가 없기 때문에 문제가 되진 않지만 추후를 고려했을때 다른 네이밍을 추천드립니다.

넵 링고에 의견을 반영해서 `expectedResult` 예상하는 결과 라는 의미의 네이밍으로 변경하였습니다.

2023-01-26 07:47 UTC, HarryHyeon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: LinkedList<Element>
> [P1] 외부에서 스택의 값을 접근 및 변경할 수 있어야 하나요? 내부에서는 변경가능하지만 외부에서는 읽기전용 프로퍼티로 만들어줄 수 있는 `private(set)`에 대해 공부해보시면 좋을 것 같아요. :)

링고의 의견대로 외부에서 접근할때는 읽기전용으로써만 접근을 하도록 제한을 하는 것이 맞다고 생각해서 private(set) 프로퍼티로 만들어주었습니다 !

2023-01-26 08:23 UTC, HarryHyeon commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: LinkedList<Element>
> 내부에서 사용하는 것은 `연결 리스트`인데 `큐`라고 네이밍 되어있는 것 같아요.

자료구조는 링크드리스트이지만 하는 역할은 선입선출의 기능을하는 큐라고 생각을해서 큐라고 네이밍을 했었는데, 링크드리스트 자료구조라는 것을 표현하는 `list`라는 이름도 괜찮을거 같아서 수정했습니다!

2023-01-26 08:25 UTC, HarryHyeon commented on Calculator/Calculator/Model/LinkedList.swift
> +    @discardableResult
> `discardableResult`는 어떤 기능을 하는 Attribute인가요?

리턴 해주는 값을 사용하지 않아도 warning 문구가 뜨지 않도록 해주는 Attribute 입니다 !

2023-01-26 08:39 UTC, HarryHyeon commented on Calculator/Calculator/Model/LinkedList.swift
> +    mutating func appendLast(_ value: T) {
구조체 또는 열거형의 내부의 프로퍼티를 수정해야 하는 경우 인스턴스 메서드에서 `mutating` 키워드를 사용해야 변경을 할 수 있습니다.

2023-01-26 08:40 UTC, HarryHyeon commented on Calculator/Calculator/Model/LinkedList.swift
> +    var tail: Node<T>?
넵 해당부분에 접근제어가 필요하다고 생각되어서 추가 했습니다 !

2023-01-26 08:40 UTC, HarryHyeon commented on Calculator/Calculator/Model/LinkedList.swift
> +        guard let value = head?.value else { return nil}
실수가 있었네요.. 다음에는 한번 더 확인해보겠습니다 !

2023-01-26 08:46 UTC, HarryHyeon commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    var sut: CalculaterItemQueue<Int>!
`@testable` Attribute는 테스트 파일에서 사용하는데, internal과 같은 접근제한이 걸려있는 모듈에 접근이 가능해지고
이를 테스트 파일에서 테스트 해볼 수 있도록 해줍니다 !

`fileprivate`과 `private` 선언이 되있는 모듈에는 `@testable` 사용하여도 접근할 수 없습니다 .

2023-01-26 08:54 UTC, HarryHyeon commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    }
> `setUpWithError`와 `tearDownWithError` 메서드는 언제 호출되나요? 

- `setUpWithError` 는 테스트 케이스를 시작하기 전에 호출해주는 메서드이고 각각의 테스트가 같은 상태와 조건에서 시작할 수 있도록 초기화해주는 작업을 합니다.
- `tearDownWithError` 는 테스트가 끝난 후 호출되는 메서드 입니다. setUpWithError에서 설정한 값들을 해제할 때 사용합니다

> 이외에도 비슷한 기능을 하는 메서드에는 어떤 것이 있을까요?
- `setUp` : `setUpWithError`와는 에러를 throw 할 수 있느냐의 차이가 있습니다.
- `tearDown` : 마찬가지로 `tearDownWithError`에서는 에러를 던질 수 있습니다.

2023-01-26 13:30 UTC, llingo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: LinkedList<Element>
좋습니다 💯 
추가적으로 `private(set)`은 사실 `internal private(set)`입니다. `internal`이 생략되어 `private(set)`으로 표기합니다.

2023-01-26 16:21 UTC, HarryHyeon commented
링고 늦은시간까지 제 궁금증을 같이 고민해주셔서 감사합니다 !
같이 이야기했던데로 테스트를 하기위해서 존재했던 불필요한 타입들을 제거하였고, 그에 맞게 테스트 케이스도 수정을 하였습니다 !

2023-01-27 01:00 UTC, llingo approved these changes
STEP 1 수고하셨습니다 :)
다음 스탭도 화이팅입니다. 🎉

2023-01-27 01:00 UTC, seu0313 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var list: LinkedList
좋습니다 💯

2023-01-27 01:00 UTC, seu0313 commented on Calculator/Calculator/Model/LinkedList.swift
> +    private var tail: Node<CalculateItem>?
좋습니다 👍

2023-01-27 01:00 UTC, merged