계산기 [STEP 1] vetto
yagom-academy/ios-calculator-app pull request #421
Opened 2023-01-25 10:31 UTC by gzzjk159

안녕하세요 @Judy-999 
이래저래 생각을 하고 구현을 하고 test까지 진행하다 보니 좀 늦은 거 같습니다. 늦었지만 좋은 피드백 부탁드립니다.

### UML
![Calculator_step1 drawio](https://user-images.githubusercontent.com/72865221/214540084-79e0d607-9727-4605-9dfa-dbc60c3db2d1.png)

### 고민했던 점
#### CalculatorItemQueue의 타입
* class와 struct 사이에서 고민하였습니다. 그래서 struct를 사용할 때를 찾아보았습니다. struct사용 이유는 아래와 같습니다.
    * 연관된 간단한 값의 집합을 캡슐화하는 것만이 목적일 경우
    * 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할때
    * 구조체에 저장된 프로퍼티가 값 타입이며, 참조하는 것보다 복사하는것이 합당할때
    * 다른 타입으로부터 상속받거나, 자신을 상속할 필요가 없을때
* 찾아 보니 class를 사용하는 것보다 struct를 사용하여 구현하는 것이 타당하다고 생각하여 struct로 구현하였습니다.

#### CalculatorItemQueue의 타입 구현에 대한 고민
* 기존의 있는 swift list를 이용한 구현
    * 장점: 손 쉬운 구현 및 append함수 사용 가능 (시간복잡도: O(1))
    * 단점: remove함수 사용시 index를 옮겨줘야 해서 (시간복잡도: O(n))
* node를 이용한 linkedlist구현
    * 장점: 리스트 추가 및 삭제 (시간복잡도: O(1))
    * 단점: 저장 공간 효율 떨어짐
* DoubleStack을 이용한 구현
    * 장점: 리스트 추가 및 삭제 (시간복잡도: O(1))
    * 단점: 저장 공간 효율 떨어짐

* 따라서 저는 linkedlist와 doubleStack 둘 중에서 고민을 하였고 제가 더 이해하기 쉬운 linkedlist로 구현하였습니다.

### 해결하지 못한 점 & 조언받고 싶은 점
#### 접근제어자
* UnitTest를 할 때 한 함수의 코드를 테스트 하려고 할 때 다른 함수를 이용하게 되면 의존성이 높아지기 때문에 다른 함수의 사용을 자제하려고 했습니다. 따라서 test를 할 때 직접 접근하기 위해서 head와 tail을 internal로 선언하였는데 괜찮은지 궁금합니다.
```swift
var head: Node<T>?
var tail: Node<T>?
```

#### clear함수
* clear라는 함수를 통해서 linkedlist로 구현된 queue를 초기화 시키는 작동을 구현하였습니다. head와 tail을 nil로 바꿔주는 간단한 로직입니다. 이렇게 되면 참조하고 있던 곳이 없어지면서 단방향으로 가리키고 있던 node들이 없어지면서 ARC에 의해 카운트가 0이 되면서 할당이 해제되는 것으로 이해하고 있는데 맞는지 궁금합니다.
```swift
mutating func clear() {
    self.head = nil
    self.tail = nil
}
```

2023-01-26 10:20 UTC, Judy-999 requested changes
안녕하세요 vetto! 로직의 세계 계산기 프로젝트로 오신걸 환영합니다  🤗

UML, 자료구조, Test 등 낯선 개념이 많으셨을 텐데 수고하셨습니다 👏👏 
어려우시더라도 차근 차근 이해해보면서 잘 진행해봅시다 💪

그리고 첫 리뷰이니 당부의 말씀을 드릴게요!

제가 드린 코멘트에 댓글로 어떻게 반영하셨는지 또는 의견을 달아주시면 제가 수정사항을 파악하기 용이합니다. 만약 큰 의미가 없는 코멘트라면 이모지만 달아주셔도 됩니다! 만약 제가 드린 코멘트가 잘 이해가 안가신다면 언제든 DM 주세요~
그리고 PR 이후와 모든 수정을 마친 후 DM을 주시면 빠르게 확인할 수 있습니다 🙌

제가 질문드리는 점은 반드시 고쳐야 한다고 둘러서 말하는게 아니라 정말 궁금하거나 의견을 묻는 경우도 있으니 반드시 수정(적용)하거나 잘못된 점이라고 생각하시지 않으면 좋겠네요!
제 의견을 무조건 수용하시기보다 vetto의 이유로 결정하는게 더 좋습니다 🙂

저는 vetto의 코드를 평가하거나 잘못된 점을 지적하는 사람이 아닙니다!
같이 코드를 고민하는 역할로 더 좋은, vetto의 이유가 있는 코드를 완성하는 데에 도움이 되면 좋겠습니다 😊

---

## 고민했던 점
### CalculatorItemQueue의 타입
>  class를 사용하는 것보다 struct를 사용하여 구현하는 것이 타당하다고 생각하여 struct로 구현하였습니다.

class와 struct를 선택하는 문제는 매번 어려우면서도 앞으로도 새로운 타입을 생성할 때마다 고민하셔야 할 문제입니다! vetto만의 기준을 정해놓고 적용하시면 되는데 이미 잘 고민하고 계신 듯 하네요 👍
<br>

### CalculatorItemQueue의 타입 구현에 대한 고민
> linkedlist와 doubleStack 둘 중에서 고민을 하였고 제가 더 이해하기 쉬운 linkedlist로 구현하였습니다.

각각의 구현 방법의 장단점과 시간 복잡도를 비교해서 선택하셨네요 👏 
내가 잘 이해하고 있는지도 중요한 선택의 기준이 되니 잘 선택하신 것 같습니다!
<br>

## 해결하지 못한 점 & 조언받고 싶은 점
### 접근제어자
> UnitTest를 할 때 한 함수의 코드를 테스트 하려고 할 때 다른 함수를 이용하게 되면 의존성이 높아지기 때문에 다른 함수의 사용을 자제하려고 했습니다. 따라서 test를 할 때 직접 접근하기 위해서 head와 tail을 internal로 선언하였는데 괜찮은지 궁금합니다.

프로퍼티를 외부로 그대로 노출하는건 좋지 않습니다! 큐에서 노드를 직접 변경하게 된다면 큐의 데이터가 온전하다는 보장이 사라지게 됩니다.

테스트를 위해 접근이 필요하다면 접근은 가능하되 수정은 제한하는 방법으로 진행하시면 됩니다!
<br>

## clear함수
> clear라는 함수를 통해서 linkedlist로 구현된 queue를 초기화 시키는 작동을 구현하였습니다. head와 tail을 nil로 바꿔주는 간단한 로직입니다. 이렇게 되면 참조하고 있던 곳이 없어지면서 단방향으로 가리키고 있던 node들이 없어지면서 ARC에 의해 카운트가 0이 되면서 할당이 해제되는 것으로 이해하고 있는데 맞는지 궁금합니다.

네! 참조만 끊어주면 ARC가 자동으로 메모리에서 해제해줍니다 🙂

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
`size`와 `peek`은 계산기 큐에서 어떤 상황에서 사용될 수 있을까요?

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculateItemProtocol.swift
> +extension Double: CalculateItem {}
`CalculateItem`의 의미를 잘 파악하시고 채택시키셨네요 👏

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
`CalculateItem`을 준수하는 타입만 요소로 받게 한 점 좋습니다~

`T`가 통용되는 형식이긴 하지만 의미있는 이름으로 표시하는게 좋을 것 같아요 👀

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(newData: Node<T>) {
`mutating`은 어떤 의미이고, 어떤 이유로 사용하셨을까요?

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(newData: Node<T>) {
현재 네이밍으로는 `enqueue(newData: node)` 이런 식으로 사용이 될 텐데 `newData`는 생략해도
`enqueue(node)` -> `node를 enqueue한다`라고 충분히 이해할 수 있어 보여요!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
외부에서 `Node` 타입을 알고 넣어주는건 불필요해 보여요! Node에 넣는 값만 받게 하는게 좋겠습니다 👀

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        } else {
`head`가 `nil`일 때 `dequeue`하는건 다른 흐름으로 봐서 바로 `nil`을 `return`한다면 `guard let`으로 처리하면 그 흐름이 더 잘 보일 것 같네요!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/Node.swift
> +class Node<T: CalculateItem> {
`Node`가 상속되어 사용할 일이 있을까요~? 아니라면 적절한 처리를 추가하시는게 좋습니다 🙂

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/Node.swift
> +class Node<T: CalculateItem> {
역시 `T` 대신 의미를 나타내는 이름을 지어주세요!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var tail: Node<T>?
LinkedList로 구현하셨다고 했는데 구현된 LinkedList는 어디에 있는걸까요?

`head`와 `tail`을 가진 `CalculatorItemQueue`가 LinkedList 역할을 하고 있는 것처럼 보이네요 🤔

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
`override`로 재정의할 때 잊지 말아야 할 단계가 있습니다! 생각해보시고 처리해주세요 🙌

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
`setUpWithError`와 `tearDownWithError`는 각각 어떤 역할을 하나요?

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/NodeTests/NodeTests.swift
> +    }
이미 구현된 기능은 테스트할 필요가 없습니다 💡

현재 NodeTest는 제네릭 타입을 잘 받고 있는지, `init` 생성할 때 `data`를 잘 할당받는지 테스트하는 것에 그치는 것 같아요. 
필요한 테스트인지 고민해 볼 필요가 있어 보입니다!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    // isEmpty computed property test
주석으로 구분하고 싶다면 `MARK` 주석을 알아보시고 사용해보세요!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_head가_nil일_때_isQueueEmpty호출하면_true이다() {
테스트 함수명을 한글로 작성하신 이유가 있을까요?

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var tail: Node<T>?
`head`와 `tail`이 그대로 노출되는건 좋지 않습니다!
제한할 수 있는 접근은 제한하는게 좋습니다.

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(result, expectation)
Test는 `given-when-then`으로 분리해서 코드를 작성하곤 합니다. 이를 주석으로 구분하는 것도 좋습니다!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_head가_nil일_때_isQueueEmpty호출하면_true이다() {
`head`가 `nil`이 되는 경우는 많을 테니 단순히 `nil`일 때 보다는 "생성 시~", "초기화 이후~"와 같이 표현하는게 명확할 것 같아요.

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_CalculatorItemQueue에_Node를_추가하고_isQueueEmpty호출하면_false이다() {
어떤 메서드(또는 연산 프로퍼티)를 테스트하는지 바로 알 수 있도록 아래와 같이 초반에 명시하는 방법도 있습니다!

`test_isQueueEmpty_~일때~~이다`
`test_isQueueEmpty호출시_~~~이다`

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(result, expectation)
`XCTAssertTrue`나 `XCTAssertFalse`을 적용할 수 있어 보이네요 👀

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
1개를 넣었을 때랑 2개를 넣었을 때 어떤 차이를 보고자 테스트하시는 걸까요? 🤔

굳이 더 테스트해보자면 값이 있다가 없어졌을 때 0이 나오는지 같은 경우가 될 것 같네요!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertTrue(expectation)
`XCTAssertNil`을 활용할 수 있겠네요~!

2023-01-26 10:20 UTC, Judy-999 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
사용자는 `dequeue`가 어떤 상황에서도 원하는 결과를 내는지 궁금할 뿐 내부적으로 `head`나 `tail`이 어떻게 변경되는지 궁금할까 싶네요 🤔
테스트 케이스는 **요구사항**을 테스트한다는 점을 고민해보시면 좋겠습니다!

2023-01-26 18:19 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
queue의 기본적이 메서드라 생각하여 작성하였는데 계산기 큐에서는 사용하지 않을 거 같아 현재는 코드를 수정하여 삭제해줬습니다. c9911b1f3c14ee3dfbf3034ca8094b72cfdc5f38

2023-01-26 18:22 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
보편적으로 많이 쓰이는 T보다는 요소라는 name이 더 어울리는 것 같아 Upper Camel Case를 따르는 제네릭에 맞춰 Element로 수정하였습니다. 00a617f0ad701bfc83f10561330530742d01a59e

2023-01-26 18:23 UTC, gzzjk159 commented on Calculator/Calculator/Model/Node.swift
> +class Node<T: CalculateItem> {
보편적으로 많이 쓰이는 T보다는 요소라는 name이 더 어울리는 것 같아 Upper Camel Case를 따르는 제네릭에 맞춰 Element로 수정하였습니다. 00a617f0ad701bfc83f10561330530742d01a59e

2023-01-26 18:26 UTC, gzzjk159 commented on Calculator/Calculator/Model/Node.swift
> +class Node<T: CalculateItem> {
Node 클래스 타입은 더 이상 상속될 일이 없을 거 같아 `final`키워드를 붙여 처리하였습니다. 7a50f644b2084b6f069b077c46aad072d0dd16a1

2023-01-26 18:27 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        } else {
리뷰어에 조언대로 `guard let`을 사용하여 더 가독성이 좋게 코드를 수정하였습니다. 7a50f644b2084b6f069b077c46aad072d0dd16a1

2023-01-26 18:31 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(newData: Node<T>) {
구조체 내에서는 메서드를 통해 구조체 내에 프로퍼티가 상수이기 때문에 변경할 수 없습니다. 하지만  mutating 키워드를 사용하게 되면 메서드 내에서 프로퍼티를 변경할 수 있게 해주기 때문에 사용했습니다.

2023-01-26 18:36 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(newData: Node<T>) {
리뷰어 조언대로 코드를 수정하여 `_`를 사용하여 전달인자 레이블을 생략할 수 있게 코드를 수정하였습니다. fb2d2ad9c985a913714758c135605418e1c8023d

2023-01-26 18:41 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
리뷰어 조언대로 타입을 알고 넣어주는 방식에서 타입을 받은 후 메서드 내에서 Node 생성 시 데이터를 넣어주고 생성한 노드를 넣는 방식으로 코드를 수정하였습니다. 3cbadad7da48cb5b2f6c618d5650a2e2b367fa39

2023-01-26 18:49 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
찾아보니 override를 할 때 부모 클래스의 메서드를 호출하여 상태를 재설정하고 오류를 던질 수 있는 기회를 줘야하는 것을 알았습니다. 현재는 코드를 수정하여 부모 클래스의 메서드를 호출하는 것으로 리팩토링 하였습니다. 0f70c5e99dd823e01533ecf244fe1e688576bcf8

2023-01-26 18:52 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
setUpWithError 메서드는 각 테스트 코드가 실행되기 전에 실행되는 함수로 각 작업에 정의하거나 초기화할 구문을 적어놓습니다.
tearDownWithError 메서드는 각 테스트 코드가 실행 된 후에 실행되어 각 작업을 끝낸 후 정리하는 구문을 적어놓습니다.

2023-01-26 18:53 UTC, gzzjk159 commented on Calculator/NodeTests/NodeTests.swift
> +    }
필요 하지 않는 테스트랑 생각되어 현재는 코드를 삭제하였습니다. 01e1624629a93c30a15e7b9302c9e96df930ab9b

2023-01-26 18:55 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    // isEmpty computed property test
그냥 주석보다는 구역을 설정해주고 구분해주는 MARK주석을 사용하여 코드를 수정하였습니다. 0f70c5e99dd823e01533ecf244fe1e688576bcf8

2023-01-26 18:59 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_head가_nil일_때_isQueueEmpty호출하면_true이다() {
테스트 함수명은 말 그대로 테스트를 하기위해 지어지는 함수라고 생각합니다. 따라서 함수명을 한글로 작성하여 어떠한 테스트인지 명확하게 설명해주는 것이 좋다고 생각하여 한글로 작성하였습니다.

2023-01-26 19:00 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var tail: Node<T>?
접근을 제한할 수있는 private와 private(set) 중에서 고민하였습니다. 결국 테스트를 하기 위해서는 값을 읽는 것이 필요하다 생각하여 private(set)으로 접근제어자를 수정하였습니다. 1dc71f3452a20fe2e4674f599351771e21c86f66

2023-01-26 19:01 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(result, expectation)
리뷰어의 조언대로 주석으로 given-when-then을 분리하여 코드로 작성했습니다.

2023-01-26 19:08 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_head가_nil일_때_isQueueEmpty호출하면_true이다() {
리뷰어의 조언대로 head가 nil이 되는 경우라는 표현보다 `test_queue생성_후_비어있는_상태에서_isEmpty호출하면_true이다`라는 명확한 표현을 사용하여 함수명을 변경하였습니다. e3be9eb1785a9429705f995288c1af10266cb94c

2023-01-26 19:13 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(result, expectation)
현재는 코드를 수정하여 `XCTAssertTrue`나 `XCTAssertFalse`같은 다양한 Assert구문을 사용하여 리팩토링하였습니다. b9d6d0fcfba6cd63f66aedb85701c3098e78c038

2023-01-26 19:15 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
현재는 size 프로퍼티를 삭제하여 코드를 리팩토링 하였습니다. 따라서 관련 테스트도 없어졌습니다. d7b39f0df54391180e628ae41620cdc3dbb4320d

2023-01-26 19:16 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertTrue(expectation)
리뷰어 조언대로 Assert구문을 찾아보았고 다양한 Assert문을 참고하여 코드를 리팩토링하였습니다. 8b608ecb4ac6ef3fa73803dcc8c5817e4d73d312

2023-01-26 19:18 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
dequeue는 head에 있는 값을 반환하는 함수라고 생각합니다. 변경하기 전에 저의 코드는 head나 tail이 어떻게 변경되는지에 대해 신경을 쓰고 코드를 작성하였습니다. 현재는 dequeue가 어떤 역할을 하는지에 대해 테스트 하는 것으로 코드를 리팩토링 하였습니다. 
8b608ecb4ac6ef3fa73803dcc8c5817e4d73d312

2023-01-26 19:23 UTC, gzzjk159 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_CalculatorItemQueue에_Node를_추가하고_isQueueEmpty호출하면_false이다() {
리뷰어의 조언대로 어떤 메서드를 테스트하는 지 바로 알 수 있도록 초반에 명시하려고 했습니다.
그러나 제 메서드가 어떤 테스트를 하는지 알기 위해서는 어떠한 조건이 있고 그 다음 메서드를 호출해야 어떤 결과가 나오는지 명확하게 알 수 있을 거 같아 초반에 명시하지 않았습니다. e3be9eb1785a9429705f995288c1af10266cb94c

2023-01-26 19:23 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var tail: Node<T>?
Node를 연결하여 큐를 구현하였는데 이것을 node로 LinkedList를 구현 후 만든 LinkedList로 queue를 구현하였다고 잘못 말하였습니다.  현재 저의 코드는 LinkedList로 구현한 것이 아닌 Node를 이용하여 queue를 구현한 것으로 알아주시면 될 거 같습니다.

2023-01-27 02:52 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T: CalculateItem> {
Item이라고도 할 수 있을 것 같은데 Element도 충분히 좋습니다 👍

2023-01-27 02:58 UTC, Judy-999 approved these changes
Queue가 Node 자체를 사용하는 것 보단 LinkedList라는 타입을 구현한 후 LinkedList로 Queue를 구현하는게 연결 리스트를 이용한 큐 구현이 될 것 같아요! 고민해보고 다음 스텝에서 같이 적용해주세요 🙌
다른건 모두 질 적용하셔서 머지하겠습니다 👍

2023-01-27 02:59 UTC, merged