계산기 [STEP 1] 혜모리
yagom-academy/ios-calculator-app pull request #422
Opened 2023-01-25 11:38 UTC by hyemory

안녕하세요 웡빙! ( @wongbingg ) 혜모리입니다.
계산기 프로젝트 첫 PR 보냅니다~
자료구조 및 `Queue`를 처음 공부해봐서 각종 구글링과 문서를 읽으며 완성해 보았습니다.
질문도 어떻게 드리면 좋을지 어려워 많이 남기지 못했습니다. 
아직 부족한게 많은 코드인데 리뷰해 주시면 부족한 부분 더 공부해보고 개선해 보겠습니다!

---
## UML

![image](https://github.com/hyemory/ios-calculator-app/blob/step1/Class_Diagram.png?raw=true)

---
## 고민했던 점

### Queue를 구현하는 방법

큐를 구현하는 방법에는 Array와 Linked List가 있다고 학습했습니다.
그냥 Array를 사용하게되면 front 제거 시 남은 요소의 인덱스를 하나하나 옮겨야하여 오버헤드가 발생된다고 합니다.
그것을 보완하기 위해 더블 스택 큐와 연결 리스트 중에 고민했는데 List를 만들어 보는 것이 선택 사항이기도 하고
이번 프로젝트 특성상 사칙연산이 없어 `맨 앞, 뒤 값`과 `전체 값` 을 제외하고는 수정하거나, 따로 특정 인덱스를 찾을 일이 없다고 판단하여 `연결 리스트`를 사용하게 되었습니다.

### struct / class

- `Node` : class로 정의했습니다. 노드 하나를 구성하는 Node 클래스의 경우, 하나의 노드에서 다음 노드의 포인터를 가지고 있기 때문에 각각의 참조를 알 수 있어야한다고 생각했습니다.
- `LinkedList` : class로 정의했습니다. 꼭 class를 사용해야하는 것은 아니나 여러 노드들을 하나의 연결리스트에서 계속해서 변경하고 추가한다고 생각했기 때문에 class를 사용했습니다.
- `CalculatorItemQueue` : struct로 정의했습니다. 이후 상속을 받거나 할 타입이 아니라고 생각했고 추후 추가할 `연산하기 위한` 기능을 캡슐화한다고 생각하였습니다.

---
## 조언이 필요한 점

### TDD

아래 예시와 같이 TDD 작성 중 반환타입이 있는 메서드를 그냥 호출할 때, 
`Result of call to 'methodName()' is unused` 라는 권고 문구를 보았습니다.
자주보는 문구라 볼 때마다 처리하지만, 유닛 테스트용 코드라 `let _ =` 와일드카드 상수에 담아 호출하는 것으로 처리하였습니다.
그런데 아무래도 `상수를 선언하면 그만큼 메모리에 새로 할당되지 않을까?`하는 생각이 들어 권고 문구를 그냥 무시하고 메서드만 호출하는 것이 더 좋을지 궁금합니다.

*LinkedListTests 중 예시 코드*
``` swift
func test_removeLast호출시_List에1_2_3이있는경우_3이삭제되고_tail은2가된다() {
    // given
    sut.appendLast("1")
    sut.appendLast("2")
    sut.appendLast("3")
    let expectation = "2"

    // when
    let _ = sut.removeLast()

    // then
    XCTAssertEqual(sut.tail?.value, expectation)
    }
```

2023-01-26 13:17 UTC, wongbingg commented
안녕하세요 혜모리~! 계산기 프로젝트 Step1 고생하셨습니다 ☺️

## UML

![image](https://github.com/hyemory/ios-calculator-app/blob/step1/Class_Diagram.png?raw=true)


UML 에서 각 타입에 사용하는 색과 Access Level 에 대한 간략한 설명을 상단에 나타내주셔서 이해하기 편했던 것 같아요~! 👍
다만, `CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다.` 라는 요구사항에 따라 CalculatorItemQueue에서 사용되는 요소(추가되고 삭제되는)가 CalculateItem 프로토콜을 채택 하는 것이 맞을 것 같아요. 한번 더 고민 해볼까요?

## ✅ 고민했던 점에 대하여

### Queue를 구현하는 방법

>큐를 구현하는 방법에는 Array와 Linked List가 있다고 학습했습니다.
그냥 Array를 사용하게되면 front 제거 시 남은 요소의 인덱스를 하나하나 옮겨야하여 오버헤드가 발생된다고 합니다.
그것을 보완하기 위해 더블 스택 큐와 연결 리스트 중에 고민했는데 List를 만들어 보는 것이 선택 사항이기도 하고
이번 프로젝트 특성상 사칙연산이 없어 `맨 앞, 뒤 값`과 `전체 값` 을 제외하고는 수정하거나, 따로 특정 인덱스를 찾을 일이 없다고 판단하여 `연결 리스트`를 사용하게 되었습니다.

<br>

자료구조를 선택 하게된 이유에 대해 잘 설명 해주셨네요~! 👍 각 자료구조를 사용했을 때의 성능(시간복잡도) 측면에서의 장단점도 고려 해보면 좋을 것 같아요!


### struct / class

>- `Node` : class로 정의했습니다. 노드 하나를 구성하는 Node 클래스의 경우, 하나의 노드에서 다음 노드의 포인터를 가지고 있기 때문에 각각의 참조를 알 수 있어야한다고 생각했습니다.
>- `LinkedList` : class로 정의했습니다. 꼭 class를 사용해야하는 것은 아니나 여러 노드들을 하나의 연결리스트에서 계속해서 변경하고 추가한다고 생각했기 때문에 class를 사용했습니다.
>- `CalculatorItemQueue` : struct로 정의했습니다. 이후 상속을 받거나 할 타입이 아니라고 생각했고 추후 추가할 `연산하기 위한` 기능을 캡슐화한다고 생각하였습니다.

<br>

`값 타입`/ `참조 타입` 을 선택하는 기준에 대해서도 잘 설명 해주셨네요~! 👍 
## ✅ 조언이 필요한 점에 대하여

### TDD

>아래 예시와 같이 TDD 작성 중 반환타입이 있는 메서드를 그냥 호출할 때, 
`Result of call to 'methodName()' is unused` 라는 권고 문구를 보았습니다.
자주보는 문구라 볼 때마다 처리하지만, 유닛 테스트용 코드라 `let _ =` 와일드카드 상수에 담아 호출하는 것으로 처리하였습니다.
그런데 아무래도 `상수를 선언하면 그만큼 메모리에 새로 할당되지 않을까?`하는 생각이 들어 권고 문구를 그냥 무시하고 메서드만 호출하는 것이 더 좋을지 궁금합니다.

<br>

깊은 고민을 해주셨군요..! 와일드 카드에 담아줄 경우 내부적으로 메모리에 새로 할당되지 않을까? 라는 생각은 저도 해보지 않았던 것 같아요. 이 부분은 찾아보고 알게되면 코멘트에 남겨둘게요🧐
 보자마자 생각나는 `@discardableResult` 라는 Attribute 가 있는데요, 이를 함수에 붙여주게 되면 함수를 호출해도 위와 같은 경고창을 없애줄 수 있을 거에요! 
 
```swift
// 예시
@discardableResult
func removeLast() -> Node {
    // 함수 내부
    return result
}
```
- [swift Github - discardableResult](https://github.com/apple/swift/blob/5094804c775b164b99ef3636c49b6a7067edb267/test/attr/attr_discardableResult.swift)

2023-01-26 14:02 UTC, wongbingg requested changes

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/CalculateItem.swift
> +}
빈 프로토콜을 잘 정의 해주셨군요 👏

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
dequeue 의 스펠링에 오류가 있는 것 같아요 🥲

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
CalculateItem 을 채택하는 곳이 맞을지 한번 더 고민해보면 좋을 것 같아요 🧐

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/Node.swift
> +}
Node 타입에 제네릭을 활용해보면 좋을 것 같아요. 현재는 value 값으로 String 타입만 들어올 수 있는데, 제네릭 타입을 활용하면 다양한 타입에 대응할 수 있을 거에요 ☺️

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/Node.swift
> +}
- Equatable 프로토콜을 채택해준다는 것을 어떤 의미를 가질까요 ? 
- Node 타입에 이 프로토콜을 채택해준 이유가 있을까요 ?

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
맨 뒤의 요소를 제거, 반환 해주는 메서드군요 👍

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
Int 타입, String 타입, 사용자 정의 타입 등등 다양한 타입을 다룰 수 있는 queue를 만들어 보면 좋을 것 같아요!
예를 들어 Int 타입을 다루는 queue1, String 타입을 다루는 queue2, 사용자 정의 타입을 다루는 queue3 
queue1, queue2, queue3 인스턴스를 만드는 데에 LinkedList 타입 하나를 사용하는 것 이에요!

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
큐의 모든 요소를 제거 해주는 메서드 이군요 👍

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/LinkedList.swift
> +}
head 와 tail을 가진 연결리스트 구현을 잘 해주셨네요 👍 
- 현재 head 와 tail 을 가지는 것으로 얻을 수 있는 장점에는 어떤 것이 있을까요? 
- Queue 자료구조는 먼저 집어 넣은 데이터가 먼저 나오는 FIFO(First In First Out) 구조로 저장하는 형식을 말해요. removeLast() 메서드가 활용될 일이 있을지 다시한번 고민 해볼까요?

- [위키백과 - 큐(자료 구조)](https://ko.wikipedia.org/wiki/큐_(자료_구조))

2023-01-26 14:02 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
super 를 통해 부모 메서드를 실행 시켜주셨네요 👏
평소 우리가 사용하는 재정의 메서드에서 부모 메서드를 호출해주는 이유는 무엇일까요 ?

2023-01-26 14:02 UTC, wongbingg commented on Calculator/LinkedListTests/LinkedListTests.swift
> +}
LinkedList에 대한 단위 테스트를 잘 해주셨네요 👍 
- 단위 테스트는 프로젝트의 기능명세서 역할을 한다고 생각해요.
- 세세한 부분까지 테스트를 하신 부분은 좋지만, 테스트의 단위를 고려해보는 것도 좋을 것 같아요
- 엣지케이스 기준으로 비슷한 테스트 주제를 묶을 수 있을 것 같아요🧐

2023-01-26 14:02 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +}
given, when, then 으로 상황을 나누어 테스트 진행을 해주셨네요 👍

2023-01-26 14:02 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
setUpWithError() 와 tearDownWithError() 는 각각 어떤 역할을 하나요?

2023-01-26 14:02 UTC, wongbingg commented on Calculator/Calculator/Model/LinkedList.swift
> +        }
```suggestion
        guard isEmpty == false else {
            return nil
        }
```

개인적으로 느낌표를 통해 논리부정 연산자를 사용하는 것보다는 이런 식으로 명확하게 false를 표현 해주는 것이 가독성이 더 좋다고 생각해요 . 참고만 해주세요☺️

2023-01-26 16:13 UTC, hyemory commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
앗 `dequeue`로 수정하겠습니다 😖

2023-01-26 16:34 UTC, hyemory commented on Calculator/Calculator/Model/Node.swift
> +}
> * Equatable 프로토콜을 채택해준다는 것을 어떤 의미를 가질까요 ?
> * Node 타입에 이 프로토콜을 채택해준 이유가 있을까요 ?

`Equatable` 프로토콜을 채택하면 Equatable을 채택한 타입끼리 비교해 줄 수 있습니다.
두 개의 Node를 비교하려고하니 다음과 같은 컴파일 에러를 만났습니다.
`Operator function '!=' requires that 'Node' conform to 'Equatable'`
두 개의 Node를 비교하기 위해 `Equatable` 프로토콜을 채택해주었습니다.

2023-01-26 16:38 UTC, hyemory commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
어떤 타입에도 유연하게 대처할 수 있도록 제네릭으로 수정해 보겠습니다!

2023-01-26 17:00 UTC, hyemory commented on Calculator/Calculator/Model/LinkedList.swift
> +}
> * 현재 head 와 tail 을 가지는 것으로 얻을 수 있는 장점에는 어떤 것이 있을까요?

`head`의 경우 배열의 dequeue 오버헤드 문제를 보완할 수 있게 됩니다. head를 지정하면 front의 위치를 바로 알 수 있게되고 dequeue 시 그 다음 노드로 head를 옮기기만 하면 되기 때문입니다.
`tail`의 장점은 단방향 Linked List에 enqueue 시 시간 복잡도를 O(n) -> O(1)으로 줄일 수 있다는 점입니다.
단방향 Linked List의 경우 노드의 위치를 특정할 수 없기때문에 enqueue 하려면 front부터 차근차근 next의 주소로 이동하며 탐색해야 한다고 합니다. 이 때 시간복잡도는 O(n)이 됩니다.
그런데 tail을 사용하면 맨 마지막에 추가된 rear의 정보를 바로 알 수 있어서 front부터 탐색할 필요가 없어집니다.

> * Queue 자료구조는 먼저 집어 넣은 데이터가 먼저 나오는 FIFO(First In First Out) 구조로 저장하는 형식을 말해요. removeLast() 메서드가 활용될 일이 있을지 다시한번 고민 해볼까요?

이 부분은 말씀해 주신대로 Queue의 기본 기능 구현에는 필요가 없다고 생각하여 구현을 해야할 지 고민을 했던 부분입니다.
아직 step2는 확인하지 못했으나 계산기에 `최근 입력한 내용을 취소하는 기능(CE)`이 있다고하여 해당 기능을 구현하였습니다.

2023-01-26 17:53 UTC, hyemory commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
1. 보통 부모 메서드를 overriding하는 경우는 부모 메서드의 기능 + 새로운 기능을 추가하거나, 부모 메서드의 기능을 입맛에 맞게 수정하기 위해서라고 생각합니다!
부모 메서드가 가진 setUpWithError() 기능을 유지하면서 추가적인 기능을 구현하기 위해 부모 메서드를 호출해주었다고 생각하는데 맞을까요?
2. `setUpWithError()` : test case가 실행되기 전에 실행되는 메서드입니다. 이번 테스트에서는 sut라는 변수에 테스트 시작 전CalculatorItemQueue 타입으로 이니셜라이저를 해줍니다.
`tearDownWithError()` : test case가 실행되고난 후 실행되는 메서드입니다. 
test를 시작하기 전 이니셜라이저 해주고,  실행한 후 nil로 변경해주는 이유는 모든 테스트 케이스를 동등한 조건에서 실행될 수 있도록 하기 위함입니다.

2023-01-27 05:39 UTC, hyemory commented
수정된 UML입니다!

![image](https://user-images.githubusercontent.com/115605734/215017390-501cda8b-96ce-4f2b-8093-71322919a5d1.png)

2023-01-27 06:41 UTC, hyemory commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
e92a2cc147a49a5b308ae997143374439e3040ff

Node 타입 Value 프로퍼티의 T 제네릭 타입에 CalculateItem를 채택하도록 수정했습니다 😄

2023-01-27 06:46 UTC, hyemory commented on Calculator/LinkedListTests/LinkedListTests.swift
> +}
처음에 TDD는 개발자 자신만 보는 것이라 생각했습니다! 
구현 시 안전한 코드를 작성하기위해 최대한 자잘한 예외처리를 작성하며 조금씩 구현해가는 것이라 생각했었습니다.
유닛 테스트도 가독성 있게 만들어야 저도, 다른 사람도 보기 쉽다는 것을 깨닫고 개선했습니다.
중복되어보이는 테스트는 삭제하고, 노드끼리 비교하는 부분은 노드의 value를 비교하는 것으로 변경해보았습니다. 
4f29f7d92db4e798eb4d51e826310d44d8d39b28

2023-01-27 06:47 UTC, hyemory commented on Calculator/Calculator/Model/LinkedList.swift
> +        }
`isEmpty == false`로 수정했습니다! 감사합니다 😊

2023-01-27 07:31 UTC, wongbingg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
>      }
제네릭 타입으로 변경을 해주셨네요 👍

2023-01-27 07:31 UTC, wongbingg commented on Calculator/Calculator/Model/String+CalculatorItem.swift
> +}
큐에서 사용하는 요소에 CalculateItem 채택을 해주셨군요 👍

2023-01-27 07:42 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
1. 네 맞습니다. 사실 super.setUpWithError() 를 호출해주지 않더라도 에러는 나지 않는데요, 부모 메서드에 꼭 먼저 실행되어야 하는 중요한 초기화 로직이 담겨있다거나 하는 경우에 super를 호출해주지 않는다면 알 수 없는 오류를 겪을 수도 있을 거에요. stackoverflow 나 야곰닷넷에서도 같은 주제에 대한 내용들이 나와있으니 참고해보시면 좋을 것 같아요 👍

2023-01-27 07:44 UTC, wongbingg commented
피드백에 대한 수정이 잘 반영 되었네요 ~! 질문에 대한 답도 잘 달아 주셨습니다. 
고생하셨습니다☺️ 이번 스텝은 머지할게요~!! 다음 스텝도 화이팅입니다 💪

2023-01-27 07:45 UTC, merged