계산기 [STEP 1] 무리
yagom-academy/ios-calculator-app pull request #423
Opened 2023-01-25 13:51 UTC by parkmuri

@wongbingg
안녕하세요 웡빙! STEP1 PR 보냅니다.
새로운 개념도 등장하고, TDD도 처음 사용해보니 시간이 오래걸리게되었네요😢
그럼 리뷰 잘부탁드리겠습니다!

---
## UML
![image](https://user-images.githubusercontent.com/115514179/214580913-dd4b84ab-56ec-43e5-8607-a8fc2fdfec1c.png)

---
## 고민했던 부분

### 1️⃣ 제네릭 타입

- 이번 스텝을 진행하며 `Queue`에 대해 찾아보게되었고, 대부분의 블로그 등에서 예시를 들때 `Queue`를 `제네릭 타입`으로 선언하여 사용했습니다.
`<T>`와 `<Element>`등 다양한 방식으로 사용하고있는데 정확이 저것이 무엇을 의미하는지 몰라 `제네릭`도 공부하게 되었습니다. `<T>`는 보통 `제네릭함수` 의 플레이스 홀더이고, `<Element>`는 `제네릭타입` Array의 플레이스홀더입니다. 
플레이스홀더는 대략적으로 이런 타입이 들어올것이라고 명시만 해주는 것이고 플레이스홀더의 실제 타입은 함수가 호출되는 순간 결정된다고 합니다.
- 그렇다면  `CalculatorItemQueue` 에서는 어떻게 사용해야할까? 고민을 하다가 어떠한 `타입`이 들어올것이란 의미로 `<T>` 를 사용하였습니다.

### 2️⃣ Queue의 isFull, Peek

- Queue를 공부하다가 위의 파라미터, 메서드를 보게되었습니다.
- `isFull`같은 경우에는 이 계산기를 이용해서 얼마나 많은 숫자를 대기열에 포함해 계산해주어야할지 예상이 가지않아 사용하지 않았습니다.
`peek()` 메서드같은 경우에는 계산기에서 중간에 위치한 값을 꺼내서 사용할일이 없었다고 생각하여 포함하지 않았습니다.

### 3️⃣ 효율 좋은 dequeue()

- 처음 UML을 그릴때만 해도 `dequeue()`는 맨 앞에있는 숫자 하나만 제거해주니까 막연하게 `removeFirst()` 를 사용해주면 되겠다고 생각했습니다.
그러다 자료를 찾아 공부하면서 `시간복잡도` 를 생각하여 `dequeue` 해주어야 효율적이라는 글들을 많이 접하게되어 최대한 이해하며 따라해보았습니다.

→ 그냥 `dequeue` 하게되면 뒤쪽의 element를 하나하나 옮기며 O(n)의 시간복잡도를 가지며 오버헤드가 발생할 수 있기 때문이라고 합니다!

- 결국 `var head`를 생성하여 `dequeue()` 호출 시 삭제되는 값은 `nil`로 변환 후 어느정도 이상(코드에서는 배열의 count가 40이상, head ÷ count가 0.25이상)이면 nil값을 한번에 삭제하는 방향으로 진행하게 되었습니다.

---

## 해결이 되지 않은 부분

### 1️⃣ UML에서의 접근제어자

- UML을 그리며 접근제어자에 대해 생각해보는 시간이 있었습니다.
아직 저 Queue에 대해 어떻게 이용할것인지 와닿지 않았고 그로인해 큐 안에있는 파라미터와 메서드에 대한 접근제어자를 어떤식으로 설정해주어야할지 고민이 많이 되었습니다 🥲
 `CalculatorItemQueue` 안의 파라미터와 메서드가 어디서 호출되거나 사용될지 막연한 느낌이라 해결되지 않은 부분에 적어봅니다😢…

---

## 조언을 얻고싶은 부분

### 1️⃣ TDD 실패 케이스

- TDD 실패 케이스를 작성하는데 있어서 어려움을 겪었습니다. 기본적인 변수를 생성 한 후에는 뭔가 무의식적으로 성공을 위한 케이스로 작성을 하게되었습니다🥲…
- 웡빙의 TDD 작성 팁이 있다면 조언부탁드립니다!

2023-01-26 14:41 UTC, wongbingg commented
안녕하세요 무리~! 계산기 프로젝트 Step1 고생하셨습니다 ☺️


## UML
![image](https://user-images.githubusercontent.com/115514179/214580913-dd4b84ab-56ec-43e5-8607-a8fc2fdfec1c.png)

- UML을 색으로 구분지어 잘 표현 해주셨네요 👍
- 프로토콜 채택에 대한 화살표 모양도 잘 선택 해주셨습니다.
- `CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다.` 라는 요구사항에 맞게 프로토콜이 채택되었는지 다시한번 고민 해볼까요?
## ✅ 고민했던 부분에 대하여

### 1️⃣ 제네릭 타입

>- 이번 스텝을 진행하며 `Queue`에 대해 찾아보게되었고, 대부분의 블로그 등에서 예시를 들때 `Queue`를 `제네릭 타입`으로 선언하여 사용했습니다.
`<T>`와 `<Element>`등 다양한 방식으로 사용하고있는데 정확이 저것이 무엇을 의미하는지 몰라 `제네릭`도 공부하게 되었습니다. `<T>`는 보통 `제네릭함수` 의 플레이스 홀더이고, `<Element>`는 `제네릭타입` Array의 플레이스홀더입니다. 
플레이스홀더는 대략적으로 이런 타입이 들어올것이라고 명시만 해주는 것이고 플레이스홀더의 실제 타입은 함수가 호출되는 순간 결정된다고 합니다.
>- 그렇다면  `CalculatorItemQueue` 에서는 어떻게 사용해야할까? 고민을 하다가 어떠한 `타입`이 들어올것이란 의미로 `<T>` 를 사용하였습니다.

<br>

제네릭 타입에 대한 학습을 잘 해주셨네요 👍 보통의 경우 플레이스 홀더로 T 를 자주 사용하는데, 여기서는 Queue 에 들어가는 "요소" 타입이니 <Element> 도 괜찮아 보이네요

### 2️⃣ Queue의 isFull, Peek

>- Queue를 공부하다가 위의 파라미터, 메서드를 보게되었습니다.
>- `isFull`같은 경우에는 이 계산기를 이용해서 얼마나 많은 숫자를 대기열에 포함해 계산해주어야할지 예상이 가지않아 사용하지 않았습니다.
`peek()` 메서드같은 경우에는 계산기에서 중간에 위치한 값을 꺼내서 사용할일이 없었다고 생각하여 포함하지 않았습니다.

<br>

- 제가 알기에는 peek() 메서드의 역할은 큐의 맨 앞 또는 맨 위의 항목을 반환하는 것으로 알고있어요! 
- 이번 프로젝트에서 사용하게 될 기능들을 고민해보신 것이 느껴지네요 👍

### 3️⃣ 효율 좋은 dequeue()

>- 처음 UML을 그릴때만 해도 `dequeue()`는 맨 앞에있는 숫자 하나만 제거해주니까 막연하게 `removeFirst()` 를 사용해주면 되겠다고 생각했습니다.
그러다 자료를 찾아 공부하면서 `시간복잡도` 를 생각하여 `dequeue` 해주어야 효율적이라는 글들을 많이 접하게되어 최대한 이해하며 따라해보았습니다.

>→ 그냥 `dequeue` 하게되면 뒤쪽의 element를 하나하나 옮기며 O(n)의 시간복잡도를 가지며 오버헤드가 발생할 수 있기 때문이라고 합니다!

>- 결국 `var head`를 생성하여 `dequeue()` 호출 시 삭제되는 값은 `nil`로 변환 후 어느정도 이상(코드에서는 배열의 count가 40이상, head ÷ count가 0.25이상)이면 nil값을 한번에 삭제하는 방향으로 진행하게 되었습니다.

<br>

배열이 커지는 문제까지 처리를 해주셨네요 👏 각 자료구조의 시간복잡도에 대해서도 알아보고 비교해보면 좋을 것 같아요. 현재는 간단한 Queue 구현이라 배열을 이용할 수 있지만, 시간이 남는다면 LinkedList 또는 DoubleStack 으로 큐를 구현 해보시는 것도 추천 드려요 ☺️

## ✅ 해결이 되지 않은 부분에 대하여

### 1️⃣ UML에서의 접근제어자

>- UML을 그리며 접근제어자에 대해 생각해보는 시간이 있었습니다.
아직 저 Queue에 대해 어떻게 이용할것인지 와닿지 않았고 그로인해 큐 안에있는 파라미터와 메서드에 대한 접근제어자를 어떤식으로 설정해주어야할지 고민이 많이 되었습니다 🥲
 `CalculatorItemQueue` 안의 파라미터와 메서드가 어디서 호출되거나 사용될지 막연한 느낌이라 해결되지 않은 부분에 적어봅니다😢…

<br>

좋은 고민을 해주셨네요! 이렇게 막연한 경우 저는 모든 프로퍼티, 메서드 접근제어자를 private으로 설정 해놓고 시작합니다. 외부에서 해당 프로퍼티 또는 메서드를 꼭 사용해야 되는 경우가 생길 때마다 private을 풀어줍니다. 그럼 외부에서 사용되지 않는 프로퍼티나 메서드들은 자연스래 private 으로 남게 되죠 ☺️
저는 공용으로 사용될 목적으로 생겨난 객체(Singleton 같은)가 아닌 이상, 접근제어를 최대한 private으로 유지하려는 편입니다.

## 조언을 얻고싶은 부분

### 1️⃣ TDD 실패 케이스

>- TDD 실패 케이스를 작성하는데 있어서 어려움을 겪었습니다. 기본적인 변수를 생성 한 후에는 뭔가 무의식적으로 성공을 위한 케이스로 작성을 하게되었습니다🥲…
>- 웡빙의 TDD 작성 팁이 있다면 조언부탁드립니다!

<br>

EdgeCase 를 찾아내는 능력을 길러야할 것 같아요! 예를들면 큐에 값이 없을 때 dequeue를 수행할 경우, 큐가 제한한 최대 크기가 되었을 때 enqueue 하는 경우, index가 배열 범위를 벗어나는 경우에 대한 테스트 등등 오류가 날만한 상황들에 집중을 해보면 좋을 것 같아요 🧐

2023-01-26 15:47 UTC, wongbingg requested changes

2023-01-26 15:47 UTC, wongbingg commented on Calculator/Calculator/CalculatorItem.swift
> +}
요구사항에 맞게 빈 프로토콜 정의를 해주셨네요 👏

2023-01-26 15:47 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
enqueue 메서드를 잘 정의 해주셨네요.  mutating 키워드는 어떤 의미일까요 ?

2023-01-26 15:47 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
dequeue 메서드도 잘 정의 해주셨네요. 
43번 조건문을 고려해봤을 때 최악의 경우는 39개의 nil을 가진 경우 겠네요 🧐

2023-01-26 15:47 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
queue 의 모든 요소를 제거해주는 메서드를 잘 정의 해주셨네요👍

2023-01-26 15:47 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
- setUpWithError() 와 tearDownWithError() 는 어떤 기능을 할까요?

2023-01-26 15:47 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
- 재정의 메서드에는 보통 부모 메서드를 호출 해주는데, 이유가 무엇일까요?

2023-01-26 15:47 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
given, when, then 세가지 상황으로 나누어 테스트를 진행 해주셨네요 👍

2023-01-26 15:47 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
`dequeue 호출 시 빈 배열을 반환한다`는 네이밍이 어색한 것 같아요. dequeue를 호출하면 1을 반환하게 될 것 같아요.
`dequeue 호출 시 data 배열은 빈 배열이 된다.` 이렇게 표현해주는 것이 더 좋을 것 같네요 🧐

2023-01-26 15:47 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
여기는 given, when, then 으로 나누어져 있지 않네요! 
또한 네이밍이 잘 이해되지 않는 것 같아요 `배열의nil값을포함하여_dequeue한다` 가 어떤 의미인가요?

2023-01-26 15:47 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var data: [T?] = []
제네릭 타입을 잘 활용 해주셧네요 👍 제네릭 타입을 이용하여 얻은 장점에는 무엇이 있었나요 ?

2023-01-26 15:47 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
배열이 비었나 확인하는 계산 프로퍼티군요👍

2023-01-26 15:47 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
first 와 last 프로퍼티는 계산기 프로젝트에서 어떻게 활용될 수 있을까요?

2023-01-26 15:47 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        // given
dequeue 실행 시 라고 해도 좋을 것 같아요.

2023-01-26 15:47 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
clearAll 메서드에 대한 테스트를 잘 해주셨네요 👍

2023-01-26 23:56 UTC, parkmuri commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
`test_data배열에_값이하나인상태에서_dequeue호출시_data배열은_빈배열이된다()`로 수정하였습니다!

07b8f7b781c6fecdc2c83e5c0af3e92d84f93f65

2023-01-26 23:59 UTC, parkmuri commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        // given
`test_data배열_dequeue실행시_first의인덱스를가르키는_head의값이증가한다()`로 수정하였습니다!

952bf146a767e0401048c3a2d32d0f81f2ebb3e0

2023-01-27 00:23 UTC, parkmuri commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
```swift
    mutating func dequeue() -> T? {
        guard head < data.count, let element = data[head] else { return nil }
        data[head] = nil
        head += 1
        
        let percentage = Double(head)/Double(data.count)
        
        if data.count >= 40 && percentage >= 0.25 {
            data.removeFirst(head)
            head = 0
        }
        
        return element
    }
```
- 현재 사용하고있는 dequeue 메서드입니다. dequeue시에 head의 값에 따라 배열의 요소에 nil을 할당하며 head를 옮겨 nil이 아닌 요소를 가리키게 하고있습니다.
- 중간 if문에 작성한 조건을 만족하게 되면 `removeFirst()`메서드를 이용하여 head가 가리키는 요소를 삭제하게되는데, 그 때 head 앞쪽의 nil값을 포함하여 삭제한다는 의미를 담고있었습니다!
#### 추가 수정내용
- dequeue로직을 마지막에 수정하다보니 수정한 `test_data배열에_값이하나인상태에서_dequeue호출시_data배열은_빈배열이된다()`의 테스트가 실패하는것을 보았습니다. (dequeue 수정 후 cmd+U로 테스트코드를 실행하지 않고 해당 테스트코드 거터로만 테스트를 한 결과같습니다😢...)
- 그래서 dequeue 시 해당 요소가 nil값으로 변환하는것을 검증하는 테스트코드로 변경하여 작성했습니다!
변경 전 `test_data배열에_값이하나인상태에서_dequeue호출시_data배열은_빈배열이된다()`
 변경 후 `test_data배열에_값이있는상태에서_dequeue호출시_값은nil이된다()`

402170ebe809324a7a32fd5ba80aa9238a3f52ea

2023-01-27 06:15 UTC, parkmuri commented
수정한 UML입니다!
![image](https://user-images.githubusercontent.com/115514179/215021569-52ab6ce4-d07f-4ac6-9beb-85f7d8bc34d3.png)

2023-01-27 07:37 UTC, parkmuri commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var data: [T?] = []
- 제네릭 타입을 이용하게되면 Any를 사용할 때보다 광범위하고 유연하게 사용할수 있다고 생각합니다. 
- 또 현재 코드에서는 CalculatorItemQueue의 인스턴스가 생성될 때 (Int나 String같은)타입이 정해지기 때문에 CalculatorItemQueue 내부에서 Element로 제네릭타입을 사용해준 부분은 정해진 타입으로만 비교할 수 있다는 장점도 있습니다!

2023-01-27 07:41 UTC, parkmuri commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
`struct`나 `enum`같은 `Value Type`은 값을 복사하여 사용하기때문에 인스턴스 메서드를 통해서 값을 변경할 수 없는데, `mutating`키워드를 통해서 해당 메서드가 인스턴스 내부의 값을 변경한다는것을 명시해줍니다!

2023-01-27 07:52 UTC, parkmuri commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
- `setUpWithError` : 각각의 test case가 실행되기 전마다 호출되어 각 테스트가 같은 상태와 조건에서 실행될 수 있도록 만들어 주는 메서드로 현재 코드에서는 큐의 인스턴스를 생성해줍니다.
`tearDownWithError`: 각각의 test 실행이 끝난 후마다 호출되는 메서드이고 setUpWithError()메서드에서 설정한 값들을 해제할 때 사용합니다. 생성한 sut의 인스턴스에 nil을 할당하여 해제하도록 만들고있습니다.

- 이미 재정의해버린 메서드에서 부모가 가진 메서드를 사용하고싶을때 `super`키워드를 이용하여 호출해 줍니다. 
테스트 코드에서는 굳이 호출할 필요가 없다고 생각하여 작성하지 않았습니다!

2023-01-27 10:07 UTC, parkmuri commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
- `first`와 `last`는 현재 배열 맨 첫번째 값과 맨 마지막 값을 반환하고있습니다. 

> peek() 메서드같은 경우에는 계산기에서 중간에 위치한 값을 꺼내서 사용할일이 없었다고 생각하여 포함하지 않았습니다. ~~peek은 맨 처음 값을 반환해주는 메서드지만~~ 
- `first`의 경우 test코드를 작성하며 dequeue가 확실하게 되었는지 확인하려고 사용하게 되었습니다. 위와같이 이야기해놓고 `peek`과 같은 기능을 하는 프로퍼티를 구현해놓았네요...! 
계산기에서 사용한다면 배열의 요소가 0인경우와 0이 아닌 경우를 판별해서 계산 로직을 다르게할 수 있을것같습니다. 
- `last`의 경우 현재 프로젝트에서는 사용하지는 않고있어 사실 삭제해도 무방할것같습니다. 
이에 대해 캠퍼들과 논의를 해봤는데... 계산기 프로젝트에서의 사용이라고 하면 `last`를 이용하여 계산기의 CE버튼을 구현하는데 사용할 수 있지 않을까요? 연산자를 누르기 전까지는 queue에 들어가지 않기 때문에 `last`는 존재하지 않아도 될까요?

- `first`를 `peek`으로 리네이밍하고, `last`는 선입선출해야하는 Queue랑은 어울리지않아 삭제해도 괜찮을것같다고 생각합니다...!

2023-01-27 10:56 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
잘 알고 계시는군요 👍 mutating 키워드를 사용했을 때 해당 프로퍼티가 내부적으로 어떻게 변경되는지에 대해서도 알아보시면 좋을 것 같아요 ☺️

2023-01-27 11:02 UTC, wongbingg commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
`배열의nil값을 삭제한다` 라는 네이밍이 더 자연스러운 것 같아요. 현재 dequeue 메서드는 T 타입을 반환하는데, nil을 포함하여 dequeue한다는 표현이 어색한거 같아요 😭

2023-01-27 11:04 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
사용하기 나름일 것 같아요~! 무리의 설계대로 진행하시면 될 것 같습니다 👍

2023-01-27 11:12 UTC, wongbingg commented
전반적으로 수정이 잘 이루어졌군요 👍 피드백 드린 점들에 대해서도 깊게 고민하신 흔적이 느껴집니다. UML 의 경우 CalculateItemQueue 가 CalculateItem 프로토콜을 채택하여 구현하는 관계로 표현된 것 같아요. 실제로는 CalculateItemQueue가 CalculateItem 을 채택하는 Element를 배열로 가지는 프로퍼티인 data: [Element] 를 가지는 관계이니 좀 더 나은 표현이 있을 것 같아요~! 한번 더 고민해보시고 step2에 적용 해주시면 좋을 것 같아요 ☺️

2023-01-27 11:13 UTC, merged