계산기 [STEP 1] Andrew
yagom-academy/ios-calculator-app pull request #424
Opened 2023-01-26 06:49 UTC by Andrew-0411

@Judy-999
안녕하세요 Judy 
자료구조가 너무 생소해서 이것저것 보고 실행해보느라 많이 늦었습니다.
잘 부탁드립니다!

## 고민했던점
1️⃣. Array와 List
- Array는 고정적인 index 값이 정해져 있기 때문에 요소를 찾을 때 효율이 좋고 List는 길이가 가변적이기 때문에 추가,삭제,수정 할때 효율이 좋다고 배웠습니다.
- 계산기는 연락처, 도서관에서 책 찾기 처럼 요소를 찾는다기보다는 추가,삭제 작업을 함으로 List 타입이 더 적합하다고 생각했습니다.

2️⃣. 제네릭타입과 Any 타입
- queue에 숫자와 부호를 담는다면 타입이 다른걸 한 array에 담아야 하기 때문에 제네릭과 any 타입이 생각났습니다.
- 제네릭은 언어가 제공하는 특징이고 any는 타입의 일종, 제네릭은 타입을 한정할 때 사용하고 any 타입은 모든 타입을 임의로 사용하기 위해 사용합니다.
- 제네릭 기반으로 생성된 타입은 특정 타입으로 정해져 있기 때문에 안전하게 사용할 수 있고, any 타입은 접근할 때 마다 타입 캐스팅을 해줘야 하는 번거로움이 있습니다.

## 조언이 필요한 부분
1️⃣. testCase
```swift
    private var queue: [T] = []
    
    mutating func enqueue(element: T) {
        queue.append(element)
    }
```
- enqueue라는 함수가 있습니다. 요소를 queue에 넣어주는 함수이고 testCase에서 테스트를 해보려고 하는데 잘 되지 않았습니다.
-  프로퍼티는 private으로 외부에서 접근을 막아주고 Method는 외부에서도 사용할 수 있도록 코드를 짜려고 하는데 다른 파일인 testCase에서 enqueue함수로 요소를 추가해도 queue 프로퍼티에 접근을 하지 못하였습니다.
- enqueue를 테스트를 하려면 어떤 방법을 써야할까요?

## UML
![UML](https://user-images.githubusercontent.com/45560895/214773964-7653ea4d-1784-4d9a-a68c-85be711088f3.jpg)

2023-01-27 06:03 UTC, Judy-999 requested changes
안녕하세요 Andrew! 로직의 세계 계산기 프로젝트로 오신걸 환영합니다  🤗

UML, 자료구조, Test 등 낯선 개념이 많으셨을 텐데 수고하셨습니다 👏👏 
어려우시더라도 차근 차근 이해해보면서 잘 진행해봅시다 💪

그리고 첫 리뷰이니 당부의 말씀을 드릴게요!

제가 드린 코멘트에 댓글로 어떻게 반영하셨는지 또는 의견을 달아주시면 제가 수정사항을 파악하기 용이합니다. 만약 큰 의미가 없는 코멘트라면 이모지만 달아주셔도 됩니다! 만약 제가 드린 코멘트가 잘 이해가 안가신다면 언제든 DM 주세요~
그리고 PR 이후와 모든 수정을 마친 후 DM을 주시면 빠르게 확인할 수 있습니다 🙌

제가 질문드리는 점은 반드시 고쳐야 한다고 둘러서 말하는게 아니라 정말 궁금하거나 의견을 묻는 경우도 있으니 반드시 수정(적용)하거나 잘못된 점이라고 생각하시지 않으면 좋겠네요!
제 의견을 무조건 수용하시기보다 Andrew의 이유로 결정하는게 더 좋습니다 🙂

저는 Andrew의 코드를 평가하거나 잘못된 점을 지적하는 사람이 아닙니다!
같이 코드를 고민하는 역할로 더 좋은, Andrew의 이유가 있는 코드를 완성하는 데에 도움이 되면 좋겠습니다 😊

---

## 고민했던점
### Array와 List
> - Array는 고정적인 index 값이 정해져 있기 때문에 요소를 찾을 때 효율이 좋고 List는 길이가 가변적이기 때문에 추가,삭제,수정 할때 효율이 좋다고 배웠습니다.
> - 계산기는 연락처, 도서관에서 책 찾기 처럼 요소를 찾는다기보다는 추가,삭제 작업을 함으로 List 타입이 더 적합하다고 생각했습니다.

List의 개념이 무엇인지 생각해보셔야할 것 같아요. 다른 언어에는 `List`라는 배열과 구분되는 자료형이 있지만 자료구조에서는 단지 **순서를 가지고 일렬로 나열한 원소들의 모임**입니다.

Swift에서는 Array 역시 List의 한 종류로 볼 수 있습니다! 즉 Array와 List에서 선택하는 것이 아닌 List를 배열 방식으로 구현할지, 배열 방식이라면 배열을 몇 개를 사용할지 아니면 Linked List 방식으로 구현할지 고민해보셔야 할 것 같네요 🙂

현재는 하나의 Array List를 사용한 방식을 선택한 것으로 보이네요! 다른 방식의 장단점도 찾아보시고 여력이 있으시다면 `더블 스택`이나 `Linked List` 방식도 적용해보시면 좋습니다. 물론 현재 방식으로 충분하다고 여기시면 반드시 적용할 필요는 없습니다~
<br>

### 제네릭타입과 Any 타입
> - queue에 숫자와 부호를 담는다면 타입이 다른걸 한 array에 담아야 하기 때문에 제네릭과 any 타입이 생각났습니다.
> - 제네릭은 언어가 제공하는 특징이고 any는 타입의 일종, 제네릭은 타입을 한정할 때 사용하고 any 타입은 모든 타입을 임의로 사용하기 위해 사용합니다.
> - 제네릭 기반으로 생성된 타입은 특정 타입으로 정해져 있기 때문에 안전하게 사용할 수 있고, any 타입은 접근할 때 마다 타입 캐스팅을 해줘야 하는 번거로움이 있습니다.

[제네릭](https://docs.swift.org/swift-book/LanguageGuide/Generics.html)은 타입을 한정할 때 사용하는 것이 아니라 오히려 모든 타입에서 작동할 수 있는 유연하고 재사용 가능한 함수 및 타입을 만드는 것입니다!

하지만 계산기 큐는 숫자와 부호만 담아야겠죠? 요구사항에서도 `CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다`라고 되어 있는 점을 생각하시면 `CalculateItem`을 사용해서 타입을 제한할 수 있을 것 같네요 🙌
<br>

## 조언이 필요한 부분
> - enqueue라는 함수가 있습니다. 요소를 queue에 넣어주는 함수이고 testCase에서 테스트를 해보려고 하는데 잘 되지 않았습니다.
> - 프로퍼티는 private으로 외부에서 접근을 막아주고 Method는 외부에서도 사용할 수 있도록 코드를 짜려고 하는데 다른 파일인 testCase에서 > - enqueue함수로 요소를 추가해도 queue 프로퍼티에 접근을 하지 못하였습니다.
> - enqueue를 테스트를 하려면 어떤 방법을 써야할까요?

프로퍼티는 가능한 외부의 접근을 차단하는 것이 좋습니다. 하지만 테스트를 위해 접근이 필요하다면 어느 정도 제한을 풀어줄 수 있습니다. 값을 읽는건 가능하지만 수정에 대해서는 제한하는 것이죠! 이런 방식으로 하면 테스트 가능할 것 같네요 🙂
<br>

## UML
`CalculateItem`과 `CalculatorItemQueue` 연관을 가진 것 처럼 표현되고 있는데 둘의 관계를 고민해보시고 수정한 후 UML에도 표현해보세요!
<br>

## Text
현재는 모든 기능에 대해서 테스트되고 있지 않네요. 모든 기능(=메서드 또는 프로퍼티)에 대해, 기능의 흐름에 대해 테스트 해보시면 좋겠습니다.
테스트 케이스는 일반적인 상황, 에러가 발생할 수 있는 상황, 경계에 있는 상황(=엣지 케이스)가 될 수 있습니다!

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
`CalculatorItemQueue`을 sturct로 구현하신 이유가 있을까요?

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
제네릭으로 여러 타입을 사용할 수 있게 한 점 좋네요 👍
다만 `T`로 통용해서 사용하긴 하지만 어떤 의미로 사용되는지 이름을 지어주시면 좋겠네요!

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
`CalculatorItemQueue`이 `CalculateItem`을 채택하고 있네요. `CalculateItem`은 어떤 역할을 하고 있을까요? 
어떤 타입이 `CalculateItem`을 채택해야 하는지 고민해보시면 좋겠습니다 🙂

참고로 요구사항에서는 `CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다.`라고 되어 있네요!

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
`mutating`은 어떤 의미이고, 어떤 이유에서 사용하셨나요?
`mutating`이 반드시 필요한지도 고민해보세요~

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    private var queue: [T] = []
`CalculatorItemQueue` 자체가 큐인데 `queue`를 프로퍼티로 가지는 건 어색한 것 같아요 🤔
요구사항에 있는 `CalculatorItemQueue의 내부에서 사용하는 List 형식의 자료구조`라는 구문을 참고하셔서 네이밍을 고민해보시면 좋겠습니다!

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
`searchQueue`는 어떤 용도의 사용을 예상하시고 구현하신 걸까요?

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +final class CalculatorTests: XCTestCase {
`final`의 사용 좋습니다 👍👍

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    var sut: CalculatorItemQueue<Any>!
모든 타입이 가능한 `Any`보다는 현재 숫자인 `Int`를 사용해 테스트하고 계시니 `Int`로 선언하는게 좋겠습니다!

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
`setUpWithError`와 `tearDownWithError`는 각각 어떤 역할을 하나요?

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
`override`로 재정의할 때 잊지 말아야 할 단계가 있습니다! 생각해보시고 처리해주세요 🙌

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열일경우_isEmpty에서_true값을반환하는함수() {
테스트 메서드명을 한글로 작성하신 이유가 있을까요?

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertTrue(sut.isEmpty())
`given-when-then`의 구성 좋습니다 👍
각 구성마다 개행을 넣어주시면 더 보기 편할 것 같네요!

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열일경우_isEmpty에서_true값을반환하는함수() {
`빈배열일경우`는 모호한 상황 같아요. 

아래의 경우 모두 `isEmpty`가 true가 돼야 할 텐데, 어떤 상황인지 정확히 표현하고 모든 상황이 테스트 되고 있는지 확인해보세요 🙂
- 처음 생성한 경우
- 모든 값을 dequeue한 경우
- `clearQueue()`를 실행한 경우

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열일경우_isEmpty에서_true값을반환하는함수() {
`true값을반환하는함수`라고 하면 해당 함수가 어떤 값을 반환할 것 같아요 😅
`true`가 나오는지 확인한다는 의미가 담기면 좋겠네요!

2023-01-27 06:03 UTC, Judy-999 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열에서_요소를삭제를시도할경우_nil값반환하는함수() {
요소 삭제라고 하면 `clearQueue()`를 테스트하는 건가 혼동할 수 있을 것 같아요.
테스트 메서드명에 어떤 메서드(또는 연산 프로퍼티)를 테스트하는지 명시되면 좋겠습니다!

2023-01-28 07:08 UTC, Andrew-0411 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
Struct와 Class는 공통된 기능이 많은데 Class 만이 사용할 수 있는 기능 (Inheritance, 소멸자를 이용한 Instance 해제, 참조횟수를 둘 이상 허용 등)을  CalculatorItemQueue에서는 사용하지 않을거 같아서 Struct를 사용했습니다

2023-01-28 08:15 UTC, Andrew-0411 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
처음에 enqueue함수를 작성할 때 mutating없이 사용했고 Xcode가 고쳐주어서 그냥 사용했었습니다. 😅
나머지 Method도 빨리 작성해야지 하는 마음에 첫번째 작성한 Method를 복붙하느라 필요하지도 않은 부분에 사용되었네요 😔

Struct는 값 타입이고 값타입의 Property를 수정하려면 mutating을 사용해야 합니다.
하지만 isEmpty 함수는 값을 변경하기보다는 값의 상태를 확인만 하는 함수여서 mutating이 필요치 않아서 삭제하였습니다

2023-01-29 09:59 UTC, Andrew-0411 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
객체를 생성할때 T자리에 타입을 적어주기 때문에 ex) CalculatorItemQueue<Int>() T대신에 dataType으로 변경해 주었습니다

2023-01-29 18:57 UTC, Andrew-0411 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    private var queue: [T] = []
node라는 네이밍 생각했지만 doubleStack방법으로 변경하였으므로 enqueueStack dequeueStack으로 네이밍을 변경하였습니다.

2023-01-29 19:03 UTC, Andrew-0411 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
Queue의 맨 앞에 있는 값을 반환해주는 기능으로 만든것인데 Queue의 Method 중에서 이걸 peek이라고 하는거 같습니다.
이것도 값을 변경하는게 아니기 때문에 mutating을 빼고 peek이라고 이름을 변경하였습니다

2023-01-29 21:47 UTC, Andrew-0411 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
setUpWithError: 각각의 테스트 케이스가 실행되기 전마다 호출됩니다. 주로 테스트마다 같은 조건에서 실행할 수 있도록 객체를 초기화 해주는 작업을 합니다.
tearDownWithError:  각각의 테스트 케이스가 끝날때 마다 호출됩니다 주로 설정한 값들을 해제해 주는 작업을 합니다

2023-01-29 21:52 UTC, Andrew-0411 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    }
override 하고나서 super 를 사용해서 상속받은것들을 호출한 다음에 제가 변경하고 싶은 값을 적어야 값을 덮어쓸 수 있다라고 생각해서 
각각의 메서드에 try super.setUpWithError()와 try super.tearDownWithError()을 사용했습니다

2023-01-29 21:55 UTC, Andrew-0411 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열일경우_isEmpty에서_true값을반환하는함수() {
Unit Test의 경우 App의 실제 빌드할때 사용하는 코드가 아닌 test를 하기 위한 코드여서 주석? 같은 의미로 알아보기 쉽게 한글로도 작성하는 방법도 있다고 해서 한글로 작성해 보았습니다 🥺

2023-01-29 22:40 UTC, Andrew-0411 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
계산기에서 사용할 버튼들 (피연산자와 연산자)가 CalculateItem에 들어갈거 같습니다.
피연산자와 연산자는 타입이 각각 Double과 String으로 타입이 다를거 같으므로 제네릭 타입으로 CalculateItem 프로토콜을 채택하였습니다.

2023-01-29 22:53 UTC, Andrew-0411 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열일경우_isEmpty에서_true값을반환하는함수() {
ㅇㅇㅇ ㅇㅇㅇ ㅇㅇㅇ true를확인하는함수() 로 변경해봤습니다! 🤔

2023-01-29 23:18 UTC, Andrew-0411 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_빈배열일경우_isEmpty에서_true값을반환하는함수() {
말씀하신대로 3가지 testCase를 작성해 봤습니다

2023-01-29 23:31 UTC, Andrew-0411 commented
1. 이번 계산기 프로젝트는 List를 사용할건데 순차리스트(array) 방식으로 구현할 것인지 연결리스트(Linked List) 방식으로 구현할 것인지 선택하고 queue를 구현할건데 그냥 queue로 구현할것인지 DoubleStack으로 구현할것인지 선택한다고 보면 될까요?

2. 계산기 프로젝트가 배열의 원소를 앞이나 중간에서 삽입,삭제해서 원소를 앞뒤로 이동하는 일이 없고 뒤에서만 값의 삽입 삭제가 된다고 생각해서 순차리스트를 선택했는데 타당한 선택일까요?

3. 일반 queue로 작성하면 dequeue할 때 시간복잡도가 O(n)이 되므로 더블스택을 사용하여 dequeue에서도 Stack의 기능인 pop를 사용하여 시간복잡도를 O(1) 줄일 수 있기 때문에 일반 Queue방식에서 더블스택 방식으로 변경하였습니다.

4. 만약 연산자 우선순위 까지 구현한다고 가정한다면 우선순위를 `탐색` 해야 하기 때문에 연결리스트 방식보다 순차리스트가 더 좋은 선택지 일까요? 아니면 제가 `탐색`을 잘못 이해하고 있는걸까요?

5. UML을 관계에 따른 화살표를 잘못 그렸던점과 프로퍼티와 메서드를 변경으로 인해 UML을 수정했습니다.

2023-01-30 02:20 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
우선 타입을 의미하기 때문에 대문자로 시작하게 해주세요!

**데이터 타입을 받는다**는 범용성이 크니 **계산기 큐의 요소 타입을 받는다**에 의미를 두어 `Item`이나 `Element` 처럼 요소를 뜻하는 단어면 좋을 것 같네요 🙂

2023-01-30 02:57 UTC, Judy-999 approved these changes
> 이번 계산기 프로젝트는 List를 사용할건데 순차리스트(array) 방식으로 구현할 것인지 연결리스트(Linked List) 방식으로 구현할 것인지 선택하고 queue를 구현할건데 그냥 queue로 구현할것인지 DoubleStack으로 구현할것인지 선택한다고 보면 될까요?

Stack은  한 쪽 끝에서만 자료를 넣거나 뺄 수 있는 선형 구조 **(LIFO - Last In First Out)** 역시 List의 한 종류로 볼 수 있습니다.

현재는 Array를 사용해 Stack처럼 동작하도록 구현하시고, 그러한 Stack을 두 개 사용하는 방식을 선택하신거죠!

궁극적인 목표는 Queue를 구현하는 것이고 Queue를 구현하기 위해 사용하는 List 중 더블 스택, 연결 리스트 등이 있는 걸로 생각하시면 됩니다.
<br>

> 계산기 프로젝트가 배열의 원소를 앞이나 중간에서 삽입,삭제해서 원소를 앞뒤로 이동하는 일이 없고 뒤에서만 값의 삽입 삭제가 된다고 생각해서 순차리스트를 선택했는데 타당한 선택일까요?

계산기 프로젝트에서는 결국 Queue를 사용하는 것입니다! [Queue](https://ko.wikipedia.org/wiki/%ED%81%90_(%EC%9E%90%EB%A3%8C_%EA%B5%AC%EC%A1%B0))는 먼저 집어 넣은 데이터가 먼저 나오는 **FIFO(First In First Out)** 구조로 `중간에서 삽입,삭제해서 원소를 앞뒤로 이동하는 일`은 불가합니다.

계산을 위해 왜 Queue 자료구조를 사용하는지 먼저 고민해보시고, 그런 Queue를 구현하기 위해서는 어떤 List로 구성하는게 좋은가 하는 생각의 흐름으로 고민해보시면 좋겠습니다 🙂
<br>

> 일반 queue로 작성하면 dequeue할 때 시간복잡도가 O(n)이 되므로 더블스택을 사용하여 dequeue에서도 Stack의 기능인 pop를 사용하여 시간복잡도를 O(1) 줄일 수 있기 때문에 일반 Queue방식에서 더블스택 방식으로 변경하였습니다.

👍
<br>

> 만약 연산자 우선순위 까지 구현한다고 가정한다면 우선순위를 탐색 해야 하기 때문에 연결리스트 방식보다 순차리스트가 더 좋은 선택지 일까요? 아니면 제가 탐색을 잘못 이해하고 있는걸까요?

우선 탐색은 찾고자 하는 자료가 있는지 확인하는 것, 어느 위치에 있는지 알아내는 것 정도로 생각하시면 됩니다. 우선순위는 탐색한다기 보다 비교하는 쪽이 맞지 않을까 싶네요 🤔

어떤 자료구조를 선택할지는 기본적으로 `삽입, 삭제, 탐색`에서 코드의 복잡성, 시간 및 공간 복잡도 등의 기준을 생각해볼 수 있습니다. 현재 목적이 Queue를 구현하기 위한 것이니 Queue의 특성에 따라서 무엇에 중점을 두어야 하는지 고려하고 더불어 해당 Queue를 계산 용도로 사용할 것이니 계산 시 어떤 동작이 중요한지를 비교해볼 수 있습니다. 또한 해당 구조를 내가 얼마나 이해하고 사용할 수 있는지 난이도 역시 중요한 기준이 될 수 있죠! 이런 기준들을 비교해서 적절한 구조를 선택하시면 됩니다.
<br>

> UML을 관계에 따른 화살표를 잘못 그렸던점과 프로퍼티와 메서드를 변경으로 인해 UML을 수정했습니다.

CalculatorItemQueue가 직접적으로 CalculateItem를 채택한 것은 아니니 제네릭 타입을 적용한 것을 표현해주시면 명확할 것 같네요!

---

수고하셨습니다 👏 추가로 남긴 코멘트에서 수정하실 부분이 있다면 다음 스텝에서 같이 진행해주세요~!

2023-01-30 02:57 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
매개변수를 받지 않고 특정한 값만 반환하는 메서드라면 연산 프로퍼티를 적용해도 좋겠네요 🙂

2023-01-30 02:57 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
좋습니다 👍 계산기 큐에서 어떤 용도로 사용할지도 예상하시고 구현하시면 좋겠네요!
당장 필요성이 없다면 미리 구현하실 필요는 없습니다 🙂

2023-01-30 02:58 UTC, merged