계산기 [STEP 1] Christy
yagom-academy/ios-calculator-app pull request #426
Opened 2023-01-27 05:13 UTC by christy-hs-lee

@wongbingg
안녕하세요 웡빙 크리스티입니다! 
제가 부족함이 많아 스텝을 본격적으로 시작하기 전 학습할 부분들이 많았습니다.
그래서 첫 PR이 다소 늦어졌습니다😥 
이번 프로젝트 리뷰 잘 부탁드리겠습니다!!

## 고민한 부분
### 자료구조와 Queue의 구현 방법
이번 스텝을 시작하며 가장 먼저 학습한 부분입니다. 
Queue를 구현하는 방법으로 `Array`, `Double Stack`, `Linked List`가 있음을 알았습니다. 각 구현 방식에 따른 장점과 단점을 비교하며 가장 이상적인 `Linked List`를 사용하여 구현하고자 했습니다. 하지만 학습이 많이 부족한 탓에 완성된 결과물을 만들 수 없었습니다😥 그래서 우선적으로 `Array`를 사용하여 구현했습니다. 추후 `Linked List`에 대한 학습을 충분히 진행하고 리팩토링하고 싶습니다.

### Class와 Struct
`CalculatorItemQueue`를 구현하기에 앞서 가장 먼저 한 고민은 "`class`와 `struct`중 어떤걸 사용할까?" 였습니다. 하지만 공식 문서를 참고하여 상속, 참조가 사용되지 않아 `CalculatorItemQueue`를 `struct`로 구현했습니다.

### TDD 작성법
처음 TDD를 사용하여 코드를 작성하다 보니 진행 과정과 순서에 많은 어려운이 있었습니다. 감이 잡히지 않아 많이 헤매고 시행착오를 겪었습니다. 아직도 많이 낯선 과정이지만 해당 프로젝트를 수행하며 배워나가려고 합니다!

---

## 조언을 얻고 싶은 부분
### 자료구조와 Queue의 구현 방법
프로젝트 핵심경험을 참고하여 추후 Linked List로 리팩토링을 시도하고 싶습니다! 그러나 아직 코드에 적용시켜 다음 단계로 나아갈 수 있는 수준은 아니라고 판단이 됩니다. 이런 상황에서 우선은 Array를 사용하여 프로젝트를 계속 진행해야 하는지, 아니면 도전 정신을 발휘하여 시도를 해야 하는지 고민입니다. 모든 일에는 우선 순위가 있는데, 이번에는 어떻게 판단해야 하는지 많이 고민이 됩니다!😥

### TDD 작성 과정
이번에 TDD를 처음 접하면서 많은 고민이 있었습니다. 어떤 부분을 고려해야 하는지, 경계값은 어떻게 설정해야 하며, 이런 부분까지 고민해야 하는지(적절함의 수준)등 많은 고민을 했습니다. 또한 이를 활용하여 코드를 작성함에 있어 고민하는 과정이 많이 어려웠습니다. 이런 부분에 있어 웡빙의 TDD 작성 과정과 핵심적으로 고민하는 포인트에 대해 듣고 싶습니다!

2023-01-27 08:25 UTC, wongbingg commented
안녕하세요 크리스티~! 계산기 프로젝트 Step1 고생하셨습니다 ☺️

## UML

<image src="https://user-images.githubusercontent.com/61936306/215018768-7a3902c4-a600-413c-a919-e43b6f02d444.png" width="300">

    
</br>

UML 을 색별로 잘 나타내 주셨네요. 프로토콜을 채택한다는 화살표모양도 잘 나타내주셨습니다👏
- data 프로퍼티는 어떤 타입인지 표시되어있지 않은 것 같아요.
- `CalculatorItemQueue에서 다루는 요소는 CalculateItem 프로토콜을 준수합니다.` 요구사항에 맞게 프로토콜을 채택했는지 다시한번 고민 해볼까요? 

## ✅ 고민한 부분에 대하여
### 자료구조와 Queue의 구현 방법
>이번 스텝을 시작하며 가장 먼저 학습한 부분입니다. 
Queue를 구현하는 방법으로 `Array`, `Double Stack`, `Linked List`가 있음을 알았습니다. 각 구현 방식에 따른 장점과 단점을 비교하며 가장 이상적인 `Linked List`를 사용하여 구현하고자 했습니다. 하지만 학습이 많이 부족한 탓에 완성된 결과물을 만들 수 없었습니다😥 그래서 우선적으로 `Array`를 사용하여 구현했습니다. 추후 `Linked List`에 대한 학습을 충분히 진행하고 리팩토링하고 싶습니다.

- 각 자료구조의 장단점은 어떤 것이 있었고 어떤 이유로 Linked List 가 가장 이상적이라고 생각하셨나요 ? 

### Class와 Struct
>`CalculatorItemQueue`를 구현하기에 앞서 가장 먼저 한 고민은 "`class`와 `struct`중 어떤걸 사용할까?" 였습니다. 하지만 공식 문서를 참고하여 상속, 참조가 사용되지 않아 `CalculatorItemQueue`를 `struct`로 구현했습니다.

값타입과 참조타입을 잘 구분지어 선택 해주셨네요 👍

### TDD 작성법
>처음 TDD를 사용하여 코드를 작성하다 보니 진행 과정과 순서에 많은 어려운이 있었습니다. 감이 잡히지 않아 많이 헤매고 시행착오를 겪었습니다. 아직도 많이 낯선 과정이지만 해당 프로젝트를 수행하며 배워나가려고 합니다!

좋습니다. 처음부터 잘할 수는 없는 것 같아요. TDD를 처음 작성해보는 만큼 많은 시행착오를 겪어봐야 한다고 생각해요 🧐


## ✅ 조언을 얻고 싶은 부분에 대하여
### 자료구조와 Queue의 구현 방법
>프로젝트 핵심경험을 참고하여 추후 Linked List로 리팩토링을 시도하고 싶습니다! 그러나 아직 코드에 적용시켜 다음 단계로 나아갈 수 있는 수준은 아니라고 판단이 됩니다. 이런 상황에서 우선은 Array를 사용하여 프로젝트를 계속 진행해야 하는지, 아니면 도전 정신을 발휘하여 시도를 해야 하는지 고민입니다. 모든 일에는 우선 순위가 있는데, 이번에는 어떻게 판단해야 하는지 많이 고민이 됩니다!😥

LinkedList 구현을 다른 테스트프로젝트에서 진행을 해본 뒤, 완성되면 적용 해주어도 좋을 것 같아요! CalculatorItemQueue 는 FIFO(First In First Out)특성과 명시된 기능(enqueue, dequeue 등등)만 하면 되니, 그 내부구현은 어떻게 바뀌던 상관 없을 것 같아요. 추후 리팩토링 하는데에 어려움이 없을 것 같습니다 ☺️ 그러니 지금은 이대로 진행을 해봐도 좋을 것 같아요 !

### TDD 작성 과정
>이번에 TDD를 처음 접하면서 많은 고민이 있었습니다. 어떤 부분을 고려해야 하는지, 경계값은 어떻게 설정해야 하며, 이런 부분까지 고민해야 하는지(적절함의 수준)등 많은 고민을 했습니다. 또한 이를 활용하여 코드를 작성함에 있어 고민하는 과정이 많이 어려웠습니다. 이런 부분에 있어 웡빙의 TDD 작성 과정과 핵심적으로 고민하는 포인트에 대해 듣고 싶습니다!

아직 엣지케이스에 대해 익숙하지 않아 어떤 테스트를 해야할지 감이 잡히지 않을 것 같아요. 실제 이 큐가 사용될 목적에 따라 엣지 케이스를 정해줄 수 있을 것 같아요. `큐가 비어있을 때 dequeue를 하는 경우`, 만약 큐의 크기를 제한해놓았다면 `큐의 크기가 최대크기일 때 enqueue를 하는 경우` 등 극단적인 테스트케이스를 만들어보면 좋을 것 같아요. 

지금은 처음 접하는 부분이니 크리스티 하고싶으신대로 테스트를 진행을 해보셔도 좋을 것 같아요. 그러다 보면 같은 주제로 묶이게 되는 테스트들을 발견하실 수 있을 거에요.

2023-01-27 08:53 UTC, wongbingg requested changes

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculateItem.swift
> +}
요구사항에 맞게 빈 프로토콜 구현을 잘 해주셨네요 👏

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T> {
제네릭 타입을 이용하셨군요 ! 
- 제네릭 타입을 이용해서 얻을 수 있는 장점은 무엇이 있을까요?

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var data = [T] ()
- 이 data 프로퍼티는 외부에서 접근이 가능한 프로퍼티인가요 ?
- 보통 배열의 초기화는 이렇게 공백을 주지 않고 작성을 한답니다
    ```suggestion
        var data = [T]()
    ```

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +
- 이 이니셜라이저는 어떤 역할을 위해 존재하나요? 
- 이 이니셜라이저가 없다면 어떻게 될까요 ?

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
큐 내부 요소의 개수를 반환해주는 계산 프로퍼티군요 👍

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
큐가 비었는지 확인해주는 메서드이군요👍

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
isEmpty 라는 네이밍은 `함수의 네이밍은 동사로 시작하는 Swift API Guideline 의 메서드 네이밍 컨벤션` 에 어긋나는 것 같아요. 
isEmpty를 계산프로퍼티로 만들면 조금 더 자연스러울 것 같습니다☺️

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
삼항연산자를 잘 활용해주셨네요 👍

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
큐 내부 모든 요소를 제거하는 메서드이군요👍

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
배열의 removeFirst() 라는 함수는 `시간 복잡도`가 어떻게 될까요 ?
removeLast() 메서드의 `시간복잡도`와 비교 해볼까요?

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
mutating 키워드는 어떤 의미일까요?

2023-01-27 08:53 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
- tearDownWithError 메서드와 다르게 15번줄의 개행이 들어간 이유가 있을까요 ?

2023-01-27 08:53 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
- setUpWithError() 메서드는 어떤 기능을 할까요?

2023-01-27 08:53 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
- tearDownWithError() 메서드는 어떤 기능을 할까요?

2023-01-27 08:53 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
given , when, then 으로 상황을 나누어 테스트를 해주셨네요 👏

2023-01-27 08:53 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
네이밍을 보았을 때, enqueue 함수가 어떤 값을 반환하는 것인가? 하는 생각이 들어요.
`enqueue 함수가 수행되면 큐의 마지막 부분에 요소가 추가된다` 이런 네이밍이 더 적절해 보이네요!

2023-01-27 08:53 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +final class CalculatorItemQueueTests: XCTestCase {
테스트 코드는 협업하는 다른 개발자가 볼 수 있는 기능명세서의 역할을 한다고 생각해요. 
각 기능에 대한 구체적인 테스트케이스를 작성함으로써  협업자는 이러한 기능이구나 라는 것을 알 수 있죠
그만큼 테스트케이스의 네이밍도 중요하고, 컨벤션을 맞춰주는 것도 중요하다고 생각합니다. 
크리스티의 테스트케이스는 전반적으로 네이밍이 잘 되어있어 쭉쭉 이해가 잘 되었습니다 ☺️

2023-01-27 08:53 UTC, wongbingg commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
두 가지 결과를 잘 테스트 해주셨군요 👍

2023-01-27 08:53 UTC, wongbingg commented on Calculator/Calculator/CalculateItem.swift
> +}
이 CalculatorItem 이라는 프로토콜은 어떤 타입이 채택해야 할까요?

2023-01-28 12:53 UTC, christy-hs-lee commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T> {
제네릭 타입을 사용하면 코드의 재사용이 높아지고 런타입 오류를 줄일 수 있어 안정성이 높아입니다. 또한 타입을 명확히 알 수 있어 코드의 가독성이 높아집니다!

2023-01-28 13:00 UTC, christy-hs-lee commented on Calculator/Calculator/CalculateItem.swift
> +}
`CalculateItemQueue`가 채택하도록 해야합니다!

2023-01-28 13:13 UTC, christy-hs-lee commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var data = [T] ()
현재는 외부에서 접근이 가능하지만 이 부분은 외부에서 접근하지 않아도 될 것 같습니다. 다음 스텝을 진행하며 `private (set)` 을 적용하겠습니다! 공백의 경우 제거했습니다!

2023-01-28 13:17 UTC, christy-hs-lee commented on Calculator/Calculator/CalculatorItemQueue.swift
> +
`init()`은 값의 초기화를 위해 존재하고 있습니다. 현재 단계에서는 `init()`의 역할이 없다고 생각합니다. 하지만 추후 `data`타입에 `private (set)`으로 접근을 제어할 경우 외부에서 값을 변경할 수 없게 되므로 해당 부분에서 이니셜라이저를 생성해줘야 합니다!

2023-01-28 14:09 UTC, christy-hs-lee commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
`removeFirst()`의 경우 시간 복잡도가 O(n) `removeLast()`의 경우 O(1)입니다. 이럴 경우 처리할 데이터가 늘어나면 `removfirst()`를 사용했을 때 시간이 오래 걸릴 수 있다고 생각이 듭니다. 이를 위해 `removeLast()`를 사용하는 방법을 생각해 보았는데, `reversed()`를 사용하는 방법을 찾았습니다. 하지만 `reversed()`의 시간 복잡도 또한 O(n)이라 과연 의미가 있을까 하는 고민을 했습니다. 이 부분에 대해서 명확한 방향이 아직 잡히지 않아 질문을 드리고 싶습니다!

2023-01-28 14:13 UTC, christy-hs-lee commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
`mutating`은 구조체나 열거형 타입의 메소드나 프로퍼티를 선언할 때 사용되는 키워드입니다. `mutating` 키워드를 사용하면 메소드나 프로퍼티는 구조체나 열거형 타입의 인스턴스 내부의 값을 변경할 수 있는 권한을 갖게 됩니다. 이를 사용하여 구조체나 열거형 타입의 인스턴스의 값을 변경할 수 있는 메소드나 프로퍼티를 정의할 수 있습니다!

2023-01-28 14:21 UTC, christy-hs-lee commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
`setUpWithError()` 메서드는 XCTestCase 클래스의 메서드로, 테스트 케이스를 실행하기 전에 필요한 설정을 하는데 사용됩니다. 이 메서드를 오버라이드해서 테스트 케이스를 실행하기 전에 필요한 데이터나 객체를 생성하거나 초기화 할 수 있습니다. 만약 `setUpWithError()` 메서드에서 error를 발생시키면 해당 테스트 케이스는 실행되지 않습니다!

2023-01-28 14:29 UTC, christy-hs-lee commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
`tearDownWithError()` 메서드는 XCTestCase 클래스의 메서드로, 테스트 케이스를 실행하고 나서 필요한 정리 작업을 하는데 사용됩니다. 이 메서드를 오버라이드해서 테스트 케이스를 실행한 뒤 필요한 정리 작업을 할 수 있습니다. 예를 들어, 생성한 객체나 사용한 리소스를 해제하는 작업을 수행할 수 있습니다. `tearDownWithError()` 메서드에서 error를 발생시키면 해당 테스트 케이스는 실행되지 않습니다!

2023-01-28 14:30 UTC, christy-hs-lee commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
해당 부분 수정 완료했습니다!

2023-01-28 16:20 UTC, christy-hs-lee commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
해당 부분 계산 프로퍼티로 수정 완료했습니다!

2023-01-30 04:07 UTC, wongbingg commented on Calculator/Calculator/CalculateItem.swift
> +}
`CalculatorItemQueue에서 다루는 요소` 가 CalculateItemQueue 를 채택하도록 해야할 것 같아요. 이 요소는 어떤 타입인지 확인 해볼까요 ?

2023-01-30 04:10 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +
structure 의 `memberwise initializer` 에 대해서 알아보시면 좋을 것 같아요~! 알아보신 내용은 간단하게 다음 스텝 pr 에 함께 보내주세요 ☺️

2023-01-30 04:18 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
좋은 접근을 해주셨네요~!👍👍 다만 `reverse()` 메서드와 혼동이 있으셨던 것 같은데요, `reversed()` 메서드의 복잡도는 O(1) 이라고 문서에 나와있어요. 이 두 메서드 `reverse()` `reversed()` 의 차이점에 대해 알아보시면 좋을 것 같아요~! ☺️


- [apple Docs - reversed](https://developer.apple.com/documentation/swift/array/reversed())

2023-01-30 04:20 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
removeLast() 메서드와 reversed() 메서드를 적절히 활용하면 더블스택을 만들어볼 수 있을 것 같아요 🧐

2023-01-30 04:30 UTC, wongbingg commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
아래 공식문서에서 `Modifying Value Types from Within Instance Methods` 부분을 보시면 좋을 것 같아요~!
`mutating` 키워드로 프로퍼티를 선언할 수 있을까요? 직접 실험해보면 좋을 것 같아요 🧐
- [Swift Programming Language Guide - Methods](https://docs.swift.org/swift-book/LanguageGuide/Methods.html)

2023-01-30 04:32 UTC, wongbingg commented
전반적으로 수정이 잘 되었네요 ☺️ 다만 드렸던 질문에 대한 답변이 아직 완벽하지 않은 부분에 대해서는 다시 코멘트를 달아두었어요~! 다음 스텝 진행 하시면서 추가적으로 학습해보시면 좋을 것 같아요 👍 

이번 스텝은 머지하도록 하겠습니다 고생하셨어요 👏

2023-01-30 04:33 UTC, merged