계산기 [Step2] Harry
yagom-academy/ios-calculator-app pull request #427
Opened 2023-01-27 12:16 UTC by HarryHyeon

@llingo 
링고 스텝2 구현을 완료하고 PR 요청드립니다!
이번에도 잘 부탁드리겠습니다  😃 

## 클래스 다이어그램
![](https://i.imgur.com/uJXTlhg.png)

## 조언받고싶은 점
### 왜 메서드명이 'componentsByOperators' 일까..
- 해당 메서드에서 메서드명을 해석해보자면 연산자를 기준으로 문자열을 짤라주는 역할을 한다고 느꼈습니다.
- 그런데 이때, 짜르면서 연사자를 버리느냐 아니면 연산자 또한 String 배열로 묶여서 반환해주냐 이것이 고민 되었습니다.
- 저는 메서드명이 해석하기 나름이라 생각되어서 꼭 문자열에서 연산기호를 제외할 필요가 없다고 느꼈습니다.
- 연산자를 제외한다면 원본 문자열에서 다시 또 연산자를 추출해서 연산자큐에 넣어주는 불필요한 작업을한다고 느껴서 문자가 공백을 뒤에 두고 계속해서 들어온다고 가정하고 코드를 작성하게되었습니다.

``` swift
private static func componentsByOperators(from input: String) -> [String] {
        let components = input.split(with: " ")
        
        return components
    }
```
- 이런식으로 코드를 작성해도 요구사항에 벗어나지 않는 건지 의견이 궁금합니다.

2023-01-29 02:28 UTC, llingo requested changes
안녕하세요, Harry
벌써 STEP 2 PR을 주셨네요. 좋은 속도입니다
이번 스텝은 UML을 파악하고 단순 구현의 느낌이었네요. UML을 보면서 구현하는 것은 어떠셨나요?

특히 `nan` 예외 처리와 고차함수를 잘 사용하신 부분이 좋았습니다

이번 스텝은 크게 수정해야할 부분이 없어서 코멘트 달아주신 내용 수정해주시면 
바로 Merge를 진행하겠습니다. 수고하셨습니다.

2023-01-29 02:28 UTC, seu0313 commented on Calculator/Calculator/Source/Model/Node.swift
>      var next: Node?
final 키워드를 사용해주셨네요 👍
[[WWDC 16] Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416) 와 [Swift Optimization](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#advice-use-final-when-you-know-the-declaration-does-not-need-to-be-overridden) 를 참고해서 추가적으로 공부하시면 좋을 것 같습니다.

2023-01-29 02:28 UTC, seu0313 commented on Calculator/Calculator/Source/Model/Operator.swift
> +    }
Divide by Zero 예외 처리를 잘 해주셨네요 👍

2023-01-29 02:28 UTC, llingo commented on Calculator/Calculator/Source/Model/ExpressionParser.swift
> +        return self.split(separator: target).map { String($0) }
String의 `components(separatedBy:)`와 `split(separator:)`는 어떤 차이가 있나요?

2023-01-29 02:28 UTC, llingo commented on Calculator/Calculator/Source/Model/Operator.swift
> +            return Double.nan
`nan`은 어떤 걸 의미하나요?

2023-01-29 02:28 UTC, llingo commented on Calculator/Calculator/Source/Model/Formula.swift
> +            guard calculationResult.isNaN == false  else { return Double.nan }
결과가 `nan`인지 판단해주는 부분인 것 같아요. 체크해주는 이유는 무엇인가요?

2023-01-29 02:28 UTC, llingo commented on Calculator/Calculator/Source/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
외부에서 `operands`와 `operators`에 접근할 수 있어야하나요?

2023-01-29 02:28 UTC, llingo commented on Calculator/CalculatorTests/FormulaTests.swift
> +        sut.operators.enqueue(Operator.add)
`sut.operators.enqueue(.add)`로 사용할 수 있을 것 같아요

2023-01-29 02:28 UTC, llingo commented on Calculator/CalculatorTests/OperatorTests.swift
> +    }
[P1] 사용하지 않는 메서드는 제거하는 것이 좋을 것 같아요

2023-01-29 02:28 UTC, llingo commented on Calculator/CalculatorTests/FormulaTests.swift
> +        let expectedResult:Double = 0
[P1] `let expectedResult: Double = 0`이 좋을 것 같아요

2023-01-30 06:38 UTC, HarryHyeon commented on Calculator/Calculator/Source/Model/Operator.swift
> +            return Double.nan
"not a Number"
숫자가 아니라는 것을 의미합니다.

2023-01-30 06:40 UTC, HarryHyeon commented on Calculator/Calculator/Source/Model/Formula.swift
> +            guard calculationResult.isNaN == false  else { return Double.nan }
`nan`을 판단해주지 않으면 중간에 계산된 결과 값이 정상적인 계산 결과처럼 리턴 되기 때문에 `0으로 devide`하는 상황이 발생하면 무조건 `nan`을 리턴해주기 위해서 해당 코드를 작성했습니다 !

2023-01-30 06:49 UTC, HarryHyeon commented on Calculator/Calculator/Source/Model/Node.swift
>      var next: Node?
클래스는 기본적으로 메서드를 Dynamic dispatch를 통해 동작하는데, 이는 오버라이딩 메서드를 사용했는지를 판단하는 시점이 런타임이기 때문입니다.
final 키워드를 사용하면 상속과 오버라이딩을 하지 않는다는 것을 의미하고 결과적으로 Static dispatch로 컴파일 타임에 어떤 메서드가 호출될지 결정지을 수 있기때문에 성능상의 이점이 있다고 이해했습니다 !

2023-01-30 07:10 UTC, HarryHyeon commented on Calculator/Calculator/Source/Model/ExpressionParser.swift
> +        return self.split(separator: target).map { String($0) }
#### components(separatedBy:)
- Foundation을 import 해야 사용가능
- 반환타입 [String]
- separatedBy: CharacterSet
  - ["a", " "] 여러개를 한꺼번에 분리할 수 있음

#### split(separator:)
- 스위프트 표준 라이브러리
- 반환타입 [Substring]
- separator: Character

이러한 차이가 있습니다.

2023-01-30 09:55 UTC, HarryHyeon commented on Calculator/CalculatorTests/FormulaTests.swift
> +        let expectedResult:Double = 0
띄어쓰기 컨벤션을 실수했네요..
해당 부분은 수정했습니다 !

2023-01-30 09:55 UTC, HarryHyeon commented on Calculator/CalculatorTests/OperatorTests.swift
> +    }
사용하지 않는 메서드라서 삭제를 했어야 했는데 실수가 있었네요.
다음에는 잘 확인하도록 하겠습니다!

2023-01-30 09:57 UTC, HarryHyeon commented on Calculator/CalculatorTests/FormulaTests.swift
> +        sut.operators.enqueue(Operator.add)
넵 ! 수정했습니다 ~

2023-01-30 11:28 UTC, llingo commented on Calculator/Calculator/Source/Model/Formula.swift
> +            guard calculationResult.isNaN == false  else { return Double.nan }
NaN에 대한 예외처리 하신 점 좋습니다 👍 
참고로 `nan`에 어떠한 연산을 하여도 결과는 `nan`이 나옵니다 :)

2023-01-30 11:30 UTC, llingo approved these changes
수고하셨습니다 :)
다음 스탭도 화이팅입니다. 🎉

2023-01-30 11:30 UTC, merged