계산기 [STEP2] 레옹아범
yagom-academy/ios-calculator-app pull request #429
Opened 2023-01-28 10:08 UTC by fatherLeon

@Judy-999 
안녕하세요 쥬디 STEP2는 UML대로 구현을 하다보니 각각 메소드와 프로퍼티에 대한 의도를 파악하느라 골머리를 앓았던것 같습니다
이번에도 좋은 리뷰 부탁드립니다🙏🙏

## UML

![](https://raw.githubusercontent.com/fatherLeon/ios-calculator-app/step2/UML.png)

## 고민한점

### 1️⃣고민한점
* UML내 “+”와 “-“에서 어떤 접근제어자를 사용하면 좋을지?
### 1️⃣해결방법
* UML내에서 “-“는 우선 폐쇄적인 접근제어자로는 private, fileprivate 중 하나를 고를 수 있을 것 같은데 Operator 내의 add, subtract 등등은 Calculate내에서 사용하기 때문에 private접근제어자를 사용했습니다
* ExpressionParser같은 경우 역시 parse내에서만 사용을 하면 충분하다고 생각을 해서 역시 private로 사용하였습니다

### 2️⃣고민한점
* String타입인 값을 Double로 바꾸는 방법
#### ExpressionParser
```swift
components.forEach { component in
    if let operand = component as? Double {	//Cast from 'String' to unrelated type 'Double' always fails
        operands.append(operand)
    }
}
```
* String 타입을 Double로 캐스팅하여 값을 받아오려했는데 String타입은 Double과 관련이 없어 타입캐스팅이 항상 false라는 문제로 고민을 했습니다

### 2️⃣해결방법
#### ExpressionParser
```swift
components.forEach { component in
    if let operand = Double(component) {
        operands.append(operand)
    }
}
```
* 처음에 위와 같이 사용했지만 조건문은 가독성을 해치는 것 같아 아래와 같이 리팩토링하여 사용했습니다
```swift
components.forEach { component in
    let operand = (component as NSString).doubleValue
    operands.append(operand)
}
```

### 3️⃣고민한점
* componentsByOperators 메소드의 의도를 정확히 알기 어려웠습니다.
* 연산자를 통해 피연산자만을 저장하여 반환을 해줘야할지 혹은 연산자와 피연산자를 구별하여 함께 반환을 해줘야하는지에 대해 고민했습니다
### 3️⃣해결방안
#### ExpressionParser
```swift
static private func componentsByOperators(from input: String) -> [String] {
    let inputs = input.split(with: " ")
        
    let components: [String] = inputs.map { component in
        if component.contains(",") {
            let newComponent = component.replacingOccurrences(of: ",", with: "")
            return newComponent
        }
            
        return component
    }
        
    return components
}
```

* componentsByOperators함수의 사용법?에 대해서 제 생각은 +, -, *, / 같은 연산자를 기준으로 나누어 주는 메소드라고 생각했습니다
* 예를들어 “1 + 2 - -3”와 같은 input값이 들어올 경우 [“1”, “+”, “2”, “-“, “-3”]으로 반환해주는 함수로 구현했습니다

## 조언을 얻고 싶은 부분
#### Formula
```swift
struct Formula {
    mutating func result() -> Double {
        guard var lhs: Double = operands.dequeue() else { return 0.0 }
        while let rhs = operands.dequeue() {
            guard let formula = operators.dequeue() else { return lhs }
            lhs = formula.calculate(lhs: lhs, rhs: rhs)
        }
        return lhs
    }
}
```

* STEP2부분에서 변수보다는 상수, 반복문 조건문보다는 고차함수 활용을 권유했는데 result부분에서 while 반복문을 사용하여 구현하는 방법 이외에 고차함수를 사용하여 구현하는 방법은 따로 생각이 나질 않아서 혹시 이 부분에서 찾아서 활용할 수 있는 고차함수가 어떤게 있을까요?
* 혹은 CalculatorItemQueue내에서 고차함수를 구현하여 Formula result에서 사용해야 될지 궁금합니다

2023-01-30 06:30 UTC, Judy-999 requested changes
수고하셨습니다 레옹아범 👏👏

쉽지 않으셨을 텐데 빠르게 잘 구현하셨네요 👍
지금은 어려워도 계산기 프로젝트에서 고민하셨던 부분들이 나중에 큰 도움이 되실겁니다!

---

## 고민한점
### UML내 “+”와 “-“에서 어떤 접근제어자를 사용하면 좋을지?
> - UML내에서 “-“는 우선 폐쇄적인 접근제어자로는 private, fileprivate 중 하나를 고를 수 있을 것 같은데 Operator 내의 add, subtract 등등은 Calculate내에서 사용하기 때문에 private접근제어자를 사용했습니다
> - ExpressionParser같은 경우 역시 parse내에서만 사용을 하면 충분하다고 생각을 해서 역시 private로 사용하였습니다

사용 범위를 고려해서 잘 적용하셨네요 👏 
반대로 `+`는 어떤 접근 제어가 될 수 있고, 현재는 적용하신 접근 제어자는 무엇일까요? 
<br>

### String타입인 값을 Double로 바꾸는 방법
> String 타입을 Double로 캐스팅하여 값을 받아오려했는데 String타입은 Double과 관련이 없어 타입캐스팅이 항상 false라는 문제로 고민을 했습니다

`as`로 타입 캐스팅을 하려면 상속 관계이거나 프로토콜을 채택한 경우에만 타입 변환이 가능합니다. 그렇기에 서로 연관이 없는 String타입은 Double 타입 사이에는 불가능하죠!

> 처음에 위와 같이 사용했지만 조건문은 가독성을 해치는 것 같아 아래와 같이 리팩토링하여 사용했습니다

무조건 짧게 쓰는 것이 좋은 가독성을 가진건 아니라고 생각해요. 오히려 많이 생략할 수록 어떤 의미인지 바로 이해하지 못할 수 있습니다. 조건문으로 어떤 조건으로 해당 코드가 실행되는지 명확히 하는게 더 필요할 때도 있습니다!
<br>

### ExpressionParser
> - componentsByOperators함수의 사용법?에 대해서 제 생각은 +, -, *, / 같은 연산자를 기준으로 나누어 주는 메소드라고 생각했습니다
> - 예를들어 “1 + 2 - -3”와 같은 input값이 들어올 경우 [“1”, “+”, “2”, “-“, “-3”]으로 반환해주는 함수로 구현했습니다

연산자를 기준으로 나누어 주는 역할로 생각하셨는데 실제 로직은 `" "` 띄어쓰기를 기준으로 나누고 있는 것 같아요 🤔 자세한 내용은 코멘트를 참고해주세요.

---

## 조언을 얻고 싶은 부분
> - STEP2부분에서 변수보다는 상수, 반복문 조건문보다는 고차함수 활용을 권유했는데 result부분에서 while 반복문을 사용하여 구현하는 방법 이외에 고차함수를 사용하여 구현하는 방법은 따로 생각이 나질 않아서 혹시 이 부분에서 찾아서 활용할 수 있는 고차함수가 어떤게 있을까요?
> - 혹은 CalculatorItemQueue내에서 고차함수를 구현하여 Formula result에서 사용해야 될지 궁금합니다

모든 부분에 고차함수를 적용하실 필요는 없습니다 🙂 해당 코드는 `while let`으로 구현하신 방법이 깔끔한 것 같네요 👍

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/DataStructure/LinkedList.swift
> +    private var tail: Node<Element>?
접근제어 좋습니다 👍
다만 **LinkedListTest**에서 해당 접근제어 때문에 오류가 나고 있는데 확인해주세요! 😅

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
UML에 `+`로 표시되어 있긴 하지만 프로퍼티는 가능하면 숨길 수 있는게 좋습니다 🙂 
가능한 접근 제어를 고려해보세요!

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +        }
`while let`의 사용 좋네요 👍👍

`guard let` 구문도 같이 넣어서 한 번에 사용할 수 있지 않을까요~?

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +        }
`formula`라고 하면 `operators.dequeue()`가 **Formula**타입을 반환한다고 생각할 것 같아요..! 다른 네이밍이 좋겠습니다.

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +        return lhs
결과로 `lhs`를 반환한다는건 혼동이 될 것 같아요. 역시 다른 네이밍을 고민해보세요!

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/Operator.swift
> +        return calculatedValue.isInfinite ? Double.nan: calculatedValue
`isInfinite`와 ` Double.nan`를 사용하셨네요 👍
각각 어떤 의미와 역할을 하는 걸까요?

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            }
숫자에 `,`가 포함되어 있는 상태를 전제로 하신 이유가 있으실까요?
**Formula**의 `result` 반환 타입 역시 Double인데 화면에 나타낼 때만 `,`가 포함되도록 하는게 간편하지 않을까 싶네요.

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
`componentsByOperators`의 이름을 보면 연산자를 기준으로 분리를 해야 할 것 같은데 구현된 내용은 띄어쓰기(`" "`)으로 분리하고 있네요. 적절한 로직인지 고민이 필요할 것 같아요!

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/Extension/String.swift
> +    }
단순히 String의 `split` 메서드를 사용해서 분리하고 있네요.
그렇다면 `split(with target: Character)`을 구현하지 않고 `split(separator: )` 사용하면 되지 않았을까요? 🤔

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/Extension/String.swift
> +    }
Hint: `Operator`가 `Character` 타입의 rawValue를 가지고 있다는 걸 유념해보세요 🙂
```swift
enum Operator: Character {
```

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            }
`Operator(rawValue: Character(component))`를 통해 연산자가 아니라면 옵셔널이 나올 텐데 `contains`로 확인해줘야 하는 이유가 있을까요?

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            let operand = (component as NSString).doubleValue
`Double(component)`가 더 직관적인 것 같아요 👀 
옵셔널을 검사해야 하는 것이 걸리신다면 `compactMap`을 활용하시면 될 것 같습니다!

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
`forEach`도 고차함수이긴 하지만 더 다양한 고차함수를 활용해보시면 좋을 것 같네요 🙂

한 번의 `forEach`를 통해 따로 넣기 보다는 `components`에서 고차함수를 통해 연산자와 숫자를 각각 뽑아내는게 어떤 로직인지 이해하기 쉬울 것 같습니다!

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
더하기, 빼기 등의 테스트는 `Operator`의 메서드에 대한 테스트가 되어야 할 것 같아요!

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/FormulaTest/FormulaTest.swift
> +        XCTAssertEqual(result, exception)
`given-when-then` 사이 개행을 하면 읽기 더 편해질 것 같네요 👀

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
**ExpressionParserTest**가 모두 **Formula**의 `result`에 의존하고 있네요 🤔

테스트는 기능 또는 기능의 흐름을 테스트해야 합니다. 테스트에 정답이 있는건 아니지만 저는 다음과 같이 생각하고 테스트했을 것 같아요.

**ExpressionParser**는 `parse`와 `componentsByOperators` 두 가지 메서드를 가지고 있으니 최소 두 기능을 테스트 해야겠네요. 그럼 정확히 어떤 동작을 테스트해야 하는지 생각해야 합니다.

`parse`로 예를 들자면 `parse`의 역할은 무엇일까요? 반환 값이 **Formula** 타입이니 의도한 **Formula**를 올바르게 반환하는지 확인하는게 좋겠네요. 그리고 이후에 경계(Edge Case)와 에러 케이스 위주로 조건을 바꿔서 테스트하면 됩니다. 

즉 테스트에서 확인하고자 하는 결과가 `result`가 아니라  `parse`와 `componentsByOperators`의 반환값 또는 해당 메서드의 역할을 위주로 생각되어야 할 것 같습니다!

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
각각 `3 + 4 5`, `3 + 4 +`은 올바를 상황이 아닌 것 같은데 값이 아니라 에러 상황이 되어야하지 않을까요?

2023-01-30 06:30 UTC, Judy-999 commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
연산자 구성만 조금 다를 뿐 다른 테스트같진 않네요. 어떤 점을 확인하고 싶으셨던 걸까요?

2023-01-30 06:57 UTC, fatherLeon commented on Calculator/Calculator/Model/DataStructure/LinkedList.swift
> +    private var tail: Node<Element>?
head와 tail값을 확인하는 테스트케이스를 peek와 back을 사용하여 검증하도록 변경하였습니다

2023-01-30 07:17 UTC, fatherLeon commented on Calculator/Calculator/Model/Formula.swift
> +        }
`operator`이라는 스위프트 시스템 내 명령어가 있어서 `operatorSymbol` 변수명으로 변경했습니다

2023-01-30 08:36 UTC, Judy-999 commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
\++ `componentsByOperators`은 `private`메서드이니 제외하고 생각하셔도 될 것 같습니다~

2023-01-30 13:34 UTC, fatherLeon commented on Calculator/Calculator/Model/Operator.swift
> +        return calculatedValue.isInfinite ? Double.nan: calculatedValue
* Double.inf라는 Double타입에 inf라는 프로퍼티가 있습니다 inf는 무한대라는 의미를 가지며 `1.0 / 0`, '2.0 / 0`과 같은 연산을 할 때 Int형은 에러가 나지만 Float과 Double은 inf라는 형태로 표시가 됩니다
* 그렇기 때문에 값이 inf인지 확인하기 위해 isInfinite를 사용하여 값을 확인했으며, 그 경우 0으로 나뉘어졌기 때문에 nan을 반환하게 끔 하였습니다
* nan의 경우 not a number이라는 뜻이며 숫자가 아니며, 계산기에서 0으로 나뉘어질 경우 nan값이면 "Nan"을 출력하기 위해 사용했습니다

2023-01-30 13:50 UTC, fatherLeon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            }
* `,`가 있는 문자열 값이 있을 경우 Double로 타입 변환 시 nil이 되는 문제가 있어서 해당 `,`를 없애는 작업을 구현했습니다
* 예를 들어 "1,000.00"이 입력값으로 들어왔을 경우 Double로 변환시 nil이 되므로 "1000.00"으로 바꿔주는 작업을 위해서 위와같이 작성하였습니다
* 뷰 컨트롤러에서 어떤식으로 데이터를 넘겨주느냐에 따라 다르겠지만 단순하게 label.text의 값만 넘겨주면 편하다고 생각하여 위와 같이 구현하였습니다

2023-01-30 15:41 UTC, fatherLeon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            }
```swift
if let operatorCase = Operator(rawValue: Character(component)) {
    operators.append(operatorCase)
    return
}
```

* 생각해보니 말씀대로 굳이 contains를 쓸 필요없어서 제거했습니다!!

2023-01-31 06:24 UTC, fatherLeon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
```swift
static private func componentsByOperators(from input: String) -> [String] {
    let operatorValues = Operator.allCases.map { $0.rawValue }
    let inputs = input.split(with: " ").filter { value in
        return operatorValues.contains(value) == false
    }
        
    let components: [String] = inputs.map { component in
        if component.contains(",") {
            let newComponent = component.replacingOccurrences(of: ",", with: "")
            return newComponent
        }
            
        return component
    }
        
    return components
}
```

* 기존 띄어쓰기(`" "`)는 유지한 채 각각의 문자열이 연산자인지를 확인하여 연산자가 아닐 경우에만 반환하게 끔 filter를 사용하였습니다, filter는 return타입이 true인 경우에만 값을 유지하므로 `== fasle`를 통해 피연산자만 남게끔 만들었습니다

2023-01-31 06:32 UTC, fatherLeon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            let operand = (component as NSString).doubleValue
```swift
let operands: [Double] = operandValues.compactMap { component in
    return Double(component)
}
```
* 말씀듣고 찾아보니 compactMap의 경우 배열의 옵셔널 값을 제거해주는 기능도 있어서 곧바로 `return Double(component)하여도 옵셔널처리를 자동으로 해주기 때문에 위와 같이 구현하였습니다

2023-01-31 06:38 UTC, fatherLeon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
```swift
let operators: [Operator] = input.split(with: " ").compactMap { component in
    if operatorValues.contains(component) {
        return Operator(rawValue: Character(component))
    }
            
    return nil
}
      
let operands: [Double] = operandValues.compactMap { component in
    return Double(component)
}
```
* 위와 같이 compactMap을 사용하여 operands와 operators를 따로따로 실행되게끔 만들었습니다

2023-01-31 06:48 UTC, fatherLeon commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
* 이 부분은 잘못된 입력이 들어올 경우 현재까지의 연산값을 확인할 수 있느냐를 테스트하려고 작성했습니다
* 다만 저희가 지금 구현하려는 계산기 특성상 `=`버튼을 누르는 상황이 아니면 이런 상황이 나오지 않을 것 같고 `3 + 4 5`. `3 + 4 +`와 같은 상황이 발생하면 뷰컨트롤러에서 에러를 처리하는게 맞는 것 같아 삭제했습니다

2023-01-31 06:52 UTC, fatherLeon commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
* 다항연산에 대하여 제대로 처리가 되는지 확인하고 싶었습니다
* 말씀대로 구성만 다를뿐 같은 테스트케이스여서 이부분도 하나만을 남기고 삭제했습니다

2023-01-31 07:37 UTC, fatherLeon commented on Calculator/FormulaTest/FormulaTest.swift
> +    }
* `Operator`에 관한 테스트케이스를 새로 작성하여 더하기 빼기와 같은 연산 테스트케이스는 그쪽에서 작성하였습니다
* Formula쪽 테스트케이스의 경우 result 메소드를 테스트해야하기 때문에 연산자가 하나있는 테스트케이스와 연산자가 여러개 있는 테스트케이스는 남겨두었습니다

2023-01-31 07:44 UTC, fatherLeon commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
* `operands`와 `operators`프로퍼티의 경우 `Formula`인스턴스를 만들거나 `result`메소드를 실행할 때를 제외하고는 외부에서 접근을 할 필요성이 없기 때문에 private로 접근제어를 하였습니다.
* private접근제어자를 사용함으로 init을 따로 만들어 주었습니다!!

```swift
struct Formula {
    private var operands: CalculatorItemQueue<Double>
    private var operators: CalculatorItemQueue<Operator>
    
    init(operands: CalculatorItemQueue<Double>, operators: CalculatorItemQueue<Operator>) {
        self.operands = operands
        self.operators = operators
    }
}
```

2023-01-31 08:27 UTC, fatherLeon commented on Calculator/ExpressionParserTest/ExpressionParserTest.swift
> +    }
* Formula를 의도한대로 반환하는지에 대해서 다시 테스트케이스를 작성하였습니다.
* Formula의 경우 operands와 operators가 현재 private이므로 비교하기 위해서는 result메소드 동작이 서로 같을 경우 같은 Formula라고 생각하며 진행했습니다
* 이를 위해 우선 extension을 통해 Formula가 Equatable을 채택하도록 했습니다

```swift
extension Formula: Equatable {
    public static func == (lhs: Calculator.Formula, rhs: Calculator.Formula) -> Bool {
        var firstFormula = lhs
        var secondFormula = rhs
        
        return firstFormula.result() == secondFormula.result()
    }
}
```

* 이후 예상 Formula를 만들고 parse로 반환된 Formula와 비교하는 테스트케이스를 만들었습니다

```swift
func test_1더하기2의_문자열이_parse인자로_들어갈경우_operands가1_2와_operator가_add인_Formula를_반환한다() {
    // given
    let operands: [Double] = [1, 2]
    let operators: [Operator] = [.add]
    let inputs = "1 + 2"
        
    let exception = Formula(operands: CalculatorItemQueue(elements: operands), operators: CalculatorItemQueue(elements: operators))
        
    // when
    let result = ExpressionParser.parse(from: inputs)
        
    // then
    XCTAssertEqual(result, exception)
}
```

2023-01-31 10:04 UTC, fatherLeon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            }
```swift
let operators: [Operator] = input.split(with: " ").compactMap { component in
    if operatorCases.contains(component) {
        return Operator(rawValue: Character(component))
    }
            
    return nil
}
```
* 현재는 이렇게 수정했으며, contains를 쓴 이유는 `Character(component)` 부분에서 String값을 Character로 변환할 때component가 두글자 이상일 경우 에러가 나기 때문에 contains를 사용하여 확인 이후에 Character로 변환하기 위해 사용했습니다

2023-01-31 10:26 UTC, fatherLeon commented on Calculator/Calculator/Model/Extension/String.swift
> +    }
* 이 부분에 대해서 Operator의 rawValue를 사용하여 현재 문자열을 나눠주려고 시도를 해봤습니다
* 하지만 문제가 있었는데 여러가지 연산자를 가진 문자열일때의 방법에 대한 해결을 하지못했습니다
* 현재 split의 target은 하나의 `Character`을 받음으로 만약 `1 + 2 - 4`라는 문자열에서 `+`를 가지고 나눠 줄 경우 `[1, 2 - 4]`로 반환이 되어 `2 - 4`를 또 한번 split을 해줘야하는 문제가 있었습니다
* 또한, 값에 음수가 있을 경우 Operator의 rawValue를 이용해서 split을 한다면 `1 - -4`에서 `[1, 4]`로 반환되는 문제가 있어서 고치지 않았습니다
* `split(separator:)`를 사용하지 않고 이것을 구현한 이유는 반환값이 다르기 때문에 구현을 하는 것이라 생각했습니다 `split(separator:)` 같은 경우 `[String.SubSequence]`를 반환함으로 `[String]`반환값을 받기 위해 구현을 하는것이라 생각했습니다

2023-01-31 10:32 UTC, fatherLeon commented
### UML상 `+`의 접근제어
* 우선 `+`의 경우 기본접근제어인 internal로 생각했습니다
* 저희가 지금 구현하는 계산기 Model은 Calculator외부에서 불러서 사용하는 것이 아닌 Calculator내부에서만 사용하기 때문에 open이나 public을 굳이 사용할 필요가 없다 생각했으며, Internal보다 더 낮은 접근제어자의 경우 Calculoatr 전역에서가 아닌 .swift파일이나 해당 타입에서만 사용가능 하기 때문에 기본 접근제어자 Internal로 생각했습니다

2023-01-31 12:05 UTC, Judy-999 approved these changes
수고하셨습니다 👏👏
추카 코멘트에서 반영하실 부분이 있으시면 다음 스텝에서 같이 진행해주세요 🙂
다음 스텝도 화이팅입니다 🙌

2023-01-31 12:05 UTC, Judy-999 commented on Calculator/LinkedListTest/LinkedListTest.swift
> +        let tailValue = sut.back!
강제 언래핑은 하지 않아도 테스트할 수 있을 것 같아요 🙂

2023-01-31 12:05 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            }
두 글자 이상인 경우 에러가 난다면 한 글자인 경우만 `filter`를 거치는 방법이 있을 것 같아요 🙂

2023-01-31 12:05 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            let operand = (component as NSString).doubleValue
고차함수의 축약형으로 아래처럼 사용도 가능합니다! 고차함수의 여러 사용법을 알아보시면 도움이 될 것 같네요~

```swift
let operands = operandValues.compactMap { Double($0) }
```

2023-01-31 12:05 UTC, Judy-999 commented on Calculator/Calculator/Model/Extension/String.swift
> +    }
고차함수와 중괄호 `{` 사이에는 띄어쓰기를 넣어주세요!
```suggestion
    func split(with target: Character) -> [String] {
        return self.split(separator: target).map { String($0) }
    }
```

2023-01-31 12:05 UTC, merged