계산기 [STEP2] brody
yagom-academy/ios-calculator-app pull request #431
Opened 2023-01-29 05:03 UTC by seunghyunCheon

@Judy-999 
안녕하세요 주디!
계산기 STEP2 PR 보내드립니다! 이번에도 잘 부탁드립니다😁

## 고민한 점과 트러블 슈팅

### 🤔 String에 CalculatorItem을 채택
- parse함수 내부에서 Operator타입과 Double타입으로 변환하기 전에 인터페이스에서 계산기의 숫자와 연산자를 누르면 처음에는 String형태의 숫자와 연산자가 들어간다고 생각해서 CalculatorQueue에서 String타입을 사용하기 위해 채택했습니다. 

### 🤔 componentsByOperators함수 구현

```swift
static private func componentnsByOperators(from input: String) -> [String]
```
요구사항에 해당 함수가 정의되어있는 것을 보고 input값으로 받은 String배열에서 연산자만 추출해서 숫자만 반환하는 것으로 이해했습니다. 
swift 내장 메서드의 `components(separatedBy: ChracterSet)`을 이용해 연산자들을 넣어줘서 해결할 수 있었지만, 고차함수를 사용해 직접 제거해주고 싶어서 이 방법은 배제했습니다. 

#### 고차함수 사용
```swift
func componentsByOperators(from input: String) -> [String] {
    var numbers: [String] = [input]

    Operator.allCases.forEach { oper in
        numbers = numbers.map{ $0.split(with: oper.rawValue) }.flatMap { $0 }
    }
    return numbers
}
```

### 🤔 큐에 들어온 음수처리 방법

큐에 음수가 포함되어 되어있을 때 음수와 빼기를 구분하는 과정이 필요했습니다. 만약 포함하지 않는다면 빼기를 기준으로 `split`할 때 음수또한 포함이 되기 때문입니다.

#### ⚒️ 트러블 슈팅 - String.Index 이용

큐에 넣어줄 때 음수에 빼기를 넣는 것이 아닌 다른 문자를 넣어줘서 해결했습니다. (빼기: -, 음수: ⎼. 미묘한 차이가 있습니다)

문제는 `parse`함수 부분에서 모조의 음수숫자를 실제 음수숫자로 변환해서 `operands`큐에 넣어야하는 과정이 필요했습니다. 이를 String의 Index를 이용해 문제를 해결했습니다.
```swift
componentnsByOperators(from: input)
    .map { $0.contains("⎼") ? ("-" + $0[$0.index(after: $0.startIndex)...]) : $0 }
    .map { Double($0) }
    .compactMap{ $0 }
    .forEach { operands.enqueue($0) }
```

### 🤔 private 메서드 테스트
`componentnsByOperators`함수는 접근제어가 private입니다. 프로퍼티는 `private(set)`을 통해 외부에서 테스트할 수 있지만 메서드는 이 방법이 불가했습니다.

자료를 조금 찾아보니 `componentsByOperators`함수를 담고있는 사용자 정의 타입(계산기 프로젝트에서는 ExpressionParser가 됩니다)에 계산 프로퍼티를 정의해 생성자를 통해 테스트를 하는 것을 볼 수 있었습니다. 

```swift
enum ExpressionParser {
    static func parse(from input: String) -> Formula { }
    static private func componentnsByOperators(from input: String) -> [String] { }
}
```
하지만 계산기 프로젝트에서 `ExpressionParser`는 enum타입으로 static 메서드만 갖고 있기 때문에 계산 프로퍼티를 갖는 것이 다소 어색하다는 느낌을 받았습니다. 만약 계산속성을 갖게되면 테스트를 위한 프로퍼티가 실제 코드에서 생성해야 하기 때문에 이렇게까지 테스트를 진행해야 하는 것이 맞나 의문이 들었습니다.

## 조언을 얻고 싶은 점
현 상태에서 `componentnsByOperators`메서드를 테스트를 어떻게 하면 좋을지에 대한 주디의 의견을 듣고싶습니다.

2023-01-30 10:24 UTC, Judy-999 requested changes
# Brody STEP 2

수고하셨습니다 Brody 👏👏

UML만 보고 코드를 구현한다는게 쉽지 않으셨을 텐데 잘 구현하셨네요 👍
지금은 어려워도 계산기 프로젝트에서 고민하셨던 부분들이 나중에 큰 도움이 되실겁니다!

---

## UML
`+`을 `public`으로 하셨네요. `internal`이 아니라 `public`으로 하신 이유가 있나요?

## 고민한 점과 트러블 슈팅
### String에 CalculatorItem을 채택
> parse함수 내부에서 Operator타입과 Double타입으로 변환하기 전에 인터페이스에서 계산기의 숫자와 연산자를 누르면 처음에는 String형태의 숫자와 연산자가 들어간다고 생각해서 CalculatorQueue에서 String타입을 사용하기 위해 채택했습니다.

숫자와 연산자가 `parse` 메서드를 통해 `CalculatorQueue`에 담기고 있는 것 같은데 String 타입을 직접 넣을 상황이 있을지 고민해보시면 좋겠네요 🙂
<br>

### componentsByOperators함수 구현
> 요구사항에 해당 함수가 정의되어있는 것을 보고 input값으로 받은 String배열에서 연산자만 추출해서 숫자만 반환하는 것으로 이해했습니다.
swift 내장 메서드의 components(separatedBy: ChracterSet)을 이용해 연산자들을 넣어줘서 해결할 수 있었지만, 고차함수를 사용해 직접 제거해주고 싶어서 이 방법은 배제했습니다.

👍 `components`와 `split`은 모두 분리하는 역할을 하는데 어떤 차이가 있는지도 알아두시면 좋습니다.
<br>

### 큐에 들어온 음수처리 방법
> 큐에 넣어줄 때 음수에 빼기를 넣는 것이 아닌 다른 문자를 넣어줘서 해결했습니다. (빼기: -, 음수: ⎼. 미묘한 차이가 있습니다)
>
> 문제는 parse함수 부분에서 모조의 음수숫자를 실제 음수숫자로 변환해서 operands큐에 넣어야하는 과정이 필요했습니다. 이를 String의 Index를 이용해 문제를 해결했습니다.

음수 숫자를 실제 음수 숫자로 변환한다는 것은 어떤 의미인가요? 음수 형태인 문자를 Double로 변환하면 숫자가 되지 않을까요?
<br>

### private 메서드 테스트 + 조언을 얻고 싶은 점
> 계산기 프로젝트에서 ExpressionParser는 enum타입으로 static 메서드만 갖고 있기 때문에 계산 프로퍼티를 갖는 것이 다소 어색하다는 느낌을 받았습니다. 만약 계산속성을 갖게되면 테스트를 위한 프로퍼티가 실제 코드에서 생성해야 하기 때문에 이렇게까지 테스트를 진행해야 하는 것이 맞나 의문이 들었습니다.
>
> 현 상태에서 `componentnsByOperators`메서드를 테스트를 어떻게 하면 좋을지에 대한 주디의 의견을 듣고싶습니다.

`private`한 메서드라면 해당 타입 내부에 있는 다른 메서드에서 사용이 되고 있을 테니 공개된 메서드를 테스트하는 것만으로도 같이 테스트 되고 있다고 생각할 수 있을 것 같습니다. 즉 따로 테스트를 하지 않아도 괜찮을 것 같아요.

하지만 만약 중요한 기능이거나 꼭 테스트 해보고 싶다면 Brody가 알아보신 대로 해당 메서드의 결과를 대변할 수 있는 연산 프로퍼티나 다른 메서드를 두어서 테스트할 순 있을 것 같습니다!

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Operator.swift
> +    }
개인적으로 0보다는 `.zero` 또는 `Double.zero` 표시하는 편입니다. 취향이니 참고만 해주세요~

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Operator.swift
> +    }
```suggestion
    private func add(lhs: Double, rhs: Double) -> Double {
        return lhs + rhs
    }
```
연산자 양 옆으로는 띄어쓰기를 넣어주세요! 다른 연산도 마찬가지입니다.

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +        var sum = initialValue
`guard var`를 활용해볼 수 있겠네요 🙂

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +            if let nextValue = operands.dequeue(), let oper = operators.dequeue() {
Swift의 네이밍은 축약형을 지양합니다.
`oper`로 축약된 형태보다는 풀네임으로 사용해주세요!

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +    var operators = CalculatorItemQueue<Operator>()
UML에 `+`로 표시되어 있긴 하지만 수정까지 오픈되어 있을 필요는 없을 것 같아요!

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/FormulaTest/FormulaTest.swift
> +    func test_result호출시_2_더하기_5_곱하기_4_나누기_2는_14이다() {
아래 테스트의 연산이 조금 더 복잡해졌을 뿐 큰 차이는 없어 보이는데 어떤 점을 확인해보고 싶으셨던 걸까요?

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Extension.swift
> +//
파일이름이 단순히 Extension보다는 String을 Extension한 것을 알 수 있음 좋지 않을까요 👀

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/SplitTest/SplitTest.swift
> +    func test_split함수실행시_마이너스를인자로넣는다면_마이너스를기준으로분리해서_배열을반환한다() {
계산기로 활용되는 선에서만 테스트가 된 것 같아요. `split` 메서드 자체는 계산기와 연관이 있지 않으니 계산기 기능에 국한되지 않고 다양한 테스트를 진행해보시면 좋겠습니다.

예를 들어 `target`이 연속하게 들어가 있는 경우, `target`이 처음이나 끝에 있는 경우 등의 상황이 될 수 있겠네요!

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +import Foundation
`Foundation`이 필요한 파일인가요?  
다른 파일에서도 필요한 프레임워크가 아니라면 지워주세요~

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
고차함수의 활용 좋습니다 👍
한 줄로 길게 쓰는 것 보다는 개행을 넣어주는게 가독성이 좋을 것 같아요~

역시 `oper` 축약형은 지양해주세요!
```suggestion
        Operator.allCases.forEach { oper in
            results = results.map { 
                $0.split(with: oper.rawValue) 
            }.flatMap { $0 }
        }
```

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        let opers = input.split(whereSeparator: { $0.isNumber || $0 == "." })
어떤 처리를 위한 코드인가요?

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +            .forEach { operands.enqueue($0) }
고차함수는 적절하게 사용하셨는데 `map`의 로직이 복잡한 것 같아요 🥲
`componentnsByOperators`로 연산자를 분리하신 것 같은데 `⎼`(빼기 연산자)를 따로 검사해야 하는걸까요?

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
`init`의 활용 좋네요 👍

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)에서 다음과 같은 문구가 있습니다.

> Name variables, parameters, and associated types according to their roles, rather than their type constraints.
> : 타입 제약 조건이 아닌 **역할**에 따라 변수, 매개 변수 및 관련 유형의 이름을 지정합니다.
>
> ex) var string = "Hello" ---> var greeting = "Hello"

이렇듯 `operChar` 처럼 변수명에 특정 타입을 명시하기 보다는  역할이나 의미로 명명하는게 좋습니다!

`oper` 역시 축약형은 지양해주세요!

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
`oper.first`를 가져오는 이유는 무엇인가요? 해당 로직을 설명해주세요!

2023-01-30 10:24 UTC, Judy-999 commented on Calculator/Calculator/Operator.swift
> +        if rhs == 0 { return .nan }
`.nan`은 어떤 의미인가요?

2023-01-30 11:55 UTC, seunghyunCheon commented on Calculator/Calculator/Formula.swift
> +        var sum = initialValue
감사합니다!

2023-01-30 12:00 UTC, seunghyunCheon commented on Calculator/FormulaTest/FormulaTest.swift
> +    func test_result호출시_2_더하기_5_곱하기_4_나누기_2는_14이다() {
다른 형태의 연산이 들어갔을 때에도 잘 동작한다는 것을 테스트하기 위해서 작성했었습니다! 더 구체적인 메서드인 아래 메서드 하나만 남겨놓겠습니다!

2023-01-30 12:01 UTC, seunghyunCheon commented on Calculator/Calculator/Extension.swift
> +//
수정했습니다

2023-01-30 12:11 UTC, seunghyunCheon commented on Calculator/SplitTest/SplitTest.swift
> +    func test_split함수실행시_마이너스를인자로넣는다면_마이너스를기준으로분리해서_배열을반환한다() {
감사합니다! 수정했습니다 😄

2023-01-30 12:15 UTC, seunghyunCheon commented on Calculator/Calculator/ExpressionParser.swift
> +        let opers = input.split(whereSeparator: { $0.isNumber || $0 == "." })
연산자들만 추출하고 싶어서 작성했습니다!
input값으로 10.5+30.2가 들어온다고 했을 때 "+, -, *, /" 뿐만 아니라 "."또한 추출이 되고 있어서 **숫자일 때와 .일 때를 기준으로 분리**하면 연산자들이 나오겠다고 생각해서 작성했습니다!

2023-01-30 12:24 UTC, seunghyunCheon commented on Calculator/Calculator/ExpressionParser.swift
> +            .forEach { operands.enqueue($0) }
빼기`-`와 음수`⎼`를 다르게 처리했습니다. 
계산기에 값을 넣을 때 -/+기호를 이용하여 음수를 큐에 넣을 때는 빼기가 아닌 음수의 기호를 숫자에 삽입한 뒤 parse에서 음수의 기호를 사용한 숫자에 대해 실제 음수로 바꿔주었습니다. 
이 때문에 map이 조금 복잡해진 것 같습니다.

2023-01-30 12:40 UTC, seunghyunCheon commented on Calculator/Calculator/ExpressionParser.swift
> +        }
Operator.init(rawValue:)의 인자로 Character 타입이 들어와야해서 first프로퍼티를 통해 Character타입을 가져왔습니다! 하지만 compactMap을 사용해서 해당 내용을 아래와 같이 바꿨습니다
```swift
 input.compactMap { Operator(rawValue: $0) }
      .forEach { operatorQueue.enqueue($0) }
            
```

2023-01-30 12:44 UTC, seunghyunCheon commented on Calculator/Calculator/Operator.swift
> +        if rhs == 0 { return .nan }
유한한 수나 무한대가 아닌 값을 nan이라고 학습했습니다. 
어떤 숫자를 0으로 나눌 시 수학적으로 개념이 성립되지 않기 때문에 .nan을 리턴하도록 했습니다!

2023-01-30 13:15 UTC, seunghyunCheon commented
> 숫자와 연산자가 parse 메서드를 통해 CalculatorQueue에 담기고 있는 것 같은데 String 타입을 직접 넣을 상황이 있을지 고민해보시면 좋겠네요 🙂
- Operator와 Double큐가 생기면서 String타입을 넣을 경우가 사라진 것 같아서 삭제했습니다!




> 👍 components와 split은 모두 분리하는 역할을 하는데 어떤 차이가 있는지도 알아두시면 좋습니다.
- 다음과 같이 정리해봤습니다
### components
- 인자 값으로 문자를 받아 문자 기준으로 쪼갠다.
- import Foundation이 필요하다.
- 반환형이 [String]이다.
```swift
func components(separatedBy separator: String) -> [String]
```
### split
- components와 동일하게 인자 값을 받아 특정 문자 기준으로 쪼갤 수 있다. 반환형은 String타입을 [SubString]으로 반환한다. 
- swift 표준 라이브러리에 들어가 있어서 import Foundation없이 사용할 수 있다.
- maxSplit: 지정한 문자 단위로 얼마나 쪼갤지 지정한다.
- omittingEmptySubsequences: Bool값으로 결과값에서 빈 시퀀스의 포함 유무를 설정한다.
```swift
func split(separator: Character, maxSplits: Int = Int.max, omittingEmptySubsequences: Bool = true) -> [Substring]
```




> 음수 숫자를 실제 음수 숫자로 변환한다는 것은 어떤 의미인가요? 음수 형태인 문자를 Double로 변환하면 숫자가 되지 않을까요?
계산기 인터페이스에서 음수를 입력받을 때 문자저장을 빼기(-)가 아닌 음수(⎼)를 사용했습니다. -13은 Double로 바로 변환이 가능하지만 ⎼13에서 ⎼은 제가 임의로 삽입한 문자기 때문에 Double로 변환하면 실패하게 돼서 이렇게 표현했습니다!

private 메서드 테스트 + 조언을 얻고 싶은 점
계산기 프로젝트에서 ExpressionParser는 enum타입으로 static 메서드만 갖고 있기 때문에 계산 프로퍼티를 갖는 것이 다소 어색하다는 느낌을 받았습니다. 만약 계산속성을 갖게되면 테스트를 위한 프로퍼티가 실제 코드에서 생성해야 하기 때문에 이렇게까지 테스트를 진행해야 하는 것이 맞나 의문이 들었습니다.

2023-01-31 01:40 UTC, Judy-999 commented on Calculator/Calculator/Operator.swift
> +        if rhs == 0 { return .nan }
[nan](https://developer.apple.com/documentation/swift/floatingpoint/nan)의 뜻을 풀이를 하면 "not a number"로 말 그대로 숫자가 아닌 값으로 생각하시면 됩니다 🙂

2023-01-31 01:48 UTC, Judy-999 approved these changes
잘 반영하셨네요 👏👏 추가로 남긴 사항은 다음 스텝에서 같이 고민해주세요~
다음 스텝도 화이팅입니다 🙌

2023-01-31 01:48 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +            .forEach { operandQueue.enqueue($0) }
**CalculatorItemQueue**를 생성한 후 하나씩 `enqueue`하는 것 보다 고차함수로 얻어낸 배열로 직접 **CalculatorItemQueue**를 생성하는게 간결하고 명확할 것 같아요!

```swift
init(enqueueStack: [Item] = []) {
    self.enqueueStack = enqueueStack
}
```

2023-01-31 01:48 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +            .forEach { operandQueue.enqueue($0) }
훨씬 간단해졌네요 👍👍

2023-01-31 01:48 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +    private (set) var operators = CalculatorItemQueue<Operator>()
접근제어 좋습니다 👏

일반적으로 괄호를 붙여서 사용합니다!
```suggestion
    private(set) var operands = CalculatorItemQueue<Double>()
    private(set) var operators = CalculatorItemQueue<Operator>()
```

2023-01-31 01:49 UTC, merged