계산기 [STEP 2] vetto
yagom-academy/ios-calculator-app pull request #432
Opened 2023-01-29 07:46 UTC by gzzjk159

# 계산기 [STEP 1] vetto
안녕하세요 @Judy-999
조금 늦은 감이 있지만 UML이 제시했던 기능들을 다 구현한 거 같아 step2 PR 보냅니다

## 고민했던 점
### split(with:)함수의 기능
* 기존에도 split이라는 함수가 있어서 이 함수는 어떤 기능을 해야하는 함수인가 고민을 했습니다.
* 기존에 split이라는 함수는 매개변수가 RegexComponent이고 반환 값은 [subString]이었습니다.
* UML에서 제시한 split(with:)함수는 매개변수가 Character이고 반환 값이 [String]인 점이 다르다고 생각하였습니다.
* 그래서 UML에서 제시한 split(with:)함수는 with(매개변수 타입: Character)를 기준으로 나누면서 [subString]대신 [String]을 반환하는 함수로 구현하였습니다.
```swift
extension String {
    func split(with target: Character) -> [String] {
        return self.split(separator: target).map { String($0) }
    }
}
```

### componentsByOperators함수의 기능
* 처음에는 어떠한 기능으로 구현해야 하는지 몰랐습니다. 하지만 swift에는 문자열을 나누어 주는 components라는 메서드가 있어서 여기서 힌트를 얻어서 기능을 구현하였습니다.
* 제가 생각한 기능으로는 "2 + 4 - 3 * -1" 이러한 문자열이 있을 때 componentsByOperators라는 함수를 사용하면 ["2", "4", "3", "-1"]이렇게 숫자들만 구분하여 [String]으로 반환하는 기능을 구현하였습니다.
```swift
private static func componentsByOperators(from input: String) -> [String] {
    return input.split(with: " ").compactMap { Double($0) }.map { String($0) }
}
```

### UML의 +,-와 밑줄의 의미
#### UML에는 `+`,`-` 기호들은 상대적으로 개방적인 것과 폐쇄적인 것을 의미한다고 하였습니다. 따라서 이 기호들이 붙은 곳에 어떤 접근 제어자를 붙여줘야 할지 고민했습니다.
* `+`는 개방적인 의미이기 때문에 public과 internal 둘 중 하나를 고민했습니다. public과 internal의 범위에서 차이가 나는데 public은 모듈 외부에서도 접근이 가능하고 internal을 하나의 모듈 내부에서만 접근이 가능합니다. 이 `+`가 붙은 메서드들을 외부 모듈에서 사용할 일이 없다고 판단하여 internal로 선언하였습니다.
* `-`는 폐쇄적인 의미이라 private 와 fileprivate 둘중 고민을 하였습니다. file안에서 접근이냐 정의한 블록에서만 접근이냐였기 때문에 파일안에서 접근하는 일이 없다고 판단하여 private로 선언하였습니다.
* 밑줄에 대해서는 static이라 판단하여 밑줄이 그어진 메서드 앞에 static으로 선언해주었습니다.

## 해결하지 못한 점 & 조언받고 싶은 점
### parse메서드의 비효율
```swift
static func parse(from input: String) -> Formula {
    var operandQueue = CalculatorItemQueue<Double>()
    var operatorQueue = CalculatorItemQueue<Operator>()
    let operandsArray = componentsByOperators(from: input).compactMap { Double($0) }
    let operatorsArray = input.split(with: " ")
                            .filter { $0.count == 1 }
                            .compactMap { Operator(rawValue: Character($0)) }
        
    operandsArray.forEach { operandQueue.enqueue($0) }
    operatorsArray.forEach { operatorQueue.enqueue($0) }
        
    return Formula(operands: operandQueue, operators: operatorQueue)
}
    
private static func componentsByOperators(from input: String) -> [String] {
    return input.split(with: " ").compactMap { Double($0) }.map { String($0) }
}
```
* componentsByOperators메서드에서 UML의 조건을 만족하기 위해Double로 바꿔주고 다시 String으로 바꿔주며 반환을 하였습니다. 하지만 parse라는 메서드에서 다시 double로 바꿔주는 작업을 처리합니다. 이렇게 되면 했던 작업을 다시 하는 것이라 비효율적이라 생각되는데 이렇게 구현을 해야 하는지 궁금합니다.

### formula test작성
* parse는 String을 parameter로 받아서 formula로 반환하는 메서드 입니다. 이것을 어떻게 테스트 하나 생각을 해보았습니다. 새로운 formula를 만들고 parse메서드로 반환된 formula를 비교하는 것이 정확한 테스트라고 생각했습니다. 
* 하지만 이렇게 하려고 하니 equatable 연산자를 적용하지 못하기 때문에 extension으로 새로운 코드를 작성해야 됐습니다. 그 결과 테스트 하는 코드보다 확장하는 코드가 길어졌는데 이것이 괜찮은지 궁금합니다.
```swift
extension Formula: Equatable {
    public static func == (lhs: Calculator.Formula, rhs: Calculator.Formula) -> Bool {
        var operatorsHead = lhs.operators.calculatorQueue.head
        
        while operatorsHead != nil {
            let lhsData = lhs.operands.calculatorQueue.head?.data
            let rhsData = rhs.operands.calculatorQueue.head?.data
            
            if lhsData != rhsData {
                return false
            }
            
            operatorsHead = operatorsHead?.next
        }
        
        var operandsHead = lhs.operands.calculatorQueue.head
        
        while operandsHead != nil {
            let lhsData = lhs.operands.calculatorQueue.head?.data
            let rhsData = rhs.operands.calculatorQueue.head?.data
            
            if lhsData != rhsData {
                return false
            }
            
            operandsHead = operandsHead?.next
        }
        
        return true
    }
}

final class ExpressionParserTests: XCTestCase {
    
    override func setUpWithError() throws {
        try super.setUpWithError()
    }
    
    override func tearDownWithError() throws {
        try super.tearDownWithError()
    }
    
    // MARK: - parse method test
    func test_parse호출후_임시로_로만든() {
    // given
    let input: String = "123 + -3 - 34 + 123 * 2"
    var formula = Formula(operands: CalculatorItemQueue<Double>(),
                              operators: CalculatorItemQueue<Operator>())
        
    formula.operands.enqueue(123)
    formula.operands.enqueue(-3)
    formula.operands.enqueue(34)
    formula.operands.enqueue(123)                       
    formula.operands.enqueue(2)
        
    formula.operators.enqueue(Operator.add)
    formula.operators.enqueue(Operator.subtract)
    formula.operators.enqueue(Operator.add)
    formula.operators.enqueue(Operator.multiply)
        
    // when
    let result = ExpressionParser.parse(from: input)
    let expectation = formula
        
    // then
    XCTAssertEqual(result, expectation)
    }
}
```

2023-01-30 13:19 UTC, Judy-999 requested changes
수고하셨습니다 vetto 👏👏

UML만 보고 코드를 구현한다는게 쉽지 않으셨을 텐데 잘 구현하셨네요 👍
지금은 어려워도 계산기 프로젝트에서 고민하셨던 부분들이 나중에 큰 도움이 되실겁니다 😊

---

## UML
현재 `split` 메서드가 String이 아닌 Double의 extension으로 표시된 것 같아요! 👀 그리고 extension은 타입은 아니기 때문에 간단하게 String의 메서드로 표시해도 될 것 같습니다.

CalculateItem을 직접 채택하고 있지 않은 타입은 선으로 연결하진 않아도 제네릭 타입으로 표현되어 있으니 괜찮을 것 같아요! 
<br>

## 고민했던 점
### split(with:)함수의 기능
> - 기존에도 split이라는 함수가 있어서 이 함수는 어떤 기능을 해야하는 함수인가 고민을 했습니다.
> - 기존에 split이라는 함수는 매개변수가 RegexComponent이고 반환 값은 [subString]이었습니다.
> - UML에서 제시한 split(with:)함수는 매개변수가 Character이고 반환 값이 [String]인 점이 다르다고 생각하였습니다.
> - 그래서 UML에서 제시한 split(with:)함수는 with(매개변수 타입: Character)를 기준으로 나누면서 [subString]대신 [String]을 반환하는 함수로 구현하였습니다.

기존 `split` 메서드와 비교하면서 잘 고민하셨네요 👍 이와 비슷한 다른 메서드인 [components(separatedBy:)](https://developer.apple.com/documentation/foundation/nsstring/1413214-components)와 차이도 알아두시면 좋습니다 🙂
<br>

### componentsByOperators함수의 기능
> - 처음에는 어떠한 기능으로 구현해야 하는지 몰랐습니다. 하지만 swift에는 문자열을 나누어 주는 components라는 메서드가 있어서 여기서 힌트를 얻어서 기능을 구현하였습니다.
> - 제가 생각한 기능으로는 "2 + 4 - 3 * -1" 이러한 문자열이 있을 때 componentsByOperators라는 함수를 사용하면 ["2", "4", "3", "-1"]이렇게 숫자들만 구분하여 [String]으로 반환하는 기능을 구현하였습니다.

결과가 숫자들을 남기는 것이라 해도 `componentsByOperators`라면 로직은 빈 칸이 아니라 Operator를 기준으로 분리해야 할 것 같습니다!
<br>

### UML의 +,-와 밑줄의 의미
> - +는 개방적인 의미이기 때문에 public과 internal 둘 중 하나를 고민했습니다. public과 internal의 범위에서 차이가 나는데 public은 모듈 외부에서도 접근이 가능하고 internal을 하나의 모듈 내부에서만 접근이 가능합니다. 이 +가 붙은 메서드들을 외부 모듈에서 사용할 일이 없다고 판단하여 internal로 선언하였습니다.
> - -는 폐쇄적인 의미이라 private 와 fileprivate 둘중 고민을 하였습니다. file안에서 접근이냐 정의한 블록에서만 접근이냐였기 때문에 파일안에서 접근하는 일이 없다고 판단하여 private로 선언하였습니다.
> - 밑줄에 대해서는 static이라 판단하여 밑줄이 그어진 메서드 앞에 static으로 선언해주었습니다.

접근 범위를 고민해서 잘 선택하셨네요 👍👍

---

## 해결하지 못한 점 & 조언받고 싶은 점
### parse메서드의 비효율
> componentsByOperators메서드에서 UML의 조건을 만족하기 위해Double로 바꿔주고 다시 String으로 바꿔주며 반환을 하였습니다. 하지만 parse라는 메서드에서 다시 double로 바꿔주는 작업을 처리합니다. 이렇게 되면 했던 작업을 다시 하는 것이라 비효율적이라 생각되는데 이렇게 구현을 해야 하는지 궁금합니다.

위에 남겼던 내용과 마찬가지고 `componentsByOperators`에서 Double로 변경하는 작업 대신 다른 로직으로 변경해보세요!
<br>

### formula test작성
> - parse는 String을 parameter로 받아서 formula로 반환하는 메서드 입니다. 이것을 어떻게 테스트 하나 생각을 해보았습니다. 새로운 formula를 만들고 parse메서드로 반환된 formula를 비교하는 것이 정확한 테스트라고 생각했습니다.
> - 하지만 이렇게 하려고 하니 equatable 연산자를 적용하지 못하기 때문에 extension으로 새로운 코드를 작성해야 됐습니다. 그 결과 테스트 하는 코드보다 확장하는 코드가 길어졌는데 이것이 괜찮은지 궁금합니다.

**Formual** 자체를 비교하는 것 보다는 `operators`와 `operands`로 잘 분리되었는지로 확인하시면 될 것 같아요.

즉 **Formual**의 `operators`와 `operands`와 예상한 **CalculatorItemQueue**를 비교하는 것인데 **CalculatorItemQueue** 역시 Equtable하지 않으니 문제가 되겠죠.

이를 해결하려면 생각나는 방법으론 **CalculatorItemQueue** 배열을 매개변수로 받는 `init`을 갖게 하고, 자신의 모든 Node를 배열로 반환하는 메서드나 프로퍼티를 가지면 이를 비교할 수 있을 것 같습니다.

이외에도 다른 방법으로 Equtable한 타입을 뽑아내서 비교하거나, 다른 타입이 지금처럼 Equtable을 채택하게 하는 방법도 있을 것 같네요.

아니면 단순하게 계속 dequeue하면서 값을 체크하는 방법도 있을 것 같네요!

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/LinkedList.swift
> +struct LinkedList<Element: CalculateItem> {
LinkedList로 분리가 잘 되었네요 👍

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/Operator.swift
> +    }
`.nan`은 어떤 의미인가요?

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/CalculatorTests/OperatorTests.swift
> +        sut = Operator(rawValue: "+")
`rawValue` 보다는 `.add`와 할당하는게 명확할 것 같네요!
다른 테스트도 마찬가지입니다 🙂

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
UML에 `+`로 표시되어 있긴 하지만 수정까지 오픈되어 있을 필요는 없을 것 같아요!

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +        result = firstOperand
`result`에 바로 `operands.dequeue()` 값을 넣으면 간편할 거 같네요!

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +            result = `operator`.calculate(lhs: result, rhs: operand)
`` 표현은 어떤 이유로 사용하신걸까요?

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/CalculatorTests/FormulaTests.swift
> +    }
테스트 이름과 테스트 내용이 다른 것 같아요 👀

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/CalculatorTests/SplitTests.swift
> +
`sut` 빈 문자열로 초기화하는 작업을 해줘도 좋겠네요 🙂

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/CalculatorTests/SplitTests.swift
> +    func test_테스트문자열에서_split_with에_Characater_7을_넣고_호출하면_7로_분리된_문자열배열이_반환된다() {
edge case가 될 수 있는 `Characater`가 연속으로 있을 때, 처음이나 끝에 있을 때도 테스트해보면 좋을 것 같아요~

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
`split(with: )`의 반환형이 `[String]`인데 Double로 변환해주시는 이유는 무엇인가요?

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
`componentsByOperators` 네임을 보면 Operators를 기준으로 분리할 것 같은데 `" "` 빈 칸으로 분리되고 있어서 이름과 맞지 않는 것 같아요 🤔

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +                                .compactMap { Operator(rawValue: Character($0)) }
어떤 로직인지 설명해주시겠어요? 👀

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +                                .compactMap { Operator(rawValue: Character($0)) }
고차함수의 활용 좋네요 👍

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var calculatorQueue = LinkedList<Element>()
`CalculatorItemQueue`가 Queue를 들고 있는건 어색한 것 같아요. 
**LinkedList<Element>** 타입과 맞는 이름이면 좋겠네요!

2023-01-30 13:19 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        operatorsArray.forEach { operatorQueue.enqueue($0) }
`enqueue`로 넣지 않고 **CalculatorItemQueue**의 init을 활용해 바로 생성하는 방법도 좋을 것 같아요!

2023-01-30 13:23 UTC, Judy-999 commented on Calculator/CalculatorTests/ExpressionParserTest.swift
> +    }
사용하지 않는 override는 지워주세요!

2023-01-31 05:19 UTC, gzzjk159 commented on Calculator/Calculator/Model/Operator.swift
> +    }
not a number의 약자로 Double타입에서 사용 가능한 숫자가 아님을 나타내는 말입니다. 0으로 나누었을때 이 숫자가 숫자가 아님을 나타내기 위해서 사용하였습니다.

2023-01-31 05:21 UTC, gzzjk159 commented on Calculator/CalculatorTests/OperatorTests.swift
> +        sut = Operator(rawValue: "+")
리뷰어 조언대로 .add같은 타입을 할당해주었습니다. 7070976b4319dc510ad754a8a02c607e39558bc6

2023-01-31 05:23 UTC, gzzjk159 commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator>
리뷰어 조언대로 읽기는 가능하지만 쓰기는 불가능한 private(set)으로 수정하였습니다.  f379a49f2428dbbb3fb55b27cd34ff683be8bfa7

2023-01-31 05:23 UTC, gzzjk159 commented on Calculator/Calculator/Model/Formula.swift
> +        result = firstOperand
리뷰어 조언대로 guard var 를 사용하여 result에 바로 넣었습니다. ba4a5f5929e75fb3d87f9fc1234b92eb34ec1d62

2023-01-31 05:24 UTC, gzzjk159 commented on Calculator/Calculator/Model/Formula.swift
> +            result = `operator`.calculate(lhs: result, rhs: operand)
백틱 기호를 사용하면 기존에 예약어로 되어있는 키워드를 변수로 사용할 수 있습니다. 다만 이렇게 하는 것이 권장되는지는 잘 모르겠습니다.

2023-01-31 05:26 UTC, gzzjk159 commented on Calculator/CalculatorTests/FormulaTests.swift
> +    }
리뷰어의 조언대로 함수명과 일치하게 test함수명을 작성하였습니다.  7070976b4319dc510ad754a8a02c607e39558bc6

2023-01-31 05:26 UTC, gzzjk159 commented on Calculator/CalculatorTests/SplitTests.swift
> +
리뷰어 조언대로 빈 문자열을 추가하였습니다. f7ba78bdf31fd41981c931ecac55d74d613c0b5b

2023-01-31 05:29 UTC, gzzjk159 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
코드 수정 전에는 빈칸으로 분리 후 숫자만 분리하기 위해 숫자로 변환 될 수 있는 data만 남기고 다시 string으로 바꿔주는 작업을 했던거 같습니다. 현재는 메서드의 로직을 바꾸어서 해당 코드는 삭제되었습니다. 97c70ca0f47fb0b5dd0a3426d8b1a297d7937d43

2023-01-31 05:30 UTC, gzzjk159 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
리뷰어 조언대로 현재는 operator로 분리할 수 있게 코드를 변경하였습니다. 97c70ca0f47fb0b5dd0a3426d8b1a297d7937d43

2023-01-31 05:32 UTC, gzzjk159 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +                                .compactMap { Operator(rawValue: Character($0)) }
처음에는 빈칸으로 분리한 후 연산자만 걸러내기 위해 코드를 작성하였습니다. 따라서 rawValue로 들어갈 수 있는 단일 문자열만 골라낸 후 그것을 compactMap으로 분리하였습니다.
현재는 코드를 수정하여 해당 코드는 변경되었습니다. 97c70ca0f47fb0b5dd0a3426d8b1a297d7937d43

2023-01-31 05:34 UTC, gzzjk159 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var calculatorQueue = LinkedList<Element>()
리뷰어 조언대로 queue를 가지고 있기보단 List를 가지고 있는 것으로 판단되어 calculatorList로 변경하였습니다. de2804d009cbd1e98709113b2bbe632d8bc638fc

2023-01-31 05:35 UTC, gzzjk159 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        operatorsArray.forEach { operatorQueue.enqueue($0) }
리뷰어 조언대로 현재 init을 추가하여 list를 넣어주는 로직으로 바꿔주었습니다. 97c70ca0f47fb0b5dd0a3426d8b1a297d7937d43

2023-01-31 05:38 UTC, gzzjk159 commented on Calculator/CalculatorTests/ExpressionParserTest.swift
> +    }
리뷰어 조언대로 사용하지 않은 override를 제거하였습니다. 6868e9cfd0e1aa54898fdfbbcdce7087c252194b

2023-01-31 05:43 UTC, gzzjk159 commented on Calculator/CalculatorTests/SplitTests.swift
> +    func test_테스트문자열에서_split_with에_Characater_7을_넣고_호출하면_7로_분리된_문자열배열이_반환된다() {
리뷰어 조언대로 처음이나 끝, 연속으로 있을 때에 테스트도 작성하였습니다. 663f983ab5385dbccbe03a838e51e6ff692aaebc

2023-01-31 06:15 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +            result = `operator`.calculate(lhs: result, rhs: operand)
[Swift Language Guide](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html)에 다음과 같은 글이 있습니다.

> If you need to give a constant or variable the same name as a reserved Swift keyword, surround the keyword with backticks (`) when using it as a name. However, avoid using keywords as names unless you have absolutely no choice.

`선택의 여지가 전혀 없는 경우가 아니면 키워드를 이름으로 사용하지 마십시오.`라고 하니 권장되는 방법은 아닙니다!

2023-01-31 06:23 UTC, Judy-999 requested changes
`split` 메서드를 구현만 하고 사용하고 있지 않네요! 
`componentsByOperators(from input: String)` 메서드에서 고차함수와 함께 이용해보시면 좋겠습니다 🙌

2023-01-31 06:23 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorsArray = input.compactMap{ Operator(rawValue: $0) }
```suggestion
        let operatorsArray = input.compactMap { Operator(rawValue: $0) }
```
고차함수와 중괄호(`{`) 사이에는 띄어쓰기를 넣어주세요~!

2023-01-31 06:23 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
이미 구현된 `components` 메서드가 아닌 String을 Extension으로 구현한 `split`을 사용해주세요! 🙂

2023-01-31 07:36 UTC, Judy-999 approved these changes
수고하셨습니다 👏👏 
띄어쓰기는 다음 스텝 하시면서 넣어주세요 🙂
화이팅입니다 🙌

2023-01-31 07:36 UTC, Judy-999 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
띄어쓰기가 빠져있네요!
```suggestion
        Operator.allCases.forEach { `operator` in
            result = result.flatMap { $0.split(with: `operator`.rawValue) }
        }
```

2023-01-31 07:37 UTC, merged