계산기 [Step2] 송준
yagom-academy/ios-calculator-app pull request #438
Opened 2023-01-30 07:47 UTC by kimseongj

## UML
![step2-UML](https://user-images.githubusercontent.com/88870642/215417733-649dd90d-c003-4b0b-bedb-cbad7ea2e8fd.jpg)

## 고민했던 점
### 1. `split(with target: Character) -> [String]`메서드의 역할
`split`메서드에서 `target`에 어떤 값을 받아올지 정말 고민을 많이 했습니다. operator들을 받아올지, 빈칸을 받아올지에 대한 고민이었습니다. `componentsOfOperators` 메서드는 메서드명 문맥상 `split`을 사용하여 operator를 기준으로 operand들을 분리해줘야 된다고 생각되었습니다. 그래서 `split`에서 operator를 파라미터로 받기로 결정했습니다. 
### 분리된 `String`타입의 값들을 `Double`과 `Operator`로 바꿔주는 과정
고차함수를 최대한 많이 사용할

`componentsByOperators`

### 2. 음수처리
`split`메서드에 operator들을 받아오기 때문에 음수처리에 각별히 신경써야 했습니다.
제가 사용한 방식은 "⎼"이라는 특수문자로 입력 받고 `parse`메서드 내부에서  "⎼"를 "-"로 바꾸는 형식을 채택했습니다. 또한, for문을 사용하여 처리했었는데, 고차함수를 통해 간결하고 가독성 있는 코드를 완성했습니다.

고차함수 사용 전
```swift
var separatedOperands = componentsByOperators(from: input)
for i in 0..<separatedOperands.count {
    if separatedOperands[i].contains("⎼") {
        separatedOperands.replacingOccurrences(of: "⎼", with: "-")
    }
}
```

고차함수 사용 후
```swift
var separatedOperands = componentsByOperators(from: input)
        
        separatedOperands = separatedOperands.map{ if $0.contains("⎼") { return $0.replacingOccurrences(of: "⎼", with: "-")} else {
            return $0
        } }
```

### 3. enum의 rawValue로 enum case값 불러오기 
Operator의 case rawValue를 통해 Operator의 case값들을 불러오는 과정이 있었습니다. 
조사해본 결과 아래와 같이 case값들을 얻을 수 있었습니다.
```swift 
enum Shoes: String {
    case nike = "나이키"
    case adidas = "아디다스"
    case converse = "컨버스"
}

let a = Shoes(rawValue: "나이키")
```

2023-01-30 11:23 UTC, llingo requested changes
안녕하세요 송준
이번 스텝은 UML을 파악하고 단순 구현의 느낌이었네요. UML을 보면서 구현하는 것은 어떠셨나요?

특히 `nan` 예외 처리와 고차함수를 잘 사용하신 부분이 좋았습니다

이번 스텝은 크게 수정해야할 부분이 없어서 코멘트 달아주신 내용 수정해주시면 
바로 Merge를 진행하겠습니다. 수고하셨습니다.

---

> 안내사항은 참고용으로 남겨두었습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

2023-01-30 11:23 UTC, seu0313 commented on Calculator/Calculator/Model/Extension.swift
> +extension String {
[P3] Extension.swift 파일 내에 같이 작성해주셨네요. Extension 그룹을 만들고 하위 파일로 구분하는 것이 좋아보입니다

```
Extension
ㄴ Double+Extension.swift
ㄴ String+Extension.swift
```

2023-01-30 11:23 UTC, seu0313 commented on Calculator/Calculator/Model/Extension.swift
> +        return split(separator: target).map { String($0) }
String의 `components(separatedBy:)`와 `split(separator:)`는 어떤 차이가 있나요?

2023-01-30 11:23 UTC, seu0313 commented on Calculator/Calculator/Model/Operator.swift
> +        return lhs / rhs
Divide by Zero 예외 처리를 잘 해주셨네요 👍
`nan`은 어떤 걸 의미하나요?

2023-01-30 11:23 UTC, seu0313 commented on Calculator/Calculator/Model/Operator.swift
> +enum Operator: Character, CaseIterable {
`CaseIterable` 프로토콜을 채택해주셨네요 👍 
`CaseIterable`을 채택하신 이유가 무엇인가요? 채택하면 어떤 것을 사용할 수 있나요?

2023-01-30 11:23 UTC, seu0313 commented on Calculator/OperatorTests/OperatorTests.swift
> +        let expectationValue:Double = 7
[P2] `let inputlhs: Double`와 같이 콜론 뒤에 한 칸씩 띄워주는 것이 좋을 것 같아요

2023-01-30 11:23 UTC, seu0313 commented on Calculator/SplitTests/SplitTests.swift
> +        sut = nil
SplitTests에서 sut를 사용하지 않는 것 같아요 👀

2023-01-30 11:23 UTC, seu0313 commented on Calculator/SplitTests/SplitTests.swift
> +        XCTAssertEqual(result, expectedValue)
[P3] `given, when, then` 주석 사이에 한 칸씩 줄바꿈이 되어있으면 구분하기 좋을 것 같아요

2023-01-30 11:23 UTC, llingo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
[P3] 아래의 고차 함수의 클로저 부분 정리가 필요할 것 같아요 :)

```swift
// 기존
separatedOperands = separatedOperands.map{ if $0.contains("⎼") { return $0.replacingOccurrences(of: "⎼", with: "-")} else {
    return $0
} }
```

한 줄로 표현하고 싶으셨다면 `삼항 연산자`를 사용하는 방법도 있을 것 같아요
```swift
조건 ? 참 : 거짓
```

---

A의 결과를 B에 저장한 후 B를 사용해서 C를 만드는 것은 절차형 프로그래밍인 것 같아요.
고차 함수의 특징을 활용해보면 좋을 것 같아요 👀

> 아래 예시는 위에서 먼저 고민해본 후 참고하시면 좋을 것 같습니다.

<details>
    <summary>예시</summary>

  ```swift
  static func parse(from input: String) -> Formula {
      var operandsQueue = CalculatorItemQueue<Double>()
      var operatorsQueue = CalculatorItemQueue<Operator>()
      
      input
          .compactMap { Operator(rawValue: $0) }
          .forEach { operatorsQueue.enqueue(item: $0) }
  
      componentsByOperators(from: input)
          .map { $0.contains("⎼") ? $0.replacingOccurrences(of: "⎼", with: "-") : $0 }
          .compactMap { Double($0) }
          .forEach { operandsQueue.enqueue(item: $0) }
  
      return Formula(operands: operandsQueue, operators: operatorsQueue)
  }
  ```

</details>

2023-01-30 11:23 UTC, llingo commented on Calculator/Calculator/Model/Formula.swift
> +    mutating func result() -> Double {
요구사항 대로 잘 구현해주셨네요 👍

2023-01-30 11:23 UTC, llingo commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		1C67CCDB298400C400FC0206 /* OperatorTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1C67CCD32983F60D00FC0206 /* OperatorTests.swift */; };
Xcode Project 파일을 보니 테스트 객체마다 타겟을 생성해주신 것 같아요 😅

![스크린샷 2023-01-30 오후 8 18 28](https://user-images.githubusercontent.com/94151993/215463035-12722a9e-1846-4e4b-be7a-9c09f6622c69.png)

---

[P2] CalculatorTests 타겟에 파일을 추가하여 `하나의 테스트 타겟`으로 변경하는 것이 좋을 것 같아요

|타겟 정보|테스트 파일 폴더|
|:---:|:---:|
|![스크린샷 2023-01-30 오후 5 02 45](https://user-images.githubusercontent.com/94151993/215420729-a039e018-72a1-47f7-ad3b-3f1b1d9d9653.png)|![스크린샷 2023-01-30 오후 8 19 39](https://user-images.githubusercontent.com/94151993/215463272-8ff0d85d-6463-47f4-963b-8c03e0fb46ca.png)|

2023-01-31 00:46 UTC, kimseongj commented on Calculator/Calculator/Model/Extension.swift
> +extension String {
수정했습니다!

2023-01-31 00:57 UTC, kimseongj commented on Calculator/SplitTests/SplitTests.swift
> +        sut = nil
사용하지 않았는데 sut를 선언했군요..ㅎ 수정했습니다!

2023-01-31 01:07 UTC, kimseongj commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
수정했습니다! 
가독성을 생각해서 저런 식의 코드를 작성했던거 같습니다.!

2023-01-31 01:55 UTC, kimseongj commented on Calculator/Calculator/Model/Operator.swift
> +enum Operator: Character, CaseIterable {
`CaseIterable`을 사용하면 enum에 있는 case들을 순서대로 나열시켜주는 역할을 합니다.
`CaseIterable`안에 정의되어 있는 AllCases를 호출하여 나열시켜줄 수 있습니다.

2023-01-31 02:18 UTC, kimseongj commented on Calculator/Calculator/Model/Extension.swift
> +        return split(separator: target).map { String($0) }
1. components(separateBy:)
```swift
func components(separatedBy separator: String) -> [String]
```
components는 분리해주는 값의 타입이 String이며, [String]배열로 반환해줍니다.

2. split(separator:)
```swift
func split(separator: Character, maxSplits: Int = Int.max, omittingEmptySubsequences: Bool = true) -> [Substring]
``` 
split은 분리해주는 값의 타입이 Character이며, [Substring]으로 반환해주기 때문에 나중에 String으로 변환시켜줘야 합니다.

2023-01-31 02:21 UTC, kimseongj commented on Calculator/Calculator/Model/Operator.swift
> +        return lhs / rhs
`nan`은 "Not a Number"의 약자입니다.
유한한 수나 무한대가 아닌 값을 나타낼 때 사용됩니다. 
만약 3을 0으로 나눈다면, 값은 무한대이기 때문에 사용되었습니다.

2023-01-31 02:28 UTC, kimseongj commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		1C67CCDB298400C400FC0206 /* OperatorTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1C67CCD32983F60D00FC0206 /* OperatorTests.swift */; };
수정했습니다! 감사합니다!

2023-01-31 02:37 UTC, llingo commented on Calculator/Calculator/Model/Extension.swift
> +        return split(separator: target).map { String($0) }
좋습니다 💯

2023-01-31 02:42 UTC, llingo approved these changes
송준 STEP 2도 수고하셨습니다 :)
다음 스탭도 화이팅입니다. 🎉

2023-01-31 02:42 UTC, llingo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
전보다 훨씬 깔끔해졌네요 🎉

2023-01-31 02:42 UTC, llingo commented on Calculator/Calculator/Model/Extension.swift
> +
[P2] Extension.swift 파일은 더 이상 필요 없을 것 같아요

2023-01-31 02:43 UTC, merged