계산기 [STEP 2] Andrew
yagom-academy/ios-calculator-app pull request #442
Opened 2023-02-01 13:37 UTC by Andrew-0411

@Judy-999
안녕하세요 Judy STEP2 PR 보내드립니다.
STEP1은 자료구조에 대해 깊게 생각했다면 
STEP2는 UML에서 각각의 swift 파일들은 무슨역할을 하는건지 그래서 무엇만 작성해야할지 생각을 많이 한거 같습니다. 🤔

## 고민했던점 & 트러블슈팅
**Unit Test를 활용한 트러블슈팅**
![](https://i.imgur.com/6KTZkHR.png)
- UML에 전달인자레이블인 with를 split with 옵션값하고 혼동해서 with로 사용했고 노란색 경고창이여서 무시하고 코드를 작성하고 테스트를 돌렸습니다.
- 이상하게도 Unit Test가 오래 걸렸고 다행이도 Unit Test 덕분에 무한루프가 돌아간다는 사실을 알았습니다.
- separator 옵션값으로 변경하니 String으로 변경해야 한다는 오류가 나왔고 아래의 주석처럼 하였더니 Unit Test가 성공하였습니다!
- 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Nan 끼리의 비교**
![](https://i.imgur.com/uMYaVwY.png)
- nan과 nan을 비교할 경우 똑같은 타입?이라서 True가 나올줄 알았지만 NaN은 다른 NaN을 포함하여 결과라 false를 반환했습니다.
- 하나의 NaN이 다른 NaN과 비교를 하면 무조건 false가 나오므로 isNaN을 사용하여 값이 NaN인지 테스트 하였습니다.

**map과 forEach의 차이점**
![](https://i.imgur.com/L3EV9fi.png)
- filter로 피연산자와 연산자 중에서 피연산자를 걸러내고 map을 활용해서 queue에 값을 넣으려고 했습니다.
- 이미지 처럼 map을 사용하니 map은 사용되지 않을거라고 경고창이 나왔습니다.
- map과 forEach는 둘다 배열을 순회하면서 각 요소에 대해 callback을 실행한다는 공통점이 있습니다.
- 하지만 map은 새 배열을 return 하기 때문에 map을 사용할 경우 새 배열을 받을 변수를 따로 만들어서 map으로 값을 받아야 했습니다.
- map을 forEach로 변경해서 새로운 변수를 만들지 않고도 queue에 값을 순차적으로 넣도록 변경하였습니다.

2023-02-02 04:34 UTC, Judy-999 requested changes
수고하셨습니다 Andrew 👏👏

UML만 보고 코드를 구현한다는게 쉽지 않으셨을 텐데 잘 구현하셨네요 👍
지금은 어려워도 계산기 프로젝트에서 고민하셨던 부분들이 나중에 큰 도움이 되실겁니다 😊

---

## 고민했던점 & 트러블슈팅
### Unit Test를 활용한 트러블슈팅
> - UML에 전달인자레이블인 with를 split with 옵션값하고 혼동해서 with로 사용했고 노란색 경고창이여서 무시하고 코드를 작성하고 테스트를 돌렸습니다.
> - 이상하게도 Unit Test가 오래 걸렸고 다행이도 Unit Test 덕분에 무한루프가 돌아간다는 사실을 알았습니다.
> - separator 옵션값으로 변경하니 String으로 변경해야 한다는 오류가 나왔고 아래의 주석처럼 하였더니 Unit Test가 성공하였습니다!

`split`메서드로 고생하셨던게 느껴지네요 🥲 메서드의 이름이 같아도 매개변수가 다른 경우가 있으니 정확한 메서드를 사요하고 있는지 확인해야 합니다! 그래도 다행히 테스트 과정에서 잘 찾아내셨네요 👍

이렇게 메서드의 매개변수만 다른 경우를 `overload`(오버로드)라고 하는데 `override`(오버라이드)와 혼동되기도 하니 어떤 개념인지 알아두시면 좋습니다!
<br>

### Nan 끼리의 비교
> - nan과 nan을 비교할 경우 똑같은 타입?이라서 True가 나올줄 알았지만 NaN은 다른 NaN을 포함하여 결과라 false를 반환했습니다.
> - 하나의 NaN이 다른 NaN과 비교를 하면 무조건 false가 나오므로 isNaN을 사용하여 값이 NaN인지 테스트 하였습니다.

`nan`은 **not a number** 뜻 그대로 숫자가 아닌 값을 의미합니다. 숫자가 아니라고 구분한 값들은 같은지 여부를 알 수가 없죠! `isNaN`을 사용해서 잘 테스트하셨네요 👍
<br>

### map과 forEach의 차이점
> - filter로 피연산자와 연산자 중에서 피연산자를 걸러내고 map을 활용해서 queue에 값을 넣으려고 했습니다.
> - 이미지 처럼 map을 사용하니 map은 사용되지 않을거라고 경고창이 나왔습니다.
> - map과 forEach는 둘다 배열을 순회하면서 각 요소에 대해 callback을 실행한다는 공통점이 있습니다.
> - 하지만 map은 새 배열을 return 하기 때문에 map을 사용할 경우 새 배열을 받을 변수를 따로 만들어서 map으로 값을 받아야 했습니다.
> - map을 forEach로 변경해서 새로운 변수를 만들지 않고도 queue에 값을 순차적으로 넣도록 변경하였습니다.

`map`과 `forEach`의 공통점과 차이점을 잘 알아보셨네요 👏 
`map을 활용해서 queue에 값을 넣으려고` -> 코멘트로도 남겼지만 `map`의 결과를 이용해서 queue를 생성하는 방식으로 진행하시면 좋을 것 같아요!

---

## UML
코드에서는 **String**과 **CalculateItem**은 관련이 없어 보이는데 UML에는 그렇지 않네요 🤔 확인해주세요~!

UML에 표시된 `+`와 `-`를 어떻게 해석하셨는지도 궁금하네요 👀

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/CalculateItem.swift
> +    }
`split`과 비슷한 동작을 하는 [components(separatedBy:)](https://developer.apple.com/documentation/foundation/nsstring/1413214-components) 메서드도 있는데 어떤 차이가 있는지 알아두시면 좋습니다 👍

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/Operator.swift
> +        }
`rhs`가 0인 경우는 예외상황이니 `guard`문으로 처리해도 좋을 것 같네요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/Operator.swift
> +        }
`Double.nan` 처럼 통일성 있게 0도 `Double.zero`로 표시할 수 있습니다~

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +    }
별다른 처리를 하지 않는 `override` 메서드는 제거하셔도 됩니다 🙂

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +    }
결국 마지막 값인 `Operator.divide`로 초기화될 텐데 모든 값을 써줄 필요는 없겠네요 🤔

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +    }
설정된 값을 해제하는 코드가 빠진 것 같아요~

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +    func test_1더하기2는3() {
이름에서 어떤 메서드를 테스트하는지 알 수 있으면 좋겠네요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +        let number2: Double = 2
1, 2보다는 의미를 나타내는 표현을 사용해주세요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +        let add = sut.calculate(lhs: number1, rhs: number2)
`result`와 `add`를 비교하는건 모호하게 느껴져요!

- `add`보다는 `결과` 또는 `계산(add)한 결과`라는 의미가 명확할 것 같습니다.
- `result` 대신 `기댓값`, `예상값` 같은 의미를 사용해도 좋습니다.

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +    }
의도한 대로 수행되고 있는지 테스트가 필요할 것 같아요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +    var operators = CalculatorItemQueue<Operator>()
UML에 `+`로 표시되어 있긴 하지만 수정까지 오픈되어 있을 필요는 없을 것 같아요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
`Operator` 인수명은 소문자로 시작합니다! `operator`와 같이 예약어를 사용하는게 권장되는 방법은 아니라 다른 표현을 사용하셔도 좋습니다.
```suggestion
        Operator.allCases.forEach { `operator` in
            result = result.map{ $0.split(with: `operator`.rawValue) }.flatMap { $0 }
        }
```

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
고차함수의 활용 좋습니다 👍

`flatMap` 역시 `map`의 역할을 하기 때문에 한 번에 처리할 수도 있습니다~

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        var result: Array<String> = [input]
```swift
private(set) var enqueueStack: [Element] = []
```
다른 코드에선 `[String]` 형식으로 배열의 타입을 표시하셨는데 코드 전체적으로 한 가지 방식으로 통일해주세요~!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
`map` 뒤에 띄어쓰기가 빠져있네요 👀
```suggestion
        Operator.allCases.forEach { Operator in
            result = result.map { $0.split(with: Operator.rawValue) }.flatMap { $0 }
        }
```

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +    }
`result`가 선언만 되고 사용하지 않고 있네요~

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +    func test_1더하기2빼기3곱하기4로입력된값을_parse에넣으면_각각연산자와_피연산자로_나누어진다() {
음수가 들어간 경우도 테스트가 필요할 것 같아요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        componentsByOperators(from: input).compactMap { Double($0) }.forEach { operands.enqueue(element: $0) }
`CalculatorItemQueue`를 `var`로 생성하고 `enqueue`로 변경하는 것보다 고차함수의 결과로 생성된 배열로`CalculatorItemQueue`를 생성하는게 효율적일 것 같아요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +        componentsByOperators(from: input).compactMap { Double($0) }.forEach { operands.enqueue(element: $0) }
고차함수의 활용 좋습니다 👍

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/CalculateItem.swift
> +    }
`split`은 직접 구현한 메서드니 역시 테스트가 필요할 것 같아요 🙂

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/Formula.swift
> +            }
띄어쓰기가 빠져있네요 👀
```suggestion
            if let prev = operands.dequeue(), let next = operands.dequeue(), let `operator` = operators.dequeue() {
                result = `operator`.calculate(lhs: prev ,rhs: next)
            }
```

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +        let inputOperand: Array<Double> = [1,2,3,4]
역시 배열의 타입 선언의 형식을 통일해주세요!

```suggestion
        let inputOperand: Array<Double> = [1, 2, 3, 4]
```
`,` 다음은 한 칸씩 띄워주세요 🙂

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/CalculateItem.swift
> +    }
**CalculateItem**과는 관계 없는 코드이니 다른 파일로 분리하는게 좋을 것 같아요!

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/Calculator/ExpressionParser.swift
> +
불필요한 개행 1️⃣

(코드 전체적으로 불필요한 개행이나 컨벤션이 통일되지 않은 개행이 있는지 확인해주세요 🙂)

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +
불필요한 개행 2️⃣
개행이 두 번 되어 있네요~

2023-02-02 04:34 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +
불필요한 개행 3️⃣

2023-02-02 05:22 UTC, Andrew-0411 commented on Calculator/Calculator/CalculateItem.swift
> +    }
split은 swift에 내장되어 있어서 import없이 사용할 수 있고 components는 Foundation을 import해야 사용할 수 있습니다.

split은 반환형이 [SubString]이고 components는 [String] 입니다.

2023-02-02 05:34 UTC, Andrew-0411 commented on Calculator/OperatorTests/OperatorTests.swift
> +    }
Operator의 case중에서 아무거나 하나를 초기화 하는 방법 말고 다른 방법은 없을까요?
Operator뒤에 allCases, self, Type  다 사용해봤는데 다른 초기화 방법을 찾지 못해서요

2023-02-02 06:02 UTC, Andrew-0411 commented on Calculator/OperatorTests/OperatorTests.swift
> +        let number2: Double = 2
아 1과 2가 값인 1과 2가 아니라 변수이름 뒤에 붙어 있는 1과 2였군요 😆

당연한건데 한참을 바보 같이 값을 어떻게 바꾸라는건지 생각하고 있었네요 ㅎ

firstNumber와 secondNumber로 변경하였습니다!

2023-02-02 06:11 UTC, Andrew-0411 commented on Calculator/OperatorTests/OperatorTests.swift
> +        let add = sut.calculate(lhs: number1, rhs: number2)
result를 기대값인 expectedValue로 변경하였고 add와 다른 사칙연산들은 addResult형식으로 변경하였습니다

2023-02-02 06:19 UTC, Andrew-0411 commented on Calculator/Calculator/ExpressionParser.swift
> +        }
operatorElement로 수정하였습니다

2023-02-02 06:24 UTC, Andrew-0411 commented on Calculator/Calculator/Formula.swift
> +    var operators = CalculatorItemQueue<Operator>()
접근을 막기는 해야되는데 읽기도 해야되니까 private (set) 으로 변경하였습니다

2023-02-02 06:34 UTC, Chanhhyuk commented on Calculator/Calculator/ExpressionParser.swift
> +        var result: Array<String> = [input]
제네릭 타입을 <>로 사용하기 때문에 헷갈리지 않게? [String] 방식으로 통일했습니다

2023-02-02 06:52 UTC, Andrew-0411 commented on Calculator/Calculator/CalculateItem.swift
> +    }
ExtensionString 파일을 따로 만들어서 분리하였습니다

2023-02-02 08:41 UTC, Andrew-0411 commented on Calculator/Calculator/CalculateItem.swift
> +    }
```swift
    func test_숫자와부호가섞여서들어있을때_숫자값만을_반환하는지_확인(){
        // given
        let inputValue = "1+2+3+4+5"
        
        // when
        let split = inputValue.split(with: "+")
        let expectedValue = ["1","2","3","4","5"]
        
        // then
        XCTAssertEqual(split, expectedValue)
    }
```
for문을 사용해서 테스트 한번에 하나의 부호만 빼보는게 아니라 여러 부호를 빼보고 싶었는데 잘 안되었네요
- * / 도 테스트하려면 따로 테스트함수를 만들어 줘야 될까요?

2023-02-03 00:42 UTC, Andrew-0411 commented on Calculator/Calculator/Formula.swift
> +    }
FormulaTests 파일을 만들어서 테스트를 해봤습니다

2023-02-03 00:44 UTC, Andrew-0411 commented on Calculator/Calculator/Formula.swift
> +    }
<img width="406" alt="스크린샷 2023-02-03 오전 9 36 28" src="https://user-images.githubusercontent.com/45560895/216483336-74fff37a-ad1f-4b26-82cf-4fe092763ad3.png">
print문으로 테스트 해본것인데요 FormulaTests를 돌리다가 우연히도 Operator가 잘못되었음을 찾았습니다.
guard문을 제가 잘못 고쳐서 일어난 일이였네요 😇

2023-02-03 01:45 UTC, Andrew-0411 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +    func test_1더하기2빼기3곱하기4로입력된값을_parse에넣으면_각각연산자와_피연산자로_나누어진다() {
<img width="268" alt="스크린샷 2023-02-03 오전 10 43 30" src="https://user-images.githubusercontent.com/45560895/216491322-09884a40-920b-4a29-9065-4ab43f68f2aa.png">
음수를 제가 직접 -를 적는거랑 스토리보드에 있는 버튼 어트리뷰트에 있는 -를 복붙해서 사용한거랑 다르게 인식하네요
예를 들어 제가 1+--2를 음수2의 앞에 -를 제가 적는거랑 스토리보드에 있는 -를 복붙해서 같다 붙이는거랑 다른결과를 출력합니다.
왜그런걸까요? 그리고 이런 방법 말고는 다른 방법은 없을까요? 스토리보드에 있는 -를 tag이름을 따로 붙여줘서 구분을 한다던지 그런 방법이요

2023-02-03 02:30 UTC, Andrew-0411 commented
String과 CalculateItem에 관해서 UML 변경했습니다.
UML에 -는 접근제한자 중에 제일 접근이 제한되는 private으로 사용하였고
+는 같은 모듈내에서 사용가능 하지만 모듈 외부에서는 접근 불가능한 internal을 사용하였습니다.

STEP2를 하면서 문법과 다른 메서드기능들을 많이 알아봤고
Unit Test로 에러나 버그를 많이 발견했지만 한계가 있어서 print를 병행하면서 사용했는데요
breakPoint를 배웠으니 좀 더 공부해서 print문을 지양해야 겠다고 생각했습니다 🤔

2023-02-03 02:54 UTC, Andrew-0411 commented on Calculator/Calculator/ExpressionParser.swift
> +        componentsByOperators(from: input).compactMap { Double($0) }.forEach { operands.enqueue(element: $0) }
```swift
let operators = input.compactMap { Operator(rawValue: $0) }
```
이렇게 고참함수로 생성된 배열로 예를들어 ["+", "-"] 결과값이 배열로 CalculatorItemQueue를 생성하는 방식으로 접근했는데 잘 안되었네요 제가 접근한 방식이 맞았을까요?

2023-02-03 04:10 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +    }
하나의 case로 선택해서 초기화해주시거나, 각 테스트마다 새로운 case를 적용해서 하고 있으니 아예 초기화작업 없이 진행해도 될 것 같네요!

2023-02-03 04:11 UTC, Judy-999 commented on Calculator/OperatorTests/OperatorTests.swift
> +        let number2: Double = 2
아하 명확하게 적어야했는데 죄송해요 😅

2023-02-03 04:12 UTC, Judy-999 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +    func test_1더하기2빼기3곱하기4로입력된값을_parse에넣으면_각각연산자와_피연산자로_나누어진다() {
음수(-)와 빼기가 다른 기호인 것입니다!
애초에 다른 기호이니 두 기호로 음수인지 빼기인지 구분하는 방법이 좋을 듯 하네요 🙂

2023-02-03 04:14 UTC, Judy-999 commented on Calculator/Calculator/CalculateItem.swift
> +    }
어차피 하나의 Charactor로 구분할 수 있는지 테스트 하는 것이니 +와 -를 나눠서 테스트할 필요는 없을 것 같네요~

2023-02-03 04:19 UTC, merged