계산기 [Step3] 레옹아범
yagom-academy/ios-calculator-app pull request #445
Opened 2023-02-01 18:45 UTC by fatherLeon

@Judy-999 
안녕하세요 쥬디 드디어 계산기 마지막스텝 PR이네요
기존에 사용하지않은 여러 개념이 나와서 구현에만 너무 급급하여 코드가 많이 난잡한것 같네요😅
이전 스텝들처럼 좋은 리뷰 부탁드립니다🙏🙏

# 고민한 점🧐
### StackView내의 StackView 지우기
#### 수정 전 코드
```swift
func removeAllStackView() {
    let allSubViewsInStackVIew = self.stackViewInScrollView.arrangedSubviews
    for stackView in allSubViewsInStackVIew {
        self.stackViewInScrollView.removeArrangedSubview(stackView)
    }
}
```

* 기존 스크롤 뷰내에 있는 가장 큰 스택뷰의 removeArrangedSubview를 사용하여 뷰를 제거하여 줬는데 해당 메소드는 스택 뷰에서 뷰의 위치나 사이즈 관리를 더 이상 하지 않을 뿐이지 스택뷰의 subviews 배열을 삭제해주지 않으므로 뷰 계층에 일부 남아있는 부작용이 있었습니다
* 이로 인해 새로운 연산이 추가 될 경우 이전 내용이 같이 출력되는 문제가 있었습니다

#### 수정 후 코드
```swift
func removeAllStackView() {
    let allSubViewsInStackVIew = self.stackViewInScrollView.arrangedSubviews
    for stackView in allSubViewsInStackVIew {
        stackView.removeFromSuperview()
    }
}
```

* 이후 stackView의 removeFromSuperview메소드를 사용하여 현재 스택뷰에서 삭제하는 것은 물론이고 뷰 계층에도 따로 안남도록 삭제하였습니다

### 스크롤뷰가 긴 상황에서 새로운 연산이 들어갈 때 자동 스크롤 하기
#### 수정 전 코드
```swift
func scrollToBottom() {
    if self.scrollView.contentSize.height < self.scrollView.bounds.size.height { return }
    self.stackViewInScrollView.layoutIfNeeded()
    let bottomOffset = CGPoint(x: 0, y: self.scrollView.contentSize.height - self.scrollView.bounds.size.height)
    self.scrollView.setContentOffset(bottomOffset, animated: true)
}
```

* 기존 코드는 구글링하여 참고하였습니다
* 현재 저희 계산기 내의 스크롤 뷰의 높이와 스크롤뷰의 contentSize의 높이가 점차 커지다가 뷰의 safearea의 부분을 넘어서지 않기 때문에 contentSize의 높이가 스크롤 뷰의 높이를 추월할 때 밑의 내용을 다시 보여주도록 만들었습니다
* setContentOffset의 경우 스크롤뷰와 관련하여 해당 뷰의 offset을 재 정의해주는 메소드로 현재 contentSize와 스크롤 뷰의 높이를 빼서 새 연산이 들어올 경우 아래로 내려가게 세팅을 해줬습니다
* 그러나, 이 부분에서 뷰가 추가되었음에도 불구하고 이 함수를 실행할 시 한박자 늦게 스크롤 되는 문제가 있었습니다

#### 수정 후 코드
```swift
    func scrollToBottom() {
        if self.scrollView.contentSize.height < self.scrollView.bounds.size.height { return }
        self.scrollView.layoutIfNeeded()
        self.stackViewInScrollView.layoutIfNeeded()
        let bottomOffset = CGPoint(x: 0, y: self.scrollView.contentSize.height - self.scrollView.bounds.size.height)
        self.scrollView.setContentOffset(bottomOffset, animated: true)
    }
```

* 디버깅 와중에 스택뷰를 추가 할 때마다 contentSize가 즉각적으로 커지지 않는다는 것을 알게 되었습니다
* `layoutIfNeeded`메소드는 해당 서브뷰들에 대한 레이아웃을 즉각적으로 업데이트 해줌으로 한박자 늦게 높이가 생기는 문제를 해결해주었습니다

# 조언을 얻고 싶은 부분😅
### NumberFormatter
```swift
func setNumberFormatter() {
    self.numberFormatter.numberStyle = .decimal
    self.numberFormatter.roundingMode = .halfUp
    self.numberFormatter.usesSignificantDigits = true
    self.numberFormatter.maximumSignificantDigits = 20
}
```

* numberFormatter와 관련해서 찾아보니 SignificantDigits와 관련한 내용을 봤습니다
* 유효숫자 관련 내용이라는 것을 확인해 20개만 유효숫자가 표시하게 사용하였는데 이럴 경우 20자 이상이 넘어갈 경우에도 표시가 되는 문제가 있었습니다

```swift
self.numberFormatter.maximumIntegerDigits = 20
```

* 이렇게 정수부분만 표시 숫자가 20개 표시될 수 있게 한다면 20자 이상이 될 경우 곧바로 0으로 출력이 되거나

```swift
self.numberFormatter.maximumIntegerDigits = 10
```

* 이렇게 유효숫자 아래로 정수형 부분을 줄 경우 `1,234,567,890` 이후 값에 1을 넣는다면 `2,345,678,901`과 같이 짤리는 부분이 있는데 numberFormatter 어떤 키워드를 검색하고 공부해봐야할까요???

2023-02-02 15:40 UTC, Judy-999 requested changes
마지막 STEP까지 잘 구현해주셨네요 👏👏
계산기가 간단해보여도 여러 복잡한 로직을 가지고 있어서 힘드셨을거예요 😅
그럼에도 마지막 STEP까지 잘 해주셨습니다 👍
계산기는 다양하게 구현될 수 있어서 세세한 로직보다는 전체적인 컨벤션이나 기능구현 위주로 본 점 알아주세요 🙌

---

## 고민한 점🧐
### StackView내의 StackView 지우기
> - 기존 스크롤 뷰내에 있는 가장 큰 스택뷰의 removeArrangedSubview를 사용하여 뷰를 제거하여 줬는데 해당 메소드는 스택 뷰에서 뷰의 위치나 사이즈 관리를 더 이상 하지 않을 뿐이지 스택뷰의 subviews 배열을 삭제해주지 않으므로 뷰 계층에 일부 남아있는 부작용이 있었습니다
> - 이로 인해 새로운 연산이 추가 될 경우 이전 내용이 같이 출력되는 문제가 있었습니다
> - stackView의 removeFromSuperview메소드를 사용하여 현재 스택뷰에서 삭제하는 것은 물론이고 뷰 계층에도 따로 안남도록 삭제하였습니다

`removeFromSuperview`과 `removeArrangedSubview`의 차이를 잘 알아보셨네요 👍 `removeFromSuperview`만 해도 화면에서 사라지긴 하지만 작성해주신 대로 **스택 뷰에서 뷰의 위치나 사이즈 관리를 더 이상 하지 않**도록 명시적으로 `removeArrangedSubview` 처리도 같이 해주시면 좋을 것 같네요 🙂
<br>

### 스크롤뷰가 긴 상황에서 새로운 연산이 들어갈 때 자동 스크롤 하기
> - 뷰가 추가되었음에도 불구하고 이 함수를 실행할 시 한박자 늦게 스크롤 되는 문제가 있었습니다
> - 디버깅 와중에 스택뷰를 추가 할 때마다 contentSize가 즉각적으로 커지지 않는다는 것을 알게 되었습니다
> - layoutIfNeeded메소드는 해당 서브뷰들에 대한 레이아웃을 즉각적으로 업데이트 해줌으로 한박자 늦게 높이가 생기는 문제를 해결해주었습니다

`layoutIfNeeded`로 잘 해결하셨네요 👏 뷰는 시각적인 변경이 반영되는 Drawing Cycle을 가지고 있습니다. 더불어 `setNeedsLayout`과 `layoutSubviews`도 알아두시면 좋은데 아직은 어려운 개념일 수 있으니 나중에 여유있으실 때 [관련 블로글](https://tech.gc.com/demystifying-ios-layout/)나 [WWDC](https://developer.apple.com/videos/play/wwdc2015/219/)를 참고해보세요~ 
<br>

## 조언을 얻고 싶은 부분😅
> - numberFormatter와 관련해서 찾아보니 SignificantDigits와 관련한 내용을 봤습니다
> - 유효숫자 관련 내용이라는 것을 확인해 20개만 유효숫자가 표시하게 사용하였는데 이럴 경우 20자 이상이 넘어갈 경우에도 표시가 되는 문제가 있었습니다
> - 이렇게 정수부분만 표시 숫자가 20개 표시될 수 있게 한다면 20자 이상이 될 경우 곧바로 0으로 출력이 되거나
> - 이렇게 유효숫자 아래로 정수형 부분을 줄 경우 1,234,567,890 이후 값에 1을 넣는다면 2,345,678,901과 같이 짤리는 부분이 있는데 numberFormatter 어떤 키워드를 검색하고 공부해봐야할까요???

`maximumIntegerDigits`의 경우 유효 숫자를 지키기 위해 앞의 숫자를 자르고, `maximumSignificantDigits`의 경우 유호 숫자를 지키기 위해 0으로 만드는 것 같네요 😅

20자리로 제한하기 위해서는 NumberFormatter가 아닌 입력 시 개수를 직접 제한해야 할 것 같습니다.
요구사항에 있지만 개인적으로 구현하기 까다로운 조건이라 생각하여 만약 구현이 복잡하거나 너무 오래걸리신다면 넘어가도 괜찮으시니 알려주세요!
<br>

---

## 오류 상항
실행하면서 발견한 오류 상황들 입니다. 수정 또는 의견을 알려주세요 ❗️

1. 0인 상황에서도 0이나 00을 누르면 추가되고 있습니다.
2. 소수점 아래 자리에는 0이 추가되지 않습니다. ex) 1.01, 1.1101 불가
3. 숫자 입력 이후에 `연산자 -> = -> 연산자 -> =`을 숫자가 계속 스크롤 뷰에 추가되는데 의도한 상황일까요?

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
>  class ViewController: UIViewController {
그냥 ViewController보단 네이밍을 해주시면 좋겠네요!

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private let numberFormatter = NumberFormatter()
`numberFormatter`를 전역으로 두고 사용하는 것 보다는 NumberFormatter 기능을 제공하는 메서드를 만들어 재사용하는 방식은 어떤가요? 👀

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
같은 동작을 하는 버튼들이 아니고, Title로 나눠서 다른 메서드를 실행한다면 애초에 다른 `@IBAction`으로 두는게 깔끔할 수도 있을 것 같네요.

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    func setNumberFormatter() {
외부에서 사용되는 메서드일까요? 접근제어자 챙겨주세요!

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +            }
`""`보다는 `isEmpty`가 의미를 나타내기 좋겠네요 🙂
```suggestion
            if self.currentOperand.isEmpty == false {
                addStackView(number: self.currentOperandLabel.text, operatorType: self.currentOperator)
            }
```

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.currentOperatorLabel.text = self.currentOperator
겹치는 코드가 많은 것 같아요. 가능하면 메서드로 분리해보는 것도 좋겠습니다!

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +                    self.inputs = ""
이렇게 지울 수도 있습니다 🙂
```suggestion
                    self.inputs.removeAll()
```

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.currentOperandLabel.text = "0"
`self`를 붙여주는 이유가 있을까요?

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +        operatorLabel.bottomAnchor.constraint(equalTo: enteredStackView.bottomAnchor, constant: 0).isActive = true
`operandLabel `를 StackView에 `addArrangedSubview`하고 추가적으로 코드로 `constraint`를 잡아준 이유는 무엇인가요?

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +        operandLabel.textColor = .white
`operatorLabel`와 `operandLabel`을 하나의 Label로 만들면 `enteredStackView` 없이도 가능하지 않을까 싶네요 🤔

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
`forEach`를 활용해볼 수 있겠네요!

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet private weak var stackViewInScrollView: UIStackView!
`scrollView`보다는 어떤 ScrollView 인지 의미를 담아주세요!

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +extension ViewController {
`extension`으로 분리해준 이유는 무엇인가요?

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var currentOperator: String = ""
코드 전반적으로 `""`가 자주 사용된다면 이렇게 직접 적는 하드코딩보다는 상수로 선언되어있으면 휴먼에러를 방지할 수 있을 것 같습니다!

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
>  class ViewController: UIViewController {
상속하지 않는다면 적절한 키워드로 표현해주세요~!

2023-02-02 15:40 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    func clickedOperator(_ operatorValue: String) {
화면 상에 터치가 발생한 경우이니 click보다는 touchup과 같은 네이밍이 좋을 것 같습니다~

2023-02-02 15:41 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet private weak var stackViewInScrollView: UIStackView!
`stackViewInScrollView` 역시 StackView인데 ScrollView로 끝나서 ScrollView로 오해할 수 있을 것 같아요. 어떤 StackView인지 표현하는 네이밍이 좋겠습니다 🙂

2023-02-03 04:18 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +    func setNumberFormatter() {
* 접근제어자와 추가로 ViewController내에 final을 붙여서 상속되지 않는 클래스임을 명시하였습니다!

2023-02-03 08:31 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.currentOperandLabel.text = "0"
해당 클래스(뷰 컨트롤러)의 프로퍼티를 사용한다는것을 명시적으로 표현하기 위해 작성하였습니다

2023-02-03 08:37 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +        operatorLabel.bottomAnchor.constraint(equalTo: enteredStackView.bottomAnchor, constant: 0).isActive = true
* addArangedSubview를 하기전에 해당 라벨들을 오토레이아웃을 걸어준다면`Unable to activate constraint with anchors`와 같은 에러가 표시되었습니다
* 아무래도 스택뷰 안에 내용이 없기 때문에 해당 오토레이아웃이 실행이 되지 않는다고 생각을 해서 `addArangedSubview` 메소드를 사용 후에 추가적으로 오토레이아웃을 잡아줬습니다
* 그런데 이미 스택뷰 자체의 오토레이아웃을 걸어줘서 굳이 라벨 각각에 대한 오토레이아웃을 설정해주지 않아도 원하던 UI가 표시되므로 해당 코드는 삭제하였습니다

2023-02-03 08:47 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +        operandLabel.textColor = .white
```swift
private func addStackView(number: String?, operatorType: String?) {
    guard let operandValue = number,
          let operatorValue = operatorType else { return }
        
    let formulaLabel = UILabel()
    formulaLabel.font = .preferredFont(forTextStyle: .title3)
    formulaLabel.text = "\(operatorValue) \(operandValue)"
    formulaLabel.textColor = .white

    self.stackViewInScrollView.addArrangedSubview(formulaLabel)
        
    scrollToBottom()
}
```
* 말씀대로 하나의 라벨을 스택뷰에 지속적으로 쌓을 수 있도록 코드를 구성하였습니다

2023-02-03 08:50 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
```swift
allSubViewsInStackVIew.forEach { label in
    self.stackViewInScrollView.removeArrangedSubview(label)
    label.removeFromSuperview()
}
```
* 위 조언대로 코드를 고치다보니 해당 라벨이 remove메소드가 있을까 의문이 들었는데
* 찾아보니 라벨은 UIView를 상속받고 있기 때문에 해당 메소드가 존재하고 작동하는 것을 확인했습니다

2023-02-03 08:57 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +extension ViewController {
* 위의 뷰컨트롤러 안의 내용은 뷰와 모델을 연결하여주는 컨트롤러의 역할을 하지만
* extension으로 확장한 뷰 컨트롤러의 메소드들은 컨트롤러의 역할보다는 순전히 뷰와 관련된 역할이 주된 역할이라고 생각을하여 조금 더 가독성을 높이기 위해 뷰와 관련 된 일을 하는 메소드들을 extension으로 분리하였습니다

2023-02-03 09:44 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +    private let numberFormatter = NumberFormatter()
``swift
private func formattingNumber(_ value: String) -> String {
    let formatter = NumberFormatter()
    formatter.numberStyle = .decimal
    formatter.usesSignificantDigits = true
    formatter.minimumSignificantDigits = 1
        
    guard let formattedNumber = formatter.number(from: value),
              let formattedOperand = formatter.string(from: formattedNumber) else { return "0" }
        
    return formattedOperand
}
```
* 기존에 중복된 코드도 있어서 메소드를 만드는 방식이 좋은것 같습니다👍
* `formattingNumber`라는 메소드를 만들어 문자열 값의 뒤에 0을 제거하거나 콤마를 추가한 문자열을 반환할 수 있게 했습니다

2023-02-03 10:09 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var currentOperator: String = ""
```swift
enum CalculatorInitial: String {
    case initValue = ""
    case initLabel = "0"
    
    func initializeValue() -> String {
        return self.rawValue
    }
}
```

* 위와 같이 열거형을 사용하여 `private var inputs: String = CalculatorInitial.initValue.initializeValue()` 이런식으로 사용할 수 있도록 만들었습니다

2023-02-03 10:24 UTC, fatherLeon commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.currentOperatorLabel.text = self.currentOperator
```swift
    private func resetOperand() {
        self.currentOperand.removeAll()
        self.currentOperandLabel.text?.removeAll()
    }
    
    private func resetOperator() {
        self.currentOperator.removeAll()
        self.currentOperatorLabel.text?.removeAll()
    }
    
    private func resetPropertity() {
        self.inputs.removeAll()
        self.currentOperand.removeAll()
        self.currentOperator.removeAll()
    }
    
    private func resetLabel() {
        self.currentOperatorLabel.text?.removeAll()
        self.currentOperatorLabel.text?.removeAll()
    }
```

* 라벨이나 프로퍼티를 리셋해주는 코드가 중복되는게 유난히 많은것 같아서 다음과 같이 메소드를 분리했습니다

2023-02-03 11:47 UTC, fatherLeon commented
### 오류
1. 0인 상황에서도 0이나 00을 누르면 추가되고 있습니다.
2. 소수점 아래 자리에는 0이 추가되지 않습니다. ex) 1.01, 1.1101 불가
3. 숫자 입력 이후에 연산자 -> = -> 연산자 -> =을 숫자가 계속 ScrollView에 추가되는데 의도한 상황일까요?

### 오류 해결
* 해당 오류는 전부 해결했습니다!!
* 2번 오류 같은 경우에는 화면에 1.01000이 표시가 되지만 실제 연산자를 누를 시 스크롤 뷰에는 1.01만 표시되도록 변경했습니다

2023-02-04 02:01 UTC, Judy-999 approved these changes
좋습니다 👍👍
STEP 3까지 고생하셨어요 👏
바로 머지 가능하지만 추가적으로 수정을 반영하고 싶으신지 알려주세요~!

2023-02-04 02:01 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +final class CalculatorViewController: UIViewController {
네이밍 좋습니다 👍 
일반적으로 파일 이름은 타입 이름과 동일하게 가지도록 합니다~!

2023-02-04 02:01 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
메서드에서 단순히 다른 메서드를 호출하기만 하고, 해당 메서드가 다른 곳에서 재사용되는 상황도 아닌데 메서드로 분리하신 이유가 있을까요?
해당 메서드의 코들르 바로 적어도 될 것 같네요 🙂

2023-02-04 02:01 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.currentOperatorLabel.text = self.currentOperator
`resetPropertity` 프로퍼티는 일반적인 단어라 대상을 표현하는게 좋겠네요!

2023-02-04 02:01 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +extension ViewController {
특정 역할의 메서드만 분리한 것이라면 `MARK` 주석으로 역할을 표시하는 방법도 좋습니다 🙂

2023-02-04 02:01 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +        self.currentOperandLabel.text = "0"
**CalculatorInitial** 이 적용될 부분 같네요!

2023-02-04 02:01 UTC, Judy-999 commented on Calculator/Calculator/Controller/ViewController.swift
> +    private var currentOperator: String = ""
`"."`이나 `-`도 같이 지정해서 사용할 수 있겠네요~

2023-02-04 02:29 UTC, merged