계산기 [STEP3] 리지
yagom-academy/ios-calculator-app pull request #449
Opened 2023-02-02 08:39 UTC by yijiye

@Judy-999  
주디 안녕하세요! step2에서 로직이 다 끝난줄 알았는데 여기가 진짜 찐이였습니다...
하면서 계속해서 오류가 나타나서 힘들었습니다.
혹시 놓친 오류가 발견된다면 알려주세요 🔥

# 고민이었던 점 & 해결과정

## stackView 활용
- 숫자가 입력되는 칸에 입력되고 연산자를 누르면 위로 올라가고 다시 초기화가 되어야 하는데, view를 확인해보니 scrollView 안에 stackView가 있고 그 안에 또 stackView가 존재했습니다. 처음에 있는 그대로 접근을 하려다 보니 가장 안에 있는 stackView에만 값이 올라갔다 내려가서 위로 계속해서 쌓이는게 아니라 값을 새로 바꿔주는 형태가 되었습니다.

### ⚒️ 해결과정
- 우선 안에 있는 stackView를 지우고 하나의 stackView를 남겨놓고 그안에 입력되어 쌓이도록 수정을 하였습니다. 
- `@IBOutlet weak private var stackView: UIStackView!` 를 viewController에 만들어 하나의 stackView와 연결시키고 stackView를 코드로 구현하여 연산자와 피연산자 text가 입력되도록 구현했습니다.
```swift
  private func addStackView() {
        
        guard let operandStackLabel = numberInput.text,
              let operatorStackLabel = operatorInput.text else {  return  }
        
        let stackLabel = UILabel()
        stackLabel.text = operatorStackLabel + " " + operandStackLabel
        stackLabel.numberOfLines = 0
        stackLabel.adjustsFontForContentSizeCategory = true
        stackLabel.font = UIFont.preferredFont(forTextStyle: .title3)
        stackLabel.textColor = .white
        stackView.addArrangedSubview(stackLabel)
        setScrollView()
        
    }
```
 
## 숫자 입력하는 칸에 NumberFormatter 적용
- 숫자가 3자리수씩 끊어서 입력되도록 구현하고자 했습니다. 처음엔 입력받는 메서드를 만들고 그 메서드를 Label.text에 반영시킬 때 NumberFormatter를 적용시키려고 하였는데, 여러 오류를 잡는 과정에서 숫자가 아닌게 들어가 return으로 빠지는 오류를 발견하였습니다. LLDB로 하나씩 타고 들어가서 확인해보니 처음 구현한 `func numberButtonTapped(_ sender: UIButton)` Bool 타입을 이용하여 조건문을 걸어준 메서드의 로직이 문제였습니다. 

### ⚒️ 해결과정
- 값을 입력해주는 부분을 연산프로퍼티로 정의하여 didSet에 적용시켜보았습니다. 초기값을 0으로 지정해두고 0이면 입력되는 숫자가 들어오고 0이 아니면 거기에 더해서 입력되는 로직으로 변경하였고 text에 입력될때 NumberFormatter가 적용되어 반환되는 `applyDecimalPoint()` 메서드의 반환값으로 넣어주었습니다.

```swift
    @IBAction func numberButtonTapped(_ sender: UIButton) {
        
        guard let number = sender.currentTitle else { return }
        if currentNumber == "0"  {
            currentNumber = number
        } else {
            currentNumber += number
        }
    }
```
    
```swift
   private var currentNumber: String = "0" {
        didSet {
            numberInput.text = applyDecimalPoint(number: currentNumber)
        }
    }
```

# 해결되지 않은 점 & 조언을 구하고 싶은 점

### scrollView 오류

- 1️⃣ stackView를 없애고 하나의 stackView만 남겨놓게 되면서 autoLayout 부분에 빨간색으로 변하면서 오류가 생기게 되었습니다. 이를 해결하고자 야곰닷넷 강의에서 본것을 참고하여 stackView와 scrollView의 높이를 같은 높이로 설정을 해주고 priority를 낮게 수정해주려고 시도했습니다. 그러나 이미 그렇게 적용이 되어 있었고, 그럼에도 오류가 발생하였습니다. 이부분이 왜 아직도 오류로 남아있는지 해결하지 못하여 조언을 구하고 싶습니다.

<img src = "https://i.imgur.com/YfBkxfx.png" width = "500">

- 2️⃣ scrollView를 새로 만들어 stackView가 더해질때 자동으로 올라가도록 구현을 했는데, 이상하게 반응속도가 조금 느린것 같습니다. 숫자가 다 입력되어 보여지는 화면아래에 숫자 1개가 들어가고 2번째 입력되면서 부터 자동으로 스크롤이 올라오는 것을 확인할 수 있었습니다. 정해준 조건 중에 y축의 문제라고 생각하여 그 부분의 수치를 바꿔서 입력해보았는데 숫자간의 간격이 달라지는 것 같아 해결책을 아직 찾지 못하였습니다. 혹시 이 부분이 1번의 오류와 연관이 있을까요? 어떤 부분을 찾아보는게 좋을까요?

### NumberFormatter 오류

- 전반적으로 숫자에 따른 여러가지 오류를 잡아야하는 일이 많았습니다. 그중에서 입력할때 20자리까지 보여져야 하는 조건이 있었는데, 이부분은 해결하지 못하였습니다...🥲 
- 처음 시도해본 방법은 `maximumFractionDigits =20 `을 조건으로 넣어주었는데 이 조건은 최대한으로 표현할 소수점의 자릿수를 나타내므로 전체숫자의 갯수를 잡아줄 수 없었습니다. 
- 다음으로 생각한 것은 `maximumIntergerDigits` 이였는데, 이건 Int 타입을 때만 적용이 되어 Double 타입과 타입을 맞춰야 한다는 어려움이 있었습니다.
이 외에 어떤 것들을 참고해 볼 수 있을까요? 

### 코드리팩토링

- 계산기에서 잡아야 하는 오류가 생각보다 많아서 하나를 만들어 놓으면 다른 곳에서 오류가 발견되고 리팩토링하고 발견하고가 반복되다 보니 코드가 너무 지저분해진 것 같습니다. 우선 한번 정리할 필요가 있다 생각하여 PR을 보내습니다. 남은 시간동안 조금 더 깔끔하게 리팩토링 해보도록 하겠습니다!

2023-02-03 02:02 UTC, Judy-999 requested changes
리지 수고하셨어요 🙌
마지막 STEP까지 잘 구현해주셨네요 👏👏
계산기가 간단해보여도 여러 복잡한 로직을 가지고 있고 계산에 따라 다양한 상황이 있어서 오류를 잡아내기 힘드셨을거예요 😅
그럼에도 마지막 STEP까지 잘 해주셨습니다 👍

---

## 해결되지 않은 점 & 조언을 구하고 싶은 점
### scrollView 오류
> 1️⃣ stackView를 없애고 하나의 stackView만 남겨놓게 되면서 autoLayout 부분에 빨간색으로 변하면서 오류가 생기게 되었습니다. 이를 해결하고자 야곰닷넷 강의에서 본것을 참고하여 stackView와 scrollView의 높이를 같은 높이로 설정을 해주고 priority를 낮게 수정해주려고 시도했습니다. 그러나 이미 그렇게 적용이 되어 있었고, 그럼에도 오류가 발생하였습니다. 이부분이 왜 아직도 오류로 남아있는지 해결하지 못하여 조언을 구하고 싶습니다.


ScrollView의 오토레이아웃을 잡는 것이 까다롭고 어려운 작업이라 잘 이해해두시면 좋습니다! 
현재 나타나는 오류는 `ScrollView의 높이가 불분명하다` 입니다. StackView의 높이와 제약을 지정해줬지만 ScrollView와 StackView 모두 비어있는 상태로는 고정된 높이가 없기 때문입니다. 
야곰닷넷에서 처럼 ScrollViewdml top을 SafeArea에서 특정 값만큼 떨어지도록 하면 해당 오류는 사라집니다. 하지만 그러면 입력한 숫자가 하단이 아닌 상단부터 나오게 되죠 😅 (한 번 해보시는 것도 좋습니다.)

현재 초기 높이가 없어서 경고가 뜨지만 실행은 되니 문제는 없습니다. 그래도 경고가 있으면 보기 좋지 않다면 초기 높이([Intrinsic Content Size](https://yagom.net/courses/autolayout/lessons/anatomy-of-a-constraint/topic/intrinsic-content-size/))를 가진 빈 Label을 StackView에 넣으면 해결 가능합니다 🙂
<br>

> 2️⃣ scrollView를 새로 만들어 stackView가 더해질때 자동으로 올라가도록 구현을 했는데, 이상하게 반응속도가 조금 느린것 같습니다. 숫자가 다 입력되어 보여지는 화면아래에 숫자 1개가 들어가고 2번째 입력되면서 부터 자동으로 스크롤이 올라오는 것을 확인할 수 있었습니다. 정해준 조건 중에 y축의 문제라고 생각하여 그 부분의 수치를 바꿔서 입력해보았는데 숫자간의 간격이 달라지는 것 같아 해결책을 아직 찾지 못하였습니다. 혹시 이 부분이 1번의 오류와 연관이 있을까요? 어떤 부분을 찾아보는게 좋을까요?

저는 입력되면 바로 올라오는 것 같은데 어떤 상황일까요? 문제 상황을 gif나 이미지로 같이 올려주시면 다시 확인해보겠습니다!
<br>

### NumberFormatter 오류
> - 전반적으로 숫자에 따른 여러가지 오류를 잡아야하는 일이 많았습니다. 그중에서 입력할때 20자리까지 보여져야 하는 조건이 있었는데, 이부분은 해결하지 못하였습니다...🥲
> - 처음 시도해본 방법은 maximumFractionDigits =20 을 조건으로 넣어주었는데 이 조건은 최대한으로 표현할 소수점의 자릿수를 나타내므로 전체숫자의 갯수를 잡아줄 수 없었습니다.
> - 다음으로 생각한 것은 maximumIntergerDigits 이였는데, 이건 Int 타입을 때만 적용이 되어 Double 타입과 타입을 맞춰야 한다는 어려움이 있었습니다.
> - 이 외에 어떤 것들을 참고해 볼 수 있을까요?

기본적으로 20자리의 숫자가 굉장히 큰 수라 다루기 어렵습니다 😅

20자리로 제한하기 위해서는 NumberFormatter가 아닌 입력되는 개수를 직접 제한해야 할 것 같습니다.
요구사항에 있지만 개인적으로 구현하기 까다로운 조건이라 생각하여 만약 구현이 복잡하거나 너무 오래걸리신다면 넘어가도 괜찮으시니 알려주세요!
<br>

### 코드리팩토링
> 계산기에서 잡아야 하는 오류가 생각보다 많아서 하나를 만들어 놓으면 다른 곳에서 오류가 발견되고 리팩토링하고 발견하고가 반복되다 보니 코드가 너무 지저분해진 것 같습니다. 우선 한번 정리할 필요가 있다 생각하여 PR을 보내습니다. 남은 시간동안 조금 더 깔끔하게 리팩토링 해보도록 하겠습니다!

처음부터 촘촘한 로직을 작성하면 좋긴 하지만 오류사항이 워낙 다양하니 우선 기능 구현 후 계속 리팩토링하는 방향도 좋습니다 👍
<br>

---

## 오류 상항
실행하면서 발견한 오류 상황들 입니다. 수정 또는 의견을 알려주세요 ❗️

1. 현재 계산이 한 번만 되고 있네요. 계속 이어서 다음 계산을 할 수 있어야 할 것 같네요.

2. 소수점(.)을 입력하면 화면에 표시가 되지 않습니다. 이후에 숫자를 입력해야 화면에 나오는데 바로 보여줘야할 것 같습니다. 

3. NaN 결과가 나온후 연산자 입력 시 ScrollView로 NaN이 올라갑니다. 적절한 결과값은 아니니 없애주는 작업이 필요할 것 같네요.

4. 음수(-)로 변경하고 숫자를 더 입력하면 음수 표현이 사라집니다.

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
>  class ViewController: UIViewController {
상속하지 않는다면 적절한 키워드로 표현해주세요~!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
>  class ViewController: UIViewController {
`ViewController`보다는 의미있는 네이밍을 해주세요!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    }
프로퍼티는 메서드보다 상단에 위치하게 해주세요~!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet weak private var scrollView: UIScrollView!
`stackView`와 `scrollView` 역시 의미를 가진 네이밍으로 표현해주세요 🙂

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    }
`didSet`을 활용하셨네요 👍

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    private var numberFormatter = NumberFormatter()
`numberFormatter`는 변경이 되고 있나요? `var`일 필요가 있는지 확인해보세요~

`applyDecimalPoint`를 통해 `,`를 넣고 계신 듯 한데, 전역으로 따로 두신 이유가 있을까요?

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        }
두 메서드 모두 `operatorButtonTapped` 메서드에서 사용되고 있는데, `numberInput.text == "0"`라는 조건이 반복되고 있으니 하나의 메서드로 만드는건 어떤가요? 👀

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        }
`checkInitialCondition`은 `isEnteredOperand`, 
`operandIsZero`은 `isChangeableOperator`를 결정하는 메서드 같아요.

모두 특정 값에 따라 true, false가 되는 것이라면 `isEnteredOperand`와 `isChangeableOperator`를 연산 프로퍼티로 구현하는 방법도 괜찮을 것 같네요!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    @IBAction func operatorButtonTapped(_ sender: UIButton) {
`@IBAction func`도 외부에서 사용하지 않는다면 역시 접근제어 처리를 해주세요 🙂

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        guard !currentNumber.contains(".") else { return }
`dot`과 `"."`은 다른걸까요?

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    }
`checkSign`은 이곳에서만 사용되는데 메서드로 분리하신 이유가 있을까요?
`checkSign`의 코드를 이곳에 작성해도 될 것 같네요!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    }
계산이 완료되지 않았더라도 `""`이 아니라 `"0"`으로 바뀌어야 하지 않나요? 🤔

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        resetOperatorInput()
세 메서드 모두 여기에서만 호출되고 reset하는 동작이니 하나의 메서드로 만드는건 어떤가요 👀

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        isFinishedCalculating = false
`isFinishedCalculating`이면 연산이 끝난는지 여부인 듯 한데, ACButton을 누르면 false 되는건 어떤 로직인지 설명해주세요~!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        stackLabel.numberOfLines = 0
해당 코드는 어떤 의미이고, 어떤 이유로 작성하신건가요?

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        guard let result = numberFormatter.string(from: NSNumber(value: operand)) else { return "" }
하나의 `guard let`문으로 사용할 수 있을 것 같네요~!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        stackView.arrangedSubviews.forEach{ $0.removeFromSuperview() }
`forEach`의 사용 좋습니다 👍

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +            .map {$0.components(separatedBy: " ").joined() }.joined(separator: "")
어떤 로직인지 설명해주세요 👀

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +            .map {$0.components(separatedBy: " ").joined() }.joined(separator: "")
```suggestion
        return calculateItems.map { $0.components(separatedBy: ",").joined() }
            .map { $0.components(separatedBy: " ").joined() }.joined(separator: "")
```

띄어쓰기가 빠졌네요 🙂

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        }
어떤 작업을 하는 코드인가요?

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        return resultLabel
이렇게 간략하게도 작성할 수 있습니다!

```suggestion
        guard let resultValue = formula.result() else { return "" }

        return String(resultValue)
```

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        return formatterNumber
가독성을 위해 개행을 넣어주시면 좋겠습니다~

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        guard let formatterNumber = numberFormatter.string(from: NSNumber(value: number)) else { return "" }
하나의 `guard`문으로 표현할 수 있겠네요 🙂
```suggestion
        guard let number = Double(resultLabel),
              let formatterNumber = numberFormatter.string(from: NSNumber(value: number)) else { return "" }
```

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +            print("계산오류")
역시 `print`만 하는 처리는 사용자는 느낄 수 없기 때문에 숫자를 `"0"`으로 만드는 것과 같은 특정 작업을 해주면 좋겠습니다!

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/Model/Enumeration/CalculatorError.swift
> +    case calcuate
어떤 상황에서 사용되는 에러인가요?

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +
메서드 첫 줄에 불필요한 개행이 많이 보이네요. 모두 제거해주세요!
이외에도 불필요한 개행을 전반적으로 정리해주세요 🙂

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        currentNumber = "0"
코드 전반적으로 `"0"`이 자주 사용되고 있는데 이렇게 직접 적는 하드코딩보다는 상수로 선언되어 있으면 휴먼에러를 방지할 수 있을 것 같습니다!

`","`나 `""`, `"."` 등에도 적용할 수 있겠네요 🙌

2023-02-03 02:02 UTC, Judy-999 commented on Calculator/Calculator/Model/Enumeration/ExpressionParser.swift
> +            }.flatMap{ $0 }
띄어쓰기를 지워주신건가요? 중괄호 `{` 전에는 띄우는게 맞습니다!

2023-02-03 02:12 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
>  class ViewController: UIViewController {
`final` 키워드로 표현했습니다!

2023-02-03 02:14 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
>  class ViewController: UIViewController {
`CalculatorViewController` 네이밍으로 변경하였습니다

2023-02-03 02:19 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +    @IBOutlet weak private var scrollView: UIScrollView!
`calculatorItemsStackView`
`calculatorItemsScrollView` 라는 네이밍으로 표현했습니다!

2023-02-03 02:28 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +    private var numberFormatter = NumberFormatter()
상수로 변경하였습니다 :)
전역으로 둔 이유는 `checkDecimalPoint` 에서 12.0 과 같은 수가 입력되었을 때, .0 을 제거해주는 곳에서도 `numberFormatter`가 사용되고 있어서 전역으로 따로 두었습니다!

2023-02-03 02:30 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +        guard !currentNumber.contains(".") else { return }
아니요 같습니다...!! 수정하였습니다

2023-02-03 02:32 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +    }
처음 의도한 바는 @IBAction 에서는 가독성을 위해 코드를 길게쓰지 않으려고 따로 함수를 분리해두었는데, 다시보니 함수를 새로 만들어서 그 함수를 넣어주니 중복되는 일이 발생해버렸습니다 😅 다시 수정하였습니다!

2023-02-03 02:38 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +        currentNumber = "0"
네임스페이스를 적용해보았습니다!

2023-02-03 02:39 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +        return resultLabel
코드가 너무 길어서 줄이고 싶어서 고민해봐도 생각이 안났는데...😅 감사합니다 주디!

2023-02-03 02:43 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +        resetOperatorInput()
하나의 함수가 하나의 기능을 한다고 접근해서 각각 메서드로 분리를 했는데, reset 하는 것을 하나의 개념으로 보고 하나로 묶는게 조금 더 깔끔한 것 같아 주디의 의견대로 반영해보았습니다!

2023-02-03 04:50 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +    private var numberFormatter = NumberFormatter()
관련하여 추가내용 아래 따로 적어두었습니다!

2023-02-03 04:51 UTC, yijiye commented on Calculator/Calculator/Model/Enumeration/CalculatorError.swift
> +    case calcuate
관련하여 추가내용 아래 따로 적어두었습니다!

2023-02-03 05:08 UTC, yijiye commented on Calculator/Calculator/CalculatorViewController.swift
> -
@Judy-999  NumberFormatter 관련하여 주디가 질문주신 내용에 대해 생각을 해보았습니다!

처음에 `numberFormatter`를 전역으로 해준 이유는 12.0 과 같은 수에서 .0으로 제거하는데도 사용되기 때문이였습니다. 그런데 이 부분을 삭제하고 `equlButtonTapped`를 실행하여 바로 계산을 해도 (0.8+0.2 = 1) 로 나오는 것을 확인할 수 있었습니다. 조건을 잡아준 적이 없는데 어떻게 실행되는건지 생각해보니`numberInput.text`에 `applyDecimalPoint`메서드를 이용해 적용이 되었기 때문이라고 생각했습니다.

처음 작성한 코드는 .0과 같은 불필요한 소수점 자리를 제거해주고, 입력될때 3자리 마다 콤마 (,)가 찍히도록 기능을 분리하였는데, 이미 `NumberFormatter`가 소수점이 제거되는 형태로 반환해준다고 이해를 했습니다.

제가 정리한 내용이 맞을까요? NumberFormatter에 대한 정확한 이해없이 사용하다보니 불필요한 코드를 많이 작성한거 같습니다 🥲

2023-02-03 06:10 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +        }
https://github.com/yagom-academy/ios-calculator-app/pull/449/commits/5ea095dd680b8847a58ba1236a3d6d46e07b9370
@IBAction 메서드에 하나로 합쳐서 적용시켜보았습니다!

2023-02-03 09:29 UTC, yijiye commented
오류 수정
> 1. 현재 계산이 한 번만 되고 있네요. 계속 이어서 다음 계산을 할 수 있어야 할 것 같네요.

https://github.com/yagom-academy/ios-calculator-app/pull/449/commits/cb024e87ded06751b091defd049070dbf9d336a6

> 2. 계산이 반복되도록 로직을 수정하였습니다. 이 과정에서 reset 메서드들이 반복되는 것 같아 메서드를 활용해보았는데요! 근데 reset 시키는 구문이 한줄이고 많지 않았습니다. 이럴 경우 그냥 코드로 필요한 곳에 입력하는게 좋을까요, 아니면 메서드로 분리해서 그 메서드를 호출시키는게 좋을까요? 

> 3. 소수점(.)을 입력하면 화면에 표시가 되지 않습니다. 이후에 숫자를 입력해야 화면에 나오는데 바로 보여줘야할 것 같습니다.

입력되는 값을 `currentNumber`로 접근하다보니 `numberFormatter`가 적용되어 소수점이 보이지 않았습니다. 이를 해결하고자 `numberInput.text`로 우선 접근하고 계산값만 `currentNumber`로 적용을 하였는데, 이렇게 되니 입력할때는 숫자가 길어져도 3자리 수가 콤마(,)로 구문되지 않는 문제(?)가 생겼습니다. ( 과제 예시에는 4자리 이상의 숫자가 없어서 이렇게 구현을 하는게 문제인지 아닌지 잘 모르겠습니다 😅 )

> 4. NaN 결과가 나온후 연산자 입력 시 ScrollView로 NaN이 올라갑니다. 적절한 결과값은 아니니 없애주는 작업이 필요할 것 같네요.

음수(-)로 변경하고 숫자를 더 입력하면 음수 표현이 사라집니다.

2023-02-03 09:43 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +    }
저도 이 부분이 명확하지 않아서 헷갈렸는데요!

![image](https://user-images.githubusercontent.com/114971172/216566698-8455d1ce-5be4-4ee9-89fd-27b937d12be1.png)

2+3-4+ 상태가 된다는 의미가 0이 아니라 비어있어야 하는건가 싶어서 이렇게 구현을 해보았습니다.
3번째 줄에 0의상태가 된다고 하여..1, 2번에서 요구하는 상태가 0을 의미하는것인가요? 🤔

2023-02-03 09:46 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +        isFinishedCalculating = false
AC 버튼을 누르고 나서 = 버튼이 다시 기능을 할 수 있게 해주려고 false 로 설정을 하였습니다. 현재는 계산이 반복되도록 로직을 수정하여 불필요한 코드라 생각하여 삭제하였습니다!

2023-02-03 09:50 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +        stackLabel.numberOfLines = 0
저는 처음에 구현되어 있던 대로 `stackView` 안에 또 다른 `stackView`가 들어가도록 하지 않고 그걸 삭제하여 하나의 `stackView`로 만들어 `Label`도 한번에 올라가도록 구현을 했습니다. 
그래서 `Label`을 새로 만들어주고 거기에 `operator`와 `operand`가 입력되도록 `stackLabel.text`를 위와같이 구현해보았습니다. 🙂

2023-02-03 10:12 UTC, yijiye commented on Calculator/Calculator/ViewController.swift
> +            .map {$0.components(separatedBy: " ").joined() }.joined(separator: "")
`arrangeCalculateItems()`메서드의 로직을 설명드리자면,
- `addStackView()` 가 호출되고 `stackView`의 `arrangedSubView`기능을 이용하여 `view`에 쌓인 `subView`들의 리스트를 확인할 수 있고 `forEach` 문으로 다 확인해줌 
- `subView`들을 돌면서 `UILabel`의 타입을 확인하여 그 `Label` 들을 `calculateItems`에 넣어줌
- return을 할때 `ExpressionParser` 를 이용하여 계산을 해야 하므로 `String` 타입으로 맞추어 반환해줌
- 입력된 값에 띄어쓰기가 포함되어 있어 그 부분을 제외하고 맵핑한 배열을 `joined` 해서 `String` 타입으로 변환시켜줌
 
이러한 과정을 거쳐서 저는 stackView에 쌓인 값들로 계산이 되도록 구현을해보았습니다.
원래코드의 의도는 입력되는 칸에 `NumberFormatter`가 적용되어 콤마까지 있어서 그 콤마를 제거해서 맵핑하고 `joined` 하고 또 띄어쓰기 제거하고 맵핑하고 `joined` 로 `String` 타입으로 변환시키도록 구현하였는데 로직이 수정되면서 입력되는 동안은 `NumberFormatter` 가 적용되지 않아 `map` 하는 과정이 하나 줄게되었습니다 😅

2023-02-04 04:08 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +    }
현재 입력된 숫자를 지운다는 의미 같은데 지운다는게 아예 화면에서 없애는게 아니라 초기화면에도 0은 표시되니 그 상태로 만드는게 아닐까 생각했습니다! 요구사항을 해석해서 구현하는 것이니 리지의 생각대로 진행하셔도 됩니다~

2023-02-04 04:15 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +        stackLabel.numberOfLines = 0
한 줄로 표현되는 것 같은데 numberOfLines을 0으로 설정하는 이유가 있을까요 🤔

2023-02-04 04:16 UTC, Judy-999 commented on Calculator/Calculator/ViewController.swift
> +            .map {$0.components(separatedBy: " ").joined() }.joined(separator: "")
특정 값을 제외한 값들로만 남기고 싶다면 filter를 사용하는게 유용하지 않을까 싶네요 🙂

2023-02-04 06:08 UTC, Judy-999 approved these changes
> 계산이 반복되도록 로직을 수정하였습니다. 이 과정에서 reset 메서드들이 반복되는 것 같아 메서드를 활용해보았는데요! 근데 reset 시키는 구문이 한줄이고 많지 않았습니다. 이럴 경우 그냥 코드로 필요한 곳에 입력하는게 좋을까요, 아니면 메서드로 분리해서 그 메서드를 호출시키는게 좋을까요?

한 줄이라도 의미나 기능을 분리하기 위해 메서드로 분리하는 건 좋다고 생각합니다! 해당 코드가 여러 곳에서 반복 사용 된다면 더더욱이죠 👍

> 입력되는 값을 currentNumber로 접근하다보니 numberFormatter가 적용되어 소수점이 보이지 않았습니다. 이를 해결하고자 numberInput.text로 우선 접근하고 계산값만 currentNumber로 적용을 하였는데, 이렇게 되니 입력할때는 숫자가 길어져도 3자리 수가 콤마(,)로 구문되지 않는 문제(?)가 생겼습니다. ( 과제 예시에는 4자리 이상의 숫자가 없어서 이렇게 구현을 하는게 문제인지 아닌지 잘 모르겠습니다 😅 )


우선 `currentNumber`의 DidSet을 구현하셨으니 숫자 패드를 누를 때 `numberInput.text`가 아닌 `currentNumber`의 값을 변경시켜야 하지 않을까요?

```swift
@IBAction private func numberButtonTapped(_ sender: UIButton) {
    restartCalculate()
    guard let number = sender.currentTitle else { return }

    if numberInput.text == Expression.zero  {
        currentNumber = number
    } else {
        currentNumber = currentNumber + number
    }
}
```

그리고 dot을 추가할 때는 `currentNumber`에도 추가해줘야 하겠네요!

```swift
@IBAction private func dotButtonTapped(_ sender: UIButton) {
    guard let dot = sender.currentTitle,
          let operand = numberInput.text else { return }
    guard !operand.contains(dot) else { return }
    
    currentNumber = operand + dot
    numberInput.text = operand + dot
}
```
<br>

> 확인해보니 계산결과가 끝나고 operator 버튼을 누르니 모든 값이 ScrollView로 올라가는 문제가 있었습니다. 1번 로직을 해결한 것과 같이 restartCalculate 메서드를 호출시켜 초기화시켜 주는 과정을 추가하였습니다!

👍
<br>

> 이부분은 정확히 어떤게 문제인지 잘 모르겠습니다...! 숫자를 먼저 입력하고 음수로 변경하고 숫자를 입력해보았는데 음수표현이 사라지지 않는 것 같습니다. 주디가 발견한 오류가 어떤 오류 일까요?

![](https://i.imgur.com/eSjxOBQ.gif)

제가 확인할 당시에는 이렇게 동작했는데 이미 해결되신 것 같네요 👍

## ScrollView 오류
> 🔥 오류해결
위와 같은 문제를 calculatorItemsScrollView.layoutSubviews() 로 해결하였습니다!
자세하게 이해하기는 어려웠지만 Main Run Loop와 Update Cycle이란 개념을 공부하면서 변화된 이벤트가 적용되는데 이 주기를 통해 검사하고 변경되므로 약간의 텀이 있다는 사실을 알게되었습니다. 이런 주기와 관련된 메서드가 대표적으로 3가지가 있었는데, 저는 그중에서 View의 값을 호출한 즉시 이벤트 변경이 일어나는 layoutSubviews()메서드를 사용하였습니다.
이는 View가 호출되면서 즉시 모든 subView가 호출되므로 비용이 많이 드는 단점이 있지만 제가 겪고 있는 문제는 즉시 변화가 보여야 하기때문에 이를 사용할 수 밖에 없었습니다. (나머지 2가지 방법은 예약을하고 update cycle을 지나면서 값은 변경되지만 사용자 눈에는 보여지지 않는다는 특징이 있다고 이해를 하였습니다.)
혹시 다른 더 좋은 방법이 있다면 알려주세요 주디! main run loop와 View에 대한 공부를 더 해봐야할 것 같습니다 🔥


잘 알아보셨는데 [layoutSubviews 문서](https://developer.apple.com/documentation/uikit/uiview/1622482-layoutsubviews)를 보시면 `You should not call this method directly.` 해당 메서드는 직접 호출하지 말라고 되어 있습니다 😅

사용하시려면 `layoutIfNeeded`를 사용하셔야 할 텐데 이유에 대해서는 아직은 어려운 개념일 수 있으니 나중에 여유있으실 때 [관련 블로글](https://tech.gc.com/demystifying-ios-layout/)나 [WWDC](https://developer.apple.com/videos/play/wwdc2015/219/)를 참고해보세요~ 

---

## 추가 확인 사항
1. 연산자 없이 `숫자 입력 -> =`을 하면 숫자가 스크롤뷰에 올라가네요 🤔
2. 소수점 계산 시 적절하지 않은 숫자가 나오기도 합니다.

<img src = "https://i.imgur.com/inK98lQ.png" width="300">

이 부분은 이런 상황도 있다고 알려드리는 것 뿐입니다 🙌

---

STEP 3까지 고생하셨습니다 👏👏
바로 머지 가능하나 추가로 수정을 반영하고 싶다면 알려주세요~

2023-02-04 06:13 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> -
네네 정확히는 **NSNumber**로 변환되면서 소수점 이후 불필요한 0은 제거가 되는 걸 확인해보실 수 있을거예요!

2023-02-04 07:19 UTC, yijiye commented
https://github.com/yagom-academy/ios-calculator-app/pull/449/commits/23ccb5645ca4e2edc4f38886d16cf4193d2513b0

소수점 관련하여 오류가 계속해서 발생하여 이부분을 잡는데 시간이 좀 오래걸렸습니다 
1️⃣  0. 00. 을 입력하고 연산자를 눌렀을때 화면이 업데이트 되지 않도록 구현
- `hasSuffix` 를 이용하여 `.`으로 끝나는 조건을 걸어 해결하였습니다.
2️⃣ 000.2 와 같이 불필요한 0 제거되도록 구현
- `addStackView`에서 Double 타입으로 한번 변환해서 000.2 -> 0.2가 되도록 잡아주는 조건을 걸어 해결하였습니다. 이렇게 하다보니 문제는 5를 입력하면 스크롤뷰에 5.0 으로 입력이 되네요...ㅎㅎㅎㅎ 최종적으로 결과값에서 잡아주는 것으로 만족하겠습니다 주디 🥲
- 여러 조건을 잡아줄 때 주디가 연산프로퍼티를 사용해보는 것을 추천해주셨는데, 이런식으로 조건을 상수로 표현하여 아래 조건문에 넣어주는 형식도 연산프로퍼티라고 볼 수 있나요..? 주로 enum에서만 사용해봐서 여기서는 어떻게 적용하면 좋을지 잘 모르겠습니다  😭

- 또한 다른 문제로 filter를 사용해서 하려고 하니 띄어쓰기도 있고 2️⃣에서 Double로 한번 변환을 해서 그런지 계산이 잘 안되서 우선 원래 map으로 두었습니다 다음에 고차함수에 더 익숙해지면 바꿔보도록 하겠습니다..!

2023-02-04 07:47 UTC, Judy-999 commented
리지 수고하셨어요 👏👏

연산 프로퍼티 활용을 추천드렸던 부분은 이전 코드에서 아래와 같이 특정 상황에서 Bool 값을 갖는다면,
```swift
if numberInput.text == Expression.zero {
    isEnteredOperand = false
} else {
    isEnteredOperand = true
}
```

따로 `false`, `true` 값을 넣어주는 대신 연산 프로퍼티로 지정할 수 있다는 내용이었습니다!
```swift
var isEnteredOperand: Bool {
    return numberInput.text != Expression.zero 
}
```

2023-02-04 07:47 UTC, merged