계산기 [STEP3] Brody
yagom-academy/ios-calculator-app pull request #450
Opened 2023-02-02 12:41 UTC by seunghyunCheon

@Judy-999 
주디 안녕하세요! 많이 어려웠지만 최선을 다해 작성해봤습니다!
제일 어려웠던 점은 기능이 추가될때마다 최대한 추가적인 변수를 생성하지 않고 해결하려고했으나 잘 하지 못한 점입니다. 
잘 부탁드립니다!😄

## 고민한 점, 해결한 점, 조언을 얻고 싶은 점

## 기능분리

### 🤔 고민한 점 
숫자나 연산자 입력에 대해 유효성을 판별하는 부분이 많았습니다. 처음에는 논리연산자와 guard문을 많이 사용하면서 처리를 했는데 기능이 추가될수록 복잡해지는 게 눈에 보였습니다.

### ⚒️ 해결한 점
validateFunction이라는 파일을 만들어 viewController의 크기를 줄였습니다.
```swift
func isValidDotInput(enteringNumber: String, numberPad: String) -> Bool {
    return enteringNumber.contains(NumberType.dot) && numberPad == NumberType.dot ? false : true
}

func equalsZero(with value: String) -> Bool {
    return value == NumberType.zero
}

func includesDot(with value: String) -> Bool {
    return value.contains(NumberType.dot)
}
```

### 😅 조언을 얻고 싶은 점
분리를 했지만 3개의 함수만 분리를 했기 때문에 여전히 뷰컨트롤러의 크기는 컸습니다. 추가적인 객체가 있으면 좋을 것 같지만 어떻게 분리를 시켜야할지 방향을 못잡겠습니다. 뷰컨트롤러가 커지는 부분을 어떻게 개선할 수 있을까요?

## Bool값의 변수사용을 통한 제어
### 🤔 고민한 점과 조언을 얻고 싶은 점
계산기에서 `=`을 한 뒤에 숫자를 입력하면 계산된 내용이 지워지고 숫자가 입력되는 상황에는 `hasEndedCalculation`변수를 통해 제어를, 0이 눌리지 않은 상태에서 연산자가 눌렀을 때 0이 연산에 들어가지 않고 연산자만 바뀌는 것을 위해 `isTappedNumber`변수를 통해 제어했습니다. 
이러한 변수값들이 2개 이상의 함수에 배치되어있어 다른 사람이 제 코드를 봤을 때 이해하기가 힘들 것이라고 생각합니다. 하지만 이를 사용하지않고 문제를 해결하려면 Bool타입이 아닌 다른타입의 또다른 변수를 생성하는 것 말고는 해결방법이 떠오르지 않았습니다. 
어떤방법으로 이 문제를 해결하면 좋을지 judy의 의견이 궁금합니다.

## NumberFormatter
### 🤔 고민한 점과 조언을 얻고 싶은 점
`formatter.maximumFractionDigits = 20`을 통해 20자리까지 표현을 하려했으나 16자리에서 끊기게 되었습니다. 어떤 부분이 문제인지 계속 찾아봤지만 결국 해결하지 못했습니다. 어떤 키워드로 문제를 접근하면 좋을까요?

2023-02-03 14:49 UTC, Judy-999 requested changes
Brody 수고하셨어요 🙌
마지막 STEP까지 잘 구현해주셨네요 👏👏
계산기가 간단해보여도 여러 복잡한 로직을 가지고 있어서 힘드셨을거예요 😅
그럼에도 마지막 STEP까지 잘 해주셨습니다 👍

---

## 고민한 점, 해결한 점, 조언을 얻고 싶은 점
### 기능분리
> - 숫자나 연산자 입력에 대해 유효성을 판별하는 부분이 많았습니다. 처음에는 논리연산자와 guard문을 많이 사용하면서 처리를 했는데 기능이 추가될수록 복잡해지는 게 눈에 보였습니다.
> - validateFunction이라는 파일을 만들어 viewController의 크기를 줄였습니다.
> - 분리를 했지만 3개의 함수만 분리를 했기 때문에 여전히 뷰컨트롤러의 크기는 컸습니다. 추가적인 객체가 있으면 좋을 것 같지만 어떻게 분리를 시켜야할지 방향을 못잡겠습니다. 뷰컨트롤러가 커지는 부분을 어떻게 개선할 수 있을까요?

MVC의 단점 중 하나가 Controller가 비대해진다는 점이 있습니다 🥲
그래서 가능한 공통된  역할을 하는 코드를 객체로 분리할 수 있습니다.

현재는 함수 몇 개로 분리하셨지만 해당 함수들을 연관성에 따라 `ExpressionParser`와 같은 객체로 분리하는 방법이 될 수 있겠죠!

이외에도 **UIScrollView**를 extension해서 구현하신 것 처럼 해당 객체에 새로운 메서드를 추가하는 방법 역시 기능을 분리하는 방법이 될 수 있습니다.

기본적으로 현재는 View에 해당하는 코드가 Controller에 혼합되어 있는 상태라 이후에 코드로 View를 구성하시는 작업을 해보시면 어느 정도 Controller가 분리되는 경험을 해보실 수 있을 것 같네요!
<br>

## Bool값의 변수사용을 통한 제어
> 계산기에서 =을 한 뒤에 숫자를 입력하면 계산된 내용이 지워지고 숫자가 입력되게 하기위해 hasEndedCalculation변수를 통해 제어를, 0이 눌리지 않은 상태에서 연산자가 눌렀을 때 0이 연산에 들어가지 않고 연산자만 바뀌는 것을 위해 isTappedNumber변수를 통해 제어했습니다.
이러한 변수값들이 2개 이상의 함수에 배치되어있어 다른 사람이 제 코드를 봤을 때 이해하기가 힘들 것이라고 생각합니다. 하지만 이를 사용하지않고 문제를 해결하려면 Bool타입이 아닌 다른타입의 또다른 변수를 생성하는 것 말고는 해결방법이 떠오르지 않았습니다.
어떤방법으로 이 문제를 해결하면 좋을지 judy의 의견이 궁금합니다.

특정 상황에 따른 값이 필요하다면 Bool 값을 활용하는 것 자체는 적절한 방법이라고 생각합니다. 다만 가능하면 따로 값을 변경하지 않아도 값을 얻을 수 있는 연산 프로퍼티로 구현할 수 있는지 고민해보시면 좋겠네요. 불가능 네이밍을 통해 어떤 역할을 하는 변수인지 직관적으로 이해할 수 있도록 구현하는 것이 최선이라고 생각합니다!
<br>

---

## 오류 상항
실행하면서 발견한 오류 상황들 입니다. 수정 또는 의견을 알려주세요 ❗️


1. 결과로 NAN이 나온 후 새로운 연산자를 입력하면 NaN과 연산이 됩니다. 가능하면 NaN이 나온 후에는 모든 연산을 clear하면 좋겠네요.

2. `+/-`으로 음수 변환 후 계산을 실행하면 계산된 값이 아닌 이후에 입력한 숫자가 나옵니다. ex) -3 + 2 = 2

3. AC를 누르면 선택된 연산자는 초기화되지 않습니다.

4. 숫자를 입력하지 않은 상태에서 연산자와 `=`을 누르면 해당 연산이 ScrollView에 올라갑니다. ex) 6 + => + 6

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +import Foundation
두 프레임워크가 모두 필요한지 알아보세요!

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +final class CalculatorViewController: UIViewController {
네이밍과 `final` 키워드 좋습니다 👍

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var enteringNumber: UILabel!
개행을 넣어주신 의도가 있을까요?

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
어떤 `scrollView`인지 네이밍해주시면 좋겠습니다!

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    }()
`lazy`는 어떤 키워드이고, 어떤 이유로 사용하셨나요?

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction func ACButtonTapped(_ sender: UIButton) {
Button과 Pad과 혼용되고 있는데 다른 의미를 두신걸까요? 🤔
큰 차이가 없다면 하나로 통일해주세요!

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        initiatalState()
메서드(`ACButtonTapped`)에서 다른 메서드(`initiatalState`)를 호출만 하고 있고, `initiatalState` 메서드가 다른 곳에선 사용되지 않는 걸로 보이는데 따로 메서드로 분리하신 이유가 있나요?

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Model/NumberType.swift
> +enum Sign {
일반적으로 파일 이름은 타입과 동일하게 사용합니다!

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Model/NumberType.swift
> +}
사용되는 문자열을 상수로 분리하셨네요 👍👍

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +
불필요한 개행으로 보이네요 👀

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction func changeCurrentSign(_ sender: UIButton) {
`~~Tapped`로 통일하는게 좋겠네요!

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +                "-" + enteringNumberLabel
삼항연산자가 간단하긴 하지만 코드가 길다면 조건문으로 구분하는게 어떤 로직인지 파악하기 쉬울 때도 있습니다~

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        return
`guard` 문이 많이 사용되었는데 여러 흐름을 가진 로직일까요? 👀
흐름을 단순하게 추려보거나 가능한 부분은 다른 메서드로 분리해도 좋을 것 같네요!

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        guard let `operator` = sender.titleLabel?.text else { return }
``operator``라고 하면 **Operator** 타입으로 혼동될 수 있으니 `operatorText`와 같이 특성을 드러내면 좋겠네요 🙂

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +
```swift
calculationExpression += (enteringOperaterLabel + enteringNumberLabel)
addStackView(elements: [enteringOperaterLabel, numberFormatter.convertToDecimal(from: enteringNumberDouble)], direction: .horizontal)
scrollView.scrollToBottom()
```

위 코드처럼 반복되는 구문은 메서드로 분리해도 좋을 것 같아요 🙂

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        calculationExpression = ""
`""`역시 상수로 분리하거나 `calculationExpression.removeAll()`로 표현할 수 있습니다~

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        enteringNumber.text = result.isNaN ? Sign.nan : numberFormatter.string(for: result)
어떤 로직인가요? 
결과가 nan일 때 `Sign.nan`과 `numberFormatter.string(for: result)`이 다른가요? 🤔

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        contentStackView.addArrangedSubview(stackView)
StackView에 Label이 아닌 StackView를 넣어주는 이유는 무엇인가요?

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        scrollView.layoutIfNeeded()
해당 코드는 어떤 역할을 하는걸까요?

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        contentStackView.subviews.forEach { $0.removeFromSuperview() }
`forEach`의 사용 좋습니다 👍

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    }
어떤 역할을 하는 메서드인가요?

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
> +            return `initialOperator`.calculate(lhs: 0, rhs: sum)
`initialOperator`는 ` `` `를 사용하지 않아도 되지 않을까요?

2023-02-03 14:49 UTC, Judy-999 commented on Calculator/Calculator/ValidateFunction.swift
> +import Foundation
해당 프레임워크가 필요한지 확인해보세요 🙂

2023-02-05 03:08 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +import Foundation
Foundation 프레임워크는 운영체제에 필요한 서비스나 기본기능을 포함하고 있는 프레임워크입니다.
UIKit내부에서 기본적으로 Foundation을 import하고 있기 때문에 UIKit을 사용하는 경우에는 Foundation을 지워도 되는 것을 확인했습니다

2023-02-05 03:09 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var enteringNumber: UILabel!
가독성을 위해 넣었지만 전체적으로 코드를 보니 어떤 곳은 개행이 있고 어떤 곳은 없는 것을 확인했습니다.
컨벤션을 정해서 사용하겠습니다!

2023-02-05 03:10 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
`calculatorScrollView`로 수정했습니다

2023-02-05 03:21 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    }()
`lazy`로 선언된 저장 변수는 처음 사용되기 전까지 초기값이 계산되지 않는 프로퍼티 입니다. 
numberFormatter를 아래 코드처럼 view가 load된 이후 실행시킬 수도 있지만 viewController내의 메서드를 생성시키는 것보다 프로퍼티 선언부분에서 설정해주는 것이 역할분리가 잘 된다고 생각이 들어서 `lazy`키워드를 사용했습니다.
```swift
let numberFormatter = NumberFormatter()

viewDidLoad() {
    setUpNumberFormatter()
}
```swift

2023-02-05 03:21 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction func ACButtonTapped(_ sender: UIButton) {
알겠습니다 😄

2023-02-05 03:22 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        initiatalState()
다른 곳에서도 재사용하기 위해서 정의를 했었는데 주먹구구식으로 작성했다보니 사용하지 못했던 것 같습니다!
수정하겠습니다!

2023-02-05 03:23 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +                "-" + enteringNumberLabel
if문을 사용해 가독성을 높였습니다!
```swift
func changedSign(_ input: String) -> String {
      if input.contains(Sign.minus) {
          return input.replacingOccurrences(of: Sign.minus, with: Sign.empty)
      }
      return (Sign.minus + input)
  }
```

2023-02-05 03:25 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        return
많이 고민되었던 부분이여서 이 부분을 개선하기 위해 계산기의 핵심로직과 담당하는 객체를 만들고 Pad별로 IBAction을 분리시켜 각 메서드의 책임을 줄였습니다

2023-02-05 03:37 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        enteringNumber.text = result.isNaN ? Sign.nan : numberFormatter.string(for: result)
다르다고 생각했었는데 `Double.nan`을 `numberFormatter.string(for:)`넣으니 `NaN`의 결과값이 나왔네요!
감사합니다

2023-02-05 03:39 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        contentStackView.addArrangedSubview(stackView)
`opeartor`와 `operand`를 가로로 묶은 `FormulaStackView`를  `ScrollView`의 `ContentStackView`에 넣어주기 위해 작성했습니다

2023-02-05 03:42 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        scrollView.layoutIfNeeded()
`layoutIfNeed`함수는 큐의 맨 뒤에 넣어서 update cycle을 기다리는 것이 아닌 곧바로 update cycle을 실행하여 레이아웃이 업데이트할 수 있는 메서드입니다.
레이아웃이 변경되고 바로 업데이트가 적용될 수 있게 `layoutIfNeed`함수를 호출했습니다.

2023-02-05 03:45 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    }
`13000.0003`이라는 숫자를 `format`하기 위해서는 정수부분과 소수부분을 나눠서해야 한다고 생각했었는데 아래 코드를 실행해보니 `numberFormatter`가 알아서 처리해준다는 것을 알게되었습니다. 
그래서 해당 메서드는 삭제했습니다! 
```swift
numberFormatter.string(for: 13000.0003)
```

2023-02-05 05:00 UTC, seunghyunCheon commented
> 결과로 NAN이 나온 후 새로운 연산자를 입력하면 NaN과 연산이 됩니다. 가능하면 NaN이 나온 후에는 모든 연산을 clear하면 좋겠네요.
- NaN도 결과값이라고 생각이 들어서 결과값에 추가 연산을 해도 NaN이 나온다는 사실을 알려주기 위해 이렇게 처리했습니다!

나머지 예외사항들은 수정했습니다!

2023-02-05 05:03 UTC, seunghyunCheon commented
추가적인 PR을 봐주신다고 하셔서 감사합니다! 주디😄
해당 스탭의 기능을 빠르게 구현하는 것에만 초점을 뒀기 때문에 버그 발생 시 여러 부분의 코드를 수정해야 하는 일이 발생했습니다. 현재는 체계적으로 코드를 작성하는 연습이 중요하다고 생각해서  UML설계부터 다시 시작해, 최대한 객체들이 각자의 책임을가지고 이들이 협력할 수 있게 만드려고 노력했습니다. 

- 코드 설명과 UML에는 많은 양을 보여주는 것보다 핵심이 보여지는 게 좋다고 생각해서 IBOutlet과 IBAction은 제거했습니다.
- STEP2가 머지된 이후 시점부터 새롭게 작성해서 STEP3에 해당하는 코드를 적었습니다.

## UML
<img src="https://i.imgur.com/DCtnJa1.jpg"/>


## 코드 설명
`CalculatorViewController`
 - `enteringNumber`: 실제 보여지는 레이블이 아닌 데이터가 입력되는 연산 프로퍼티
 - `calculationExpression`: 피연산자와 연산자가 들어있는 표현식
 -  `calculatorChecker`: 계산기의 핵심로직들을 담당하는 객체
 -  `numberFormatter`: 숫자값과 문자적 표현 사이를 변환해주는 객체
 - `addFormulaStackView(to:with:)`: `to`에 `with`전달인자를 넣어 `formulaStackView`를 추가해주는 메서드
 -  `initialState()`: 초기상태를 갖게 해주는 메서드
 -  `removeAllFormulaStackView()`: 전체 스택뷰에 들어간 `FormulaStackView`들을 제거해주는 메서드

`CalculatorChecker`
> 계산기의 핵심 로직들(유효성 판별, 값 반환)을 담당하는 객체
- `hasCurrentInput(_ currentText: String) -> Bool`: 들어온 입력값이 유효한지 판단하는 메서드
- `hasDot(_ currentText: String) -> Bool`: 들어온 입력값에 dot이 포함되어있는지 판단하는 메서드
-  `appendingDot(_ currentText: String) -> String`:  현재 입력값의 dot에 대한 유효성을 판단해 상태에 맞는 값을 반환하는 메서드
-  `isZero(_ input: String) -> Bool`: 입력값이 0인지 판단하는 메서드
-  `changedSign(_ currentText: String) -> String`: 현재 입력값의 상태에 맞게 부호를 변환한 값을 반환하는 메서드
-  `calculate(with expression: String) -> Double`: 입력값으로 들어온 표현식을 계산된 값을 반환하는 메서드

`FormulaStackView`
> UIStackView를 상속받은 커스텀 클래스
- `addLabels(_ elements: [String])`: 입력값으로 들어온 텍스트들을 Label로 만들어 스택뷰에 추가하는 메서드

## 조언을 받고 싶은점

### SOLID 원칙
객체를 분리해서 책임을 나눴지만 프로토콜을 사용해서 SOLID원칙을 지키진 못했습니다. 정확하게는 어떤 부분에서 지켜야할 지 감이 안왔던 것같네요..😅 혹시 계산기 프로젝트에서 프로토콜을 사용해 더 개선할 곳이 있는지 궁금합니다!

### UML 아규먼트 레이블
스위프트에는 함수를 호출할 때 가독성을 높여주기 위해 아규먼트 레이블을 사용합니다. 
처음 UML을 그릴 때는 파라미터의 명확성이 더 중요하다고 생각해서 지웠지만 어떤 문맥에서는 아규먼트 레이블을 사용하지않는 것이 조금 어색하다고 느꼈습니다.
UML에는 아규먼트레이블 또한 같이 명시해주는 건지 궁금합니다!

### UML 문서화
View, ViewController, Model 레이어를 명확하게 나누고 싶어서 가로로 길게 된 UML을 작성했습니다. UML을 그릴때는 확대한 상태로 작업하기 때문에 무리는 없지만 ReadMe와 같은 공간에 넣게되면 글씨가 잘 안 보이는 경우가 생겼습니다. 이러한 이유로 글씨를 키워보기도 했지만 여전히 잘 보이지 않았고 프로젝트가 커진다면 이런 현상이 더욱 심해질 것이라고 생각이 들었습니다. 이 부분은 어떻게 해결하면 좋을까요?

### UML의 시점
UML을 그리게 되면 다른 개발자 혹은 미래의 내가 구조를 알아보기 편하다는 장점과 더불어 UML을 그릴 때 객체의 책임에 대한 고민을 많이하기 때문에 도움이 된다는 사실을 그리면서 느끼게 되었습니다!

하지만 이번 프로젝트에서는 시행착오를 겪은 후 다시 UML을 작성했기 때문에 보다 구조적으로 만들 수 있었다고 생각이 드는데요! 만약 프로젝트의 구조가 이해되지 않은상태에서 UML을 그린다면 프로젝트 진행 중에 코드 뿐만 아니라 UML도 많은 부분을 수정해야 할 것 같다는 생각이 들었습니다. 이 또한 많은 시간이 소요되기 때문에 무시할 수 없을 것 같습니다. 

그래서 UML은 개발이 완료가 된 후에 다른 개발자 혹은 필요한 다른 사람들을 위해 그리는 것만이 좋은 것일까? 아니면 객체 간의 역할을 정하는 것이 중요하니까 시간이 걸리더라도 UML작성에 힘을 많이 쓰는 게 좋은 것일까?에 대한 고민을 했습니다.

주디는 처음 프로젝트를 시작할 때 UML을 확실하게(100%는 아니더라도 90%에 가까운) 그린 후에 프로젝트를 진행하는지 궁금합니다!

2023-02-05 13:27 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    }()
메서드에서 생성시키지 않고자 하는 의도였다면 `lazy`를 적용하지 않아도 가능합니다 🙂
그리고 역시 `private` 잊지말아주세요~
```swift
    private let numberFormatter = {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.roundingMode = .halfUp
        formatter.maximumFractionDigits = 20
        return formatter
    }()
```

2023-02-05 15:02 UTC, Judy-999 approved these changes
확실히 이전보다 코드가 간결해졌네요 👏👏
객체의 분리도 좋고 짧은 시간에 효과적으로 리팩토링 하신 것 같습니다 👍

---

## 조언을 받고 싶은점
### SOLID 원칙
>객체를 분리해서 책임을 나눴지만 프로토콜을 사용해서 SOLID원칙을 지키진 못했습니다. 정확하게는 어떤 부분에서 지켜야할 지 감이 안왔던 것같네요..😅 혹시 계산기 프로젝트에서 프로토콜을 사용해 더 개선할 곳이 있는지 궁금합니다!

모든 SOLID를 다 적용하는건 이상적인 코드라 사실 무리가 있습니다. 게다가 로직이 복잡하긴 하지만 단순하게 보면 하나의 뷰와 `계산하다`라는 하나의 기능을 가진 프로젝트여서 적용할 부분을 찾기 더 어려웠을 것 같네요 😅

우선 가장 기본적인 SRP를 우선으로 적용하려고 노력하시면 좋겠습니다!

나중에 기회가 되시면 디자인패턴들 공부하다 보면 SRP, OCP 등에 어떤 식으로 적용이 가능한지 이해하실 수 있을거예요. 지금은 이 정도로 생각하신 것만으로도 대단합니다 👍👍
<br>

### UML 아규먼트 레이블
> 스위프트에는 함수를 호출할 때 가독성을 높여주기 위해 아규먼트 레이블을 사용합니다.
처음 UML을 그릴 때는 파라미터의 명확성이 더 중요하다고 생각해서 지웠지만 어떤 문맥에서는 아규먼트 레이블을 사용하지않는 것이 조금 어색하다고 느꼈습니다.
UML에는 아규먼트레이블 또한 같이 명시해주는 건지 궁금합니다!

아규먼트 레이블을 사용했다면 사용했을 때의 의미전달이 더 명확하다는 뜻일 테니 명시해주는게 좋을 것 같아요. 

요구사항에 있던 UML을 보면 함께 적어주었네요 🙂
![](https://i.imgur.com/rRAHSbC.png)
<br>

### UML 문서화
> View, ViewController, Model 레이어를 명확하게 나누고 싶어서 가로로 길게 된 UML을 작성했습니다. UML을 그릴때는 확대한 상태로 작업하기 때문에 무리는 없지만 ReadMe와 같은 공간에 넣게되면 글씨가 잘 안 보이는 경우가 생겼습니다. 이러한 이유로 글씨를 키워보기도 했지만 여전히 잘 보이지 않았고 프로젝트가 커진다면 이런 현상이 더욱 심해질 것이라고 생각이 들었습니다. 이 부분은 어떻게 해결하면 좋을까요?

지금도 그렇고 더 방대한 프로젝트에서는 모든 타입을 표현하기는 사실상 불가능합니다. 결국 객체간의 관계를 보여주고 싶은 것이니 어느 정도 생략은 괜찮다고 생각합니다.

지금처럼 큰 의미를 갖지 않는 프로퍼티나 메서드는 명시하지 않거나, 아예 타입 자체가 중요하지 않다면 없어도 무방하다고 생각해요. 전달하고자 하는 핵심이 잘 드러나도록만 표현할 것 같습니다. 저는 Model이 복잡했던 경우에는 모두 생랼하고 Model 타입의 관계만 표현한 적도 있습니다~ 
<br>

### UML의 시점
> UML을 그리게 되면 다른 개발자 혹은 미래의 내가 구조를 알아보기 편하다는 장점과 더불어 UML을 그릴 때 객체의 책임에 대한 고민을 많이하기 때문에 도움이 된다는 사실을 그리면서 느끼게 되었습니다!
> 
>  하지만 이번 프로젝트에서는 시행착오를 겪은 후 다시 UML을 작성했기 때문에 보다 구조적으로 만들 수 있었다고 생각이 드는데요! 만약 프로젝트의 구조가 이해되지 않은상태에서 UML을 그린다면 프로젝트 진행 중에 코드 뿐만 아니라 UML도 많은 부분을 수정해야 할 것 같다는 생각이 들었습니다. 이 또한 많은 시간이 소요되기 때문에 무시할 수 없을 것 같습니다.
> 
>  그래서 UML은 개발이 완료가 된 후에 다른 개발자 혹은 필요한 다른 사람들을 위해 그리는 것만이 좋은 것일까? 아니면 객체 간의 역할을 정하는 것이 중요하니까 시간이 걸리더라도 UML작성에 힘을 많이 쓰는 게 좋은 것일까?에 대한 고민을 했습니다.
> 
> 주디는 처음 프로젝트를 시작할 때 UML을 확실하게(100%는 아니더라도 90%에 가까운) 그린 후에 프로젝트를 진행하는지 궁금합니다!

프로젝트를 진행하기 전에 먼저 `프로젝트 기획`이 있을 테니 기획된 구조를 보고 UML을 작성하게 된다고 생각합니다. 즉 `기획 -> UML 작성 -> 구현` 이런 순서가 되겠죠!

`다른 개발자 혹은 필요한 다른 사람들을 위해`라는 것은 동의하지만 그 대상이 협업하는 팀원이 우선이 되어야 한다고 생각해요. 기획을 보고 어떤 코드와 구조로 구현할지 협업하는 팀원들과 이야기하며 같이 UML을 작성하는 것이죠. UML을 작성하면서 어떤 타입들끼리 관계를 갖는지 의논하고, UML을 잘 작성해두면 UML만 보고 각자 맡은 부분의 코드를 작성할 수 있는 것이죠. 물론 프로젝트를 진행하면서 구조가 변경될 수는 있지만 이미 작성한 UML에 먼저 반영해보면 변경할 방향도 쉽게 잡을 수 있다고 생각합니다. 

다만 처음부터 확실한 구조를 잡는건 힘들 테니 `시간이 걸리더라도 UML작성에 힘을 많이 쓰는`것 까지는 추천하지 않습니다. 변경의 여유를 두고 초기안으로 생각하고 작성하는 정도면 좋을 것 같아요! 저 역시 부끄럽지만 UML을 작성하지 않거나 README와 함께 작성한 경우가 많았습니다 😅 야곰에서는 짝 프로그래밍으로 거의 진행하니 협업에서의 UML의 필요성이 아마 크게 느껴지지 않을 것 같네요. 작성 시점이나 정도에 대해서는 팀원과 이야기해보고 결정하는게 가장 좋을 것 같습니다 🙂

2023-02-05 15:02 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculateViewController.swift
> +class CalculateViewController: UIViewController {
`final`이 사라졌네요 😮

2023-02-05 15:02 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculateViewController.swift
> +            if enteringNumber == Sign.empty || enteringNumber == Sign.space {
**CalculatorChecker**의 `hasCurrentInput` 메서드와 동일한 작업 같은데 활용할 수 있지 않을까요?

2023-02-05 15:02 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculateViewController.swift
> +        enteringNumber = numberFormatter.string(for: addedEnteringNumber) ?? Sign.zero
여러 부문에서 `numberFormatter.string(for: Double)` 형태로 사용되고 있는 것 같은데 `numberFormatter`을 전역변수로 두는 대신 메서드를 만들어 재사용하는 방법도 좋을 것 같네요!

2023-02-05 15:02 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorChecker.swift
> +        if currentText == Sign.empty || currentText == Sign.space {
만약 **CalculatorChecker**가 계산을 처리하도록 객체로 하고 싶다면 `enteringNumber`와 `calculationExpression`는 계산에 사용되는 프로퍼티이니 **CalculatorChecker**의 프로퍼티로 구현할 수도 있을 것 같아요.

그러면 `hasCurrentInput` 같은 메서드는 연산 프로퍼티로 구현할 수 있겠죠!

현재는 이렇게 변경하면 코드의 변경사항이 너무 많으니 어떨지 생각만 해보시면 됩니다 🙂

2023-02-05 15:02 UTC, Judy-999 commented on Calculator/Calculator/Utils/StringExtension.swift
> +        let addedNumber = (self + number).split(separator: ",").joined()
","를 제거하고자 하는 로직이라면 `filter`를 활용해볼 수 있겠네요!
```swift 
let addedNumber = (self + number).filter { $0 != "," }
```

2023-02-05 15:02 UTC, Judy-999 commented on Calculator/Calculator/View/FormulaStackView.swift
> +class FormulaStackView: UIStackView {
**UIStackView**를 상속받아 Custom StackView를 만드셨네요 👍

2023-02-05 15:02 UTC, Judy-999 commented on Calculator/Calculator/View/FormulaStackView.swift
> +class FormulaStackView: UIStackView {
역시 상속되지 않는다면 `final` 잊지말아주세요~

2023-02-06 00:07 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculateViewController.swift
> +            if enteringNumber == Sign.empty || enteringNumber == Sign.space {
그렇네요! `hasCurrentInput`으로 수정했습니다!

2023-02-06 00:09 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculateViewController.swift
> +            if enteringNumber == Sign.empty || enteringNumber == Sign.space {
그렇네요! `hasCurrentInput`을 사용해서 수정했습니다!

2023-02-06 00:16 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculateViewController.swift
> +        enteringNumber = numberFormatter.string(for: addedEnteringNumber) ?? Sign.zero
수정했습니다😀

2023-02-06 00:16 UTC, seunghyunCheon commented on Calculator/Calculator/Utils/StringExtension.swift
> +        let addedNumber = (self + number).split(separator: ",").joined()
수정했습니다!

2023-02-06 00:19 UTC, Judy-999 commented
수고하셨어요 👏👏 🥳

2023-02-06 00:19 UTC, merged