계산기 [STEP 3] 혜모리
yagom-academy/ios-calculator-app pull request #451
Opened 2023-02-02 12:42 UTC by hyemory

안녕하세요 웡빙! ( @wongbingg ) STEP3 PR 보냅니다
view 쪽은 저번 쥬스메이커 때 처음 경험해 보았던 부분이라 너무 자신이 없었습니다 😅
코드도 최대한 정리해보긴 했으나 예외처리할 내용이 너무 많았습니다. 
아직 정리 능력이 부족해서... 코드 보시는데 어려움드려 미리 죄송합니다.
도움주시면 잘 수정해 보겠습니다! 리뷰 잘 부탁드립니다~ 감사합니다 😊

---
## 구현한 내용

### 1️⃣ 네임 스페이스
특정 문자를 기준으로 예외처리를 많이 하다보니 네임 스페이스로 정의하였습니다!

```swift
enum Sign {
    static let dot: Character = "."
    static let blank = " "
    static let empty = ""
    static let zero = "0"
    static let zeroZero = "00"
    static let negative = "-"
    static let nan = "NaN"
}
```

### 2️⃣ 전역 변수 정의
- `expression` : parser로 보낼 연산식을 전역 변수로 선언하여 이벤트가 발생할 때마다 업데이트 하였습니다.
- `isCalculatedStatus` : 연산이 완료되었는지 알려주는 상태입니다. 연산 완료 시 결과 값을 없애고 피연산자를 새로 입력하도록 하기위해 만들었습니다.
    - 기본값 `false` : 연산 내용 입력중
    - `true` : 연산완료
- `currentOperator`, `currentOperand` 현재 입력중인 연산자와 피연산자 입니다. 옵셔널 바인딩 과정을 줄이기위해 만들었습니다.

### 3️⃣ 피연산자 입력
- 예외처리 사항
    1. 연산 완료(isCalculatedStatus - true) 상태인지 : 연산중인 false 상태로 변경하고 입력한 숫자를 바로 적용합니다.
    2. 현재 피연산자 값이 0인지 : 0이라면 0과 00을 입력할 수 없습니다.
    3. 값에 `.`이 포함되어있으면 이후로는 넘버포맷터를 적용하지 않습니다.
    (111.0과 같은 상황이면 넘버포맷터가 소수점 뒷 내용을 다 지워버리기 때문)
- `.`의 경우 한 번만 입력 가능하도록 구현하였습니다.

### 4️⃣ 연산자 입력
`expression`에는 쉼표가 들어가면 계산이 제대로되지 않는 관계로, `,`를 빼주는 작업을 추가했습니다.

- 예외처리 사항
    1. expression 빈값인지 : 새로운 연산이므로 expression에 숫자만 추가, 스택 뷰에는 피연산자만 추가합니다.
    2. 현재 피연산자 값이 0인지 : 0이라면 " + "으로 저장되는 연산자를 바꾸기 위해 연산자 등록(3글자) 후 뒤에서 3글자 삭제했습니다.

### 5️⃣ 부호 변경 및 연산 결과
- 예외처리 사항
    1. 현재 피연산자 값이 0인지 : 0이라면 실행되지 않습니다.
    2. 현재 피연산자 첫번째 글자가 `-`인지 : `-`라면 `-`를 삭제하고, 아니면 추가해줍니다. 
- Equal 버튼 클릭 시 연산자가 공백일 때 =을 누를 수 없습니다.

### 6️⃣ NumberFormatter
코드를 정리하기 위해 String의 `extension`으로 구현하였습니다.
이미 쉼표가(`,`) 적용되어있는 피연산자에 적용하려고하면 제대로 적용되지 않아
문자열에서 쉼표를 빼주는 작업을 진행했습니다.

넘버 포매터 관련 해결하지 못한 점이 있어 아래 `해결하지 못한 점`에 작성했습니다.

### 7️⃣ StackView, ScollView 
> iOS의 View는 업데이트할 컨텐츠가 생기면 즉각 그리지 않고 다음 drawing cycle에 그린다

- 스크롤이 최하단까지 내려가지 않는 현상이 있어 캠퍼분에게 질문하여 `layoutIfNeeded()`을 사용하게됐습니다. 정확하게 공부는 못했지만 `드로잉 사이클`로 인해 마지막 컨텐츠가 나타나지 않는 것이란 것을 알게 되었습니다. 추후에 시간이 남을 때 공부해 보겠습니다!

---
## 해결하지 못한 내용
> 숫자는 최대 20자리까지만 표현합니다.
> 잘리는 숫자는 반올림합니다.

이러한 요구 사항이 있었는데 결국 구현에 실패하였습니다.
NumberFofmatter의 Fraction, Significant 자리수를 제한하는 프로퍼티를 사용해 보았는데 요구사항과 비슷한 결과를 얻지 못했습니다.
(요구사항도 잘 이해하지 못했는데 정수 + 소수점 뒷자리 모든걸 포함해서 20자리인 것인가요?)

또한 숫자 17개를 입력 시부터 (ex. 66,666,666,666,666,667,000...) 마지막 자리 숫자가 반올림되고 있는데, 
`maximumFractionDigits`, `maximumSignificantDigits` 를 더 높은 숫자로 변경해 보았으나 달라지는게 없어 결국 NumberFormatter 자리수 관련한 문제의 답을 찾지 못했습니다. 😭
조언해 주시면 개선해 보겠습니다!

2023-02-03 00:01 UTC, wongbingg commented
안녕하세요 혜모리 ☺️ step3 고생 많으셨습니다. 

---
## ✅ 구현한 내용에 대하여

### 1️⃣ 네임 스페이스
>특정 문자를 기준으로 예외처리를 많이 하다보니 네임 스페이스로 정의하였습니다!

매직 리터럴을 enum으로 정리해주는 습관 👍 매우매우 좋습니다

### 2️⃣ 전역 변수 정의
>- `expression` : parser로 보낼 연산식을 전역 변수로 선언하여 이벤트가 발생할 때마다 업데이트 하였습니다.
>- `isCalculatedStatus` : 연산이 완료되었는지 알려주는 상태입니다. 연산 완료 시 결과 값을 없애고 피연산자를 새로 입력하도록 하기위해 만들었습니다.
    - 기본값 `false` : 연산 내용 입력중
    - `true` : 연산완료
>- `currentOperator`, `currentOperand` 현재 입력중인 연산자와 피연산자 입니다. 옵셔널 바인딩 과정을 줄이기위해 만들었습니다.

전역변수의 경우 객체 내 모든 메서드에서 접근이 가능하기 때문에 사용성이 편리한 측면이 있지만, 반면에 모든 메서드에서 수정이 가능하므로 어떤 오류가 났을 때, 어느 메서드에서 수정한 것인지 찾기가 어려운 점이 있을 것 같아요.

### 3️⃣ 피연산자 입력
>- 예외처리 사항
    1. 연산 완료(isCalculatedStatus - true) 상태인지 : 연산중인 false 상태로 변경하고 입력한 숫자를 바로 적용합니다.
    2. 현재 피연산자 값이 0인지 : 0이라면 0과 00을 입력할 수 없습니다.
    3. 값에 `.`이 포함되어있으면 이후로는 넘버포맷터를 적용하지 않습니다.
    (111.0과 같은 상황이면 넘버포맷터가 소수점 뒷 내용을 다 지워버리기 때문)
>- `.`의 경우 한 번만 입력 가능하도록 구현하였습니다.

예외케이스에 대한 처리도 잘 해주셨네요 👍

### 4️⃣ 연산자 입력
>`expression`에는 쉼표가 들어가면 계산이 제대로되지 않는 관계로, `,`를 빼주는 작업을 추가했습니다.

>- 예외처리 사항
    1. expression 빈값인지 : 새로운 연산이므로 expression에 숫자만 추가, 스택 뷰에는 피연산자만 추가합니다.
    2. 현재 피연산자 값이 0인지 : 0이라면 " + "으로 저장되는 연산자를 바꾸기 위해 연산자 등록(3글자) 후 뒤에서 3글자 삭제했습니다.

잘 처리 해주셨군요 👍

### 5️⃣ 부호 변경 및 연산 결과
>- 예외처리 사항
    1. 현재 피연산자 값이 0인지 : 0이라면 실행되지 않습니다.
    2. 현재 피연산자 첫번째 글자가 `-`인지 : `-`라면 `-`를 삭제하고, 아니면 추가해줍니다. 
>- Equal 버튼 클릭 시 연산자가 공백일 때 =을 누를 수 없습니다.

잘 처리 해주셨군요 👍

### 6️⃣ NumberFormatter
>코드를 정리하기 위해 String의 `extension`으로 구현하였습니다.
이미 쉼표가(`,`) 적용되어있는 피연산자에 적용하려고하면 제대로 적용되지 않아
문자열에서 쉼표를 빼주는 작업을 진행했습니다.

>넘버 포매터 관련 해결하지 못한 점이 있어 아래 `해결하지 못한 점`에 작성했습니다.

### 7️⃣ StackView, ScollView 
> iOS의 View는 업데이트할 컨텐츠가 생기면 즉각 그리지 않고 다음 drawing cycle에 그린다

>- 스크롤이 최하단까지 내려가지 않는 현상이 있어 캠퍼분에게 질문하여 `layoutIfNeeded()`을 사용하게됐습니다. 정확하게 공부는 못했지만 `드로잉 사이클`로 인해 마지막 컨텐츠가 나타나지 않는 것이란 것을 알게 되었습니다. 추후에 시간이 남을 때 공부해 보겠습니다!

`layoutIfNeeded()` 와 더불어 뷰 드로잉사이클에 대한 개념은 추후 활동학습에서 배우게 되실거에요! 여유가 된다면 미리 학습해두면 좋겠네요👍

---
## ✅ 해결하지 못한 내용에 대하여
> 숫자는 최대 20자리까지만 표현합니다.
> 잘리는 숫자는 반올림합니다.

>이러한 요구 사항이 있었는데 결국 구현에 실패하였습니다.
NumberFofmatter의 Fraction, Significant 자리수를 제한하는 프로퍼티를 사용해 보았는데 요구사항과 비슷한 결과를 얻지 못했습니다.
(요구사항도 잘 이해하지 못했는데 정수 + 소수점 뒷자리 모든걸 포함해서 20자리인 것인가요?)

>또한 숫자 17개를 입력 시부터 (ex. 66,666,666,666,666,667,000...) 마지막 자리 숫자가 반올림되고 있는데, 
`maximumFractionDigits`, `maximumSignificantDigits` 를 더 높은 숫자로 변경해 보았으나 달라지는게 없어 결국 NumberFormatter 자리수 관련한 문제의 답을 찾지 못했습니다. 😭
조언해 주시면 개선해 보겠습니다!

이 부분은 Swift 의 데이터타입 Double에 대해 알아보시면 좋을 것 같은데요. Double은 부동소수점을 사용하는 실수인데, 부동소수점 방식과 한계점에 대해 찾아보시면 이유를 알 수 있을 것 같아요! 

나머지는 코드를 보고 코멘트 남겨두겠습니다👍

2023-02-03 01:01 UTC, wongbingg requested changes

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    @IBOutlet weak var operationScrollView: UIScrollView!
스토리 보드의 UI 와 IBOutlet 으로 잘 연결 해주셨네요 👏

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +final class ViewController: UIViewController {
final 처리 좋습니다 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +//
주석까지 깔끔하게 통일시켜주셨네요 👏

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
ViewController 내에서만 사용되는 enum 이라면 private enum 으로 처리해주어도 좋을 것 같아요 🧐

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
AC 버튼이 탭 됐을 때 동작을 구현 해주셨네요 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Model/Operator.swift
> +
스토리보드상 적용되어있는 문자로 변경 해주셨군요 👏

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Model/extensions.swift
> +    }
NumberFormatter 를 잘 이용 해주셨네요 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Model/extensions.swift
> +    }
아래의 메서드도 한번 알아보시면 좋을 것 같아요 
-[Apple Docs - replacingoccurrences](https://developer.apple.com/documentation/foundation/nsstring/1412937-replacingoccurrences)

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
각 버튼을 잘 연결 해주셨네요 👏 네이밍도 한번에 알아볼 수 있게 잘 해주신 것 같습니다

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
레이블 생성 메서드를 깔끔하게 작성 해주셨네요 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
+/- 버튼에 대한 로직도 깔끔합니다 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
. 버튼에 대한 로직도 잘 처리 해주셨습니다 👍
다만, guard else 구문에 대한 개행 컨벤션이 각각의 메서드 마다 다른데 통일 시켜주면 더 좋을 것 같아요 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    var currentOperand: String { (operandLabel.text ?? Sign.empty) }
이 변수들은 ViewController 외부에서 접근할 가능성이 있을까요 ?

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
⚠️ 모든 함수에 해당됩니다 ⚠️

외부에서 접근이 가능한 메서드들 일까요 ?

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
스택뷰 생성 메서드를 깔끔하게 작성 해주셨군요 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
contentOffset 을 설정해줌으로 자동스크롤 되도록 만드셨네요 👏

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
operationStackView 를 만들어서 operationContentStackView 에 넣어주는 작업을 하는 메서드이니 
네이밍이 setOperationContentStackView가 되면 더 자연스러울 것 같아요 🧐

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> -
불필요한 개행 제거 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
Operator 버튼에 대한 로직이군요 👍 조건이 3개 이상 존재할 때는 switch 구문을 활용 해봐도 좋을 것 같아요 
또한 split.joined() 가 자주 사용되니 String 의 extension 으로 메서드를 분리 해주어도 좋을 것 같네요 🧐

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
숫자 입력에 대한 로직도 잘 처리 해주셨네요 👏

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
= 버튼을 탭했을 때 계산결과를 보여주는 로직이군요 👍

2023-02-03 01:01 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
`숫자는 최대 20자리까지 표현합니다` 라는 요구사항은 여기서 처리해줄 수 있을 것 같아요 🧐

2023-02-03 03:35 UTC, hyemory commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
UI를 구성하는 타입이 viewController 타입 하나밖에 없어 전부 은닉화 할 수 있었습니다!
5d7e268a7fb14428f4987015f32e3f676912fe89

2023-02-03 03:37 UTC, hyemory commented on Calculator/Calculator/Model/extensions.swift
> +    }
이렇게 좋은 메서드가 있었다니...! 정말 감사합니다 😊

2023-02-03 03:38 UTC, hyemory commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
감사합니다! 더 깔끔하게 보이네요! 892c2e94dfc848eb3a8980efcf61b3523517dd9c

2023-02-03 03:39 UTC, hyemory commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
네이밍 변경했습니다! 892c2e94dfc848eb3a8980efcf61b3523517dd9c

2023-02-03 09:55 UTC, hyemory commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
9efa35bdb30bf95a592500580f0f272cc285077f
우선 쉼표 포함 모든 숫자 20자 제한으로 설정하였습니다!

2023-02-03 09:56 UTC, hyemory commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
- 229a1f70baf677f243535724867a5dcda9dd8fc9 : guard + if else 문으로 변경하였습니다!
- abb6f2fc063ca275781c34dc2633e565790673ae : removeComma() 메서드를 추가해 주었습니다!

2023-02-04 07:41 UTC, wongbingg commented
step3 까지 모두 마무리 되었네요 고생하셨습니다 👍
20자리 숫자 처리에 대해서는 Double 타입의 특성상 소수점 15자리까지만 표현할 수 있으므로 쉼표 포함 20자리가 맞을 것이라고 생각돼요🧐 아니면 진짜 숫자만 20자리까지 라면 큰 수 처리 알고리즘을 적용해 주어야 하지 않을까 추측이 됩니다🧐(아닐수도 있어요) 이 부분은 나중에 여유가 될 때 알아 보셔도 좋을 것 같아요 지금도 잘 처리 해주셨습니다 👍

2023-02-04 07:41 UTC, merged