계산기 [Step3] 해리
yagom-academy/ios-calculator-app pull request #452
Opened 2023-02-02 15:50 UTC by HarryHyeon

@llingo
안녕하세요 링고
여러가지 예외사항에 대해 처리하다 보니 PR이 조금 늦어졌습니다.
이번 스텝도 잘 부탁드립니다 😆 

# 고민한 점
### 유효숫자 20자리 표시
- 맥북의 기본 계산기 앱을 참고하여 기능을 구현했습니다.
- 기본 계산기 앱에서 많은 수를 입력하게되면 앞쪽부터 짤려서 화면에 표시되는 것을 확인했고, 저는 20자리가 넘어가면 원본 데이터는 유지하지만 숫자의 자릿수가 늘어날때마다 앞쪽에서 하나씩 짤리도록 구현했습니다.

### 스택뷰
- 스택뷰 안의 두 레이블을 코드로 생성해주다보니 Compression Resistance가 기본값인 것을 인지하지 못했습니다.
- 그 결과로 아주 많은 자릿수의 숫자가 입력되면 계산내역에서 연산자를 표시해주는 레이블이 사라지는 현상이 나타났습니다.
- 연산자 레이블을 생성하는 부분에서 Compression Resistance를 높게 설정해주어 해결하였습니다.

# 조언을 얻고 싶은 점

### 사칙연산 버튼처리
- 이 부분에서 많은 조건을 처리하는 것이 힘들었습니다.. 

``` swift
// 한번 계산된적이 있는지 처리
        if isCalculated {
            guard let continuedText = displayNumbersLabel.text?
                .components(separatedBy: ",")
                .joined() else { return }
            
            expression.append(continuedText)
            addHistoryEntry(left: "", right: continuedText)
            currentOperatorLabelText = `operator`
            isCalculated = false
            return
        }
        
// 현재 계산기가 초기 상태인지 검사 후 사칙연산버튼이 눌리지 않게 처리
        if currentNumbersLabelText == "0" {
            if currentOperatorLabelText == "" {
                return
            } else if currentOperatorLabelText != "" {
                currentOperatorLabelText = `operator`
                return
            }
        }
```
- 이런 조건식을 코드를 보고 이해하기가 매우 힘들고 저도 뒤돌아서면 이게 무슨 기능을 담당하는지 헷갈리는 수준입니다.
- 조금 더 알아보기 쉬운 코드를 작성하는 방법이 있다면 조언해주시면 감사하겠습니다 !

2023-02-03 07:45 UTC, llingo requested changes
안녕하세요 Harry
계산기 프로젝트 STEP 3 수고하셨습니다 :)
연산자, 피연산자의 상태 때문에 사이드 이펙트를 잡는 것이 많이 어려웠을 것 같아요.
그래도 요구사항대로 잘 구현해주셨습니다 👏

---

앞으로의 원활한 리뷰 진행을 위해 몇 가지 안내사항을 드리겠습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

---

**Q1. 사칙연산 버튼처리**

```swift
// 한번 계산된적이 있는지 처리
if isCalculated {
    guard let continuedText = displayNumbersLabel.text?
        .components(separatedBy: ",")
        .joined() else { return }

    expression.append(continuedText)
    addHistoryEntry(left: "", right: continuedText)
    currentOperatorLabelText = `operator`
    isCalculated = false
    return
}

// 현재 계산기가 초기 상태인지 검사 후 사칙연산버튼이 눌리지 않게 처리
if currentNumbersLabelText == "0" {
    if currentOperatorLabelText == "" {
        return
    } else if currentOperatorLabelText != "" {
        currentOperatorLabelText = `operator`
        return
    }
}
```

> 이게 무슨 기능을 담당하는지 헷갈리는 수준입니다. 조금 더 알아보기 쉬운 코드를 작성하는 방법이 있다면 조언해주시면 감사하겠습니다 !

A1. Operator 버튼이 탭 되었을때 호출되는 메서드에서 여러가지 조건을 처리하고 있기 때문에 복잡하고 헷갈리게 되는 것 같아요. 기능을 쪼갠다면 알아보기 쉬운 코드가 될 것 같습니다.

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/Model/NumberConverter.swift
> +                return formattedNumber
[P1] 들여쓰기가 이상한 것 같아요. `ctrl + i` 를 통해 잘못된 들여쓰기를 한번에 수정할 수 있습니다 :)

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/Model/NumberConverter.swift
> +    static func convertFormattedString(text: String) -> String {
Number Formatting 을 담당하는 객체를 따로 생성해주셨네요 👍

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/Model/Operator.swift
> +    case multiply = "×"
Operator의 rawValue 값이 변경된 이유가 있나요?

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        horizontalStackView.translatesAutoresizingMaskIntoConstraints = false
`translatesAutoresizingMaskIntoConstraints`는 어떤 기능을 하는 프로퍼티인가요?
operandLabel에는 사용하지 않은 이유가 있을까요? 👀

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        operatorLabel.setContentCompressionResistancePriority(UILayoutPriority(1000), for: .horizontal)
setContentCompressionResistancePriority를 사용해주셨네요 👍 어떤 기능을 하는 메서드인가요?
`Compression Resistance`와 `Hugging` 개념을 제대로 익혀두면 좋을 것 같아요

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +    private static func generateLabel(text: String) -> UILabel {
히스토리 뷰를 생성하는 객체를 구현해주셨네요 👀
더 나아가서 히스토리에 필요한 Label과 StackView를 사용한 `커스텀 뷰`를 한번 만들어보면 좋을 것 같아요 👍

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        horizontalStackView.distribution = .fill
UIStackView의 `axis, alignment, distribution, spacing`은 어떤 역할을 하나요? 그리고 기본값은 어떤 값으로 되어있을까요? 👀

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        label.font = UIFont.preferredFont(forTextStyle: .title3)
타입 추론을 사용하여 아래와 같이 작성해볼 수 있어요
```swift
label.font = .preferredFont(forTextStyle: .title3)
```

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/Controller/CalculatorViewController.swift
> +        }
`didSet`을 사용해주셨네요 👍 `willSet`과 `didSet`은 어떤 기능을 하나요?

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/Controller/CalculatorViewController.swift
> +        }
애니메이션도 적용해주셨네요 👍

2023-02-03 07:45 UTC, seu0313 commented on Calculator/Calculator/Source/Controller/CalculatorViewController.swift
> +        historyScrollView.setContentOffset(bottomOffset, animated: true)
UIScrollView의 `contentSize, contentOffset, contentInset`은 각각 어떤 역할을 하는 프로퍼티인가요? 👀

2023-02-03 08:28 UTC, HarryHyeon commented on Calculator/Calculator/Source/Model/NumberConverter.swift
> +                return formattedNumber
코드를 다른 파일에서 긁어오면서 수정이 안되었던 것 같습니다 ! 수정완료 했습니다 👍

2023-02-03 08:29 UTC, HarryHyeon commented on Calculator/Calculator/Source/Model/Operator.swift
> +    case multiply = "×"
버튼의 currenTitle로 입력 문자를 처리하고 있어서 Operator의 rawValue와 버튼의 제목이 비슷하게 생겼지만 다른 문자여서 계산하는데 오류가 발생해 수정해주었습니다 !

2023-02-03 08:46 UTC, HarryHyeon commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        horizontalStackView.translatesAutoresizingMaskIntoConstraints = false
아직 명확하게 와닿지 않는 기능인 것 같습니다..
제가 이해하고 있는 바로는
`translatesAutoresizingMaskIntoConstraints` 속성은 기본적으로 true 입니다.
인터페이스 빌더에서 뷰를 추가하는 경우에는 자동으로 이 속성이 false가 되는데, 저는 현재 코드로 뷰를 생성하고 있기때문에 시스템이 슈퍼뷰의 크기가 변함에 따라 서브뷰의 크기를 자동으로 조정하는 것을 막기 위해 사용한다고 이해하고 있습니다.

또한, Autoresizing mask를 통한 뷰의 크기 조절이 아닌 AutoLayout을 통해 뷰간의 관계설정을 통해 크기와 위치를 정하려면 충돌을 방지하기 위해 해당 프로퍼티를 false로 설정해주어야 합니다.

2023-02-03 08:53 UTC, HarryHyeon commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        horizontalStackView.translatesAutoresizingMaskIntoConstraints = false
이 프로퍼티에대한 이해도가 부족한 채로 사용했던 것 같습니다. operandLabel도 Autoresizing이 필요하지 않아 false로 설정해주는것이 좋을 것 같아서 수정했습니다!

2023-02-03 08:56 UTC, HarryHyeon commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        operatorLabel.setContentCompressionResistancePriority(UILayoutPriority(1000), for: .horizontal)
`setContentCompressionResistancePriority` 메서드는 수평이나 수직 축에서 compression resistance의 우선순위를 설정할 수 있는 메서드 입니다 !

2023-02-03 09:02 UTC, HarryHyeon commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        operatorLabel.setContentCompressionResistancePriority(UILayoutPriority(1000), for: .horizontal)
- Compression Resistance priority
  - 공간이 부족할때 무엇이 줄어들지 우선순위를 설정하는 기능입니다.
  - 우선순위 숫자가 클 수록 자신의 크기를 유지할 수 있습니다.
  - 이번 프로젝트에서 숫자 Label의 크기가 늘어나서 연산자를 표기해주는 Label이 없어지는 현상을 방지했습니다 !
- Hugging priority
  - 공간이 남을때 무엇이 늘어날지 우선순위를 정할 수 있는 기능입니다.
  - 우선순위 숫자가 낮을 수록 늘어나게 됩니다.

2023-02-03 09:25 UTC, HarryHyeon commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        horizontalStackView.distribution = .fill
- axis
  - 기본값: horizontal
  - 스택뷰의 축을 지정할 수 있습니다. (horizontal, vertical)
- alignment
  - 기본값: fill 
  - fill: axis와 반대방향으로 스택뷰 안의 요소들을 가득 채웁니다.
  - center: 요소들을 가운데 축으로 정렬합니다. 
  - trailing: vertical 스택일 경우 오른쪽으로 정렬합니다.
  - leading: vertical 스택일 경우 왼쪽으로 정렬합니다.
  - bottom: horizontal 스택일 경우 아래쪽으로 나란히 정렬합니다.
  - top: horizontal 스택일 경우 위쪽으로 나란히 정렬합니다.
- distribution
  - 기본값: fill
  - fill: axis와 동일한 방향으로 스택뷰 안의 요소들을 우선순위에따라 크기를 줄이거나 확장시킵니다.
  - fillEqually: 스택뷰 안의 요소들이 같은 크기로 채워집니다.
  - fillProportionall: 스택뷰 안의 요소들이 가지는 비율에 맞춰 채워줍니다.
  - equalSpacing: 일정한 공간 간격으로 배치되어 스택뷰를 채워줍니다.
  - equalCentering: 스택뷰의 가운데 축을 기준으로 동일한 간격을 유지하도록 채워줍니다.
- spacing
  - 기본값: 0.0
  - 스택뷰 안의 서브뷰들의 간격을 설정할 때 사용합니다.

2023-02-03 09:27 UTC, HarryHyeon commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +        label.font = UIFont.preferredFont(forTextStyle: .title3)
생각못했던 부분이었는데 감사합니다 !

2023-02-03 09:44 UTC, HarryHyeon commented on Calculator/Calculator/Source/Controller/CalculatorViewController.swift
> +        }
`willSet`과 `didSet`은 프로퍼티 옵저버로 프로퍼티의 값의 변화를 관찰하고 응답하는 기능을합니다.
- `willSet`: 값이 변경되기 직전에 호출됩니다.
- `didSet`: 프로퍼티 값이 변경된 직후에 호출됩니다.

2023-02-03 10:14 UTC, HarryHyeon commented on Calculator/Calculator/Source/Controller/CalculatorViewController.swift
> +        historyScrollView.setContentOffset(bottomOffset, animated: true)
- contentSize : 스크롤이 가능한 영역의 크기를 말합니다.
- contentOffset : 컨텐츠 뷰의 최상단과 얼마만큼 떨어져있는지를 나타내는 수치 입니다. 이 값을 통해 얼마만큼 스크롤되었는지를 의미할 수 있습니다.
- contesntInset: 스크롤 뷰와 컨텐츠 뷰 간의 가장자리 간격을 설정하는 프로퍼티입니다.

2023-02-03 13:38 UTC, HarryHyeon commented on Calculator/Calculator/Source/View/HistoryViewGenerator.swift
> +    private static func generateLabel(text: String) -> UILabel {
링고 DM으로 도움 많이 주셔서 UIStackView를 상속받는 커스텀뷰를 만들어서 클래스 인스턴스를 생성할때, 생성자에 바로 Label의 Text를 넣을 수 있도록 수정했습니다 !

2023-02-04 09:03 UTC, llingo approved these changes
해리 계산기 I 프로젝트동안 수고하셨습니다 :)
다음 프로젝트도 화이팅입니다. 🎉

2023-02-04 09:03 UTC, merged