계산기 [Step3] 송준
yagom-academy/ios-calculator-app pull request #453
Opened 2023-02-03 01:19 UTC by kimseongj

@llingo
안녕하세요 링고! 리뷰 받기전에 먼저 죄송하다는 말씀 전해드리겠습니다.. 코드가 매우 난잡해서 보다보면 눈이 아플거 같군요😂
이번 스텝에서 수많은 로직 구현과 예외처리를 하면서 벽을 느꼈습니다. 특히, 처음에 판을 잘못 짰는데 그 방향으로 밀어붙이니 결과는 좋지 않군요! 밀어붙인 방향으로 PR을 보내보고, 추가적으로 다른  방법으로 리팩토링해볼 생각입니다.
이번 리뷰도 잘부탁드립니다 링고!

-----------
## 고민했던 점
### 1. 숫자버튼과 (.), 0, 00버튼의 분리 안했을 때
>  숫자버튼과 (.), 0, 00을 모두 같은 IBAction으로 받았습니다.  (.), 0, 00버튼은 예외사항이 많아 추가적인 함수가 많이 필요했습니다. 또한, 하나의 IBAction으로 모든 예외사항을 처리해야 하다보니 가독성이 많이 떨어지게 되었습니다. 

### 2. scrollView에서 contentViewSize가 커지면 현재 계산식이 가려지는 문제점
위 문제를 해결하기 위해 아래와 같은 방법을 사용했습니다. 
- bound는 기준이 자기 자신이며, scrollView의 `contentSize.height`에서 현재 `scrollView.bounds.height`를 빼주어서 CGPoint를 지정해주었습니다. 
```swift
expressionScrollView.setContentOffset(
            CGPoint(x: 0, 
                    y: expressionScrollView.contentSize.height - expressionScrollView.bounds.height),
            animated: true)
````

- 이 때 문제점은 설정은 제대로 되었지만, 바로 적용되지 않는 오류가 발생합니다. 이를 해결하기 위해 `layoutIfNeeded()`라는 메서드를 호출했습니다.
- `layoutIfNeeded()` 함수를 사용하여, 즉각적인 화면의 변화를 나타내줍니다.
```swift
expressionScrollView.layoutIfNeeded()
```

## 조언을 얻고 싶은 점
### 로직을 구현할 때 방향성
> 간단한 로직 구현은 여차저차 잘해왔던거 같은데, 이렇게 다양한 요구사항을 맞닥뜨리고 로직을 구현하려고 하니 정말 어려움을 많이 겪었던 것 같습니다. 사람마다 다 다르겠지만, 링고의 요구사항을 풀어나갈 때 무엇을 우선시 하는지 궁금합니다!

### 해결하지 못한 점
### 1. 소수점과 소수점에서 0이 즉각적으로 나오지 않습니다😂
> `numberFormatter`를 사용하기 전에는 String형으로는 소수점이 잘적혔는데,` numberFormatter`를 적용하고 나서부터 `.`을 입력해도 바로 나오지 않습니다.

![step3](https://user-images.githubusercontent.com/88870642/216487950-13ecfa86-8210-445e-8cfc-52c911b956fe.gif)

### 2. 화면에 20자리까지만 나오게 하고 싶습니다.
> Significant, Fraction의 자리수를 제한하는 등 여러 방법으로 자리수를 제한하려 했습니다. 하지만 20자리까지 제한되지 않았습니다. (,)가 포함된 자리수가 20자리인지, 숫자들만 포함하여 20자리인지 궁금합니다!

2023-02-04 08:59 UTC, llingo requested changes
안녕하세요 송준
계산기 프로젝트 STEP 3 수고하셨습니다 :)
연산자, 피연산자의 상태 때문에 사이드 이펙트를 잡는 것이 많이 어려웠을 것 같아요.
그래도 요구사항대로 잘 구현해주셨습니다 👏

---

> 안내사항은 참고용으로 남겨두었습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

---

**Q1. 소수점과 소수점에서 0이 즉각적으로 나오지 않습니다😂**

> numberFormatter를 사용하기 전에는 String형으로는 소수점이 잘적혔는데, numberFormatter를 적용하고 나서부터 .을 입력해도 바로 나오지 않습니다.

A1. NumberFormatter를 통해 처리할 때 만약 `1234.` 인 경우 프로퍼티에 저장된 값은 `1234.`이지만 포맷팅된 결과는 `1234`로 화면에 표시되기 때문에 발생한 것 같아요.


**Q2. 화면에 20자리까지만 나오게 하고 싶습니다.**

> Significant, Fraction의 자리수를 제한하는 등 여러 방법으로 자리수를 제한하려 했습니다. 하지만 20자리까지 제한되지 않았습니다. (,)가 포함된 자리수가 20자리인지, 숫자들만 포함하여 20자리인지 궁금합니다!

A2. `,`은 숫자를 표시하는 방식이므로 `,`를 제외한 숫자들만 포함하여 20자리라고 생각합니다.

2023-02-04 08:59 UTC, seu0313 commented on Calculator/Calculator/Controller/AppDelegate.swift
> +   @main
[P1] 탭이 하나 추가된 것 같아요 :)

2023-02-04 08:59 UTC, seu0313 commented on Calculator/Calculator/Model/Operator.swift
> +    case multiply = "×"
Operator의 rawValue 값이 변경된 이유가 있나요?

2023-02-04 08:59 UTC, seu0313 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBOutlet weak var expressionScrollView: UIScrollView!
외부에서 UI 프로퍼티로 직접 접근할 수 있을 것 같아요 :)

2023-02-04 08:59 UTC, seu0313 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        expressionScrollView.layoutIfNeeded()
`layoutIfNeeded`를 사용해주셨네요. 해당 메서드는 어떤 기능을 하나요?

2023-02-04 08:59 UTC, seu0313 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +final class CalculatorViewController: UIViewController {
ViewController 이름을 변경해주셨네요 👍

2023-02-04 08:59 UTC, seu0313 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +    @IBAction private func numberButton(sender: UIButton) {
[P1] `IBAction`의 경우 UI 요소가 사용자로 인해 이벤트를 전달 받았을때 호출되는 메서드입니다.
`명사형` 네이밍보다 `동사 + 명사형`으로 동작을 의미하는 네이밍이 더 좋을 것 같네요 :)

2023-02-04 08:59 UTC, llingo commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        operandExpression = ""
[P1] 명사형은 함수의 네이밍으로 좋지 않는 것 같아요. 일반적으로 `동사 + 명사`형으로 작성하는 편입니다.

2023-02-04 08:59 UTC, llingo commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if numberLabelText.first == "-" && operandExpression.first == "-" {
[P3] if, guard 등 코드 사이의  개행에 대한 송준만의 규칙이 있나요?
코드의 개행도 의도를 포함하여 일관되도록 작성하는 것이 가독성 측면에서도 좋을 것 같아요 👀

2023-02-04 08:59 UTC, llingo commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        partOfExpressionStackView.spacing = 5
UIStackView의 `axis, alignment, distribution, spacing`은 어떤 역할을 하나요? 
그리고 기본값은 어떤 값으로 되어있을까요? 👀

2023-02-04 08:59 UTC, llingo commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        maintainScrollViewBottom()
여유가 있으시다면 `커스텀 뷰`로 만들어보시는 것을 추천드립니다 👍

2023-02-04 08:59 UTC, llingo commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            CGPoint(x: 0, y: expressionScrollView.contentSize.height - expressionScrollView.bounds.height),
UIScrollView의 `contentSize, contentOffset, contentInset`은 각각 어떤 역할을 하는 프로퍼티인가요? 👀

2023-02-05 08:29 UTC, kimseongj commented on Calculator/Calculator/Model/Operator.swift
> +    case multiply = "×"
제가 생각했던 빼기, 곱하기, 나누기 기호와 계산기 UI에 구현되어 있던 빼기, 곱하기, 나누기 기호가 달랐습니다! 로직이 돌아가기 위해서 case 값들을 변경해야 했습니다!

2023-02-05 11:13 UTC, kimseongj commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        if numberLabelText.first == "-" && operandExpression.first == "-" {
문맥상 다르거나, 다른 기능을 하면 띄어쓰기를 하는 편이었습니다.
이번 코딩에서는 한개의 함수 내에 여러 기능들이 들어가서 코딩컨벤션도 맞추기 어려웠던거 같습니다ㅠ 수정했습니다!

2023-02-05 11:30 UTC, kimseongj commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        expressionScrollView.layoutIfNeeded()
`layoutIfNeeded`는 UI업데이트가 즉각적으로 될 수 있도록 해주는 메서드입니다.
이 메서드가 호출되면 Update Cycle을 바로 실행하여 레이아웃이 즉각적으로 적용될 수 있습니다.

#### Main Run Loop
- 어플리케이션이 실행되면 메인 스레드에서 main run loop를 실행시킵니다. main run loop는 터치 이벤트, 위치의 변화, 디바이스의 회전 등의 각종 이벤트들을 처리하게 됩니다. 이러한 처리 과정은 각 이벤트들에 알맞는 핸들러를 찾아 그들에게 권한을 위임하며 진행됩니다.
- 이렇게 발생한 이벤트들을 모두 처리하고 권한이 다시 main run loop로 돌아오게 되고 이 시점을 update cycle입니다.

#### Update Cycle
- main run loop에서 이벤트가 처리되는 과정에서 버튼을 누르면 크기나 위치가 이동하는 애니메이션과 같이 layout이나 position 값을 바꾸는 핸들러가 실행될 때도 있습니다. 이러한 변화는 즉각적으로 반영되는 것이 아닙니다.
- 시스템은 이러한 layout이나 position이 변화되는 View를 체크합니다. 그리고 모든 핸들러가 종료되고 main run loop로 권한이 다시 돌아오는 시점인 update cycle에서 이런 View들의 값을 바꿔주어 position이나 layout의 변화를 적용시킵니다.

2023-02-05 11:30 UTC, kimseongj commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        maintainScrollViewBottom()
넵!! 다음주 계산기 때 적용시켜보겠습니다!

2023-02-05 12:01 UTC, kimseongj commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        partOfExpressionStackView.spacing = 5
1. axis : 스택뷰의 방향을 결정합니다.(가로 세로)
- 가로(Horizontal)
- 세로(Vertical)

3. distribution(axis 방향으로) : axis와 평행한 방향으로 내부 요소를 배치하는 속성입니다.
- fill: 스택뷰 안에 여러 뷰들로 채워준다.
- fillEqually: 뷰들이 동일한 크기로 채워준다.
- fillProportionally: 뷰의 컨텐츠 비율대로 채워준다.
- equalSpacing: 간격을 동일하게 가져간다.
- equalCentering: 각각의 뷰들의 중앙을 기점으롤 동일한 간격을 가진다.

4. alignment(axis가 아닌 방향으로) : axis와 수직인 방향으로 내부 요소를 배치하는 속성입니다.
- fill: 뷰를 스택뷰 크기만큼 채워준다.
- leading: leading에 정렬된다.
- top: top으로 정렬된다.
- firstBaseline:  text의 맨 윗줄을 기준으로 정렬
- center: 가운데 정렬
- trailing: trailing에 정렬
- bottom: bottom에 정렬
- lastBaseline: text의 맨 아랫줄을 기준으로 정렬

5. spacing : 내부에 있는 서브뷰의 간격을 결정합니다.

2023-02-05 12:32 UTC, kimseongj commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            CGPoint(x: 0, y: expressionScrollView.contentSize.height - expressionScrollView.bounds.height),
1. contentInset

- contentInset은 컨텐츠에 상하좌우 여백을 주는 것이라고 생각하면 됩니다.

- contentView의 inset이 safe area나 scrollView에서 얼마나 떨어져있는지 의미합니다.

2. contentOffset

- contentOffset은 contentView가 위치한 point입니다. 

즉 사용자가 영역을 스크롤한 후에 있는 지점을 의미하고, 사용자가 스크롤할 때마다 값이 바뀝니다.

3. contentSize 

- 컨텐츠 뷰의 사이즈입니다

2023-02-06 00:40 UTC, llingo approved these changes
송준 계산기 I 프로젝트동안 수고하셨습니다 :)
다음 프로젝트도 화이팅입니다. 🎉

2023-02-06 00:40 UTC, merged