계산기 [STEP 3] Rhode
yagom-academy/ios-calculator-app pull request #454
Opened 2023-02-03 02:23 UTC by Rhode-park

@llingo 안녕하세요 링고! UI에 대한 이해가 부족해 많이 늦었습니다. 리뷰 해주시는 것 정말 감사합니다!!

# 조언을 얻고 싶은 부분
### 1. 스크롤뷰를 최하단으로 내리면 스택뷰가 하나씩 누락되는 문제
다음과 같은 코드를 사용해서 스크롤뷰를 최하단으로 내렸습니다.
```swift
scrollView.setContentOffset(CGPoint(x: 0, y: scrollView.contentSize.height - scrollView.bounds.height), animated: true)
```

그런데, 스택뷰가 하나씩 누락되는 문제가 생기고 있어 뺐습니다.
왜일까요...
8ㅅ8
`layoutIfNeeded()`라는 것을 발견하긴 했는데, 이것을 사용해보면 좋을까요?

### 2. 3.03-1.03을 했을 때 1.9999999999999998이 나타나는 문제
3.03-1.03을 진행했을 때 1.9999999999999998이 나타납니다.
플레이 그라운드에서 연산을 했을 때 같은 결과가 나오는 걸로 봐서 Double의 문제인 것 같기도 합니다.
어떻게 해결해야할까요? 8ㅅ8

### 3. 1을 17번 이상 입력하면 2가 찍히고 20번 입력하면 넘버 포매터가 적용되지 않는 문제
![](https://i.imgur.com/iSbPwlZ.gif)
위 그림과 같이 1을 17번 이상 입력하면 2가 찍히고, 20번 입력하면 쉼표를 찍기 위한 넘버 포매터가 적용되지 않습니다.
브레이크를 찍어보니 이 부분(String extension의 20번째 줄)에서 2가 들어가게 되는 것 같습니다.
```swift
return numberFormatter.string(from: NSNumber(value: intValue)) ?? self
```
NS넘버의 문제인가 싶어서 다음과 같은 코드를 작성해보았는데도 여전히 2가 들어가고 쉼표가 사라집니다.
```swift
extension String {
    
    func addComma() -> String {
        guard self.count > 3 else {
            return self
        }
        var newValue: [String] = self.map({ String($0) })
        var counts: [Int] = []
        for index in 0..<self.count {
            counts.append(index)
        }
        for count in counts.reversed() {
            if (self.count - count) % 3 == 0, count != 0 {
                newValue.insert(",", at: count)
            }
        }
        return newValue.joined()
    }
}
```
왜일까요...
오늘도 좋은 리뷰 감사드립니다.
잘부탁드리겠습니다.

2023-02-04 08:43 UTC, llingo requested changes
안녕하세요 Rhode
계산기 프로젝트 STEP 3 수고하셨습니다 :)
연산자, 피연산자의 상태 때문에 사이드 이펙트를 잡는 것이 많이 어려웠을 것 같아요.
그래도 요구사항대로 잘 구현해주셨습니다 👏

---

앞으로의 원활한 리뷰 진행을 위해 몇 가지 안내사항을 드리겠습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

---

**Q1. 스크롤뷰를 최하단으로 내리면 스택뷰가 하나씩 누락되는 문제**

```swift
scrollView.setContentOffset(CGPoint(x: 0, y: scrollView.contentSize.height - scrollView.bounds.height), animated: true)
```

> layoutIfNeeded()라는 것을 발견하긴 했는데, 이것을 사용해보면 좋을까요?

A1. 해당 부분은 Update Cycle과 관련된 문제같아요. [Update Layout Cycle](https://tech.gc.com/demystifying-ios-layout/)과 `layoutIfNeeded`를 사용해보면서 관련 다른 함수들에 대해서도 공부해보면 좋을 것 같아요

**Q2. 3.03-1.03을 했을 때 1.9999999999999998이 나타나는 문제**

> 3.03-1.03을 진행했을 때 1.9999999999999998이 나타납니다.

A2. 실수 자료형에서 소수점 아래 값을 저장하는 과정에서 발생한 오차로 인해 나타난 문제라고 생각되네요. [Swift - Decimal](https://developer.apple.com/documentation/foundation/decimal)을 사용하는 방법이 있을 것 같아요.

**1을 17번 이상 입력하면 2가 찍히고 20번 입력하면 넘버 포매터가 적용되지 않는 문제**

A3. 이 부분은 NumberFormatter에서 처리하는 과정에서 16-17자리를 넘어갈때 발생하는 문제로 보입니다. Decimal를 NSNumber로 캐스팅을 통해 해결할 수 있을 것 같아요.

```swift
numberFormatter.string(from: Decimal(intValue) as NSNumber) ?? self
```

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/View/CircleButton.swift
> +}
커스텀 버튼 타입을 구현해주셨네요 💯 
`draw(rect:)`은 어떤 기능을 하는 메서드인가요? [Update Cycle](https://tech.gc.com/demystifying-ios-layout/) 과 함께 공부해보면 좋을 것 같아요 :)

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +        loadView(operatorLabelText: operatorText, operandsLabelText: operandsText)
커스텀 StackView를 구현해주셨네요 💯

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +        spacing = 8
UIStackView의 `axis, alignment, distribution, spacing`은 어떤 역할을 하나요? 
그리고 기본값은 어떤 값으로 되어있을까요? 👀

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +    private func configure() {
[P1] 뷰를 설정하는 네이밍으로 `configureOOO`이나 `setupOOO`으로 작성할 수 있을 것 같아요. 외부에서 호출할 필요가 없다면 `private` 접근 제어자를 사용하는 것이 좋아보입니다 :)

예시) `configureCollectionView, configureStackView`

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +    }
[P3] 클로저를 통한 저장 프로퍼티 생성을 활용할 수 있을 것 같아요

```swift
private let operandLabel: UILabel = {
    let label = UILabel()
    label.textAlignment = .right
    label.textColor = .white
    label.font = .preferredFont(forTextStyle: .title3)

    return label
}()
```

위를 활용하여 아래와 같이 작성해볼 수 있을 것 같습니다

<details>
    <summary>예시(참고용)</summary>

```swift
final class 커스텀스택뷰: UIStackView {
    private let operatorLabel: UILabel = {
        let label = UILabel()
        label.textAlignment = .right
        label.textColor = .white
        label.font = .preferredFont(forTextStyle: .title3)

        return label
    }()

    private let operandsLabel: UILabel = {
        let label = UILabel()
        label.textAlignment = .right
        label.textColor = .white
        label.font = .preferredFont(forTextStyle: .title3)

        return label
    }()

    init(operatorText: String?, operandsText: String?) {
        super.init(frame: .zero)

        configureView()

        operatorLabel.text = operatorText
        operandsLabel.text = operandsText
    }

    required init(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    private func configureView() {
        axis = .horizontal
        alignment = .fill
        distribution = .fill
        spacing = 8.0
        
        addArrangedSubview(operatorLabel)
        addArrangedSubview(operandsLabel)
    }
}
```
</details>

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +final class ViewController: UIViewController {
[P1] ViewController 만으로는 어떤 기능의 화면인지 알 수 없을 것 같아요. 의미를 추가하면 좋을 것 같습니다.

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +    @IBOutlet private weak var scrollView: UIScrollView!
[P1] scrollView 네이밍 만으로 파악하기 힘들 것 같아요. 구체적인 의미를 담은 네이밍으로 변경하면 좋을 것 같습니다 :)

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +        }
[P2] allClear()에도 같은 기능이 중복되어 있네요. 기능을 개별 함수로 쪼개면 좋을 것 같아요 :)

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Extension/String+.swift
> +    var insertComma: String {
[P1] insertComma는 `동사 + 명사`형으로 프로퍼티 네이밍으로는 좋지 않은 것 같아요. 
일반적으로 `동사 + 명사`형은 함수의 네이밍으로 많이 사용하는 형태입니다. 👀

2023-02-04 08:43 UTC, seu0313 commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +    }
아래와 같이 guard 문을 사용하시면 들여쓰기 depth를 줄일 수 있을 것 같아요.

```suggestion
    @IBAction private func tapDotButton(_ sender: UIButton) {
        guard currentNumber.contains(".") == false else {
            return
        }

        if currentNumber == NameSpace.emptyString {
            currentNumber += NameSpace.stringZero
            stringToBeCalculated += NameSpace.stringZero
        }

        insertString(titleName: sender.titleLabel?.text)
        setCurrentNumber(titleName: sender.titleLabel?.text)
    }
```

2023-02-04 12:26 UTC, Rhode-park commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +    }
다음과 같이 클로저를 활용하여 refactoring 해보았습니다:
```swift
private let label: UILabel = {
    let label = UILabel()
    label.textAlignment = .right
    label.textColor = .white
    label.font = .preferredFont(forTextStyle: .title3)
    return label
}()

private func makeLabel(labelText: String?) -> UILabel {
    label.text = labelText
    return label
}
```

2023-02-04 13:58 UTC, Rhode-park commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +    @IBOutlet private weak var scrollView: UIScrollView!
수정하였습니다 :)

2023-02-04 14:00 UTC, Rhode-park commented on Calculator/Calculator/Extension/String+.swift
> +    var insertComma: String {
수정하였습니다 :)

2023-02-04 14:01 UTC, Rhode-park commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +final class ViewController: UIViewController {
수정하였습니다 :)

2023-02-04 14:02 UTC, Rhode-park commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +        loadView(operatorLabelText: operatorText, operandsLabelText: operandsText)
감사합니다!

2023-02-04 14:10 UTC, Rhode-park commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +        spacing = 8
- `axis`: 스택뷰를 종적으로 만들지 횡적으로 만들지 결정하는 속성입니다.
 - `alignment`: 스택 뷰의 axis의 수직 방향을 기준으로 요소들을 어떻게 정렬할지 결정하는 속성입니다. 
스택뷰를 처음 생성했을 때는 기본값으로 Fill이 설정되어 있습니다.
Fill: 스택 뷰의 높이만큼 내부 요소들의 높이를 결정해 스택뷰의 높이만큼 채웁니다.
 - `distribution`: 스택뷰의 axis의 수평방향을 기준으로 내부 요소들을 어떻게 배치할지 결정하는 속성입니다.
Fill: 현재 기준 방향으로 요소들을 채우기 위한 속성입니다. 만약 내부 요소들의 너비의 합이 스택 뷰의 너비보다 크다면 서브 뷰들의 크기를 줄이고, 내부 요소들의 너비의 합이 스택 뷰의 너비보다 작으면 뷰들의 너비를 확장시킵니다.
 - `spacing`은 내부에 있는 라벨이나 뷰 사이의 간격을 정해진 얼마나 떨어뜨려줄지 결정하는 속성입니다.

2023-02-04 14:12 UTC, Rhode-park commented on Calculator/Calculator/Sources/View/OperateStackView.swift
> +    private func configure() {
`setupView`로 수정하였습니다.

2023-02-04 14:16 UTC, Rhode-park commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +        }
`allClearViews`라는 함수로 쪼갰습니다.

2023-02-04 14:18 UTC, Rhode-park commented on Calculator/Calculator/Sources/View/CircleButton.swift
> +}
이미지를 네모로 그려주는 메서드입니다. 저는 반지름을 높이의 1/2로 주어서 동그란 버튼을 만들기 위하여 사용했습니다.

2023-02-04 17:53 UTC, Rhode-park commented on Calculator/Calculator/Sources/Controller/ViewController.swift
> +    }
guard문으로 수정하였습니다!

2023-02-04 17:55 UTC, Rhode-park commented
코멘트 반영하여 모두 수정하였습니다 :-) 하하 감사합니다!!!

2023-02-05 02:54 UTC, llingo approved these changes
Rhode 계산기 I 프로젝트동안 수고하셨습니다 :)
다음 프로젝트도 화이팅입니다. 🎉

2023-02-05 02:54 UTC, llingo commented on Calculator/Calculator/Sources/Controller/CalculatorViewController.swift
> +        allClearViews()
중복되었던 기능을 하나의 함수로 분리해주셨군요 👍

2023-02-05 02:54 UTC, llingo commented on Calculator/Calculator/Formatter/CalculatorFormatter.swift
> +    private init() {}
타입으로 분리해주셨네요 💯

2023-02-05 02:54 UTC, llingo commented on Calculator/Calculator/Sources/View/CircleButton.swift
> +}
`draw(rect:)` 메서드는 아래 그림처럼 Update Cycle과 관련 있는 함수입니다!
추후 [Update Cycle](https://tech.gc.com/demystifying-ios-layout/) 과 함께 공부해보면 좋을 것 같아요 :)

![1](https://user-images.githubusercontent.com/94151993/216798513-b78e9c35-ee6d-43cb-8f14-8021d5443adc.png)

2023-02-05 02:54 UTC, llingo commented on Calculator/Calculator/Formatter/CalculatorFormatter.swift
> +class CalculatorFormatter {
상속과 같은 다형성을 사용할 필요가 없다면 `final` 키워드를 작성하는 것이 좋습니다. `final` 키워드를 작성해두어 다른 개발자들이 해당 클래스를 무분별하게 상속해 사용하는 것을 막을 수 있고 최적화 측면에서도 장점이 있습니다 :)

2023-02-05 02:54 UTC, merged

2023-02-05 04:26 UTC, Rhode-park commented on Calculator/Calculator/Formatter/CalculatorFormatter.swift
> +class CalculatorFormatter {
네 수정하겠습니다!