계산기 [STEP 3] vetto
yagom-academy/ios-calculator-app pull request #455
Opened 2023-02-03 05:56 UTC by gzzjk159

# 계산기 [STEP 3] vetto
안녕하세요 @Judy-999
UI, 오토레이아웃에 익숙치 않아 고생하다가 step3 PR 보냅니다
제가 발견하지 못한 오류, 구현하지 못한 기능이 있다면 알려주시면 최대한 노력해서 고치겠습니다.

## 고민했던 점
### 계산기 입력 부분에서의 NumberFormatter
* 계산기에 숫자를 입력할 때에도 자릿수가 3자리가 넘어가면 `,`를 붙여야 한다는 것을 인지하였습니다. 하지만 입력할 때마다 NumberFormatter 소수점 뒤에 0들은 나오지 않게 코드를 작성하여 자꾸 없어진다는 것을 알게 되었습니다. 일단 PR을 보내고 천천히 이 부분에 대해서 고민하려고 합니다.

### subview의 업데이트
* addArrangedSubview로 view를 추가한다 해도 view가 바로바로 업데이트 되지 않는다는 것을 알았습니다. 다른 분의 도움을 받아 layoutIfNeeded라는 함수를 사용하면 업데이트가 된다고 들었습니다. 일단은 함수를 사용하여 업데이트가 바로바로 되게 코드를 적었습니다. 이러한 부분의 공부도 한번 해봐야 할 거 같습니다.

## 해결하지 못한 점 & 조언받고 싶은 점
### ViewController
* 메인 뷰컨트롤러가 너무 커지는 것을 코드를 작성하면서 알았습니다. 이것을 분리할 필요가 있다고 생각하는데 어떻게 분리해야 될 지 감이 오지 않습니다. 어떻게 분리하면 좋은지 리뷰어의 도움이 필요합니다. (파일 분리에 대한 조언도 해주시면 감사하겠습니다.)

2023-02-04 09:11 UTC, Judy-999 requested changes
vetto 수고하셨어요 🙌
마지막 STEP까지 잘 구현해주셨네요 👏👏
계산기가 여러 복잡한 로직을 가지고 있어서 어려우셨을 텐데 오토레이아웃 부부도 있어서 힘드셨을 거예요 😅
그럼에도 마지막 STEP까지 잘 해주셨습니다 👍

---

## 고민했던 점
### 계산기 입력 부분에서의 NumberFormatter
> 계산기에 숫자를 입력할 때에도 자릿수가 3자리가 넘어가면 ,를 붙여야 한다는 것을 인지하였습니다. 하지만 입력할 때마다 NumberFormatter 소수점 뒤에 0들은 나오지 않게 코드를 작성하여 자꾸 없어진다는 것을 알게 되었습니다. 일단 PR을 보내고 천천히 이 부분에 대해서 고민하려고 합니다.


자세히는 로직에 따라 다르겠지만 text에 넣을 때 numberFormatting을 거쳐야 하지는 않나요? 🤔
```swift
    private var calculateOperand: String = "0" {
private var calculateOperand: String = "0" {
    didSet {
        operandLabel.text = calculateOperand.numberFormatting()
    }
}
```
<br>

### subview의 업데이트
> addArrangedSubview로 view를 추가한다 해도 view가 바로바로 업데이트 되지 않는다는 것을 알았습니다. 다른 분의 도움을 받아 layoutIfNeeded라는 함수를 사용하면 업데이트가 된다고 들었습니다. 일단은 함수를 사용하여 업데이트가 바로바로 되게 코드를 적었습니다. 이러한 부분의 공부도 한번 해봐야 할 거 같습니다.

`layoutIfNeeded`로 해결하셨네요 👏 뷰는 시각적인 변경이 반영되는 Drawing Cycle을 가지고 있습니다. 더불어 `setNeedsLayout`과 `layoutSubviews`도 알아두시면 좋은데 아직은 어려운 개념일 수 있으니 나중에 여유있으실 때 [관련 블로글](https://tech.gc.com/demystifying-ios-layout/)나 [WWDC](https://developer.apple.com/videos/play/wwdc2015/219/)를 참고해보세요~ 
<br>

## 해결하지 못한 점 & 조언받고 싶은 점
### ViewController
> 메인 뷰컨트롤러가 너무 커지는 것을 코드를 작성하면서 알았습니다. 이것을 분리할 필요가 있다고 생각하는데 어떻게 분리해야 될 지 감이 오지 않습니다. 어떻게 분리하면 좋은지 리뷰어의 도움이 필요합니다. (파일 분리에 대한 조언도 해주시면 감사하겠습니다.)

MVC의 단점 중 하나가 Controller가 비대해진다는 점이 있습니다 🥲
그래서 가능한 공통된 역할을 하는 코드는 객체로 분리할 수 있습니다.

`ExpressionParser`와 같은 객체로 분리하는 방법이 될 수 있겠죠!

이외에도 **String**을 extension해서 구현하신 것 처럼 타입에 기능을 추가하는 방법 역시 기능을 분리하는 방법이 될 수 있습니다. 하지만 해당 타입에 공통적인 기능을 추가하는 것이므로 무분별하게 `extension`하는 것은 지양해야 합니다.

기본적으로 현재는 View에 해당하는 코드가 Controller에 혼합되어 있는 상태라 이후에 코드로 View를 구성하시는 작업을 해보시면 View와 Controller가 분리되는 경험을 해보실 수 있을 것 같네요!

파일은 관련된 파일들끼리 그룹으로 묶는 것을 추천합니다. 기본적으로 vetto가 원하는 방식을 기반으로 해야겠지만 제 기준을 알려드릴게요! MVC 구조라면 Model, View, Controller로 구분하는 편입니다. AppDelegate와 SceneDelegate는 App의 Life Cycle을 관리하므로 `Application` 그룹으로 정리합니다. 

그룹 내에서도 연관된 파일끼리 묶어주고는 하는데 예를들어 Model 내부에서도 CalculatorItemQueue와 관련된 파일들끼리 그룹으로 만들어 관리하는 것이죠. 파일 분류에 대해서는 다양한 코드를 보시면서 어떻게 구분되어 있는지 보시고 예시로 삼으셔도 좋습니다 🙂
<br>

---

## 오류 상황
실행하면서 발견한 오류 상황들 입니다. 수정 또는 의견을 알려주세요 ❗️

1. 0인 상태에서 00을 누르면 추가가 됩니다.
2. 연산 결과가 나온 후 `숫자 입력 -> =`을 반복하면 숫자가 계속 스크롤뷰에 추가됩니다.

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +final class CalculatorViewController: UIViewController {
네이밍과 `final` 적용 좋네요 👍

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +    private var calculateOperand: String = "0" {
어떤 의미의 개행들인가요? 모든 프로퍼티들 사이에 개행을 넣는건 불필요할 것 같네요!

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +        }
didSet을 활용하셨네요 👍

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +    @IBAction func didTapACButton() {
`@IBAction func` 역시 접근 제어 신경써주세요!

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +    private func setDefault() {
`set`은 여러 의미로 해석될 수 있어 설정을 의미한다면 `setup`을 사용하는 편입니다!
`Default`보다도 무엇을 set하는지를 표현하시면 좋겠습니다~

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +        calculateStackView.arrangedSubviews.forEach { $0.removeFromSuperview() }
`forEach` 사용 좋습니다 👍

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +        calculateOperand = "0"
이렇게도 처리할 수 있겠네요~
```swift
if isCalculated == false {
    calculateOperand = "0"
}
```

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +        addToCalculateItem(left: calculateOperator, right: calculateOperand)
두 메서드는 같이 호출되는 걸로 보이는데 두 메서드를 호출하는 코드를 메서드로 분리하거나, 둘을 하나의 메서드로 구성해봐도 좋겠네요 🙂

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +        }
`return` 한다면 `guard` 구문을 활용해서 원하지 않는 흐름임을 표시하는 것도 좋습니다 👀

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +                                    .joined() else { return }
","를 제거하고자 한다면 `filter { $0 != "," }`도 활용해볼 수 있습니다!

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +        calculateOperand = "0"
코드 전반적으로 "0"이 자주 사용되고 있는데 이렇게 직접 적는 하드코딩보다는 상수로 선언되어 있으면 휴먼에러를 방지할 수 있습니다 🙂

"," 나 ""도 마찬가지입니다~

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +        let bottomOffset = CGPoint(x: 0,
불필요한 개행으로 보이네요 👀

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +                                    - calculateScrollView.bounds.height)
어떤 위치일까요? 🤔

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/CalculatorViewController.swift
> +    }
UILable과 UIStackView를 생성 및 설정하는 부분을 메서드로 구현하셨네요 👍

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/Model/StringExtension.swift
> +    }
어떤 처리를 위한 코드인가요? 동작을 설명해주세요 👀

2023-02-04 09:11 UTC, Judy-999 commented on Calculator/Calculator/Model/StringExtension.swift
> +        }
```suggestion
            let numberFormatter = NumberFormatter()
            numberFormatter.numberStyle = .decimal
            numberFormatter.maximumFractionDigits = 20
            numberFormatter.roundingMode = .halfUp
```

이렇게 바로 사용하는게 더 간편하지 않을까요 🤔

2023-02-05 08:51 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +    private var calculateOperand: String = "0" {
리뷰어 조언대로 불필요한 개행들을 삭제하였습니다. d61419f74b869c97863fa26acc5cf311b4eabd27

2023-02-05 08:52 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +    @IBAction func didTapACButton() {
리뷰어 조언대로 접근제어자를 private로 바꾸어 외부에서 접근을 못하게 설정하였습니다 d61419f74b869c97863fa26acc5cf311b4eabd27

2023-02-05 08:53 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +    private func setDefault() {
리뷰어 조언대로 set대신 setup을 사용하고 default같이 모호한 단어보다 Operand, Operator를 붙어주어 함수가 어떤 것을 실행하는지 명확하게 표현하였습니다. d61419f74b869c97863fa26acc5cf311b4eabd27

2023-02-05 08:55 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +        calculateOperand = "0"
리뷰어 조언대로 불필요한 코드를 줄였습니다 d61419f74b869c97863fa26acc5cf311b4eabd27

2023-02-05 08:56 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +        addToCalculateItem(left: calculateOperator, right: calculateOperand)
리뷰어 조언대로 같이 호출되는 것을 확인하고 addExpressionAndCalculateItem 함수를 만들어 같이 실행할 수 있게 해주었습니다. 15445047f31b46b64deaf1771893ac013c8fac58

2023-02-05 08:57 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +        }
리뷰어 조언대로 guard 구문을 활용하여 원하지 않는 흐름에서 빠져나올 수 있게 하였습니다 d61419f74b869c97863fa26acc5cf311b4eabd27

2023-02-05 08:58 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +                                    .joined() else { return }
리뷰어 조언대로 ","를 제거하기 위해 활용한 코드였습니다. 이것이 자주 쓰일거 같아 string extension을 활용하여 ","를 제거하는 함수를 작성하였습니다. 15445047f31b46b64deaf1771893ac013c8fac58

2023-02-05 09:00 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +        calculateOperand = "0"
리뷰어 조언대로 자주 쓰이는 숫자나 기호들을 enum 타입을 활용하여 넣어주고 그것을 호출하는 방식으로 코드를 수정하였습니다. ee7d93d7ad5d77f48c4c33a37c1d8bf1e314ed1d

2023-02-05 09:01 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +        let bottomOffset = CGPoint(x: 0,
리뷰어 조언대로 불필요한 개행들을 찾아서 제거했습니다. 1d3917ef54009ae34acf625a9a6916f950ac3476

2023-02-05 09:01 UTC, gzzjk159 commented on Calculator/Calculator/CalculatorViewController.swift
> +                                    - calculateScrollView.bounds.height)
위치를 전체적으로 수정하는 코드로 바꾸었습니다. 1d3917ef54009ae34acf625a9a6916f950ac3476

2023-02-05 09:02 UTC, gzzjk159 commented on Calculator/Calculator/Model/StringExtension.swift
> +    }
위에 작성된 메서드는 쓸모가 없는 메서드라 생각되어 지우고 다시 작성하였습니다. 따라서 위에 코드는 현재 존재하지 않습니다.

2023-02-05 09:03 UTC, gzzjk159 commented on Calculator/Calculator/Model/StringExtension.swift
> +        }
리뷰어 조언대로 바로 사용할 수 있게 바꾸었습니다.  15445047f31b46b64deaf1771893ac013c8fac58

2023-02-05 09:06 UTC, gzzjk159 commented
@Judy-999 말씀하신 오류는 최대한 수정하였습니다. 만약 다른 오류가 있다면 말씀해주시면 감사하겠습니다. 그리고 저의 나름대로 파일을 분리하는 작업을 수행했습니다. 리뷰어가 말씀해주신 Model View Controller로 나누는 부분은 아직  MVC의 구분이 쉽지않아 하지 못했습니다. 나중에 공부하여 파일을 분리하는 작업을 하도록 하겠습니다.

2023-02-05 15:26 UTC, Judy-999 approved these changes
전체적으로 코드가 깔끔해졌네요 👍👍
`Extension`, `Protocol` 파일들도 그룹으로 분리하신 점 좋네요 🙂

2023-02-05 15:26 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
공통된 조건이 있으니 아래와 같이 처리할 수 있겠네요 🙂
```suggestion
        guard calculateOperand != Symbol.zero else {
           if  calculateOperator != Symbol.blank {
               calculateOperator = operatorSign
           }
           return
        }
```

2023-02-05 15:26 UTC, Judy-999 commented on Calculator/Calculator/Extension/NumberFormatter+Extension.swift
> +    }
메서드의 매개변수 타입을 **Double**과 **String**으로 다르게 하여  모두 적용할 수 있도록 하였네요 👍

2023-02-05 15:26 UTC, Judy-999 commented on Calculator/Calculator/Extension/String+Extension.swift
> +    }
**extension**으로 연산 프로퍼티도 만들 수 있습니다 🙂

```suggestion
    var withoutComma: String {
        return self.filter({ $0 != Character(Symbol.comma) })
    }
```

2023-02-06 02:06 UTC, Judy-999 commented
수고하셨습니다 👏👏🥳

2023-02-06 02:06 UTC, merged