계산기 [STEP 3] 릴라
yagom-academy/ios-calculator-app pull request #456
Opened 2023-02-03 08:51 UTC by juun97

## 계산기 [STEP 3] 릴라
@wongbingg
안녕하세요 웡빙 step 3 피알 보냅니다!
이번 스텝을 진행하면서 제가 많이 부족하구나 뼈저리게 느꼈습니다...
메서드 안에서 기능분리를 신경쓸 새도 없이 작성하다보니 많이 지저분하네요 ㅜㅜ

## 고민했던점 🤨

### 1️⃣ 0이 계속해서 들어왔을 때의 오류처리

<img width="600" alt="image" src=https://i.imgur.com/B8j0As5.png>

- sender 의 currentTitle 로 버튼의 숫자를 받아온 뒤 해당 숫자가 0과 00일 경우에 조건문을 통해 오류처리를 진행 하였습니다.
 
### 2️⃣ 연산자 버튼의 오류처리
- 제일 오랫동안 헤매던 부분이었습니다 😭
- 연산자 버튼을 클릭했을 때 생각해야 했던 경우의 수는 다음과 같았습니다.
    > 1. OperandsLabel 에 아무값이 들어오지 않은 채 버튼이 눌렸을 때
    > 2. 연산자 버튼이 연속으로 눌렸을 때
 
 - 1번의 경우 전역으로 OperandLabel 의 텍스트 값을 가지고 있는 CurrentLabelText 를 통해 값이 존재하지 않는 경우 연산자의 라벨만 입력값으로 교체한 뒤 리턴을 하는 방향으로 진행 했습니다.
```swift
         if currentLabelText.isEmpty && formattedOperands.isEmpty {
             OperatorLabel.text = sender.currentTitle
             return
         }
```

 - 2번의 경우 입력값을 연산자와 피연산자를 순서대로 보관하고 있는 inputList 를 통해 마지막 element 가 Operator 로 형변환이 가능한지를 판단하여 Operator일 경우 OperatorLabel 의 text 만 변경을 해준 뒤 return을 했습니다.

```swift
         if let element = inputList.last {
             guard Operator(rawValue: Character(element)) == nil else {
                 OperatorLabel.text = operatorSign
                 return
             }
         }
```

### 3️⃣ 계산식을 만드는 로직
- 계산식의 경우 operand 와 oprator 를 순서대로 보관하는 `inputList: [String]` 배열을 만들어 관리했습니다.
- 요소를 `append` 하는 시점은 하나의 입력이 끝났다고 판단하는 `operatorButton` 의 클릭 시점으로 잡았습니다.
- 하지만 이런식으로만 `append` 를 진행할경우 `마지막 1개의 operand` 가 화면에만 출력되고 배열에는 들어가지 않음으로 calculate 버튼이 눌렸을 때 화면에 출력되어있는 요소에 대해 append를 진행 하였습니다.
- operator 의 경우에도 문제점이 있었는데 연산자가 `연속으로 클릭` 되었을 때 화면에 출력되있는 operator만 수정한뒤 return  하고 있었기에 inputList에 저장되있는 operator와 화면에 출력되있는 operator가 다를 수도 있는 문제점이 있었습니다.
- 이 부분은 calculate 버튼이 클릭되는 시점에 operand 가 append 되기전 inputList의 마지막 요소를 제거한 뒤 현재 화면에 출력되있는 operand를 다시 append 를 진행하였습니다.

```swift
    @IBAction func calculateButtonDidTap(_ sender: UIButton) {
           guard currentLabelText.isEmpty == false,
                 let operatorSign = OperatorLabel.text  else { return }
           inputList.removeLast()
           inputList.append(operatorSign)
           
           updateScrollView()
           inputList.append(currentLabelText)
           
           let calculate = inputList.reduce("") { current, next in current + " " + next}
           
    //...
       }
```
- 만약 정상적으로 inputList의 append 가 완료 되었다면 고차함수 `reduce` 를 이용해 하나의 String으로 합쳐주어 작업을 진행하였습니다.

### 4️⃣ 계산이 끝난 후 나온값을 연속해서 처리하기 위한 로직
- 하나의 연산의 끝나게 되면 결과값이 `operandsLabel` 에 출력이 됩니다. 하지만 결과값이 출력이 된 상태에서 operands 의 입력이 오게 된다면 결과값에 추가하는게 아닌 `새로운 입력값` 으로 처리를 진행해야 했기에 고민이 필요했습니다.
    - operands가 새로 들어올 때
    > 결과값이 사라지고 새로운 값이 화면에 출력됨
    - 결과값이 출력된 채로 operator가 들어올 때
    > 해당값을 inputList에 append 해야함
- 연산이 끝나게 되면 현재 유저가 어떤 값을 입력하고 있는지 판단하는 currentTextLabel에 공백을 주고 operatorButton 에서 operands의 판단 기준을 OperandsLabel로 잡는 방식으로 해결했습니다.

## 해결하지 못한점

### 1️⃣ NumberFormatter의 자릿수 제한
- 소수가 아닌 부분의 자릿수에 따라 소수의 자릿수가 유동적으로 변화 해야했기에 이 부분을 어떻게 해결해야 될지 잘 모르겠습니다 웡빙,,,

2023-02-04 07:55 UTC, wongbingg commented
안녕하세요 릴라 ☺️ step3 고생 많으셨습니다. 

## ✅ 고민했던 점에대해


### 1️⃣ 0이 계속해서 들어왔을 때의 오류처리

>- sender 의 currentTitle 로 버튼의 숫자를 받아온 뒤 해당 숫자가 0과 00일 경우에 조건문을 통해 오류처리를 진행 하였습니다.

순서도를 이용해 논리적으로 처리를 잘 해주셨네요 👍 좋은 습관인 것 같아요
 
### 2️⃣ 연산자 버튼의 오류처리
>- 제일 오랫동안 헤매던 부분이었습니다 😭
>- 연산자 버튼을 클릭했을 때 생각해야 했던 경우의 수는 다음과 같았습니다.
    > 1. OperandsLabel 에 아무값이 들어오지 않은 채 버튼이 눌렸을 때
    > 2. 연산자 버튼이 연속으로 눌렸을 때
 
 >- 1번의 경우 전역으로 OperandLabel 의 텍스트 값을 가지고 있는 CurrentLabelText 를 통해 값이 존재하지 않는 경우 연산자의 라벨만 입력값으로 교체한 뒤 리턴을 하는 방향으로 진행 했습니다.

 >- 2번의 경우 입력값을 연산자와 피연산자를 순서대로 보관하고 있는 inputList 를 통해 마지막 element 가 Operator 로 형변환이 가능한지를 판단하여 Operator일 경우 OperatorLabel 의 text 만 변경을 해준 뒤 return을 했습니다.

연산자 버튼에 대한 오류처리에 대해 고민 하셨네요 👍 오류케이스를 파악하는 것도 프로젝트 진행에서 중요한 요소라고 생각합니다. 가장 단순한 방법은 몽키테스트를 해보는 것이죠😂


### 3️⃣ 계산식을 만드는 로직
>- 계산식의 경우 operand 와 oprator 를 순서대로 보관하는 `inputList: [String]` 배열을 만들어 관리했습니다.
>- 요소를 `append` 하는 시점은 하나의 입력이 끝났다고 판단하는 `operatorButton` 의 클릭 시점으로 잡았습니다.
>- 하지만 이런식으로만 `append` 를 진행할경우 `마지막 1개의 operand` 가 화면에만 출력되고 배열에는 들어가지 않음으로 calculate 버튼이 눌렸을 때 화면에 출력되어있는 요소에 대해 append를 진행 하였습니다.
>- operator 의 경우에도 문제점이 있었는데 연산자가 `연속으로 클릭` 되었을 때 화면에 출력되있는 operator만 수정한뒤 return  하고 있었기에 inputList에 저장되있는 operator와 화면에 출력되있는 operator가 다를 수도 있는 문제점이 있었습니다.
>- 이 부분은 calculate 버튼이 클릭되는 시점에 operand 가 append 되기전 inputList의 마지막 요소를 제거한 뒤 현재 화면에 출력되있는 operand를 다시 append 를 진행하였습니다.

>- 만약 정상적으로 inputList의 append 가 완료 되었다면 고차함수 `reduce` 를 이용해 하나의 String으로 합쳐주어 작업을 진행하였습니다.

계산식을 만드는 경우에 대한 예외케이스 처리를 잘 해주셨네요 👍


### 4️⃣ 계산이 끝난 후 나온값을 연속해서 처리하기 위한 로직
>- 하나의 연산의 끝나게 되면 결과값이 `operandsLabel` 에 출력이 됩니다. 하지만 결과값이 출력이 된 상태에서 operands 의 입력이 오게 된다면 결과값에 추가하는게 아닌 `새로운 입력값` 으로 처리를 진행해야 했기에 고민이 필요했습니다.
    - operands가 새로 들어올 때
    > 결과값이 사라지고 새로운 값이 화면에 출력됨
    - 결과값이 출력된 채로 operator가 들어올 때
    > 해당값을 inputList에 append 해야함
>- 연산이 끝나게 되면 현재 유저가 어떤 값을 입력하고 있는지 판단하는 currentTextLabel에 공백을 주고 operatorButton 에서 operands의 판단 기준을 OperandsLabel로 잡는 방식으로 해결했습니다.

연속 계산을 위한 처리도 잘 해주셨네요 👍

## ✅ 해결하지 못한점에 대하여

### 1️⃣ NumberFormatter의 자릿수 제한
>- 소수가 아닌 부분의 자릿수에 따라 소수의 자릿수가 유동적으로 변화 해야했기에 이 부분을 어떻게 해결해야 될지 잘 모르겠습니다 웡빙,,,

이 부분은 코드를 보고 코멘트 남겨보도록 할게요 🧐

2023-02-04 08:31 UTC, wongbingg requested changes

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +final class ViewController: UIViewController {
final 처리를 잘 해주셨군요 👏

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        OperandsLabel.text = "0"
뷰 라이프사이클 메서드 내부는 메서드로 정리해서 넣어주는 습관을 주면 좋을 것 같아요
현재 OperandsLabel에 초기값 0을 대입하는 내용이니 setupInitialValue 같은 네이밍의 메서드로 만들어 여기서 실행시켜주면,
네이밍에서 어떤 역할을 하는지 명확하게 알 수 있을 것 같아요 🧐

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
- operands 영역이 탭 되었을 때 처리해주는 부분 이군요. 네이밍은 개인적으로 `operandsButtonTapped` 가 자연스러울 것 같아요
- 이 메서드 내에서 20자 입력제한에 대한 처리를 해줄 수 있을 것 같아요
- else if 구문에서 return 부분은 개행을 해주는 것이 더 자연스러울 것 같아요!
-

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +     }
- 46번 줄에서 operatorSign을 할당해주면 되지 않을까요 ?

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
내부에서 stackView , Label 두개의 생성코드가 들어가 있어 하나의 메서드가 너무 커진 것 같아요. 메서드 분리를 통해 stackView를 생성하는 메서드, Label을 생성하는 메서드로 나누어 적절한 파라미터를 설정해주면 좋을 것 같아요

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
UI 요소의 네이밍은 보통 `let operandsLabel = UILabel()` `let mainStackView = UIStackView()` 처럼 클래스명의 UI 뒤에 이름을 같이 붙여주어야 구분하기 좋다고 생각해요.

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +           }
- 92 번 줄에서 in 뒤에는 개행을 해주는 것이 좋을 것 같아요

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +           }
- calculate 라는 상수가 어떤 상수인지 명확하게 네이밍을 해주면 좋을 것 같아요

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +           }
하나의 메서드가 너무 길어 파악이 잘 안되는 것 같아요. 메서드 분리를 해주면 좋을 것 같아요

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
AC 버튼에 대한 정의를 잘 해주셨네요 👏

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
CE 버튼에 대한 정의를 잘 해주셨네요 👏

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
+/- 버튼에 대한 정의를 잘 해주셨네요 👏

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
첫번째 조건과 2,3 번째 조건은 다르다고 생각하는데 else if 로 연결해주신 이유가 있을까요? 
```suggestion
        guard currentLabelText.isEmpty == false else {
            currentLabelText = "0."
            OperandsLabel.text = currentLabelText
        }
         
        if isDotClicked == false {
            currentLabelText += "."
            OperandsLabel.text = currentLabelText
            isDotClicked = true
        } else if isDotClicked == true {
            return
        }
```

이렇게 조건을 구분해주면 좋을 것 같아요

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Model/Operator.swift
> +    case multiply = "×"
스토리보드 상 나와있는 문자열로 교체 해주셨네요 👏

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
- 숫자에 numberFormatter를 적용해주는 메서드군요 👍

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
- 164번째 줄에서 } 앞에 공백이 빠진 것 같아요

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
- result 라는 네이밍보다는 formattedNumber 이런 식으로 명확한 네이밍을 해주면 좋을 것 같아요

2023-02-04 08:31 UTC, wongbingg commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
쉼표를 제거해주는 메서드 같네요. 이 방법도 좋지만, 문자열을 다룰 때 자주 사용되는 `replacingOccurences` 라는 메서드도 알아보시면 좋을 것 같아요 🧐

2023-02-05 12:45 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
25388cd6dc902f30ace3b5d857fada21b319835d

이런 메서드가 있었군요! 적용시켜보았습니다!

2023-02-05 12:45 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
수정완료 했습니다!

2023-02-05 12:46 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        }
상황에 따라 세가지중 하나의 결과만 있을거라 생각하고 다른 조건임에도 한번에 이어서 쓴 것 같습니다! 수정했습니다!

2023-02-05 12:48 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +           }
Parse 가 되기전의 계산식임을 알려주기위해 `formulaBeforeParse` 로 변경했습니다

2023-02-05 12:54 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
d7b994e4fff4e7ca567e560ccebe2ac1997afbe4

UI를 생성하는 부분은 따로 메서드를 만들어 기능을 분리 시켜두었습니다!

2023-02-05 13:02 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +        OperandsLabel.text = "0"
a13c6add304ec9c4b345244e4c75f0dc95d5b643

유념하겠습니다 웡빙!

2023-02-05 13:56 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +    }
수정했습니다!

2023-02-05 14:19 UTC, juun97 commented on Calculator/Calculator/Controller/ViewController.swift
> +           }
943ae61981b9c8b58bfd2523d7000d14742793d7

일단 분리를 시도 해보긴 했는데 UI 변경하는 부분을 분리한쪽에 맡기는게 어색해보여서 그런지 정작 코드 길이가 많이 줄어들진 않았네요,,!

2023-02-05 23:47 UTC, wongbingg commented
피드백에 대한 부분이 잘 적용 되었네요 👍 계산기 프로젝트 step3 까지 고생하셨습니다.
추후 리팩토링을 진행하실 때는 숫자 20개 제한도 적용 해보시면 좋을 것 같아요. 그리고 큰 수 곱하기를 시도하면 오류가 발생하는데 이 부분도 에러처리를 해주면 좋을 것 같아요.
다음 프로젝트도 화이팅입니다 💪

2023-02-05 23:47 UTC, merged