계산기2 [STEP2] 레옹아범, brody
yagom-academy/ios-calculator-app pull request #469
Opened 2023-02-08 08:28 UTC by seunghyunCheon

안녕하세요 @Judy-999 
계산기2 STEP2 PR작성합니다
잘 부탁드립니다!😄

## UML
<img src="https://user-images.githubusercontent.com/70146658/217475262-4c430600-2c71-4880-a21f-ca8aa7748010.png"/>

## 코드 설명
`CalculatorChecker`
- `enteringNumber`: 입력중인 피연산자를 담은 변수
- `calculationExpression`: 피연산자와 연산자를 담은 계산표현식
- `labelUpdateClosure`: `viewController`의 라벨을 업데이트하기위한 클로저 프로퍼티
- `hasCurrentInput`: `enteringNumber`에 값이 있는지를 알려주는 Bool타입 계산 프로퍼티
- `hasDot`: `enteringNumber`에 `.`이 있는지를 알려주는 Bool타입 계산 프로퍼티
----
- `appendingNumber(_ numberPad: String)`: 피연산자를 추가하는 메서드
- `appendingExpression(_ operatorText: String, _ operandText: String)`: 피연산자와 연산자를 표현식에 추가하는 메서드
- `appendingZero(_ zeroPad: String)`: `0`을 추가하는 메서드
- `appendingDot()`: `.`을 추가하는 메서드
- `changeSign()`: 부호를 변환하는 메서드
- `calculate(_ operatorText: String)`: 표현식을 계산하는 메서드
- `isZero(_ currentText: String) -> Bool`: `0`인지 판단하는 메서드
- `initialState()`: 모든 상태를 초기화하는 메서드
- `initialEnteringNumber()`: 입력중인 값을 초기화하는 메서드

### `UILabel`업데이트
계산기의 핵심로직들을 `CalculatorChecker`가 다루고있기 때문에 단순히 반환값을 줘서 `ViewController`에 있는 `UILabel`을 업데이트하는 것은 디테일한 구현을하는데 한계가 있었습니다.

이를 해결하기 위해 `labelUpdateClosure`이름의 클로저 프로퍼티를 생성하고 `CalculatorChecker`내부의 실제 입력되는 숫자가 변경될 때마다 `labelUpdateClosure`를 실행해 `ViewController`에서 업데이트할 수 있게 만들었습니다.

```swift
// CalculatorChecker.swift
struct CalculatorChecker {
    private(set) var enteringNumber = Sign.empty {
        didSet {
            labelUpdateClosure(enteringNumber)
        }
    }
    init(updateClosure closure: @escaping (String) -> Void) {
        self.labelUpdateClosure = closure
    }
}

// CalculatorViewController.swift
override func viewDidLoad() {
    super.viewDidLoad()
    calculatorChecker = CalculatorChecker(updateClosure: { enteringNumber in
        self.enteringNumberLabel.text = enteringNumber == Sign.empty ? Sign.zero : enteringNumber
    })
    // something...
}
```

## 고민했던 점 && 조언을 얻고 싶은 점

### 클로저의 ARC
![](https://i.imgur.com/YHYS2Xd.png)

* 현재 `CalculatorChecker` 타입은 `CalculatorViewController`를 캡처한 클로저를 가지고 있습니다
* 이 부분에서 `calculatorChecker`타입은 클로저를 참조하고 있고 클로저는 `ViewController`를 캡처하고 있으므로 참조한다고 생각하여 위와 같은 구조를 가진다고 생각하였습니다
* 공부하면서 느낀것으로는 각각 참조타입이 서로를 참조하고 있지 않는 한 강한참조 문제가 발생하지 않는다고 생각합니다
* 그렇기 때문에 강한 참조 문제가 발생하지 않는다고 생각하여 `weak`, `unowned`를 써주지 않았습니다

### 클로저의 할당 방법
```swift
struct CalculatorChecker {
    private var labelUpdateClosure: (String) -> Void
    
    init(updateClosure closure: @escaping (String) -> Void) {
        self.labelUpdateClosure = closure
    }
}
```
* 현재 `init`을 사용해서 클로저를 `CalculatorChecker`에 넘겨주면서 인스턴스를 생성하고 있습니다
* 클로저를 특정 변수에 할당하거나 사용할 때 `init`부분에 사용하여도 괜찮은지? 아니면 인스턴스 생성 후 다른 시점에서 클로저를 할당해야하는지가 궁금합니다

2023-02-09 04:58 UTC, Judy-999 requested changes
레옹아범, brody 수고하셨어요 🙌
벌써 계산기 대장정의 마지막이네요!
여러 오류사항을 잡아내신건 물론, 구조적인 시도를 하셔서 아주 좋습니다 👍👍
<br>

## 고민했던 점 && 조언을 얻고 싶은 점
### 클로저의 ARC
> - 현재 CalculatorChecker 타입은 CalculatorViewController를 캡처한 클로저를 가지고 있습니다
> - 이 부분에서 calculatorChecker타입은 클로저를 참조하고 있고 클로저는 ViewController를 캡처하고 있으므로 참조한다고 생각하여 위와 같은 구조를 가진다고 생각하였습니다
> - 공부하면서 느낀것으로는 각각 참조타입이 서로를 참조하고 있지 않는 한 강한참조 문제가 발생하지 않는다고 생각합니다
> - 그렇기 때문에 강한 참조 문제가 발생하지 않는다고 생각하여 weak, unowned를 써주지 않았습니다

설명해주신 구조 상에서는 그럴 수 있지만 우선 **CalculatorViewController**과 **Closure**의 관계에서 **Closure** 내부에서 **CalculatorViewController**를 `self`로 참조하고 있기 때문에 순환참조가 발생할 수 있습니다. 

`Closure 순환 참조`, `Closure weak self`와 같은 키워드로 알아보시면 좋겠네요 🙂
<br>

### 클로저의 할당 방법
> - 현재 init을 사용해서 클로저를 CalculatorChecker에 넘겨주면서 인스턴스를 생성하고 있습니다
> - 클로저를 특정 변수에 할당하거나 사용할 때 init부분에 사용하여도 괜찮은지? 아니면 인스턴스 생성 후 다른 시점에서 클로저를 할당해야하는지가 궁금합니다

현재 사용하신 구조가 MVVM에서 데이터를 바인딩하는 것과 아주 유사하네요 😮👍
아직은 생소한 개념이실거라 데이터가 변경되면 UI가 업데이트 되도록하는 법이라고만 생각해두셔도 됩니다.

보통 값이 변하는지 지켜보다가 closure를 실행하는 `Observable`이라는 타입을 구현해서 사용하곤 합니다. [didSet과 closure를 통한 데이터 바인딩](https://sujinnaljin.medium.com/swift-didset%EA%B3%BC-closure%EB%A5%BC-%ED%86%B5%ED%95%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B0%94%EC%9D%B8%EB%94%A9-5a610d28c220) 참고로만 봐주세요! 

해당 구조를 보면 closure를 옵셔널로 가지도록 합니다. init으로 넣어주셔도 좋지만 그로 인해 
`private var calculatorChecker: CalculatorChecker?` 이렇게 `calculatorChecker`를 옵셔널로 들고 있기도 하고, 클로저 없이는 **CalculatorChecker**로 연산작업을 진행할 수 없으니 위 링크 참고하셔서 closure를 옵셔널로 두고 메서드로 할당하는 방식이 좋을 것 같습니다!

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        enteringOperatorLabel.text = Sign.empty
두 줄이라도 메서드로 분리해서 초기화한다는 의미를 나타내면 좋을 것 같아요~

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +            self.enteringNumberLabel.text = enteringNumber == Sign.empty ? Sign.zero : enteringNumber
한 눈에 보고 어떤 코드인지 바로 파악하기 어려워보여요.
조건문으로 분리하거나 괄호로 분리해서 표시하는게 좋겠습니다!
```suggestion
            self.enteringNumberLabel.text = (enteringNumber == Sign.empty) ? Sign.zero : enteringNumber
```

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +              calculatorChecker?.enteringNumber != Sign.space else { return }
`calculatorChecker?.enteringNumber`을 `Sign.space ` 또는 `Sign.empty`와 비교하는 구문이 많아 보이는데 `calculatorChecker`의 `enteringNumber`를 직접 접근하기 보다 연산 프로퍼티로 가지고 있거나, 값을 비교하는 메서드를 이용하는 방법은 어떤가요? 👀

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorChecker.swift
>  struct CalculatorChecker {
이제 단순히 체크하는 기능을 넘어 전반적인 연산을 담당하고 있으니 이를 내포하는 이름으로 변경해주세요!

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorChecker.swift
>      }
전 개인적으로 연산 프로퍼티는 연산 프로퍼티들끼리 두는게 보기 편했습니다 🙂

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorChecker.swift
> +    mutating func appendingNumber(_ numberPad: String) {
저는 대부분에 메서드가 `mutating`해야 한다면 class를 고려해보는 편입니다 🤔

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorChecker.swift
> +        }
**CalculateViewController**의 메서드에서 ` guard` 조건을 처리하는 경우도 있고, **CalculatorChecker**의 메서드에서도 `guard`를 가지기도 하는데 어떤 차이가 있나요?

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/Calculator/Model/Formula.swift
>          }
어떤 경우를 처리하는 코드인가요?

2023-02-09 04:58 UTC, Judy-999 commented on Calculator/CalculatorCheckerTest/CalculatorCheckerTest.swift
> +        // given
`test_initialState호출시_입력한연산식들이_초기화된다`라는 테스드도 있는데 `calculationExpression`이 `입력한연산식`인 것이 맞을까요? 통일해서 표현해주세요!

또한 개인적으로 테스트 결과로 `EnteringNumber`나 `calculationExpression` 같은 변수명보다는 어떤 요구사항인지 드러나는게 좋다고 생각해요. 다른 테스트의 결과로 작성해주신 `현재_값이_음수라면_양수가_된다` 처럼요 🙂

2023-02-09 07:08 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +              calculatorChecker?.enteringNumber != Sign.space else { return }
연산 프로퍼티로 수정했습니다!

2023-02-09 07:15 UTC, seunghyunCheon commented on Calculator/Calculator/Model/CalculatorChecker.swift
>  struct CalculatorChecker {
`CalculatorProcessor`로 수정했습니다!

2023-02-09 07:57 UTC, seunghyunCheon commented on Calculator/Calculator/Model/CalculatorChecker.swift
> +        }
`CalculatorViewController`에서는 사용자 입력을 제어하기 위한 용도로 `guard`를 사용했고 `CalculatorChecker`에서는 계산식에 대한 조건을 처리하기 위해 많이 사용했습니다.

2023-02-09 08:08 UTC, seunghyunCheon commented on Calculator/Calculator/Model/Formula.swift
>          }
처음에 입력값이 존재하지 않을때 연산자와 피연산자만 입력했을때 화면에 보여지는 0과 연산이 되어야한다고 생각해서 해당 부분을 처리하는 코드를 넣었습니다!

2023-02-09 08:11 UTC, fatherLeon commented on Calculator/Calculator/Model/CalculatorChecker.swift
> +    mutating func appendingNumber(_ numberPad: String) {
* 복잡한 구조체일 경우 인스턴스를 여러개 만들 경우 메모리 낭비도 심하며,
* mutating을 해주었을 때 같은 프로퍼티에 동시에 접근한다면 오류가 발생할 가능성도 있다고 찾게되어 class로 변경하였습니다

2023-02-09 09:09 UTC, seunghyunCheon commented
<img src="https://i.imgur.com/8ldUJuA.png" width="300"/>

* `Observable` 클래스를 추가한 이후에 힙 영역에 존재하는 인스턴스들을 위 그림처럼 그려봤습니다. 
* `ViewController`에서 `subscribe`를 할 때 클로저 인스턴스를 전달하면서 클로저를 참조하게 되고, 클로저는 `ViewController.enteringNumberLabel`을 참조하고 있기 때문에 강한순환참조가 일어날 수 있다고 생각해 클로저에서 `[weak self]`를 사용했습니다.

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    calculatorProcessor.enteringNumberObservable.subscribe { [weak self] enteringNumber in
        self?.enteringNumberLabel.text = (enteringNumber == Sign.empty) ? Sign.zero : enteringNumber
        }
    initializeLabel()
}
```

저희가 이해한 게 맞을까요?

2023-02-09 09:39 UTC, Judy-999 commented on Calculator/Calculator/Model/Observable.swift
> +
`Observable`을 구현하셨네요 👍
현재는 label을 업데이트하기 위해 사용되지만 `CalculateObservable`이 아니라 범용적인 객체니 클로저의 네이밍도 범용적인게 좋겠습니다!

2023-02-09 09:47 UTC, Judy-999 approved these changes
> - Observable 클래스를 추가한 이후에 힙 영역에 존재하는 인스턴스들을 위 그림처럼 그려봤습니다.
> - ViewController에서 subscribe를 할 때 클로저 인스턴스를 전달하면서 클로저를 참조하게 되고, 클로저는 ViewController.enteringNumberLabel을 참조하고 있기 때문에 강한순환참조가 일어날 수 있다고 생각해 클로저에서 [weak self]를 사용했습니다.

네네 맞습니다 👍 `ViewController`에서 클로저를 사용할 때는 순환 참조를 유의해야 하는데요. 모든 상황에서 반드시 발생하는 것은 아니지만 가능한 챙겨주는게 좋습니다 🙌

여러 방면으로 탄탄한 계산기를 구현하신 것 같네요 👏👏 수고하셨습니다 😊

2023-02-09 09:47 UTC, Judy-999 commented on Calculator/Calculator/Model/CalculatorProcessor.swift
> +class CalculatorProcessor {
상속되지 않는 클래스는 `final` 챙겨주세요 🙂

2023-02-09 09:47 UTC, Judy-999 commented on Calculator/Calculator/Model/Observable.swift
> +    var labelUpdateClosure: ((T) -> Void)?
`Observable`을 구현하셨네요 👍
현재는 label을 업데이트하기 위해 사용되지만 `CalculateObservable`이 아니라 범용적인 객체니 클로저의 네이밍도 범용적인게 좋겠습니다!

2023-02-09 09:47 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
코드 길이가 길기도 하고 `subscribe`할 때 개행하는 컨벤션도 있습니다~ 참고만 해주세요 👀
```swift
calculatorChecker.enteringNumberObservable
    .subscribe { [weak self] enteringNumber in
        self?.enteringNumberLabel.text = (enteringNumber == Sign.empty) ? Sign.zero : enteringNumber
    }
```

2023-02-09 09:47 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
행당 코드 역시 메서드로 분리해도 좋겠네요! 데이터와 bind하는 역할이라 `bind()`로 네이밍하곤 합니다~

2023-02-10 06:21 UTC, fatherLeon commented on Calculator/Calculator/Model/Observable.swift
> +    var labelUpdateClosure: ((T) -> Void)?
```swift
var closure: ((T) -> Void)?
```
* `Observable`이라는 이름이 관찰하고 해당 변수 값이 바뀔 때마다 클로저가 호출 되기 때문에 좀 더 범용성 있는 `closure`라는 이름으로 변경하였습니다

2023-02-10 08:39 UTC, seunghyunCheon commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
`bind()`가 `rxcocoa`에서 사용하는 메서드를 의미하는 걸까요? 아니면 `subscribe`대신에 `bind`라는 네이밍을 사용한다는 말씀이신가요?

2023-02-10 08:48 UTC, Judy-999 commented on Calculator/Calculator/Controller/CalculatorViewController.swift
> +        }
`rxcocoa`에서도 `bind` 메서드가 있는데요! 그와 비슷한 역할을 하는 코드라 `bind`라는 네이밍을 추천해드린겁니다 🙂

2023-02-10 08:51 UTC, Judy-999 approved these changes
계산기 마무리 축하드려요 👏👏🥳
수고하셨어요 😊 앞으로도 화이팅입니다~🙌

2023-02-10 08:51 UTC, merged