계산기2 [STEP2] Harry, Goat
yagom-academy/ios-calculator-app pull request #475
Opened 2023-02-09 08:03 UTC by HarryHyeon

@llingo 
안녕하세요 링고!
스텝2 마무리를 하고 PR 요청드립니다.
이번 스텝도 잘 부탁드리겠습니다 👍 

## 고민한 점

### 계산수식을 관리해주는 타입 분리
* 각각의 버튼 IBAction에서 처리하는 조건이 많다보니 코드를 이해하기가 어려운 문제가 있었습니다.
* 버튼의 입력에 따른 조건을 검사하는 부분과 최종 계산수식을 관리하는 새로운 타입`InputManager`을 만들어 해당 부분을 처리하도록 분리하였습니다.

```swift
final class InputManager {
    var expression = ""
    var currentNumber = "0"
    var currentOperator = ""
    var isCalculated: Bool = false
    
    func handleNumbers(input: String) -> String {}
    func handleDotSign(input: String) -> String {}
    func handleHundredNumber(input: String) -> String {}
    func handleConvertSign() -> String {}
    func handleOperator() -> (operatorText: String, operandText: String) {}
    func handleResultExpression() -> String {}
    func convertToFormattedString(number: String) -> String {}
    func clearInputManager() {}
```

## 조언을 얻고 싶은 점
### InputManager 파일의 위치
- InputManager는 최종 계산 수식을 관리해주는 객체입니다. 버튼 입력에 따라 조건식으로 수식에 추가할지 안할지 판단을 해주고 최종적으로 계산할 수식을 완성시켜줍니다.
- 현재 Model 폴더에 위치하고 있는데, 뭔가 Model 폴더에 있는 것이 어색한 느낌이 들어서 어떤 폴더에 InputManager 파일을 넣는것이 좋을까요?

2023-02-09 13:06 UTC, llingo requested changes
안녕하세요 Harry, Goat
계산기 II 프로젝트 STEP 2 수고하셨습니다 :)

---

> 안내사항은 참고용으로 남겨두었습니다.

1. **PR을 보내기 전에는 3가지를 확인해주세요.**
    - `캠핑사이트 - Course - Pull Request 보낼 때` 글을 꼭 확인해주세요.
    - `yagom-academy:main`로 보내고 있는 것은 아닌 지 확인해주세요.
    - 이전 STEP이 Merge된 후 다음 STEP의 PR을 보내주세요.
2. **PR 수정 코멘트에는 P1 - P3의 중요도를 남겨두었습니다. 중요하지 않는 경우 확인했다는 이모지만 남기셔도 됩니다.**
    - [P1] 무조건 수정이 필요합니다.
    - [P2] 다음 스탭에서 수정해도 됩니다.
    - [P3] 꼭 반영하지 않고 참고만 해도 됩니다.
3. **PR 처럼 수정 후에도 DM를 남겨주시면 빠르게 확인하겠습니다.**

---

**Q1. InputManager 파일의 위치**
> InputManager는 최종 계산 수식을 관리해주는 객체입니다. 버튼 입력에 따라 조건식으로 수식에 추가할지 안할지 판단을 해주고 최종적으로 계산할 수식을 완성시켜줍니다. 현재 Model 폴더에 위치하고 있는데, 뭔가 Model 폴더에 있는 것이 어색한 느낌이 들어서 어떤 폴더에 InputManager 파일을 넣는것이 좋을까요?

A1. InputManager의 경우 ViewController에서 받은 이벤트, 텍스트를 Model을 거쳐 다시 ViewController로 전달하여 표시하기 위한 중간다리 역할을 하고 있어보여요.
특히 InputManager는 Model를 의존하고 있기 때문에 `Model - (InputManager) - ViewController` 형태라고 생각합니다.

> 마치 MVVM 구조의 ViewModel 느낌이네요 👀

그렇다고 Model이라고 하기에는 애매한 느낌이 있습니다. 
개인적으로는 InputManager는 ViewController를 캡슐화한 느낌이 강하다고 생각이 들어 Controller 폴더에 있는 것이 좋지 않을까 생각되네요. 

---

Harry, Goat 3주간 고생하셨습니다 👏 
다음 주부터 방학이라고 하네요 😎 
방학동안 충분한 휴식과 여유가 되신다면 계산기 프로젝트뿐만 아니라 앞선 프로젝트에서 공부하셨던 내용을 잘 복습해두시면 남은 캠프 생활을 잘 수행해내실 거라고 생각합니다!

추가적으로 프로젝트 마감일까지 아직 하루가 남았네요 :)
실제 아이폰 계산기 버튼은 둥근 형태인데 어떻게 하면 사각형에서 원형으로 바꿀 수 있을까요?

혹시 코드 커버리지 확인하는 방법 아시나요. 여유가 있으시다면 엣지 케이스에 대해 
테스트 케이스를 더 추가해보면 좋은 경험이 될 것 같아요.

코멘트 확인하시고 DM 남겨주시면 바로 Merge 진행할게요
두분 모두 수고하셨습니다.
다음 프로젝트도 화이팅입니다. 🎉

2023-02-09 13:06 UTC, seu0313 commented on Calculator/Calculator/Contorller/CalculatorViewController.swift
> +class CalculatorViewController: UIViewController {
의미있는 네이밍으로 변경해주셨네요 👍

2023-02-09 13:06 UTC, seu0313 commented on Calculator/Calculator/Contorller/CalculatorViewController.swift
> +    @IBOutlet weak var historyStackView: UIStackView!
[P1] `scrollView`라는 네이밍 만으로는 어떤 곳에서 사용되는지 파악하기 힘든 것 같아요. 명확한 이름으로 변경해보면 좋을 것 같습니다 :)

2023-02-09 13:06 UTC, seu0313 commented on Calculator/Calculator/Contorller/CalculatorViewController.swift
> +              inputManager.currentNumber.last != "." else { return }
guard 문 사이에 개행을 해두셔서 읽기 편하네요 좋습니다 💯

2023-02-09 13:06 UTC, seu0313 commented on Calculator/Calculator/Model/InputManager.swift
> +final class InputManager {
기존 ViewController에 몰려있던 기능을 분리해주신 점 매우 좋습니다 👍
ViewController가 가벼워지고 가독성이 좋아졌네요 :)
 
이처럼 ViewController, View는 `사용자 이벤트`나 `UI 표시`만을 담당하도록하고 
Model로부터 가져온 데이터를 가공하는 로직을 객체로 분리하면 개발하고 관리하는 데도 편리해지겠네요! 👏

2023-02-09 13:06 UTC, seu0313 commented on Calculator/Calculator/Model/InputManager.swift
> +        }
[P3] 아래 코드처럼도 할 수 있습니다 :) 꼭 수정할 필요는 없습니다!

```suggestion
        if !currentNumber.contains(".") {
            currentNumber += input
        }
        
        return currentNumber 
```

2023-02-09 13:06 UTC, seu0313 commented on Calculator/Calculator/Model/InputManager.swift
> +    }
[P3] 이 부분도 아래와 같이 변경할 수 있겠네요 :)
```suggestion
    func handleHundredNumber(input: String) -> String {
        if currentNumber != "0" {
            currentNumber += input
        }
        
        return currentNumber
    }
```

2023-02-10 01:46 UTC, Goatt8 commented on Calculator/Calculator/Model/InputManager.swift
> +        }
넵 위와같이 수정했습니다 감사합니다ㅎ

2023-02-10 01:46 UTC, Goatt8 commented on Calculator/Calculator/Model/InputManager.swift
> +    }
넵 좋습니다! 수정했습니다

2023-02-10 01:47 UTC, HarryHyeon commented on Calculator/Calculator/Model/InputManager.swift
> +        }
,넵 링고가 추천해주신 작성 방법이 더 읽기 쉬운것 같아서 수정했습니다 👍

2023-02-10 01:48 UTC, HarryHyeon commented on Calculator/Calculator/Model/InputManager.swift
> +    }
이 부분도 마찬가지로 수정하였습니다 !!

2023-02-10 01:49 UTC, Goatt8 commented on Calculator/Calculator/Contorller/CalculatorViewController.swift
> +    @IBOutlet weak var historyStackView: UIStackView!
scrollView -> historyScrollView 네이밍으로 수정했습니다!

2023-02-10 01:56 UTC, Goatt8 commented
button커스텀 말씀해주신부분은
별도의 커스텀 class( RoundButton )로 conrnerRadius를 줘서 클래스를 연결하는 방식으로 해결해봤습니다!

2023-02-10 02:26 UTC, llingo approved these changes
Harry, Goat 계산기 II 프로젝트동안 수고하셨습니다 :)
다음 프로젝트도 화이팅입니다. 🎉

2023-02-10 02:26 UTC, llingo commented on Calculator/Calculator/Contorller/CalculatorViewController.swift
> +    @IBOutlet weak var historyScrollView: UIScrollView!
네이밍을 변경해주셨군요 좋습니다 👍

2023-02-10 02:26 UTC, llingo commented on Calculator/Calculator/View/RoundedButton.swift
> +}
커스텀 Button을 구현해주셨네요 👍

2023-02-10 02:28 UTC, merged