계산기 [STEP 1] maxhyunm
yagom-academy/ios-calculator-app pull request #481
Opened 2023-05-30 10:12 UTC by maxhyunm

@jsa0224
안녕하세요 솜!
우여곡절 끝에 계산기 첫 PR을 올려드립니다.
이번 스텝은 진행하면서 정말 많은 고민이 있었는데 끌어안고 있기보다는 한 번 완성하여 올려보자는 마음으로 진행했습니다...!
고민했던 내용들도 함께 정리해 보았습니다.
그럼 리뷰 잘 부탁드립니다!!🙇‍♀️

## 진행 내용
### UML
![](https://hackmd.io/_uploads/S17HjL78h.jpg)
[UML 파일](https://hackmd.io/_uploads/S17HjL78h.jpg)

### QUEUE 구현
- 처음에는 Array를 활용하여 간단히 구현해보려 했지만, QUEUE 작업에 있어서 Array의 데이터 형태가 잘 맞지 않는다는 생각이 들었습니다. (Array의 경우 인덱스를 통해 첫 번째 값에 접근하여 선입선출을 적용할 수는 있지만, 그렇게 하면 내부 요소들이 dequeue 작업을 할 때마다 인덱스를 하나씩 앞으로 이동해야 해서 시간복잡도가 올라가는 것으로 알고 있습니다!) 반면 링크드 리스트는 객체가 많이 생성되어야 해서 공간복잡도가 올라갈 수 있다는 단점이 있긴 하지만, 계산기에서 그렇게까지 많은 양의 객체가 생성될 일은 없을 것으로 생각되어 링크드 리스트를 구현하기로 결정했습니다. 
- 양방향 리스트를 구성하였다가 중간에 단방향으로 변경하였는데, 그 이유는 계산기에서 반대로 값을 찾을 일이 없다고 판단되었기 때문입니다!
- 링크드 리스트는 배열이 들어갈 Queue 타입 내부에 Node 타입의 class 인스턴스를 참조할 수 있게끔 작업하였습니다.
- 관련 메서드들은 보통 외부에서 접근할 수 있어야 하는 내용으로 생각되어 접근제어를 따로 추가하지 않았고, 변수에는 private(set)으로 읽기 전용 제어를 추가했습니다.
- Queue타입은 딱히 참조값이 필요없을 것 같아서 struct로, 그리고 내부 노드는 반드시 참조를 해야 하므로 class로 구현했습니다.
### 타입 익스텐션
- 요구사항에 큐 내부 요소는 CalculateItem 프로토콜로 구현을 하라는 부분이 있었는데, 빈 프로토콜 타입으로는 테스트가 어려워서 Int, Double, String의 extension을 만들어 해당 프로토콜을 준수하도록 만들었습니다.
### 연산 로직 구현
- 요구사항에 포함된 내용인지 아닌지 잘 파악이 안 되어서ㅠㅠ 일단 전체 쌓인 큐를 한번에 연산하는 로직도 간단히 추가해 두었습니다. 이에 따라 CalculateItem 타입을 계산 가능한 형태로 캐스팅하는 절차가 필요해져서, Node 타입 내부에 value를 캐스팅하는 메서드를 두 가지 생성했습니다. 
- 연산 타입을 OperatorType이라는 enum으로 작성하여, 각 연산자에 따른 연산식을 formula라는 연산 프로퍼티로 받아 활용할 수 있도록 작성했습니다.

## 고민했던 점
### TDD
- TDD를 기반으로 진행하려고 최대한 노력했지만 작업을 하다보니 수정할 내용이 생기고, 그럼 기존에 작성했던 테스트도 바뀌어야 해서 오히려 반대로 코드 리팩토링 -> 테스트 수정 -> 다시 테스트 순서로 작업을 한 부분도 제법 많았습니다ㅠㅠ 이런 과정을 최소화하려면 작업 전에 설계가 완벽히 끝나야 할 것 같다는 생각이 드는데, 사실 완벽한 설계라는 것은 없지 않나라는 생각도 들어서(너무 근본적인 문제네요ㅠㅠ) 고민이 많았습니다. TDD 작업하실때 이런 부분을 최소화할 수 있는 팁 같은 게 있을까요ㅠㅠ?
### 타입캐스팅(다운캐스팅)
- 위에 작성한 대로 CalculateItem 타입을 계산하고 비교하기 위해 메서드를 따로 생성해 두었는데, 이 형태가 그리 깔끔해보이지가 않아서 많이 고민했습니다. 솜이라면 어떤 식으로 작업하셨을지 궁금합니다!
### subscript 활용
- 프로젝트에 있어 필요한 내용은 아니지만, 새로운 리스트 타입을 만들어보는 김에 subscript도 활용해보고 싶었는데요...! subscript에서는 예외를 던질 수 없게 되어 있는 것을 확인했습니다! 그렇다면 만약 subscript로 전달받은 인덱스가 전체 길이를 넘어서는 경우에는 단순히 nil을 반환시켜야 하는 걸까요? 더 좋은 방법이 있을지 궁금합니다! (이 부분은 고민 끝에 그냥 제거하고 진행했습니다)

2023-05-30 15:11 UTC, jsa0224 requested changes
안녕하세요, 맥스!
2주 동안 맥스의 리뷰를 맡은 솜입니다😊
전반적으로 고민하신 흔적이 많이 보이는 프로젝트네요!
커밋 분기도 너무 좋습니다👍
캠프 사이트에 명시된 Step 1은 `Queue`의 구현과 테스트인데, 계산 기능까지 넣으셔서 좀 의아했습니다🤔
이 부분은 디엠이나 라이브로 자세하게 말씀드릴게요.

## 진행 내용에 대한 코멘트
> ### QUEUE 구현
> - 처음에는 Array를 활용하여 간단히 구현해보려 했지만, QUEUE 작업에 있어서 Array의 데이터 형태가 잘 맞지 않는다는 생각이 들었습니다. (Array의 경우 인덱스를 통해 첫 번째 값에 접근하여 선입선출을 적용할 수는 있지만, 그렇게 하면 내부 요소들이 dequeue 작업을 할 때마다 인덱스를 하나씩 앞으로 이동해야 해서 시간복잡도가 올라가는 것으로 알고 있습니다!) 반면 링크드 리스트는 객체가 많이 생성되어야 해서 공간복잡도가 올라갈 수 있다는 단점이 있긴 하지만, 계산기에서 그렇게까지 많은 양의 객체가 생성될 일은 없을 것으로 생각되어 링크드 리스트를 구현하기로 결정했습니다.
> - 양방향 리스트를 구성하였다가 중간에 단방향으로 변경하였는데, 그 이유는 계산기에서 반대로 값을 찾을 일이 없다고 판단되었기 때문입니다!
> - 링크드 리스트는 배열이 들어갈 Queue 타입 내부에 Node 타입의 class 인스턴스를 참조할 수 있게끔 작업하였습니다.
> - 관련 메서드들은 보통 외부에서 접근할 수 있어야 하는 내용으로 생각되어 접근제어를 따로 추가하지 않았고, 변수에는 private(set)으로 읽기 전용 제어를 추가했습니다.
> - Queue타입은 딱히 참조값이 필요없을 것 같아서 struct로, 그리고 내부 노드는 반드시 참조를 해야 하므로 class로 구현했습니다.

- 단방향 리스트와 양방향 리스트의 차이점이 무엇인가요? 
- 읽기 전용 제어에 관련된 코멘트는 아래에 남기도록 하겠습니다.

## 고민했던 점에 대한 답변
> ### TDD
> - TDD를 기반으로 진행하려고 최대한 노력했지만 작업을 하다보니 수정할 내용이 생기고, 그럼 기존에 작성했던 테스트도 바뀌어야 해서 오히려 반대로 코드 리팩토링 -> 테스트 수정 -> 다시 테스트 순서로 작업을 한 부분도 제법 많았습니다ㅠㅠ 이런 과정을 최소화하려면 작업 전에 설계가 완벽히 끝나야 할 것 같다는 생각이 드는데, 사실 완벽한 설계라는 것은 없지 않나라는 생각도 들어서(너무 근본적인 문제네요ㅠㅠ) 고민이 많았습니다. TDD 작업하실때 이런 부분을 최소화할 수 있는 팁 같은 게 있을까요ㅠㅠ?

이 부분은 나중에 UI 작업하면서 어느 정도 해결될 수 있는 문제라고 생각이 듭니다. 
저는 보통 real test는 시뮬레이터와 함께 하기 때문에, 어느 정도 수정을 마치고 테스트로 넘어가서 비교적 이런 문제는 적었던 거 같아요.
완벽한 설계가 없다는 말에 깊히 공감합니다...🥺

> ### 타입캐스팅(다운캐스팅)
> - 위에 작성한 대로 CalculateItem 타입을 계산하고 비교하기 위해 메서드를 따로 생성해 두었는데, 이 형태가 그리 깔끔해보이지가 않아서 많이 고민했습니다. 솜이라면 어떤 식으로 작업하셨을지 궁금합니다!

이 부분은 추후에 나오는 스탭에서 진행될 예정입니다!

> ### subscript 활용
> - 프로젝트에 있어 필요한 내용은 아니지만, 새로운 리스트 타입을 만들어보는 김에 subscript도 활용해보고 싶었는데요...! subscript에서는 예외를 던질 수 없게 되어 있는 것을 확인했습니다! 그렇다면 만약 subscript로 전달받은 인덱스가 전체 길이를 넘어서는 경우에는 단순히 nil을 반환시켜야 하는 걸까요? 더 좋은 방법이 있을지 궁금합니다! (이 부분은 고민 끝에 그냥 제거하고 진행했습니다)

좋은 질문을 주셨네요!
저도 역으로 맥스에게 왜 에러를 throw하고 싶은지 궁금해지네요🤔

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculateItem.swift
> +extension String: CalculateItem {}
Step 1에서는 Queue에 대한 구현과 테스트만 하시면 되는데, 이 부분과 다른 부분을 포함해서 계산 목적의 기능을 구현하시려고 한 거 같네요...? 
Step 1에 명시되어 있는 부분이 아닌데, 구현해주신 이유가 있으실까요?

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemNode.swift
> +    }
이 부분도 `Node`의 역할이라고 보기엔 애매하고.. 계산 목적으로 구현하신 코드 같아요.

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var count: Int = 0
테스트를 위해 읽기전용으로 구현하신 거 같은데, 해당 `Queue`를 `protocol`로 추상화하면 테스트 목적의 객체와 실제로 앱에서 사용되는 객체를 따로 만들 수 있지 않을까요?

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
이 부분도 의문이 드는 부분인데요! `Queue`의 역할이 무엇이라고 생각하시나요? `Queue` 객체에 적절한 기능일까요?

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/Calculator/Model/OperatorType.swift
> +}
이 객체도 지금 단계에서는 필요하지 않다고 생각이 듭니다😊

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +}
이 부분은 마찬가지로 현재 스탭에서 벗어난 테스트 코드 같네요.

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertIdentical(newNode2, secondNode)
`XCTAssertEqual`과의 차이는 무엇인가요? 
`XCTAssertIdentical`로 구현하시게 된 이유가 궁금합니다🙋‍♀️

2023-05-30 15:11 UTC, jsa0224 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        }
오류 관련 테스트 메서드도 구현해보셨군요👍

2023-05-30 15:55 UTC, maxhyunm commented on Calculator/Calculator/Model/CalculateItem.swift
> +extension String: CalculateItem {}
이 부분은 테스트에서 값을 넣고 빼는 부분을 확인해보려고 추가했었습니다!

2023-05-30 15:55 UTC, maxhyunm commented on Calculator/Calculator/Model/CalculatorItemNode.swift
> +    }
맞습니다ㅠㅠ! 해당 부분 아래 코멘트로 정리해서 올리겠습니다!

2023-05-30 15:56 UTC, maxhyunm commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private(set) var count: Int = 0
queue 자체를 테스트용으로 따로 생성할 수 있겠네요! 해당 부분은 protocol 활용하여 테스트용 객체를 생성해보도록 하겠습니다!

2023-05-30 15:57 UTC, maxhyunm commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
범위 파악 실수로 인한 내용입니다ㅠㅠ! 이 부분도 아래 코멘트에 정리해두겠습니다.

2023-05-30 15:57 UTC, maxhyunm commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertIdentical(newNode2, secondNode)
XCTAssertIdentical은 두 가지 인스턴스가 완전히 동일한 것인지 type id 일치여부를 확인하는 메서드인 것으로 알고 있습니다! 때문에 단순 값의 비교가 아닌 동일 노드 여부를 확인하는 곳에서는 XCTAssertIdentical을 활용해보는 게 좋겠다고 판단했습니다.

2023-05-30 15:59 UTC, maxhyunm commented
솜! 빠른 리뷰 감사드립니다🙇‍♀️
사실 계산 기능이 들어간 것은 단순히 제가 STEP 1의 요구사항 범위를 헷갈려서 추가했던 것입니다😂
요구사항에는 Queue의 구현이라고만 적혀있었는데, Queue의 명칭이 CalculatorItemQueue이고 내부 구현이 자유라고 되어있다보니, 이게 단순히 요소를 넣었다 빼는 내용만 해당되는 것인지 아니면 CalculatorItem으로 행해야 하는 내용이 포함되어야 하는 것인지 혼자서 헷갈렸던 것 같아요... 완성 후 리팩토링을 하면서 뒤늦게 Node에 타입캐스팅이 들어가는 것도 좀 이상한가...? 내지는 Queue인데 연산이 들어가는게 맞나...? 라는 생각이 들었지만 이미 작성한 내용이니 일단 넣어보자고 판단해서 그냥 올렸었는데, 솜 말씀을 듣고 보니 확실히 해당 내용은 빼놓고 올리는 게 맞았을 것 같아요!
스텝에서 벗어나는 부분은 제거해보도록 하겠습니다!

### 읽기전용 제어 관련
queue 자체를 테스트용으로 따로 생성할 수 있겠네요! 해당 부분은 protocol 활용하여 테스트용 객체를 생성해보도록 하겠습니다!

### subscript 관련
보통 잘못된 인덱스로 접근하면 오류가 발생하기 때문에 여기서도 당연히 오류처리가 되어야 한다고 생각했던 것 같습니다. 단순히 nil을 던져주게 되면 잘못된 접근이 명시적으로 느껴지지 않을 것 같아서 그렇게 느낀 게 아닌가 생각이 드네요...! 이 부분은 추가적으로 처리할 수 있는 방법을 좀 더 찾아보도록 하겠습니다!

2023-05-31 01:07 UTC, maxhyunm commented
@jsa0224 
솜, 말씀하신 대로 STEP 1 범위 외의 내용 삭제 후 다시 올려드렸습니다!
의견 주셨던 접근제어 설정 부분을 해결하기 위해 프로토콜로 분리해 테스트 더블을 만들어 보았는데, 아래와 같은 사유로 중복코드를 작성하게 되었습니다ㅠㅠ
- 프로토콜의 경우 프로토콜 자체에서도, 채택 후 구현할 때도 프로퍼티를 private으로 설정하는 것이 불가능
    - fileprivate으로 설정할 수는 있지만 그렇게 할 경우에도 해당 프로토콜이 있는 파일 외부(예: 테스트용 코드파일)에서는 결과적으로 접근이 불가능
- private 처리되어야 하는 프로퍼티들이 모든 메서드에서 활용되고 있기 때문에 해당 프로퍼티 정의 없이 메서드 내용을 extension으로 구현할 수 없음
해당 부분을 해소할 수 있을까 싶어 클래스 상속으로도 시도해 보았지만 상속의 경우 저장프로퍼티 오버라이딩이 불가하고, 저장프로퍼티에 private을 설정할 경우 해당 프로퍼티는 아예 상속되지 않기 때문에 역시 특정 자식 클래스에서만 접근제어 설정을 변경하는 것은 어렵다는 것을 확인했습니다.
더 좋은 방법이 있을지 계속 고민해 보도록 하겠습니다!

2023-05-31 06:34 UTC, jsa0224 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertIdentical(newNode2, secondNode)
저도 이번에 테스트 공부해보면서 알게 된 키워드라 반가워서 질문 드려봤어요👍
`AnyObject`로 비교하는 테스트 메서드라 `Node` 인스턴스에 쓰는 게 저도 적절해보입니다!

2023-05-31 07:21 UTC, jsa0224 reviewed
프로토콜로 추상화하는 과정이 어려우셨을텐데 잘 해내주셨군요👍

---

> **subscript 관련**
보통 잘못된 인덱스로 접근하면 오류가 발생하기 때문에 여기서도 당연히 오류처리가 되어야 한다고 생각했던 것 같습니다. 단순히 nil을 던져주게 되면 잘못된 접근이 명시적으로 느껴지지 않을 것 같아서 그렇게 느낀 게 아닌가 생각이 드네요...! 이 부분은 추가적으로 처리할 수 있는 방법을 좀 더 찾아보도록 하겠습니다!

저는 에러 타입을 설정하는 이유가 사용자에게 해당 오류를 알려주기 위해서 구현합니다.
사용자가 큐의 요소가 nil인지 아닌지 알 필요는 없을 거 같고, 계산에 오류가 났다 정도만 알면 되지 않을까 해서 질문 드려봤던 내용입니다!
맥스의 답변을 듣고 개발자가 알기 위한 오류로 구현하실 목적으로 질문하셨다는 생각이 드네요!
`subscript`가 시퀀스 개념을 품고 있지만, 사실장 제가 이 문법을 많이 활용해보질 않아서 맥스가 원하는 방향에 답변을 드리기가 힘들 거 같네요😅
나중에 방법 찾아보시면 꼭 공유해주세요👍

> **테스트 더블 관련**

그쵸. 사실상 프로토콜로 추상화한 프로퍼티는 은닉화하기 쉽지 않고, `extension`으로 기본 구현해도 쉽지 않죠. 
저는 한편으로 기본 구현하지 않고 따로 해도 문제 없다고 생각이 들어요.
`Fake` 객체는 테스트 용도니까, 테스트 폴더에 같이 넣는 게 적절할 거 같고, 
읽기 전용으로 `프로퍼티`를 접근 제어할 필요도 없다고 생각이 드는데, 
이 부분은 맥스가 생각해보시라고 따로 코멘트로 남기지는 않았습니다.

추가로, 맥스도 이번에 `Queue` 공부해보시면서 아시겠지만, `Queue`를 구현하는 방식이 여러가지가 있어요.
그렇다면 `Queue`를 추상화하려면 이 모든 구현 방식을 다 고려해야할 수도 있겠죠? 
갑자기 `Queue`의 구현 방식을 바꾸는 일도 생길지도 모르니까요.
그러면 `Queue`의 구현 방식이 다 다르더라고 `enqueue`, `dequeue`, `clear` 까지는 모두 있는 기능이니 추상화로 구현해도 좋을 거 같다는 생각으로 말씀 드린 것도 있어요😉
이 부분은 맥스가 잘 구현해주셔서 따로 코멘트로 남기지는 않았어요!

2023-05-31 07:21 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +protocol LinkedListQueue {
`LinkedList`와 `Queue`는 엄연히 다른 자료구조이기 때문에, 해당 네이밍은 적절하지 않은 거 같습니다.

2023-05-31 07:21 UTC, jsa0224 commented on Calculator/Calculator/Model/TestDouble/CalculatorItemQueueFake.swift
> +struct CalculatorItemQueueFake: LinkedListQueue {
네이밍에서 테스트를 위한 객체 관련 공부하신 게 보이네요👀👍

2023-05-31 07:21 UTC, jsa0224 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        let valuefromHeadBefore = headBefore?.value as? String
변수 네이밍에 카멜케이스 지켜주세요!

2023-05-31 07:35 UTC, maxhyunm commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +protocol LinkedListQueue {
해당 타입명 QueueType으로 수정하도록 하겠습니다!

2023-05-31 07:36 UTC, maxhyunm commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        let valuefromHeadBefore = headBefore?.value as? String
앗!!!! 놓친 부분이네요 확인 감사합니다🙏

2023-05-31 08:54 UTC, jsa0224 commented
수고하셨습니다, 맥스! 
다음 Step 2 진행해주시면 됩니다!

2023-05-31 08:54 UTC, merged