계산기 [STEP 1] myungsun
yagom-academy/ios-calculator-app pull request #482
Opened 2023-05-30 12:15 UTC by myungsun7782

안녕하세요! 솜(@jsa0224) 🙂
저에게는 많이 어려웠던 계산기 STEP 1 이었던 거 같습니다..!😂
많이 부족하지만, 리뷰 잘 부탁드리겠습니다 :)
 감사합니다!
 
## 코드를 작성하면서 고민했던 점 및 어려웠던 점
- 처음에는 `CalculatorItemQueue`에 들어갈 숫자와 연산 기호를 합쳐서 1개의 타입으로 정의해볼까 생각해봤지만, 그러면 1개의 타입에서 숫자와 연산자들을 구분하기 쉽지 않고, 나중에 확장성이나 유지보수 측면에서 좋지 않을 거 같아 결국에는 `NumberItem` 클래스와 `OperatorItem` 열거형 타입을 생성해 나눠서 코드를 작성했습니다.
- 처음에는 `CalculatorItemQueue`에 들어갈 숫자 배열과 연산 기호 배열을 각각 선언해서 코드를 작성하였으나, 이렇게 하면 `Queue`를 사용하는 의미도 없어질 뿐만 아니라 연산 결과를 구할 때 2개의 배열을 사용해야 하므로 개발자가 실수할 수도 있고, 원하지 않는 결과 값이 나올수도 있겠다는 생각이 들었습니다. 그래서 `NumberItem` 클래스와 `OperatorItem` 열거형에서 `CalculateItem` 프로토콜을 채택하도록 코드를 작성했습니다. 이렇게 2개의 서로 다른 타입이 동일한 1개의 프로토콜을 채택함으로서 하나의 타입(`CalculateItem`)으로 취급하여 사용할 수 있었습니다.
- 숫자를 3자리마다 쉼표를 표기해주기 위해서 어떻게 해야할 까 고민하다가 `NumberFormatter`에 대해서 알게 되었습니다. NumberFormatter는 숫자를 문자열로 변환하거나 문자열을 숫자로 변환하는 데 사용되는 클래스로서 다양한 형식의 숫자 표현을 지원해준다고 학습했습니다. `NumberFormatter`의 `numberStyle` 프로퍼티를 `decimal`로 설정해줘서 숫자를 3자리마다 쉼표로 표기해줄 수 있었습니다. 그리고 `minimumFractionDigits`, `maximumFractionDigits` 프로퍼티를 사용해서 소수점 이하의 자릿 수를 제어할 수도 있었습니다.
- `TDD`와 `Unit Test`를 처음 해봤는데, 정말 어렵고, 제가 잘 하고 있는 게 맞는 건지 계속 의문이 들었습니다.

## 조언을 얻고 싶은 점 

- 저는 `CalculateItemQueue`에 있는 `items`를 `Linked List`로 구현하려고 했지만, 잘 되지 않아서 결국 `Array`로 구현을 했습니다. 혹시 `Array`가 아닌 `Linked List`로 구현했을 때 얻을 수 있는 장점이 `enqueue`,  `dequeue`를 할 때 시간복잡도가 `Array`로 구현했을 때의 `O(n)`에 비해  `O(1)`로 빠르다는 것 외에 다른 장점이 있을까요? 아직 큰 규모의 앱을 만들어 본 경험이 없어서 시간 복잡도가 낮다고 해서 얻을 수 있는 장점이 확 와닿지 않는거 같아요..
- 나중에 `App`을 개발하다가 `Queue` 자료 구조가 필요해서 만들어 사용해야 하는 상황이 온다면, 꼭 `Linked List`를 사용해서 구현해야 하는 걸까요?
- `Unit Test`를 진행할 때 어느 정도의 경우의 수까지 나눠서 진행해야 하는 지 잘 모르겠습니다.
- `NumberItem` 구조체와 `OperatorItem` 열거형을 테스트할 때는 별도로 `sut(system under test)`를 생성해주지 않았는데, `Unit Test`를 진행할 때 이렇게 `sut`를 만들지 않고 진행하는 경우도 있을까요?

## UML

<img src="https://github.com/myungsun7782/TIL/assets/74762699/94695302-7a81-41e3-b47a-7d33297c5659" style="zoom:50%;" />

2023-05-30 15:10 UTC, jsa0224 requested changes
---

2023-05-31 06:24 UTC, jsa0224 requested changes
안녕하세요, 명선!
2주 동안 명선의 리뷰를 맡은 솜입니다😊
커밋 분기도 잘 나누셨고, 프로젝트도 고민하시고 구현하신 흔적이 보였습니다👍

## 조언을 얻고 싶은 점에 대한 답변
> - 저는 CalculateItemQueue에 있는 items를 Linked List로 구현하려고 했지만, 잘 되지 않아서 결국 Array로 구현을 했습니다. 혹시 Array가 아닌 Linked List로 구현했을 때 얻을 수 있는 장점이 enqueue, dequeue를 할 때 시간복잡도가 Array로 구현했을 때의 O(n)에 비해 O(1)로 빠르다는 것 외에 다른 장점이 있을까요? 아직 큰 규모의 앱을 만들어 본 경험이 없어서 시간 복잡도가 낮다고 해서 얻을 수 있는 장점이 확 와닿지 않는거 같아요..

시간복잡도라는 개념이 눈에 명확히 보이지 않아서 더 와닿지 않으신 거 같아요. 
검색 사이트에서 검색을 하는데 로딩이 느린 경우, 영상의 로딩이 긴 경우 등등 사용자에게 대기 시간을 부여하는 거 자체가 저는 좋은 경험이라고 생각은 안 들어요.
당장 사칙연산만 하는 작은 프로젝트는 시간복잡도에 크게 구애받지 않을 수 있어도, 공학계산기로 업그레이드 될 경우, 시간복잡도를 고려하지 않고 설계했다면 다시 설계해야 하는 불상사가 생길 수도 있죠.
답변이 되었을지는 모르겠네요😅

> - 나중에 App을 개발하다가 Queue 자료 구조가 필요해서 만들어 사용해야 하는 상황이 온다면, 꼭 Linked List를 사용해서 구현해야 하는 걸까요?

꼭이라는 말은 좀 위험할 거 같아요!
이 부분은 공부해보시면서 자신만의 기준을 찾으셨으면 좋겠어요.
힌트를 드리자면 앞서 말씀드린 시간복잡도 키워드와 관련이 있습니다.

> - Unit Test를 진행할 때 어느 정도의 경우의 수까지 나눠서 진행해야 하는 지 잘 모르겠습니다.

기능을 충분히 테스트하는 게 좋죠!
enqueue의 경우, 큐에 잘 들어가는지 / dequeue의 경우, head에 있는 요소가 잘 빠져나가는 지
이런 기준으로 테스트를 하면 되지 않을까요?
오류 처리를 했다면, 해당 오류가 잘 나오는지도 테스트해보는 게 중요할 거 같네요.

![스크린샷 2023-05-31 오후 2 54 30](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/5ab9ef13-da4d-4867-9b84-ac0a698aee4a)


코드 커버리지를 보니 명선은 테스트 잘 해주신 거 같아요!

> - NumberItem 구조체와 OperatorItem 열거형을 테스트할 때는 별도로 sut(system under test)를 생성해주지 않았는데, Unit Test를 진행할 때 이렇게 sut를 만들지 않고 진행하는 경우도 있을까요?

경우에 따라 다르겠지만, 테스트가 잘 안 되고 있을 거 같긴 하네요.

![스크린샷 2023-05-31 오후 3 15 07](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/2a34ddc0-e2ef-4090-a653-01aa6a4dfd0d)
![스크린샷 2023-05-31 오후 3 15 14](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/41ebf678-6831-45b0-870d-c9f8d2aebb7a)


이번 스탭과 관련 없는 객체들이라 따로 리뷰를 드리지 않았지만, 코드 커버리지 상에서도 테스트가 안 되고 있다고 뜹니다. 

## 조언 드리고 싶은 부분
- `Generic` 
[Generic](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/generics/) 공부해보셨으면 좋겠어요! 그러면 제가 코멘트에 남겼던 문제점들을 해결할 수 있을 거라 생각이 듭니다.
- `clear()` 테스트
![스크린샷 2023-05-31 오후 3 14 30](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/ef1b0ca2-8ea5-4e43-a6d8-d5cb24caf3c0)

    `clear()`도 테스트가 안 되었는지 코드 커버리지 상에서 0으로 나옵니다.

2023-05-31 06:24 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +final class CalculatorItemQueue {
`class`로 구현하신 이유가 무엇인가요?

2023-05-31 06:24 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var items: [CalculateItem] = []
`더블 스택`으로 구현하는 방법도 있는데, 배열 하나로 구현하신 이유가 있으실까요?

2023-05-31 06:24 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
`Queue`의 역할은 무엇인가요? `Queue`라는 객체가 계산 기능이 필요한가요?

2023-05-31 06:24 UTC, jsa0224 commented on Calculator/Calculator/Model/NumberItem.swift
> +}
- 이 부분은 현재 스텝에서 필요한 객체는 아닙니다. 
- 큐에 어떤 타입이 들어올지는 예상할 수 없는데, `NumberItem`이라는 객체로 설정하는 것은 확장성이 떨어지는 거 같습니다.

2023-05-31 06:24 UTC, jsa0224 commented on Calculator/Calculator/Model/OperatorItem.swift
> +}
이 부분도 현재 스텝에서 필요한 객체는 아닙니다.

2023-05-31 06:24 UTC, jsa0224 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
이 부분도 해당 스탭에서 진행될 테스트는 아닌 것으로 보입니다.

2023-05-31 12:11 UTC, myungsun7782 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +final class CalculatorItemQueue {
처음에는 `Queue` 안에 있는 `items` 프로퍼티가 다른 변수에 할당 되더라도 참조 상태가 유지될 필요가 있을거 같기 때문에 `class`로 선언했는데, 다시 `Queue`의 역할에 대해서 고민해보니깐 굳이 참조 상태가 유지될 필요가 없다고 판단해서 `struct`로 수정했습니다:)

2023-05-31 12:14 UTC, myungsun7782 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var items: [CalculateItem] = []
큐를 구현할 때 단순히 1개의 `Array`와 `LinkedList`로 구현하는 방법밖에 없는 줄 알아서 `Array`로 구현하게 되었습니다. 그래서 `Double Stack`으로도 `Queue`를 구현할 수 있다는 것을 깨닫고 다시 학습한 뒤에 `Double Stack`으로 구현했습니다!

2023-05-31 12:17 UTC, myungsun7782 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var items: [CalculateItem] = []
`Double Stack`으로 `Queue`를 구현하면서 얻을 수 있는 가장 큰 이점은 `dequeue`할 때 시간 복잡도를 줄일 수 있다는 것이었습니다. `dequeue`메서드는 `outStack`이 비어있을 경우, `inStack`의 모든 요소를 `outStack`으로 옮기는 작업이 필요하므로, 시간 복잡도가 `O(n)`이 되지만 이 작업은 `oustStack`이 비어 있는 경우에만 수행되므로, 각 요소는 한 번씩만 옮겨집니다. 따라서, `dequeue`의 평균 시간 복잡도는 `O(1)`이 됩니다.

2023-05-31 12:19 UTC, myungsun7782 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
`Queue`의 역할은 들어온 데이터 요소를 순서대로 처리하고 관리하는 역할을 합니다! 따라서, `calculate` 메서드가 들어가는 것은 적절하지 않다고 판단되어 삭제해줬습니다!

2023-05-31 12:21 UTC, myungsun7782 commented on Calculator/Calculator/Model/NumberItem.swift
> +}
`NumberItem` 구조체 삭제 완료했습니다! 그리고 솜이 말한 것처럼 `NumberItem`이라는 객체로 설정하는 것은 확장성이 떨어지는 거 같습니다! 만약 확장성을 고려해야 한다면 제네릭(`Generics`) 타입으로 구현해줘야 할 거 같습니다:)

2023-05-31 12:21 UTC, myungsun7782 commented on Calculator/Calculator/Model/OperatorItem.swift
> +}
삭제 완료했습니다:)

2023-05-31 12:22 UTC, myungsun7782 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
삭제 완료했습니다! 추가적으로 `calculatorItemQueue` 테스트 코드를 다시 작성했습니다:)

2023-06-01 01:44 UTC, jsa0224 commented
수고하셨습니다, 명선!
다음 스탭 진행해주시면 됩니다!

2023-06-01 01:44 UTC, merged