계산기 [STEP 1] Kobe
yagom-academy/ios-calculator-app pull request #487
Opened 2023-05-31 03:14 UTC by devKobe24

안녕하세요 원비(@wonbi92) 🙌
처음으로 원비께 리뷰를 받게된 코비🥴 입니다.
잘 부탁드립니다.

---

## 🏗️ UML
<img src = "https://github.com/devKobe24/images/blob/main/QueueUML_2.drawio.png?raw=true" width = 550>

---
## 🤔 고민한 점
1. Queue의 원리에 대해서 고민했습니다.
- Queue라는 자료구조가 어떤 원리와 어떤 구조로 생겼는지 찾아보았으며 많은 변형이 있다는 것을 알게 되었습니다.

2. 배열 vs 단방향 리스트 
- Queue 구조를 구현시 배열과 단방향 리스트로 구현할 수 있다는 것을 알게되었습니다. 아직 단방향 리스트에 대한 정확한 개념과 단방향 리스트로 구현할 수 있는 충분한 학습이 되어있지 않아 배열로 구현하였습니다.
- 배열과 단방향 리스트로 큐를 구현했을 때의 차이점은 시간 복잡도에 있다는 것을 알았습니다. 예를 들어 배열의 첫 번째 요소가 빠지면 뒤에 있는 요소들이 앞으로 한 칸씩 자리를 다시 정렬해야해서 O(n)이 걸리지만 단방향 리스트의 경우 첫 번째 요소가 빠진다고 해도 노드를 가리키고 있는 참조만 끊어주면 되기 때문에 O(1)이 걸린다고 학습했습니다.

> 이와 같은 이유로 배열로 큐를 구현하게 되었습니다.

---

## 🙋‍♂️ 조언을 얻고 싶은 부분
1. TDD.
- 함수가 구현되어 있지 않은 상태에서 어떻게 테스트를 할지 계속해서 고민이 됩니다 그래서 제가 선택한 방법은 일단 빈 함수를 만들고 [RED] -> 내부에 함수 로직 구성 [GREEN] -> 리팩토링 [BLUE] 이렇게 하고 있는데 이 방식이 맞는지 궁굼합니다.

2. Queue의 단방향 리스트 구현.
- Queue를 단방향 리스트 구조를 이용해서 구현해야 하는 경우 어떤 점을 중점적으로 고민하고 구현해야할까요?

2023-06-01 03:22 UTC, wonbi92 requested changes
@devKobe24 
반갑습니다 코비! 3주동안 계산기 리뷰를 맡게된 Wonbi입니다! 앞으로 잘 부탁드려요~ 😁

step1진행하시느라 고생하셨습니다!

몇가지 수정사항과 참고하실만한 부분들을 코맨트 드렸으니 쭉 읽어보시고 궁금하신 점 있으시면 말씀해주세요~ 💪

### 아래는 질문주신 부분에 대한 제 생각입니다! 😁
---
> 함수가 구현되어 있지 않은 상태에서 어떻게 테스트를 할지 계속해서 고민이 됩니다 그래서 제가 선택한 방법은 일단 빈 함수를 만들고 [RED] -> 내부에 함수 로직 구성 [GREEN] -> 리팩토링 [BLUE] 이렇게 하고 있는데 이 방식이 맞는지 궁굼합니다.
- TDD는 방법론이기 때문에 개발 방식 외에 모든 결정은 개발자 스스로 결정해야 합니다. 코비가 고민하시고 결정하신 방법이 맞다 틀리다 라고 할 수는 없을거 같아요!
- 말씀하시는 빈 함수가 어떤 함수인지 파악하기가 조금 힘드네요! 테스트 하고자 하시는 객체의 메서드인지 테스트 케이스인지.. 
- 일반적으로 TDD는 테스트를 작성한 후 그 테스트를 성공시키기 위해 리팩토링을 진행하죠! 그런데 테스트를 작성하려면 테스트 하려는 로직 자체는 필요하잖아요? 그렇기 때문에, 테스트 하려는 객체에 비어있는 함수를 구현하고, 이 함수를 통해 원하는 결과가 나오는지 테스트하는 테스트 케이스를 작성하신 후, 빈 함수를 리팩토링하는 방식으로 진행될거 같아요!

2023-06-01 03:22 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +}
빈 프로토콜을 선언할 때는 대괄호 사이를 한칸 띄어쓰는게 일반적인 방법입니다. 정답은 아니니 참고하세용~
```suggestion
protocol CalculateItem { }
```

2023-06-01 03:22 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
`CalculatorItemQueue`가 `CalculateItem`을 채택하고 있군요..! 요구사항을 보면 
> `CalculatorItemQueue`에서 **다루는 요소**는 `CalculateItem` 프로토콜을 준수합니다.

라고 하고 있어요! 지금 코드대로 라면 "다루는 요소"가 `CalculateItem` 프로토콜을 준수한다고 할 수 없을거 같은데.. 🤔

2023-06-01 03:22 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
`enqueue`하는 메서드가 배열을 반환하는 이유를 알 수 있을까요? 👀

2023-06-01 03:22 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
요 메서드는 어디서 사용하는 메서드일까요? 👀

2023-06-01 03:22 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
`removeAll()`을 호출한 후에 배열이 비어있는지 확인하는 로직이군요..! 다만, `removeAll()`메서드가 실패할 수 있는 메서드일까요? 🤔 
제 생각에는 이 로직에서는 무조건 if문을 타고 true를 반환할거 같아요! 배열이 비어있는지 확인하는 로직을 추가하신 이유를 알 수 있을까요? 😅

2023-06-01 03:22 UTC, wonbi92 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +		var input = sut.enqueue(1)
`input`변수에 대한 컴파일 경고가 뜨고 있네요! 이 컴파일에러는 무엇이고, 어떻게 해결할 수 있을까요?

2023-06-01 03:22 UTC, wonbi92 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +	func tests_배열에_값이_들어간다() {
테스트 케이스를 작성하는 방법은 사바사, 회바회기 때문에 정답은 없습니다만, 각 테스트 케이스별 표현 방식은 통일 시켜주시는게 좋겠죠? 또한, 케이스를 작성하실 때는 어떤 케이스를 테스트하는지 명확하게 전달해줄 필요가 있습니다. 

현재 작성하신 케이스는 변인통제를 제대로 명시하지 않아 테스트 케이스를 해석하기 모호해지는 것 같습니다.
배열에 어떤 값이 들어가는지, 얼마나 들어가는지 모르고, 배열에 값이 제대로 들어가는지 확인하는 테스트인지, 배열에 값이 들어가는 로직 자체를 확인하는 테스트인지.. 등등 모호한 부분이 너무 많습니다. 좀 더 정확한 표현으로 이 테스트가 어떤 테스트인지 명시해주세요!

2023-06-01 07:33 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +}
네!! 꼭 참고하겠습니다 🙋‍♂️

2023-06-01 07:33 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
요구사항을 조금 더 자세히 보고 이해한 후 수정해보도록 하겠습니다. 🙌

2023-06-01 07:35 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
TDD시 테스트를 위해 반환값을 주었습니다. 반환값이 굳이 필요 없는 함수에 TDD를 위해 반환값을 준 것을 수정해보도록 하겠습니다 🙌

2023-06-01 07:36 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
처음 값이 0이나 기호가 안들어가게 만들기 위해 큐의 첫 번째 요소를 검사하려고 만든 메서드입니다.🙋‍♂️

2023-06-01 07:39 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
지금 보니 if 문이 없으면 더 깔끔한 코드가 될 것 같습니다. 더 깊이 생각해보고 수정해보겠습니다 🙋‍♂️

2023-06-01 07:42 UTC, devKobe24 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +		var input = sut.enqueue(1)
변수가 쓰여졌지만 사용은 안되서 나는 에러입니다. 와일드 카드 패턴을 사용해서 해결할 수 있을 것 같습니다 🙋‍♂️

2023-06-01 07:45 UTC, devKobe24 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +	func tests_배열에_값이_들어간다() {
테스트 케이스 변인통제를 제대로 명시하여 테스트 케이스를 해석하기에 모호해지는 일이 없도록 수정하고 이후에는 테스트 케이스 변인통제를 제대로 명확하게 명시하도록 하겠습니다 🙋‍♂️

2023-06-02 03:35 UTC, wonbi92 reviewed
@devKobe24 
리팩토링 해주신 부분들 잘 봤습니다! 고생하셨어요! 👍

추가적인 코맨트를 드렸으니 참고해보시기 바랍니다. 

---

현재 큐를 구현함에 있어 링크드 리스트에 대한 공부가 부족해 배열을 사용하신 부분은 이해가 됩니다. 다만, 큐를 구현하는 방법은 배열을 사용하는 것과 링크드 리스트를 사용하는 방법 외에도 몇가지가 더 있는데요. 해당 부분에 대해 고려하신 것 같지 않아서 이 부분은 조금 아쉽네요..! 
배열과 링크드 리스트 외에 다른 방법들도 한번 고려해보시고, 최종적으로 어떤 방법을 선택하실지 좀더 고민해보시길 바랍니다!

2023-06-02 03:35 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<Element: CalculateItem> where Element: Equatable {
`where`절을 통해 `Equatable`로 제한하신 이유를 알 수 있을까요? 🤔

2023-06-02 03:35 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
테스트를 위한 메서드를 작성하셨군요..!
해당 로직 자체는 테스트에서만 필요하다는 생각이 들긴 합니다만, 주객전도라는 생각도 듭니다.
테스트의 방법을 바꿔보시거나 해당 로직을 테스트 객체 안으로 옮기시는것도 좋아보여요.
아니면 Test Double을 이용해 Mock객체를 만들어서 해당 객체에만 이 로직을 옮기는 것도 방법이 될 수 있겠네요!

테스트를 위한 메서드나 프로퍼티가 실제 객체에 존재하는 거 자체가 조금 어색해 보입니다. 
이 부분은 다른 방법을 고려해볼 필요가 있겠네요.

2023-06-02 03:35 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +		}
사바사겠지만, 저였다면 요런식으로 표현하는게 좀 더 간단해 보이네요! 어떻게 생각하세요?
```suggestion
		elements.isEmpty ? nil : elements.removeFirst()
```

2023-06-03 08:27 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<Element: CalculateItem> where Element: Equatable {
저 코드를 구현할 당시에 Element의 대소비교를 가능하게 하려고 Equatable로 제한을 두었습니다.🙋‍♂️

2023-06-03 08:28 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	}
현재 Test Double을 공부하고 Mock 객체를 따로 만들어 테스트에 사용하였습니다 🙋‍♂️

2023-06-03 08:30 UTC, devKobe24 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +		}
원비께서 피드백주신 삼항 연산자가 훨씬 깔끔하고 가독성이 좋습니다. 가독성이 좋은 코드를 만들기 위해 노력하겠습니다. 🙋‍♂️

2023-06-05 03:59 UTC, wonbi92 approved these changes
@devKobe24 
안녕하세요 코비!
잘 수정해주셨어요! 고민하신 흔적이 보여서 좋았습니다! 👍👍

약간 고민하실만한 부분들이 있지만 다음 스탭 진행하시면서 하셔도 충분할거 같아요! 
코맨트 읽어보시고 다음 스탭 진행하시면서 같이 적용시켜 보시기 바랍니다!

2023-06-05 03:59 UTC, wonbi92 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +	private var list: LinkedList<T>?
큐 내부의 리스트가 꼭 옵셔널일 필요가 있을까요? 🤔 리스트가 옵셔널일 경우 어떻게 되나요? 한번 고민해보시기 바랍니다!

2023-06-05 03:59 UTC, wonbi92 commented on Calculator/Calculator/Model/LinkedList.swift
> +	associatedtype T: Any
`associatedtype T`가 `Any`를 채택한 이유가 무엇일까요?

2023-06-05 03:59 UTC, wonbi92 commented on Calculator/TestDouble/MockCalculatorItemQueue.swift
> +}
링크드리스트를 프로토콜로 한번 추상화를 하였는데 다시 목객체를 추상화 하고 있네요..! 이러면 테스트 링크드 리스트와 실제 링크드리스트는 완전히 별개의 객체로 되어있는거 같아요..! TestDouble을 활용한 Mock객체를 만드는 이유에 대해 조금 더 고민해보시면 좋을 것 같습니다.

2023-06-05 03:59 UTC, merged