계산기 [Step 1] Yetti
yagom-academy/ios-calculator-app pull request #495
Opened 2023-06-01 03:25 UTC by iOS-Yetti

@wonbi92 
쥬스메이커에 이어 계산기프로젝트도 잘 부탁드립니다 원비🙂
모르는 부분이 많아 공부하며 작성하다보니 첫 PR이 조금 딜레이됐네요

그리고 개인 프로젝트라 커밋 단위를 신경쓰지 않다가 중간부터 커밋 단위를 나누기 시작했습니다..ㅎ..
신경써서 커밋하겠습니다😂

# 고민했던 것

- UML작성과 테스트작성의 순서에 대해 고민하였습니다. 제 생각으로는 UML을 통해 구조를 잡아두고 UML을 바탕으로 테스트코드를 작성하며 TDD방식으로 진행하고 싶었습니다. step 1에서는 구조가 크지 않아 무리가 없었지만 구조가 커지게 되면 어느 타입에 어떤 메서드들이 필요할지에 대해 헷갈릴 것 같았습니다.
- `제네릭 사용 여부`
제네릭을 사용해 구현이 필요할지에 대해 고민하였습니다. 제네릭은 범용타입으로써 계산기프로젝트에서 숫자와 연산자를 함께 담기에 좋을 것 같다고 생각했습니다. 하지만 숫자와 연산자를 `String`으로 받아올 수 있다면 제네릭을 사용하지 않고도 가능하겠다는 생각에 결과적으로 제네릭을 사용하지않고 `String`을 사용하여 구현하였습니다. 추후 step에서 제네릭이 필요하게 된다면 리팩토링해 볼 예정입니다.
- `deQueue메서드의 효율성`
`deQueue`메서드를 수행할 때 더 효율적인 구현 방법이 어떤 것인지 고민했습니다. 처음엔 간단하게 하나의 `Array`에서 `removeFirst()`를 이용해 값을 삭제해주었습니다. 하지만 시간복잡도의 개념에서  `removeFirst()`는 `O(n)`이 되기 때문에 좀 더 개선된 효율성을 찾다가 `Double Stack Queue`로 구현하는 방법을 찾았고 `Double Stack Queue`로 `deQueue`를 구현하게 되면 시간복잡도가 `O(1)`이 된다는 것을 알게 되었습니다. 결과적으로 배열 2개를 이용하는 `Double Stack Queue`를 구현하여 `Queue`를 구현해보았습니다.
- `removeLast() vs popLast()`
deQueue를 구현할 때 `removeLast()`를 사용할지 `popLast()`를 사용할지에 대해 고민하였습니다.
처음엔 마지막 요소를 삭제하는 메서드가 왜 2개나 존재하는지 몰랐습니다. 찾아본 결과 `removeLast()`는 마지막 요소 값을 삭제 후 그대로 반환하는 것이었고 `popLast()`는 마지막 요소의 값을 삭제 후 그대로 반환하지않고 `Optional`로 반환한다는 것을 알게 되었습니다. 각 배열이 비었을 경우를 고려하여야 하기 때문에 결과적으로`popLast()`를 이용해 `deQueue`를 구현해 주었습니다.
- `TDD`와 `Unit Test` 모두 처음 진행하는 데다가 개인 프로젝트라 내가 하는게 지금 맞나? 라고 고민하며 보낸 시간이 꽤 길었습니다.

# 조언이 필요한 것

- 커밋 단위를 나눌 때에 유닛테스트 코드도 나누어서 커밋해야 할지 앱 코드를 기준으로만 커밋해야 하는 건지에 대해 조언을 구하고 싶습니다.
- clear메서드 같은 경우 내부에서 진행하는 부분이 removeAll메서드를 이용하는 부분밖에 없습니다. 그럼에도 모든 메서드를 테스트해야한다는 생각 때문에 테스트를 작성해주었는데 저런부분까지 테스트를 진행해야하는지 아니면 넘어가도 되는지 궁금합니다.

# UML 다이어그램
![계산기UML drawio](https://github.com/yagom-academy/ios-calculator-app/assets/100982422/4a54a991-89bf-483f-90cf-6d9d6ee74722)

2023-06-02 02:12 UTC, wonbi92 requested changes
@iOS-Yetti
반갑습니다 예티! 한번 더 3주동안 계산기 리뷰를 맡게된 Wonbi입니다! 한번 더 잘 부탁드려요~ 😁

step1진행하시느라 고생하셨습니다!

몇가지 수정사항과 참고하실만한 부분들을 코맨트 드렸으니 쭉 읽어보시고 궁금하신 점 있으시면 말씀해주세요~ 💪

### 아래는 질문주신 부분에 대한 제 생각입니다! 😁
---
> 커밋 단위를 나눌 때에 유닛테스트 코드도 나누어서 커밋해야 할지 앱 코드를 기준으로만 커밋해야 하는 건지에 대해 조언을 구하고 싶습니다.
- 커밋 단위는 하기 나름이죠? 당연하게도 정답은 없습니다! TDD는 방법론이고, 커밋 단위를 결정하는 것은 개발자의 몫입니다. 세세하게 나누고 싶다면 유닛테스트와 앱 코드를 나눠서 커밋해야 할테고, 너무 잘게 쪼개기 싫다면 한번에 TDD사이클을 커밋 단위로 잡을 수도 있겠죠?
- 예티만의 기준을 잡으시고, 그 기준을 철저하게 지키는 방향으로 해보시면 좋을거 같아요!

> clear메서드 같은 경우 내부에서 진행하는 부분이 removeAll메서드를 이용하는 부분밖에 없습니다. 그럼에도 모든 메서드를 테스트해야한다는 생각 때문에 테스트를 작성해주었는데 저런부분까지 테스트를 진행해야하는지 아니면 넘어가도 되는지 궁금합니다.
- 사실, 테스트의 목적은 사이드 이팩트를 통한 원하지 않는 동작을 방지하는 것이고, TDD는 이를 먼저 잡아가면서 유닛단위로 메서드를 나누고, 예외를 최소화 하는 방향으로 개발하는 방법론이라 생각합니다.
- 때문에 TDD의 방법론적인 시각에서는 각 행동(메서드)이 정확하게 동작하는지 검증하는 과정이 필수적으로 필요합니다.
- 저는 방법론적으로는 필요하다는 생각이 드네요. 코드 커버리지를 100%로 만들고자 하는 목적으로 작성하시는 분들도 있겠지만요. ㅎㅎ

### 아래는 고민하신 부분에 대한 제 의견입니다. 😉
---
 > 제네릭 사용 여부
제네릭을 사용해 구현이 필요할지에 대해 고민하였습니다. 제네릭은 범용타입으로써 계산기프로젝트에서 숫자와 연산자를 함께 담기에 좋을 것 같다고 생각했습니다. 하지만 숫자와 연산자를 String으로 받아올 수 있다면 제네릭을 사용하지 않고도 가능하겠다는 생각에 결과적으로 제네릭을 사용하지않고 String을 사용하여 구현하였습니다. 추후 step에서 제네릭이 필요하게 된다면 리팩토링해 볼 예정입니다.
- 방향성은 이해 했습니다. 다만, 코맨트로도 말씀 드렸던 부분인데 프로젝트의 요구사항을 충족하지는 못하게 되어버렸어요. 큐가 "다루는 요소"는 CalculateItem 프로토콜을 채택해야만 합니다!
- 고민에 대한 결론이 잘못되었다는 것은 아니지만, 별개로 요구사항 자체는 충족해야겠죠? 😄

2023-06-02 02:12 UTC, wonbi92 commented on Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: DoubleStackQueue, CalculateItem {
`CalculatorItemQueue`가 `CalculateItem`을 채택하고 있군요..! 요구사항을 보면 
> `CalculatorItemQueue`에서 **다루는 요소**는 `CalculateItem` 프로토콜을 준수합니다.

라고 하고 있어요! 지금 코드대로 라면 "다루는 요소"가 `CalculateItem` 프로토콜을 준수한다고 할 수 없을거 같은데.. 🤔

2023-06-02 02:12 UTC, wonbi92 commented on Calculator/CalculatorItemQueue.swift
> +    var deQueueStack: [String] = []
요 두 배열은 외부에서 접근이 가능한 상태 같군요! 외부에서 접근할 필요가 있을까요? 👀

2023-06-02 02:12 UTC, wonbi92 commented on Calculator/CalculatorItemQueue.swift
> +    }
`reversed()`메서드를 두번 사용하고 있네요..! 이런 로직이라면 더블 스택 큐의 장점을 제대로 활용하지 못하고 있다는 생각이 듭니다.
더블 스택큐는 어떤 장점이 있을까요? 그리고 `reversed()`메서드의 시간 복잡도는 어떻고, 반환값은 뭘까요? 🤔

2023-06-02 02:12 UTC, wonbi92 commented on Calculator/CalculatorItemQueue.swift
> +        return enQueueStack == [] ? nil : enQueueStack[0]
out of range 런타임 에러를 방지하기 위해 조건문을 이용하셨군요! 👍 일어날 수 있는 에러를 방지하는 로직 좋습니다! 
사바사겠지만, 저는 다음과 같이 쓰는게 좀 더 읽기 편해보이네요! 어떠신가요? 😁
```suggestion
        return enQueueStack.isEmpty ? nil : enQueueStack[0]
```

2023-06-02 02:12 UTC, wonbi92 commented on Calculator/Protocol.swift
> +}
프로토콜을 활용해 큐를 추상화 해주셨군요! 👍👍

2023-06-02 23:49 UTC, iOS-Yetti commented on Calculator/CalculatorItemQueue.swift
> +    var deQueueStack: [String] = []
테스트코드에서 호출하고있어서 에러가 나서 접근제어자를 붙이지 않았었습니다. 테스트를 수정하여 input을 이용해 eqQueueStack과 deQueueStack에 직접접근하지 않도록하고 private(set)을 붙여주었습니다!

2023-06-02 23:50 UTC, iOS-Yetti commented on Calculator/CalculatorItemQueue.swift
> +    }
- 더블스택큐에 대한 공부가 미숙한 채로 진행해서 발생한 로직이네요 🥲
제가 이처럼 로직을 짰던 이유는 `enQueueStack`과 `deQueueStack`을 각각 `enQueue`, `deQueue`의 “용도”로만 인식해서 발생한 로직입니다..!
다시 공부를 해보고 찾아보니 `enQueueStack`, `deQueueStack`이 함께 “하나의 큐 역할”을 해야한다는 걸 깨달았습니다. 그리고 그렇게 활용되기 위한 로직으로 전면 수정하였습니다!
- `reversed()`는 o(1)의 시간복잡도를 가지고 있고 역순의 새로운 배열을 리턴하는 것이 아니라 역순으로 접근할 수 있는 래퍼 유형을 리턴해줍니다.

2023-06-02 23:54 UTC, iOS-Yetti commented on Calculator/CalculatorItemQueue.swift
> +        return enQueueStack == [] ? nil : enQueueStack[0]
원비 말씀대로  isEmpty를 활용하는 방향이 가독성이 좋은것 같아 수정하였습니다! 다만 peek메서드는 로직을 바꾸며 전면수정하였고 enQueueStack과 deQueueStack에 요소가 있는가없는가를 판별하기위해 아래처럼 표현해주었습니다.
```swift
deQueueStack.count >= 1
```

2023-06-02 23:58 UTC, iOS-Yetti commented on Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: DoubleStackQueue, CalculateItem {
이 부분에 대해서는 감이 잘 잡히지 않습니다 원비..! 아직 빈 프로토콜이라 어디서 `CalculateItem`을 다뤄야할지 감이 잡히지 않습니다😭
조언이나 힌트를 얻을 수 있을까요??

2023-06-04 10:43 UTC, wonbi92 commented on Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: DoubleStackQueue, CalculateItem {
프로토콜을 다루는 것은 아니고, 이 프로토콜을 채택하는 객체입니다! "큐 내부에 저장되는 객체"가 `CalculateItem`프로토콜을 채택해야 해요! 현제 예티의 코드에서는 "큐 내부에 저장되는 객체"가 아니라 "큐 자체"가 `CalculateItem`프로토콜을 채택하고 있습니다.

2023-06-04 16:01 UTC, wonbi92 commented on Calculator/CalculatorItemQueue.swift
> +    }
`reversed()`메서드의 시간복잡도가 O(1)인건 맞지만 이는 메서드를 호출하는 것에 대한 이야기입니다. 찾아보신대로 역순으로 접근할 수 있는 래퍼를 리턴해주죠!
답변주신대로 리턴받아온 래퍼를 다시 `deQueueStack`에 할당해주고 있죠? 이 과정에서 새로운 배열을 만들고 그 안에 역순으로 접근해서 데이터를 하나하나 인서트 하는것과 똑같은 로직을 하게되서 결국 O(n)의 시간 복잡도를 가지게 됩니다. 

더블스택큐는 배열 하나만 사용해 `removeLast()`메서드를 사용하는 것 보다는 개선된 시간 복잡도를 가지겠지만, 그럼에도 리버스하는 과정 자체에서는 O(n)의 시간 복잡도를 가지게 되는 문제가 있네요!

2023-06-04 16:06 UTC, wonbi92 commented
@iOS-Yetti 
안녕하세요 예티! 잘 수정해주셨어요!
다만, 한가지 요구사항이 아직 충족되지 않아서 그부분만 수정해주시면 머지해드리겠습니다.
코맨트 읽어보시고 고민해보세요~ 화이팅입니다! 💪

2023-06-05 03:52 UTC, iOS-Yetti commented on Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: DoubleStackQueue, CalculateItem {
원비의 조언대로 "큐 내부에 저장되는 객체"가 CalculateItem을 채택할 수 있도록 extension을 이용해 큐에 저장되어야 할 수도 있는 Double, Int, String에 CalculateItem을 채택해 주었습니다!

2023-06-05 03:55 UTC, iOS-Yetti commented
정말 고민이 많이되고 어렵기도하고 배우기도 많이 배우는 스텝인거 같습니다 😂
전면적으로 String을 다루는 큐에서 제네릭을 사용할 수 있도록 수정해주었고 peek과dequeue메서드도 철저히 예외 상황을 방지하기 위해 노력했습니다!

2023-06-05 04:01 UTC, merged