계산기 [STEP2] EtialMoon
yagom-academy/ios-calculator-app pull request #506
Opened 2023-06-06 10:31 UTC by hojun-jo

계산기 [STEP2] EtialMoon

@jsa0224
안녕하세요 Som!
EtialMoon입니다.
STEP2 PR 보내드립니다~
잘 부탁드립니다. 🙇

---

### 고민한 점
#### Formula의 result를 계산하는 부분
처음 계산할 때는 큐에서 값을 두 번 꺼내와 계산하고 그 이후에는 이전에 계산된 값과 큐에서 꺼낸 값을 계산해야 합니다. 조건을 걸어 두 경우를 나누게 되면 비슷한 로직이 반복되는 것 같았습니다. 반복을 줄이기 위해 `operators`에 미리 값을 넣어 두고 반복문 한 번으로 동작하도록 만들었습니다.
```swift
struct Formula {
    var operands: CalculatorItemQueue<Double> = CalculatorItemQueue<Double>()
    var operators: CalculatorItemQueue<Operator> = CalculatorItemQueue<Operator>(enqueuedCalculatorItems: [Operator.add])
    
    mutating func result() throws -> Double {
        var operationCount = operators.count()
        var result = 0.0
        
        while operationCount > 0 {
            guard let operand = operands.dequeue(),
                  let operationResult = operators.dequeue()?.calculate(lhs: result, rhs: operand) else {
                throw FormulaError.operationError
            }
            
            result = operationResult
            operationCount -= 1
        }
        
        return result
    }
}
```
#### 음수와 연산자 구분
입력을 받게 되면 연산자를 기준으로 피연산자를 나누기 때문에 `-`의 경우 음수와 연산자의 구분이 어렵습니다. 연산자는 모양이 같은 이모지를 사용하여 음수와 구분할 수 있게 했습니다.
```swift
enum Operator: Character, CaseIterable, CalculateItem {
    case add = "+"
    case subtract = "−"
    ...
}
```

---

### 조언을 얻고 싶은 점
`Formula`의 `result` 구현을 편하게 하기 위해 `operators`를 초기화하며 임의로 값을 넣었습니다. 원래 의미를 따지자면 사용자가 입력한 값들을 저장해야 하는 객체인데 개발자가 계산을 편하게 하기 위해 임의로 값을 넣어도 괜찮을까요?
<br>
고차 함수를 권장하는 말이 있어서 `for-in`을 `forEach`로 변경했습니다. `forEach`가 조금 더 빠른 것 같긴 하지만 `for-in`과 `forEach`의 차이가 얼마나 중요한지 잘 모르겠습니다.
`forEach`가 `for-in`과 다른 점
- `break` 또는 `continue`를 사용할 수 없다.
- 본문 클로저에서 `return` 문을 사용하면 외부 범위가 아닌 본문에 대한 현재 호출에서만 종료되며 후속 호출을 건너뛰지 않는다.

위의 차이가 생기는 이유

- `for-in` → 직접 구현하는 **반복문**
- `forEach` → 반복하고 싶은 내용을 **클로저**로 작성하여 `forEach`의 파라미터로 넘김

```swift
import Dispatch

let start0 = DispatchTime.now()
var a = Array(1...100000)
let end0 = DispatchTime.now()
let timeElapsed0 = end0.uptimeNanoseconds - start0.uptimeNanoseconds
// 119,020,792

let start1 = DispatchTime.now()
var b = Array(1...100000)
let end1 = DispatchTime.now()
let timeElapsed1 = end1.uptimeNanoseconds - start1.uptimeNanoseconds
// 42,072,083

let start2 = DispatchTime.now()
a.forEach {
    print($0)
}
let end2 = DispatchTime.now()
let timeElapsed = end2.uptimeNanoseconds - start2.uptimeNanoseconds
// 35,690,213,459

let start3 = DispatchTime.now()
for i in b {
    print(i)
}
let end3 = DispatchTime.now()
let timeElapsed3 = end3.uptimeNanoseconds - start3.uptimeNanoseconds
// 50,193,694,625
```
<br>

폴더 구조를 어떻게 해야 할지 잘 모르겠습니다. 지금은 익스텐션과 프로토콜 모두 모델에서 사용하기 때문에 모델에 넣었습니다. 하지만 이후에 컨트롤러에서 필요한 일이 생기게 되면 이 구조는 적합하지 않게 된다고 생각합니다. 혹시 폴더 구조에 대한 가이드라인 같은 것이 있을까요?
그리고 테스트의 경우 지금은 타입별로 테스트를 만들어 진행했는데 `모듈Tests` 폴더 안에 `타입별Tests.swift` 파일을 만드는 것이 좋을까요?
```
📦Calculator
 ┣ 📂Calculator
 ┃ ┣ 📂App
 ┃ ┃ ┣ 📜AppDelegate.swift
 ┃ ┃ ┗ 📜SceneDelegate.swift
 ┃ ┣ 📂Assets.xcassets
 ┃ ┃ ┣ 📂AccentColor.colorset
 ┃ ┃ ┗ 📂AppIcon.appiconset
 ┃ ┣ 📂Base.lproj
 ┃ ┣ 📂Controller
 ┃ ┃ ┗ 📜ViewController.swift
 ┃ ┣ 📂Error
 ┃ ┃ ┣ 📜ExpressionParserError.swift
 ┃ ┃ ┗ 📜FormulaError.swift
 ┃ ┣ 📂Model
 ┃ ┃ ┣ 📂Extension
 ┃ ┃ ┃ ┣ 📜Double+.swift
 ┃ ┃ ┃ ┗ 📜String+.swift
 ┃ ┃ ┣ 📂Protocol
 ┃ ┃ ┃ ┗ 📜CalculateItem.swift
 ┃ ┃ ┣ 📜CalculatorItemQueue.swift
 ┃ ┃ ┣ 📜ExpressionParser.swift
 ┃ ┃ ┣ 📜Formula.swift
 ┃ ┃ ┗ 📜Operator.swift
 ┃ ┣ 📂View
 ┃ ┃ ┣ 📂Assets.xcassets
 ┃ ┃ ┃ ┣ 📂AccentColor.colorset
 ┃ ┃ ┃ ┃ ┗ 📜Contents.json
 ┃ ┃ ┃ ┣ 📂AppIcon.appiconset
 ┃ ┃ ┃ ┃ ┗ 📜Contents.json
 ┃ ┃ ┃ ┗ 📜Contents.json
 ┃ ┃ ┗ 📂Base.lproj
 ┃ ┃ ┃ ┣ 📜LaunchScreen.storyboard
 ┃ ┃ ┃ ┗ 📜Main.storyboard
 ┃ ┗ 📜Info.plist
 ┣ 📂CalculatorItemQueueTests
 ┃ ┗ 📜CalculatorItemQueueTests.swift
 ┣ 📂ExpressionParserTests
 ┃ ┣ 📜ExpressionParserTests.swift
 ┃ ┗ 📜StubExpressionParser.swift
 ┣ 📂FormulaTests
 ┃ ┗ 📜FormulaTests.swift
 ┣ 📜.DS_Store
 ┗ 📜Calculator.xctestplan
```

---

### 참고
[forEach(_:) | Apple Developer Documentation](https://developer.apple.com/documentation/swift/array/foreach(_:))

[Swift) for - in / forEach 제대로 알고 쓰기](https://babbab2.tistory.com/95)

2023-06-07 06:31 UTC, jsa0224 requested changes
안녕하세요, 문!
이번 스탭은 미리 설계된 UML를 참고하여 프로젝트를 처음 진행하신 것만큼 어려움도 많으셨을 거라고 생각이 듭니다.

## 고민한 점에 대한 답변
> **Formula의 result를 계산하는 부분**

이 부분은 제가 아래 코멘트에서 답변 드리도록 하겠습니다.

> **음수와 연산자 구분**

스토리보드에 음수와 빼기 연산자의 기호가 다른데, 이 부분도 참고하시면 좋을 거 같습니다.

## 조언을 얻고 싶은 점에 대한 답변
> `Formula`의 `result` 구현을 편하게 하기 위해 `operators`를 초기화하며 임의로 값을 넣었습니다. 원래 의미를 따지자면 사용자가 입력한 값들을 저장해야 하는 객체인데 개발자가 계산을 편하게 하기 위해 임의로 값을 넣어도 괜찮을까요?

이 부분도 아래 코멘트로 답변 드렸습니다.

> 고차 함수를 권장하는 말이 있어서 `for-in`을 `forEach`로 변경했습니다. `forEach`가 조금 더 빠른 것 같긴 하지만 `for-in`과 `forEach`의 차이가 얼마나 중요한지 잘 모르겠습니다.

저는 고차함수가 코드의 간결함을 위해 존재한다고 생각합니다. 
문의 말씀대로 for문과 고차함수의 성능은 별 차이가 없지만, 간결하다는 장점이 크기 때문에 나중에도 유용하게 쓰실거라 생각이 듭니다.

> 폴더 구조를 어떻게 해야 할지 잘 모르겠습니다. 지금은 익스텐션과 프로토콜 모두 모델에서 사용하기 때문에 모델에 넣었습니다. 하지만 이후에 컨트롤러에서 필요한 일이 생기게 되면 이 구조는 적합하지 않게 된다고 생각합니다. 혹시 폴더 구조에 대한 가이드라인 같은 것이 있을까요?
그리고 테스트의 경우 지금은 타입별로 테스트를 만들어 진행했는데 모듈Tests 폴더 안에 타입별Tests.swift 파일을 만드는 것이 좋을까요?

폴더 구조는 어떤 아키텍처를 쓰느냐에 따라 조금씩 다른 걸로 알고 있습니다.
테스트 파일을 모듈 test 폴더에 넣어주신 건 잘해주신 거 같아요!
`protocol`이 어떤 `protocol`이냐에 따라 다르겠지만 지금은 `model`의 `protocol`이기 때문에 `model`에 넣어주시는 게 좋은 거 같습니다.
`extension`의 경우는 저는 `Util`이라는 폴더를 따로 만들어서 파일링을 해주는데요. 
이 부분은 따로 찾아보셔도 예제들이 많기 때문에 꼭 정답은 없는 부분입니다.

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
연산 프로퍼티로 구현하는 게 더 적절해보이네요!

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    @available(iOS 16.0, *)
이 부분은 왜 필요한가요?

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
- 해당 지역변수들은 불필요해보입니다.
- operandQueue, operatorQueue 두 개를 구현해서 Formula 객체에 주입해서 리턴해주면 되지 않을까요?
```swift
return Formula(operands: operandQueue, operators: operatorQueue)
```

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator> = CalculatorItemQueue<Operator>(enqueuedCalculatorItems: [Operator.add])
프로퍼티 값을 임의적으로 생성하는 게 위험하다는 생각도 드네요.

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/Calculator/Model/Formula.swift
> +    }
`while문`의 조건을 바꾸면 `operationCount` 변수가 불필요해지고, `result`도 0.0의 `default 값`을 가질 필요가 없어집니다.
한 번 고민해보시고, 리팩토링해주세요!

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +        XCTAssertEqual(resultOperators, expectedOperators)
이 부분은 `Formula`도 같이 테스트한 느낌이 듭니다.
`ExpressionParser.parse`는 어떤 기능을 하는지 생각해보시고, 그 기능에 대한 테스트만 진행해주세요!

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +    }
이 부분도 마찬가지입니다!

2023-06-07 06:31 UTC, jsa0224 commented on Calculator/ExpressionParserTests/StubExpressionParser.swift
> +}
ExpressionParser만 테스트 객체로 구현하셨는지 궁금합니다!

2023-06-07 10:44 UTC, hojun-jo commented on Calculator/Calculator/Model/Formula.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/506/commits/ff3f207e9b5d0fd9543e19243c653022c8da1e5f
`while`의 조건을 `isEmpty`로 바꾸고 `result`도 옵셔널로 선언하여 기본값 없이 사용할 수 있도록 했습니다.

2023-06-07 10:45 UTC, hojun-jo commented on Calculator/Calculator/Model/Formula.swift
> +    var operators: CalculatorItemQueue<Operator> = CalculatorItemQueue<Operator>(enqueuedCalculatorItems: [Operator.add])
값을 임의적으로 생성하지 않고 사용할 수 있도록 `result`를 수정했습니다.

2023-06-07 10:46 UTC, hojun-jo commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
`Formula`의 `result`의 `while` 조건을 `isEmpty`로 바꾸게 되며 `count`를 사용하지 않게 되었기 때문에 `count`는 지우고 `isEmpty`를 연산 프로퍼티로 구현했습니다.

2023-06-08 03:43 UTC, hojun-jo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    @available(iOS 16.0, *)
https://github.com/yagom-academy/ios-calculator-app/pull/506/commits/4a7231ab4778791f654d678d283073faaccb00b5
parse를 수정하면서 해당 부분도 없어졌네요!
찾아 주셔서 감사합니다~

2023-06-08 03:45 UTC, hojun-jo commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/pull/506/commits/4a7231ab4778791f654d678d283073faaccb00b5
큐 두 개를 구현해서 `return`할 때 `Formula`에 주입시키도록 하고 `operatorsQueue`를 만드는 로직도 수정 했습니다!

2023-06-08 03:48 UTC, hojun-jo commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +        XCTAssertEqual(resultOperators, expectedOperators)
https://github.com/yagom-academy/ios-calculator-app/pull/506/commits/95c6d4834b9f613b32d47c2b1eaa48dd75599f17#diff-07be587a376bff53f69a0d52d7bdce5690d716f942b5c5498ac01350c28d4914
`Formula`까지 가지 않고 테스트 객체 내에서 기능에 대한 테스트를 끝낼 수 있도록 `StubExpressionParser`의 프로퍼티로 `operandsQueue`와 `operatorsQueue`를 두고 테스트 했습니다.

2023-06-08 03:49 UTC, hojun-jo commented on Calculator/ExpressionParserTests/ExpressionParserTests.swift
> +    }
https://github.com/yagom-academy/ios-calculator-app/commit/95c6d4834b9f613b32d47c2b1eaa48dd75599f17#diff-07be587a376bff53f69a0d52d7bdce5690d716f942b5c5498ac01350c28d4914
이 부분도 위와 같이 수정되었습니다.

2023-06-08 03:59 UTC, hojun-jo commented on Calculator/ExpressionParserTests/StubExpressionParser.swift
> +}
componentsByOperators가 private이기 때문에 테스트를 위해 직접 접근하지 못 했습니다.
메서드 마다 테스트를 진행하기 위해 테스트 객체를 만들게 되었습니다.

2023-06-08 12:52 UTC, jsa0224 commented
수고하셨습니다, 문!
다음 스탭 진행하시면 됩니다!

2023-06-08 12:52 UTC, merged