계산기 [STEP 3] maxhyunm
yagom-academy/ios-calculator-app pull request #523
Opened 2023-06-09 09:04 UTC by maxhyunm

@jsa0224 
안녕하세요 솜!
늦은 STEP 3 PR 올려드립니다. 최대한 빨리 드리고 싶었는데 부족함이 많네요😖
멘토링 하면서 주셨던 의견을 참고하여 추가로 수정을 거쳤습니다!
수정하다 보니 발견하지 못했던 오류사항도 발견하여 함께 수정하였습니다😂😂
STEP 3이 지금까지 한 프로젝트 중에서 가장 어려운 고비였던 것 같습니다... 이제 시작이겠죠...

## 고민했던 사항
### 비대해지는 ViewController의 기능 쪼개기
- 버튼이 많고 기능 및 로직이 분리되는 지점이 너무나 다양하여 기능에 맞게 쪼개는 부분에서 굉장히 많은 고민을 하였습니다. 아직도 충분히 쪼개지 못한 것 같아서 정말 아쉽습니다. 뷰컨트롤러에서 진행해야 하는 오브젝트 변경 작업을 제외한 나머지 로직은 최대한 분리하고자 새로운 타입들을 생성하였습니다. ButtonTypeEnum을 통해 현재 눌린 버튼이 어떤 성질을 가진 것인지를 구분하도록 했고, LabelParser라는 타입을 새로 만들어 각 상황에 맞는 Operator, Operand 레이블 값들을 반환받도록 했습니다. 또한 CalculatorNamespace 타입을 열거형으로 생성하였고 static let으로 값을 주어서 case가 아니어도 접근 가능하도록 구현했습니다.
- 현재 Operator와 Operand 레이블 값에 접근하는 방법은 매번 옵셔널처리를 추가하지 않게끔 연산 프로퍼티를 활용하였습니다. 

### StackView에 쌓인 내용을 합쳐 계산하기
- 두 가지 메서드로 나누어서 StackView 내부의 레이블 텍스트 값을 배열로 만들고, 그 배열을 돌면서 저장할 내용을 하나의 String으로 만들도록 구현하였습니다. 여기서 실제 계산을 진행할 내용은 이미 연산이 끝난 부분 이후의 시점이 되어야 하기 때문에, 빈 연산자 값이 들어왔을 때를 기준으로 수식을 분리하도록 했습니다. 여전히 로직의 모양새가 깔끔하지 못해 고민이 많은 부분입니다.

### 자동 스크롤 구현
- 스크롤을 자동으로 최하단으로 이동하도록 하는 기능은 CGPoint로 좌표값을 생성하여 setContentOffset() 메서드를 통해 구현하였습니다. 해당 내용을 layoutSubviews()를 통해 매번 레이아웃 정보를 새로 계산할 수 있도록 하였습니다.

2023-06-09 11:11 UTC, jsa0224 requested changes
안녕하세요, 맥스!
프로젝트 잘 보았습니다!
MVC 패턴으로 진행하신 만큼 이번에 `ViewController`가 많은 역할을 담고 있어 문제점이라고 느끼신 거 같습니다.
중간 객체를 활용하시려고 하신 거 같은데, enum으로 구현하신 점에 대해 의문이 생겨 이 부분은 아래 코멘트로 질문 남겼습니다.

## 고민했던 점에 대한 답변
> ### 비대해지는 ViewController의 기능 쪼개기
> - 버튼이 많고 기능 및 로직이 분리되는 지점이 너무나 다양하여 기능에 맞게 쪼개는 부분에서 굉장히 많은 고민을 하였습니다. 아직도 충분히 쪼개지 못한 것 같아서 정말 아쉽습니다. 뷰컨트롤러에서 진행해야 하는 오브젝트 변경 작업을 제외한 나머지 로직은 최대한 분리하고자 새로운 타입들을 생성하였습니다. ButtonTypeEnum을 통해 현재 눌린 버튼이 어떤 성질을 가진 것인지를 구분하도록 했고, LabelParser라는 타입을 새로 만들어 각 상황에 맞는 Operator, Operand 레이블 값들을 반환받도록 했습니다. 또한 CalculatorNamespace 타입을 열거형으로 생성하였고 static let으로 값을 주어서 case가 아니어도 접근 가능하도록 구현했습니다.
> - 현재 Operator와 Operand 레이블 값에 접근하는 방법은 매번 옵셔널처리를 추가하지 않게끔 연산 프로퍼티를 활용하였습니다.

중간 객체를 활용하시려고 하신 거 같은데, `enum`으로 구현하신 점에 대해 의문이 생겨 이 부분은 아래 코멘트로 질문 남겼습니다.

> ### StackView에 쌓인 내용을 합쳐 계산하기
> - 두 가지 메서드로 나누어서 StackView 내부의 레이블 텍스트 값을 배열로 만들고, 그 배열을 돌면서 저장할 내용을 하나의 String으로 만들도록 구현하였습니다. 여기서 실제 계산을 진행할 내용은 이미 연산이 끝난 부분 이후의 시점이 되어야 하기 때문에, 빈 연산자 값이 들어왔을 때를 기준으로 수식을 분리하도록 했습니다. 여전히 로직의 모양새가 깔끔하지 못해 고민이 많은 부분입니다.

시뮬레이터로 실행해보면서 문제점이 있었는데, 아마도 이 부분의 구현과정에서 나는 오류 같습니다. 
빈 String에 연산자와 피연산자를 담아서 `parse`하면 될 거 같은데, 배열을 돌 필요가 있는지 잘 모르겠습니다!

> ### 자동 스크롤 구현
> - 스크롤을 자동으로 최하단으로 이동하도록 하는 기능은 CGPoint로 좌표값을 생성하여 setContentOffset() 메서드를 통해 구현하였습니다. 해당 내용을 layoutSubviews()를 통해 매번 레이아웃 정보를 새로 계산할 수 있도록 하였습니다.

저는 `layoutSubviews()` 호출하는 건 그렇게 효율적인 거 같지 않아, 아래 코멘트에 3가지 메서드를 비교해보시라고 코멘트 남겼습니다. 

## 보여지는 문제상황

|입력단계에서 `numberFormatter`가 적용되지 않는 문제|연산 과정에서 0으로 리셋되는 문제|
|:----:|:----:|
|![ezgif com-video-to-gif (2)](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/9f2de945-ccf1-4d64-85c7-d28b765de1ce)|![ezgif com-video-to-gif (3)](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/d6134b92-bfaf-4bdb-aa31-6559de424c4f)|

시뮬레이터로 실행할 때, 해당 문제들이 나옵니다.
계속 중간에 0이 추가되는 건 다른 기능 테스트가 불가한 큰 버그이기 때문에, 이 부분 수정해주시면 다른 부분들도 확인 가능할 거 같습니다.

2023-06-09 11:11 UTC, jsa0224 commented on Calculator/Calculator/Controller/Enum/LabelParser.swift
> +enum LabelParser {
`LabelParser` 객체를 `enum`으로 구현하신 이유가 있으실까요?

2023-06-09 11:11 UTC, jsa0224 commented on Calculator/Calculator/Controller/MainViewController.swift
> +    }
```suggestion
    private func setIsZero(senderTitle: String) {
        if senderTitle == CalculatorNamespace.Zero ||
           operandValue == CalculatorNamespace.Zero {
            isZero = true
        }
        
        if isZero && operandValue != CalculatorNamespace.Zero {
            if operatorValue != CalculatorNamespace.Empty {
                addNewFormulaStackView(LabelParser.getDefaultLabelValues())
            }
            
            isZero = false
        }
    }
```
간혹 코드에 `조건문` 혹은 `guard문`을 개행없이 구현하시는 경우가 있으신데, 저는 이런 컨벤션이 가독성에 좋다고 생각이 듭니다!

2023-06-09 11:11 UTC, jsa0224 commented on Calculator/Calculator/Controller/MainViewController.swift
> +        formulaListScrollView.layoutSubviews()
` layoutSubviews()`, `setNeedsLayout()`와 `layoutIfNeeded()`의 차이는 무엇인가요?

2023-06-09 13:07 UTC, maxhyunm commented on Calculator/Calculator/Controller/Enum/LabelParser.swift
> +enum LabelParser {
특별한 이유는 없었습니다! 타입 내부 내용은 static 메서드로만 구현할 예정이었고, ExpressionParser가 enum타입으로 이미 존재하기 때문에 형식을 맞추면 조금 정리된 느낌이 들 것 같아서 enum을 선택했습니다☺️

2023-06-09 13:08 UTC, maxhyunm commented on Calculator/Calculator/Controller/MainViewController.swift
> +    }
개행을 잊고 진행한 부분들이 있었네요ㅠㅠ! 수정 적용해 두겠습니다!

2023-06-09 13:14 UTC, maxhyunm commented on Calculator/Calculator/Controller/MainViewController.swift
> +        formulaListScrollView.layoutSubviews()
작업할 당시에는 세 가지 함수의 차이점을 모르고 작업했었는데, 찾아보니 layoutSubviews()는 전체 레이아웃을 업데이트하기 위해 하위 views로 재귀 호출을 하기 때문에 작업에 따른 비용이 큰 메서드로 공식적으로 직접 호출을 삼가라고 되어 있었네요ㅠㅠ!!! 뒤의 두 가지 메서드는 모두 layoutSubviews()를 활용하기 위한 메서드로, 이 두 가지를 사용하는 게 권장된다는 것을 이해했습니다. setNeedsLayout()은 변경사항이 다음 update cycle에 적용되는 방식이고, layoutIfNeeded()는 당장 변경사항을 적용할 수 있도록 하는 메서드인 것으로 확인했는데(즉 두 메서드의 차이는 layoutSubviews()를 호출하는 시점), 계산기같은 경우는 반드시 setNeedsLayout()을 적용해도 충분한 작업인 것 같아서 해당 메서드로 수정 진행하겠습니다.

2023-06-09 14:11 UTC, jsa0224 commented
안녕하세요, 맥스! 
시뮬레이터로 테스트 중에 오류를 발견해서 다시 한 번 코멘트 남깁니다.
|소수점이 안 찍히는 오류|16자리까지 9를 입력했을 때 10000....000으로 바뀌는 오류|
|:----:|:----:|
|![ezgif com-video-to-gif (1)](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/542774bb-9a11-4fa7-98db-e50b92d9d928)|![ezgif com-video-to-gif](https://github.com/yagom-academy/ios-calculator-app/assets/94514250/0f4a6872-e9e3-4341-a731-2662767c1126)|

ㅠㅠ... 파이팅입니다👍

2023-06-09 23:36 UTC, maxhyunm commented
@jsa0224 
솜, 주말에 알림이 가게 해서 죄송합니다! 두 가지 오류 수정 완료했습니다😂 두 번째 오류가 잡히지 않아서 한참 헤맸는데... Double 타입에서 사용할 수 있는 최대값을 넘어갔기 때문으로 이해하여, NSDecimalNumber로 타입 변경 후 진행하니 정상적으로 출력되는 것을 확인했습니다.

2023-06-11 03:06 UTC, jsa0224 commented
수고하셨습니다, 맥스!
이번 계산기 프로젝트 많이 어려우셨을텐데, 끝까지 하시는 모습 너무 멋있습니다👍

2023-06-11 03:06 UTC, merged