계산기 [STEP1] Kiseok
yagom-academy/ios-calculator-app pull request #548
Opened 2023-10-03 13:40 UTC by carti1108

@Rhode-park 
안녕하세요! Rhode! step1 PR 보냅니다!
아직 배우지 못한 부분들을 구현하느라 부족한 부분이 많다고 생각합니다.
피드백 주시면 열심히 배우고 고쳐보겠습니다!

## 고민되었던 점
- queue를 struct로 할지 class로 할지 고민했습니다.
-> 프로젝트 내에서 queue를 상속해야할 경우는 없을 것 같아서 struct로 구현하였습니다.
- queue구현 시 linked list와 double stack 중 무엇으로 할지 고민했습니다.
-> 두 방식 모두 탐색하는 것을 빼고는 시간 복잡도가 O(1), 하지만 linked list로 구현 시 Node class를 참조하는 것 때문에 성능에서 double stack이 더 우월할 것이라는 생각을하여 double stack으로 구현하였습니다.
- queue를 generic 타입으로
-> 계산기 프로젝트 구현 시 숫자만 입력받는 것이 아닌 연산자도 사용하게 되어 여러 타입에서 사용할 수 있도록 제네릭 타입으로 구현하였습니다.
- queue에서 다루는 요소는 CalculateItem프로토콜을 준수해야한다.
-> 요구사항에서 queue에서 다루는 요소는 CalculateItem프로토콜을 준수해야 한다고 해서 지금 당장 unit test에서 사용할 타입인 Int타입을 Extension을 통해 CalculateItem 프로토콜을 따르도록 구현하였습니다.

## 조언을 얻고 싶은 부분
- queue를 구현하긴 했지만 처음 구현하는 부분이라 많이 어색하고 제가 제대로 구현한게 맞는지 의문이 듭니다.
- 시간 복잡도와 메모리 성능 부분에서 어느 것에 더 중점을 두고 코드를 짜는게 좋은지 궁금합니다.
- 처음 혼자 프로젝트를 진행하다 보니 제가 보기에도 커밋 단위를 엉망으로 나누었다고 생각합니다. 커밋 단위에 대해서 피드백 주시면 step2부터는 피드백 주신대로 최대한 노력하겠습니다.
- 테스트 메서드 네이밍은 잘 알아볼 수 있게만 적는다면 어떤 식으로 네이밍을 해도 상관없는지 궁금합니다.

2023-10-05 13:37 UTC, Rhode-park requested changes
## ✅ 고민되었던 점
> * queue를 struct로 할지 class로 할지 고민했습니다.
> -> 프로젝트 내에서 queue를 상속해야할 경우는 없을 것 같아서 struct로 구현하였습니다.

Queue를 구현하는데에 있어서 struct를 사용할지, class를 사용할지 고민하셨군요!
Queue를 복사하거나 상속해야할 일이 없으니, 그 관점에서는 struct가 더 좋은 선택일 수 있겠네요.
물론, [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes#Use-Classes-When-You-Need-to-Control-Identity)에 다음과 같은 말이 나와있긴 합니다:
* Use structures by default.

그런데, Mutability나 Reference semantics 등의 관점에서도 생각해보셨을까요?
**class의 사용이 더 적합하다고 말씀드리는 것은 아닙니다.**
다른 관점에서도 struct와 class의 사용에 대해서 생각해보셨는지 궁금합니다.
지금 이 상황에서 struct로 구현하는 것이 class로 구현하는 것보다 나은 이유들이 무엇이 있을까요?


> * queue구현 시 linked list와 double stack 중 무엇으로 할지 고민했습니다.
> -> 두 방식 모두 탐색하는 것을 빼고는 시간 복잡도가 O(1), 하지만 linked list로 구현 시 Node class를 참조하는 것 때문에 성능에서 double stack이 더 우월할 것이라는 생각을하여 double stack으로 구현하였습니다.

Queue를 구현하는 데에 어떤 방법들이 있을까요?
Array를 사용하는 방법, Linked List를 사용하는 방법, Double Stack을 사용하는 방법 정도가 있을 것 같습니다.
각각의 장단점이 어떻게 될까요?
간단하게 공부해보시고 답변 부탁드립니다.


> * queue를 generic 타입으로
> -> 계산기 프로젝트 구현 시 숫자만 입력받는 것이 아닌 연산자도 사용하게 되어 여러 타입에서 사용할 수 있도록 제네릭 타입으로 구현하였습니다.

타입에 대한 고민을 많이 하신 것이 느껴집니다. 멋집니다!


> * queue에서 다루는 요소는 CalculateItem프로토콜을 준수해야한다.
> -> 요구사항에서 queue에서 다루는 요소는 CalculateItem프로토콜을 준수해야 한다고 해서 지금 당장 unit test에서 사용할 타입인 Int타입을 Extension을 통해 CalculateItem 프로토콜을 따르도록 구현하였습니다.

수고하셨습니다!

## ✅ 조언을 얻고 싶은 부분
> * queue를 구현하긴 했지만 처음 구현하는 부분이라 많이 어색하고 제가 제대로 구현한게 맞는지 의문이 듭니다.

코멘트 드렸습니다.

> * 시간 복잡도와 메모리 성능 부분에서 어느 것에 더 중점을 두고 코드를 짜는게 좋은지 궁금합니다.

아무래도, time complexity와 memory usage 사이에는 트레이드 오프가 있을 수밖에 없겠네요.
둘 사이의 적절한 balance를 유지하는 것이 좋을 것 같지만, 어느 하나를 선택해야하는 순간이 오겠네요.
이것을 선택하는 기준은 해당 프로젝트가 어떤 프로젝트냐에 따라 달라질 것 같습니다.
기석께서 하고 있는 `계산기`는 어떤 프로젝트이며, 어떤 부분에 더 중점을 두어야할까요?
고민해보시고, 답변 부탁드립니다.

> * 처음 혼자 프로젝트를 진행하다 보니 제가 보기에도 커밋 단위를 엉망으로 나누었다고 생각합니다. 커밋 단위에 대해서 피드백 주시면 step2부터는 피드백 주신대로 최대한 노력하겠습니다.

commit 단위가 엉망으로 나뉘어졌다고 생각하시는 이유가 있을 것 같은데, 그 이유가 궁금합니다.
commit 단위를 어느정도로 나누는 것이 적절하다고 생각하시나요?
정답은 없습니다만, 저는 **One Action, One Commit**이라고 생각합니다.
함수나 메서드를 기능단위로 분리하듯이, commit도 기능단위로 분리하는게 좋지 않을까 생각이 듭니다.
그러면, commit을 나누는 기석만의 기준을 정해볼까요?

> * 테스트 메서드 네이밍은 잘 알아볼 수 있게만 적는다면 어떤 식으로 네이밍을 해도 상관없는지 궁금합니다.

정답은 없다고 생각합니다.
다만, 저는 **개인적으로** 이런 방식으로 테스트 메서드 네이밍을 하곤 합니다:
`test_given_when_then`혹은 `test_when_given_then`
given, when, then에 따라서 Test Code를 진행하기 때문에, 그를 순차적으로 잘 표현하는 네이밍이면 좋지 않을까 하는 생각에서입니다.
예시로 몇 가지 코멘트 달아보았으니 확인해보시길 바랍니다.
이 역시 마찬가지로 기석만의 기준을 정해보는 것은 어떠신지요?


## ✅ 드리고 싶은 말씀
### 1️⃣ Test Code와 Given-When-Then
Test code를 작성하실 때, 주석으로 Given-When-Then을 나눠주시면 더 보기 좋을 것 같습니다.
Given-When-Then의 순서로 주어진 상황과 가정 그리고 결과를 나눠보면 좋을 것 같습니다.
그리고, Test Code의 Coverage가 100%에 가까울 수록 좋습니다.

2023-10-05 13:37 UTC, Rhode-park commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +//  File.swift
주석의 내용을 수정해보면 어떨까요?
파일명이 반영되면 좋을 것 같습니다.

2023-10-05 13:37 UTC, Rhode-park commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var dequeueBox: [Element] = []
외부에서 읽기만 가능하고, 내부에서는 쓰기가 가능하게 하면 어떨까요?

2023-10-05 13:37 UTC, Rhode-park commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var front: Element? {
front보다는 peek이라는 네이밍을 사용하는 것이 어떨까요?

2023-10-05 13:37 UTC, Rhode-park commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    @discardableResult
`@discardableResult`는 어떨 때 사용하는 것인가요?
설명 부탁드립니다.

2023-10-05 13:37 UTC, Rhode-park commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
stack이 빈 상황을 Given이나 When으로 보여주고, result로 True가 나온다는 걸 확인하면 좋을 것 같습니다.
마찬가지로 네이밍 역시, 다음과 같은 방식이면 좋을 것 같습니다:
`text_isEmpty프로퍼티를확인할시_비어있을때_True를 반환한다.`

2023-10-05 13:37 UTC, Rhode-park commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
마찬가지로 stack이 비어있지 않은 상황을 given, `isEmpty` 프로퍼티를 찍어본 상황을 when, 결과를 then으로 나타내면 좋을 것 같습니다.
그리고, enqueue를 통해 비어있지 않은 stack을 만들어주면, `isEmpty`에 대한 test code가 아닌 것 같습니다.
init등을 통해서 비어있지 않은 stack을 구현해보는 것은 어떨까요:
```swift
func test_isEmpty프로퍼티를확인할시_요소가하나라도있을때_False를반환한다() {
    //given
    sut = .init([1])
    
    //when
    let result = sut.isEmpty
    
    //then
    XCTAssertFalse(result)
}
```
이런식으로 해볼 수 있을 것 같습니다.

2023-10-05 13:37 UTC, Rhode-park commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_count가옳게출력되는지테스트() {
`test_count프로퍼티를확인할때_1과2와3이들어있을시_count가3이출력된다()`
이런 방식으로 메서드 네이밍을 하면 더 좋을 것 같습니다.

2023-10-06 00:59 UTC, carti1108 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    @discardableResult
현재 메서드에서 리턴값을 사용하지 않아서 warning 메세지를 띄우는데 이 키워드를 사용하면 warning 메세지를 띄우지 않습니다.

2023-10-06 01:03 UTC, carti1108 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +//  File.swift
수정 완료했습니다!

2023-10-06 01:04 UTC, carti1108 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var dequeueBox: [Element] = []
두 프로퍼티 모두 private(set)으로 설정해주었습니다!

2023-10-06 01:04 UTC, carti1108 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var front: Element? {
수정 완료했습니다!

2023-10-06 01:04 UTC, carti1108 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
수정 완료했습니다!

2023-10-06 01:11 UTC, carti1108 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
CalculatorItemQueue에 initializer를 만들어 수정했습니다!

> enqueue를 통해 비어있지 않은 stack을 만들어주면, isEmpty에 대한 test code가 아닌 것 같습니다.

1. 위 부분의 이유가 궁금합니다,,
2. 지금 프로젝트에서는 테스트를 제외하고는 인스턴스 생성 시 초기값을 넣어줘야할 경우는 없을꺼같은데 그렇다면 뭔가 테스트를 위한 코드를 작성하게 된 느낌입니다. 괜찮을까요?

2023-10-06 01:12 UTC, carti1108 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_count가옳게출력되는지테스트() {
수정 완료했습니다!

2023-10-06 01:15 UTC, carti1108 commented
> 다른 관점에서도 Struct와 Class의 사용에 대해서 생각해보셨는지 궁금합니다.
지금 이 상황에서 Struct로 구현하는 것이 Class로 구현하는 것보다 나은 이유들이 무엇이 있을까요?

말씀해주신 부분들의 관점까지 고려하지는 않았습니다,,
제가 Class와 Struct를 고르는 기준은 
- 인스턴스의 동일성이 필요한가
- 참조를 해야하는가
- 상속을 해야하는가

이 경우를 제외하면 Struct를 사용합니다.
지금 이 프로젝트에서는 사실 어떤 타입을 선택하든 문제가 생길꺼라고 생각하지는 않습니다. 그렇다면 reference counting을 하게되는 Class보다는 Struct를 사용하는게 메모리 성능 면에서 더 나을 것이라고 생각하여 Struct를 선택하였습니다.

> Queue를 구현하는 데에 어떤 방법들이 있을까요?
Array를 사용하는 방법, Linked List를 사용하는 방법, Double Stack을 사용하는 방법 정도가 있을 것 같습니다.
각각의 장단점이 어떻게 될까요?

- Array
Array 하나 사용
enqueue 시간 복잡도 O(1) 시간복잡도
dequeue시 맨 앞에 원소를 없애주고 뒤 요소들을 앞으로 옮겨주는 과정 때문에 O(n)의 시간복잡도를 가짐
- Linked List
데이터가 Array에 저장되는 것이 아닌 각각 떨어져있고 그것들이 연결됨
Node 사용
각각의 Node에 데이터가 저장되어있고, 다음 Node를 가리키는 주소값이 저장되어있음
enqueue, dequeue O(1) 시간 복잡도
- Double Stack
두 개의 Array(inbox, outbox) 사용
inbox에 삽입, outbox에 inbox의 거꾸로 뒤집어 할당
enqueue, dequeue O(1) 시간 복잡도

Linked List와 Double Stack 중 하나를 고민했지만 Node Class를 참조하는 방식의 Linked List보단 Double Stack이 메모리 성능이 더 좋다고 생각해 Double Stack을 선택했습니다.

> 기석께서 하고 있는 계산기는 어떤 프로젝트이며, 어떤 부분에 더 중점을 두어야할까요?
고민해보시고, 답변 부탁드립니다.

현 프로젝트는 값을 넣고, 연산하고, 값을 빼는 기능들이 주라고 생각합니다. 따라서 현 프로젝트에서는 시간 복잡도를 더 신경쓰는게 맞다고 생각합니다.

> commit 단위가 엉망으로 나뉘어졌다고 생각하시는 이유가 있을 것 같은데, 그 이유가 궁금합니다.

저 또한 로데께서 말씀해주신대로 One Action, One Commit이 좋다고 생각합니다.
하지만 이번 프로젝트에서는 메서드를 여러개를 구현한 후 commit을 남기게되어 엉망이라고 생각했습니다. 

추가로 step1은 queue를 구현하는데 급급해서 TDD 방식으로 진행하지 못했습니다. 다음 step부터는 TDD 방식으로 진행하도록 노력해보겠습니다.

2023-10-08 05:12 UTC, Rhode-park commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    @discardableResult
조금 더 자세한 이유를 알고 있으면 좋을 것 같습니다.
warning은 왜 뜨는 것이며, 어떤 내용을 경고하고 있으며, 저걸 붙이면 왜 없어지나요?

2023-10-08 05:14 UTC, Rhode-park commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
1. test code에 test하고자 하는 메서드 뿐만 아니라 다른 메서드까지 들어가니까 독립성이 조금 떨어진다고 생각합니다.
2. test를 왜 하는 것일까요? 저는 해당 기능이 잘 돌아가고 있는지를 정확히 판단하기 위해서 한다고 생각합니다. 그를 위해서 조금의 추가적인 코드들은 용인 되어야한다고 생각합니다.

2023-10-08 05:15 UTC, Rhode-park commented
코멘트 추가적으로 달았고 이 부분 확인 후 DM주시면 바로 merge해드리겠습니다!

2023-10-08 05:39 UTC, carti1108 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    @discardableResult
dequeue 메서드 사용 시 요소를 리턴하게 되는데 이 요소를 사용하지 않는다면 이 리턴값이 사용되지 않는다는 내용의 warning 메세지를 띄웁니다.  @discardableResult 속성을 사용하게 되면 값을 반환하는 메서드가 리턴값을 사용하지 않아도 경고가 뜨지 않도록 만들어줍니다.

2023-10-09 17:15 UTC, merged