계산기 [STEP1] 미르
yagom-academy/ios-calculator-app pull request #549
Opened 2023-10-04 04:55 UTC by mireu79

@Tediousday93 
안녕하세요 Rowan! 게산기 STEP1 PR보냅니다!
잘부탁드립니다!

### 고민했던점 
- swift에선 Queue를 지원하지 않아 어떻게 구현해야하는지에 대한 고민했고, 대기행렬로 보내면 알아서 분산처리를 해주니 속도가 빠를수 있겠다라고 생각했습니다.
- Quee를 구현할떄 enqueue()로 큐를 넣어주는 메서드와 다시 삭제하는 dequeue()를 구현했고, 초기화가 될수 있게 clear()메서드를 구현해줬습니다.
- step이 더 진행되어봐야겠지만 프로토콜 채택을 왜 해야하는지에 대한 의문이 생겼습니다.
- 다양한 타입을 받아 사용할수 있는 제네릭타입을 사용해봤는데, 기능구현에 대한 감이 잡히지 않아 우선 String타입을 구현해줬습니다.
___
### 조언을 얻고 싶은 부분
- TDD기반으로 처음해보는 프로젝트인데 테스터케이스를 작성할때 어느정도까지 진행해야하는지 궁금하고, 테스트케이스의 네이밍은 적절한지 궁금합니다.
- 프로젝트에는 따로 설명되어 있지 않는데 MVC로 파일을 분리해줘야할지 궁금합니다.
- Queue에 대한 메서드를 구현할때 시간복잡도를 고려하며 구현해야하는 것인지 궁금합니다.

2023-10-05 06:38 UTC, Tediousday93 requested changes
안녕하세요 미르 😊
step1 고생하셨습니다.

제가 드리는 코멘트는 정답이 아닙니다. PR을 통해 저와 함께 고민하고 여러분이 스스로 코드를 작성한 이유를 설명할 수 있게 되는 것을 목표로 하면 좋겠습니다. 합당한 이유를 말씀해주시면 코멘트는 참고만 하고 넘어가셔도 좋습니다! 👍

3주간 함께 성장하는 시간이 되었으면 좋겠네요.
잘 부탁드립니다 ☺️

이번 프로젝트 마무리까지 화이팅입니다! 💪

---

### ✅ 고민했던 점
**Queue**
* Queue의 필수적인 메서드를 잘 구현해주셨습니다 👍
* 분산 처리는 무엇이고 누가 알아서 해주는건가요? 🤔
* 속도가 빠르다는 것은 큐의 시간복잡도를 고려한 말씀이실까요? 아니면 단순히 하드웨어의 성능이 좋아져서 연산 속도가 빨라진 것을 의미하신걸까요?
* 기능 구현에 대해 감이 잡히지 않았다는 말씀은 Queue의 책임(역할)에 대한 파악이 명확하지 않아서 그럴 수도 있을 것 같아요. Queue는 한 마디로 무슨 책임을 가질까요?

**Protocol**
* 요구사항을 다시 살펴보고, 프로토콜을 누가 채택해야하는지 고민해보시면 좋을 것 같아요 ☺️
* 빈 프로토콜의 의미를 찾으셨다면 코멘트에 남겨주세요 💪

**Generic**
* Queue 타입에 제네릭을 잘 활용해주셨네요 👍 </br> 제네릭에 대해 자세히 알아보시는 것도 좋겠습니다. WWDC 영상이나 공식문서를 참고하셔서 직접 정리하시고 공유해주시면 더욱 좋습니다 😄
* 작성해주신 대로 다양한 타입을 받아 사용할 수 있도록 어떤 타입이 들어올 자리(placeholder)를 표현하는 녀석이기 때문에, generic한 타입을 사용하는 부분에서 타입을 결정해주는 것이 맞습니다. (ex. `Array<T>` 타입의 경우, 사용할 때 `Array<Int>`, `[Int]` 로 타입을 작성하는 것과 동일합니다.)


</br>

### ✅ 조언을 얻고 싶은 부분
**Unit Test**
* test case 네이밍을 전반적으로 쉽게 이해할 수 있도록 잘 작성해주신 것 같아요 👍 다만, 개인적으로는 마지막에 ~하는지 보다는 명확하게 ~한다, ~된다 로 맺어주시면 좋을 것 같습니다 💭
* test case를 어느 정도까지 만들어야 하는가는 직접 기준을 설정하시는 것이 가장 좋습니다! 너무 case가 많아지면 Test를 작성하는 데에 엄청난 시간이 들겠죠?! 🤔
* code coverage를 90% 이상 채우겠다 등의 기준이 있으면 좋을 것 같아요. (프로젝트 내에 유닛테스트가 불가능한 코드도 있을 수 있기 때문에 가능한 만큼만 진행하는 것이 좋습니다 👀)

**Architecture**
* 프로젝트 아키텍처는 Cocoa MVC를 기본적으로 가져간다고 생각하시면 될 것 같아요.

**시간복잡도**
* 사실 하드웨어의 성능이 좋아지면서 시간복잡도가 큰 문제가 되지는 않을 것 같아요. 하지만 고려하면 좀 더 효율적으로 연산할 수 있다는 의미가 있지 않을까요?
* 반드시 고려하여 작성해야 한다는 것은 아닙니다. 하지만 고민하시는 만큼 또 배워가는 것이 있을 거에요 👍

</br>

### Feedback
* UML을 먼저 작성하셨군요! 설계 먼저 하시는 모습이 인상깊습니다. 👍
* PR도 readme와 같이 하나의 글이라고 생각합니다. 글을 작성할 때는 항상 톤앤매너를 지켜주시면 독자에게 도움이 된답니다! 😊
* 동일한 의미의 다른 단어를 사용하기 보다는 일관성 있게 한 가지만 사용하는 것이 좋을 것 같아요. (Queue, 대기행렬)
* 고민한 점이 조금 더 상세해지면 좋겠습니다 👀

---
</br>

코드 코멘트 확인해주시고, 누락된 접근제어와 프로토콜 채택 부분만 수정해주시면 머지하도록 하겠습니다. 😊

2023-10-05 06:38 UTC, Tediousday93 commented on Calculator/Calculator/CalculateItem.swift
> +}
빈 프로토콜을 잘 작성해주셨네요 👍

중괄호 내에 내용이 없는 경우 간략히 한 줄로 쓰기도 합니다.
```suggestion
protocol CalculateItem { }
```

2023-10-05 06:38 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
Queue를 제네릭 타입으로 잘 만들어주셨네요 👏
하지만 프로토콜을 채택하는 대상이 요구사항과 맞지 않는 것 같아요. 💭

2023-10-05 06:38 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var queue: [T] = []
Queue 타입 내부에 queue라는 프로퍼티가 있는 것이 조금 어색하다고 느껴집니다.
Queue가 관리할 T들의 모음이라는 의미가 보이는 네이밍으로 수정해주세요!

이 프로퍼티는 외부에서 알 필요가 있을까요?

2023-10-05 06:38 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    }
필수적인 메서드와 부가적인 것들까지 잘 작성해주셨네요 👍

2023-10-05 06:38 UTC, Tediousday93 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
테스트 환경 통제 👍

2023-10-05 06:38 UTC, Tediousday93 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
전반적으로 각 메서드가 어떤 기능을 하는지 알 수 있도록 test case의 이름을 잘 지어주셨네요. 👍👍👍
Queue타입의 code coverage도 100% 채워주셨습니다 👏

2023-10-05 11:37 UTC, mireu79 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
프로토콜을 채택하는 대상이 요구사항과 맞지 않는 것 같아 수정하였고, 확장을 통해 String타입을 구현해줬습니다!

2023-10-05 11:39 UTC, mireu79 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var queue: [T] = []
네이밍적으로 어색하여 `list`로 수정을 해줬고, 프로퍼티에 `private`를 통해 접근제어를 해줬습니다.

2023-10-05 13:00 UTC, mireu79 commented
### ✅ 고민했던 점
Queue
- 👍
-  분산처리는 여러개의 쓰레드에서 Queue에서 쌓인 유사한 작업들을 알아서 분산되어 처리하는 것으로 알고 있습니다!
- 저는 분산처리를 하게되면 한쓰레드에서 할일을 여러 쓰레드로 나눠서 일을 해주기 떄문에 하드웨어의 성능이 좋아져 연산 속도가 빨라진다는 것을 의미했습니다!
- 큐는 쓰레드(작업을 수행하는 실질적인 주체)에 작업을 분배해주는 매니저(?)와 같은 역할을 한다고 생각합니다.

Protocol
- 제네릭 타입을 프로토콜을 따르는 타입만 사용할수 있도록 제약을 두어 프로토콜에 제약사항이 있다면 그 조건을 따라야 하기 떄문에 프로토콜을 비워뒀다고 생각합니다!

Generic
- 우선 제네릭이 필요한 이유는 구현내용은 같지만 타입만 다른경우 타입마다 모든경우를 다 정의해야 하는 불편함이 있어 포괄적인 제네릭을 사용해서 재사용하기도 쉽고, 코드의 중복을 줄일 수 있어 유연하게 대응할 수 있다는 장점이 있습니다!
___
조언을 주신 부분, 피드백을 주신 부분 확인하였습니다! 감사합니다!
앞으로 PR보낼떄 피드백주신 대로 유의해서 작성할수 있도록 하겠습니다!😊

2023-10-06 04:28 UTC, Tediousday93 commented
요구사항이 잘 반영되었네요!

**분산처리**
이 부분은 약간 현재 맥락과 맞지 않는 표현같아요. 분산처리가 무엇인지 정확히 알아볼 필요도 있을 것 같습니다. 💭
스레드 관련해서는 추후에 동시성 프로그래밍에 대해 학습하시고 다시 생각해보시면 좋겠습니다! 😊

**프로토콜**
빈 프로토콜의 의미를 잘 파악해주신 것 같아요 👍

**Generic**
간략하게 잘 정리해주셨네요. 👍 
나중에 더 깊이 알아보실 기회가 있을겁니다!

머지 하도록 하겠습니다!
고생 많으셨습니다.
다음 스텝도 화이팅 💪

2023-10-06 04:29 UTC, merged