계산기 [STEP1] 쥬봉이
yagom-academy/ios-calculator-app pull request #550
Opened 2023-10-04 05:28 UTC by jyubong

@Rhode-park 
안녕하세요 로데🫶🏻 쥬봉이입니다. 이번 프로젝트동안 잘부탁드립니다.
첫 PR 보냅니다.

### 고민이 되었던 점
#### 1. 큐 구현 방법
큐는 First In Frist Out(FIFO)방식의 자료구조로
큐를 구현하기위한 방법이 고민되었습니다. 제가 공부한 방법은 아래와 같습니다.
1. 배열
  - 장점 : append(), removeFirst() 등 기본으로 구현되어있어 큐를 구현하기 편리함
  - 단점 : 삭제할때 0번 인덱스 값 제거 후 인덱스를 1개씩 당겨야하기때문에 O(n)의 시간복잡도
  
2. LinkedList
  - 순차적으로 모인 데이터들의 모음으로, 각각의 데이터는 노드이며 각 노드는 다음 차례 노드의 주소를 가지고 있다.
  - 종류 : 단순 연결 리스트, 이중 연결 리스트, 순환 연결 리스트
  - 장점 : O(1)로 추가 및 삭제 가능
  - 단점 : 인덱스로 원소의 접근이 불가능하여 원소를 찾는데 O(n)의 시간 복잡도

3. Double Stack
  - 두개의 배열로 double stack 구현(inStack, outStack)
  - 장점 : O(1)로 추가 및 삭제 가능
  - 단점 : deQueue시 stack reversed() 해줘야함(outStack) - 시간복잡도는 O(1)

**시간복잡도와 공간복잡도**
||마지막 삽입|첫번째 삭제|peek(index)|공간|
|---|---|---|---|---|
|array|O(1)|O(n)|O(1)|O(n)|
|Linked List|O(1)|O(1)|O(n)|O(n)|
|Double Stack|O(1)|O(1)|O(1)|O(n)|

따라서, 해당 프로젝트에서 주로 `사용할 삽입과 삭제에 용이한 단순 연결 리스트`를 활용하여 큐를 구현하였습니다.

#### 2. UML
아래와 같이 UML을 작성하여 코드를 구현하였습니다.
![CalculatorItemQueue](https://github.com/yagom-academy/ios-calculator-app/assets/126065608/3eafea50-7c0b-49c1-a842-c810c6e92865)

#### 3. 제네릭 사용
CalculatorItemQueue에 `들어올 값이 숫자, 문자(+,- 등 연산자) 등 다양한 타입`이기때문에 재사용성을 생각하여 제네릭을 사용하였습니다.
그리고 CalculatorItemQueue에 이용될 값들은 CalculatorItem 프로토콜을 준수해야하기때문에 `<Element: CalculatorItem>로 제약조건`을 적용하였습니다.

### 조언을 얻고 싶은 부분
#### 1. 큐와 연결리스트가 올바르게 구현이되었는지
- 큐에서 `front와 rear의 경우 wiki에서는 각각이 처음과 마지막 인덱스를 나타낸다고 명시`되어있습니다. 하지만 다른 자료들을 참고하였을때 front와 rear를 들어간 값(즉, Element)로 표현하는 경우가 있었습니다. 저도 Test에서의 활용성을 생각해 Element로 구현하였는데 적절한지 의문입니다.
- LinkedList class 내에 Node class를 구현하였는데, Linked List가 Node의 생명주기를 관여하는 밀접한 관계라고 생각하여 내부에 구현하였습니다.
- LinkedList를 확장하여 index에 따른 Node를 구할 수 있도록 구현하였는데, 현재 큐에서는 활용이 안되지만 test에서의 활용성을 생각하여 구현하였습니다. 이부분이 test를 위한 코드 작성인 것 같아 우려가됩니다.

#### 2. Unit Test가 올바르게 구현되었는지
- TDD로 코드를 구현하려다보니 케이스를 다양하게 쪼개어 test를 하게되면서 test의 양이 많아졌습니다. `Unit Test가 올바르게 작성되고 있는지` 걱정입니다.
- 한 케이스에 대해 아래처럼 구현이 되었는데 정확성을 보기위해 `then에서 확인하는 로직이 많아졌습니다.` 이 부분이 괜찮은지 궁금합니다.
``` swift
func test_append호출시_count가2이상일때_tail에newNode가할당되는지() {
    // given
    let firstData: Int = 10
    let secondData: Int = 20
    let thirdData: Int = 30
    let forthData: Int = 40
    sut.append(firstData)
    sut.append(secondData)
    sut.append(thirdData)

    // when
    sut.append(forthData)

    // then
    XCTAssertEqual(sut.head?.data, firstData)
    XCTAssertEqual(sut[at: 1]?.data, secondData)
    XCTAssertEqual(sut[at: 2]?.data, thirdData)
    XCTAssertEqual(sut.tail?.data, forthData)
    XCTAssertTrue(sut[at: 3] === sut.tail)
}
```
- TDD로 코드를 구현하기위해 노력했으나 코드 작성 후 Test를 시행한 부분들도 있습니다🥲

2023-10-05 14:52 UTC, Rhode-park requested changes
## ✅ 고민되었던 점

> #### 1. 큐 구현 방법
> 큐는 First In Frist Out(FIFO)방식의 자료구조로
> 큐를 구현하기위한 방법이 고민되었습니다. 제가 공부한 방법은 아래와 같습니다.
> 1. 배열
>   - 장점 : append(), removeFirst() 등 기본으로 구현되어있어 큐를 구현하기 편리함
>   - 단점 : 삭제할때 0번 인덱스 값 제거 후 인덱스를 1개씩 당겨야하기때문에 O(n)의 시간복잡도
>   
> 2. LinkedList
>   - 순차적으로 모인 데이터들의 모음으로, 각각의 데이터는 노드이며 각 노드는 다음 차례 노드의 주소를 가지고 있다.
>   - 종류 : 단순 연결 리스트, 이중 연결 리스트, 순환 연결 리스트
>   - 장점 : O(1)로 추가 및 삭제 가능
>   - 단점 : 인덱스로 원소의 접근이 불가능하여 원소를 찾는데 O(n)의 시간 복잡도
> 
> 3. Double Stack
>   - 두개의 배열로 double stack 구현(inStack, outStack)
>   - 장점 : O(1)로 추가 및 삭제 가능
>   - 단점 : deQueue시 stack reversed() 해줘야함(outStack) - 시간복잡도는 O(1)
> 
> **시간복잡도와 공간복잡도**
> ||마지막 삽입|첫번째 삭제|peek(index)|공간|
> |---|---|---|---|---|
> |array|O(1)|O(n)|O(1)|O(n)|
> |Linked List|O(1)|O(1)|O(n)|O(n)|
> |Double Stack|O(1)|O(1)|O(1)|O(n)|
> 
> 따라서, 해당 프로젝트에서 주로 `사용할 삽입과 삭제에 용이한 단순 연결 리스트`를 활용하여 큐를 구현하였습니다.

큐를 구현하기 위한 세 가지 방법을 잘 조사하셨습니다. 멋집니다!
시간복잡도 역시 고려해주셨군요. 멋집니다!
Queue를 구현하는 데에 있어서 고민을 많이 하신게 느껴지며, 그에 따라 쥬봉이만의 명확한 이유가 있으신 것 같아 보기 좋습니다.

> #### 2. UML
> 아래와 같이 UML을 작성하여 코드를 구현하였습니다.
> ![CalculatorItemQueue](https://github.com/yagom-academy/ios-calculator-app/assets/126065608/3eafea50-7c0b-49c1-a842-c810c6e92865)

UML까지 미리 작성하셨군요.
UML을 작성하면 프로젝트에 필요한 청사진을 그릴 수 있습니다.
그래도, 프로젝틀를 많이 해보지 않은 입장에서는 사전에 UML을 작성하는 것이 까다로울 수 있는데, 멋지게 잘 해내셨습니다. 멋집니다!

> #### 3. 제네릭 사용
> CalculatorItemQueue에 `들어올 값이 숫자, 문자(+,- 등 연산자) 등 다양한 타입`이기때문에 재사용성을 생각하여 제네릭을 사용하였습니다.
> 그리고 CalculatorItemQueue에 이용될 값들은 CalculatorItem 프로토콜을 준수해야하기때문에 `<Element: CalculatorItem>로 제약조건`을 적용하였습니다.

멋집니다!

## ✅ 조언을 얻고 싶은 부분
> #### 1. 큐와 연결리스트가 올바르게 구현이되었는지
> - 큐에서 `front와 rear의 경우 wiki에서는 각각이 처음과 마지막 인덱스를 나타낸다고 명시`되어있습니다. 하지만 다른 자료들을 참고하였을때 front와 rear를 들어간 값(즉, Element)로 표현하는 경우가 있었습니다. 저도 Test에서의 활용성을 생각해 Element로 구현하였는데 적절한지 의문입니다.
> - LinkedList class 내에 Node class를 구현하였는데, Linked List가 Node의 생명주기를 관여하는 밀접한 관계라고 생각하여 내부에 구현하였습니다.
> - LinkedList를 확장하여 index에 따른 Node를 구할 수 있도록 구현하였는데, 현재 큐에서는 활용이 안되지만 test에서의 활용성을 생각하여 구현하였습니다. 이부분이 test를 위한 코드 작성인 것 같아 우려가됩니다.

공식문서는 아니지만, 연결리스트에 대해서 참고할만한 깃허브가 있어서 첨부해봅니다.
[swift-algorithm-club/Linked List](https://github.com/kodecocodes/swift-algorithm-club/tree/master/Linked%20List)
개념을 잡는 데에 도움이 되었으면 좋겠습니다.

> #### 2. Unit Test가 올바르게 구현되었는지
> - TDD로 코드를 구현하려다보니 케이스를 다양하게 쪼개어 test를 하게되면서 test의 양이 많아졌습니다. `Unit Test가 올바르게 작성되고 있는지` 걱정입니다.
> - 한 케이스에 대해 아래처럼 구현이 되었는데 정확성을 보기위해 `then에서 확인하는 로직이 많아졌습니다.` 이 부분이 괜찮은지 궁금합니다.
> ``` swift
> func test_append호출시_count가2이상일때_tail에newNode가할당되는지() {
>     // given
>     let firstData: Int = 10
>     let secondData: Int = 20
>     let thirdData: Int = 30
>     let forthData: Int = 40
>     sut.append(firstData)
>     sut.append(secondData)
>     sut.append(thirdData)
> 
>     // when
>     sut.append(forthData)
> 
>     // then
>     XCTAssertEqual(sut.head?.data, firstData)
>     XCTAssertEqual(sut[at: 1]?.data, secondData)
>     XCTAssertEqual(sut[at: 2]?.data, thirdData)
>     XCTAssertEqual(sut.tail?.data, forthData)
>     XCTAssertTrue(sut[at: 3] === sut.tail)
> }
> ```
> - TDD로 코드를 구현하기위해 노력했으나 코드 작성 후 Test를 시행한 부분들도 있습니다🥲

테스트코드에 대해서는 리뷰에서 말씀드렸습니다.

그리고, 물론 TDD로 코드를 구현하는 게 좋습니다.
그렇지만, 말은 누구나 그렇게 할 수 있는 것이고, 아직 코드 작성에 익숙하지 않은 사람이 TDD까지 지키는 것은 어려운 일이라고 생각합니다.
그래서 지금 코드 작성 후 Test를 시행한 것에 대해서 너무 주눅들지 않으셨으면 좋겠습니다.

## ✅ 드리고 싶은 말씀
### 1️⃣ Test Code와 init
Test Code를 작성할 시, Given의 상황에서 이미 전제 조건이 준비되어있어야한다고 생각합니다.
그렇지 않으면, append, enQueue 등을 통해서 전제 상황을 만들게 됩니다.
그러면, 하나의 기능만을 test하는 코드가 아닌 하나의 기능+append의 기능 혹은 하나의 기능+enQueue의 기능을 test하는 코드가 된다고 생각합니다.
그러므로, 가능하다면 init등을 통해서 전제 상황을 갖춰놓는 것이 어떨까요?
그렇다면, 불필요하게 다른 기능들을 추가할 필요가 없을것이며, then도 짧아질 수 있을것이라고 생각합니다.

두 개의 test code file이 같은 맥락을 가지고 있습니다.
드리고 싶은 말씀이 반복되어, 모든 곳에 코멘트를 달지는 않았습니다.
그러므로, 이 점에 주안점을 두어 test code를 처음부터 끝까지 천천히 보시고 리팩토링해보시면 좋을 것 같습니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +    }
class를 struct안에 넣어주신 이유가 있으실까요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +    private(set) var tail: Node<DataType>?
외부에서 읽기만 가능하고, 내부에서는 쓰기가 가능하게 해주셨군요. 멋집니다!

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +    var count: Int = 0
이 친구 외부에서 수정될 일이 있나요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +    var count: Int = 0
맨 처음에 count를 0으로 초기화 한 후, 각각의 메서드들에 따라서 count를 변경해주는 방법을 사용하시고 계십니다.
count 자체에 대한 프로퍼티나 메서드가 제대로 구현되어있지 않는 것 같습니다.
그런 방식보다는, count를 연산프로퍼티로 구현해봄은 어떨까요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +    }
Linked List가 비어있다면, head역시 nil이겠죠? 그걸 확인하는 방식으로 isEmpty를 구현해보면 어떨까요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +        count += 1
count에 대한 부분은 앞서 말씀드렸다싶이 따로 다뤄주시는 것이 좋을 것 같습니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +}
이 부분은 무엇을 위한 구현이죠?
추가적인 설명 부탁드려도 될까요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +        guard 0..<count ~= index else { return nil }
`~=`가 어떤 연산자인지 알고 계신가요?
설명 부탁드립니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    @discardableResult
`@discardableResult`는 어떨 때 사용하는 것인가요?
설명 부탁드립니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/LinkedListTests/LinkedListTests.swift
> +        sut.count = 0
count에 직접 접근하기보다는, count가 0인 상황 즉 linkedList가 비어있는 상황을 만들어주는게 더 좋을 것 같습니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/LinkedListTests/LinkedListTests.swift
> +    }
마찬가지로 count에 바로 접근하기보다는 empty하지 않은 상황을 만들어주는게 좋을 것 같습니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/LinkedListTests/LinkedListTests.swift
> +    }
append호출시 tail쪽만 확인해도 되지 않을까요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/LinkedListTests/LinkedListTests.swift
> +        sut.append(data)
(참고)이 부분 init을 통해서 구현해볼 수 있을까요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/LinkedListTests/LinkedListTests.swift
> +    }
마찬가지로 init을 통해서 linked list 셋업을 해주면 하나하나 확인할 일이 없을 것 같습니다.
그리고 tail에 newNode가 할당 된 것에 대한 테스트코드면 그 부분만 확인하는 것이 좋을 것 같습니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
data를 세 개씩이나 넣어봐야할 필요가 있을까요?
하나만 넣고 rear와 넣은 data의 일치성을 확인해도 좋을 것 같습니다.

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        sut.enQueue(thirdData)
init등을 통해서 enQueue 없이 given을 완성할 수 있을까요?

2023-10-05 14:52 UTC, Rhode-park commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.rear, thirdData)
rear가 세 번째 값이란 것과 front가 삭제되는 것은 무관한 내용인 것 같습니다.

2023-10-06 01:52 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +    var count: Int = 0
알려주신 LinkedList 자료 참고하여 count 부분을 연산프로퍼티로 수정하였습니다.
``` swift
    var count: Int {
        guard var node = head else {
            return 0
        }
        
        var count = 1
        
        while let next = node.next {
            node = next
            count += 1
        }
        
        return count
    }
```

2023-10-06 01:56 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +    var count: Int = 0
기존에는 test에서 count를 변경하여 given을 세팅해주어 private으로 바꾸기 어려웠습니다.
test 로직을 수정하고 count를 연산프로퍼티로 변경하여 해당 부분은 수정되었습니다.

2023-10-06 01:57 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +    }
head의 유무에따라 isEmpty가 변경되도록 수정하였습니다.
``` swift
  var isEmpty: Bool {
      return head == nil ? true : false
  }
```

2023-10-06 01:58 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +        count += 1
count 부분을 연산프로퍼티로 수정하면서 메서드에서 count를 조절해주었던 부분들을 삭제하였습니다.

2023-10-06 02:00 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +}
해당 subscript는 linkedlist에서 원하는 순서의 node을 확인할 수 있는 것이었습니다.
queue를 구현하기위한 linked list에서는 필요가 없는 부분이라고 생각하였지만 test과정에서 필요성을 느껴 만들었던 부분입니다.
하지만 test를 수정하면서 해당 subscript의 필요성이 없어져 삭제하였습니다.

2023-10-06 02:12 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +        guard 0..<count ~= index else { return nil }
`~=`는 오른쪽의 상수가 왼쪽의 범위안에 속하는지 확인하는 연산자입니다.

2023-10-06 02:23 UTC, jyubong commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    @discardableResult
`@discardableResult` 는 값을 반환하는 함수나 메서드가 해당 결과를 사용하지 않고 호출될 때 컴파일러 경고를 억제할때 상용하는 Attribute입니다. 
참고 : [Attributes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/)

2023-10-06 02:25 UTC, jyubong commented on Calculator/LinkedListTests/LinkedListTests.swift
> +        sut.count = 0
linkedlist에 init을 구현하여 비어있는 상황을 만들어주었습니다.

2023-10-06 02:26 UTC, jyubong commented on Calculator/LinkedListTests/LinkedListTests.swift
> +    }
linkedlist에 init()을 구현하여 head, tail에 값을 넣으줌으로써 empty하지 않은 상황을 만들어주었습니다.

2023-10-06 02:27 UTC, jyubong commented on Calculator/LinkedListTests/LinkedListTests.swift
> +    }
append호출시 tail쪽만 확인하는 메서드로 변경하였으며, 추가적으로 isEmpty일때 head = newNode를 확인해주는 test도 필요하여 해당 부분도 추가적으로 구현해주었습니다.

2023-10-06 02:30 UTC, jyubong commented on Calculator/LinkedListTests/LinkedListTests.swift
> +        sut.append(data)
linkedlist에 init()을 구현하여 head, tail에 값을 넣으줌으로써 append를 대체하였습니다.

2023-10-06 02:31 UTC, jyubong commented on Calculator/LinkedListTests/LinkedListTests.swift
> +    }
linkedlist에 init()을 구현하여 head, tail에 값을 넣으줌으로써 append를 대체하였습니다.
또한 tail에 newNode가 할당된 것에만 확인하는 test로 변경하였습니다.

2023-10-06 03:31 UTC, jyubong commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    }
아직 test를 어디까지 확인을 해야하는지 감이잡히지 않아 최대한 세분화하면서 많은 것을 확인해야할거같아 발생한문제입니다🥹
해당 부분은 rear와  넣은 데이터의 일치성을 확인하였습니다.

2023-10-06 03:32 UTC, jyubong commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        sut.enQueue(thirdData)
linkedlist와 같이 init을 사용하여 given을 세팅하였습니다.

2023-10-06 03:36 UTC, jyubong commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.rear, thirdData)
rear에 값은 온전히 있는 지 확인하기 위해 넣었던 부분입니다.
해당 부분은 첫번째값 변화만 확인하면 될 것같아 수정하였습니다.

2023-10-06 04:39 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +    }
Node는 다음 Node 주소를 가지고 있어야하기 때문에 reference type인 class로 만들어주었습니다. 그리고 Linked List가 Node의 생명주기를 관여하는 밀접한 관계라고 생각하여 LinkedList내부에 구현하였습니다.

그러면서 LinkedList의 타입을 class와 struct 중에 어떤 것이 적합한지 계속 고민이됩니다.
LinkedList의 유일성을 보장해주기 위해 struct로 구현하였으나 class를 참조하면서 오버헤드가 발생하여 class가 적합한가 생각이듭니다. 
그리고 struct 내 class가 있을 경우 struct가 값타입으로써의 유일성이 보장이 안되어 무의미하다고 생각하여 struct를 class로 변경해주었습니다.
참고 : [LinkedList 자료구조 구현시 class/struct 선택](https://velog.io/@dev_jane/LinkedList-%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0-%EA%B5%AC%ED%98%84%EC%8B%9C-classstruct-%EC%84%A0%ED%83%9D)

2023-10-06 05:16 UTC, jyubong commented
Test code를 작성할때 어디까지 확인을 해야할지 아직 어렵습니다.
현재는 아래의 케이스들로 나누어 test 해주었습니다.
||CalculatorItemQueueTest|LinkedListTest|
|---|---|---|
|count| - 값이없을때 0 <br>- enQueue 1번되면 1 | - 노드없을때 0 <br> - 노드 1개 1 <br> - 노드 2개 2|
|isEmpty|| - 노드가없을때 True <br> - 노드가있을때 False|
|enQueue / append| - rear에값이변경 | - isEmpty일때 head에newNode가할당 <br> - tail에newNode가할당|
|deQueue / removeFirst| - isEmpty일때 nil반환 <br> - front를반환| - isEmpty일때 nil반환 <br> - 첫번째노드가제거|
|clear / removeAll| - isEmpty가 되는지 | - head와 tail이 nil인지|

결과적으로는 code converage는 100% 이지만 적절한지 궁금합니다.
deQueue 혹은 append 에서 '첫번째 값이 사라지는지'와 '첫번째값을반환하는지' 중 어느쪽이 test에 적합할지 또는 둘다 확인하는게 나을지도 의견을 구하고 싶습니다.

2023-10-08 05:24 UTC, Rhode-park commented on Calculator/Calculator/LinkedList.swift
> +    }
1. linked list의 외부에 Node가 구현되어있다면 어떤 차이를 가질까요?
2. struct와 class 사이를 고민하면서 많은 이유를 생각해보셨군요 좋습니다.

2023-10-08 05:29 UTC, Rhode-park commented
test code에 대해서는 직접 드루와방에서 의견 나눠보는 것이 좋을 것 같습니다.
가능하신 시간을 말씀해주세요.
그외에 달린 코멘트 확인 부탁드리고 dm주시면 merge해드리겠습니다.

2023-10-08 05:44 UTC, jyubong commented on Calculator/Calculator/LinkedList.swift
> +    }
Node는 linked list의 내부 부품과도 같다고 생각합니다. 그래서 Node는 linked list를 통해서만 접근할 수 있도록 해야한다고 생각하였습니다.
외부에 Node를 구현하면 위의 사유에 어긋나 어느 곳에서도 Node에 직접적인 접근이 가능하게 됩니다.

2023-10-09 17:16 UTC, merged