계산기 [STEP 2] 쥬봉이
yagom-academy/ios-calculator-app pull request #557
Opened 2023-10-10 12:18 UTC by jyubong

@Rhode-park 
로데 step2 PR보냅니다 잘부탁드립니다:)

### 고민이 되었던 점
1. 각 타입과 프로퍼티, 메서드의 역할
    UML을 보고 다음과 같이 생각해보았습니다.

|  | 역할 | 프로퍼티 | 메서드 |
| --- | --- | --- | --- |
| Operator | 연산자와 연산모음 | rawValue 활용 | calculator: case에 따라 연산이 나뉨 |
| Formula | 큐에서 꺼내서 최종 연산 | double이 담긴 큐, 연산자가 담긴 큐 | result : operands큐와 operator큐 dequeue 활용하여 값을 꺼내서 연산 -> operator의 calculate 사용 |
| ExpressionParser | 계산기 viewController에서 들어온 String을 operands와 operator로 구분 -> input부터 띄어쓰기로 각각 구분되도록 생각(ex. "1 + 2 / 3") |  | - 밑줄은 타입메서드를 나타냄(static) <br> - components 메서드에서 extension String에서 구현한 split 활용 <br> - parse: viewcontroller에서 들어온 input을 compents메서드로 먼저 분리하고 각각 operands와 operators로 나누어 담은 Formula 생산 |
| Double | Queue의 element로 사용할 수 있도록 CalculateItem protocol 채택|  |  |
| String | componentsByOperators에 사용할 메서드|  | split: character로 split하여 [Substring] -> [String] mapping |

위처럼 생각하여 구현해보았습니다.
그리고 `+는 기본 접근제어자인 internal로 -는 private으로 구현`하였습니다.

2. error 처리
    Operator의 divide 메서드에서 `0으로 나누기를 시도할시 NaN을 출력하기위해 error를 생성`하여 던졌습니다. 그리고 viewController부분에서 error를 처리하기위해 해당 step에서는 계속 던지고만 있습니다.
    
3. Formula result 메서드
    operands Queue와 operators Queue에서 순서대로 dequeue하여 연산을 하기위해 `while let`을 활용하였습니다. while let (조건)은 조건이 nil이 아닌 경우 계속 실행되며, operands나 operator에서 더이상 deQueue할 값이 없을때(dequeue에서 nil이 반환될때) 종료하고 최종 연산값을 반환하도록 구현하였습니다.
    
4. ExperssionParser parse 메서드
    ExperssionParser의 메서드 전체가 생각하기 어려웠던 부분입니다. 
    현재는 빈 operands, operator Queue를 만들고 각각에 맞는 값들을 넣는 형식입니다. `input으로 들어온 string이 띄어쓰기로 숫자와 연산자가 구분되어있다는 가정하에 구현`하였습니다.(실제로도 이렇게 가공하여 input으로 넣어줄 계획입니다.) input은 componentsByOperator(String.split)을 거쳐 String 배열이 됩니다. 그리고 이 `배열을 forEach 고차함수를 이용`하여 각각의 값들을 `if let 바인딩으로 조건을 나누어` Double로 변환되면 operand Queue에, Operator의 rawValue 값이면 operator Queue에 넣어 최종적으로 해당 Queue들을 가지고 있는 Formula를 반환하도록 하였습니다.

### 조언을 구하고 싶은 부분
1. UML에 대한 이해가 맞는지 궁금하고 이에 대한 구현도 올바른 방향인지도 궁금합니다.
2. ExperssionParser의 parse에서 string 배열값들을 고차함수로 알맞은 큐에 enqueue해주는 과정에서 처음에는
```swift
if let `operator` = Operator(rawValue: Character(component)) {
    operators.enQueue(`operator`)
} else if let operand = Double(component) {
    operands.enQueue(operand)
}
```
순으로 구현해주었는데, test를 하면서 음수인 double형태의 string이 들어갈 경우(ex. "1 * -2") 아래와 같은 오류가 발생하였습니다.
`can't form a character from a string containing more than one extended grapheme cluster`
그래서 순서를 바꾸어주었더니 문제가 없는데 정말로 문제가 없는 것인지 궁금합니다.

3. Unit Test가 올바른지도 궁금합니다.(TDD는 하지 못하였습니다...) coverage 100%가 확인되었는데 생각했던 것보다 case가 적어서 맞는지 확신이 없습니다.
    그리고 "2.0 + 3.0 - 4.0"와 같은 input의 result를 확인할때 expectaion을 연산 결과인 1.0으로 해주는게 나은지, 아니면 firstNode.data + secondNode.data - thirdNode.data와 같이 상수를 연산식으로 해주는게 나은지도 궁금합니다.

2023-10-11 18:04 UTC, Rhode-park requested changes
## ✅ 고민이 되었던 점
### 1️⃣ 각 타입과 프로퍼티, 메서드의 역할
> UML을 보고 다음과 같이 생각해보았습니다.
> 
> |  | 역할 | 프로퍼티 | 메서드 |
> | --- | --- | --- | --- |
> | Operator | 연산자와 연산모음 | rawValue 활용 | calculator: case에 따라 연산이 나뉨 |
> | Formula | 큐에서 꺼내서 최종 연산 | double이 담긴 큐, 연산자가 담긴 큐 | result : operands큐와 operator큐 dequeue 활용하여 값을 꺼내서 연산 -> operator의 calculate 사용 |
> | ExpressionParser | 계산기 viewController에서 들어온 String을 operands와 operator로 구분 -> input부터 띄어쓰기로 각각 구분되도록 생각(ex. "1 + 2 / 3") |  | - 밑줄은 타입메서드를 나타냄(static) <br> - components 메서드에서 extension String에서 구현한 split 활용 <br> - parse: viewcontroller에서 들어온 input을 compents메서드로 먼저 분리하고 각각 operands와 operators로 나누어 담은 Formula 생산 |
> | Double | Queue의 element로 사용할 수 있도록 CalculateItem protocol 채택|  |  |
> | String | componentsByOperators에 사용할 메서드|  | split: character로 split하여 [Substring] -> [String] mapping |
> 
> 위처럼 생각하여 구현해보았습니다.
> 그리고 `+는 기본 접근제어자인 internal로 -는 private으로 구현`하였습니다.

ExpressionParser의 역할을 메서드명을 고려하여 다시 생각해보시면 좋을 것 같습니다.


### 2️⃣ error 처리
> Operator의 divide 메서드에서 `0으로 나누기를 시도할시 NaN을 출력하기위해 error를 생성`하여 던졌습니다. 그리고 viewController부분에서 error를 처리하기위해 해당 step에서는 계속 던지고만 있습니다.

error를 던지는 것은 좋은 시도입니다만, Double의 프로퍼티에 대해서 더 알아보면 좋을 것 같습니다.


### 3️⃣ Formula result 메서드
> operands Queue와 operators Queue에서 순서대로 dequeue하여 연산을 하기위해 `while let`을 활용하였습니다. while let (조건)은 조건이 nil이 아닌 경우 계속 실행되며, operands나 operator에서 더이상 deQueue할 값이 없을때(dequeue에서 nil이 반환될때) 종료하고 최종 연산값을 반환하도록 구현하였습니다.

while let을 잘 사용해주셨습니다. 멋집니다!
    
### 4️⃣ ExperssionParser parse 메서드
> ExperssionParser의 메서드 전체가 생각하기 어려웠던 부분입니다. 
> 현재는 빈 operands, operator Queue를 만들고 각각에 맞는 값들을 넣는 형식입니다. `input으로 들어온 string이 띄어쓰기로 숫자와 연산자가 구분되어있다는 가정하에 구현`하였습니다.(실제로도 이렇게 가공하여 input으로 넣어줄 계획입니다.) input은 componentsByOperator(String.split)을 거쳐 String 배열이 됩니다. 그리고 이 `배열을 forEach 고차함수를 이용`하여 각각의 값들을 `if let 바인딩으로 조건을 나누어` Double로 변환되면 operand Queue에, Operator의 rawValue 값이면 operator Queue에 넣어 최종적으로 해당 Queue들을 가지고 있는 Formula를 반환하도록 하였습니다.

componentsByOperator라는 메서드명을 고려해보자면, 띄어쓰기로 구분하는 것은 의도된 방향이 아닐 것 같습니다. 다른 방법을 더 찾아보는 것은 어떨까요? 실제로 저렇게 가공하는 방향이 쉽지는 않을 것 같습니다.


## ✅ 조언을 구하고 싶은 부분
### 1️⃣ UML에 대한 이해
> UML에 대한 이해가 맞는지 궁금하고 이에 대한 구현도 올바른 방향인지도 궁금합니다.

componentsByOperator에 대한 해석이 조금 미흡한 것 같습니다.

### 2️⃣ parse
> ExperssionParser의 parse에서 string 배열값들을 고차함수로 알맞은 큐에 enqueue해주는 과정에서 처음에는
> ```swift
> if let `operator` = Operator(rawValue: Character(component)) {
>     operators.enQueue(`operator`)
> } else if let operand = Double(component) {
>     operands.enQueue(operand)
> }
> ```
> 순으로 구현해주었는데, test를 하면서 음수인 double형태의 string이 들어갈 경우(ex. "1 * -2") 아래와 같은 오류가 발생하였습니다.
> `can't form a character from a string containing more than one extended grapheme cluster`
> 그래서 순서를 바꾸어주었더니 문제가 없는데 정말로 문제가 없는 것인지 궁금합니다.

순서를 바꾸어주었을 때 문제가 없는지, 있는지를 Test를 통해 파악해야합니다. 
그런데, 현재 test가 모두 count를 세어주는 방향으로만 되어있네요? 
이런 방식으로는 문제가 있는지 없는지 파악하기 어렵지 않을까요?


```text
can't form a character from a string containing more than one extended grapheme cluster
```
위의 문구는 언제 나오는 것일까요?
여러자의 character를 단일 character로 사용하고자 할 때 나오는 오류인 것 같네요.
"1.1 * -2.2"라는 input이 들어갔을 때, 1.1이 character로서 캐스팅될 수 없어서 생기는 오류 같습니다.
Character를 string을 통해서 init했을 때 optional한 값이 나오지 않습니다.
[다음](https://developer.apple.com/documentation/swift/character/init(_:)-6o1aq)을 확인해보시기 바랍니다.


### 3️⃣ unit test
> Unit Test가 올바른지도 궁금합니다.(TDD는 하지 못하였습니다...) coverage 100%가 확인되었는데 > 생각했던 것보다 case가 적어서 맞는지 확신이 없습니다.
> 그리고 "2.0 + 3.0 - 4.0"와 같은 input의 result를 확인할때 expectaion을 연산 결과인 1.0으로 해주는게 나은지, 아니면 firstNode.data + secondNode.data - thirdNode.data와 같이 상수를 연산식으로 해주는게 나은지도 궁금합니다.

coverage가 100이 되었다고 해도, 최대한 모든 경우의 수를 다 test해보는 것이 좋습니다.
경우를 조금 더 세분화시켜서 더 많은 testcode를 작성하는 것이 좋아보입니다.
그리고, 무엇보다도, test code가 count를 통해서만 검증을 하고 있다는 것이 위험해보입니다.

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/Operator.swift
> +        }
여기에서 error를 throw해주니까 뒤의 작업들에서도 계속 throws가 붙어야하는 불편함이 있네요. viewController부분에서 error를 처리하시려는 이유가 있으실까요? Double을 return해줘야하는 메서드라, nan이라는 글자를 return 해주지 못해서일까요? 그런 사고방식의 결과라면, [Double](https://developer.apple.com/documentation/swift/double)이 어떤 프로퍼티들을 가지고 있는지 더 알아볼 필요가 있을 것 같습니다.

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/Operator.swift
> +enum Operator: Character, CaseIterable, CalculatorItem {
`CaseIterable` 프로토콜을 채택해주셨네요 👍 
`CaseIterable`을 채택하신 이유가 무엇인가요? 채택하면 어떤 것을 사용할 수 있나요?

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +        return previousOperand
`lhs`, `rhs`와 같은 네이밍보다는 `previousOperand`와 `operand`라는 명칭을 쓴 이유는 무엇일까요?

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +        guard var previousOperand = operands.deQueue() else { return 0.0 }
마찬가지로 [Double](https://developer.apple.com/documentation/swift/double)이 어떤 프로퍼티를 가지고 있는지 더 살펴보는 것이 좋을 것 같습니다. 그렇다면, 매직넘버를 줄일 수 있을 것 같습니다.

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +        }
while let을 잘 사용해주셨습니다. 멋집니다!

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +extension Double: CalculatorItem { }
Extension 그룹을 만들고 하위 파일로 구분하는 것이 좋아보입니다

```
Extension
ㄴ Double+.swift
ㄴ String+.swift
```

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +}
마찬가지로 extension폴더 내의 파일로 관리하는 것이 좋을 것 같습니다.

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return split(separator: target).map{ String($0) }
String의 `components(separatedBy:)`와 `split(separator:)`는 어떤 차이가 있나요?

2023-10-11 18:04 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
split을 사용하여 주어진 input값을 빈칸을 기준으로 구분해주려고 하고 계십니다.
그러면, 이를 위해서 input이라는 String을 만들 때, 숫자나 문자의 입력이 끝나면, 빈칸을 한 칸씩 넣어줘야하는 것인가요?
그리고 메서드명이 componentsByOperators네요?
그럼 무엇을 기준으로 끊어주는 것이 좋을까요?

2023-10-12 04:19 UTC, jyubong commented on Calculator/Calculator/Model/Operator.swift
> +        }
처음에 로데가 말씀한 것처럼 nan이라는 글자를 return해주지못해 error로 처리해야겠다고 생각했습니다.
하지만 Doulbe에 NaN을 반환하는 nan 프로퍼티가 있는 것을 확인하여 변경하였습니다👍

2023-10-12 04:22 UTC, jyubong commented on Calculator/Calculator/Model/Operator.swift
> +enum Operator: Character, CaseIterable, CalculatorItem {
CaseIterable 프로토콜은 UML에 있어 구현하였으나 초기 코드에서는 활용하지 못하였습니다.

CaseIterable은 enum의 모든 케이스가 담긴 컬렉션을 제공하여 컬렉션 메서드를 활용할 수 있습니다.
수정한 코드에서 `Operator.allcases.forEach`를 활용하였습니다.

2023-10-12 04:25 UTC, jyubong commented on Calculator/Calculator/Model/Formula.swift
> +        return previousOperand
전과 후 연산자를 나타내기 위한 네이밍으로 해당 이름을 채택하였으나 lhs, rhs를 활용하는게 더 좋을 것 같아 변경하였습니다.

2023-10-12 04:30 UTC, jyubong commented on Calculator/Calculator/Model/Formula.swift
> +        guard var previousOperand = operands.deQueue() else { return 0.0 }
Double에는 zero 프로퍼티가 있어 0.0을 zero로 변경하였습니다.

2023-10-12 04:31 UTC, jyubong commented on Calculator/Calculator/Model/Formula.swift
> +extension Double: CalculatorItem { }
이 부분도 고민이 되었던 부분이었습니다. 새로 폴더를 만들어 extesion을 분리해주었습니다.

2023-10-12 04:32 UTC, jyubong commented on Calculator/Calculator/Model/ExpressionParser.swift
> +}
새로 폴더를 만들어 extension을 분리해주었습니다.

2023-10-12 04:50 UTC, jyubong commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return split(separator: target).map{ String($0) }
제가 알아본 바로는
||split|components|
|-|-|-|
|매개변수|최대 3가지, 타입 Self.Element <br> - separator: Self.Element <br> - maxSplits: Int = Int.max <br> - omittingEmptySubsequences: Bool = true|1가지, 타입 String <br> separatedBy separator: String|
|return 타입|[Substring]|[String]|
|import|Swift Standard Library|Foundation import 필수|
|그외||구분 기호 문자가 인접해 있으면 결과에 빈 문자열이 생성|

- split은 map을 이용해 String으로 변환하는 과정이 추가되며
- components를 사용할 경우 1.1+ 처럼 연산자가 뒤에 위치할때 "" 빈문자열이 발생합니다.

처음에는 split하여 map으로 변환해주었습니다. 하지만 코드를 수정하면서 ""를 걸러주는 로직을 추가할 필요성이 생겨 split 또한 components로 바꾸어주어 map하는 소요를 줄였습니다.

2023-10-12 04:55 UTC, jyubong commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
operator 기준으로 나누어 주어야겠다고 처음에 생각했으나 구현이 쉽지 않아 다른 방식으로 생각했습니다. 이 방향이 아니었군요🥲
operator로 나눌 수 있도록 새로 코드를 구현하였습니다. 아래에 해당 부분을 작성하도록 하겠습니다.

2023-10-12 05:06 UTC, jyubong commented
operator로 나누는 components를 구현하는 것이 어려웠습니다.🤯

extenstion String에서는 components를 이용해서 seperator(operator)기준으로 나누어 splitedString을 만들어준 뒤 component 사이에 해당 seperator(operator)를 다시 집어 넣어주었습니다.

ExpressionParser의 componentsByOperator에서는 input의 공백을 없애고 [String]으로 만들었습니다.
operator.allCasese.forEach를 활용해 operator 순서대로 input을 나누었습니다. 이때 그냥 계속 나누면 배열안에 배열안에 배열.. 이렇게 된다고 생각하여 flatMap을 이용해 operator 별로 split을 한 뒤 하나의 [String]으로 다시 통합되도록 구현하였습니다.

parse메서드에서는 ""인 요소가 있을 때 넘어가도록 로직을 추가하였습니다.

그리고 어려웠던 것이 빼기 연산자와 음수의 '-'를 구분하는것이 어려웠습니다. 그래서 활용한 방법으로 이모지의 빼기 모양('−')으로 비슷하지만 다른 minus를 활용하여 이것을 빼기 연산자로, 음수의 마이너스는 원래의 '-'로 구현하였는데 적절 방법인지도 조언을 구하고 싶습니다.
Xcode에서 이모지  '−'는 Minus Sign, 키보드 '-'는 Hyphen Minus로 서로 다르게 인식합니다.

2023-10-13 06:29 UTC, Rhode-park requested changes
음수 기호와 빼기 기호를 구분 짓는 것은 좋은 선택이라고 생각합니다.
코멘트 두 개 더 달았습니다.
확인해보시고 반영 후 DM주시면 바로 merge해드리겠습니다.

2023-10-13 06:29 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var splitedString = [input.filter { $0 != " " }]
이 부분이 꼭 필요한 것인가요?
어떤 기능을 하고 있는지 설명 부탁드립니다.

2023-10-13 06:29 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorList = Operator.allCases
굳이 상수를 하나 더 선언할 필요 없이 forEach문에서 써줘도 될 것 같네요.

2023-10-13 07:12 UTC, jyubong commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var splitedString = [input.filter { $0 != " " }]
이 부분은 input에 공백이 들어있을 경우 제거해주는 로직입니다. 혹시 1 + 2-3처럼 공백이 들어올 경우를 생각해서 구현했습니다.
이부분이 현재는 필요가 없을 것 같아 filter 부분은 빼주었습니다.

2023-10-13 07:12 UTC, jyubong commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorList = Operator.allCases
상수에 할당없이 바로 forEach에 해당 부분을 추가해주었습니다.

2023-10-14 07:16 UTC, merged