계산기 [Step2] Kiseok
yagom-academy/ios-calculator-app pull request #558
Opened 2023-10-10 18:55 UTC by carti1108

@Rhode-park 
안녕하세요 Rhode!
step2 pr보냅니다 잘 부탁드립니다!

## 고민되었던 점
- componentsByOperators메서드 구현
-> 처음엔 연산자를 기준으로 나눌려고하였으나 연산자로 나눌경우 operator queue에 값을 넣어줄 방법을 찾지 못 해 빈문자열을 기준으로 나누도록 구현
- input문자열을 나눠 각각 operator queue와 operand queue에 할당
-> forEach 구문을 통해 각각의 요소마다 Double이 된다면 operand queue로 Character가 된다면 operator queue로 들어가도록 조건문 생성
- Formula result메서드 구현
-> 처음 구현 시 첫번째 연산의 결과값을 활용하지 않아 올바른 결과값이 나오지 않아서 lhs 매개변수에 연산결과값을 넣어줌

## 조언을 얻고 싶은 부분
- enum을 case없이 사용한 경우를 본 적이 없어서 ExpressionParser가 왜 enum으로 구현되어있는지 궁금합니다.
- componentsByOperator메서드의 이름 뜻이 명확하게 해석이 안됩니다. 정확한 의미를 알고싶습니다,,,,
- input을 구태여 String타입으로 받는 이유와 왜 split메서드를 오버로딩해서 사용해야하는지 이해가 되지 않습니다.
어차피 다 각 queue에 들어갈 수 있게 타입 변환을 해주는 과정을 거치는데 그렇다면 저렇게 새로운 기능을 만들지 않고 배열을 사용해서 배열의 메서드들을 활용하는게 더 낫지않을까라는 생각이 들었습니다.

2023-10-12 01:05 UTC, Rhode-park requested changes
## ✅ 고민이 되었던 점
> * componentsByOperators메서드 구현
> -> 처음엔 연산자를 기준으로 나눌려고하였으나 연산자로 나눌경우 operator queue에 값을 넣어줄 방법을 찾지 못 해 빈문자열을 기준으로 나누도록 구현

input을 연산자를 기준으로 나눈 것을 operands에 넣어주고, operators에는 input을 고차함수로 처리하여 각각 넣어주면 되지 않을까요?

> * input문자열을 나눠 각각 operator queue와 operand queue에 할당
> -> forEach 구문을 통해 각각의 요소마다 Double이 된다면 operand queue로 Character가 된다면 operator queue로 들어가도록 조건문 생성

componentsByOperators메서드를 달리 구현해야할 것 같은데, 이 부분에 대한 리팩토링이 필요하겠네요.

> * Formula result메서드 구현
> -> 처음 구현 시 첫번째 연산의 결과값을 활용하지 않아 올바른 결과값이 나오지 않아서 lhs 매개변수에 연산결과값을 넣어줌

항상 어떤 과정마다 result가 어떻게 나오는지를 고민하고 코드를 짜시면 좋을 것 같습니다.

## ✅ 조언을 구하고 싶은 부분
> * enum을 case없이 사용한 경우를 본 적이 없어서 ExpressionParser가 왜 enum으로 구현되어있는지 궁금합니다.

enum안의 메서드들 앞에 static이 붙어있네요?
어떨 때, static func를 사용할 수 있나요?
그리고 static func는 왜 사용하나요?
공부해보시고 답변 부탁드립니다.

> * componentsByOperator메서드의 이름 뜻이 명확하게 해석이 안됩니다. 정확한 의미를 알고싶습니다,,,,

연산자를 기준으로 요소들을 나누라는 뜻이 될 것 같습니다.

> * input을 구태여 String타입으로 받는 이유와 왜 split메서드를 오버로딩해서 사용해야하는지 이해가 되지 않습니다.

input을 그러면 String이 아닌 어떤 타입으로 받아야하나요?
생각해두신 타입이 있으실까요?

> * 어차피 다 각 queue에 들어갈 수 있게 타입 변환을 해주는 과정을 거치는데 그렇다면 저렇게 새로운 기능을 만들지 않고 배열을 사용해서 배열의 메서드들을 활용하는게 더 낫지않을까라는 생각이 들었습니다.

배열을 통해 Queue를 만드는 방법도 있겠네요.

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Operator.swift
> +    case multiply = "x"
rawValue가 나누기는 왜 "/"인데, 곱하기는 왜 "x"인가요?
어떤 기준으로 rawValue를 정한 것이죠?

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Operator.swift
> +            return divide(lhs: lhs, rhs: rhs)
switch에서 분기처리를 하기 보다는, divide자체에서 분기처리를 하는 것이 좋을 것 같습니다.

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Operator.swift
> +                throw CalculatorError.divideByZeroError
여기에서 error를 throw해주니까 뒤의 작업들에서도 계속 throws가 붙어야하는 불편함이 있네요. error를 throw하시는 이유가 있으실까요? Double을 return해줘야하는 메서드라, nan이라는 글자를 return 해주지 못해서일까요? 그런 사고방식의 결과라면, [Double](https://developer.apple.com/documentation/swift/double)이 어떤 프로퍼티들을 가지고 있는지 더 알아볼 필요가 있을 것 같습니다.

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Operator.swift
> +    }
이 안에서 분기처리를 할 수 있게 해볼까요?

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +        }
`lhs`를 `operands`로부터 dequeue하지 못할 경우에, result가 어떤 결과를 내뱉어야할까요?
`operands`에 아무런 숫자도 안 들어있을 경우네요?
연산의 결과는 무엇이 되어야 할까요?
그것을 생각하면 else문을 채우기 좋을 것 같습니다.

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +        while !operators.isEmpty {
while문의 조건이 깔끔하네요!

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +            }
마찬가지입니다. `operators`로부터 dequeue를 할 수 없는 경우, 즉, `operators`에 아무것도 없는 경우 계산의 결과는 어떻게 되어야할까요?

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operators = operators.dequeue() else {
Queue와 단일 Operator가 `operators`라는 같은 이름을 쓰는 것이 부적절해보입니다.
`operatorSymbol`과같은 식으로 다르게표현해보면 어떨까요?

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +            }
여기까지 넘어왔다는 것은, lhs와 operator는 존재하지만, 그 다음 연산을 위한 숫자인 rhs가 존재하지 않을 수 있다는거군요.
그러면, "2.0+"가 입력된 상황이라는건데, 그 결과로 error를 내뱉고 싶으신거군요!
아이폰 계산기로는 "2+="를 입력하면 4가 나오고, 다른 계산기 기준으로는 "2+="를 입력하면 2가 나오는 것 같습니다.
꼭 error를 던져야할지 궁금증이 드네요.

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +            result = lhs
그냥 `return lhs`라고 쓸 수는 없을까요?

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/Extension.swift
>  }
Extension 그룹을 만들고 하위 파일로 구분하는 것이 좋아보입니다

```
Extension
ㄴ Double+.swift
ㄴ String+.swift
```

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var formula = Formula(operands: CalculatorItemQueue(enqueueBox: [], dequeueBox: []), operators: CalculatorItemQueue(enqueueBox: [], dequeueBox: []))
`formula`에 대한 부분이 너무 길어서 가독성이 떨어집니다.
`operands`, `operators`라는 상수를 만들어서 Queue를 만들고 그 상수를 각각 `Formula`의 변수로 담아주는 것은 어떨까요?

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var formula = Formula(operands: CalculatorItemQueue(enqueueBox: [], dequeueBox: []), operators: CalculatorItemQueue(enqueueBox: [], dequeueBox: []))
기존에 다음과 같이 Queue의 init을 구현해주셔서 enqueueBox와 dequeueBox를 채워줘야하는 것 같습니다:
```swift
init(enqueueBox: [Element], dequeueBox: [Element]) {
    self.enqueueBox = enqueueBox
    self.dequeueBox = dequeueBox
}
```
그런데, enqueue가 될 때는 enqueueBox에 숫자를 넣어주는데, 초기화할때라고 해서 dequeueBox에 숫자를 넣어줘야할 이유가 있을까요?

다음과 같은 형태의 init을 만든다면 문제가 되는 점이 있을까요:

```swift
init(enqueueBox: [Element] = []) {
    self.enqueueBox = enqueueBox
}
```

2023-10-12 01:05 UTC, Rhode-park commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
split을 사용하여 주어진 input값을 빈칸을 기준으로 구분해주려고 하고 계십니다.
그러면, 이를 위해서 input이라는 String을 만들 때, 숫자나 문자의 입력이 끝나면, 빈칸을 한 칸씩 넣어줘야하는 것인가요?
그리고 메서드명이 componentsByOperators네요?
그럼 무엇을 기준으로 끊어주는 것이 좋을까요?

2023-10-12 06:19 UTC, carti1108 commented on Calculator/Calculator/Model/Operator.swift
> +    case multiply = "x"
특별한 기준없이 정했던 것 같습니다,,
곱하기의 rawValue는 스위프트의 곱하기 연산자와 동일하게 "*"로 수정했습니다.

2023-10-12 07:18 UTC, carti1108 commented on Calculator/Calculator/Model/Operator.swift
> +            return divide(lhs: lhs, rhs: rhs)
수정완료했습니다.

2023-10-12 07:21 UTC, carti1108 commented on Calculator/Calculator/Model/Operator.swift
> +                throw CalculatorError.divideByZeroError
0으로 나누는 것은 단순히 오류라고만 생각해 오류처리를 해줬던 것 같습니다.
Double이 [nan](https://developer.apple.com/documentation/swift/double/nan)이라는 프로퍼티를 가지고 있다는 것을 찾은 뒤 리턴 값을 nan으로 변경해주었습니다.

2023-10-12 07:22 UTC, carti1108 commented on Calculator/Calculator/Model/Operator.swift
> +    }
수정완료했습니다.

2023-10-12 07:34 UTC, carti1108 commented on Calculator/Calculator/Model/Formula.swift
> +        }
아이폰 계산기로 첫번째 피연산자를 비우고 진행한 결과 첫번째 피연산자에 0을 넣어주는 것으로 보였습니다.
따라서 else문 내 .zero를 리턴하도록 변경하였습니다.

2023-10-12 07:57 UTC, carti1108 commented on Calculator/Calculator/Model/Formula.swift
> +            }
아이폰 계산기에서 첫번째 피연산자 입력 후 =를 눌렀을 때 계속 첫번째 피연산자가 떠있는 것을 보고 lhs를 리턴하도록 변경하였습니다.

이 부분은 operators queue가 비어있지 않을 때만 실행되는 while문 내부 부분이라 else문이 실행될 일은 없다고 생각했었습니다.
그래도 dequeue에 실패한 경우는 잘못된 경우다 라는 것을 단순히 명시하기 위해서 오류를 던지는 방식을 사용했습니다.
이런 경우에는 어떤 식으로 처리하는게 좋을까요?

2023-10-12 08:02 UTC, carti1108 commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operators = operators.dequeue() else {
수정완료했습니다.

2023-10-12 08:39 UTC, carti1108 commented on Calculator/Calculator/Model/Formula.swift
> +            }
아이폰 계산기를 기준으로 rhs else문에서 calculate의 전달인자 두 개 모두 lhs를 사용하여 리턴하도록 하였습니다.

2023-10-12 08:40 UTC, carti1108 commented on Calculator/Calculator/Model/Formula.swift
> +            result = lhs
그냥 단순히 연산의 결과값이란 것을 명시적으로 보여주고 싶었던 것 같습니다,,
그럴 필요가 없다고 생각이 들어 result를 없애주었습니다.

2023-10-12 08:47 UTC, carti1108 commented on Calculator/Calculator/Model/Extension.swift
>  }
수정완료했습니다.

2023-10-12 08:53 UTC, carti1108 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var formula = Formula(operands: CalculatorItemQueue(enqueueBox: [], dequeueBox: []), operators: CalculatorItemQueue(enqueueBox: [], dequeueBox: []))
step1 구현 때 테스트에서 dequeueBox에도 값을 넣어줄 생각을 했어서 저런 식으로 구현한 것 같습니다.
필요가 없다고 판단되어 dequeueBox부분을 없애는걸로 수정했습니다.

2023-10-12 09:07 UTC, carti1108 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        var formula = Formula(operands: CalculatorItemQueue(enqueueBox: [], dequeueBox: []), operators: CalculatorItemQueue(enqueueBox: [], dequeueBox: []))
수정완료했습니다.

2023-10-13 05:32 UTC, carti1108 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
연산자로 나눠줄 때 마땅한 방법들이 떠오르지 않아 요행을 바라고 사용한 방식인 것 같습니다.
split에서 빈 문자열을 없애주는 로직 추가 후 componentsByOperators 안에서 연산자를 기준으로 나눠주고 parse부분에서 operator들을 따로 추출하는 로직을 추가하였습니다.

2023-10-13 06:31 UTC, carti1108 commented
> 어떨 때, static func를 사용할 수 있나요?
그리고 static func는 왜 사용하나요?

static 키워드를 붙여주면 타입 메서드가 됩니다. 타입 메서드는 인스턴스를 생성하지 않고 타입 자체에서 접근하여 사용할 수 있습니다.
타입의 인스턴스 생성을 원치 않고 메서드를 해당 타입자체에 직접적으로 영향을 주고싶을때 사용합니다.
이런 타입 메서드나 프로퍼티를 이용하여 네임스페이스를 만들 수 있는데 네임스페이스를 사용하면 인스턴스를 생성하지 않고 바로 사용할 수 있기 때문에 불필요한 코드가 줄어들 것 같고, 관련 메서드를 한 곳에 모아두고 사용하니 유지,보수에 용이해질 것 같고 재사용도 편리해질 것 같습니다.
아마 ExpressionParser도 이와 같은 맥락으로 만들어 준게 아닌가 싶습니다.

이번 step2 리뷰를 보면서 공부하려는 자세보다는 구현을 하려고만 했었다는게 많이 느껴져서 반성 중 입니다.
좋은 피드백 감사합니다.

2023-10-14 07:24 UTC, Rhode-park commented on Calculator/Calculator/Model/Formula.swift
> +            }
else문이 실행될 일이 없기때문에 변경된 것이 더 적절해보입니다.

2023-10-14 07:29 UTC, Rhode-park commented
merge해드리겠습니다.
`ExpressionParser`에서 `parse`의 코드를 줄이는 방법이 있습니다.
두 개의 `forEach`를 뺄 수 있습니다.
한 번 더 고민해보시기 바랍니다.

2023-10-14 07:29 UTC, merged