계산기 [STEP2] 찰스
yagom-academy/ios-calculator-app pull request #560
Opened 2023-10-11 08:55 UTC by Charl-es

@Tediousday93 
안녕하세요 로웬! STEP2 제출합니다.

## 고민했던점
- 확장을 통한 `split`메서드 구현
   - `components`와 `split` 중에 고민을 했었습니다.  `components`같은 경우는 `[String]`을 반환하고 `split`은 `[Self.SubSquence]`를 반환하여  `map`고차함수를 사용하여 매핑을 할까 고민을 했지만 `components`를 사용하기로 하였습니다.
  
- `ExpressionParser`의 `componentsByOperators` 구현
   - 우선 `components` 메서드 경우 구분 기호 문자열이 인접하여 발생하면 빈 문자열이 생성되고, 문자열이 구분기호로 시작하거나 끝나면 각각 첫 번째 또는 마지막 하위 문자열이 빈문자열로 생성되기에 이를 반환할 때 `filter`를 사용하여 걸러주었습니다.
> split만 했을 경우
```swift
let a = " 1 + 2 * 3 - 1 "

extension String {
    func split(with target: Character) -> [String] {
        return components(separatedBy: String(target))
    }
}

let b = a.split(with: " ")
print(b)

// Prints :  ["", "1", "+", "2", "*", "3", "-", "1", ""]
```

> filter까지 했을 경우
```swift
let a = " 1 + 2 * 3 - 1 "

extension String {
    func split(with target: Character) -> [String] {
        return components(separatedBy: String(target))
    }
}

let b = a.split(with: " ").filter { $0 != "" }
print(b)

// Prints : ["1", "+", "2", "*", "3", "-", "1"]
```
   - 이 후, 문자열이 띄워쓰기 없이 매개변수로 전달될 경우를 생각하여 전달받은 문자열을  `for문`을 통하여 글자 하나씩 살펴 공백이 아닌 경우 공백을 추가하여 새로운 문자열을 만들어 이를 이용하여 반환을 하도록 구현하였습니다.
 > 띄워쓰기 없이 문자열을 전달했을 경우
```swift
let a = "1+2*3-1"

extension String {
    func split(with target: Character) -> [String] {
        return components(separatedBy: String(target))
    }
}

func componentsByOperators(from input: String) -> [String] {
    var input2 = ""
    for char in input {
        if char != " " {
            input2 += String(char) + " "
        }
    }
    return input2.split(with: " ").filter{ $0 != "" }
}

var c = componentsByOperators(from: a)
print(c)

// Prints : ["1", "+", "2", "*", "3", "-", "1"]
```

- `componentsByOperators`를 통해 전달받은 배열을 어떻게 나누어 각각에 큐에 넣어줄까
   - 이는 `forEach`를 이용하여 각각에 요소에 접근하면 그 요소를 `Double`로 바뀌는지 아니면 `Operator`로 바뀌는 지 확인하여 각각에 맞는 타입의 큐로 넣어주었습니다.

- `Formula`의 `result`메서드 구현
   - 처음에는 `reduce`를 이용하여 누적된 값으로 연산하는 방식으로 구현을 하려고 했으나, 이를 이용하기 위해 `reversed`메서드를 사용해 먼저 큐를 뒤집어야 해서 이는 더블 스택의 본질을 흐린다 판단하여 누적값을 담는 변수를 선언하여 이를 토대로 연산자와 매칭하여 연산을 하도록 구현하였습니다. 

---

## 조언을 얻고싶은 점
- MVC로 파일들을 분리하였는데, 이번 프로젝트와 같이 String 확장 같은 경우는 어떻게 관리를 해야하는 지에 대한 조언을 얻고 싶습니다.
- `ExpressionParser` 같은 경우 `enum` 타입으로 구현하라 UML에 명시되어 있는데 `case`로 나누지 않는데 구조체를 사용해도 될 걸 굳이 왜 열거형으로 정의를 하라고 했을까에 대한 의문을 가졌지만 이에 대한 해결이 되지 않아 조언을 얻고 싶습니다.

2023-10-11 17:57 UTC, Tediousday93 requested changes
안녕하세요 찰스 🙌
step2 고생하셨습니다.
UML을 잘 파악해서 작성해주신 것 같습니다 👍
하지만 조금은 개선해야할 부분이 있어서 해당 부분만 수정해봅시다!

---

### ✅ 고민했던 점
**ExpressionParser**
* enqueue하기 전 수행되는 작업을 잘 파악하신 것 같습니다. 👍
* 고차함수를 활용하려고 노력하셨군요 👍👍👍


**Formula**
* 연산 누계 변수를 활용하는 방법 👍
* reduce를 활용하는 방법에 대한 설명이 잘 이해가 되지 않습니다. Queue 내부에서 reduce를 사용하신다는 걸까요? 만약 그렇게 된다면 Operator enum 타입은 어떻게 활용하게 되나요?
* Queue를 역순으로 정렬하는 방법은 어떻게 구현하려고 하셨을까요? Queue타입 내부의 배열은 private(set) 접근수준을 갖고 있기 때문에 타입 내부에서만 수정할 수 있습니다. 또한 Queue가 들고있는 배열을 외부에서 조작하는 것은 테스트 코드가 아닌 이상 바람직하지 않다고 생각합니다.


</br>

### ✅ 조언을 얻고 싶은 부분
**파일 관리**
* 주어진 UML에 따르면 String extension은 모델 내 전역적으로 정의되어야 할 것으로 보이네요. 파일 위치 자체는 적절하다고 생각됩니다.
* 만약 `split` 메서드가 ExpressionParser 타입 내부에서만 활용된다면, 해당 파일(ExpressionParser)에 fileprivate 하게 하단에 추가하는 방법도 있겠네요.
* 관련된 extension들만 따로 폴더를 모아 관리하는 방법도 있습니다.

**case 없는 열거형 타입**
* case 없는 열거형과 구조체의 차이점이 뭘까요?
* NameSpace를 만드는 여러가지 방법에 대해 알아보신 적이 있다면 해당 내용에서 힌트를 얻을 수 있습니다.

</br>

### Feedback
* UnitTest가 생각보다 부족합니다.. ExpressionParser에 대한 테스트를 조금 더 신경써서 진행하셨다면 개선할 부분을 스스로 찾는 것이 가능하셨을 것 같습니다.

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/Operator.swift
> +    }
0으로 나눌 경우 어떻게 될까요?

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/OperateError.swift
> +}
UML에 없는 타입을 만드셨네요.
0으로 나눴을 때 오류처리를 위해 만드신 것이 맞나요? 활용된 부분이 없어서 질문 드립니다.

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/ExpressionParser.swift
> +            }
Formula 타입의 memberwise initializer를 활용하고 있어서 코멘트 드립니다 👍

Formula 인스턴스를 먼저 만든 후 큐 프로퍼티에 접근해 enqueue를 하는 것 보다
operands, operators 큐를 먼저 완성하고 Formula 인스턴스를 만드는 것이 좋아 보입니다. 🤔

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/ExpressionParser.swift
> +    }
고민해볼만한 부분이네요. 💭
* 여기에서 input을 조작할 필요가 있을까요?
* viewController에서 model의 로직에 맞춰 input을 전달하는 것이 맞지 않을까요?
* 음수가 섞여있는 경우는 결과가 어떻게 되나요? character 기준으로 하게되면 음수는 어떻게 처리될까요?
* operand의 자릿수가 두 자리 이상이 되면 어떻게 될까요?

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/ExpressionParser.swift
> +        componentsArray.forEach{ component in
후행 클로저 컨벤션 주의해주세요!

```suggestion
        componentsArray.forEach { component in
```

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/ExpressionParser.swift
> +            } else if let operatorSymbol = Operator(rawValue: Character(component)) {
Operator 열거형 인스턴스를 만들고 있는데 이름은 왜 Symbol일까요? 💭
operator를 정의했을 때, 예약어 때문에 사용할 수 없었다면 앞 뒤에 `를 붙여 사용할 수 있습니다.
```suggestion
            } else if let `operator` = Operator(rawValue: Character(component)) {
```

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/Formula.swift
> +        var accumulatingValue: Double = 0
0을 하드코딩 하는 것 보다는 Double 타입에 있는 타입 프로퍼티를 활용하는 것을 추천드립니다. 👍
```suggestion
        var accumulatingValue: Double = .zero
```

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/Calculator/Models/Formula.swift
> +            guard let rhs = operands.dequeue() else { break }
while let을 활용하는 방법도 있습니다.
guard문을 없앨 수 있으니 사용해보세요 👍

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/ExpressionPaserTests/ExpressionPaserTests.swift
> +    func test_띄워쓰기없이_요소들이_주어졌을때_결과값은_5이다() {
given when then이 명확하게 표현된 이름으로 수정해주시면 좋겠습니다.
테스트케이스 전반적으로 수정이 필요해 보입니다.
ex. 띄어쓰기없는_input이_주어지면_result호출시_결과가5이다

그리고 위쪽 코멘트에서 고민해볼 내용에 말씀드렸다시피,
띄어쓰기는 ExpressionParser 타입에서 조작할 내용이 아닌 것 같습니다 😢

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/ExpressionPaserTests/ExpressionPaserTests.swift
> +    }
ExpressionParser 테스트인데 sut가 Formula네요..? 🤔
ExpressionParser는 프로퍼티가 없으니 따로 통제할 변수는 없는 것 같습니다.
불필요하다면 setup, teardown을 하지 않아도 될 것 같아요.

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/ExpressionPaserTests/ExpressionPaserTests.swift
> +        let result = sut.result()
여기에 테스트할 메서드가 호출되어야 하는데.. 지금은 Formula test와 다름 없지 않나요? 🤔

parse 메서드는 무슨 일을 하고 있을까요??
고민해보시고 parse의 기능을 테스트하는 케이스를 작성해주세요! 💪

2023-10-11 17:57 UTC, Tediousday93 commented on Calculator/FormulaTests/FormulaTests.swift
> +    func test_피연산자2331_연산자AddMultiplySubtract가_큐에존재할때_모두를연산한결과는_14와같다() {
마찬가지로 given when then이 보이는 형태로 수정해주세요 🙏

2023-10-11 21:21 UTC, Tediousday93 commented on Calculator/Calculator/Models/ExpressionParser.swift
> +    }
메서드의 이름만 봤을 때는 Operator를 기준으로 나머지 String을 나눠야 할 것 같네요.

이름과는 다른 동작을 하고 있지만 현재 개선해야할 부분만 수정하면
앱을 구동하는데는 문제가 없을 겁니다.

2023-10-13 06:19 UTC, Charl-es commented on Calculator/Calculator/Models/ExpressionParser.swift
> +            }
해당 부분은 `Formula` 프로퍼티에 기본값을 주는 방식으로 변경하였습니다.

2023-10-14 03:40 UTC, Charl-es commented on Calculator/Calculator/Models/Operator.swift
> +    }
해당부분은 아래 코멘트 주신 오류타입을 만들어 오류를 던지도록 구현해 놓았습니다.
오류처리는 뷰컨트롤러 부분에서 해줄 것 같습니다.

2023-10-14 03:44 UTC, Charl-es commented on Calculator/Calculator/Models/ExpressionParser.swift
> +    }
연산자 기준으로 구분하여 피연산자들을 요소로 가지는 배열을 리턴하는 방식으로 변경하였습니다!
움수 처리는 하이픈을 UI 버튼 타이틀의 기호와 구분짓는 방식으로 변경해두었습니다!

2023-10-14 03:45 UTC, Charl-es commented on Calculator/Calculator/Models/ExpressionParser.swift
> +        componentsArray.forEach{ component in
수정하였습니다!

2023-10-14 03:45 UTC, Charl-es commented on Calculator/Calculator/Models/Formula.swift
> +            guard let rhs = operands.dequeue() else { break }
`while let` 사용하여 수정해 보았습니다!

2023-10-14 03:46 UTC, Charl-es commented on Calculator/Calculator/Models/ExpressionParser.swift
> +            } else if let operatorSymbol = Operator(rawValue: Character(component)) {
알려주신 방법으로 수정해보았습니다!

2023-10-14 05:39 UTC, Charl-es commented on Calculator/ExpressionPaserTests/ExpressionPaserTests.swift
> +    }
참고하여 수정해보았습니다!

2023-10-14 05:39 UTC, Charl-es commented on Calculator/ExpressionPaserTests/ExpressionPaserTests.swift
> +        let result = sut.result()
수정하였습니다!

2023-10-16 02:40 UTC, Tediousday93 approved these changes
요구사항이 잘 반영되었네요!
전반적으로 잘 수정해주셨습니다 👍

추가 코멘트는 참고해보시고 수정을 원하시면 다음 스텝에 적용해봅시다! 😊
고생하셨습니다. 👏

2023-10-16 02:40 UTC, Tediousday93 commented on Calculator/Calculator/Models/ExpressionParser.swift
> +            operatorsQueue.enqueue(component)
고차함수 활용 👍👍👍
고차함수를 체이닝할 때 개행을 추가해주면 좀 더 가독성이 좋아지는 것 같아요.
단축인자이름도 컨벤션 중 하나라고 생각하기 때문에 가능하다면 맞춰 주시는 것이 좋다고 생각합니다. 😊
이 부분은 개인 취향과 팀에서 정하는 룰대로 맞춰가는 것이니 기준을 잘 정해두시면 좋습니다~!
참고만 해주세요!
```suggestion
        operandsArray.compactMap { Double($0) }
            .forEach { operandsQueue.enqueue($0) }
        
        input.compactMap { Operator(rawValue: $0) }
            .forEach { operatorsQueue.enqueue($0) }
```

2023-10-16 02:40 UTC, Tediousday93 commented on Calculator/Calculator/Models/Formula.swift
> +        while !operators.isEmpty, let `operator` = operators.dequeue(), let rhs = operands.dequeue() {
dequeue에 실패하면 while문이 끝나기때문에 isEmpty는 확인하지 않아도 될 것 같아요~!

2023-10-16 02:40 UTC, Tediousday93 commented on Calculator/ExpressionPaserTests/ExpressionPaserTests.swift
> +        let operatorsExpactation = [Operator(rawValue: "×")!, Operator(rawValue: "−")!]
rawValue 이니셜라이저보다는 case 인스턴스를 만들어주는 것이 좋다고 생각합니다. 🤔
```swift
// type annotation, inference 활용
        let operatorsExpactation: [Operator] = [.multiply, .subtract]
        
// 배열에 Operator 인스턴스 직접 할당
        let operatorsExpectation = [Operator.multiply, Operator.subtract]
```

2023-10-16 02:40 UTC, Tediousday93 commented on Calculator/FormulaTests/FormulaTests.swift
> +    }
throw test 👍👍👍👍

2023-10-16 02:40 UTC, Tediousday93 commented on Calculator/FormulaTests/FormulaTests.swift
> +            break
이 테스트에서는 success가 의도하지 않은 결과이기 때문에 
여기는 `XCTFail`을 활용해 테스트를 실패하게 만들어주는 것이 좋다고 생각합니다 💭
```suggestion
            XCTFail("Not Expected Result")
```

2023-10-16 02:40 UTC, merged