계산기 [Step2] 미르
yagom-academy/ios-calculator-app pull request #561
Opened 2023-10-11 09:05 UTC by mireu79

@Tediousday93 
안녕하세요! 로웬! stpe2보내드립니다! 
시간이 많이 걸렸지만 잘부탁드립니다..!

### 1️⃣고민했던점
- UML에 대해 이해하는데만 시간을 정말 많이 투자한것 같습니다..정해진 틀에서 구현을 한다는 것이 결코 쉽지 않다는 것을 느꼈습니다. UML을 보고 각타입에 대한 구현을 먼저 해주고, 각타입이 어떻게 쓰일까 고민을 많이 해봤습니다. 
    - 제가 생각한바로는 ExpressionPraser은 계산을 하려는 연산자와 피연산자의 계산식 큐요소에 추가된다고 생각했고, Formula인스턴스에 operand와 operator큐가 추가되도록 구현을 해줬습니다. 
    - Formula는 계산을 하면 계산에 대한 결과값이 생성된다고 생각했고, 옵셔널 바인딩 해준 값들을 Operator타입에 calculate메서드를 나타내 연산자와 피연산자가 들어왔을때 계산을 해주고 그에 대한 결과값이 나오도록 구현을 해줬습니다.

<br>

- `변수보다는 상수를, 반복문 조건문 보다는 고차함수를 더 활용하도록 노력해보세요.
` 라는 문구가 있어서 고차함수로 표현을 해주려고 했습니다. 기존 배열에서 나열을 하는 상황이라 비슷하지만 반복문보다는 고차함수가 가독성이 좋다고 생각하여 `forEach`를 사용하여 구현해줬습니다.
~~~swift
//수정전
for component in operatorscomponent {
                if let oprators2 = Operator(rawValue: Character(component)) {
                    operators.enqueue(oprators2)
                }

//수정후
    operatorscomponent.forEach{ component in
            if let oprators = Operator(rawValue: Character(component)) {
                operators.enqueue(oprators)
            }
        }
~~~
- input에 대한 split을 어떻게 해줘야하나 고민을 했습니다.
    - split에 띄어쓰기와 연산자 중 어떻게 넣어야 오류없이 구현이 될지 생각을 했었는데, 피연산자 중에 마이너스 값도 들어 갈수 있다고 생각하여 마이너스 표현도 나눠지는 값이기에 띄어쓰는 split을 구현해줬습니다.

### 2️⃣해결되지 못한점 
ExpressionParse 유닛테스트를 진행하던중 parse메서드를 실행하면 큐에 추가되는 갯수에 대한 테스트를 진행하였는데, 피연산자수가 두자리숫자가 되면 아래 그림과 같이 오류가 나는데 오류에 대한 구글링을 해봤지만 찾을 수없어 해결하진 못했습니다... 이에 대한 해결방법 및 조언을 해주실 부분이 있으시다면 조언 부탁드립니다🙏
![](https://hackmd.io/_uploads/Hk1SVn7bp.png)

<br>

### 3️⃣조언을 얻고 싶은 부분
- 유닛테스트를 진행해봤는데 구현이 잘되었는지 확인부탁드리며 부족한 부분이 있다면 조언 부탁드립니다.
- 고차함수를 쓴다고 썼는데 추가적으로 쓰여질 부분이 있다면 조언 부탁드립니다.
- Formula 타입에서 옵셔널 바인딩을 해준 부분이 있는데 guard let이라는 키워드가 겹치는 부분이 있었습니다. 저는 명확성을 위해 중복된 부분을 겹쳐서 쓰진 않고 따로 써주긴 했는데, 이런경우 로웬은 어떻게 표현하는게 좀더 좋은 생각을 듣고 싶습니다.
~~~swift
guard let secondResult = operands.dequeue() else { return 0 }
            
guard let operatorSign = operators.dequeue() else { return 0 }
~~~
- 모든 케이스를 담은 배열을 리턴해주는 CaseIerable 프로토콜를 UML에 표현되어 있어 채택을 하였지만 필요하다고 생각하지 않아 구현을 해주진 않았습니다. 로웬은 어떻게 구현을 해줄수 있을지 조언을 얻고 싶습니다.
- 유닛테스트를 진행하면서 잘못된 부분은 없다고 생각하는데, 전반적인 코드에 대한 조언을 얻고 싶습니다.

2023-10-11 19:59 UTC, Tediousday93 requested changes
안녕하세요 미르 🙌
step2 고생하셨습니다.
많이 고민하신게 느껴지네요 😄

---

### ✅ 고민했던 점
**UML**
* 각 타입의 역할을 이해하려고 노력하신 부분 👍👍👍
* 접근제어, 타입 메서드 등을 잘 파악하셨습니다.
* 생각하셨던 내용을 글로 작성할 때 조금 더 다듬어주시면 좋겠네요!
* ExpressionParser: 주어진 수식 문자열을 연산자와 피연산자로 나누어 큐에 담아 Formula를 만드는 역할
* Formula: queue의 요소들을 이용해 수식의 결과를 도출하는 역할

**고차함수의 활용**
* 대부분의 반복문은 고차함수로 바꿀 수 있습니다. for-in 반복문을 잘 수정해주셨네요 👏
* 후행 클로저는 보통 첫 중괄호 왼쪽에 공백을 한 칸 줍니다.

**Split**
* 다양한 input을 고려해주셨네요 👍

</br>

### ✅ 해결되지 않은 점

**ExpressionParser**
* 해당 오류는 문자열의 길이가 1을 넘기 때문에 발생한 것입니다.
* String은 Character의 모임이기 때문에 길이가 1을 초과하면 변환에 실패합니다. 두 자리 수 뿐만아니라 음수일 경우도 변환에 실패하게 되겠죠?
* 지금처럼 공백을 두고 split하는 방법도 괜찮다고 생각합니다.
* 저는 아래와 같이 해결해봤습니다.
```swift
// Character로 변환 가능한 요소 찾기
let operatorList = input.split(with: " ")
    .filter { inputComponent in
        guard let firstCharacter = inputComponent.first else {
            return false
        }
        
        return String(firstCharacter) == inputComponent
    }
    .map { Character($0) }
    .compactMap { Operator.init(rawValue: $0) }

// operand를 먼저 구한 뒤 operand에 포함되지 않는 요소만 필터
let operandList = componentsByOperators(from: input)
let operatorList = input.split(with: " ")
    .filter { operandList.contains($0) == false }
    .map { Character($0) }
    .compactMap { Operator.init(rawValue: $0) }
```

</br>

### ✅ 조언을 얻고 싶은 부분
**UnitTest, 코드 전반 조언**
* 고민하셨던 내용과 어느 정도까지 알아봤는지, 시도해본 내용과 그 결과는 어떤지 말씀해주시면 조언을 드리기 수월해집니다 😊
* 일단 제가 볼 수 있는 만큼은 코드 코멘트에 남겨드리려고 하는 편입니다. 코멘트를 잘 확인해주세요 👀


**고차함수 활용**
* 필요한 부분에 잘 활용하신 것 같습니다. 앞으로도 자주 사용하게 될거에요. 후행 클로저 문법에 익숙해집시다 😊


**옵셔널 바인딩**
* 연속된 바인딩이 있는 경우, 아래처럼 작성하기도 합니다.
```swift
guard let secondResult = operands.dequeue(),
      let operatorSign = operators.dequeue() else { 
    return 0 
}

// 또는
guard let secondResult = operands.dequeue(),
      let operatorSign = operators.dequeue() 
else { 
    return 0 
}
```
* 해당 부분의 개선 방향은 코드 코멘트에 남겨드렸습니다.


**CaseIterable**
* 굳이 사용해보자면 operators 큐에 넣어줄 요소의 배열을 만들 때 써볼 수 있겠네요. 현재 미르의 코드에서는 그닥 큰 도움이 되진 않을 것 같습니다 😅
* 이렇게 쓰는 방법이 있구나 정도로 참고만 해주세요.
```swift
let operatorStrings = Operator.allCases
            .map { $0.rawValue }
            .map { String($0) }
let operatorsComponents = input.split(with: " ")
            .filter { operatorStrings.contains($0) }

```

</br>

### Feedback
* readme도 그렇고 pr도 그렇고 독자가 있는 "글"이죠! 따라서, 작성하실 때 글의 가독성과 나의 생각이 충분히 잘 전달되고 있는가에 대해 조금 더 고려해주시면 독자가 훨씬 편안하게 읽을 수 있을 것 같습니다~!

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/CalculatorError.swift
> +}
따로 파일을 분리하여 관리할 수도 있지만
해당 Error가 던져지는 메서드를 갖는 타입과 같은 파일에서 관리하는 것도 좋다고 생각합니다 😊
아니면 Model 내에서 관련된 파일끼리 묶어 하위 폴더를 만드는 것도 방법이 될 수 있겠네요!

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        return isEmpty ? nil : list.removeFirst()
간단한 if문을 삼항연산자로 리팩토링하셨군요 👍

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/Operator.swift
> +    }
0으로 나눌 경우 적절한 오류처리를 해주셨네요 👍👍👍

Double 타입에는 `nan` 이라는 수가 아님(not a number)을 나타내는 타입 프로퍼티가 있습니다.
이를 활용해보는 방법도 있어요 😊
```suggestion
    private func divide(lhs: Double, rhs: Double) -> Double {
        if rhs == .zero {
            return .nan
        }
        return lhs / rhs
    }
```

오류처리를 하는 방법과 오류처리를 하지 않고 조건문을 활용하여 예외사항을 만드는 방법 모두 괜찮다고 생각합니다.
일반적으로 오류처리가 조금 더 안전할 수도 있겠네요~!
두 방법 중 하나를 선택할 때 자신만의 기준을 세우시길 바랍니다 👍
이 부분은 수정하지 않으셔도 좋습니다.

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operatorSign = operators.dequeue() else { return 0 }
while let을 활용하는 방법도 있습니다.
guard문을 없앨 수 있으니 사용해보세요 👍

그리고 반복문 내에서 빠른 종료를 할 때는 
0을 리턴하기 보다는 현재까지 계산된 결과를 리턴해줘야 하지 않을까요?

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/Formula.swift
> +        guard var firstResult = operands.dequeue() else { return 0 }
마지막에 firstResult를 리턴하게 되는데 그에 맞는 네이밍이라고 생각하기 어려운 듯 합니다.
누적 합계, 현재 결과 등의 의미로 수정하면 좋겠네요!

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +
불필요한 개행은 삭제해주세요!

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/Formula.swift
> +        return firstResult
이 return 문은 다른 곳과 개행 컨벤션이 맞지 않는 것 같습니다.

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/Operator.swift
> +        return lhs / rhs
이 부분도 개행 컨벤션을 맞춰주세요!

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/Extension.swift
> +    }
고차함수 활용 👍

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        return Formula(operands: operands, operators: operators)
memberwise initializer를 잘 활용해주셨네요!
Queue 인스턴스를 생성하여 enqueue로 채워준 이후 Formula에 주입해주는 흐름이 보기 좋습니다 😊

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorscomponent = componentsByOperators(from: input)
* 상수 이름에 Camel Case를 지켜주세요 👀
* 배열의 경우 네이밍을 복수형으로 하는 편입니다.

두 상수는 현재 같은 배열로 보이는데 따로 만들어주신 이유가 있을까요?

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
같은 배열을 2회 순회하고 있기 때문에 합치는 것이 좋아 보입니다 🤔

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        operandcomponent.forEach{ component in
후행 클로저 컨벤션 주의해주세요!
```suggestion
        operandcomponent.forEach { component in
```

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorTest/ExtensionTest/ExtensionTest.swift
> +final class ExtensionTest: XCTestCase {
StringExtensionTest가 더 명확하겠네요!

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorTest/ExtensionTest/ExtensionTest.swift
> +        XCTAssertTrue((result != nil))
nil이 아님을 확인하기 보다는
AssertEqual을 활용해 ["0 ", " 1 ", " 2"] 가 나오는지 확인해야하지 않을까요?

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorTest/FormulaTest/FormulaTest.swift
> +    }
sut를 설정하는 코드가 없네요!
Formula의 메서드를 테스트할 것이기 때문에 sut는 Formula가 되어야하겠죠?!
저는 테스트의 용이성을 위해 아래와 같이 프로퍼티를 주입시켜 주는 편입니다.
이 파일 전반적으로 수정이 필요해보입니다~ 💪

테스트케이스는 잘 작성하신 것 같습니다 👍👍👍
다만, throw하는 메서드의 경우는 예외 상황에서 제대로 오류를 던지는지 테스트할 필요도 있습니다. 🤔

```suggestion
final class FormulaTest: XCTestCase {
    var operands: CalculatorItemQueue<Double>!
    var operators: CalculatorItemQueue<Operator>!
    var sut: Formula!
    
    override func setUpWithError() throws {
        try super.setUpWithError()
        operands = .init()
        operators = .init()
        sut = .init(operands: operands, operators: operators)
    }

    override func tearDownWithError() throws {
        try super.tearDownWithError()
        operands = nil
        operators = nil
        sut = nil
    }
```

2023-10-11 19:59 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorTest/ExpressionParserTest/ExpressionParserTest.swift
> +    }
한 번에 진행해도 괜찮을 것 같아요!

parse 메서드의 기능을 잘 파악해서 작성해주신 것 같습니다 👍👍👍
테스트케이스 네이밍만 조금 더 직관적으로 볼 수 있도록 수정해봅시다!
ex. 1더하기1문자열이주어질때_parse를_호출하면_Formula인스턴스에_operators의count가1이다

2023-10-11 21:25 UTC, Tediousday93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +
이 함수의 이름을 보면 input을 Operator 기준으로 나누어 배열로 반환하게 만들어야 할 것 같네요.
이름과는 맞지 않는 기능을 하고 있지만 앱을 구동했을 때 문제는 없을 겁니다.

2023-10-12 08:49 UTC, mireu79 commented on Calculator/Calculator/Model/CalculatorError.swift
> +}
확인하여 Error파일 생성후 Error가 던져지는 메서드를 갖는 타입 파일에 합쳐주었습니다.

2023-10-12 09:20 UTC, mireu79 commented on Calculator/Calculator/Model/Formula.swift
> +            guard let operatorSign = operators.dequeue() else { return 0 }
- while let을 활용하니 가독성이 좋아보이네요👍 

- 빠른종료를 해서 현재까지 계산된 결과를 리턴해주는게 좀더 흐름을 파악하는게 좋아보여 수정하였습니다!

2023-10-12 09:21 UTC, mireu79 commented on Calculator/Calculator/Model/Formula.swift
> +        guard var firstResult = operands.dequeue() else { return 0 }
네이밍 수정하였습니다!

2023-10-12 09:21 UTC, mireu79 commented on Calculator/Calculator/Model/Formula.swift
> +        return firstResult
개행 컨벤션 통일하여 수정하였습니다!

2023-10-12 12:10 UTC, mireu79 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operatorscomponent = componentsByOperators(from: input)
- 황당한 실수를 했네요...😅
- 아! 네이밍 복수형으로 하였습니다!
- 처음에 연산자와 피연산자를 구분지어 주려고 상수를 따로 만들어줬었는데, 다시보니 같은 배열로 쓰이고 있어서 상수 하나로 수정하였습니다!

2023-10-12 12:11 UTC, mireu79 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        }
이 부분도 확인되어 합치게 하여 수정하였습니다!

2023-10-12 12:12 UTC, mireu79 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        operandcomponent.forEach{ component in
넵! 주의하겠습니다!

2023-10-12 12:13 UTC, mireu79 commented on Calculator/Calculator/CalculatorTest/ExtensionTest/ExtensionTest.swift
> +        XCTAssertTrue((result != nil))
AssertEqual을 활용해 ["0", "1", "2"] 가 나오도록 수정하였습니다!

2023-10-12 12:38 UTC, mireu79 commented on Calculator/Calculator/CalculatorTest/FormulaTest/FormulaTest.swift
> +    }
Formula테스트에 대한 전반적인 수정을 하였고, 오류처리에 대한 케이스도 추가적으로 구현해줬습니다!

2023-10-12 13:11 UTC, mireu79 commented
피드백주신부분 꼼꼼하게 읽어봤습니다. 상세한 피드백 감사드립니다! 나름 PR을 신경써서 쓴다고 썼는데 부족했던 점이 많았던 거 같습니다😢  글의 가독성과 나의 생각이 충분히 잘 전달될 수 있게 작성하도록 하겠습니다!

2023-10-13 00:33 UTC, Tediousday93 reviewed
요구사항이 잘 반영되었네요!
추가 코멘트 확인해주시고 머지를 원하시면 코멘트 / 디스코드 DM 부탁드립니다~

2023-10-13 00:33 UTC, Tediousday93 commented on Calculator/Calculator/Model/Error/Formula.swift
> +        guard var presentResult = operands.dequeue() else { return 0 }
음.. 이전 결과라는 의미로 지어주신 것 같네요! 
그냥 result로 해도 괜찮을 것 같아요 🤔

2023-10-13 00:33 UTC, Tediousday93 commented on Calculator/Calculator/Model/Error/Formula.swift
> +            guard let operatorSign = operators.dequeue() else { return presentResult }
while let 에서 바인딩에 실패하면 반복문이 종료되고 메서드 마지막에 현재까지 계산한 결과를 return 하게 되는데
반복문 내부에서 guard-else를 통한 return문을 작성하는 이유가 있을까요?!

2023-10-13 00:33 UTC, Tediousday93 commented on Calculator/Calculator/Model/Error/Formula.swift
> +        while let nextResult = operands.dequeue() {
다음 피연산자를 바인딩하고 있으니 nextOperand가 좋지 않을까요? 💭

2023-10-13 00:33 UTC, Tediousday93 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            } else if let oprators = Operator(rawValue: Character(component)) {
operator 하나를 만드는데 복수형을 사용하셨네요 🤔
\`operator\` 또는 Formula에서 처럼 operatorSign을 사용해보면 어떨까요?

2023-10-13 00:33 UTC, Tediousday93 commented on Calculator/Calculator/CalculatorTest/FormulaTest/FormulaTest.swift
> +        XCTAssertThrowsError(try sut.result()) { error in XCTAssertEqual(error as? CalculatorError, CalculatorError.divideByZero)}
👍👍👍👍

후행 클로저에서 축약형을 사용하지 않고 파라미터를 명시해주는 경우에는
아래와 같이 개행을 추가해주는 편입니다.
```suggestion
        XCTAssertThrowsError(try sut.result()) { error in
            XCTAssertEqual(error as? CalculatorError, CalculatorError.divideByZero)
        }
```

2023-10-13 06:35 UTC, mireu79 commented on Calculator/Calculator/Model/Error/Formula.swift
> +            guard let operatorSign = operators.dequeue() else { return presentResult }
nextOperand와 operatorSign 각각 바인딩을 통해 명확성을 위해 기능 구분을 지어주려고 했었습니다. 그러나 guard문에서도 계산된 결과를 return을 하기에 중복된다고 생각하여 굳이 따로 써줄 필요가 없다고 생각하여 수정하였습니다!

2023-10-13 06:37 UTC, mireu79 commented on Calculator/Calculator/Model/Error/Formula.swift
> +        while let nextResult = operands.dequeue() {
수정했습니다!

2023-10-13 06:39 UTC, mireu79 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +            } else if let oprators = Operator(rawValue: Character(component)) {
`operator`로 수정했습니다!

2023-10-13 09:55 UTC, merged

2023-10-13 09:56 UTC, Tediousday93 commented
고생하셨습니다.