계산기 [STEP1] Hamzzi
yagom-academy/ios-calculator-app pull request #571
Opened 2024-02-06 09:43 UTC by kkomgi

안녕하세요 @havilog STEP1 PR 입니다.
STEP1 으로 큐(Queue) 타입(CalculatorItemQueue) 을 구현하였습니다.
STEP1 의 요구사항을 이해하고 PR 한 것인지 잘 모르겠습니다.
바쁘시겠지만 피드백 주시면 감사하겠습니다.(_ _)(^-^)

2024-02-06 14:50 UTC, havilog requested changes
구현하시느라 고생하셨어요 햄찌~!
코멘트 작성하여 수정해보시면 좋을 듯 합니다 :)

2024-02-06 14:50 UTC, havilog commented on Calculator/Calculator/Resources/Images/test.md
> +qwer
들어줘 나의 디스코드?

2024-02-06 14:50 UTC, havilog commented on Calculator/Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +final class CalculatorItemQueueTest: XCTestCase {
해당 스탭은 TDD를 기반으로 테스트를 먼저 짜는 프로젝트로 알고 있는데 테스트가 비어있는건 왜때문일까용?

2024-02-06 14:50 UTC, havilog commented on Calculator/Calculator/Controller/AppDelegate.swift
AppDelegate, SceneDelegate는 보통 `App`이라고 폴더를 만들어서 뷰와는 분리해서 넣어주심 좋아용

2024-02-06 14:50 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
https://minsone.github.io/programming/check-index-of-array-in-swift
요런걸 참고해보는 것은 어떨까요?

2024-02-06 14:50 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
이렇게 사용하면 큐 처럼은 사용할 수 있지만, 
자료구조에 대한 개념을 학습하는 의미에서
Queue의 핵심 개념인 Node를 구현하여, head와 tail을 연결해주는 것은 어떨까요? ㅎㅎ

2024-02-08 19:13 UTC, kkomgi commented on Calculator/Calculator/Resources/Images/test.md
> +qwer
제가 이걸 왜 적었을까요?...

2024-02-08 19:15 UTC, kkomgi commented on Calculator/Calculator/Controller/AppDelegate.swift
넵

2024-02-08 20:24 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
indices 속성은 아래와 같은 상황에 유용하다는 것을 알게 되었습니다
- 경계가 확실하지 않은 컬렉션을 처리할 때
- 컬렉션을 반복하고 요소 인덱스를 기반으로 검사, 작업 수행

2024-02-08 20:31 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
배열 대신 연결 리스트(linked list) 를 사용하여 구현하시는 것을 말씀하시는 것 같네요. 도전해보고 다시 PR 드리겠습니다.

2024-02-08 20:31 UTC, kkomgi commented on Calculator/Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +final class CalculatorItemQueueTest: XCTestCase {
앗...

2024-02-09 15:55 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
```swift
func get(indexPosition: Int) -> Element? {
    if storage.indices.contains(indexPosition) {
        return storage[indexPosition]
    } else {
        return nil
    }
}
```

구현에 참고가 되었습니다. node 로 구현하는 방법은 배열과 동일한 방식으로 인덱스를 사용할 수 없어서 또 다른 방법을 찾아봐야 할 것 같습니다.

2024-02-09 18:41 UTC, kkomgi commented
새해 복 많이 받으세요. 하비(@havilog)
리뷰해주신 것을 토대로 Node를 이용하여 Queue를 구현하였습니다.
덕분에 linked list 에 대한 개념을 익혔습니다.
자꾸 늦은 시간에 깃헙 알람이 가는 거 같아서 걱정이 되네요.
즐거운 명절 보내세요 ^0^

2024-02-10 11:55 UTC, havilog approved these changes
밤 새 선 채 죽으시고 ,, 고생 많으셨어요 햄찌

2024-02-10 11:55 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<Element>: CalculateItem where Element: Equatable {
CalculateItem이라는 프로토콜은 Node나 Element에 준수되어야할거 같이 생겼는데
혹시 어떤 역할이라고 생각하시나요??

2024-02-10 11:55 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
CalculatorItemQueue에 프로퍼티를 두고, enqueue할 때 + 1, dequeue할 때 - 1하는 방법도 있었을거 같은데,
요렇게 구현하시게 된 계기가 궁금해요

2024-02-10 11:55 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        guard let headNode = head else { return nil }
```suggestion
        guard let head else { return nil }
```

2024-02-10 11:55 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        tail = newNode
tail?.next도 newNode이고, tail도 newNode인걸까요??

2024-02-10 11:55 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
58번 라인에서 nil검증이 됐는데, 다시 타고 있어서 이 조건은 실행되지 않을거 같아요

2024-02-10 11:55 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
print와 같은 아이는 #if DEBUG 전처리문으로 릴리즈 버전에서는 노출되지 않도록 해보는건 어떨까요?

2024-02-10 11:55 UTC, havilog commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +        var queue = CalculatorItemQueue<Int>()
테스트 하는 아이는 보통 sut(system under test)라고 두고, CalculatorItemQueueTest가 프로퍼티로 가지고 setUpWithError시점에 initialize해주면 좋을 거 같아요

2024-02-10 11:55 UTC, havilog commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +    func testEnqueueAndDequeue() {
저는 테스트 이름은 보통 한글로 짓는 편이에요!
또한 엔큐와 디큐를 동시에 하는 테스트는 통합테스트로,
test_Enqueue를_할_수_있다() 와 같이 하나의 유닛테스트가 먼저 작성되고
통합테스트가 작성되어야할거 같아요

또한 given / when / then으로 정의하는 Behavior Driven Development 키워드로도 함 쓱 보시면 좋을 듯 합니당

2024-02-10 11:55 UTC, havilog commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +    }
음 요건 갠적인 생각인데,
요 테스트는 정의가 조금 애매한거 같아요
무언가를 실행한 경우, print가 실행된다
라던가
print했을 때의 문구는 "~~~" 이다
라던가
요런 느낌을 생각했어요!

2024-02-14 05:49 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<Element>: CalculateItem where Element: Equatable {
Node나 Element가 CalculateItem 프로토콜을 준수해야 한다는 것은 타입이 큐 내에서 관리되는 아이템임을 나타낸다고 생각합니다. 그만큼 어떠한 계산이나 연산을 지원하는 역할이 될 거 같네요..

2024-02-14 09:04 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
카운트를 직접 관리하는 방식(enqueue할 때 + 1, dequeue할 때 - 1) 은 직관적이고 간단해보일 수 있습니다. 하지만 복잡한 상황이나 다중 스레드 환경에서는 실수로 인한 오류가 발생할 수 있으니까요.(예를 들어 여러 연산이 발생하면서 enqueue 가 1번 시도가 되야 하는데 2번 될 수도 있다는 것) 제가 이 방법을 선택한 것은 큐의 현재 상태를 직접적으로 반영하고 다른 연산들이 큐에 직접적으로 영향을 미치지 않기 때문에 항상 카운트 값이 정확하게 나올 수 밖에 없다고 봅니다. 저의 경험에 의하자면 DB에서도 필드에 카운트를 따로 저장하는 방식보다 실제로 count(*)를 한다거나 max, min 값을 가져오는 방법을 사용했었습니다. 가장 안전하고 정확한 방법이라고 생각이 됩니다.

2024-02-14 11:57 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        tail = newNode
tail?.next 로 newNode 를 삽입하고 print(tail) 을 해보면 newNode를 출력합니다. 하지만 이렇게 하게 되면 큐의 구조가 달라지기 때문입니다.
- <b>head</b>: 큐의 첫 번째 노드 참조
- <b>tail</b>: 큐의 마지막 노드를 참조하지 않음
- <b>next</b>: 다음 노드를 참조

그래서 tail?.next로 이미 새로운 tail이 지정되었지만 tail에 값을 또 지정해주는 이유는 큐의 구조를 명확하게 유지하기 위해서입니다.

2024-02-14 12:00 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        }
네 불필요한 검증이 맞습니다!

2024-02-14 12:00 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        guard let headNode = head else { return nil }
참고하겠습니다 :)

2024-02-14 12:04 UTC, kkomgi commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +        var queue = CalculatorItemQueue<Int>()
네 참고해서 다시 PR 하겠습니다.

2024-02-14 12:13 UTC, kkomgi commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
오! 새로운 것을 알게 되었습니다. 감사합니다.

2024-02-14 12:26 UTC, kkomgi commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +    func testEnqueueAndDequeue() {
테스트 코드의 의도를 명확하게 표현하기 위하여 좋은 방법이네요! 통합 테스트는 유닛 테스트로 수정하였습니다.

2024-02-14 12:30 UTC, kkomgi commented on Calculator/CalculatorItemQueueTest/CalculatorItemQueueTest.swift
> +    }
코드가 애매하고 테스트 목표가 명확하지 않은 것 같아서 삭제했습니다!

2024-02-14 12:46 UTC, kkomgi commented
@havilog 하비 안녕하세요. 명절 잘 보내셨나요?
리뷰해주신 것을 토대로 코드를 수정하니 많은 공부가 되었습니다.
퇴근 후 바쁘실텐데 꼼꼼하게 봐주셔서 감사합니다.

2024-02-14 14:05 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        tail = newNode
흠 요 부분은 제가 배운 queue의 자료구조랑 다른거 같은데, 다시 확인 부탁드려요
제 기억이 맞고, 햄찌가 일반적인 링크드 리스트 개념의 queue를 구현하셨다면 tail 노드의 next는 비어있어야해서요

![image](https://github.com/yagom-academy/ios-calculator-app/assets/57659933/d83b3f3e-0969-4b2f-8aea-7978cd7c2911)

2024-02-14 14:14 UTC, havilog commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
흠 햄찌 의견에 수긍이 가네요!
다만 제 의견을 몇가지 더 말씀드리자면,

햄찌가 말씀하신 예시 (enqueue 두 번) 같은 Data Race Condition은 비동기 프로그래밍에서 발생할 수 있을 거 같아요.
그런 상황을 방지하기 위해 actor가 존재하는데요,
현재 상황은 동기 프로그래밍으로 처음 불린 enqueue가 끝날 때까지 다음 enqueue는 실행되지 않아서 데이터 정합성을 보장할 수 있을 것 같아요!

또한 Swift의 array.count가 내부적으로 어떻게 되어있는지 까보지는 못하지만,
RandomAccessCollection의 경우 시간복잡도가 `O(1)`이 걸린다고 명시가 되어있는데요,
현재는 그렇지 않아서 `O(n)`이 걸릴 수도 있을거라는 생각이 들긴 하네요!

다만 요 부분과, 남은 스탭의 priority를 잘 측정하셔서, 너무 오래걸릴 것 같다 하면 패스하고 다음 스탭 진행하셔도 좋을 듯 합니다.

![image](https://github.com/yagom-academy/ios-calculator-app/assets/57659933/fbc98526-c184-4f42-a60e-f34eb17fd57d)

2024-02-14 14:15 UTC, havilog approved these changes
👍

2024-02-15 04:42 UTC, merged