계산기 [STEP 1] chacha
yagom-academy/ios-calculator-app pull request #58
Opened 2021-11-09 08:08 UTC by ChaminLee

안녕하세요 cory! @corykim0829 
계산기 Step 1까지 구현 완료하여 PR 보내드립니다!
TDD 방식으로 처음 진행해봤는데 제가 놓친 부분이 있다면 말씀 부탁드립니다🙏🏻

---

## UML
![Calculator_Model_UML_1](https://user-images.githubusercontent.com/45652743/140879022-2b667e5b-7d49-49dd-8f1a-951211ea8223.png)

## 고민된 점 및 해결 방법

> 1. 타입 명시에 관한 부분 

`LinkedList`나 `CalculatorItemQueue`를 구현할 때에 특정한 타입을 선택해서 적어줘야 할까에 대한 고민을 해봤습니다. 현재는 계산기 프로젝트이기 때문에 유효한 타입으로는 `Double`(or `Float`)이나 `String`정도가 들어올 수 있다고 생각했습니다. 이에 특정한 타입을 정해두고 `LinkedList`나 `CalculatorItemQueue`를 구현하는 것이 아니라 generics를 활용하여 확장성있는 타입을 구현하였습니다. 또한 generics 사용시 `T`가 아닌 더 명확한 의미를 주고자 `Element`라는 키워드를 활용하였습니다

> 2. `Array` vs `LinkedList`

Queue를 구현하기 위해 어떠한 자료구조를 써야할지 고민을 해봤습니다. Array를 기반으로 queue를 구현한다면 별도의 추가 코드 없이 구현할 수 있겠지만, LinkedList의 이점이 명확하게 드러나는 것 같아 LinkedList 자료구조를 선택했습니다. 

|자료 구조|Array|LinkedList|
|---|---|---|
|장점|1. 인덱싱(검색)이 빠르다(`O(1)`)|1. 데이터 추가 및 삭제가 빠르다 <br> 2. 데이터 추가/삭제시 메모리 재배치가 필요없기에 오버헤드가 낮다  |
|단점|1. 메모리의 위치가 연속적이고 고정적이기에 오버헤드가 높다 <br> 2. 데이터 추가/삭제가 느리다 |1. 인덱싱(검색)이 느리다(`O(n)`) |

계산기 프로젝트에서는 값의 검색보다는 추가/삭제가 더 빈번하게 발생할 것이라 생각하여 `LinkedList` 타입을 선택하였고 그 중에서 `계산은 우선순위 없이 순서대로 된다`라는 부분에 착안하여 `Singly Linked List`를 구현한 후 이를 활용하여 Queue를 구현했습니다. 

> 3. TDD에 대하여 

TDD 기반으로 프로젝트를 진행해보고자 테스트 코드를 우선적으로 작성하였습니다. 테스트 코드를 짤 때 미세하게 놓친 부분들이 실제 프로덕션 코드를 구현할 때 생각이 나기도 했고 이를 수정해가며 테스트를 통과할 수 있는 코드를 작성해봤습니다. 테스트 실행 이후 code coverage를 살펴보며 커버되지 않는 부분이 있는지 스스로 피드백하며 테스트를 진행해봤습니다. 

## 질문 

> 1. code coverage에 대하여

code coverage를 살펴보던 도중 100%가 되지 않는 부분들을 확인해봤는데 아래의 코드에서 궁금한 부분이 있어 여쭙고 싶습니다. 

```swift
@discardableResult
func removeFirstNode() -> Node? {
    if head == nil {
        return nil
    } else {
        let firstNode = head
        head = head?.next
        return firstNode
    }
} // code coverage 빨간불
```
해당 메서드를 테스트 할 때 code coverage가 다른 것들과 달리 100%가 나오지 않는데, 이는 `if-else`문 내에서 `return`이 되었기 때문이라고 생각하는데 제가 생각한 부분이 맞는지 궁금합니다! 또 이런 경우 `if-else`내에서 `return`하지 않고 외부에서 `return`하도록 해야하는 것인지 궁금합니다. 

혹은 `guard` 문으로 적는다면 위에서 궁금했던 code coverage 문제는 해결(100%)되는 것 같은데 `!(느낌표)` 사용을 지양함에 따라 `else` 부분에 일부 로직이 들어가게 되었는데 이렇게 구현해도 무방할까요??
어디선가 `guard`문의 else에는 별도의 로직을 적어주지 않는 방향으로 구현하는게 좋다고 했던 것 같아 여쭙습니다!

```swift
@discardableResult
func removeFirstNode() -> Node? {
    guard head == nil else {
        let firstNode = head
        head = head?.next
        return firstNode
    }

    return nil
}
```

> 2. 테스트 코드 작성시 commit 단위에 대햐여

테스트 케이스를 생각해보고 테스트 코드를 짜다보니 현업에서는 테스트 코드 작성시 커밋 단위를 어떻게 하고 계시는지 궁금해졌습니다. 우선 저는 테스트라는 것이 각 케이스가 존재하기는 하지만 하나의 객체에 대한 테스트라고 생각하여 파일 단위로 테스트 케이스를 작성하고 커밋하였는데 이렇게 진행해도 무방한지 궁금합니다!

감사합니다!

2021-11-09 15:41 UTC, corykim0829 requested changes
수고하셨습니다 chacha! 👏

고민한 점을 깔끔하게 정리하고, 해결한 모습이 인상적이었습니다! 👍
전반적으로 코드도 깔끔하고 테스트코드도 잘 작성하였네요 👏
남겨드린 피드백 기반으로 더 개선해봐요! 😃

---

> 질문

> code coverage에 대하여

➡️ 네 생각 하신 대로 if-else 분기에서 모두 처리되고 return되어서 빨간 부분에는 테스트코드에서 접근하지 못하고 종료되어서 cover되지 못한 것입니다. 구현한 코드가 모두 cover되었으니 괜찮습니다 :)

> guard 문으로 적는다면 위에서 궁금했던 code coverage 문제는 해결(100%)되는 것 같은데 !(느낌표) 사용을 지양함에 따라 else 부분에 일부 로직이 들어가게 되었는데 이렇게 구현해도 무방할까요??
어디선가 guard문의 else에는 별도의 로직을 적어주지 않는 방향으로 구현하는게 좋다고 했던 것 같아 여쭙습니다!

``` swift
@discardableResult
func removeFirstNode() -> Node? {
    guard head == nil else {
        let firstNode = head
        head = head?.next
        return firstNode
    }

    return nil
}
```

➡️ 네 guard 문의 else에는 로직을 작성하지 않는게 좋습니다. 그 외 설명은 위에 해드린 부분에 답변이 될 것 같아요!

> 테스트 코드 작성시 commit 단위에 대햐여
테스트 케이스를 생각해보고 테스트 코드를 짜다보니 현업에서는 테스트 코드 작성시 커밋 단위를 어떻게 하고 계시는지 궁금해졌습니다. 우선 저는 테스트라는 것이 각 케이스가 존재하기는 하지만 하나의 객체에 대한 테스트라고 생각하여 파일 단위로 테스트 케이스를 작성하고 커밋하였는데 이렇게 진행해도 무방한지 궁금합니다!

➡️ 커밋 단위는 팀이나 조직마다 규칙에 맞춰서 진행합니다. 메소드 별로 할 수도 있고, 객체별로도 할 수 있겠죠. 지금은 객체가 작기 때문에 가능하지만 나중에 가면 하나의 객체에 테스트할 코드가 많을 수도 있습니다. 이러한 부분들을 잘 고려해서 기준을 세워 커밋을하면 될 것 같아요!

2021-11-09 15:41 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorItemQueueTest.swift
> +        let queue = CalculatorItemQueue<Any>()
Any 타입을 사용하면, 제너릭을 사용한 의미가 없어지는 것 같아요!

2021-11-09 15:41 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorItemQueueTest.swift
> +    func test_enqueue_in_queue() {
테스트 함수명들이 모호한 느낌이 있어서 명확한 의미 전달이 잘 안되는 것 같아요! 테스트 코드 함수는 길어져도 더 자세하게 적어야 좋습니다. 한글로 적어도 좋구요!

2021-11-09 15:41 UTC, corykim0829 commented on Calculator/CalculatorTests/LinkedListTest.swift
> +class LinkedListTest: XCTestCase {
이 부분 테스트도 CalculatorItemQueueTest 피드백과 동일하게 수정해주면 될 것 같아요!

2021-11-09 15:41 UTC, corykim0829 commented on Calculator/Calculator/Model/LinkedList.swift
> +    func appendNewNode(value: Element) {
함수명이 `appendNode`가 아닌 `appendNewNode`라고 한 이유가 있나요?

2021-11-09 15:41 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    @discardableResult
깔끔하게 잘 사용하셨네요 👍

2021-11-09 15:41 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var items = LinkedList<Element>()
private으로 선언하지 않은 이유가 있나요?

2021-11-09 15:41 UTC, corykim0829 commented on Calculator/Calculator/Model/LinkedList.swift
> +class LinkedList<Element> {
LinkedList를 깔끔하게 구현 잘하셨네요! 👍

2021-11-10 00:55 UTC, ChaminLee commented on Calculator/CalculatorTests/CalculatorItemQueueTest.swift
> +        let queue = CalculatorItemQueue<Any>()
앗 그러네요..! 피연산자와 연산자를 함께 넣어 테스트해보고 싶어서 `Any` 타입으로 선언해줬었는데, 말씀해주신 것 처럼 그러면 제네릭의 의미가 없어지겠네요! 각각 타입을 명시해주는 방식으로 수정하겠습니다!

2021-11-10 01:06 UTC, ChaminLee commented on Calculator/CalculatorTests/CalculatorItemQueueTest.swift
> +    func test_enqueue_in_queue() {
중간에 너무 길어지는 느낌이 있어서 줄여보려고 했는데, 말씀주신 것 처럼 한글로 조금 더 명확하게 의미를 담아서 네이밍을 하는 방향으로 수정해보겠습니다!

2021-11-10 01:08 UTC, ChaminLee commented on Calculator/Calculator/Model/LinkedList.swift
> +    func appendNewNode(value: Element) {
처음에는 "새로운 노드가 추가된다"라는 의미로 New를 붙였는데, 생각해보니 새로운 노드가 아닌 기존 노드가 들어올 수도 있고 아닌 다른 경우도 있을 것 같네요..! New를 붙인 케이스와 붙이지 않은 케이스를 고민하다가 결국에는 붙여서 사용하였는데, 조금 더 범용적인 네이밍이 좋을 것 같네요! `appendNode`로 수정해보겠습니다~

2021-11-10 01:11 UTC, ChaminLee commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var items = LinkedList<Element>()
이 부분은 놓쳤던 것 같습니다..ㅠㅠ 외부에서는 값을 변경할 수 없고, 볼 수 없도록 `private`으로 지정해주고자 합니다. 만약 외부에서 값을 봐야할 필요할 일이 있다면 추가 메서드를 만들어 이용하는 방식으로 진행해보겠습니다~!

2021-11-10 02:41 UTC, ChaminLee commented
안녕하세요 cory! @corykim0829 
남겨주신 코멘트들 확인하고 개선사항들 반영하였습니다~!
꼼꼼하게 리뷰해주셔서 감사합니다!! 

--- 

추가적으로 한 가지 궁금한 부분이 있습니다! `CalculatorItemQueue`를 테스트하기 위해 `items`의 프로퍼티를 이용해서 값을 비교하였는데, 코멘트 달아주신 것 처럼 `items`에 접근 제어자를 달아주려고 처음에는 프로젝트 내에서 직접적으로 `items`를 부르거나, 값을 변경해주는 일이 없을 거라고 보고 `private`를 생각했었습니다. 하지만 테스트 코드 내에서 `items`를 사용하고 있어 결국에는 `private(set)`으로 두었는데요, 이렇게 테스트 코드에 영향을 받아 프로덕션 코드의 접근 제어자를 설정해주는 방식이 올바른 것인지 궁금합니다!!

2021-11-11 02:36 UTC, corykim0829 approved these changes
수고 많으셨어요 차차! 👏👏👏👏

테스트도 함수도 꼼꼼해서 좋네요 ㅎ
남겨드린 피드백은 다음 스텝 진행하면서 해주시고, DM으로 다음 스텝 PR 목표 일정 말해주세요!

2021-11-11 02:36 UTC, corykim0829 commented on Calculator/CalculatorTests/LinkedListTest.swift
> +    func test_링크드리스트가_비어있는지() {
실제 empty 한 경우도 값을 잘 반환하는 지 확인하면 좋을 것 같아요!

2021-11-11 02:37 UTC, corykim0829 commented
제가 질문을 나중에 봤네요!

> 추가적으로 한 가지 궁금한 부분이 있습니다! CalculatorItemQueue를 테스트하기 위해 items의 프로퍼티를 이용해서 값을 비교하였는데, 코멘트 달아주신 것 처럼 items에 접근 제어자를 달아주려고 처음에는 프로젝트 내에서 직접적으로 items를 부르거나, 값을 변경해주는 일이 없을 거라고 보고 private를 생각했었습니다. 하지만 테스트 코드 내에서 items를 사용하고 있어 결국에는 private(set)으로 두었는데요, 이렇게 테스트 코드에 영향을 받아 프로덕션 코드의 접근 제어자를 설정해주는 방식이 올바른 것인지 궁금합니다!!

테스트 코드의 영향으로 private(set)으로 처리한거긴 하지만, private(set)은 아주 괜찮은 접근입니다. 외부에서 값을 읽는 것은 코드나 값에 영향을 주는게 아니라서 객체지향에서 아주 좋습니다.

2021-11-11 02:38 UTC, merged

2021-11-11 02:54 UTC, ChaminLee commented on Calculator/CalculatorTests/LinkedListTest.swift
> +    func test_링크드리스트가_비어있는지() {
넵 참고해서 테스트 케이스 추가해보도록 하겠습니다!