계산기 [Step1] Allie
yagom-academy/ios-calculator-app pull request #64
Opened 2021-11-09 10:39 UTC by wooyani77

@GREENOVER 
안녕하세요, 그린! 🍏 
계산기 step1 PR 드립니다!

부족한점이 많습니다 :) 리뷰 잘 부탁드려요!

### 고민되었던 점

- ✔️ `CalculatorItemQueue`의 메서드에 대한 test case를 작성하면서, 접근제어를 설정해주어야하는지에 대해 고민이 되었어요. 
    아래와 같이, 접근제어를 해주면 테스트를 진행할 때, `enQueueArray`에 접근할 수 없어서 count 메서드를 만들어서 이용하는 방법으로 고민을 해보았어요. 
    그런데 제가 테스트해보고 싶은 건 array의 요소들이 잘 들어가 있는지였는데, count는 array의 요소의 개수만 알려주더라구요 :cry: 
    테스트를 위한 메서드를 만들어주는 방법도 있겠지만, 일단은 접근제어를 설정해주지 않는 방법으로 해보았습니다..!
    ```swift
    private(set) var enQueueArray: [T] = []
    private(set) var deQueueArray: [T] = []

    var count: Int {
        return enQueueArray.count
    }
    var deQueueCount: Int {
        return deQueueArray.count
    }
    ```

- **Unit test**를 처음으로 작성해보았어요!
    `enQueue()` 메서드는 append를 하는 기능만 가지고 있는데, 이 메서드에 대해서 테스트를 할 필요가 있을지에 대한 고민을 했습니다. 
    append는 swift 기본 라이브러리에 구현되어있는 함수인데 그 기능에 대해서 테스트를 해야하나,,라는 고민이 있었지만 일단은 진행해보았습니다! 
    단위테스트를 처음 해보니까, test case 자체를 만드는데도 어려움이 있었어요..! 어떤 것을 더 검증해야하는지 생각이 잘 안나서 괴로웠습니다ㅎㅎ..!

- Queue 타입을 구현할때, 처음에 아래와 같이 작성을 했었습니다.
    ```Swift
    struct CalculatorItemQueue<T>: CalculateItem {
        var queue: [T] = []

        mutating func enQueue(_ element: T) {
            queue.append(element)
        }

        mutating func deQueue() -> T? {
            if queue.isEmpty {
                return nil
            }
            return queue.removeFirst()
        }
    }

    ```
    다른 캠퍼들과 이야기 하다보니 기존 방식은 시간복잡도가 O(n)이라 `Double Stack`을 이용해서 현재 방식으로 바꿔주었는데요,
    현재 방식도 메모리에 두개의  `var enQueueArray: [T] = [], var deQueueArray: [T] = []`가 공간을 차지하고 있다고 생각이 되어서 어떤 방식이 더 나은건지 아직 잘 모르겠습니다..!

2021-11-09 13:57 UTC, GREENOVER requested changes

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
제네릭을 T로 정의한 이유가 무엇인가요~?🙋🏻
스위프트 공식문서에서는 제네릭을 어떻게 표현하고 있을까요🧐
(틀렸다는것이 아닙니다!)

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueArray: [T] = []
해당 네이밍에 어떤 의미가 있는건지 궁금합니다🙋🏻
이후 스텝에서 해당 프로퍼티들을 사용할텐데 그때 해당 네이밍이 적절할지도 궁금해요!
뭔가 가독성이 떨어질것 같다라고 생각했어요.

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func deQueue() -> T? {
deQueue는 큐에서 빼는 느낌인데반해 해당 메서드 시그니쳐에 반환값도 들어있습니다.
그렇기에 좀 더 어울리는 네이밍이 있을것 같아요.
음.. 로직을 보면 결국 `enQueueArray`의 첫번째 요소를 픽업해오는것과 동일하게 보여서 메서드명만으로
그걸 알 수 있는 네이밍은 어떨까요🧐

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func enQueue(_ element: T) {
enQueue와 deQueue가 흔히 배열에 더하고 뺄때 사용해주는 메서드명이긴한데
커스텀하게 만들고 계신다면 좀 더 괜찮은 네이밍도 있을것 같습니다!
제 의견일뿐이라 앨리 생각도 궁금합니다🙋🏻

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +            return nil
nil 반환도 좋습니다!
그렇지만 추후 스텝을 위해 에러처리를 간단하게 만들어두면 어떨까하는 의견이 있습니다🙋🏻

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_enQueue에_요소를_추가했을때_잘들어가는지() {
테스트 메서드 네이밍에 정답은 없지만 혹시 추후 글로벌 동료와 협업한다면 이 코드는 어려움이 있을것 같아요🙋🏻
정말 개인적인 스타일의 차이지만 최대한 저는 한글을 지향하고 있습니다.
물론 앨리가 만든 테스트 메서드명을 보고 어떤 테스트인지 파악이 잘되어서 좋았지만,
코드와 영문 메서드명으로 그걸 잘 표현해내는것도 연습일것 같습니다!
정말 현업가면 네이밍 짓기가 너무 어려우니.. 습관처럼 연습이 필요하더라구요😅

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        }
if let으로 바인딩한 이유가 궁금합니다🙋🏻

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
구조체로 타입을 정의한 이유가 궁금해요~!🙋🏻

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +        return deQueueArray.removeLast()
로지컬하네요👍

2021-11-09 13:57 UTC, GREENOVER commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		FB011352273A57BA00310758 /* CalculatorItemQueueTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = FB011351273A57BA00310758 /* CalculatorItemQueueTests.swift */; };
추후 스텝에서 진행될 수도 있겠지만..!
기능에 맞는 그룹화를 시키면 더 좋을것 같습니다🙋🏻

2021-11-09 13:58 UTC, GREENOVER commented
@wooyani77 
안녕하세요 앨리🙌
2주동안 계산기 리뷰를 맞게되어서 영광입니다😁
저의 리뷰는 정답이 아니라 의견을 나누는 자리임을 다시 강조드리면서 저도 같은 팀원이라고 생각해주세요!
2주 잘부탁드립니다~
***
### 칭찬드리고 싶은 부분
- 협의한 프로젝트 일정에 맞춰 잘 진행되었네요💯
- UML 명세대로 구현이 잘 된점 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. 접근제어자 관련
- 접근제어자를 붙여야되는 이유가 어떤걸까요?🧐
접근제어자를 붙이고 싶다면 앨리가 위에 언급한바와 같이 `private(set)`을 사용하면 될것 같은데 다른 문제가 있었나요??
카운트 프로퍼티를 만들어두어도 좋을것 같은데 PR 코드에서는 없애셨던것도 궁금합니다!
음.. 테스트와 대부분 관련이 있는데 바로 밑에서 다시 테스트에 대해서 자세히 말해볼께요☺️
2. Unit test 관련
- 우선 테스트코드에 대해서 이런 마이너한것까지 짜야하나라는 생각이 정말 저도 많이 드는데.. 정말 제대로된 테스트코드는 모든 경우의 수를 가지고 있습니다.
append에 대해 현재 구현된 테스트코드에서 만약 nil을 넣을수도 있고 Int로 Queue를 만들었는데 문자가 들어올 수도 있고 정말 다양한 에러가 존재한다고 생각해요.
이렇기에 테스트코드를 짜는 시간이 실제 코드를 짜는 시간보다 더 오래걸리게 되는것이고 그걸 지키는게 쉽진 않지만(저도 잘 안되지만ㅠ) 이상적인 TDD 방법론이라고 생각합니다.
현재 앨리도 많은 테스트 코드를 정의해주셨지만 Int, Double, Char등 타입에 따라서 모든 경우에 대해 더 추가할 수도 있다고 보입니다.
정말 생각하면 무궁무진한것이 테스트 코드라 어느정도로 짜야할지에 대해서는 정답은 없습니다.
다만 앨리가 앞으로 스텝을 진행하면서 문제가 될것 같거나 예측되는 모든 값들에 대해서는 테스트 코드를 추가하는게 맞다고 생각합니다!
append는 말씀하신대로 기본 스위프트에서 지원하는 라이브러리지만 사실 그걸 받아서 구현하는 enQueue나 deQueue 같은 경우는 표면상 append만 해주기에 문제가 없을것이다 생각하지만 결국 프로그래머가 짠 로직이자 코드이기에 문제가 없을거라고 단정짓는건 위험합니다😅
- 테스트 코드 메서드마다 queue를 매번 생성하게 되는데 `setUp`과 `tearDown`도 알아보시면 도움이 될것 같습니다🙋🏻
- 테스트 코드 네이밍에 대해서도 저의 의견(정답아님!)을 리뷰 코멘트에도 남겨봤습니다😄
3. 시간복잡도 관련
- 스택을 더블로 두는것의 메모리 효율과 하나의 스택으로 이용할때의 시간복잡도 사이에 성능에 관한것인데, 저는 프로퍼티를 하나 더 두는것이 성능에 큰 영향을 미치지 않는다고 생각합니다.
캠퍼들과 앨리가 의견을 나눈바와 같이 하나의 스택으로 로직을 구성한다면 O(n)만큼 시간복잡도가 들것이고 만약 정말 그안에 담긴 요소가 너무 많다면 점점 비효율적일것입니다.
음.. 그럼 배열 변수가 미치는 메모리에 대해서 한번 알아보시면 어떤게 더 효율적인지 더 잘 알 수 있으실것 같습니다😄
***
### 궁금한점
- 현재 하나의 큐에서 연산자와 피연산자 모두 담기게 구성을 하시는건지?
아니면 두개로 나눠서 로직을 가져가실건지 궁금하네요!
아직 공통된 구현만 있어서 코드만 보고는 판단이 잘 안되었습니다😅
하나의 큐에서 계산 시 모든걸 deQueue로 처리해줘야한다면 어떻게 하실지도 궁금해요!
아마 험난할것 같긴해서..
- 현재 테스트코드에서 Int만 검증하고 있는데 Double 타입도 염두해 두신건지 궁금합니다.
Int와 Double을 모두 하나의 피연산자큐에 같이 담는다면 계산 시 형변환을 해주셔야될것 같아서 모두 우선 Double로 담아 계산하고
UI에 보여줄때 결정하면 어떨까 싶습니다🙋🏻
***
우선 스텝1의 필수 요구사항이 좀 애매하긴 하지만 구현되야될 사항은 되었다고 봅니다..!
다만 앞으로 어떤 방향으로 갈지에 대해서 정해져야 머지를 할 수 있을것 같아요..!
왜냐하면 그거에 따라 필수구현이 덜 이루어졌는지 판단할 수가 있을것 같습니다
(현재는 애매해서 판단이 잘 안서네요😅)
그래서 우선은 잘못된 부분은 없지만 Request Changes로 해두겠습니다🙏🏻
위의 저의 궁금한점에 코멘트를 남겨주시면 감사하겠습니다🙇🏻
고생 많으셨습니다 앨리! 
제 코멘트에 이해가 안되거나 궁금한것 그리고 제가 잘못 이해한 부분은 언제든 말해주세요!👍

2021-11-10 08:41 UTC, wooyani77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
다른 예제들을 참고할 때, 대부분 T로 정의가 되어있어서 사용했습니다! 공식문서를 읽어보니 빈 배열로 된 프로퍼티를 선언할 때, Element를 placeholder로 사용한다고 하네요 😅  언제나 공식문서를 우선적으로 보도록 하겠습니다!ㅎㅎㅎㅎ

2021-11-10 08:44 UTC, wooyani77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +struct CalculatorItemQueue<T>: CalculateItem {
`CalculatorItemQueue`를 구조체로 만들어준 이유는, 참조 타입인 class로 만들어준다면 여러 인스턴스가 있을 때, 원본의 값이 변경될 수 있기 때문에 값 타입인 구조체로 만들어줘야한다고 생각했습니다! 구조체로 만들어주면 각 인스턴스는 복사본을 갖고있게되어 원본에 영향을 주지 않기 때문에요!

2021-11-10 09:03 UTC, wooyani77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueArray: [T] = []
단순히 삽입, 삭제를 전담하는? 배열이라서 저렇게 네이밍을 해주었습니다. 다음 스텝까지 생각한다면 적절하게 변경해주는게 가독성을 위해서도 좋을 것 같아요! 그런데 1) inputArray, outputArray / 2) inbox, outbox 정도로 생각해 보았는데, 뭐가 더 나은지 잘 모르겠습니다.. 😓  그린이 보시기엔 어떤가요?ㅠㅠ

2021-11-10 09:21 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueArray: [T] = []
음 저는 array라는 네이밍보다 items이나 elements와 같이 요소를 담고 있는걸 표현해주는건 어떨까 싶었어요!
정말 네이밍은 항상 어렵고 정답이 없지만..
어레이라는 네이밍보다 좀 더 명확히 표현하는것이 어떨까 의견을 드려봅니다🙋🏻

2021-11-10 09:23 UTC, wooyani77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func deQueue() -> T? {
해당 메서드는 사용처에서 입력받은 값을 하나씩 빼내올 때 사용하고 있는데, deQueue 자체로 빼내온 값을 반환한다는 의미를 갖고있어서 저렇게 네이밍 했습니다. `deQueueFirstElement` 정도로 수정하면 어떨까요? 🧐

2021-11-10 09:25 UTC, wooyani77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func enQueue(_ element: T) {
위와 같은 이유로 큐에 삽입, 삭제하는 기능을 나타내도록 작성해주었습니다..! 네이밍은 항상 어려운 문제인 것 같아요 😢 😢

2021-11-10 09:25 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func deQueue() -> T? {
네 좋습니다!
deQueue만으론 빼오긴하지만 어떤것을 빼오는지 명확하지 않다고 생각이 들었는데
훨씬 명확해져서 저는 더 나은것 같습니다!
개개인의 코드 스타일 차이라 제가 맞다 할순 없지만 많은 라이브러리들을 보면서 주로 어떤 네이밍을 대중적으로 사용하는지
보면 많은 도움이 될거에요🙌

2021-11-10 09:25 UTC, wooyani77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +            return nil
넵! 에러처리 해주도록 하겠습니다!ㅎㅎ

2021-11-10 09:28 UTC, wooyani77 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		FB011352273A57BA00310758 /* CalculatorItemQueueTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = FB011351273A57BA00310758 /* CalculatorItemQueueTests.swift */; };
폴더를 나누어보라는 말씀이시죠? 😄  수정 하도록 하겠습니다!

2021-11-10 09:29 UTC, wooyani77 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_enQueue에_요소를_추가했을때_잘들어가는지() {
야곰닷넷에서 Unit test에 대한 강의를 보는데 case에 한글이 있어서 저도 모르게 당연히? 한글을 쓴 것 같아요ㅎㅎ 추후에 글로벌 동료와 협업한다면 역시 영어로 작성하는 습관도 들여야겠네요! 감사합니다. 💯

2021-11-10 09:30 UTC, GREENOVER commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    mutating func enQueue(_ element: T) {
그쵸 정답이 없어서 더욱 어렵습니다..!
그치만 충분히 잘하고 계시고 이런 네이밍 고민을 하는 과정들이 추후 도움이 많이 될겁니다👍
정답은 없지만 대중적인것은 있으니까요😁

2021-11-10 09:31 UTC, GREENOVER commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		FB011352273A57BA00310758 /* CalculatorItemQueueTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = FB011351273A57BA00310758 /* CalculatorItemQueueTests.swift */; };
네 맞습니다..!

2021-11-10 09:33 UTC, GREENOVER commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        }
혹시 그러면 바인딩이 잘못되어서 if문을 타지 않아도 해당 테스트는 통과될것 같은데 의도된건가요~?🧐

2021-11-10 09:34 UTC, wooyani77 commented on Calculator/Calculator/CalculatorItemQueue.swift
> +    var deQueueArray: [T] = []
코드 내에서 전반적으로 element라는 단어를 많이 사용하고 있어서`enQueueElements`와 `deQueueElements`로 수정했습니다! 의견 감사합니다!! 🥂

2021-11-10 09:36 UTC, GREENOVER commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_enQueue에_요소를_추가했을때_잘들어가는지() {
저도 스타일의 차이일뿐이라..!
많은 캠퍼들이 무의식속에 한글로 당연하게 받아들이시는것 같아서요..!
당연 잘못된것도 아니고 테스트코드 메서드명이라는게 같이 협업하는 사람들이 더욱 잘 이해할 수 있도록 짓는것이기에
한글 메서드명이 현재 더 올바른 방향일 순 있지만
우리 애플갈꺼니까~ 영어 네이밍의 연습도 필요할것 같아서 말씀드렸습니다!

2021-11-10 09:37 UTC, wooyani77 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +        }
테스트를 하면서 바인딩이 안될 경우에 대해서는 생각을 하지 않았네요..! 하하.. 😭  else로 예외 상황에 대해서도 대비하는게 맞을 것 같습니다..!

2021-11-10 09:39 UTC, wooyani77 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
> +    func test_enQueue에_요소를_추가했을때_잘들어가는지() {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ애플 갈거니까..! 이런부분 너무 좋습니다!! 저두 영어 네이밍 연습도 꼭 해야한다고 생각합니다!

2021-11-10 11:30 UTC, wooyani77 commented
1. 접근제어자 관련
접근제어자를 붙여야되는 이유는 외부에서 array들에 접근해 마음대로 값을 바꿔줄 수 있다면, 삽입 및 삭제 연산의 존재의 의미가 없다고 생각해요. 그래서 접근제어를 붙여서 마음대로 접근할 수 없도록 막아주어야 한다고 생각합니다~ 저번에는 private(set)을 사용했을 때, test 코드에서 해당 array들에 접근이 불가능 했었던 것 같은데 제가 private하고 혼동했던 것 같아요!

카운트 프로퍼티는 테스트를 위해 만들어봤었는데, 저는 값을 비교해서 확인하고 싶었는데 카운트 프로퍼티는 값이 아닌 개수로 비교한다는 점에서 제가 의도한 바가 아닌 것 같아 삭제해주었습니다.ㅎㅎ

2. Unit test 관련
제가 짠 로직이자 코드이기에 문제가 없을거라고 단정짓는건 위험한 생각이라는 걸 다시 느꼈습니다..! 😓  앞으로 스텝을 진행하면서 문제가 될것 같것 같은 값들에 대해서는 테스트 코드를 추가해보도록 하겠습니다!
클래스의 각 테스트 메소드의 호출 전,후에 호출되어서 setUp은 초기화를 하고 tearDown 해체하는 메서드라고 나오네요!
해당 메서드들을 이용하면, 테스트 코드를 좀 더 깔끔하고 유연하게 작성할 수 있을 것 같습니다 😄 

3. 시간복잡도 관련
배열 변수와 메모리에 대해서 공부해보도록 하겠습니다ㅎㅎ 의견 감사해요 그린!!

4. 현재 하나의 큐에서 연산자와 피연산자 모두 담기게 구성을 하시는건지? 
-> 네! step1에서 각각 담아야한다는 요구사항이 없다고 생각되어 우선 하나의 큐만 구현해주었습니다~ step2에서는 두개로 나누어 로직을 가져갈 예정입니다ㅎㅎ
5. 하나의 큐에서 계산 시 모든걸 deQueue로 처리해줘야한다면 어떻게 하실지도 궁금해요! 
-> 이부분에 대해서는 생각해보지 않았습니다..! 아마 두개로 나누어 진행할 것 같아요!
6. 현재 테스트코드에서 Int만 검증하고 있는데 Double 타입도 염두해 두신건지 궁금합니다. Int와 Double을 모두 하나의 피연산자큐에 같이 담는다면 계산 시 형변환을 해주셔야될것 같아서 모두 우선 Double로 담아 계산하고 UI에 보여줄때 결정하면 어떨까 싶습니다🙋🏻
-> Double 타입은 염두에두지 않았습니다. 그린의 조언대로 우선 Double로 담아 계산하고 UI에 보여줄 때 결정하는 방법으로 해볼게요!

---
개인 프로젝트는 처음이라 많이 걱정되었는데, 그린의 리뷰덕분에 많이 배워가는 것 같습니다 👍 
질문주신 사항에 대해서 나름대로 답변을 달아보았는데, 더 궁금하신 부분이 있으시면 말씀해주세요!
감사합니다!! 😃

2021-11-10 11:50 UTC, GREENOVER approved these changes
고생하셨습니다 앨리!
전반적으로 더 가독도 좋아지고 개선 되었네요👍
마이너한 두가지 이슈 및 코멘트를 달아놓았습니다!
간단히 보완할 수 있는 부분이라고 보고 스텝2에서 수정하여 진행하시면 될것 같아 머지하겠습니다~😁
스텝2 요구사항을 충분히 보고 설계하신 후 목표기한을 말씀해주시면 감사하겠습니다!
화이팅입니다👍

2021-11-10 11:50 UTC, GREENOVER commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				C713D9432570E5EB001C3AFC /* SceneDelegate.swift */,
AppDelegate와 SceneDelegate 파일을 Controller 그룹에 묶어준 이유가 있을까요?
어떤 의미에서 같이 그룹화를 진행했는지 궁금해요🙋🏻
제가 생각하는 컨트롤러는 뷰에 대한 컨트롤러라고 생각했어요!

2021-11-10 11:50 UTC, GREENOVER commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
>      }
요 테스트 케이스 에러가 나는데 한번 확인해보시면 좋을것 같습니다🙋🏻

2021-11-10 11:51 UTC, merged

2021-11-10 13:59 UTC, wooyani77 commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				C713D9432570E5EB001C3AFC /* SceneDelegate.swift */,
지난 프로젝트에서는 Controller 폴더에 AppDelegate와 SceneDelegate 파일이 들어있더라구요..! 어떻게 해야할지 몰라서 지난 프로젝트 참고해서 controller에 넣어주었습니다! 혹시 delegate 파일들은 어디에 넣어줘야할까요? 😮

2021-11-10 13:59 UTC, wooyani77 commented on Calculator/CalculatorItemQueueTests/CalculatorItemQueueTests.swift
>      }
앗 step2 하면서 확인해 보겠습니다! :)