계산기 [STEP 1] 고사리
yagom-academy/ios-calculator-app pull request #71
Opened 2021-11-09 14:17 UTC by FIIIIN

안녕하세요, 엘림(@lina0322)😸

계산기 프로젝트의 리뷰를 부탁드리게 된 고사리입니다.

아직 모르는 것이 많습니다. 이주동안 잘 부탁드립니다🙏

# 고민한 점

### 연산Queue를 `Linked List`로 구현하였습니다

- Array의 프로퍼티 `last`의 시간 복잡도가 O(1)인 것을 확인하고, Array는 FIFO인 Queue를 구현하기에 적합하지 않다는 생각을 했습니다.
- 이때 떠올린 연결 리스트의 위키백과([https://ko.wikipedia.org/wiki/연결_리스트](https://ko.wikipedia.org/wiki/%EC%97%B0%EA%B2%B0_%EB%A6%AC%EC%8A%A4%ED%8A%B8)) 의 내용을 참고해보았습니다.
    - Linked List(연결 리스트)는 노드의 중간지점에서도 자료의 추가와 삭제가 O(1)의 시간에 가능하다는 장점이 있습니다.
    - 추가와 삭제가 핵심이라고 판단되는 계산기 프로그램이기 때문에 Array 대신 Linked List를 선택하였습니다.

### 제네릭 타입의 필요성을 느꼈습니다

- Node나 LinkedList 타입의 경우, 재사용성을 고려해야 한다고 생각하였습니다.

### 함수의 이름을 `test_Elements`로 작성하였습니다

- 연결 리스트의 elements를 배열로 반환하는 함수인 만큼, 명사형인 편이 호출부에서의 가독성이 향상될 것으로 판단하였습니다.
- 현재로서는 유닛 테스트에서 결과를 확인하는 용도이기 때문에 테스트 파일과 동일한 `test_` 를 붙였습니다.
    - 해당 네이밍은 함수의 사용성이 증가할 경우 대체될 수 있습니다.

### 테스트 단위를 고민해보았습니다

- 파라미터의 단위가 한정되어있기 때문에 작성한 테스트 단위 외에 고려해봄직한 오류 케이스를 떠올리기 어려웠습니다.

# 해결하지 못한 문제

- 제네릭 타입으로 변경을 시도하며 생긴 문제로, 두 번 들여쓰기를 지양하고자 했지만 해결하지 못했습니다.

```swift
while current != nil {
            if let currentValue = current?.value {
                listItems.append(currentValue)
            }
            current = current?.next
        }
```

- 클래스 Queue가 Generic 타입의 LinkedList를 상속받지 못하여 Node 타입을 포함하여 모두 제네릭이 아닌 String 타입으로 작성하였습니다.

2021-11-10 11:39 UTC, lina0322 requested changes
안녕하세요, 고사리~
반가워요😀

아직 모르는게 많다니, 더 기대되는군요!
앞으로 발전할 것이 많은 가능성이 넘치는 캠퍼라니, 반가워요👍

### 연산Queue를 Linked List로 구현하였습니다
Linked List와 Queue 구현한 것 잘 보았어요~
다만, 제가 일반적으로 보던 느낌과는 조금 차이가 있는데, 어떤걸 보면서 학습했을까요?
추가로 동료들의 코드를 보면서 어떤 차이가 있는지 생각해보면 좋을거같아요.

### 제네릭 타입의 필요성을 느꼈습니다
혹시 제가 코드를 다 못본건가요ㅠ.ㅠ 코드에는 제네릭이 없던데..
느끼긴 했지만, 아래 문제때문에 사용을 못한걸까요?!
제네릭을 사용해서 코드를 한번 리팩토링 해줄 수 있나요? 
그 부분이 어렵게 느껴진다면,
제네릭은 무엇이고 어떻게 사용하는 것인지 예를 들어서 설명해주는 것으로 마무리해도 좋고요!

### 함수의 이름을 test_Elements로 작성하였습니다
테스트 함수의 이름을 이와 같이 작성하는건 아주 좋아요.
하지만 실제 코드에 테스트 코드를 담는 것은 좋은 방법은 아닌 것 같아요.
실제 사용하는 코드가 잘 돌아가는지 확인하기 위해서 하는 것이 테스트 코드니까
테스트의 의미를 다시 한 번 생각해보고, 전체적으로 코드를 점검해보는 것이 좋겠어요~

### 테스트 단위를 고민해보았습니다
테스트는 기능이 늘때마다 하나씩 더 늘려 나가면 되니까 지금도 좋아요~

### 해결하지 못한 문제
```swift
while current != nil {
    if let currentValue = current?.value {
        listItems.append(currentValue)
    }
    current = current?.next
}
```
while 조건문에 `let currentValue = current?.value`를 넣으면 어떻게될까요?🙂

### 제네릭이 아닌 String 타입으로 작성하였습니다.
위에서 얘기 했던 것처럼
한번 천천히 생각해보고 제네릭으로 변경을 시도해보는걸 추천드려요!
너무 어려우면 혼자하지말고 동료들과 함께 해보고, 
그래도 어려우면 저에게 말씀해주세요~

추가로 궁금한 부분 있으면 언제나 편하게 DM 주세욥!

2021-11-10 11:39 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    init(value: String, next: Node?) {
매번 next에 nil을 넣어주는 것 보다 좋은 방법이 있지 않을까요?😀

2021-11-10 11:39 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +        }
guard와 if는 어떤 기준으로 선택하고 있나요??

2021-11-10 11:39 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    }
test 코드를 여기다 작성하는게 맞나요?🥲

2021-11-10 11:39 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    }
delete 동작에 문제는 없었나요?🤔

2021-11-10 11:39 UTC, lina0322 commented on Calculator/Calculator/Model/Queue.swift
> +class Queue: LinkedList {
Queue가 LinkedList를 사용하면서 또 상속 받고 있네요.
어떤 구조로 두 가지를 구성했는지, 혹시 설명 해줄 수 있나요?

2021-11-11 02:28 UTC, FIIIIN commented on Calculator/Calculator/Model/LinkedList.swift
> +    init(value: String, next: Node?) {
Node 타입의 초기화로 nil 값을 넣어주면 매번 nil을 중복하여 넣어주지 않아도 된다는 것을 떠올렸습니다. 아래와 같이 수정했습니다.

```swift
init(value: T?, next: Node? = nil) {
        self.value = value
        self.next = next
}
```

2021-11-11 03:28 UTC, FIIIIN commented on Calculator/Calculator/Model/LinkedList.swift
> +        }
저는 guard 와 if 의 차이를 처리방식에 두고 선택하고 있습니다.
조건이 true일 경우 따라붙는 코드를 실행하는 `if`와 다르게 `guard`는 조건이 false일 경우 (else 뒤에) 따라붙는 코드를 실행하는데, 이 안에는 `제어문 전환`을 위한 return, throw, break 등이 사용됩니다.

따라서 위의 코드는 `guard` 문보다는 `if` 문 사용이 적절할 것으로 판단했습니다!

2021-11-11 03:36 UTC, FIIIIN commented on Calculator/Calculator/Model/LinkedList.swift
> +    }
해당 코드의 쓰임에 대해 고민해보았습니다.

이후 스탭에서 요소를 어떻게 활용하여 사칙연산을 진행할지에 대해서는 아직 불분명하지만, 요소의 배열을 예외처리에 활용해보아도 괜찮을 것 같다는 판단을 하였습니다. 따라서 test_를 제거하는 방향으로 리팩토링 진행해보았습니다.

해당 케이스에 대해 저는 위와 같이 판단하여 진행했는데, 엘림의 의견이 궁금합니다.
` 테스트의 의미를 다시 한 번 생각해보고, 전체적으로 코드를 점검해보는 것이 좋겠어요~
` 라고 적어주셨는데, 엘림은 다른 방법을 생각하셨을까요?

2021-11-11 03:46 UTC, FIIIIN commented on Calculator/Calculator/Model/LinkedList.swift
> +    }
![스크린샷 2021-11-11 오후 12 45 19](https://user-images.githubusercontent.com/85180502/141233509-60ce0259-4610-4541-a1c1-27cad90fd10f.png)

유닛 테스트의 결과로는 문제가 없는 것으로 보이며, 제 선에서는 로직의 문제를 확인하지 못했습니다.

2021-11-11 03:48 UTC, FIIIIN commented on Calculator/Calculator/Model/Queue.swift
> +class Queue: LinkedList {
LinkedList 인스턴스를 생성해주는 것과는 별개로 Element 메서드를 오버라이드하고 싶어서 상속까지 진행했습니다.

현재는 제네릭 타입 적용 과정에서 생기는 오류때문에, LinkedList의 인스턴스만 생성해주었습니다.

2021-11-11 04:41 UTC, FIIIIN commented
세심한 리뷰와 친절한 말씀 감사합니다! 말씀해주신 내용을 토대로 개선하게 된 이유 등을 정리해서 적어볼게요😊 코멘트로 남겨주신 부분은 답코멘트로 남기겠습니다!

~~아래의 제목 들은 각각 어떤 파트에 대한 이야기인지 명확히 하기 위해 그대로 사용하였습니다~~

## 연산Queue를 Linked List로 구현하였습니다
연결리스트는 노드가 연결되어 만들어진 자료구조라는 점, 그리고 큐는 FIFO의 규칙을 가진 자료구조라는 점을 인지하며 작성해보았습니다. 몇 캠퍼의 코드를 읽어보았는데, 연결리스트와는 별개로 큐 배열을 추가적으로 생성해주는 점이 엘림이 생각한 차이일까요?

정신없는 탓에 놓쳐서 이번에 추가하게 되었지만, 저는 LinkedList의 head 프로퍼티에게 접근제어를 걸어주어서 지금까지 작성한 타입이 하나의 자료를 관리하기를 의도하였습니다. 따라서 큐 배열을 따로 만들어주지 않았습니다. 혹시 제 의도와 제 설계가 맞지 않거나, 의도가 적절치 않다면 의견 나눠주시면 감사하겠습니다🙏!!

## 제네릭 타입의 필요성을 느꼈습니다
말씀하신 것처럼 문제를 해결하지 못하여, 희망과는 다르게 String 타입을 적용하여 1차 PR 드렸습니다. 제 설명이 부족했던 듯 합니다. 이 뒤로는 조금 더 차분히 설명할 수 있도록 하겠습니다..!🤛

## 해결하지 못한 문제
current ≠ nil 조건과 let currentValue = current?.value 조건이 결국 같은 맥락이라는 것을 엘림의 말씀을 보고 깨달았습니다🙀 해당 부분은 수정되어 들여쓰기 개선하였습니다!

2021-11-11 11:12 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    }
테스트 코드라는건 앱에서 사용될 코드에 대해서 `정상적으로 동작하는지 확인하기 위한 코드`인데요:)
이렇게 타입안에 들어있는건 `실제로 앱을 실행했을때 돌아가는 코드`겠죠?
해당 코드가 실제 앱에서 사용될 코드라면 test라는 접두사는 옳바르지 않을 것이고, 오히려 지금처럼 수정한 코드를 test영역에서 실행시키는 함수가 test_라는 접두사를 달아야 할 것 같습니다!

2021-11-11 11:22 UTC, lina0322 requested changes
좋습니다! 짧은 시간안에 많은 발전이 있었네요😁
코멘트 한번 더 확인해주시고, 수정후에 DM주세요~!

2021-11-11 11:22 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    func Elements() -> [T] {
함수명 소문자로 시작할 수 있도록 변경해주세요~

2021-11-11 11:22 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
이 부분도 의도해서 `test_`로 시작하는걸까요?👀

2021-11-11 11:22 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T: Equatable, CalculateItem> {
Equatable을 채택한 이유는 무엇이고, 어떤 프로토콜인지 설명해주실 수 있을까요?😀

2021-11-11 11:22 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +        while current != nil && current?.value != value {
`current != nil` 조건이 없으면 어떻게 동작하나요?
옵셔널 체이닝에 대해서 알고있나요?😀

2021-11-11 11:22 UTC, lina0322 commented on Calculator/QueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.test_Elements(), [])
Equal 위주로 테스트 하고있는데요. 혹시 NotEqual로도 테스트 코드 작성해볼 수 있을까요?😀

2021-11-11 13:55 UTC, FIIIIN commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    }
위의 Elements까지 제가 당연한 부분을 놓치고 리뷰를 부탁드렸습니다ㅠㅠ
앞으로는 더 철저히 확인 후 커밋해야겠습니다..!

2021-11-11 14:03 UTC, FIIIIN commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +class CalculatorItemQueue<T: Equatable, CalculateItem> {
Equatable 프로토콜은 String, Int 등과 같은 기본 데이터 타입도 채택하고 있는 프로토콜입니다.
두 타입을 비교하여 Bool을 반환해주며, 해당 코드는 사용자 정의 타입을 사용하기 때문에 채택하게 되었습니다.

2021-11-11 14:30 UTC, FIIIIN commented on Calculator/Calculator/Model/LinkedList.swift
> +        while current != nil && current?.value != value {
옵셔널 체이닝에 대해서 알고 있습니다.
`current?.value`로 예시를 들면 current에 대한 nil 확인이 없이도 value에 접근할 수 있으며 반환값이 옵셔널이기 때문에 후자의 조건으로도 current의 nil 확인이 가능합니다.

current != nil은 삭제했습니다. 놓친 부분에 대해서 말씀해주셔서 감사합니다...😿🙏

2021-11-11 14:35 UTC, FIIIIN commented on Calculator/QueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.test_Elements(), [])
아래와 같이 작성해보았습니다.

```swift
func test_enque로_value를넣으면_비어있지않은배열을반환하는지() {
        sut.enqueue("9")
        
        XCTAssertNotEqual(sut.elements(), [])
}
```

의도하신 NotEqual 을 이용한 테스트 코드가 맞을까요? 🤔

추가적으로, 제 프로젝트의 현재 시점에서 NotEqual 이 필요한 이유 또한 궁금합니다. Equal로도 충분히 확인이 가능해 보여서요..!

2021-11-11 14:38 UTC, FIIIIN commented on Calculator/Calculator/Model/LinkedList.swift
> +    }
그렇군요! 구체적인 설명 감사합니다☺️
그렇다면, 이번과 다르게 `실제 앱에서 사용되지 않을 코드이지만 테스트 상 필요한 코드`라면 아예 test 영역에서 작성하여도 무방한 걸까요?

2021-11-12 02:49 UTC, FIIIIN commented
엘림이 말씀해주신 부분과 더불어 delete 메서드에서 논리적 오류가 확인되어 해당 부분도 수정하였습니다.
참고하여 확인해주시면 감사하겠습니다...!!

2021-11-12 12:21 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +    }
> 실제 앱에서 사용되지 않을 코드이지만 테스트 상 필요한 코드라면 아예 test 영역에서 작성하여도 무방한 걸까요?

무방하다기 보다는 test 영역에서 작성하는게 맞다고 생각되네요~😀
그 코드도 작성하면서 테스트를 위해 given, when, then에 맞춰서 작성하면 되지않을까요??🥲

2021-11-12 12:23 UTC, lina0322 commented on Calculator/QueueTests/CalculatorItemQueueTests.swift
> +        XCTAssertEqual(sut.test_Elements(), [])
Equal로도 가능하지만, NotEqual까지 사용해본다면 테스트의 질과 다양성을 더 높일 수 있다고 생각되어서, 사용을 권유 드려보았습니다 🙏

2021-11-12 12:25 UTC, lina0322 approved these changes
고생하셨습니다!
다음 스텝으로 넘어가봅시다~💪

2021-11-12 12:25 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +}
다른 파일로 분리해주면 더 좋을 것 같습니다.
양이 적더라도 보통 파일 하나에 타입 하나만 정의하는 경우가 많아서요!😀

2021-11-12 12:25 UTC, lina0322 commented on Calculator/Calculator/Model/LinkedList.swift
> +        }
LGTM💚

2021-11-12 12:26 UTC, merged