ios-calculator-app [STEP 1] nicholas
yagom-academy/ios-calculator-app pull request #75
Opened 2021-11-10 04:59 UTC by Kim-EunsooSilver

안녕하세요 코리(@corykim0829 )!!
말씀하신대로 이전 PR close 처리후에 PR 다시 올립니다!!!

step 2가 공개 되기전에 저만의 설계를 생각했었는데 step2 공개가 되고 보니....
step1은 단순히 큐 자료구조를 만드는 거였었네요....

이러한 사실을 안지 별로 되지 않아서 일단 제가 설계한 코드로 PR 드립니다...😭

# Class Diagram
<img width="801" alt="스크린샷 2021-11-09 오후 5 41 12" src="https://user-images.githubusercontent.com/83689084/140891035-98d5ee4e-38f9-447d-90e9-d7a818ca14cb.png">

# 고민한 점
* 데이터 타입에 대한 고민
    * 사용자에게 입력받은 숫자를 기본적으로 Double 형으로 형변환을 해볼까 아님 Int와 Double형을 혼합해서 사용할까 고민했습니다.
    * 최종적으로 Double형으로 선택하였고, 이유는 Int형과 같이 사용할 경우 연산시 형 변환에서 자원소모가 Double형으로 변환후 연산하는 자원소모보다 훨씬 더 클거 같아서 입니다.
* 입력값과 입력된 연산자 처리
    * 이 부분에서 많은 고민을 했습니다.  제가 생각한 케이스를 먼저 말씀드리겠습니다.
        1. 사용자의 입력을 하나의 string으로 처리 ex)    `1+`, `2-`
        2. 사용자의 입력을 연산자와 입력값을 별개의 스택으로 처리
            * ex)
            * `[1, 2 ]`    `["+", "-"]`
     * 제가 최종적으로 선택한 건 2번 케이스입니다. 1번 케이스로 진행할 경우 숫자와 연산자를 분리하는 함수를 별도로 구현해야 하며, 연산시마다 해당 기능이 연속적으로 사용되는것이 비효율(?)적이라고 생각했었습니다. 2번 케이스로 진행할 경우에는 메모리 공간적으로 봤을때 비효율적이지만 1번의 단점을 피할 수 있다고 생각했습니다. 

# 궁금한 점
* TDD 방법에 관련해서 궁금합니다.
    * 제가 커밋한 순서대로 진행하는게 맞나요?
    *  테스트에서는 !연산자를 이용해 옵셔널을 해제시켰는데, 테스트에서도 !연산자를 지양해야 하나요?
    * TDD를 학습활동에서 배우고 프로젝트에서 처음 진행했습니다...(너무 낯설어서... 혼났네요😭) 제가 개선할 점이 있을까요?
* 고민한 점 두번째 항목이 궁금합니다.
    * 이 프로젝트 한정으로 봤을때 어떤 케이스가 더 효율적인 방법인가요?
* MVC 아키텍처 관련 질문입니다.
    * MVC 아키텍쳐에 의거하여 소스를 분리해봤습니다. 다만 궁금한게 storyboard는 view 객체일까요? 웹 프로그래밍으로 봤을때 뷰에는 html, css 등이 들어가는데, Swift에서는 어느 파일이 view 객체인지 궁금합니다!

2021-11-10 05:55 UTC, corykim0829 requested changes
수고하셨습니다 👏👏👏👏

고민한 내용을 잘 정리하여 공유해주셔서 코드를 이해하기 편했습니다 😃
제가 해드린 피드백을 기반으로 더 개선해봅시다!

> 궁금한 점
> TDD 방법에 관련해서 궁금합니다.
> 제가 커밋한 순서대로 진행하는게 맞나요?

➡️ 테스트 코드를 먼저 작성하는게 더 깔끔하고 책임이 덜한 코드를 작성할 수 있습니다! 좋은 접근이에요 👍

> 테스트에서는 !연산자를 이용해 옵셔널을 해제시켰는데, 테스트에서도 !연산자를 지양해야 하나요?
> TDD를 학습활동에서 배우고 프로젝트에서 처음 진행했습니다...(너무 낯설어서... 혼났네요😭) 제가 개선할 점이 있을까요?

➡️ 네 `!`는 지양해주세요. 

> 고민한 점 두번째 항목이 궁금합니다.
이 프로젝트 한정으로 봤을때 어떤 케이스가 더 효율적인 방법인가요?
사용자의 입력을 연산자와 입력값을 별개의 스택으로 처리

➡️ 두개의 스택을 사용해서 숫자와 연산자를 별개로 처리하는 것은 좋은 시도 같습니다만, 현재 구현한 코드를 보면 동시에 짝지어서 입력받는 방법은 효율적이지 못한 것 같아요.

> MVC 아키텍처 관련 질문입니다.
MVC 아키텍쳐에 의거하여 소스를 분리해봤습니다. 다만 궁금한게 storyboard는 view 객체일까요? 웹 프로그래밍으로 봤을때 뷰에는 html, css 등이 들어가는데, Swift에서는 어느 파일이 view 객체인지 궁금합니다!

➡️ 스토리보드는 뷰에 가깝지만, 로직적인 부분도 어느정도 들어가서 조금 애매한 부분입니다. 현재로써는 UIKit 관련 객체들이 view에 속한다고 생각하면 됩니다.

2021-11-10 05:55 UTC, corykim0829 commented on Calculator/Calculator/Model/LinkedList/LinkedList.swift
> +    func append(_ value: T) {
깔끔한 함수명과 인자처리 좋아요 👍

2021-11-10 05:55 UTC, corykim0829 commented on Calculator/Calculator/Model/LinkedList/LinkedList.swift
> +        self.tail = newNode
여기 self는 꼭 필요한 부분인가요?

2021-11-10 05:55 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func enqueue(_ computingValue: Double, _ operator: String) {
여기서 함수 파라미터에서 와일드카드 패턴을 사용하게 되면 두개 인자 구분이 힘들 것 같아요.

그리고 operator를 String으로 받게되면 연산자 제외하고 다른 값이 들어올 수도 있을 것 같아요.

2021-11-10 05:55 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func enqueue(_ computingValue: Double, _ operator: String) {
숫자와, 연산자를 한번에 인자로 받는 이유가 있나요?
이렇게 두개의 인자만 받을 수 있으면, 계산기에서는 숫자, 연산자를 입력할 때만 처리가 되는건가요?
숫자만 입력하는 것은 불가능한가요?

2021-11-10 05:55 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func cleanQueue() {
clean이라는 명칭은 조금 애매한 것 같아요. 다른 함수명으로 개선해볼 수 있을 것 같아요!

2021-11-10 05:55 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func test_기존_연산큐에_데이터가_없을때_계산기가_입력받은_1와_더하기_연산자는_연산큐에_쌓이는가() {
한글로 상세한 테스트함수명 좋네요 👍

2021-11-10 05:55 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
이 CalculatorItemQueue는 struct와 class 중 struct로 구현한 이유가 있나요?

2021-11-10 10:08 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/LinkedList/LinkedList.swift
> +        self.tail = newNode
어...음... 버릇이였습니다...

이 부분에서는 불필요합니다... 피드백 반영했습니다.

2021-11-10 10:12 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func enqueue(_ computingValue: Double, _ operator: String) {
스텝 2가 공개되기전 제가 설계했던 계획은
사용자가 숫자를 입력 -> 연산자 터치 -> 스택 enqueue 
이렇게 설계했었습니다.

스텝 2가 공개가 되고 요구 명세를 분석을 했을경우 enqueue가 되는 시점은 사용자가 `=` 버튼을 터치했을때로 분석을 했습니다.
제가 스텝2 명세를 올바르게 분석했다면은 스텝2에서 변경 및 구현해도 될까요?

2021-11-10 10:15 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func cleanQueue() {
🧐🤔호옥시... reset은 어떠세요? 코리?

`resetQueue`로 변경했습니다~!

2021-11-10 10:21 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +struct CalculatorItemQueue: CalculateItem {
🤔🧐커밋 로그를 보시면 아시겠지만 초기에 class로 구현했다가 struct로 변경했는데요!!!
일단은 제가 선택한 이유 첫번째는 애플은 class보다 struct를 더 좋아하는거 같았어요!
[Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)
>Use structures by default.

두번째로는 해당 타입의 역활상 굳이 참조를 사용해야 하는 이유가 있을까? 라는 고민을 했고 참조될 일이 없을거 같다고 생각해서 변경했습니다!!

2021-11-10 12:20 UTC, Kim-EunsooSilver commented
코리~!
제가 구현한 스텝1을 꼼꼼하게 분석해주시고 훌륭한 피드백 주셔서 감사합니다~!!! 다음 피드백도, 그리고 다음 스텝도 정말 기대되는데요!!!!
---

> 본인 브랜치로 PR을 날렸었는데, 왜 step 브랜치로 PR을 날려야 하는지를 한번 고민해보고 같이 이야기해보면 좋을 것 같아요

🤔🧐이번 코리와 함께하는 프로젝트를 포함한 이전의 4개의 프로젝트에서 pr 전송시의 절차를 말씀드리도록 하겠습니다.
1. 저의 repository에 포크후, 나머지 브랜치 제거
2. step1 브랜치 생성
3. step1 브랜치로 step1의 요구사항 구현
4. 저의 메인 브랜치에서 step1 머지
5. 머지가 된 메인 브랜치로 pr 전송
6. 피드백 반영 및 머지
7. next step 브랜치 생성 및 진행

저는 이런 절차로 진행했습니다. 한 달이상 이렇게 하다보니 별 생각 없이 제 절차대로 진행해 왔습니다.
오늘 코리의 조언으로 step 브랜치로 pr을 왜 날려야하는지를 고민을 해보았는데요!
저는 머지가 되기 이전 피드백 반영 부분에 초점을 맞춰봤습니다!
메인 브랜치로 피드백을 반영하게 되는데 추후에 이전 스텝의 피드백 반영 부분과 다음 스텝 기능구현 부분의 경계가 모호해 질거 같았습니다!

이를 개선하고자 절차를 수정해보았습니다.
1. 저의 repository에 포크후, 나머지 브랜치 제거
2. step1 브랜치 생성
3. step1 브랜치로 step1의 요구사항 구현
4. step1으로 PR 전송
5. step1으로 피드백 반영
6. 머지
7. 저의 메인 브랜치에서 step1 머지
8. 다음 step 브랜치 생성 및 진행

이렇게 수정해 보았습니다!! 혹시 제가 코리의 조언을 잘못이했거나 수정된 절차보다 더 좋은 절차가 있다면 조언 부탁드리도록 하겠습니다🙏🏻

2021-11-11 02:41 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func cleanQueue() {
Queue라는 객체의 함수이니 `reset`이라고 해도 깔끔하고 명확할 것 같아요! 참고하세요 ㅎ

2021-11-11 02:50 UTC, corykim0829 approved these changes
수고하셨습니다 👏👏👏👏

다음 스텝 진행하기 전에 DM으로 목표 PR 일정을 보내주세요!!

> 🤔🧐이번 코리와 함께하는 프로젝트를 포함한 이전의 4개의 프로젝트에서 pr 전송시의 절차를 말씀드리도록 하겠습니다.

> 저의 repository에 포크후, 나머지 브랜치 제거
step1 브랜치 생성
step1 브랜치로 step1의 요구사항 구현
저의 메인 브랜치에서 step1 머지
머지가 된 메인 브랜치로 pr 전송
피드백 반영 및 머지
next step 브랜치 생성 및 진행
저는 이런 절차로 진행했습니다. 한 달이상 이렇게 하다보니 별 생각 없이 제 절차대로 진행해 왔습니다.
오늘 코리의 조언으로 step 브랜치로 pr을 왜 날려야하는지를 고민을 해보았는데요!
저는 머지가 되기 이전 피드백 반영 부분에 초점을 맞춰봤습니다!
메인 브랜치로 피드백을 반영하게 되는데 추후에 이전 스텝의 피드백 반영 부분과 다음 스텝 기능구현 부분의 경계가 모호해 질거 같았습니다!

> 이를 개선하고자 절차를 수정해보았습니다.
1. 저의 repository에 포크후, 나머지 브랜치 제거
2. step1 브랜치 생성
3. step1 브랜치로 step1의 요구사항 구현
4. step1으로 PR 전송
5. step1으로 피드백 반영
6. 머지
7. 저의 메인 브랜치에서 step1 머지
8. 다음 step 브랜치 생성 및 진행
이렇게 수정해 보았습니다!! 혹시 제가 코리의 조언을 잘못이했거나 수정된 절차보다 더 좋은 절차가 있다면 조언 부탁드리도록 하겠습니다🙏🏻

수정한 절차 1번에서 나머지 브랜치를 하나씩 제거했나요? 특정 브랜치만 포크할 수 있어요! 다음 프로젝트에서 여유가 있다면 도전해보세요!

---

6번 머지가 진행되면, `포크한 저장소 - step1` 브랜치가 `야곰 아카데미 저장소 - 니콜라스` 브랜치에 머지됩니다.
이 머지된 `야곰 아카데미 저장소 - 니콜라스` 브랜치를 `포크한 저장소 - 니콜라스` 브랜치와 동기화 시켜주면 됩니다. (rebase, pull 등을 사용한 동기화 처리)

`포크한 저장소 - 니콜라스` 브랜치는 직접 건드리지 않고 코드를 작성하는 방식입니다! 여기에는 온전한 코드만 들어가야된다고 생각하시면 될 것 같아요 ㅎ

그리고 지금 보니까 클래스 다이어그램에서 CalculatorItemQueue가 CalculatorItemQueue와의 관계가 있는데, 이 부분 한번 확인해주세요!

2021-11-11 02:50 UTC, merged