계산기 [STEP1] 릴리
yagom-academy/ios-calculator-app pull request #76
Opened 2021-11-10 05:56 UTC by yeahg-dev

안녕하세요 코리! (@corykim0829)

스텝1 PR 요청드립니다.
자료구조 구현이 처음이라 아직 부족한 부분이 많습니다🥲
제가 더 생각해볼 점이나, 놓치고 있는 시야가 있다면 아낌없이 지적해주세요~!
잘 부탁드립니다🙏🏻

# CalculatorItemQueue 클래스 다이어그램
![calculator_step1_classdiagram 복사본](https://user-images.githubusercontent.com/81469717/140922958-ac43cc6a-34f9-40c0-ac71-019fdaea3f1c.jpeg)

- `CalculateItem` : "`CalculateItemQueue`의 요소는 `CalculateItem`프로토콜을 준수합니다 " 라는 프로젝트 요구사항에 따라서 구현했습니다.
-  `Operator` : 계산기의 연산자가 5가지로 한정적이어서 열거형으로 정의 후, `CalculateItem`프로토콜을 채택했습니다.
- `Number` : 계산기로 입력받을 숫자를 `Double`타입의 프로퍼티로 정의 후,  `CalculateItem`프로토콜을 채택했습니다.
- `CalculatItemQueue` : `CalculateItem`프로토콜 타입의 array로 `queue`를 만들었습니다.

<br>

# 🤔 고민한 점
## 1. Queue 구현 방법 : `Array List` vs `Linked list`
Queue를 어떤 자료구조로 구현할지에 대해 고민해보았습니다~

Queue는 자료가 선형적으로 나열되고, First-In-First-Out 방식으로 추가/삭제가 이루어집니다.
따라서 `Array List`, `Linked List` 자료구조를 후보로 생각했습니다.
 
**Queue는 추가는 마지막 요소에서만 일어나고, 삭제는 첫번째 요소에서만 일어난다**는 점을 고려했을 때,
시간복잡도를 기준으로 효율성을 비교해보았습니다.
|자료 구조/시간복잡도|ArrayList|LinkedList|
|---|---|---|
|마지막 요소에 추가|O(1)|O(n) <br>(추가를 하기위해 마지막요소를 탐색하는 시간복잡도까지 고려) |
|첫번째 요소 삭제|O(n) |O(1) |

비교해 본 결과, 두 자료구조의 시간복잡도는 추가/삭제를 함께 고려하면 같다는 결론을 내렸습니다.
저는 Swift에서 기본으로 제공하는 array의 메서드를 사용하고자 Array List를 선택했습니다.

> 제가 시간복잡도를 알맞게 분석한게 맞을까요?

<br>

## 2. CalculateItemQueue 구현시 타입 선택
아래와 같은 이유로 `CalculateItemQueue`을 처음엔 struct로 구현했습니다. 
- struct가 default로 권장
- 스텝1만 고려했을 땐, 상속, 타입캐스팅이 필요없어 보임

그런데 멤버 변수인`queue`가 메서드를 통해 계속해서 수정되고, 따라서 모든 메서드에 `mutating`키워드를 추가해주어야 했습니다.
그래서 queue는 값이 복사되기보단, 참조가 전달되는 것이 적절한 것 같아 class타입으로 수정해주었습니다. 그리고 `mutating`키워드를 전체적으로 사용할 바엔 class를 쓰는 것이 더 좋은 건가? 하는 의문도 생겼습니다.

> class만이 가지는 능력(상속, 타입캐스팅, Objective-C와 호환)을 사용할 일이 없음에도,
프로퍼티가 메서드내에서 계속해서 수정되어야하는 경우, `mutating`키워드를 쓰는 것보다 class를 쓰는 것이 적절한 것인지? 코리의 의견이 궁금합니다!
<br>

## 3. TDD 커밋 단위
 TDD방식으로 처음 개발을 진행하다보니, 커밋을 언제 끊어야할지가 아리송했습니다🙄

저는 TDD의 한 사이클이 기능 단위와 같다고 생각해서 
 `실패하는 testcode작성` - `프로덕션 코드 작성` - `refactor` 마다 커밋을 했습니다.

<br>

# 궁금한 점

class diagram으로 처음 프로토콜을 표현해보았는데 위의 방식이 알맞은지 궁금합니다!

2021-11-10 07:54 UTC, corykim0829 requested changes
수고하셨습니다 릴리 👏👏👏👏

많이 고민한 흔적이 느껴지는 코드였습니다 👍
struct, class 고민한 부분에서 mutating 부분까지 잘 고려해서 잘 선택하신 것 같습니다. 

현재 커밋 방식도 좋습니다 👍

테스트 함수를 전체적으로 한번 더 개선해보면 좋을 것 같아요!

많이 기다리신 것 같아서 일단 코드에 대해서만 피드백을 먼저 드릴게요! 같이 더 개선해봐요!
고민한 점이나 궁금한 점에 추가적인 답변은 제가 최대한 빠르게 다시 답변 드리겠습니다!

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculateItem.swift
> +enum Operator: CalculateItem {
연산자를 enum으로 나누어준 부분이 좋습니다. 👍

CalculateItem 프로토콜을 채택한 이유가 있나요?

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculateItem.swift
> +struct Number: CalculateItem {
Number라는 구조체를 따로 구현한 이유가 있을까요?

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculateItem.swift
> +struct Number: CalculateItem {
CalculateItem 프로토콜을 채택한 이유도 궁금합니다!

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        guard queue.count != 0 else {
count이다 보니 `queue.count > 0` 이 조금 더 코드를 읽기에 자연스러울 것 같아요!

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        //expectation
expectation, result 커멘트는 어떤 의도로 적으신건가요?

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_queue가_빈배열일때_dequeue는_실행되지않는다() {
dequeue가 실행되지 않는다는 말은 모순인 것 같아요! 네이밍을 변경하는게 좋을 것 같습니다!

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_removeAllItems호출시_queue는_빈배열이된다() {
함수명도 가장 깔끔하고 함수명의 의도와 적합한 테스트를 진행하고 있는 것 같아요! 👍

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertNotNil(calculatorItemQueue.queue)
1을 추가하면 not nil 뿐만 아니라 다른 것도 확인을 해야할 것 같아요

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_enqueue호출시_queue에_1을_추가한다() {
한글로 테스트 함수명을 작성하여 읽기 더 쉽네요 👍 
그런데 1을 추가해서 무엇을 테스트하는지 조금 더 명확하게 명시가 되면 좋을 것 같아요.
아래 다른 함수들도 조금 더 명확하게 수정하면 좋을 것 같아요

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculateItem.swift
> +//  CalculateItem.swift
프로토콜 파일에 다른 enum 코드도 있네요. 👀

분리해주면 좋을 것 같아요!

2021-11-10 07:54 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: [CalculateItem] = []
이 queue 프로퍼티는 private, public 중 어느 것을 사용하는게 좋을까요? 👀

2021-11-10 12:33 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculateItem.swift
> +enum Operator: CalculateItem {
"`CalculatorItemQueue`에서 다루는 요소는 `CalculateItem` 프로토콜을 준수합니다"라는 요구사항이 있었습니다. 
`CaluclatorItemQueue`의 `queue`에 들어가고 나가는 요소가 `Operator`와 `Number`가 될 것이라 생각해 채택해주었습니다. 그리고 다른 두 타입을 프로토콜 타입으로 묶어줄 수도 있다고 생각했습니다.

2021-11-10 12:48 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculateItem.swift
> +struct Number: CalculateItem {
위에 남긴 댓글과 연결되는 부분인 것 같아요!
계산기의 숫자가 Double타입으로 들어가고, `queue`에 `Operator`타입과 함께 배열로 담아주기위해 `CalculateItem`프로토콜을 채택해주었습니다. 

그런데 PR후 좀 더 찾아보니,`Number` 구조체를 구현하지 않고 스위프트의 기본 자료형인 Double에 extension을 추가한 후 `CalculateItem`을 채택하는 방법도 있다는걸 알게되었어요!👀
그리고 추가적으로 STEP2에서 공개된 UML도 그 방법인 `extension Double: CalculateItem`으로 구현하라고 요구한다고 생각했습니다.

**[STEP2 UML]**
<img width="1247" alt="스크린샷 2021-11-10 오후 9 43 33" src="https://user-images.githubusercontent.com/81469717/141115141-1c623de5-3f2b-459b-b52f-d44189926a73.png">

그래서 `extension Double: CalculateItem`으로 코드를 수정해보려합니다!

2021-11-10 12:50 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        guard queue.count != 0 else {
네 그런것 같습니다! 수정하도록 하겠습니다😊

2021-11-10 14:18 UTC, yeahg-dev commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        //expectation
unit test에서 test code작성시 테스트의 흐름을 쉽게 파악하기 위해 커멘트를 쓰는 사례를 보아서 적용을 시켜보았습니다~
줄바꿈을 이용한다면 삭제해도 되는 코멘트일까요?
TDD방식으로 개발을 진행할 때 실제로 커멘트는 생략하는 경우가 많은가요??

2021-11-10 15:02 UTC, yeahg-dev commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        XCTAssertNotNil(calculatorItemQueue.queue)
네~ `queue`에 1이 정상적으로 들어갔는지도 확인이 필요할 것 같습니다~
`XCTAssertEqual(calculatorItemQueue.queue[0] as! Double, 1.0)` 을 추가적으로 작성해보았습니다!

2021-11-10 15:18 UTC, yeahg-dev commented on Calculator/CalculatorTests/CalculatorTests.swift
> +    func test_enqueue호출시_queue에_1을_추가한다() {
네~ 좀 더 명확한 의미를 내포하도록 리팩토링 해보겠습니다🙂

2021-11-10 15:36 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculateItem.swift
> +//  CalculateItem.swift
extension과 protocol은 Model뿐만 아니라 ViewController에서도 사용이 될 것 같아, `Extensions`, `Protocols`폴더를 생성했습니다. 그리고 그 안에 Double의 익스텐션과, CaluclateItem 프로토콜을 넣어주었습니다.

이렇게 분리하면 명확한 것 같긴한데... 폴더가 너무 많아지는 단점도 있는 것 같습니다🥲 이렇게 관리하는 것에 대한 코리의 생각은 어떠신가요?

2021-11-10 15:41 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var queue: [CalculateItem] = []
CalculatorItemQueue의 메서드를 통해서만 접근이 가능하고 캡슐화하기위해 `private`을 설정해주는 것이 좋을 것 같습니다!

2021-11-11 02:53 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculateItem.swift
> +struct Number: CalculateItem {
좋은 수정 방안입니다 😀
STEP2에서 공개된 UML은 야곰아카데미에서 제시해준건가요?

현재 UML은 요소간 관계가 잘못된 것 같아서 이를 참고해서 수정해보면 좋을 것 같아요!

2021-11-11 02:55 UTC, corykim0829 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        //expectation
제 생각에는 따로 테스트 코드에 대한 컨벤션을 그라운드룰로 정했다면 굳이 사용하지 않을 것 같아요!
매우 반복적인 느낌이 들어서 차라리 따로 규칙으로 빼는게 좋을 것 같네요.

2021-11-11 02:56 UTC, corykim0829 commented on Calculator/Calculator/Model/CalculateItem.swift
> +//  CalculateItem.swift
전혀 많지 않습니다! 파일이 많은 것보다 훨씬 좋아요 ㅎ

2021-11-11 02:58 UTC, corykim0829 approved these changes
수고하셨습니다 릴리 👏👏👏👏

피드백해드린 부분에 대한 수정사항은 크지 않아서 다음 스텝 진행하면서 반영해주세요!

다음 스텝을 진행하기 전에 저한테 DM으로 PR 목표 기한을 말해주세요!

2021-11-11 02:58 UTC, merged

2021-11-11 04:40 UTC, yeahg-dev commented on Calculator/Calculator/Model/CalculateItem.swift
> +struct Number: CalculateItem {
네 야곰아카데미에서 제시한 UML입니다~다음 스텝은 위 UML을 바탕으로 코드를 설계할 예정입니다.

화살표 방향이 잘못된것 같군요! 수정하겠습니다. 감사합니다😊

2021-11-11 04:44 UTC, yeahg-dev commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        //expectation
네 참고해보도록 하겠습니다!