계산기 [STEP1] 제리
yagom-academy/ios-calculator-app pull request #78
Opened 2021-11-10 07:56 UTC by llghdud921

안녕하세요 쿠마! @leejun6694  
제리입니다 :) 
Step1 코드 구현을 완료하여 PR 전달드립니다

잘 부탁드립니다! 감사합니다~~~

---

# **고민했던 점**

### **CalculateItem 프로토콜 준수**
    
> `CalculatorItemQueue`에서 다루는 요소는 `CalculateItem` 프로토콜을 준수합니다
    
프로젝트 요구 사항에 해당 문구가 있었습니다.
따라서 `CalculatorItemQueue`내 함수 매개변수, 반환타입, 프로퍼티 등을 `CalculateItem`  프로토콜을 type으로 사용하였습니다.
추가로 `LinkedList` 구현 시에도 각 노드의 data의 타입을 `CalculateItem` 프로토콜로 이용하여 해당 프로토콜을 준수한 타입만 입력할 수 있게 제한두었습니다.
    
### **TDD를 이용한 코드 작성**
> TDD의 3단계 : 실패하는 코드 작성 → 기능을 개발하여 테스트를 통과 → 코드 리팩토링

위 3단계를 거쳐 코드를 작성하였습니다.
처음에는 코딩 속도도 더디고 실패하는 case를 생각하는데 애를 먹었지만 TDD의 장점은 다른 기능이 추가되거나 리팩토링하는데에서 뚜렷하게 나타났습니다. 
아래에는 제가 코드를 작성해보면서 느꼈던 TDD의 장점을 나열해보았습니다. 
 - 테스트 case가 이미 구현되어있으니 수정 시에도 test를 손쉽게 진행할 수 있다.
 - 타입만 구현할 시에도 해당 코드가 어떻게 작동하는지 알 수 있어 작동할 코드를 구성하는데 도움이 된다.
    
### **Test를 위한 코드 분리 및 그룹화**
테스트를 진행하다보니 실제 코드와 테스트를 위한 코드도 많이 생겨나게 되었습니다. 
 예를 들어, 저는 테스트 결과 확인을 String Array 배열 비교를 이용하였습니다.  
 ```swift
 XCTAssertEqual(convertList(list: queue.queueListForTest.searchAll()), ["1"])
```
이때 두가지 과정을 거쳤는데요 
 1. `LinkedList` 를 data를 빈 배열에 append하여 배열화
2. 배열 안의 값을 String으로 변환
    
위 과정을 위해서 테스트를 위한 코드가 많이 생겨나게 되었습니다. 저는 실제 코드와 테스트를 위한 코드를 분리하고자 extension을 이용하고 `CalculatorTest` 폴더 내 `CalculatorItemQueueExtension` 파일을 만들어서 그룹화하는 과정을 거쳤습니다.
    
### **LinkedList 구현**

선택사항으로 있었던 List의 자료구조를 구현해보았습니다.
계산기 동작 설명을 참고하여 해당 프로젝트내 Queue는 Dequeue, 즉 양쪽 끝에서 삽입, 삭제가 가능한 자료구조를 사용할 필요 없이 일반적인 FIFO만을 지원하는 Queue를 구현해도 작동에 문제 없겠다는 판단이 들었습니다.
Queue는 FIFO으로 첫번째 노드를 삭제하고 반환하는 기능과 마지막 노드에 데이터를 삽입하는 기능만 필요로 합니다. 그렇다면 탐색이나 조회의 기능이  중요하지 않고 첫번째 노드와 마지막 노드에 접근하는 방법이 중요하다고 생각했습니다.
    
 LinkedList는 순차적으로 data에 접근하여 탐색, 조회 시 시간복잡도가 증가하는 단점이있지만 첫번째 노드와 마지막 노드에 접근하는 시간복잡도에서 유리합니다. 
그리고 해당 프로젝트 내에는 중간 데이터에 접근하는 경우가 없어서 단순연결리스트로 구현하였으며 append시 마지막 노드를 탐색해야하는 단점을 보완하여 tail 프로퍼티를 사용하여 구현하였습니다.
    

---

# 아쉬웠던 점

### **LinkedList 구현 시 TDD 를 이용하지 않은 것**
    
초반에 Queue를 구현했을 때 TDD를 활용하여 코드를 작성을 했습니다. 후에 선택사항인 list 자료구조를 구현했을 때 refactoring 이라고 생각하여 LinkedList에 대한 test코드를 작성하지 않고 queue의 test만을 가지고 테스트를 진행했습니다.
 의존모둠인 알라딘과 함께 이야기를 나누어보니 LinkedList에 대한 테스트 코드를 작성했다는 사실을 알게되었습니다. 생각해보니 충분히 작성할 수 있고 세분화된 테스트를 진행할 수 있었음에 아쉬움이 남습니다. 
    
앞으로는 리팩토링이라고 생각하는 부분도 테스트 먼저 해볼까? 라고 생각해보자는 다짐을 하게되었습니다.
    
---

# **조언을 얻고 싶은 부분**

### **LinkedList내 메서드와 CalculatorItemQueue의 메서드명 네이밍에 대한 고민**
    
linkedList의 메서드명을 append, removeFirst라고 네이밍을 해보았는데요. Array에서 사용하던 메서드명을 참고해서 네이밍을 했습니다. 또한 Queue에서는 enqueue, dequeue라고 지었습니다. 이때, dequeue는 FristOut인 의미를 지니고 있지만 자료구조인 Dequeue과 혼동할 수 있다는 점, 값을 반환한다는 점에서 해당 이름으로 네이밍을 하는 것이 맞는지 고민이 됩니다. 
    
### **Test를 위한 코드를 분리 시 해결하지 못한 문제**
    
위의 고민했던 점 - Test를 위한 코드 분리 및 그룹화 에서 해결하지 못한 점이 있습니다. 
CalculatorItemQueue내 queueList와 LinkedList내 head, tail의 경우 외부에서 접근할수도 없고 볼수도 없어야 하는 private 키워드를 사용한다고 생각했습니다. 하지만 테스트 결과를 확인하기 위해서 해당 리스트를 관찰해야했고 
    
첫번째 해결방안은
```swift
    extension CalculatorItemQueue {
        var queueListForTest: LinkedList {
            return self.queueList
        }
    }
 ```
extension을 이용해 리스트를 전달하였습니다.

그런데 `CalculatorTest` 폴더 내 `CalculatorItemQueueExtension` 파일을 만들어서 그룹화하는 과정에서 private키워드는 동일한 파일 안에 선언되어있는 extension만 가능하여 위 코드를 다른 파일로 이동할 수 없는 문제가 발생했습니다.

어쩔수없이 실제 코드에 위 코드를 적용하는 방법을 택했지만 다른 해결 방안이 있는지 여쭙게 싶습니다!
    
### **LinkedList clear 방식에 대한 고민**
    
LinkedList clear메소드 구현 시에 head = nil, tail = nil 하면 나머지 연결이 다 끊기니까 메모리 해제가 되겠지? 하는 생각으로 구현했습니다. 그런데 뭔가 head, tail를 제외한 나머지 데이터들이 둥둥 떠다니고 있을 것 같다는 생각도 들었습니다..ㅎㅎ 
뭐가 정답인지 몰라서 전체 탐색해서 nil처리를 해주었는데요
    
전체 탐색을 안하고 tail, head만 nil처리 할 경우 메모리 해제가 될 수 있는지 여쭤보고싶습니다!

2021-11-11 03:11 UTC, leejun6694 requested changes
제리 안녕하세요 : )
구현을 깔끔하게 해주셔서, 코드를 읽는데 많은 도움이 되었습니다.
몇가지 코드 리뷰를 드렸는데 확인 부탁드려요!

2021-11-11 03:11 UTC, leejun6694 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +
불필요한 줄바꿈이 있네요 : )

2021-11-11 03:11 UTC, leejun6694 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        let data2 = queue.dequeue()
`dequeue` 가 왜 두번 진행되고 있는 것일까요~~?

2021-11-11 03:11 UTC, leejun6694 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        var compareList:[String] = []
띄어쓰기...!

2021-11-11 03:25 UTC, leejun6694 commented
> LinkedList내 메서드와 CalculatorItemQueue의 메서드명 네이밍에 대한 고민

충분히 잘 구현해주신 것 같습니다ㅎㅎ

> Test를 위한 코드를 분리 시 해결하지 못한 문제

음.. 두가지 방법이 있을 것 같네요.
- 예를 들어 headForTest 값은 `front()` 와 같은 method 로 구현해도 될 것 같습니다.
- 이게 아닌 테스트를 위한 method 라면, test file 내 `fileprivate` 과 같은 access control 를 주는건 어떨까요??

> LinkedList clear 방식에 대한 고민

리뷰 드렸던 내용이랑 겹치는군요ㅎㅎ deinit 으로 확인해볼까요??

2021-11-11 08:20 UTC, llghdud921 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func enqueue(item: CalculateItem?) {
네! UI까지 구성된 부분을 생각해보면 nil인 경우에는 enqueue 하지 않도록 설계하는게 좋을것같습니다! 
수정했습니다~

2021-11-11 08:21 UTC, llghdud921 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        return queueList.isEmpty ? nil : queueList.removeFrist()
TDD를 이용한 코드구현이다 보니 리팩토링이 쉽지 않네요..ㅎㅎ

removeFirst 로직에 빈큐인지 확인하는 로직이 있어서 현재 코드에는 필요없다고 생각합니다. 삭제완료했습니다!

2021-11-11 08:30 UTC, llghdud921 commented on Calculator/Calculator/Model/LinkedList.swift
> +        if head?.next == nil {
ㅠㅠ 쿠마 감사해요.. 연결리스트를 직접 구현해본게 처음이라 서툰부분이 많이 보이네요..ㅎ 

해당 코드에는 if 문이 필요하지 않아서 삭제했습니다!
수정완료 했습니다!

2021-11-11 08:34 UTC, llghdud921 commented on Calculator/Calculator/Model/LinkedList.swift
> +        node = nil
질문드린 사항에 답변이 된것같아요! 
head = nil, tail = nil 코드로 모든 노드가 해제되네요!

이유는 head와 tail이 해제가 되면서 연결된 노드의 참조카운트가 0이 되어 순차적으로 해제가 되는것이라 생각됩니다!
실제로 deinit을 사용하여 검증도 완료하였습니다.

![스크린샷 2021-11-11 오후 5 31 36](https://user-images.githubusercontent.com/40068674/141264646-dd39b48b-5106-422c-baaf-61587ef9d2fb.png)

감사합니다~

2021-11-11 08:35 UTC, llghdud921 commented on Calculator/Calculator/Model/LinkedList.swift
> +        return head == nil ? true : false
네 dequeue에서 사용한 isEmpty가 필요없어지면서 해당 코드는 사용하지 않아 삭제하였습니다!

2021-11-11 08:35 UTC, llghdud921 commented on Calculator/CalculatorTests/CalculatorItemQueueExtension.swift
> +        var searchedList:[CalculateItem] = []
아고 죄송합니다......!

2021-11-11 08:38 UTC, llghdud921 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> CalculateItem? {
리턴 값을 사용하지 않는 경우 warning 메세지가 뜨는데요
![스크린샷 2021-11-11 오후 5 36 56](https://user-images.githubusercontent.com/40068674/141265406-0c4d8d5a-d38c-4b20-a2ae-6c6bf35a6eb8.png)

해당 메세지를 무시할 수 있는 어노테이션 @discardableResult을 사용하였습니다.

2021-11-11 08:39 UTC, llghdud921 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +
네 개선완료하였습니다!

2021-11-11 08:40 UTC, llghdud921 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        let data2 = queue.dequeue()
아!!!! 원래 하나의 값이 들어있어서였는데.......!!!!! 

죄송해요ㅠ 개선하였습니다!

2021-11-11 08:41 UTC, llghdud921 commented on Calculator/CalculatorTests/CalculatorTests.swift
> +        var compareList:[String] = []
네!!!!! 명심 또 명심하겠습니다!!!!!!!!!

2021-11-11 09:15 UTC, llghdud921 commented
안녕하세요 쿠마 리뷰 감사드립니다!

피드백 이후 수정을 완료했구요! 변경된 사항 간단하게 말씀드리겠습니다.

1. 테스트를 위한 코드
> 예를 들어 headForTest 값은 front() 와 같은 method 로 구현해도 될 것 같습니다.
쿠마의 말씀대로 메서드로 구현해도 괜찮을 것같다는 생각이 들었어요!
두번째 해결방법은 메서드로 구현해서 최대한! 은닉화를 해보려고 했습니다 

2. enqueue 메서드 오버로딩
   enqueue메서드 사용 시에 `enqueue(item: NumberItem(data: 1))` 와 같은 코드로 test를 진행해 
   가독성을 떨어트린다고 생각하였습니다. 앞으로 구현할 실제 코드도 마찬가지일것같아서
   오버로딩을 이용해서 코드 리팩토링을 진행하였습니다.  

```
private mutating func enqueue(item: CalculateItem) {
        queueList.append(data: item)
    }
    
    mutating func enqueue(number: Int) {
        self.enqueue(item: NumberItem(data: number))
    }
    
    mutating func enqueue(operatorItem: OperatorItem) {
        self.enqueue(item: operatorItem)
    }
```


더 부족한 점 있으시면 말씀해주세요:)

2021-11-11 18:21 UTC, leejun6694 approved these changes
리뷰 내용을 잘 반영해주셔서 감사합니다 : )
몇가지 눈에 띄는 코드들을 더 리뷰 남겼는데, 확인 부탁드려요.
step 1 구현으로 고생 많으셨습니다~~!

2021-11-11 18:21 UTC, leejun6694 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private mutating func enqueue(item: CalculateItem) {
enqueue 를 private method 로 만들고, 따로 두개의 method 를 더 만든 이유가 궁금합니다ㅎㅎ

2021-11-11 18:21 UTC, leejun6694 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        self.enqueue(item: NumberItem(data: number))
`self.` 를 쓰는 곳이 있고 안쓰는 곳이 있네요.
하나의 스타일로 정하면 좋을 것 같습니다ㅎㅎ

2021-11-11 18:21 UTC, leejun6694 commented on Calculator/Calculator/Model/LinkedList.swift
> +    mutating func append(data: CalculateItem?) {
여기도 옵셔널일 이유가 없을 것 같네요...!?

2021-11-11 18:21 UTC, merged

2021-11-12 01:30 UTC, llghdud921 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private mutating func enqueue(item: CalculateItem) {
enqueue메서드 사용 시에 enqueue(item: NumberItem(data: 1)) 와 같은 코드로 test를 진행해
가독성을 떨어트린다고 생각하였습니다.

그래서 메서드 오버로딩을 이용해서 사용 시 enqueue(number: 1) 의 코드로 입력받는것을 의도했습니다!

private을 쓴 이유는 enqueue(number:), enqueue(operator: ) enqueue(item:) 세 메소드를 전부 가능하게할 시에
혼란을 줄 수 있을것같아서 enqueue(item:) 은 private 접근제한자를 지정하였습니다!

저도 끝까지 고민했었는데요. 더 생각해보고 수정사항 반영해보도록 하겠습니다!

2021-11-12 01:33 UTC, llghdud921 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        self.enqueue(item: NumberItem(data: number))
self를 쓴 이유는 해당 클래스 내부에 있는 enqueue를 사용한 것입니다! 라는 의도를 코드에 담고싶었기 떄문입니다.

어느 부분은 self를 사용하고 self 안사용한 것이 더 가독성을 떨어트리는것같네요,..ㅎㅎ
수정완료하였습니다!

2021-11-12 01:42 UTC, llghdud921 commented on Calculator/Calculator/Model/LinkedList.swift
> +    mutating func append(data: CalculateItem?) {
그렇네요! node data에 해당하는 부분은 옵셔널 제거해주었습니다! 

감사합니다~