계산기 [STEP 1] PR 알라딘
yagom-academy/ios-calculator-app pull request #80
Opened 2021-11-10 10:33 UTC by junbangg

안녕하세요 @leejun6694 !
계산기 프로젝트 Step 1를 마쳐서 PR 보냅니다!
TDD가 너무 어려워서 엉망으로 한 것 같지만..😎
리뷰 잘부탁드립니다🙏

프로젝트를 하면서 궁금했던 점들을 정리 해봤습니다~

# 고민한 점

## 1. TDD 의 Git Workflow에 대해서 고민해봤습니다.

- 원래 git 관리를 할때 실제코드/production 코드만 들어가는 브랜치를 다른 브랜치들과 분리하는 경우가 많다고 들었는데.
- TDD에서 테스팅을 하는 테스트 코드는 따로 Test branch 를 파서 해야되나?라는 생각이 들었습니다.
- 그래서 TDD를 통해 최종적인 Production Code 에 들어갈 코드가 작성되면 그때 실제 코드가 있는 브랜치로 merge 시키는게 좋을지에 대한 고민을 해봤습니다.
- 그리고 TDD는 아니더라도, 현업에서는 단위 테스트 코드에 대한 관리는 Git상으로 어떻게 하는지 궁금합니다!

## 2. 테스트 코드에서 `Generic` 타입끼리의 비교를 하면서 문제에 부딪혔습니다.

- 이번 Step 을 하면서, `LinkedList` 와 `CalculateItemQueue` 를 모두 `Generic` 으로 구현해봤습니다.
- 그리고 `String` 타입의 연산자("+", "-", "/", "*")와 `Int` 타입의 숫자들을 섞어서 `LinkedList` 타입과 `CalculateItemQueue` 에 넣어 보고싶었는데, 테스트를 하면서 부딪혔던 문제가 많습니다.
- 타입이 다른 데이터들을 섞어서 `Queue` 또는 `LinkedList` 에 넣고나서, 그 데이터들이 제대로 들어갔는지 확인하기 위해서는 `Generic` 타입끼리의 비교를 하게 됐는데, `Generic` 자체로는 `Equatable` 을 채택할 수 없어서 비교가 안되는 문제점에 부딪혔습니다.
- 이 문제를 해결하기위해 `CalculateItem` 이라는 비어있는 프로토콜을 채택하는 `DummyItem` 을 만들어서 테스트 했습니다.
    
    ```swift
    enum DummyItem: Equatable, CalculateItem {
        case number(value: Int)
        case symbol(value: String)
    }
    
    ```
    
- 근데 이게 맞는건지 잘 모르겠습니다..테스트 코드와 실제 코드의 독립성을 유지하기 위해서 `Generic` 타입들을 `DummyItem` 으로 감싸서 비교를 했는데, 그게 아니라 실제 코드에서 `CalculateItem` 을 채택하는 타입을 만들었어야하는지에 대한 고민을 계속 했습니다.
- **혹시 더 좋은 방법은 없었을지에 대한 쿠마의 의견이 궁금합니다!**
<br>

## 3. 테스트를 위해 특정 타입의 변경사항을 주는 방법에 대한 고민을 했습니다.

- 예를 들어 만약에 실제 코드에서는 연결리스트의 `head` , `tail` 속성들을 `private` 로 사용하고싶다면, 테스트에서는 이걸 접근할 수 없는데 테스트를 어떻게 하지?라는 고민이 생겼습니다.
- 테스트를 위해 실제 코드에서 잠깐 `private` 를 `internal` 로 바꾸는것도 맞지 않다고 생각해서, 어떻게 하면 테스트코드와 실제 코드의 독립성을 유지하면서 작성할지가 고민이었습니다.
- 그렇다면 이걸 어떤 방법으로 하는게 맞을까요?
- **제가 고민해본 방법들은 다음과 같은데 쿠마의 의견이 궁금합니다!**
    - `LinkedList`를 그대로 테스트 파일에서 또 구현해서 필요한 메서드만 추가한다.
    - `LinkedList`를 `protocol`로 만들어서 테스트 파일에서 `struct MockLinkedList: LinkedList` 이런 식으로 사용한다.
        - 근데 그러면 `protocol` 을 채택하면서 `private` 는 사용이 안돼서 또 문제네요...ㅠㅠㅠㅠ
        - 그리고 이것도 어떻게 보면 테스트를 위해 실제 코드를 변경하는것 같다는 생각이 들었습니다.
        - `extension` 을 사용하면 테스트 파일에서만 사용하는 타입의 속성/기능들을 추가해서 사용할 수 있는걸로 아는데, 저장 속성인 `head` 와 `tail` 은 변경이 안돼서 또 막혀버렸습니다ㅎㅎ
- 그렇다면 **"Testable"** 한 코드를 작성하기 위해서 `head` 와 `tail` 을 굳이 `private` 로 안하는것도 좋은 방법인가?? 라는 생각에 그냥 `private` 를 `internal` 로 바꿔서 코드를 작성했습니다. 😂
- 이것에 대한 쿠마의 의견이 궁금합니다 :)

<br>

### 4. `String` 대신에 `Character` 를 사용하는 이점이 있는지에 대한 쿠마의 의견이 궁금합니다.

- 연산자 하나 (예: "+") 를 `Character` 로 타입을 지정할지 `String` 으로 지정할지에 대한 고민을 했습니다.
- 숫자와 연산자가 섞인 `Any` 타입의 배열을 연결리스트로 변환 시켜서 테스트를 할때, "+", "-", 같은 문자열은 스위프트가 `Character` 가 아닌 `String` 으로 추론을 하더라고요.
- 저는 "+" 를 `String` 보다 작은 단위인 `Character` 로 사용하는게 맞지않을까?라는 막연한 생각에 "연산자는 `Character` 로 사용하자" 라는 생각을 했었는데, 생각해볼 수록 근거가 없더라고요.
- `String` 을 쓰던 `Character` 를 쓰던 연산자 하나가 들어가면 (예: "+", "-"..) 16 바이트로 사이즈도 동일하고, `Character` 를 쓰는 이점이 전혀 떠오르지않더라고요...
- 그래서 결국 그냥 `String` 을 사용했는데 이것에 대한 쿠마의 의견이 궁금합니다~
<br>

## 5. 작성하는 데에 어려움을 느꼈던 테스트가 있습니다.

- 연결리스트의 모든 노드를 삭제하는 `removeAll()` 를 수행할때, 기존에 존재했던 모든 연결리스트 노드들이 메모리 상으로도 완전히 삭제가 됐는지 확인하는 테스트를 작성해 보고싶었습니다.
- `removeAll()` 에 대한 첫번째 테스트를 작성하고, (TDD 과정 중의 RED)
- 만약에 그 테스트를 통과하기 위한 최소한의 코드를 작성했을때(TDD과정 중의 GREEN), 만약에 아래와 같은 코드가 나왔으면

```swift
 mutating func removeAll() {
    head = nil
    tail = nil
 }

```

- 겉으로 봤을때는 연결리스트의 모든 노드가 없어진것 같지만, 메모리 상으로는 `head` 와 `tail` 사이에 존재했던 `node` 인스턴스들의 흔적이 남아있지않을까 라는 생각을 했습니다.
- 그런데 위 코드를 실패시키는 테스트를 작성하고싶었는데 작성하는 데에 어려움을 겪었습니다.
- 위 코드를 반증하는 테스트를 못 만들어서 그냥 뒀습니다..원래는 `tail` 부터 한 `node` 씩 역순으로 `nil` 로 만들면서 메모리에서 완전히 지우고싶었는데, TDD 의 과정으로는 반증이 된 후에 refactor를 해야되는것 같아서 내버려뒀습니다!
- 그래서 제가 궁금한것은!
- `removeAll()` 을 수행하기전에, 확인하고싶은 `node` 의 메모리 주소를 잠깐 저장해뒀다가, `removeAll()` 이 수행된 후에 그 메모리 주소에 뭔가가 남아있는지 확인하는 방법은 없는건가요???
- 그리고 저 위의 코드로 충분히 `removeAll()` 를 수행하는 데 문제가 없는지도 궁금합니다:)

## 긴 글 읽어주셔서 감사합니다!

2021-11-10 18:29 UTC, leejun6694 requested changes
알라딘 안녕하세요 : )
구현을 잘 해주셨는데, 몇 가지 궁금한 점과 수정해볼만한 코드들을 리뷰 드렸습니다.
감사합니다~~!

2021-11-10 18:29 UTC, leejun6694 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> T? {
return 값을 사용하지 않는 곳도 보이네요.
`let _ = queue.dequeue()`
와 같이 불필요한 변수가 정의되는데, 이를 해결할 수 있는 방법이 있을까요?

2021-11-10 18:29 UTC, leejun6694 commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +extension CalculatorItemQueue {
test file 에만 필요한 값들이네요.
하지만 이렇게 정의했을 경우 다른 곳에서도 사용할 수 있게되는데, 어떻게 막을 수 있을까요?

2021-11-10 18:50 UTC, leejun6694 commented
> TDD 의 Git Workflow에 대해서 고민해봤습니다.

음.. 우선 저희 팀에서는 아쉽게도 TDD 를 사용하고 있지 않아서, 현업에서 관리하는 부분은 말씀드리기 어려울 것 같습니다ㅠㅡㅜ
말씀주신 내용을 읽어보니, production 과 production+test 로 branch 를 나눠서 관리할 수는 있겠네요ㅎㅎ

> 테스트 코드에서 Generic 타입끼리의 비교를 하면서 문제에 부딪혔습니다.

리뷰 내용 반영과, 3번 궁금증 관련해서 리뷰 내용이 반영된 이후에 다시 같이 확인해도 괜찮을까요!?

> 테스트를 위해 특정 타입의 변경사항을 주는 방법에 대한 고민을 했습니다.

코드에 리뷰를 남긴 부분이 있는데, 이런 고민이 있으셨군요ㅎㅎ
음.. 이해가 다를 수 있겠지만, 결국 테스트는 코드를 실제로 사용할 때 문제가 없는지 체크하는 용도 입니다.
궁금한 점에 작성해주신 것처럼 `접근할 수 없는 값은 접근하면 안된다고` 생각이 드네요. 실제로 사용할 때도 접근하면 안되는 값이니까요..!
예를 들면 코드가 잘 돌아가고 있는지, 또는 코드 수정이 있을 때 테스트에서 잘 확인이 될 수 있도록 테스트 코드가 작성되어야하는 것이지, 테스트를 하기 위해 코드가 변경되는 일은 없어야한다고 생각됩니다.

> String 대신에 Character 를 사용하는 이점이 있는지에 대한 쿠마의 의견이 궁금합니다.

저도 크게 생각해본적이 없었던 것 같네요😅
다만, Character 사용에 큰 이점을 못 느낀다면 (때에 따라 다르겠지만, 이번 프로젝트에서..), 가벼운 마음으로 String 을 써도 되지 않을까 생각됩니다.

> 작성하는 데에 어려움을 느꼈던 단위 테스트가 있었습니다.

node 의 deinit 으로 확인해보는건 어떨까요?

2021-11-11 04:59 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    var list = LinkedList<T>()
원래 private 로 했었는데, 테스트를 할때 `list` 에 접근을 할 방법을 못찾아서 `internal` 로 바꿨습니다.
근데 맨 아래에 글 써주신거 읽어보니까, `private` 이라서 접근이 불가능한 코드는 테스트를 안하는것도 맞는 이야기 같습니다:)

2021-11-11 05:18 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        guard list.isNotEmpty else {
작성했을때는 명확하게 작성하려고 한건데 말씀해주신것처럼 저 `guard` 문은 사실상 필요가 없을것 같네요!

2021-11-11 05:21 UTC, junbangg commented on Calculator/Calculator/Model/LinkedList.swift
> +        return remove(node: nodeToBeRemoved)
오 감사합니다!
처음에 저도 `head` 를 이용해서 접근을 했었는데,
retrieveNode를 이미 구현했으니 그걸 이용하는게 좋지 않을까?라는 생각으로 바꿨습니다.
근데 이번 스텝의 요구사항이라면 `retrieveNode()` 는 사실상 필요없는 기능이긴해서 한 번 다시 바꿔보겠습니다:)

2021-11-11 05:24 UTC, junbangg commented on Calculator/Calculator/Model/LinkedList.swift
> +    func retrieveNode(at index: Int) -> Node<T>? {
아니요 참고한 자료는 없습니다..연결리스트의 중간에 있는 노드를 가져오는 테스트를 작성했는데, 그거에 맞추서 구현하다보니까 저렇게 나왔습니다:)
이번 스텝에서 큐의 중간 노드를 접근할 일이 없어서 저 메서드는 필요 없을것 같긴합니다!
그냥 이번에 TDD를 처음 해보는김에 최대한 연결리스트의 모든 기능들을 구현해보려고 한건데, 저건 사실 없애도 될것 같네요:)

2021-11-11 05:28 UTC, junbangg commented on Calculator/Calculator/Model/LinkedList.swift
> +    mutating func remove(node: Node<T>) -> Node<T> {
연결리스트의 중간에서 노드를 삭제 할때, `retrieveNode(at index: Int)` 와 함께 사용하려고 만들었습니다.
사실상 하나의 메서드를 두개로 나눈건데 저 메서드를 굳이 사용하려면 `private` 로 바꿔도 괜찮았을것 같네요!

2021-11-11 05:37 UTC, junbangg commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +extension CalculatorItemQueue {
앗 접근제어를 부여할 생각까지 못했네요 감사합니다:)

2021-11-11 07:22 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> T? {
방법이 잘 떠오르지않네요😬
리턴값이 있는 메서드 하나랑 리턴값이 없는 메서드 하나 만들어야되는걸까요??

2021-11-11 07:33 UTC, junbangg commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func dequeue() -> T? {
`@discardableResult` 를 말씀하시는건가요?!
의존모둠이랑 이야기를 하면서 나왔던 방법입니다:)

2021-11-11 18:23 UTC, leejun6694 approved these changes
리뷰 내용을 잘 반영해주셔서 감사합니다 : )
몇가지 리뷰를 추가로 남겼는데, 확인 부탁드려요.
step 1 구현으로 고생 많으셨습니다~~!

2021-11-11 18:23 UTC, leejun6694 commented on Calculator/CalculatorTests/LinkedListTests.swift
> +fileprivate extension LinkedList {
access control 로 test 코드에서만 사용되도록 잘 구현해주셨네요 👍

2021-11-11 18:24 UTC, merged

2021-11-12 01:57 UTC, junbangg commented on Calculator/Calculator/Model/LinkedList.swift
> +            newNode.previous = tailNode
앗 중간에서 노드 제거 해보려고 이중연결리스트로 만들었던건데 저거 변경하는걸 깜빡했네요!!
단순연결리스트로도 충분할것 같아요!