계산기 [STEP 1] 쿼카(Quokkaaa)
yagom-academy/ios-calculator-app pull request #83
Opened 2021-11-10 12:08 UTC by Quokkaaa

안녕하세요 엘림! [@lina0322](@lina0322)
리뷰받게되서 영광입니다.  😄  리뷰 잘 부탁드리겠습니다

계산기 STEP1 PR 보내드립니다! 

# UML

<img width="463" alt="스크린샷 2021-11-10 21 07 12" src="https://user-images.githubusercontent.com/91132536/141110284-d6880a09-e5db-41e2-975a-c2d7f96907de.png">

- Array를 선택한 이유

배열은 데이터를 삽입 제거할경우 전체적인 값들의 이동이 있을 수 있다는 단점이있지만 계산기를 이용할때 사용할 수 있는 데이터값들이 많지않을 수 있겠다고 생각했습니다.추가로

연속적인 메모리위치에 요소를 저장하므로 저장된 요소에 대한 주소를 쉽게 계산할 수 있으므로 특정 인덱스의 요소에 더 빠르게 접근할 수 있다는 장점과 Linked List로 사용하게되면 값을 참조할때 혼란스러울 수 있을것 같다는점과 마지막으로 배열의 장단점을 더 알아가고 싶은 마음에 선택했습니다.

[참조링크]([https://www.geeksforgeeks.org/linked-list-vs-array/](https://www.geeksforgeeks.org/linked-list-vs-array/))

궁금한점)

- 연산프로퍼티와 func으로 구현하는 것중 어느것이 좋을지 궁금합니다.
    
    var push: Int {} **VS** func ()
    
    func을 사용하면 stack으로 사용되고 함수기능이끝나면 메모리에서 사라지는걸로 알고있어서 func을 사용했는데요 연산프로퍼티는 생성시 메모리에 계속 남아있나요 ?
    둘 중 메모리의 효율이 더 좋은것 과 연산프로퍼티의 사용처가 궁금합니다.!
    
- struct 함수 내부에서 nodes프로퍼티와의 연결이되어있어 이 메서드는 nodes와 의존성이 있다고 생각되어집니다. nodes프로퍼티가 없으면 push가 기능을 못한다고 생각이들었습니다. 혹시 의존성이 있다면 줄일 수 있는 방법에대한 의견이 있으실까요 ?

- UnitTest를 할때 기본적인 기능동작 여부를 테스트했는데요 적절하게 하고있는건지 궁금합니다.

2021-11-10 12:44 UTC, lina0322 requested changes
반가워요. 쿼카!

이번 프로젝트 함께 잘 해쳐나가 봅시다.💪

### Array를 선택한 이유
좋습니다! 명확한 이유가 있다면, 어떤걸 사용해도 좋습니다!!
다만 혹시 linkedList 구현을 해본적이 있나요? 관련해서 이해를 하고 있는지요🙂
Array를 선택했다 하더라도 linkedList를 명확하게 하고 갔으면 좋겠어요.

### 연산프로퍼티와 func으로 구현하는 것중 어느것이 좋을지 궁금합니다.
제가 알기로는 연산프로퍼티도 메모리에 남지 않습니다.
연산프로퍼티와 자주 비교되는 계산 프로퍼티(stored property)는 이름처럼 메모리에 저장되겠죠?

그리고 둘 중에 하나를 선택하는 것에는 다양한 이유가 있을 것입니다. 
다만 저는 매개변수를 받지 않는다던가, 내부에서 복잡한 계산을 하지 않는다던지, 
의미적으로 타입이 프로퍼티로 소지하는 쪽이 더 명확한 것일때 계산 프로퍼티를 사용합니다.

관련해서는 쿼카가 좀 더 찾아보고 자신만의 기준을 만드는 것을 추천드려요!

### struct 함수 내부에서 nodes프로퍼티와의 연결이되어있어 이 메서드는 nodes와 의존성이 있다고 생각되어집니다. nodes프로퍼티가 없으면 push가 기능을 못한다고 생각이들었습니다. 혹시 의존성이 있다면 줄일 수 있는 방법에대한 의견이 있으실까요 ?
제가 쿼카의 질문 의도를 잘 파악하지 못했는데요😅
struct 안에 property와 의존성을 갖는다는게 어떤 의미인가요? 그러면 struct에 프로퍼티가 없는 상태로 만들고 싶다는 걸까요..?🥲
만약 쿼카가 node를 Node라는 다른 타입을 만들어서 했다면 의존성이 있겠지만, 지금 코드내에서 어떤 의존관계를 말하는지 제가 잘 이해가 안가서요... 좀 더 자세히 설명 부탁드려도 될까요?🙏

### UnitTest를 할때 기본적인 기능동작 여부를 테스트했는데요 적절하게 하고있는건지 궁금합니다.
unitTest는 쿼카가 만든 함수가 잘 동작하는지를 적절하게 테스트 하는 용도이죠!
다양하게 많은 테스트를 하고있는데, 저는 지금 좋아보입니다.👍

---

코멘트 달아드린 것 생각해보시고, 추가적으로 궁금한 사항 생기면 편하게 DM주세요😀

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes
return을 명시하지 않은 이유가 있나요?
또, nodes의 private 하지 않았다면 외부에서 접근이 가능 했을텐데, 그것을 막고 이렇게 사용한 이유가 있나요?😀

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func deleteRear() -> Int? {
줄 바꿈이 필요해보여요~👀

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.removeFirst()
removeFirst와 remove(at: 0)는 차이가 있나요?😀

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func calculatorSize() -> Int {
계산기 사이즈라는 함수명이 조금 모호한 것 같은데 어떤가요??

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var nodes: [Int] = []
Int로 한정짓지 않고 다양한 타입을 사용하게 만들 수는 없나요?🤔

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        if isEmpty() {
nodes.isEmpty와는 어떤 차이가 있나요?👀

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func push(_ item: Int) {
mutating이라는 키워드는 어떤 의미를 가지고 있는지 알고있을까요?😊

2021-11-10 12:44 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.isEmpty
`nodes.isEmpty()`와 `nodes == []`는 어떻게 다를까요?🥲

2021-11-10 12:50 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var nodes: [Int] = []
하나만 더 추가하자면, class랑 stuct중에 struct를 선택한 이유는 무엇일까요?😁

2021-11-10 13:45 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes
메서드내 한줄코드로 끝나는경우 생략이 가능한것으로 이애했는데요 return을 적으면 좀더 직관적일 수 있을것같다는생각도했지만 이런 자동으로 만든 시스템에 이유가있지않을까해서 생략해보았어요!

private을 적용하여 불필요한 외부의 접근을 제한하고nodes는 메서드를 통해서 값을 접근하는 방식이 객체제향에 더 가까운것같지않나..?라고 생각했어요!

2021-11-10 13:47 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func deleteRear() -> Int? {
deleteFront와 deleteRear메서드의 성질이 비슷하다고 생각되어 두 메서드는 붙여주었는데 떼는게 적절한거겠죠?ㅎㅎ

2021-11-10 14:21 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.removeFirst()
공식문서를 참고해보았는데요! 둘의 시간복잡도나 기능은 거의 유사한것같습니다. remove(at: )은 숫자선택으로 인덱스를 확인할수있는점은 제외하고
차이점이 있다고하면 removeFirst는 매개변수를 받지않고 첫번째의 인덱스를 제거하고 remove(at: 0) 는 매개변수를 받아서 첫번째인덱스를 제거하는 차이가 있는것같습니다!
혹시 의도하신 대답이맞을까요..?

2021-11-10 14:26 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    func calculatorSize() -> Int {
다시확인해보니 nodesSize 같은메서드명이 더 적절한것같습니다..!!!
확인감사합니다

2021-11-10 14:36 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        if isEmpty() {
isEmpty메서드를 구현한부분은 nodes의 값을확인하고 nodes.isEmpty도 동일한것같습니다!!!!
나중에 메서드를 굳이 사용할 필요가 없다라고하면 nodes.isEmpty로 유지해도될것같다는생각이들어요!

2021-11-10 14:39 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func push(_ item: Int) {
struct타입내 nodes인스턴스 프로퍼티의 값이 변경될 수 있음을 컴파일러에게 암시적으로 알려주는 행위라고 알고있습니다.
코드를 작성한 제입장에선 nodes의 값이 바뀔수있다는걸 알지만 컴파일러 입장에서는 mutating을 붙여주기 전까지는 인식할 수 없어서 붙여주는걸로 이해했습니다.

2021-11-10 14:50 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.isEmpty
헉.. 메서드사용을 하고 안하고의 차이가 있을것같습니다!!
피드백감사드려요..!!

2021-11-10 16:18 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes
혹시 접근 제어자 set, get 따로 설정할 수 있다는것 알고 있나요?👀

2021-11-10 16:19 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var nodes: [Int] = []
네!😁

2021-11-10 16:21 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.isEmpty
오.. 어떻게 동작방식이 다른지에 대해서 생각해보면 좋을거같아요!! 메서드 사용을 하지 말라는 의미는 아니었습니다.🙏

2021-11-11 06:04 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes
아하!! ㅎㅎ감사합니다
set, get의 존재는 알고있었습니다만 코드작성할때는 인지하지는 못하고 구현했던것같아요!!
private(set)은 외부에서 값을 읽을 수만 있고 값을 수정하는 것은 간접적으로 접근해야하는데 private(set)프로퍼티와 같은 범위내에서 메서드나 저장프로퍼티나 계산프로퍼티등으로 간접적으로 값을 변경할 수 가 있다 정도로 이해했어요!

private(get)은 외부에서 값을 읽을 수 있지만 값변경은 불가능하다. 구조체 내부에서도 값 변경이 불가능하고 메서드나 프로퍼티를 이용한 간접적인 값 변경또한 불가능하다 정도로 이해해는데 (get)부분은 이해가 잘 안되는것 같습니다 ㅜㅜ

2021-11-11 06:07 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var nodes: [Int] = []
현재로써는 struct와 class 중 어떤 것을 선택해야할 지 모르겠다는 생각들어 struct를 기본타입으로 적용하라는 공식문서를 참고하여 struct를 선택했습니다.

그런데 공식문서내에 struct는 값타입이다보니 값을 다루는 다양한 프로토콜이 존재한다라는 걸 확인했는데요
값을다루는 계산기 프로젝트에 도움이 될 수 있을까 ?라는 의문이 들었는게 어떻게생각하시나요 ?

2021-11-11 06:57 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var nodes: [Int] = []
Any와 Generics의 차이점은 더 공부해봐야 알것 같습니다만..!!
추측해보기론 Generics은 struct나 class등 타입유형에 적용할 수 있어 개별 프로퍼티의 타입이나 매개변수의 타입으로 사용하는 것 보다는 유연한것같다는생각이 들어요!!

2021-11-11 07:00 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.isEmpty
아하!!넵ㅎㅎ
동작하는 방식의 차이점에 대해서도 고민해보겠습니다!!

2021-11-11 11:23 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes
private(get)을 사용해본적 있나요?😀

2021-11-11 11:24 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var nodes: [Int] = []
struct에는 프로토콜을 채택할 수 없나요?👀

2021-11-11 13:56 UTC, Quokkaaa commented
- Array를 선택한이유에 대한 답변
Array List에서 보안된 자료구조 방식이 Linked List이라고 알고있습니다! 그래서 Linked List의 장단점 학습과 시간내서 코드 구현도 시도해보겠습니다! 

- 연산프로퍼티와 func으로 구현하는 것 중 어느것이 좋을지에 대한 답변
func 연산 프로퍼티도 메모리에 남지않는군요 !!!
매개변수를 받지 않거나 내부에서 복잡한 계산을 하지않는다던지 의미적으로 타입이 프로퍼티로 소지하는 쪽이 명확할때 계산프로퍼티를 사용하는 부분 너무 좋은 피드백이네요 !!
스스로만의 기준을 만들어가볼게요 ㅎㅎ

- struct함수 내부에서 nodes프로퍼티와의 연결이되어있어 이메서드는..........에대한 답변..
그리고 nodes의 프로퍼티와 struct함수의 의존성을 말씀드렸는데 ㅜㅜ 제가 설명을 잘못한 것 같아요 메서드의 재사용성에 대해서 여쭤보고싶었습니다. 현재 nodes메서드의 전용 메서드가 아닌가? 라는 생각이 들어서 개선하고싶은마음에 여쭤보려는게 와전이된것같아요 ㅠㅠ

2021-11-11 15:49 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes
아니요...없습니다 ㅠㅠ 공식문서 잘 참고해야겠어요  😭 😭

2021-11-11 16:05 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes
bringNodes메서드에서 매개변수사용을 하지않아 연산프로퍼티로 변경해주었습니다.

2021-11-11 16:06 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    mutating func deleteRear() -> Int? {
개행 추가 및 nil발생시 오류처리해줄 구분까지 추가해주었습니다.

2021-11-11 16:10 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +    private var nodes: [Int] = []
채택할 수 있는것으로 알고있는데요! 자세한건 더 알아봐야할것같습니다..!!
우선 제네릭을 적용했습니다.

2021-11-11 16:12 UTC, Quokkaaa commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.isEmpty
동일하게 매개변수를 사용하지않아 연산프로퍼티로 변경해주었고 
nodes == []으로 적용하고싶었으나 Equatable프로토콜을 채택하여 추가적인 타입메서드를 구현해야한다는것을 알게되어 우선 이부분에대한 이해가 없기에 추가하지않고 nodes.inEmpty 를 return값으로 설정했습니다.

2021-11-12 12:29 UTC, lina0322 approved these changes
고생하셨습니다~
코멘트 드린 부분은 생각해보시고 다음 스텝에서 반영해주시면 좋을거같아요!
다음 스텝으로 갑시다 💪

2021-11-12 12:29 UTC, lina0322 commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        nodes.count as! T
꼭 `as!`를 사용해야 하는건가요?👀

2021-11-12 12:30 UTC, lina0322 commented
<img width="547" alt="스크린샷 2021-11-12 오후 9 30 24" src="https://user-images.githubusercontent.com/49546979/141467538-47cb6a50-dd39-43d5-aa27-6df76ae2b9ce.png">

PR보내기 전에 브랜치 확인하는거 잊지 말아주세요!

2021-11-12 12:31 UTC, merged