계산기 [STEP 1] Toni
yagom-academy/ios-calculator-app pull request #84
Opened 2021-11-10 12:10 UTC by oksunwoo

안녕하세요 도미닉(@AppleCEO )
4기 캠퍼 토니입니다!
늦은 PR 죄송합니다. 아직 많이 부족한 실력이라 혼자 공부해보는 시간을 갖고자했는데, 생각보다 잘 안되더군요. 
제가 고민했던 점이나 질문사항 정리해서 보내드립니다.
따끔한 리뷰 부탁드립니다🙏 
2주동안 많이 배워가도록 하겠습니다
감사합니다

### 고민했던 점

1. 클래스 or 구조체?
    
    이 부분에 대해서 고민을 하다가, 아직 명세서에는 구체적인 것이 나와있지않고 어떻게 이용할 지 다음스텝에서 모른다고 생각해서, 애플에서 특별한 상황이 아니면 사용하라고 하는 구조체를 사용하여 구현했습니다.
    

1. 배열 or 링크드리스트?
    
    우선 배열과 링크드리스트에 차이가 배열에서 값을 제거할 때의 수행시간때문에 링크드리스트의 효율이 좋다는 것을 배웠습니다. 저는 배열을 선택했는데, 우선적으로 사용이 간편한 배열을 사용하고, 추후에 링크드 리스트로 구현해볼 생각에 배열로 구현을 하였습니다.
    
2. 접근제어자
    
    현재 제 코드에는 아무런 접근제어자가 붙어있지 않습니다. Step1만의 요구사항으로는 굳이 어디에도 붙일 필요가 없겠다고 생각을 하여 접근제어자를 붙이지 않았습니다.😓
    

### 질문사항

1. Type
    
    기존에는 연산자만이 쓰이는 큐를 구현을 하는 것 같아, CalculatorItem 타입으로 구현을 해주었는데 테스트 진행 시 Equtable로 테스트가 불가능하기도 했고, 명세서에서 `계산기가 입력받은 숫자와 연산자는 연산큐에 쌓입니다` 이러한 문구가 있어서, 같은 큐를 두개만들어줄 필요가 없을 것 같다는 생각에 generic 타입으로 변경을 했습니다. 제가 생각한 것이 맞는 지 궁금합니다.🧐
    

1. enqueue시의 테스트코드
    
    enqueue작업을 할 때 테스트코드가 3개 (연산자를 저장가능한지, 2개이상 저장이 가능한지, 순서대로 저장이 되는지) 작성되어 있는데, 추가적으로 테스트를 해줘야하는게 있는지 궁금합니다.
    

1. TDD 진행시 Fatal Error
    
    제가 TDD에서 테스트조건에 빈 배열에서 값을 추출하려 할때 nil을 반환하는 테스트코드를 먼저 작성해놓고, 빈 operationStorage에서 remove() 를 진행시켰더니 Fatal Error가 발생했습니다. 여기서의 commit을 굉장히 고민했는데, 고민한 점은 이러합니다. 
    
    1. TDD는 테스트를 위한 코드이니 fatal error일지라 하더라도 잘못된것을 발견한 것이 맞으니 commit을 보내도 된다 
    2. 작동도 안하는 코드인데, fatal Error 만이라도 발생하지 않도록 본래 코드를 수정하고 commit을 작성한다.
    
    이렇게 두개가 상충하는 고민을 하였습니다. 저는 TDD방식에 따라 1번이 맞다고 생각하였으나, 실제로는 어떤것이 맞는지 리뷰어님의 의견을 듣고 싶습니다.🤔
    

1. 검증이 끝난 메소드를 테스트에서 사용해도 되는지 여부
    
    제가 enQueue 메소드를 작성한 후, 다음 deQueue테스트를 위해서 사용하였습니다. 제가 이렇게 한 이유는 검증이 제대로 끝난 메소드라면, 다음 메소드의 테스트 진행 시 문제가 없을 것이라고 생각했기 때문입니다. 지금 PR 작성하는 도중 생각해보니, 따로따로 해주는 것이 추후에 문제점이 발생했을 경우에 대처하기가 쉽다고 생각이 드는데 리뷰어님의 의견이 궁금합니다.

부족한 글 읽어주셔서 감사합니다!😇

2021-11-11 02:43 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
토니 첫 PR 축하합니다.
코멘트들 참고해서 개선해보시면 좋겠습니다~

1. Type

기존에는 연산자만이 쓰이는 큐를 구현을 하는 것 같아, CalculatorItem 타입으로 구현을 해주었는데 테스트 진행 시 Equtable로 테스트가 불가능하기도 했고, 명세서에서 계산기가 입력받은 숫자와 연산자는 연산큐에 쌓입니다 이러한 문구가 있어서, 같은 큐를 두개만들어줄 필요가 없을 것 같다는 생각에 generic 타입으로 변경을 했습니다. 제가 생각한 것이 맞는 지 궁금합니다.🧐
- 하나의 큐에 넣는 것이 좋을 것 같습니다. 만약 연산자 큐와 숫자 큐가 따로 있으면 어떤 숫자 이후에 어떤 연산자가 들어왔는지 확인이 힘들 것 같습니다.

2. enqueue시의 테스트코드

enqueue작업을 할 때 테스트코드가 3개 (연산자를 저장가능한지, 2개이상 저장이 가능한지, 순서대로 저장이 되는지) 작성되어 있는데, 추가적으로 테스트를 해줘야하는게 있는지 궁금합니다.
- 코멘트에서 말씀드린 것처럼 CalculatorItemQueue 안에 operationStorage 에 직접 접근해서 값을 값을 확인하면 안 되고요. operationStorage 은 밖에서 접근 못하도록 수정하고 CalculatorItemQueue 에 큐의 기본 동작들을 메소드로 작성해서 그 메소드들을 테스트하는 식으로 되어야할 것 같습니다.

3. TDD 진행시 Fatal Error

제가 TDD에서 테스트조건에 빈 배열에서 값을 추출하려 할때 nil을 반환하는 테스트코드를 먼저 작성해놓고, 빈 operationStorage에서 remove() 를 진행시켰더니 Fatal Error가 발생했습니다. 여기서의 commit을 굉장히 고민했는데, 고민한 점은 이러합니다.

TDD는 테스트를 위한 코드이니 fatal error일지라 하더라도 잘못된것을 발견한 것이 맞으니 commit을 보내도 된다
작동도 안하는 코드인데, fatal Error 만이라도 발생하지 않도록 본래 코드를 수정하고 commit을 작성한다.
이렇게 두개가 상충하는 고민을 하였습니다. 저는 TDD방식에 따라 1번이 맞다고 생각하였으나, 실제로는 어떤것이 맞는지 리뷰어님의 의견을 듣고 싶습니다.🤔
- 꼼꼼하게 실패까지 커밋에 작성한 것 좋습니다! 보통 fatal Error 가 발생하게 되도 커밋을 남기도록 하는 것 같습니다. 어차피 "실패하는 테스트"를 작성하는 것이 주이기 때문에 해당 테스트가 fatal Error 인지 다른 에러인지는 조금 부가적일 것 같습니다.

4. 검증이 끝난 메소드를 테스트에서 사용해도 되는지 여부

제가 enQueue 메소드를 작성한 후, 다음 deQueue테스트를 위해서 사용하였습니다. 제가 이렇게 한 이유는 검증이 제대로 끝난 메소드라면, 다음 메소드의 테스트 진행 시 문제가 없을 것이라고 생각했기 때문입니다. 지금 PR 작성하는 도중 생각해보니, 따로따로 해주는 것이 추후에 문제점이 발생했을 경우에 대처하기가 쉽다고 생각이 드는데 리뷰어님의 의견이 궁금합니다.
- 테스트는 보통 순서가 렌덤하게 돌아가도 동작하는 것을 목표로 합니다. 테스트 순서에 대한 질문 같은데 어떤 순서로 되든 성공하도록 구성이 되면 좋을 것 같습니다.

2021-11-11 02:43 UTC, AppleCEO commented on Calculator/Calculator/Model/CalculatorQueue.swift
> +    }
코드의 가독성이 아주 좋습니다! 🥇

2021-11-11 02:43 UTC, AppleCEO commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +        sut = CalculatorItemQueue()
setUpWithError 에서 큐를 생성해준 것 아주 좋습니다! 💯 
이렇게 해서 반복을 줄일 수 있었습니다.

2021-11-11 02:43 UTC, AppleCEO commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +    func test_calculatorItemQueue_item이_2개_또는_그이상이_들어올경우_내부저장소에_저장이되는지() {
테스트명은 보통 이 테스트가 동작하는 내용만을 작성합니다. 
<2개 들어올 경우 내부 저장소에 저장이 되는지> 라는 테스트명이 더 좋을 것 같습니다 ㅎㅎ

2021-11-11 02:43 UTC, AppleCEO commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +        testArr.append(sut.operationStorage.removeFirst())
operationStorage에서 직접 removeFirst() 를 하는 것이 아니라
CalculatorItemQueue 에서 dequeue 라는 메소드를 구현해서 해당 메소드를 테스트해야 할 것 같습니다.

2021-11-11 02:43 UTC, AppleCEO commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +        let operationRemoveAllTest = sut.operationStorage.count
큐 안에 있는 요소에 직접 접근해서 count 등을 하는 것이 아니라 sut(CalculatorItemQueue) 에 enqueue, dequeue 등 큐의 기본 동작을 직접 구현하는 것처럼 그 메소드를 테스트해야 합니다.
예를 들어 sut.count() 이런 식으로 되어야 합니다.

2021-11-11 13:51 UTC, oksunwoo commented on Calculator/Calculator/Model/CalculatorQueue.swift
> +    }
감사합니다!😁

2021-11-11 13:54 UTC, oksunwoo commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +        sut = CalculatorItemQueue()
엄청 의도했던 것은 아니고, 이건 그 야곰강의에서 예시보면서 따라했었습니다. 코드를 작성하면서 이렇게 만들어준다면 각 테스트코드에서 인스턴스를 만들어주지 않아도 되겠구나하고 느끼긴 했었습니다..하하..😅

2021-11-11 14:06 UTC, oksunwoo commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +    func test_calculatorItemQueue_item이_2개_또는_그이상이_들어올경우_내부저장소에_저장이되는지() {
아 그렇군요! 변경완료 하였습니다 😁

2021-11-11 15:23 UTC, oksunwoo commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +        testArr.append(sut.operationStorage.removeFirst())
제가 이 테스트는 dequeue 메소드를 구현하기전, enqueue에 값이 순서대로 저장이 잘 되는지에 대한 테스트를 한번 시도해보기 위함이였습니다! 저의 코드가 목적이 불분명하다고 생각하여 코드를 수정했습니다!

2021-11-11 17:28 UTC, oksunwoo commented on Calculator/CalculatorQueueTests/CalculatorQueueTests.swift
> +        let operationRemoveAllTest = sut.operationStorage.count
큐 안에 있는 요소에 직접 접근하지 못하도록 우선 private 접근자를 붙여줬습니다. 그리고 CalculatorItemQueue에 메소드를 통해 테스트를 하는 방식으로 변경을 해주었습니다.

2021-11-11 17:58 UTC, oksunwoo commented
안녕하세요 도미닉(@AppleCEO )
4기 캠퍼 토니입니다!

우선 꼼꼼한 리뷰 감사드립니다. Step1의 수정사항이 일부 발생하여 이렇게 글남깁니다. 

1. README 수정
    
    변경사항이 발생하여, README 순서도를 수정하여 다시 올렸습니다.
    
2. 접근제어자
    
    기존에 operationStorage에 없던 접근제어자를 `private`으로 설정하고, 직접적으로 값을 얻지 못하도록 변경하였습니다. `private(set)`으로 읽기만 가능하게 사용해볼까도 고민했습니다.
    
3. 테스트명 수정
    
    `2개이상 → 2개가 들어올 경우` 로 메소드명을 조금 더 명확하게 변경하였습니다.
    
4. 테스트 시 dequeue 사용
    
    이 부분에서 가장 큰 고민이 되었고, 여쭙고 싶은게 있습니다. 사실 이 테스트는 `dequeue`가 작성되기 이전에 오로지 `enqueue`만을 테스트하기 위한 코드였습니다. 커밋상에서도 중간에 리팩토링 과정에서 조금 더 테스트코드의 의미를 명확히 했었으나, private접근제어자를 붙이면서 사실상 `enqueue`만으로 내부저장소에 순서대로 저장이 되는지에 대한 테스트를 할 수가 없다고 생각했습니다. 많은 고민 끝에 결국 dequeue를 사용하여 코드를 다시 수정하게 되었고, 순서대로 저장이 되는지에 대한 검증을 성공적으로 마쳤습니다. 다만, 이 경우 제가 처음에 테스트하려고 했던 의도에서 벗어났다고 생각이 들었습니다. `dequeue`가 작성이 되었고, `dequeue`에 대한 검증 역시 우선적으로 이루어졌기에 테스트가 성공할 수 있었다고 생각합니다. 여러개의 테스트가 한번에 이뤄진다는 느낌이 들어서 이러한 경우에는 어떻게 하는 것이 최선의 방법인지 여쭙고 싶습니다.

부족한 코드 및 PR읽어주셔서 감사드립니다😊

2021-11-12 02:43 UTC, AppleCEO commented
고생하셨습니다!

이 부분에서 가장 큰 고민이 되었고, 여쭙고 싶은게 있습니다. 사실 이 테스트는 dequeue가 작성되기 이전에 오로지 enqueue만을 테스트하기 위한 코드였습니다. 커밋상에서도 중간에 리팩토링 과정에서 조금 더 테스트코드의 의미를 명확히 했었으나, private접근제어자를 붙이면서 사실상 enqueue만으로 내부저장소에 순서대로 저장이 되는지에 대한 테스트를 할 수가 없다고 생각했습니다. 많은 고민 끝에 결국 dequeue를 사용하여 코드를 다시 수정하게 되었고, 순서대로 저장이 되는지에 대한 검증을 성공적으로 마쳤습니다. 다만, 이 경우 제가 처음에 테스트하려고 했던 의도에서 벗어났다고 생각이 들었습니다. dequeue가 작성이 되었고, dequeue에 대한 검증 역시 우선적으로 이루어졌기에 테스트가 성공할 수 있었다고 생각합니다. 여러개의 테스트가 한번에 이뤄진다는 느낌이 들어서 이러한 경우에는 어떻게 하는 것이 최선의 방법인지 여쭙고 싶습니다.
- 그렇군요... 보통 큐는 isEmpty, enqueue, dequeue, peek  4가지 연산자만 구현하면 된다고 알고 있습니다. 
- 이 4가지를 이용해서 적절하게 테스트를 작성해 볼 수 있을 것 같습니다. 
- 예를 들어 enqueue 를 세번하고 dequeue 를 세번하면 isEmpty 가 true 일 것입니다. 이런 식으로 테스트하는게 최선이지 않을까 합니다 ㅜㅜ

2021-11-12 02:49 UTC, merged