계산기 [STEP 2] 숲재
yagom-academy/ios-calculator-app pull request #85
Opened 2021-11-11 15:35 UTC by forestjae

수고많으십니다 그린! @GREENOVER 

지난번 스텝 1에서 정말 좋은 리뷰와 고민거리를 주셔서 좋은 학습이 되었습니다!
정말 감사드립니다 🙇🏻‍♂️

계산기 프로젝트 스텝 2 PR 드립니다 !
이번 스텝을 진행하면서 고민했던 점과 궁금했던 점 아래와 같이 보내드립니다.
천천히 봐주세요! :)

## 고민했던 것
### 1. 각 타입들이 앱에서 어떻게 동작하지?
  - 제시된 UML을 바탕으로 생각해 본 결과는 아래와 같습니다.
    1. View에서 어떤 동작을 했을때 `ExpressionParser` 타입이 `문자열로 된 계산식`을 받아 파싱하여 `Formula`의 인스턴스를 생성함
    2. `Formla`의 인스턴스 메소드인 `result()`를 사용하여 `결과값: Double`을 반환
       - 여기에서 `Formula`의 인스턴스 프로퍼티인 2개의 `queue: CalculatorItemQueue` 를 사용함
 
### 2. 어디까지가 모델의 영역이고 ViewController에선 어떤 역할을 해야할까? 
  - 명세서에서 요구하는 동작을 준수하기 위해서는 많은 예외처리와 오류처리가 필요해 보였습니다.
  - 대전제 : `ScrollView에 있는 Label들이 한꺼번에 String으로 Model에 전달 될 것이다.`
  - 본 스텝에서는 모델영역에서만 코드 작성이 이루어지므로, 역할이 어떻게 분배되야 할지를 미리 생각해 보았습니다.
      1. AC 버튼과 CE 버튼의 동작 : model의 메소드를 활용하여 VC에서 처리
      2. +/- 부호 버튼의 동작 : Label의 조작이므로 VC에서 처리
      3. = 버튼을 눌렀을때의 동작 : `ExpressionParser` 메소드의 작동 트리거 
      4. 기타 특정 조건(입력 Label이나 Formula인스턴스의 상태에 따른)에서 버튼을 눌렀을때 아무 동작도 하지 않는 것 : VC에서 처리
      5. 유효한 숫자만 표현할것 (e.g 0.123000 -> 0.123) : `ScrollView에 나타나는 입력값` -> VC에서 처리 / `계산의 결과값` -> 모델에서 처리
      6. 반올림 : VC에서 처리 (모델에서는 정확한 값을 다루고 최종 결과값만 반올림 해주는 것이 맞다고 생각하였습니다.)
  - 위와 같이 역할을 미리 분배해보고 코드를 작성하니 시행착오를 줄일 수 있었습니다.
  
### 3. TDD
  - 스텝1에서 겪은 시행착오를 바탕으로 이번에는 TDD를 조금 더 수월하게 진행 할 수 있었습니다. 그린이 말씀해주신 것 처럼 먼저 깡통 코드까지만 작성 해놓고 테스트 코드를 작성한 뒤에 테스트를 해가며 본 코드를 작성해 보았습니다. 테스트 코드를 작성하는 과정에서 어떤 예외처리와 오류처리가 필요할 지에 대한 고민이 본 코드를 작성할 때에 큰 도움이 된 것 같습니다. 또, 불필요한 실수를 줄일 수 있었습니다.
  - 다만, 제가 작성한 테스트코드가 가독성이 매우 안좋습니다. 오늘 활동학습 시간에 Mock객체를 활용한 TDD를 맛보기해봤는데요, 나중에 적용해보고 싶네요!
 
### 4. 오류처리
 - 제가 이번 프로젝트에서 현재까지 만들어 놓은 에러들은 다음과 같습니다.
   1. QueueError : 큐를 다룰 때 발생할 수 있는 에러
      - isEmpty : 빈 Queue에서 `dequeue()`나 `removeLast()`를 하게되면 반환
   2. OperationError : 연산과정에서 발생할 수 있는 에러
      - devidedByZero : 0으로 나눗셈 실행
      - invalidFormula : 잘못된 계산식이 들어왔을 때 (앱 동작과정에서는 발생할 수 없는 에러로 보이는데 일단 넣어 두었습니다.)
 
 - 기타 넣을까 말까 고민한 에러입니다.
   1. 0으로 나눗셈 처리 : 구글링을 해보다 `NaN`에 대해서도 알게 되었는데요, 해당 타입을 반환하여 줄 지 고민하다가 에러타입을 반환하기로 하였습니다. 에러를 반환하게 되면 VC에서 에러처리를 해주면서 라벨을 NaN으로 표시 해주는 기능을 넣어주면 코드가 더 깔끔할 것 같다고 생각했습니다.
   2. 파싱과정에서 발생할 수 있는 에러 
      - 연산자와 피연산자 개수가 맞지 않을때 (`OperandQueue.count != OperatorQueue - 1`) -> 이 케이스는 invalidFormula에서 걸러집니다.
      - 연산자와 피연산자 외 다른 이상한 문자가 들어왔을 때 -> 사용자가 타이핑을 하는게 아닌, 버튼을 눌러서 입력하기 때문에 발생할 수 없는 에러라고 생각했습니다.

## 궁금한 것

### 1. Enum As NameSpace
  - 처음 UML을 보고 가장 당황한 것은 enum에 케이스가 없다는 것이었어요... 검색을 해보니 `caseless Enumeration`이 연관성있는 프로퍼티나 메소드를 저장할 수 있는 공간으로 쓰일 수 있다는 걸 알 수 있었습니다. 그래서 메소드에 static을 붙여주어서 타입메서드로 사용 가능하게 작성하였습니다. 또한 구조체와는 다르게 인스턴스가 생성될 일이 없는 열거형이기에 그에따른 장점이 있다고 공부했습니다. 다만, 보통의 NameSpace는 프로퍼티 위주로 쓰이는 걸로 검색이 되고 이렇게 메소드만 있는 것은 찾아 볼 수가 없어서 일반적으로 쓰이는 방법인지 궁금합니다!
     
### 2. 고차함수
  - 이번 프로젝트에서 고차함수를 권장하기 때문에 되도록이면 고차함수를 사용해 보려고 노력했는데요, 아래와 같이 가독성이 좋지 않은 코드가 탄생하게 되었습니다. 저는 제가 작성했기 때문에 알아보기가 쉬운데, 혹시 그린의 의견은 어떠신지 궁금하네요! 조금 더 가독성을 챙기는게 좋을까요?
```Swift
        let operators = input.split(with: " ")
                .filter { operatorSet.contains($0) }
                .compactMap { Operator(rawValue: Character($0)) }
```

### 3. Extension의 물리적 위치
   - 제시된 UML에서는 기본 타입인 `String`과 `Double`에 익스텐션을 작성하게 되어있는데요. 기본타입이기 때문에 각각의 타입마다 별도의 파일을 만들어서 거기서 익스텐션을 해 주었습니다. 그래서 생기는 의문점이 Extension을 파일로 분리하는 경우는 이런 케이스가 아니라면 어떤 케이스가 있을까요? VC의 Extension도 별도의 파일로 분리하는 경우가 있는지 궁금합니다.

---

읽어주셔서 감사합니다 🙏🏻

2021-11-11 22:59 UTC, GREENOVER commented
@forestjae 
브랜치 변경 부탁드립니다🙌

2021-11-12 01:56 UTC, GREENOVER requested changes

2021-11-12 01:56 UTC, GREENOVER commented
@forestjae 
안녕하세요 숲재!
이번 스텝2도 고생많으셨습니다🙌
굉장히 빠르게 진행해주셔서 열정에 놀랐습니다!
특히 테스트 코드에 집중을 많이 하신것 같아서 많이 배워가고 계시구나라는걸 느꼈어요🥳
그럼 저의 의견을 담은 코드 리뷰를 드려보겠습니다
언제나 그렇듯 제가 이해를 못하거나 캐치를 못한 부분은 항상 있을 수 있으니 다 수용하지 마시고 어..!? 이건 내 의견이 좀 더 적절한데? 아니면 여기를 놓친것 같은데..!? 하는 생각이 들면 가감없이 말씀해주세요🤙🏻
***
### 칭찬드리고 싶은 부분
- 커밋 관리를 아주아주아주 세부적이고 명확하게 잘 하시고 계신점 💯
- TDD에 대해 이해하시고 잘 실천하고 계신점 💯
- UML 파악을 정확히 하시고 그대로 구현해주신점 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. 각 타입의 동작에 대해
- 이 부분은 DM으로 의견을 나눴던 부분과 동일한 고민이네요! 숲재가 결정했던 방향이 적절한것 같고 그것이 또한 코드에 잘 녹아져있어 UML에서 각 타입에 대해 잘 이해했다고 보입니다👍
타입 구조에 대해서는 수정없이 다음 스텝들을 진행할 수 있을거라 생각해요😁
2. 모델과 뷰컨트롤러 영역에 대해
- 전체적으로 모델과 VC에서 해야할 영역에 대해 생각하신게 맞습니다.
다만 아직 VC에 바인딩을 해보지 않은 상태여서 한두가지는 어떻게 VC에 하실지? 조금 모호하지만 이건 이후 스텝에서 숲재의 구현을 보고 모델과 VC중 어떤 부분이 더 적합할지 의견을 나눠보면 좋겠습니다🙌
저도 아직 다음 스텝에 대한 구현을 못봤기에 드는 생각이고 숲재의 생각의 방향대로 구현해주시면 좋을것 같아요☺️
다만 VC에서는 정말 뷰에 요소를 띄우고 모델과 연결해주는 느낌만 갖고 로직들의 처리는 최대한 지양하면 좋겠습니다~!
3. TDD에 대해
- 이전 스텝보다 정말 훠월씬 세부적이고 다양한 테스트 코드들이 심어져 있어서 저도 편리했습니다👍
가독이 좀 더 좋은 코드로의 발전은 하다보면 정말 이건 느는 부분이라 로직적으로 잘못되거나 하는 부분은 없습니다.
그렇기에 계속 실 코드를 작성하면서도 이런 예외처리 저런 예외처리에 대해 생각해보고 녹여낸다면 더 많은 연습이 되겠네요!
몇가지 메서드명에 대해 모호한 부분은 리뷰 코멘트로 남겨보았습니다😅
또한 추가되었으면 좋겠다 생각했던 부분은 현재 올바른 값을 비교하는 테스트 코드가 많은 느낌이였습니다.
조금 더 더 욕심을 내서 잘못들어오는 값에 대한 처리들이 더 많아지면 좋겠습니다🙋🏻
예를들어 `CalculatorItemQueueTests` 테스트 코드의 아래와 같이
```swift
    func testEnqueueOperandAndDequeue() {
        XCTAssertEqual(try operandQueue.dequeue(), 1.0)
        XCTAssertEqual(try operandQueue.dequeue(), 2.0)
        XCTAssertEqual(try operandQueue.dequeue(), 13.5)
    }
```
이런 테스트 코드가 있는데 이건 정말 순서대로 잘 작동되었을때고 거꾸로 dequeue도 해보고 아예 다른값을 dequeue 시켜보는 그런 테스트 코드도 있다면 더 금상첨화일것 같아요🙌
테스트 코드 정말 쉽지 않죠..?😅
프로그래머 입장에서는 왠만하면 코드를 짠 로직대로 테스트를 해보고 그 외에는 잘 생각하기 힘듭니다. 이건 누구나 그렇드라구요..
항상 그래서 저는 사용자를 원숭이라 생각하고 (비하 아닙니다ㅠ) 몽키 테스팅을 많이 하는 편입니다..!
정말 어떤것을 누를지 어떤 계산을 해볼지 우리는 전혀 예측할 수 없는 부분들의 시도도 하는걸 현업에선 많이 보게되더라구요😭
몽키 테스팅에 대해 학습해보셔도 좋은 주제일것 같네요👍
4. 오류처리에 대해
- 오류 처리를 잘 나누어서 적절하게 해주었다고 생각합니다.
다만 조금 더 세부적이고 많은 오류처리에 대해 고민해보셨으면 합니다!
리뷰 코멘트로는 아주 간단히 하나정도? 오류처리에 대해 남겨두었는데 아직 저도 어떤 오류처리가 보완되면 좋을지 바로 생각나는게 없지만
같이 생각해서 아예 모든 케이스에 대비할 수 있도록 추가되면 좋겠다 생각했습니다.
(정말 정말 추가될게 더 없을수도 있어요..!ㅋㅋ)
아! 그리고 하나 궁금한게 있습니다.
파싱 과정에서 발생할 수 있는 에러 부분처리에서 오퍼랜드와 오퍼레이터의 수가 같지 않다면 에러가 발생한다고 보았습니다.
혹시 예를들어 `3`이라는 숫자가 입력되고 `+` 가 입력되고 이어서 `-`가 입력된다면 기존 `+`에 `-`로 덮어써지거나 무시되는 처리는 VC에서 해주는걸까요?
모델에서 해줘야한다면 이 부분에 대한 처리가 누락되어 있다고 보였습니다.
제가 코드상 놓친거라면 말씀해주시면 감사하겠습니다🙇🏻
***
### 궁금하신것에 대한 저의 의견
1. Enum As NameSpace
- 이 부분은 정말 일반적으로 이럴땐 이렇게 무조건 사용한다~ 이런 일반화는 아니라고 생각합니다. 
숲재와 우리가 흔히 알고 있는 Enum 형태로 (케이스가 있고 등등..) 사용을 저도 하는 편입니다.
그렇지만 정말 이건 코드 스타일의 차이일뿐이라 어떤 장단점을 가져갈지에 대해 판단해보고 사용될 수 있겠습니다.
해당 프로젝트에서도 숲재가 파악한 장점이 있기에 그렇게 사용되었을거라 생각합니다.
또한 프로퍼티 케이스로 나누지 않고 저렇게 메서드만 열거로 들어가있다면 프로퍼티 케이스로 타고 들어가서 메서드를 구현하거나 호출하지 않아도 간결하긴 하네요!
흠... 저도 저렇게 사용을 많이 하지 않는걸 봐서 일반적이지 않은건가 싶지만 이건 정말...ㅋㅋ
제가 딱 결론을 내릴 순 없겠습니다 ㅠ
다만 숲재가 스스로의 코드 스타일 기준을 세우고 싶어 이것이 일반적인지 기준을 세우려면 외부 라이브러리 혹은 애플의 라이브러리들을 까보면서 대부분 어떻게 쓰고 있나 본다면 본인의 명확한 기준이 세워질것 같습니다!
2. 고차함수
- 이번 스텝에서 숲재가 많은 부분에서 고차함수를 잘 활용한걸 보았습니다.
저라도 저렇게 했을것 같은데요..?
전 저 부분도 체이닝이 잘되어있어서 가독이 좋고 무리없이 이해했습니다!
코드로 보여주신 저 부분에서 하나 마이너하게 궁금한 부분은 리뷰 코멘트로 달아봤습니다😀
3. Extension의 물리적 위치
- 저는 명확하게 구분을 하는 편인데, 지금처럼 기존 내장 타입에 있어 Extension 할때는 별도 파일로 숲재처럼 빼는 편입니다.
파일명에 대해서는 `Double+extensions`로 가져갑니다.
이렇게 파일명을 가져간것에 대해 예전에 어떤 아티클을 보고 통용되는 많은 라이브러리에서 저렇게 규칙아닌 규칙으로 쓴다는걸 보고 사용을 하는데 다시 찾으려니 못찾겠어요😅
파일명은 현재 숲재처럼도 많이 쓰이는것 같더라구요..!
익스텐션 파일 네이밍 컨벤션에 대해 저도 다시 한번 찾아볼께요!
숲재도 찾으시면 꼭 알려주세요🙇🏻
그리고 만약 내장 타입에 대한 익스텐션이 아니다! 하는 경우에는 별도 파일로 빼지 않고 해당 파일 아래에 익스텐션 코드를 넣습니다.
정리하자면 기본 내장 타입들의 익스텐션은 별도 파일로 빼서 따로 그룹화시켜 관리하고 커스텀한 VC같은것의 익스텐션은 구현한 파일 아래에 코드를 심어 관심사를 한 파일에서 가져가게끔하고 가독성도 높입니다🙌
***
### 제가 궁금한 부분 및 의견
- 리뷰 코멘트에도 남기긴 했지만 우선 가장 궁금했던게 문자열이 전달될때 공백으로 스플릿을 하는데 이 공백은 왜 필요한것이며 어디서 심어주는지 궁금해요🙋🏻
- 조금 더 개선을 시켜볼 수도 있을것 같은 포인트가 아래 코드 부분인데요.
```swift
let operands = componentsByOperators(from: input)
let operators = input.split(with: " ")
    .filter { operatorSet.contains($0) }
    .compactMap { Operator(rawValue: Character($0)) }

operands.forEach { operandsQueue.enqueue($0) }
operators.forEach { operatorsQueue.enqueue($0) }
```
요게 사실 input에 대해서 2번 도는거라 조금 비효율적일수도 있겠다 싶었어요.
현재 구조에서 input을 한번만 돌면서 operandQueue와 operatorsQueue에 값을 넣어줄 수 도 있을것 같은데 숲재 생각은 어떠실까요?
***
다시 한번 빠르게 완성도 있는 스텝2를 하심에 박수를 보냅니다👍👍👍
현재로써 저의 궁금한점 1번에 대한 부분만 해소되면 스텝2의 필수 요구사항에 대해서는 문제될것이 없다 판단됩니다!
다만 빠르게 스텝2를 해주셨기에 조금 놓쳤거나 보완되면 좋은 부분들이 있다고 생각합니다.
이에 우선은 이대로 머지되도 되지만 스텝2에서 에러처리와 테스트 코드에 대해 조금 더 보완할 수 있도록 Request Changes로 하겠습니다!
부족한 부분이 아닌 다시 한번 돌아보고 코드를 점검하는 시간으로 생각해주시면 감사하겠습니다🙌

2021-11-12 09:32 UTC, forestjae commented on Calculator/Calculator/Model/Double-Extension.swift
> +}
해당 프로토콜을 채택한것은 `Double`과 `Operator` 2개의 타입입니다. `CalculatorItemQueue<Element: CaclculatorItem>`와 같은 방식으로 표현하니, 제네릭타입에 해당될 수 있는 타입을 프로토콜을 채택한 타입으로 제한하는 효과가 있었습니다. 그래서 그 의도로 빈프로토콜을 만들게 한게 아닌가 생각이 되었었는데, 오동나무의 말로도 빈 프로토콜을 구현하게 하는 의도가 맞다고 하네요! 스텝이 진전되었을 때 어떤 역할을 할 수 있을지 궁금하긴 하네요.

2021-11-12 09:47 UTC, forestjae commented on Calculator/Calculator/Model/ExpressionParser.swift
> +                .compactMap { Operator(rawValue: Character($0)) }
이번 스텝에서 문자열을 나눠서 각각 연산자와 피연산자로 분리하는 일련의 메소드들을 어떻게 구현할 지 결정하기 어려웠는데요.
1. `split(input: String) -> [String]` 
2. `componentsByOperators(input: String) -> [String]`

명세서가 상기 2개의 메소드를 구현하라는 요구를 하고 있어서 일단 저 2개의 메소드의 역할이 뭘까 생각해봤습니다. 1번 메소드는 2번 내부에서 사용될 거라고 생각하였습니다. 2번째 메소드는 이름으로 추측컨데, 연산자를 기준으로 문자를 나눠서 문자열의 배열을 반환하는 역할을 할거같은데요. 저는 피연산자들만 반환되고 연산자는 따로 얻어줘야 된다고 생각했는데, 그린이 남겨준 코멘트들을 읽어보니 한꺼번에 처리하는게 좀 더 좋은 방향인 것 같습니다. 

문자열의 입력 형태는 `1 + 2 * 3`와 같이 중간에 공백으로 구분이 되서 들어온다고 생각했습니다.(이 부분은 VC에서 보내줄 때 구현이 되야 될 듯 싶습니다.) `1*-4/-5`와 같이 만약 공백으로 구분되지않게 들어온다면 negative부호가 문제가 됩니다. subtract기호와 negative부호가 완전히 똑같은 문자이기 때문에 해당 작업을 처리하기위해서는 정규표현식이나 전체 문자를 순회하면서 조건을 판단하는 방법밖에 없다고 생각이 됩니다. 다만 순회하면서 조건을 판단하게 되면 `split`함수가 필요 없어지게 되어 명세서가 의도한 내용이 아닐거라고 판단이 됩니다. 그래서 공백구분자가 있을거라고 기준은 유지하고 2번 메소드가 연산자와 피연산자를 합한 모든 계산식의 요소들을 반환해주는 방법을 생각해서 리팩토링 해보겠습니다.

2021-11-12 09:52 UTC, forestjae commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = input.split(with: " ")
`split()`함수를 구현하는것이 조건에 있어서 최대한 활용하려다 그렇게 되었습니다... ㅎㅎㅎ 
이 구문에서는 components와 별다른 차이가 없을 것 같습니다!

2021-11-12 09:54 UTC, GREENOVER commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let operators = input.split(with: " ")
그러네요..!
제가 UML상 놓친 부분인것 같습니다.
감사합니다👍

2021-11-12 09:55 UTC, GREENOVER commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    private static func componentsByOperators(from input: String) -> [Double] {
위와 동일하게 이해가 되었습니다!
제가 놓쳤었습니다😅🙏🏻

2021-11-12 10:02 UTC, forestjae commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let result = input.split(with: " ")
계산기의 동작 과정을 보게되면, scroll view에 사용자가 입력한 수식들이 아래와 같이 세로로 쌓이게 되는데요.
### +  5.0
### -  10.1
### ÷  -29.8

부호표시부분과 숫자표시부분이 별도의 `Label`로 구현되어 있어 해당 수식을 모아서 모델에 전달해줄때, 공백으로 각 요소들을 나눠서 전달할 수 있다고 생각하였습니다!

2021-11-12 10:06 UTC, GREENOVER commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let result = input.split(with: " ")
아아~ 이해했습니다!👍

2021-11-12 10:06 UTC, forestjae commented on Calculator/Calculator/Model/Formula.swift
> +    }
처음 생각했을때는, 계산기의 AC버튼을 누르게 되면 모든 입력사항들이 초기화 되야되기 때문에 Formula의 인스턴스를 초기화 해주기 위해서 만들어 두었는데 실제로 사용될지는 잘 모르겠습니다 ㅜㅜ

2021-11-12 10:07 UTC, forestjae commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.isEmpty == false {
오 이런 방법이 있다는걸 몰랐네요 !! 수정하겠습니다!!

2021-11-12 10:07 UTC, GREENOVER commented on Calculator/Calculator/ViewController.swift
> +
엥 이 코드는 Outdated되었던건데 제가 못봤나봅니다.
아마 처음 리뷰 시 메인 브랜치에 넘겨주고 있던것때문에 그런가봐요!
해당 코멘트 무시하셔도 됩니다~😇

2021-11-12 10:09 UTC, GREENOVER commented on Calculator/Calculator/Model/Formula.swift
> +    }
아직 감이 안오신다면 다음 스텝에서 실제로 사용되는지 확인해보고 필요없다면 없애보는 방향으로 가도 좋겠네요😁

2021-11-12 10:20 UTC, forestjae commented on Calculator/Calculator/Model/Formula.swift
> +        }
해당 구문은 계산이 종료되었는데도 연산자가 남아있을 때 잘못된 계산식으로 판단하는 기능을 하기때문에 작성을 해주었습니다!
test에 피연산자 하나만 들어갔을때의 케이스도 있습니다!

2021-11-12 13:10 UTC, forestjae commented on Calculator/Calculator/Error/OperationError.swift
> +            return "잘못된 계산식입니다."
잘못된 계산식 오류가 발생할 수 있는 경우는 연산자와 피연산자의 개수가 맞지 않을때 나타난다고 생각했어요! 그래서 저렇게 표현을 하게 되었습니다 ...!

2021-11-12 13:23 UTC, forestjae commented on Calculator/Calculator/Model/ExpressionParser.swift
> +                .compactMap { Operator(rawValue: Character($0)) }
어떻게 하든 for문을 쓰지 않으면, input을 2번 불러오게 되네요 ㅠㅠ
프로젝트 요구사항에 고차함수를 최대한 활용하라는 이야기가 있어서 해당 로직은 변경하지 않았습니다.
다만, 그린이 말씀해주신 방향으로 코드를 살짝 수정해보았습니다!

2021-11-12 13:28 UTC, forestjae commented on Calculator/Calculator/Model/Formula.swift
> +                throw QueueError.isEmpty
에러타입을 세분화하여 수정하였습니다!

2021-11-12 13:30 UTC, forestjae commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +    func testEnqueueOperandAndDequeue() {
메서드명을 변경하였습니다!

2021-11-12 21:28 UTC, GREENOVER commented
@forestjae 
더 보완된 코드가 되었네요!
고생하셨습니다 숲재🥳
꼭 수정이 필요하다고 생각되는 부분이 한곳과 한두가지 제 의견을 리뷰로 남겨보았습니다!
이부분이 처리되면 머지하겠습니다👍
아..! 제가 디엠을 놓칠때도 있어서 PR에 대해 재리뷰 요청은 PR우측 상단
![스크린샷 2021-11-13 오전 6 24 36](https://user-images.githubusercontent.com/72292617/141536522-f37532e1-4ff5-4e8f-a62e-69c3fd13fb0b.png)
요기서 리프레쉬 버튼을 눌러주시면 저한테도 요청 알림이 가기에 이걸 사용해주세요~!
또한 깃헙에 흔적을 남기시는게 좋다고 생각해서 수정 후 숲재의 의견들을 디엠도 좋지만 요 깃헙에 코멘트로 남겨두시면
추후 좋은 참고자료와 근거가 될겁니다👍

2021-11-12 21:28 UTC, GREENOVER requested changes

2021-11-12 21:28 UTC, GREENOVER commented on Calculator/Calculator/Error/QueueError.swift
> +    case OperatorIsEmpty
대문자로 case 네이밍을한 특별한 이유가 있나요🧐

2021-11-12 21:28 UTC, GREENOVER commented on Calculator/CalculatorTests/FormulaTests.swift
> +    var formula: Formula = Formula(operands: CalculatorItemQueue<Double>(), operators: CalculatorItemQueue<Operator>())
간혹 이렇게 인자들이 길어지는 시그니쳐의 경우 가독이 떨어질 경우가 많은데요.
저는 약 30~40개 정도의 알파벳 길이를 벗어나면 아래와 같이 사용하곤 해요.
```swift
var formula: Formula = Formula(
    operands: CalculatorItemQueue<Double>(),
    operators: CalculatorItemQueue<Operator>()
)
```
이런 방식에 대해 숲재의 의견은 어떠신가요?
아마 지금 배우셨는지 모르겠지만 이런 컨벤션들을 swift-format이나 lint로 정의해둘 수 있습니다.
현업에선 여러명이 코딩하기에 가독이 정말 우선시 되기에 이런 사소한 컨벤션까지 룰로 정의해두고 따르고 있습니다😄

2021-11-12 21:28 UTC, GREENOVER commented on Calculator/Calculator/Error/QueueError.swift
> +            return "연산자 큐가 비어있습니다."
세부적인 에러처리 좋네요!
그런데 네이밍에서 조금 마이너한것이 궁금합니다.
`operandIsEmpty`라는 네이밍은 오퍼랜드가 비어있다는 네이밍의 느낌이 강한데
`emptyQueue`처럼 queue 워딩도 포함되어야 할것 같은데 어떤 의도이신가요?
추가로, `emptyQueue` 케이스도 필요한건가요?
큐는 오퍼랜드큐와 오퍼레이터큐 두개로 나눠 지는것 같은데 중복된다는 느낌이 있어서요🙋🏻
또 default를 하나 만들어 우선적으로 알 수 없는 에러에 대해서도 구성해둔다면 유용하게 쓰일순 있을것 같아요!

2021-11-13 00:52 UTC, forestjae commented on Calculator/Calculator/Error/QueueError.swift
> +    case OperatorIsEmpty
엄청난 실수를 해버렸네요 ;; 수정하도록 하겠습니다

2021-11-13 00:58 UTC, forestjae commented on Calculator/CalculatorTests/FormulaTests.swift
> +    var formula: Formula = Formula(operands: CalculatorItemQueue<Double>(), operators: CalculatorItemQueue<Operator>())
그린이 제안 해 주신 방식이 가독성이 훨씬 좋네요! 수정하도록 하겠습니다.
lint에 대해서는 처음 접해서 검색을 해봤는데, 코딩 컨벤션을 도구가 알려주거나 수정해주는 것이군요 ! 신기하네요.
제 ground rule에 글자수에 따른 개행에 대한 기준을 추가하고 다음 프로젝트부터 반영해보겠습니다 !

2021-11-13 01:23 UTC, forestjae commented on Calculator/Calculator/Error/QueueError.swift
> +            return "연산자 큐가 비어있습니다."
네이밍 관련하여 말씀해 주신대로 좀 더 명확하게 표현해야 할 것 같아 queue를 붙여주어 수정하였습니다.
emptyQueue에러 같은 경우는 CalculatorItemQueue 타입에서는 현재 본인이 가지고 있는 값이 어떤 타입인지 모르기 때문에 빈 큐를 dequeue했을때 저런 제너럴한 에러를 반환하도록 설계 해놨었습니다. 그런데, 에러를 세분화해서 Fomular함수에서 반환시켜주는 만큼, Queue타입에서는 에러를 굳이 반환하지 않고 옵셔널을 반환 해주도록하고 Formula에서 바인딩을 하면서 오류를 여부를 판단 해주는 것으로 변경하였습니다!!

2021-11-13 02:34 UTC, forestjae commented
빠르고 꼼꼼한 리뷰에 정말 감사드립니다 👍
리뷰해주신 부분을 바탕으로 수정을 해보았는데요, 추가로 고민했던 점에 대해 아래와 같이 보내드립니다.

### 고민했던 것 (해결하지 못한 것)
ExpressionParser 타입의 `parse()` 메소드의 구현이 아쉽습니다. UML에서 주어진 조건들을 바탕으로 아무리 조립을 해봐도 기획자가 정확히 어떤 의도인지 찾아내지 못했습니다.  parse메소드의 역할은 Formula객체를 인스턴스화 하면서 객체의 프로퍼티인 2개의 Queue에 각 요소들을 enqueue 해준다라고 생각이 되는데요.
1. `ComponentsByOperators(input: String) -> [String]` 메소드는 이름과 반환타입을 봤을 때 연산자를 기준으로 나누어 `[String]`을 반환하는 것으로 생각이 됩니다. 연산자를 기준으로 나누라는 것은 결국 입력시에 공백문자가 없이 `1+2/3*-6` 이런식으로 들어오는 건가? 하는 생각이 들었습니다.
2. `split(target: Character) -> [String]` 함수의 역할이 무엇인지 생각 해봤습니다. target의 타입이 **Character**로 명시가 되어 있기 때문에,  `ComponentsByOperators`함수 내부에서 쓰이며 Operator가 target에 들어가서 연산자를 기준으로 문자를 나누는 기능을 한다고 생각했습니다. 그런데 여기서 negative 기호 `-`가 문제가 됩니다. subtract의 기호와 똑같기 때문에 단순히 split함수를 사용해서 나누기는 어렵고 flow Control을 활용하는 수 밖에 없을 것 같은데 그렇게 되면 너무 비효율적인게 아닌가 하는 생각과 split함수가 필요가 없는게 아닐까 하고 생각했습니다.
3. Operator Enum에 CaseIterable프로토콜을 채택하라고 요구서에 명시가 되어있습니다. 그래서 해당 프로토콜을 채택했을때 사용할 수 있는 `.allCases` 프로퍼티를 활용하여 구현을 했습니다.

엄청 장황하게 쓴거 같은데요 ㅠㅠ.. 결론적으로 뭔가를 수정할 때마다 요구사항과 맞물리지 않는게 하나씩 생겨서 결국 답을 찾아내지 못하였습니다.
결국 고민한 끝에 UML의 설계가 이상한 게 아닐까? 라는 생각까지 도달하게 되었습니다... 

그래서 저의 최종 코드는 `ComponentsByOperators` 함수는 피연산자만의 문자열 배열을 반환하고, 연산자의 배열은 input에 고차함수를 사용하여 획득 해주었습니다. negative와 subtract의 기호만 달랐어도 쉽게 해결 됐을 것 같은데 해결방법을 찾지 못해 아쉽습니다! (임의로 negative기호를 변경하여 날려주는것은 하드코딩의 느낌이 강하다고 생각하여 하지 않았습니다.)

2021-11-14 10:21 UTC, GREENOVER commented
@forestjae 
변경사항들 확인했습니다~
스텝2 고생많으셨습니다..!👍

2021-11-14 10:22 UTC, GREENOVER approved these changes

2021-11-14 10:22 UTC, merged