계산기 [STEP2] 호박
yagom-academy/ios-calculator-app pull request #86
Opened 2021-11-12 01:53 UTC by hoBahk

안녕하세요 도미닉! @AppleCEO 
STEP2 PR 보내드립니다..! 
STEP2도 잘 부탁드립니다~ 😁

고민한 점 질문드리고 싶은 점들을 정리해 보았습니다.

## 의도한 점, 고민한 점

1. 열거형 Operator 타입 사용
구조체 `Formula` 의 프로퍼티의 연산자 타입을 처음에는 `Character` 로 했었는데 `operator` 타입을 이용하여 프로그램 내에서 데이터를 전달할 때 `operator` 타입으로 던져 줌으로써 정해놓은 값만 사용할 수 있게 하였고 코드의 가독성도 좋도록 하여 enum의 장점을 살릴 수 있도록 하였습니다.
2. 요구사항 및 UML
요구사항에 맞춘 최소한의 기능만 구현 하였으며, UML에 만족하는 코드로 구현해보았습니다. UML에 맞춰 구현하는 것은 처음이어서 UML에 있는 메서드의 기능을 이해하고 구현을 하는데에 시간이 조금 걸렸지만 좋은 경험이었습니다.

## 질문 드리고 싶은 부분

1. 고차함수 적극활용
요구사항에 고차함수를 적극 활용하라는 요구사항이 있어 조금은 과하게? 고차함수를 활용하였습니다. 애초에 제가 작성한 코드가 어떤 구성을 가지고 있는지에 대해 알고 있으면 오히려 코드가 간결해서 이해하기는 쉬울 것 같은데 이 코드를 처음 본 사람은 한눈에 이해하기 어려울수도 있다고 생각했습니다. 
그래도 나름 보기에 최대한 쉽도록 고차함수를 사용해 보았는데 혹시 불편한 부분들이 있을까요? (`ExpressionParser` 열거형과  `extension String`에서 사용하였습니다.)

2. 열거형 `ExpressionParser` 사용
제공된 UML에는 `ExpressionParser`에는 case는 없고 메서드만 있습니다.
그래서 `static` 을 붙여 타입메서드로 활용될 수 있도록 하였습니다.
열거형은 인스턴스가 없으니 타입 메서드를 활용하여 필요할 때 부담 없이 사용할 수 있는 장점을 가졌다고 생각합니다. 
제가 생각한 것외에 혹시 다른 장점도 있을까요? 도미닉의 의견이 궁금합니다!

3. 코드 컨벤션
선언부를 적어 주고 구현부를 들어갈 때 한 줄을 띄워 주었습니다. 
`return`할 값이 있을 때는 구현부에서 닫는 괄호 하나로 끝날 때에는 바로 아래줄에 적어주었고, 괄호로 끝나지 않으면 `return`을 한줄 띄우고 적어주었습니다.
또한 한 줄에 코드가 너무 길어지면 중간에 끊어서 다음 줄로 넘어갈 수 있도록 하였습니다.
도미닉은 코드컨벤션을 주로 어떻게 하시나요? 

    1) 선언부가 아래와 같이 4줄인데 두줄 두줄 성격이 좀 다른 경우 4줄을 모두 붙여서 쓰시나요? 아님 두줄 두줄 띄워서 쓰시나요?
    1) 메서드 마지막 부분에 return이 있을 때 한 줄을 띄우고 return을 적어주시나요? 아님 바로 아래줄에 적어주시나요?
```swift
var operands = CalculatorItemQueue<Double>()
var operators = CalculatorItemQueue<Operator>()
let OperatorsOfInputString = componentsByOperators(from: input)
let operandsOfInputString = input.split(with: " ")
```

```swift
private func divide(lhs: Double, rhs: Double) throws -> Double {
	if rhs == 0 {
	  throw CalculateError.NotANumber
  }
  return lhs / rhs
} 
```

2021-11-13 04:47 UTC, AppleCEO requested changes
1. 고차함수 적극활용
- 과하게 사용했다는 생각이 들지는 않았습니다. 다만 축약형보다 조금 더 익숙해질 때까지는 기본형을 사용하는 것이 보기에 좋겠습니다!

2. 열거형 ExpressionParser 사용
- 성능 상으로도 enum과 struct 를 사용하면 클래스에 비해 장점이 많이 있는 것으로 알고 있습니다 ㅎㅎ

3. 코드 컨벤션
- i : 저는 붙여서 쓰는 편입니다. 공백 하나에도 이유와 의미가 있어야합니다 ㅎㅎ
- ii : 아래 케이스에서는 한 칸 띄우는게 보기에 좋을 것 같습니다!

2021-11-13 04:47 UTC, AppleCEO commented on Calculator/Calculator/Model/Formula.swift
> +    mutating func result() throws -> Double {
result 라는 메소드명은 모호한 것 같습니다.
연산의 결과인지, 연산에 성공했다는 결과(Bool)인지, 큐의 결과인지 알 수 없습니다.
더 명확한 메소드명이 좋겠습니다!

2021-11-13 04:47 UTC, AppleCEO commented on Calculator/Calculator/Model/LinkedList.swift
> +            throw QueueError.deQueueFailed
디큐에 실패했을 때 오류를 넣었다는게 좋았다고 생각이 들었다가...
옵셔널을 사용하기 좋은 상황인 것 같은데 오류로 실패를 처리하도록 바꾼 이유는 무엇인가요?
장점은 어떤게 있을까요?

2021-11-13 04:47 UTC, AppleCEO commented on Calculator/Calculator/Model/Operator.swift
> +    case multiply = "*"
열거형을 사용하기 좋은 상황 같네요! 🔢

2021-11-13 04:47 UTC, AppleCEO commented on Calculator/CalculatorTests/CalculatorTests.swift
>          XCTAssertEqual(queue.returnQueue(), [1, 2])
리턴 큐 라는 메소드명은 조금 어색한 것 같네요.
보통 메소드명에 리턴을 넣지는 않습니다.
개선해보면 좋겠습니다~

2021-11-15 07:18 UTC, hoBahk commented on Calculator/Calculator/Error/CalculateError.swift
> +    case calculateFailed
아! 그러네요..! 제가 놓쳤습니다..ㅎ
그런데 막상 보니 해당 에러를 사용하는 곳이 없어서 삭제 하였습니다!

2021-11-15 07:26 UTC, hoBahk commented on Calculator/Calculator/Model/CalculatorItemQueue.swift
> +        return try queue.deQueue()
처음에는 큐를 위한 리스트로만 생각하여 이름을 지었는데 도미닉의 이야기를 듣고 나니 LinkedList에만 어울리는 이름을 짓게 되면 나중에 큐가 아닌 스택을 구현할 때에도 메소드를 한두개만 추가하면 해당 LinkedList를 사용하여 구현할 수 있는 장점도 있을 것 같아요!
나중에 스택을 구현하지 않더라도 LinkedList와 Queue를 명확히 구분할 수 있는 장점도 있구요!

2021-11-15 07:56 UTC, hoBahk commented on Calculator/Calculator/Extension/Extension.swift
> +        return self.split(separator: target).compactMap{ String($0) }
네! 이번 프로젝트에서는 기본형을 사용하여 풀어쓰겠습니다.
그런데 역시 풀어쓰니 가독성이 좋지는 않네요 ㅠ
그래도 풀어서 써보니 이해하기도 쉽고 익숙해져서 좋은 것 같아요!

2021-11-15 08:20 UTC, hoBahk commented on Calculator/Calculator/Model/Formula.swift
> +    mutating func result() throws -> Double {
저도 같은 생각이었습니다..! 
그런데 요구사항에 제공된 UML에 메서드명이 result라고 되어 있어서 result라는 메서드명을 사용하였습니다.

2021-11-15 08:31 UTC, hoBahk commented on Calculator/Calculator/Model/LinkedList.swift
> +            throw QueueError.deQueueFailed
`LinkedList`에서 옵셔널로 리턴을 하게 되면 `CalculatorItemQueue`에서 옵셔널로 받게 되고  또 옵셔널로 리턴을 하게 되면 다른 곳에서 `deQueue`를 사용할 때마다 옵셔널 바인딩을 해야하는 불편한 점이 있었습니다. 
그래서 애초에 `LinkedList`에서 바인딩을 해서 리턴하자는 생각이었습니다. 

그런데 `LinkedList`에서 `QueueError`라는 것이 어울리는 에러명이 아니라고 생각이 됩니다. 그리고 `LinkedList`는 옵셔널로 리턴하고 다른 곳에서 `LinkedList`타입을 사용할 때 옵셔널을 알아서 처리할 수 있도록 하는 것이 좋겠다고 생각이 들었습니다. 그래서 `LinkedList`에서는 옵셔널로 반환 하고 `CalculatorItemQueue`에서 처리할 수 있도록 수정하였습니다.

2021-11-15 08:55 UTC, hoBahk commented on Calculator/CalculatorTests/CalculatorTests.swift
>          XCTAssertEqual(queue.returnQueue(), [1, 2])
아! 메서드명을 `convertArray`로 변경하였습니다. 🙂

2021-11-16 01:45 UTC, merged

2021-11-16 01:45 UTC, AppleCEO commented
머지 드렸습니다~ ㅎㅎ