계산기 [STEP 2] chacha
yagom-academy/ios-calculator-app pull request #88
Opened 2021-11-12 07:14 UTC by ChaminLee

안녕하세요 cory!  @corykim0829 
차차입니다! 
계산기 step 2 구현 완료하여 PR 보내드립니다. 
이번 스텝도 마찬가지로 TDD 기반으로 프로젝트를 진행해보고자 했으며, 궁금한 부분들은 아래 정리하여 따로 남겨두었습니다!
또한 나름대로 UML을 해석한 내용을 적어두었는데, 현재 스텝에서의 요구사항와 다른 점이 있다면 피드백 부탁드립니다!
항상 꼼꼼하게 리뷰해주셔서 감사합니다!🙏🏻

--- 

## 1. UML 분석 

- `ExpressionPaser`
	- 연산식에서 피연산자와 연산자를 분리하는 역할과 책임을 갖는 타입이라고 생각했습니다. 
	- `parse`: 연산식에서 피연산자/연산자를 분리하고 이를 활용하여 `Formula` 인스턴스를 만들어 반환
	- `componentsByOperators`: 연산자를 제외한 연산자 배열만 반환하는 기능
- `String`
	- `split`: 특정 구분자를 갖고 연산식을 피연산자/연산자와 분리허는 기능
- `Operator`
	- 연산을 담당하는 타입 
	- 연산자 케이스와 각 케이스에 맞는 연산 로직 매칭 담당
- `Formula`
	- 최종 연산자/피연산자로 구성된 queue를 각각 가지고 있다.
	- 이를 통해 result 메서드를 사용하여 최종 연산 결과를 얻어내는 역할을 한다.

`Double`이나 `Operator`가 빈 프로토콜인 `CalculateItem`를 채택하는 이유는 `CalculatoritemQueue`가 다루는 요소가 `CalculateItem`를 채택하기 때문에 이들 또한 채택해야 요소로서 사용할 수 있을 것이라 생각했습니다. 

## 2. 고민된 점 및 해결 방법

> 1. guard 문 

```swift
while  operands.items.count  >  0  &&  operators.items.count  >  0 {
    guard let nextOperand = operands.dequeue() else {
        throw QueueError.queueIsEmpty
    }
    ...
}
```
이렇게 사전에 조건을 달아줌에 따라 요소가 있는 것을 확인해주는 역할을 하지만, 최대한 안정성을 추구하고자 내부에서 dequeue할 때도 강제 언래핑이 아닌 옵셔널 바인딩을 사용했습니다. 

### Set 과 array

`Operator`인지 여부를 파악하기 위해 filter하는 부분에서 `Operator`의 `allCases`를 `Array`가 아닌 `Set`으로 두었습니다. 
그 이유는 `Set`의 `.contains` 시간 복잡도는 `O(1)`이고, `Array`의 `.contains`가 `O(n)`이어서 더 빠른 `Set`으로 구현하였습니다. 

## 3. 질문하고 싶은 부분

> 1. Enumeration의 Initializer

```swift
init(arithmetic: Character) {
    switch arithmetic {
    case "+":
        self = .add
    case "-":
        self = .subtract
    case "/":
        self = .divide
    case "*":
        self = .multiply
    default:
        fatalError("")
    }
}
```

enum에서 기본적으로 제공되는 실패가능한 이니셜라이저인 `init?(rawValue: )`를 사용하는 경우 옵셔널 처리가 불가피해 보여서 새로운 이니셜라이저를 만들려고 했었습니다. 이 때 위처럼 구현한다고 했을 때 앱이 종료되게 만드는 `fatalError`를 사용하는 방식이 좋지 않은방식인지 궁금합니다. 우선은 앱이 종료되는 케이스들을 없애주는게 맞는 것 같아 기본적으로 제공되는 이니셜라이저를 사용하고 옵셔널 바인딩하는 방법으로 해결하였습니다. 

> 2. TDD

테스트 코드를 짤 때 테스트 대상이 되는 메서드의 세부 로직을 구상하면 안되는지 궁금합니다!

예를 들어 `result() -> Double`라는 메서드를 테스트하려고 하는 경우,  내부 로직이 어떤지를 모르기에 테스트하기 어려울 거라 생각했습니다. 이에 자연스럽게 `result()` 메서드는 어떤 방식으로 구현될까?를 생각해보게 되었는데 이러한 상황이 뭔가 테스트 코드와 프로덕션 코드를 동시에 생각하게 되는 모습인 것 같아 의문입니다! 

그래서 고민해봤을 때, 테스트 코드를 짤 때는 타겟이 되는 메서드의 파라미터와 반환값만 가지고 코드를 짜고, 테스트가 완성되면 그 때서야 프로덕션 코드의 메서드를 어떻게 구현할 것인지 고민해보는 순서가 맞는가 생각을 해봤습니다. 

뭔가 병행하는 느낌이 들어서인가 싶은데, 이렇게 테스트 코드를 짤 때, 해당 메서드의 로직을 일부 생각하면서 짜도 되는 것인지 궁금합니다! 

> 3. 피연산자/연산자를 입력받는 형식

피연산자와 연산자를 입력받는 형식이 따로 주어져있지 않아 UI단에서 버튼을 눌렀을 때 피연산자와 연산자를 공백이나 다른 구분자를 두어 문자열에 `append`될거라 가정하고 Step 2를 진행했습니다. 

```swift
let expression = "123 + 23 / 4 * 90" 
```

이렇게 가정을 한 것처럼 피연산자와 연산자를 받아도 되는지 혹은 구분자 없이 연속적으로 피연산자와 연산자를 받아 다른 방식(정규표현식 등) 으로 구분해야하는지 궁금합니다. 우선 저는 구분자를 두고 값을 받는 경우가 구분하기에 명확하고 더 편리할 것 이라고 생각하여 이와 같이 구현했습니다. 

> 4. 0으로 나누는 경우

처음에는 0으로 나누는 경우를 굳이 별도의 에러 타입을 만들어서 반환하도록 하지 않았습니다. `nan`이라는 값 자체가 필요한 것이라고 생각되어 `Double.nan`을 반환하는 것으로 에러를 대체하여 사용하여 해결했었습니다.
 
```swift
private func divide(lhs: Double, rhs: Double) -> Double {
    if rhs == 0.0 {
        return .nan
    }
    
    return lhs / rhs
}
```

  하지만 이 경우 추후에 연산결과가 `nan`일 때 계산기 UI에 `NaN`을 띄워야 하는데,  에러를 리턴하는게 아니라 `nan`이라는 값을 리턴하기에 예외 처리가 더 어려워지는 것 같아 에러를 반환하는 방식으로 결국 변경하였는데, 이렇게 `nan`을 반환하는 방식으로 진행해도 이후 `nan`이라는 값을 기억하고 진행하면 문제가 없을 것 같은데 크게 차이가 없는 걸까요??

> 5. 단일 메서드도 테스트 해야하는가? 

아래와 같이 swift에서 기본적으로 제공해주는 메서드만을 사용하고 별도의 로직 없는 메서드를 구현하였다면 이 또한 유닛 테스트를 해주는게 맞을까 의문입니다! 우선은 제가 만든 메서드이기에 테스트는 필요할 것이다라고 판단하여 TDD 방식으로 진행했을 때 테스트 코드를 먼저 작성하기는 했습니다. 다만 앞으로도 이렇게 메서드내 코드가 적은 경우나, 로직이 간단한 경우에도 테스트해야하는지 궁금합니다! 추가적으로 테스트 대상이 되는 메서드를 고르는 기준(?)이 따로 있으신지 궁금합니다!!

```swift
func split(with target: Character) -> [String] {
    return self.split(separator: target).map { String($0) }        
}
```

---

감사합니다!🙇🏻‍♂️

2021-11-14 16:13 UTC, corykim0829 requested changes
수고 많으셨어요 차차 👏👏👏👏

질문들을 많이 하는 모습이 좋습니다! 👍
테스트 코드도 꼼꼼하게 잘 작성해서 좋습니다.

질문한 부분에 대한 답과 코드 리뷰를 해드렸습니다!
리뷰 해드린 부분 수정하면서 개선해봅시다!

---
3. 질문하고 싶은 부분

> 1. Enumeration의 Initializer

➡️ fatalError는 사용하지 않는게 좋습니다! 예외 처리를 해줘야지 강제 종료되는 코드를 만드는 것 자체가 위험해요!

> 2. TDD

➡️ 어떤 걱정을 하는지 알 것 같아요! result 함수 안에 사용되는 객체들을 TDD 했다면 문제가 없지 않을까요?

> 3. 피연산자/연산자를 입력받는 형식

➡️ 지금 입력을 String으로 모두 바꾼 뒤에 처리하는 방식으로는 사용한 방법 또는 정규식을 사용해야하는데요. `CalculateItem` 프로토콜을 활용하면 다른 방식으로 처리를 할 수 있을 것 같아요. `CalculateItem` 프로토콜을 구현해놓고 사용하지 않아서 말씀드리는 약간의 힌트..? 입니다 ㅎ

> 4. 0으로 나누는 경우

➡️ Double을 확장시켜서 .nan이라는 값을 만드는 것은 좋아보이지 않습니다. 이 값을 이해하는데 비용이 들 것 같아요.
다른 방법으로 처리하는 것을 고민해봅시다!

> 5. 단일 메서드도 테스트 해야하는가?

➡️ 작은 메서드라도 할 수 있다면 하는게 좋다고 생각합니다! swift 프레임워크 코드를 사용했다고 해도 의도한대로 코드가 작동되는지 확실한 증표가 될 수 있으니까요!

2021-11-14 16:13 UTC, corykim0829 commented on Calculator/CalculatorTests/OperatorTest.swift
> +class OperatorTest: XCTestCase {
Operator에 대한 테스트가 전체적으로 깔끔하고 좋아요 👍

2021-11-15 06:41 UTC, ChaminLee commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.items.count > 0 && operators.items.count > 0 {
말씀주신 것 처럼 해당 조건문을 조금 더 명확하게 하기 위해 먼저 `CalculatorItemQueue` 내에 계산 프로퍼티를 하나 추가해주었습니다. 
```swift
// CalculatorItemQueue
var hasOneOrMoreItems: Bool {
    return self.items.count > 0
}
```

변수명은 고민하다가 "하나 이상의 아이템을 가진" 이라는 뜻을 가진 `hasOneOrMoreItems` 이라고 했습니다! 처음에는 `hasMoreThanOneItem`이라고 지었는데, "more than one"이라는게 자칫 하나 이상이 아닌 초과로 볼 수 있는 가능성이 있을 것 같아 조금 더 명확하게 표현하기 위해 1개 혹은 그 이상이라는 의미를 가질 수 있는 네이밍을 선택했습니다!

실제 사용은 아래와 같이 했습니다~!
```swift
// Formula 타입의 result 메서드 
while operands.hasOneOrMoreItems && operators.hasOneOrMoreItems {
    ....
}
```

2021-11-15 06:42 UTC, ChaminLee commented on Calculator/Calculator/Model/Formula.swift
> +            let nextCalculationResult = try nextOperator.calculate(lhs: calculationResult, rhs: nextOperand)
뭔가 계산이 연속적으로 다음, 다음 ... 다음이 된다고 생각해서 `next`라는 단어를 사용했는데, 말씀주신 것 처럼 `new`라는 단어가 상황에 더 적합해보이네요!! 감사합니다!

2021-11-15 06:43 UTC, ChaminLee commented on Calculator/Calculator/Model/Formula.swift
> +            guard let nextOperator = operators.dequeue() else {
예약어를 최대한 안써보려고 하다보니 next라는 단어를 추가해줬던 것 같습니다! 말씀주신 것 처럼 반복문 내에 next 키워드를 사용하는게 조금 더 헷갈릴 수 있을 것 같습니다. 

다른 수식어 없이 `operand`와 `operator`로 네이밍 수정했습니다!

2021-11-15 06:44 UTC, ChaminLee commented on Calculator/Calculator/Error/OperationError.swift
> +    case diviedByZero
아이고😢  제가 꼼꼼히 확인을 못했네요..! 바로 수정하도록 하겠습니다!

2021-11-15 07:08 UTC, ChaminLee commented on Calculator/Calculator/Error/QueueError.swift
> +enum QueueError: Error {
조금 더 의미를 명확히 하기 위해 "데이터를 추출할 때 발생하는 에러"라는 의미를 담도록 하게 위해 `DataExtractionError`라는 네이밍으로 수정하였습니다. 이렇게 네이밍을 수정하면 큐가 아닌 다른 자료구조에서도 사용할 수 있을 것 같고, 추출이라는 상황에 한정 짓는 것 같아 조금 더 구체적인 네이밍인 것 같은데 어떻게 생각하실지 궁금합니다!

2021-11-15 07:09 UTC, ChaminLee commented on Calculator/Calculator/Error/QueueError.swift
> +    case queueIsEmpty
에러 타입명이 `DataExtractionError`로 변경 됨에 따라 해당 케이스는 `hasNoElement`로 수정하였습니다. 이 또한 마찬가지로 data라는 단어의 중복을 피하기 위해 element라는 단어를 사용하였습니다!

2021-11-15 07:21 UTC, ChaminLee commented
안녕하세요 cory! @corykim0829 
질문을 많이 드렸음에도 피드백과 함께 꼼꼼히 답변주셔서 감사합니다! 
덕분에 많은 도움이 되었습니다! 

> 1. fatalError

말씀주신 것 처럼 지금이나 이후 프로젝트에서도 최대한 지양하고, 예외처리 하는 방식으로 진행해보고자 합니다!

> 2. TDD

최대한 작은 조각으로 나눠서, 작은 조각들을 테스트하고 그 조각들을 합친 테스트를 하면 문제가 없겠군요! 감사합니다!


> 3. 피연산자/연산자를 입력받는 형식

주신 힌트를 기반으로 한 번 생각해보겠습니다..! 다만 현재 UML상에 입력이 string으로 받는 것 처럼 보여서 이처럼 생각했었습니다. 조금 더 깊은 고민이 필요하겠네요... 감사합니다! 

> 4. 0으로 나누는 경우

구현했던 것 처럼 에러 핸들링을 해주는 방식이 더 비용이 적게 드는 거라고 봐도 되겠네요! 감사합니다!

> 5. 단일 메서드도 테스트 해야하는가?

단일 메서드이면 굳이..? 이런 느낌이 있었는데, 의도대로 되고 있는지 확인해보려면 거의 웬만한 것들은 다 테스트 해보는 것도 나쁘지 않겠네요! 

---

주신 코멘트에 따라 네이밍이 어색한 부분, 조금 더 명확하게 표현할 수 있는 다른 방식 사용 등을 고려하여 개선하였습니다! 

꼼꼼하게 코멘트 해주셔서 감사합니다~! 🙇🏻‍♂️

2021-11-15 16:33 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.items.count > 0 && operators.items.count > 0 {
틀린 것은 아니지만, 이렇게 구현하면 너무 구체적인 상황을 위한 코드라는 생각이 드네요 👀
Queue라는 특성이기 때문에 isEmpty 같은 조금 더 대중적으로 많이 쓰는 프로퍼티를 만들어서 사용하는 것도 좋다고 생각이 듭니다. 참고만 하세요!

2021-11-15 16:36 UTC, corykim0829 commented on Calculator/Calculator/Error/QueueError.swift
> +enum QueueError: Error {
큐 관련 에러니까 CalculatorItemQueueError라고 해도 좋을 것 같아요. 데이터 추출과정에서만 사용되는건 아니니까요!

2021-11-15 16:36 UTC, corykim0829 commented on Calculator/Calculator/Error/QueueError.swift
> +    case queueIsEmpty
에러명 좋네요 👍

2021-11-15 16:40 UTC, corykim0829 requested changes
수고 많았어요 차차! 👏👏👏👏

다시 확인해보니 현재 입력을 무조건 string으로 받도록 미션이 되어있네요! 그렇다면 일단은 이대로 진행하면 좋을 것 같아요! 제가 미션을 제대로 확인 못했네요 죄송해요 🥲

남겨드린 피드백 빠르게 반영해서 다음 스텝 넘어갑시다! 😎

2021-11-15 16:47 UTC, ChaminLee commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.items.count > 0 && operators.items.count > 0 {
`isEmpty`를 생각하기도 했는데 그렇게 되면 `!(느낌표)` 사용을 하게 될 것 같더라고요..! 제약사항에 `!(느낌표)`를 사용하지 말라는 제약이 있어서 이처럼 표기했는데, `isEmpty`를 사용하면서 `!(느낌표)`를 쓰는 것은 다른 의미로 괜찮을까요??

2021-11-15 16:49 UTC, ChaminLee commented on Calculator/Calculator/Error/QueueError.swift
> +enum QueueError: Error {
앗.. 네네!! 제가 다른 방향으로 멀리갔군요...! 말씀주신 것 처럼 어떤 큐인지 더 명확하게 하는게 좋아보이네요! `CalculatorItemQueueError`로 수정하겠습니다.

2021-11-15 16:54 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.items.count > 0 && operators.items.count > 0 {
왜 isEmpty를 사용하면 `!`가 사용되는지 설명해줄 수 있나요?

2021-11-15 17:00 UTC, ChaminLee commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.items.count > 0 && operators.items.count > 0 {
```swift
var isEmpty: Bool {
    return self.items.isEmpty
}
```
위와 같이 `CalculationItemQueue`내의 `isEmpty`를 활용하여 프로퍼티를 만들어 정의한다면 반복문의 조건에서는 아래와 같이 사용될 거라 생각했습니다! 

```swift
// Formula 타입의 result 메서드 
while !operands.isEmpty && !operators.isEmpty {
    ....
}
```

2021-11-15 17:01 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.items.count > 0 && operators.items.count > 0 {
아하 이 느낌표는 강제 언래핑이 아니여서 괜찮습니다 ㅎ 이번 미션에서 강제 언래핑을 쓰지 않고 진행하는 것이고, 이 코드에서 !는 Bool값을 토글해주는 연산자입니다! ㅎ

2021-11-15 17:04 UTC, ChaminLee commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.items.count > 0 && operators.items.count > 0 {
아아 저는 Bool 타입에 쓰이는 `!`도 쓰지 말라는 것으로 이해했는데 괜찮은거군요..! 그러면 해당 방향으로 수정하도록 하겠습니다~!🙏🏻

2021-11-15 17:09 UTC, corykim0829 approved these changes
스텝2 머지 축하드립니다 차차! 👏👏👏

다음 스텝 진행 전에 DM으로 목표 PR 시간 말씀해주세요!

2021-11-15 17:09 UTC, merged

2021-11-15 17:10 UTC, ChaminLee commented
꼼꼼하게 의견주셔서 감사합니다 cory!! @corykim0829 
또 늦은 시간에 이렇게 빠른 피드백 주셔서 감사합니다~! 💪🏻

말씀주신 것 처럼 Step 3 일정은 내일 시작 전에 정리해서 말씀드리겠습니다~!