ios-calculator-app [STEP 2] nicholas
yagom-academy/ios-calculator-app pull request #92
Opened 2021-11-12 17:27 UTC by Kim-EunsooSilver

안녕하세요 코리(@corykim0829 )!!
꿀같은 주말에 PR 전송을 드려 송구스럽습니다...🙈
당장 리뷰를 바라는건 절대 아니니,, ㅎㅎ 편히 쉬시고 여유로우실때 리뷰 부탁드립니다!!🙉🙈🙉

## 궁금한점
* 이전 스텝 PR에서의 브랜치 관련해서 여쭤보고 싶습니다.
    > 특정 브랜치만 포크할 수 있어요! 다음 프로젝트에서 여유가 있다면 도전해보세요!
    * 말씀하신 `특정 브랜치만 포크`를 공부해보려고 검색도 해보고,,, 선배기수분들과도 의견을 공유했는데... 방법을 못찾았습니다... 코리 정말 바쁘시겠지만, 혹시 방법을 알 수 있을까요...? 꼭 알려주셔야 합니다... 선배 기수분들이 꼭 말해달라고 부탁했거든요...🙏🏻
    > 이 머지된 야곰 아카데미 저장소 - 니콜라스 브랜치를 포크한 저장소 - 니콜라스 브랜치와 동기화 시켜주면 됩니다. (rebase, pull 등을 사용한 동기화 처리)
    * 해당 방법도 찾아보고 의견 공유를 해봤습니다. 말씀 하신 방법을 하기 위해서는 레포지터리 관리자가 콜라보레이터를 지정해야 가능하다고 결론이 지어졌는데요...! 혹시 저희가 잘못 생각했다면.. 바로잡아주세요 코리... 3기 엘렌이 무척 궁금해 합니다..
* 입력 받은 문자열관련한 질문입니다!
    * 저는 View 객체에서 사용자가 입력한 숫자와 연산자를 "," or "(공백)" 등을 삽입해서 모델객체로 넘겨주는 방식으로 이해했습니다. 그렇다면 구분자 역활을 하는 Charactor를 별도의 전역 상수를 넣으면 좋을거 같다라는 생각을 했습니다. 프로젝트 요구사항 중 `추가하고 싶은 사항이 있다면 리뷰어와 협의 후 진행하세요` 라는 요구가 있어서 여쭤봅니다. 전역 상수를 선언해도 될까요?
* 와일드 카드 패턴 사용의 적절성 관련 질문입니다.
   * parse 메소드 내부에 와일드 카드패턴을 사용했습니다.
   ```swift
    static func parse(from input: String) -> Formula {
        ...
        _ = componentsByOperators(from: input).compactMap { Double($0) }
                                              .map { formula.operands.enqueue($0) }
        
        _ = componentsByOperators(from: input).compactMap { Operator(rawValue: Character($0)) }
                                              .map { formula.operators.enqueue($0) }
        ...
    }
   ```
    * 아직 클로저와 고차함수가 낯선 저로서는... 솔직히... 반복문과 조건문을 이용해서 구현하고 싶지만, 고차함수를 활용하라는 요구로 상위와 같이 작성했습니다. 구현 하다보니 고차함수는 반환값을 반환하게 되는데, 불필요한 반환값을 무시하고 싶어 와일드카드 식별자를 사용했습니다. 저는 코드 작성자이기에 코드를 해석하는데 쉽게 읽히지만, 와일드 카드 식별자가 다른 개발자가 해석하는데 혹시 불편을 줄까요? 가독성을 해치는 요소인가요?
---
이상입니다~! 코리! 꿀🍯주말 되길 바라요!!!! 저도...... 꿀주말을 보내...도 되겠져...?ㅎ;;

2021-11-12 17:45 UTC, Kim-EunsooSilver commented
추가적인 수정이 있어 코멘트 작성합니다!!! 코리!!!!

와일드카드 패턴 관련해서 3기 수박과 의견을 나누던 중에 forEach 라는 고차함수를 알게 되었습니다. forEach 함수는 반환값이 없기에 제가 와일드 카드 패턴으로 구현한 부분을 forEach를 활용하여 수정하였습니다!!!! 
이로써 와일드 카드 패턴은 제거가 되었으나, 와일드 카드 패턴의 사용이 가독성에 해가 되는지는 아직 궁금합니다!

2021-11-14 17:14 UTC, corykim0829 requested changes
수고 많으셨습니다!! 👏👏👏

고민을 많이하신 흔적이 보여서 좋았습니다. 고민하셨던 부분에 대해서는 아래 답을 해드렸어요! 
제가 해드린 리뷰 바탕으로 개선해봅시다 ㅎ

---

> 이전 스텝 PR에서의 브랜치 관련해서 여쭤보고 싶습니다.

➡️ 특정 브랜치 포크는 제가 한번 더 찾아보고 말씀드릴게요!
➡️ 브랜치 동기화 부분은 step2 머지할 때 한번 같이 해봐요!

> 입력 받은 문자열관련한 질문입니다!

➡️ 네 전역변수 만드셔도 됩니다!

> 와일드 카드 패턴 사용의 적절성 관련 질문입니다.

➡️ map이 값을 반환하는 고차함수여서 그렇습니다. 반환하지 않는 고차함수를 사용하면 와일드카드 패턴을 사용하지 않아도 됩니다.

2021-11-14 17:14 UTC, corykim0829 commented on Calculator/CalculatorTests/FormulaTests.swift
> +class FormulaTests: XCTestCase {
테스트 코드 깔끔합니다 👍

2021-11-14 17:14 UTC, corykim0829 commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    func test_9_나누기0의_결과가_3인가() {
에러 부분을 테스트하는 부분 좋습니다!
그런데 테스트 함수명이 조금 어색해보이네요! 개선해봅시다 ㅎ

2021-11-14 21:28 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/Formula.swift
> +    enum FormulaErro: Error {
😭죄송합니다... 바로 수정했습니다.

2021-11-14 21:29 UTC, Kim-EunsooSilver commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +    func test_9_나누기0의_결과가_3인가() {
😭 테스트 함수 복붙의... 폐단이네요... 좀더 신경쓰도록 노력하겠습니다...ㅜㅜ

2021-11-14 21:39 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/Formula.swift
> +    var operators = CalculatorItemQueue<Operator>()
일단은 제가 이렇게 구현한 이유부터 말씀드리도록 하겠습니다.
step2의 요구중 `UML대로 연산과 관련한 타입을 구현합니다`라는 요구가 있었으며, UML에 기재된 해당 속성들은 `+`로 되어있었습니다!!
🧐🤔제가 요즘 `객체지향의 사실과 오해`라는 책을 읽고 있습니다..(아직 앞부분이지만요...)
제가 읽은 내용대로 Formula를 구현하자면, 객체의 독립성과 자율성을 위해 operands와 oprators를 private로 접근을 제어하고, 외부에서 해당 속성에 접근하여, 추가할 수 있도록 별도의 메서드를 구현하는게 더 좋다고 생각합니다.

2021-11-14 21:51 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.queue.first != nil {
ㅎㅎ;;;; 맞아요... 코리가 말씀하신데로 제가 구현한걸 차근차근 다시 보니 `isEmpty`가 있었네요...
```swift
while !operands.queue.isEmpty {
...
}
```
요렇게 수정했습니다!!!

추가적으로 코리..! 코리는 이부분 관련해서 동일한 경험이 있으셨는지 궁금합니다! 
프로젝트가 진행되가면서 이전에 내가 작성한 기능들을 기억못한 경험이요...!
만약 있으셨다면, 어떻게 극복하셨는지도 궁금합니다!!!

2021-11-14 22:40 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/Formula.swift
> +            guard let calculatingOperand = operands.dequeue() else {
수정 완료했습니다!!!!
🤔🧐 변수명과 함수명은... 항상 어려운거 같습니다...!!

제가 수용할수 있도록 명확한 근거를 말씀해 주셔서 정말 감사합니다!!!!!🙏🏻

2021-11-14 22:42 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/Formula.swift
> +            guard let currentOperator = operators.dequeue() else {
넵!!! 피드백 반영했습니다~!!!!

2021-11-14 23:10 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/Formula.swift
> +        result = result + initialValue
코리!! 혹시 코리가 말씀하시는 방향은
해당 부분을 `result = initialValue` 으로 변경하는 건가요...?

🤔만약 제가 코리의 방향을 잘 해석했다면... 전 더해주는게 더 코드를 해석하는데 더 좋다고 생각해요!

---
제가 생각한 절차
1. result = 0
2. result에 초기값을 더해준다
---
제가 추측한 코리의 방향에 대한 절차
1. result = 0
2. result에 초기값을 할당해 준다
---
그런데.... 이렇게 작성하다보니 **_코리의 의견이 더 좋다고 생각이 되네요_**...ㅎㅎㅎㅎ;;;
그래서 이렇게 변경해 봤습니다~!

변경전
---
```swift
    func result() throws -> Double {
        var result: Double = 0.0
        guard let initialValue = operands.dequeue() else {
            return 0.0
        }
        
        result = result + initialValue
        
        while !operands.queue.isEmpty {
            guard let `operator` = operators.dequeue() else {
                return 0.0
            }
            guard let operand = operands.dequeue() else {
                return 0.0
            }
            
            if `operator` == .divide && operand == 0.0 {
                throw FormulaError.NaN
            }
            
            result = `operator`.calculate(lhs: result, rhs: operand)
        }
        
        return result
    }
```
변경후
---
```swift
    func result() throws -> Double {
        guard var result = operands.dequeue() else {
            return 0.0
        }
        
        while !operands.queue.isEmpty {
            guard let `operator` = operators.dequeue() else {
                return 0.0
            }
            guard let operand = operands.dequeue() else {
                return 0.0
            }
            
            if `operator` == .divide && operand == 0.0 {
                throw FormulaError.NaN
            }
            
            result = `operator`.calculate(lhs: result, rhs: operand)
        }
        
        return result
    }
```

2021-11-14 23:28 UTC, Kim-EunsooSilver commented
안녕하세요 코리~!!
늦은 시간까지 PR 피드백 주셔서 정말 감사드립니다!!!!
또한, 꼼꼼한 피드백까지....🙏🏻 감사합니다!!
피드백 주신 부분에 대해서 reply 로 답변 진행했습니다!!

전반적으로 제 코드를 다시 돌아보면서 추가적으로 궁금한 점이 생겼습니다
```swift
componentsByOperators(from: input).compactMap { Double($0) }
                                  .forEach { formula.operands.enqueue($0) }
        
componentsByOperators(from: input).compactMap { Operator(rawValue: Character($0)) }
                                  .forEach { formula.operators.enqueue($0) }
```
이 부분인데요!. 생각해 보니 componentsByOperators 메서드가 두번 호출이 되더라구요! 
그래서 요렇게 수정해봤습니다.
```swift
let componentedInput = componentsByOperators(from: input)
        
componentedInput.compactMap { Double($0) }.forEach { formula.operands.enqueue($0) }
componentedInput.compactMap { Operator(rawValue: Character($0)) }.forEach { formula.operators.enqueue($0) }
```
요렇게 하면 componentsByOperators 메서드가 한번 호출이 됩니다!
여기서 드는 의문점이 있습니다. 동일한 메서드를 두번 호출해서 처리하는게 좋은가요? 아님 해당 메서드의 결과를 담을 무언가(여기서는 상수가 되겠네요!)를 만들고 이 녀석을 별도의 처리를 해주는게 좋은가요?
전자의 경우는 별도의 메모리 공간을 소비하지는 않고... 후자의 경우는 동일한 처리를 해주는 메서드를 한번만 호출하는데.. 각각 일장일단이 있어서요... 상황에 따라 적절하게 사용하는게 좋을까요? 지금 이 프로젝트의 경우는 어떤것이 더 좋은가요?

그리고... 아직 풀리지 않은 궁금증이 있습니다. 와일드 카드 패턴을 사용하는 부분에 있어서 단점이 있을까요?

2021-11-15 16:09 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +            guard let calculatingOperand = operands.dequeue() else {
변수, 함수명은 현업에서도 시간이 많이 드는 것 중에 하나에요 ㅎ

2021-11-15 16:13 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +    enum FormulaErro: Error {
죄송할 것 까지는.. 없어요! ㅎㅎ

2021-11-15 16:14 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +    var operators = CalculatorItemQueue<Operator>()
UML에 명시되어있군요! 제가 못봤네요 ㅎㅎ
접근제어에 대해서 객체지향적으로 잘 이해하고 계신 것 같네요! 👍 그럼 public으로 진행해주세요!

2021-11-15 16:20 UTC, corykim0829 commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.queue.first != nil {
기억 못할 수도 있죠! 이런 상황에서는 operands 객체 구현부에 들어가서 지금 상황에 적절한 코드가 구현되어있는지 확인한다면 바로 ㅅㅏ용할 수 있었을 것 같아요.

그런데 operands 자체가 큐인데 또 queue를 가져와서 isEmpty 값에 접근하는 게 깔끔하진 않네요.
depth는 되도록이면 하나인게 좋고 queue가 중복되는게 어색하네요! 조금 더 개선해봐요!

2021-11-15 16:28 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/Formula.swift
> +        while operands.queue.first != nil {
음... depth에 대해서는 전혀 생각하지 못했습니다!!!
기억하도록 하겠습니다!!!

CalculatorItemQueue - isEmpty 함수를 구현했습니다!
해당 함수를 사용함으로서
```swift
while !operands.isEmpty() {
}
```
이렇게 수정했습니다~!

2021-11-15 16:30 UTC, corykim0829 requested changes
수고 많으셨어요 니콜라스 👏👏👏

코드가 전체적으로 많이 깔끔해졌네요 ㅎㅎ
조금만 더 수정해봐요!!

---

> 요렇게 하면 componentsByOperators 메서드가 한번 호출이 됩니다!
여기서 드는 의문점이 있습니다. 동일한 메서드를 두번 호출해서 처리하는게 좋은가요? 아님 해당 메서드의 결과를 담을 무언가(여기서는 상수가 되겠네요!)를 만들고 이 녀석을 별도의 처리를 해주는게 좋은가요?
전자의 경우는 별도의 메모리 공간을 소비하지는 않고... 후자의 경우는 동일한 처리를 해주는 메서드를 한번만 호출하는데.. 각각 일장일단이 있어서요... 상황에 따라 적절하게 사용하는게 좋을까요? 지금 이 프로젝트의 경우는 어떤것이 더 좋은가요?

➡️ 어차피 함수 호출 할 때만 해당 메모리를 할당해서 큰 차이가 없다고 생각이 듭니다. 저는 후자가 더 읽기 좋은 코드 같아요 😀

> 그리고... 아직 풀리지 않은 궁금증이 있습니다. 와일드 카드 패턴을 사용하는 부분에 있어서 단점이 있을까요?

➡️ 여기서 와일드 카드 패턴이라고 하기에는 애매한 것 같아요. 이전에 사용하신 것은 반환값을 그냥 사용하지 않겠다고 명시해주는 것인데, 이는 반환값이 있는 함수나 어떤 코드를 사용할 때 불가피하게 반환값을 사용하지 않고 처리하는 부분에서 명시하는 건데, 저희는 반환값이 없는 다른 고차함수를 쓸 수 있는 옵션이 있었기 때문에 굳이 언더바 `_`를 쓸 이유가 없다는 의미로 리뷰를 해드린 부분이었습니다.
말씀하신 와일드 카드 패턴에 대한 이슈는 함수 파라미터에서 사용되는 언더바 `_`이기 때문에 조금 다른 것 같네요 😀

2021-11-15 16:30 UTC, corykim0829 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let componentedInput = componentsByOperators(from: input)
상수로 따로 빼서 처리하는 부분은 깔끔하고 좋습니다. 다만 componentedInput 이라는 이름이 좀 어색하네요! 개선해봐요 👀

2021-11-15 16:30 UTC, corykim0829 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        componentedInput.compactMap { Operator(rawValue: Character($0)) }.forEach { formula.operators.enqueue($0) }
고차함수 여러개를 쓸 때 이렇게 한줄에 다 써버리면 읽기가 어렵습니다. 개선해봐요 😀

2021-11-15 16:49 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let componentedInput = componentsByOperators(from: input)
👀separatedInput 요건 어떠신가요!!!!ㅎㅎㅎ

separatedInput 으로 수정해봤습니다.

2021-11-15 16:54 UTC, Kim-EunsooSilver commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        componentedInput.compactMap { Operator(rawValue: Character($0)) }.forEach { formula.operators.enqueue($0) }
코리~! 19행의 경우 고차함수식이 길어서 가독성을 위해 개행처리를 진행했습니다.

다만, 18행은 짧다고 생각되며, 짧은 경우라면 개행을 할 경우 오히려 가독성이 더 안좋다고 생각해서 수정처리는 진행하지 않았습니다만,,, 혹시  고차함수 2개 이상이면 개행을 하는게 더 좋은가요...?

전 저만의... 주관에 사로잡혀서.. 방향을 잡지 못하겠네요!!
가르침 부탁드립니다~!

2021-11-15 16:56 UTC, corykim0829 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        let componentedInput = componentsByOperators(from: input)
componentsByOperators 함수가 input을 받아서 String 배열로 반환해 줘서 input이라는 말은 안들어가는게 좋을 것 같기는 합니다!
근데 separatedInput도 의미는 명확한 것 같아요

2021-11-15 17:00 UTC, corykim0829 commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        componentedInput.compactMap { Operator(rawValue: Character($0)) }.forEach { formula.operators.enqueue($0) }
가독성도 중요하지만 일관성도 어느정도 중요해서 규칙이 있으면 좋은데요.
https://github.com/StyleShare/swift-style-guide 컨벤션 참고해서 해보는 것도 좋아요!

개인적으로는 고차함수는 이렇게 개행처리하는 걸 좋아합니다.
```swift
componentedInput
      .compactMap { Double($0) }
      .forEach { formula.operands.enqueue($0) }
```

2021-11-15 17:08 UTC, corykim0829 approved these changes
step2 머지 축하드려요!!! 👍

다음 스텝 진행 전에 저에게 DM으로 목표 PR 시간 말씀해주세요!

2021-11-15 17:08 UTC, merged