계산기 [STEP 2] 호댕
yagom-academy/ios-calculator-app pull request #98
Opened 2021-11-15 10:24 UTC by yanghojoon

리뷰어: @GREENOVER
안녕하세요! 그린! 🙌
계산기 Step 2 PR 제출합니다.
고민했던 부분과 조언을 얻고 싶은 부분에 대해 정리했습니다!

부족한 점이 많은데 잘 부탁드려요 🙏

### Step 2에서 고민했던 부분
#### 1. `CalculateItem` 프로토콜을 어디에 채택하면 좋을지 고민했습니다. 
`CalculatorItemQueue`의 제네릭 타입에 프로토콜을 채택하는 것이 가장 적합하다고 생각했습니다. 타입에 채택을 하게 되면 타입에는 `Operator` 열거형과 `Double`만 들어올 수 있게 되고 다른 타입의 인스턴스를 생성할 수 없어 가장 타당하다고 판단했습니다. 

#### 2. `ExpressionParser`가 왜 케이스가 없이 구현된 것인지 고민했습니다. 
열거형을 싱글톤처럼 사용하기 위함이라 생각합니다. 열거형의 경우 따로 인스턴스를 생성할 수 없습니다. 
따라서 함수를 `static`으로 타입 메서드를 생성하면 파일 전체에서 연산자와 피연산자를 분리하는 `parse` 메서드를 싱글톤처럼 호출할 수 있기 때문에 타입 메서드로 구현했습니다. 
```swift=
static func parse(from input: String) -> Formula {
    var formula = Formula()
    let operandsItems = componentsByOperators(from: input).compactMap { Double($0) }
    let operatorsItems = input.compactMap { Operator(rawValue: $0) }
        
    formula.operands.items = operandsItems
    formula.operators.items = operatorsItems
        
    return formula
}
```

#### 3. 연산자 배열과 피연산자 배열을 어떻게 분리할 지 고민했습니다. 
피연산자 배열의 경우 `Double` 배열, 연산자 배열의 경우 `Operator` 타입의 배열로 생성해야했습니다.
또한 음수의 경우 마이너스를 연산자가 아닌 피연산자로 인식해야 했습니다. 

먼저 operandsItems의 경우 `String`을 `Double`로 변환해야 했습니다. 이 때 `map`을 사용하게 되면 변환이 되면서 옵셔널 Double 타입으로 변환이 되기 때문에 `compactMap`을 사용했습니다. 

또한 operatorsItems의 경우 `String`을 `Operator`로 변환해야 했습니다. 또한 Operator 열거형의 rawValue에 해당하는 값만 꺼내와야 했기에 `let operatorsItems = input.compactMap { Operator(rawValue: $0) }` 이렇게 구현했습니다. 
변환이 되지 않아 nil로 된 값은 제거해줘야 했기에 `compactMap`을 사용했습니다. 

또한 음수와 연산자를 구분하기 위해 연산 가능한 minus와 연산이 불가능한 minus를 나눠서 String으로 값을 받도록 했습니다.
먼저 `.replacingOccurrences`메서드를 활용해 연산자를 `" "`로 수정해줬고 이를 토대로 extension으로 구현한 `split` 메서드를 활용해 쪼갠 뒤 map을 활용해 연산이 안되는 minus를 연산 가능한 minus로 수정했습니다. 

`let convertOperands = operands.map { $0.replacingOccurrences(of: "−", with: "-") }`

### Step 2에서 조언을 얻고 싶은 부분
1. 테스트 코드에서 `.`이나 `+` 같은 기호를 쓰고 싶다면 어떻게 사용하면 좋을까요? 
2. `CalculateItem` 프로토콜을 제네릭의 타입에 채택한다면 UML 상에서 `CalculateItem`과 `CalculatorItemQueue`가 연결이 안되는 것이 맞는지 궁금합니다. UML 상에서 간접 연관으로 연결될 수 있는 것이 아닐까요?
3. `takeOutItem` 함수에 반환값을 추가하면서 테스트 코드에 경고창이 떴다. 반환값을 사용해주지 않았기 때문으로 파악했는데 이런 경우 그냥 경고창을 무시해도 되는 걸까요? 오류가 나오는지 확인하는 테스트라 반환값을 굳이 사용해줄 필요는 없다고 생각하는데 그린의 의견이 궁금합니다. 
4. `CalculatorItemQueue`에서 `appendItem`, `removeItem`, `removeAllItems` 메서드가 3개가 있는데 그렇다면 SOLID의 단일 책임 원칙을 위배한 것인지 궁금합니다. 
5. 왜 빈 문자열은 Character로 바꿀 수 없는지 궁금합니다. `Can't form a Character from an empty String`

2021-11-15 15:14 UTC, GREENOVER requested changes
@yanghojoon 
호댕 스텝2도 고생많으셨습니다!!🥳
만만치 않으셨을것 같은데 잘 소화해내시고 발전하고 계시네요👍
이번주가 벌써 계산기(전) 프로젝트의 마지막이네요😂
그럼 이번 한주도 잘 부탁드립니다~!

### 칭찬 드리고 싶은 부분
- 스텝2도 이슈와 프로젝트 관리를 잘해주고 계시네요! 💯
- 리드미 작성이 날이 갈수록 좋아지시네요! 포폴도 수월하겠어요 💯
- 정해진 기한에 맞춰 스텝을 진행하신점 💯
- 세분화된 커밋 관리 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. CalculateItem 프로토콜을 어디에 채택하면 좋을지
- 이 부분 너무 잘해주신걸 코드로 확인했습니다!👍👍
뿐만 아니라 잘 이해하고 계신것 같아 제가 더 첨언 드릴게 없네요😅
2. ExpressionParser가 왜 케이스가 없이 구현된 것인지
- 이것도 1번과 마찬가지로 잘 이해하고 계십니다!
추가로 학습 포인트를 하나 첨언 드리자면 [Cassless Enum](https://codecram.asoftwareco.com/2017/12/14/caseless-enums/) 레퍼런스를 공유드려보겠습니다🙌
아마 다 학습해보거나 아시는 내용이긴 하실것 같은데 관심사가 같은 프로퍼티/메서드들을 담는 용도로도 사용되곤 합니다!
3. 연산자 배열과 피연산자 배열을 어떻게 분리할 지
- 해당 고민포인트가 잘 반영된 코드를 확인했습니다!
이상은 없어 보이지만 조금 욕심을 내보자면 코드의 중복이 있는 부분과 가독성이 약간은 떨어지는 포인트가 있습니다.
이에 리뷰 코멘트로 달기는 했지만 한번 고민을 해보고 리팩토링을 간단히 해본다면 더 좋은 코드가 나올 수 있을것 같습니다!
***
### 조언 요청에 대한 저의 의견
1. 테스트 코드에서 .이나 + 같은 기호를 쓰고 싶다면 어떻게 사용하면 좋을까요?
- 사실 이 질문을 정확하게 이해하지 못했습니다😭
테스트 코드에서 어떻게 사용되고 싶으신건지 조금 구체적인 설명을 붙여주실 수 있을까요?
2. CalculateItem 프로토콜을 제네릭의 타입에 채택한다면 UML 상에서 CalculateItem과 CalculatorItemQueue가 연결이 안되는 것이 맞는지 궁금합니다. UML 상에서 간접 연관으로 연결될 수 있는 것이 아닐까요?
- 제네릭 타입으로 채택했을때 의미상으론 관련이 있다고 보일 수 있지만 UML 상에서는 간접 연관으로 연결되는 부분은 아닐것 같아요.
해당 구조체가 프로토콜을 채택하는것이 아니고 오로지 타입이 채택하는것이기에 CalculatorItemQueue와는 연결되지 않을거라 생각합니다.
다만 Element라는 타입과는 연관이 있겠지만 현재 제공된 캠프 UML에선 제네릭 타입까지 UML로 정의하진 않았기에 패스될 수 있을거라 봅니다!
호댕은 조금 더 구체적으로 어떤 포인트에서 UML 상 간접 연관을 생각하셨을까요? 저도 궁금합니다~!🤔
3. takeOutItem 함수에 반환값을 추가하면서 테스트 코드에 경고창이 떴다. 반환값을 사용해주지 않았기 때문으로 파악했는데 이런 경우 그냥 경고창을 무시해도 되는 걸까요? 오류가 나오는지 확인하는 테스트라 반환값을 굳이 사용해줄 필요는 없다고 생각하는데 그린의 의견이 궁금합니다.
- 호댕의 생각도 맞습니다.
이 부분은 굳이 사용되지 않고 또한 테스트 코드이니 워닝이 떠도 무시해도 됩니다..!
다만 워닝이 뜨는걸 두는것보다 워닝이 안뜨게 해주는게 더 좋겠죠?😀
안그래도 이에 관해 리뷰 코멘트로 해당 부분에 몇개 달아봤습니다!
4. CalculatorItemQueue에서 appendItem, removeItem, removeAllItems 메서드가 3개가 있는데 그렇다면 SOLID의 단일 책임 원칙을 위배한 것인지 궁금합니다.
- 음 저는 SRP에 위배되지 않았다고 생각해요.
제가 그렇게 생각하는 근거는 하나의 책임을 가져야되는게 호댕도 알다시피 SRP인데 여기서 하나의 책임은 어떤걸까요?
저는 그 책임이 Items를 관리해주는거라 생각합니다.
append를 해주는것도 remove를 해주는것도 모두 Item을 관리하는 하나의 책임의 관심사로 묶여있다고 봅니다.
만약 여기에 Item을 관리해주는 관심사의 메서드가 아닌 DB에서 Item을 불러오거나 하는 메서드가 있다면 단일 책임에 위배가 되겠죠?
그럴 경우엔 Item을 관리해주는 책임과 Item DB를 소통하는 책임으로 2가지의 책임이 생긴다 봅니다.
5. 왜 빈 문자열은 Character로 바꿀 수 없는지 궁금합니다. Can't form a Character from an empty String
- 우선 이것부터 생각해보면 좋을것 같아요.
Character 타입에 빈문자를 나타낼 수 있나요?
제가 알기론 Character 타입은 하나의 문자를 나타내는것으로 0개의 문자를 할당해줄 수 없는걸로 알고 있습니다!
***
### 추가 보완되면 좋을것 같은 부분
- 전체적으로 테스트 코드가 세부적이고 다양하게 짜여져 있어서 좋습니다.
다만 양수의 계산만 있기에 음수라던지 다른 여러 케이스들을 고려해서 테스트 코드를 추가해보는건 어떨까 싶어요!
- 현재 에러 타입이 하나로 정의되어 있는데 QueueError에서도 세분화 되었으면 더 좋을것 같고 추가로 계산에 대해서도 에러가 발생하는 부분이 있을 수 있는데 이 부분도 에러를 정의하고 사용한다면 어떨까 합니다!
***
지금 이상태도 스텝2 필수 요구사항은 구현되었지만 조금 더 보완이 되면 좋을 부분들이 있어 우선 Request Changes로 해놓겠습니다..!
스텝2가 잘되어야 다음 스텝이 굉장히 수월할거라 생각해 한번 더 고민해보시는 시간으로 생각해주시면 감사하겠습니다🙏🏻
화이팅입니다!🙌

2021-11-16 01:55 UTC, yanghojoon commented
- 사실 이 질문을 정확하게 이해하지 못했습니다😭
테스트 코드에서 어떻게 사용되고 싶으신건지 조금 구체적인 설명을 붙여주실 수 있을까요?

-> 테스트 코드의 이름에 +나 . 같은 기호를 붙이면 `Consecutive declarations on a line must be separated by ';'`와 `(`, `{`를 붙이라는 에러가 발생하더라구요! 혹시 함수 명에서 저런 기호를 붙일 수 있는 방법이 있나 궁금했습니다!

- 제네릭 타입으로 채택했을때 의미상으론 관련이 있다고 보일 수 있지만 UML 상에서는 간접 연관으로 연결되는 부분은 아닐것 같아요.
해당 구조체가 프로토콜을 채택하는것이 아니고 오로지 타입이 채택하는것이기에 CalculatorItemQueue와는 연결되지 않을거라 생각합니다.
다만 Element라는 타입과는 연관이 있겠지만 현재 제공된 캠프 UML에선 제네릭 타입까지 UML로 정의하진 않았기에 패스될 수 있을거라 봅니다!
호댕은 조금 더 구체적으로 어떤 포인트에서 UML 상 간접 연관을 생각하셨을까요? 저도 궁금합니다~!🤔

-> 제네릭의 타입이 프로토콜을 준수하고 있으니 구조체 안에 생성한 프로퍼티 또한 해당 프로토콜을 준수하는 타입으로 생성될 것이라고 생각했습니다! 따라서 프로퍼티를 특정 타입으로 제한하고 있으니 영향을 주고 있는 것이고, 프로토콜이 없어진다고 해당 프로퍼티를 사용할 수 없는 것은 아니니 간접 연관으로 볼 수 있지 않을까 생각했어요!
```swift
struct CalculatorItemQueue<Element: CalculateItem> {
    var items: [Element] = [] // 이 프로퍼티들이 프로토콜을 준수하는 타입으로만 생성될 수 있도록 연관이 되어 있다고 생각했습니다!
    var reversedItems: [Element] = []
}
```

- 호댕의 생각도 맞습니다.
이 부분은 굳이 사용되지 않고 또한 테스트 코드이니 워닝이 떠도 무시해도 됩니다..!
다만 워닝이 뜨는걸 두는것보다 워닝이 안뜨게 해주는게 더 좋겠죠?😀
안그래도 이에 관해 리뷰 코멘트로 해당 부분에 몇개 달아봤습니다!

-> 감사합니다 그린! 🙏 

- 음 저는 SRP에 위배되지 않았다고 생각해요.
제가 그렇게 생각하는 근거는 하나의 책임을 가져야되는게 호댕도 알다시피 SRP인데 여기서 하나의 책임은 어떤걸까요?
저는 그 책임이 Items를 관리해주는거라 생각합니다.
append를 해주는것도 remove를 해주는것도 모두 Item을 관리하는 하나의 책임의 관심사로 묶여있다고 봅니다.
만약 여기에 Item을 관리해주는 관심사의 메서드가 아닌 DB에서 Item을 불러오거나 하는 메서드가 있다면 단일 책임에 위배가 되겠죠?
그럴 경우엔 Item을 관리해주는 책임과 Item DB를 소통하는 책임으로 2가지의 책임이 생긴다 봅니다.

-> 책임을 메서드의 기능을 통합하여 묶을 수 있다면 하나의 책임으로 묶을 수 있군요!! 하나의 책임이란 것이 하나의 기능만 한다고 오해를 했네요! 감사합니다!!

- 우선 이것부터 생각해보면 좋을것 같아요.
Character 타입에 빈문자를 나타낼 수 있나요?
제가 알기론 Character 타입은 하나의 문자를 나타내는것으로 0개의 문자를 할당해줄 수 없는걸로 알고 있습니다!

-> 아하.. 공식 문서에 버젓이 나와있었군요..🥲
The Character type represents a character made up of one or more Unicode scalar values, grouped by a Unicode boundary algorithm
왜 안바뀌는지에만 초점을 맞춰서 character의 본질을 생각하지 못했었네요ㅠㅠ 감사합니다!!

2021-11-16 02:12 UTC, yanghojoon commented on Calculator/Calculator/Model/CalculateItemProtocol.swift
> +
이 부분 확인을 못했네요ㅠㅠ 앞으로 불필요하게 줄바꿈한 것은 지우고 커밋하도록 하겠습니다! 감사해요 🙏

2021-11-16 02:15 UTC, yanghojoon commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +		DEB4E0C5273D59A70067135B /* CalculateItemProtocol.swift in Sources */ = {isa = PBXBuildFile; fileRef = DEB4E0B4273D1F630067135B /* CalculateItemProtocol.swift */; };
단순히 클래스나 구조체 같은 타입이 아니기 때문에 구분을 위해 프로토콜로 특정해서 네이밍을 했었습니다! 
하지만 말씀하신 부분에 대해 생각을 해보니 굳이 구분해서 Protocol만 네이밍에 적어줘야 하는지 이유가 없었네요..

CalculateItem으로 네이밍 수정했습니다!

2021-11-16 02:31 UTC, yanghojoon commented on Calculator/CalculatorTests/ExpressionParserTests.swift
> +//    }
수정 완료했습니다!

2021-11-16 02:46 UTC, yanghojoon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +        formula.operators.items = operatorsItems
이니셜라이저를 활용해 값을 넣어주는 방식으로 수정했습니다! 
처음엔 operatorsItems의 타입이 `[Double]`, `operatorsItems`의 타입이 `[Operator]`이고 이니셜라이저에 들어가야하는 타입은 `CaluculatorItemQueue<Double>`, `CaluculatorItemQueue<Operator>`이기 때문에 기존 방식대로 넣어줬었는데 `CaluculatorItemQueue(items: )`에 넣어주면 되는군요! 감사합니다!

2021-11-16 05:59 UTC, yanghojoon commented on Calculator/Calculator/Model/Formula.swift
> +    var operators = CalculatorItemQueue<Operator>()
구조체의 경우 
```swift 
var operands: CalculatorItemQueue<Double>
var operators: CalculatorItemQueue<Operator>
```
이렇게 놔두면 멤버와이즈 이니셜라이저가 자동으로 생성이 되는데 이니셜라이저를 꼭 만들어야 할지 궁금합니다! 

의존성 주입을 통해 외부에서 CalculatorItemQueue<Double>과 CalculatorItemQueue<Operator>를 받도록 하는 것이 CalculatorItemQueue와의 의존성을 줄일 수 있다고 판단해서 일단 위처럼 수정했습니다!!

2021-11-16 06:13 UTC, yanghojoon commented on Calculator/Calculator/Model/Formula.swift
> +            result = try firstOperator.calculate(lhs: firstOperand, rhs: nextOperand[0])
이전에는 0으로 나눌 경우 오류를 뱉어줬지만 지금은 Double.nan을 리턴해주면서 오류를 제거했었는데 여기에 try를 지우지 않았었군요! 수정완료했습니다!

2021-11-16 06:15 UTC, yanghojoon commented on Calculator/Calculator/Model/Formula.swift
> +                result = try nextOperator[0].calculate(lhs: result, rhs: nextOperand[0])
위와 동일하게 수정했습니다! 😄

2021-11-16 06:20 UTC, yanghojoon commented on Calculator/Calculator/Model/Operator.swift
> +    func calculate(lhs: Double, rhs: Double) -> Double {
0으로 나누는 상황 이외에 또다른 오류가 있을까요???

2021-11-16 06:21 UTC, yanghojoon commented on README.md
> +### 🤔 Step 2에서 고민했던 부분
감사합니다! 그린! 
이번에는 고민했던 부분이 있으면 바로바로 정리를 해놨었는데 뿌듯하네요!!

2021-11-16 06:37 UTC, yanghojoon commented on Calculator/Calculator/Extension/StringExtension.swift
> +        self.components(separatedBy: String(target))
split은 seperator가 Character이고, 반환타입은 [SubString]이었습니다! 또한 Swift 표준 라이브러리에 포함되어 있어 Foundation을 import하지 않아도 사용할 수 있었습니다. 
components의 경우 매개 변수로 String이 들어오고, 반환타입은 [String]이었습니다! components의 경우 Foundation을 import해야 사용할 수 있다고 알고 있습니다. 

일단 여기서 components를 사용했던 이유는 반환값이 String이었기 때문입니다! 물론 split의 결과값을 map을 사용해 변환할 수도 있었지만 Character 타입인 target을 String으로 바꾸는 방식이 더 간단하다고 판단해 components를 사용했습니다!

2021-11-16 07:33 UTC, yanghojoon commented on Calculator/Calculator/Model/ExpressionParser.swift
> +    }
compactMap을 통해 Double로 형변환을 하려고 하면 String이 Character로 쪼개지면서 double로 변환이 잘 되질 않네요.. 😞 
그리고 이렇게 된다면 생성한 split 메서드를 사용하지 않는다고 판단하여 일단 그대로 뒀습니다!

2021-11-16 07:51 UTC, yanghojoon commented on Calculator/Calculator.xcodeproj/project.pbxproj
>  				DEB4E09E273A5B840067135B /* QueueError.swift */,
에러 파일을 따로 빼주는 것으로 수정했습니다!! 감사해요!

2021-11-16 08:05 UTC, yanghojoon commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
> +        XCTAssertThrowsError(QueueError.emptyItem)
do catch를 쓰면 오류 처리까지 전부 해줘야 하지만 여기서 알고 싶은 것은 removeItem()을 했을 때 오류가 정확히 나오는지 알고 싶은 것이니 말씀하신대로 하는 것이 맞는 것 같아요!! 
수정완료했습니다!

2021-11-16 08:05 UTC, yanghojoon commented on Calculator/CalculatorTests/FormulaTests.swift
> +        XCTAssertThrowsError(QueueError.emptyItem)
위와 같은 방식으로 수정했습니다!

2021-11-16 08:12 UTC, yanghojoon commented on Calculator/CalculatorTests/OperatorTests.swift
> +
컨벤션에 맞춰 수정했습니다! 추가적으로 `XCTAssertEqual(,)`의 경우 다른 파일에서 전부 줄바꿈을 하고 적어줘서 이 부분도 수정했습니다!

2021-11-16 08:13 UTC, yanghojoon commented on Calculator/CalculatorTests/OperatorTests.swift
> +
수정 완료했습니다 🙇

2021-11-16 08:41 UTC, yanghojoon commented on Calculator/CalculatorTests/FormulaTests.swift
> +    var sut: Formula!
Formula는 분명 생성된 타입이나 tearDownWithError()에서 sut에 nil값을 할당해주기 위해 옵셔널로 설정한다고 알고 있습니다! 
반드시 있는 타입인데도 force-unwrapping은 사용을 지양하는 것이 맞을까요?

물론 Formula?로 옵셔널로 지정해주고 sut에서도 전부 sut?으로 해주면 정상 작동하는 것을 확인했는데 이렇게 한다면 각각 인스턴스를 생성해줘서 테스트를 진행하는 것이 낫지 않나 생각이 듭니다 :cry:

2021-11-16 08:50 UTC, yanghojoon commented on Calculator/CalculatorTests/OperatorTests.swift
> +    var multiply: Operator!
`Operator.calculate(.add)(lhs: 2, rhs: 4)` 이런 식으로 바로 연산을 해서 값을 비교할 수 있도록 수정했습니다!

2021-11-16 09:01 UTC, yanghojoon commented on Calculator/CalculatorTests/CalculatorItemQueueTests.swift
>          var queue = CalculatorItemQueue<Double>()
doubleSut과 operatorSut을 생성하여 중복을 줄여봤습니다!

2021-11-16 09:34 UTC, GREENOVER commented on Calculator/Calculator/Model/Operator.swift
> +    func calculate(lhs: Double, rhs: Double) -> Double {
만약 알 수 없는 에러가 날 수도 있을거에 대비해 
기타예외 케이스도 하나 만들어보면 좋을것 같아요!
지금 딱 다른 오류가 생각나는건 아니지만
완벽하게 오류 처리를 다 해볼 수 없는 상황이 많기에
"알 수 없는 에러" 라는 케이스도 있다면 나중에 우선적으로 사용될것 같아서요..!
이건 의견이고 저도 다른 에러가 나는 상황이 없는지 궁금해서 여쭤봤습니다~🙋🏻

2021-11-16 09:36 UTC, GREENOVER commented on Calculator/CalculatorTests/FormulaTests.swift
> +    var sut: Formula!
여기서 중요한건 이런것들이 정말 사소한 습관이 되곤 합니다 ㅠ
캠프에서 부딪힐 수 있을때 좋은 습관을 들이는게 좋을거라고 생각해서 테스트 코드여서 문제가 되진 않지만 습관에 대해 말씀드려봤습니다..!

2021-11-16 09:39 UTC, GREENOVER commented
@yanghojoon 
아하 메서드명에 기호를 말씀하셨던거군요..!
알아보신 방법외엔 사용할 수 없다고 저는 알고 있습니다.
그런데 돌이켜 생각해보면 그런 키워드나 예약어, 기호를 사용해서 메서드명을 표현하는것은 네이밍 가이드에 맞지 않다고 생각해요.
최대한 문자로 풀어보는게 어떨까요?
우선 재코멘트를 통해 계속 확인은 해보고 있습니다..!
만약 리뷰에 대해 코멘트 및 수정이 끝나신다면 요 PR의 우측 상단
![스크린샷 2021-11-16 오후 6 39 17](https://user-images.githubusercontent.com/72292617/141960544-b45f7f84-93c4-4d0d-be0d-47cfb7514e07.png)
저기의 리프레쉬 버튼을 눌러 PR 재리뷰 요청을 주시면 확인 후 머지하겠습니다🙌

2021-11-16 10:11 UTC, yanghojoon commented on Calculator/Calculator/Model/Formula.swift
> +            }
중복되는 코드를 최대한 줄여봤습니다!!

2021-11-16 11:11 UTC, yanghojoon commented on Calculator/Calculator/Model/QueueError.swift
> +    case emptyItem
에러케이스를 세분화해서 연산자가 비었을 때와 피연산자가 비였을 때를 나눠서 에러 처리를 할 수 있도록 수정했습니다!

다만 이렇게 처리를 하니 CalculatorItemQueue에서 따로 Queue가 비었을 때 에러를 던지는 것이 의미가 있나 궁금합니다!

2021-11-16 11:30 UTC, GREENOVER commented on Calculator/Calculator/Model/QueueError.swift
> +    case emptyItem
물론 따로 큐가 비었을때 계산기에서 체크하는 부분이 없을 수 있습니다.
호댕도 그렇게 생각하셨기에 하나의 에러 케이스로 만드셨을거구요..!
다만 모든 에러의 경우를 미리 생각해보고 적용한다하더라도 UI와 연동하거나 추후 어떤 기획이 바뀔지도 모르기에 항상 확장성 있게 하는것이 더 좋을것 같다고 생각했습니다🧐
그렇기에 현재 설계단계에서 최대한 확장성을 가져가고 이후 UI와 연동할때 정말 사용되지 않거나 필요없다면 그때 제거해도 괜찮지 않을까 하는 의견이 있습니다.
실제적으로 에러 케이스가 거의 없는 플젝이여서 지금은 간단히 생각할 수 있지만 어느 플젝들은 다양한 에러를 미리 생각할 수 없을 수 있기에 최대한 세분화되게 만들면 어떨까 합니다!

2021-11-16 12:32 UTC, yanghojoon commented on Calculator/Calculator.xcodeproj/project.pbxproj
>  				C713D9422570E5EB001C3AFC /* AppDelegate.swift in Sources */,
사실 JuiceMaker 프로젝트에서 AppDelegate와 SceneDelegate가 controller에 위치해있어서 별 생각없이 Controller 그룹에 넣었었네요.. 😥 
찾아보니 AppDelegate는 iOS13 이후로 데이터 구조를 초기화하고, 알림에 대응하며, 앱 자체를 타겟하는 이벤트에 대응한다고 이해했습니다. 
SceneDelegate는 scene에서 일어나는 lifecycle event에 대해 다루고 있구요! 즉 화면에 뭘 보여줘야 할지 관리하는 역할이라 이해했습니다. 

아직 AppDelegate와 SceneDelegate를 직접 사용한 적이 한 번도 없어 정확하진 않지만 아예 따로 분리하는 것이 좋을 것 같다는 생각이 듭니다. 모델과 뷰를 연결해주는 역할이라기 보다 앱을 총괄하는 역할이라 분리하는 것이 좋을 것 같은데 네이밍에 대해선 잘 모르겠네요...

2021-11-16 12:35 UTC, yanghojoon commented on Calculator/CalculatorTests/FormulaTests.swift
> +    var sut: Formula!
아하 감사합니다!!

2021-11-16 12:48 UTC, GREENOVER approved these changes
고생하셨습니다 호댕!
저의 사소한 궁금증과 답변들 3개 정도 리뷰로 남겨두었습니다..!
이번 스텝은 여기서 마무리하고 다음 스텝으로 가시죠~!
만약 보완이나 수정되어야 할 부분이 있다면 스텝3에서 같이 해보시면 될것 같아요ㅎㅎ
스텝 3도 화이팅입니다🙌

2021-11-16 12:48 UTC, GREENOVER commented on Calculator/Calculator/Model/Formula.swift
> +        var `operator` = operators.items
이렇게 가져가시는게 가독성이 더 나아보이는건가요?🧐
궁금해서 여쭤봅니다~!

2021-11-16 12:48 UTC, GREENOVER commented on Calculator/CalculatorTests/FormulaTests.swift
> +    func test_음수가_섞인_다양한_연산자와_숫자가_있을_경우_계산이_잘_되는지() {
더 다양한 TC가 되었네요👍

2021-11-16 12:48 UTC, GREENOVER commented on Calculator/Calculator.xcodeproj/project.pbxproj
> +				C713D9432570E5EB001C3AFC /* SceneDelegate.swift */,
좋습니다!
저는 꼭 그룹화를 지어줄 필요는 없다고 생각합니다~!

2021-11-16 12:48 UTC, merged

2021-11-16 12:55 UTC, yanghojoon commented on Calculator/Calculator/Model/Formula.swift
> +        var `operator` = operators.items
첫 번째 연산자로 나누지 않고 연산자로 네이밍을 통합하다보니 저렇게 표현했었는데, 백틱을 사용하는 것보단 연산자 배열인 만큼 operatorItems로 네이밍을 하는 것이 가독성에도 더 좋을 것 같습니다!