계산기 [STEP 2] singularis7(신나)
yagom-academy/ios-calculator-app pull request #99
Opened 2021-11-15 11:12 UTC by smart8612

안녕하세요 🍎 @AppleCEO 도미닉! 

계산기 STEP2 PR 보내드립니다! 🤩
언제나 정성스럽게 피드백 해주셔서 감사드립니다~~~

## UML

![step2 Diagram](https://user-images.githubusercontent.com/25794814/141769960-0df5083a-2760-4a3d-9afe-c05527dba6d5.jpg)

## 고민된 부분

- **UML 차트에 구현된 Type과 Method에 대하여 설계자의 의도를 파악하는 고민**
    
    UML 차트에 있는 타입의 역할을 다음과 같이 해석하여 구현했습니다.
    
    `Operator` : 수식에서 연산자에 해당되는 부분을 정의하였습니다. Operator 의 인스턴스를 통해 calculate 메서드를 호출하여 연산할 수 있습니다.
    
    `Double`: CalculateItem 프로토콜을 채택하도록 기존 Double Type 을 확장합니다. CalculatorItemQueue에 Double 형 숫자를 담을 수 있도록 설정되었습니다.
    
    `Formula` : 하나의 수식을 추상화한 타입입니다. 숫자에 해당하는 부분은 operands, 연산자에 해당하는 부분은 operators 큐에 담깁니다. 연산 결과는 result 메서드를 통해 확인할 수 있습니다.
    
    `ExpressionParser`: String 타입의 수식을 파싱하여 숫자와 연산자를 구분하는 Formula 형태로 만들어줍니다. 내부적으로 componentsByOperators 를 통해 수식을 파싱합니다.
    
- **CalculateItem Type과 CalculatorItemQueue 관계에 있어서 [Step 1] 과의 요구 사항 충돌**
    
    [Step 1] 요구사항 중에서 "`CalculatorItemQueue`에서 다루는 요소는 `CalculateItem` 프로토콜을 준수합니다." 가 **CalculateItem** Type과 **CalculatorItemQueue** 사이에 의존성을 갖도록 전제하고 있다고 생각하였습니다. 
    
    [Step 2] 요구 사항에서 UML 차트 상에는 두 타입 간에 어떠한 상관 관계도 갖지 않는 것 처럼 보였지만 CaculatorItemQueue 를 필요한 데로 커스텀하여 사용해도 된다는 크루의 글을 기반으로 기존처럼 의존성을 갖도록 구현을 유지시켰습니다. [[디스코드 링크]](https://discord.com/channels/767712486614368277/892360868430503997/908248831496425482)
    
- **Double 자료형을 통해 10진수를 계산했을 때 발생되는 부동소수점 연산 오류**
    
    Double 자료형을 통해 10진수를 연산할 때 부동소수점 오차에 따른 부정확한 연산이 이뤄졌습니다.
    
    이 문제를 해결하기 위해 10진수체계로 부동소수점수를 연산해주는 Decimal 타입을 활용해보았습니다.
    
    > **Decimal**
    A structure representing a base-10 number.
    - [Apple Document](https://developer.apple.com/documentation/foundation/decimal)
    > 
    
    Decimal을 통해 연산한 뒤에 Double 타입으로 변환하는 과정에서도 근사치를 통한 변환이 이뤄지기 때문에 여전히 연산 오류의 발생 가능성이 존재합니다.
    
    ```swift
    extension Decimal {
        var doubleValue: Double {
            NSDecimalNumber(decimal: self).doubleValue
        }
    }
    ```
    
    이 문제를 해결하기 위해 String으로 먼저 변환시킨 다음 Double 형으로 변환해주는 방법을 사용해보려했으나 해당 format 함수는 iOS 15 이상을 최소 지원 타깃으로 설정하고 있기 때문에 사용하지 못했습니다.
    
    ```swift
    @available(macOS 12.0, iOS 15.0, tvOS 15.0, watchOS 8.0, *)
    extension Decimal {
       ... 
       /// Creates a `FormatOutput` instance from `value`.
       public func format(_ value: Decimal) -> String
       ...
    }
    ```
    
- **0으로 나눴을 때 Double.nan이 아닌 Error 방식을 선택한 고민 과정**
    
    Swift의 Double 타입에는 숫자가 아님을 나타내는 `nan` 프로퍼티가 존재합니다. 
    
    > A NaN compares not equal, not greater than, and not less than every value, including itself. Passing a NaN to an operation generally results in NaN.
    > 
    
    만약 `Double` 타입의 `nan` 프로퍼티를 통해 0으로 나누는 경우를 처리한다면 CalculateItem 를 채택하는 또 다른 자료형에 대해서는 Double의 `nan` 프로퍼티가 없기 때문에 타입별로 중복된 예외 처리가 구현되야한다고 생각하였습니다.
    
    Error 예외처리를 사용하면 View에서 0으로 나눠졌을 때에 대한 예외 동작 사항만 구현해두고 CalculateItem 입장에서는 연산되는 순간 0으로 나눈 상황이 발생한 경우 사전에 지정된 오류만 던지면 계산기 프로젝트 요구 사항에 적힌 NAN 처리를 쉽게 구현할 수 있을거라 생각합니다.
    

## 조언을 얻고 싶은 부분

- Double 형을 10진수 체계로 연산하여 오류를 줄이고자 고민했지만 위와 같은 사유로 여전히 연산 오류의 가능성이 남아있는 상황입니다. 이 문제를 해결하기 위한 다른 접근 방법이 있을까요?
- 예외 처리가 포함된 코드를 테스트할 때 XCTAssertThrowError 를 사용하면 에러를 던지는 모든 코드를 테스트 통과로 구분하는 모습을 볼 수 있었습니다.
    
    ```swift
    func test_Double형_80와_Double형_10을_divide_operator로_연산하면_Double형_8점0가_반환되는가() {
            // given
            let leftOperand = 80.0
            let rightOperand = 10.0
    
            // when
            do {
                sutDouble = try sutDivideOperator.calculate(lhs: leftOperand, rhs: rightOperand)
            } catch {
                XCTAssertTrue(false)
            }
            
            // then
            XCTAssertEqual(sutDouble, 8.0)
        }
    ```
    
    코드가 정상적으로 실행될 때 결과를 갖고 테스트 케이스를 검증하되 에러가 발생하면 false를 반환하는 코드가 내부적으로 XCTAssert함수를 여러번 호출하고 있다는 점에서 문제가 있다고 생각하여 좀더 개선시켜보고 싶은 고민을 하고 있습니다!

- 이번 프로젝트에서 String 수식을 " " 단위로 구분하여 파싱하는 것을 전제로 구현하였습니다. View 에서 띄어쓰기로 연산자와 피연산자를 구분하여 모델에게 제공한다는 전제를 깔고 구현했는데 같은 문제를 좀 더 쉽게 해결할 수 있다고 생각하여 선택하였습니다. 다만 ViewController 에서 모델에게 수식 String을 약간 수정해서 model 에게 제공해야 한다는 단점이 있기는 한데,, 이 접근 방법이 MVC 패턴을 훼손하고 있는 것은 아닐지 도미닉의 의견을 여쭤보고 싶어요~
    ```Swift
     func test_2_더하기_3_빼기_4_더하기_5의_parse_result로_6을_반환하는가() {
        // given
        let form = "2 + 3 − 4 + 5"
        
        // when
        do {
            sutResult = try ExpressionParser.parse(from: form).result()
        } catch {
            XCTAssertTrue(false)
        }
        
        // then
        XCTAssertEqual(sutResult, 6.0)
    }
    ```

    이번에는 가독성을 높혀보고자 노력해보았어요! 이전처럼 제가 주로 고민했던 내용을 정리하기는 했는데 반대로 말하자면 그 외의 것들은 생각하지 못하였을 수 있습니다! 많이 지적해주시면 매우 감사드리겠습니다~~~

2021-11-16 02:49 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
신나 고생하셨습니다~
아래 몇개 코멘트보고 개선해보시면 좋겠습니다~

Double 형을 10진수 체계로 연산하여 오류를 줄이고자 고민했지만 위와 같은 사유로 여전히 연산 오류의 가능성이 남아있는 상황입니다. 이 문제를 해결하기 위한 다른 접근 방법이 있을까요?
- 반올림이나 길이를 체크할 수도 있을 것 같아요.

이번 프로젝트에서 String 수식을 " " 단위로 구분하여 파싱하는 것을 전제로 구현하였습니다. View 에서 띄어쓰기로 연산자와 피연산자를 구분하여 모델에게 제공한다는 전제를 깔고 구현했는데 같은 문제를 좀 더 쉽게 해결할 수 있다고 생각하여 선택하였습니다. 다만 ViewController 에서 모델에게 수식 String을 약간 수정해서 model 에게 제공해야 한다는 단점이 있기는 한데,, 이 접근 방법이 MVC 패턴을 훼손하고 있는 것은 아닐지 도미닉의 의견을 여쭤보고 싶어요~
- 뷰컨트롤러에서 최소한의 동작만 하는 것이 좋긴 합니다. 모델에서 String을 수정 안 하고 모델에게 제공해서 모델에서 가공을 하는 것은 어떨까요?

2021-11-16 07:48 UTC, smart8612 commented on Calculator/Calculator/Model/CalculateParser/CalculatorError.swift
> +    case divideByZero
고맙습니다 🥳
unknownOperator 예외 케이스의 경우 현재 프로젝트에서 하이픈 마이너스와 음수 부호 마이너스를 혼용하고 있기 때문에 발생할 수 있는 문제점의 원인을 빠르게 파악할 수 있도록 추가 정의 해주었습니다!
ViewController 에서 모델을 사용할 때 발생할 수 있는 예외 케이스가 있다면 위와 같이 이유와 목적을 갖고 예외 케이스를 추가해보고자합니다!

2021-11-16 07:58 UTC, smart8612 commented on Calculator/Calculator/Model/CalculateParser/ExpressionParser.swift
> +            }
이번 코멘트를 계기로 클로저 기본에 대하여 복습해보는 시간을 가져보았습니다. 🤔
프로젝트 Expression Parser 구현부를 고차함수를 통해 구현하는 코드로 변환하면서
클로저 원형을 사용하는 방향으로 코드를 재구현하였습니다! 🤗

---

축약형 표현을 클로저의 정석 표현으로 바꾸면 다음과 같습니다
```Swift
input.compactMap({ (each: String) -> Double in 
    return Double(each) 
})
```

함수의 마지막 인수가 클로저라면 함수 외부에 정의할 수 있습니다.
``` Swift
input.compactMap { (each: String) -> Double in 
    return Double(each) 
}
```

input의 type을 통해 compactMap의 클로저 인자 타입이 정해져있으며 컴파일러가 매개변수의 타입을 유추할 수 있기 때문에 클로저 인자 type 표시를 생략할 수 있습니다.
반환값의 타입을 Int 형으로 유추할 수 있기 때문에 생략할 수 있습니다.
```Swift
input.compactMap { (each) in 
    return Double(each) 
}
```

약칭 전달인자를 사용하여 클로저의 인자 순서대로 $0, $1 ... 형태로 표현할 수 있습니다.
```Swift
input.compactMap { 
    return Double($0)
}
```

클로저가 반환하는 값이 있을때 마지막 줄 결과값은 암묵적으로 반환값으로 취급하며 return 을 생략할 수 있습니다. 물론 한줄로도 표현이 가능합니다.
```Swift
input.compactMap { Double($0) }
```

2021-11-16 08:00 UTC, smart8612 commented on Calculator/Calculator/Model/CalculateParser/ExpressionParser.swift
> +            }
```Swift
let parsedInput = try componentsByOperators(from: input)
        
parsedInput
    .compactMap({ (each: String) -> Double? in
        return Double(each)
    })
    .forEach({ (each: Double) -> Void in
        operands.enqueue(each)
    })
```

2021-11-16 08:02 UTC, smart8612 commented on Calculator/Calculator/Model/CalculateParser/ExpressionParser.swift
> +            }
* 프로젝트에 반영된 클로저 기본 구현입니다~! 🧐

```Swift
let parsedInput = try componentsByOperators(from: input)
parsedInput
    .filter({ (each: String) -> Bool in
        return Double(each) == nil
    })
    .compactMap({ (each: String) -> Operator? in
        return Operator(rawValue: Character(each))
    })
    .forEach({ (each: Operator) -> Void in
        operators.enqueue(each)
    })
```

2021-11-16 08:07 UTC, smart8612 commented on Calculator/Calculator/Model/CalculateParser/Formula.swift
> +              let operatorInstance = operators.dequeue()
처음엔 코드를 길게 작성할 것인가? 개행을 통해 길이를 줄일 것인가만 고민하여 위 코드 처럼 작성하게 되었습니다.
도미닉이 주신 의견처럼 while 문의 condition 에 해당되는 코드와 while 문 내부 statement가 혼동될 수 있다고 생각해서
condition을 같은 줄에 작성하는 방향으로 코드를 수정하였습니다.

```Swift
func result() throws -> Double {
        guard var result = operands.dequeue() else { return 0.0 }
        
        while let number = operands.dequeue(), let operatorInstance = operators.dequeue() {
            result = try operatorInstance.calculate(lhs: result, rhs: number)
        }
        
        return result
}
```

2021-11-16 08:08 UTC, smart8612 commented on Calculator/CalculatorTests/CalculateItemTests/OperatorTests.swift
> +    func test_Double형_0점2와_Double형_0점1을_add_operator로_연산하면_Double형_0점3이_반환되는가() {
[Step 1]에서 주신 테스트 명 피드백 예시를 반영하는 방향으로 코드를 개선해나가고 있습니다!
고맙습니다~~ 🤩

2021-11-16 08:14 UTC, smart8612 commented on Calculator/CalculatorTests/CalculateItemTests/OperatorTests.swift
> +    func test_Double형_80와_Double형_0점0을_divide_operator로_연산하면_notANumber오류가_반환되는가() {
도미닉의 의견과 동일하게 "오류가 반환되는가" 라는 표현은 참 거짓을 판명하기 모호한 부분이 있다고 생각합니다!
따라서 다음과 같이 "반환되어야한다" 방식으로 함수명을 리팩토링하였습니다!

현재 프로젝트에는 오류를 반환하는지 검증하는 테스트 케이스가 두개 작성되어있습니다.

우선 Operator 타입을 테스트 하는 케이스 명을 다음과 같이 수정하였습니다.
*  func test_Double형_80와_Double형_0점0을_divide_operator로_연산하면_divideByZero_오류가_반환되어야한다() 

다음으로 ExpressionParser 타입을 테스트 하는 케이스 명을 다음과 같이 수정하였습니다.
* func test_잘못된_연산자를_포함하여_1_더하기_2_빼기_3_곱하기_2_빼기_3_나누기_음수6_의_result로_unknownOperator_오류를_반환해야한다() {

2021-11-16 08:26 UTC, smart8612 commented on Calculator/CalculatorTests/CalculateParserTests/CalculatorItemQueueTests/CalculatorItemQueueCharacterTests.swift
> +    var sutQueue: CalculatorItemQueue<Character>!
* 코드 작성상의 목적으로는 일반적인 방식으로 옵셔널 체이닝을 통해 프로퍼티에 접근할 때 반복되는 `?` 옵셔널 확인 절차를 줄이기 위함입니다.
* 매번 테스트 케이스가 실행될 때는 `setUpWithError` 와 `tearDownWithError` 를 통하여 옵셔널 값이 명확히 설정되어있다고 판단을 할 수 있어서 sut 접근시 옵셔널을 확인하는 절차가 불필요하다고 생각하였습니다.

> Sometimes it’s clear from a program’s structure that an optional will always have a value, after that value is first set. In these cases, it’s useful to remove the need to check and unwrap the optional’s value every time it’s accessed ... These kinds of optionals are defined as implicitly unwrapped optionals. - [implicitly unwrapped optional](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID334)

2021-11-16 08:31 UTC, smart8612 commented
[코드 주요 개선 사항]

* Expression Parser 의 구현을 띄어쓰기로 구분되지 않는 수식으로 처리할 수 있도록 구조를 개선시켰습니다
* 상수와 고차 함수만을 활용하여 구현해보았습니다

2021-11-17 01:07 UTC, merged

2021-11-17 01:07 UTC, AppleCEO commented
요청해주셔서 머지 드립니다. 고생하셨습니다~